### ISSUE TITLE
freerdp-any: this client could not display bitmap correctly

### ISSUE THREAD

**Issue by silenceli** [neutrinolabs/xrdp#10]
Hi,jsorg71

   when I come to "Login to xrdp" , I choose freerdp-any  "module". then,I get into the windows. everything seems ok except the bitmap. when I open a picture, the picture is displayed as a number of square blocks,some blocks display correctly,but others seems to be upside down ,that  is to say , For a bitmap block, the graphics shown in the above should be shown in the below ,the bitmap block is top and bottom reversed.I think  may be the coordinates of the bitmap error . I hope you can solve the problem. thank you!
ps:in xrdp.ini freerdp-any "module" set as:
[xrdp6]
name=freerdp-any
lib=libxrdpfreerdp1.so
ip=ask
port=ask3389
username=ask
password=ask

but if i choose rdp-any "module" is setted as
 [xrdp5]
name=rdp-any
lib=librdp.so
ip=ask
port=ask3389
in xrdp.ini 
every bitmap is display correctly
the version I use:
xrdp version:FreeRDP-xrdp-b124612
FreeRDP version:FreeRDP-FreeRDP-3996620
Client: mstsc

ScreenShot:
<img src=http://goto.ncepu.edu.cn/image/Screenshot.png />

**Comment by metalefty** [comment]
FreeRDP module was removed long ago. Closing.
