### ISSUE TITLE
Document a list of known working configurations, known not-working configurations

### ISSUE THREAD

**Issue by joseortiz3** [neutrinolabs/xrdp#1004]
Hello,

I think of greatest use for people interested in using xrdp would be to provide some information in an easy-to-access location (like the main readme, the front page, etc) about configurations that are known to work well, or are known not to work well. This would save thousands of people tens of thousands of hours of troubleshooting (leading to most people just giving up).

Otherwise, the strategy I or another potential user will take is to just try random configurations and random how-to-guides trying to get things to work, which in my case has resulted in dozens of wasted hours. The problem with this is there are no how-to-guides that compare which configurations are _the most likely to work_.

As an example of what not to do: I have tried Linux Mint 18.2, Ubuntu 16.04 LTS, and Ubuntu 17.10, trying to find a working, reliable configuration that allows Windows Remote Desktop to properly and usefully access linux through xrdp, especially in conjunction with modern GPU drivers from Nvidia. I have not fully succeeded - each time I try, there is usually a problem of xrdp supporting the desktop version (unity is not supported I guess, cinnamon crashes to fallback mode, mate works but doesn't support GPU and causes problems, the new desktop on ubuntu 17.10 simply disconnects the session when using Nvidia driver).

If the list of working / not-working configurations existed, I would have simply used whatever configuration was most-likely to work. I think such a list would indicate that xrdp does not, for instance, support default Ubuntu 16.04's desktop, unity. Such a list might indicate it works with some other desktops. Or to try a different distribution that it works with by default.

I hope I have made my case clear that the potential benefits of providing some suggestions of working configurations (or just _more-likely-to-work_ configurations) far outweighs the pain of the ten minutes it would take someone to write down what they know about xrdp compatibility, and include it in the readme, or somewhere visible.

On the other hand, I am still wondering what configurations are more reliable, so if my suggestion is not taken, I would still greatly appreciate some advice. Thanks for xrdp, and hope to get it working reliably soon.

**Comment by metalefty** [comment]
Dup of #997. Both issues have almost same goal.

**Comment by joseortiz3** [comment]
I saw #997, but I think the issue, possible solutions, and the importance are more-precisely stated here. That thread seems to go off on a tangent, and makes it less likely the underlying problem (users have no clue where they should start, or what to avoid) will get solved.

**Comment by metalefty** [comment]
Of course I don't mean I only solve either one of these issues. I will keep your requests in mind when I work on #997.
