### ISSUE TITLE
Sesman Passwd file reused when logging into multiple machines with same user

### ISSUE THREAD

**Issue by danasmoot** [neutrinolabs/xrdp#1006]
My network has multiple machines that use the RedHat IDM and LDAP server to have the same users and home drives available on any machine we log into.  When I connect to one machine via XRDP it creates the passwd file at ~/.vnc/sesman_$USER_passwd:10 and everything works.  If I leave my session logged in there and close the Remote Desktop window, and connect to another machine that uses the same home drive, the Sesman passwd file is then overwritten with a new "password" by XRDP running on that machine, and it logs in correctly.

The problem arises when I try to reconnect to the first machine, the VNC authentication fails when "checking" the ~/.vnc/sesman_$USER_passwd:10 file that was overwritten by the second machine.  The only way I can get around this is to backup the file for each machine when I first start the session, and then when I want to reconnect, I make sure that the file is the correct one.

To fix this, I suggest modifying the env_set_user() function in env.c to use the hostname in creating the filename for the passwd file.  This way no mater which machine I log into, it gets its own file.

Alternatively, is there a way using the AuthFilePath config option to set a directory that uses the username and system hostname to create a unique file?

**Comment by jsorg71** [comment]
Never thought about that situation.  We can change to add hostname to file.
You should not see this with the Xorg backend, this is just a Xvnc problem.
AuthFilePath can not work without being changed either.

**Comment by danasmoot** [comment]
Ok, thanks.  Guess for now I will have to keep with my workaround of creating backups of that file.

**Comment by jsorg71** [comment]
created #1007 for this

**Comment by metalefty** [comment]
Fixed by #1007, #1076.
