### ISSUE TITLE
startwm.sh uses the wrong shell

### ISSUE THREAD

**Issue by bnevis-i** [neutrinolabs/xrdp#1009]
startwm.sh run as /bin/sh but then proceeds to source ~/.bash_profile.

If .bash_profile contains bash-specific syntax (which it is allowed to do, because it is bash_profile), it causes an error that will abort starting the window manager.

**Comment by metalefty** [comment]
Good catch, thanks for reporting!

**Comment by Thaodan** [comment]
Is bash support really needed here? I see no use for bash here.

**Comment by itamarjp** [comment]
on most linux distros sh is a symlink to bash -> 

$ ls -lia /bin/sh
1842414 lrwxrwxrwx 1 root root 4 Feb 13 12:08 /bin/sh -> bash

**Comment by metalefty** [comment]
@Thaodan As the reporter says, `startwm.sh` includes `.bash_profile` and it can contain bash-specific syntax, it will cause an error.  If you don't use bash, of course you can don't need use bash in `startwm.sh`. Actually whatever shell is possible. You can rewrite `startwm.sh` with zsh, tcsh, dash, ksh or any but our built-in default is bash.

```
#!/bin/sh
startxfce4
```

@itamarjp And what? The change is for the distro that `/bin/sh` is not bash. AFAIK, `/bin/sh` of Debian/Ubuntu is not bash but dash. I don't think they're out of  *most*.

**Comment by Thaodan** [comment]
Yes I know but why should this be sourced? This file is explicit for starting a bash login shell not for starting a wm.

**Comment by metalefty** [comment]
Actually, distro has each own startwm.sh and uses it. Not our built-in sample. This means our startwm.sh is not best for each distro.  There's some room for improvement. Sourcing `bash_*` might be removed in the future but I decided to use bash explicitly as a workaround at this time.

**Comment by AeliusSaionji** [comment]
I might be wrong, but I think we need to reexamine this issue.

The script uses bash to source ~/.profile as bash: but this is not a bash specific file. Mine is actually just sh.
Similarly, my xinitrc is sh, not bash. If I understand correctly, sourcing these files inside bash will not execute them with their defined `#!shebang`.

What do you think?

**Comment by Thaodan** [comment]
Yes the shebang is only used by the OS and 
not bash.
Both files have no shebang.
I don't see the reason behind sourcing 
bash_profile.

**Comment by bnevis-i** [comment]
In a traditional Unix environment, login shells will read /etc/profile and ~/.profile, (Bourne, similar set for Bash shell) and it is this place where environment variables are properly set.  That said, it would be more portable to pass the `-l` switch in the shebang and let the shell source its own files.

```
#!/bin/sh -l
```

Also for @itamarjp's comment above, many Unix utilities will look at $0 and behave differently depending on the name of the command that they are invoked as.  In fact, shell does this and starts a login shell if invoked with a leading hyphen, as in "-/bin/sh".  The fact that symlinks point to the same executable doesn't mean that they behave the same at runtime.

**Comment by AeliusSaionji** [comment]
> Both files have no shebang

Clarification: I use dash as my login shell, and dash also utilizes .profile like bash.
For reasons related to not having a DE, my xinitrc is executable and thus I put the shebang in there.
