### ISSUE TITLE
gnome-settings-daemon killed by SIGFPE Centos 7

### ISSUE THREAD

**Issue by Alhel** [neutrinolabs/xrdp#1010]
[https://bugs.centos.org/view.php?id=14054]
xrdp-sesman.log 
```
[20180126-07:54:39] [INFO ] A connection received from 127.0.0.1 port 48746
[20180126-07:54:41] [INFO ] ++ created session (access granted): username root,
[20180126-07:54:41] [INFO ] starting Xvnc session...
[20180126-07:54:41] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5911)
[20180126-07:54:41] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6011)
[20180126-07:54:41] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6211)
[20180126-07:54:41] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20180126-07:54:41] [INFO ] calling auth_start_session from pid 16586
[20180126-07:54:41] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
[20180126-07:54:41] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20180126-07:54:41] [INFO ] Xvnc :11 -auth .Xauthority -geometry 1684x993 -depth
[20180126-07:54:41] [CORE ] waiting for window manager (pid 16588) to exit
[20180126-07:58:09] [INFO ] A connection received from 127.0.0.1 port 48798
[20180126-07:58:09] [INFO ] ++ created session (access granted): username root,
[20180126-07:58:09] [INFO ] starting Xorg session...
[20180126-07:58:09] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5912)
[20180126-07:58:09] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6012)
[20180126-07:58:09] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6212)
[20180126-07:58:09] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20180126-07:58:09] [INFO ] calling auth_start_session from pid 17695
[20180126-07:58:09] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
[20180126-07:58:09] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20180126-07:58:09] [INFO ] setpriv --no-new-privs Xorg :12 -auth .Xauthority -c
[20180126-07:58:10] [CORE ] waiting for window manager (pid 17697) to exit
[20180126-07:58:18] [CORE ] window manager (pid 17697) did exit, cleaning up ses
[20180126-07:58:18] [INFO ] calling auth_stop_session and auth_end from pid 1769
[20180126-07:58:18] [DEBUG] cleanup_sockets:
[20180126-07:58:18] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdpapi_12
[20180126-07:58:18] [DEBUG] cleanup_sockets: failed to delete /tmp/.xrdp/xrdpapi
[20180126-07:58:18] [INFO ] ++ terminated session:  username root, display :12.0
```

xrdp.log
```
[20180126-07:54:39] [INFO ] A connection received from 127.0.0.1 port 48746
[20180126-07:54:41] [INFO ] ++ created session (access granted): username root,
[20180126-07:54:41] [INFO ] starting Xvnc session...
[20180126-07:54:41] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5911)
[20180126-07:54:41] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6011)
[20180126-07:54:41] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6211)
[20180126-07:54:41] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20180126-07:54:41] [INFO ] calling auth_start_session from pid 16586
[20180126-07:54:41] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
[20180126-07:54:41] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20180126-07:54:41] [INFO ] Xvnc :11 -auth .Xauthority -geometry 1684x993 -depth
[20180126-07:54:41] [CORE ] waiting for window manager (pid 16588) to exit
[20180126-07:58:09] [INFO ] A connection received from 127.0.0.1 port 48798
[20180126-07:58:09] [INFO ] ++ created session (access granted): username root,
[20180126-07:58:09] [INFO ] starting Xorg session...
[20180126-07:58:09] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5912)
[20180126-07:58:09] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6012)
[20180126-07:58:09] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6212)
[20180126-07:58:09] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20180126-07:58:09] [INFO ] calling auth_start_session from pid 17695
[20180126-07:58:09] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
[20180126-07:58:09] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20180126-07:58:09] [INFO ] setpriv --no-new-privs Xorg :12 -auth .Xauthority -c
[20180126-07:58:10] [CORE ] waiting for window manager (pid 17697) to exit
[20180126-07:58:18] [CORE ] window manager (pid 17697) did exit, cleaning up ses
[20180126-07:58:18] [INFO ] calling auth_stop_session and auth_end from pid 1769
[20180126-07:58:18] [DEBUG] cleanup_sockets:
[20180126-07:58:18] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdpapi_12
[20180126-07:58:18] [DEBUG] cleanup_sockets: failed to delete /tmp/.xrdp/xrdpapi
[20180126-07:58:18] [INFO ] ++ terminated session:  username root, display :12.0
```

**Comment by moobyfr** [comment]
The usefull log here is ~/.xorgxrdp.12.log

**Comment by Alhel** [comment]
`
[ 75016.900] 
X.Org X Server 1.19.3
Release Date: 2017-03-15
[ 75016.900] X Protocol Version 11, Revision 0
[ 75016.900] Build Operating System:  3.10.0-514.16.1.el7.x86_64 
[ 75016.900] Current Operating System: Linux ip-10-172-1-101.ec2.internal 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64
[ 75016.900] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-3.10.0-693.11.6.el7.x86_64 root=UUID=0f790447-ebef-4ca0-b229-d0aa1985d57f ro console=ttyS0,115200 console=tty0 console=ttyS0,115200n8 vconsole.font=latarcyrheb-sun16 crashkernel=auto vconsole.keymap=us LANG=en_US.UTF-8
[ 75016.900] Build Date: 05 August 2017  06:19:43AM
[ 75016.900] Build ID: xorg-x11-server 1.19.3-11.el7 
[ 75016.900] Current version of pixman: 0.34.0
[ 75016.900] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[ 75016.900] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[ 75016.900] (++) Log file: ".xorgxrdp.12.log", Time: Fri Jan 26 07:58:09 2018
[ 75016.900] (++) Using config file: "/etc/X11/xrdp/xorg.conf"
[ 75016.900] (==) Using config directory: "/etc/X11/xorg.conf.d"
[ 75016.900] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[ 75016.901] (==) ServerLayout "X11 Server"
[ 75016.901] (**) |-->Screen "Screen (xrdpdev)" (0)
[ 75016.901] (**) |   |-->Monitor "Monitor"
[ 75016.901] (**) |   |-->Device "Video Card (xrdpdev)"
[ 75016.901] (**) |-->Input Device "xrdpMouse"
[ 75016.901] (**) |-->Input Device "xrdpKeyboard"
[ 75016.901] (**) Option "DontVTSwitch" "on"
[ 75016.901] (**) Option "AutoAddDevices" "off"
[ 75016.901] (**) Not automatically adding devices
[ 75016.901] (==) Automatically enabling devices
[ 75016.901] (==) Automatically adding GPU devices
[ 75016.901] (==) Automatically binding GPU devices
[ 75016.901] (==) Max clients allowed: 256, resource mask: 0x1fffff
[ 75016.901] (==) FontPath set to:
	catalogue:/etc/X11/fontpath.d,
	built-ins
[ 75016.901] (==) ModulePath set to "/usr/lib64/xorg/modules"
[ 75016.901] (II) Loader magic: 0x55ca5aefa020
[ 75016.901] (II) Module ABI versions:
[ 75016.901] 	X.Org ANSI C Emulation: 0.4
[ 75016.901] 	X.Org Video Driver: 23.0
[ 75016.901] 	X.Org XInput driver : 24.1
[ 75016.901] 	X.Org Server Extension : 10.0
[ 75016.902] (II) xfree86: Adding drm device (/dev/dri/card0)
[ 75016.926] (--) PCI:*(0:0:2:0) 1013:00b8:5853:0001 rev 0, Mem @ 0xf0000000/33554432, 0xf3000000/4096, BIOS @ 0x????????/131072
[ 75016.926] (II) "glx" will be loaded. This was enabled by default and also specified in the config file.
[ 75016.926] (II) LoadModule: "dbe"
[ 75016.926] (II) Module "dbe" already built-in
[ 75016.926] (II) LoadModule: "ddc"
[ 75016.926] (II) Module "ddc" already built-in
[ 75016.926] (II) LoadModule: "extmod"
[ 75016.926] (II) Module "extmod" already built-in
[ 75016.926] (II) LoadModule: "glx"
[ 75016.927] (II) Loading /usr/lib64/xorg/modules/extensions/libglx.so
[ 75016.928] (II) Module glx: vendor="X.Org Foundation"
[ 75016.928] 	compiled for 1.19.3, module version = 1.0.0
[ 75016.928] 	ABI class: X.Org Server Extension, version 10.0
[ 75016.928] (II) LoadModule: "int10"
[ 75016.928] (II) Loading /usr/lib64/xorg/modules/libint10.so
[ 75016.929] (II) Module int10: vendor="X.Org Foundation"
[ 75016.929] 	compiled for 1.19.3, module version = 1.0.0
[ 75016.929] 	ABI class: X.Org Video Driver, version 23.0
[ 75016.929] (II) LoadModule: "record"
[ 75016.929] (II) Module "record" already built-in
[ 75016.929] (II) LoadModule: "vbe"
[ 75016.929] (II) Loading /usr/lib64/xorg/modules/libvbe.so
[ 75016.929] (II) Module vbe: vendor="X.Org Foundation"
[ 75016.929] 	compiled for 1.19.3, module version = 1.1.0
[ 75016.929] 	ABI class: X.Org Video Driver, version 23.0
[ 75016.929] (II) LoadModule: "xorgxrdp"
[ 75016.929] (II) Loading /usr/lib64/xorg/modules/libxorgxrdp.so
[ 75016.929] (II) Module XORGXRDP: vendor="X.Org Foundation"
[ 75016.929] 	compiled for 1.19.3, module version = 1.0.0
[ 75016.929] 	ABI class: X.Org Video Driver, version 23.0
[ 75016.929] xorgxrdpSetup:
[ 75016.929] (II) LoadModule: "fb"
[ 75016.929] (II) Loading /usr/lib64/xorg/modules/libfb.so
[ 75016.930] (II) Module fb: vendor="X.Org Foundation"
[ 75016.930] 	compiled for 1.19.3, module version = 1.0.0
[ 75016.930] 	ABI class: X.Org ANSI C Emulation, version 0.4
[ 75016.930] (II) LoadModule: "xrdpdev"
[ 75016.930] (II) Loading /usr/lib64/xorg/modules/drivers/xrdpdev_drv.so
[ 75016.930] (II) Module XRDPDEV: vendor="X.Org Foundation"
[ 75016.930] 	compiled for 1.19.3, module version = 1.0.0
[ 75016.930] 	ABI class: X.Org Video Driver, version 23.0
[ 75016.930] xrdpdevSetup:
[ 75016.930] (II) LoadModule: "xrdpmouse"
[ 75016.930] (II) Loading /usr/lib64/xorg/modules/input/xrdpmouse_drv.so
[ 75016.930] (II) Module XRDPMOUSE: vendor="X.Org Foundation"
[ 75016.930] 	compiled for 1.19.3, module version = 1.0.0
[ 75016.930] 	Module class: X.Org XInput Driver
[ 75016.930] 	ABI class: X.Org XInput driver, version 24.1
[ 75016.930] rdpmousePlug:
[ 75016.930] (II) LoadModule: "xrdpkeyb"
[ 75016.930] (II) Loading /usr/lib64/xorg/modules/input/xrdpkeyb_drv.so
[ 75016.930] (II) Module XRDPKEYB: vendor="X.Org Foundation"
[ 75016.930] 	compiled for 1.19.3, module version = 1.0.0
[ 75016.930] 	Module class: X.Org XInput Driver
[ 75016.930] 	ABI class: X.Org XInput driver, version 24.1
[ 75016.930] rdpkeybPlug:
[ 75016.930] rdpIdentify:
[ 75016.930] (II) XRDPDEV: driver for xrdp: XRDPDEV
[ 75016.930] rdpDriverFunc: op 10
[ 75016.930] (WW) Falling back to old probe method for XRDPDEV
[ 75016.930] rdpProbe:
[ 75016.930] (II) Loading sub module "fb"
[ 75016.930] (II) LoadModule: "fb"
[ 75016.931] (II) Loading /usr/lib64/xorg/modules/libfb.so
[ 75016.931] (II) Module fb: vendor="X.Org Foundation"
[ 75016.931] 	compiled for 1.19.3, module version = 1.0.0
[ 75016.931] 	ABI class: X.Org ANSI C Emulation, version 0.4
[ 75016.931] (II) XRDPDEV(0): using default device
[ 75016.931] rdpPreInit:
[ 75016.931] (**) XRDPDEV(0): Depth 24, (--) framebuffer bpp 32
[ 75016.931] (==) XRDPDEV(0): RGB weight 888
[ 75016.931] (==) XRDPDEV(0): Using gamma correction (1.0, 1.0, 1.0)
[ 75016.931] (==) XRDPDEV(0): Default visual is TrueColor
[ 75016.931] (==) XRDPDEV(0): DPI set to (96, 96)
[ 75016.931] (II) XRDPDEV(0): 	mode "640x480" ok
[ 75016.931] (II) XRDPDEV(0): 	mode "800x600" ok
[ 75016.931] (--) XRDPDEV(0): Virtual size is 800x600 (pitch 800)
[ 75016.931] (**) XRDPDEV(0):  Default mode "800x600": 36.0 MHz (scaled from 0.0 MHz), 35.2 kHz, 56.2 Hz
[ 75016.931] (II) XRDPDEV(0): Modeline "800x600"x0.0   36.00  800 824 896 1024  600 601 603 625 +hsync +vsync (35.2 kHz d)
[ 75016.931] (==) Depth 24 pixmap format is 32 bpp
[ 75016.931] rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
[ 75016.931] rdpScreenInit: pfbMemory bytes 1920000
[ 75016.931] rdpScreenInit: pfbMemory 0x7f92d3dac010
[ 75016.931] rdpSimdInit: assigning yuv functions
[ 75016.931] rdpSimdInit: cpuid ax 1 cx 0 return ax 0x000406f1 bx 0x01020800 cx 0xfffa3203 dx 0x178bfbff
[ 75016.931] rdpSimdInit: sse2 amd64 yuv functions assigned
[ 75016.931] rdpXvInit: depth 24
[ 75016.931] (==) XRDPDEV(0): Backing store enabled
[ 75016.932] rdpClientConInit: kill disconnected [0] timeout [0] sec
[ 75016.932] 
[ 75016.932] rdpScreenInit: out
[ 75016.932] (==) RandR enabled
[ 75016.936] (II) SELinux: Disabled by boolean
[ 75016.942] (II) AIGLX: Screen 0 is not DRI2 capable
[ 75016.942] (EE) AIGLX: reverting to software rendering
[ 75016.950] (II) IGLX: enabled GLX_MESA_copy_sub_buffer
[ 75016.951] (II) IGLX: Loaded and initialized swrast
[ 75016.951] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[ 75016.982] (II) Using input driver 'XRDPMOUSE' for 'xrdpMouse'
[ 75016.982] (**) Option "CorePointer"
[ 75016.982] (**) xrdpMouse: always reports core events
[ 75016.982] rdpmousePreInit: drv 0x55ca5b00e630 info 0x55ca5b1124c0, flags 0x0
[ 75016.982] (II) XINPUT: Adding extended input device "xrdpMouse" (type: Mouse, id 6)
[ 75016.982] rdpmouseControl: what 0
[ 75016.982] rdpmouseDeviceInit:
[ 75016.982] rdpmouseCtrl:
[ 75016.982] rdpRegisterInputCallback: type 1 proc 0x7f92d4185d20
[ 75016.982] (**) xrdpMouse: (accel) keeping acceleration scheme 1
[ 75016.982] (**) xrdpMouse: (accel) acceleration profile 0
[ 75016.982] (**) xrdpMouse: (accel) acceleration factor: 2.000
[ 75016.982] (**) xrdpMouse: (accel) acceleration threshold: 4
[ 75016.982] rdpmouseControl: what 1
[ 75016.982] rdpmouseDeviceOn:
[ 75016.982] (II) Using input driver 'XRDPKEYB' for 'xrdpKeyboard'
[ 75016.982] (**) Option "CoreKeyboard"
[ 75016.982] (**) xrdpKeyboard: always reports core events
[ 75016.982] rdpkeybPreInit: drv 0x55ca5b00ed60 info 0x55ca5b29c050, flags 0x0
[ 75016.982] (II) XINPUT: Adding extended input device "xrdpKeyboard" (type: Keyboard, id 7)
[ 75016.982] rdpkeybControl: what 0
[ 75016.982] rdpkeybDeviceInit:
[ 75017.008] rdpkeybChangeKeyboardControl:
[ 75017.008] rdpkeybChangeKeyboardControl: autoRepeat on
[ 75017.008] rdpRegisterInputCallback: type 0 proc 0x7f92d3f824d0
[ 75017.008] rdpkeybControl: what 1
[ 75017.008] rdpkeybDeviceOn:
[ 75017.009] (II) config/udev: Adding input device Power Button (/dev/input/event0)
[ 75017.009] (II) AutoAddDevices is off - not adding device.
[ 75017.010] (II) config/udev: Adding input device Sleep Button (/dev/input/event1)
[ 75017.010] (II) AutoAddDevices is off - not adding device.
[ 75017.010] (II) config/udev: Adding input device AT Translated Set 2 keyboard (/dev/input/event2)
[ 75017.010] (II) AutoAddDevices is off - not adding device.
[ 75017.010] (II) config/udev: Adding input device ImExPS/2 Generic Explorer Mouse (/dev/input/event3)
[ 75017.010] (II) AutoAddDevices is off - not adding device.
[ 75017.010] (II) config/udev: Adding input device ImExPS/2 Generic Explorer Mouse (/dev/input/mouse0)
[ 75017.010] (II) AutoAddDevices is off - not adding device.
[ 75017.010] (II) config/udev: Adding input device PC Speaker (/dev/input/event4)
[ 75017.010] (II) AutoAddDevices is off - not adding device.
[ 75017.013] rdpSaveScreen:
[ 75017.013] rdpDeferredRandR:
[ 75017.013] rdpResizeSession: width 1024 height 768
[ 75017.013]   calling RRScreenSizeSet
[ 75017.013] rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
[ 75017.014] rdpRRGetInfo:
[ 75017.014]   screen resized to 1024x768
[ 75017.016]   RRScreenSizeSet ok 1
[ 75017.016] rdpResizeSession: width 1024 height 768
[ 75017.108] rdpInDeferredUpdateCallback:
[ 75017.108] rdpkeybChangeKeyboardControl:
[ 75017.108] rdpkeybChangeKeyboardControl: autoRepeat off
[ 75017.395] rdpRRGetInfo:
[ 75017.448] rdpClientConGotConnection:
[ 75017.448] rdpClientConGotConnection: g_sck_accept ok new_sck 21
[ 75017.448] rdpClientConGotConnection: adding only clientCon
[ 75017.451] rdpClientConProcessMsgVersion: version 0 0 0 1
[ 75017.451] rdpClientConProcessScreenSizeMsg: set width 1024 height 768 bpp 16
[ 75017.451] rdpClientConProcessScreenSizeMsg: shmemid 4554765 shmemptr 0x7f92d3e01000
[ 75017.451] rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1024 cy 768
[ 75017.460] rdpClientConProcessMsgClientInfo:
[ 75017.460]   got client info bytes 5744
[ 75017.460]   jpeg support 0
[ 75017.460]   offscreen support 1
[ 75017.460]   offscreen size 7864320
[ 75017.460]   offscreen entries 2000
[ 75017.460]   client supports glyph cache but server disabled
[ 75017.460]   client can do offscreen to offscreen blits
[ 75017.460]   client can do new(color) cursor
[ 75017.460]   client can not do multimon
[ 75017.460] rdpRRSetRdpOutputs: numCrtcs 0 monitorCount 0
[ 75017.460] rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1024 height 768
[ 75017.460] rdpLoadLayout: keylayout 0x00000409 variant  display 12
[ 75017.460] rdpkeybChangeKeyboardControl:
[ 75017.460] rdpkeybChangeKeyboardControl: autoRepeat on
[ 75017.461] rdpkeybChangeKeyboardControl:
[ 75017.461] rdpkeybChangeKeyboardControl: autoRepeat on
[ 75017.561] rdpInDeferredUpdateCallback:
[ 75017.561] rdpkeybChangeKeyboardControl:
[ 75017.561] rdpkeybChangeKeyboardControl: autoRepeat off
[ 75017.561] rdpkeybChangeKeyboardControl:
[ 75017.561] rdpkeybChangeKeyboardControl: autoRepeat off
[ 75017.607] rdpRRGetInfo:
[ 75017.620] rdpRRGetInfo:
[ 75017.642] rdpRRGetInfo:
[ 75017.643] rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
[ 75017.644] rdpRRGetInfo:
[ 75017.644]   screen resized to 1024x768
[ 75017.645] rdpRROutputSetProperty:
[ 75017.646] rdpRROutputGetProperty:
[ 75017.649] rdpmouseCtrl:
[ 75017.714] rdpkeybChangeKeyboardControl:
[ 75017.714] rdpkeybChangeKeyboardControl: autoRepeat on
[ 75017.714] rdpkeybChangeKeyboardControl:
[ 75017.714] rdpkeybChangeKeyboardControl: autoRepeat on
[ 75017.714] rdpkeybChangeKeyboardControl:
[ 75017.714] rdpkeybChangeKeyboardControl: autoRepeat on
[ 75017.714] rdpkeybChangeKeyboardControl:
[ 75017.714] rdpkeybChangeKeyboardControl: autoRepeat on
[ 75017.722] rdpkeybChangeKeyboardControl:
[ 75017.722] rdpkeybChangeKeyboardControl: autoRepeat on
[ 75017.722] rdpkeybChangeKeyboardControl:
[ 75017.722] rdpkeybChangeKeyboardControl: autoRepeat on
[ 75017.822] rdpInDeferredUpdateCallback:
[ 75017.822] rdpkeybChangeKeyboardControl:
[ 75017.822] rdpkeybChangeKeyboardControl: autoRepeat off
[ 75017.822] rdpkeybChangeKeyboardControl:
[ 75017.822] rdpkeybChangeKeyboardControl: autoRepeat off
[ 75019.543] rdpRROutputGetProperty:
[ 75019.561] rdpRRGetInfo:
[ 75020.202] rdpkeybChangeKeyboardControl:
[ 75020.202] rdpkeybChangeKeyboardControl: autoRepeat off
[ 75020.202] rdpkeybChangeKeyboardControl:
[ 75020.202] rdpkeybChangeKeyboardControl: autoRepeat off
[ 75020.203] rdpkeybChangeKeyboardControl:
[ 75020.203] rdpkeybChangeKeyboardControl: autoRepeat off
[ 75020.203] rdpkeybChangeKeyboardControl:
[ 75020.203] rdpkeybChangeKeyboardControl: autoRepeat off
[ 75022.361] rdpRRCrtcGetGamma: 0x55ca5b2b6f20 (nil) (nil) (nil)
[ 75024.596] rdpkeybChangeKeyboardControl:
[ 75024.596] rdpkeybChangeKeyboardControl: autoRepeat off
[ 75024.596] rdpkeybChangeKeyboardControl:
[ 75024.596] rdpkeybChangeKeyboardControl: autoRepeat off
[ 75025.101] rdpRRCrtcGetGamma: 0x55ca5b2b6f20 0x55ca5b673d60 0x55ca5b673d30 0x55ca5b673d90
[ 75025.390] rdpmouseControl: what 2
[ 75025.390] rdpmouseDeviceOff:
[ 75025.390] rdpkeybControl: what 2
[ 75025.390] rdpkeybDeviceOff:
[ 75025.487] rdpkeybControl: what 3
[ 75025.487] rdpkeybUnInit: drv 0x55ca5b00ed60 info 0x55ca5b29c050, flags 0x0
[ 75025.487] rdpUnregisterInputCallback: proc 0x7f92d3f824d0
[ 75025.487] rdpmouseControl: what 3
[ 75025.487] rdpmouseUnInit: drv 0x55ca5b00e630 info 0x55ca5b1124c0, flags 0x0
[ 75025.487] rdpUnregisterInputCallback: proc 0x7f92d4185d20
[ 75025.493] rdpCloseScreen:
[ 75025.493] xorgxrdpDownDown:
[ 75025.493] xorgxrdpDownDown: 1
[ 75025.493] rdpClientConDeinit:
[ 75025.493] rdpClientConDeinit: disconnecting only clientCon
[ 75025.493] rdpClientConDisconnect:
[ 75025.494] rdpClientConDisconnect: clientCon removed from dev list
[ 75025.494] rdpClientConDeinit: deleting file /tmp/.xrdp/xrdp_display_12
[ 75025.494] rdpClientConDeinit: deleting file /tmp/.xrdp/xrdp_disconnect_display_12
[ 75025.494] (II) Server terminated successfully (0). Closing log file.

`

**Comment by metalefty** [comment]
Be sure to surround with "```"  (triple back quotation) when you post logs.

**Comment by Alhel** [comment]
installing the latest version of xorgxrdp solved the problem
