### ISSUE TITLE
Can't run dist-upgrade

### ISSUE THREAD

**Issue by nmsousa** [neutrinolabs/xrdp#1012]
Hello guys, can any one help or point me to the right place to ask this question, i've the following error using MobaXterm on my pc to update my OSMC (raspberry pi) with the following command:
$ sudo apt-get dist-upgrade

`Job for xrdp-sesman.service failed because of unavailable resources or another system error.
See "systemctl status xrdp-sesman.service" and "journalctl -xe" for details.
xrdp-sesman.service couldn't start.
Processing triggers for libc-bin (2.24-11+deb9u1) ...
W: APT had planned for dpkg to do more than it reported back (0 vs 4).
   Affected packages: xrdp:armhf
`

If I then run this:
$ systemctl status xrdp-sesman.service

I'm getting this error:
```
* xrdp-sesman.service - xrdp session manager
   Loaded: loaded (/lib/systemd/system/xrdp-sesman.service; enabled; vendor preset: enabled)
   Active: failed (Result: resources) since Sat 2018-01-27 14:39:37 WET; 7min ago
     Docs: man:xrdp-sesman(8)
           man:sesman.ini(5)
  Process: 32296 ExecStart=/usr/sbin/xrdp-sesman $SESMAN_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 32259 (code=exited, status=0/SUCCESS)

Jan 27 14:39:37 osmc systemd[1]: Starting xrdp session manager...
Jan 27 14:39:37 osmc xrdp-sesman[32296]: (32296)(1992482816)[DEBUG] libscp initialized
Jan 27 14:39:37 osmc xrdp-sesman[32297]: (32297)(1992482816)[INFO ] starting xrdp-sesman with pid 32297
Jan 27 14:39:37 osmc xrdp-sesman[32297]: (32297)(1992482816)[ERROR] bind error on port '3350': 22 (Invalid argument)
Jan 27 14:39:37 osmc xrdp-sesman[32297]: (32297)(1992482816)[DEBUG] Closed socket 7 (AF_INET6 :: port 0)
Jan 27 14:39:37 osmc systemd[1]: xrdp-sesman.service: PID file /run/xrdp/xrdp-sesman.pid not readable (yet?) after start: No such file or directory
Jan 27 14:39:37 osmc systemd[1]: Failed to start xrdp session manager.
Jan 27 14:39:37 osmc systemd[1]: xrdp-sesman.service: Unit entered failed state.
Jan 27 14:39:37 osmc systemd[1]: xrdp-sesman.service: Failed with result 'resources'.
```

Running this:
$ journalctl -xe

I get the error:
`Jan 27 14:47:50 osmc transmission-daemon[320]: [2018-01-27 14:47:50.348] magnet status: checksum passed 0, metainfo parsed 0 (torrent-magnet.c:342)`

Thanks in advance,
Best regards!

**Comment by metalefty** [comment]
It seems your distro issue.
