### ISSUE TITLE
module-xrdp-sink.so and module-xrdp-source.so installed but no sound

### ISSUE THREAD

**Issue by iinux** [neutrinolabs/xrdp#1013]
I do as https://github.com/neutrinolabs/xrdp/wiki/How-to-set-up-audio-redirection written, and I can see xrdp-sink and xrdp-source. When I play a song, the second progress bar will move, but I can not hear the sound. 
![xrdp](https://user-images.githubusercontent.com/7881398/35479555-463e7cfe-0435-11e8-88f1-629399b9631c.png)
Should I do some additional configuration?
Should I use other session (Xorg, X11rdp) not Xvnc?
pulseaudio 10.0
xrdp 0.9.5
CentOS 7

**Comment by metalefty** [comment]
What's your client?

**Comment by iinux** [comment]
Windows 7 mstsc

**Comment by metalefty** [comment]
Okay, if the second bar is moving, it is almost working. 
Of course, your client configuration plays the sound locally, right?

**Comment by iinux** [comment]
client configuration is ok, and the same configuration which connect to a windows 7 server can play the sound.

**Comment by iinux** [comment]
because occur a error before
```
vnc connecting to 127.0.0.1 5910
vnc error - problem connecting
some problem
```
so I edit the xrdp.ini
```
[Xvnc]
name=Xvnc
lib=libvnc.so
username=ask
password=ask
ip=127.0.0.1
port=5901 ! change from -1 to 5901
#xserverbpp=24
delay_ms=2000
```
and can not see **xrdp-sink** and **xrdp-source**, I add 
```
.ifexists module-xrdp-sink.so
load-module module-xrdp-sink
.endif
.ifexists module-xrdp-source.so
load-module module-xrdp-source
.endif
```
to `/etc/pulse/default.pa`
**xrdp-sink** and **xrdp-source** is appeared
other configuration is default, xrdp is installed by `sudo yum install xrdp`

**Comment by coredump4** [comment]
I've seen something similar while trying to build my own 0.9.5 RPM on CentOS 7.  I get the exact behavior described above.  And when I check the chansrv folder, there aren't any sockets there.  Thinking this was odd, I attached strace to the xrdp-chansrv process, and it seemed to be stuck in select().  I'd love to understand what's going on, since CentOS' xrdp packages are always out-of-date, or missing essential options (like audio!).

**Comment by iinux** [comment]
@coredump4  Which one are you used? Xvnc Xorg X11rdp?

**Comment by coredump4** [comment]
I use xorgxrdp and Xvnc back-ends... same behavior with each.  Which makes sense to me, since it seems to be something with the channel server.

**Comment by coredump4** [comment]
The last message I see from chansrv is:
channel_thread_loop:  thread start
@metalefty any idea what could be going on with channels?
Thanks!

**Comment by bmalnersic** [comment]
PROBABLE SOLUTION
Hi, was just having a same issue - everything looks OK, no sound (Windows 10, Windows Server 2012 R2). It turned out that my issue was due to modules being compiled using the git clone of the current xrdp... It compiled just fine on the latest Raspibian with apt source pulseaudit, however it did not work. What I did next is, I downloaded the Raspibian source of the xrdp (apt source xrdp) - v0.9.1 and compiled modules from that source. Now the sound redirection works.
Hope this helps.

**Comment by IanDury** [comment]
Thanks bmalnersic!

Had the same issue. Your solution also works for Debian 9.

**Comment by darkphoenix** [comment]
For me (Ubuntu 18.04) the modules (no matter whether I build them by hand or using xrdp-build-pulse-modules) compile fine but constantly fail to connect to a socket in /tmp/.xrdp/ - apparently that's supposed to be created by xrdp-chansrv, which for some reason doesn't even start, and if I start it by hand, it doesn't do anything (last message same as with @coredump4, /tmp/.xrdp still doesn't exist...) - is this a known issue? Any ideas how to make chansrv create the sockets? It just says the socket types that are allowed, but for some reason, they aren't opened? I'm out of ideas here, and after hours of googling I'm quite annoyed about the nonexistence of docs about troubleshooting the PulseAudio forwarding - there's hardly any on building the module to begin with, everything else seems to just be "trial and error". Is this even actively developed/maintained any more?

**Comment by hymer-up** [comment]
Looking for the best linux-friendly RDP server solution but same sound issue on my stretch. The xrdp-pulseaudio-installer package is brokken and not really better with rebuilding modules on 0.9.1 which just have correct vumeter display on xrdp sink...

**Comment by smooker** [comment]
cat /etc/xrdp/xrdp.ini
....
[Channels]
rdpsnd=true
....
???

**Comment by mohsinis** [comment]
I had same issue and I was able to solve it by simply changing `allow_channels` from `false` to `true` in my `/etc/xrdp/xrdp.ini` file and after that I restarted the machine and everything started working as expected.
```
; Section name to use for automatic login if the client sends username
; and password. If empty, the domain name sent by the client is used.
; If empty and no domain name is given, the first suitable section in
; this file will be used.
autorun=

allow_channels=true
allow_multimon=true
bitmap_cache=true
bitmap_compression=true
bulk_compression=true
#hidelogwindow=true
max_bpp=32
new_cursors=false
```

**Comment by matt335672** [comment]
I'm closing this issue now. Version 0.6 of the pulseaudio module [has been released](/neutrinolabs/pulseaudio-module-xrdp/releases/tag/v0.6) with significant changes, and the [wiki README](/neutrinolabs/pulseaudio-module-xrdp/wiki/README) has been updated with better build instructions.
