### ISSUE TITLE
Question about /etc/xrdp.sh

### ISSUE THREAD

**Issue by Vraiment** [neutrinolabs/xrdp#1019]
I'm working on making the */etc/xrdp.sh* script work on Mac OS to be able to easily start/stop XRDP with a single command.

From reading the comments at the top of */etc/xrdp.sh* I see that is for using it as an init script, why not store it as */bin/xrdp-ctrl* or */sbin/xrdp-ctrl*. Mac OS could use a slightly different version of the script but it would make more sense to drop it in one of those directories and then the operating systems could share the same script.

**Comment by moobyfr** [comment]
What about a launchd item ?

**Comment by Vraiment** [comment]
Because I'm new to Mac OS internals and I'm learning as I go, launchd sounds good but have to read in deep about it

**Comment by metalefty** [comment]
That script for Linux is ancient and not maintained. Not tested if it works with recent Linux distro.  At least recent Linux systems use systemd so the script is not needed. I think script can be removed from the repository.

You can make another script for macOS and name place it the path such as _$PREFIX/sbin/xrdp-ctrl_.  I think making `.plist` files for launchd would be much better.

**Comment by Vraiment** [comment]
Ok, I will see onto writing the `plist` files, is there any proper documentation about how to launch and stop xrdp and xrdp-sesman?

**Comment by metalefty** [comment]
AFAIK, `xrdp -h` `xrdp-sesman -h` are all.

**Comment by jsorg71** [comment]
I do use "/etc/xrdp/xrdp.sh"
I don't think there is a "/etc/xrdp.sh"

**Comment by Vraiment** [comment]
I mean */etc/xrdp/xrdp.sh* from the beginning

**Comment by Vraiment** [comment]
I'm closing this issue as is better to have _launchd_ files instead of _/etc/xrdp/xrdp.sh_
