### ISSUE TITLE
--enable-strict-locations is inverted

### ISSUE THREAD

**Issue by Vraiment** [neutrinolabs/xrdp#1020]
If you do:
```sh
./configure --prefix=/tests/ --sysconfdir=/tests/etc
```
the configure script will ignore the values passed to *--sysconfdir*.

But if you do:
```sh
./configure --prefix=/tests/ --sysconfdir=/tests/etc --enable-strict-locations
```
the configure script will use the values passed to *--sysconfdir*.

I would think that *--enable-strict-locations* forces you to use the default locations (ie: */etc*).

**Comment by metalefty** [comment]
--enable-strict-locations works as intended.
