### ISSUE TITLE
Poor performance of xorg over wan

### ISSUE THREAD

**Issue by kaysond** [neutrinolabs/xrdp#1026]
I have xrdp configured with a single xorg environment. When I log in via the local network, performance is great and mostly pretty smooth.

When I log in from work (i.e. over the internet), the performance degrades significantly, and becomes very choppy. Its entirely possible its just due to the internet quality. I get about 24Mbps of bandwidth to my server, and ping averages 87ms with a max of 186ms. I'm running a 1920x1200 desktop.

Any ideas how to debug? Or if this bandwidth is sufficient for the connection? In the windows task manager I only see the network utilization spike up to about 3Mbps when I'm scrolling a window in rdp, for example.

**Comment by metalefty** [comment]
Can you let me know if is RemoteFX being used?

~/.xorgxrdp.%s.log will contain 
```
[914697.603] rdpClientConProcessMsgClientInfo: got RFX capture
```

if RemoteFX is being used.

**Comment by kaysond** [comment]
Looked through Xorg.10.log and xrdp.log, didn't see that message anywhere. (grep'd all the logs actually and no results)

**Comment by metalefty** [comment]
RemoteFX provides you more efficient compression and performance.  Try **24 or 32 bit color** and connection type **LAN** not _autodetect_.

**Comment by kaysond** [comment]
You mean in the rdp client settings?

**Comment by metalefty** [comment]
yep

**Comment by kaysond** [comment]
Looks like RemoteFX is being used, but still no luck. Here's the whole log file (RFX on line 233). Any ideas? https://pastebin.com/YnBPvcDJ

**Comment by kaysond** [comment]
I'm still having a lot of trouble with this. I tried using my phone as a hotspot to get off the work internet, but same performance. 0% CPU usage on my router, so I don't think that's it... I only have a text editor and a terminal open (using openbox). Not sure why its so slow. Please help!

**Comment by moobyfr** [comment]
What are the version used for xrdp and xorgxrdp ?

**Comment by kaysond** [comment]
0.9.1-9 for both

**Comment by kaysond** [comment]
I also tried using an rdp client on my phone (wifi and cellular), and I get the same sort of performance issue

**Comment by Suncatcher** [comment]
> ~/.xorgxrdp.%s.log will contain

How can I check another way that RemoteFX is enabled? My Xorg.0.log is empty, nothing is being written to it.

**Comment by metalefty** [comment]
@Suncatcher Why you're looking at `Xorg.0.log`?

**Comment by Suncatcher** [comment]
> Why you're looking at Xorg.0.log?

Because I have no ~/.xorgxrdp.%s.log file in my home dir.

**Comment by metalefty** [comment]
It is definitely not the xorgxrdp's log. It is console Xorg's log.  Anyway, let’s get back on track. Raise your own issue for your question. I'll answer if time permits.

**Comment by metalefty** [comment]
If RemoteFX is being used, that is the best performance so far.

**Comment by kaysond** [comment]
bump. this is still a problem and its quite a bummer. what else can I provide to help debug? I'm happy to use a workaround. Is a different display manager going to perform better?

**Comment by kaysond** [comment]
@metalefty 
I've collected some logs. Both are

- Fullscreen (1920x1200)
- no Audio
- Apply Windows Key Combinations: Only when using fulls creen
- Local devices and resources: clipboard only
- No programs
- Connection speed: LAN (all boxes checked)

This log is 16bit color: https://pastebin.com/pzzhC3s5
This log is 24bit color: https://pastebin.com/CmBmCYeQ

Both logs start from a fresh session (i.e. they open a new window manager). I opened sublime text, typed some text, and then closed the client. The lag is still there on both.

Any ideas?

**Comment by lieff** [comment]
Hmm, I use same setup and no problem, but my connection 100mbps.
Have you tried 32bpp? RFX codec supports only 32bpp. You can see all possible selections in latest Remmina:
![screenshot from 2018-08-13 23-39-20](https://user-images.githubusercontent.com/10080078/44056905-5c387c7c-9f52-11e8-9708-883f5c73bee8.png)

You can also try 8bpp aka 256colors, it can provide acceptable quality in office cases. Also you can check bandwidth utilization using wireshark.

**Comment by kaysond** [comment]
Updated my previous comment with a 32bit color log. Still the same thing. I can't actually select 8b color on the windows client.

My server has a 25mbps upload connection, but nethogs shows xrdp only using 10KB/s... Is that normal? I'm happy for it to use more if it improves performance...

**Comment by lieff** [comment]
```
[567565.031] rdpClientConProcessMsgClientInfo:
[567565.031]   got client info bytes 5744
[567565.031]   jpeg support 0
[567565.031]   offscreen support 1
[567565.031]   offscreen size 7864320
[567565.031]   offscreen entries 100
[567565.031] rdpClientConProcessMsgClientInfo: got RFX capture
[567565.031]   cap_width 1920 cap_height 1216
[567565.031] rdpClientConProcessMsgClientInfo: shmemid 11993091 shmemptr 0x7f1988b58000 bytes 9338880
[567565.031]   client can not do offscreen to offscreen blits <<< ???
[567565.031]   client can do new(color) cursor
[567565.031]   client can not do multimon
```

My info:
```
[  3207.459]   got client info bytes 5744
[  3207.459]   jpeg support 0
[  3207.459]   offscreen support 1
[  3207.459]   offscreen size 7864320
[  3207.459]   offscreen entries 2000
[  3207.459]   client supports glyph cache but server disabled
[  3207.459]   client can do offscreen to offscreen blits
[  3207.459]   client can do new(color) cursor
[  3207.459]   client can not do multimon
```
MS Client can be affected by some security policy.
You can try FreeRDP client instead.

**Comment by kaysond** [comment]
Interesting. I'm not sure why that's there. But I would like to find a solution that allows use of built-in windows clients.

**Comment by lieff** [comment]
You can at least try and check if it helps. On my side MS client works slower even with MS server, especially in video case.

**Comment by lieff** [comment]
Remmina->XRDP vs MSTSC->WIN. By video case I mean running video player. On windows I use MPC-HC, and VLC on linux.

**Comment by kaysond** [comment]
@lieff Can you tell me how much bandwidth your xrdp conection uses on average?

**Comment by lieff** [comment]
![image](https://user-images.githubusercontent.com/10080078/44157977-5bd85480-a0bc-11e8-96f8-72c270759de0.png)

First peak up to 1.5 Megabytes\s - fast window dragging.
Second peak up to 10 Megabytes\s - video playback.
So, full 100Mbps utilized in video case.
This is without additional H264 channel for video.

**Comment by johnvondoe** [comment]
> RemoteFX provides you more efficient compression and performance. If you're using Windows built-in Remote Desktop Client, try **24 or 32 bit color** and connection type **LAN** not _autodetect_ to use RemoteFX.

@metalefty I simply cannot upvote you enough. Ater hours of struggle, close to giving up, I changed to LAN and my fps went from ~0.15 (not mistaken, a frame every 7 seconds) peak performance to ~15-20 fps. 100x improvement. Literally. Thank you, sir,

**Comment by 3b7ameed** [comment]
> Hmm, I use same setup and no problem, but my connection 100mbps.
> Have you tried 32bpp? RFX codec supports only 32bpp. You can see all possible selections in latest Remmina:
> ![screenshot from 2018-08-13 23-39-20](https://user-images.githubusercontent.com/10080078/44056905-5c387c7c-9f52-11e8-9708-883f5c73bee8.png)
> 
> You can also try 8bpp aka 256colors, it can provide acceptable quality in office cases. Also you can check bandwidth utilization using wireshark.

Thanks for that , what worked for me is changing for " RemoteFx (32 bpp) " now it's much better

**Comment by metalefty** [comment]
@johnvondoe Just for a note, 24/32 bit color and LAN are necessary but not sufficient condition to use RemoteFX codec.
