### ISSUE TITLE
Cannot use x11vnc to connect through xrdp to existing desktop

### ISSUE THREAD

**Issue by uberlinuxguy** [neutrinolabs/xrdp#1028]
#960 states that x11vnc should be able to be used as a back end to connect to the existing X desktop.  I've tried this several different ways and even had a look into the sesman code.  It seems that x11vnc never gets executed by sesman because sesman only recogizes Xvnc, Xdrp and Xorg as valid session types.  There is no "custom" session type and sesman appears to silently die and not spawn a server session if one of these three types is not used.

Suggestion: Add a feature to just plain ol' execute whatever is in the specified session instead of locking us into the 3 types.

**Comment by trainwrecktony** [comment]
your x11vnc, xrdp.ini must be not configured correctly. i have the below working with xorgxrdp driver, tigervnc xorg console driver on port 5900, x11vnc console on port 5901, and tigervnc non console on 5902.
running arch linux xfce4, x11vnc as service with -display :0 -rfbport 5901 -auth /var/run/lightdm/root/:0 lightlocker resplaced with sxlock
  
`[Xorg]
name=Xorg
lib=libxup.so
username=tony
password=
ip=127.0.0.1
port=-1
xserverbpp=24
code=20

[console]
name=console
lib=libvnc.so
ip=127.0.0.1
port=5900
username=na
password=na

[consolex11vnc]
name=consolex11vnc
lib=libvnc.so
ip=127.0.0.1
port=5901
username=na
password=na

[tigervnc5902]
name=tigervnc5902
lib=libvnc.so
ip=127.0.0.1
port=5902
username=na
password=`

**Comment by metalefty** [comment]
That configuration should work but not necessary. You can also use `vnc-any` to connect running x11vnc. It should be more universal.

**Comment by metalefty** [comment]
Use vnc-any.
