### ISSUE TITLE
Single Linux Remote Application

### ISSUE THREAD

**Issue by athenaNK** [neutrinolabs/xrdp#1038]
I am new to remote desktop and I have been searching for days.

I am interested in exposing Linux remote applications on every other desktop (Linux, Windows). 
Windows offer that with the RemoteApp. Is there any way that xrdp may offer the same functionality? 
Just to mention that I use Apache Guacamole and I am interested in exposing just a single Linux app on the browser.

Thank you in advance!

**Comment by evanlinde** [comment]
It is possible to start single applications in the remote desktop connection (at least when using the Xorg backend).

You just have to specify the full path of the program you want to start. In Guacamole, this should be the `initial-program` setting.
![2018-02-12_01](https://user-images.githubusercontent.com/12647483/36129900-2e80f0e6-102f-11e8-8fd2-3a6648fced2f.png)

The result isn't as integrated with the rest of your desktop as MS RemoteApps -- probably not a major concern since you're using Guacamole, but without a window manager you'll be missing some basic window controls.
![2018-02-12_02](https://user-images.githubusercontent.com/12647483/36129907-3b23b572-102f-11e8-83f8-2247f47ce79e.png)

If you want or need the window controls, you can write a custom script to start a window manager with your application:
```bash
#!/bin/bash
openbox &
/usr/bin/geany
```

**Comment by evanlinde** [comment]
I could be wrong, but I don't think you'll be able to accomplish what you're looking for using Guacamole.

If you use an RDP client like `mstsc` and get drive redirection setup correctly, you *should* be able work with files on your local system, but I don't think it's possible to get the same seamless experience that you describe with Windows RemoteApp.

**Comment by jsorg71** [comment]
True Remote App support in xrdp is started but not complete.  It will take a some development time to finish.

**Comment by athenaNK** [comment]
This is great! Nothing to do but wait.

**Comment by jsorg71** [comment]
Why wait, why not actually help!

**Comment by vishal144** [comment]
Was this finished ?

**Comment by defcon8** [comment]
> It is possible to start single applications in the remote desktop connection (at least when using the Xorg backend).
> 
> You just have to specify the full path of the program you want to start. In Guacamole, this should be the `initial-program` setting.
> ![2018-02-12_01](https://user-images.githubusercontent.com/12647483/36129900-2e80f0e6-102f-11e8-8fd2-3a6648fced2f.png)
> 
> The result isn't as integrated with the rest of your desktop as MS RemoteApps -- probably not a major concern since you're using Guacamole, but without a window manager you'll be missing some basic window controls.
> ![2018-02-12_02](https://user-images.githubusercontent.com/12647483/36129907-3b23b572-102f-11e8-83f8-2247f47ce79e.png)
> 
> If you want or need the window controls, you can write a custom script to start a window manager with your application:
> 
> ```shell
> #!/bin/bash
> openbox &
> /usr/bin/geany
> ```

My MSTSC doesn't have the "programs" tab.. using win10.

**Comment by defcon8** [comment]
Can XRDP be configured so that when a user log's in. He only sees one particular application instead of a window manager? Without having to set options in the RDP client?

We are trying to setup XRDP in a way, that one of our customers can launch an application on our infrastructure. But he must be restricted to this single application.

**Comment by evanlinde** [comment]
@defcon8 Yes, you can. In xrdp's `sesman.ini` file, there's a setting `DefaultWindowManager=startwm.sh`. You can edit or replace this `startwm.sh` script to do just about whatever you want.

A simpler option, if you only need to do this for one user, is to create a file `.xsession` in the user's home directory and make it executable with content like the following:
```bash
exec /path/to/app
```
Keep in mind that since the file is in the user's home directory, a sophisticated user might be able to edit, move/rename, or delete this file. You may be able to restrict file permissions on `.xsession` to prevent this, but I haven't tested it out.

**Comment by okhowang** [comment]
I test with [remoteapptool](http://www.kimknight.net/remoteapptool) on windows server
remoteapp should have a native window experience
![image](https://user-images.githubusercontent.com/3352585/93451694-183f1d00-f90a-11ea-9908-50453792ea24.png)
![image](https://user-images.githubusercontent.com/3352585/93451699-1bd2a400-f90a-11ea-91a1-93805f5ff996.png)

I modify the rdp file to connect I linux server.
```
allow desktop composition:i:1
allow font smoothing:i:1
alternate full address:s:[my server ip]
alternate shell:s:/usr/bin/geany
devicestoredirect:s:*
disableremoteappcapscheck:i:1
drivestoredirect:s:*
full address:s:[my server ip]
prompt for credentials on client:i:1
promptcredentialonce:i:0
redirectcomports:i:1
redirectdrives:i:1
remoteapplicationmode:i:1
remoteapplicationname:s:Geany
remoteapplicationprogram:s:||Gneay
span monitors:i:1
use multimon:i:1
```
but only got like this
![image](https://user-images.githubusercontent.com/3352585/93452073-900d4780-f90a-11ea-9722-23c50804c910.png)
there may need some extra processing for xrdp

**Comment by aquesnel** [comment]
I've been looking into enabling RAIL for mstc as well and I experience the same issue of the client not finishing the connection dialog.

I've traced down two problems for this issue, but there are more errors that I encounter and have not been able to fix yet.

Here are the two fixes that I made (not merged into devel yet):
* https://github.com/aquesnel/xrdp/commit/480689d2e3e712d0078c601f41f19795ab26a500
* https://github.com/aquesnel/xrdp/commit/8d6a56dfdd5a5fad05d1e3f4ed79c74fa5f0bf11

**Comment by Suncatcher** [comment]
So what feedback is needed for this issue? What is the prospective plan for it? Is it going to be implemented?

**Comment by qianglchina** [comment]
Is there any progress ?

**Comment by matt335672** [comment]
Not on this issue I'm afraid.

**Comment by StudyAndGrow** [comment]
> I test with [remoteapptool](http://www.kimknight.net/remoteapptool) on windows server remoteapp should have a native window experience ![image](https://user-images.githubusercontent.com/3352585/93451694-183f1d00-f90a-11ea-9908-50453792ea24.png) ![image](https://user-images.githubusercontent.com/3352585/93451699-1bd2a400-f90a-11ea-91a1-93805f5ff996.png)
> 
> I modify the rdp file to connect I linux server.
> 
> ```
> allow desktop composition:i:1
> allow font smoothing:i:1
> alternate full address:s:[my server ip]
> alternate shell:s:/usr/bin/geany
> devicestoredirect:s:*
> disableremoteappcapscheck:i:1
> drivestoredirect:s:*
> full address:s:[my server ip]
> prompt for credentials on client:i:1
> promptcredentialonce:i:0
> redirectcomports:i:1
> redirectdrives:i:1
> remoteapplicationmode:i:1
> remoteapplicationname:s:Geany
> remoteapplicationprogram:s:||Gneay
> span monitors:i:1
> use multimon:i:1
> ```
> 
> but only got like this ![image](https://user-images.githubusercontent.com/3352585/93452073-900d4780-f90a-11ea-9722-23c50804c910.png) there may need some extra processing for xrdp

I encountered the same problem, has this been solved?

**Comment by StudyAndGrow** [comment]
> Thank you for your prompt answer evanlinde. Unfortunately i believe that this is different from what I am looking for.
> 
> Using the initial_program I get the exact screen as the second of yours.
> 
> ![gedit_with_initial](https://user-images.githubusercontent.com/10614030/36148562-3e30ee6a-10c5-11e8-8d3a-07724410c54f.PNG)
> 
> There is a script that is executed when RDP connection is established and launched gedit. If I try to save the file it will not be saved in my local machine. With Windows RemoteApp this is not the case. For instance if you want to access Word it will be launched in your local machine and the file also will be persisted in your local machine.
> 
> This is a kind of scenario that I need to find out is offered from xrdp regarding linux apps.

Could you please tell me how to write startwm.sh?

**Comment by dsappacybelesoft** [comment]
> I've been looking into enabling RAIL for mstc as well and I experience the same issue of the client not finishing the connection dialog.
> 
> I've traced down two problems for this issue, but there are more errors that I encounter and have not been able to fix yet.
> 
> Here are the two fixes that I made (not merged into devel yet):
> 
> * [aquesnel@480689d](https://github.com/aquesnel/xrdp/commit/480689d2e3e712d0078c601f41f19795ab26a500)
> * [aquesnel@8d6a56d](https://github.com/aquesnel/xrdp/commit/8d6a56dfdd5a5fad05d1e3f4ed79c74fa5f0bf11)


hello @aquesnel 
I am reviewing these changes that you propose, I have even downloaded and compared the repo forked by you, I have not seen these changes reflected there, you have had some progress in this time, greetings.

**Comment by aquesnel** [comment]
Hi @dsappacybelesoft 
I haven't made progress in the xrdp code base for rail. I'm continuing to slowly investigate the issue by comparing xrdp rail messages vs mstsc rail messages. Please let me know if you'd like to collaborate.

**Comment by dsappacybelesoft** [comment]
Of course!
I am beginning to see how to progress with this, I will try to apply what you have proposed and I will surely leave you some comments about it.
