### ISSUE TITLE
Help setting up xrdp -- blank screen after connection

### ISSUE THREAD

**Issue by kingst** [neutrinolabs/xrdp#104]
I am having trouble setting up xrdp.  I built the latest version of xrdp from source and installed it on my raspberry pi running wheezy.  When I connect to it I only get a blank screen when I would expect the login prompt.  I looked through the logs and everything looks ok, and I tried some simple modifications of the startwm.sh script, like launching xeyes, but I could not seem to figure out the issue.

Does anyone have any guidance?

**Comment by metalefty** [comment]
No news almost 3 years, closing. Feel free to reopen if you want.
