### ISSUE TITLE
sesman.ini and killdisconnected setting doesn't seem to work

### ISSUE THREAD

**Issue by briantownjr** [neutrinolabs/xrdp#1042]
I have MaxSessions set to 1 in my sesman.ini and killDisconnected=true.

When a user disconnects from RDP I wait 60seconds and the process is still running and holding port 5910 so that any other use can't disconnect. Is this working as intended? Shouldn't that setting kill the process holding that port after 60 seconds?

**Comment by metalefty** [comment]
It seems you're using Xvnc backend because you mention about port 5910. The feature doesn't work with Xvnc session. Use xorgxrdp instead.

**Comment by metalefty** [comment]
No feedback from the reporter for 1 month. Closing.

**Comment by FelixZhang** [comment]
Tip for the Tigervnc users:
Tigervnc implementation of Xvnc supports a ["−MaxDisconnectionTime" option](http://tigervnc.org/doc/Xvnc.html):

So editing sesman.ini to work around:
```
[Xvnc]

...

param=-MaxDisconnectionTime

param=60
```
