### ISSUE TITLE
Why a single xrdp process don't use more than one cpu core (on my system) ?

### ISSUE THREAD

**Issue by tm-dd** [neutrinolabs/xrdp#1044]
Dear XRDP developers,

I like xrdp very much, but I have a small question.
I use xrdp on a bigger Linux server (28 CPU-Cores + hyper threading, 64 GB RAM) and compile the last stable version 0.9.5 from https://github.com/neutrinolabs/xrdp with audio redirection.

It works well with the video player vlc and smaller video sizes (like 960 × 540) but on higher resolution the video and audio quality will be poorer.

On the process table I see that vlc use more than 200 % CPU but xrdp will not using more than one cpu core. The xrdp process is not using more than 100 % CPU.

I tried other VNC software (like turbovnc and tigervnc) and X11rdp also, but the problem on my installation is always the same. I also tested some other RDP-Clients. But xrdp don’t use more than 100 % CPU and this should be the problem of the poorer video quality on bigger videos.

Now the question:

**Is there a way to compile xrdp so, that a single xrdp process can use more than one cpu core ?**

I use the following commands on debian 9 for compiling:

```
wget https://github.com/neutrinolabs/xrdp/releases/download/v0.9.5/xrdp-0.9.5.tar.gz
tar -xzf xrdp-0.9.5.tar.gz

cd /root/xrdp/librfxcodec
./bootstrap
./configure
make

./configure --enable-tjpeg --enable-fuse --enable-rfxcodec --enable-simplesound --enable-rfx --enable-strict-locations --enable-static /opt/local/xrdp
make
make install
...
```

Regards,

Thomas

**Comment by jsorg71** [comment]
Hi Thomas,  you have yasm or nasm installed when building, right?  If not the encoder will run higher CPU.
The RemoteFX encoder runs on a separate thread from the main thread so it does not block any other traffic.  It's currently only one thread and can't be configured to use more.  We would need to make a code change to use more but it's should not be that difficult to do.  Xrdp sets 2 "in flight" frames so we can have one thread per "in flight" or break the tile set up for multi thread processing.  The former is easier.  Also down the road we can use CUDA or OpenCL which would have 1 thread per tile most likely.

**Comment by tm-dd** [comment]
Hi jsorg71,

yes I installed nasm, because it should be necessary for X11rdp.

I'm using the following simple script for compiling:


```
#!/bin/bash
#
# script to compile xrdp on debian 9 by Thomas Mueller with instructions of:
#
#    - https://241931348f64b1d1.wordpress.com/2013/05/27/how-to-compile-xrdpx11rdp-on-ubuntu/
#    - http://manu.agat.net/dotclear/index.php/post/2015/07/23/Efficient-Remote-Desktop-on-linux
#    - https://github.com/neutrinolabs/xrdp/issues/438
#    - https://github.com/neutrinolabs/xrdp/issues/818
#    - https://github.com/neutrinolabs/xrdp
#    - and other web pages
#
#    *** YOU USE THIS SCRIPT AT YOUR OWN RISK. ***
#

set -x

# install git, wget and vim
apt-get update
apt-get -y install git wget vim

# install here 
INSTALLXRDPDIR='/opt/local/xrdp/xrdp_'`date '+%Y-%m-%d'`
INSTALLX11RDPDIR='/opt/local/x11rdp/x11rdp_'`date '+%Y-%m-%d'`
XRDPPREFIX='--prefix='${INSTALLXRDPDIR}
rm -rf ${INSTALLXRDPDIR}
rm -rf ${INSTALLX11RDPDIR}		
sleep 3

# nessesary software to compile for xrdp
apt-get update
apt-get -y build-dep xserver-xorg-core
apt-get -y install vim autoconf libtool pkg-config
apt-get -y install libssl-dev libpam0g-dev libjpeg-dev libx11-dev libxfixes-dev flex bison libxml2-dev intltool xsltproc xutils-dev python-libxml2 xutils libpulse-dev

# nessesary software to compile for x11rdp
apt-get -y install libfuse-dev
apt-get -y install libturbojpeg0 libturbojpeg0-dev
apt-get -y install libxrandr-dev
apt-get -y install nasm

# nessesary software to compile xrdp with "--enable-neutrinordp" (RDP proxy module)
apt-get -y install libfreerdp-dev

# compile xrdp
rm -rf /root/xrdp/
mv ${INSTALLXRDPDIR} ${INSTALLXRDPDIR}.last
set +x; echo; echo -n "Should the last xrdp source downloaded from git instead of version 0.9.5 (y/*) ? "
read USERINPUT
set -x
if [ $USERINPUT == y ]
then
    git clone --recursive https://github.com/neutrinolabs/xrdp
    tar -czf 'xrdp_from_git_'`date '+%Y-%m-%d'`.tar.gz xrdp
else
    rm xrdp-0.9.5.tar.gz
    wget https://github.com/neutrinolabs/xrdp/releases/download/v0.9.5/xrdp-0.9.5.tar.gz
    tar -xzf xrdp-0.9.5.tar.gz
    mv xrdp-0.9.5 /root/xrdp
fi
cd /root/xrdp/
./bootstrap
sleep 3


# configure an build librfxcodec
cd /root/xrdp/librfxcodec
./bootstrap
./configure
make

# configure, build and install xrdp (you can also try to use the option: --enable-neutrinordp)
cd /root/xrdp/
./configure --help
sleep 3

./configure --enable-tjpeg --enable-fuse --enable-rfxcodec --enable-simplesound --enable-rfx --enable-strict-locations --enable-static ${XRDPPREFIX}
make || ( echo "ERROR BY COMPILING."; sleep 10; exit -1 )
make install

sleep 3

set +x; echo; echo -n "Should X11RDP be compiled to use on XRDP later - this will take some time (y/*) ? "
read USERINPUT
set -x
if [ $USERINPUT == y ]
then
    # compile x11rdp (this takes the most time of this script)
    set +x; echo; echo -n "OK, COMPILING X11RDP now. THIS WILL TAKE SOME EXTRA TIME."; sleep 3; set -x
    cd /root/xrdp/xorg/X11R7.6/
    ./buildx.sh ${INSTALLX11RDPDIR}
    rm -f /usr/local/bin/X11rdp
    ln -s ${INSTALLX11RDPDIR}/bin/X11rdp /usr/local/bin/X11rdp
    sleep 3
    # activate xrdp and check the keys
    cp ${INSTALLXRDPDIR}/etc/xrdp/xrdp.sh ${INSTALLXRDPDIR}/etc/xrdp/xrdp.sh.changed
    set +x; echo 'Press Enter and change the paths in '${INSTALLXRDPDIR}'/etc/xrdp/xrdp.sh.changed to the places on '${INSTALLXRDPDIR}' .'; set -x
    read
    vim ${INSTALLXRDPDIR}/etc/xrdp/xrdp.sh.changed
    rm -f /etc/init.d/xrdp.sh
    cp ${INSTALLXRDPDIR}/etc/xrdp/xrdp.sh.changed /etc/init.d/xrdp.sh
    chmod 744 /etc/init.d/xrdp.sh
    update-rc.d xrdp.sh defaults
    ls -l ${INSTALLXRDPDIR}/etc/xrdp/rsakeys.ini 
    sleep 3

else
    # compile x11rdp (this takes the most time of this script)
    set +x; echo; echo -n "Should XORGRDP be compiled to use on XRDP later - this will take some time (y/*) ? "
    read USERINPUT
    set -x
    if [ $USERINPUT == y ] && [ ${XRDPPREFIX} == '' ]
    then
        set +x; echo; echo -n "OK, COMPILING XORGRDP now. THIS WILL TAKE SOME EXTRA TIME."; sleep 3; set -x
        cd /root/xrdp/neutrinolabs
        wget https://github.com/neutrinolabs/xorgxrdp/releases/download/v0.2.4/xorgxrdp-0.2.4.tar.gz
        tar xvfz xorgxrdp-0.2.4.tar.gz
        ./bootstrap
        ./configure
        make && make install
        sleep 3
    else
        set +x; echo; echo "OK, X11RDP and XORGRDP will NOT COMPILED now."; sleep 3; echo; set -x
    fi
fi

# download and configure the source of pulseaudio
apt-get -y install libjson-c-dev libsndfile1-dev libspeex-dev libspeexdsp-dev
apt-get -y install libltdl-dev libcap-dev
cd /tmp/
rm -rf /tmp/pulseaudio-10.0.tar.gz /tmp/pulseaudio-10.0/
wget https://freedesktop.org/software/pulseaudio/releases/pulseaudio-10.0.tar.gz
tar -xzf pulseaudio-10.0.tar.gz 
cd /tmp/pulseaudio-10.0/
./configure

# compile and install the xrdp sink for the rdp audio support
cd /root/xrdp/sesman/chansrv/pulse/
make
cp module-xrdp-sink.so /usr/lib/pulse-10.0/modules/
ls -l /usr/lib/pulse-10.0/modules/module-xrdp-sink.so
sleep 3

# change the path to the pulse script
set +x;  echo 'Press Enter and change the path of PULSE_SCRIPT to '${INSTALLXRDPDIR}'/etc/xrdp/pulse/default.pa .'; set -x
read
vim ${INSTALLXRDPDIR}/etc/xrdp/sesman.ini

# configure the system to use only xrdp sink
echo 'pcm.pulse {
type pulse
}
ctl.pulse {
type pulse
}
pcm.!default {
type pulse
}
ctl.!default {
type pulse
}
' > /etc/asound.conf
sleep 3
mv /etc/pulse/default.pa /root/default.pa.original
cp ${INSTALLXRDPDIR}/etc/xrdp/pulse/default.pa /etc/pulse/default.pa
sleep 3

# create the logrotate definitions
echo '/var/log/xrdp-sesman.log {
	daily
	missingok
	rotate 7
	ifempty
	postrotate
		echo kill -HUP `cat /var/run/xrdp-sesman.pid`
	endscript
	compress
	delaycompress
	create
} ' > /etc/logrotate.d/xrdp-sesman
chmod 644 /etc/logrotate.d/xrdp-sesman

# create the logrotate definitions
echo '/var/log/xrdp.log {
	daily
	missingok
	rotate 7
	ifempty
	postrotate
		echo kill -HUP `cat /var/run/xrdp.pid`
	endscript
	compress
	delaycompress
	create
} ' > /etc/logrotate.d/xrdp
chmod 644 /etc/logrotate.d/xrdp

# install vncserver for using Xvnc
apt-get -y install tigervnc-standalone-server 

# enable xrdp
mkdir -p '${INSTALLXRDPDIR}'/var/run/
systemctl enable xrdp-sesman
systemctl enable xrdp

# reboot and informations
set +x; echo '
Now press Enter to REBOOT and try XRDP manually first with the commands in two consoles:

   systemctl stop xrdp
   ps awux | grep xrdp | grep -v grep
   '${INSTALLXRDPDIR}'/sbin/xrdp -n
   '${INSTALLXRDPDIR}'/sbin/xrdp-sesman -n
   
Later setup the default configurations:

	'${INSTALLXRDPDIR}'/etc/xrdp/sesman.ini
	'${INSTALLXRDPDIR}'/etc/xrdp/xrdp.ini
  
'; set -x

read
reboot

```

Maybe nasm is not necessary for using xrdp with Xvnc.
The following screenshot shows the CPU problem, with the Microsoft RDP-Client for macOS from: https://itunes.apple.com/de/app/microsoft-remote-desktop-8-0/id715768417?mt=12

![screenshot](https://user-images.githubusercontent.com/9142382/36490482-a4acdc12-1728-11e8-8171-06627b595ad1.png)

If someone really would change the source so, that xrdp can use more CPU threads - that will be nice.

Maybe an better way can be, that xrdp is creating lesser jpeg quality on the often changed areas to reduce cpu power.

Best regards,

Thomas

**Comment by jsorg71** [comment]
Can you try the Xorg driver backend.  It looks like you do build it.  None of the SSE code is used with X11rdp and Xvnc backends.  Xvnc - xrdp - MSTSC will use RLE encoding only.

**Comment by metalefty** [comment]
One important thing, MS official RDP client for Mac doesn't use RemoteFX when xrdp is a RDP server so far.

**Comment by tm-dd** [comment]
Dear metalefty,

thank you for the information.
It looks so, that by using Xvnc on xrdp the clients **xfreerdp** and **rdesktop** are not using RemoteFX, also.

I tried the following commands on macOS:

   rdesktop -f -z -r sound:local SERVER
   xfreerdp /v:SERVER /rfx /rfx-mode:video /sound:latency:100 /f

Both commands are working, but not better than the MS RDP client. Strangely, with free RDP clients VLC needs more CPU power on the server side. The new screenshots will show that. 

If you see a mistake with the options of the RDP clients, please inform me.

Best regards,

Thomas

![xfreerdp](https://user-images.githubusercontent.com/9142382/36528493-949b31c4-17b5-11e8-9db9-5a7cacd0ea5c.png)
![rdesktop](https://user-images.githubusercontent.com/9142382/36528494-94b300ec-17b5-11e8-9846-82dea8003cbb.png)

**Comment by tm-dd** [comment]
Hi jsorg71,

using the Module Xorg is unfortunately unusable on my installation.

After the login of the user "user" the process xrdp-sesman stops his working.

> root@dhcp059:~ # id user
> uid=1000(user) gid=1000(user) groups=1000(user),**5(tty)**,24(cdrom),25(floppy),29(audio),30(dip),44(video),46(plugdev),108(netdev),115(bluetooth),116(lpadmin),120(scanner)
> root@dhcp059:~ # 

> root@dhcp059:~ # ls -l /dev/tty8
> crw--w---- 1 root tty 4, 8 Feb 22 16:39 /dev/tty8
> root@dhcp059:~ # 

> root@dhcp059:~ # grep -v '^#' /etc/X11/Xwrapper.config
> allowed_users=anybody
> needs_root_rights=yes
> root@dhcp059:~ # 

> root@dhcp059:~# /opt/local/xrdp/xrdp_2018-02-21/sbin/xrdp-sesman -n
> starting sesman in foreground...
> sesman config:
> 	ListenAddress:            127.0.0.1
> 	ListenPort:               3350
> 	EnableUserWindowManager:  1
> 	UserWindowManager:        startwm.sh
> 	DefaultWindowManager:     startwm.sh
> 	AuthFilePath:             disabled
> Xvnc parameters:
> 	Parameter 00                   Xvnc
> 	Parameter 01                   -bs
> 	Parameter 02                   -nolisten
> 	Parameter 03                   tcp
> 	Parameter 04                   -localhost
> 	Parameter 05                   -dpi
> 	Parameter 06                   96
> X11rdp parameters:
> 	Parameter 00                   X11rdp
> 	Parameter 01                   -bs
> 	Parameter 02                   -nolisten
> 	Parameter 03                   tcp
> 	Parameter 04                   -uds
> XOrg parameters:
> 	Parameter 00                   Xorg
> 	Parameter 01                   -config
> 	Parameter 02                   xrdp/xorg.conf
> 	Parameter 03                   -noreset
> 	Parameter 04                   -nolisten
> 	Parameter 05                   tcp
> 	Parameter 06                   -logfile
> 	Parameter 07                   .xorgxrdp.%s.log
> security configuration:
> 	AllowRootLogin:       1
> 	MaxLoginRetry:        4
> 	AlwaysGroupCheck:     0
> 	TSUsersGroup:         44
> 	TSAdminsGroup:        44
> session configuration:
> 	MaxSessions:                 50
> 	X11DisplayOffset:            10
> 	KillDisconnected:            0
> 	IdleTimeLimit:               0
> 	DisconnectedTimeLimit:       0
> 	Policy:       0
> SessionVariables parameters:
>   Parameter 00                   PULSE_SCRIPT=/opt/local/xrdp/xrdp_2018-02-21/etc/xrdp/pulse/default.pa
> logging configuration:
> 	LogFile:       /opt/local/xrdp/xrdp_2018-02-21/var/log/xrdp-sesman.log
> 	LogLevel:      4
> 	EnableSyslog:  1
> 	SyslogLevel:   4
> [20180222-16:51:44] [DEBUG] libscp initialized
> [20180222-16:51:44] [INFO ] starting xrdp-sesman with pid 923
> [20180222-16:51:44] [INFO ] listening to port 3350 on 127.0.0.1
> [20180222-16:52:11] [INFO ] A connection received from 127.0.0.1 port 39250
> [20180222-16:52:11] [INFO ] ++ created session (access granted): username user, ip 172.17.128.11:57850 - socket: 12
> [20180222-16:52:11] [INFO ] starting Xorg session...
> [20180222-16:52:11] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5910)
> [20180222-16:52:11] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:0)
> [20180222-16:52:11] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5911)
> [20180222-16:52:11] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:0)
> [20180222-16:52:11] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5912)
> [20180222-16:52:11] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6012)
> [20180222-16:52:11] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6212)
> [20180222-16:52:11] [INFO ] calling auth_start_session from pid 940
> [20180222-16:52:11] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
> [20180222-16:52:11] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
> [20180222-16:52:11] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
> [20180222-16:52:11] [INFO ] Xorg :12 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log  
> 
> X.Org X Server 1.19.2
> Release Date: 2017-03-02
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 4.9.0-4-amd64 x86_64 Debian
> Current Operating System: Linux dhcp059 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64
> Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.9.0-5-amd64 root=UUID=4bec6596-6ed4-4abc-b8de-4fedd3f4a7cc ro quiet
> Build Date: 16 October 2017  08:19:45AM
> xorg-server 2:1.19.2-1+deb9u2 (https://www.debian.org/support) 
> Current version of pixman: 0.34.0
> 	Before reporting problems, check http://wiki.x.org
> 	to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
> 	(++) from command line, (!!) notice, (II) informational,
> 	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: ".xorgxrdp.12.log", Time: Thu Feb 22 16:52:11 2018
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> (EE) 
> Fatal server error:
**> (EE) xf86OpenConsole: Cannot open virtual console 2 (Permission denied)**
> (EE) 
> (EE) 
> Please consult the The X.Org Foundation support 
> 	 at http://wiki.x.org
>  for help. 
> (EE) Please also check the log file at ".xorgxrdp.12.log" for additional information.
> (EE) 
> (EE) Server terminated with error (1). Closing log file.
> [20180222-16:52:21] [ERROR] X server for display 12 startup timeout
> [20180222-16:52:21] [CORE ] waiting for window manager (pid 941) to exit
> chansrv::main: using log file [/home/user/.local/share/xrdp/xrdp-chansrv.12.log]
> [20180222-16:52:21] [CORE ] main: app started pid 945(0x000003b1)
> [20180222-16:52:21] [INFO ] main: DISPLAY env var set to :12.0
> [20180222-16:52:21] [INFO ] main: using DISPLAY 12
> [20180222-16:52:21] [INFO ] channel_thread_loop: thread start
> [20180222-16:52:22] [ERROR] X server for display 12 startup timeout
> [20180222-16:52:22] [ERROR] another Xserver might already be active on display 12 - see log
> [20180222-16:52:22] [DEBUG] aborting connection...
> [20180222-16:52:22] [CORE ] window manager (pid 941) did exit, cleaning up session
> [20180222-16:52:22] [INFO ] calling auth_stop_session and auth_end from pid 940
> [20180222-16:52:22] [INFO ] term_signal_handler: got signal 15
> [20180222-16:52:22] [DEBUG] cleanup_sockets:
> [20180222-16:52:22] [INFO ] channel_thread_loop: g_term_event set
> [20180222-16:52:22] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_socket_12
> xrdp-chansrv [3191286596]: scard_deinit:
> chansrv:smartcard_pcsc [3191286596]: scard_pcsc_deinit:
> [20180222-16:52:22] [INFO ] channel_thread_loop: thread stop
> [20180222-16:52:22] [INFO ] main: app exiting pid 945(0x000003b1)
> [20180222-16:52:22] [DEBUG] cleanup_sockets: failed to delete /tmp/.xrdp/xrdp_chansrv_socket_12
**> [20180222-16:52:22] [INFO ] ++ terminated session:  username user, display :12.0, session_pid 940, ip 172.17.128.11:57850 - socket: 12**
> 

And on the log of the xrdp is written:

> root@dhcp059:~# /opt/local/xrdp/xrdp_2018-02-21/sbin/xrdp -n
> logging configuration:
> 	LogFile:       /opt/local/xrdp/xrdp_2018-02-21/var/log/xrdp.log
> 	LogLevel:      4
> 	EnableSyslog:  1
> 	SyslogLevel:   4
> [20180222-16:51:56] [INFO ] starting xrdp with pid 938
> [20180222-16:51:56] [INFO ] listening to port 3389 on 0.0.0.0
> [20180222-16:52:03] [INFO ] Socket 12: AF_INET connection received from 172.17.128.11 port 57850
> [20180222-16:52:03] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)
> [20180222-16:52:03] [DEBUG] Closed socket 12 (AF_INET 172.17.1.131:3389)
> [20180222-16:52:03] [INFO ] Using default X.509 certificate: /opt/local/xrdp/xrdp_2018-02-21/etc/xrdp/cert.pem
> [20180222-16:52:03] [INFO ] Using default X.509 key file: /opt/local/xrdp/xrdp_2018-02-21/etc/xrdp/key.pem
> [20180222-16:52:03] [DEBUG] TLSv1.2 enabled
> [20180222-16:52:03] [DEBUG] TLSv1.1 enabled
> [20180222-16:52:03] [DEBUG] TLSv1 enabled
> [20180222-16:52:03] [DEBUG] Security layer: requested 11, selected 1
> ssl_tls_accept: TLS connection accepted
> colorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp)
> [20180222-16:52:05] [INFO ] connected client computer name: rabbit.mpipks-d
> postBeta2ColorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp 0xca02 15bpp 0xca03 16bpp 0xca04 24bpp)
> highColorDepth 0x0018 (0x0004 4bpp 0x0008 8bpp 0x000f 15bpp 0x0010 16 bpp 0x0018 24bpp)
> supportedColorDepths 0x000f (0x0001 24bpp 0x0002 16bpp 0x0004 15bpp 0x0008 32bpp)
> earlyCapabilityFlags 0x05a1 (0x0002 want32)
> got client client connection type 0x00000007
> xrdp_sec_process_mcs_data_CS_SECURITY:
>   client supports 40 bit encryption
>   client supports 128 bit encryption
>   client supports 56 bit encryption
>   client supports fips encryption
> error unknown xrdp_sec_process_mcs_data tag 0xc006 size 8
> error unknown xrdp_sec_process_mcs_data tag 0xc00a size 8
> xrdp_sec_out_mcs_data: using no security
> xrdp_load_keyboard_layout: keyboard_type [4] keyboard_subtype [0]
> xrdp_load_keyboard_layout: model [] variant [] layout [de] options []
> [20180222-16:52:05] [INFO ] TLS connection established from 172.17.128.11 port 57850: TLSv1.2 with cipher ECDHE-RSA-AES256-SHA
> xrdp_caps_process_order: bitmap cache v3 supported
> xrdp_caps_process_pointer: client supports new(color) cursor
> xrdp_process_offscreen_bmpcache: support level 0 cache size 0 MB cache entries 0
> unknown in xrdp_caps_process_confirm_active 27
> unknown in xrdp_caps_process_confirm_active 25
> xrdp_caps_process_surface_cmds:
>   cmdFlags 0x00000052
> xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
> xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
> xrdp_process_capset_rail: rail_support_level 3
> xrdp_process_capset_window wnd_support_level 2 wnd_num_icon_caches 3 wnd_num_icon_cache_entries 12
> yeah, up_and_running
> xrdp:xrdp_bitmap [3191269650]: xrdp_bitmap_create: noorders
> [20180222-16:52:05] [DEBUG] xrdp_000003ab_wm_login_mode_event_00000001
> xrdp:xrdp_mm [3191269657]: xrdp_mm_create: bpp 24 mcs_connection_type 7 jpeg_codec_id 0 v3_codec_id 0 rfx_codec_id 3 h264_codec_id 0
> [20180222-16:52:05] [INFO ] Loading keymap file /opt/local/xrdp/xrdp_2018-02-21/etc/xrdp/km-00000407.ini
> [20180222-16:52:05] [WARN ] local keymap file for 0x00000407 found and doesn't match built in keymap, using local keymap file
> xrdp_wm_login_mode_changed: login_mode is 0
> in xrdp_wm_init: 
>    xrdp_wm_init: no autologin / auto run detected, draw login window
> xrdp:xrdp_cache [3191269669]: xrdp_cache_add_bitmap: reset detected cache_id 2
> xrdp:xrdp_cache [3191269669]: xrdp_cache_add_bitmap: reset detected cache_id 1
> out xrdp_wm_init: 
> xrdp_wm_login_mode_changed: login_mode is 1
> xrdp_wm_login_mode_changed: login_mode is 2
> [20180222-16:52:11] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
> connecting to sesman ip 127.0.0.1 port 3350
> [20180222-16:52:11] [INFO ] xrdp_wm_log_msg: sesman connect ok
> sesman connect ok
> [20180222-16:52:11] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
> sending login info to session manager, please wait...
> [20180222-16:52:11] [DEBUG] return value from xrdp_mm_connect 0
> xrdp_wm_login_mode_changed: login_mode is 3
> [20180222-16:52:11] [INFO ] xrdp_wm_log_msg: login successful for display 12
> login successful for display 12
> loaded module 'libxup.so' ok, interface size 8456, version 3
> [20180222-16:52:11] [DEBUG] xrdp_wm_log_msg: started connecting
> started connecting
> [20180222-16:52:15] [DEBUG] Closed socket 19 (AF_UNIX)
> [20180222-16:52:19] [DEBUG] Closed socket 19 (AF_UNIX)
> [20180222-16:52:22] [DEBUG] Closed socket 19 (AF_UNIX)
> [20180222-16:52:26] [DEBUG] Closed socket 19 (AF_UNIX)
> ...

Maybe this is a misconfiguration of me. But I could not find the problem.
A local "startx" as "user" works fine.

Best regards and many thanks for your time,

Thomas

**Comment by jsorg71** [comment]
What distro is this?
It looks like you build script is doing a lot of un needed things.  First I think you need to get Xorg backend working.  All future improvements will be using that.

**Comment by tm-dd** [comment]
Dear jsorg71,

I'm sorry, I was very busy the last days.

I'm using Debian 9 on a real hardware and on a virtual machine for testing.

And yes the script is doing some not necessary things.
I will trying now the hand made compilation and write my results later.
