### ISSUE TITLE
Unable to move windows about

### ISSUE THREAD

**Issue by JamesKBowler** [neutrinolabs/xrdp#1054]
Hi,

**Environment Setup**
Latest updates performed - yes
On a fresh installation of Ubuntu desktop 16.04 and following these instructions...
https://askubuntu.com/questions/592537/can-i-access-ubuntu-from-windows-remotely

I am unable to move any windows on XRPD session from Windows. Whenever I try to select a window its just beeps?

How do I fix this?

Thank you

James

**Comment by moobyfr** [comment]
Ubuntu Xenial ships a xrdp version too old: 0.6.1 
0.7 was released in 2009, so your version is 10 years old!
Please upgrade to a newer version before reporting bugs

**Comment by metalefty** [comment]
Try newer version.
