### ISSUE TITLE
GUI shutdown doesn't work (and dialog box differs)

### ISSUE THREAD

**Issue by ben-cohen** [neutrinolabs/xrdp#1055]
In Linux Mint (17 and 18.2, and apparently [Ubuntu 10.14](https://askubuntu.com/questions/276535/how-to-shutdown-a-server-thats-configured-to-use-xrdp-for-remote-desktop-ubunt)) the GUI shutdown button doesn't work.  Yet the expected behaviour is seen when running from a GUI session logged in from the console.

Steps to reproduce:
1. Connect to an xrdp server running Cinnamon (or GNOME, presumably) and log in. Open the system menu and press "Quit / Shut down the computer".
2. Press "Shut down" or wait for the shutdown to happen.

Expected behaviour:
1. Dialog box says "This system will be automatically shut down in 60 seconds" and has buttons to "Restart", "Hibernate", etc., as well as "Shut down" (immediately) or "Cancel".
2. Computer shuts down.

Observed behaviour:
1. Dialog box says "This system will be automatically shut down in 60 seconds" but the only button is "Cancel".
2. Session is logged out but computer does not shut down.

**Comment by metalefty** [comment]
It looks like a Polkit issue. For some reasons, your xrdp session is out of Polkit.

**Comment by ben-cohen** [comment]
See also systemd/systemd#2833 which asks to be able to create virtual graphical sessions/seats on demand, and a [comment](https://github.com/systemd/systemd/issues/2833#issuecomment-213464809) says PolicyKit relies on logind so it looks like a systemd problem - or at least they are best-placed to solve it.  Unfortunately the issue was closed by their developers.

**Comment by ben-cohen** [comment]
Note to self: I wonder if it would be possible to fix this by creating a device driver for a fake/dummy graphics card?

**Comment by metalefty** [comment]
So do you mean this issue is different from such as #2298 and have different solution? If so, I will reopen.

**Comment by matt335672** [comment]
@ben-cohen - based on the OP, this still looks like a polkit issue to me.

Have a look at https://github.com/matt335672/pk-local It may help you work out what's going on here.

**Comment by ben-cohen** [comment]
@matt335672 Thank you, that looks useful.

@metalefty I hadn't seen that issue - the fix there is good, thank you.

I was thinking an alternative might be to create a device to [base](https://wiki.ubuntu.com/MultiseatTeam/Instructions) the session on, so that it is created by logind with a proper seat, as shown by `loginctl list-sessions`.  That might also solve any other problems caused by the GUI session not having a seat.  But it would be a lot more complicated (if it's even possible) so it's beyond the scope of this issue. :slightly_smiling_face:
