### ISSUE TITLE
Software rendering notification is displayed on log in to Cinnamon

### ISSUE THREAD

**Issue by ben-cohen** [neutrinolabs/xrdp#1056]
When you connect to xrdp on Linux Mint Cinnamon (17 or 18.2) it displays a notification:

> Running in software rendering mode
>
> Cinnamon is currently running without video hardware acceleration and, as a result, you may observe much higher than normal CPU usage.
> There could be a problem with your drivers or some other issue.  For the best experience, it is recommended that you only use this mode for troubleshooting purposes.

Can someone confirm whether this is expected?  (I wouldn't be surprised!)

Meanwhile, the nicest way [to turn it off ](https://unix.stackexchange.com/questions/295921/how-do-i-turn-off-the-running-in-software-rendering-mode-warning)is to add this line to /etc/xrdp/startwm.sh with the other environment variables:

```
export CINNAMON_2D=1
```

**Comment by jsorg71** [comment]
Thanks for the note.
I've been working on getting hardware accel in xrdp, see #1029

**Comment by ben-cohen** [comment]
Then it is expected for now so I'll close the issue - thanks.
