### ISSUE TITLE
No xorgxrdp log

### ISSUE THREAD

**Issue by Suncatcher** [neutrinolabs/xrdp#1058]
I have no .xorgxrdp.%s.log on my system thus cannot check if my connection utilize RemoteFX.

**Comment by metalefty** [comment]
First of all, let me know basic informations.
* distro
* xrdp version
* xorgxrdp version 

And make sure you're using xorgxrdp.  Then find `-config xrdp/xorg.log` line, that's the instance of xrgxrdp. You'll see `-logfile .xorgxrdp.%s.log` in the line. The log can be found in your home directory.
```
$ ps uxaww | grep Xorg
Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
```

Also, you can see the Xorg arguments in `xrdp-sesman.log`.
```
[20180307-00:10:30] [INFO ] starting Xorg session...
[20180307-00:10:31] [INFO ] calling auth_start_session from pid 70868
[20180307-00:10:31] [INFO ] Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log  
[20180307-00:10:31] [CORE ] waiting for window manager (pid 70870) to exit
[20180307-09:50:09] [INFO ] A connection received from ::1 port 56733
```

**Comment by Suncatcher** [comment]
distro
**Xubuntu 17.10**
xrdp version
**0.9.1**
xorgxrdp version
**0.9.1-9**

`ps uxaww | grep` Xorg gives
xoob       1415  0.2  2.2 352736 89852 ?        Sl   10:08   0:02 /usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp

I don't see the `-logfile` addition

**Comment by metalefty** [comment]
Okay, I remember Debian intentionally disables the log. Need to enable it again.
I don't have Debian/Ubuntu VM right now. Give me time.

Also, I think RemoteFX status should be logged `xrdp.log`, too. I'll do it in future version.

**Comment by Suncatcher** [comment]
Finally I got RFX capture :)

    [   102.423] rdpClientConProcessMsgClientInfo: got RFX capture

And got the working log. But I had to upgrade to 0.9.5 for that. Closing the issue.
