### ISSUE TITLE
XRDP does throw an error after latest updates of Raspbian (Debian 9)

### ISSUE THREAD

**Issue by welljsjs** [neutrinolabs/xrdp#1062]
```
[DEBUG] libscp initialized
[20180316-13:12:52] [INFO ] starting xrdp-sesman with pid 3986
[20180316-13:12:52] [INFO ] listening to port 3350 on 127.0.0.1
[20180316-13:12:55] [INFO ] A connection received from ::1 port 56282
*** Error in `xrdp-sesman': free(): invalid next size (fast): 0x01cdef98 ***
Aborted
```

__XRDP-Version:__ 0.9.1

This is the error I get after starting xrdp-sesman with the *n*-parameter (in foreground, same in background). 

This error only occurs after the latest updates of Raspbian. I tried to reinstall xrdp and tightvnc4server.

Any help is highly appreciated!

Thanks in advance.

**Comment by welljsjs** [comment]
Not solved, but I installed the latest version via Strecht-backports.

**Comment by metalefty** [comment]
Can you try the latest version? If the issue doesn't occur with the latest version, you should report the issue to distro packager.

**Comment by welljsjs** [comment]
Reporting to distro packer. Thanks.
