### ISSUE TITLE
$PATH is incorrect while using XRDP

### ISSUE THREAD

**Issue by Abinayasandhiya** [neutrinolabs/xrdp#1065]
Hi,

We are using XRDP on Our RHEL6 machine.
Please find below details about our machine:

```
[root@xxx]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)
[root@xxx]$ rpm -qa | grep xrdp
xrdp-0.6.1-4.el6.x86_64
[root@xxx]$ /etc/init.d/xrdp status
xrdp (pid  5095) is running...
xrdp-sesman (pid  5100) is running...
```

In PuTTY my $PATH is like below:
```
[root@xxx]$ echo $PATH
/usr/lib64/qt-3.3/bin:/opt/EE_XX/bin/:/opt/APTOdevel/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/opt/bin:/opt/UsageModel:/root/bin
```

When Our user try to access the server using XRDP $PATH is different so we are facing some environment issue.
Please find below attachment for better understanding.

![capture](https://user-images.githubusercontent.com/31726216/37597645-02ed81be-2ba6-11e8-83c3-2cfab2657754.JPG)

Can anyone help me it would be grateful.

**Comment by metalefty** [comment]
You can reset your PATH by editing `startwm.sh` as you like.

**Comment by Abinayasandhiya** [comment]
Hi,

I have edit the below line in startwm.sh but s

**Comment by metalefty** [comment]
Can you show me current your startwm.sh?

**Comment by Abinayasandhiya** [comment]
Please find below file which i got once i installed XRDP:

[root@XXX xrdp]$ cat startwm.sh
#!/bin/sh

# if xinitrc exists use it instead, it should load user prefferences
# including desktop environment specified in /etc/sysconfig/desktop
if [ -f /etc/X11/xinit/xinitrc ]
then
    . /etc/X11/xinit/xinitrc
    exit 0
fi

# change the order in line below to run to run whatever window manager you
# want, default to kde

SESSIONS="gnome-session blackbox fluxbox startxfce4 startkde xterm"

#start the window manager
wm_start()
{
  for WindowManager in $SESSIONS
  do
    which $WindowManager
    if test $? -eq 0
    then
      echo "Starting $WindowManager"
      $WindowManager
      return 0
    fi
  done
  return 0
}

#Execution sequence for interactive login shell
#Following pseudo code explains the sequence of execution of these files.
#execute /etc/profile
#IF ~/.bash_profile exists THEN
#    execute ~/.bash_profile
#ELSE
#    IF ~/.bash_login exist THEN
#        execute ~/.bash_login
#    ELSE
#        IF ~/.profile exist THEN
#            execute ~/.profile
#        END IF
#    END IF
#END IF
pre_start()
{
  if [ -f /etc/profile ]
  then
    . /etc/profile
  fi
  if [ -f ~/.bash_profile ]
  then
    . ~/.bash_profile
  else
    if [ -f ~/.bash_login ]
    then
      . ~/.bash_login
    else
      if [ -f ~/.profile ]
      then
        . ~/.profile
      fi
    fi
  fi
  return 0
}

#When you logout of the interactive shell, following is the
#sequence of execution:
#IF ~/.bash_logout exists THEN
#    execute ~/.bash_logout
#END IF
post_start()
{
  if [ -f ~/.bash_logout ]
  then
    . ~/.bash_logout
  fi
  return 0
}

#. /etc/environment
#export PATH=$PATH
#export LANG=$LANG

# change PATH to be what your environment needs usually what is in
# /etc/environment
#PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
#export PATH=$PATH

# for PATH and LANG from /etc/environment
# pam will auto process the environment file if /etc/pam.d/xrdp-sesman
# includes
# auth       required     pam_env.so readenv=1

pre_start
wm_start
post_start

exit 1

**Comment by Abinayasandhiya** [comment]
Hi,

I don't know why some letter are getting bold i have attached the file.
PFA.

[startwm.sh.txt](https://github.com/neutrinolabs/xrdp/files/1828069/startwm.sh.txt)

**Comment by Abinayasandhiya** [comment]
One more information, RHEL7 XRDP is setting PATH correctly.
Issue is only on RHEL6.

**Comment by metalefty** [comment]
Surround with ``` or ~~~ when you paste config or log. If massively long, attach is better.

**Comment by Abinayasandhiya** [comment]
Yes, Can i give startwm.sh file again.

**Comment by metalefty** [comment]
Maybe xrdp on RHEL7 has different startwm.sh from RHEL6's. What about bring it from RHEL7?

**Comment by Abinayasandhiya** [comment]
Yes, I guess you are right.

I could see some difference in "/etc/X11/xinit/xinitrc-common" file of RHEL 6 and RHEL 7.

RHEL 7 the file is like below:

```# Copyright (C) 1999 - 2004 Red Hat, Inc. All rights reserved. This
# copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the
# GNU General Public License version 2.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# xinitrc-common
#
# This is common code shared by both Xsession and xinitrc scripts.  Be sure
# to take this into account when fixing bugs or adding new functionality.

# Set up i18n environment
if [ -r /etc/profile.d/lang.sh ]; then
  . /etc/profile.d/lang.sh
fi

**[ -r $HOME/.profile ] && . $HOME/.profile**

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
userxkbmap=$HOME/.Xkbmap

sysresources=/etc/X11/Xresources
sysmodmap=/etc/X11/Xmodmap
sysxkbmap=/etc/X11/Xkbmap

# merge in defaults
[ -r "$sysresources" ] && xrdb -nocpp -merge "$sysresources"
[ -r "$userresources" ] && xrdb -merge "$userresources"

# merge in keymaps
if [ -r "$sysxkbmap" ]; then
    setxkbmap $(cat "$sysxkbmap")
    XKB_IN_USE=yes
fi

if [ -r "$userxkbmap" ]; then
    setxkbmap $(cat "$userxkbmap")
    XKB_IN_USE=yes
fi

# xkb and xmodmap don't play nice together
if [ -z "$XKB_IN_USE" ]; then
    [ -r "$sysmodmap" ] && xmodmap "$sysmodmap"
    [ -r "$usermodmap" ] && xmodmap "$usermodmap"
fi

unset XKB_IN_USE

# run all system xinitrc shell scripts.
for file in /etc/X11/xinit/xinitrc.d/* ; do
        . $file
done

# Prefix launch of session with ssh-agent if available and not already running.
SSH_AGENT=
if [ -z "$SSH_AGENT_PID" ] && [ -x /usr/bin/ssh-agent ]; then
    if [ "x$TMPDIR" != "x" ]; then
        SSH_AGENT="/usr/bin/ssh-agent /bin/env TMPDIR=$TMPDIR"
    else
        SSH_AGENT="/usr/bin/ssh-agent"
  fi
fi

CK_XINIT_SESSION=
if [ -z "$XDG_SESSION_COOKIE" ] && [ -x /usr/bin/ck-xinit-session ]; then
    CK_XINIT_SESSION="/usr/bin/ck-xinit-session"
fi

**Comment by Abinayasandhiya** [comment]
RHEL 6 the same file is like below:

#!/bin/bash
# Copyright (C) 1999 - 2004 Red Hat, Inc. All rights reserved. This
# copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the
# GNU General Public License version 2.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# xinitrc-common
#
# This is common code shared by both Xsession and xinitrc scripts.  Be sure
# to take this into account when fixing bugs or adding new functionality.

# Set up i18n environment
  . /etc/profile.d/lang.sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
userxkbmap=$HOME/.Xkbmap

sysresources=/etc/X11/Xresources
sysmodmap=/etc/X11/Xmodmap
sysxkbmap=/etc/X11/Xkbmap

# merge in defaults
[ -r "$sysresources" ] && xrdb -nocpp -merge "$sysresources"
[ -r "$userresources" ] && xrdb -merge "$userresources"

# merge in keymaps
if [ -r "$sysxkbmap" ]; then
    setxkbmap $(cat "$sysxkbmap")
    XKB_IN_USE=yes
fi

if [ -r "$userxkbmap" ]; then
    setxkbmap $(cat "$userxkbmap")
    XKB_IN_USE=yes
fi

# xkb and xmodmap don't play nice together
if [ -z "$XKB_IN_USE" ]; then
    [ -r "$sysmodmap" ] && xmodmap "$sysmodmap"
    [ -r "$usermodmap" ] && xmodmap "$usermodmap"
fi

unset XKB_IN_USE

# run all system xinitrc shell scripts.
for file in /etc/X11/xinit/xinitrc.d/* ; do
        . $file
done

# Prefix launch of session with ssh-agent if available and not already running.
SSH_AGENT=
if [ -x /usr/bin/ssh-agent -a -z "$SSH_AGENT_PID" ]; then
    if [ "x$TMPDIR" != "x" ]; then
        SSH_AGENT="/usr/bin/ssh-agent /bin/env TMPDIR=$TMPDIR"
    else
        SSH_AGENT="/usr/bin/ssh-agent"
  fi
fi

CK_XINIT_SESSION=
if [ -x /usr/bin/ck-xinit-session -a -z "$XDG_SESSION_COOKIE" ]; then
    CK_XINIT_SESSION="/usr/bin/ck-xinit-session"
fi

"[ -r $HOME/.profile ] && . $HOME/.profile" line is missing in RHEL6 configuration file.

**Comment by Abinayasandhiya** [comment]
I couldn't see any startwm.sh file in RHEL 7.

``` [root@XXX xrdp]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
[root@XXX xrdp]$ ls
cert.pem         km-0000040b.ini  km-00000414.ini  km-00000807.ini  km-0000100c.ini  sesman.ini
key.pem          km-0000040c.ini  km-00000415.ini  km-00000809.ini  km-00010409.ini  xrdp.ini
km-00000407.ini  km-00000410.ini  km-00000416.ini  km-0000080c.ini  openssl.conf     xrdp_keyboard.ini
km-00000409.ini  km-00000411.ini  km-00000419.ini  km-00000813.ini  pulse
km-0000040a.ini  km-00000412.ini  km-0000041d.ini  km-00000816.ini  rsakeys.ini

**Comment by metalefty** [comment]
In RHEL7, startwm.sh is placed somewhere in libexec directory, named startwm-bash.sh.

**Comment by Abinayasandhiya** [comment]
Yes, its working thanks for all your help. I have another doubt can you clear that also.

**Comment by metalefty** [comment]
What? If your another issue is completely different from this topic, raise another github issue.

**Comment by Abinayasandhiya** [comment]
Ok. Thanks for all your help.

**Comment by Abinayasandhiya** [comment]
Issue has fixed by add the startwm.sh file of RHEL7.
Thanks metalefty for all you help:).
