### ISSUE TITLE
XRDP log file 

### ISSUE THREAD

**Issue by Abinayasandhiya** [neutrinolabs/xrdp#1066]
As per our user request they need to change XRDP log file from /var/log/xrdp-sesman.log to /var/log/xrdp/xrdp-sesman.log.

So I could found one sesman.ini file in /etc./xrdp which i can see below line:

```[Logging]
LogFile=/var/log/xrdp-sesman.log
LogLevel=DEBUG
EnableSyslog=0
SyslogLevel=DEBUG

I tried to change the LogFile path like

LogFile=/var/log/xrdp/xrdp-sesman.log

After made changes I tried to restart the xrdp service and i could see sesman service get failed like below:

```[root@XXX xrdp]$ /etc/init.d/xrdp restart
Stopping xrdp:                                             [  OK  ]
Stopping xrdp-sesman:                                      [  OK  ]
Starting xrdp:                                             [  OK  ]
Starting xrdp-sesman:                                      [FAILED]

Can anyone help me is there any way to change the log file PATH.

**Comment by metalefty** [comment]
Just in case, please also tell me your distro and xrdp version.

**Comment by Abinayasandhiya** [comment]
Please find below details:

[root@XXX xrdp]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)
[root@XXX xrdp]$ rpm -qa | grep xrdp
xrdp-0.6.1-4.el6.x86_64

**Comment by metalefty** [comment]
I'd say the version v0.6.1 is deprecated. I recommend you to switch v0.9.x.

I don't want to spending time on supporting v0.6.x but just for your information, running xrdp-sesman in foreground will show you some helpful information. You can run it in foreground by executing `xrdp-sesman -ns`.

**Comment by Abinayasandhiya** [comment]
Ok, Please let me know from where i can download XRDP v0.9

**Comment by Abinayasandhiya** [comment]
But we are using xrdp 0.9 on one of our RHEL 7 machine.

[root@XXX log]$ rpm -qa | grep xrdp
xrdp-0.9.5-1.el7.x86_64
xorgxrdp-0.2.5-3.el7.x86_64

Here also i could see log file under /var/log/xrdp.log and /var/log/xrdp-sesman.log.
Please can you let me know how i can change it.

**Comment by metalefty** [comment]
Do you mean you're failing to change log file path with xrdp 0.9.5 on RHEL7, too?

**Comment by Abinayasandhiya** [comment]
RHEL7 is working.
So I think i have to use xrdp v0.9 on RHEL6 also then all issue seems to be fixed.

Can you share some URL where we can download XRDP v0.9.

**Comment by metalefty** [comment]
You can use X11RDP-RH-Matic to build and install the latest xrdp. 
It supports RHEL6 (actually tested only on CentOS 6 not genuine RHEL6).

See also: https://github.com/metalefty/X11RDP-RH-Matic

**Comment by Abinayasandhiya** [comment]
Thanks we will check with xrdp 0.9 and raise another ticket if any issue
