### ISSUE TITLE
xrdp should create its xauthority file in /tmp/ same as gdm

### ISSUE THREAD

**Issue by gnshkl1** [neutrinolabs/xrdp#1069]
Due to some weird reason xrdp not able to create .Xauthority file in NFS mounted user home directory.
At that time xrdp should use Xauthority file from user runtime directory same as gdm do.

**Comment by moobyfr** [comment]
I'll have a look at it, can you give us a little more on your setup ? (I use xrdp on NFSv4 for 100+ students without known problem.)

**Comment by gnshkl1** [comment]
We are using NetApp for nfsv3

**Comment by gnshkl1** [comment]
Nfs server:netapp
Nfs client :Ubuntu 16.04x64 Japanese remix
Client tools:libpam-mount and nfs-common
 Attached screenshots of settings.
Also can you please provide your setup details of how you achieved same.
Let me know if anymore information you need.

**Comment by moobyfr** [comment]
you are mounting the user $HOME at login ? (i.e. you don't mount server:/home under /home directly)

**Comment by gnshkl1** [comment]
I have tried both, mounting at Pam session, and also tried static mounting
before user session

**Comment by gnshkl1** [comment]
Is there any problem with nfsv3 with xrdp?

**Comment by moobyfr** [comment]
Not xrdp itself, but creating a xauth file on NFS can be problematic if the server doesn't handle lock correctly (that's why I switched to nfsv4, locks are working properly).
 I looked at the code, the  ``XAUTHORITY`` variable is handled, it can be used to override the default value of ```~/.Xauthority ``` (GDM places Xauth file in ``/tmp/.xauthXXXXX```)
if you can export a value for XAUTHORITY for the used, it will be used.

**Comment by gnshkl1** [comment]
@moobyfr can you please provide how can we get user xauthority file from before running session .
because i have searched in /user/run/pid/Xauthority which is not there

**Comment by gnshkl1** [comment]
@moobyfr  why xrdp not using method such as gdm uses for example ,
gdm:-
 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3
xrdp:-
 /usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log

**Comment by metalefty** [comment]
xrdp supports multiple operating systems not only recent GNU/Linux.
So the path cannot be changed to `/run/user/UID/Xauthority` without considerations.

One possible candidate under `${socketdir}`.

**Comment by metalefty** [comment]
Too GNU/Linux specific idea.

**Comment by Lehmaning** [comment]
It seems that xrdp-sesman doesn't follow the ```XAUTHORITY``` variable on my computer. The xrdp session always got terminated immediately after logging in when I tried to force moving the annoying ```~/.Xauthority``` file to $XDG_RUNTIME_DIR or setting the ```XAUTHORITY``` variable. Then ```~/.Xauthority``` will still be created. I think this is definitely a unresolved issue, or even a bug.

**Comment by moobyfr** [comment]
Hello
There is no much configuration available for setting the xautority file: 
it's in the $HOME or in the place fixed by $XAUTHORITY
when I implemented it, the variable setting was working.
Can you verify that the variable is set for the user ? some PAM 
configuration needs to include pam_env to be able to set variable for 
the user, and so the XAUTHORITY variable

Emmanuel

**Comment by Lehmaning** [comment]
@moobyfr Setting the variable takes no efficient at all for my Arch Linux. Here's the log:
```
systemd[1]: Starting xrdp session manager...
xrdp-sesman[3098]: [INFO ] starting xrdp-sesman with pid 3098
systemd[1]: Started xrdp session manager.
xrdp-sesman[3098]: [INFO ] Socket 12: AF_INET6 connection received from ::1 port 33886
xrdp-sesman[3098]: [INFO ] Terminal Server Users group is disabled, allowing authentication
xrdp-sesman[3098]: [INFO ] ++ created session (access granted): username *username*, ip *hidden* 12
xrdp-sesman[3098]: [INFO ] starting Xorg session...
xrdp-sesman[3098]: [INFO ] Found X server running at /tmp/.X11-unix/X10
xrdp-sesman[3098]: [INFO ] Starting session: session_pid 3126, display :11.0, width 1364, height 768, bpp 24, client ip *hidden* 12, user name *username*
xrdp-sesman[3126]: [INFO ] [session start] (display 11): calling auth_start_session from pid 3126
xrdp-sesman[3098]: [ERROR] sesman_data_in: scp_process_msg failed
xrdp-sesman[3126]: pam_unix(xrdp-sesman:session): session opened for user *username*(uid=1000) by (uid=0)
xrdp-sesman[3098]: [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
xrdp-sesman[3126]: pam_env(xrdp-sesman:session): deprecated reading of user environment enabled
xrdp-sesman[3126]: [INFO ] Found X server running at /tmp/.X11-unix/X11
xrdp-sesman[3126]: [INFO ] Session started successfully for user *username* on display 11
xrdp-sesman[3126]: [INFO ] Session in progress on display 11, waiting until the window manager (pid 3127) exits to end the session
xrdp-sesman[3126]: [WARN ] Window manager (pid 3127, display 11) exited with non-zero exit code 1 and signal 0. This could indicate a window manager config problem
xrdp-sesman[3126]: [WARN ] Window manager (pid 3127, display 11) exited quickly (1 secs). This could indicate a window manager config problem
xrdp-sesman[3126]: [INFO ] Calling auth_stop_session and auth_end from pid 3126
xrdp-sesman[3126]: pam_unix(xrdp-sesman:session): session closed for user *username*
xrdp-sesman[3126]: [INFO ] Terminating X server (pid 3128) on display 11
xrdp-sesman[3126]: [INFO ] Terminating the xrdp channel server (pid 3134) on display 11
xrdp-sesman[3126]: [INFO ] X server on display 11 (pid 3128) returned exit code 0 and signal number 0
xrdp-sesman[3098]: [INFO ] Process 3126 has exited
xrdp-sesman[3098]: [INFO ] ++ terminated session:  username *username*, display :11.0, session_pid 3126, ip *hidden* 12
systemd[1]: Stopping xrdp session manager...
xrdp-sesman[3098]: [INFO ] sesman_main_loop: sesman asked to terminate
systemd[1]: xrdp-sesman.service: Deactivated successfully.
systemd[1]: Stopped xrdp session manager.
```
Xrdp would not start the session and wm normally until I removed the XAUTHORITY variable.

**Comment by matt335672** [comment]
@Lehmaning - where are you setting `XAUTHORITY`?

I suspect you're setting it in `.bashrc` or similar. This won't work as this file isn't read when the X server is started.

Does your system support [pam_env](https://linux.die.net/man/8/pam_env) ?

**Comment by Lehmaning** [comment]
> I suspect you're setting it in `.bashrc` or similar. This won't work as this file isn't read when the X server is started.
> 
> Does your system support [pam_env](https://linux.die.net/man/8/pam_env) ?

@matt335672 No, I set ```XAUTHORITY``` as a global environment variable in /etc/profile with the line ```export XAUTHORITY=/tmp/Xauthority```. Even more I set it again in ```/etc/xrdp/startwm.sh```, but it still didn't work as usual. Surely, I use Arch Linux so it must support pam_env. Should I set the variable by editing ```/etc/environment```?

**Comment by matt335672** [comment]
pam_env looks like it's part of the Arch core so it should be on your system.

I've got a Manjaro VM here. The file `/etc/pam.d/xrdp-sesman` contains this line:-

```
session     include     system-remote-login
```

The file `/etc/pam.d/system-remote-login` contains this line:-

```
session   include   system-login
```

The file `/etc/pam.d/system-login` contains this line:-

```
session    required   pam_env.so           user_readenv=1
```

So it looks like you should be able to set your XAUTHORITY in either `/etc/environment` or `~/.pam_environment`. More information can be found in [pam_env(8)](https://linux.die.net/man/8/pam_env) and [pam_env.conf(5)](https://linux.die.net/man/5/pam_env.conf).

**Comment by matt335672** [comment]
@Lehmaning - do you need any more input on this?

Thanks.

**Comment by Lehmaning** [comment]
> @Lehmaning - do you need any more input on this?
> 
> Thanks.

Sorry for replying so late. I'll create an new detailed issue if I freed up my time.

**Comment by matt335672** [comment]
Thanks.

When you open the new issue, please add a reference to this one using the string #1069 so we can follow the chain?

**Comment by Lehmaning** [comment]
OK, I will.
