### ISSUE TITLE
Does clipboard work in vnc-any session?

### ISSUE THREAD

**Issue by Adonai** [neutrinolabs/xrdp#1072]
Hi. Thanks for good RDP implementation.

Status:

* Client: Windows 7, mstsc
* Host: RHEL 7.3 tigervnc 1.8.0, xrdp 0.9.4

I connect via `vnc-any` type to an existing VNC session that I start with `vncserver :1`

I noticed that clipboard seems to be broken - I see it works Linux->Windows way, but not the Windows->Linux way.

No `xrdp-chansrv` process is forked from `xrdp-sesman`, nor do I see any activity in logs in `.local` and `/var/log/xrdp` when I copy anything.

Is this scenario supported? Can I somehow start `xrdp-chansrv` and point it to `sesman` socket?

**Comment by metalefty** [comment]
﻿﻿﻿﻿﻿It works Client->Server way, not Server->Client way for me.
