### ISSUE TITLE
why xrdp does not use freerdp,bugs in NeutrinoRDP  are no longer fixed.

### ISSUE THREAD

**Issue by zhonghesc** [neutrinolabs/xrdp#1075]
such as:
https://www.talosintelligence.com/vulnerability_reports/TALOS-2017-0337

**Comment by metalefty** [comment]
The reason why xrdp switched from FreeRDP to NeutrinoRDP (fork) is stability.

When we decided to fork FreeRDP, it may be 2012-2013, FreeRDP wasn't stable and makes drastic changes every day. We were tired to follow such changes. However, recent days, FreeRDP (2.0.0) seems to be stable. I personally think we should support both FreeRDP and NeutrinoRDP and provide users a choice which to use.

Regarding NeutrinoRDP, "no longer fixed" is not correct. It is our fork. Can be fixed.

**Comment by blackcrack** [comment]
Hi metalefty :)
Some answer's can you copy in a "FaQ" and be able to close,
therewith have you a Faq where the Peoples can read and you can linked every by closing :)

best regards
Blacky
