### ISSUE TITLE
gnome-shell session resize on reconnect not working

### ISSUE THREAD

**Issue by gnshkl1** [neutrinolabs/xrdp#1079]
client:-ubuntu 16.04 with freerdp 2.1
server:-vanilla-gnome-ubuntu16.04_x64
xrdp version:-0.9.5

scenario:-
1:-connect with 1024x768 resolution
2:-disconnect
3:-reconnect with 1920x1080 resolution

Note:-xrandr shows correct resolution but screen display in not updated to new resolution

**Comment by gnshkl1** [comment]
@jsorg71 attached screenshot
![gnome_res](https://user-images.githubusercontent.com/8046158/37861430-7fb13684-2f5f-11e8-902f-b8b8abf87b4f.png)

**Comment by metalefty** [comment]
Dup of #914.
