### ISSUE TITLE
new user addition in tsusers group not reflected in xrdp without xrdp service restart

### ISSUE THREAD

**Issue by gnshkl1** [neutrinolabs/xrdp#1080]
client:-ubuntu 16.04 with freerdp 2.1
server:-centos7_x64
xrdp version:-0.9.5

when new user added in tsusers group ,xrdp service need to be restarted to take effect of tsusers group
modification.
This should be dynamic.

**Comment by metalefty** [comment]
#1061 turned out that the issue for new users? If so, close the either one.

**Comment by metalefty** [comment]
@gnshkl1 Hello?

**Comment by gnshkl1** [comment]
@metalefty we can close this issue

**Comment by metalefty** [comment]
why?

**Comment by gnshkl1** [comment]
@metalefty this issue seems to be solved .
users are reflected in xrdp in running service.
#1061 needs to be fixed.
