### ISSUE TITLE
xrdp problem on CentOS

### ISSUE THREAD

**Issue by Suncatcher** [neutrinolabs/xrdp#1086]
As the @metalefty said xrdp certainly works with Gnome, I start this as a separate thread.
I have such logs on CentOS 7

```
Mar  4 09:06:52 localhost xrdp[1124]: (1124)(140033041733696)[INFO ] Socket 12: AF_INET connection received from 192.168.1.101 port 54800
Mar  4 09:06:52 localhost xrdp[2818]: (2818)(140033041733696)[INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
Mar  4 09:06:52 localhost xrdp[2818]: (2818)(140033041733696)[INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Mar  4 09:06:52 localhost xrdp[1124]: (1124)(140033041733696)[INFO ] Socket 12: AF_INET connection received from 192.168.1.101 port 54801
Mar  4 09:06:52 localhost xrdp[2819]: (2819)(140033041733696)[INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
Mar  4 09:06:52 localhost xrdp[2819]: (2819)(140033041733696)[INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Mar  4 09:06:52 localhost xrdp[2819]: (2819)(140033041733696)[INFO ] connected client computer name: ISIDA
Mar  4 09:06:52 localhost xrdp[2819]: (2819)(140033041733696)[INFO ] TLS connection established from 192.168.1.101 port 54801: TLSv1.2 with cipher AES256-GCM-SHA384
Mar  4 09:06:52 localhost xrdp[2819]: (2819)(140033041733696)[INFO ] Loading keymap file /etc/xrdp/km-00000419.ini
Mar  4 09:06:52 localhost xrdp[2819]: (2819)(140033041733696)[WARN ] local keymap file for 0x00000419 found and doesn't match built in keymap, using local keymap file
Mar  4 09:06:52 localhost xrdp-sesman[1098]: (1098)(140534459889792)[INFO ] A connection received from 127.0.0.1 port 44058
Mar  4 09:06:53 localhost xrdp[2819]: (2819)(140033041733696)[INFO ] xrdp_wm_log_msg: sesman connect ok
Mar  4 09:06:53 localhost xrdp-sesman[1098]: (1098)(140534459889792)[INFO ] ++ created session (access granted): username penny, ip 192.168.1.101:54801 - socket: 12
Mar  4 09:06:53 localhost xrdp-sesman[1098]: (1098)(140534459889792)[INFO ] starting Xorg session...
Mar  4 09:06:53 localhost xrdp[2819]: (2819)(140033041733696)[INFO ] xrdp_wm_log_msg: login successful for display 12
Mar  4 09:06:53 localhost xrdp-sesman[2822]: (2822)(140534459889792)[INFO ] calling auth_start_session from pid 2822
Mar  4 09:06:53 localhost xrdp-sesman[2825]: (2825)(140534459889792)[INFO ] Xorg :12 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
Mar  4 09:07:03 localhost xrdp-sesman[2822]: (2822)(140534459889792)[ERROR] X server for display 12 startup timeout
Mar  4 09:07:03 localhost xrdp-sesman[2822]: (2822)(140534459889792)[CORE ] waiting for window manager (pid 2824) to exit
Mar  4 09:07:03 localhost xrdp-sesman[2824]: (2824)(140534459889792)[ERROR] X server for display 12 startup timeout
Mar  4 09:07:03 localhost xrdp-sesman[2824]: (2824)(140534459889792)[ERROR] another Xserver might already be active on display 12 - see log
Mar  4 09:07:03 localhost xrdp-sesman[2822]: (2822)(140534459889792)[CORE ] window manager (pid 2824) did exit, cleaning up session
Mar  4 09:07:03 localhost xrdp-sesman[2822]: (2822)(140534459889792)[INFO ] calling auth_stop_session and auth_end from pid 2822
Mar  4 09:07:03 localhost xrdp-sesman[1098]: (1098)(140534459889792)[INFO ] ++ terminated session:  username penny, display :12.0, session_pid 2822, ip 192.168.1.101:54801 - socket: 1
```

Tried both @imc0 recommendations:

> I created the script called /usr/libexec/xrdp/startwm-local.sh containing the two lines (revised version:)
> #!/bin/sh
> exec dbus-launch --exit-with-x11 /usr/libexec/xrdp/startwm-bash.sh
and adding this file to sesman.ini

and also simple adding `/usr/lib/gnome-session/gnome-session-binary --session=gnome` to startwm.sh.

Nothing worked, still `another Xserver might already be active on display`...

Tried to disable X like `sudo systemctl enable multi-user.target --force`, but that didn't help. I do xrdp connection prior to any logins

![untitled](https://user-images.githubusercontent.com/6388034/37251868-5e8a8814-2520-11e8-8fd9-b99a137ecbb8.png) 
and get the same

![image](https://user-images.githubusercontent.com/6388034/36948352-75421cae-1fe2-11e8-8d14-24898191f78e.png)

**Comment by metalefty** [comment]
Can you login to the machine via SSH with user penny and run this command?

```
Xorg :12 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
```

The output gives us a hint why it fails.

**Comment by metalefty** [comment]
Just FYI, GNOME is working.

![2018-03-29 18 32 36](https://user-images.githubusercontent.com/941609/38081692-97dcce98-337f-11e8-8a03-799a2f3fb2a1.png)

**Comment by Suncatcher** [comment]
> Can you login to the machine via SSH with user penny and run this command?

Here is it 

    [penny@centy ~]$ Xorg :12 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
    
    X.Org X Server 1.19.3
    Release Date: 2017-03-15
    X Protocol Version 11, Revision 0
    Build Operating System:  3.10.0-693.17.1.el7.x86_64
    Current Operating System: Linux centy 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64
    Kernel command line: BOOT_IMAGE=/vmlinuz-3.10.0-693.21.1.el7.x86_64 root=/dev/mapper/centos-root ro crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet LANG=en_US.UTF-8
    Build Date: 07 March 2018  01:39:22PM
    Build ID: xorg-x11-server 1.19.3-11.el7_4.2
    Current version of pixman: 0.34.0
            Before reporting problems, check http://wiki.x.org
            to make sure that you have the latest version.
    Markers: (--) probed, (**) from config file, (==) default setting,
            (++) from command line, (!!) notice, (II) informational,
            (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
    (++) Log file: ".xorgxrdp.12.log", Time: Thu Mar 29 09:29:27 2018
    (==) Using config directory: "/etc/X11/xorg.conf.d"
    (==) Using system config directory "/usr/share/X11/xorg.conf.d"
    xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)

**Comment by Suncatcher** [comment]
Well?

**Comment by metalefty** [comment]
```
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
```

This doesn't occur with ordinary users. This is YOUR root cause but out of the scope of xrdp. If you solve the xf86EnableIOPorts error, everything will go fine.

**Comment by Suncatcher** [comment]
So what should be the probable troubleshooting steps? I googled but found nothing relevant.

**Comment by Suncatcher** [comment]
Can be closed. Reinstall solved the problem.
