### ISSUE TITLE
xrdp blank screen on raspberry pi

### ISSUE THREAD

**Issue by danmiller84** [neutrinolabs/xrdp#1088]
Been using xrdp for a few weeks without issue. However last week i 

`sudo apt-get update`

And all of a sudden, it has stopped working and i just get a blank screen when i try to log in. 

I have new to raspberry pi and command so apologise if I've missed something obvious. 

I have read loads of different articles from the internet on how to solve the issue but none of them work! 

Any help would be great - thanks in advance.

**Comment by jtmoderate876** [comment]
I have the same problem (blank screen) so I tried a clean install using 2018-04-18 version of raspbian and if I leave the user name and password pi / raspberry then it works (I have some trouble with a couple "root" permission apps but that's a different issue).

If I change the password then I can't log in via xrdp anymore.
if I change pw back to raspberry then xrdp works again.

I've tried changing the password first, then installing xrdp but that doesn't work.

**Comment by Xelosy** [comment]
Can confirm same problem. if i change to default password it works.  If i put a ! or a capital letter  in my password it dont work

**Comment by codyreed** [comment]
I just set this up on my RPI and when I enter the IP on my mac to connect, it brings up a blank dialog box in the top left corner with no text and an empty button. I hit enter or press the button, and it brings me to what I think should be the xrdp login, but entering my username and pw and hitting enter brings me right back to the first dialog box. There's no text at all, just the teal background and the boxes.

I am also running the 2018-04-18 4.14 version of raspbian with a changed username and password.

Will try reverting back to original password and username later.

**Comment by Spartacus1066** [comment]
This was driving me nuts, trying all solutions. For me, the login screen came, I logged in, and it was a blank screen with a mouse for my remote Pi connection.
The issue was the SESSION type defaulted to ... I forgot! The first option did not work when logging in Xvnc is the right one. Bingo, all is well now

**Comment by Deedikjupijn** [comment]
I have the same issue, when I try xorg it gives me a blank blue screen and doesnt work and when set it to Xvnc it does the same thing...

**Comment by matt335672** [comment]
@sebas202 - is this the same as #2060?

**Comment by hansratzinger** [comment]
I had the same problem. After logged in a blank screen, in my case it was a green one ;-) 
Thankfully I found the solution here: [https://www.reddit.com/r/raspberry_pi/comments/qw1cdw/comment/ib4cd2e/?utm_source=share&utm_medium=web2x&context=3](url)
You need to create another user. The Pi root user cannot RDP for whatever reason.

    `sudo adduser <username>`.
    Choose password
    Confirm password
    Hit enter for defaults
    Try RDP again with that login

**Comment by cartpauj** [comment]
`sudo deluser pi render` worked for me.
