### ISSUE TITLE
x11rdp is unreasonably slow

### ISSUE THREAD

**Issue by alandarev** [neutrinolabs/xrdp#109]
First of all, I understand that the issue is vague, and you would need more details. Thus I am asking for any suggestions and where do I dig more details.

Problem: sesman-X11rdp module is slow.
It takes around 1 minute to draw initial desktop, and then 30 seconds if I open a folder, or anything which involves significant image change.

That very unlikely due to internet limitations: I am able to upload/download files to the server at 1MB/s rate, and sesman-Xvnc works fine, but what I am looking into is get X11 work, not VNC.

Any ideas on why this might be happening? Thank you.

P.S. I have been using X11RDP-o-Matic as a wrapper script to install xrdp. Doing it by hands was beyond my knowledge

**Comment by metalefty** [comment]
I think this and #386 are same.
