### ISSUE TITLE
xrdp-sesrun only start session by Xvnc

### ISSUE THREAD

**Issue by yingque** [neutrinolabs/xrdp#1095]
Installed with X11rdp and Xvnc on my machine(ubuntu16.04).
I use `xrdp-sesrun localhost test test 1024 768 24` to start a session.  
I not find some information about it.    xrdp-sesrun just support Xvnc ??

**Comment by metalefty** [comment]
Yes.

**Comment by metalefty** [comment]
Solved by #1108.
