### ISSUE TITLE
RedHat 7.4 install/update issue

### ISSUE THREAD

**Issue by guleyupo** [neutrinolabs/xrdp#1099]
Update of RedHat fails or install of xrdp fails on the latest version of RedHat 7.4 with the following error:

```
Error: Package: xorgxrdp-0.2.6-1.el7.x86_64 (epel)
           Requires: xorg-x11-server-Xorg(x86-64) = 1.19.3
           Installed: xorg-x11-server-Xorg-1.19.5-5.el7.x86_64 (@rhel-7-server-rpms)
               xorg-x11-server-Xorg(x86-64) = 1.19.5-5.el7
```

**Comment by evanlinde** [comment]
xorgxrdp is only good for the version of Xorg it was built against and the dependencies defined in the rpms reflect this. 

Your newer Xorg version isn't in all?/any? of the downstream RedHat-based distros yet -- I've only checked CentOS -- so it may be a while before anything new gets built in EPEL.

To get a new build of xorgxrdp in the EPEL repo (which seems like what you're looking for) you'll want to contact the appropriate EPEL package maintainer. This link should help you get started: https://koji.fedoraproject.org/koji/packageinfo?packageID=23887

And, of course, you *could* build it yourself.

**Comment by guleyupo** [comment]
Great info; thanks.

**Comment by itamarjp** [comment]
the correct link to file this bug is  http://bugz.fedoraproject.org/xrdp
