### ISSUE TITLE
Clipboard could not use in win7 or xp

### ISSUE THREAD

**Issue by silenceli** [neutrinolabs/xrdp#11]
Hi,
When I use Rdesktop in Linux as client  to access my remote desktop throught  XRDP, I found my remote desktop`s  clipboard works well. but when I use mstsc in win7 or xp ,Clipboard couldn`t  work. I don`t know why. I hope you can solve this problem.

I use libxrdpfreerdp1.so

**Comment by metalefty** [comment]
Reopen if this issue is not fixed in the latest release (v0.9.1).
