### ISSUE TITLE
How to make a .deb target?

### ISSUE THREAD

**Issue by billyork23** [neutrinolabs/xrdp#1100]
I've used the make instructions (link below) to build the latest xrdp source. While this works, I'd like to pack derived files into a .deb file so I can install them later in an environment without the all the build tools installed.

Any help would be appreciated!

Here are the build instructions I used:

https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8

**Comment by Natureshadow** [comment]
Hi,

> I've used the make instructions (link below) to build the latest xrdp
> source.  While this works, I'd like to pack derived files into a .deb file
> so I can install them later in an environment without the all the build
> tools installed.
> 
> Any help would be appreciated!
> 
> Here are the build instructions I used:
> 
> https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8                                                                                                                        

I am just preparing an xrdp 0.9.6 upload to jessie-backports-sloppy[1], which
will be there in a few days.  Just in case that's all you need…

-nik

[1] https://backports.debian.org/

**Comment by billyork23** [comment]
Excellent. Do you know if a Jessie build will work with Ubuntu 16.04?

**Comment by billyork23** [comment]
Hello again,

Is 0.9.6 available via backports now?

I tried the following but it seems I’m getting 0.6.1

# add this to /etc/apt/sources.list
deb http://ftp.debian.org/debian jessie-backports-sloppy main

# update packages
sudo apt-get update

# install xrdp
sudo apt-get -t jessie-backports-sloppy install xrdp
