### ISSUE TITLE
Session doesn't start on Kali Linux on WSL

### ISSUE THREAD

**Issue by samtorrero** [neutrinolabs/xrdp#1102]
I am trying to connect to Kali from Windows Subsystem for Linux. I installed xrdp, started it and connect with RDP in the port. Prompt appears with login an then a window with this:

connecting to sesman ip 127.0.0.1 port 3390
sesman connect ok
sending login info to session manager, please wait...
login successful for screen 10
started connecting
connection problem, giving up
some problem

I tried to edit the file in /etc/X11/Xwrapper.config changing "allowed_users=anybody".

Any ideas?
Thanks!

**Comment by metalefty** [comment]
> I tried to edit the file in /etc/X11/Xwrapper.config changing "allowed_users=anybody".

Don't be fooled by old information on the web. Stand on your own legs. AFAIK Kali Linux is a Debian based distro, if  `/usr/share/doc/xrdp/README.Debian` or some documents like that of your installation doesn't mention about editing `Xwrapper.config`, you don't need to edit. 

You're also a pioneer using xrdp on Kali Linux on WSL. See also #1101.

**Comment by evanlinde** [comment]
You might be able to get your RDP connection working by using the `Xvnc` back-end instead of the `Xorg` back-end. Instructions here: https://github.com/neutrinolabs/xrdp/issues/1101#issuecomment-382033147

**Comment by samtorrero** [comment]
That worked! Thank you so much!
