### ISSUE TITLE
No audio device available on the client

### ISSUE THREAD

**Issue by Flunkyball** [neutrinolabs/xrdp#1110]
Hi everyone,

I did a fresh install of manjaro Linux (Arch) with KDE and grabbed the latest version of xorgxrdp incl. xrdp 0.9.6. Pulseaudio-11 is installed as well and setup according to this small howto: [http://dp.nonoo.hu/forwarding-sound-on-lan/](url)
However, after connecting to the remote computer via RDP there is no sound device present and therefore no sound is audible. On the remote machine itself audio works without any issues.
I tried connecting from a Windows 10 machine as well as from another Linux machine using Remmina, both with the same result.

Any idea where the problem lies ?

Cheers,
Ludwig

**Comment by metalefty** [comment]
Why did you think the how to works?

**Comment by Flunkyball** [comment]
Since I was able to set the pulseaudio preferences and did not see any errors within the journal I assumed everything worked.
Well, after starting pulseaudio with "pulseaudio --start" manually I got a audio device called Dummy Device. However, still no audio output....

**Comment by metalefty** [comment]
Do you want to setup pulseaudio itself? If so, it's out of our scope.

**Comment by Flunkyball** [comment]
I want audio redirection with xrdp working. Since it did not work out of the box I landed with setting up pulseaudio which does not work neither.
-> How it is supposed to work after all ?

**Comment by metalefty** [comment]
Why are you struggling by reading someone's blog not the instructions in README.md written by we developers?

**Comment by Flunkyball** [comment]
It seemed awkward that I really need to go through all that trouble building those modules myself for such a common functionality... So I did exactly that and audio now works.
Thank you for you patience and your help which is really appreciated.
