### ISSUE TITLE
Hyper-V sockets support

### ISSUE THREAD

**Issue by Jonesb** [neutrinolabs/xrdp#1111]
Is there a plan to include the Hyper-V socket support in the standard release rather than requiring the recompilation of the source?

**Comment by metalefty** [comment]
It depends on your distro.

**Comment by Jonesb** [comment]
Ok thanks.

**Comment by itamarjp** [comment]
what are your linux distro / SO ?

**Comment by Jonesb** [comment]
Hi I’m using epel-release

**Comment by itamarjp** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1553453
