### ISSUE TITLE
Selinux alerts on CentOS

### ISSUE THREAD

**Issue by Suncatcher** [neutrinolabs/xrdp#1113]
Have anybody faced such SELinux AVC alerts in Gnome GUI? Here is what I have in **/var/log/audit/audit.log**:

    type=AVC msg=audit(1524250749.897:34): avc:  denied  { write } for  pid=738 comm="accounts-daemon" name="root" dev="dm-0" ino=33580513 scontext=system_u:system_r:accountsd_t:s0 tcontext=system_u:object_r:admin_home_t:s0 tclass=dir
    type=USER_AVC msg=audit(1524255601.633:544): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  received policyload notice (seqno=2)  exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
    type=AVC msg=audit(1524507900.440:208): avc:  denied  { search } for  pid=2871 comm="geoclue" name="2403" dev="proc" ino=30970 scontext=system_u:system_r:geoclue_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    type=AVC msg=audit(1524508008.333:217): avc:  denied  { search } for  pid=2004 comm="colord" name="2577" dev="proc" ino=31617 scontext=system_u:system_r:colord_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    type=AVC msg=audit(1524508008.338:218): avc:  denied  { search } for  pid=2004 comm="colord" name="2577" dev="proc" ino=31617 scontext=system_u:system_r:colord_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    type=AVC msg=audit(1524508601.169:146): avc:  denied  { setsched } for  pid=1948 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524508601.177:147): avc:  denied  { setsched } for  pid=1948 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524508601.187:148): avc:  denied  { setsched } for  pid=1948 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524508601.193:149): avc:  denied  { setsched } for  pid=1948 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524508601.198:150): avc:  denied  { setsched } for  pid=1948 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524508601.203:151): avc:  denied  { setsched } for  pid=1948 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524508601.208:152): avc:  denied  { setsched } for  pid=1948 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524508601.213:153): avc:  denied  { setsched } for  pid=1948 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524508601.224:154): avc:  denied  { setsched } for  pid=1948 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524508601.232:155): avc:  denied  { setsched } for  pid=1948 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524508601.238:156): avc:  denied  { setsched } for  pid=1948 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524508648.696:169): avc:  denied  { search } for  pid=2315 comm="geoclue" name="1912" dev="proc" ino=26273 scontext=system_u:system_r:geoclue_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    type=AVC msg=audit(1524508652.770:173): avc:  denied  { search } for  pid=2111 comm="colord" name="2073" dev="proc" ino=27771 scontext=system_u:system_r:colord_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    type=AVC msg=audit(1524508652.776:174): avc:  denied  { search } for  pid=2111 comm="colord" name="2073" dev="proc" ino=27771 scontext=system_u:system_r:colord_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    type=AVC msg=audit(1524509988.725:146): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524509988.732:147): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524509988.741:148): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524509988.747:149): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524509988.752:150): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524509988.758:151): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524509988.763:152): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524509988.770:153): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524509988.777:154): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524509988.784:155): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524509988.791:156): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524509999.009:168): avc:  denied  { search } for  pid=2289 comm="geoclue" name="1919" dev="proc" ino=25559 scontext=system_u:system_r:geoclue_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    type=AVC msg=audit(1524509999.265:169): avc:  denied  { search } for  pid=2130 comm="colord" name="2106" dev="proc" ino=27342 scontext=system_u:system_r:colord_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    type=AVC msg=audit(1524509999.270:170): avc:  denied  { search } for  pid=2130 comm="colord" name="2106" dev="proc" ino=27342 scontext=system_u:system_r:colord_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    type=AVC msg=audit(1524566138.081:843): avc:  denied  { setsched } for  pid=10448 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524566138.087:844): avc:  denied  { setsched } for  pid=10448 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524566138.098:845): avc:  denied  { setsched } for  pid=10448 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524566138.104:846): avc:  denied  { setsched } for  pid=10448 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524566138.112:847): avc:  denied  { setsched } for  pid=10448 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524566138.118:848): avc:  denied  { setsched } for  pid=10448 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524566138.123:849): avc:  denied  { setsched } for  pid=10448 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524566138.130:850): avc:  denied  { setsched } for  pid=10448 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524566138.138:851): avc:  denied  { setsched } for  pid=10448 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524566138.146:852): avc:  denied  { setsched } for  pid=10448 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524566138.154:853): avc:  denied  { setsched } for  pid=10448 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    type=AVC msg=audit(1524566181.055:866): avc:  denied  { search } for  pid=10811 comm="geoclue" name="10412" dev="proc" ino=53877 scontext=system_u:system_r:geoclue_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    type=AVC msg=audit(1524566206.518:871): avc:  denied  { search } for  pid=10623 comm="colord" name="10600" dev="proc" ino=55394 scontext=system_u:system_r:colord_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    type=AVC msg=audit(1524566206.525:872): avc:  denied  { search } for  pid=10623 comm="colord" name="10600" dev="proc" ino=55394 scontext=system_u:system_r:colord_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir

I had disabled colord password prompts with this global polkit policy:

    /etc/polkit-1/rules.d/49-nopasswd_global.rules
    /* Allow members of the wheel group to execute any actions
     * without password authentication, similar to "sudo NOPASSWD:"
     */
    polkit.addRule(function(action, subject) {
        if (subject.isInGroup("wheel")) {
            return polkit.Result.YES;
        }
    });

But this only prevented prompts but SELinux alerts left and they annoy me very much.
I had allowed xrdp with 

    chcon --type=bin_t /usr/sbin/xrdp
    chcon --type=bin_t /usr/sbin/xrdp-sesman

I found [this thread](https://www.centos.org/forums/viewtopic.php?t=59312) but it has no solution, and I believe these alerts are xrdp-related. Any suggestions?

**Comment by matt335672** [comment]
Seen something similar here. Your session is running in unconfined_service_t context rather than unconfined_t. You can verify this by using the 'id -Z' command on the command line. Compare the result of the command when logged in with XRDP to the result when logged in on the console.

This is probably because when the PAM session is being opened, you're not running pam_selinux.so as part of the session stack.

If you're using GNOME 3, edit /etc/pam.d/xrdp, comment out the existing lines and uncomment the lines specific to GNOME 3. I believe this may fix things for you.

Most of this is from memory, as I'm not at work at the moment and don't have a CentOS 7.4 VM handy. I hope it makes sense.

**Comment by Suncatcher** [comment]
Thanks for your response. There is no **/etc/pam.d/xrdp** file in my system, only **xrdp-sesman** and **xrdp-sesman.rpmnew**. **xrdp-sesman** is empty and **xrdp-sesman.rpmnew** contains following

    #%PAM-1.0
    # Generic Fedora config
    auth       include      password-auth
    account    include      password-auth
    password   include      password-auth
    session    include      password-auth
    
    # Gnome specific Fedora config
    #auth       include      gdm-password
    #account    include      gdm-password
    #password   include      gdm-password
    #session    include      gdm-password

I commented generic Fedora config and uncommented GDM config like this

    #%PAM-1.0
    # Generic Fedora config
    #auth       include      password-auth
    #account    include      password-auth
    #password   include      password-auth
    #session    include      password-auth
    
    # Gnome specific Fedora config
    auth       include      gdm-password
    account    include      gdm-password
    password   include      gdm-password
    session    include      gdm-password

but this didn't help. 

Maybe I should uncomment %PAM-1.0 line? Or should I create _/etc/pam.d/xrdp_ anyway?

**Comment by Suncatcher** [comment]
Also I examined audit log with **sealert** I found such messages:
**colord**

    SELinux is preventing /usr/libexec/colord from search access on the directory 2229.
    
    *****  Plugin catchall (100. confidence) suggests   **************************
    
    If you believe that colord should be allowed search access on the 2229 directory by default.
    Then you should report this as a bug.
    You can generate a local policy module to allow this access.
    Do
    allow this access for now by executing:
    # ausearch -c 'colord' --raw | audit2allow -M my-colord
    # semodule -i my-colord.pp
    
    Additional Information:
    Source Context                system_u:system_r:colord_t:s0
    Target Context                system_u:system_r:unconfined_service_t:s0
    Target Objects                2229 [ dir ]
    Source                        colord
    Source Path                   /usr/libexec/colord
    Port                          <Unknown>
    Host                          fortnox
    Source RPM Packages           colord-1.3.4-1.el7.x86_64
    Target RPM Packages           
    Policy RPM                    selinux-policy-3.13.1-166.el7_4.9.noarch
    Selinux Enabled               True
    Policy Type                   targeted
    Enforcing Mode                Enforcing
    Host Name                     fortnox
    Platform                      Linux fortnox 3.10.0-693.21.1.el7.x86_64 #1 SMP
                                  Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64
    Alert Count                   14
    First Seen                    2018-04-24 06:36:46 EDT
    Last Seen                     2018-05-03 00:37:36 EDT
    Local ID                      29e5a2e6-1027-40d1-9758-fa03bcf20643
    
    Raw Audit Messages
    type=AVC msg=audit(1525322256.440:177): avc:  denied  { search } for  pid=2255 comm="colord" name="2229" dev="proc" ino=28047 scontext=system_u:system_r:colord_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
    
    
    type=SYSCALL msg=audit(1525322256.440:177): arch=x86_64 syscall=open success=no exit=EACCES a0=55b575291b30 a1=0 a2=7ffcf6324ae0 a3=0 items=0 ppid=1 pid=2255 auid=4294967295 uid=997 gid=995 euid=997 suid=997 fsuid=997 egid=995 sgid=995 fsgid=995 tty=(none) ses=4294967295 comm=colord exe=/usr/libexec/colord subj=system_u:system_r:colord_t:s0 key=(null)
    
    Hash: colord,colord_t,unconfined_service_t,dir,search

**accounts-daemon**

    SELinux is preventing /usr/libexec/accounts-daemon from write access on the directory root.
    
    *****  Plugin catchall (100. confidence) suggests   **************************
    
    If you believe that accounts-daemon should be allowed write access on the root directory by default.
    Then you should report this as a bug.
    You can generate a local policy module to allow this access.
    Do
    allow this access for now by executing:
    # ausearch -c 'accounts-daemon' --raw | audit2allow -M my-accountsdaemon
    # semodule -i my-accountsdaemon.pp
    
    Additional Information:
    Source Context                system_u:system_r:accountsd_t:s0
    Target Context                system_u:object_r:admin_home_t:s0
    Target Objects                root [ dir ]
    Source                        accounts-daemon
    Source Path                   /usr/libexec/accounts-daemon
    Port                          <Unknown>
    Host                          localhost.localdomain
    Source RPM Packages           accountsservice-0.6.45-2.el7.x86_64
    Target RPM Packages           filesystem-3.2-21.el7.x86_64
    Policy RPM                    selinux-policy-3.13.1-166.el7.noarch
    Selinux Enabled               True
    Policy Type                   targeted
    Enforcing Mode                Enforcing
    Host Name                     localhost.localdomain
    Platform                      Linux localhost.localdomain 3.10.0-693.el7.x86_64
                                  #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64
    Alert Count                   1
    First Seen                    2018-04-20 14:59:09 EDT
    Last Seen                     2018-04-20 14:59:09 EDT
    Local ID                      fb5e53f8-3edd-4927-806b-dc477d8e3b83
    
    Raw Audit Messages
    type=AVC msg=audit(1524250749.897:34): avc:  denied  { write } for  pid=738 comm="accounts-daemon" name="root" dev="dm-0" ino=33580513 scontext=system_u:system_r:accountsd_t:s0 tcontext=system_u:object_r:admin_home_t:s0 tclass=dir
    
    
    type=SYSCALL msg=audit(1524250749.897:34): arch=x86_64 syscall=mkdir success=no exit=EACCES a0=557c2b485860 a1=1c0 a2=0 a3=7fff75367cf0 items=0 ppid=1 pid=738 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm=accounts-daemon exe=/usr/libexec/accounts-daemon subj=system_u:system_r:accountsd_t:s0 key=(null)
    
    Hash: accounts-daemon,accountsd_t,admin_home_t,dir,write

**rtkit-daemon**

    SELinux is preventing /usr/libexec/rtkit-daemon from using the setsched access on a process.
    
    *****  Plugin catchall (100. confidence) suggests   **************************
    
    If you believe that rtkit-daemon should be allowed setsched access on processes labeled unconfined_service_t by default.
    Then you should report this as a bug.
    You can generate a local policy module to allow this access.
    Do
    allow this access for now by executing:
    # ausearch -c 'rtkit-daemon' --raw | audit2allow -M my-rtkitdaemon
    # semodule -i my-rtkitdaemon.pp
    
    Additional Information:
    Source Context                system_u:system_r:rtkit_daemon_t:s0
    Target Context                system_u:system_r:unconfined_service_t:s0
    Target Objects                Unknown [ process ]
    Source                        rtkit-daemon
    Source Path                   /usr/libexec/rtkit-daemon
    Port                          <Unknown>
    Host                          localhost.localdomain
    Source RPM Packages           rtkit-0.11-10.el7.x86_64
    Target RPM Packages           
    Policy RPM                    selinux-policy-3.13.1-166.el7_4.9.noarch
    Selinux Enabled               True
    Policy Type                   targeted
    Enforcing Mode                Enforcing
    Host Name                     cubical-wifi
    Platform                      Linux cubical-wifi 3.10.0-693.21.1.el7.x86_64 #1
                                  SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64
    Alert Count                   22
    First Seen                    2018-04-23 14:36:41 EDT
    Last Seen                     2018-04-23 14:59:48 EDT
    Local ID                      f423a01a-c77f-4833-b291-cacfcb2027d2
    
    Raw Audit Messages
    type=AVC msg=audit(1524509988.791:156): avc:  denied  { setsched } for  pid=1955 comm="rtkit-daemon" scontext=system_u:system_r:rtkit_daemon_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=process
    
    
    type=SYSCALL msg=audit(1524509988.791:156): arch=x86_64 syscall=sched_setscheduler success=no exit=EACCES a0=7a2 a1=40000000 a2=7fffdee781b0 a3=0 items=0 ppid=1 pid=1955 auid=4294967295 uid=172 gid=172 euid=172 suid=172 fsuid=172 egid=172 sgid=172 fsgid=172 tty=(none) ses=4294967295 comm=rtkit-daemon exe=/usr/libexec/rtkit-daemon subj=system_u:system_r:rtkit_daemon_t:s0 key=(null)
    
    Hash: rtkit-daemon,rtkit_daemon_t,unconfined_service_t,process,setsched

**geoclue**

     SELinux is preventing /usr/libexec/geoclue from search access on the directory 1919.
     
     *****  Plugin catchall (100. confidence) suggests   **************************
     
     If you believe that geoclue should be allowed search access on the 1919 directory by default.
     Then you should report this as a bug.
     You can generate a local policy module to allow this access.
     Do
     allow this access for now by executing:
     # ausearch -c 'geoclue' --raw | audit2allow -M my-geoclue
     # semodule -i my-geoclue.pp
     
     Additional Information:
     Source Context                system_u:system_r:geoclue_t:s0
     Target Context                system_u:system_r:unconfined_service_t:s0
     Target Objects                1919 [ dir ]
     Source                        geoclue
     Source Path                   /usr/libexec/geoclue
     Port                          <Unknown>
     Host                          localhost.localdomain
     Source RPM Packages           geoclue2-2.4.5-1.el7.x86_64
     Target RPM Packages           
     Policy RPM                    selinux-policy-3.13.1-166.el7_4.9.noarch
     Selinux Enabled               True
     Policy Type                   targeted
     Enforcing Mode                Enforcing
     Host Name                     cubical-wifi
     Platform                      Linux cubical-wifi 3.10.0-693.21.1.el7.x86_64 #1
                                   SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64
     Alert Count                   3
     First Seen                    2018-04-23 14:25:00 EDT
     Last Seen                     2018-04-23 14:59:59 EDT
     Local ID                      19cc01cb-b534-4882-ae57-b740c7268009
     
     Raw Audit Messages
     type=AVC msg=audit(1524509999.9:168): avc:  denied  { search } for  pid=2289 comm="geoclue" name="1919" dev="proc" ino=25559 scontext=system_u:system_r:geoclue_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
     
     
     type=SYSCALL msg=audit(1524509999.9:168): arch=x86_64 syscall=open success=no exit=EACCES a0=c84600 a1=0 a2=0 a3=7fff7eae4000 items=0 ppid=1 pid=2289 auid=4294967295 uid=994 gid=989 euid=994 suid=994 fsuid=994 egid=989 sgid=989 fsgid=989 tty=(none) ses=4294967295 comm=geoclue exe=/usr/libexec/geoclue subj=system_u:system_r:geoclue_t:s0 key=(null)
     
     Hash: geoclue,geoclue_t,unconfined_service_t,dir,search

Should I create app-specific local rules as suggested in their description or better to fix problem globally? I prefer the latter.

**Comment by matt335672** [comment]
Apologies Sunscratcher - at the time I was writing from memory and I seem to have caused some confusion as a result.

The file you want to edit is `/etc/pam.d/xrdp-sesman`. This file should not be blank!

If you are running GNOME 3, edit it to look like this:-
```
#%PAM-1.0
# Generic Fedora config
#auth       include      password-auth
#account    include      password-auth
#password   include      password-auth
#session    include      password-auth

# Gnome specific Fedora config
# We have to use this for RHEL 7 to get the correct SELinux
# transitions for user sessions
auth       include      gdm-password
account    include      gdm-password
password   include      gdm-password
session    include      gdm-password
```

The idea is that xrdp-sesman will then behave like GDM when it starts the PAM session. You should end up with an SELinux context of `unconfined_t`.

I believe that at the moment if you enter the command `id -Z` on the command line it will show you that you are still running a context of `unconfined_service_t` rather than `unconfined_t`. `unconfined_service_t` is the context that the xrdp-sesman process runs in.

If you can get to a state where `id -Z` shows a context of `unconfined_t`, that should eliminate most of the errors you have just posted. The exception is the account-daemon error which I think you will get if you log in as root on CentOS 7.4.

Hope that helps - let us know how you get on.

**Comment by Suncatcher** [comment]
If I apply the above correction to /etc/pam.d/xrdp-sesman, logon gets completely broken and I cannot start the RDP session. 

![image](https://user-images.githubusercontent.com/6388034/39567307-390243ae-4ec7-11e8-9127-9aec853e0ec8.png)

**Comment by matt335672** [comment]
The message suggests that the XRDP executable is having problems connecting to the X server.

Some questions for you:-

- Which backend are you using? Xorg or Xvnc?
- Does disabling SELinux with `setenforce 0` allow you to log in now?
- Are you getting any useful messages in the journal after you try to log in with either `journalctl --since=-10m` or `ausearch -m avc -ts recent`?

**Comment by Suncatcher** [comment]
> Which backend are you using? Xorg or Xvnc?

Xorg.

> Does disabling SELinux with setenforce 0 allow you to log in now?

Well, disabling SELinux solves all my problems at all, even AVC messages, so there is no need in PAM editing :) 

> Are you getting any useful messages in the journal after you try to log in with either journalctl --since=-10m

There is plenty of errors. What should I search for?

**Comment by matt335672** [comment]
Well, if disabling SELinux works OK, we probably need to look at the audit log.

First a question I forgot to ask. I take it you're the using xrdp RPM from EPEL? Have you also installed the xrdp-selinux RPM? You need that to allow the process transitions to happen in the first place.

Assuming you have, could you wait a bit, and then have a look at the output of `ausearch -m avc -ts recent`. That gives SELinux errors over the last 10 minutes or so. Also, the output of `ausearch -m avc -ts recent | audit2allow` could be a useful summary.

**Comment by Suncatcher** [comment]
God bless you, man! It works! xrdp-selinux (with combination of `/etc/pam.d/xrdp-sesman` modifiction) works. This problem was drilling me several days.
Thanks a ton!

**Comment by matt335672** [comment]
Sorry I didn't think of the separate xrdp-selinux RPM sooner - glad we got there.

It's a standard technique to package the SELinux bits separately from the standard RPM as it gives the administrator more control over whether to install it or not. That said, looking at my local copy of EPEL, the number of separate SELinux packages is around 1 in 1000, so it's easy not to come across it.

I though it worth adding a final note for the record that if you're running SELinux and the standard targeted policy, it's quite important that the `id -Z` command shows you're running in the `unconfined_t` domain:-

```
$ id -Z
unconfined_u:unconfined_r:unconfined_t:s0
```

If you're running in `unconfined_service_t`, things will mostly work but you may experience subtle problems. For example on RHEL 7.5, the `chronyc` command will fail silently, displaying no output. So it's worth checking.

**Comment by Suncatcher** [comment]
> If you're running in unconfined_service_t, things will mostly work but you may experience subtle problems. For example on RHEL 7.5, the chronyc command will fail silently, displaying no output. So it's worth checking.

Thanks for pointing out.

**Comment by Suncatcher** [comment]
`xrdp-selinux` installation probably should be included in CentOS manuals, updated them

**Comment by metalefty** [comment]
It looks a little bit strange for me. If xrdp depends on `xrdp-*` package, it is a circular dependency.
 You should see what xrdp-selinux package does and do it by your own.

The build instruction should explain what should be done if xrdp-selinux package not provided.

**Comment by Suncatcher** [comment]
> You should see what xrdp-selinux package does and do it by your own.

Yes, but I believe both variants should be included in the installation guide (manual configuring + `xrdp-selinux` package). You should be keep in mind that not all users are so experienced in CentOS and not all users have time and skills to dig though the mess of configuration stuff. Configuring is a very questionable fun.
Why not to include it just as an option?
