### ISSUE TITLE
Using NFS as Users HOME.

### ISSUE THREAD

**Issue by Zohman** [neutrinolabs/xrdp#1117]
seems like xrdp can't support users that their HOME is an NFS mount-point.

i wanted to support redirected drives and i've encounter issues with setting it up.

what I've ending up doing is setting FuseMountName as below 
FuseMountName=.redirected_drives

using 0.9.6 version - this parameter can't contain path or any variables, 
as far as i can see it's only looking for <FuseMountName> in the user HOME.
so what i did is to make FuseMountName link to /tmp/ like this:

in startwm.sh:
---------------------------
#link redirected drives
mkdir /tmp/.xrdp/${USER}_redirected_drives
ln -nfs /tmp/.xrdp/${USER}_redirected_drives $HOME/.redirected_drives
find $HOME/Desktop/ -type l -name "[A-Z]:" -exec rm -f {} \;
ls $HOME/.redirected_drives | while read d
  do
    ln -nfs $HOME/.redirected_drives/$d $HOME/Desktop/$d
  done

< gnome executable >

#logout
/bin/fusermount -u /tmp/.xrdp/${USER}_redirected_drives
rmdir /tmp/.xrdp/${USER}_redirected_drives

--------------------

this is working very well for me, except that 
making the /tmp/.xrdp/${USER}_redirected_drives is created after sesman open the drive redirection channel so the directory is not exist at that time, so it can't be fused-mount at first startwm.sh startup,
users will need to logout and re-login and it's working (obviously now the directory there) .

but this scenario also prevent me from deleting this directory when user logout;
rmdir /tmp/.xrdp/${USER}_redirected_drives

as it will never work on login\logout so i can't clean the environment.

is there any way i can instruct xrdp to load script before creating Xorg session
and opening the channels?

Thanks,

**Comment by Zohman** [comment]
anyone?
some idea?

**Comment by Zohman** [comment]
Okay,

I've managed to create some workaround,
posting it here if anyone want to implement it on a seemlier scenario.

first i changed the xrdp-chansrv to xrdp-chansrv.orig within the sbin directory:
mv ./xrdp-chansrv ./xrdp-chansrv.orig

created xrdp-chansrv bash script on the directory which execute:

 xrdp-chansrv
----------------
#!/bin/bash
mkdir /tmp/.xrdp/${USER}_redirected_drives
test -L $HOME/.redirected_drives || ln -nfs /tmp/.xrdp/${USER}_redirected_drives $HOME/.redirected_drives
<PATH_TO_YOUR_XRDP>/sbin/xrdp-chansrv.orig

startwm.sh:
-------------
mkdir $HOME/Desktop/redirected_drives
ls $HOME/.redirected_drives | while read d
 do
  ln -nfs $HOME/.redirected_drives/$d $HOME/Desktop/redirected_drives/$d
 done

< gnome executable >

/bin/fusermount -u /tmp/.xrdp/${USER}_redirected_drives
rmdir /tmp/.xrdp/${USER}_redirected_drives
rm -rf $HOME/Desktop/redirected_drives

------

Done :)
now i can create and clean the environment much better.
did all my checks, implementing it for 200~ users on 12 servers.

**Comment by matt335672** [comment]
@Zohman - I know this is an old issue, but I thought you might like to know we're merging #1703 for the next xrdp release.

I believe this will also fix your issue as described above, so I'm closing this one now. Feel free to re-open it if I've misunderstood.
