### ISSUE TITLE
Unable to install on Centos 7.4

### ISSUE THREAD

**Issue by MoonMoon1919** [neutrinolabs/xrdp#1119]
I'm unable to install xrdp 0.9.6-1 on Centos 7.4.

Log output:  
``` 
STDERR: Error: Package: xorgxrdp-0.2.6-2.el7.x86_64 (epel)
               Requires: xorg-x11-server-Xorg(x86-64) = 1.19.5
               Installed: xorg-x11-server-Xorg-1.19.3-11.el7_4.2.x86_64 (@updates)
                   xorg-x11-server-Xorg(x86-64) = 1.19.3-11.el7_4.2
               Available: xorg-x11-server-Xorg-1.19.3-11.el7.x86_64 (base)
                   xorg-x11-server-Xorg(x86-64) = 1.19.3-11.el7
               Available: xorg-x11-server-Xorg-1.19.3-11.el7_4.1.x86_64 (updates)
                   xorg-x11-server-Xorg(x86-64) = 1.19.3-11.el7_4.1
```

Thus far I am unable to find xorg-x11-server-Xorg-1.19.5 for Centos in any package repos. From what I can tell, xorg-x11-server-Xorg-1.19.3-11.el7_4.2.x86_64 is the newest available via Centos Updates.

Any recommendation?

**Comment by MoonMoon1919** [comment]
@tastle73 Any idea on when that might trickle down to being available to CentOS distros?

**Comment by evanlinde** [comment]
Until the newer `xorg-x11-server-Xorg` is available in CentOS, you may be able to get around this by manually installing one of the older builds of `xorgxrdp`.

You can find the builds of `xorgxrdp` at https://apps.fedoraproject.org/packages/xorgxrdp/builds. Based on the output above, xorgxrdp-0.2.6-1.el7 is the build you'll want. (It's also the one installed on my systems.)

Here's what I mean by "manually" install:
```bash
wget https://kojipkgs.fedoraproject.org/packages/xorgxrdp/0.2.6/1.el7/x86_64/xorgxrdp-0.2.6-1.el7.x86_64.rpm
yum install xorgxrdp-0.2.6-1.el7.x86_64.rpm
```

**Comment by MoonMoon1919** [comment]
@evanlinde This worked out very nicely, thanks for saving the day!
