### ISSUE TITLE
Looking for feedback: XRDP connection should check for at least 1 valid UID

### ISSUE THREAD

**Issue by jterry75** [neutrinolabs/xrdp#1123]
On Windows 10 using Hyper-V VMConnect with xrdp over Hyper-V Sockets we are seeing an issue where when xrdp is configured as part of an oem-setup (Ubuntu 18.04) it is possible to see the xrdp login prompt before the oem-setup has completed. This means that a user will be prompted to use xrdp to connect before setting up their user account which does not work at all because xrdp requires a valid user session.

One proposed fix is to check for at least one entry in `/etc/passwd` where the `UID >= 1000`. In this case xrdp will not allow connections while this invariant is still true. Does this invariant hold for all distros who might want to use xrdp or should this be a configurable option in xrdp.ini? Are there other ideas? Thanks for the feedback.

If this seems to be a good approach I can submit a fix that does this behavior.

**Comment by metalefty** [comment]
I don't get you.  At least 1 valid uid required to login but why should xrdp check it? 
Does OpenSSH check it? - no. The common point between OpenSSH and xrdp is to provide remote login.

**Comment by jterry75** [comment]
OpenSSH doesn't provide a portal to connect to a machine without a user/pass combo. On the other hand xrdp does provide such a facility and you can connect to the host to see the xrdp login screen. But what is the point of allowing this connection if there are no user/pass combos that you could put in the login screen that would connect. IE: if there are no user/pass combos there should be no connection. This is exactly how OpenSSH would work. If there are no user/pass combos you couldn't connect via ssh either. The ask is that we dont allow XRDP to provide the login screen or accept connections if there are no valid user accounts to connect to.

**Comment by moobyfr** [comment]
You shouldn't go this way. For example with large setup, you won't be able to enumerate users (nothing in ``/etc/passwd`` apart classic service account, and nothing returned with ``getent passwd``) This is, for example, my setup with 100k users in Active Directory, and using default winbind configuration (i.e. not for exposing all users).
Il you really want this type or usage, you should only start xrdp service when you are sure oem-setup has completed.

**Comment by jsorg71** [comment]
I was thinking maybe delay startup is xrdp until ready.
You can also setup your system to allow root loing to xrdp so parsing /etc/passwd would not work in general.

**Comment by jterry75** [comment]
Ok no problem. I will work on figuring out how to do this differently through oem-setup to avoid starting the service until the setup is complete.

**Comment by jterry75** [comment]
This has been fixed in the installer a different way. Thanks for the feedback no changes are required.
