### ISSUE TITLE
Missing screen update

### ISSUE THREAD

**Issue by moobyfr** [neutrinolabs/xrdp#113]
Hi
I've noticed a small bug in xrdp/X11rdp, when dealing with fast updates: the last update isn't sent.
I can reproduce the problem 100% or the time with:
- open an xterm
- use 'dmesg' command
- look last line: it isn't the prompt
- press a key to force an update
- you'll see the last line, and the prompt

**Comment by metalefty** [comment]
Does this happen in current devel head?
And what about xorgxrdp?

**Comment by moobyfr** [comment]
no more reproducible in current X11rdp.
