### ISSUE TITLE
Startwm.sh env variable for non-root

### ISSUE THREAD

**Issue by Suncatcher** [neutrinolabs/xrdp#1130]
The problem is that `startwm.sh` affects only root user when I redefine environment variables.
For example, when I want to override locales like
 
     . /etc/default/locale

it works only for root, not for regular user. Is it a bug or I am doing smth worng?

**Comment by metalefty** [comment]
startwm.sh will be run under regular user privilege unless you log in as root.

**Comment by Suncatcher** [comment]
> unless you log in as root.

I log in as a regular user, and BTW this locale redefinition is the last command I run before DE start, so it cannot be overwritten afterwards. Here is how my `startwm.sh` looks like:

    #!/bin/sh
    
    # Execution sequence for interactive login shell - pseudocode
    pre_start()
    {
      if [ -r /etc/profile ]; then
        . /etc/profile
      fi
      if [ -r ~/.bash_profile ]; then
        . ~/.bash_profile
      else
        if [ -r ~/.bash_login ]; then
          . ~/.bash_login
        else
          if [ -r ~/.profile ]; then
            . ~/.profile
          fi
        fi
      fi
      return 0
    }
    
    # When loging out from the interactive shell, the execution sequence is:
    post_start()
    {
      if [ -r ~/.bash_logout ]; then
        . ~/.bash_logout
      fi
      return 0
    }
    
    #start the window manager
    wm_start()
    {
      if [ -r /etc/default/locale ]; then
        . /etc/default/locale
        export LANG LANGUAGE
      fi
    
      # debian
      if [ -r /etc/X11/Xsession ]; then
        pre_start
        . /etc/X11/Xsession
        post_start
        exit 0
      fi
    
      # el
      if [ -r /etc/X11/xinit/Xsession ]; then
        pre_start
        . /etc/X11/xinit/Xsession
        post_start
        exit 0
      fi
    
      # suse
      if [ -r /etc/X11/xdm/Xsession ]; then
        # since the following script run a user login shell,
        # do not execute the pseudo login shell scripts
        . /etc/X11/xdm/Xsession
        exit 0
      fi
    
      pre_start
      xterm
      post_start
    }
    
    #. /etc/environment
    #export PATH=$PATH
    #export LANG=$LANG
    
    . /etc/default/locale
    
    # change PATH to be what your environment needs usually what is in
    # /etc/environment
    #PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
    #export PATH=$PATH
    
    # for PATH and LANG from /etc/environment
    # pam will auto process the environment file if /etc/pam.d/xrdp-sesman
    # includes
    # auth       required     pam_env.so readenv=1
    gnome-session
    #wm_start
    
    exit 1

**Comment by Suncatcher** [comment]
Really, when I set explicit variables in `startwm.sh` it works for regular user

    export LC_ALL="en_US.UTF-8"

But when I want them to be loaded from global config, it works only for non-root

    . /etc/default/locale

Is there any trick I am missing?
