### ISSUE TITLE
OSX compiling fails: configure failed for librfxcodec

### ISSUE THREAD

**Issue by GGGunrunner** [neutrinolabs/xrdp#1138]
Did everything as prescribed in building instructions for OSX, getting this:
brew install nasm
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
fibjs

Warning: nasm 2.13.03 is already installed and up-to-date
To reinstall 2.13.03, run `brew reinstall nasm`
-----

then configure:

checking for nasm... nasm
checking for object file format of host system... Mach-O64
checking for object file format specifier (NAFLAGS) ... -fmacho64 -DMACHO -D__x86_64__
checking whether the assembler (nasm -fmacho64 -DMACHO -D__x86_64__) works... no
configure: error: installation or configuration problem: assembler cannot create object files.
configure: error: ./configure failed for librfxcodec

I googled all links (20+). Nothing.

I really dont understand: OSX is one of the most standardized OSes. You get it pre-installed, or you install an official distribution. Same set of libraries and frameworks on millions of computers...
Its not some crazy customized/obsolete Linux. If all deps are met, it should be like clockwork.

Yet, compiling a project like XRDP can eat 2-3 hours of your time just by googling.... I dont understand.

**Comment by Magneticdud** [comment]
the *ancient* version 0.91 mentioned in the wiki compiles just fine on 10.13

**Comment by metalefty** [comment]
Should be reported to neutrinolabs/librfxcodec.
