### ISSUE TITLE
xrdp 0.9.6 remote shell application does not accept argument

### ISSUE THREAD

**Issue by gnshkl1** [neutrinolabs/xrdp#1154]
server:- xubuntu-16.04.4_x64
client:-xubuntu-16.04.4_x86
Freerdp version=2.0rc2

**Comment by speidy** [comment]
can you specify the client command line your'e running?
I assume your'e talking about `xfreerdp /shell:`?

**Comment by gnshkl1** [comment]
@speidy 
xfreerdp  /bpp:32 /f  "/shell:gedit  argument"  /u:"user" /v:x.x.x.x  /p:xxx  /rfx

**Comment by gnshkl1** [comment]
@speidy  any update
