### ISSUE TITLE
xrdp does not re-authenticate the screen lock when Linux machine is member of Active Directory domain

### ISSUE THREAD

**Issue by DezignNet** [neutrinolabs/xrdp#116]
If your Linux machine is joined to an Active Directory domain and you connect to an xrdp session using an AD user this issue occurs.  If the screen lock kicks in, you can not unlock the machine.  Testing from a straight GUI Desktop connection works fine it only happens when connected via XRDP.

If you need logs or anything, let me know and I can/will get you whatever you need.

**Comment by metalefty** [comment]
The reporter say the issue was not xrdp issue, closing.
