### ISSUE TITLE
xrdp 0.9.7 microphone not working over skype call

### ISSUE THREAD

**Issue by gnshkl1** [neutrinolabs/xrdp#1162]
Server OS :- Xubuntu 16.04_x64
Server configuration:-4 core with 4Gb Ram
Client Display Resolution:-Full HD 1080p
Client OS:- Ubuntu 18.04_x64
Freerdp Version:- This is FreeRDP version 2.0.0-dev3 (613e0be20)
Commandline:- xfreerdp /u:xxx /p:xxx /v:x.x.x.x  /sound:sys:pulse  /microphone:sys:pulse /rfx
Test:-
1:-take remote session and launch skype 
2:-Audio is choppy on skype call (audio is good in youtube video play over firefox)
3:-microphone input not working

**Comment by metalefty** [comment]
See: https://github.com/neutrinolabs/xrdp/issues/849
