### ISSUE TITLE
xrdp-0.9.7 session re-connection sometimes not working

### ISSUE THREAD

**Issue by ganeshjkale** [neutrinolabs/xrdp#1164]
Server OS :- Xubuntu 16.04_x64
Server configuration:-4 core with 4Gb Ram
Client Display Resolution:-Full HD 1080p
Client OS:- Ubuntu 18.04_x64
Freerdp Version:- This is FreeRDP version 2.0.0-dev3 (613e0be20)
Commandline:- xfreerdp /u:xxx /p:xxx /v:x.x.x.x /sound:sys:pulse  /rfx 
Note:-xrdp.ini has default policy applied for session 

Test:-
1:-take remote session and run firefox
2:-goto youtube play 720p video
3:-disconnect session from windows cross button
4:-reconnect session with same commandline
Result :-got new session sometimes

**Comment by PKizzle** [comment]
Which session are you using? Xvnc, xorgxrdp or x11rdp?

**Comment by gnshkl1** [comment]
@PKizzle xorgxrdp

**Comment by metalefty** [comment]
Solved by neutrinolabs/xorgxrdp#121
