### ISSUE TITLE
How to Kill xrdp and xorg processes automatically after closing windows remote desktop

### ISSUE THREAD

**Issue by asule90** [neutrinolabs/xrdp#1166]
i've posted in [askubuntu.com](https://askubuntu.com/questions/1054063/local-ubuntu-desktop-cannot-login-after-opened-xrdp-session), previously my problem was i could not login locally after xrdp session opened.

i found that not only xrdp process to kill, but also xOrg

```
7313 ?        00:00:02 Xorg
7325 ?        00:00:00 xrdp-chansrv
```

after that, i can now login locally.
now the next question is, is there any chance you could make it automatically kill the processes after i close remote desktop?

thank you

**Comment by metalefty** [comment]
Did you read `man sesman.ini`?

**Comment by asule90** [comment]
after reading sesman.ini,
i tried there configuration :
**sesman.ini**
`[Globals]`
'ListenAddress=127.0.0.1'
`ListenPort=3350`
`EnableUserWindowManager=true`
`UserWindowManager=startwm.sh`
`DefaultWindowManager=startwm.sh`

`[Security]`
`AllowRootLogin=true`
`MaxLoginRetry=4`
`TerminalServerUsers=tsusers`
`TerminalServerAdmins=tsadmins`
`AlwaysGroupCheck=false`

`[Sessions]`
`X11DisplayOffset=10`
`MaxSessions=1`
`KillDisconnected=1`
`DisconnectedTimeLimit=3`
`Policy=Default`

`[Logging]`
`LogFile=xrdp-sesman.log`
`LogLevel=DEBUG`
`EnableSyslog=1`
`SyslogLevel=DEBUG`

`[Xorg]`
`param=/usr/lib/xorg/Xorg`
`param=-config`
`param=xrdp/xorg.conf`
`param=-noreset`
`param=-nolisten`
`param=tcp`
`param=-logfile`
`param=.xorgxrdp.%s.log`

`[Xvnc]`
`param=Xvnc`
`param=-bs`
`param=-nolisten`
`param=tcp`
`param=-localhost`
`param=-dpi`
`param=96`

`[Chansrv]`
`FuseMountName=thinclient_drives`

`[SessionVariables]`
`PULSE_SCRIPT=/etc/xrdp/pulse/default.pa`

now xrdp cannot create new session
**xrdp-sesman.log**
`[20180713-16:21:32] [INFO ] A connection received from ::1 port 43818`
`[20180713-16:21:33] [INFO ] ++ created session (access granted): username superadmin, ip ::ffff:192.168.10.5:53478 - socket: 12`
`[20180713-16:21:33] [INFO ] starting Xorg session...`
`[20180713-16:21:33] [INFO ] max concurrent session limit exceeded. login for user superadmin denied`
`[20180713-16:21:33] [DEBUG] Closed socket 8 (AF_INET6 ::1 port 3350)`

even after i reverted sesman.ini with
`MaxSessions=0`
`KillDisconnected=false`
`DisconnectedTimeLimit=0`

xrdp still got session limit `login failed for display 0`

**Comment by metalefty** [comment]
Yes but you can change it by editing the source and recompiling.
https://github.com/neutrinolabs/xorgxrdp/blob/5ca1b8c517b4216b3987c8b1719a5b108ea17c4b/module/rdpClientCon.c#L1286

**Comment by metalefty** [comment]
I'm not sure because I didn't decide the 60s value but I think to give users a chance to resurrect from unintentional disconnection.

**Comment by metalefty** [comment]
Closing as your original issue is solved.
