### ISSUE TITLE
dynamic-resolution support not working with xrdp-0.9.7

### ISSUE THREAD

**Issue by gnshkl1** [neutrinolabs/xrdp#1170]
currently freerdp 2.0.0.dev3 has dynamic-resolution support which is not working with xrdp-0.9.7
with xorgxrdp-0.2.7 as backend

**Comment by speidy** [comment]
its not supported yet in xrdp.

we working on support thses day though.

**Comment by metalefty** [comment]
We have #448 for the feature.
