### ISSUE TITLE
Easy way to display alerts?

### ISSUE THREAD

**Issue by ttruong7** [neutrinolabs/xrdp#1176]
Is there an easy way to display alerts to xrdp sessions? I know how to use wall, zenity, or send-notify but how do I get it to show up in the xrdp sessions?  My use case is I want to send a notify before shutdown.

**Comment by robanybody** [comment]
You could use xmessage
`DISPLAY=:10 xmessage "System shutdown in 5min"`

**Comment by robanybody** [comment]
you could build a for loop to message all users like so:
` for d in $(ps axo command | grep [X]org  | awk '{print $2}'); do "DISPLAY=$d" xmessage "System shutdown in 5min" ; done`

**Comment by moobyfr** [comment]
You will get more accurate way to get xrdp users with the wtmp branch to
target them

**Comment by metalefty** [comment]
Seems to be solved.
