### ISSUE TITLE
module-xrdp-sink initialization failed

### ISSUE THREAD

**Issue by hmakmur** [neutrinolabs/xrdp#1178]
I know audio with xrdp works on my regular Centos 7.4/7.5  machines. However when I do the same setup  on a headless server with Nvidia 1080Ti GPU, pulseaudio fails to work with the following errors resulting in xrdp 0.9.6 session without sound.  I am not sure what I need to do to correct this. Any help is appreciated.

thanks
-hanz

debug message when called with: pulseaudio -vvv
```
...
I: [pulseaudio] module.c: Loaded "module-augment-properties" (index: #0; argument: "").
D: [pulseaudio] module-always-sink.c: Autoloading null-sink as no other sinks detected.
I: [pulseaudio] sink.c: Created sink 0 "auto_null" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] sink.c:     device.description = "Dummy Output"
I: [pulseaudio] sink.c:     device.class = "abstract"
I: [pulseaudio] sink.c:     device.icon_name = "audio-card"
I: [pulseaudio] source.c: Created source 0 "auto_null.monitor" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] source.c:     device.description = "Monitor of Dummy Output"
I: [pulseaudio] source.c:     device.class = "monitor"
I: [pulseaudio] source.c:     device.icon_name = "audio-input-microphone"
D: [null-sink] module-null-sink.c: Thread starting up
I: [pulseaudio] core.c: default_source: (unset) -> auto_null.monitor
I: [pulseaudio] core.c: default_sink: (unset) -> auto_null
I: [pulseaudio] module.c: Loaded "module-always-sink" (index: #1; argument: "").
D: [pulseaudio] module.c: Checking for existence of '/usr/lib64/pulse-10.0/modules/module-xrdp-sink.so': success
E: Invalid sample format specification or channel map
E: [pulseaudio] module.c: **Failed to load module "module-xrdp-sink" (argument: ""): initialization failed.**
E: [pulseaudio] main.c: Module load failed.
E: [pulseaudio] main.c: Failed to initialize daemon.
I: [pulseaudio] module.c: Unloading "module-null-sink" (index: #2).
D: [pulseaudio] module-always-sink.c: Autoloaded null-sink removed
I: [pulseaudio] core.c: default_sink: auto_null -> (unset)
I: [pulseaudio] core.c: default_source: auto_null.monitor -> (unset)
D: [null-sink] module-null-sink.c: Thread shutting down
I: [pulseaudio] sink.c: Freeing sink 0 "auto_null"
I: [pulseaudio] source.c: Freeing source 0 "auto_null.monitor"
I: [pulseaudio] module.c: Unloaded "module-null-sink" (index: #2).
I: [pulseaudio] module.c: Unloading "module-always-sink" (index: #1).
I: [pulseaudio] module.c: Unloaded "module-always-sink" (index: #1).
I: [pulseaudio] module.c: Unloading "module-augment-properties" (index: #0).
I: [pulseaudio] module.c: Unloaded "module-augment-properties" (index: #0).
I: [pulseaudio] main.c: Daemon terminated.

```

**Comment by hmakmur** [comment]
Good clue! I recompiled pulseaudio 10 from RPM Source and now it works!!!
This problem is solved for me and this issue can be closed. I added a note in 
https://github.com/neutrinolabs/xrdp/wiki/How-to-set-up-audio-redirection reflecting this issue so the next guy wont waste time.

Thanks.
hanz

**Comment by metalefty** [comment]
It should be written generally. Use the version that matches your pulseaudio version on your system.

**Comment by metalefty** [comment]
Whichever RPM source and tarball source works if version and version in paths matche.

**Comment by hmakmur** [comment]
Sorry about the confusion on the documentation.  Current documentation is addressing details on Debian 9/Ubuntu with Pulse Audio 11. Using regular pulseaudio source pointed in the page does not work with Centos 7.5.  I was trying to be specific to address issue with Centos 7.5 which requires one to compile with source RPM and this  is not documented anywhere in the page. I will leave the page as is. You can add whatever notes necessary or someone will eventually find this discussion to address their issue. Keep up the good work!  Thanks for the help.

**Comment by metalefty** [comment]
@hmakmur  It turned out you're correct and I misunderstood the issue. I confirmed it doesn't work unless pulse modules are built with distro pulseaudio source. Regarding CentOS 7.5, pulseaudio modules *must* be built with CentOS's pulseaudio source.

pulse modules need to be built like this. I'll update the build instruction again.
https://github.com/neutrinolabs/pulseaudio-module-xrdp/pull/17

**Comment by hmakmur** [comment]
Thank you for adding a whole lot of steps into the instruction. 
Now the page actually have complete Centos 7.5 instruction which will help lots of people using Centos 7.5. 

hanz
