### ISSUE TITLE
XRDP is using the broken 512 bit RSA key

### ISSUE THREAD

**Issue by XeronX** [neutrinolabs/xrdp#118]
XRDP is using the broken 512 bit RSA key. All intelligence agencies in the world (such as NSA, GCHQ)  and hackers using MITM attacks can crack the 512 bit RSA key by factorization using an algorithm such as the general number field sieve.

**Comment by metalefty** [comment]
Now 2048bit key is the default 5af0d06d1e184a06c25bc044aa9a82921c2f59b5, can be closed.
