### ISSUE TITLE
building xrdp with pulseaudio support for ubuntu 18.04 fails

### ISSUE THREAD

**Issue by bmullan** [neutrinolabs/xrdp#1181]
I have an ubuntu 18.04 VM.

I followed the instructions found here:
https://github.com/neutrinolabs/xrdp/wiki/How-to-set-up-audio-redirection

Everything seems to install correctly until 

> Finally, let's make. You'll have two .so files module-xrdp-sink.so and module-xrdp-source.so.
> 
> cd ~/xrdp/sesman/chansrv/pulse
> make PULSE_DIR="~/pulseaudio-11.1"

At that point I get the following error...

> 
> :~/xrdp/sesman/chansrv/pulse$ make PULSE_DIR="~/pulseaudio-11.1"
> cc -Wall -O2 -I~/pulseaudio-11.1 -I~/pulseaudio-11.1/src -DHAVE_CONFIG_H -fPIC   -c -o module-xrdp-sink.o module-xrdp-sink.c
> module-xrdp-sink.c:25:10: fatal error: config.h: No such file or directory
>  #include <config.h>
>           ^~~~~~~~~~
> compilation terminated.
> <builtin>: recipe for target 'module-xrdp-sink.o' failed
> make: *** [module-xrdp-sink.o] Error 1

NOTE: the contents of the following directory... there is no config.h file ??

> ~/xrdp/sesman/chansrv/pulse$ ls
> Makefile            module-xrdp-sink-symdef.h  module-xrdp-source-symdef.h
> module-xrdp-sink.c  module-xrdp-source.c       README.md

I have tried re-doing this several times just to make sure I didn't skip a step but always the same failure.

Are there files missing from the github ?

Any ideas would be welcome.

Brian

**Comment by metalefty** [comment]
I confirmed it builds. Did you changed enviroment-dependent values to fit yours?

**Comment by metalefty** [comment]
Where's your PULSE_DIR?

**Comment by metalefty** [comment]
BTW, I  didn't say envirnment variables, environment-dependent values.

**Comment by bmullan** [comment]
Sorry.. it's really late here.

I'll recheck any makefiles etc tomorrow.

**Comment by metalefty** [comment]
The `config.h` being searched during the build is `config.h` at the top of the pulseaudio source directory. Set the correct PULSE_DIR then everything will work well.

**Comment by shadoxx** [comment]
I can confirm this bug.
I have a fresh Ubuntu 18.04 VM and have compiled xrdp from the v0.9.7 tagged release. After following all of the instructions located at `xrdp/sesman/chansrv/pulse/README.md`, I experience the same error that @bmullan listed above.

```
cc -Wall -O2 -I~/pulseaudio/pulseaudio-11.1 -I~/pulseaudio/pulseaudio-11.1/src -DHAVE_CONFIG_H -fPIC   -c -o module-xrdp-sink.o module-xrdp-sink.c
module-xrdp-sink.c:25:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'module-xrdp-sink.o' failed
make: *** [module-xrdp-sink.o] Error 1
```

**Comment by metalefty** [comment]
As @shadoxx described it doesn't work when PULSE_DIR includes `~`.
I've merged his PR. @bmullan  Can you try the latest devel branch?
