### ISSUE TITLE
when stopping xrdp services it does not kill all it's children

### ISSUE THREAD

**Issue by andreimarghescu** [neutrinolabs/xrdp#1194]
xrdp forks into a lot of xrdp-sesman services, which are not killed when stopping the main process

**Comment by andreimarghescu** [comment]
scenario: you have a lot of connections from different users and you kill the xrdp service. Now, you have to manually kill every xrdp (sesman) that forked from the main process.

This is bad if a user is starting ONLY firefox (for example) and this process will not be terminated when stopping xrdp service. After the user reconnects, he'll get an error that firefox is already running.

**Comment by metalefty** [comment]
Then, kill it. Some people want to keep children, and some other people don't want to keep children like you. To satisfy both people, we shouldn't kill children without user interaction.

**Comment by andreimarghescu** [comment]
I think it would be neater to do a proper cleanup (kill all the child processes that we started).

**Comment by metalefty** [comment]
It depends on the case.
