### ISSUE TITLE
MS RDP OS X Client v. 10 Still an issue

### ISSUE THREAD

**Issue by tastle73** [neutrinolabs/xrdp#1196]
I do see the other support request about this, but I wanted to add the 10.2 GA is still not showing any fonts on the login screen.  Latest xRDP build from git with libpainter is being accessed.

MS claims they're going to deprecate the v8 app "soon" 

Am I missing some font lib on my Mac? is there any other workaround other than just an auto login?

Thanks!

**Comment by metalefty** [comment]
We know the issue. Dup of #643.
