### ISSUE TITLE
xrdp 0.9.7 sound not working on centos 7.5_1804

### ISSUE THREAD

**Issue by gnshkl1** [neutrinolabs/xrdp#1199]
xrdp version :-  v0.9.7
xorgxrdp version :- 0.2.7
Freerdp version :- Freerdp-2.0.0-rc3

audio module compiled using below reference:-
https://github.com/neutrinolabs/xrdp/wiki/Audio-Output-Virtual-Channel-support-in-xrdp

same is working fine on ubuntu_gnome_16.04

**Comment by metalefty** [comment]
Did you read the top line of the link?

**Comment by gnshkl1** [comment]
@metalefty ok i am trying your suggestion now

**Comment by gnshkl1** [comment]
@metalefty i have tried new procedure of audio sink building and installing still no sound

**Comment by gnshkl1** [comment]
#new method to build pulseaudio:-
yum -y install  doxygen xmltoman tcp_wrappers-devel alsa-lib-devel GConf2-devel avahi-devel libatomic_ops-static libatomic_ops-devel sbc-devel libXtst-devel xcb-util-devel orc-devel libtdb-devel libasyncns-devel systemd-devel dbus-devel libcap-devel  bluez* fftw-devel webrtc-audio-processing* rpm-build

rpmdev-setuptree
yumdownloader --source pulseaudio
rpm  --install pulseaudio\*.src.rpm
rpmbuild -bb --noclean ~/rpmbuild/SPECS/pulseaudio.spec

cd /tmp
git clone https://github.com/neutrinolabs/pulseaudio-module-xrdp.git
cd puleaudio-module-xrdp
./bootstrap && ./configure PULSE_DIR=~travis/rpmbuild/BUILD/pulseaudio-$(pkg-config --modversion libpulse)
make -j4
make install

**Comment by gnshkl1** [comment]
@metalefty audio now working ,closing issue.

Issue resolved with client OS xubuntu-16.04 on vmware having default audio device as alsa audio
