### ISSUE TITLE
is KillDisconnected implemented and working?

### ISSUE THREAD

**Issue by monkey-jsun** [neutrinolabs/xrdp#1205]
I have the following options set in my sessman.ini file.  However, it appears a disconnected session does not get kill.  Anyone knows why?  Anything I did wrong?

KillDisconnected=true
DisconnectedTimeLimit=70

**Comment by metalefty** [comment]
It should work. xorgxrdp must be v0.2.1 or later.

**Comment by monkey-jsun** [comment]
I'm using Xvnc.  Does that matter?

Thanks for replying.

**Comment by metalefty** [comment]
Xvnc mode doesn't support it.

**Comment by monkey-jsun** [comment]
Is it difficult to add this feature?  If you can give some guide, I might be brave enough to take a dive.

Thanks.

**Comment by metalefty** [comment]
Use xorgxrdp, it is much easier.

**Comment by FelixZhang** [comment]
TigerVNC supports a MaxDisconnectionTime option, which you could pass to it's Xvnc in /etc/xrdp/sesman.ini, like:
```
[Xvnc]
param1=-bs
param2=-ac
param3=-nolisten
param4=tcp
param5=-localhost
param6=-dpi
param7=96
param8=-MaxDisconnectionTime
param9=60
```
Unfortunately this is not supported by other vendors of Xvnc like TightVNC or TurboVNC. So I guess it's probably not good idea to implement it in xrdp for compatibility reasons.

**Comment by metalefty** [comment]
@FelixZhang I didn't know that. Thank you for letting me know. I'm still not affirmative in implementing integration xrdp and TigerVNC kill disconnection feature. But it's a good idea to provide configuration examples in documents such as Wiki.
