### ISSUE TITLE
Can not start XRDP v0.9.1 on Raspbian

### ISSUE THREAD

**Issue by DRSDavidSoft** [neutrinolabs/xrdp#1214]
I recently did a `apt upgrade` to update my packages on Raspberry Pi 3.

Unfortunately, now my `xrdp` package (version 0.9.1) is not working.
Instead I'm greeted with the following message:

```
Sep 23 01:49:43 DRS-pi systemd[1]: Starting xrdp daemon...
Sep 23 01:49:44 DRS-pi systemd[1]: xrdp.service: PID file /run/xrdp/xrdp.pid not readable (yet?) after start: No such file or directory
Sep 23 01:49:45 DRS-pi systemd[1]: Started xrdp daemon.
Sep 23 01:49:46 DRS-pi xrdp[10875]: (10875)(1995436608)[INFO ] starting xrdp with pid 10875
Sep 23 01:49:46 DRS-pi xrdp[10875]: (10875)(1995436608)[ERROR] xrdp_listen_main_loop: listen error, possible port already in use
Sep 23 01:49:46 DRS-pi xrdp[10875]: (10875)(1995436608)[DEBUG] Closed socket 11 (AF_INET6 :: port 0)
```

Running `sudo xrdp` gives me this:
```
g_mk_temp_dir: /var/run/xrdp/sockdir does not exist
g_mk_temp_dir: /var/run/xrdp/sockdir does not exist
```

Running neither of these return anything:
    - `netstat -tulnap | grep xrdp`
    - `netstat -tulnap | grep 3389` (I left `3389` as the default port.)

Is this issue already fixed in `0.9.5` and I need to wait on its release on Raspbian,
Or should I edit anything (including `xrdp.ini`) in order to make XRDP work again?

**Comment by metalefty** [comment]
It's not our bug but a distro specific bug so we do nothing to fix it. Ask the Raspbian team.
