### ISSUE TITLE
Can't reconnect from a different machine

### ISSUE THREAD

**Issue by 1noob4ever** [neutrinolabs/xrdp#1219]
Not sure if this is an "issue" but I can connect from one machine then close session without logout and go to another machine and try to login but I get the infamous "some problem". If I go back to original login machine and rdp in and logout of user session then I can go to any machine and rdp in again. Being logged into console keeps me from connecting with rdp client also or being connected with rdp keeps me from login at the console.
This is on a kali 2018.3a and I only installed xrdp and tigervnc-standalone-server then modified xrdp.ini to move [xvnc] option to default connection options.

**Comment by metalefty** [comment]
Xvnc backed session doesn't support that.
