### ISSUE TITLE
dynamic virtual channel improvements

### ISSUE THREAD

**Issue by jsorg71** [neutrinolabs/xrdp#1222]
Update and improve DVC(dynamic virtual channel) in xrdp.  DVC is implemented over the static virtual channel drdynvc.  MSDN doc MS-RDPEDYC
https://msdn.microsoft.com/en-us/library/cc241215.aspx

Future improvements to RDP is usually in dynamic channels.  We need an easy to use and fast DVC API for internal use inside xrdp and chansrv.  The GFX graphics pipeline is a DVC, video redirection and dynamic monitors are both DVCs.

All channels in drdynvc must be opened from the server, as the document states.

Using drdynvc **in xrdp**, these function are in libxrdp.h

  - Open a channel with `libxrdp_drdynvc_open` (Pass callbacks in struct xrdp_drdynvc)
  - Wait for callback open_response
  - Then you can call any of
	`libxrdp_drdynvc_data_first`
	`libxrdp_drdynvc_data`
	`libxrdp_drdynvc_close`
  - Then when done with the channel call
	`libxrdp_drdynvc_close`

Using drdynvc **in chansrv**, these functions are in chansrv.h
  - Open a channel with `chansrv_drdynvc_open` (Pass callbacks in struct chansrv_drdynvc)
  - Wait for callback open_response
  - Then you can call any of
	`chansrv_drdynvc_data_first`
	`chansrv_drdynvc_data`
	`chansrv_drdynvc_close`
  - Then when done with the channel call
	`chansrv_drdynvc_close`

**Comment by scooley** [comment]
Yeeees!  Ping @jterry75 and @cwilhit.

**Comment by jsorg71** [comment]
PR is here #1224

**Comment by jsorg71** [comment]
merged, until we start using it, hard to know what doesn't work.  Let's create new issues when found.

**Comment by jterry75** [comment]
Many thanks @jsorg71! I will get to this sometime in the near future and will update you what I find.

**Comment by cwilhit** [comment]
Awesome! Let me give it a test run today/tomorrow :)

**Comment by jsorg71** [comment]
Note, this does not mean dynamic monitors work, just that it should be easier to implement now.
To show how to use the new internal API, I'll add Mic support which is a Dynamic Virtual channel in chansrv and another one in xrdp, maybe dynamic monitors.
