### ISSUE TITLE
Error on build OSX 10.11

### ISSUE THREAD

**Issue by madmonkey2** [neutrinolabs/xrdp#1234]
Hi all, I'm getting the following error while trying to build the xrdp on OSX 10.11.6 El Capitan. Could anyone help?
-----
bash:xrdp-v0.6.0 mac$ ./bootstrap
/opt/local/bin/autoconf
/opt/local/bin/automake
/usr/bin/libtool
ln: /Users/mac/Desktop/xrdp/xrdp-v0.6.0/sesman/tools/config.c: File exists
./bootstrap: /opt/local/bin/autoreconf: /opt/local/bin/perl: bad interpreter: No such file or directory

**Comment by metalefty** [comment]
That is your local issue.

```
./bootstrap: /opt/local/bin/autoreconf: /opt/local/bin/perl: bad interpreter: No such file or directory
```

 BTW, v0.6.0 is now out of scope. Use it at your own risk.

**Comment by madmonkey2** [comment]
Hi @metalefty, thanx, managed to run bootstrap and configuration successfully. But "make" returns

**Comment by madmonkey2** [comment]
Hi @metalefty, thanx, managed to run bootstrap and configuration successfully. But "make" returns:

Making all in libpainter
make[2]: *** No rule to make target `all'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Is this local issue as well?

**Comment by madmonkey2** [comment]
libpainter and librfxcoded are missing in the latest version (0.9.8)
???

**Comment by metalefty** [comment]
Not missing.

**Comment by metalefty** [comment]
You might need to `git clone --recursive`.
