### ISSUE TITLE
km-0000080a.ini for Spanish Latin American

### ISSUE THREAD

**Issue by ivanbaldo** [neutrinolabs/xrdp#1237]
Thanks for including it!!!
[km-0000080a.ini](https://github.com/neutrinolabs/xrdp/files/2517043/km-0000080a.ini.txt)

**Comment by metalefty** [comment]
Also updated xrdp_keyboard.ini is required.

**Comment by ivanbaldo** [comment]
Thanks for your attention!
I need help modifying that file though.
```
setxkbmap -query:
model:      pc105
layout:     latam
```
So, I have come with this half of the equation:
```
[default_rdp_layouts]
rdp_layout_XXX=0x0000080A

[default_layouts_map]
rdp_layout_XXX=latam

[rdp_layouts_map_mac]
rdp_layout_XXX=YYY
```
I don't know what value to use for XXX, how can I find it out?
Maybe XXX should be equal to "latam" but I am not sure.
And I don't have a Mac so I don't know what should be used for YYY too.
But if you can guide me, I may be able to use the Mac of a friend if necessary.
Thanks a lot!!!

**Comment by metalefty** [comment]
It does not necessarily need to be equal to latam but latam would be fine.
