### ISSUE TITLE
xrdp won't automatically reconnect

### ISSUE THREAD

**Issue by corrugatedcardboard** [neutrinolabs/xrdp#1238]
I might have overlooked something, but maybe someone could help me with this: 
Xrdp does not automatically reconnect to a linux/CentOS host the same way standard windows rdp does to another windows system when the connection has been interrupted (network problems, massive packet loss, etc.)  
Some pictures illustrating the problem (sadly it's in german):

![error_reconnecting](https://user-images.githubusercontent.com/44494847/47557840-f9989d00-d911-11e8-8f4a-33176264b786.PNG)

This is the error message I am trying to get, basically what it says is that windows is going to automatically reconnect to the session as soon as possible, or as soon as the network connectivity has been established again.

Instead I get this error message:

![the_connection_has_been_closed](https://user-images.githubusercontent.com/44494847/47557896-2a78d200-d912-11e8-9c6e-c2ca3e72fe70.PNG)

Here it essentially tells me that the connections has been completely aborted. I already tried changing the sesman.ini file this way:

`
[Security]
AllowRootLogin=true
MaxLoginRetry=4
TerminalServerUsers=tsusers
TerminalServerAdmins=tsadmins
; When AlwaysGroupCheck=false access will be permitted
; if the group TerminalServerUsers is not defined.
AlwaysGroupCheck=false

[Sessions]
;; X11DisplayOffset - x11 display number offset
; Type: integer
; Default: 10
X11DisplayOffset=10

;; MaxSessions - maximum number of connections to an xrdp server
; Type: integer
; Default: 0
MaxSessions=999

;; KillDisconnected - kill disconnected sessions
; Type: boolean
; Default: false
; if 1, true, or yes, kill session after 60 seconds
KillDisconnected=false

;; DisconnectedTimeLimit - when to kill idle sessions
; Type: integer
; Default: 0
; if not zero, the seconds before a disconnected session is killed
; min 60 seconds
DisconnectedTimeLimit=61
`
 
As you can see, the session won't be killed after a disconnect, but still windows does not want to automatically reconnect.

Is this a bug or am I overlooking something? Any help is appreciated!

**Comment by metalefty** [comment]
Works as intended.
