### ISSUE TITLE
xrdp 0.9.7 session resize not working sometimes in session reconnection

### ISSUE THREAD

**Issue by gnshkl1** [neutrinolabs/xrdp#1239]
Client OS :- Xubuntu 16.04.3_x86
Freerdp Version :- 2.0.0.rc3
Server OS :- Ubuntu  Gnome 16.04_x64
Xrdp Version :- 0.9.7
Xorgxrdp version :- 0.2.7

Scenario:-
1:-take remote session from client machine (without fullscreen)
xfreerdp /u:xx /p:xxxx /v:x.x.x.x  /rfx 
2:-disconnect session
3:- now connect same session from differrent machine (with full screen flag)
xfreerdp /u:xx /p:xxxx /v:x.x.x.x  /rfx /f
 
Result :- 
1:- session is not resized for fullscreen

**Comment by gnshkl1** [comment]
@metalefty  attached screenshot for same
![session_from_second_machine](https://user-images.githubusercontent.com/8046158/47766681-02181b80-dcf6-11e8-83e4-cc2ab196c9fe.png)
![session_from_first_machine_nofullscreen](https://user-images.githubusercontent.com/8046158/47766682-02b0b200-dcf6-11e8-8493-1f99aac9cbef.png)

**Comment by metalefty** [comment]
Dup of #914.
