### ISSUE TITLE
macOS Continuous Integration

### ISSUE THREAD

**Issue by mancoast** [neutrinolabs/xrdp#1242]
I suggest CircleCi

**Comment by cosmo0920** [comment]
Travis CI also can run CI on macOS.
https://docs.travis-ci.com/user/reference/osx/

**Comment by metalefty** [comment]
We accept your contributions for macOS but we cannot spare time on macOS right now. macOS is out of our scope. Read the README.

Regarding Travis CI, if someone made a PR to support macOS build, we'll merge it.

**Comment by metalefty** [comment]
not only adding macOS build, I'd appreciate if someone maintain macOS CI continuously.

**Comment by metalefty** [comment]
Looking for someone who can do it.
