### ISSUE TITLE
connection failure causes session restart

### ISSUE THREAD

**Issue by johnarnold** [neutrinolabs/xrdp#1247]
Running xrdp 0.9.5 + xorgxrdp  both built from source.  Everything has been working fine for >6 months until the last week or so.

Sometimes I get disconnected from my session (typically a connection failure / spotty wifi / spotty vpn), when I reconnect I get a new session instead of resuming my session.  This is causing headaches like losing unsaved files in progress etc.  This seems to happen about 50% of the time.  Not sure if it's related to how long the disconnect is (?)

home folder .xorgxrdp.log:
http://paste.ubuntu.com/p/N4t9sPQVCC/

last 500 lines of /var/log/xrdp-sesman.log:
http://paste.ubuntu.com/p/vcmtNp5CXZ/

Any ideas on lines of investigation? Nothing in the logs jumps out at me.  I tried clearing stale sessions and rebooting the server, no improvement.  It's weird that it worked for a long time with no issues, now there are issues.

**Comment by metalefty** [comment]
xorgxrdp log looks wrong.  This line shows us display number 42 used however as far as I look at xrdp-sesman.log, no one uses display number 42.

```
[2231419.229] rdpLoadLayout: keylayout 0x00000409 variant  display 42
```

Only xrdp-sesman.log is useful so far. As far as I look at your log, connection failure doesn't causes session restart but it looks *session crash is causing disconnection* to me.

Just for the tips in long time use, if you build from source and using for a long time, don't forget rebuild xorgxrdp after Xorg version change.

**Comment by johnarnold** [comment]
@metalefty   This is happening for multiple users -- not sure what is causing session crash.   What should I look for?  Suggestions on how to proceed / troubleshoot?

We haven't changed versions of anything built from source.  Are there any library/package dependencies that could have changed, separate from "built from source" stuff?

**Comment by metalefty** [comment]
Anyway, show me the correct log.

**Comment by johnarnold** [comment]
@metalefty  Weird, the logfile rotation seems to be out of order...

Latest home folder xorgxrdp logfile
-rw-r--r--  1 johnar johnar     18126 Nov 26 19:15 .xorgxrdp.13.log
johnar@netdev1-westus2:~$ date
Mon Nov 26 19:19:25 UTC 2018
johnar@netdev1-westus2:~$ pastebinit .xorgxrdp.13.log

http://paste.ubuntu.com/p/tZTKJ8Pjtm/

**Comment by johnarnold** [comment]
I'm going to close this issue, as the problem went away when I upgraded to 0.9.8.
