### ISSUE TITLE
update http://www.xrdp.org/ to point to this repo

### ISSUE THREAD

**Issue by nmccready** [neutrinolabs/xrdp#125]
The website is confusing as it still points to sourceforge .

**Comment by gschwind** [comment]
Hello,
I agree, as user I had hard time to find this repository and could easily miss this project xrdp. (In fact I missed the project for many mouths)

iom, there is also some missing peace in some missing documentation, in particular for xorgxrdp xorg modules, which are mush shorter than building X11rdp for example.

Best regards.

**Comment by speidy** [comment]
I linked download on the website to github so it can be easy to find
בתאריך יום ד׳, 19 באוג׳ 2015 ב-18:33 מאת gschwind <notifications@github.com
