### ISSUE TITLE
Hardware Recommendation

### ISSUE THREAD

**Issue by brijeshjaiswal** [neutrinolabs/xrdp#1252]
What will be the ideal server hardware recommended for 100 users for simultaneously using XRDP session.

**Comment by Akhaladze** [comment]
Hello! It's depend on what you user will be do
For office/browser workers you can calculate your hardware 1 server CPU core per 5 users and 1GB memory per user. 
You need at least 2 CPU with at least 10 cores and 128GB RAM
It'is minimum
