### ISSUE TITLE
Xrdp install OSX mavericks

### ISSUE THREAD

**Issue by nmccready** [neutrinolabs/xrdp#126]
I am trying to follow the directions which use automake via ./bootstrap.

```
./bootstrap //passes
./configure //passes
make //fails

xrdp_mm.c:27:10: fatal error: 'security/_pam_types.h' file not found
#include "security/_pam_types.h"
```

I have installed open pam via http://www.opensource.apple.com/release/os-x-1092/ OpenPAM-20 . The files are there:

```
╰─⠠⠵ ll /usr/local/include/security
total 88
-rw-r--r--  1 root  admin   8.6K May 14 15:45 openpam.h
-rw-r--r--  1 root  admin   749B May 14 15:45 openpam_attr.h
-rw-r--r--  1 root  admin   2.1K May 14 15:45 openpam_version.h
-rw-r--r--  1 root  admin   4.9K May 14 15:45 pam_appl.h
-rw-r--r--  1 root  admin   3.9K May 14 15:45 pam_constants.h
-rw-r--r--  1 root  admin   4.2K May 14 15:45 pam_modules.h
-rw-r--r--  1 root  admin   2.6K May 14 15:45 pam_types.h
```

CPPFLAGS

```
echo $CPPFLAGS
-I/opt/X11/include -I/usr/local/include/security
```

I have also set it to `-I/usr/local/include` and it results in the same error above.

**Comment by Bllacky** [comment]
These are the missing headers you need. Sorry, I didn't bother to edit the proper include paths, so just unzip and place both folders in the root of the xrdp source.
https://www.mediafire.com/?pv86wjy4yvl655i

With pam libraries included, I still get the errors above:
ard_file.Tpo -c -o clipboard_file.o clipboard_file.c
clipboard_file.c:105:24: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
timeval2wintime(struct timeval *tv)
                       ^
clipboard_file.c:110:17: error: incomplete definition of type 'struct timeval'
    result += tv->tv_sec;
              ~~^
clipboard_file.c:105:24: note: forward declaration of 'struct timeval'
timeval2wintime(struct timeval *tv)
                       ^
clipboard_file.c:112:17: error: incomplete definition of type 'struct timeval'
    result += tv->tv_usec * 10;
              ~~^
clipboard_file.c:105:24: note: forward declaration of 'struct timeval'
timeval2wintime(struct timeval *tv)

**Comment by Bllacky** [comment]
Ok, if add this
#include <sys/time.h>

to

clipboard_file.c
chansrv_fuse.c

I've managed to avoid the above errors.
However, now I am stuck at 

man.Tpo -c -o sesman.o sesman.c
sesman.c:62:9: error: void function 'sesman_main_loop' should not return a value [-Wreturn-type]
        return 1;
        ^      ~
sesman.c:286:17: warning: 5 enumeration values not handled in switch: 'LOG_STARTUP_OK', 'LOG_ERROR_NULL_FILE',
      'LOG_ERROR_NO_CFG'... [-Wswitch]
        switch (error)
                ^
sesman.c:216:16: warning: comparison of constant -1 with expression of type 'enum logReturns' is always false
      [-Wtautological-constant-out-of-range-compare]
        if (-1 == error)
            ~~ ^  ~~~~~
2 warnings and 1 error generated.

**Comment by Bllacky** [comment]
Ok, fixed that as well by going into sesman.c

and replacing (probably very unwise):
<code>
    g_sck = g_tcp_socket();
    if (g_sck < 0)
    {
        log_message(LOG_LEVEL_ERROR, "error opening socket, g_tcp_socket() failed...");
        return =1;
    }
</code>
with

<code>
    g_sck = g_tcp_socket();
    if (g_sck < 0)
    {
        log_message(LOG_LEVEL_ERROR, "error opening socket, g_tcp_socket() failed...");
        return;
    }
</code>

**Comment by Bllacky** [comment]
Finally, the last error was:
<code>
xrdpapi.c:179:58: error: use of undeclared identifier 'MSG_NOSIGNAL'
            error = send(sck, data + sent, bytes - sent, MSG_NOSIGNAL);
 </code>

which I fixed by editing xrdapi.c

and replacing

<code>
        error = send(sck, data + sent, bytes - sent, MSG_NOSIGNAL );
            if (error < 1)
            {
</code>

with

<code>
        error = send(sck, data + sent, bytes - sent, SO_NOSIGPIPE );
            if (error < 1)
            {
</code>

Tomorrow I will actually check if whatever was compiled actually works.

**Comment by Bllacky** [comment]
After a long struggle I got the bloody thing to compile. I ran it and actually got to the login screen.
Unfortunately I get login failed and the logs write:

[CODE]23/05/15 01:37:37,061 XRDP-sesman[171]: in openpam_read_chain(): /etc/pam.d/xrdp-sesman(2): invalid facility '@include' (ignored)
[/CODE]

Any ideas are welcomed!

**Comment by Bllacky** [comment]
This is version of devel branch that will compile. But make install still fails with:chmod 755 /etc/xrdp/xrdp.sh
if [ -f /etc/init.d/xrdp ]; then \
		chmod 755 /etc/init.d/xrdp; \
		sed -i 's|__BASE__|/usr|' /etc/init.d/xrdp; \
	fi
sed: 1: "/etc/init.d/xrdp": command i expects \ followed by text

**Comment by NetworkLlama** [comment]
Change the line to:

sed -i .bak 's|BASE|/usr|' /etc/init.d/xrdp; \

This will create backup file /etc/init.d/xrdp.bak.  Alternately, you can remove the -i switch entirely.

**Comment by proski** [comment]
This issue is fully resolved now. The PAM issues are discussed in #166.
