### ISSUE TITLE
window manager exits without errors in ubuntu 18.04

### ISSUE THREAD

**Issue by lisaction** [neutrinolabs/xrdp#1261]
Hi, I set up everything and wasn't able to start sessions via mstsc.
Here is my log.

```
[20181129-11:29:40] [INFO ] A connection received from ::1 port 49560
[20181129-11:29:40] [INFO ] ++ created session (access granted): username lin, ip ::ffff:127.0.0.1:58704 - socket: 12
[20181129-11:29:40] [INFO ] starting Xorg session...
[20181129-11:29:40] [DEBUG] Closed socket 9 (AF_INET6 :: port 5910)
[20181129-11:29:40] [DEBUG] Closed socket 9 (AF_INET6 :: port 6010)
[20181129-11:29:40] [DEBUG] Closed socket 9 (AF_INET6 :: port 6210)
[20181129-11:29:40] [DEBUG] Closed socket 8 (AF_INET6 ::1 port 3350)
[20181129-11:29:40] [INFO ] calling auth_start_session from pid 39307
[20181129-11:29:40] [DEBUG] Closed socket 7 (AF_INET6 ::1 port 3350)
[20181129-11:29:40] [DEBUG] Closed socket 8 (AF_INET6 ::1 port 3350)
[20181129-11:29:40] [INFO ] /usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
[20181129-11:29:41] [CORE ] waiting for window manager (pid 39308) to exit
[20181129-11:29:41] [CORE ] window manager (pid 39308) did exit, cleaning up session
[20181129-11:29:41] [INFO ] calling auth_stop_session and auth_end from pid 39307
[20181129-11:29:41] [DEBUG] cleanup_sockets:
[20181129-11:29:41] [DEBUG] cleanup_sockets: deleting /var/run/xrdp/sockdir/xrdp_chansrv_socket_10
[20181129-11:29:41] [DEBUG] cleanup_sockets: deleting /var/run/xrdp/sockdir/xrdpapi_10
[20181129-11:29:41] [DEBUG] cleanup_sockets: failed to delete /var/run/xrdp/sockdir/xrdpapi_10
[20181129-11:29:41] [INFO ] ++ terminated session:  username lin, display :10.0, session_pid 39307, ip ::ffff:127.0.0.1:58704 - socket: 12
```

The connection log from mstsc window shows
```
connection problem, giving up
some problem
```

I hardly get any useful infromation from the log... Anyone can help? Thank you!

**Comment by sandreas** [comment]
Same here... things i tried (without success - none of these solutions worked):
```
# install xrdp and related packages
sudo apt install -y xrdp gnome-tweak-tool

# replace allowed users in Xwraper.config
sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config

# add policies
sudo bash -c "cat >/etc/polkit-1/localauthority/50-local.d/45-allow.colord.pkla" <<EOF
[Allow Colord all Users]
Identity=unix-user:*
Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
ResultAny=no
ResultInactive=no
ResultActive=yes
EOF

# enable extensions
gnome-shell-extension-tool -e ubuntu-dock@ubuntu.com
gnome-shell-extension-tool -e ubuntu-appindicators@ubuntu.com


# try some other things
sudo apt install -y vino
gsettings set org.gnome.Vino require-encryption false

# increase MaxSessions
sudo vi /etc/xrdp/sesman.ini
# set MaxSessions=500

# reinstall libglib (see https://dynamic.reauktion.de/flugphase/2018/04/24/ubuntu-xrdp-server-black-screen-on-login/)
```

links:
- https://c-nergy.be/blog/?p=11868
- https://www.lifewire.com/setup-ubuntu-remote-desktop-4129666
- https://sourceforge.net/p/xrdp/discussion/389417/thread/1af7d057/?limit=25
- https://askubuntu.com/questions/1031519/xrdp-on-ubuntu-18-04lts
- https://dynamic.reauktion.de/flugphase/2018/04/24/ubuntu-xrdp-server-black-screen-on-login/

**Comment by sandreas** [comment]
In my case it now works, after i installed `xorgxrdp` manually (there were problems with dependencies `xorg-video-abi-23` and `xserver-xorg-core`). 

After that, i used http://c-nergy.be/blog/?p=12043 to get rid of color profile warnings.

```
sudo apt install -y xrdp xorgxrdp xorg-video-abi-23 xserver-xorg-core
cat <<EOF > /tmp/45-allow-colord.pkla
[Allow Colord all Users]
Identity=unix-user:*
Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
ResultAny=no
ResultInactive=no
ResultActive=yes
EOF
sudo mv /tmp/45-allow-colord.pkla /etc/polkit-1/localauthority/50-local.d/
sudo rm /var/crash/*
reboot
```
Now its working for me.

**Comment by q2807c** [comment]
> In my case it now works, after i installed `xorgxrdp` manually (there were problems with dependencies `xorg-video-abi-23` and `xserver-xorg-core`).
> 
> After that, i used http://c-nergy.be/blog/?p=12043 to get rid of color profile warnings.
> 
> ```
> sudo apt install -y xrdp xorgxrdp xorg-video-abi-23 xserver-xorg-core
> cat <<EOF > /tmp/45-allow-colord.pkla
> [Allow Colord all Users]
> Identity=unix-user:*
> Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
> ResultAny=no
> ResultInactive=no
> ResultActive=yes
> EOF
> sudo mv /tmp/45-allow-colord.pkla /etc/polkit-1/localauthority/50-local.d/
> sudo rm /var/crash/*
> reboot
> ```
> 
> Now its working for me.
> 
> _**edit:**_ Since the dependencies of `xorgxrdp` contain `xserver-xorg-core`, but in my case `xserver-xorg-core-hwe` is installed, that seems to be the problem with the dependencies. So to get the more recent release of `xrdp` and `xorgxrdp` you could also use the files from _Ubuntu 19.04_, which worked nicely in my case:
> 
> ```
> cd /tmp
> wget http://archive.ubuntu.com/ubuntu/pool/universe/x/xrdp/xrdp_0.9.9-1_amd64.deb
> sudo dpkg -i xrdp_0.9.9-1_amd64.deb
> wget http://archive.ubuntu.com/ubuntu/pool/universe/x/xorgxrdp/xorgxrdp_0.2.9-1_amd64.deb
> sudo dpkg -i --ignore-depends=xserver-xorg-core xorgxrdp_0.2.9-1_amd64.deb
> 
> # get rid of the color profile messages
> cat <<EOF > /tmp/45-allow-colord.pkla
> [Allow Colord all Users]
> Identity=unix-user:*
> Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
> ResultAny=no
> ResultInactive=no
> ResultActive=yes
> EOF
> sudo mv /tmp/45-allow-colord.pkla /etc/polkit-1/localauthority/50-local.d/
> sudo rm /var/crash/*
> reboot
> ```

This solution fixed my problem too. Do you know the detailed meaning of the configuration file or where can I find such info. Thanks.

**Comment by pktiuk** [comment]
```
wbuser@ubuntu:~$ sudo apt install -y xrdp xorgxrdp xorg-video-abi-23 xserver-xorg-core
Package xorg-video-abi-23 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'xorg-video-abi-23' has no installation candidate
```
This package is not available now
(I am on Ubuntu 20.04)
