### ISSUE TITLE
start bash with parameters

### ISSUE THREAD

**Issue by d-yacenko** [neutrinolabs/xrdp#1269]
Helo.
I have a litle problem. I need start app on xrdp as follows **rdesktop -s "/my/bash/script.sh parameters" ip** , but xrdp run startwm.sh instead my script. I litle bit modificate sources for solution this problem. Patch is in attachments. Could you include something like this in the new release?
[mypatch.patch.zip](https://github.com/neutrinolabs/xrdp/files/2674943/mypatch.patch.zip)

**Comment by metalefty** [comment]
No time for the next release. Next next release at the earliest.

**Comment by d-yacenko** [comment]
ok, of course when it is convenient for you. :)

**Comment by metalefty** [comment]
I'd appreciate if you learn how to use GitHub and submit your patch as a pull request.
