### ISSUE TITLE
what version of microsoft rdp is xrdp compatible with 

### ISSUE THREAD

**Issue by bmullan** [neutrinolabs/xrdp#1272]
I've searched but I can't find anything on the github or the sourceforge forum that definitively says what version of microsoft rdp the xrdp server supports?

I did see a couple issues that had been filed that mentioned an RDP 8.1.x release.

I am asking because I use Guacamole v0.9.14 and in its "connection" configuration screen it references a setting Guacamole calls "**Display Update Virtual Channel (RDP 8.1+)**.   

So I am wondering if xrdp supports that?

thanks in advance
brian

**Comment by jsorg71** [comment]
All features in RDP are negotiated so some RDP 7.1 features are supported and some RDP 4.0 features are not supported.
As far the display, 8.1(GFX channel) is not done yet so the xrdp only support RDP 7.1

**Comment by bmullan** [comment]
Thanks for the information ..!
