### ISSUE TITLE
./configure instructions for MacOS on wiki

### ISSUE THREAD

**Issue by slbayer** [neutrinolabs/xrdp#1275]
Hi folks -

The wiki page here:

https://github.com/neutrinolabs/xrdp/wiki/Building-on-OSX

is really, really helpful, and I've happily run xrdp on my Mac for a couple years. On Mojave, things seem to have changed a bit, or perhaps it's the more recent xrdp releases. The librfxcodec configuration script uses the "nasm" utility, and the version installed in /usr/bin/nasm doesn't seem to do anything useful:

```
$ nasm
nasm: error: unable to find utility "nasm", not a developer tool or in PATH
```

After I installed nasm using MacPorts, and ensured that the newly installed version was first in my path, the instructions given work just fine, even using MacPorts instead of brew.

**Comment by asheenlevrai** [comment]
Nice!

I'd be very happy if you would post instructions on how to install/configure xrdp on macOS mojave anywhere.

Thanks
-a-

**Comment by metalefty** [comment]
Out of scope. See README. But feel free to edit and add new build instructions on that wiki page.

**Comment by IBIT-ZEE** [comment]
> I'd be very happy if you would post instructions on how to install/configure xrdp on macOS mojave anywhere.

Please do so and put the link here ...

**Comment by metalefty** [comment]
Everyone can be the one to post it first! Be someone!
