### ISSUE TITLE
does or could xrdp support single sign on (SSO) 

### ISSUE THREAD

**Issue by bmullan** [neutrinolabs/xrdp#1276]
Does or could xrdp support single sign on (SSO) capability?

The newly released Guacamole v1.0 now supports TOTP (via Google's authenticator), OpenID, CAS etc.

I implement an Guacamole v1.0 on Ubuntu 18.04 with XRDP, XORGXRDP etc in LXD containers that run either a Mate, XFCE4 or Budgie Desktop environment.   I'd like to explore using Guacamole's new TOTP capability but after logging in via Guacamole my connections to the various Desktop "containers" is via xrdp and I'd like to be able to not prompt the users for a login ID and password by xrdp's login screen if that were possible.   So essentially a SSO via Guacamole and the user could then select one of the LXD desktop containers and just be logged in?

I did some searching but so far haven't found anything regarding whether xrdp supports an SSO capability somehow.

thanks for any information
brian

**Comment by doubled1** [comment]
I don't know how XRDP related this is but...

I'm using a very similar setup and do the following

XRDP will use the credentials passed by the RDP client (Guacamole in your case)

In your Guacamole connection:
Set the Username field to ${GUAC_USERNAME}
Set the Password field to ${GUAC_PASSWORD}

Whatever credentials are used to log into Guacamole are passed through to the RDP server.  The usernames and passwords must match though, which is simplest if using LDAP or AD for authentication in both the desktop and Guacamole.

**Comment by bmullan** [comment]
This works for me & my scripts

https://github.com/bmullan/ciab-remote-desktop

I use Guacamole v1.0, xrdp, ubuntu etc

Login w/out using ldap only requires user login to Guacamole & selection on
which connection.

I also recently implemented TOTPNusing google Authenticator on iPhone or
Android but after that still works...
