### ISSUE TITLE
xRDP will not install properly on Ubuntu 18.04

### ISSUE THREAD

**Issue by vinsont70** [neutrinolabs/xrdp#1278]
I've been working eight hours trying to get XRDP to work on  Ubuntu 18.04. I have attempted several different desktop version. Performed a complete remove and manually removed various folders. Lastly I installed a custom installer from here: https://c-nergy.be/blog/?p=12894 but still no go.

x@x:~$ service xrdp restart
PolicyKit daemon disconnected from the bus.
We are no longer a registered authentication agent.
Failed to restart xrdp.service: Message recipient disconnected from message bus without replying

x@x:~$ systemctl status xrdp.service
* xrdp.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)

Please help. Thanks!

**Comment by metalefty** [comment]
The custom installer is not made by xrdp team. Here's not the best place to support it.
