### ISSUE TITLE
Copy/paste issue on Win 10 

### ISSUE THREAD

**Issue by Abinayasandhiya** [neutrinolabs/xrdp#1282]
Hi,

Server details:
RHEL6 and RHEL7

We are facing issue in XRDP - 0.9.7.
Clipboard is not working on Win10 but fails sometimes and works only again after restart.
That means a re-connect does NOT solve the clipboard-problem (this also our experience) – you need to restart the application so all sessions are lost.

Can anyone help us here.

**Comment by Abinayasandhiya** [comment]
Hi @metalefty ,

Process is invoking while the connection of XRDP.

Please find details below:

[root@RHEL7 ~]$ ps -ef | grep xrdp-chansrv
asand 4420  4406  0 08:53 ?        00:00:00 /usr/sbin/xrdp-chansrv
root      5067  4312  0 08:54 pts/8    00:00:00 grep --color=auto xrdp-chansrv
dems 14417 14405  0 Jan23 ?        00:00:00 /usr/sbin/xrdp-chansrv
[root@ulsvtest02 ~]$ dems11q1^C

**Comment by Abinayasandhiya** [comment]
One of our user facing copy/paste issue, but xrdp-chansrv process seems <defunct> like below:

[root@RHEL7 ~]$ ps -ef | grep xrdp-chansrv | grep -i af023788
afrai 58380 58368  0 08:41 ?        00:00:00 [xrdp-chansrv] <defunct>

Did this information help you to find the issue.

**Comment by Abinayasandhiya** [comment]
Hi @metalefty ,

On some cases xrdp-chansrv getting <defunct>.
Can you please provide an idea why this issue occur.

[root@RHEL7~]$ ps -ef | grep xrdp-chansrv | grep -i af023788
af023788 58380 58368  0 08:41 ?        00:00:00 [xrdp-chansrv] <defunct>

After kill all the connected session again clipboard seems working fine.
Since this is not a good approach what we need.

Can you help us on this.

**Comment by Abinayasandhiya** [comment]
> 
> 
> Can you confirm if xrdp-chansrv process is living for the session? There could be two cases. One is xrdp-chansrv living but stucked. The other one is xrdp-chansrv has died for some reasons.

On our case "xrdp-chansrv" seems stuck.

**Comment by Abinayasandhiya** [comment]
Can we get any update here.

Or let us know if you need any more details from our end.

This is quite big issue which is really need to be fixed or documented as Known issue at least with proper reason/cause of the issue.

Can someone please help us on here.

Thanks in Advance.

**Comment by metalefty** [comment]
Thanks, I also think the issue needs to be fixed. I'm thinking of the solution.

**Comment by Abinayasandhiya** [comment]
Thanks for the update.

Please let us know once you get the solution.

**Comment by Abinayasandhiya** [comment]
Hi @metalefty ,

Any update ?

**Comment by Abinayasandhiya** [comment]
Hi @metalefty ,

FYI : https://github.com/neutrinolabs/xrdp/issues/1188#issuecomment-466874018

Between Windows 10 to CentOS 7.6 Copy paste seems working via Xorg session but not via Xvnc.
For my case on some point of time Copy/Paste seems working with both Xorg and Xvnc.
But there is sudden broke down happens, On that point we could see that xrdp-chansrv process becomes defunct state [ still not able to find an root cause of the issue with log files of XRDP ].

**Comment by Abinayasandhiya** [comment]
Hi,

Is there any update/suggestion in this case.

**Comment by soliChen** [comment]
I met the same problem, no matter win7 or win10，users connect to ubuntu server，but some users' clipboard may not work suddenly but others' works fine.

Logs
`(ERROR-19816 /build/fcitx-PSoVA1/fcitx-4.2.9.1/src/lib/fcitx/instance.c:440) Exiting.
** Message: main.vala:131: log directory: /home/aaa/.cache/lxsession/LXDE
** Message: main.vala:132: log path: /home/aaa/.cache/lxsession/LXDE/run.log
(ERROR-19797 /build/fcitx-PSoVA1/fcitx-4.2.9.1/src/module/remote/remote.c:70) Can't open socket /tmp/fcitx-socket-:13: Address already in use
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
No such file or directory: No such file or directory
QDBusConnection: name 'org.a11y.atspi.Registry' had owner '' but we thought it was ':1.1'
No LSB modules are available.
No LSB modules are available.`

**Comment by abdnasee** [comment]
@metalefty 
I'm also facing the same issue reported by Abinaya on clipboard issue
It is crashing the "xrdp-chansrv" service. But the log is not showing this issue and we are doubtful on how to take this issue forward.
The only way from our end what we can do is to kill the service and reconnect the session which is hassle.
We are looking for an alternate solution either to have another version or any workaround that will fix this issue atleast

**Comment by abdnasee** [comment]
@metalefty 
Any update here please on the issue

**Comment by Honghe** [comment]
Sometimes, this is the problem connecting with `rdpclip.exe` of Windows. Try this:
- stop `rdpclip.exe` on Windows 10 Task Manager
- start `rdpclip.exe` 
- restart Remmina

**Comment by metalefty** [comment]
Copy&paste on Win 10 is now working, closing.
