### ISSUE TITLE
Disable the thinclient_drives Mounted Drive?

### ISSUE THREAD

**Issue by Zer0CoolX** [neutrinolabs/xrdp#1283]
I noticed when I rdp into my RHEL 7.6 box running xrdp (installed from EPEL) that it mounts a drive called "thinclient_drives" and displays an icon for it on the desktop.

Is this something that can be removed, not mounted or hidden?

Its not entirely clear to me what its purpose is and I am afraid that users might try and store content in it, either succeeding in moving files across "boundaries" they should not or simply losing their work.

I have searched and found a couple results online with recommendations that appear dated and no longer working. Some of these include ideas in #218, none of which changed anything for me. After each attempt I rebooted the server and then connected to the remote machine to see if the thinclient_drives "drive" was mounted again.

So I guess I have 2 questions:

1. Is the "thinclient_drives" drive required for RDP/xrdp itself to function? Whats its intended purpose?
2. If its not required, is it possible to remove it or at least make users unaware of it? If so, what functionality might one lose by doing so?

Thanks

**Comment by metalefty** [comment]
1. The directory is for drive redirection & clipboard file transfer
2. It is safe to remove the directory but will be created every time you log in via xrdp

**Comment by Zer0CoolX** [comment]
Ok if we are not using those features is there a way to disable the "thinclient_drive" so it is automatically not included/mounted/attached?

Thanks

**Comment by bmullan** [comment]
@Zer0CoolX 
What was the answer to your question:

> Ok if we are not using those features is there a way to disable the "thinclient_drive" so it is automatically not included/mounted/attached?

I have an interest in doing the same thing.

Thanks
Brian

**Comment by EvgenyPrikhodko** [comment]
Hey!
Is there a setting?

**Comment by bmullan** [comment]
> Hey! Is there a setting?

Look at /etc/xrdp/sesman.ini

Near the bottom you will see a section:
 
> [Chansrv]
> ; drive redirection, defaults to xrdp_client if not set
> **FuseMountName=thinclient_drives**
> ; this value allows only the user to acess their own mapped drives.
> ; Make this more permissive (e.g. 022) if required.
> FileUmask=077

You can comment out the "_**FuseMountName=thinclient_drives**_" by changing that line to:

> ; FuseMountName=thinclient_drives

**Comment by matt335672** [comment]
xrdp v0.9.15 and later let you specify `EnableFuseMount=false` in sesman.ini

**Comment by McSh4dow** [comment]
@matt335672 @all I know it's been a while since the last post.
I've set EnableFuseMount=false in [Chansrv] section in sesman.ini. Unfortunately I am still able to transfer files from xrdp server to my client - the other way is being blocked. There is no thinclient_drives mounted.

Is there a way to block the file transfer from xrdp server to the clients? Shouldn't it be done by setting EnableFuseMount to false?

I also tried umount thinclient_drives on logon and also using another mount point (/tmp/FuseMount) with chmod 700, so users cannot access it -> No success...

For these tests I went from Ubuntu 20.04 (focal) to Ubuntu 22.04 (jammy) and updated xrdp (from 0.9.12 to 0.9.17) in the same process.

Thanks for your help and best wishes
McSh4dow

**Comment by matt335672** [comment]
@McSh4dow - how are you transferring the files? Can you give more detail?

Thanks.

**Comment by ztaid** [comment]
Same problem with me, the ACL get Wacked after operation, and locks up and hangs, directory shows ? ? ? ? username and group and permissions.  Unable to access with root , chmod, chown, etc. So tried setfacl, etc, that did not work, tried EnableFuseMount=false in sesman.ini, that did not work.

So lets hack it.

sudo systemctl set-default multi

reboot

cd /home/[username] etc.

chown [username]:[username] thinclient_drives/
chattr +i thinclient_drives/

PROBLEM GONE.
