### ISSUE TITLE
Blank screen from Remmina (Ubuntu). No font from Microsoft Remote Desktop (macOS). 

### ISSUE THREAD

**Issue by lars20070** [neutrinolabs/xrdp#1284]
I followed [this recipe](https://medium.com/@vivekteega/how-to-setup-an-xrdp-server-on-ubuntu-18-04-89f7e205bd4e) and installed xRDP on Ubuntu 18.04.1.

From Remmina (Ubuntu) I get a blank screen. https://github.com/neutrinolabs/xrdp/issues/832
From Microsoft Remote Desktop (macOS) I get no fonts. https://github.com/neutrinolabs/xrdp/issues/1203

Were these two issues fixed?

**Comment by lieff** [comment]
Is this remote server with no GUI installed before xrdp recipe?

**Comment by lieff** [comment]
Hmm, worked for me on Ubuntu 18.10. Even without start startwm.sh modification. Only issue is color profile permissions.
But when I install it on GUI-less server, I have similar issue. Full GUI env must be installed before. Just install
```
sudo apt-get install xfce4
sudo apt-get install xfce4-terminal
sudo apt-get install gnome-icon-theme-full tango-icon-theme
```
is not enough.

**Comment by metalefty** [comment]
Why don't you mention xrdp version?????

**Comment by lars20070** [comment]
`xrdp 0.9.5-2`
Sorry.

**Comment by metalefty** [comment]
You'd also read NEWS.md. That's why I sum up what's changed between releases and I write up the summary every time making a release.

**Comment by lars20070** [comment]
In 0.9.4 it mentions that the blank screen was fixed in build 16273.

After a few minutes I get the message below on the blank screen. What action shall I take? Upgrade to v0.9.9?

![screenshot from 2019-01-25 13-23-57](https://user-images.githubusercontent.com/6149805/51816851-bf4fea80-22c8-11e9-8fac-40e67eccf665.png)

**Comment by Dennis360ict** [comment]
I have the same problem with ubuntu 18.04 connecting to 18.04. Installed xrdp 0.95 from respository and build from source v0.9.9

**Comment by metalefty** [comment]
@Dennis360ict Which issue?
The original reporter @lars20070 mentions two issues in one issue. That makes us confused. 
@lars20070 One issue per one issue, please.

**Comment by metalefty** [comment]
Closing. Create a new issue for each issue. One issue per one issue.
