### ISSUE TITLE
Buiding x11rdp fails on fedora 20

### ISSUE THREAD

**Issue by abregar** [neutrinolabs/xrdp#130]
Building current master on fedora 20 fails with

../build_dir/xorg-server-1.9.3/os/.libs/libos.a(connection.o): In function `ClientAuthorized':
connection.c:(.text+0xb83): undefined reference to `Xserver_client__auth_semaphore'
connection.c:(.text+0xba3): undefined reference to `Xserver_client__auth_semaphore'
../build_dir/xorg-server-1.9.3/os/.libs/libos.a(connection.o):(.note.stapsdt+0x24): undefined reference to `Xserver_client__auth_semaphore'
../build_dir/xorg-server-1.9.3/os/.libs/libos.a(connection.o):(.note.stapsdt+0x88): undefined reference to `Xserver_client__connect_semaphore'
../build_dir/xorg-server-1.9.3/dix/.libs/libdix.a(dispatch.o):(.note.stapsdt+0x24): undefined reference to `Xserver_client__disconnect_semaphore'
../build_dir/xorg-server-1.9.3/dix/.libs/libdix.a(dispatch.o):(.note.stapsdt+0x74): undefined reference to `Xserver_request__done_semaphore'
../build_dir/xorg-server-1.9.3/dix/.libs/libdix.a(dispatch.o):(.note.stapsdt+0xe4): undefined reference to `Xserver_request__start_semaphore'
../build_dir/xorg-server-1.9.3/dix/.libs/libdix.a(events.o): In function `WriteEventsToClient':
events.c:(.text+0x2d10): undefined reference to `Xserver_send__event_semaphore'
../build_dir/xorg-server-1.9.3/dix/.libs/libdix.a(events.o):(.note.stapsdt+0x24): undefined reference to `Xserver_send__event_semaphore'
../build_dir/xorg-server-1.9.3/dix/.libs/libdix.a(resource.o):(.note.stapsdt+0x24): undefined reference to `Xserver_resource__alloc_semaphore'
../build_dir/xorg-server-1.9.3/dix/.libs/libdix.a(resource.o):(.note.stapsdt+0x88): undefined reference to `Xserver_resource__free_semaphore'
../build_dir/xorg-server-1.9.3/dix/.libs/libdix.a(resource.o):(.note.stapsdt+0xe8): undefined reference to `Xserver_resource__free_semaphore'
../build_dir/xorg-server-1.9.3/dix/.libs/libdix.a(resource.o):(.note.stapsdt+0x14c): undefined reference to `Xserver_resource__free_semaphore'
../build_dir/xorg-server-1.9.3/dix/.libs/libdix.a(resource.o):(.note.stapsdt+0x1b0): undefined reference to `Xserver_resource__free_semaphore'
collect2: error: ld returned 1 exit status

**Comment by itamarjp** [comment]
closing
