### ISSUE TITLE
please help Me

### ISSUE THREAD

**Issue by lasaidhari** [neutrinolabs/xrdp#1301]
![eroor konek](https://user-images.githubusercontent.com/34808023/53810878-89b6b500-3f8a-11e9-9a56-f169cd8ac8bc.png)
centos 7

**Comment by Abinayasandhiya** [comment]
We have faced the same issue,  which is fixed by installed all Desktop manager packages.

For us the issue came while invoking "gnome-session" so we have done "yum groupinstall gnome-desktop" which solved the issue for us.

**Comment by raupie** [comment]
Experiencing the same issue running budgie-desktop.
I tried adding `budgie-desktop` to `~/.xsession` and the `/etc/xrdp/startwm.sh` file.

**Comment by ganeshjkale** [comment]
@Abinayasandhiya why you are not using xorgxrdp backend instead of vnc
