### ISSUE TITLE
sad homepage

### ISSUE THREAD

**Issue by mirabilos** [neutrinolabs/xrdp#1305]
A user just complained that the homepage is rather sad, “Aug 15, 2017:  xrdp v0.9.3.1 has been officially released” and pointing to dead Sourceforge.

I see that http://xrdp.sourceforge.net (which we had as Homepage link in the Debian packages) redirects (although only with a 302, why?) to http://www.xrdp.org/ but that site is still in that sad state, even if the “Downloads” link shows 0.9.9 on github.

Also, the Sourceforge address shows up in the code at least thrice in `xrdp/xrdpwin.c`.

**Comment by metalefty** [comment]
@jsorg71 Can you set a redirection www.xrdp.org -> github.com/neutrinolabs/xrdp for the moment?

**Comment by jsorg71** [comment]
I setup to go to
http://neutrinolabs.github.io/xrdp/
That even better, right?
I think we can update that page with a simple pull request.

**Comment by metalefty** [comment]
Looks better, thanks!

**Comment by mirabilos** [comment]
Thanks, looks better-ish, although it doesn’t offer stable release tarballs any more. (Also, should not xorgxrdp be available for development and download as well?)

**Comment by metalefty** [comment]
Created #1314.

**Comment by mirabilos** [comment]
Thanks, I think we’re done here thus now.
