### ISSUE TITLE
Third party static channels not working with xrdp-0.9.9 and xrdp-0.9.10

### ISSUE THREAD

**Issue by ganeshjkale** [neutrinolabs/xrdp#1306]
OS : -Ubuntu Gnome 16.04_x64
Client :- Xubutnu 16.04 x86
Client RDP :- Freerdp 2.0.rc4

Same third party virtual channels were working till xrdp-0.9.7.

Please provide any hint what has been changed.

**Comment by jsorg71** [comment]
Hi @ganeshjkale 
I made some change to channels.  I also change xrdpapi, that's probably what you're using.  I can change it back.  Is your channel implementation available to me or is it too difficult to setup?

**Comment by ganeshjkale** [comment]
@jsorg71 we dont have source code of channel implementation.
Please revert it back if you can.

**Comment by ganeshjkale** [comment]
@jsorg71 closing issue as the developer has recompiled the plugin with new api and problem got resolved.
