### ISSUE TITLE
High bandwidth usage in legacy (non-RemoteFX) mode

### ISSUE THREAD

**Issue by oofnikj** [neutrinolabs/xrdp#1309]
I'm trying to diagnose an issue where xrdp uses very high amounts of bandwidth in classic RDP mode (non RemoteFX), on the order of ~115 Mbit/s in 32bpp mode for a static screen. Tested both with Windows native RDP client and FreeRDP / Remmina 2.0.0.

Server: Ubuntu 16.04.5
xrdp version: 0.9.9 `dea3408a8a`
xorgxrdp version: 0.2.9 `6d2306e06d`

When running freerdp in debug mode, I see this message printed several hundred times per second: 

> [17:24:51:838] [2748:2749] [DEBUG][com.freerdp.core.rdp] - recv Update Data PDU (0x02), length: 8176
> [17:24:51:839] [2748:2749] [DEBUG][com.freerdp.core.rdp] - recv Update Data PDU (0x02), length: 8175
> [17:24:51:840] [2748:2749] [DEBUG][com.freerdp.core.rdp] - recv Update Data PDU (0x02), length: 9594
> [17:24:51:843] [2748:2749] [DEBUG][com.freerdp.core.rdp] - recv Update Data PDU (0x02), length: 8490
> [17:24:51:844] [2748:2749] [DEBUG][com.freerdp.core.rdp] - recv Update Data PDU (0x02), length: 8628
> [17:24:51:845] [2748:2749] [DEBUG][com.freerdp.core.rdp] - recv Update Data PDU (0x02), length: 8201
> [17:24:51:849] [2748:2749] [DEBUG][com.freerdp.core.rdp] - recv Update Data PDU (0x02), length: 9168
> [17:24:51:850] [2748:2749] [DEBUG][com.freerdp.core.rdp] - recv Update Data PDU (0x02), length: 8536
> [17:24:51:851] [2748:2749] [DEBUG][com.freerdp.core.rdp] - recv Update Data PDU (0x02), length: 8982
> [17:24:51:853] [2748:2749] [DEBUG][com.freerdp.core.rdp] - recv Update Data PDU (0x02), length: 8472
> [17:24:51:853] [2748:2749] [DEBUG][com.freerdp.core.rdp] - recv Update Data PDU (0x02), length: 10332

RemoteFX mode uses much less bandwidth (~1-10 Mbit/s), but surprisingly the performance is still worse than classic mode in terms of UI responsiveness . In RFX mode the 'recv Update Data PDU' message disappears.

Is this expected behavior or is something not working right?

**Comment by jsorg71** [comment]
What desktop manger are you using?  It seems like something is always drawing, even if you can't see anything change.  RFX mode does a frame diff so that might be my it's lower.

**Comment by oofnikj** [comment]
I tried playing with my window manager settings (Xfce / Xfwm), and noticed that turning off compositing made a significant improvement. I left it off and installed compton instead, which seems to play much nicer.
To anyone else who may encounter this issue with Xfce, compositing can be disabled by launching "Window Manager Tweaks" -> "Compositor" -> uncheck "Enable display compositing". 

Thanks @jsorg71 for the tip!

**Comment by metalefty** [comment]
This also helped me, thanks!
