### ISSUE TITLE
error starting window manager after KILL -HUP

### ISSUE THREAD

**Issue by dhoffend** [neutrinolabs/xrdp#1315]
Version: xrdp 0.9.8-2~bpo9+1 (debian backports)

We used the following configuration
```
# /etc/xrdp/sesman.ini
[Globals]
...
UserWindowManager=startwm.sh
DefaultWindowManager=startwm.sh
```

After kill -HUP on the main xrdp-sesman process (after a config change for max sessions) we get the following error message.
```
[CORE ] error starting default wm for user .... pid 23400
[CORE ] waiting for window manager (pid 23400) to exit
[DEBUG] errno: 2, description: No such file or directory
```

Maybe the process is running in the wrong path (cwd) after forking or so and doesn't find the script. After changing it to an absolute path everything is running fine. Not sure if it's a packaging bug or code.

**Comment by metalefty** [comment]
I'll test it today. Thanks for reporting.

**Comment by metalefty** [comment]
Confirmed.

**Comment by metalefty** [comment]
reconnect.sh has the same issue.

**Comment by metalefty** [comment]
@dhoffend Can you test?

**Comment by metalefty** [comment]
@TomTrenker you too.

**Comment by TomTrenker** [comment]
Using full path names in sesman.ini fixed the problem that I was seeing.

    On Thursday, March 28, 2019, 1:24:39 a.m. CST, metalefty <notifications@github.com> wrote:  
 
 
@TomTrenker you too.

**Comment by metalefty** [comment]
Just in case, I meant the issue is already fixed and you no londer need to use full path in sesman.ini.

**Comment by TomTrenker** [comment]
Thanks, I understand.

    On Sunday, May 5, 2019, 4:26:38 a.m. CST, metalefty <notifications@github.com> wrote:  
 
 
Just in case, I meant the issue is already fixed and you no londer need to use full path in sesman.ini.
