### ISSUE TITLE
linuxMint, dependencies removed X

### ISSUE THREAD

**Issue by FLamorce** [neutrinolabs/xrdp#1322]
Just wanted to compile xrdp on my LinuxMint 17.3, I started with

sudo apt-get install git autoconf libtool pkg-config gcc g++ make  libssl-dev libpam0g-dev libjpeg-dev libx11-dev libxfixes-dev libxrandr-dev  flex bison libxml2-dev intltool xsltproc xutils-dev python-libxml2 g++ xutils libfuse-dev libmp3lame-dev nasm libpixman-1-dev xserver-xorg-dev

Say, it installed a bunch of stuff, let's reboot to have everything into effect.

But this has removed my X server! Now my system does not boot anymore!?!?!?

**Comment by metalefty** [comment]
You need not to reboot in that case.

**Comment by FLamorce** [comment]
in my apt history I see it has removed the package xserver-xorg-lts-vivid

**Comment by metalefty** [comment]
Nice to solve yourself.

**Comment by FLamorce** [comment]
It's working fine!
