### ISSUE TITLE
sudo service xrdp restart

### ISSUE THREAD

**Issue by roccqqck** [neutrinolabs/xrdp#1324]
when some users r using xorgxrdp or they didnt logout.

someone restart the xrdp
$ sudo service xrdp restart

it wont kill their sessions. 
their sessions r still there, but they cant reconnect to their sessions.
they cant create new sessions.

there r no command to kill their sessions.

we need to reboot the server.

**Comment by metalefty** [comment]
Yo can kill them because you have root privilege via sudo. You're doing `sudo service xrdp restart`. You should have root privilege.

**Comment by roccqqck** [comment]
> Yo can kill them because you have root privilege via sudo. You're doing `sudo service xrdp restart`. You should have root privilege.

in my knowledge there are no root commands to kill other users' xorgxrdp sessions.

can u please teach me how?
