### ISSUE TITLE
keymap issue

### ISSUE THREAD

**Issue by IskhakovR** [neutrinolabs/xrdp#1332]
Hi there,

I have been able to compile the xrdp v8 for sles11 sp4 , but there is an issue for key map.
Here you are error that we have in log file 

 [WARN ] local keymap file for 0x0409 found and dosen't match built in keymap, using local keymap file
[20190411-16:08:21] [ERROR] xrdp_bitmap_load: error bitmap file [/usr/local/share/xrdp/xrdp_logo.bmp] read

We are unable to log in , because there is no reaction on keyboard  at all.
Could you please assist to sort this problem out ?

Thank you in advance,
Ruslan I

**Comment by metalefty** [comment]
What is xrdp v8? We don't have such version.

**Comment by IskhakovR** [comment]
Hi, this one xrdp 0.8.1.
Branch URL is https://github.com/neutrinolabs/xrdp/tree/v0.8

**Comment by metalefty** [comment]
The version is no longer supported.

**Comment by IskhakovR** [comment]
Ok , thanks 

But one more question , is there a chance that xrdp v0.9 can be compiled for SLES 11 SP4 ? 

Thank you in advance
Ruslan I

**Comment by metalefty** [comment]
I'm not really sure about SLES but openSUSE has the latest xrdp.

**Comment by IskhakovR** [comment]
which version of the openSUSE  ?

**Comment by metalefty** [comment]
The version is no longer supported. Closing.
