### ISSUE TITLE
EL7 + EPEL + xrdp == nautilus-desktop using 100% CPU

### ISSUE THREAD

**Issue by pyite** [neutrinolabs/xrdp#1337]
I set up a few xrdp systems lately, using the EL7 "Server with GUI" desktop.  They all work well except for one thing: there is always a nautilus-desktop process consuming 100% of one CPU core.

The best solution I've found is to ditch the desktop icons altogether by running "chmod a-x /usr/bin/nautilus-desktop" but obviously this isn't ideal.

Does anyone have an idea how to make nautilus-desktop behave better?

Thanks,
Mark

**Comment by matt335672** [comment]
This is pretty stale now, so I'm closing it. Feel free to open another issue if this is still a problem.
