### ISSUE TITLE
Client to connect XRDP

### ISSUE THREAD

**Issue by Abinayasandhiya** [neutrinolabs/xrdp#1339]
Hi,

Since there is lot of issue with XRDP to connect via RDP from windows.

Could anyone suggest me any other windows client other than RDP to connect XRDP.

We are using XRDP to connect our RedHat 6 and 7 machine remotely but there is lot of clipboard issue and KDE bar freeze issue.
Have raised multiple queries under concerned team but no update/solution.

So at least we move and give a try with some other client other than RDP.

If anyone have any idea on this would be appreciated.

Thanks!

**Comment by metalefty** [comment]
mstsc or FreeRDP would be best.
