### ISSUE TITLE
Small Login screen

### ISSUE THREAD

**Issue by ssonnenwald** [neutrinolabs/xrdp#1344]
When I bootup Ubuntu 18.04 LTS the xrdp login screen that comes up is very small as well as the fonts.   I know you can customize the size of the dialog, but the fonts etc are still very small in high res.  Is is possible to customize this screen more???

**Comment by metalefty** [comment]
It is possible right now but if someone implement it, login screen can be scaled.

**Comment by metalefty** [comment]
Sorry, not possible. But we accept contributions.
