### ISSUE TITLE
XRDP on Linux Mint not displaying xrdp login screen at boot on Windows 10 Pro VM(Hyper-V)

### ISSUE THREAD

**Issue by ssonnenwald** [neutrinolabs/xrdp#1345]
I have installed the latest xrdp and xorgxrdp on Linux Mint 19.01, which is running on a Microsoft Hyper-v on Windows 10 Pro.  It is up and running and I can see that by running the netstat -an and viewing the listening ports and also viewing the services via sudo service xrdp status and sudo service xrdp-sesman.  I also added a .xsession file with cinnamon2d in it.  My question here is I also have a Ubuntu 18..04.02 LTS VM running and when I boot up that VM I immediately get the xrdp login screen, but not on Linux Mint 19.1.  What is the trick here to make Linux Mint display the xrdp login screen on boot up?  I have spent hours googling all this and trying to get it to work, but with no luck.  Any help would be appreciated.  Thank you in advance.

**Comment by ssonnenwald** [comment]
Getting further along here.   Run this on my windows 10 Pro powershell.

Set-VM -VMName <your_vm_name> -EnhancedSessionTransportType HvSocket

Once I did that I was presented with the xrdp login screen and was able to login.

**Comment by matt335672** [comment]
This is pretty stale now, so I'm closing it. Feel free to open another issue if this is still a problem.
