### ISSUE TITLE
Extend keyboard mapping to support volume keys

### ISSUE THREAD

**Issue by knightly100** [neutrinolabs/xrdp#1347]
When connecting to xrdp (0.9.9-1) on CentOS7 volume keys (e.g.   XF86AudioLowerVolume, XF86AudioRaiseVolume) do not get mapped.  In fact they are mapped to keys 'b' and 'c' respectively.

This seems to be due to a limitation in lang.c where there appears to only be support for a smaller set of keys and scan codes.

Can this be extended?

**Comment by knightly100** [comment]
Hi - Wondering if anybody can comment as to whether this is a feasible request and whether it may be included as a fix at some point?  Thanks

**Comment by metalefty** [comment]
I'll look at it. What keycodes does XF86Audio*Volume have?

**Comment by knightly100** [comment]
Hi.  Thanks!
On the Windows side, vol up generates key code 175, vol down is 174 and vol mute is 173.
If I RDP to another Windows host, these keys work as expected.
If I RDP to a CentOS7 box running xrdp then using xev I see that these keys are being mapped, literally to 'b', 'c' and 'd'.
Let me know of any more info I can provide to help.

**Comment by metalefty** [comment]
RDP scancode: 
VolUp = 48,
VolDown = 46,
VolMute = 32

**Comment by metalefty** [comment]
VolUp = b (48) with ext device_flags
VolDown = c (46) with ext device_flags
VolMute = d (32) with ext device_flags

ext flags needs to be handled.

**Comment by metalefty** [comment]
I'm working on this in my unoccupied hours. Will be fixed *someday*. If someone else wants to fix this, welcome.

**Comment by knightly100** [comment]
Thanks very much. Appreciate all the work.

**Comment by matt335672** [comment]
Should be addressed in devel by #3022 and #3039

**Comment by lukepalmer** [comment]
Thank you for fixing this!
