### ISSUE TITLE
xrdp - 0.9.10 issue on RHEL7

### ISSUE THREAD

**Issue by Abinayasandhiya** [neutrinolabs/xrdp#1349]
Hi,

We have tried to test XRDP - 0.9.10 on RedHat 7 machine.

Whenever we launch a session we couldn't see any process.

FYI:

On xrdp 0.9.7 whenever we launch a new session we could see the running session process like:

[root@uls1 x86_64]$ ps -ef | grep xrdp
avahi     1746     1  0 May17 ?        00:00:00 avahi-daemon: running [xrdp-7.local]
root      2088     1  0 May17 ?        00:00:00 /sbin/dhclient -1 -q -lf /var/lib/dhclient/dhclient--eth0.lease -pf /var/run/dhclient-eth0.pid -H xrdp-7 eth0
root     28360     1  0 15:42 ?        00:00:00 /usr/sbin/xrdp-sesman --nodaemon
root     28361     1  0 15:42 ?        00:00:00 /usr/sbin/xrdp --nodaemon
root     28385 28361  0 15:43 ?        00:00:00 /usr/sbin/xrdp --nodaemon
root     28392 28360  0 15:43 ?        00:00:00 /usr/sbin/xrdp-sesman --nodaemon
asandh 28398 28392  0 15:43 ?        00:00:00 /bin/bash -l /usr/libexec/xrdp/startwm-bash.sh
**asandh 28399 28392  1 15:43 ?        00:00:00 Xvnc :20 -auth .Xauthority -geometry 1364x768 -depth 32 -rfbauth /home/asandhiy/.vnc/sesman_passwd-asandhiy@xrdp-7:20 -bs -nolisten tcp -localhost -dpi 96**
asandh 28415 28392  0 15:43 ?        00:00:00 /usr/sbin/xrdp-chansrv
root     28472 28060  0 15:43 pts/0    00:00:00 grep --color=auto xrdp

But when we launch session using latest version of XRDP - 0.9.10 we could see only xrdp-chansrv process like 

[root@uls01 asandh]$ ps -ef | grep -i xrdp
root     21618     1  0 14:46 ?        00:00:00 /usr/sbin/xrdp-sesman --nodaemon
root     21619     1  0 14:46 ?        00:00:00 /usr/sbin/xrdp --nodaemon
root     23272 21618  0 14:47 ?        00:00:00 /usr/sbin/xrdp-sesman --nodaemon
asandh 23370 23272  0 14:47 ?        00:00:00 /usr/sbin/xrdp-chansrv
root     25397 21619  0 14:48 ?        00:00:00 /usr/sbin/xrdp --nodaemon
root     26475 21619  0 14:49 ?        00:00:00 /usr/sbin/xrdp --nodaemon
root     26498 21619  0 14:49 ?        00:00:00 /usr/sbin/xrdp --nodaemon
root     26531 21618  0 14:49 ?        00:00:00 /usr/sbin/xrdp-sesman --nodaemon
asandh 26610 26531  0 14:49 ?        00:00:00 /usr/sbin/xrdp-chansrv
root     28402 18281  0 14:51 pts/21   00:00:00 grep --color=auto -i xrdp
[root@uls01 asandh]$

Can you please let me know whether this is the expected change or is there any issue.

**Comment by Abinayasandhiya** [comment]
Any idea about below log.

Not able to connect Xorg session and log capture like below:

[20190522-15:38:13] [CORE ] waiting for window manager (pid 50084) to exit
[20190522-15:38:13] [ERROR] X server for display 20 startup timeout
[20190522-15:38:13] [ERROR] another Xserver might already be active on display 20 - see log
[20190522-15:38:13] [DEBUG] aborting connection...
[20190522-15:38:13] [CORE ] window manager (pid 50084) did exit, cleaning up session
[20190522-15:38:13] [INFO ] calling auth_stop_session and auth_end from pid 50077
[20190522-15:38:13] [DEBUG] cleanup_sockets:
[20190522-15:38:13] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_socket_20
[20190522-15:38:13] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdpapi_20
[20190522-15:38:13] [INFO ] ++ terminated session:  username asandhiy, display :20.0, session_pid 50077, ip 10.125.72.1:56250 - socket: 12


Have tried all the possibilities to fix.

**Comment by Ramalama2** [comment]
do you have xorgxrdp installed?
+ change in sesman.ini the xorg parameter, from
param=xrdp/xorg.conf
to
param=/etc/X11/xrdp/xorg.conf

try to remove any driver file from X (or backup them before you delete)
located in
/usr/share/X11/xorg.conf.d/
/etc/X11/xorg.conf.d/

check if you have any X server running on display :20...

Just my recommendation, use ubuntu 18.04... it comes with pulseaudio 11.1
for my findings its the only one distro, where audio redirection works....

You just need to get rid off all ubuntu crap that comes with, the get a small distro like centos :-)
+ ubuntu/debian have TLS 1.3 support in the SSL libs, where Centos 7 will never support TLS 1.3..

Cheers :-)

**Comment by Abinayasandhiya** [comment]
Hi @Ramalama2 

Thanks for the update.

Have tried with your suggested changes but no difference issue is still persist.

:(

**Comment by Abinayasandhiya** [comment]
We have 1000+ RedHat 6 / RedHat 7 servers around glob where user using XRDP for remote session.

But there seems lot of issues and which needs to be fixed.

**Comment by Abinayasandhiya** [comment]
Please let me know below details:

1. XRDP - 0.9.10 i couldn't reconnect the same session on different machine.

For Ex:
if i connect a session in office network I couldn't connect the same session on home network.
It seems sessions getting changed as per the IP i used to login.

[root@ulsv01 ~]$ ps -ef | grep -i xvnc
asandh 35732 35724  0 09:16 ?        00:00:00 Xvnc :12 -auth .Xauthority -geometry 1364x768 -depth 16 -rfbauth /home/asandhiy/.vnc/sesman_passwd-asandh@uls01.emea.nsn-net.net:12 -bs -nolisten tcp -localhost -dpi 96 //session one connected in office net

asandh 38065 38056  0 09:19 ?        00:00:00 Xvnc :13 -auth .Xauthority -geometry 1364x768 -depth 32 -rfbauth /home/asandhiy/.vnc/sesman_passwd-asandh@uls01.emea.nsn-net.net:13 -bs -nolisten tcp -localhost -dpi 96  //session one connected from home net
 
root     39487  9093  0 09:20 pts/0    00:00:00 grep --color=auto -i xvnc

is this is the expected behavior on latest XRDP version.

**Comment by Ramalama2** [comment]
There is in sesman.ini
Policy=
Setting... The thing is, "Default" should be perfect for you,
but in my experiments, xrdp makes always a new session if the screenresolution changes...

I understand the thing with Centos... In our Company its exactly the same :-)

**Comment by Abinayasandhiya** [comment]
Hi @Ramalama2 

Thanks for the update.

Just to confirm:

But on older version of XRDP (0.9.7) we able to reconnect the same session from different computer.

Is this is the feature in latest XRDP version

Do you have any idea on this? if yes it would be appreciate 👍

**Comment by metalefty** [comment]
>  is this is the expected behavior on latest XRDP version.

No, but it is the expected behaviour on the **RHEL** xrdp. RHEL configures a little bit different from ours.

**Comment by Abinayasandhiya** [comment]
Hi @metalefty ,

Thanks for the update.

can we change it?
is there any possible way to reconnect the same session on different machine on RHEL.

**Comment by Abinayasandhiya** [comment]
Also , XOrg is not working , could see below issue is capturing in log:

[20190524-08:22:18] [ERROR] X server for display 11 startup timeout
[20190524-08:22:18] [CORE ] waiting for window manager (pid 4005) to exit
[20190524-08:22:18] [ERROR] X server for display 11 startup timeout
[20190524-08:22:18] [ERROR] another Xserver might already be active on display 11 - see log
[20190524-08:22:18] [DEBUG] aborting connection...
[20190524-08:22:18] [CORE ] window manager (pid 4005) did exit, cleaning up session
[20190524-08:22:18] [INFO ] calling auth_stop_session and auth_end from pid 3997
[20190524-08:22:18] [DEBUG] cleanup_sockets:
[20190524-08:22:18] [INFO ] ++ terminated session:  username asandh, display :11.0, session_pid 3997, ip 10.125.72.1:63265 - socket: 12


Have killed all XRDP related process and still issue is persist.

no Xorg related command is able to execute:

[root@uls01 ~]$ Xorg
Xorg: symbol lookup error: Xorg: undefined symbol: drmFreeDevice
[root@uls01 ~]$

any help here please.

**Comment by Abinayasandhiya** [comment]
Issue has been fixed.

*Workaround:*

xorg-x11-server-Xorg  required latest version of libdrm.
updated has fixed the issue.

**Comment by Abinayasandhiya** [comment]
Hi @metalefty ,

Continue of https://github.com/neutrinolabs/xrdp/issues/1349#issuecomment-495434208

Can we connect the same session from different machine.
please let me know if we have any way for that on RHEL7.

Thanks.

**Comment by metalefty** [comment]
You said "issue has been fixed". What's still the issue?

**Comment by Abinayasandhiya** [comment]
Hi,

https://github.com/neutrinolabs/xrdp/issues/1349#issuecomment-495488280 --> this has been fixed 

Now we would like to know about the reconnecting same session from different machine,

 RHEL7, reconnecting session from different machine is not possible.

Also you said that it seems expected behavior on RHEL7.

I am just asking help that is there any way to reconnect the same session on different machine.
