### ISSUE TITLE
 bind error on port '3350': 22 (Invalid argument)

### ISSUE THREAD

**Issue by IchUseKomplexe** [neutrinolabs/xrdp#1352]
Hey,
so XRDP is not working for me. When I was using Debian 8 it worked but not on Debian 9. The error is

>  Loaded: loaded (/etc/init.d/xrdp; generated; vendor preset: enabled)
   Active: active (exited) since Wed 2019-05-29 18:17:47 CEST; 2min 18s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1076 ExecStop=/etc/init.d/xrdp stop (code=exited, status=0/SUCCESS)
  Process: 1097 ExecStart=/etc/init.d/xrdp start (code=exited, status=0/SUCCESS)
May 29 18:17:47 vmd39172.contaboserver.net systemd[1]: Starting LSB: xrdp (X Remote Desktop Protocol) full server...
May 29 18:17:47 vmd39172.contaboserver.net xrdp-sesman[1109]: (1109)(139641476202880)[DEBUG] libscp initialized
May 29 18:17:47 vmd39172.contaboserver.net xrdp-sesman[1110]: (1110)(139641476202880)[INFO ] starting xrdp-sesman with pid 1110
May 29 18:17:47 vmd39172.contaboserver.net xrdp-sesman[1110]: (1110)(139641476202880)[ERROR] bind error on port '3350': 22 (Invalid argument)
May 29 18:17:47 vmd39172.contaboserver.net xrdp-sesman[1110]: (1110)(139641476202880)[DEBUG] Closed socket 7 (AF_INET6 :: port 0)
May 29 18:17:47 vmd39172.contaboserver.net systemd[1]: Started LSB: xrdp (X Remote Desktop Protocol) full server.
May 29 18:17:49 vmd39172.contaboserver.net xrdp[1113]: (1113)(140589698668288)[INFO ] starting xrdp with pid 1113
May 29 18:17:49 vmd39172.contaboserver.net xrdp[1113]: (1113)(140589698668288)[ERROR] xrdp_listen_main_loop: listen error, possible port already in use
May 29 18:17:49 vmd39172.contaboserver.net xrdp[1113]: (1113)(140589698668288)[DEBUG] Closed socket 11 (AF_INET6 :: port 0)

I changed the Port to other Ports and it still says failed to bind port. You know why?

**Comment by Archie-Ruin** [comment]
No (((

**Comment by gschwind** [comment]
Hello,

Did you double check the output of "netstat -l -n" for already used port ?

Beste regards

**Comment by metalefty** [comment]
No feedback from the reporter, closing.
