### ISSUE TITLE
macOS can not login

### ISSUE THREAD

**Issue by wanggggggg** [neutrinolabs/xrdp#1355]
I install rdp use ：https://github.com/neutrinolabs/xrdp/wiki/Building-on-OSX

my xorg log:

[20190531-13:03:05] [DEBUG] return value from xrdp_mm_connect 1
[20190531-13:03:37] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
[20190531-13:03:42] [DEBUG] Closed socket 23 (AF_INET 127.0.0.1:50083)

**Comment by wanggggggg** [comment]
bash-3.2$ sudo startx
Password:
font_cache: Scanning user font directories to generate X11 font caches
font_cache: Updating FC cache
font_cache: Done
expr: syntax error
expr: syntax error
expr: syntax error
xauth:  file /Users/wangg/.serverauth.7205 does not exist

**Comment by metalefty** [comment]
The startx error is not related to xrdp at all.

BTW, I would say you need to read README.
> Other operating systems such as macOS are not supported so far, but we welcome your contributions.
