### ISSUE TITLE
Black screen when xrdp-sesman process is non root - SOLVED

### ISSUE THREAD

**Issue by asteriosgr** [neutrinolabs/xrdp#1360]
Solved:
Having xrdp, xrdp-sesman fully functional in an unprivileged container.

Solutions : 
chown -R user /etc/xrdp/ directory
and modify logs path in /etc/xrdp.ini and /etc/sesman.ini to /home/user/.
After that, xrdp --nodaemon can be initiated as normal as for xrdp-sesman initiate it like this:
DISPLAY=:10 xrdp-sesman --nodaemon

Only issue would be what happens when display changes for some reason. The issue can be closed.

**Comment by GuillaumeSmaha** [comment]
Wow !! So much thanks  ! Works for me in docker too :)
