### ISSUE TITLE
utf-8 accented characters

### ISSUE THREAD

**Issue by atiertant** [neutrinolabs/xrdp#1362]
there are some strange behaviors in xrdp sessions with utf-8 accented character:

in vi for sample, when typing an accented character like 'é', a space is add after and some time when delete it, a '�' replace it.

other sample: google chrome don't like 'Téléchargements' folder for downloads, it create an other directory: 'T?l?chargements' and can't open file downloaded in directory.

is there a way to handle correctly utf-8 accented characters in xrdp sessions?

**Comment by matt335672** [comment]
This should all be sorted since #2794
