### ISSUE TITLE
Freeze - Soft Lockup - Display Lockup

### ISSUE THREAD

**Issue by DevinCharles** [neutrinolabs/xrdp#1373]
I'm experiencing a periodic "lock-up,"  which happens at a regular interval, approximately every 13s, where the display locks for ~3s, then activity returns to normal. During this time, the mouse cursor is still responsive, however any keyboard input or screen output **appears** to be frozen.

I thought at first this was a disk issue, but it only appears while in an xrdp session. Also, as per below, everything is actually still running, but the **display** is locked-up. I haven't yet tried vnc or teamviewer to see if there's a similar issue.

I wrote a script on the client computer that types the name of a python script which outputs the current time. What's interesting is that the **server is still receives this keyboard input from the client** and displays the correct time (each command is run at ~0.05s, and the intervals remain the same) while it's "locked up," there's just no response from the display for ~3s. 

The issue appears independent of client machine.

I've tried checking the open issues here and the usual google search, but I've had no luck. I've checked a few logs (), but don't see any smoking gun (nothing written at this short of an interval ~13-20s). Any suggestions of specific logs to check, or any other ideas what this might be? I consider myself a novice+ Linux user, so assume any normal checks / setup issues haven't been completed.

Server Info:
-------------------------------------------------
OS: Debian 10 (Buster)
Kernel: 4.19.0-5-amd64
xrdp version: xrdp-0.9.9
CPU: Ryzen 7 1700x

**Comment by jsorg71** [comment]
what client?
which desktop environment?

**Comment by DevinCharles** [comment]
**The clients I've tried:**
- FreeRDP (my go to)
- Remmina
- RD Client (on android device)

Current DE is XFCE 4.12, though it should be noted that KDE was also installed, so there's some "cross pollination" if you will, of apps and settings.

**Comment by jsorg71** [comment]
Client and DE look ok.
I recently had a network issue like this and it was a switch.
Can you verify with iperf?
What happens with pings during these 3 secs?
maybe strace the xrdp process when this happens.
sudo strace -f -p <xrdp-pid>

**Comment by DevinCharles** [comment]
I definitely wouldn't rule out network, I'm not at home and I'm using a *suboptimal* router. I'm not entirely sure what to make of `iperf` results, but that `0 bytes 0bits/s` seems not quite right...

**Serving iperf3 on Client Computer**
ie: RDP Server is 192.168.0.123, RDP Client is 192.168.0.107
```bash
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 192.168.0.123, port 53886
[  5] local 192.168.0.107 port 5201 connected to 192.168.0.123 port 53888
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec  6.91 MBytes  58.0 Mbits/sec                  
[  5]   1.00-2.00   sec  7.26 MBytes  60.9 Mbits/sec                  
[  5]   2.00-3.00   sec  4.24 MBytes  35.6 Mbits/sec                  
[  5]   3.00-4.00   sec  1014 KBytes  8.31 Mbits/sec                  
[  5]   4.00-5.00   sec  1.64 MBytes  13.8 Mbits/sec                  
[  5]   5.00-6.00   sec  2.33 MBytes  19.5 Mbits/sec                  
[  5]   6.00-7.00   sec  5.99 MBytes  50.3 Mbits/sec                  
[  5]   7.00-8.00   sec  7.94 MBytes  66.6 Mbits/sec                  
[  5]   8.00-9.00   sec  7.74 MBytes  64.9 Mbits/sec                  
[  5]   9.00-10.00  sec  8.03 MBytes  67.4 Mbits/sec                  
[  5]  10.00-10.06  sec   452 KBytes  63.3 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  5]   0.00-10.06  sec  57.0 MBytes  47.5 Mbits/sec  1052             sender
[  5]   0.00-10.06  sec  53.5 MBytes  44.6 Mbits/sec                  receiver
```

**Listening to Client from Server**
```bash
Connecting to host 192.168.0.107, port 5201
[  5] local 192.168.0.123 port 53888 connected to 192.168.0.107 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  8.70 MBytes  72.9 Mbits/sec    0    372 KBytes       
[  5]   1.00-2.00   sec  8.27 MBytes  69.4 Mbits/sec    0    742 KBytes       
[  5]   2.00-3.00   sec  5.00 MBytes  41.9 Mbits/sec  600    554 KBytes       
[  5]   3.00-4.00   sec  0.00 Bytes   0.00 bits/sec   376    139 KBytes       
[  5]   4.00-5.00   sec  2.50 MBytes  21.0 Mbits/sec   32   56.6 KBytes       
[  5]   5.00-6.00   sec  2.50 MBytes  21.0 Mbits/sec   12   55.1 KBytes       
[  5]   6.00-7.00   sec  6.25 MBytes  52.4 Mbits/sec   32    102 KBytes       
[  5]   7.00-8.00   sec  7.50 MBytes  62.9 Mbits/sec    0    150 KBytes       
[  5]   8.00-9.00   sec  7.50 MBytes  62.9 Mbits/sec    0    185 KBytes       
[  5]   9.00-10.00  sec  8.75 MBytes  73.4 Mbits/sec    0    216 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  57.0 MBytes  47.8 Mbits/sec  1052             sender
[  5]   0.00-10.00  sec  53.5 MBytes  44.9 Mbits/sec                  receiver
```

**Comment by DevinCharles** [comment]
I've been using the *nouveau* driver, just now installed the *nvidia* drivers, the display lags seem to be gone, so I think I'll close this.
