### ISSUE TITLE
Fixed Xvnc Password

### ISSUE THREAD

**Issue by Ramalama2** [neutrinolabs/xrdp#1374]
Hi, is it somehow possible to make a fixed Xvnc Session password? :-)

**Comment by metalefty** [comment]
I don't get it. You can authenticate your system password via xrdp.

**Comment by Ramalama2** [comment]
Yeah you dont get it :-)

xrdp-sesman generates a random password for each Xvnc session, located in 
$HOME/.vnc/sesman_passwd-$USER@tsrv:$DISPLAY

The thing is, if you modify sesman.ini and comment out
; param=-localhost
in the Xvnc section, you are able to connect via any vnc client to the running session....

The problem is, Xvnc (at least tigervnc's version of Xvnc) does not support guestpassword/adminpassword or anything else except "rfbauth"

So you have the problem that
$HOME/.vnc/sesman_passwd-$USER@tsrv:$DISPLAY
password changes everytime and i need always to decrypt it, to connect with an vnc client to that session.

There is no other way to get 2 users connected to the same session (for example if user 1 needs help)

Or do i miss something, is there a way to connect to a already running session to help User1 ?

So thats why im asking if its possible to make that Xvnc "rfbauth" password somehow not random generated?

i fond in the sources where the password gets generated, but if i put a static password there, it breaks xrdp to Xvnc connection....

Cheers :-)

**Comment by metalefty** [comment]
> So thats why im asking if its possible to make that Xvnc "rfbauth" password somehow not random generated?

It is possible but impossible the current xrdp as-is. Such uses are out of our scope. There will be some workarounds.

**Comment by Ramalama2** [comment]
Thanks!!
But ive solved it.
I made an script that monitors Xvnc sessions using pgrep&ps,
that scripts grabs username, session time, rfbauth file and decrypts the password, and the listening port of xvnc....
Then it write to an www folder files for each user, and php outputs it on an website.

Ive made that extremely secure, so that you cant access anything from the web if you are not authentificated and so on...

Than there is an other script, that gets started with the user session, and kills the session + all user tasks if the user disconnets/kill his rdp session (so that the script above doesnt see sessions that are idle)

Works extremely awesome.

It just taked me a whole week to script that all...

However, thats not a solution for everyone, just a workaround, that an admin/supporter, can connect to the users session and help him...

Cheers:-)

**Comment by llhua2329** [comment]
@Ramalama2 I got the same problem, I want to know how to decrypt the password in $HOME/.vnc/sesman_passwd-$USER@tsrv:$DISPLAY. 
Thank you.

**Comment by Ramalama2** [comment]
That was 2 years ago 😂
Im working in another company already and don't have access to my old scripts 🙈
Basically if it helps you, i found online a script that decrypts the passwords. That part was relatively easy. And in addition to that i made a wrapper around that script, but you can call it from php or whatever you like too.

Please don't ask me where i found it, it's too long ago for my brain and since then i did a ton of other things 🤦 @llhua2329

**Comment by llhua2329** [comment]
@Ramalama2 Thanks reply, 2 years is really too long for memory. I will continue google. Thank you all the same
