### ISSUE TITLE
need an excessive delay_ms 

### ISSUE THREAD

**Issue by feenberg** [neutrinolabs/xrdp#1375]
We are testing xrdp on a dual socket 128GB server and find that we have to set delay_ms to a very large value (~20000ms) to reliably get a connection. It isn't as if the server is overloaded, small applications load in a fraction of a second, firefox in 5 seconds  and characters echo instantly. Most of the time delay_ms=4000ms is enough, but sometimes much more is required.  Is there any solution?  I guess I am a little surprised that a race condition like this wouldn't be addressed with an automatic retry.  Is there any way to do that?

The server is running Scientific Linux  7.6 with Linux kernel 3.10.0  but home directories and all executables are on NFS mounted partitions. Is that the problem?  The desktop is Mate.

**Comment by matt335672** [comment]
This is pretty stale now, so I'm closing it. Feel free to open another issue if this is still a problem.
