### ISSUE TITLE
Xrdp-Session (Xorg) Multiuser Session

### ISSUE THREAD

**Issue by Ramalama2** [neutrinolabs/xrdp#1376]
Hi, ive made it working with Xvnc, but now i want a solution for Xrdp too.

What?:
A supporter should be able to connect to an already running xrdp session, to help the user.
(At the moment User1 gets kicked, if someone else connect)

Here is my Solution for Xvnc:
https://github.com/neutrinolabs/xrdp/issues/1374

Now i need one for xorgxrdp.

The problem is, i dont have even an idea, how to make this possible.
Does anyone have some hints or ideas?

Cheers:-)

**Comment by metalefty** [comment]
It is possible but xrdp is not designed for such usage because xrdp is a terminal service, not a remote assistance. Drive redirection feature is not intended to be mounted from miltiple clients at the same time. We xrdp team don't support doing that but this should help you.

See: https://github.com/neutrinolabs/xrdp/issues/883

**Comment by Ramalama2** [comment]
Nice, thank you very much!

Will try out :-)

**Comment by Ramalama2** [comment]
Im a bit stupid in C, my proble is the code changed over time, so i dont know if i should just comment out everything that is in the "if (dev->clientConTail != NULL)" section.

New Code:
```
#if 1
    if (dev->clientConTail != NULL)
    {
        /* Only allow one client at a time */
        LLOGLN(0, ("rdpClientConGotConnection: "
                   "marking only clientCon %p for disconnect",
                   dev->clientConTail));
        dev->clientConTail->connected = FALSE;
    }
```
Old Code:
```
#if 1
    if (dev->clientConTail != NULL)
    {
        LLOGLN(0, ("rdpClientConGotConnection: disconnecting only clientCon"));
        rdpClientConDisconnect(dev, dev->clientConTail);
        dev->clientConHead = NULL;
        dev->clientConTail = NULL;
    }
```

Can you help me out here?

Cheers :-)

**Comment by Ramalama2** [comment]
Or should i just change it simply to:
```
#if 0
    if (dev->clientConTail != NULL)
    {
        rdpClientConDisconnect(dev, dev->clientConTail);
        dev->clientConHead = NULL;
        dev->clientConTail = NULL;
    }
```

Thats what i think, but i dont know if i break something else.... sry :-(
