### ISSUE TITLE
password authentication error 

### ISSUE THREAD

**Issue by muse117** [neutrinolabs/xrdp#1380]
Hi，I use xorgxrdp and xvnc mode joining session, Report the "Authentication error". The neutrinordp is good.
![微信截图_20190724164521](https://user-images.githubusercontent.com/9733486/61783700-db2ce700-ae3a-11e9-90be-894b0063a03f.png)

**Comment by metalefty** [comment]
It's not our bug. It also occurs with VNC. Should be fixed in upstream.

https://bugzilla.redhat.com/show_bug.cgi?id=1149893
https://github.com/TurboVNC/turbovnc/issues/47
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/273

**Comment by muse117** [comment]
I did not have this problem with the yum installation. this problem is through compile source.
