### ISSUE TITLE
Large fonts 

### ISSUE THREAD

**Issue by Slonik923** [neutrinolabs/xrdp#1383]
I generated fonts using fontdump utility, but when I change size to anything bigger than 12, fonts are either generated or drawn incorrectly. I tried all the fonts, with same result.
Image with "DejaVu Sans" size 14 font:
![1565170083530 remmina-2019-8-14-11:7:51,042483](https://user-images.githubusercontent.com/18482995/63016938-45aed100-be95-11e9-94ed-9a8a94ea3eba.png)

**Comment by metalefty** [comment]
This has been implemented by #2341.
