### ISSUE TITLE
about view desktop of connected users

### ISSUE THREAD

**Issue by hubutui** [neutrinolabs/xrdp#1385]
This [wiki](https://github.com/neutrinolabs/xrdp/wiki/view-desktop-of-connected-users) shows us how to view desktop of connected user (Xvnc on?). But it's not well documented. Another solution, one could use `pgrep -a vnc` to see all  vnc related processes. We could get something like this:
```text
34711 Xvnc :11 -auth .Xauthority -geometry 1920x1052 -depth 32 -rfbauth /home/USER//.vnc/sesman_passwd-USER@lab-linux-06:11 -bs -nolisten tcp -localhost -dpi 96
```
OK, xrdp or xrdp-sesman start Xvnc on port `:11` in localhost (to the remote machine).

Not sure how to check xorgxrdp connection, maybe `journalctl -u xrdp-sesman` could tell us something.

**Comment by metalefty** [comment]
The wiki page is not created by we xrdp developers. We do not gurarantee if it works.
