### ISSUE TITLE
Package installer version problem 1.20.4

### ISSUE THREAD

**Issue by derbetakevin** [neutrinolabs/xrdp#1391]
The CentOS package installer reports a package error during installation.
Error: Package: xorgxrdp-0.2.10-4.el7.x86_64 (epel)
            Required: xorg-x11 server-xorg (x86-64) = 1.20.4
            Installed: xorg-x11-server-Xorg-1.20.1-5.6.el7_6.x86_64 (@updates)
                xorg-x11-server-Xorg (x86-64) = 1.20.1-5.6.el7_6
            Available: xorg-x11-server-Xorg-1.20.1-3.el7.x86_64 (base)
                xorg-x11-server-Xorg (x86-64) = 1.20.1-3.el7
            Available: xorg-x11-server-Xorg-1.20.1-5.el7.x86_64 (updates)
                xorg-x11-server-Xorg (x86-64) = 1.20.1-5.el7
            Available: xorg-x11-server-Xorg-1.20.1-5.1.el7.x86_64 (updates)
                xorg-x11-server-Xorg (x86-64) = 1.20.1-5.1.el7
            Available: xorg-x11-server-Xorg-1.20.1-5.2.el7_6.x86_64 (updates)
                xorg-x11-server-Xorg (x86-64) = 1.20.1-5.2.el7_6
            Available: xorg-x11-server-Xorg-1.20.1-5.3.el7_6.x86_64 (updates)
                xorg-x11-server-Xorg (x86-64) = 1.20.1-5.3.el7_6

**Comment by metalefty** [comment]
Dup of #1378

**Comment by metalefty** [comment]
... and #1119
