### ISSUE TITLE
Keymap don't apply when there is more than one km-000XX.ini file in /etc/xrdp

### ISSUE THREAD

**Issue by DevCentre** [neutrinolabs/xrdp#1392]
As title states: Keymap don't apply when there is more than one km-000XX.ini file in /etc/xrdp

Also, i had to increase the permissions to the one file i kept (km-00000409.ini) to 755 to get it work.

Sorry if this is duplicated. Haven't found anything similar in issues section.

PS. Using CentOS 7 and lastest xrdp (0.9.10)

**Comment by matt335672** [comment]
Closing this - no-one's looked at it in 5 years, and things have moved on a bit since then.
