### ISSUE TITLE
Ubuntu 18.04, unable to get connection to the message bus session

### ISSUE THREAD

**Issue by owidat** [neutrinolabs/xrdp#1394]
ubuntu xrdp windows 10 gui not working, after login from Windows 10 RDP (after select Xorg and input name/password), I get the following error, then after that I get a black screen:
"unable to get connection to the message bus session"
![image](https://user-images.githubusercontent.com/6874904/63636162-6ab0fa00-c674-11e9-8721-0c3d942f31d0.png)

```
root@DBA-PC:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

root@DBA-PC:~# xrdp -v
xrdp: A Remote Desktop Protocol server.
Copyright (C) Jay Sorg 2004-2014
See http://www.xrdp.org for more information.
Version 0.9.5
```

**Comment by matt335672** [comment]
I'm closing this as it's remained unanswered.

@owidat - feel free to re-raise it if it's still a problem.
