### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by iouwon** [neutrinolabs/xrdp#1395]
I have my xrdp server running on ubuntu 18.04 and i've configured systemd to get to multi-user.target so nobody is logged on and x is not running, but when I try to remote using Xorg it connects ok and starts an x session but displays it on the monitor of the server rather than the remote client i'm connecting from

**Comment by bmullan** [comment]
@iouwon you might try my CIAB project out.   It installs via a set a bash scripts and uses:

- Guacamole
- Mysql
- NGINX
- Tomcat
- XRDP

Installation is mostly automatic as you will get prompted a few times for things like mysql pswd, new User ID etc and should be done on a new/clean ubuntu 18.04 Server, VM or Cloud Instance.

It installs the above in an LXD Ubuntu 18.04 container (ciab-guac) on the Ubuntu 18.04 Host/Server/VM.   The ciab-guac container is intended for the CIAB Admin use to create Guacamole "connections" to Windows or other XRDP enabled Ubuntu Desktop machines (local or remote)

It also creates a 2nd LXD  Ubuntu 18.04 container (CN1) where the "users" Desktops will be.

Both the above containers have the Ubuntu MATE Desktop installed.

All remote users (can be local too if the above is all installed in  a VM) need for access is any HTML5 enabled Browser.

I'm in the middle of a new update for my Github but don't have it uploaded yet but the current one works fine and has been installed many times.

It takes about 30-50 minutes to install depending on your "Host" system (SSD vs Spinning Disk, how many cores, memory etc).

You can read about it on my Github:
https://github.com/bmullan/ciab-remote-desktop

**Comment by iouwon** [comment]
I'm just interested in understanding what's going wrong, as in my OP

**Comment by matt335672** [comment]
I'm closing this as it remains unanswred.

@iouwon - feel free to open a new issue if you're still experiencing this.
