### ISSUE TITLE
Issue In XRDP Installation

### ISSUE THREAD

**Issue by mhzia** [neutrinolabs/xrdp#1402]
![xrdp](https://user-images.githubusercontent.com/54584790/64116765-a2265180-cdac-11e9-9767-ea92a6556b8e.png)
how i can resolve this issue, anyone can please help me.

**Comment by metalefty** [comment]
Dup of #1378, #1246, #1391, #1119.

**Comment by metalefty** [comment]
Report to the repository manager, not us.
