### ISSUE TITLE
Can i restrict drives redirection and clipboard transfer?

### ISSUE THREAD

**Issue by AlexNikolaenko** [neutrinolabs/xrdp#1404]
Centos + XRDP.
Can I restrict for users local drive redirection and clipboard transfer for security reason ?

**Comment by evanlinde** [comment]
You can disable both features by modifying `/etc/xrdp/xrdp.ini`. 

In the `[Channels]` section, set `rdpdr=false` to disable drive redirection and `cliprdr=false` to disable clipboard redirection.

Then restart your xrdp service to use the new settings.

**Comment by AlexNikolaenko** [comment]
Thanks! That what I need.

**Comment by howardandlili** [comment]
Thanks! That what I need.
