### ISSUE TITLE
Ubuntu 18.04 PAM BUG 

### ISSUE THREAD

**Issue by jfrazee216** [neutrinolabs/xrdp#1406]
We have discovered that there is a bug with PAM in Ubuntu 18.04 when using xrdp. 

If you kill your xrdp session instead of logging out properly then it registers as a failure in /etc/pam.d/common-auth 

If you do this 5 consecutive times then you lock yourself out.

Our workaround was to change deny=5 to 50000 in /etc/pam.d/common-auth

**Comment by evanlinde** [comment]
This may be a duplicate of #262

**Comment by metalefty** [comment]
Yes, it is already reported and on the ToDo List.
