### ISSUE TITLE
Xfce Debian Missing Menu Items

### ISSUE THREAD

**Issue by ameeno** [neutrinolabs/xrdp#1407]
Hello, I am using Debian 10 and also tried debian sid (september 2019)

with XFCE4 installed and .xinitrc setup to exec startxfce4,

if i log into xfce without xrdp i see the full xfce interface and menu including settings appearance ect,

however withxrdp login much of the menu is missing.

what is causing this?

**Comment by metalefty** [comment]
Cen you share us the screenshots?

**Comment by metalefty** [comment]
No feedback from the reporter, closing.

**Comment by metalefty** [comment]
When you're back, leave comment on this. Will reopen.
