### ISSUE TITLE
recording via rdpsnd should be completely disabled by switch

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#1409]
As reported on xrdp-jp group, one of the connectivity issues with Wyse client become clear.
https://groups.google.com/forum/#!topic/xrdp-jp/eh81BoBgz68

Wyse clients seem a little bit stricter. Wyse clients will disconnect when received unknown PDU.  xrdp sends SNDC_REC_NEGOTIATE(39) in `sound_send_server_input_formats` and this causes disconnection.

Recording via rdpsnd should be completely disabled by switch to be RDP compliant.

**Comment by jsorg71** [comment]
created #1427 for this

**Comment by metalefty** [comment]
Thanks, I'll ask the original reporter to test it.

**Comment by metalefty** [comment]
It works fine with Wyse client.
