### ISSUE TITLE
copying to the X clipboard causes disconnect from tightvnc

### ISSUE THREAD

**Issue by jlapeyre** [neutrinolabs/xrdp#141]
Calling XStoreBuffer() causes a disconnect when using tightvnc. This happens
on at least two linux architectures and with several clients.
This bug was reported on debian bts in 2010. I also see the same bug.
I use a workaround that adds a single line to vnc.c ignoring a particular error.
This stops the disconnect, but does not fix the bug.
A detailed discussion can be found at

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=600543

**Comment by asmwarrior** [comment]
I do exact the same steps of installing xrdp and tigervnc under CentOS 6.7, see [Install XRDP Remote Desktop to CentOS 6.5 » Ramblings of an IT Guy.](http://ajmatson.net/wordpress/2014/01/install-xrdp-remote-desktop-to-centos-6-5/). Basically, it is xrdp 0.6.1 official release.

I also see a quite similar bug, it looks like vncconfig is not running, so basically the clipboard is not supported as stated by the vncconfig document. I can manually run vncconfig, but after that if I copy anything, the session get disconnected. I see other people also state this bug in the wepage here: [Remote Desktops with VNC and RDP | SysteMajik Consulting](https://www.systemajik.com/blog/remote-desktops-with-vnc-and-rdp/)

> Were you able get clipboard sharing to work with xrdp? I read somewhere that you need to run “vncconfig -nowin” for this and confirmed from the man page that it should work, but the first time I ran it, the session got disconnected. I was able to connect back, but whenever I try to copy something, the session gets disconnected, so I ended up killing vncconfig.

Any one know how to solve this issue? Do I need to use a git version of xrdp? Thanks.

**Comment by asmwarrior** [comment]
From a comment in #162, see [on 24 Feb 2015](https://github.com/neutrinolabs/xrdp/issues/162#issuecomment-75706177), some guy suggest using x11rdp instead of xvnc, so my question is that dose xrdp not support clipboard if xvnc backend is used?

**Comment by asmwarrior** [comment]
I find another similar bug report in xrdp's developer maillist, but without any response, see here: [xrdp-0.6.1: Clipboard doesn't work without vncconfig, with it disconnects (and also doesn't work)](http://permalink.gmane.org/gmane.network.rdesktop.xrdp.devel/1930)

**Comment by JohnstonJ** [comment]
I had similar problems a couple months back with xrdp and/or X2Go in combination with tightvnc, if I remember right.  Part of the problem is that tightvnc is basically abandoned now with no recent releases/maintenance.  It's not a good choice.

Try using TigerVNC.  It seems to be currently-maintained and it fixed some of the weird X server problems I was having, including this one.  For some reason it's not in the Ubuntu package repositories but TigerVNC has .deb files you can download.

**Comment by asmwarrior** [comment]
Hi, JohnstonJ, when using the latest TigerVNC(the preview binary 1.70), this issue still exists.

**Comment by metalefty** [comment]
Merging into #755.
