### ISSUE TITLE
Failed to load xorg driver modules on Arch Linux

### ISSUE THREAD

**Issue by shangjiaxuan** [neutrinolabs/xrdp#1411]
I was using trying to use hyper-v enhanced mode in a virtual machine installed on a usb hard drive. (I was also booting from the drive via uefi.) The normal hyper-v functions just fine with a user configured to use the fbdev driver for screen output.

When using xrdp, however, an error says that it cannot detect devices, and `/var/log/Xorg.0.log` complains about missing symbols in driver files.

    [  1271.811] (WW) Failed to open protocol names file lib/xorg/protocol.txt
    [  1271.826] 
    X.Org X Server 1.20.5
    X Protocol Version 11, Revision 0
    [  1271.863] Build Operating System: Linux Arch Linux
    [  1271.876] Current Operating System: Linux shangjiaxuan-xps-15 5.2.14-arch2-1-ARCH #1 SMP PREEMPT Thu Sep 12 10:42:38 UTC 2019 x86_64
    [  1271.876] Kernel command line: initrd=\intel-ucode.img initrd=\initramfs-linux.img root=UUID=5168af1e-c1aa-4a97-9f78-083df641df84 rw mem_sleep_default=deep rcutree.rcu_idle_gp_delay=1 video=hyperv_fb:1600x900
    [  1271.906] Build Date: 30 June 2019  09:52:01AM
    [  1271.921]  
    [  1271.936] Current version of pixman: 0.38.4
    [  1271.967] 	Before reporting problems, check http://wiki.x.org
    	to make sure that you have the latest version.
    [  1271.967] Markers: (--) probed, (**) from config file, (==) default setting,
    	(++) from command line, (!!) notice, (II) informational,
    	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
    [  1272.032] (==) Log file: "/var/log/Xorg.0.log", Time: Mon Sep 16 14:57:39 2019
    [  1272.049] (==) Using config file: "/etc/X11/xorg.conf"
    [  1272.066] (==) Using config directory: "/etc/X11/xorg.conf.d"
    [  1272.083] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
    [  1272.083] (**) Option "defaultserverlayout" "Dell XPS 15 7590 Default"
    [  1272.083] (++) ServerLayout "Xrdp-X11-Server"
    [  1272.083] (**) |-->Screen "Screen (xrdpdev)" (0)
    [  1272.083] (**) |   |-->Monitor "Monitor"
    [  1272.083] (**) |   |-->Device "Video Card (xrdpdev)"
    [  1272.083] (**) |   |-->GPUDevice "Video Card (xrdpdev)"
    [  1272.083] (**) |   |-->GPUDevice "card0 (Intel UHD Graphics 630)"
    [  1272.083] (**) |   |-->GPUDevice "card1 (NVIDIA GeForce GTX1650)"
    [  1272.083] (**) |-->Input Device "xrdpMouse"
    [  1272.083] (**) |-->Input Device "xrdpKeyboard"
    [  1272.083] (**) Option "DontVTSwitch" "on"
    [  1272.083] (**) Option "AutoAddDevices" "off"
    [  1272.083] (**) Not automatically adding devices
    [  1272.083] (==) Automatically enabling devices
    [  1272.083] (==) Automatically adding GPU devices
    [  1272.083] (==) Automatically binding GPU devices
    [  1272.083] (==) Max clients allowed: 256, resource mask: 0x1fffff
    [  1272.083] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/misc".
    [  1272.083] 	Entry deleted from font path.
    [  1272.083] 	(Run 'mkfontdir' on "/usr/share/fonts/misc").
    [  1272.083] (WW) The directory "/usr/share/fonts/OTF" does not exist.
    [  1272.083] 	Entry deleted from font path.
    [  1272.084] (WW) The directory "/usr/share/fonts/Type1" does not exist.
    [  1272.084] 	Entry deleted from font path.
    [  1272.084] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/misc".
    [  1272.084] 	Entry deleted from font path.
    [  1272.084] 	(Run 'mkfontdir' on "/usr/share/fonts/misc").
    [  1272.084] (WW) The directory "/usr/share/fonts/OTF" does not exist.
    [  1272.084] 	Entry deleted from font path.
    [  1272.084] (WW) The directory "/usr/share/fonts/Type1" does not exist.
    [  1272.084] 	Entry deleted from font path.
    [  1272.084] (**) FontPath set to:
    	/usr/share/fonts/TTF,
    	/usr/share/fonts/100dpi,
    	/usr/share/fonts/75dpi,
    	/usr/share/fonts/TTF,
    	/usr/share/fonts/100dpi,
    	/usr/share/fonts/75dpi
    [  1272.084] (**) ModulePath set to "/usr/lib/xorg/modules"
    [  1272.084] (II) Module ABI versions:
    [  1272.084] 	X.Org ANSI C Emulation: 0.4
    [  1272.084] 	X.Org Video Driver: 24.0
    [  1272.084] 	X.Org XInput driver : 24.1
    [  1272.084] 	X.Org Server Extension : 10.0
    [  1272.084] (++) using VT number 1
    
    [  1272.086] (II) systemd-logind: took control of session /org/freedesktop/login1/session/_31
    [  1272.086] (II) no primary bus or device found
    [  1272.086] (WW) Open ACPI failed (/var/run/acpid.socket) (No such file or directory)
    [  1272.086] (II) "glx" will be loaded. This was enabled by default and also specified in the config file.
    [  1272.086] (II) LoadModule: "glx"
    [  1272.086] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
    [  1272.087] (II) Module glx: vendor="X.Org Foundation"
    [  1272.087] 	compiled for 1.20.5, module version = 1.0.0
    [  1272.087] 	ABI class: X.Org Server Extension, version 10.0
    [  1272.087] (II) LoadModule: "vnc"
    [  1272.087] (II) Loading /usr/lib/xorg/modules/extensions/libvnc.so
    [  1272.093] (II) Module vnc: vendor="TigerVNC Project"
    [  1272.093] 	compiled for 1.20.5, module version = 1.0.0
    [  1272.093] 	Module class: X.Org Server Extension
    [  1272.093] 	ABI class: X.Org Server Extension, version 10.0
    [  1272.093] (II) LoadModule: "xrdpdev"
    [  1272.093] (II) Loading /usr/lib/xorg/modules/drivers/xrdpdev_drv.so
    [  1272.093] (EE) Failed to load /usr/lib/xorg/modules/drivers/xrdpdev_drv.so: /usr/lib/xorg/modules/drivers/xrdpdev_drv.so: undefined symbol: rdpRRModeDestroy
    [  1272.093] (EE) Failed to load module "xrdpdev" (loader failed, 0)
    [  1272.093] (II) LoadModule: "intel"
    [  1272.094] (II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so
    [  1272.094] (II) Module intel: vendor="X.Org Foundation"
    [  1272.094] 	compiled for 1.20.5, module version = 2.99.917
    [  1272.094] 	Module class: X.Org Video Driver
    [  1272.094] 	ABI class: X.Org Video Driver, version 24.0
    [  1272.094] (II) LoadModule: "nvidia"
    [  1272.094] (II) Loading /usr/lib/xorg/modules/drivers/nvidia_drv.so
    [  1272.094] (II) Module nvidia: vendor="NVIDIA Corporation"
    [  1272.094] 	compiled for 1.6.99.901, module version = 1.0.0
    [  1272.094] 	Module class: X.Org Video Driver
    [  1272.094] (II) LoadModule: "xrdpmouse"
    [  1272.094] (II) Loading /usr/lib/xorg/modules/input/xrdpmouse_drv.so
    [  1272.094] (EE) Failed to load /usr/lib/xorg/modules/input/xrdpmouse_drv.so: /usr/lib/xorg/modules/input/xrdpmouse_drv.so: undefined symbol: rdpUnregisterInputCallback
    [  1272.094] (EE) Failed to load module "xrdpmouse" (loader failed, 0)
    [  1272.094] (II) LoadModule: "xrdpkeyb"
    [  1272.094] (II) Loading /usr/lib/xorg/modules/input/xrdpkeyb_drv.so
    [  1272.094] (EE) Failed to load /usr/lib/xorg/modules/input/xrdpkeyb_drv.so: /usr/lib/xorg/modules/input/xrdpkeyb_drv.so: undefined symbol: rdpUnregisterInputCallback
    [  1272.094] (EE) Failed to load module "xrdpkeyb" (loader failed, 0)
    [  1272.094] (II) intel: Driver for Intel(R) Integrated Graphics Chipsets:
    	i810, i810-dc100, i810e, i815, i830M, 845G, 854, 852GM/855GM, 865G,
    	915G, E7221 (i915), 915GM, 945G, 945GM, 945GME, Pineview GM,
    	Pineview G, 965G, G35, 965Q, 946GZ, 965GM, 965GME/GLE, G33, Q35, Q33,
    	GM45, 4 Series, G45/G43, Q45/Q43, G41, B43
    [  1272.094] (II) intel: Driver for Intel(R) HD Graphics
    [  1272.094] (II) intel: Driver for Intel(R) Iris(TM) Graphics
    [  1272.094] (II) intel: Driver for Intel(R) Iris(TM) Pro Graphics
    [  1272.094] (II) NVIDIA dlloader X Driver  435.21  Sun Aug 25 08:17:08 CDT 2019
    [  1272.094] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
    [  1272.095] (EE) No devices detected.
    [  1272.095] (EE) 
    Fatal server error:
    [  1272.095] (EE) no screens found(EE) 
    [  1272.095] (EE) 
    Please consult the The X.Org Foundation support 
    	 at http://wiki.x.org
     for help. 
    [  1272.095] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
    [  1272.095] (EE) 
    [  1272.166] (EE) Server terminated with error (1). Closing log file.`

The evaluated xorg.conf file (interesting part) is as follows
    
    Section "ServerLayout"
        Identifier     "Dell XPS 15 7590 Default"
        Screen      0  "Screen0 (Intel)" 0 0
        Screen      1  "Screen1 (NVIDIA)" RightOf "Screen0 (Intel)"
        InputDevice    "Mouse0" "CorePointer"
        InputDevice    "Keyboard0" "CoreKeyboard"
    EndSection
    
    Section "ServerFlags"
        option "DefaultServerLayout" "Dell XPS 15 7590 Default"
    EndSection
    
    Section "Files"
        ModulePath      "/usr/lib/xorg/modules"
        FontPath        "/usr/share/fonts/misc"
        FontPath        "/usr/share/fonts/TTF"
        FontPath        "/usr/share/fonts/OTF"
        FontPath        "/usr/share/fonts/Type1"
        FontPath        "/usr/share/fonts/100dpi"
        FontPath        "/usr/share/fonts/75dpi"
    EndSection

    Section "Module"
        Load           "glx"
        Load           "vnc"
    EndSection

    # Devices to use when in HYPER-V VM
    
    Section "ServerLayout"
        Identifier     "HYPER-V_Virtual_Machine"
        Screen      0  "HYPER-V Remote Screen" 0 0
        InputDevice    "Mouse0" "CorePointer"
        InputDevice    "Keyboard0" "CoreKeyboard"
    EndSection

    Section "Device"
        Identifier   "HYPER-V Framebuffer"
        Driver       "fbdev"
    EndSection
    
    Section "Screen"
        Identifier     "HYPER-V Remote Screen"
        Device         "HYPER-V Framebuffer"
        DefaultDepth    24
        Subsection     "Display"
            Depth       24
        EndSubsection
    EndSection

    Section "ServerLayout"
        Identifier "Xrdp-X11-Server"
        Screen "Screen (xrdpdev)"
        InputDevice "xrdpMouse" "CorePointer"
        InputDevice "xrdpKeyboard" "CoreKeyboard"
        Option "DontVTSwitch" "on"
        Option "AutoAddDevices" "off"
    EndSection
    
    Section "Module"
        Load "ddc"
        Load "extmod"
        Load "int10"
        Load "record"
        Load "vbe"
        Load "xorgxrdp"
        Load "fb"
    EndSection

    Section "InputDevice"
        Identifier "xrdpKeyboard"
        Driver "xrdpkeyb"
    EndSection
    
    Section "InputDevice"
        Identifier "xrdpMouse"
        Driver "xrdpmouse"
    EndSection

    Section "Monitor"
        Identifier "Monitor"
        Option "DPMS"
        HorizSync 30-80
        VertRefresh 60-75
        ModeLine "1920x1080" 138.500 1920 1968 2000 2080 1080 1083 1088 1111 +hsync -vsync
        ModeLine "1280x720" 74.25 1280 1720 1760 1980 720 725 730 750 +HSync +VSync
        Modeline "1368x768" 72.25 1368 1416 1448 1528 768 771 781 790 +hsync -vsync
        Modeline "1600x900" 119.00 1600 1696 1864 2128 900 901 904 932 -hsync +vsync
    EndSection
    
    Section "Device"
        Identifier "Video Card (xrdpdev)"
        Driver "xrdpdev"
    EndSection

    Section "Screen"
        Identifier "Screen (xrdpdev)"
        Device "Video Card (xrdpdev)"
        Monitor "Monitor"
        DefaultDepth 24
        SubSection "Display"
            Depth 24
            Modes "640x480" "800x600" "1024x768" "1280x720" "1280x1024" "1600x900" "1920x1080"
        EndSubSection
    EndSection

Then start X using `startx -- -layout Xrdp-X11-Server`

The non-VM drivers are used to work with bootng directly from disk. The errors seems to not related to these modules.

**Comment by metalefty** [comment]
```
[  1272.093] (II) Loading /usr/lib/xorg/modules/drivers/xrdpdev_drv.so
[  1272.093] (EE) Failed to load /usr/lib/xorg/modules/drivers/xrdpdev_drv.so: /usr/lib/xorg/modules/drivers/xrdpdev_drv.so: undefined symbol: rdpRRModeDestroy
[  1272.093] (EE) Failed to load module "xrdpdev" (loader failed, 0)
```

**Comment by sshaikh** [comment]
Possible fix here https://github.com/neutrinolabs/xrdp/issues/1029#issuecomment-724105386
