### ISSUE TITLE
Local sound cards are not detected

### ISSUE THREAD

**Issue by zd-dalibor** [neutrinolabs/xrdp#1414]
When I connect to my ubuntu machine with xrdp I cannot play sound view local sound card. I do not want to play sound on a machine that starts xrdp session. Do not want to do sound redirection.
The only recognized devices are "xrdp sink" and "xrdp source". But "arecord -l" command shows one hardware sound cart

```
**** List of CAPTURE Hardware Devices ****
card 0: NVidia [HDA NVidia], device 0: VT1708S Analog [VT1708S Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

![image](https://user-images.githubusercontent.com/226822/65647361-be5d8d00-dffe-11e9-95f8-00fc44422e33.png)

How to play sound on local hardver sound card on the machine I am connected via xrdp?

By the way this is how rdp client is configured:

![image](https://user-images.githubusercontent.com/226822/65647541-55c2e000-dfff-11e9-8d40-02cb9de9391b.png)

**Comment by metalefty** [comment]
@zd-dalibor What `pacmd info` command results?

**Comment by zd-dalibor** [comment]
@metalefty 

I gave up of trying to run xrdp server on my ubuntu 19.10 machine.

The current ubuntu xrdp package installs it but there are missing dependencies, some security issues, xrdp server is miss configured... So I need approximately one whole day to be able to get the point where I can test playing sound on remote machine without redirection.

I return to slow and ugly VNC and TeamViewer desktop sharing.

By the way I follow this [blog](https://c-nergy.be/blog/?p=13390) how to install xrdp server on ubuntu machine

**Comment by zd-dalibor** [comment]
This is a quick installation script for ubuntu 18.04.
[xrdp installation](https://c-nergy.be/blog/?p=13420)

**Comment by matt335672** [comment]
I'm closing this issue now. Version 0.6 of the pulseaudio module [has been released](/neutrinolabs/pulseaudio-module-xrdp/releases/tag/v0.6) with significant changes, and the [wiki README](/neutrinolabs/pulseaudio-module-xrdp/wiki/README) has been updated with better build instructions.

Regarding this specific fault, when an xrdp session is started with audio, the xrdp sound drivers will be set to the default drivers. However with 0.6, the local sound drivers will be available, and can be set as default sources and sinks with the `pacmd set-default-source` and `pacmd set-default-sink` commands.

**Comment by ccwang65** [comment]
> [@zd-dalibor](https://github.com/zd-dalibor) What `pacmd info` command results?

Add your account into group audio. [https://unix.stackexchange.com/questions/635032/can-you-access-bluetooth-or-audio-devices-over-xrdp](url)

**Comment by ccwang65** [comment]
> I'm closing this issue now. Version 0.6 of the pulseaudio module [has been released](/neutrinolabs/pulseaudio-module-xrdp/releases/tag/v0.6) with significant changes, and the [wiki README](/neutrinolabs/pulseaudio-module-xrdp/wiki/README) has been updated with better build instructions.
> 
> Regarding this specific fault, when an xrdp session is started with audio, the xrdp sound drivers will be set to the default drivers. However with 0.6, the local sound drivers will be available, and can be set as default sources and sinks with the `pacmd set-default-source` and `pacmd set-default-sink` commands.

Add your account to group audio? It works for [me.](https://unix.stackexchange.com/questions/635032/can-you-access-bluetooth-or-audio-devices-over-xrdp)
