### ISSUE TITLE
XRDP+Xvnc=MaxDisconnectionTime?

### ISSUE THREAD

**Issue by sccoll** [neutrinolabs/xrdp#1415]
Hello.
I need help setting up xrdp.
How to remove the parameter "MaxDisconnectionTime 60"?
In the xrdp.ini and sesman.ini configuration files, the parameter "MaxDisconnectionTime 60" is not
When connected:

Xvnc :208 -geometry 1600x1200 -depth 16 -rfbauth /home/user/.vnc/sesman_user_passwd -MaxDisconnectionTime 60 -bs -ac -nolisten tcp -localhost -dpi96

Suse Linux Enterprise Server 12 SP4

**Comment by metalefty** [comment]
@sccoll Please note that is not our issue. SUSE team modifies xrdp to add KillDisconnected feature.

See this patch: https://build.opensuse.org/package/view_file/X11:RemoteDesktop/xrdp/xrdp-support-KillDisconnected-for-Xvnc.patch?expand=1

SUSE team is responsible to the MODIFIED VERSION of xrdp. I would say you should ask the SUSE team. I can advise setting `KillDisconnected=false` will do the trick according to the patch. If you have further questions, ask the SUSE team.

**Comment by sccoll** [comment]
Hello. Where is the parameter set?

KillDisconnected=false
MaxDisconnectionTime 60

**Comment by sccoll** [comment]
In file sesman.ini?

**Comment by metalefty** [comment]
Should be asked SUSE team.
