### ISSUE TITLE
What RDP Protocol version level is xrdp at?

### ISSUE THREAD

**Issue by BloodyIron** [neutrinolabs/xrdp#1420]
It's been several years since I tried xrdp last, and when I did, it used a very substantial amount of bandwidth for one connection.

I'm curious, since I can't find this documented, what MS RDP protocol level ( https://en.wikipedia.org/wiki/Remote_Desktop_Protocol#History ) can xRDP serve at? I haven't seen any of the release notes talk about protocol version or bandwidth/performance improvements, so I'd like to know more about where that's at.

**Comment by jsorg71** [comment]
The latest features from RDP 7.1.  The RemoteFX codec is used.  So it's not great on bandwidth.
We have plans to implement RDP 8 GFX and that should happen soon.  GFX will have bandwidth up to 10 times better as it used codecs like h264 and progressive remotefx.

**Comment by BloodyIron** [comment]
@jsorg71 yay! Is there any sort of ticket/issue I can watch for that development? :)

**Comment by jsorg71** [comment]
I create #1422 for GFX tracking

**Comment by BloodyIron** [comment]
@jsorg71 thanks! :D sub'd
