### ISSUE TITLE
Can't log in to remote centos 7.7

### ISSUE THREAD

**Issue by mrpotatoserver** [neutrinolabs/xrdp#1421]
Hi, 
I can't select X11rdp in the checklist of the login menu and also can't log in using Xorg, Xvnc sessions. 
I recently installed XRDP in my brand new centos 7.7. Everything goes well in the installation (https://github.com/neutrinolabs/xrdp) and algo isntalling prerequesites ( https://github.com/neutrinolabs/xorgxrdp). I've also followed this link (https://github.com/neutrinolabs/xrdp/wiki/Building-on-CentOS-(or-Red-Hat-based-distributions)) to check if something was wrong about the quick installation but it seems that I'm having the same issue. 
What I'm doing is the following.
1) Open RDP in my W10
2) write the IP of the machine that I want to login.
3) Select form the options available (under) the sessions Xvnc or Xorg.
    options available:
![xrdpOptions](https://user-images.githubusercontent.com/55957776/66718911-7ce42480-ede9-11e9-92f5-beeb9fc31ceb.png)

    Xvnc
    Xorg
    vnc-any
    neutrinordp-any

What am I missing?   I can show you the logs if it is necessary but I can advance you that are not giving much info.
Thanks in advice.

**Comment by matt335672** [comment]
Hi @mrpotatoserver.

I notice you're not using the RPMs from EPEL. If you don't know about these, they're worth having a look at, as not only do you get the dependencies packaged up, but there's also an xrdp-selinux package which you will need if you're using SELinux - see #1113. Also, the packaged RPMs have some additional patches in which make the process of running on CentOS a bit easier.

I'm happy to give you a hand to get the source build sorted out however, if you're still keen on that. Can we start with Xvnc which is the simplest option, and then move on if necessary?

You'll need two things from starters:-
-  tigervnc-server-minimal RPM installed to get Xvnc
- (if using SELinux) either install xrdp-selinux from EPEL, or temporarily set SELinux to permissive mode with "sudo setenforce 0". We can sort out SELinux later.

Can you do those two things, and report back? In particular, what are you seeing on the screen after you try to log in?

**Comment by mrpotatoserver** [comment]
Hi @matt335672 

Thanks for answering. I've did the two things you told me:

You'll need two things from starters:-

- tigervnc-server-minimal RPM installed to get Xvnc
It was already installed, so when I've tried to install the last version.  yum install tigervnc-server-minimal-1.8.0-17.el7.x86_64
![xrdptigervnc](https://user-images.githubusercontent.com/55957776/66839333-89da5280-ef66-11e9-93eb-c3e7a6142529.png)


- (if using SELinux) either install xrdp-selinux from EPEL, or temporarily set SELinux to permissive mode with "sudo setenforce 0". We can sort out SELinux later.

I've changed the mode of SELinux to permissive as you told me 
![xrdptigervnc](https://user-images.githubusercontent.com/55957776/66839590-f5242480-ef66-11e9-8068-53358083303a.png)
The problem is that I get the same result, when I try to log to the centos system it tries for a few seconds and after that it closes. 
Do you need that more info from the logs?

**Comment by matt335672** [comment]
Thanks for that.

I think changing the file back is a good idea for now.

Going back to your original trace, it looks like all is well for a bit, and then the Xvnc server disappears. This could be because of a negotiation error, or (more likely) that your graphical session isn't starting correctly.

You'll need a desktop environment of some sort installed, even if the machine is running without a graphical login. If you do have a graphical login on the machine console can you get to it, and is it working OK?

In terms of getting a log, we can use journalctl to do this. Try the login again, and immediately after it fails, use the following command as root to get all the messages for the last two minutes:-

`journalctl -S -2m >error.log`

Post that back, and we'll try to get a bit further.

**Comment by mrpotatoserver** [comment]
Hi @matt335672 

I've changed back the file and now I get the same message: 
![xrdp-screen1](https://user-images.githubusercontent.com/55957776/66910149-4c310480-f00e-11e9-8666-793ba870c01d.png)


I've also executed the command you told me:
journalctl -S -2m >error.log

Getting the following traces:




[20191016-12-00error.log](https://github.com/neutrinolabs/xrdp/files/3733700/20191016-12-00error.log)

Answering your question I think that my graphical "desktop" is correctly installed. I followed this link (https://github.com/neutrinolabs/xrdp/wiki/Building-on-CentOS-(or-Red-Hat-based-distributions)) to install the X11 graphical login. Am I missing something?

(PD: thanks for your help=

**Comment by mrpotatoserver** [comment]
Hi @matt335672 

You are completely right my graphical desktop was not well installed. What I've did is reinstall xfce again using the following commands:

sudo yum groupinstall -y "Xfce"

echo "xfce4-session" > ~/.Xclients
chmod a+x ~/.Xclients
sudo reboot

I just want to make another question referred to the configuration of the proxy of Neutrinordp (https://github.com/neutrinolabs/xrdp/wiki/NeutrinoRDP-proxy-module-for-xrdp). Should I open another thread?

**Comment by matt335672** [comment]
OK - glad you've found it.

Please open another thread about Neutrinordp - I can't personally help you with that one, as I've not used it.

As regards your original query, are you now able to log in?

There's also the small matter of SELinux which we've disabled. Assuming you are able to log in, what does the output of `ps -Z $$` say in a terminal window?

**Comment by mrpotatoserver** [comment]
Hi @matt335672 

What I get when I execute the command ps -Z $$ :
![xrdp-unconfined](https://user-images.githubusercontent.com/55957776/67309997-2ff50200-f4fd-11e9-8cd0-8264c46215b7.JPG)


What is supposed to be this information?

Currently I can log in from an external IP (internet) but I want to log from my corporate network.

**Comment by matt335672** [comment]
That all looks fine - on the desktop you're supposed to be running as `unconfined_t`.

It's possible if you don't install the xrdp-selinux RPM that you'll end up running in `unconfined_service_t`. 

I don't understand your comment about the corporate network. What are you trying to achieve?

**Comment by mrpotatoserver** [comment]
Well, what I've try to do is the following:
(Me)           (proxy:8080)                              (cloud virtual machine)
W10 ----> proxy.corporation.com-------->  W10

I want to RDP (graphic environment) to a cloud machine, the fact is that I need to go through a proxy  in the same way as putty does. Currently I can reach the machine with a terminal using putty (ssh) but  can't open a graphic environment.

**Comment by matt335672** [comment]
Oh right -this relates to #1424 

I think it might be best to move any comments about the proxy to that thread, and leave this thread for getting the environment working, which I think we have done.

**Comment by mrpotatoserver** [comment]
yes, I think we can close it. Thanks for your help
