### ISSUE TITLE
system crashes after remote access attempt from Windows

### ISSUE THREAD

**Issue by markolbert** [neutrinolabs/xrdp#1423]
I'm running xrdp (0.9.8) under debian stretch on a Raspberry Pi 3B+. Up until a few weeks ago I was able to access it from my Windows 10 desktop machine with no problems of any kind.

Recently, however, when I try to access the Pi from the same Windows 10 machine the Pi crashes. So hard that I have not been able to find any warning messages, or messages of any kind, in the logs I've checked.

I'm happy to do more research on this if someone can point me to resources that would help me set up kdump (or whatever other tool is recommended).

If there are configuration settings I should check on the Pi I'm happy to do that, too.

**Comment by hmehra** [comment]
Was there ever a solution provided? I see this on my Raspberry Pi 4 running Ubuntu 21.10 with xrdp 0.9.15

**Comment by markolbert** [comment]
I'm sorry, but I no longer even remember the context of the problem, or whatever solution, if any, I arrived at. Good luck!
