### ISSUE TITLE
Showing 2 monitors in RDP for XFCE4 on CentOs7

### ISSUE THREAD

**Issue by mforde84** [neutrinolabs/xrdp#1430]
I have a virtual machine hosted by a vCenter appliance. The machine has 2 monitors specified in it's setting. However when I RDP into the box, the session only sees one monitor. I guess that makes sense since the monitors specified in the vCenter setting would be considered "physical" monitors, so when RDP into the box I'm starting a new X session that has nothing to do with these monitors. When I try setting RDP to use multiple monitors the connection crashes automatically. Any one have experience in this matter? I tried with GNOME, and it appears to set the resolution to span monitors at 3840x1080. Is there a way to force xrdp to show two monitors at 1920x1080 or alternatively a single monitor at 3840x1080?

**Comment by matt335672** [comment]
You're quite correct in that that "physical" monitors connected to your VM are not important.

When you connect to the VM from an RDP client, the client will request a particular screen layout. If you're connecting from the Windows MSTSC.EXE client (and I assume you are), you can either request a single screen, or you can tick the _Use all my monitors for the remote session_ box. This option will cause the client to send a description of all its connected monitors to the VM.

To actually use multiple monitors with the current version of XRDP (0.9.11):-
-  you will need to select the Xorg backend when you connect
- the server will need to have xorgxrdp installed.

If you use the Xvnc backend you will end up with a single spanning monitor, which is possibly what you have already seen.

**Comment by matt335672** [comment]
Closing this - multimon support has been a thing for quite a while.
