### ISSUE TITLE
Cannot reconnect to active session from another machine if session started from local shell

### ISSUE THREAD

**Issue by alphamodel** [neutrinolabs/xrdp#1431]
My OS is ubuntu-18.04 LTS, xrdp is working as expected if only using from one location.

I have experienced following behavior:

1. If I login from the local machine, then xrdp cannot connected.
2. If I login from xrdp first, then cannot login from local machine.
3. If I login from the local machine, and then logout the user. Then xrdp can be connected.
4. If I login from xrdp first, and then logout xrdp. After logout,  I can login from local machine.
5. If I login from xrdp from host A first, then I can login from host B through xrdp, no need to logout. Host A session will be terminated on the connection of host B.

I believe behavior 5 is the expected behavior. Is there any setting I am missing cause the local shell not working as any other remote sessions.

If more detailed information is needed, please let me know. Thanks for your help!

**Comment by metalefty** [comment]
1 and 2 are Ubuntu issue. Ask Ubuntu team.

**Comment by metalefty** [comment]
In other words, xrdp has no mechanism at all to restrict concurrent graphical login at the same time.

**Comment by jjasoncool** [comment]
> 
> 
> 1 and 2 are Ubuntu issue. Ask Ubuntu team.

centos have same issue.

**Comment by na69an** [comment]
@metalefty do you know any linux configuration which does not reproduce @alphamodel issues?

Is it possible to reuse the local session from remotely like windows remote desktop method?

**Comment by metalefty** [comment]
@na69an I'm not sure but regarding the latter question, I'm always using a remote session even if I'm on the local console by connecting localhost:3389.

**Comment by alphamodel** [comment]
@metalefty do you mind I ask how to connect to remote session from a local console? Thanks.

**Comment by na69an** [comment]
Possibly @metalefty has a user only for local usage and connect to remoteuser@localhost:rdp with something rdp client. It is a tricky workaround solution, but not the similar best windows to windows.
I am waiting for the best solution. Thanks!

**Comment by alphamodel** [comment]
@na69an the problem is I cannot log into the local desk environment if a rdp session is started from the other machine. How can I rdp back to my local machine without a desk environment? A bit confused how to do it.

**Comment by jjasoncool** [comment]
> 
> 
> @na69an the problem is I cannot log into the local desk environment if a rdp session is started from the other machine. How can I rdp back to my local machine without a desk environment? A bit confused how to do it.

you can login as root and use pkill

**Comment by alphamodel** [comment]
@na69an This is a good idea. No need to kill your user, just login the other user first, and rdp back to the main user.

**Comment by metalefty** [comment]
@na69an 

Yes, that's a workaround. There's some other workaround but they're still workaround.

xrdp works like a graphical version of GNU screen or tmux.  Imagine that you're using a command line session.  Sessions not started in screen/tmux cannot be reattached from a different location. 

If you intend to reuse a session from a different location, you must start a session in screen/tmux. Then you can reattach the screen/tmux session via SSH and get the session you created before. That's same with xrdp. If you intend to reuse a session from remote, start it in xrdp.

Please understand GNU/Linux is completely different operating system from Windows. Not everything can be possible like Windows.

**Comment by na69an** [comment]
@metalefty, thanks for the technical details. In this remoting scenario +1 for the windows platform. :-(

**Comment by alphamodel** [comment]
Thanks for your detailed answers, @metalefty.
