### ISSUE TITLE
Centos 8 can't connect to rdp server

### ISSUE THREAD

**Issue by jjasoncool** [neutrinolabs/xrdp#1432]
This is xorg connection.
![圖片](https://user-images.githubusercontent.com/24731867/67615439-481b9880-f7ff-11e9-8638-74754507c08e.png)

I only do 
`yum install epel-release`
`yum install xrdp xrdp-selinux xorgxrdp`

The CentOS 8 is new install OS.
I install CentOS with "GUI server" then install xrdp.
I haven't change any setting in xrdp.ini and sesman.ini files.
But in CentOS 7 is work.

What step I miss or I have to install?
And which file I have to provide?

> [20191026-13:38:04] [INFO ] setpriv --no-new-privs Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log  
> [20191026-13:38:14] [ERROR] X server for display 10 startup timeout
> [20191026-13:38:14] [CORE ] waiting for window manager (pid 693) to exit
> [20191026-13:38:14] [ERROR] X server for display 10 startup timeout
> [20191026-13:38:14] [ERROR] another Xserver might already be active on display 10 - see log
> [20191026-13:38:14] [DEBUG] aborting connection...
> [20191026-13:38:14] [CORE ] window manager (pid 693) did exit, cleaning up session

Sorry I am a newbie.
Thank you!

[Connection Video](https://github.com/neutrinolabs/xrdp/files/3774575/Video_2019-10-26_155025.zip)

**Comment by jjasoncool** [comment]
[20191026-13:38:04] [INFO ] setpriv --no-new-privs Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log  
[20191026-13:38:14] [ERROR] X server for display 10 startup timeout
[20191026-13:38:14] [CORE ] waiting for window manager (pid 693) to exit
[20191026-13:38:14] [ERROR] X server for display 10 startup timeout
[20191026-13:38:14] [ERROR] another Xserver might already be active on display 10 - see log
[20191026-13:38:14] [DEBUG] aborting connection...
[20191026-13:38:14] [CORE ] window manager (pid 693) did exit, cleaning up session

**Comment by jjasoncool** [comment]
https://github.com/neutrinolabs/xrdp/issues/1106

**Comment by jjasoncool** [comment]
I have found some inflammation.
https://www.centos.org/forums/viewtopic.php?f=54&t=71817&p=301957&hilit=xrdp#p301957
When using xvnc remote login, you need to log out of the local account to log in successfully.
When using xorg remote login, it will display a blue screen whether or not you log in to your local account.

**Comment by sebastian-luna-valero** [comment]
FYI: for my CentOS 8.1 desktop it was required the following configuration changes:

```
diff /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.bak.2020.06.18
181,192c181,183
< [Xorg]
< name=Xorg
< lib=libxup.so
< username=ask
< password=ask
< ip=127.0.0.1
< port=-1
< code=20
< 
< #[Xvnc]
< #name=Xvnc
< #lib=libvnc.so
---
> #[Xorg]
> #name=Xorg
> #lib=libxup.so
196a188,196
> #code=20
> 
> [Xvnc]
> name=Xvnc
> lib=libvnc.so
> username=ask
> password=ask
> ip=127.0.0.1
> port=-1


diff /etc/xrdp/sesman.ini /etc/xrdp/sesman.ini.bak.2020.06.18
86c86
< param=/usr/libexec/Xorg
---
> param=Xorg
96,103c96,103
< #[Xvnc]
< #param=Xvnc
< #param=-bs
< #param=-nolisten
< #param=tcp
< #param=-localhost
< #param=-dpi
< #param=96
---
> [Xvnc]
> param=Xvnc
> param=-bs
> param=-nolisten
> param=tcp
> param=-localhost
> param=-dpi
> param=96
```

**Comment by danchitnis** [comment]
> FYI: for my CentOS 8.1 desktop it was required the following configuration changes:
> 
> ```
> diff /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.bak.2020.06.18
> 181,192c181,183
> < [Xorg]
> < name=Xorg
> < lib=libxup.so
> < username=ask
> < password=ask
> < ip=127.0.0.1
> < port=-1
> < code=20
> < 
> < #[Xvnc]
> < #name=Xvnc
> < #lib=libvnc.so
> ---
> > #[Xorg]
> > #name=Xorg
> > #lib=libxup.so
> 196a188,196
> > #code=20
> > 
> > [Xvnc]
> > name=Xvnc
> > lib=libvnc.so
> > username=ask
> > password=ask
> > ip=127.0.0.1
> > port=-1
> 
> 
> diff /etc/xrdp/sesman.ini /etc/xrdp/sesman.ini.bak.2020.06.18
> 86c86
> < param=/usr/libexec/Xorg
> ---
> > param=Xorg
> 96,103c96,103
> < #[Xvnc]
> < #param=Xvnc
> < #param=-bs
> < #param=-nolisten
> < #param=tcp
> < #param=-localhost
> < #param=-dpi
> < #param=96
> ---
> > [Xvnc]
> > param=Xvnc
> > param=-bs
> > param=-nolisten
> > param=tcp
> > param=-localhost
> > param=-dpi
> > param=96
> ```

This line should be changed in sesman.ini otherwise xorg won't work:
*param=/usr/libexec/Xorg*

**Comment by OlegBoul** [comment]
have changed on my CentOs 8.2 like danchitnis adised:
[root@localhost ~]# diff /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.orig
181,192c181,183
< [Xorg]
< name=Xorg
< lib=libxup.so
< username=ask
< password=ask
< ip=127.0.0.1
< port=-1
< code=20
< 
< #[Xvnc]
< #name=Xvnc
< #lib=libvnc.so
---
> #[Xorg]
> #name=Xorg
> #lib=libxup.so
196a188,196
> #code=20
> 
> [Xvnc]
> name=Xvnc
> lib=libvnc.so
> username=ask
> password=ask
> ip=127.0.0.1
> port=-1
[root@localhost ~]# diff /etc/xrdp/sesman.ini /etc/xrdp/sesman.ini.orig
88,89c88
< #param=Xorg
< param=/usr/libexec/Xorg
---
> param=Xorg
99,106c98,105
< #[Xvnc]
< #param=Xvnc
< #param=-bs
< #param=-nolisten
< #param=tcp
< #param=-localhost
< #param=-dpi
< #param=96
---
> [Xvnc]
> param=Xvnc
> param=-bs
> param=-nolisten
> param=tcp
> param=-localhost
> param=-dpi
> param=96
but the result almost the same
![Clipboard](https://user-images.githubusercontent.com/19363860/99534804-0c7ae000-29b9-11eb-8a16-01f750b4f4e3.jpg)
