### ISSUE TITLE
what happen to travis-ci?

### ISSUE THREAD

**Issue by jsorg71** [neutrinolabs/xrdp#1438]
It seems travic-ci is gone for both xrdp and xorgxrdp

**Comment by metalefty** [comment]
It still there: https://travis-ci.org/neutrinolabs/xrdp/pull_requests

But I cannot see integrations or link on GitHub. It seems disappeared on PRs:
https://github.com/neutrinolabs/xrdp/pull/1437

I'm still not sure what happened.

**Comment by metalefty** [comment]
Once I revoke Travis CI authorization from GitHub, then sign out from Travis CI and sign in again, it's back to me.

Revoke from here: https://github.com/settings/applications

![スクリーンショット 2019-11-08 15 09 50](https://user-images.githubusercontent.com/941609/68453802-009efe80-023a-11ea-9990-f1a2e920f9ed.png)

**Comment by jsorg71** [comment]
Ok, thanks, it's back
