### ISSUE TITLE
xrdp debian9

### ISSUE THREAD

**Issue by yohohoro** [neutrinolabs/xrdp#1444]
`systemctl status xrdp`
`.service - xrdp daemon
   Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-11-15 09:53:11 MSK; 14min ago
     Docs: man:xrdp(8)
           man:xrdp.ini(5)
  Process: 999 ExecStopPost=/bin/rm -rf /var/run/xrdp/sockdir (code=exited, status=0/SUCCESS)
  Process: 996 ExecStop=/usr/sbin/xrdp $XRDP_OPTIONS --kill (code=exited, status=0/SUCCESS)
  Process: 1026 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
  Process: 1016 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
 Main PID: 1027 (xrdp)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/xrdp.service
           └─1027 /usr/sbin/xrdp

Nov 15 10:07:32 server.domain.com xrdp[1423]: (1423)(140643874998016)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:serverip port 3389)
Nov 15 10:07:32 server.domain.com xrdp[1423]: (1423)(140643874998016)[ERROR] Listening socket is in wrong state, terminating listener
Nov 15 10:07:43 server.domain.com xrdp[1027]: (1027)(140643874998016)[INFO ] A connection received from: ::ffff:myip port 64469
Nov 15 10:07:43 server.domain.com xrdp[1027]: (1027)(140643874998016)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:serverip port 3389)
Nov 15 10:07:43 server.domain.com xrdp[1424]: (1424)(140643874998016)[DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
Nov 15 10:07:43 server.domain.com xrdp[1424]: (1424)(140643874998016)[INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
Nov 15 10:07:43 server.domain.com xrdp[1424]: (1424)(140643874998016)[INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Nov 15 10:07:43 server.domain.com xrdp[1424]: (1424)(140643874998016)[DEBUG] Security layer: requested 3, selected 0
Nov 15 10:07:43 server.domain.com xrdp[1424]: (1424)(140643874998016)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:serverip port 3389)
Nov 15 10:07:43 server.domain.com xrdp[1424]: (1424)(140643874998016)[ERROR] Listening socket is in wrong state, terminating listener`

**Comment by metalefty** [comment]
I could not get you. You just pasted the log. Speak in words of yours.
