### ISSUE TITLE
xrdp-sesman becomes <defunct> and cannot login.

### ISSUE THREAD

**Issue by tanakakz-alpha** [neutrinolabs/xrdp#1447]
// Version
OS: Ubuntu 18.04
Version: 0.9.5-2 (Provided by Ubuntu.)

// Playback procedure
1. login to server.
1. logoff from server.
1. login to server.

// Correct behavior
Login succeeded.

// Actual behavior
cannot login.

// Possible cause
Trying to reconnect to the deleted display.

**Comment by derekschrock** [comment]
Sounds like https://github.com/neutrinolabs/xrdp/pull/1487 fix in https://github.com/neutrinolabs/xrdp/releases/tag/v0.9.13

**Comment by metalefty** [comment]
Looks like already fixed issue, closing.
