### ISSUE TITLE
xrdp/sesman/sesman.ini.in: Xorg-Server not found

### ISSUE THREAD

**Issue by DeadRabbits307** [neutrinolabs/xrdp#1448]
On Manjaro 18 I had to adopt `xrdp/sesman/sesman.ini` from
`param=Xorg` to
`param=/usr/lib/Xorg`
otherwise I could not log in via RemoteDesktop( login window vanished and about 2 minutes you could only see the turquoise screen; in this time, no Xorg-Server was startet checking with `ps -ef | grep -I xorg`). Cost me a lot of time. Funny enough, older machines I set up (three months ago) I did not 
have to modify `xrdp/sesman/sesman.ini`...

In addition, the Xorg-Arch path given in the comment above is not correct for Manjaro...

Don‘t know if this is a bug, but for me setting up xrdp once again was quite annoying and time-consuming...definitely this can be managed to be more convenient for the user :)

**Comment by DeadRabbits307** [comment]
https://forum.manjaro.org/t/remote-desktop-via-xrdp-from-windows-10/101183?

**Comment by metalefty** [comment]
So where was the correct path?

**Comment by DeadRabbits307** [comment]
for Manjaro `sesman.ini` is in `/etc/xrdp/` and 
_`; Arch Linux            :  param=/usr/lib/xorg-server/Xorg`_
is not correct for Manjaro; here it is `/usr/lib/Xorg`

**Comment by metalefty** [comment]
Thanks. Actually, also Arch Linux should be `/usr/lib/Xorg` now.  `/usr/lib/xorg-server/Xorg` is the former path. Manjaro is Arch Linux based so the paths should be same.

I can find the current path here: https://www.archlinux.org/packages/extra/x86_64/xorg-server/
