### ISSUE TITLE
issues when building xrdp on slackware

### ISSUE THREAD

**Issue by dragonauta** [neutrinolabs/xrdp#145]
Hi, I didn't know if post here or through xrdp-devel mailing list.
I'm trying to build xrdp on Slackware.
I downloaded as ZIP file, unzipped and ran bootstrap.
I know that don't have PAM, so I used "configure --enable-nopam" but I get this error:

``` bash
xrdp-master/sesman/session.c:553: undefined reference to `auth_stop_session'
collect2: error: ld returned 1 exit status
```

How can I continue?

**Comment by metalefty** [comment]
Need more information. Reopen is you reproduce with the latest release v0.9.2.
