### ISSUE TITLE
Idle disconnect issue on v0.9.11

### ISSUE THREAD

**Issue by GoldenMouse** [neutrinolabs/xrdp#1451]
**Specs**
CentOS 7.7

We have been using v0.9.4 with no issues. Now on v0.9.11, if I minimize the RDP session and go about my own thing, after 4 or more minutes RDP disconnects and get a windows prompt that the RDP connection was lost. 

My logs are on DEBUG and nothing outputs when this happens.  I don't think it ever happens when I'm doing something in the session. I've checked my configuration and DisconnectedTimeLimit=0
KillDisconnected=false are set.

**Troubleshooting steps**
I thought it had something to do with the EPEL package. So I compiled from source:

-  v0.9.11 - same issue
-  v0.9.10 - no issue
-  v0.9.4 - no issue

**Comment by metalefty** [comment]
Can you show us the log (xrdp.log, xrdp-sesman.log) when disconnection happen?

**Comment by metalefty** [comment]
Close due to no feedback from the reporter.
