### ISSUE TITLE
SBINDIR is hardwired in the start-up script

### ISSUE THREAD

**Issue by yecril71pl** [neutrinolabs/xrdp#1452]
The start-up script `xrdp.sh` expects xrdp to be installed in `/usr/local/bin`, which is not always the case (and it is called SBINDIR for some weird reason).  As a result, the script to start xrdp does not work.  This path should be configurable.

**Comment by metalefty** [comment]
The startup script is outdated and deprecated. It will be removed in future. Consider using systemd.

**Comment by yecril71pl** [comment]
I tried using `systemd`, [it does not work](https://bugzilla.suse.com/show_bug.cgi?id=1158714).

**Comment by metalefty** [comment]
Report it to your distro.

**Comment by jsorg71** [comment]
@metalefty I might be the only one using that old startup script.  We can removing it.

**Comment by metalefty** [comment]
Some few distro not using systemd might have own startup script. People using such distro can use it. So I also think we can remove it. Alternatively, we can borrow and import it from them. 

+1 to remove it. We can keep maintaining the script but not very worth to spend time on that.

**Comment by yecril71pl** [comment]
> Report it to your distro.

I had linked the report.
