### ISSUE TITLE
os_calls.c: g_sck_get_peer_cred() needs to be patched for FreeBSD

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#146]
On FreeBSD, g_sck_get_peer_cred() in os_calls.c always returns `1` and it prevents xup from working. I have no pull request yet but to be patched like [this](http://lists.freedesktop.org/archives/wayland-devel/2013-February/007443.html).

**Comment by metalefty** [comment]
I looked at `lib_mod_log_peer` in `xup/xup.c`, the pid which is gotten in `g_sck_get_peer_cred()` is used only for logging, right?  

This is still a problem but not a fatal problem.  I can't see the pid of X11rdp in `xrdp.log` however no more and no less. I said this problem blocks xrdp ported to BSDs but I was wrong.  This problem is not fatal. 
```
[20150317-07:03:02] [INFO ] lib_mod_log_peer: xrdp_pid=51896 connected to X11rdp_pid=0 X11rdp_uid=0 X11rdp_gid=32767 client_ip=192.168.24.5 client_port=12877
```

**Comment by metalefty** [comment]
I made pull request #231 with minor changes. OS X also needs as same modification as FreeBSD's.

**Comment by proski** [comment]
Since #231 has been merged, can this issue be closed?

**Comment by metalefty** [comment]
It is just a workaround.  I'd like to close this after fundamental fix.

**Comment by metalefty** [comment]
In FreeBSD, X11rdp_pid, X11rdp_uid, X11rdp_gid are not correctly logged.

When lib_mod_log_peer can log them correctly, we can close this issue.

```
[20170119-09:28:39] [INFO ] lib_mod_log_peer: xrdp_pid=83760 connected to X11rdp_pid=0 X11rdp_uid=0 X11rdp_gid=32767 client_ip=::ffff:192.168.69.1 client_port=50405
```
