### ISSUE TITLE
macOS (Catalina) xrdp building error

### ISSUE THREAD

**Issue by Peter-J-Jansen** [neutrinolabs/xrdp#1461]
When building under MacOS Catalina I get the following error : 
```
[…]
  CCLD     xrdp-xcon
Making all in chansrv
  CC       chansrv.o
In file included from chansrv.c:32:
In file included from ./devredir.h:24:
In file included from ./irp.h:30:
./chansrv_fuse.h:30:5: error: unknown type name 'off_t'
    off_t           size;              /* Size of file, in bytes.           */
    ^
./chansrv_fuse.h:103:34: error: unknown type name 'off_t'
                                 off_t offset,
                                 ^
2 errors generated.
make[3]: *** [chansrv.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
Help will be appreciated. Thanks.

**Comment by matt335672** [comment]
Hi @Peter-J-Jansen 

Can you try adding this line to `xrdp/sesman/chansrv/chansrv_fuse.h` above the line `#include "arch.h"`:-

```
#include <sys/types.h>
```

That's where `off_t` is defined according to the [POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html). So if it's available of MacOS, that's where it will be.

Let me know if that gets you going, and if so I'll submit a PR to get it into devel. I don't have access to an installation of MacOS myself, so I can't test it here.

HTH

**Comment by Peter-J-Jansen** [comment]
Dear HTH,

Thanks for your speedy help, and it worked ! This is what I did : 
```
hercules@pjmacz390 xrdp % git diff sesman/chansrv/chansrv_fuse.h
diff --git a/sesman/chansrv/chansrv_fuse.h b/sesman/chansrv/chansrv_fuse.h
index 9a94900e..80cc3e2d 100644
--- a/sesman/chansrv/chansrv_fuse.h
+++ b/sesman/chansrv/chansrv_fuse.h
@@ -19,6 +19,7 @@
 #ifndef _CHANSRV_FUSE_H
 #define _CHANSRV_FUSE_H
 
+#include "sys/types.h"
 #include "arch.h"
 
 #include "ms-erref.h"
hercules@pjmacz390 xrdp % 
```
And as a result, the make (and sudo make install) worked perfectly. I can now try to configure and see if I can get xrdp to work on MacOS Catalina.

Cheers,

Peter

**Comment by Peter-J-Jansen** [comment]
The xrdp installation appears to work. After starting xrdp (sudo /usr/local/sbin/xrdp), ticking Screen Sharing for all users, and setting a  VNC password, I can successfully RDP from a Windows (10, build 1909) PC to this macOS xrdp, but ... ONLY using "vnc-any". Neither the "Xorg" for "Xvnc" session managers work. I presume this is as expected with what I have currently installed.

In order to try getting "Xorg" to work, I then moved on to the "xorgxrdp" installation, and this is the new problem where I got stuck : 

```
git clone https://github.com/neutrinolabs/xorgxrdp.git
cd xorgxrdp
./bootstrap
./configure
[...]
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for xorg-server >= 0... no
configure: error: please install xserver-xorg-dev, xorg-x11-server-sdk or xorg-x11-server-devel
```
Is the above "missing" Xorg perhaps because I installed XQuartz (using XQuartz-2.7.11.dmg) instead of for example "xorg-server" from MacPorts ? For me Quartz is working just fine (e.g. for "x3270" which I use a lot).

Any help will be appreciated !

Thanks,

Peter

**Comment by matt335672** [comment]
Hi Peter,

Glad the fix worked. I'll submit a PR with it soonish, family commitments permitting!

- `xorgxrdp` is highly dependent on Xorg, so that will need to be available for you to compile `xorgxrdp`. You'll need development files in addition to the runtime files.
- To get the `Xvnc` backend working you'll need a working installation of the Xvnc server

I'm afraid I can't be much more help than that as I don't have access to a MacOS installation. I hope that's useful.
I suggest raising a separate issue if you get further and need more advice so we can keep this one dedicated to your original problem

Matt

**Comment by Peter-J-Jansen** [comment]
Hi Matt,

Thanks for your update. I agree with you that this xrdp issue can be closed. I just opened a new issue, neutrinolabs/xorgxrdp 155. It shows that I was able to correct my xorgxrdp configure problem like this : 
```
./configure PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig
```
which resulted in a successful building of "xorgxrdp" based on my XQuartz installation, but then a more serious error developed as "Xorg" reports a fatal error at startup, "Cannot run in framebuffer mode", which I somehow suspect to be a tougher problem.

At any rate, thanks for your support, xrdp works for me, albeit only using the vnc-any session manager, which has some of the known VNC drawbacks. (I think I prefer TeamViewer, but that's just a personal opinion.)

Cheers,

Peter

**Comment by doanhtien** [comment]
I have problem when run ./configure PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig 
It error
`configure: error: please install xserver-xorg-dev, xorg-x11-server-sdk or xorg-x11-server-devel
`

**Comment by benbaker76** [comment]
> I have problem when run ./configure PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig
> It error
> `configure: error: please install xserver-xorg-dev, xorg-x11-server-sdk or xorg-x11-server-devel `

Take a look at config.log and see if there are any errors. For me I had the following:
```
Package xproto was not found in the pkg-config search path.
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'xorg-server', not found
configure:12955: $? = 1
configure:12969: $PKG_CONFIG --exists --print-errors "xorg-server >= 0"
Package xproto was not found in the pkg-config search path.
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'xorg-server', not found
```
So I ran:
`brew install xorgproto`
Then I got:
```
In file included from rdpDraw.c:44:
/opt/X11/include/xorg/dixfontstr.h:30:10: fatal error: 'X11/fonts/libxfont2.h' file not found
#include <X11/fonts/libxfont2.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
So I ran:
`sudo nano /opt/X11/include/xorg/dixfontstr.h`
Changed the following lines:
```
//#include <X11/fonts/libxfont2.h>
#include "../X11/fonts/libxfont2.h"
```
Now it compiles (for complete instructions follow [this guide](https://ryancreecy.com/2019/10/29/xrdp-on-mac.html))

**Comment by usridzero** [comment]
have you been able to expand the xrdp session over multiple displays?

**Comment by doanhtien** [comment]
Oh I have confige successful on MAC Bigsur 

But when connect via remote desktop we only see black screen. How to fix the problem?
