### ISSUE TITLE
Cirrus CI

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#1463]
@jsorg71 
I'm trying to add CI on FreeBSD by Cirrus CI. Cirrus CI is free for public OSS projects.
FreeBSD CI is WIP in my cirrus branch: https://github.com/metalefty/xrdp/commits/cirrus

Can you add Cirrus CI integration to xrdp repository? Probably only organization owner can do it.
https://cirrus-ci.org/guide/quick-start/

**Comment by jsorg71** [comment]
@metalefty I think it's added.

**Comment by metalefty** [comment]
Pushed #1466. Not it seems to be working.
