### ISSUE TITLE
Fedora 30/31 with Xrdp/Xvnc: Issues regarding corporate users, not killing session after usage, and repeated password requests after first login

### ISSUE THREAD

**Issue by peddanet** [neutrinolabs/xrdp#1475]
Hi, I find Xrdp the most satisfying solution, when accessing a Linux system remotely from anywhere!
But I have some minor and yet disturbing issues:

- corporate users can't login (login successful display 11, but VNC error connecting to 127.0.0.1:5911)
- local users can log in once, a XVnc session will live forever and you cannot login from another computer before not killing that specific Xvnc session

      -        ssh: kill and wait until the zombie is killed (could last some minutes)
      -        eventually restart xrdp.service and xrdp-sesman.service

- local user first logs in and password is requested for 5-9 times like for
        -                - color profile (4x)
        -                - keyring (2x)
        -                - PC/SC (3x)
        -                - .....
- It is not possible to have access to USB for example for virtmanager or qemu
- Session is not killed after closing the remote desktop connection

**I was not able to test it with Xorg! Does anybody has experiences how to do this with Fedora?**
I was installing xorgxrdp and edited xrdp.ini to enable it. But when I try to log in I only get a blank screen.

Best regards
Peter

**Comment by metalefty** [comment]
@peddanet 

> corporate users can't login (login successful display 11, but VNC error connecting to 127.0.0.1:5911)

what do you mean corporate users?

> local users can log in once, a XVnc session will live forever and you cannot login from another computer before not killing that specific Xvnc session

As Fedora's VNC implementation is TigerVNC, you can kill Xvnc session automatically using `-MaxDisconnectionTime` option of TigerVNC.

This is an example how `sesman.ini` should be modified.
```diff
[Xvnc]
param=Xvnc
param=-bs
param=-nolisten
param=tcp
param=-localhost
param=-dpi
param=96
+param=-MaxDisconnectionTime
+param=60
```

> local user first logs in and password is requested for 5-9 times like for

these should help you.
* https://bugzilla.redhat.com/show_bug.cgi?id=1149893
* https://c-nergy.be/blog/?p=12073

**Comment by metalefty** [comment]
No feed back from the reporter almost 2 months, closing.
