### ISSUE TITLE
mouse forward/back button and horizontal scroll

### ISSUE THREAD

**Issue by okhowang** [neutrinolabs/xrdp#1477]
my mouse has no horizontal scroll function, but has forward/back button.
when using mstsc with xrdp, I found  forward/back button event was transfer as button 6/7 in `xrdp_wm_process_input_mousex`
```c
    if (device_flags & PTRXFLAGS_DOWN)
    {
        if (device_flags & PTRXFLAGS_BUTTON1)
        {
            xrdp_wm_mouse_click(self, x, y, 6, 1);
        }
        else if (device_flags & PTRXFLAGS_BUTTON2)
        {
            xrdp_wm_mouse_click(self, x, y, 7, 1);
        }
    }
    else
    {
        if (device_flags & PTRXFLAGS_BUTTON1)
        {
            xrdp_wm_mouse_click(self, x, y, 6, 0);
        }
        else if (device_flags & PTRXFLAGS_BUTTON2)
        {
            xrdp_wm_mouse_click(self, x, y, 7, 0);
        }
    }
```
but in `xrdp_wm_process_input_mousex`, button 6/7 was described as horizontal scroll. and it's will be trigger multiple times when press up/down mouse button
```c
                /* horizontal scroll */

                if (but == 6)
                {
                    self->mm->mod->mod_event(self->mm->mod, WM_BUTTON6DOWN,
                                             self->mouse_x, self->mouse_y, 0, 0);
                    self->mm->mod->mod_event(self->mm->mod, WM_BUTTON6UP,
                                             self->mouse_x, self->mouse_y, 0, 0);
                }

                if (but == 7)
                {
                    self->mm->mod->mod_event(self->mm->mod, WM_BUTTON7DOWN,
                                             self->mouse_x, self->mouse_y, 0, 0);
                    self->mm->mod->mod_event(self->mm->mod, WM_BUTTON7UP,
                                             self->mouse_x, self->mouse_y, 0, 0);
                }
```
it lead that in linux desktop, I will got keypress and keyrelease event when I PRESS button, and after I release the button, it's got a keypress and keyrelease event again.

**Comment by okhowang** [comment]
according to [https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/5073f4ed-1e93-45e1-b039-6e30c385867c](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/5073f4ed-1e93-45e1-b039-6e30c385867c)
horizontal scroll should in mouse event, not mousex event
maybe there is mistake when process mousex event.

**Comment by metalefty** [comment]
FTR, 2.2.8.1.1.3.1.1.3 Mouse Event (TS_POINTER_EVENT).

**Comment by metalefty** [comment]
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/2c1ced34-340a-46cd-be6e-fc8cab7c3b17
