### ISSUE TITLE
belgian keyboard  in rdpinput.c

### ISSUE THREAD

**Issue by petoetje** [neutrinolabs/xrdp#148]
- in ~/.xsessionrc we put "setxkbmap -model pc104 -layout be", but after a few seconds keyboard switches back to layout "us".
- traced this down to "rdpinput.c", function"rdpLoadLayout", which does not know "Belgian" (0x00000813 or 0x0000080C).  Thus this function, which runs after normal X init scripts, reverts keyboard back to "us"
- added Belgian case to function 

``` c
case 0x00000813: /* Belgian */
            set.layout = "be";
            break;
```
- partial success : without needing to call setxkbmap, keyboard is azerty (good), but altgr does not work (bad)
- "setxkbmap be" makes altgr work.  Strange : output of "setxkbmap -query" before calling "setxkbmap be" and after calling is identical.  Yet before altgr does not work
- ended up stubbing call to rdpLoadlayout in "rdpup.c", function "rdpup_process_msg" , thus preventing xrdp from changing the keyboard layout. We set the keyboard layout in ~/.xsessionrc
- disadvantage : keyboard layout is fixed, not changing depending on rdp client

**Comment by metalefty** [comment]
I've add Belgian keybaord #858. Now it should work fine.
