### ISSUE TITLE
Default TCP send buffer size too low

### ISSUE THREAD

**Issue by oofnikj** [neutrinolabs/xrdp#1483]
On a 1920x1080x32bpp display shared over a ~300mbit 802.11ac wifi network, the performance of `xrdp` is kind of lackluster with the default TCP send buffer size of 32768 bytes.

The defaults set in `xrdp.ini` are as follows:
```
[Globals]
#tcp_send_buffer_bytes=32768
#tcp_recv_buffer_bytes=32768
tcp_nodelay=true
tcp_keepalive=true
```

When uncommented, `xrdp` uses these values to set the send and recieve buffer sizes.

This results in send/recieve buffers of 65536 bytes each, respectively, since the (Linux) kernel doubles the value requested ([tcp man page](http://man7.org/linux/man-pages/man7/tcp.7.html)). Besides being printed in the log output, this can be independently confirmed by
```
$ ss -lnm sport 3389
Netid                State                 Recv-Q                Send-Q                                 Local Address:Port                                 Peer Address:Port                Process                
tcp                  LISTEN                0                     2                                            0.0.0.0:3389                                      0.0.0.0:*                   
	 skmem:(r0,rb65536,t0,tb65536,f0,w0,o0,bl0,d0)
```

I noticed that `xrdp` wasn't even close to saturating the link speed, which is what prompted this investigation.

By setting `tcp_send_buffer_bytes` to something a little more generous (e.g., `4194304`):
```
[Globals]
tcp_send_buffer_bytes=4194304
```

And increase the corresponding `sysctl` limit to 2x the requested buffer size:
```
$ sudo sysctl -w net.core.wmem_max=8388608
```

We get much improved performance (seamless window dragging, smooth scrolling, full screen FHD video playback).

I think this should be written somewhere - maybe in the wiki, in the man pages, or briefly mentioned as a comment in the stock `xrdp.ini`.

Hope this helps someone.

**Comment by TeslaCN** [comment]
Thanks! This is very helpful.

**Comment by tobih7** [comment]
Does it make sense to set the value to 32 MiB (33554432 bytes) or does a too high value have negative effects?

**Comment by ivanbaldo** [comment]
Shouldn't XRDP just leave that value out and use the kernel default?

I think the kernel autosizes that value depending on the congestion window and the receive window which is adjusted by packet loss signals or other methods (in BBR).

If I understand correctly, the kernel uses up to 6 MiB by default.

The size should be the BDP (Bandwidth-Delay Product) and that calculation should be small for a WiFi net.

In terms of interactivity I think setting net.ipv4.tcp_notsent_lowat (also can be set by the application) to for example 16 KiB is beneficial.

Maybe apps can also select a preferred congestion algorithm, which in this case, BBR should be a good option.

Also we can help users by writing some doc about suggested kernel settings to improve interactivity and performance.

**Comment by matt335672** [comment]
If you leave the values out of the config file, xrdp will use the kernel defaults.

**Comment by rowlap** [comment]
FWIW, some example BDP calculations for buffer size 32768:
* 262mbps @ 1ms RTT
* 26mbps @ 10ms RTT
* 13mbps @ 20ms RTT
* 5mbps @ 50ms RTT

Regularly seeing xrdp pushing 50-100mbps under load test, allowing the OS to auto-scale the buffer size is desirable, and I'm not sure if it's even possible after `setsockopt` pins the value.

**Comment by matt335672** [comment]
Thanks @rowlap 

There's a Linux workaround for the current behaviour in [this post](https://github.com/neutrinolabs/xrdp/issues/2905#issuecomment-1880694050) which is part of issue #2905.

A fix is in PR #2910 which I'm hopeful we'll merge for v0.10.x

**Comment by ciroiriarte** [comment]
What about tcp_recv_buffer_bytes?

**Comment by matt335672** [comment]
@ciroiriarte - I don't think the same 32K limit was ever applied to the receive buffer. I can't find any evidence of it in the source code.
