### ISSUE TITLE
Connection Issue - Problem connecting, some problem

### ISSUE THREAD

**Issue by artlemaks** [neutrinolabs/xrdp#1486]
Hello,
I have an issue when trying to connect to my VM using XRDP. When trying to login, I get the following error message
![image](https://user-images.githubusercontent.com/25079150/72877603-31e38280-3cf1-11ea-90e7-d74e8def5439.png)

I check the sesman.log file and here is what it says 

>  [20200122-08:21:25] [INFO ] A connection received from 127.0.0.1 port 39322
> [20200122-08:21:25] [INFO ] ++ created session (access granted): username azureuser, ip 86.42.180.192:65247 - socket: 12
> [20200122-08:21:25] [INFO ] starting Xvnc session...
> [20200122-08:21:25] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5914)
> [20200122-08:21:25] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6014)
> [20200122-08:21:25] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6214)
> [20200122-08:21:25] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
> [20200122-08:21:25] [INFO ] calling auth_start_session from pid 100581
> [20200122-08:21:25] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
> [20200122-08:21:25] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
> [20200122-08:21:25] [ERROR] Error creating .vnc directory: Permission denied
> [20200122-08:21:35] [ERROR] X server for display 14 startup timeout
> [20200122-08:21:35] [ERROR] X server for display 14 startup timeout
> [20200122-08:21:35] [CORE ] waiting for window manager (pid 100585) to exit
> [20200122-08:21:35] [ERROR] another Xserver might already be active on display 14 - see log
> [20200122-08:21:35] [DEBUG] aborting connection...
> [20200122-08:21:36] [CORE ] window manager (pid 100585) did exit, cleaning up session
> [20200122-08:21:36] [INFO ] calling auth_stop_session and auth_end from pid 100581
> [20200122-08:21:36] [DEBUG] cleanup_sockets:
> [20200122-08:21:36] [INFO ] shutting down sesman 1

I'm not sure what is the issue that I'm facing? There is something about a denied permission, but I'm not sure how to address that?

**Comment by matt335672** [comment]
```
[20200122-08:21:25] [ERROR] Error creating .vnc directory: Permission denied
```
The session code is trying to create a directory `~/.vnc` for your logging in user (azureuser), and is unable to. Without this directory, and the file it contains, the X server `Xvnc` will not start.

The directory creation happens in the context of azureuser. That suggests the user doesn't have a home directory or the home directory isn't writeable.

Are you using SELinux? Can you log in using ssh?

**Comment by artlemaks** [comment]
> ```
> [20200122-08:21:25] [ERROR] Error creating .vnc directory: Permission denied
> ```
> 
> The session code is trying to create a directory `~/.vnc` for your logging in user (azureuser), and is unable to. Without this directory, and the file it contains, the X server `Xvnc` will not start.
> 
> The directory creation happens in the context of azureuser. That suggests the user doesn't have a home directory or the home directory isn't writeable.
> 
> Are you using SELinux? Can you log in using ssh?

I am using CentOS and yes, I can login using SSH. I have noticed just now that when I login to SSH, the very first message that I see is 

> Could not chdir to home directory /home/azureuser: No such file or directory

**Comment by matt335672** [comment]
You'll need to create a (writeable) home directory for your user in order to use XRDP.

It will be useful for ssh too, as you can then use keys to log in rather than passwords.

Hope that's useful.

**Comment by artlemaks** [comment]
Ok. Can you point me in a direction as to how it should be done? I'm fairly new to Linux. 

Thank you.

**Comment by matt335672** [comment]
Off the top of my head, there are two possibilities here, and I don't know which applies to your situation. One of this is (hopefully) useful!

If your user is a local user in `/etc/passwd`, the following wlll be adequate, run as root:-
```
usermod -d /home/azureuser azureuser
```

If your user is from a directory service (i.e. LDAP / Active Directory) and you are expecting other users to use this machine, you should be configuring the machine to create home directories when users log in. The link to the directory service will probably have been created with the `authconfig` command or `system-config-authentication` GUI. There's an option on those both (I think) to enable this feature.

If you've got a default CentOS installation, you'll also need to install the `xrdp-selinux` RPM if you haven't done so already.

**Comment by artlemaks** [comment]
Thank you so much for your input. I have now been able to login to my machine through RDP! 

Once again, thank you :)
