### ISSUE TITLE
XRDP: Cannot with AD user on CentOS 8

### ISSUE THREAD

**Issue by mfcosta** [neutrinolabs/xrdp#1489]
Dears, good morning,
I'm trying to setup xrdp tp allow domain users from Active Directory authenticate using Microsoft Remote Desktop on CentOS, but I'm failing to properly setup it.
Right now, any CentOS local user can authenticate local and remote, and AD users can authenticate local, but not remotely

sssd.conf:

> [sssd]
domains = training.local
config_file_version = 2
services = nss, pam
[domain/training.local]
ad_domain = training.local
krb5_realm = TRAINING.LOCAL
realmd_tags = manages-system joined-with-adcli
cache_credentials = True
id_provider = ad
krb5_store_password_if_offline = True
default_shell = /bin/bash
ldap_id_mapping = True
use_fully_qualified_names = True
fallback_homedir = /home/%u@%d
simple_allow_users = $
access_provider = ad
ad_gpo_access_control = permissive

/var/log/secure
> Jan 30 08:00:44 localhost xrdp-sesman[4103]: pam_sss(xrdp-sesman:auth): authentication success; logname= uid=0 euid=0 tty=xrdp-sesman ruser= rhost= user=administrator@training.local
Jan 30 08:00:44 localhost xrdp-sesman[4103]: pam_sss(xrdp-sesman:account): Access denied for user administrator@training.local: 6 (Permission denied)
Jan 30 08:00:52 localhost xrdp-sesman[4103]: pam_sss(xrdp-sesman:auth): authentication success; logname= uid=0 euid=0 tty=xrdp-sesman ruser= rhost= user=administrator@training.local
Jan 30 08:00:52 localhost xrdp-sesman[4103]: pam_sss(xrdp-sesman:account): Access denied for user administrator@training.local: 6 (Permission denied)

/etc/pam.d/xrdp-sesman
> #%PAM-1.0
auth       include      password-auth
account    include      password-auth
password   include      password-auth
session    include      password-auth
#auth       include      gdm-password
#account    include      gdm-password
#password   include      gdm-password
#session    include      gdm-password

**Comment by odeneriksson** [comment]
xrdp from epel8 is not built with kerberos support, that's why?

**Comment by matt335672** [comment]
What CentOS major version is this?

It's clear from your logs that pam_sss is failing on account validation with permission denied. The authentication stage has already succeeded.

I no longer have access to a suitable setup for looking at these sort of problems, but I can give you a couple of possible leads:-
- Does ssh work for your AD users? If not, this would be a good place to start looking.
- Try winding up the sssd `debug_level` (see sssd.conf(5)), and then checking to see if you get more information from the sssd logging. For CentOS 7, this will be under `/var/log/sssd`. I don't yet know about CentOS 8 I'm afraid.

Hope that's a bit useful.

**Comment by mfcosta** [comment]
Hi all,
Acctually, we changed the whole server scope. We aren't going to use GUI anymore, as both servers will be used only for PostgreSQL 11. We are going to implement them with bash interface only, and I will install SSH for remote access.
Thank you for your support.

**Comment by Hashfastr** [comment]
Sorry to necro-bump but I found a solution. The problem appears to deal with GPO access configuration with SSSD and PAM modules. The default if you haven't configured this, or don't know how to, is to deny all access regardless. To disable this functionality and allow for xrdp for your Kerberos systems add this line to your domain configuration:

```
# /etc/sssd/sssd.conf
[domain/example.com]
...
ad_gpo_access_control = disabled
```

You can verify you're affected by looking for a log entry like these in `/var/log/sssd/sssd_ad.example.com.log` after putting SSSD into log level 4 by adding `debug_level = 4` to the `[sssd]` section in `/etc/sssd/sssd.conf`. 

```
# /var/log/sssd/sssd_ad.example.com.log
   *  (2023-05-23 11:10:18): [be[example.com]] [ad_gpo_access_send] (0x0400): [RID#6] Configuration hint: PAM service 'xrdp-sesman' is not mapped to any Group Policy rule. If you plan to use this PAM service it is recommended to use the ad_gpo_map_* family of options to map this PAM service to a Group Policy rule. PAM services not present in any map will fall back to value set in ad_gpo_default_right, which is currently set to Denied (see manual pages 'man sssd-ad' for more details).
   *  (2023-05-23 11:10:18): [be[example.com]] [ad_gpo_access_send] (0x0400): [RID#6] service xrdp-sesman maps to Denied
   *  (2023-05-23 11:10:18): [be[example.com]] [ad_gpo_access_done] (0x0040): [RID#6] GPO-based access control failed.
```

If you want to further configure GPOs then glhf, out of the scope of this message.

Resources:

- https://linux.die.net/man/5/sssd-ad
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/identity_management_guide/sssd-gpo
