### ISSUE TITLE
Typo in readme, pkgconfig instead of pkg-config

### ISSUE THREAD

**Issue by LazzariPaolo** [neutrinolabs/xrdp#1492]
> To compile xrdp from a checked out git repository, you would additionally need ... pkgconfig.

```
$ sudo apt-get install pkgconfig
E: Unable to locate package pkgconfig
```

I believe `pkgconfig` should be `pkg-config`

```
$ sudo apt-get install pkg-config
```

**Comment by matt335672** [comment]
Agreed - this name is used on both Debian and CentOS
