### ISSUE TITLE
Blue screen and error "connection problem, giving up. some problem" on Mac OS X Catalina

### ISSUE THREAD

**Issue by arpsyapathy** [neutrinolabs/xrdp#1511]
Hi all!

I install xrdp and xorg step by step with this manual.
https://github.com/neutrinolabs/xrdp/wiki/Building-on-OSX-(not-official)
When i try connect and login i get blue screen and in xrdp.log this error:

> [20200311-18:09:36] [DEBUG] xrdp_wm_log_msg: connection problem, giving up
> [20200311-18:09:36] [DEBUG] Closed socket 18 (AF_UNIX)
> [20200311-18:09:36] [DEBUG] xrdp_wm_log_msg: some problem
> [20200311-18:09:36] [DEBUG] xrdp_mm_module_cleanup

How fix it? Thank you

**Comment by liaolunhui** [comment]
+1

**Comment by metalefty** [comment]
No update. We don’t support macOS officially. Closing.
