### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [neutrinolabs/xrdp#1514]
I would like to point out that identifiers like “[`_RAIL_H`](https://github.com/neutrinolabs/xrdp/blob/e7c0b11336bce95fbd2c8a5624bb476f038536de/common/rail.h#L19 "Update candidate")” and “[`_SOUND_H_`](https://github.com/neutrinolabs/xrdp/blob/e7c0b11336bce95fbd2c8a5624bb476f038536de/sesman/chansrv/sound.h#L19 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
How do you think about to avoid that [this software](https://github.com/neutrinolabs/xrdp/blob/ce10d3a1a8ebeae56ea88de8854a11f8161880b3/sesman/chansrv/irp.h#L24 "Update candidate") [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by matt335672** [comment]
We'll be happy to take a PR from you.
