### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [neutrinolabs/xrdp#1516]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages "Description for enumerated types") to stress their relationships?
- [CRYPT_LEVEL…](https://github.com/neutrinolabs/xrdp/blob/ae1514c1679e87edfdeba5ca3eb2b3659ef44b1a/libxrdp/libxrdp.h#L87)
- [WTS_CHANNEL_OPTION…](https://github.com/neutrinolabs/xrdp/blob/e7c0b11336bce95fbd2c8a5624bb476f038536de/xrdpapi/xrdpapi.h#L36)

**Comment by metalefty** [comment]
What for?

**Comment by elfring** [comment]
* Are enumeration identifiers better usable for software debugging than these preprocessor symbols?
* How do you think about to provide further reusable data types?
