### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [neutrinolabs/xrdp#1517]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output") ⇒ [main](https://github.com/neutrinolabs/xrdp/blob/e7c0b11336bce95fbd2c8a5624bb476f038536de/genkeymap/genkeymap.c#L136)
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [tc_mutex_create](https://github.com/neutrinolabs/xrdp/blob/e7c0b11336bce95fbd2c8a5624bb476f038536de/common/thread_calls.c#L101)

**Comment by metalefty** [comment]
Pull request please.
