### ISSUE TITLE
xrdp and xrdp-sesman crash when trying to access with rdesktop

### ISSUE THREAD

**Issue by tiago-as** [neutrinolabs/xrdp#1526]
Hi, I'm using xrdp as a bridge into x11vnc. When I try to access the machine with rdesktop the xrdp services crash without much output.

* Operating System: Kubuntu 20.04 (early versions)
* Xrdp version used: 0.9.12-1
* Xorgxrdp version used: 1:0.2.12-1
* rdesktop version used: 1.9.0-2
* x11vnc command used: `x11vnc -localhost -accept popup -passwd $TEMPPWD`

xrdp.ini file:

```
[globals]
ini_version=1
bitmap_cache=yes
bitmap_compression=yes
port=3389
crypt_level=low
channel_code=1
max_bpp=24
ssl_protocols=TLSv1.2, TLSv1.3
allow_channels=true

[Logging]
LogFile=xrdp.log
LogLevel=DEBUG
EnableSyslog=true
SyslogLevel=DEBUG

[Channels]
; Channel names not listed here will be blocked by XRDP.
; You can block any channel by setting its value to false.
; IMPORTANT! All channels are not supported in all use
; cases even if you set all values to true.
; You can override these settings on each session type
; These settings are only used if allow_channels=true
rdpdr=true
rdpsnd=true
drdynvc=true
cliprdr=true
rail=true
xrdpvr=true
tcutils=true

[Console]
name=console
lib=libvnc.so
ip=127.0.0.1
port=5900
password=ask

```

rdesktop command used and output:
```
$ rdesktop -v -k pt 192.168.1.165
is_wm_active(): WM name: KWin
Connecting to server using NLA...
Connection established using plain RDP.
Connection successful
Clipboard(error): xclip_handle_SelectionNotify(), unable to find a textual target to satisfy RDP clipboard text request
Protocol(warning): process_data_pdu(), unhandled data PDU type 40
Core(error): tcp_recv(), recv() failed: Connection reset by peer
Disconnecting...
Disconnected due to network error, exiting...
disconnect: Unknown reason.
```

Using rdesktop with version 1.8.3-1 on an Ubuntu 16.04 XRDP does not crash - it works just fine with the **same configuration**.

**Comment by metalefty** [comment]
It doesn't look xrdp is crashing.

**Comment by matt335672** [comment]
Hi @tiago-as 

Is this the same issue as #1569? If so can I close this one? Or feel free to close it yourself,

**Comment by tiago-as** [comment]
Hi, @matt335672,

No these are different. In the case of this issue I was using a VNC backend and it was a manual authorization from the server in order to access via XRDP.

In case of #1569 I'm setting up XRDP with xorgxrdp backend and in server mode to be used as a remote system for thin clients.

The cause might be the same so I will also check if the solution is usable for this issue aswell. If so I'll mark close the issues and let you know so you mark it as duplicate.

Is that ok?

**Comment by matt335672** [comment]
That's great - thanks.

**Comment by matt335672** [comment]
Hi @tiago-as 

Are you maybe in a position to check whether setting `use_fastpath=both` fixes this issue in the same way it fixes #1569?

Thanks

**Comment by tiago-as** [comment]
@matt335672 I'm going to try to reproduce this issue. And try the option ti fix.

I'll let you know. Thank you so much for the help

**Comment by tiago-as** [comment]
@matt335672 just confirmed that the setting `use_fastpath=both` fixes the crash issue.
Same problem different situation. I don't know how you guys handle the flow of issues but, feel free to mark it as duplicate if it fits :D 
Once again, thanks for the help
