### ISSUE TITLE
memory out of bounds write in scard_process_list_readers

### ISSUE THREAD

**Issue by hac425xxx** [neutrinolabs/xrdp#1533]
**version**

```
https://github.com/neutrinolabs/xrdp/blob/1c4e14415d923666ac60cb77c7e753ca24e0268d/sesman/chansrv/smartcard_pcsc.c#L600
```

**vuln**

`scard_process_list_readers` first read 4 bytes to `bytes_groups`, then use `g_malloc(bytes_groups + 1, 1)` to alloc memory.

if  `bytes_groups=0xffffffff` , it could trigger Integer overflow (`0xffffffff+1=0`), it could alloc 0 size memory to `groups`.

Then it could use `in_uint8a`  to copy data to  `groups`. resulting in **out-of-bounds write**

```
int
scard_process_list_readers(struct trans *con, struct stream *in_s)
{
    ..............................
    ..............................
    in_uint32_le(in_s, hContext);
    in_uint32_le(in_s, bytes_groups);
   
    groups = (char *) g_malloc(bytes_groups + 1, 1); // 0xffffffff + 1 = 0
    in_uint8a(in_s, groups, bytes_groups);  // copy 0xffffffff data to groups
```

**Comment by metalefty** [comment]
Thank you very much but why not create a pull request?
