### ISSUE TITLE
xrdp 0.9.5 / ubuntu 18.04.1 - Multiple screens - window content not erased dragging around

### ISSUE THREAD

**Issue by rhy-ama** [neutrinolabs/xrdp#1548]
Hello,

Using Windows 7 rdp client on ubuntu host. Client pc has nvidia nvs 450 4 monitor gfx. When connecting to the ubuntu machine using all screens, screens are available, but dragging windows around produces tracer effect - ie. old window position is not erased / replaced by background.

**Comment by metalefty** [comment]
Why not share screenshot?

**Comment by rhy-ama** [comment]
@metalefty if YOU think the description of the tracing effect - moving window around does not erase the old position - is not clear, if so i will gladly share the screenshot. otherwise i do not see the need to do so.

**Comment by derekschrock** [comment]
@rhy-ama What window manager are you running in the xrdp session and do you know if it paints the root window's background at startup?

In the RDP session can you run `xsetroot -s black` in a terminal?

**Comment by matt335672** [comment]
Closing this - no-one's looked at it in 4 years, and things have moved on a bit since then.
