### ISSUE TITLE
Ubuntu 18.04 Xrdp is not running without the user is logged in

### ISSUE THREAD

**Issue by zaher88abd** [neutrinolabs/xrdp#1552]
Hello,

I want to use xrdp with Jetson Nano, but I have issue where the xrdp not working if I didn't loggedin, And when the user is logout, I am getting an error message "Remote access to the server is not enabled ..."

Is there any solution, please.

**Comment by matt335672** [comment]
Closing this - no-one's looked at it in 4 years, and things have moved on a bit since then.
