### ISSUE TITLE
Audio not working after xRDP session

### ISSUE THREAD

**Issue by MEA707** [neutrinolabs/xrdp#1556]
I am not sure if this is an xRDP issue or a PulseAudio issue, but I have found after I have completed a remote session from Windows 10 to the Linux PC (Linux Mint 19.3 64-bit) using xRDP, the audio does not work when I go back and physically log on.

Checking the sound properties, it still shows "Dummy Output" instead of recognizing the sound card. Logging off and back on, doesn't fix it. Only a restart or running `pulseaudio -k` in the terminal restores the audio.

I do not have the xrdp pulseaudio module installed, although previously when I did, the same behavior was exhibited except instead of "Dummy Output" it was the "xrdp sink" from the xrdp audio.

This is on a clean install of Linux Mint 19.3.

I did test it also in Ubuntu 18.04.4 virtual machine and got the same behavior.

Not sure if there's any logs I can pull, but if there are any let me know and I'd be happy to run them.

I'm using xRDP 9.5-2 from the official Ubuntu PPA.

Thanks for any help.

**Comment by jsorg71** [comment]
I see this too.  If you log out and back in within 20 seconds, audio does not work.
The pulseaudio daemon has a 20 second timeout from when the last audio client disconnects to when the daemon exits.  I have a fix or you can open a prompt and run pulseaudio --kill after you login for now.
It would be nice if you can verify the 20 second timeout.

**Comment by MEA707** [comment]
@jsorg71,

Just tested it by waiting 30 seconds and I got sound. Thanks for that! If there is a way to fix it, that'd be great, otherwise I don't mind waiting 20+ seconds or using pulseaudio -kill.

Thanks again.

**Comment by jsorg71** [comment]
You can add this line to the end of /etc/xrdp/sesman.ini(adding it to the SessionVariables section)
PULSE_CONFIG=/etc/xrdp/pulse/daemon.conf
and create the file
/etc/xrdp/pulse/daemon.conf
and just have this one line in it
exit-idle-time = 2
This changes it from 20 seconds to 2
But you will still have the problem when you log out of console and log in to xrdp session in less than 20 seconds.

**Comment by MEA707** [comment]
Thanks for that.

**Comment by ameeno** [comment]
Hello, following on from this, If i am using Xrdp under hyper-V for Vsock Connections,

I have a pulse server installed on windows and running as a service. DO i need to install XRDP-Pulse-Sink and redirect audio via xrdp, or can I use the current pulse server settings that send pulse audio to my windows desktop via PULSE_SERVER environment Variable?

**Comment by matt335672** [comment]
I'm closing this issue now. Version 0.6 of the pulseaudio module [has been released](/neutrinolabs/pulseaudio-module-xrdp/releases/tag/v0.6) with significant changes, and the [wiki README](/neutrinolabs/pulseaudio-module-xrdp/wiki/README) has been updated with better build instructions.
