### ISSUE TITLE
Ubuntu 20.04 - Audio compilation Error

### ISSUE THREAD

**Issue by gamersalpha** [neutrinolabs/xrdp#1564]
Hello there, i m on Lubuntu 20.04 with XRDP installed
```
root@Poste01:/home/issa/Téléchargements/pulseaudio-13.99.1# xrdp -v
xrdp 0.9.12
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2018 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -fdebug-prefix-map=/build/xrdp-GJgww4/xrdp-0.9.12=. -fstack-protector-strong -Wformat -Werror=format-security
      LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2
      PKG_CONFIG_PATH=/build/xrdp-GJgww4/xrdp-0.9.12/pkgconfig

  Compiled with OpenSSL 1.1.1f  31 Mar 2020
```
and works not bad, is not verysmouth, but works, i just have an issue with sound

so i see the wiki sound : https://github.com/neutrinolabs/xrdp/wiki/Audio-Output-Virtual-Channel-support-in-xrdp

so i look my version : 

```
root@Poste01:/home/issa/Téléchargements/pulseaudio-13.99.1# pulseaudio --version
pulseaudio 13.99.1
```
so i donwload my version pulseAudio plugin : 

`wget https://freedesktop.org/software/pulseaudio/releases/pulseaudio-13.99.1.tar.gz`

i extract : 

`tar -xzvf pulseaudio-13.99.1.tar.gz`

i start configuration : 
```

root@Poste01:/home/issa/Téléchargements/pulseaudio-13.99.1# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for stow... no
checking whether make supports nested variables... (cached) no
checking whether ln -s works... yes
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/home/issa/Téléchargements/pulseaudio-13.99.1':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
```

and this is what i see in config.log : 

```
root@Poste01:/home/issa# tail -f config.log
#define PACKAGE_TARNAME "pulseaudio"
#define PACKAGE_VERSION "13.99.1"
#define PACKAGE_STRING "pulseaudio 13.99.1"
#define PACKAGE_BUGREPORT "pulseaudio-discuss (at) lists (dot) freedesktop (dot) org"
#define PACKAGE_URL "http://pulseaudio.org/"
#define PACKAGE "pulseaudio"
#define VERSION "13.99.1"
#define CANONICAL_HOST "x86_64-pc-linux-gnu"

configure: exit 1

```

do u have some help for me
please

**Comment by gamersalpha** [comment]
Missing some prerequis : 

`apt-get install gcc m4 libltdl-dev`

but now i m stuck on this : 

```
checking whether SYS_memfd_create is declared... yes
checking for memfd_create... yes
checking for X11... no
checking for library containing cap_init... no
checking sys/capability.h usability... no
checking sys/capability.h presence... no
checking for sys/capability.h... no
configure: error: *** sys/capability.h not found.  Use --without-caps to disable capabilities support.

```

**Comment by metalefty** [comment]
I don't see any errors in your last try.

**Comment by matt335672** [comment]
Hi @gamersalpha - if I read your description properly you're starting by building pulseaudio.

You can track most down the dependencies you need  by looking at the way the pulseaudio deb package is built on 20.04.

In brief:-
- Find the source package for pulseaudio in https://packages.ubuntu.com. It's [here](https://packages.ubuntu.com/source/focal/pulseaudio).
- Following the link to the version control system which takes you [here](https://git.launchpad.net/~ubuntu-audio-dev/pulseaudio).
- You'll need to select the correct git branch to get the right file. At the moment, fortunately that seems to be the current branch.
- On the tree tab, browse down to the debian/control file [here](https://git.launchpad.net/~ubuntu-audio-dev/pulseaudio/tree/debian/control).

The Build-Depends stanza tells you what packages are needed to build pulseaudio on a focal system.

I hope that's useful. I'm a bit strapped for time today, but if you're still stuck after that, we'll try to get you going tomorrow.

**Comment by gamersalpha** [comment]
Hello, 
so i sucefill run the ./configure

now i m stuck on the next step,
i can 't found the directory  : 

> 
> Note: You don't need to actually build the downloaded pulse audio.
> 
> Next, cd into xrdp/sesman/chansrv/pulse
> 
> You need to edit the Makefile in that directory in order to build the pulse sink.

**Comment by matt335672** [comment]
Hi @gamersalpha 

Sorry about the confusion yesterday - I didn't have much time and I don't appear to have helped at all.

I've studied the above messages, and I'm a bit confused as to where you are at the moment. Importantly, the first comment I have is that the **Wiki link you are using is now obsolete**. The correct one is:-

[https://github.com/neutrinolabs/pulseaudio-module-xrdp/wiki/README](https://github.com/neutrinolabs/pulseaudio-module-xrdp/wiki/README)

However, I think this page could do with updating anyway.

Could I please ask you to try the instructions on this page I've just created:-

[https://github.com/matt335672/xrdp/wiki/README](https://github.com/matt335672/xrdp/wiki/README)

I've got as far as making sure the modules build on 20.04, so hopefully you'll be able to follow my instructions and tell me if they don't make sense or don't work.

Let me know how it goes.

**Comment by matt335672** [comment]
Hi @gamersalpha 

Have you managed to make any further progress with this? Can I help you any further?

**Comment by matt335672** [comment]
No more feedback, so closing this for now.
