### ISSUE TITLE
Broken image on "XRDP Architecture Overview" page

### ISSUE THREAD

**Issue by darac** [neutrinolabs/xrdp#1567]
The image on https://github.com/neutrinolabs/xrdp/wiki/XRDP-Architecture-Overview is currently showing as "This image is no longer available. Visit tinypic.com for more information".

**Comment by metalefty** [comment]
Thanks for the report. There should be an image like this. The original image should be somewhere in my hard drive....
https://bz-attachments.freebsd.org/attachment.cgi?id=167166

**Comment by metalefty** [comment]
@jsorg71 do you have that overview image?

**Comment by metalefty** [comment]
I found it in my hard drive.

![xrdp_arch](https://user-images.githubusercontent.com/941609/81632210-aed36d00-9444-11ea-8429-d1c1598e2241.png)
