### ISSUE TITLE
Ubuntu 20.04, XFCE4 V4.14 : Can not sudo GUI programs in xrdp-sessions anymore

### ISSUE THREAD

**Issue by ICarryTheDustOfAJourney** [neutrinolabs/xrdp#1568]
When logged in locally, I can. This wasn't the case when used in 18.04
```
sudo thunar [pswd]

thunar: Failed to initialize Xfconf: Error spawning command line ?dbus-launch --autolaunch=2eab04bc9f74426393f809c967db3791 --binary-syntax --close-stderr?: Child process exited with code 1

No protocol specified
Unable to init server: Could not connect: Verbindungsaufbau abgelehnt

(thunar:1268): Gtk-WARNING **: 13:29:56.214: cannot open display: :10.0
```
Everything up-to-date. 
Edit: using lightdm
Edit2: using dbus-x11

**Comment by metalefty** [comment]
First of all, you should not use `sudo` to run GUI applications in root privilege.
https://help.ubuntu.com/community/RootSudo

**Comment by ICarryTheDustOfAJourney** [comment]
The proposed workarounds don't work, I already tried that.
pkexec doesn't even work in a local session. 
We need GUI tools for all kinds of administrative tasks.

**Comment by metalefty** [comment]
I didn't proposed anything but I just said you shouldn't use `sudo` in that case. 
Anyway, it seems the issue is not xrdp issue.

**Comment by metalefty** [comment]
I just wanted to show you using sudo in such case is not recommended at all. Not to show you alternative workaround. As mentioned in the article, it contains old stuff. However, the part sudo is not recommended is still true.

> March 14, 2019 PLEASE NOTE: This wiki article is being significanly rewritten as it contains a good deal of old, dated and possibly questionable material. Using caution and consulting with others on the Ubuntu Forums or Ask Ubuntu is highly recommended!

BTW, how pkexec didn't work?

**Comment by matt335672** [comment]
Please pardon me for jumping in on this one.

@metalefty is correct in that you should be using `pkexec` to do this.

I've got a fairly fresh install of Xubuntu 20.04 here with:-
- `xrdp` and `xorgxrdp` installed
- `dbus-user-session` removed (see the [wiki](../wiki/Debian-dbus-user-session-package)).

I can log in on the local X11 console with an admin user (i.e. one with sudo privileges), and the following command authenticates and runs Thunar:-

```
pkexec /usr/bin/thunar
```

Out-of-the-box, this does not work in an XRDP session. This is a consequence of the way polkit treats non-local sessions by default, and can be fixed as follows:-

In the local session, when thunar is authenticated, there's a 'Details' button. Pressing on this reveals the polkit action to be `org.xfce.thunar`.

You can query the base version of this action with the `pkaction` command:-
```bash
pkaction --action-id org.xfce.thunar -v
org.xfce.thunar:
  description:       Run Thunar as root
  message:           Authentication is required to run Thunar as root.
  vendor:            Thunar
  vendor_url:        https://xfce.org/
  icon:              system-file-manager
  implicit any:      no
  implicit inactive: auth_admin
  implicit active:   auth_admin
  annotation:        org.freedesktop.policykit.exec.path -> /usr/bin/thunar
  annotation:        org.freedesktop.policykit.exec.allow_gui -> true
```

The console session will come under `implicit active`.  The consequence of running `pkexec /usr/bin/thunar` in one of these sessions is that the action proceeds provided it is authenticated by an admin user. This is documented in `polkit(8)`.

XRDP sessions, along with any other remote sessions, come under `implicit any`. The above query illustrates that by default this is not permitted.

xubuntu 20.04 LTS comes with version 0.105 of polkit which is somewhat old. This allows actions to be overridden with `.pkla` files.

I've created a file `/etc/polkit-1/localauthority/50-local.d/xrdp-thunar.pkla` with the following contents:-

```
[Authorize thunar for remote sessions]
Identity=unix-user:*
Action=org.xfce.thunar
ResultAny=auth_admin
```
 
With this in place, I can now `pkexec /usr/bin/thunar` from an XRDP session (admin user), and it works as expected.

@ICarryTheDustOfAJourney - I hope the above is detailed enough to allow you to work out what's going on, and to authenticate other programs which you may need in remote sessions. First you'll need to get `pkaction` working in a local session.

**Comment by ICarryTheDustOfAJourney** [comment]
Wonderful, thank you! 

I got pkexec locally working by removing an apparently incorrect policy concerning the  "Managed Color Device"-authorisation.
 
With your help I then got thunar working as root remotely again, great! And finally I have an idea why many programs don't work when run using XRDP.
Then I tried the same approach for /usr/bin/baobab `xrdp-baobab.pkla` with 
```
[Authorize baobab for remote sessions]
Identity=unix-user:*
Action=org.freedesktop.policykit.exec
ResultAny=auth_admin
```
by using the info from the details-button in the autorisation dialog, but this didn't work:
```
Unable to init server: Could not connect: Connection refused
(baobab:1379): Gtk-WARNING **: 21:01:19.080: cannot open display: 
```
then
```
pkaction --action-id org.freedesktop.policykit.exec -v
org.freedesktop.policykit.exec:
  description:       Run programs as another user
  message:           Authentication is required to run a program as another user
  vendor:            The PolicyKit Project
  vendor_url:        http://hal.freedesktop.org/docs/PolicyKit/
  icon:              
  implicit any:      auth_admin
  implicit inactive: auth_admin
  implicit active:   auth_admin
```
Context: We are trying to give the not-so-console-liking admins of our server remote RDP-access, eg to conveniently find out where all the disk space went to etc.

**Comment by matt335672** [comment]
The PKLA file we added before just modified an existing action for Thunar.

For Baobab no action is defined by the system, and so what I think happens is the system falls back on `org.freedesktop.policykit.exec`. This action is missing the following magic line which the Thunar action includes:-

```
annotation:        org.freedesktop.policykit.exec.allow_gui -> true
```

Another indicator we have no policy is that `pkexec /usr/bin/baobab` doesn't work on the console either.

Action files are defined by XML and stored in  `/usr/share/polkit-1/actions/`. I've quickly knocked up the following action file, which you can try copying to `/usr/share/polkit-1/actions/mycorp.apps.baobab.policy`:-

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">

<policyconfig>

<!-- Choose action_id so as not to conflict with anything else -->
 <action id="mycorp.apps.baobab">
 <description>Run Baobab as root</description>

<!-- These appear on the authentication dialog box.

     The icon is the one provided by the baobab package
-->
 <vendor>mycorp</vendor>
 <vendor_url>https://wiki.mycorp.org/Apps/Baobab</vendor_url>
 <icon_name>org.gnome.baobab</icon_name>

 <defaults>
 <!-- allow_any set to auth_admin for XRDP users -->
 <allow_any>auth_admin</allow_any>
 <allow_inactive>auth_admin</allow_inactive>
 <allow_active>auth_admin</allow_active>
 </defaults>

 <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/baobab</annotate>
 <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
 </action>

</policyconfig>
```

With that done, I can query the new action `mycorp.apps.baobab`  with `pkaction`:-

```bash
$ pkaction | grep baobab
mycorp.apps.baobab
$ pkaction --action-id mycorp.apps.baobab -v
mycorp.apps.baobab:
  description:       Run Baobab as root
  message:           
  vendor:            mycorp
  vendor_url:        https://wiki.mycorp.org/Apps/Baobab
  icon:              org.gnome.baobab
  implicit any:      auth_admin
  implicit inactive: auth_admin
  implicit active:   auth_admin
  annotation:        org.freedesktop.policykit.exec.path -> /usr/bin/baobab
  annotation:        org.freedesktop.policykit.exec.allow_gui -> true
```
 
That should give you enough to play with. You'll want to pick a suitable action name and vendor info to suit your own environment.

Hopefully I've explained that clearly enough. I must emphasise that I'm not a policykit expert - I only really know enough to find my way about. The definitive docs for version 0.105 are here:-

[https://www.freedesktop.org/software/polkit/docs/0.105/](https://www.freedesktop.org/software/polkit/docs/0.105/).

**Comment by ICarryTheDustOfAJourney** [comment]
Excellent! This is what I was missing.

I really think your explanations deserve a more prominent place. It would have saved me (& probably others) a lot of time. I was not far from abandoning XRDP due to this problem.

I meanwhile found a quick & dirty workaround, just for others landing here after googling this subject: 
When opening a terminal from a pkexec'ed Thunar (recipe above), baobab and others run as root without complaints. Not really unexpected, but not the most elegant way to achieve it.

Thx a lot!

**Comment by matt335672** [comment]
Thanks for the feedback, and the additional info.

You're not the only person to comment on the documentation gap, although you've put it more tactfully than most others!

I think a large part of the documentation problem is that polkit, used by many desktop environments, is in general poorly understood. I'm certainly not criticising polkit - I suspect it's poorly understood largely because it's so well designed that for many users it simply isn't visible when used locally.

I'll have a think about what we can do to provide some documentation here which isn't going to be too onerous to keep up to date.

I'll leave this issue open for a couple of weeks, in case you feel like adding any more information to it. As you say, it may well be useful for others who come across this thread, in the absence of something more comprehensive.

**Comment by eastmoutain** [comment]
have a try:

```sh
$ su root
$ echo xfce4-session >~/.xsession
```
