### ISSUE TITLE
Require_authentication and Xrdp as a gateway

### ISSUE THREAD

**Issue by Elvinra** [neutrinolabs/xrdp#157]
XRDP.ini

require_authentication = yes, in connection sections, i was set ip=ask.
I'm use xrdp as a gateway with the domain (_IP)
but it's just black and nothing else.
When require_authentication = no, the field IP is set correctly.

I'm think is not implémented for require_authentication = yes

**Comment by metalefty** [comment]
v0.9.2 should work fine. It not, please reopen.
