### ISSUE TITLE
Unable to connect (xrdp 0.9.13, xorgxrdp 0.2.13) with Glamor enabled

### ISSUE THREAD

**Issue by seamus-x** [neutrinolabs/xrdp#1570]
Local: Chrome OS, Xtralogic RD Client
Remote: GNOME 3 on Debian 10

sesman initiates successfully, but unable to start session with unspecified error. See attached log.

[xrdp.log](https://github.com/neutrinolabs/xrdp/files/4589540/xrdp.log)

**Comment by metalefty** [comment]
xrdp.log doesn't matter in this case. Xorg log is need to see what's happening.

**Comment by seamus-x** [comment]
A couple scary lines...

[ 36586.736] (EE) systemd-logind: failed to take device /dev/dri/card0: Operation not permitted
[ 36586.736] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

[xorgxrdp.11.log](https://github.com/neutrinolabs/xrdp/files/4664552/xorgxrdp.log)

**Comment by seamus-x** [comment]
I should also mention that the system has two discrete graphics card and no integrated GPU, one AMD and one Nvidia. The Nvidia GPU is blacklisted as it is used on a VM via PCI passthrough, and both the guest and the host are accessed solely via remote sessions). The issue persists even with just 1 card installed for either one of them.

**Comment by jsorg71** [comment]
I don't see any glamor lines in you log, I don't think it's enabled.  But I think that's seperate.
The session not starting, did you setup /etc/X11/Xwrapper.config file?

**Comment by seamus-x** [comment]
That's odd, I used --enable-glamor option on configuring both xrdp and xorgxrdp. I did not alter the stock /etc/X11/Xwrapper.config file, the only active element is "allowed_users=console", though that did not prevent the session from starting using the Debian repository versions (0.9.9 xrdp /0.2.9 xorgxrdp).

**Comment by jsorg71** [comment]
I suspect they set sesman.ini to run the non root Xorg.
You can do that too, see notes in /etc/xrdp/sesman.ini

**Comment by seamus-x** [comment]
That did it! sesman.ini defaulted to Xorg instead of /usr/lib/xorg/Xorg; setting it to the latter fixed the session failing to start issue. The log still says nothing about glamor, though, and software rendering is still used.
[xorgxrdp.log](https://github.com/neutrinolabs/xrdp/files/4666306/xorgxrdp.log)

**Comment by jsorg71** [comment]
--enable-glamor does nothing for xrdp but when running ./configure --enable-glamor for xorgxrdp you should see
checking for XORG_SERVER... yes
checking for XORG_SERVER_GLAMOR... yes

**Comment by seamus-x** [comment]
Yep... 
[configure.txt](https://github.com/neutrinolabs/xrdp/files/4666564/configure.txt)

**Comment by seamus-x** [comment]
And here's /etc/X11/xrdp/xorg.conf
[xorg.conf.txt](https://github.com/neutrinolabs/xrdp/files/4666571/xorg.conf.txt)

**Comment by jsorg71** [comment]
ok, cool,
next make sure /dev/dri/renderD128 exists and can be opened by your user.
Check the rights on the file, you might have to add your user to 'render' or 'video' group.
Also, for you it might be /dev/dri/renderD129, not sure, if it is, that setting is in /etc/X11/xrdp/xorg.conf

**Comment by seamus-x** [comment]
Adding user to "render" group did it. Thanks for your help!

[ 52396.603] (II) XRDPDEV(0): glamor X acceleration enabled on Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 4.19.0-9-amd64, LLVM 7.0.1)
[ 52396.603] rdpPreInit: glamor init ok

**Comment by lixaotec** [comment]
@seamus-x i think i am passing through the same problem.

Have you accomplished using xRDP with hw acceleration?

**Comment by matt335672** [comment]
Closing this - no-one's looked at it in 4 years, and things have moved on a bit since then.
