### ISSUE TITLE
Cannot connect to linux via windows after installing xrdp

### ISSUE THREAD

**Issue by wajika** [neutrinolabs/xrdp#1575]
linux version: xubuntu 20.04
windows 10 pro

![image](https://user-images.githubusercontent.com/17058349/81385845-9d3d4d00-9146-11ea-972c-b8f2d236efdb.png)

When i click ok.
![image](https://user-images.githubusercontent.com/17058349/81385876-ae865980-9146-11ea-93e6-c75764e228b7.png)

The connection is automatically terminated.
![image](https://user-images.githubusercontent.com/17058349/81386105-0de46980-9147-11ea-839b-90ea86842489.png)

xrdp config
![image](https://user-images.githubusercontent.com/17058349/81386279-556af580-9147-11ea-9e09-7e03b6bbdca0.png)

**Comment by matt335672** [comment]
Hi @wajika 

Have you installed `xorgxrdp`?

Also, see the [wiki](..//wiki/Debian-dbus-user-session-package) regarding running on Ubuntu variants and using the console login with XRDP.

**Comment by wajika** [comment]
![image](https://user-images.githubusercontent.com/17058349/81516412-59c32880-936a-11ea-84df-86b2c85cec74.png)
![image](https://user-images.githubusercontent.com/17058349/81516417-5cbe1900-936a-11ea-95e0-58aab15abf18.png)

The problem is solved.
the same user can only be connected either locally or remotely

**Comment by matt335672** [comment]
Hi @wajika 

You should be able to connect both locally and remotely on xubuntu 20.04. If you need this, see the [wiki[(https://github.com/neutrinolabs/xrdp//wiki/Debian-dbus-user-session-package)
