### ISSUE TITLE
grey screen of xrdp in ubuntu 14.04

### ISSUE THREAD

**Issue by zhouxucs** [neutrinolabs/xrdp#158]
I have been used xrdp for 2 year. Recently, we moved to Ubuntu 14.04, and it seems xrdp does not work with Ubuntu 14.04. When I connect the server with an Windows client. Everything is OK except the screen is grey and nothing shows. 

I installed xrdp using "apt-get install xrdp".

I have also compile the version in github, and it seems to have the some problem. 

I noticed many other people have the some problem in Internet. For example,
http://askubuntu.com/questions/449785/ubuntu-14-04-xrdp-grey

Does it have fixes?

Thank you!

**Comment by metalefty** [comment]
Not an xrdp issue.
