### ISSUE TITLE
address=127.0.0.1 is not limiting listen only on localhost [Ubuntu 20.04]

### ISSUE THREAD

**Issue by UnreaI** [neutrinolabs/xrdp#1583]
I am trying to disable remote connection by adding `address=127.0.0.1` under the global section in xrdp.ini. After restart the service, somehow I am still able to connect the machine via ip address. This only happens on Ubuntu 20.04.
Version: xrdp 0.0.12

**Comment by metalefty** [comment]
I don't get you. xrdp has no control on SSH.

**Comment by UnreaI** [comment]
> 
> 
> I don't get you. xrdp has no control on SSH.

My bad, bad title. What I am trying to do is make XRDP listen to Port 3389 on the localhost only. However adding `address=127.0.0.1` doesn't seems to do anything on 20.04.

**Comment by metalefty** [comment]
Where did you add `address=127.0.0.1`?

**Comment by UnreaI** [comment]
> 
> 
> Where did you add `address=127.0.0.1`?

/etc/xrdp/xrdp.ini under [Global].

**Comment by metalefty** [comment]
Okay, let me some time to confirm.

**Comment by metalefty** [comment]
Actually, it is not distro-specific but a bug after #1441 .

You can also configure the listen-address limitation by `port`. You'll see examples in xrdp.ini. Can you try `port` instead?

**Comment by UnreaI** [comment]
That works! Thanks :)
