### ISSUE TITLE
I am not prompted for sudo actions in the GUI when connected via RdP

### ISSUE THREAD

**Issue by felipeleon73** [neutrinolabs/xrdp#1584]
In Manjaro 20.1 KDE  I am not prompted for sudo actions in the GUI when connected via RdP.

Everything else works perfectly, but I can't do any action that requires administrator privileges from the GUI.
sudo and kdesu from Konsole, on the other hand, work correctly.

**Comment by matt335672** [comment]
Hi @felipeleon73 

When you say you aren't prompted, do you mean that you don't get GUI prompts to enter a password when you are expecting one? Can you give an example of something that doesn't work so we can have a look at it?

Thanks,

**Comment by felipeleon73** [comment]
> Hi @felipeleon73
> 
> When you say you aren't prompted, do you mean that you don't get GUI prompts to enter a password when you are expecting one? Can you give an example of something that doesn't work so we can have a look at it?
> 
> Thanks,

e.g. Setting a theme in System Settings > Login Screen (Sddm).
If i try to change the theme from remote, when i press apply the theme reset to previous. Changing from local, btw, pressing apply i get the GUI for enter the password.

**Comment by matt335672** [comment]
Thanks.
I'm not familiar with Manjaro, so I'll have to install it, which might take me a while to get to. If I was to take a wild guess however, I'd say this looks like a policykit problem.

Policykit is used by a lot of desktop environments, and is responsible for allowing GUIs to perform privileged actions.

What does the following command give you as output?

```
pkaction --version
```

**Comment by felipeleon73** [comment]
Also in my opinion it can be a polkit problem ... I tried to play with allow_inactive, but without success.
However the output of the `pkaction --version` command is:
`pkaction version 0.116`

**Comment by matt335672** [comment]
It's almost certainly a polkit issue then, and you're on the right lines I think.

The version of polkit you have is quite modern, and some of the advice on the internet will relate to earlier versions with PKLA - IIRC 0.105 is the latest version to support PKLA files but I could be wrong on that.

Can you have a poke around in log files and see if you can find any errors related to polkit? This would verify that polkit is at the root of the problem, and let us start working on a rules file.

**Comment by felipeleon73** [comment]
Really great answer! Thank you very much!
