### ISSUE TITLE
RDP error in kali  (WSL)

### ISSUE THREAD

**Issue by Lucifer-00007** [neutrinolabs/xrdp#1586]
`hey!` I started kali linux on AWS later on CMD i tried to connect to rdp for kali and I am getting this error !!
I have done these:-` ```
root@kali:/home/ec2-user# apt install xrdp`,
                                                ` apt-get install tightvncserve`r,
                                                  `apt-get update`
  apt-get install xrdp lxde-core lxde tigervnc-standalone-server -y
                                                         nano /etc/X11/Xwrapper.config

                                     (  allowed_users=ec2-user  )

                                                    

```
root@kali:/home/ec2-user# systemctl start xrdp
Failed to start xrdp.service: Unit xrdp.service not found.
root@kali:/home/ec2-user#
```

**Comment by metalefty** [comment]
Where's your xrdp.service?

**Comment by Luci-f** [comment]
it ia present  remote desktop.

if  you  want  to know what  i  did see this:-{ https://www.youtube.com/watch?v=GYtdVSSy-zg }
i followed   this tutorial   to start  the command line  interface in cmd of kali linux .

later  i found  that  i need   GUI  of  Kali Linux  so  i started to follow this:-{ https://www.youtube.com/watch?v=DO9O0FOQkU4&t=1s }

and  in  this  video  this part :-
 root@kali:/home/ec2-user# systemctl start xrdp
Failed to start xrdp.service: Unit xrdp.service not found.
root@kali:/home/ec2-user#

didnot  worked   for  me, now  what  should  i do??

**Comment by matt335672** [comment]
It looks like something's gone wrong with your xrdp installation.

What are the outputs of these commands?

```
dpkg -l "*xrdp*"
dpkg -L xrdp
```
```

**Comment by metalefty** [comment]
I meant usually `xrdp.service` is located in `/lib/systemd/system/xrdp.service` or somewhere like there. Can you confirm if `xrdp.service` really present?

**Comment by sbroers** [comment]
You must enable the service: 

sudo systemctl enable xrdp
sudo systemctl enable xrdp-sesman
sudo systemctl daemon-reload
sudo systemctl start xrdp

for more infos and scripts see:
https://github.com/sbroers/linux-on-hyper-v

**Comment by Luci-f** [comment]
> It looks like something's gone wrong with your xrdp installation.
> 
> What are the outputs of these commands?
> 
> ```
> dpkg -l "*xrdp*"
> dpkg -L xrdp
> ```



hey!!  this is:-

"ec2-user@kali:~$ sudo dpkg -l "*xrdp*"
dpkg-query: no packages found matching *xrdp*

ec2-user@kali:~$ sudo dpkg -L xrdp
dpkg-query: package 'xrdp' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents."



what  I got. Now what  should I do??

**Comment by Luci-f** [comment]
> sudo systemctl enable xrdp
> sudo systemctl enable xrdp-sesman
> sudo systemctl daemon-reload
> sudo systemctl start xrdp



👆👆didn't  work   for me...

**Comment by metalefty** [comment]
It is natural it didn't work because xrdp is not installed.

**Comment by metalefty** [comment]
The commandlet that @sbroers has shown is misleading for your case. Just forget about it.
It is effective if everything going fine but yours is not going fine and we're try to find out what is going wrong.

**Comment by matt335672** [comment]
The very first command you mentioned in the first post seems to have failed.

What do these commands give you (notice the asterisks in the second one):-

```
sudo apt install -y xrdp
sudo dpkg -l "*xrdp*"

**Comment by Luci-f** [comment]
> The very first command you mentioned in the first post seems to have failed.
> 
> What do these commands give you (notice the asterisks in the second one):-
> 
> ```
> sudo apt install -y xrdp
> sudo dpkg -l "*xrdp*"
> ```





\ec2-user@kali:~$ sudo apt install -y xrdp

Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 python3-dev : Depends: python3 (= 3.8.2-3) but 3.7.5-3 is to be installed
               Depends: libpython3-dev (= 3.8.2-3) but 3.7.5-3 is to be installed
               Depends: python3.8-dev (>= 3.8.2-1~) but it is not going to be installed
 python3-ldb : Depends: python3 (>= 3.8~) but 3.7.5-3 is to be installed
               Depends: libpython3.8 (>= 3.8.2) but it is not going to be installed
 python3-pandas : Depends: python3 (>= 3.8~) but 3.7.5-3 is to be installed
                  Depends: python3-pandas-lib (>= 0.25.3+dfsg2-2) but 0.25.3+dfsg-4+b1 is to be installed
 python3-samba : Depends: samba-libs (= 2:4.11.5+dfsg-1+b1) but 2:4.11.3+dfsg-1 is to be installed
                 Depends: python3 (>= 3.8~) but 3.7.5-3 is to be installed
                 Depends: libpython3.8 (>= 3.8.2) but it is not going to be installed
                 Depends: libwbclient0 (= 2:4.11.5+dfsg-1+b1) but 2:4.11.3+dfsg-1 is to be installed
 python3-talloc : Depends: python3 (>= 3.8~) but 3.7.5-3 is to be installed
                  Depends: libpython3.8 (>= 3.8.2) but it is not going to be installed
 python3-tdb : Depends: libtdb1 (= 1.4.2-3+b1) but 1.4.2-3 is to be installed
               Depends: python3 (>= 3.8~) but 3.7.5-3 is to be installed
 python3-twisted-bin : Depends: python3 (>= 3.8~) but 3.7.5-3 is to be installed
 samba : Depends: samba-common (= 2:4.11.5+dfsg-1) but 2:4.11.3+dfsg-1 is to be installed
         Depends: samba-common-bin (= 2:4.11.5+dfsg-1+b1) but 2:4.11.3+dfsg-1 is to be installed
         Depends: python3 (>= 3.8~) but 3.7.5-3 is to be installed
         Depends: libgnutls30 (>= 3.6.12) but 3.6.11.1-2 is to be installed
         Depends: libpython3.8 (>= 3.8.2) but it is not going to be installed
         Depends: libwbclient0 (= 2:4.11.5+dfsg-1+b1) but 2:4.11.3+dfsg-1 is to be installed
         Depends: samba-libs (= 2:4.11.5+dfsg-1+b1) but 2:4.11.3+dfsg-1 is to be installed
 samba-dsdb-modules : Depends: samba-libs (= 2:4.11.5+dfsg-1+b1) but 2:4.11.3+dfsg-1 is to be installed
                      Depends: libgnutls30 (>= 3.6.12) but 3.6.11.1-2 is to be installed
                      Depends: libwbclient0 (= 2:4.11.5+dfsg-1+b1) but 2:4.11.3+dfsg-1 is to be installed
 samba-vfs-modules : Depends: samba-libs (= 2:4.11.5+dfsg-1+b1) but 2:4.11.3+dfsg-1 is to be installed
                     Depends: libwbclient0 (= 2:4.11.5+dfsg-1+b1) but 2:4.11.3+dfsg-1 is to be installed
                     Recommends: libgfapi0 (>= 7.3) but 7.1-1 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).



ec2-user@kali:~$ sudo dpkg -l "*xrdp*"

dpkg-query: no packages found matching *xrdp*

ec2-user@kali:~$ 
\

👆👆This  is  my  output brother. Now how should  i proceed?

thanks  to  all  of  you  for  your help!! I  am new to this coding field and till now i have  learned a lot of things from you all.😊😊

**Comment by matt335672** [comment]
Your package database is in a mess. As a result, you are not able to install xrdp at all, much less run it. The `apt` command simply won't work in this situation.

You'll need to fix the errors above before you can continue.

I suggest you remove any PPAs you've installed as a starter. See [here](https://askubuntu.com/questions/307/how-can-ppas-be-removed) [askubuntu.com] bearing in mind you won't be able to install the `ppa-purge` utility if it isn't already installed.

**Comment by metalefty** [comment]
Reporter’s local issue. No update from the reporter, closing.
