### ISSUE TITLE
xrdp port error

### ISSUE THREAD

**Issue by kei97103** [neutrinolabs/xrdp#1587]
I have problem with setting xrdp in my ubuntu server.

My systemd log shows that the port which I want to use for xrdp is already in use.
Below is my syslog

> May 18 15:54:55 d8-System-Product-Name systemd[1]: Started xrdp session manager.
> May 18 15:54:55 d8-System-Product-Name systemd[1]: Starting xrdp daemon...
> May 18 15:54:55 d8-System-Product-Name xrdp[5358]: (5358)(140313490638656)[DEBUG] Testing if xrdp can listen on 0.0.0.0 port 12346.
> May 18 15:54:55 d8-System-Product-Name xrdp[5358]: (5358)(140313490638656)[DEBUG] Closed socket 7 (AF_INET6 :: port 12346)
> May 18 15:54:55 d8-System-Product-Name systemd[1]: xrdp.service: Can't open PID file /var/run/xrdp/xrdp.pid (yet?) after start: No such file or directory
> May 18 15:54:56 d8-System-Product-Name systemd[1]: Started xrdp daemon.
> May 18 15:54:57 d8-System-Product-Name xrdp[5359]: (5359)(140313490638656)[INFO ] starting xrdp with pid 5359
> May 18 15:54:57 d8-System-Product-Name xrdp[5359]: (5359)(140313490638656)[ERROR] xrdp_listen_main_loop: listen error, possible port already in use
> May 18 15:54:57 d8-System-Product-Name systemd[1]: xrdp.service: Main process exited, code=exited, status=1/FAILURE
> May 18 15:54:57 d8-System-Product-Name systemd[1]: xrdp.service: Failed with result 'exit-code'.
> 

#880 said that it's user's local issue, but actually I don't know what to do...

I tested various port but it doesn't work. (3389, 12346, 58585 and etc)
![xrdp 에러코드](https://user-images.githubusercontent.com/22884167/82191750-f6b73000-992d-11ea-9c69-06764d9267c3.PNG)

I checked if there is any process using that port.
Below is `netstat -nap | grep LISTEN` result
**note** : port 12345 is which I set for ssh. not 12346
![xrdp 에러 2](https://user-images.githubusercontent.com/22884167/82191748-f61e9980-992d-11ea-95a2-777291d8b4f1.PNG)

I also make `iptables` allow tcp at port 12346, but it also doesn't work.
![iptables](https://user-images.githubusercontent.com/22884167/82191743-f4ed6c80-992d-11ea-8abd-d05267354c58.PNG)

Anyone can help me?

**Comment by metalefty** [comment]
You should look at this:
> May 18 15:54:55 d8-System-Product-Name systemd[1]: xrdp.service: Can't open PID file /var/run/xrdp/xrdp.pid (yet?) after start: No such file or directory

**Comment by metalefty** [comment]
No futther input, closing.
