### ISSUE TITLE
Enabling clean, secure sessions from Windows clients

### ISSUE THREAD

**Issue by iskunk** [neutrinolabs/xrdp#1589]
Hello, I am using xrdp 0.9.12 as shipped in Ubuntu focal. I am aiming to set up a server in a corporate environment to allow mostly Windows-based users to log in to a graphical Linux environment. My main goals are (1) high security (I am using `security_layer=tls` and `ssl_protocols=TLSv1.3`), and (2) as little awkwardness as possible compared to regular Windows RDP servers (no scary warnings, no config-tweaking, etc.).

I am having difficulty making this work, and there does not appear to be much in the way of documentation addressing this subject. I would like to ask if what I'm after is possible, if I'm doing something wrong, what I should be doing, and so on.

For xrdp, I have obtained a signed certificate from my org's internal CA, produced using their template for internal Web servers. I received a regular certificate file, as well as a certificate-chain file, both Base64-encoded.

The client is the native one on an up-to-date Windows 10 system:

![ms-rdp-about](https://user-images.githubusercontent.com/523357/82619476-1061ad00-9ba4-11ea-83b8-645976c5a8d3.png)

The Windows system belongs to the org, and has the internal CA cert pre-installed.

I attempted two different modes of making the connection:
1. Bring up the RDP client from the Start Menu normally, type in the hostname, and hit "Connect."
2. Save the RDP session to an `.rdp` file, then edit the file in a text editor, adding the line `enablecredsspsupport:i:0` (a trick learned from [this page](https://www.niallbrady.com/2017/08/23/how-can-i-rdp-to-an-azure-ad-joined-windows-10-device/)). Connect by opening this file.

I could not find any information on whether the file specified in `certificate=` should be a regular certificate or a certificate chain, so I tried both.

Here is the resulting 2x2 matrix of my results:

Mode of connecting | Certificate (solo) | Certificate chain
------------|------------|-----------
Connect from initial **mstsc** dialog | Error 0x80004005 | "Connecting to:" dialog pops up for a fraction of a second, and then disappears
Connect using modified `.rdp` file | Yellow warning, then error 0x80004005 | Yellow warning, then error 0x80004005

The 0x80004005 error dialog looks like this:

!["An authentication error has occurred (Code: 0x80004005)."](https://user-images.githubusercontent.com/523357/82619535-30916c00-9ba4-11ea-8b96-be6b8a8bcbcf.png)

The yellow warning dialog looks like this:

!["The publisher of this remote connection can't be identified. Do you want to connect anyway?"](https://user-images.githubusercontent.com/523357/82619541-36874d00-9ba4-11ea-800e-3670563042e3.png)

Unfortunately, no combination that I've tried so far has given me a remote window, let alone one without warning/error messages. (I am able to connect and authenticate to xrdp from a Linux RDP client without any issues, of course.) What does it take to make xrdp "just work" from Windows?

**Comment by metalefty** [comment]
Can you share us TLS related logs in xrdp.log?

**Comment by metalefty** [comment]
@iskunk  I guess `ssl_protocols=TLSv1.3` is too strict with Windows right now.

`Error 0x80004005` indicates the failure of TLS negotiation not only NLA error.  Windows' RDP client doesn't support TLSv1.3 yet but you restrict xrdp server to TLSv1.3. As a result, TLS negotiation fails and you cannot connect with `Error 0x80004005`. 

Can you also try to loosen SSL protocols with `ssl_protocol=TLSv1.2, TLSv1.3`?

Regarding certificate, `cerfiticate=` can be a chained cert if your certificate requires intermediate certificate.

**Comment by metalefty** [comment]
The version of my **mstsc** seems the same as yours. It doesn't support TLSv1.3 yet.

![スクリーンショット 2020-05-22 16 34 03](https://user-images.githubusercontent.com/941609/82643209-17db9180-9c4a-11ea-8ef6-0242f3ae786f.png)

**Comment by iskunk** [comment]
That did the trick :-)

Specifically, setting `ssl_protocols=TLSv1.2, TLSv1.3`. (This is strange; I didn't think TLSv1.3 would have been an option if the Windows client didn't support it.)

With that change, I can now log in to xrdp from the initial **mstsc** dialog, with no warnings nor errors, just like a regular MS RDP server. This is exactly what I wanted, and I thank you for your help!

Before I close this issue, I have just a few follow-up questions:

1. Does the order of items in `ssl_protocols` make a difference? E.g. if a client supports both versions, but TLSv1.2 is specified first, will that result in the client using v1.2?

2. Are you sure that a certificate chain is supposed to work? Using xfreerdp, I was able to log in from a Linux system, but that was when xrdp was using the regular certificate. After I posted the report, I tried logging in again when the certificate-chain was in place, and xfreerdp gave me the following error:
   ```
   [16:08:38:123] [18445:18446] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_TLS_CONNECT_FAILED [0x00020008]
   [16:08:38:123] [18445:18446] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
   [16:08:38:123] [18445:18446] [ERROR][com.freerdp.client.x11] - Freerdp connect error exit status 1
   ```
   When I tried it from Windows, I don't get an error---just a very brief "Connecting to:" dialog that disappears after a fraction of a second, leaving me back at the initial **mstsc** dialog with no session started.

   Does the certificate chain have to be in a specific format that could be different from what I have? (This would be strange, because my org's CA interface appears to be the regular Microsoft one, as shown at the top of [this page](https://www.get-itsolutions.com/install-ssl-certificate-microsoft-iis/).)

3. Would it be okay if I (or you) updated [this page](https://github.com/neutrinolabs/xrdp/wiki/TLS-security-layer) with specific information on compatibility with Windows clients? For example, the bit about TLSv1.3 not being supported yet appears to be new information.

**Comment by metalefty** [comment]
1. No. The highest version both client and server support should be selected.

2. Yes it should work. I'm actually using a chained certificate. Put the certificate first, put the intermediate certificate next. Let's encrypt's `fullchain.pem` is actually works. 

3. Yes. Feel free to do that.

**Comment by iskunk** [comment]
1. Okay, so this is not something I need to worry about :-)

2. The certificate-chain file that I have contains a single `BEGIN`/`END` block. Are you talking about a file that has two or more such blocks, concatenated together?

3. I'll prepare my edits!

One more question, on a tangent: I've noticed that if I do `/etc/init.d/xrdp restart`, existing sessions are terminated (not just disconnected). This is different from what happens when you do e.g. `/etc/init.d/ssh restart`, which does not end existing SSH sessions.

Is this known/expected/correct behavior, or should it be considered a bug in how Ubuntu packages xrdp?

**Comment by metalefty** [comment]
I'm not sure if the order of certificate matters but this config is working for me.

`certificate=/path/to/fullchain.pem`

`fullchain.pem` as follows:
```
-----BEGIN CERTIFICATE-----
SERVER CERTIFICATE
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
INTERMEDIATE CERTIFICATE
-----END CERTIFICATE-----
```

Regarding restart behaviour, it is expected. I know some people don't like such behaviour but  it is expected so far.

However, you don't need to restart xrdp on certificate change. The certificate and key will be reloaded automatically.

**Comment by iskunk** [comment]
Thank you for clarifying all these details; it is greatly appreciated. That certificate-chain format appears to be the same `.ca-bundle` format used by Apache.

I have revised the [TLS-security-layer](https://github.com/neutrinolabs/xrdp/wiki/TLS-security-layer) page. Please have a look at it, and make any corrections that you see necessary. (I had no idea what the bit about "TLS direct connections" is about, or if it still applies to the current version of xrdp, so I left that as a TODO at the bottom of the page.)

Closing this issue, as it has been very nicely resolved :-)

**Comment by iskunk** [comment]
One small addendum: I _just_ noticed that the previous revisions of the wiki page seem to have disappeared. I'm not sure why this occurred, but it may have to do with the fact that I changed the page format from Mediawiki to Markdown (since the other wiki pages appear to be in Markdown format).

For what it's worth, the old text can be viewed [here](https://web.archive.org/web/20190621084529/https://github.com/neutrinolabs/xrdp/wiki/TLS-security-layer).
