### ISSUE TITLE
XRDP service report error? 

### ISSUE THREAD

**Issue by Garfield2013** [neutrinolabs/xrdp#1592]
xrdp.service: Can't open PID file /run/xrdp/xrdp.pid (yet?) after start: Operation not permitted

I can login at my AWS EC2 m5d.large/m5d.xlarge instance (2/4 VCPU + 8/16GB memory + SSD) - But the response time is like 30s-60s for every click (My internet connection is 530M/bit - ooh yes! So I guess that part is okay ;))
What is the reason for the super slow response time? Has it something to do - with the service error?

Fresh image / instance --> Ubuntu: 20.04 @ AWS:

sudo apt-get update -y
sudo apt-get upgrade -y
reboot
sudo apt install xrdp -y
sudo systemctl enable --now xrdp
sudo systemctl status xrdp
sudo apt install tasksel -y
sudo apt install xubuntu-desktop -y
reboot
sudo adduser xrdp ssl-cert 
sudo systemctl restart xrdp
sudo systemctl set-default graphical.target

**Comment by Garfield2013** [comment]
FYI: I just tried to install AnyDesk and TeamViewer in the Ubuntu server and connection to it from my Windows 10 laptop - it running SUPER SMOOTH! :-)

**Comment by matt335672** [comment]
Closing this - no-one's looked at it in 4 years, and things have moved on a bit since then.
