### ISSUE TITLE
Cannot connect from Remmina when colour depth set to "RemoteFX (32bpp)"

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#1597]
As @ikunya mentioned in [Ubuntu Weekly Recipe Vol.621](https://gihyo.jp/admin/serial/01/ubuntu-recipe/0621?page=2), Remmina cannot connect to xrdp when colour depth set to RFX.

> 「色数」と「共有フォルダー」は注意が必要です。「⁠色数」は「True color (24bpp)」くらいにしておくのが妥当と思われます。「⁠GFX」や「RemoteFX」が付いているものにすると接続できませんでした。

As is known,  Remmina is a front-end wrapper of FreeRDP.

![スクリーンショット_2020-06-03_14-20-52](https://user-images.githubusercontent.com/941609/83599276-b4852400-a5a6-11ea-9d0a-f859b92c1dba.png)

I reproduced the issue with the following environment.

OS: FreeBSD 12-STABLE
Remmina 1.3.9 + FreeRDP 2.0.0-rc4
xrdp v0.9.13 + xorgxrdp v0.2.13

Video of reproduction: https://youtu.be/vjwJ24YhRnY

**Comment by metalefty** [comment]
I thought I reproduced the issue but it might not be identical to his issue.

I managed to connect from Remmina with RFX enabled. My issue is identical to #1266. 

This worked for me but it is not limited to RFX.
☑ Glyph cache
☑ Relax order checks 

![スクリーンショット_2020-06-03_14-44-36](https://user-images.githubusercontent.com/941609/83600145-e6978580-a5a8-11ea-912b-9a63e9e02f06.png)

**Comment by matt335672** [comment]
@metalefty - can we close this one now?

**Comment by metalefty** [comment]
I think so but let me confirm with v0.10.

**Comment by metalefty** [comment]
This is no longer an issue with v0.10.1, closing.
