### ISSUE TITLE
Password Leakage

### ISSUE THREAD

**Issue by sleicasper** [neutrinolabs/xrdp#1599]
reproduce step:
1. using rdp client connect xrdp server, login
2. using `gdb` attach xrdp-sesman process
3. using `find` command to search your password if you installed `peda` plugin for gdb. You will find your password in plaintext on heap.

fix:
after authentication, xrdp-sesman should wipe out saved password on heap.

**Comment by J-W-C** [comment]
First, I agree with the idea that sensitive information should be zeroed out when it's no longer needed.  The issue title seem a bit provocative though, as anyone who can debug the sesman process can also just read passwords off the wire.

Note to whoever might implement the fix:  be aware of the possibility of a smart compiler optimizing away your out-zeoroing.
