### ISSUE TITLE
No suspend after login to Ubuntu 18.04 via xrdp with xorg

### ISSUE THREAD

**Issue by Saberfox** [neutrinolabs/xrdp#1601]
Hello everyone,

unfortunatly i have a problem, which i dont know how to start to debug and i also tried one thing or another without any success.

First of all, i use an Intel NUC8i5BEH2 as the hardware and Ubuntu18.04 is the OS.

I installed xrdp manually like the following:

aptitude install xrdp xorgxrdp xserver-xorg-core xserver-xorg-input-all

Afterwards i edited a file for the polkit:

vi /etc/polkit-1/localauthority.conf.d/01-allow-colrd.conf

polkit.addRule(function(action, subject) {
if ((action.id == “org.freedesktop.color-manager.create-device” || action.id == “org.freedesktop.color-manager.create-profile” || action.id == “org.freedesktop.color-manager.delete-device” || action.id == “org.freedesktop.color-manager.delete-profile” || action.id == “org.freedesktop.color-manager.modify-device” || action.id == “org.freedesktop.color-manager.modify-profile”) && subject.isInGroup(“{group}”))
{
return polkit.Result.YES;
}
});

The Problem now is, after i log in to my ubuntu workstation, it won't suspend after a certain time anymore. Even after loggin out.
Whenever i login localy, the setting are back and it will go into suspend after e.g. 30 minutes being idle. 
If i logout after loggin in localy, it wont go into suspend as well.

I also tried editing the file in /etc/X11/xrdp/xorg.conf with the following:
Adding: Option "StandbyTime" "3"
             Option "SuspendTime" "5"
under "Serverlayout"

and also adding "true"  to: "DPMS" under the "Monitor"-Section.
Unfortunatly it didn't help as well.

I also tried to find out, what stand in the way of my workstation to go into suspend, so i used:
echo 1 > /sys/power/pm_trace, but it won#t really give me any output, as to why it fails to go into suspend.

I don#t know, what i need to provide for anyone, to locate the error in this, so pls just tell me, what you need and i will provide it as soon, as possible! 

I hope it is possible to find a solution to this problem, as i have no clue how to begin debugging this on my own or if there is even a solution at all. :(

Please help, thank you!

**Comment by matt335672** [comment]
@saberfox - it's not clear to me what you mean by 'suspend' above. Do you mean just the monitor going to sleep (i.e. DPMS), or do you mean the computer is entering an [ACPI sleep state](https://en.wikipedia.org/wiki/Advanced_Configuration_and_Power_Interface#Power_states)? 

If it's the latter, bear in mind that you'll have no network when the machine suspends. That means:-
- if you're logged in remotely at the time won't be able to reconnect.
- If you're not logged in at the time, you won't be able to reconnect remotely.

Are you sure this is the behaviour you want?

**Comment by Saberfox** [comment]
First, thank you very much for your fast reply. It already giving me hope.

And i see, i do not only mean the monitor going to sleep. I want the computer to enter an ACPI sleep state (S3 - Suspend to RAM).

Also yes, this is the behavior i want, i have another remote tool, to wake up my computer via wake on lan, so i dont have to worry, not being able to connect, after the computer enters the ACPI sleep state.

So if it is possible to achieve this bevaviour, i would love to be able to get it. :)
Thank you already for your help.

**Comment by matt335672** [comment]
Just noticed your file `/etc/polkit-1/localauthority.conf.d/01-allow-colrd.conf`.

**This won't work in Ubuntu 18.04.** The polkit daemon for this operating system does not understand these files. I suggest you remove it, or you'll have a broken polkit daemon.

I think you're not getting suspend when no-one is logged in because the `gdm` user does not support it. You can read more about that [here](https://askubuntu.com/questions/1101043/prevent-sleep-suspend-when-not-logged-in-to-a-specific-account). The first answer suggests a way to get this working.

When you're logged in over XRDP, polkit will stop your remote session from suspending the computer. You can see this difference between local and XRDP sessions by typing the command `systemctl suspend` in on both sessions. On the console it will suspend the machine immediately, and on an XRDP session it won't without additional authorization.

I don't know what will happen if you allow both `gdm` and `xrdp` sessions to suspend the machine. It may not work as well as you would like. You'll have to try it to find out.

To allow XRDP to suspend the machine, add this file `/etc/polkit-1/localauthority/50-local.d/allow-suspend.pkla`. On Ubuntu 18.04 PKLA files have to be used to modify the behaviour of polkit.

```
[Allow Wall message]
Identity=unix-user:*
Action=org.freedesktop.login1.set-wall-message
ResultAny=yes

[Allow suspend]
Identity=unix-user:*
Action=org.freedesktop.login1.suspend
ResultAny=yes
```

You will now find that `systemctl suspend` works from an XRDP session, and so I suspect the session suspend will as well.

Be aware this lowers the security of your system. Any user logged on over ssh can now suspend your system. You can work around this by using group memberships but this is more complicated.

**Comment by Saberfox** [comment]
Thank you so much for you answer! 

It helped me a lot in understanding, why it wouldn't work and how to fix it with certain policies.
And just like you said, with this pkla-file i now can suspend manually, even over a remote connection.

So this Error is fixed with this.

Now only how to change the automatic suspend, when no one is logged in (local or remote), since unfortunatly i only get Errors "Failed to open file “/root/.config/dconf/user”: Permission denied" when i try:
IFS=$'\n'; for x in $(sudo -u username gsettings list-recursively org.gnome.settings-daemon.plugins.power); do eval "sudo -u gdm dbus-launch gsettings set $x"; done; unset IFS

with the way described in the link you gave me, about gdm. :(

I tried the following to set gdm to go into suspend, afetr a certain time:
 su - gdm -s /bin/bash
GSETTINGS_BACKEND=dconf gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type suspend
GSETTINGS_BACKEND=dconf gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 300

And it also works, unfortunatly, since gdm is ALWAYS idle, after rebooting and after logging in via xrdp (since it is a different login-screen and not the usual gdm), it will always go into suspend after 5 Minutes, even while working. Ofc only when i am logged in remotly or via ssh and not localy, but right now only remote matters. :(

I dont know if you or anyone else may have a solution to this kinda Problem.

**Comment by matt335672** [comment]
Hi @Saberfox 

What you are seeing is what I suspected might happen if you enabled suspend for the `gdm` user. The desktops are unaware of each other, and so the suspend is happening regardless.

You can solve this a different way I think. I'll sketch something out as an idea, and leave you to fill in the pieces.

The command `loginctl list-sessions` can be used to list the active sessions. You can put this in a script run as root, and use it to suspend the machine when there are no session active apart from `gdm` sessions. Here's a basic bash script, which I can't claim to have tested much:-

```
#!/bin/bash

declare -ir SUSPEND_TIMEOUT=15

session_count()
{
    set -- $(loginctl list-sessions --no-legend | awk '{print $3}')
    local -i count=0
    local user
    for user in "$@"; do
        case "$user" in
            gdm) ;;
            *)   ((++count))
        esac
    done

    echo $count
}

# -----------------------------------
declare -i mins=0
while true; do
    sleep 60
    if [[ $(session_count) -gt 0 ]]; then
        mins=0
    else
        ((++mins))
        if [[ mins -ge $SUSPEND_TIMEOUT ]]; then
            systemctl suspend
            mins=0
        fi
    fi
done
```

That will need to be running as root all the time.

Does that help?

**Comment by Saberfox** [comment]
Hi @matt335672 ,

thank you very much for all your help.

And yes, the sketch for your script, just like everything else you helped me with, helped a ton.
I was really hoping not having to write a script for that, but i guess, there was no other choice.

And the sketch for the script also worked just fine so far, so again, thank you very much.
I wrote another skript, checking for the process, which i implemented as a cronjob, so it will always run.

With this, i will close this thread and mark it as done.

Thank you very much anf for everything, i have learned.
