### ISSUE TITLE
Red Hat 8 in Active Directory login failed for dispaly 0 if I try to login with AD user

### ISSUE THREAD

**Issue by Niubbo75** [neutrinolabs/xrdp#1605]
Hello, I've a rhel8 joined to a Windows 2016 AD. If I login directly into rhel using Windows AD users, I've got no issue, if I try to login remotely via SSH, again, no issue but if I try to login via xRDP using both Windows RDP client or Guacamole, I got "login failed for dispaly 0". If I try to login using both Windos RDP client or Guacamole and a LOCAL (I means a non-ad user) user, I can login with no issue.
Where I could start to investigate to solve the problem or does anyone have had similar issue and had solved?

**Comment by metalefty** [comment]
Probably you need to configure pam file of xrdp-sesman. Also you shuold see xrdp-sesman.log.

**Comment by Niubbo75** [comment]
The issue was in sssd.conf
I had to add in /etc/sssd/sssd.conf
`[sssd]
domains = domain.local
config_file_version = 2
services = nss, pam

[domain/domain.local]
ad_domain = domain.local
....................................................................
access_provider = ad
ad_gpo_access_control = enforcing
ad_gpo_map_remote_interactive = +xrdp-sesman`

the last 2 strings

`ad_gpo_access_control = enforcing
ad_gpo_map_remote_interactive = +xrdp-sesman`

and they did the trick!

Thanks for your hint!
Regards,
Alessandro

**Comment by metalefty** [comment]
That's good to hear.
