### ISSUE TITLE
documentation for sesman.ini KillDisconnected/DisconnectedTimeLimit

### ISSUE THREAD

**Issue by drw25** [neutrinolabs/xrdp#1607]
Hi,

It's not clear from the sesman.ini manpage exactly how the parameters KillDisconnected and DisconnectedTimeLimit affect session disconnection behaviour.

For KillDisconnected it says "every session will be killed within 60 seconds after the user disconnects" if set true.

Suppose I set DisconnectedTimeLimit=300. If I also set KillDisconnected=true are disconnected sessions still killed within 60 seconds, or will it use my new 5 minute limit? Or do I need to set KillDisconnected=false otherwise my 5 minutes will be overridden by a hardcoded limit of 60s?

The above applies equally to the comments in the default sesman.ini.

Relevant files:
[https://github.com/neutrinolabs/xrdp/blob/devel/docs/man/sesman.ini.5.in](url)
[https://github.com/neutrinolabs/xrdp/blob/devel/sesman/sesman.ini.in](url)

Thanks

**Comment by matt335672** [comment]
Hi @drw25 

From my persusal of the code, I can't see any evidence that these variables are connected to anything yet.

They seem to have been added by [this commit](../commit/153b59ad8447d47d4a241e0f63307b096585172b) dated January 2006.  This would have been when xrdp was hosted on sourceforge. I can't find the developer who made the commit on github, although others may know different.

At present, sesman does not know when a session disconnects, which makes these variables rather useless anyway. There have been recent discussions regarding this - see #1598.

I'm going to reference this issue in #1598 so that when disconnections get addressed we can get these variables connected to something.

Sorry not to be more constructive, but I hope that's at least informative.

**Comment by drw25** [comment]
Thanks @matt335672.

I was thrown by #1042 and #1205 where there were suggestions that these parameters maybe work for xorgxrdp backend. 

#1415 suggests the MaxDisconnectionTime might be used by a downstream SUSE package with VNC backend.

I'll wait for disconnect-awareness to be implemented in sesman.

**Comment by drw25** [comment]
Seems like it might communicate with xorgxrdp via the XRDP_SESMAN_KILL_DISCONNECTED and XRDP_SESMAN_MAX_DISC_TIME environment variables? 

set here
https://github.com/neutrinolabs/xrdp/blob/f37d1ba46e9a6faab112c69bf0a0553e0056cd8c/sesman/session.c#L642

read here
https://github.com/neutrinolabs/xorgxrdp/blob/a144f8b4e3a6ede4bfd2acf07218152246e24d20/module/rdpClientCon.c#L1384

**Comment by matt335672** [comment]
Good catch - I'd missed that.

Yes, perusing your links it looks like these parameters have an effect for xorgxrdp backends only unless a patch is used. I'll have a dig around tomorrow and try to work out the behaviour. We can then get the documentation clarified a bit.

**Comment by metalefty** [comment]
> At present, sesman does not know when a session disconnects, which makes these variables rather useless anyway. 

sesman doesn't know session disconnection but X servers such as VNC or xorgxrdp aware of disconnection.

**Comment by matt335672** [comment]
I've had a look at the code, and I believe the following change to the `sesman.ini` manpage would explain the behaviour better.

```
       KillDisconnected=[true|false]
              If set to 1, true or yes, every session will be killed within 60
              seconds after the user disconnects.  This setting currently only
              works with xorgxrdp sessions.

       DisconnectedTimeLimit=number
              Sets the time limit for KillDisconnected to a value greater than
              60.  Values less than 60 cannot be set. You do not actually have
              to specify KillDisconnected if you set this value.  This setting
              currently only works with xorgxrdp sessions.
```

@drw25 - is that clearer?

**Comment by drw25** [comment]
Hi @matt335672. Yes - that's definitely clearer. Thanks for pursuing this!
