### ISSUE TITLE
xrdp memory growth is particularly fast when using VPN proxies

### ISSUE THREAD

**Issue by limenghui614** [neutrinolabs/xrdp#1608]
Hi,
Memory has been growing rapidly with VPNS, especially for batch operations or video playback.

**Comment by metalefty** [comment]
I don't think VPNs matter but can you confirm it reproduces also without VPN?

**Comment by limenghui614** [comment]
I can confirm that the memory is stable without VPN

**Comment by matt335672** [comment]
Possibly a duplicate of #1634
