### ISSUE TITLE
Can't connect to xrdp on Ubuntu 20.04 from Windows 10

### ISSUE THREAD

**Issue by paulr24** [neutrinolabs/xrdp#1609]
When I try to connect via RDP I briefly get a black screen and then the window closes. I ran "sudo systemctl status xrdp" and the result is below. Any ideas how to fix this? Thanks!

● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2020-06-17 03:27:25 UTC; 36min ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
   Main PID: 1361 (xrdp)
      Tasks: 1 (limit: 9255)
     CGroup: /system.slice/xrdp.service
             └─1361 /usr/sbin/xrdp

Jun 17 04:03:15 ubuntu xrdp[4953]: (4953)(281473823191056)[INFO ] xrdp_wm_log_msg: login successful for display 10
Jun 17 04:03:15 ubuntu xrdp[4953]: (4953)(281473823191056)[DEBUG] xrdp_wm_log_msg: started connecting
Jun 17 04:03:15 ubuntu xrdp[4953]: (4953)(281473823191056)[INFO ] lib_mod_log_peer: xrdp_pid=4953 connected to X11rd>
Jun 17 04:03:15 ubuntu xrdp[4953]: (4953)(281473823191056)[DEBUG] xrdp_wm_log_msg: connected ok
Jun 17 04:03:16 ubuntu xrdp[4953]: (4953)(281473823191056)[DEBUG] xrdp_mm_connect_chansrv: chansrv connect successful
Jun 17 04:03:16 ubuntu xrdp[4953]: (4953)(281473823191056)[DEBUG] Closed socket 16 (AF_INET6 ::1 port 60160)
Jun 17 04:03:17 ubuntu xrdp[4953]: (4953)(281473823191056)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.1.226 po>
Jun 17 04:03:17 ubuntu xrdp[4953]: (4953)(281473823191056)[DEBUG] xrdp_mm_module_cleanup
Jun 17 04:03:17 ubuntu xrdp[4953]: (4953)(281473823191056)[DEBUG] Closed socket 17 (AF_UNIX)
Jun 17 04:03:17 ubuntu xrdp[4953]: (4953)(281473823191056)[DEBUG] Closed socket 18 (AF_UNIX)

**Comment by matt335672** [comment]
Hi @paulr24 

Are you by any chance logged in at the console? If so, you might want to check out this [wiki entry](../wiki/Debian-dbus-user-session-package).

Failing that, do the following:-

- Log in over ssh.
- Make a note of the time (hh:mm:ss) by running the `date` command.
- Try to log in over RDP
- Post the output of the command `sudo journalctl -S hh:mm:ss` where hh:mm:ss is the time you noted earlier.

**Comment by paulr24** [comment]
Hi @matt335672, thanks for the reply. I did see some info regarding being logged in at the console. I tried logging out, and also following the wiki entry, but I'm still having the same issue. I then did what you asked, and here are the results:

date: Wed Jun 17 15:55:36 EDT 2020

Tried logging in over RDP, then here are the results of the command:

-- Logs begin at Wed 2020-04-01 13:23:43 EDT, end at Wed 2020-06-17 15:57:17 EDT. --
Jun 17 15:55:40 ubuntu dbus-daemon[17287]: [session uid=122 pid=17285] Activating service name='org.freedesktop.Noti>
Jun 17 15:55:40 ubuntu dbus-daemon[17287]: [session uid=122 pid=17285] Activating service name='org.xfce.Xfconf' req>
Jun 17 15:55:40 ubuntu dbus-daemon[17287]: [session uid=122 pid=17285] Successfully activated service 'org.xfce.Xfco>
Jun 17 15:55:40 ubuntu dbus-daemon[17287]: [session uid=122 pid=17285] Successfully activated service 'org.freedeskt>
Jun 17 15:55:41 ubuntu xrdp[1389]: (1389)(281473264242704)[INFO ] Socket 12: AF_INET6 connection received from ::fff>
Jun 17 15:55:41 ubuntu xrdp[1389]: (1389)(281473264242704)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.1.226 po>
Jun 17 15:55:41 ubuntu xrdp[18426]: (18426)(281473264242704)[DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
Jun 17 15:55:41 ubuntu xrdp[18426]: (18426)(281473264242704)[INFO ] Using default X.509 certificate: /etc/xrdp/cert.>
Jun 17 15:55:41 ubuntu xrdp[18426]: (18426)(281473264242704)[INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Jun 17 15:55:41 ubuntu xrdp[18426]: (18426)(281473264242704)[ERROR] Cannot read private key file /etc/xrdp/key.pem: >
Jun 17 15:55:41 ubuntu xrdp[18426]: (18426)(281473264242704)[DEBUG] TLSv1.3 enabled
Jun 17 15:55:41 ubuntu xrdp[18426]: (18426)(281473264242704)[DEBUG] TLSv1.2 enabled
Jun 17 15:55:41 ubuntu xrdp[18426]: (18426)(281473264242704)[DEBUG] Security layer: requested 11, selected 0
Jun 17 15:55:41 ubuntu xrdp[18426]: (18426)(281473264242704)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.1.226 >
Jun 17 15:55:42 ubuntu xrdp[1389]: (1389)(281473264242704)[INFO ] Socket 12: AF_INET6 connection received from ::fff>
Jun 17 15:55:42 ubuntu xrdp[1389]: (1389)(281473264242704)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.1.226 po>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] Using default X.509 certificate: /etc/xrdp/cert.>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[ERROR] Cannot read private key file /etc/xrdp/key.pem: >
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] TLSv1.3 enabled
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] TLSv1.2 enabled
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] Security layer: requested 0, selected 0
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] connected client computer name: PAULRYZEN
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] adding channel item name rdpdr chan_id 1004 flag>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] adding channel item name rdpsnd chan_id 1005 fla>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] adding channel item name cliprdr chan_id 1006 fl>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] adding channel item name drdynvc chan_id 1007 fl>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] Non-TLS connection established from ::ffff:192.1>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] xrdp_000047fb_wm_login_mode_event_00000001
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[WARN ] local keymap file for 0x00000409 found and doesn>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0>
Jun 17 15:55:42 ubuntu xrdp-sesman[1353]: (1353)(281473614072064)[INFO ] A connection received from ::1 port 37930
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] xrdp_wm_log_msg: sesman connect ok
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] xrdp_wm_log_msg: sending login info to session m>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] return value from xrdp_mm_connect 0
Jun 17 15:55:42 ubuntu xrdp-sesman[1353]: pam_unix(xrdp-sesman:auth): Couldn't open /etc/securetty: No such file or >
Jun 17 15:55:42 ubuntu xrdp-sesman[1353]: pam_unix(xrdp-sesman:auth): Couldn't open /etc/securetty: No such file or >
Jun 17 15:55:42 ubuntu xrdp-sesman[1353]: (1353)(281473614072064)[INFO ] ++ created session (access granted): userna>
Jun 17 15:55:42 ubuntu xrdp-sesman[1353]: (1353)(281473614072064)[INFO ] starting Xorg session...
Jun 17 15:55:42 ubuntu xrdp-sesman[1353]: (1353)(281473614072064)[DEBUG] Closed socket 9 (AF_INET6 :: port 5910)
Jun 17 15:55:42 ubuntu xrdp-sesman[1353]: (1353)(281473614072064)[DEBUG] Closed socket 9 (AF_INET6 :: port 6010)
Jun 17 15:55:42 ubuntu xrdp-sesman[1353]: (1353)(281473614072064)[DEBUG] Closed socket 9 (AF_INET6 :: port 6210)
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] xrdp_wm_log_msg: login successful for display 10
Jun 17 15:55:42 ubuntu xrdp-sesman[1353]: (1353)(281473614072064)[DEBUG] Closed socket 8 (AF_INET6 ::1 port 3350)
Jun 17 15:55:42 ubuntu xrdp-sesman[18428]: (18428)(281473614072064)[INFO ] calling auth_start_session from pid 18428
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] xrdp_wm_log_msg: started connecting
Jun 17 15:55:42 ubuntu xrdp-sesman[18428]: pam_unix(xrdp-sesman:session): session opened for user ubuntu by (uid=0)
Jun 17 15:55:42 ubuntu systemd-logind[1273]: New session c7 of user ubuntu.
Jun 17 15:55:42 ubuntu systemd[1]: Started Session c7 of user ubuntu.
Jun 17 15:55:42 ubuntu xrdp-sesman[18428]: (18428)(281473614072064)[DEBUG] Closed socket 7 (AF_INET6 ::1 port 3350)
Jun 17 15:55:42 ubuntu xrdp-sesman[18428]: (18428)(281473614072064)[DEBUG] Closed socket 8 (AF_INET6 ::1 port 3350)
Jun 17 15:55:42 ubuntu xrdp-sesman[18430]: (18430)(281473614072064)[INFO ] /usr/lib/xorg/Xorg :10 -auth .Xauthority >
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[INFO ] lib_mod_log_peer: xrdp_pid=18427 connected to X1>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] xrdp_wm_log_msg: connected ok
Jun 17 15:55:42 ubuntu xrdp-sesman[18428]: (18428)(281473614072064)[CORE ] waiting for window manager (pid 18429) to>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] xrdp_mm_connect_chansrv: chansrv connect success>
Jun 17 15:55:42 ubuntu xrdp[18427]: (18427)(281473264242704)[DEBUG] Closed socket 16 (AF_INET6 ::1 port 37930)
Jun 17 15:55:43 ubuntu dbus-daemon[18477]: [session uid=1000 pid=18475] AppArmor D-Bus mediation is enabled

**Comment by matt335672** [comment]
Well that all looks OK. I can't see the session closing at all.

I didn't ask you to wait until the RDP session had terminated before generating the log - sorry. Could you try again and wait until the session has close before generating the log?

**Comment by kbfifi** [comment]
Same problem here. black screen en mouse pointer is moveable. I noticed that while seeing the black screen and starting an application from the host desktop the application is shown in the remote rdp session! Only the application  is visible.

I followed the instructions on the wiki en eventually reboot the system. Now I can see a remote desktop, except that it is not the existing instance that was already running but a new one. How can this be fixed? Any suggestion is appreciated.

**Comment by matt335672** [comment]
Hi @kbfifi 

I don't understand your question. You've rebooted the system, and so there won't be any instances running. Can you please clarify what you mean by a new instance?

**Comment by kbfifi** [comment]
Hi matt335672,

Thanks for your response. By new instance I mean a new desktop session. to reproduce:
boot Ubuntu
login 
start some app x
start a RDP session to this machine
Now a new clean session is shown (new instance) not showing app x
Start a new app y in this new session => it is only shown in the new session not in the original host session

I'd like to have the same default behaviour as with Windows RDP sessions: take over an existing session

**Comment by matt335672** [comment]
OK - thanks - that's clear.

It's not quite the way it works though - the console session has its own (private) X server, and you can't take that over.

The closest you can come is to run a VNC server as part of your console session and connect to that VNC session. There are a lot of options here. Some desktops have a VNC server built in (i.e. GNOME Vino), or you can run x11vnc to provide a server onto an existing desktop. You can then use XRDP as a shim to connect to the console, or use a VNC client to connect direct from whatever platform you're coming from.

Does that make sense?

**Comment by kbfifi** [comment]
Ok thanks for the explanation! Maybe a bit off topic and more of a X-window question: Would it be possible to switch started apps between the 2 X-displays? So in my example make app x visible in the other session?

**Comment by matt335672** [comment]
If the app was on an X screen on the same server it would be possible. But it's not possible between two X servers. Each one holds quite a bit of state related to each app, and there's no mechanism to transfer apps between servers.

**Comment by Sebazzz** [comment]
The original issue reported by @paulr24 I had too when upgrading xrdp. To fix this, ensure your startwm.sh script is configured correctly. In my case, I boot to XCFE, so I needed to modify my script accordingly.

**Comment by TheLeank** [comment]
@Sebazzz just installed xrdp and I'm in a xfce wm, with the same error that we all have. What should I modify from the file? Thank you for your help.

**Comment by Sebazzz** [comment]
These are the contents of the file I have:

```sh
#!/bin/sh

export STARTUP=xfce4-session

#start the window manager
wm_start()
{
  if [ -r /etc/default/locale ]; then
    . /etc/default/locale
    export LANG LANGUAGE
  fi

  # debian
  if [ -r /etc/X11/Xsession ]; then
    . /etc/X11/Xsession
    exit 0
  fi

  # el
  if [ -r /etc/X11/xinit/Xsession ]; then
    . /etc/X11/xinit/Xsession
    exit 0
  fi

  # suse
  if [ -r /etc/X11/xdm/Xsession ]; then
    . /etc/X11/xdm/Xsession
    exit 0
  fi

  xterm
}

# Execution sequence for interactive login shell - pseudocode
#
# IF /etc/profile is readable THEN
#     execute ~/.bash_profile
# END IF
# IF ~/.bash_profile is readable THEN
#     execute ~/.bash_profile
# ELSE
#     IF ~/.bash_login is readable THEN
#         execute ~/.bash_login
#     ELSE
#         IF ~/.profile is readable THEN
#             execute ~/.profile
#         END IF
#     END IF
# END IF
pre_start()
{
  if [ -r /etc/profile ]; then
    . /etc/profile
  fi
  if [ -r ~/.bash_profile ]; then
    . ~/.bash_profile
  else
    if [ -r ~/.bash_login ]; then
      . ~/.bash_login
    else
      if [ -r ~/.profile ]; then
        . ~/.profile
      fi
    fi
  fi
  return 0
}

# When loging out from the interactive shell, the execution sequence is:
#
# IF ~/.bash_logout exists THEN
#     execute ~/.bash_logout
# END IF
post_start()
{
  if [ -r ~/.bash_logout ]; then
    . ~/.bash_logout
  fi
  return 0
}

#. /etc/environment
#export PATH=$PATH
#export LANG=$LANG

# change PATH to be what your environment needs usually what is in
# /etc/environment
#PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
#export PATH=$PATH

# for PATH and LANG from /etc/environment
# pam will auto process the environment file if /etc/pam.d/xrdp-sesman
# includes
# auth       required     pam_env.so readenv=1

pre_start
wm_start
post_start

exit 1
```

**Comment by TheLeank** [comment]
@Sebazzz Sadly it didn't work for me, I appreciate your help. Now, that's a really different file of what I have. I'll keep investigating despite I'm not really good at it.

**Comment by matt335672** [comment]
Hi @TheLeank 

I'm happy to help if you can provide more information.

The following would be useful :-
- Operating system and version
- XRDP installed from package manager or built from source?
- XRDP version
- Xvnc or Xorg backend?
- If Xorg backend, what version of xorgxrdp is installed?
- What exactly your symptoms are

Thanks.

**Comment by TheLeank** [comment]
Ubuntu 20.04.1 LTS (Linux Lite)
XRDP version xrdp 0.9.12 installed from package manager
Xorg backend
0.2.12
As the creator of this issue, I can connect with the Windows 10 rdp default client, then I get to type my password: when I do, the screen goes black and the rdp client dies.

I didn't change anything in the configuration until I tried the startwm.sh file Sebazzz provided

**Comment by matt335672** [comment]
OK - that's good.

Can you do the following for me:-

1. Make sure no-one is logged in to the machine console. See the [wiki](/neutrinolabs/xrdp/wiki/Debian-dbus-user-session-package) for why that is a bad idea.
2. Log in to the Linux machine using `ssh` from another machine, or `putty` from Win 10.
3. Make a note of the system time in hours, minutes and seconds (HH:MM:SS) with the `date` command
4. Try to connect from Windows 10
5. After the client dies use the command `sudo journalctl -S HH:MM:SS` (where HH:MM:SS is the time from step 3) to get a system log.
6. Paste that here and we'll have a look at it.

Thanks.

**Comment by TheLeank** [comment]
Oh @matt335672 , I'm kind of embarrased, checked the wiki but didn't read it all. It's working after I logout the session. Expected a windows-like popup telling me to drop the current  session. Thank you, sir!

**Comment by matt335672** [comment]
OK - that's cool. Thanks for letting us know, and have a good weekend.

**Comment by itnavigate** [comment]
I also had this problem on a ubuntu 20 server install. 
I have attempted to resolve it by:
`
sudo  apt remove dbus-user-session #From Wiki
sudo  apt install xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils #From https://websiteforstudents.com/how-to-connect-via-remote-desktop-rdp-to-ubuntu-20-04-18-04/
`

I don't care for having multiple sessions open - I will only be connected once. But I can't connect to ubuntu 20.04 initially installed as a server, with `
apt-get install xrdp
`
to install the windowing environment.

I get the login screen, type in the password, then black screen, then exit. Any hnts?

**Comment by matt335672** [comment]
If you're not going to have multiple sessions, don't mess with the dbus stuff.

Hints:-
- If you're using the xorg back end, install xorgxrdp
- If you're using the xvnc back end install tigervnc-standalone-server
- If you're having problems starting a session, check `/var/log/xrdp-sesman.log`, `sudo journalctl -S -5m` and `~/.xsession-errors` for the account you're trying to log in to.

**Comment by Mathew-Jones** [comment]
matt, seriously could use your help. I have installed xrdp but when i attempt to log on iget an error stating it cant log on. everyone says its my username and password, but i use them daily to get into the Linux VM, So they should work to get into it remotely as well. Please help

**Comment by matt335672** [comment]
@Mathew-Jones - can you please raise a new issue on this?

Please include software versions and the contents of xrdp.log and xrdp-sesman.log following a login attempt.

**Comment by fatlumrreci** [comment]
You should try to log out from the signet user in Ubuntu first, and then connect via RDP.
