### ISSUE TITLE
xrdp 0.9.12-1 fails to start when binded to an interface

### ISSUE THREAD

**Issue by robertoetcheverryr** [neutrinolabs/xrdp#1610]
Running Kali Linux 2020.2, inside Hyper-V with 3 network interfaces configured.
Installed xrdp 0.9.12-1, enabled the services at startup, and configured xrdp.ini to listen on one specific interface:
```
port=tcp://10.0.0.1:3389
```
Now, xrdp always fails to start with the system with:
```
[ERROR] trans_listen_address failed
[DEBUG] Closed socket 7 (AF_INET 0.0.0.0:0)
[ERROR] Failed to start xrdp daemon, possibly address already in use.
```
If I log into the system and manually start the services:
```
sudo service xrdp start
```
They come up without any problems.

If I modify the xrdp.ini to bind to ALL interfaces:
```
port=tcp://:3389
```
It starts up fine (binding to 0.0.0.0 of course) and it also starts fine on the interface I actually want.

I spent a couple of hours playing around with the systemd targets, services and devices. I assume that xrdp fails due to the interface not being UP yet.
Is there any other way to configure either the systemd service or the .ini so xrdp will actually wait for the interface?
Should there be a default service configuration or a warning in the config fail regarding this? I cannot be the only one wanting to bind to a specific interface.
I would rather do it the right way, instead of hacking together a script that waits until the iface is ready and then starts the service.

**Comment by metalefty** [comment]
I'm not so sure with Kali Linux but as you say it's not an xrdp issue but issue of daemon's starting order. 

What about adding `Restart=` to the unit file as workaround? It makes xrdp to try to start more than one time even if it fails to start.  By default, the daemon tries to restart 5 times with 10 seconds interval. As a result you'll have 50 seconds to wait the interface being up.

https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=interval

**Comment by robertoetcheverryr** [comment]
I will try this and report back. In the meantime, the spirit of this comment/issue is that if sshd, which I have configured in the same way, to listen only on that interface, can start and wait until ready, why not fix whatever is needed for xrdp to do it as well?

**Comment by robertoetcheverryr** [comment]
Fixed it by adding:
```
ExecStartPre=/bin/sh -c 'until ping -c1 interfaceIP; do sleep 1; done;'
```
To the [Service] portion.
Now, as I said, if the ssh daemon can somehow be initialized by systems and not crash due to the network not being ready what would be needed for xrdp to behave that way? I do not have enough systemd knowledge to find the differences between both service definitions (since the only one I could see was a dependency on auditd.service which didn't matter).

I did notice that a
```
systemd-analyze plot
```
Doesn't actually mention the actual sshd service that I see running later and that the plot itself shows that xrdp and xrdp-sesman are among the very last to be initialized...

**Comment by matt335672** [comment]
Hi @robertoetcheverryr 

I've had a look at the sshd code, and also at the behaviour of sshd, and I can't find any evidence of special handling if interfaces are not available.

I did the following on a copy of Mint 19:-
- Copied `/etc/ssh/sshd_config` to `/tmp/sshd_config`
- Edited `/tmp/sshd_config` and added `ListenAddress 10.0.0.1`
- Ran `sudo $(which sshd) -d -f /tmp/sshd_config `

Output was:-
```
debug1: sshd version OpenSSH_7.6, OpenSSL 1.0.2n  7 Dec 2017
debug1: private host key #0: ssh-rsa SHA256:xxxxxx
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:xxxxxx
debug1: private host key #2: ssh-ed25519 SHA256:xxxxxx
debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-d'
debug1: rexec_argv[2]='-f'
debug1: rexec_argv[3]='/tmp/sshd_config'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 22 on 10.0.0.1.
Bind to port 22 on 10.0.0.1 failed: Cannot assign requested address.
Cannot bind any address.
```

So it seems likely that this is something being handled elsewhere, either by systemd as you suggest, or possibly another component.

I don't have a Kali VM to hand, but on my Mint 19 system (also based on Debian), the `openssh-server` package contains a file `/etc/network/if-up.d/openssh-server`. This simply restarts sshd each time an interface comes up. Is that what's happening on your system? Have a look at the output of `dpkg -L openssh-server` for interesting files.

**Comment by robertoetcheverryr** [comment]
Hi @matt335672
I was securing my Kali VM and I noticed that it wasn't sshd that was listening on the ssh port... It was systemd. Apparently, systemd now has a service that starts "ondemand" servers. That is the reason for the discrepancy between xrdp and sshd. When using sshd.service itself, it fails just as xrdp. This stems from the network target not being clearly defined:

https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

Adding an override with Wants=network-online.target doesn't resolve the issue and both still fail to come up.

So, in the end, if you want to secure the services by restricting their listening IPs, you better be ready to manually check that those IPs are ready before service start. The wiki mentions a kernel option to bind to a not-yet-existent IP,  maybe that could be a solution? Maybe as an option in the config?

**Comment by matt335672** [comment]
Another way to do it would be to listen on all interfaces and use the firewall to allow only those connections which you want.

The option you mention (I think) is a 'non-local bind', set with this Linux sysctl:-

```
net.ipv4.ip_nonlocal_bind=1
```

More recent kernels have an ipv6 variant available too. Which wiki did you find it on? I can't find it on the xrdp wiki.

I don't think we'd want to add that as an XRDP config option, as it affects the behaviour of other services using the same network stack (see [here](https://stackoverflow.com/questions/60710149/how-can-ip-nonlocal-bind-1-break-applications) (stackoverflow.com]). From what I've read this should be transparent to the services it's set for.

**Comment by robertoetcheverryr** [comment]
@matt335672 
The wiki is the one I referenced.
`
If you write a server: if you want to listen on other, explicitly configured addresses, consider using the IP_FREEBIND sockopt functionality of the Linux kernel. This allows your code to bind to an address even if it is not actually (yet or ever) configured locally. This also makes your code robust towards network configuration changes.
`

The IP_FREEBIND option is per-socket instead of per-interface and it shouldn't affect other programs.
https://man7.org/linux/man-pages/man7/ip.7.html

In any case, using the wildcards for IPv4 and IPv6 and then restricting seems to be the way to go. I think some kind of warning or comment next to the listening IP section could stave off this kind of problem in the future. Maybe a clarification that if you don't bind to the wildcards it might fail to start/bind and to use the firewall?

**Comment by matt335672** [comment]
Oh - that's a lot better than the sysctl (which will work). Thanks for the reference.

I agree that something should be done, even if it's only the improved commenting as you suggest. We'll leave this open until it gets addressed.

Thanks for the input - that's very useful.

**Comment by robertoetcheverryr** [comment]
May I make a PR touching xrdp/xrdp/xrdp.ini.in to add the commenting? If, later, somebody can investigate a better solution it can be changed again.

**Comment by matt335672** [comment]
By all means - thank you.

You might want to consider `docs/man/xrdp.ini.5.in` as well (or instead of) depending on the comment contents.

**Comment by robertoetcheverryr** [comment]
I will do both. A quick comment on the file itself and a better explanation on the man. I have found an inconsistency on the man for xrdp.ini:
It mentions an address property, separated from the port but it is never referenced on the .ini itself:

```
address=ip address
Specify  xrdp  listening  address. If not specified, defaults to 0.0.0.0 (all interfaces).
```

Then, it mentions the port property but only claims to define the port:
```
port=port
Specify TCP port to listen on for incoming connections.  The default for RDP is 3389.
```

I am not sure if the address/port format is valid anymore but the current practice per the included .ini is to define them both as `port` properties.

Should I update docs/man/xrdp.ini.5.in to clarify that address is not used anymore and copy part of the examples in the .ini file to the man?

**Comment by matt335672** [comment]
The old address/port way of doing things is no longer supported - good catch.

the manpage needs bringing up-to-date. I wouldn't bother mentioning the old way of doing it, as we'd never remove it.

Thanks again.

**Comment by matt335672** [comment]
I'm closing this one now - issue #1707 has been raised as a specific feature request to add IP_FREEBIND support for XRDP.
