### ISSUE TITLE
cannot start xrdp daemon

### ISSUE THREAD

**Issue by loachfish** [neutrinolabs/xrdp#1614]
update the xrdp with the following commands in Ubuntu 16.04 LTS:
`sudo apt-get install xrdp`
`sudo apt-get install vnc4server`
`sudo apt-get install xubuntu-desktop`

after run these commands, and restart the xrdp service
`sudo systemctl start xrdp`

error occurs:
Job for xrdp.service failed because the control process exited with error code. See "systemctl status xrdp.service" and "journalctl -xe" for details.

the information of `systemctl status xrdp.service`:
```
● xrdp.service - xrdp daemon
   Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since
     Docs: man:xrdp(8)
           man:xrdp.ini(5)
  Process: 49975 ExecStop=/usr/local/sbin/xrdp $XRDP_OPTIONS --kill (code=exited, status=1/FAILURE)
  Process: 44991 ExecStart=/usr/local/sbin/xrdp $XRDP_OPTIONS (code=exited, status=1/FAILURE)
 Main PID: 3316 (code=exited, status=0/SUCCESS)
```

**Comment by matt335672** [comment]
What does `/var/log/xrdp.log` contain?

Also, have you made any changes to `xrdp.ini`?

Thanks,

**Comment by loachfish** [comment]
> What does `/var/log/xrdp.log` contain?
> 
> Also, have you made any changes to `xrdp.ini`?
> 
> Thanks,

[20200623-17:37:27] [DEBUG] xrdp_mm_module_cleanup
[20200623-17:37:27] [DEBUG] xrdp_mm_module_cleanup
[20200623-17:37:27] [DEBUG] xrdp_mm_module_cleanup
[20200623-17:37:27] [DEBUG] xrdp_mm_module_cleanup
[20200623-17:37:27] [DEBUG] Closed socket 19 (AF_UNIX)
[20200623-17:37:27] [DEBUG] Closed socket 19 (AF_UNIX)
[20200623-17:37:27] [DEBUG] Closed socket 19 (AF_UNIX)
[20200623-17:37:27] [DEBUG] Closed socket 25 (AF_UNIX)
[20200623-17:37:27] [DEBUG] Closed socket 20 (AF_UNIX)
[20200623-17:37:27] [DEBUG] Closed socket 20 (AF_UNIX)
[20200623-17:37:27] [DEBUG] Closed socket 20 (AF_UNIX)
[20200623-17:37:27] [DEBUG] Closed socket 26 (AF_UNIX)

**this logs are recorded when I restart xrdp. And there is not any other log if I start xrdp.**

**when I update the xrdp the configs have been keep as the default. details see the following logs:**
Selecting previously unselected package xrdp.
(Reading database ... 340889 files and directories currently installed.)
Preparing to unpack .../xrdp_0.6.1-2ubuntu0.3_amd64.deb ...
Unpacking xrdp (0.6.1-2ubuntu0.3) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for systemd (229-4ubuntu21.28) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Setting up xrdp (0.6.1-2ubuntu0.3) ...

Configuration file '/etc/xrdp/sesman.ini'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** sesman.ini (Y/I/N/O/D/Z) [default=N] ? N

Configuration file '/etc/xrdp/startwm.sh'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** startwm.sh (Y/I/N/O/D/Z) [default=N] ? N

Configuration file '/etc/xrdp/xrdp.ini'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** xrdp.ini (Y/I/N/O/D/Z) [default=N] ? N
Processing triggers for systemd (229-4ubuntu21.28) ...
Processing triggers for ureadahead (0.100.0-19.1) ...

**Comment by loachfish** [comment]
**if the vnc4server has provided the vncserver?**

update-alternatives: using /usr/bin/vnc4server to provide /usr/bin/vncserver (vncserver) in auto mode
update-alternatives: using /usr/bin/Xvnc4 to provide /usr/bin/Xvnc (Xvnc) in auto mode
update-alternatives: using /usr/bin/x0vnc4server to provide /usr/bin/x0vncserver (x0vncserver) in auto mode
update-alternatives: using /usr/bin/vnc4passwd to provide /usr/bin/vncpasswd (vncpasswd) in auto mode
update-alternatives: using /usr/bin/vnc4config to provide /usr/bin/vncconfig (vncconfig) in auto mode

**Comment by matt335672** [comment]
Thanks.

If your getting that prompt, it seems likely your `xrdp.ini` has changed, and that is possibly preventing the XRDP daemon from starting.

Try the following to start with clean files:-

```
sudo mv /etc/xrdp/sesman.ini /etc/xrdp/sesman.ini.sav
sudo mv /etc/xrdp/startwm.sh /etc/xrdp/startwm.sh.sav
sudo mv /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.sav
sudo apt -o Dpkg::Options::="--force-confmiss" install --reinstall xrdp
```

If that gets you running we can look at the saved files to see what they actually contain.

**Comment by matt335672** [comment]
Hi @loachfish 

Any updates on the above? Did you manage to get it working?

**Comment by metalefty** [comment]
N feedback from the reporter, closing.

**Comment by faheemezani** [comment]
> Hi @loachfish

> Any updates on the above? Did you manage to get it working?

I had a similar problem and followed the suggestions above. It certainly resolved the issue on my Ubuntu 20.04 LTS (WSL).

**Comment by loachfish** [comment]
It has been resovled by installing the program via the resource code.

**Comment by tangzhi1996** [comment]
A year has passed, why do I still have this problem when I installed it by command? After the system restarts, the XRDP service fails to start

**Comment by tangzhi1996** [comment]
root@arm-64:~# systemctl status xrdp.service
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-01-19 01:26:18 CST; 10s ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 2205 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/>
    Process: 2213 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=1/FAILURE)
        CPU: 39ms

**Comment by tangzhi1996** [comment]
vnc - xrdp service fails to start after reboot - Raspberry Pi Stack Exchange
https://raspberrypi.stackexchange.com/questions/75892/xrdp-service-fails-to-start-after-reboot
已经解决了

**Comment by wotori** [comment]
I got this error only if I have remote desktop turned on (in gnome environment)
![image](https://user-images.githubusercontent.com/10486621/184964243-0057b378-7045-4e80-a9e5-b49cef0bcd57.png)
after switching it of xrdp starts normally

**Comment by ghost** [comment]
> N feedback from the reporter, closing.



> Thanks.
> 
> If your getting that prompt, it seems likely your `xrdp.ini` has changed, and that is possibly preventing the XRDP daemon from starting.
> 
> Try the following to start with clean files:-
> 
> ```
> sudo mv /etc/xrdp/sesman.ini /etc/xrdp/sesman.ini.sav
> sudo mv /etc/xrdp/startwm.sh /etc/xrdp/startwm.sh.sav
> sudo mv /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.sav
> sudo apt -o Dpkg::Options::="--force-confmiss" install --reinstall xrdp
> ```
> 
> If that gets you running we can look at the saved files to see what they actually contain.


Hello @matt335672 ,
Sorry for bothering you.
Is there any way to access via rdp after changing xrdp.ini file ?
I changed the port in xrdp.ini file.

Thanks

**Comment by matt335672** [comment]
If you changed the port to another number (for example, 33389), you could try adding the changed port number to the server in the RDP connection dialog. Assuming you're using mstsc.exe:-

![image](https://user-images.githubusercontent.com/30179339/208239360-a25d0e7c-9a8b-4bcf-9b4f-f599b44194c3.png)

**Comment by ghost** [comment]
Hello @matt335672 ,
Got it.
Sorry for my bad explanation.

After changing from the RDP default port into 80 port in xrdp.ini file, I can not start xrdp service in ubuntu 20.04.

I wanted to ask how I could solve this issue.
Is there any way to start the xrdp service?

Thanks

**Comment by matt335672** [comment]
On Ubuntu, xrdp runs as a non-privileged user. This user is unable to listen on port 80, as it's what's called a privileged port. If anyone could listen on port 80 (or 443), a non-privileged user could pretend to be a web server on that machine.

Here's one workaround:-

https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443

**Comment by ghost** [comment]
Yes. I know.
Even though a non-privileged user could pretend to be a web server, I would like to start xrdp server after changing xrdp.ini file.

**Comment by matt335672** [comment]
@blkdot - I don't understand your question. What exactly are you trying to do?

**Comment by QyhOfficial** [comment]
> On Ubuntu, xrdp runs as a non-privileged user. This user is unable to listen on port 80, as it's what's called a privileged port. If anyone could listen on port 80 (or 443), a non-privileged user could pretend to be a web server on that machine.
> 
> Here's one workaround:-
> 
> https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443

I changed port number to 11111 in xrdp.ini file on Ubuntu 22.04 and xrdp.service failed to start. How to make xrdp daemon listen on 11111?
```
root@ubuntu22:/home/Qyh# systemctl status xrdp
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2024-05-17 05:34:19 UTC; 5min ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 4979 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 4987 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=1/FAILURE)

May 17 05:34:18 ubuntu22 systemd[1]: Starting xrdp daemon...
May 17 05:34:18 ubuntu22 xrdp[4987]: (4987)(140637888030528)[INFO ] address [0.0.0.0] port [11111] mode 1
May 17 05:34:18 ubuntu22 xrdp[4987]: (4987)(140637888030528)[INFO ] listening to port 11111 on 0.0.0.0
May 17 05:34:18 ubuntu22 xrdp[4987]: (4987)(140637888030528)[ERROR] g_tcp_bind(7, 11111) failed bind IPv6 (errno=98) an>
May 17 05:34:18 ubuntu22 xrdp[4987]: (4987)(140637888030528)[ERROR] trans_listen_address failed
May 17 05:34:19 ubuntu22 xrdp[4987]: (4987)(140637888030528)[DEBUG] Closed socket 7 (AF_INET6 :: port 0)
May 17 05:34:19 ubuntu22 xrdp[4987]: (4987)(140637888030528)[ERROR] Failed to start xrdp daemon, possibly address alrea>
May 17 05:34:19 ubuntu22 systemd[1]: xrdp.service: Control process exited, code=exited, status=1/FAILURE
May 17 05:34:19 ubuntu22 systemd[1]: xrdp.service: Failed with result 'exit-code'.
May 17 05:34:19 ubuntu22 systemd[1]: Failed to start xrdp daemon.
lines 1-18/18 (END)
```
