### ISSUE TITLE
CentOS 7: "Unlock" button in GUI grayed out and prompted for password to shutdown / restart?

### ISSUE THREAD

**Issue by jeffreymcclain** [neutrinolabs/xrdp#1615]
When using XRDP to login as a user with Administrator privileges, I can't create another user in "Settings > Details > Users" because the "Unlock" button near the upper right is grayed out. I also noticed that I get prompted to enter a password when using the menu in the upper right to Restart or Power Off the machine.

When logging in with the same user account directly via VMware Remote Console, the "Unlock" button is not grayed out and I do not get prompted for credentials when restarting / powering off, so it appears to be specific to logging in via remote desktop.

Is there a way to grant administrator users these permissions when logging in via remote desktop? Ideally I'd like the experience to mimic logging in directly via VMware Remote Console as closely as possible, with the same permission set for both.

P.S.: Apologies if the answer should be trivial, I am still somewhat new to Linux administration in general.

Environment: CentOS 7 64-bit, GNOME 3 desktop (classic version)

**Comment by metalefty** [comment]
Hi, it is polkit related issue. You can enable it by configuring polkit properly.

**Comment by jeffreymcclain** [comment]
> Hi, it is polkit related issue. You can enable it by configuring polkit properly.

Apologies if it should be self-explanatory, but would you mind elaborating on what specifically I need to do for "configuring polkit properly"? If the process is already documented somewhere else that's perfectly fine as well, I'd greatly appreciate if you could link me to the instructions / documentation, if it's not too much trouble for. 

Either way, thanks for the assistance!

**Comment by jeffreymcclain** [comment]
As a quick update, I did some Googling and came across an article [with this section](https://i.imgur.com/dLp2Opq.png) discussing xrdp and polkit which seems promising, though it specifically mentions Ubuntu rather than CentOS 7 (and also mentions that it will generate a "crash system" popup on older versions of Ubuntu).

Is this what you mean by "configuring polkit properly", or are the instructions different for CentOS?

**Comment by metalefty** [comment]
Polkit controls whether to allow users to shutdown/restart and other commands so generally it's out of scope of xrdp.
This instruction is written in Japanese but you'll find the similar if you google it. I hope you can find it in your language.

https://www.clear-code.com/blog/2016/12/27.html

**Comment by jeffreymcclain** [comment]
Ah ok, thanks for clarifying! 

I'll close my issue since it sounds like this is just a default security restriction that comes with the operating system installation, rather than anything specific with xrdp. I don't mind logging in via VMware Remote Console directly if I want to create a new user through the GUI, so I think I'll just leave the security policy as is to be safe.
