### ISSUE TITLE
xrdp 0.6.1 vs 0.9.0

### ISSUE THREAD

**Issue by hetzbh** [neutrinolabs/xrdp#162]
Hi,

Looking at xrdp.org - it seems the last version there is 0.6.1 while here it's 0.9.0, yet I can't find whats the differences and what's changed since 0.6.1. Could someone shed a light please?

Also, in 0.6.1 the X11rdp-sesman was using RDP 4 IIRC, has this been changed? whats better these days? Xvnc or X11rdp?

Thanks

**Comment by therevoman** [comment]
I too would like to know the answer to this question.

**Comment by metalefty** [comment]
0.6.1 is the previous stable release.
0.9.0 is under development, it hasn't been released yet. I call this 0.9.0beta.
0.8.0 is the latest stable release.

I personally don't recommend to use Xvnc. It is obsoleted. Please don't confuse I'm not saying VNC is obsoleted. Using Xvnc with xrdp is obsoleted.

0.9.0beta (github master branch) with X11rdp is the best, IMHO. 0.8.0 with X11rdp is the second. The reason why I recommend 0.9.0beta than 0.8.0 is (brushed-up) TLS support. Classic RDP cipher is no longer considered to be safe.

**Comment by jsorg71** [comment]
Yes, this is right except that there is about to be a v0.8.1 that has all the TLS fixes.
v0.8.1 will be just like master at that point.

Soon Xvnc will be removed from xrdp unless we can get some security patches in their side.
You will still be able to proxy VNC connection but sesman will not manage them.

**Comment by metalefty** [comment]
That's great. 
Do you have a plan merging Japanese Keyboard fixes that I and AkiraPenguin made v0.8.1?

Most Linux distributors only make packages from officially released tarballs. If v0.8.1 included our fixes,  more Japanese xrdp users can live a happy xrdp life :smiley:

**Comment by metalefty** [comment]
I overlooked JP keyboard changes had already merged into v0.8 branch.

**Comment by geiseri** [comment]
I think there is a problem that packagers do not want to build X11rdp in the current state since you need root, or an absolute file path to build it.  I think until the xorg driver is stable VNC is still the best for generic use.

**Comment by metalefty** [comment]
v0.9.1 has been released.  We recommend to use v0.9.1 rather than v0.6.1. Closing.
