### ISSUE TITLE
CentOS 7.7: Xvnc session working OK, but Xorg session does not...

### ISSUE THREAD

**Issue by acidrop** [neutrinolabs/xrdp#1621]
Hello,

Trying to get Xorg session working on my system, but having some difficulties...appreciate your help.

System: CentOS 7.7
XRDP: xorgxrdp-0.2.13-1.el7.x86_64, xrdp-0.9.13-2.el7.x86_64

[xrdp.ini.txt](https://github.com/neutrinolabs/xrdp/files/4840104/xrdp.ini.txt)
[sesman.ini.txt](https://github.com/neutrinolabs/xrdp/files/4840105/sesman.ini.txt)

Issue:
Once authenticated on Xorg session, session starts but immediately closes without showing any content. Tested with various RDP clients (Windows, Mac). Xvnc session is working without any issues.

Logs:
[xrdp.log.txt](https://github.com/neutrinolabs/xrdp/files/4840130/xrdp.log.txt)
[xrdp-sesman.log.txt](https://github.com/neutrinolabs/xrdp/files/4840131/xrdp-sesman.log.txt)
[xorgxrdp.15.log.txt](https://github.com/neutrinolabs/xrdp/files/4840132/xorgxrdp.15.log.txt)

**Comment by matt335672** [comment]
The GLX extension is not loading, and the GNOME desktop requires this. From your xorgxrdp log file:-

```
[142193.430] (EE) Failed to initialize GLX extension (Compatible NVIDIA X driver not found)
```

We can confirm the effects of this by using this procedure to see what the desktop is logging:-
- Make a note of the current time (hh:mm:ss)
- Try to create a session
- After the session has exited, use `sudo journalctl -S <hh:mm:ss>` to dump out everything logged by the session.

You might see messages like the following :-

```
gnome-session-binary[]: WARNING: software acceleration check failed: Child process exited with code 1
gnome-session[]: gnome-session-binary[]: CRITICAL: We failed, but the fail whale is dead. Sorry....
```

These would indicate that GLX is inoperative.

It looks to me like you've got some bits and pieces from an old NVidia installation knocking round on your machine in `/usr/lib64/xorg/modules/extensions`. If that's the case you might also have a file in `/etc/ld.so.conf.d/` which needs removing. I don't have any NVidia hardware myself to play with here, but hopefully that's helpful to you.

**Comment by acidrop** [comment]
Many thanks for you reply... Attaching log as requested:
[xrdp.log](https://github.com/neutrinolabs/xrdp/files/4846565/xrdp.log)

Found the following lines which may be related to what you said:
```
Jun 29 16:40:07 pukeko gnome-session[23811]: gnome-session-binary[23811]: WARNING: software acceleration check failed: Child process exited
Jun 29 16:40:07 pukeko gnome-session-binary[23811]: WARNING: software acceleration check failed: Child process exited with code 1
Jun 29 16:40:08 pukeko gnome-session-f[24482]: Cannot open display:
```

Also ...

```
root@pukeko[04:51 pm]:/ ls -l /usr/lib64/xorg/modules/extensions/
total 502
-rwxr-xr-x 1 root root 297960 Jan 29  2019 libglx.so
-rwxr-xr-x 1 root root 583832 Aug  9  2019 libvnc.so
drwxr-xr-x 2 root root      4 Feb 18 12:05 nvidia
root@pukeko[04:51 pm]:/ ls -l /usr/lib64/xorg/modules/extensions/nvidia/
total 3713
lrwxrwxrwx 1 root root       17 Feb 18 12:05 libglx.so -> libglx.so.390.116
-rwxr-xr-x 1 root root 14013096 Feb 15 11:53 libglx.so.390.116
```

I'm using a NVidia Quadro K4200 graphics card with drivers installed directly from NVidia site (v390.116) (not nuveau). 
The NVidia graphics card works fine when logged on the interactive session (with GNOME). By removing you mean removing the driver completely from the system ? Unfortunately that is not possible, as I need the drivers installed for 3rd party app to work (3D hardware acceleration). 

Thanks

**Comment by matt335672** [comment]
The NVidia drivers always work well with the main console as that's why they sell the cards. Sadly the NVidia drivers have a history of breaking other bits of the system as you'll find by perusing this forum and others.

I can offer you three ways forward which might work
- Try installing the NVidia drivers from [ELREPO](https://elrepo.org). These are packaged for RHEL/CentOS and can work better than the generic NVIdia run script.
- See if the Xvnc back end works. It may or may not. See for example [here](https://github.com/TigerVNC/tigervnc/issues/39)
- Use a desktop for remote sessions which doesn't need 3D acceleration.

As an aside, I don't believe that xorgxrdp is yet able to make use of NVidia hardware for accelerating XRDP sessions.

**Comment by acidrop** [comment]
Thanks for your suggestions. I installed drivers from ELREPO but that did not make any difference.
I ended up using your last suggestion, a Desktop which does not require 3D acceleration (MATE).
