### ISSUE TITLE
xrdp doesn't open windows manager on linux

### ISSUE THREAD

**Issue by erdosnew** [neutrinolabs/xrdp#1622]
Hi, I installed xrdp on my Devuan beowulf (3.0) system.  once connection is established from windows 10, i can choose either 'Xorg' or 'Xrdp' session at login screen, but the desktop only shows a terminal window instead of showing a windows manager ( i have 'icewm') once logged in, I'd like to launch into my system with windows manager. 

any advice?

**Comment by matt335672** [comment]
On Debian and Debian-like systems, the desktop session startup normally goes like this:-

- xrdp-sesman calls the script named by the `[Globals]/DefaultWindowManager` setting in `/etc/xrdp/sesman.ini`. This is normally `/etc/xrdp/startwm.sh`
- `startwm.sh` will normally call `/etc/X11/Xsession` which is part of Debian
- `Xsession` will look for a session (if it's not given one) using a variety of methods. The backstop is `/usr/bin/x-terminal-emulator` which is where you seem to be ending up.

You can use `~/.xsession` to tell the `Xsession` script which window manager to run.  This is the recommended way. 

Use one of these two options, both of which you'll find more detailn on on the web. I'm assuming that `/usr/bin/icewm-session` starts icewm. I may be wrong.

1. `ln -s /usr/bin/icewm-session ~/.xsession`
2. Create `~/.xsession` as a text file with the following contents:-

```bash
#!/bin/bash

exec /usr/bin/icewm-session
```

Alternatively, use the information above to roll your own solution.

**Comment by erdosnew** [comment]
thank you!  The problem has resolved itself after i rebooted.
