### ISSUE TITLE
Oh my fucking god what the fuck is the problem with you guys??!?!?!?

### ISSUE THREAD

**Issue by RubyGParrish** [neutrinolabs/xrdp#1628]
Your fucking software is by far THE WORST, MOST UNSTABLE, COUNTERINTUITIVE, AND WITH THE MOST FUCKED UP UI I HAVE EVER SEEN IN LIKE 30 YEARS OF WORKING IN IT 

WHAT THE FUCK IS THE PROBLEM WITH YOU MOTHERFUCKERS?!?!? JUST FUCKING LEARN HOW TO FUCKING DEVELOP SOFTWARE OR OTHERWISE GO CHILL ON THE FUCKING BEACH, OR GO FUCK YOUR OWN SISTERS BEN CHODS (I guess the most of you are Indian by the looks of your code) I DON'T EVEN FUCKING CARE WHAT YOU DO WITH YOUR FUCKING SHIT JUST JO IT FUCKING FAR AWAY FROM THE FUCKING COMPUTER SCIENCE FIELD. FUCK YOU ALL WITH WITH YOUR FUCKING SHIT YOU BEN CHODS SHITFUCKERS

**Comment by metalefty** [comment]
Hasta la vista.

**Comment by blackcrack** [comment]
pfffhaha.. tztztz..
@metalefty ,types exist.. he made extra an account especially for this.., Support of Github should check the IP's where was login and catche his real IP and disable them real account also.. 0("holy!!")0
best :)

**Comment by metalefty** [comment]
Yes, I've reported that fucking addicted guy to GitHub.

**Comment by blackcrack** [comment]
oh maan.. hihi.. something enriches life already *bg*
this helps to see what for a well live it have by self ;)
if I would be annoyed with something like that, it would only hit me on my stomach, so you can try to stand over something like that and be enriched that there are worse things  ;)
best
