### ISSUE TITLE
Patches from Fedora project 

### ISSUE THREAD

**Issue by hetzbh** [neutrinolabs/xrdp#163]
Hi,

The Fedora project builds XRDP packages for version 0.6.1 and there are patches which would help a lot people with Fedora 20 which include systemd support.

Pathces are located at: http://pkgs.fedoraproject.org/cgit/xrdp.git

Are those patches merged? if not, who can merge those patches? Without those patches, you won't be able to stop/start/restart XRDP

Thanks

**Comment by metalefty** [comment]
Summarized status.

http://pkgs.fedoraproject.org/cgit/xrdp.git/tree/xrdp-0.6.1-implicit-decl.patch
http://pkgs.fedoraproject.org/cgit/xrdp.git/tree/xrdp-0.6.1-memset.patch
http://pkgs.fedoraproject.org/cgit/xrdp.git/tree/xrdp-0.6.1-syslog-format.patch
http://pkgs.fedoraproject.org/cgit/xrdp.git/tree/xrdp-0.6.1-vnc-delay.patch -> #184 (merged)
http://pkgs.fedoraproject.org/cgit/xrdp.git/tree/xrdp-endian.patch -> #165 (merged)
http://pkgs.fedoraproject.org/cgit/xrdp.git/tree/xrdp-pam-auth.patch
http://pkgs.fedoraproject.org/cgit/xrdp.git/tree/xrdp-pam_session.patch

**Comment by itamarjp** [comment]
most of the pacthes merged, closing this.
