### ISSUE TITLE
Error: Can't open PID file /run/xrdp.pid + Closed socket 19 (AF_UNIX)

### ISSUE THREAD

**Issue by RebelCoderRU** [neutrinolabs/xrdp#1630]
Hello, I have seen this issue raised before, but non of the solutions worked for me.

I am on latest Manjaro, xrdp service is running but with one error/warning about xrdp.pid?

```
Jul 09 04:48:48 RebelVeggie xrdp[2220]: [20200709-04:48:48] [INFO ] listening to port 3389 on 0.0.0.0
Jul 09 04:48:48 RebelVeggie xrdp[2220]: [20200709-04:48:48] [INFO ] xrdp_listen_pp done
Jul 09 04:48:48 RebelVeggie xrdp[2220]: [20200709-04:48:48] [DEBUG] Closed socket 7 (AF_INET 0.0.0.0:3389)
Jul 09 04:48:48 RebelVeggie xrdp[2220]: daemon process 2221 started ok
Jul 09 04:48:48 RebelVeggie systemd[1]: xrdp.service: Can't open PID file /run/xrdp.pid (yet?) after start: Operation not permitted
Jul 09 04:48:49 RebelVeggie systemd[1]: Started xrdp daemon.
Jul 09 04:48:50 RebelVeggie xrdp[2221]: (2221)(140350250735808)[INFO ] starting xrdp with pid 2221
Jul 09 04:48:50 RebelVeggie xrdp[2221]: (2221)(140350250735808)[INFO ] address [0.0.0.0] port [3389] mode 1
Jul 09 04:48:50 RebelVeggie xrdp[2221]: (2221)(140350250735808)[INFO ] listening to port 3389 on 0.0.0.0
Jul 09 04:48:50 RebelVeggie xrdp[2221]: (2221)(140350250735808)[INFO ] xrdp_listen_pp done

```

When I attempt to connect, client disconnects and server starts spamming this:

```
Jul 09 04:50:11 RebelVeggie xrdp[2310]: (2310)(140350250735808)[DEBUG] Closed socket 19 (AF_UNIX)

```

Any ideas?

**Comment by matt335672** [comment]
The PID message can be ignored - it's an artefact of the way XRDP is packaged for Manjaro.

More info is required. Can you post  the following:-
- `/var/log/xrdp-sesman.log`
- The `~/.xorgxrdp.X.log` with the highest number `X` if you're using the xorgxrdp backend.

Thanks.

**Comment by GeorgeCastanza** [comment]
I'm getting this as well. Same PIS message as above. 

![image](https://user-images.githubusercontent.com/30585632/91309124-928ced80-e7f3-11ea-8a02-8bd1aa8768e8.png)

**Comment by matt335672** [comment]
Can you please add a bit more info:-
- What's the actual problem you're experiencing? The log's not telling us that.
- What platform are you on?
- Version of XRDP?
- xrdp installed from package manager or source?
- Are you using Xorg or Xvnc backend?

Thanks.

**Comment by GeorgeCastanza** [comment]
Sorry, problem is when I attempt to connect, client disconnects. I enter the user name/password and hit OK, and then after 20 seconds RDC on Windows is closed. It's been working well for months, upgraded packages yesterday, XRDP fails. 

Platform: Armbian, 20.04 (kept up to date on latest stable builds)
XRDP version: 0.9.12
XRDP installed via package manager, uninstalled and re-installed manually.
Using Xorg (not sure how to change via backend).

I also get the same error as the OP (xrdp.service: Can't open PID file /run/xrdp.pid (yet?) after start: Operation not permitted) 

I've tried all the suggestions via google for this error.

**Comment by GeorgeCastanza** [comment]
After doing some more googling, this solved my issue:

In /etc/xrdp/startwm.sh change #!/bin/sh to #!/bin/bash

Info here: https://askubuntu.com/questions/1166568/remote-desktop-blue-screen-after-login

**Comment by fraz0815** [comment]
> After doing some more googling, this solved my issue:
> 
> In /etc/xrdp/startwm.sh change #!/bin/sh to #!/bin/bash
> 
> Info here: https://askubuntu.com/questions/1166568/remote-desktop-blue-screen-after-login

this also fixed black screens on my SBC's running armbian.

**Comment by matt335672** [comment]
That's interesting - thanks.

The scripts in `/etc/profile.d` should all be POSIX compliant, as this directory is used by all Bourne-type shells. The fix you've used is fine if your user community is using bash exclusively, but if you've got any users using `dash` you could still have problems.

I don't suppose you know which script in `/etc/profile.d` is failing?

On a couple of the other points you raise:-
- The back-end is selected on the initial login screen along with the username and password. XRDP supports two backends (Xorg and Xvnc). Normally Xorg is recommended, but Xvnc can work better in a few edge cases.
- The PID error is an artefact of the way XRDP is packages for Debian/Ubuntu and can be ignored.

**Comment by GeorgeCastanza** [comment]
> I don't suppose you know which script in /etc/profile.d is failing?

No, sorry I dont.  I am happy to help if you want me to provide any details.

**Comment by matt335672** [comment]
OK - thanks for the offer. Hopefully we can track it down and I can raise a launchpad issue on the correct package.

Could you please give me the output of the following commands which might give us a clue?

```
ls -l /etc/profile.d
/bin/sh -x /etc/profile
```

The first command tells us what we're dealing with, and the second uses the Bourne shell in trace mode to run through them.

**Comment by GeorgeCastanza** [comment]
![image](https://user-images.githubusercontent.com/30585632/91674564-91a1e600-eb7c-11ea-8530-e24033dbec2d.png)

Sorry it took a while. I was busy over the weekend.

**Comment by matt335672** [comment]
That looks pretty clear.

Also, it looks like an Armbian issue rather than Debian.

I don't have a PI to hand, so could you please give me the output of the following command?

```
dpkg -S /etc/profile.d/armbian-check-first-login.sh
```

Thanks

**Comment by GeorgeCastanza** [comment]
Sure, here it is:  (By the way, it's an Odroid N2, not a PI...)

![image](https://user-images.githubusercontent.com/30585632/91720550-a8772580-ebda-11ea-8e90-92f362bb60ca.png)

**Comment by matt335672** [comment]
OK - ta.

This is getting a bit complicated. I've found the source for that file here:-

[https://github.com/armbian/build/packages/bsp/common/etc/profile.d/armbian-check-first-login.sh](https://github.com/armbian/build/packages/bsp/common/etc/profile.d/armbian-check-first-login.sh)

It's definitely not sh compatible. There's a 'function' keyword at line 20 and an array definition at line 57 for starters.

I'll raise another issue here as it affects all Raspbian users. That issue will reference this one and I'll close this one.

Thanks for your help with this.

**Comment by matt335672** [comment]
Moved to #1672
