### ISSUE TITLE
compiling with turbojpeg on ubuntu 14.4 fails

### ISSUE THREAD

**Issue by FrankVanDamme** [neutrinolabs/xrdp#164]
Compiling with --enable-tjpeg on ubuntu 14.4 halts with an error:

libtool: link: gcc -shared  -fPIC -DPIC  .libs/libxrdp.o .libs/xrdp_channel.o .libs/xrdp_iso.o .libs/xrdp_mcs.o .libs/xrdp_orders.o .libs/xrdp_rdp.o .libs/xrdp_sec.o .libs/xrdp_bitmap_compress.o .libs/xrdp_bitmap32_compress.o .libs/xrdp_jpeg_compress.o .libs/xrdp_orders_rail.o .libs/xrdp_mppc_enc.o   -Wl,-rpath -Wl,/home/bigboss/Downloads/neutrinolabs-xrdp/common/.libs -Wl,-rpath -Wl,/usr/local/lib/xrdp -L/opt/libjpeg-turbo/lib -L/usr/local/lib ../common/.libs/libcommon.so -lfreerdp-core -lfreerdp-codec -lfreerdp-gdi -lfreerdp-kbd -lfreerdp-rail -lfreerdp-channels -lfreerdp-utils -lturbojpeg  -Wl,-rpath -Wl,/opt/libjpeg-turbo/lib -Wl,-rpath -Wl,/usr/local/lib   -Wl,-soname -Wl,libxrdp.so.0 -o .libs/libxrdp.so.0.0.0
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libxrdp.la] Error 1
make[2]: Leaving directory `/home/bigboss/Downloads/neutrinolabs-xrdp/libxrdp'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/bigboss/Downloads/neutrinolabs-xrdp'
make: *** [all] Error 2

**Comment by metalefty** [comment]
Not a turbojpeg issue and no activities for 2 years, closing.
