### ISSUE TITLE
Internal username / password (256) buffer is smaller than max username / password in rdp protocol (511)

### ISSUE THREAD

**Issue by bolkedebruin** [neutrinolabs/xrdp#1648]
While experimenting with SSO with JWT tokens supplied in the username field I encountered that usernames above 256 characters are not accepted (xrdp drops the connection). However on the protocol level it is specified te be a maximum of 511 characters. 

The internal buffers in xrdp use indeed 256 although it checks for 511 when accepting the connection

I suggest (and will provide a PR) to have a larger buffer.

**Comment by metalefty** [comment]
Good catch.
