### ISSUE TITLE
xrdp port=ask-1 "some problem error"

### ISSUE THREAD

**Issue by j4jes** [neutrinolabs/xrdp#1649]
Hi I'm using the port=ask-1 option in my xrdp.ini to resume my sessions and it works fine, but I get this nagging error each time before I login to the custom logo screen. It says: connecting to 127.0.0.1 ask-1 , vnc error - problem connecting  some problem.

![error](https://user-images.githubusercontent.com/32603912/89689655-d9618480-d8d2-11ea-9be1-a246cc306f7a.PNG)

**Comment by metalefty** [comment]
How did you invent the usage of  `ask-1`?

**Comment by metalefty** [comment]
No feedback from the reporter, closing.
