### ISSUE TITLE
xrdp won't listen to ipv4 port on 18.04

### ISSUE THREAD

**Issue by quang777** [neutrinolabs/xrdp#1652]
This issue is similar to 
https://github.com/neutrinolabs/xrdp/issues/1596
and
https://github.com/neutrinolabs/xrdp/issues/1450

XRDP seems to ONLY bind to the ipv6 (when enabled) even if I explicitly set the port using ipv4 syntax.  When ipv6 is disabled via grub, it refuses to start per the other discussion (#1596 ). On Ubuntu 18.04 (supported until 2023 right?), the latest version of xrdp is 0.9-5.2

```
root@lovage:/var/log# systemctl start xrdp
root@lovage:/var/log# ps -ef|grep xrdp
root      2772     1  0 11:57 ?        00:00:00 /usr/sbin/xrdp-sesman
xrdp      2783     1  0 11:57 ?        00:00:00 /usr/sbin/xrdp
root      2821  4726  0 11:58 pts/0    00:00:00 grep --color=auto xrdp

```
```
root@lovage:/var/log# netstat -nl|grep 3389
tcp6       0      0 ::1:3389                :::*                    LISTEN     
```

```
root@lovage:/var/log# head -10 /etc/xrdp/xrdp.ini
[Globals]
# xrdp.ini file version number
ini_version=1

bitmap_cache=yes
bitmap_compression=yes
address=127.0.0.1
port=3389
allow_channels=true
max_bpp=24



```

**Comment by matt335672** [comment]
Thanks for opening this @quang777 

From what I've seen of this fault, I don't believe it's the same as #1547 

You've posted above what happens when IPv6 is enabled. Can you add some more information about what happens when IPv6 is disabled? In particular, when the failure occurs, what is the output of `sudo systemctl status xrdp`  and `sudo systemctl status xrdp-sesman`?

One other thing (which is unrelated) you've got `address=127.0.0.1` set in the `xrdp.ini` file. Is this intentional? Are you not expecting incoming connections to TCP port 3389?

**Comment by quang777** [comment]
Remote access services are restricted in our company, so we only allow it using a loopback device via a ssh tunnel. 
I couldn't disable ipv6 on the previous machine (as it was in use), so I set up another identically configured machine running 18.04 and disabled ipv6 after seeing it work with ipv6 ENABLED. 
Here's the output you requested when ipv6 is disabled:
root@gladys-0009341:~# dmesg|grep BOOT_IMAGE
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-112-generic root=UUID=7c7fde9a-da32-47f8-8dc6-f1d871cf1181 ro ipv6.disable=1 quiet
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-112-generic root=UUID=7c7fde9a-da32-47f8-8dc6-f1d871cf1181 ro ipv6.disable=1 quiet

root@gladys-0009341:~# sudo systemctl status xrdp
● xrdp.service - xrdp daemon
   Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:xrdp(8)
           man:xrdp.ini(5)

Aug 17 19:53:35 gladys-0009341 systemd[1]: Dependency failed for xrdp daemon.
Aug 17 19:53:35 gladys-0009341 systemd[1]: xrdp.service: Job xrdp.service/start failed with result 'dependency'.
root@gladys-0009341:~# sudo systemctl status xrdp-sesman
● xrdp-sesman.service - xrdp session manager
   Loaded: loaded (/lib/systemd/system/xrdp-sesman.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-08-17 19:53:35 PDT; 19min ago
     Docs: man:xrdp-sesman(8)
           man:sesman.ini(5)
  Process: 2131 ExecStart=/usr/sbin/xrdp-sesman $SESMAN_OPTIONS (code=exited, status=1/FAILURE)

Aug 17 19:53:32 gladys-0009341 xrdp-sesman[2243]: (2243)(140044069459264)[INFO ] IPv6 not supported, falling back to IPv4
Aug 17 19:53:32 gladys-0009341 xrdp-sesman[2131]: (2131)(140044069459264)[DEBUG] Testing if xrdp-sesman can listen on 127.0.0.1 port 3350.
Aug 17 19:53:32 gladys-0009341 xrdp-sesman[2243]: (2243)(140044069459264)[INFO ] listening to port 3350 on 127.0.0.1
Aug 17 19:53:33 gladys-0009341 xrdp-sesman[2131]: (2131)(140044069459264)[ERROR] bind_loopback(5, 3350) failed; IPv6 ::1 (errno=97), IPv4 127.0.0.1 (errno=98) and IPv6 ::FFFF:127.0.0.1 (errno=97).
Aug 17 19:53:33 gladys-0009341 xrdp-sesman[2131]: (2131)(140044069459264)[ERROR] Failed to start xrdp-sesman daemon, possibly address already in use.
Aug 17 19:53:34 gladys-0009341 systemd[1]: xrdp-sesman.service: Control process exited, code=exited status=1
Aug 17 19:53:34 gladys-0009341 xrdp-sesman[2243]: (2243)(140044069459264)[INFO ] shutting down sesman 1
Aug 17 19:53:34 gladys-0009341 xrdp-sesman[2243]: (2243)(140044069459264)[DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
Aug 17 19:53:35 gladys-0009341 systemd[1]: xrdp-sesman.service: Failed with result 'exit-code'.
Aug 17 19:53:35 gladys-0009341 systemd[1]: Failed to start xrdp session manager.
root@gladys-0009341:~# netstat -nl|grep 3389

Interestingly, on boot up, the xrdp.service failed to start, so I tried starting it by hand and it failed the FIRST (on boot) / SECOND (manual). However, on the third time, it stayed running unlike the other 18.04 machine where it didn't matter how many times I restarted.

Here's the output of the FIRST manual start:
root@gladys-0009341:~# sudo systemctl start xrdp.service
A dependency job for xrdp.service failed. See 'journalctl -xe' for details.
root@gladys-0009341:~# sudo journalctl -xe
-- Defined-By: systemd 
-- Support: http://www.ubuntu.com/support
--
-- Unit UNIT has finished starting up.
--
-- The start-up result is RESULT.
Aug 17 20:12:10 gladys-0009341 systemd[8755]: Reached target Default.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd 
-- Support: http://www.ubuntu.com/support
--
-- Unit UNIT has finished starting up.
--
-- The start-up result is RESULT.
Aug 17 20:12:10 gladys-0009341 systemd[8755]: Startup finished in 48ms.
-- Subject: User manager start-up is now complete
-- Defined-By: systemd 
-- Support: http://www.ubuntu.com/support
--
-- The user manager instance for user 0 has been started. All services queued
-- for starting have been started. Note that other services might still be starting
-- up or be started at any later time.
--
-- Startup of the manager took 48192 microseconds.
Aug 17 20:12:10 gladys-0009341 systemd[1]: Started User Manager for UID 0.
-- Subject: Unit user@0.service has finished start-up
-- Defined-By: systemd 
-- Support: http://www.ubuntu.com/support
--
-- Unit user@0.service has finished starting up.
--
-- The start-up result is RESULT.
Aug 17 20:12:41 gladys-0009341 sudo[8920]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/bin/systemctl status xrdp
Aug 17 20:12:41 gladys-0009341 sudo[8920]: pam_unix(sudo:session): session opened for user root by root(uid=0)
Aug 17 20:12:41 gladys-0009341 sudo[8920]: pam_unix(sudo:session): session closed for user root
Aug 17 20:12:44 gladys-0009341 sudo[8934]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/bin/systemctl status xrdp-sesman
Aug 17 20:12:44 gladys-0009341 sudo[8934]: pam_unix(sudo:session): session opened for user root by root(uid=0)
Aug 17 20:12:44 gladys-0009341 sudo[8934]: pam_unix(sudo:session): session closed for user root
Aug 17 20:16:48 gladys-0009341 systemd[1]: Starting xrdp session manager...
-- Subject: Unit xrdp-sesman.service has begun start-up
-- Defined-By: systemd 
-- Support: http://www.ubuntu.com/support
--
-- Unit xrdp-sesman.service has begun starting up.
Aug 17 20:16:48 gladys-0009341 xrdp-sesman[9661]: (9661)(139757727249728)[DEBUG] libscp initialized
Aug 17 20:16:48 gladys-0009341 xrdp-sesman[9671]: (9671)(139757727249728)[INFO ] starting xrdp-sesman with pid 9671
Aug 17 20:16:48 gladys-0009341 xrdp-sesman[9661]: (9661)(139757727249728)[INFO ] IPv6 not supported, falling back to IPv4
Aug 17 20:16:49 gladys-0009341 xrdp-sesman[9671]: (9671)(139757727249728)[INFO ] IPv6 not supported, falling back to IPv4
Aug 17 20:16:49 gladys-0009341 xrdp-sesman[9661]: (9661)(139757727249728)[DEBUG] Testing if xrdp-sesman can listen on 127.0.0.1 port 3350.
Aug 17 20:16:49 gladys-0009341 xrdp-sesman[9671]: (9671)(139757727249728)[INFO ] listening to port 3350 on 127.0.0.1
Aug 17 20:16:49 gladys-0009341 xrdp-sesman[9661]: (9661)(139757727249728)[ERROR] bind_loopback(5, 3350) failed; IPv6 ::1 (errno=97), IPv4 127.0.0.1 (errno=98) and IPv6 ::FFFF:127.0.0.1 (errno=97).
Aug 17 20:16:49 gladys-0009341 xrdp-sesman[9661]: (9661)(139757727249728)[ERROR] Failed to start xrdp-sesman daemon, possibly address already in use.
Aug 17 20:16:49 gladys-0009341 systemd[1]: xrdp-sesman.service: Control process exited, code=exited status=1
Aug 17 20:16:49 gladys-0009341 xrdp-sesman[9671]: (9671)(139757727249728)[INFO ] shutting down sesman 1
Aug 17 20:16:49 gladys-0009341 xrdp-sesman[9671]: (9671)(139757727249728)[DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
Aug 17 20:16:49 gladys-0009341 systemd[1]: xrdp-sesman.service: Failed with result 'exit-code'.
Aug 17 20:16:49 gladys-0009341 systemd[1]: Failed to start xrdp session manager.
-- Subject: Unit xrdp-sesman.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit xrdp-sesman.service has failed.
-- 
-- The result is RESULT.
Aug 17 20:16:49 gladys-0009341 systemd[1]: Dependency failed for xrdp daemon.
-- Subject: Unit xrdp.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit xrdp.service has failed.
--
-- The result is RESULT.
Aug 17 20:16:49 gladys-0009341 systemd[1]: xrdp.service: Job xrdp.service/start failed with result 'dependency'.

THIRD time (2nd MANUAL start), it worked.
root@gladys-0009341:~# sudo systemctl start xrdp.service
root@gladys-0009341:~# sudo systemctl status xrdp-sesman
● xrdp-sesman.service - xrdp session manager
   Loaded: loaded (/lib/systemd/system/xrdp-sesman.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-08-17 20:17:41 PDT; 10s ago
     Docs: man:xrdp-sesman(8)
           man:sesman.ini(5)
  Process: 9831 ExecStart=/usr/sbin/xrdp-sesman $SESMAN_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 9841 (xrdp-sesman)
    Tasks: 1 (limit: 9830)
   CGroup: /system.slice/xrdp-sesman.service
           └─9841 /usr/sbin/xrdp-sesman

Aug 17 20:17:41 gladys-0009341 systemd[1]: Starting xrdp session manager...
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9831]: (9831)(139722110571840)[DEBUG] libscp initialized
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9841]: (9841)(139722110571840)[INFO ] starting xrdp-sesman with pid 9841
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9831]: (9831)(139722110571840)[INFO ] IPv6 not supported, falling back to IPv4
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9841]: (9841)(139722110571840)[INFO ] IPv6 not supported, falling back to IPv4
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9831]: (9831)(139722110571840)[DEBUG] Testing if xrdp-sesman can listen on 127.0.0.1 port 3350.
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9831]: (9831)(139722110571840)[DEBUG] Closed socket 5 (AF_INET 127.0.0.1:3350)
Aug 17 20:17:41 gladys-0009341 systemd[1]: Started xrdp session manager.
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9841]: (9841)(139722110571840)[INFO ] listening to port 3350 on 127.0.0.1

root@gladys-0009341:~# sudo systemctl status xrdp-sesman
● xrdp-sesman.service - xrdp session manager
   Loaded: loaded (/lib/systemd/system/xrdp-sesman.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-08-17 20:17:41 PDT; 25s ago
     Docs: man:xrdp-sesman(8)
           man:sesman.ini(5)
  Process: 9831 ExecStart=/usr/sbin/xrdp-sesman $SESMAN_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 9841 (xrdp-sesman)
    Tasks: 1 (limit: 9830)
   CGroup: /system.slice/xrdp-sesman.service
           └─9841 /usr/sbin/xrdp-sesman

Aug 17 20:17:41 gladys-0009341 systemd[1]: Starting xrdp session manager...
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9831]: (9831)(139722110571840)[DEBUG] libscp initialized
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9841]: (9841)(139722110571840)[INFO ] starting xrdp-sesman with pid 9841
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9831]: (9831)(139722110571840)[INFO ] IPv6 not supported, falling back to IPv4
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9841]: (9841)(139722110571840)[INFO ] IPv6 not supported, falling back to IPv4
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9831]: (9831)(139722110571840)[DEBUG] Testing if xrdp-sesman can listen on 127.0.0.1 port 3350.
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9831]: (9831)(139722110571840)[DEBUG] Closed socket 5 (AF_INET 127.0.0.1:3350)
Aug 17 20:17:41 gladys-0009341 systemd[1]: Started xrdp session manager.
Aug 17 20:17:41 gladys-0009341 xrdp-sesman[9841]: (9841)(139722110571840)[INFO ] listening to port 3350 on 127.0.0.1
root@gladys-0009341:~# netstat -nl|grep 3389
tcp        0      0 127.0.0.1:3389          0.0.0.0:*               LISTEN

To verify these results, I rebooted again and tried the same steps. Immediately after boot up, it failed to start. I tried several times and went away for a few minutes. After returning, I tried it again and this time it worked!

root@gladys-0009341:~# sudo systemctl status xrdp
● xrdp.service - xrdp daemon
   Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:xrdp(8)
           man:xrdp.ini(5)

Aug 17 20:30:24 gladys-0009341 systemd[1]: Dependency failed for xrdp daemon.
Aug 17 20:30:24 gladys-0009341 systemd[1]: xrdp.service: Job xrdp.service/start failed with result 'dependency'.
root@gladys-0009341:~# sudo systemctl status xrdp-sesman
● xrdp-sesman.service - xrdp session manager
   Loaded: loaded (/lib/systemd/system/xrdp-sesman.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-08-17 20:30:24 PDT; 1min 16s ago
     Docs: man:xrdp-sesman(8)
           man:sesman.ini(5)
  Process: 2398 ExecStart=/usr/sbin/xrdp-sesman $SESMAN_OPTIONS (code=exited, status=1/FAILURE)

Aug 17 20:30:22 gladys-0009341 xrdp-sesman[2488]: (2488)(140250580288832)[INFO ] IPv6 not supported, falling back to IPv4
Aug 17 20:30:22 gladys-0009341 xrdp-sesman[2398]: (2398)(140250580288832)[DEBUG] Testing if xrdp-sesman can listen on 127.0.0.1 port 3350.
Aug 17 20:30:22 gladys-0009341 xrdp-sesman[2488]: (2488)(140250580288832)[INFO ] listening to port 3350 on 127.0.0.1
Aug 17 20:30:23 gladys-0009341 xrdp-sesman[2398]: (2398)(140250580288832)[ERROR] bind_loopback(5, 3350) failed; IPv6 ::1 (errno=97), IPv4 127.0.0.1 (errno=98) and IPv6 ::FFFF:127.0.0.1 (errno=97).
Aug 17 20:30:23 gladys-0009341 xrdp-sesman[2398]: (2398)(140250580288832)[ERROR] Failed to start xrdp-sesman daemon, possibly address already in use.
Aug 17 20:30:24 gladys-0009341 systemd[1]: xrdp-sesman.service: Control process exited, code=exited status=1
Aug 17 20:30:24 gladys-0009341 xrdp-sesman[2488]: (2488)(140250580288832)[INFO ] shutting down sesman 1
Aug 17 20:30:24 gladys-0009341 xrdp-sesman[2488]: (2488)(140250580288832)[DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
Aug 17 20:30:24 gladys-0009341 systemd[1]: xrdp-sesman.service: Failed with result 'exit-code'.
Aug 17 20:30:24 gladys-0009341 systemd[1]: Failed to start xrdp session manager.

root@gladys-0009341:~# uptime
 20:31:54 up 2 min,  1 user,  load average: 1.49, 1.08, 0.44

-- Unit xrdp-sesman.service has begun starting up.
Aug 17 20:32:05 gladys-0009341 xrdp-sesman[4589]: (4589)(140533808633152)[DEBUG] libscp initialized
Aug 17 20:32:05 gladys-0009341 xrdp-sesman[4600]: (4600)(140533808633152)[INFO ] starting xrdp-sesman with pid 4600
Aug 17 20:32:05 gladys-0009341 xrdp-sesman[4589]: (4589)(140533808633152)[INFO ] IPv6 not supported, falling back to IPv4
Aug 17 20:32:05 gladys-0009341 xrdp-sesman[4600]: (4600)(140533808633152)[INFO ] IPv6 not supported, falling back to IPv4
Aug 17 20:32:05 gladys-0009341 xrdp-sesman[4589]: (4589)(140533808633152)[DEBUG] Testing if xrdp-sesman can listen on 127.0.0.1 port 3350.
Aug 17 20:32:06 gladys-0009341 xrdp-sesman[4600]: (4600)(140533808633152)[INFO ] listening to port 3350 on 127.0.0.1
Aug 17 20:32:06 gladys-0009341 xrdp-sesman[4589]: (4589)(140533808633152)[ERROR] bind_loopback(5, 3350) failed; IPv6 ::1 (errno=97), IPv4 127.0.0.1 (errno=98) and IPv6 ::FFFF:127.0.0.1 (errno=97).
Aug 17 20:32:06 gladys-0009341 xrdp-sesman[4589]: (4589)(140533808633152)[ERROR] Failed to start xrdp-sesman daemon, possibly address already in use.
Aug 17 20:32:06 gladys-0009341 systemd[1]: xrdp-sesman.service: Control process exited, code=exited status=1
Aug 17 20:32:06 gladys-0009341 xrdp-sesman[4600]: (4600)(140533808633152)[INFO ] shutting down sesman 1
Aug 17 20:32:06 gladys-0009341 xrdp-sesman[4600]: (4600)(140533808633152)[DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
Aug 17 20:32:06 gladys-0009341 systemd[1]: xrdp-sesman.service: Failed with result 'exit-code'.
Aug 17 20:32:06 gladys-0009341 systemd[1]: Failed to start xrdp session manager.
-- Subject: Unit xrdp-sesman.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit xrdp-sesman.service has failed.
-- 
-- The result is RESULT.
Aug 17 20:32:06 gladys-0009341 systemd[1]: Dependency failed for xrdp daemon.
-- Subject: Unit xrdp.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit xrdp.service has failed.
-- 
-- The result is RESULT.
Aug 17 20:32:06 gladys-0009341 systemd[1]: xrdp.service: Job xrdp.service/start failed with result 'dependency'.
Aug 17 20:32:06 gladys-0009341 sudo[4586]: pam_unix(sudo:session): session closed for user root
root@gladys-0009341:~# sudo systemctl start xrdp.service
A dependency job for xrdp.service failed. See 'journalctl -xe' for details.
root@gladys-0009341:~# sudo systemctl start xrdp.service
A dependency job for xrdp.service failed. See 'journalctl -xe' for details.
root@gladys-0009341:~# sudo systemctl start xrdp.service
A dependency job for xrdp.service failed. See 'journalctl -xe' for details.
root@gladys-0009341:~# sudo systemctl start xrdp.service
A dependency job for xrdp.service failed. See 'journalctl -xe' for details.
root@gladys-0009341:~# sudo systemctl start xrdp.service
root@gladys-0009341:~# date
Mon Aug 17 20:35:43 PDT 2020

Looks like the first machine (lovage) was on 18.04.4 while the second test machine that I could reboot as I pleased is running 18.04.5. However, they both had the same version of xrdp (0.9.5-2). It seems to take a while for xrdp to be able to successfully bind to the ipv4 interface. In this case, it took as long as 3+ minutes.

**Comment by matt335672** [comment]
Thanks for the thorough reporting - it's very useful indeed.

I think it's fair to say there's no problem with the `xrdp` executable. It looks like the problem is `xrdp-sesman` is failing to start most of the time and the systemd dependency tracking is then resulting in the `xrdp` executable not starting.

I reckon this is related to #988 which fixed a problem with 0.9.5, and which was released in 0.9.6. You're on Ubuntu 0.9.5-2 so won't have the fix for this problem. I think because you're only using one transport rather than two, there's a greatly increased chance of the race condition identified in #988 causing the `xrdp-sesman` listen to fail.

I can try raising a fault against 18.04 to backport the patch for #988, but this is likely to be a slow process and at this stage in the 18.04 lifecycle there aren't likely to be many new users who are coming across this. I can however offer you a workaround which appear to work on my VM (18.04.4, 2 cores).

The problem in #988 is caused by `xrdp-sesman` forking before it's performed a listen test. The workaround involves simply preventing `xrdp-sesman` from forking by starting it with the `-n` switch.

There's one other change we need to make. The systemd unit file for `xrdp-sesman` expects the process to fork at startup - it's configured with `Type=forking` in the unit manifest. If `xrdp-sesman` is no longer forking we need to override this and set `Type=simple`. 

Service types are explained in more detail in the manpage `systemd.service(5)`. Overrides are explained in `systemd.unit(5)` and there's also a pretty useful page at [askubuntu.com](https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services)

With all that explanation out of the way, can you please try the following on your machine `gladys-0009341`:-
- `sudo mkdir /etc/systemd/system/xrdp-sesman.service.d`
- Create a file `/etc/systemd/system/xrdp-sesman.service.d/issue1652.conf` with the following contents:-
   ```ini
   [Service]
   Type=simple
   ExecStart=
   ExecStart=/usr/sbin/xrdp-sesman -n $SESMAN_OPTIONS
   ```
- `sudo systemctl daemon-reload`

I think that should get us a bit further.

Incidentally, the blank `ExecStart=` line is needed above as otherwise systemd will try to use the `ExecStart` setting from both files. This is explained in `systemd.unit(5)` round about line 1243 on your system.

Feel fre to come back to me on any of this if it doesn't make any sense. Hopefully however it will get us a bit further.

**Comment by quang777** [comment]
Thanks @matt335672, that seems to have worked. After putting in the override and rebooting, it started up on boot up this time. BTW, is the systemd start up supposed to restart the service if it dies? On another machine (16.04), when the xrdp service dies, it doesn't auto restart. Is that normal?

**Comment by matt335672** [comment]
You'll need to add `Restart=` to the systemd unit file for that. From `systemd.service)(5)` for 18.04 with some bits removed:-

```
       Restart=
           Configures whether the service shall be restarted when the service
           process exits, is killed, or a timeout is reached.
           . . .
           Takes one of no, on-success, on-failure, on-abnormal, on-watchdog,
           on-abort, or always. If set to no (the default), the service will
           not be restarted.
           .  . 
```

So yes it is normal, but you can override it by using the mechanisms which we've used above. That is, of course, assuming that all this is supported on 16.04. I don't have a copy installed which I can consult. You'll need to investigate that.

Are you happy with that? Can I close this issue now? Or feel free to close it yourself.

**Comment by quang777** [comment]
Thanks @matt335672 !

**Comment by stayprivate** [comment]
The  Type=Simple and -n option has solve the problem for me (Ubuntu 18.04). Thanks!

**Comment by cheekykite** [comment]
This solved my problem too, thank you. (Ubuntu 18.04)
