### ISSUE TITLE
Access gnome instead of xfce Ubuntu 18.04

### ISSUE THREAD

**Issue by mascenzi80** [neutrinolabs/xrdp#1655]
Hi, 

I want to access the gnome desktop on a TX2 instead of the xfce on Ubuntu 18.04 from my windows pc. I was able to accomplish this on a different tx2 board running ubuntu 16, but the same configuration on the new tx2 board, defaults to xfce. I purged xfce, but now it doesn't connect to the board at all. Any suggestions?

After installing xrdp, I attempt to log in with the xorg option and I see the NVIDIA screen, and then it boots me right out. X11rdp just sits on the blue xrdp screen doing nothing. Xvnc shows the connection log and gives me an error. 
![image](https://user-images.githubusercontent.com/18700156/90632704-d6c82e80-e1f2-11ea-8043-7c95999a20f0.png)

**Comment by matt335672** [comment]
Hi @mascenzi80 

You're going to have significant issues with a TX2 and GNOME I'm afraid, which is possibly why the default is XFCE. GNOME requires 3D acceleration and on the TX2 with the NVidia software set this doesn't actually seem to be possible for remote desktops.

This is discussed in #721 and #1582. The latter one of these has a link to the NVidia developers' forum where I've raised this. I suggest you have a look #1582 in particular.

**Comment by mascenzi80** [comment]
Hi @matt335672,

Thats interesting and bit disappointing. I wonder what occurred between the upgrad from jetback 3.3 to 4.3, that it no longer is possible.

**Comment by matt335672** [comment]
I've no idea I'm afraid as it's not hardware I have any experience with. It's a pity that the post I'd made to the developers' forum has not attracted more interest or comment but as I don't have a TX2 or similar, it would in any case be tricky for me to contribute further!

XFCE (and many other desktops) should however be fine provided you don't want to run any accelerated applications in the remote session.
