### ISSUE TITLE
RemoteFX USB device redirection

### ISSUE THREAD

**Issue by matthewdva** [neutrinolabs/xrdp#1656]
Is RemoteFX usb device redirections supposed to work?  I am trying to redirect a USB device (Android ADB device) from W10 to CentOS.  The redirection works correctly Win10 -> Win10 but not Win10-> CentOS.  I am not clear if RemoteFX USB redirection is supposed to work.

I have referred to [issue #722](https://github.com/neutrinolabs/xrdp/issues/722).  I do see in the logs where rfx_codec is loading and starting.  However I still do not see the usb device on the remote system.

If usb device redirection is supported I could use guidance troubleshooting the issue.

**Comment by Slugger2k** [comment]
Same Problem here!

**Comment by metalefty** [comment]
RemoteFX is originally a codec name to compress display bitmap. It doesn’t include USB redirection. 

RemoteFX USB is a commercial naming which is different from RemoteFX.
