### ISSUE TITLE
Xrdp install on OSX mavericks 

### ISSUE THREAD

**Issue by tomoso** [neutrinolabs/xrdp#166]
i'm make & install success..
but login failed when i connect it with Microsoft Remote Desktop Client ,

the connection log: 

connecting to sesman ip 127.0.0.1 port 3350
sesman connect ok
sending login info to session manager , please wait ...
xrdp_mm_process_login_response:login failed

**Comment by proski** [comment]
Please try this for `/etc/pam.d/xrdp-sesman`:
```
# xrdp-sesman: auth account password session
auth       required       pam_opendirectory.so
account    required       pam_opendirectory.so
password   required       pam_opendirectory.so
session    required       pam_permit.so
```
This is not a compile issue, by the way.

**Comment by metalefty** [comment]
The pam config introduced by proski should work, closing.
