### ISSUE TITLE
Proposal: Allow token sign in without autologon for SSO

### ISSUE THREAD

**Issue by bolkedebruin** [neutrinolabs/xrdp#1667]
**Challenge**

RDP files do not allow storing for passwords that are set by the server. This limits single sign on possibilities without NLA. So for example if you use a remote desktop gateway (like, shameless plug, https://github.com/bolkedebruin/rdpgw) which creates a downloadable RDP file you cannot make this single sign on at the moment.

**Proposed solution**
If a "enable_token_login" is specified in the config file and a ASCII record separator character is detected everything before the separator is considered to be the username and everything after the separator is considered to be the authentication token (like JWT). So something like

bolke|JWT_TOKEN

At logon time the username is scanned and if the ASCII record separator is found the token is copied over to the password and the username is set to everything before the separator.

Copying the token to the password very early in the provess ensures that the password does not get accidentally logged. Detection is also important to ensure a login attempt does not get triggered without cause and users do not get locked out. 

Of course an alternative separator (character or string) can be used, but not that the username string is limited to 511 characters.

I have a working solution.

what do you thing @matt335672 @metalefty @jsorg71 ?

**Comment by matt335672** [comment]
As a workaround for your particular use case it sounds OK to me.

I think it's important it's disabled by default otherwise we'll be encouraging users to store passwords in .ini files which won't go down well with enterprise security departments.

**Comment by bolkedebruin** [comment]
@matt335672 that makes sense. The linked PR is doing exactly that. Do you mind reviewing it?

**Comment by matt335672** [comment]
Since we've merged the PR, I'll close this.
