### ISSUE TITLE
black screen with green block

### ISSUE THREAD

**Issue by okhowang** [neutrinolabs/xrdp#1674]
I use xorgxrdp 0.2.14 with xrdp 0.9.14.
and got this.
![image](https://user-images.githubusercontent.com/3352585/91926302-8cbe6d00-ed09-11ea-9d91-9922bde749d8.png)
I try locate bug with `git bisect`.
and got [this commit](https://github.com/neutrinolabs/xrdp/commit/5cd36c511cab76ae4a7c14a792055449077e4fc1) lead the bug.
I also notice there are some error in `.xorgxrdp.*.log`
![image](https://user-images.githubusercontent.com/3352585/91926503-fa6a9900-ed09-11ea-9771-961bac124696.png)

**Comment by matt335672** [comment]
Hi @okhowang 

It's highly likely I think that your xorgxrdp isn't the right version. A couple of other users have seen this, and it came down to a mismatch between the version of xrdp and xorgxrdp.

The commit you've identified with your bisect introduced a necessary change to xorgxrdp, and so for v0.9.14 you must definitely be running the latest one. See [this discussion](https://github.com/neutrinolabs/xrdp/pull/1653#pullrequestreview-471163988) for more info. You might have to click on the 'Show resolved' button next to `common/xrdp_client_info.h` to see the detail.

Can you double-check you are running 0.2.14 of xorgxrdp? It's not easy to do this as it doesn't seem to log its version anywhere I can see at the moment. Maybe I'm missing it.

**Comment by metalefty** [comment]
Can you make sure rebuild xorgxrdp against xrdp v0.9.14. 

xrdp_client_info structure has been changed.  So there might be structure mismatch between xrdp and xorgxrdp.

**Comment by okhowang** [comment]
I rebuild xorgxrdp with latest xrdp header, and It's OK.
Thank you
