### ISSUE TITLE
migrate travis CI builds from .org to .com

### ISSUE THREAD

**Issue by aquesnel** [neutrinolabs/xrdp#1683]
Problem:

The Travis CI in-progress builds don't get displayed on github commit or pull request page until the build is complete. This has changed in recent months. I believe that this is because the nutrinolabs/xrdp repository is using the legacy travis-ci.org integration. 

There is [TravisCI documentation for migrating](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) open source projects from travis-ci.org to travis-ci.com and integrating with github via GitHub actions.

The TravisCI migration docs says that it's still in Beta, but the migration seems to have been in progress since 2018, so it's likely safe to migrate.
I have followed the instructions for migrating the `aquesnel/xrdp` repository to travis-ci.com and it solved the github integration problem. See example build: https://github.com/aquesnel/xrdp/runs/1088065752

**Comment by metalefty** [comment]
Looks nice. I didn't know that.

**Comment by aquesnel** [comment]
Apparently I was wrong about the travis CI builds not displaying in github only while the build is in progress. It appears instead that the build never gets linked to triggering commit or pull request even tough the build is still triggered.

Example commit that triggered a travis CI build but is not displayed on the github UI
* github commit: https://github.com/neutrinolabs/xrdp/pull/1633/commits/8c5d4c4337b91debf4f11a9d5de202603a72b6c0
* travis CI build: https://travis-ci.org/github/neutrinolabs/xrdp/builds/726144015

Also, I had forgotten to mention in my original comment, that the migration of the `aquesnel/xrdp` repository from travis-ci.org to travis-ci.com did not require any code changes. The migration does require that an administrator of the `neutrinolabs/xrdp` repository connect the repository to a travis-ci.com (free open-source) account.

**Comment by matt335672** [comment]
I'll close this one now we've moved to GitHub actions - it's been somewhat overtaken by events.
