### ISSUE TITLE
Ubuntu 20.04 - No sound - Compilation error

### ISSUE THREAD

**Issue by gamersalpha** [neutrinolabs/xrdp#1698]
Hello so i follow this ticket closed : 

https://github.com/neutrinolabs/xrdp/issues/1564

and i try this how to : 
https://github.com/matt335672/xrdp/wiki/README

And i m stuck at this line : 

```
issa@issa-Standard-PC-i440FX-PIIX-1996:~$ sudo apt build-dep pulseaudio
[sudo] Mot de passe de issa :
Lecture des listes de paquets... Fait
E: You must put some 'deb-src' URIs in your sources.list
issa@issa-Standard-PC-i440FX-PIIX-1996:~$
```

what do u think please ?

**Comment by matt335672** [comment]
Hi @gamersalpha 

Thanks for trying the instructions.

I'll build a clean VM and try them here. Then I can update the instructions and I'll let you know what I've missed out.

**Comment by matt335672** [comment]
I've updated [https://github.com/matt335672/xrdp/wiki/README](https://github.com/matt335672/xrdp/wiki/README)

The original instructions were for Debian, but I've updated them for Ubuntu as well. The extra bits I've added are at the end of this message.

Please let us know how you get on, or whether I've not been clear.

Thanks

# Extra Instructions (for Ubuntu)
## Source repositories
Edit `/etc/apt/sources.list` and make sure these two lines are uncommented:-

```
deb-src http://<path-to-mirror>/ <distro> main restricted
deb-src http://<path-to-mirror> <distro>-updates main restricted
```

Depending on your location and your exact operating system, `<path-to-mirror>` and `<distro>` will have different values.

After doing the above enter `sudo apt update` to load the contents of the new repositories.

## Build and development tools
In addition to the tools you've already installed, you'll need `git`:-

```bash
sudo apt install -y git
```

**Comment by zachh83** [comment]
I get to the make command, and then the comp fails.

~/src/pulseaudio-module-xrdp$ make
make  all-recursive
make[1]: Entering directory '/home/dad/src/pulseaudio-module-xrdp'
Making all in src
make[2]: Entering directory '/home/dad/src/pulseaudio-module-xrdp/src'
  CC       module_xrdp_sink_la-module-xrdp-sink.lo
module-xrdp-sink.c:26:10: fatal error: config.h: No such file or directory
   26 | #include <config.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:481: module_xrdp_sink_la-module-xrdp-sink.lo] Error 1
make[2]: Leaving directory '/home/dad/src/pulseaudio-module-xrdp/src'
make[1]: *** [Makefile:418: all-recursive] Error 1
make[1]: Leaving directory '/home/dad/src/pulseaudio-module-xrdp'
make: *** [Makefile:350: all] Error 2


Thoughts?

**Comment by zachh83** [comment]
Question.

I already have pulseaudio installed on ubuntu cinnamon when I run the command pulseaudio --version. 
With that being said, would that change anything from the walkthrough?

I followed it step by step, and am still getting no results. It still says dummy output when I RD into my VM.

**Comment by matt335672** [comment]
Have a look at #1842 and [my comment](https://github.com/neutrinolabs/xrdp/issues/1842#issuecomment-809384363) there about `systemd --user`.

**Comment by zachh83** [comment]
It does seem that that was the issue. I ran a pulseaudio -k and it fixed it. I put it into my system startup as a command to run. Hopefully that will be fine for the life of the system!

Thanks!
