### ISSUE TITLE
cannot rdp to linux workstation any more, get this error X server -- no display in range is available

### ISSUE THREAD

**Issue by tonyguadagno** [neutrinolabs/xrdp#1699]
hi, one day, I was unable to rdp to my linux workstation any more... after doing some research i see this might be the issue
[https://github.com/neutrinolabs/xrdp/issues/866](866)
but I get the impression that this was fixed.  When I increase my max session from 50 to 80 in sesman.ini, it works again.  There seems to be a script that will delete the stale sockets, but it does not work because it expects them to be in /tmp/.xrdp and that folder does not exist on my CenOS 7 computer.  if its a matter of deleting files, I can do that, but where are they?

Has this issue been fixed, I am on the latest 0.9.14, or, where are the files I should delete?

thanks in advance!

here are my log excerpts

xrdp-sesman.log
> [20201012-09:42:32] [INFO ] shutting down sesman 1
> [20201012-09:42:32] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
> [20201012-09:42:32] [DEBUG] libscp initialized
> [20201012-09:42:32] [INFO ] starting xrdp-sesman with pid 9756
> [20201012-09:42:32] [INFO ] listening to port 3350 on 127.0.0.1
> [20201012-09:42:55] [INFO ] A connection received from 127.0.0.1 port 37360
> [20201012-09:42:56] [INFO ] ++ created session (access granted): username tonyg, ip 10.1.1.40:63572 - socket: 12
> [20201012-09:42:56] [INFO ] starting Xvnc session...
> [20201012-09:42:56] [ERROR] X server -- no display in range is available
> [20201012-09:42:56] [DEBUG] Closed socket 9 (AF_INET 127.0.0.1:3350)

xrdp.log
> [20201012-09:42:32] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)
> [20201012-09:42:32] [DEBUG] Closed socket 12 (AF_INET 10.50.32.42:3389)
> [20201012-09:42:32] [DEBUG] xrdp_mm_module_cleanup
> [20201012-09:42:32] [INFO ] starting xrdp with pid 9757
> [20201012-09:42:32] [INFO ] address [0.0.0.0] port [3389] mode 1
> [20201012-09:42:32] [INFO ] listening to port 3389 on 0.0.0.0
> [20201012-09:42:32] [INFO ] xrdp_listen_pp done
> [20201012-09:42:49] [INFO ] Socket 12: AF_INET connection received from 10.1.1.40 port 63571
> [20201012-09:42:49] [DEBUG] Closed socket 12 (AF_INET 10.50.32.42:3389)
> [20201012-09:42:49] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)
> [20201012-09:42:49] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
> [20201012-09:42:49] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
> [20201012-09:42:49] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
> [20201012-09:42:49] [DEBUG] TLSv1.2 enabled
> [20201012-09:42:49] [DEBUG] Security layer: requested 11, selected 1
> [20201012-09:42:50] [DEBUG] Closed socket 12 (AF_INET 10.50.32.42:3389)
> [20201012-09:42:50] [INFO ] Socket 12: AF_INET connection received from 10.1.1.40 port 63572
> [20201012-09:42:50] [DEBUG] Closed socket 12 (AF_INET 10.50.32.42:3389)
> [20201012-09:42:50] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)
> [20201012-09:42:50] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
> [20201012-09:42:50] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
> [20201012-09:42:50] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
> [20201012-09:42:50] [DEBUG] TLSv1.2 enabled
> [20201012-09:42:50] [DEBUG] Security layer: requested 11, selected 1
> [20201012-09:42:50] [INFO ] connected client computer name: USGBS-IT-LT05
> [20201012-09:42:50] [INFO ] adding channel item name rdpdr chan_id 1004 flags 0x80800000
> [20201012-09:42:50] [INFO ] adding channel item name rdpsnd chan_id 1005 flags 0xc0000000
> [20201012-09:42:50] [INFO ] adding channel item name cliprdr chan_id 1006 flags 0xc0a00000
> [20201012-09:42:50] [INFO ] adding channel item name drdynvc chan_id 1007 flags 0xc0800000
> [20201012-09:42:50] [INFO ] TLS connection established from 10.1.1.40 port 63572: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
> [20201012-09:42:51] [DEBUG] xrdp_00002643_wm_login_mode_event_00000001
> [20201012-09:42:51] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
> [20201012-09:42:51] [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
> [20201012-09:42:55] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
> [20201012-09:42:55] [INFO ] xrdp_wm_log_msg: sesman connect ok
> [20201012-09:42:56] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
> [20201012-09:42:56] [DEBUG] return value from xrdp_mm_connect 0
> [20201012-09:42:56] [INFO ] xrdp_wm_log_msg: login failed for display 0
> [20201012-09:42:56] [DEBUG] xrdp_mm_module_cleanup
> [20201012-09:42:56] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:37360)

**Comment by matt335672** [comment]
Hi @tonyguadagno 

It's possible that stale chansrv sockets are causing your issue, but there could be other things too.

The sockets directory was moved to from `/tmp/.xrdp` to `/run/xrdp` for EPEL XRDP 0.9.13-2 by Red Hat engineering to fix [BZ#1834178](https://bugzilla.redhat.com/show_bug.cgi?id=1834178) (reported as #1482 on our side).

When this happens, could you enter the following commands? This will let us determine why `sesman` is unable to find a slot for the X server:-

```
ls /tmp/.X11-unix/X* /tmp/.X*-lock /run/xrdp/*
ss -ltn
```

Thanks

**Comment by tonyguadagno** [comment]
hi, thanks for responding.  right now, with max set to 80, the user is able to rdp.  this is the results of the commands right now

> [root@linuxeafafe xrdp]# ls /tmp/.X11-unix/X* /tmp/.X*-lock /run/xrdp/*
> ls: cannot access /run/xrdp/*: No such file or directory
> /tmp/.X0-lock        /tmp/.X11-unix/X22  /tmp/.X11-unix/X38  /tmp/.X11-unix/X53
> /tmp/.X11-unix/X0    /tmp/.X11-unix/X23  /tmp/.X11-unix/X39  /tmp/.X11-unix/X54
> /tmp/.X11-unix/X1    /tmp/.X11-unix/X24  /tmp/.X11-unix/X4   /tmp/.X11-unix/X55
> /tmp/.X11-unix/X10   /tmp/.X11-unix/X25  /tmp/.X11-unix/X40  /tmp/.X11-unix/X56
> /tmp/.X11-unix/X11   /tmp/.X11-unix/X26  /tmp/.X11-unix/X41  /tmp/.X11-unix/X57
> /tmp/.X11-unix/X117  /tmp/.X11-unix/X27  /tmp/.X11-unix/X42  /tmp/.X11-unix/X58
> /tmp/.X11-unix/X12   /tmp/.X11-unix/X28  /tmp/.X11-unix/X43  /tmp/.X11-unix/X59
> /tmp/.X11-unix/X13   /tmp/.X11-unix/X29  /tmp/.X11-unix/X44  /tmp/.X11-unix/X6
> /tmp/.X11-unix/X14   /tmp/.X11-unix/X3   /tmp/.X11-unix/X45  /tmp/.X11-unix/X60
> /tmp/.X11-unix/X15   /tmp/.X11-unix/X30  /tmp/.X11-unix/X46  /tmp/.X11-unix/X61
> /tmp/.X11-unix/X16   /tmp/.X11-unix/X31  /tmp/.X11-unix/X47  /tmp/.X11-unix/X62
> /tmp/.X11-unix/X17   /tmp/.X11-unix/X32  /tmp/.X11-unix/X48  /tmp/.X11-unix/X7
> /tmp/.X11-unix/X18   /tmp/.X11-unix/X33  /tmp/.X11-unix/X49  /tmp/.X11-unix/X8
> /tmp/.X11-unix/X19   /tmp/.X11-unix/X34  /tmp/.X11-unix/X5   /tmp/.X11-unix/X9
> /tmp/.X11-unix/X2    /tmp/.X11-unix/X35  /tmp/.X11-unix/X50
> /tmp/.X11-unix/X20   /tmp/.X11-unix/X36  /tmp/.X11-unix/X51
> /tmp/.X11-unix/X21   /tmp/.X11-unix/X37  /tmp/.X11-unix/X52
> [root@linuxeafafe xrdp]# ss -ltn
> State      Recv-Q Send-Q Local Address:Port               Peer Address:Port                     
> LISTEN     0      128          *:38832                    *:*
> LISTEN     0      128          *:10000                    *:*
> LISTEN     0      5      192.168.122.1:53                       *:*                             
> LISTEN     0      2      127.0.0.1:3350                     *:*                                 
> LISTEN     0      128          *:22                       *:*
> LISTEN     0      64     127.0.0.1:31415                    *:*                                 
> LISTEN     0      128    127.0.0.1:631                      *:*                                 
> LISTEN     0      100          *:25                       *:*
> LISTEN     0      64     127.0.0.1:31515                    *:*                                 
> LISTEN     0      2            *:3389                     *:*
> LISTEN     0      128          *:9443                     *:*
> LISTEN     0      128       [::]:22                    [::]:*
> LISTEN     0      64       [::1]:31415                 [::]:*
> LISTEN     0      128      [::1]:631                   [::]:*
> LISTEN     0      100       [::]:25                    [::]:*
> LISTEN     0      64       [::1]:31515                 [::]:*
> LISTEN     0      50        [::]:3141                  [::]:*
>

**Comment by matt335672** [comment]
You seem to have a lot of X servers running, but no chansrv processes.

Are your users running captive `Xvnc` or `Xnest` processes for build purposes, etc?

What do you get from these commands?

```
/usr/sbin/xrdp --version
ps -ef | grep X
```

Thanks.

**Comment by tonyguadagno** [comment]
hi, we are using xrdp from the centos repo's, we are not building.

> [root@linuxeafafe ~]# /usr/sbin/xrdp --version
> xrdp 0.9.14
>   A Remote Desktop Protocol Server.
>   Copyright (C) 2004-2018 Jay Sorg, Neutrino Labs, and all contributors.
>   See https://github.com/neutrinolabs/xrdp for more information.
> 
>   Configure options:
>       --build=x86_64-redhat-linux-gnu
>       --host=x86_64-redhat-linux-gnu
>       --program-prefix=
>       --disable-dependency-tracking
>       --prefix=/usr
>       --exec-prefix=/usr
>       --bindir=/usr/bin
>       --sbindir=/usr/sbin
>       --sysconfdir=/etc
>       --datadir=/usr/share
>       --includedir=/usr/include
>       --libdir=/usr/lib64
>       --libexecdir=/usr/libexec
>       --localstatedir=/var
>       --sharedstatedir=/var/lib
>       --mandir=/usr/share/man
>       --infodir=/usr/share/info
>       --enable-fuse
>       --enable-pixman
>       --enable-painter
>       --enable-vsock
>       --with-socketdir=/run/xrdp
>       build_alias=x86_64-redhat-linux-gnu
>       host_alias=x86_64-redhat-linux-gnu
>       CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic
>       LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
>       PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig
> 
>   Compiled with OpenSSL 1.0.2k-fips  26 Jan 2017
> [root@linuxeafafe ~]# ps -ef | grep X
> user.user+   318 32745  0 Oct13 pts/3    00:02:01 /home/domain/user.user/Xilinx/Vivado/2018.1/bin/unwrapped/lnx64.o/vivado -mode tcl -source /tmp/sysgentmp-user.user/31156//tmp_376436726f.tcl
> root      1023     1  0 Oct12 ?        00:00:00 /usr/bin/abrt-watch-log -F Backtrace /var/log/Xorg.0.log -- /usr/bin/abrt-dump-xorg -xD
> root      1852  1508  0 Oct12 tty1     00:15:49 /usr/bin/X :0 -background none -noreset -audit 4 -verbose -auth /run/gdm/auth-for-gdm-dSR8Sk/database -seat seat0 -nolisten tcp vt1
> root     10693 10557  0 10:29 pts/6    00:00:00 grep --color=auto X
> user.user+ 23486 23034  0 08:03 pts/5    00:00:00 /bin/bash /home/domain/user.user/Xilinx/Vivado/2018.1/bin/vivado rpc_design_zu15eg.xpr
> user.user+ 23508 23486  0 08:03 pts/5    00:00:00 /bin/bash /home/domain/user.user/Xilinx/Vivado/2018.1/bin/loader -exec vivado rpc_design_zu15eg.xpr
> user.user+ 23549 23508 18 08:03 pts/5    00:26:37 /home/domain/user.user/Xilinx/Vivado/2018.1/bin/unwrapped/lnx64.o/vivado rpc_design_zu15eg.xpr
> user.user+ 26220 26216  0 Oct13 pts/2    00:00:00 /bin/bash /home/domain/user.user/Xilinx/Vivado/2018.1/bin/vivado -mode batch -source s_prj_open_gui_no_reset_project.tcl
> user.user+ 26242 26220  0 Oct13 pts/2    00:00:00 /bin/bash /home/domain/user.user/Xilinx/Vivado/2018.1/bin/loader -exec vivado -mode batch -source s_prj_open_gui_no_reset_project.tcl
> user.user+ 26283 26242 16 Oct13 pts/2    04:32:35 /home/domain/user.user/Xilinx/Vivado/2018.1/bin/unwrapped/lnx64.o/vivado -mode batch -source s_prj_open_gui_no_reset_project.tcl
> user.user+ 31156 31152  8 Oct13 pts/3    02:13:42 /home/domain/user.user/.XILINX_MATLAB_RUNTIME/GCC62/SG_2018.1_R2017b/MATLAB -r addpath('/home/domain/user.user/Xilinx/Vivado/2018.1/lib/lnx64.o/matlab');addpath('/home/domain/user.user/Xilinx/Vivado/2018.1/scripts/sysgen/matlab');addpath('/home/domain/user.user/Xilinx/Vivado/2018.1/scripts/sysgen/matlab/plugins/compilation');addpath('/home/domain/user.user/Xilinx/Vivado/2018.1/examples/sysgen_demos');javaaddpath('/home/domain/user.user/Xilinx/Vivado/2018.1/lib/classes/sysgen.jar');disp(['Type <a href=' char(34) 'matlab:xlDoc' char(34) '>xlDoc</a> to open the Xilinx System Generator help documentation.']);disp(['Type <a href=' char(34) 'matlab:demo blockset xilinx' char(34) '>demo blockset xilinx</a> to view the demos available for Xilinx System Generator.']);xlTip;
> user.user+ 32641     1  0 Oct13 pts/0    00:00:00 /bin/bash /home/domain/user.user/Xilinx/Vivado/2018.1/bin/vivado -mode tcl -notrace -nolog -nojou -source /home/domain/user.user/Xilinx/Vivado/2018.1/scripts/sysgen/tcl/SgWaveformServer.tcl -tclargs librdi_dsp_tcltasks.so /home/domain/user.user/Xilinx/Vivado/2018.1/scripts/sysgen/tcl/SgPaSlaveInterp.tcl 31156
> user.user+ 32663 32641  0 Oct13 pts/0    00:00:00 /bin/bash /home/domain/user.user/Xilinx/Vivado/2018.1/bin/loader -exec vivado -mode tcl -notrace -nolog -nojou -source /home/domain/user.user/Xilinx/Vivado/2018.1/scripts/sysgen/tcl/SgWaveformServer.tcl -tclargs librdi_dsp_tcltasks.so /home/domain/user.user/Xilinx/Vivado/2018.1/scripts/sysgen/tcl/SgPaSlaveInterp.tcl 31156
> user.user+ 32704 32663  0 Oct13 pts/0    00:00:19 /home/domain/user.user/Xilinx/Vivado/2018.1/bin/unwrapped/lnx64.o/vivado -mode tcl -notrace -nolog -nojou -source /home/domain/user.user/Xilinx/Vivado/2018.1/scripts/sysgen/tcl/SgWaveformServer.tcl -tclargs librdi_dsp_tcltasks.so /home/domain/user.user/Xilinx/Vivado/2018.1/scripts/sysgen/tcl/SgPaSlaveInterp.tcl 31156
> user.user+ 32721 31156  0 Oct13 pts/3    00:00:00 /bin/sh /home/domain/user.user/Xilinx/Vivado/2018.1/scripts/sysgen/vivado_shmem.sh /tmp/sysgentmp-user.user/31156//tmp_376436726f.tcl SharedMemory 31156 -release sgproxy31156_5f85901c
> user.user+ 32723 32721  0 Oct13 pts/3    00:00:00 /bin/bash /home/domain/user.user/Xilinx/Vivado/2018.1/bin/vivado -mode tcl -source /tmp/sysgentmp-user.user/31156//tmp_376436726f.tcl
> user.user+ 32745 32723  0 Oct13 pts/3    00:00:00 /bin/bash /home/domain/user.user/Xilinx/Vivado/2018.1/bin/loader -exec vivado -mode tcl -source /tmp/sysgentmp-user.user/31156//tmp_376436726f.tcl
>

**Comment by matt335672** [comment]
Thanks.

It's still not clear (to me at least) what processes are listening on those X11 sockets.

I've created a [bash script](https://gist.github.com/matt335672/949b3027292e2fe0f6fe8c96ff7be68b) to try to figure this out. The raw version is here:-

[https://gist.githubusercontent.com/matt335672/949b3027292e2fe0f6fe8c96ff7be68b/raw/a1391bc8c24fd666cc7d8adfce7c6429f0f77211/socks.sh](https://gist.githubusercontent.com/matt335672/949b3027292e2fe0f6fe8c96ff7be68b/raw/a1391bc8c24fd666cc7d8adfce7c6429f0f77211/socks.sh)

Could you get that on to your system and run it? There's a `sudo` call in it, so please satisfy yourself that it's OK to do so.

**Comment by tonyguadagno** [comment]
> [root@lasdf tmp]# sudo ./x
> UID        PID  PPID  C STIME TTY          TIME CMD
> root      1852  1508  0 Oct12 tty1     00:25:21 /usr/bin/X :0 -background none -noreset -audit 4 -verbose -auth /r

**Comment by matt335672** [comment]
To summarise:-
- it looks like you've got a load of stale X sockets which have been created at some stage (presumably by an X server) but are no longer being used.
- while scanning for an X server number, `sesman` skips these slots as it appears they are in use.

What are the time on these sockets in /tmp? Do they pre-date the last system boot time? In other words, what is the output of these commands:-

```
ls -lt /tmp/.X11-unix/
who -b
```

I can't think of anything other than an X server which would create these sockets. X servers are normally pretty good at clearing up after themselves, so all I can think is that the machine is being reset while they are active.

**Comment by matt335672** [comment]
Hi Tony - do you need any more help with this?

**Comment by dgassen** [comment]
This issue lead me to an extra step to fix my issue running on WSL2 with xrdp. Needed to delete lock files in /tmp also.

was getting this is /var/log/ xrdp-sesman.log
[20230419-10:29:00] [ERROR] X server -- no display in range is available

found these files in /tmp as well
derek@htsocorro:tmp$ ll .X*-lock
-r--r--r-- 1 derek derek 11 Nov 12  2021 .X10-lock
-r--r--r-- 1 derek derek 11 Nov 12  2021 .X11-lock
-r--r--r-- 1 derek derek 11 Nov 27  2021 .X12-lock
-r--r--r-- 1 derek derek 11 Nov 27  2021 .X13-lock
-r--r--r-- 1 derek derek 11 Nov 27  2021 .X14-lock
<snip.>
removed all of them
derek@htsocorro:tmp$ rm .X*-lock

bounced ubuntu, i.e., wsl --shutdown

Log messages in /var/log/xrdp-sesman.log look good
[20230419-10:33:29] [INFO ] starting xrdp-sesman with pid 121
[20230419-10:33:29] [INFO ] listening to port 3350 on 127.0.0.1

After that Remotedesktop is able to use xrdp and login to x11.
