### ISSUE TITLE
TLS tasks

### ISSUE THREAD

**Issue by speidy** [neutrinolabs/xrdp#170]
- [x] negotiation of client compatible sec layer is broken (security_layer=negotiate)
- [x] ssl_shutdown shouldn't be called
- [ ] Jay's change for "none" security in xrdp_sec assumes that client shouldn't advertise any encryption method, however when using mstsc with tls mode, mstsc still sends all encryption methods.
- [x]  xrdp_rdp_recv should be changed for fastpath with tls mode support (maybe move it to xrdp_fastpath)
- [ ] implement TLS direct approach 
- [x] support certificate chains

**Comment by metalefty** [comment]
How's it going about else issues?

**Comment by bantu** [comment]
Is it possible to notify xrdp to reload the certificate and key from the filesystem or does xrdp automatically pick up new certificates/keys like e.g. postfix? If not, you may want to consider adding that as a task.

**Comment by metalefty** [comment]
@bantu IIRC, xrdp should always read certificates per access.

**Comment by metalefty** [comment]
I think this can be closed now.
