### ISSUE TITLE
[Just question] xrdp performance rely on CPU or GPU?

### ISSUE THREAD

**Issue by jjasoncool** [neutrinolabs/xrdp#1719]
As the title question, because I tested xrdp is delayed, but the network bandwidth is sufficient, if I need to improve the performance of the host, should I use a high-end CPU or GPU?

Current CPU: INTEL E3 1230 v6 GPU: gt1030

 Thank you.

**Comment by drewer** [comment]
It depends on various factors. For example if you are using glamor with rfx the network bandwidth is the problem with more than 350MBit per second. Without glamor, a 16 core CPU can be used to 100% with one user. The egfx branch with avc444 and glamor is the best ... very little CPU usage and 2-5 Mbit bandwidth

downside are some freeze or studdering all 30 sec on videos/youtube ... (and choppy sound)...but for office work its good enough...
