### ISSUE TITLE
xrdp failed for display 0

### ISSUE THREAD

**Issue by huanjoyous** [neutrinolabs/xrdp#1720]
#Platform
No LSB modules are available.
Distributor ID:	Uos
Description:	UnionTech OS Desktop 20 Home

#Version of xrdp

> ls /tmp/.X11-unix/X* /tmp/.X*-lock /run/xrdp/*

```
/run/xrdp/xrdp.pid  /run/xrdp/xrdp-sesman.pid  /tmp/.X0-lock  /tmp/.X11-unix/X0
/run/xrdp/sockdir:
```

> /usr/sbin/xrdp --version

```
xrdp 0.9.9
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2018 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/var/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -fdebug-prefix-map=/build/xrdp-GQ2R2u/xrdp-0.9.9=. -fstack-protector-strong -Wformat -Werror=format-security
      LDFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2
      PKG_CONFIG_PATH=/build/xrdp-GQ2R2u/xrdp-0.9.9/pkgconfig

  Compiled with OpenSSL 1.1.1d  10 Sep 2019
```

#xrdp installed from package manager or built from scratch?
#symptoms of failure
![image](https://user-images.githubusercontent.com/28851617/98793426-ded6e980-2442-11eb-8975-8411b07b9cf6.png)

**Comment by matt335672** [comment]
The username and password you have entered have not been accepted.

Do the username and password you are using with over ssh? What is the username you are using?

**Comment by huanjoyous** [comment]
> dpkg -l | grep openssh-client

```
ii  openssh-client                                1:7.9p1.1-1+dde                     amd64        secure shell (SSH) client, for secure access to remote machines
```

1,使用的root用户和密码
2,使用的新建用户和密码
两种方式我试试了,还是报这个错误

**Comment by matt335672** [comment]
XRDP will not let you log in as root or with a UID of 0. You'll need a different user.

I'd recommend setting up a new user as follows:-
- UID is 1000 or larger
- User name just uses letters 'a' to 'z'.  We've had some reports of problems with systemd when user names have unusual characters in them.
- User name not too long. Nine characters or less is recommended.

Get the new user working with an ssh login and then we can look further into what is happening on your system.

**Comment by huanjoyous** [comment]
Thank you, please ignore, system bug

![image](https://user-images.githubusercontent.com/28851617/99079231-9c580d00-25fa-11eb-96be-20866e9dbcb0.png)
url:https://bbs.deepin.org/post/204101

**Comment by matt335672** [comment]
Thanks for letting us know what you've found.

I'll close this issue for now.
