### ISSUE TITLE
Log of failed logins

### ISSUE THREAD

**Issue by rafelamer** [neutrinolabs/xrdp#1724]
In the file scp_v0.c, the allowed logins are logged with the code  

`log_message(LOG_LEVEL_INFO, "++ created session (access granted): username %s, ip %s", s->username, s->client_ip);
`

and the username and client_ip are logged.

It is possible the log the failed logins? I think it will be useful.

Regards,
Rafel Amer
Technic University of Catalonia

**Comment by metalefty** [comment]
I agree. It is quite useful.

**Comment by matt335672** [comment]
I'm working on this area at  the moment for a fix for #1684. I'll pick this one up at the same time.
