### ISSUE TITLE
Cannot Connect to xrdp from Win10 to Fedora 33

### ISSUE THREAD

**Issue by dejannenov** [neutrinolabs/xrdp#1731]
1. Clean Install of Fedora 33

2. Installed xrdp using:
    dnf -y install xrdp tigervnc-server
    systemctl enable --now xrdp

3. Disabled firewalld altogether
    [root@nenov-media log]# ps -ef | grep firewall
    root       37380   22289  0 13:22 pts/0    00:00:00 grep --color=auto firewall

4. xrdp.ini and xrdp-sesman.ini are attached
[xrdp.zip](https://github.com/neutrinolabs/xrdp/files/5580051/xrdp.zip)
[sesman.zip](https://github.com/neutrinolabs/xrdp/files/5580052/sesman.zip)

5. Log files area ttached
[xrdp-sesman.log.zip](https://github.com/neutrinolabs/xrdp/files/5580084/xrdp-sesman.log.zip)
[xrdp.log.zip](https://github.com/neutrinolabs/xrdp/files/5580085/xrdp.log.zip)

6. Short screen recording of client behavior is attached - 
using the Windwos10 RemoteDesktop client and MobaXterm RDP Session Cleint.
[xrdp-fedora33-from-win10-problem-session-disconnected.mp4.zip](https://github.com/neutrinolabs/xrdp/files/5580093/xrdp-fedora33-from-win10-problem-session-disconnected.mp4.zip)

7. Clients are assumed OK - as I am able to connect to xrdp on Lubuntu 20.4 with no issues - this seems to be a Fedora 33 specific issue as far as I can tell.

**Comment by matt335672** [comment]
xrdp-sesman.log shows your session is finishing abruptly:-

```
20201122-13:58:23] [CORE ] waiting for window manager (pid 52344) to exit
[20201122-13:58:24] [CORE ] window manager (pid 52344) did exit, cleaning up session
```

Can you post a system log? You can get it as follows:-

1.    Make a note of the system time in hours, minutes and seconds (HH:MM:SS) on your PuTTY connection.
2.    Attempt to connect using XRDP
3.    When this fails, enter this command on the PuTTY session, changing HH:MM:SS to the time you recorded in step 1.

   ```bash
    sudo journalctl -S HH:MM:SS
   ```

Thanks.

**Comment by dejannenov** [comment]
Embarrassingly I am no longer able to reproduce - I can now connect with no issues over RDP.
Not sure whether the issue was due to not initially doing a full "dnf upgrade".

However - in the remote desktop session neither terminal nor files (nautilus) will start. Neither does Thunar.
Had to go to Konqueror and LXTerminal instead.

**Comment by matt335672** [comment]
I hate it when that happens!

I'm very happy to help you debug the GNOME situation if you want. Fedora 33 is running a version of systemd which is already causing issues on Arch/Manjaro (#1684) and it might be useful to get it bottomed out. From the description of your problem you may be having DBUS issues.

If you post a system log as detailed above I'll take a look at it.

**Comment by dejannenov** [comment]
So... about that - I have NOT had this happen to me before - but for the SECOND time - pulled up a session to this instance today - and - of course - both the terminal and the files app came up with no issues. I am stumped - I spend 2 hours yesterday trying to get this to work and finding workarounds - I am stumped - and irritated for wasting your time. Apologies.

**Comment by matt335672** [comment]
That's fine. There may well be a bug buried in here somewhere, so thanks for looking again.

I'll close this issue in about a week if you don't add anything else to it. If you do however, I'll take a look.

**Comment by matt335672** [comment]
Closing now - feel free to re-open if you find anything further.
