### ISSUE TITLE
Login problem with gcp ssh

### ISSUE THREAD

**Issue by MOOGAA** [neutrinolabs/xrdp#1736]
I'm facing login problem in gcp ssh can any1 tell whts wrong is happening 

Is it can be bcz of shared ip

**Comment by MOOGAA** [comment]
![Uploading Screenshot_2020-11-27-16-06-18-292_com.microsoft.rdc.android.jpg…]()

**Comment by matt335672** [comment]
Can't see the image!

**Comment by MOOGAA** [comment]
> Can't see the image!

https://t.me/UserGeSpam/108086

Check this out

**Comment by matt335672** [comment]
I still can't see that.

Can you drag and drop it on to a github posting for me please?

Thanks.

**Comment by MOOGAA** [comment]
> I still can't see that.
> 
> Can you drag and drop it on to a github posting for me please?
> 
> Thanks.

![Screenshot_2020-11-27-16-06-18-292_com microsoft rdc android](https://user-images.githubusercontent.com/67998406/100971482-03fbdb00-355d-11eb-88d2-46640b9a132e.jpg)

**Comment by matt335672** [comment]
OK - thanks.

That looks like a username/password error, or similar.

Couple of questions/pointers for you:-
- Can the same user+password log in using ssh?
- You're not using `root` are you? That's not allowed.
- Some users have reported problems with usernames with unusual characters in them (e.g. '.'). Try a username with only letters and digits, and nine characters or less.

What platform are you on? I may be able tu suggest other places you can look for username-related errors.

**Comment by MOOGAA** [comment]
> OK - thanks.
> 
> That looks like a username/password error, or similar.
> 
> Couple of questions/pointers for you:-
> 
> * Can the same user+password log in using ssh?
> * You're not using `root` are you? That's not allowed.
> * Some users have reported problems with usernames with unusual characters in them (e.g. '.'). Try a username with only letters and digits, and nine characters or less.
> 
> What platform are you on? I may be able to suggest other places you can look for username-related errors.

Idk abt 1st q

No I'm not useing root as username

I'm useing <username> as username

My username don't hav any special chars

Platform is gcp & I set firewall for xrdp port & it's showing in rdp client but I can't login which ss I have alredy uploaded

...

**Comment by matt335672** [comment]
GCP just tells me you're running a Linux VM on Google. It doesn't tell me what the underlying Linux operating system you're using is - it could be CentOS or Ubuntu for example. Can you find out what Linux flavour you're running? We can then point you in the direction of the right logs.

Thanks.

**Comment by MOOGAA** [comment]
I'm useing ubuntu 20.04 LTS SSH

**Comment by MOOGAA** [comment]
I also tryed chrome remote desktop but it kinda sucks inturms of reliability bcz I can't past txt to vm via chrome remote desktop so xrdp is the only hope 4 now

**Comment by MOOGAA** [comment]
> GCP just tells me you're running a Linux VM on Google. It doesn't tell me what the underlying Linux operating system you're using is - it could be CentOS or Ubuntu for example. Can you find out what Linux flavour you're running? We can then point you in the direction of the right logs.
> 
> Thanks.

Also can we talk on Telegram 

https://t.me/KAKAROT379

**Comment by matt335672** [comment]
We can't talk on telegram I'm afraid - the whole point of this forum is it's a shared resource and the conversations here are of benefit to other users.

On your Ubuntu box, can you do the following:-

1) Log in over ssh
2) Check your username and password work at a local level with this command:-
    <pre>
    su - <b>&lt;username&gt;</b> -c "echo OK"</pre>

    You should get an OK back if they do.

3) Make a note of the system time in hours, minutes and seconds (HH:MM:SS) with the date command
4) Try to connect from your RDP client
5) After the authentication fail, use the command `sudo journalctl -S HH:MM:SS` (where `HH:MM:SS` is the time from step 3) to get a system log.
6) Paste that here and we'll have a look at it.

**Comment by MOOGAA** [comment]
> We can't talk on telegram I'm afraid - the whole point of this forum is it's a shared resource and the conversations here are of benefit to other users.
> 
> On your Ubuntu box, can you do the following:-
> 
> 1. Log in over ssh
> 2. Check your username and password work at a local level with this command:-
>      su - <username> -c "echo OK"
>    You should get an OK back if they do.
> 3. Make a note of the system time in hours, minutes and seconds (HH:MM:SS) with the date command
> 4. Try to connect from your RDP client
> 5. After the authentication fail, use the command `sudo journalctl -S HH:MM:SS` (where `HH:MM:SS` is the time from step 3) to get a system log.
> 6. Paste that here and we'll have a look at it.

I tryed ssh-key passwd & It shows authentication falier

**Comment by MOOGAA** [comment]
Wht I'm looking for in logs

**Comment by matt335672** [comment]
Hi @MOOGAA 

I don't understand your comment above. Are you saying you can't log in over ssh using a password? Or are you saying you can log in to the machine with an ssh-key, but then the username and password doesn't work?

What you'll need to do is get the machine to a state where you can log in with ssh using a password. That account should then be usable with XRDP.

Does that make sense?

**Comment by MOOGAA** [comment]
> Hi @MOOGAA
> 
> I don't understand your comment above. Are you saying you can't log in over ssh using a password? Or are you saying you can log in to the machine with an ssh-key, but then the username and password doesn't work?
> 
> What you'll need to do is get the machine to a state where you can log in with ssh using a password. That account should then be usable with XRDP.
> 
> Does that make sense?

I'm able to login to ssh

" I'm not able to login on xrdp "

**Comment by matt335672** [comment]
OK -thanks. That's clear to me now.

Can you log in over ssh and do the steps in [the post above](1736#issuecomment-740471960)? That should give us a lot more information.

**Comment by MOOGAA** [comment]
> OK -thanks. That's clear to me now.
> 
> Can you log in over ssh and do the steps in [the post above](1736#issuecomment-740471960)? That should give us a lot more information.

I've did those steps

**Comment by MOOGAA** [comment]
I've try sudo passwd which shud be same as ssh-key pass
But it clearly shows authentication failure

**Comment by MOOGAA** [comment]
> OK -thanks. That's clear to me now.
> 
> Can you log in over ssh and do the steps in [the post above](1736#issuecomment-740471960)? That should give us a lot more information.

Also does any1 before me tryed xrdp on gcp

**Comment by matt335672** [comment]
It's the first time I've heard GCP mentioned myself on these forums.

Since your username isn't working for 'su', it's possible that GCP is logging you in using over ssh using a different method, like a secret key protected by a passphrase. In this case your passphrase won't be the same as the password.

You can try adding another user to experiment:-

```
sudo adduser xrdptest
```

You will be prompted for extra info for this user, including a password. Then try that with xrdp. When you're done, remove the user with:-

```
sudo deluser xrdptest
rm -rf /home/xrdptest
```

I would caution against exposing the RDP port to the internet to log in to your machine. This is not a safe thing to so. You can tunnel over an SSH login though, and that's a lot safer.

Let me know if that's not clear, or you need more help.

**Comment by MOOGAA** [comment]
> It's the first time I've heard GCP mentioned myself on these forums.
> 
> Since your username isn't working for 'su', it's possible that GCP is logging you in using over ssh using a different method, like a secret key protected by a passphrase. In this case your passphrase won't be the same as the password.
> 
> You can try adding another user to experiment:-
> 
> ```
> sudo adduser xrdptest
> ```
> 
> You will be prompted for extra info for this user, including a password. Then try that with xrdp. When you're done, remove the user with:-
> 
> ```
> sudo deluser xrdptest
> rm -rf /home/xrdptest
> ```
> 
> I would caution against exposing the RDP port to the internet to log in to your machine. This is not a safe thing to so. You can tunnel over an SSH login though, and that's a lot safer.
> 
> Let me know if that's not clear, or you need more help.

I tryed that & it partially worked

Wht happened is I added another user & pass & I logged in successfully but right after it sm home I've get kicked out of to session

**Comment by MOOGAA** [comment]
> It's the first time I've heard GCP mentioned myself on these forums.
> 
> Since your username isn't working for 'su', it's possible that GCP is logging you in using over ssh using a different method, like a secret key protected by a passphrase. In this case your passphrase won't be the same as the password.
> 
> You can try adding another user to experiment:-
> 
> ```
> sudo adduser xrdptest
> ```
> 
> You will be prompted for extra info for this user, including a password. Then try that with xrdp. When you're done, remove the user with:-
> 
> ```
> sudo deluser xrdptest
> rm -rf /home/xrdptest
> ```
> 
> I would caution against exposing the RDP port to the internet to log in to your machine. This is not a safe thing to so. You can tunnel over an SSH login though, and that's a lot safer.
> 
> Let me know if that's not clear, or you need more help.

Gcp = Google Cloud Platform

**Comment by matt335672** [comment]
Great - thanks for that.

When the session ends, use `sudo journalctl -S -2m` (or similar) to get a recent system log. We should be able to find out why the session isn't running in there.

Which desktop have you installed on the VM for this? Is it working on the console?

**Comment by MOOGAA** [comment]
> Great - thanks for that.
> 
> When the session ends, use `sudo journalctl -S -2m` (or similar) to get a recent system log. We should be able to find out why the session isn't running in there.
> 
> Which desktop have you installed on the VM for this? Is it working on the console?

Ubuntu-desktop

I don't understand what do u mean by " working on console "

**Comment by matt335672** [comment]
What I mean is, on GCP can you get to the VM console to try to log in the same way as you would at a physical machine?

If you're using Ubuntu-desktop, you'll need to have `gdm` running as otherwise things like screen-unlock won't work.  That's just the way GNOME is designed I'm afraid.

**Comment by MOOGAA** [comment]
> What I mean is, on GCP can you get to the VM console to try to log in the same way as you would at a physical machine?
> 
> If you're using Ubuntu-desktop, you'll need to have `gdm` running as otherwise things like screen-unlock won't work. That's just the way GNOME is designed I'm afraid.

Can u explain some more abt that

I don't hav any idea wht ur talking abt

**Comment by matt335672** [comment]
Have you got access to a physical machine or a local VM you can play with before using GCP?

I think you should probably get an idea of how all these things work together before trying to get them working on the cloud. I'm happy to help you get xrdp working, but it's not really my job to tell you how a Linux desktop works in general.

**Comment by MOOGAA** [comment]
No I don't hav any local machine

**Comment by MOOGAA** [comment]
Thnx for ur time & help but only I'm facing this err this for sure some one ik use it on AWS (Amazon Web services) & it worked for him

**Comment by matt335672** [comment]
It'll work for sure, but with the standard Ubuntu desktop (GNOME) you need to get the machine configured so that it's accepting logins in the 'console', which is that the screen and keyboard would be on a physical machine. I don't know if on GCP you can get to that see what's happening on the console.

**Comment by MOOGAA** [comment]
> It'll work for sure, but with the standard Ubuntu desktop (GNOME) you need to get the machine configured so that it's accepting logins in the 'console', which is that the screen and keyboard would be on a physical machine. I don't know if on GCP you can get to that see what's happening on the console.

Well it just worked after 2 vm recreation & adding another sudo user

The only problem im facing is an login tab which I can't 4 some reason close
