### ISSUE TITLE
black screen after connection to newest lubuntu / xubuntu

### ISSUE THREAD

**Issue by bartoll** [neutrinolabs/xrdp#1743]
Does anybody use 'xrdp' with newest version of Lubuntu / Xubuntu 20.04?
I try to install those systems and configure 'xrdp' package with no success. Every times I connect from the remote client, I get black screen. On the server there is an error in logs concerning

`    Couldn't open /etc/securetty: No such file or directory`

All logs are here: https://pastebin.com/BA5HzT91

**Comment by bartoll** [comment]
I've discovered that the problem is only when VM is on VirtualBox. When I switched to VM in Amazon AWS, I was able to connect with sucess.

**Comment by matt335672** [comment]
I don't think the securetty message is relevant here - see [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932458](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932458).

Are you using the Xorg or Xvnc backend? Can you try the other backend and see what happens?

**Comment by matt335672** [comment]
@bartoll - do you need any more help with this?
