### ISSUE TITLE
Remoteapplicationprogram parameter in rdp file

### ISSUE THREAD

**Issue by Jackobama** [neutrinolabs/xrdp#1748]
Hello, can the remoteapplicationprogram parameter in the windows rdp file be retrieved in xrdp? I read the code and found that there is no place in xrdp to set or assign this parameter.

**Comment by aquesnel** [comment]
The remoteapplicationprogram is used for defining the application to start when using a RAIL RDP session. [XRDP doesn't support RAIL](https://github.com/neutrinolabs/xrdp/wiki/RAIL-support-in-xrdp) as of version 0.9.14 but does have some code for RAIL connections that is incomplete.

Here is the [existing code](https://github.com/neutrinolabs/xrdp/blob/devel/sesman/chansrv/rail.c#L458) that parses the [TS_RAIL_ORDER_EXEC](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdperp/98a6e3c3-c2a9-42cc-ad91-0d9a6c211138) message from the client which includes the value set in remoteapplicationprogram field.
