### ISSUE TITLE
Syslog log level "crit" for rather informational messages

### ISSUE THREAD

**Issue by eht16** [neutrinolabs/xrdp#1749]
xrdp logs messages like
```
xrdp-sesman[1990800]: (1990800)(redacted)[CORE ] waiting for window manager (pid 1990801) to exit
xrdp-sesman[1990800]: (1990800)(redacted)[CORE ] window manager (pid 1990801) did exit, cleaning up session
```
with log level "crit" to Syslog (if enabled).
The messages look rather like "info" to me and so I wondered about the high log level. I noticed such messages on normal logout, i.e. session quit.

The messages are emitted at https://github.com/neutrinolabs/xrdp/blob/28c35f962ddd526a2f7d67aa3bda2c6c261e9648/sesman/session.c#L812 with `LOG_LEVEL_ALWAYS` which maps to "crit" on Syslog: https://github.com/neutrinolabs/xrdp/blob/dd9f7c6092df7f257320ba88a227a435d4075241/common/log.c#L88

What do you think about lowering the log level for such messages?

**Comment by matt335672** [comment]
Hi @eht16 

It's a good question.

There's a good case to leave them where they are. A common cause of failure on new installations, particularly from new users, is a session which exits very quickly. This can exhibit itself in unusual ways to the user (e.g. see the current #1747 - there are others) and these two messages are pretty important to triage the actual problem.

The bottom line is we need a way to detect sessions which exit unusually quickly, so just changing the log level of these messages isn't a good idea.

**Comment by eht16** [comment]
Hi @matt335672,

I see that the messages are important for debugging.
My suggestion is just to log them with log level "info" as for normal operation they are just messages not errors.

What about to check the exit code of the process of `window_manager_pid` and if it is not `0`, log an appriate message?
Exit code checking might be a bit tricky to get right on all platforms but it might be worth.

**Comment by matt335672** [comment]
There are quite a few options in this area, some of which are more work than others.

Could you tell us a bit about your own interest and/or requirements in this area? Are you monitoring logs for particular events or unusual activity maybe? It would help inform the discussion.

Thanks.

**Comment by eht16** [comment]
Rather monitoring for unusual events, nothing in special. For example, I'm using `logcheck` to get an email report of syslog messages and while checking the `xrdp` messages and deciding whether I can ignore them, I noticed the high log level of these messages.

It's nothing too critical, it just seems wrong to me.
If it's not reasonable to change anything here, I'll just blacklist those messages.

**Comment by matt335672** [comment]
Thanks - that's useful.

Leave it with me and I'll see what I can do that makes sense for that use case.

One last question - are you building from source or running a packaged XRDP?

**Comment by eht16** [comment]
Thanks for the changes, they look good!

> One last question - are you building from source or running a packaged XRDP?

Packaged version in Debian Testing (at the time of writing 0.9.12).
