### ISSUE TITLE
 I connected to xrdp on linux through mstsc, but when the network of the pc where mstsc was disconnected, the session ended and disconnected, and there was no reconnection

### ISSUE THREAD

**Issue by StudyAndGrow** [neutrinolabs/xrdp#1752]

**Comment by matt335672** [comment]
We'll need a bit more to go on than that, @StudyAndGrow 

Are you able to reproduce this? If so we can have a look at it.

**Comment by metalefty** [comment]
If you're talking about automatic reconnection which is already supported in Windows-to-Windows RDP, the feature is not supported in xrdp yet.

**Comment by metalefty** [comment]
FYI: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/15b0d1c9-2891-4adb-a45e-deb4aeeeab7c
