### ISSUE TITLE
sesman.ini  |  can't open app in full screen

### ISSUE THREAD

**Issue by kbruno89** [neutrinolabs/xrdp#1754]
Hi,

I'm testing XRDP and need to make a specific use:

Open only one application without loading the entire graphical interface.

I edited the startwm.sh file and changed it to call firefox.
When access is made, firefox opens, but not in full screen. There is a black space on the screen.

![image](https://user-images.githubusercontent.com/17727951/102519297-0e47ca00-4071-11eb-836c-3c71b4573eb5.png)

Does anyone know about this?

**Comment by kbruno89** [comment]
I think this issue is with IceWM.

I installed the MatchboxWM and it is now opening in full screen!

**Comment by qihang-liu** [comment]
Could you tell me how to edit the startwm.sh file and change it to call firefox only,thx
