### ISSUE TITLE
drive redirection in same user multiple sessions

### ISSUE THREAD

**Issue by muyu1944** [neutrinolabs/xrdp#1760]
Hi,
I know that when use xrdp to connect target, a directory named "thinclient_drives" in the target user's home directory will do the drive redirection job.
I want to connect the same target and same user twice or more times, and every session has a different local drive to redirection, when I try that, only the first session can mount thinclient_drives, other session's has an error message like: "FUSE xfuse_init_lib: 792 : ERROR: fuse_mount() failed".
I think the error occurred because thinclient_drives mounted by the first session, so it can't be mount again.
So, is there a config parameter or something to make the same user different drive redirection work?

**Comment by metalefty** [comment]
Short answer:  It is impossible as of now.

Longer answer: 
Multiple sessions for the same user is not the use case that developers expect. It is not recommended but allowed for the users who understand the pros and cons.  Multiple drive redirection still has a chance to be supported if there's a strong demand from many users and someone sponsors the feature.

**Comment by matt335672** [comment]
See also #1136 which appears to be a duplicate.
