### ISSUE TITLE
 xrdp_wm_log_msg:log_msg: Error connecting to sesman: 127.0.0.1 port: 3350

### ISSUE THREAD

**Issue by kamel2005** [neutrinolabs/xrdp#1777]
oid-buster64 xrdp[5510]: (5510)(548469129232)[DEBUG] return value from xrdp_mm_connect 1
oid-buster64 xrdp[5510]: (5510)(548469129232)[DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
oid-buster64 xrdp[5510]: (5510)(548469129232)[DEBUG] Closed socket 16 (AF_INET6 ::1 port 54312)
oid-buster64 xrdp[5510]: (5510)(548469129232)[DEBUG] Closed socket 16 (AF_INET6 ::1 port 54314)
oid-buster64 xrdp[5510]: (5510)(548469129232)[DEBUG] Closed socket 16 (AF_INET6 ::1 port 54316)
oid-buster64 xrdp[5510]: (5510)(548469129232)[ERROR] xrdp_wm_log_msg: Error connecting to sesman: 127.0.0.1 port: 3350
oid-buster64 xrdp[5510]: (5510)(548469129232)[DEBUG] Closed socket 16 (AF_INET6 ::1 port 54318)
oid-buster64 xrdp[5510]: (5510)(548469129232)[DEBUG] return value from xrdp_mm_connect 1
oid-buster64 xrdp[5510]: (5510)(548469129232)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:127.0.0.1 port 3389)
oid-buster64 xrdp[5510]: (5510)(548469129232)[DEBUG] xrdp_mm_module_cleanup

**Comment by matt335672** [comment]
It looks like `seman` isn't running, based on the snippet above.

If you need more than that, can you let us know a bit more about what you're running and what you're trying to do.

Thanks.

**Comment by kamel2005** [comment]
i have  gnome 3.38.2 installed on Debain bullseye. kernell 4.9.213+, aarch64, i have allso installed xorgxrdp and added xrdp user  to ssl-cert. Every thing working. But connectting  from remote machine win 10 using rdp not working.
what settings are messing if i am not mistaken?
Thanks

**Comment by kamel2005** [comment]
here is the full xrdp status.
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2020-12-11 14:25:43 EST; 3 weeks 3 days ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 2277 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 2289 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 2294 (xrdp)
      Tasks: 1 (limit: 3846)
     Memory: 1.3M
     CGroup: /system.slice/xrdp.service
             └─2294 /usr/sbin/xrdp

Jan 04 23:13:52 odroid-buster64 xrdp[2615]: (2615)(547719778320)[WARN ] local keymap file for 0x0000040c found and doesn'>
Jan 04 23:13:52 odroid-buster64 xrdp[2615]: (2615)(547719778320)[DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.>
Jan 04 23:13:56 odroid-buster64 xrdp[2615]: (2615)(547719778320)[DEBUG] Closed socket 18 (AF_INET6 ::1 port 48086)
Jan 04 23:14:00 odroid-buster64 xrdp[2615]: (2615)(547719778320)[DEBUG] Closed socket 18 (AF_INET6 ::1 port 48088)
Jan 04 23:14:04 odroid-buster64 xrdp[2615]: (2615)(547719778320)[DEBUG] Closed socket 18 (AF_INET6 ::1 port 48090)
Jan 04 23:14:08 odroid-buster64 xrdp[2615]: (2615)(547719778320)[ERROR] xrdp_wm_log_msg: Error connecting to sesman: 127.>
Jan 04 23:14:08 odroid-buster64 xrdp[2615]: (2615)(547719778320)[DEBUG] Closed socket 18 (AF_INET6 ::1 port 48092)
Jan 04 23:14:08 odroid-buster64 xrdp[2615]: (2615)(547719778320)[DEBUG] return value from xrdp_mm_connect 1
Jan 04 23:14:08 odroid-buster64 xrdp[2615]: (2615)(547719778320)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.1.2 por>
Jan 04 23:14:08 odroid-buster64 xrdp[2615]: (2615)(547719778320)[DEBUG] xrdp_mm_module_cleanup
l

**Comment by metalefty** [comment]
Again, It looks like seman isn't running.

**Comment by matt335672** [comment]
@kamel2005 - look at the `xrdp-sesman` service. It's installed alongside the `xrdp` service and is necessary to create sessions.

**Comment by kamel2005** [comment]
**xrdp-sesman is running.**

kamel@odroid-buster64:~$ sudo service xrdp status
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-01-06 08:30:28 EST; 5min ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 2671 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 2680 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 2681 (xrdp)
      Tasks: 2 (limit: 3846)
     Memory: 15.1M
     CGroup: /system.slice/xrdp.service
             ├─2681 /usr/sbin/xrdp
             └─2689 /usr/sbin/xrdp

Jan 06 08:31:49 odroid-buster64 xrdp[2689]: (2689)(547848785936)[ERROR] xrdp_wm_log_msg: Error connecting to sesman: 127.>
Jan 06 08:31:49 odroid-buster64 xrdp[2689]: (2689)(547848785936)[DEBUG] Closed socket 18 (AF_INET6 ::1 port 49278)
Jan 06 08:31:49 odroid-buster64 xrdp[2689]: (2689)(547848785936)[DEBUG] return value from xrdp_mm_connect 1
Jan 06 08:33:10 odroid-buster64 xrdp[2689]: (2689)(547848785936)[DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.>
Jan 06 08:33:14 odroid-buster64 xrdp[2689]: (2689)(547848785936)[DEBUG] Closed socket 18 (AF_INET6 ::1 port 49280)
Jan 06 08:33:18 odroid-buster64 xrdp[2689]: (2689)(547848785936)[DEBUG] Closed socket 18 (AF_INET6 ::1 port 49282)
Jan 06 08:33:22 odroid-buster64 xrdp[2689]: (2689)(547848785936)[DEBUG] Closed socket 18 (AF_INET6 ::1 port 49284)
Jan 06 08:33:26 odroid-buster64 xrdp[2689]: (2689)(547848785936)[ERROR] xrdp_wm_log_msg: Error connecting to sesman: 127.>
Jan 06 08:33:26 odroid-buster64 xrdp[2689]: (2689)(547848785936)[DEBUG] Closed socket 18 (AF_INET6 ::1 port 49286)
Jan 06 08:33:26 odroid-buster64 xrdp[2689]: (2689)(547848785936)[DEBUG] return value from xrdp_mm_connect 1
--------------------------------------------------------------------------------------------------------------------------

kamel@odroid-buster64:~$ sudo service xrdp-sesman status
● xrdp-sesman.service - xrdp session manager
     Loaded: loaded (/lib/systemd/system/xrdp-sesman.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-01-06 08:30:27 EST; 6min ago
       Docs: man:xrdp-sesman(8)
             man:sesman.ini(5)
    Process: 2660 ExecStart=/usr/sbin/xrdp-sesman $SESMAN_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 2670 (xrdp-sesman)
      Tasks: 1 (limit: 3846)
     Memory: 696.0K
     CGroup: /system.slice/xrdp-sesman.service
             └─2670 /usr/sbin/xrdp-sesman

Jan 06 08:30:27 odroid-buster64 systemd[1]: Starting xrdp session manager...
Jan 06 08:30:27 odroid-buster64 xrdp-sesman[2660]: (2660)(547969943856)[DEBUG] libscp initialized
Jan 06 08:30:27 odroid-buster64 xrdp-sesman[2660]: (2660)(547969943856)[DEBUG] Testing if xrdp-sesman can listen on 127.0>
Jan 06 08:30:27 odroid-buster64 xrdp-sesman[2660]: (2660)(547969943856)[DEBUG] Closed socket 5 (AF_INET6 ::1 port 3350)
Jan 06 08:30:27 odroid-buster64 xrdp-sesman[2670]: (2670)(547969943856)[INFO ] starting xrdp-sesman with pid 2670
Jan 06 08:30:27 odroid-buster64 systemd[1]: Started xrdp session manager.
Jan 06 08:30:27 odroid-buster64 xrdp-sesman[2670]: (2670)(547969943856)[INFO ] listening to port 3350 on 127.0.0.1

**Comment by matt335672** [comment]
Thanks for that.

xrdp and xrdp-sesman use TCP port 3350 on the loopback interface (127.0.0.1) to communicate. From above it looks like `xrdp-sesman` is listening on 3350, but `xrdp` is for some reason unable to connect to it.

Firstly; are you running a firewall on the loopback interface? If so, could you temporarily disable it and see if that makes a difference?

If that's not it, can you please install nmap if it's not installed (`sudo apt install nmap`), and then run the following commands which I'll need the output for. The first command checks the processes are using the same network stack, the second looks for processes listening on port 3350, and the third probes port 3350 to see if it's open.

```
sudo ps -e -o pid,netns,command | grep xrdp
sudo ss -alp 'sport = 3350'
sudo nmap -p 3350 127.0.0.1
```

**Comment by kamel2005** [comment]
Because of security issue  i don't want to install nmap. 
Thanks for help.

**Comment by mihvoi** [comment]
My problem "Error connecting to sesman: 127.0.0.1 port: 3350" on xrdp after upgrade to Ubuntu 23.10 mantic was fixed by disabling ipv6 on all interfaces. 

I had ipv6 enabled only on some interfaces, probably this made xrdp to attempt connecting to xrdp-sesman via ipv6, while the loopback interface had ipv6 disabled. Interestingly, the problem appeared after upgrade to Ubuntu 23.10 mantic without changing any config.

This is only the last piece I tried that solved the xRDP connection, not sure if it was the only one needed. 
Before this, I also migrated from Wayland to Xorg and from gnome to xfce, not sure if those were actually needed.


**How to disable ipv6 on all interfaces:**

`sysctl -a | grep disable_ipv6`

> net.ipv6.conf.all.disable_ipv6 = 1
> net.ipv6.conf.default.disable_ipv6 = 1
> net.ipv6.conf.enp89s0.disable_ipv6 = 1
> net.ipv6.conf.lo.disable_ipv6 = 1
> net.ipv6.conf.wlo1.disable_ipv6 = 1

If some of these are not 1, you can force them to 1 with something like:
sysctl -w net.ipv6.conf.enp89s0.disable_ipv6=1

Check again:
`sysctl -a | grep disable_ipv6`
Restart system to be sure
