### ISSUE TITLE
No Mouse / Keyboard interaction possible 

### ISSUE THREAD

**Issue by SH160388** [neutrinolabs/xrdp#1779]
Hello, 
i have the problem that i can't use any mouse or keyboard interaction. I think it happens since kernel upgrade to linux510 but i'm not really sure. 

(OS : Manjaro xfce)

Logs: 
```
[20210105-18:31:34] [WARN ] unknown in xrdp_caps_process_confirm_active 27
[20210105-18:31:34] [WARN ] xrdp_caps_process_confirm_active: not enough orders supported by client, client wants off screen bitmap but offscreen bitmaps disabled
[20210105-18:31:34] [INFO ] Loading keymap file /etc/xrdp/km-00000407.ini
[20210105-18:31:34] [WARN ] local keymap file for 0x00000407 found and doesn't match built in keymap, using local keymap file
[20210105-18:31:34] [ERROR] libxrdp_query_channel - Channel 0 name RDPDR
[20210105-18:31:34] [ERROR] libxrdp_query_channel - Channel 1 name rdpsnd
[20210105-18:31:34] [ERROR] libxrdp_query_channel - Channel 2 name cliprdr
[20210105-18:31:34] [ERROR] libxrdp_query_channel - Channel 3 name drdynvc
[20210105-18:31:34] [ERROR] libxrdp_query_channel - Channel out of range 4
[20210105-18:31:35] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20210105-18:31:35] [INFO ] drdynvc_process_capability_response: DVC version 2 selected
[20210105-18:31:35] [INFO ] xrdp_wm_log_msg: login successful for display 10
```

**Comment by matt335672** [comment]
Hi @SH160388

Thanks for opening a new issue on this. It will make it easier for other people having a problem to find our conversation.

A few questions for you.
1. Are the keyboard and mouse working on the login screen? It looks like they are from the log file above.
2. If you're using the `Xorg` backend, can you try `Xvnc` instead and see if it makes a difference?
3. If you're using the `Xorg` backend, can you post the contents of `~/.xorgxrdp.10.log` from your home directory.

Thanks.

**Comment by SH160388** [comment]
Hello thanks for your support.

1. yes it works on the Login-screen. I've saved it on my RDP Client so they passed through but now i've tried it without saved credentials and yes i can use mouse  and the keyboard on login-screen.

2.  yes i used Xorg backend. (without this i get only blackscreen with xrdp) I've tried it and yes its the same wit Xvnc. 

3. `[    88.964] (WW) Failed to open protocol names file lib/xorg/protocol.txt
[    88.964] 
X.Org X Server 1.20.10
X Protocol Version 11, Revision 0
[    88.964] Build Operating System: Linux Manjaro Linux
[    88.964] Current Operating System: Linux manjaro-host 5.10.2-2-MANJARO #1 SMP PREEMPT Tue Dec 22 08:14:42 UTC 2020 x86_64
[    88.964] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.10-x86_64 root=UUID=663123a9-9e32-4006-b85c-57f4bea6124d rw nouveau.modeset=0 quiet apparmor=1 security=apparmor udev.log_priority=3
[    88.964] Build Date: 16 December 2020  10:33:32PM
[    88.964]  
[    88.964] Current version of pixman: 0.40.0
[    88.964] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[    88.965] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    88.965] (++) Log file: ".xorgxrdp.10.log", Time: Thu Jan  7 18:34:28 2021
[    88.971] (++) Using config file: "/etc/X11/xrdp/xorg.conf"
[    88.971] (==) Using config directory: "/etc/X11/xorg.conf.d"
[    88.971] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    88.972] (==) ServerLayout "layout"
[    88.972] (**) |-->Screen "Screen (xrdpdev)" (0)
[    88.972] (**) |   |-->Monitor "Monitor"
[    88.972] (**) |   |-->Device "Video Card (xrdpdev)"
[    88.973] (**) Option "DontVTSwitch" "on"
[    88.973] (**) Option "AutoAddDevices" "off"
[    88.973] (**) Not automatically adding devices
[    88.973] (==) Automatically enabling devices
[    88.973] (==) Automatically adding GPU devices
[    88.973] (==) Automatically binding GPU devices
[    88.973] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    88.973] (WW) The directory "/usr/share/fonts/OTF" does not exist.
[    88.973] 	Entry deleted from font path.
[    88.973] (WW) The directory "/usr/share/fonts/Type1" does not exist.
[    88.973] 	Entry deleted from font path.
[    88.973] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/100dpi".
[    88.973] 	Entry deleted from font path.
[    88.973] 	(Run 'mkfontdir' on "/usr/share/fonts/100dpi").
[    88.973] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/75dpi".
[    88.973] 	Entry deleted from font path.
[    88.973] 	(Run 'mkfontdir' on "/usr/share/fonts/75dpi").
[    88.973] (==) FontPath set to:
	/usr/share/fonts/misc,
	/usr/share/fonts/TTF
[    88.973] (==) ModulePath set to "/usr/lib/xorg/modules"
[    88.973] (==) |-->Input Device "<default pointer>"
[    88.973] (==) |-->Input Device "<default keyboard>"
[    88.973] (==) The core pointer device wasn't specified explicitly in the layout.
	Using the default mouse configuration.
[    88.973] (==) The core keyboard device wasn't specified explicitly in the layout.
	Using the default keyboard configuration.
[    88.973] (II) Module ABI versions:
[    88.973] 	X.Org ANSI C Emulation: 0.4
[    88.973] 	X.Org Video Driver: 24.1
[    88.973] 	X.Org XInput driver : 24.1
[    88.973] 	X.Org Server Extension : 10.0
[    88.974] (EE) systemd-logind: failed to get session: PID 2446 does not belong to any known session
[    88.974] (II) xfree86: Adding drm device (/dev/dri/card0)
[    88.975] (**) OutputClass "nvidia" ModulePath extended to "/usr/lib/nvidia/xorg,/usr/lib/xorg/modules,/usr/lib/xorg/modules"
[    88.975] (**) OutputClass "nvidia" ModulePath extended to "/usr/lib/nvidia/xorg,/usr/lib/xorg/modules,/usr/lib/nvidia/xorg,/usr/lib/xorg/modules,/usr/lib/xorg/modules"
[    88.975] (--) PCI:*(1@0:0:0) 10de:13c2:1458:366a rev 161, Mem @ 0xf6000000/16777216, 0xe0000000/268435456, 0xf0000000/33554432, I/O @ 0x0000e000/128, BIOS @ 0x????????/131072
[    88.975] (WW) Open ACPI failed (/var/run/acpid.socket) (No such file or directory)
[    88.975] (II) "glx" will be loaded. This was enabled by default and also specified in the config file.
[    88.975] (II) LoadModule: "dbe"
[    88.975] (II) Module "dbe" already built-in
[    88.975] (II) LoadModule: "ddc"
[    88.975] (II) Module "ddc" already built-in
[    88.975] (II) LoadModule: "extmod"
[    88.975] (II) Module "extmod" already built-in
[    88.975] (II) LoadModule: "glx"
[    88.975] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    88.976] (II) Module glx: vendor="X.Org Foundation"
[    88.976] 	compiled for 1.20.10, module version = 1.0.0
[    88.976] 	ABI class: X.Org Server Extension, version 10.0
[    88.976] (II) LoadModule: "int10"
[    88.976] (II) Loading /usr/lib/xorg/modules/libint10.so
[    88.982] (II) Module int10: vendor="X.Org Foundation"
[    88.982] 	compiled for 1.20.10, module version = 1.0.0
[    88.982] 	ABI class: X.Org Video Driver, version 24.1
[    88.982] (II) LoadModule: "record"
[    88.982] (II) Module "record" already built-in
[    88.982] (II) LoadModule: "vbe"
[    88.982] (II) Loading /usr/lib/xorg/modules/libvbe.so
[    88.983] (II) Module vbe: vendor="X.Org Foundation"
[    88.983] 	compiled for 1.20.10, module version = 1.1.0
[    88.983] 	ABI class: X.Org Video Driver, version 24.1
[    88.983] (II) LoadModule: "xorgxrdp"
[    88.983] (II) Loading /usr/lib/xorg/modules/libxorgxrdp.so
[    88.984] (II) Module XORGXRDP: vendor="X.Org Foundation"
[    88.984] 	compiled for 1.20.10, module version = 0.2.15
[    88.984] 	ABI class: X.Org Video Driver, version 24.1
[    88.984] xorgxrdpSetup:
[    88.984] (II) LoadModule: "fb"
[    88.984] (II) Loading /usr/lib/xorg/modules/libfb.so
[    88.984] (II) Module fb: vendor="X.Org Foundation"
[    88.984] 	compiled for 1.20.10, module version = 1.0.0
[    88.984] 	ABI class: X.Org ANSI C Emulation, version 0.4
[    88.984] (II) LoadModule: "xrdpdev"
[    88.984] (II) Loading /usr/lib/xorg/modules/drivers/xrdpdev_drv.so
[    88.984] (II) Module XRDPDEV: vendor="X.Org Foundation"
[    88.984] 	compiled for 1.20.10, module version = 0.2.15
[    88.984] 	ABI class: X.Org Video Driver, version 24.1
[    88.984] xrdpdevSetup:
[    88.984] (II) LoadModule: "mouse"
[    88.985] (WW) Warning, couldn't open module mouse
[    88.985] (EE) Failed to load module "mouse" (module does not exist, 0)
[    88.985] (II) LoadModule: "kbd"
[    88.985] (WW) Warning, couldn't open module kbd
[    88.985] (EE) Failed to load module "kbd" (module does not exist, 0)
[    88.985] rdpIdentify:
[    88.985] (II) XRDPDEV: driver for xrdp: XRDPDEV
[    88.985] rdpDriverFunc: op 10
[    88.985] (WW) Falling back to old probe method for XRDPDEV
[    88.985] rdpProbe:
[    88.985] (II) Loading sub module "fb"
[    88.985] (II) LoadModule: "fb"
[    88.985] (II) Loading /usr/lib/xorg/modules/libfb.so
[    88.985] (II) Module fb: vendor="X.Org Foundation"
[    88.985] 	compiled for 1.20.10, module version = 1.0.0
[    88.985] 	ABI class: X.Org ANSI C Emulation, version 0.4
[    88.985] (II) XRDPDEV(0): using default device
[    88.985] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[    88.985] rdpPreInit:
[    88.985] (**) XRDPDEV(0): Depth 24, (--) framebuffer bpp 32
[    88.985] (==) XRDPDEV(0): RGB weight 888
[    88.985] (==) XRDPDEV(0): Using gamma correction (1.0, 1.0, 1.0)
[    88.985] (==) XRDPDEV(0): Default visual is TrueColor
[    88.985] (==) XRDPDEV(0): DPI set to (96, 96)
[    88.985] (II) XRDPDEV(0): 	mode "640x480" ok
[    88.985] (II) XRDPDEV(0): 	mode "800x600" ok
[    88.985] (II) XRDPDEV(0): Virtual size is 800x600 (pitch 800)
[    88.985] (**) XRDPDEV(0):  Default mode "800x600": 36.0 MHz (scaled from 0.0 MHz), 35.2 kHz, 56.2 Hz
[    88.985] (II) XRDPDEV(0): Modeline "800x600"x0.0   36.00  800 824 896 1024  600 601 603 625 +hsync +vsync (35.2 kHz d)
[    88.985] rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
[    88.985] rdpScreenInit: pfbMemory bytes 1920000
[    88.985] rdpScreenInit: pfbMemory 0x7fd4c6783010
[    88.985] rdpSimdInit: assigning yuv functions
[    88.985] rdpSimdInit: cpuid ax 1 cx 0 return ax 0x000306c3 bx 0x05100800 cx 0x7ffafbbf dx 0xbfebfbff
[    88.985] rdpSimdInit: sse2 amd64 yuv functions assigned
[    88.985] (==) XRDPDEV(0): Backing store enabled
[    88.985] rdpClientConInit: disconnect idle session after [0] sec
[    88.985] rdpClientConInit: kill disconnected [0] timeout [0] sec
[    88.985] rdpXvInit: depth 24
[    88.985] rdpScreenInit: out
[    88.985] (II) Initializing extension Generic Event Extension
[    88.985] (II) Initializing extension SHAPE
[    88.985] (II) Initializing extension MIT-SHM
[    88.985] (II) Initializing extension XInputExtension
[    88.985] (II) Initializing extension XTEST
[    88.985] (II) Initializing extension BIG-REQUESTS
[    88.985] (II) Initializing extension SYNC
[    88.985] (II) Initializing extension XKEYBOARD
[    88.985] (II) Initializing extension XC-MISC
[    88.985] (II) Initializing extension SECURITY
[    88.985] (II) Initializing extension XFIXES
[    88.985] (II) Initializing extension RENDER
[    88.985] (II) Initializing extension RANDR
[    88.985] (II) Initializing extension COMPOSITE
[    88.985] (II) Initializing extension DAMAGE
[    88.985] (II) Initializing extension MIT-SCREEN-SAVER
[    88.985] (II) Initializing extension DOUBLE-BUFFER
[    88.985] (II) Initializing extension RECORD
[    88.985] (II) Initializing extension DPMS
[    88.985] (II) Initializing extension Present
[    88.985] (II) Initializing extension DRI3
[    88.985] (II) Initializing extension X-Resource
[    88.985] (II) Initializing extension XVideo
[    88.985] (II) Initializing extension XVideo-MotionCompensation
[    88.985] (II) Initializing extension GLX
[    88.985] (II) AIGLX: Screen 0 is not DRI2 capable
[    89.156] (II) IGLX: Loaded and initialized swrast
[    89.156] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[    89.156] (II) Initializing extension XFree86-VidModeExtension
[    89.156] (II) Initializing extension XFree86-DGA
[    89.156] (II) Initializing extension XFree86-DRI
[    89.156] (II) Initializing extension DRI2
[    89.156] rdpCreateScreenResources:
[    89.170] (II) LoadModule: "mouse"
[    89.171] (WW) Warning, couldn't open module mouse
[    89.171] (EE) Failed to load module "mouse" (module does not exist, 0)
[    89.171] (EE) No input driver matching `mouse'
[    89.171] (II) Falling back to input driver `libinput'
[    89.171] (II) LoadModule: "libinput"
[    89.171] (II) Loading /usr/lib/xorg/modules/input/libinput_drv.so
[    89.171] (II) Module libinput: vendor="X.Org Foundation"
[    89.171] 	compiled for 1.20.8, module version = 0.30.0
[    89.171] 	Module class: X.Org XInput Driver
[    89.171] 	ABI class: X.Org XInput driver, version 24.1
[    89.171] (II) Using input driver 'libinput' for '<default pointer>'
[    89.171] (**) Option "CorePointer" "on"
[    89.172] (**) <default pointer>: always reports core events
[    89.172] (EE) PreInit returned 2 for "<default pointer>"
[    89.172] (II) UnloadModule: "libinput"
[    89.172] (II) LoadModule: "kbd"
[    89.172] (WW) Warning, couldn't open module kbd
[    89.172] (EE) Failed to load module "kbd" (module does not exist, 0)
[    89.172] (EE) No input driver matching `kbd'
[    89.172] (II) Falling back to input driver `libinput'
[    89.172] (II) Using input driver 'libinput' for '<default keyboard>'
[    89.172] (**) Option "CoreKeyboard" "on"
[    89.172] (**) <default keyboard>: always reports core events
[    89.172] (EE) PreInit returned 2 for "<default keyboard>"
[    89.172] (II) UnloadModule: "libinput"
[    89.180] (II) config/udev: Adding input device Power Button (/dev/input/event1)
[    89.180] (II) AutoAddDevices is off - not adding device.
[    89.181] (II) config/udev: Adding input device Power Button (/dev/input/event0)
[    89.181] (II) AutoAddDevices is off - not adding device.
[    89.181] (II) config/udev: Adding input device HDA NVidia HDMI/DP,pcm=3 (/dev/input/event3)
[    89.181] (II) AutoAddDevices is off - not adding device.
[    89.181] (II) config/udev: Adding input device HDA NVidia HDMI/DP,pcm=7 (/dev/input/event4)
[    89.181] (II) AutoAddDevices is off - not adding device.
[    89.181] (II) config/udev: Adding input device HDA NVidia HDMI/DP,pcm=8 (/dev/input/event5)
[    89.181] (II) AutoAddDevices is off - not adding device.
[    89.182] (II) config/udev: Adding input device HDA NVidia HDMI/DP,pcm=9 (/dev/input/event6)
[    89.182] (II) AutoAddDevices is off - not adding device.
[    89.182] (II) config/udev: Adding input device HDA NVidia HDMI/DP,pcm=10 (/dev/input/event7)
[    89.182] (II) AutoAddDevices is off - not adding device.
[    89.182] (II) config/udev: Adding input device HDA NVidia HDMI/DP,pcm=11 (/dev/input/event8)
[    89.182] (II) AutoAddDevices is off - not adding device.
[    89.182] (II) config/udev: Adding input device HDA NVidia HDMI/DP,pcm=12 (/dev/input/event9)
[    89.182] (II) AutoAddDevices is off - not adding device.
[    89.183] (II) config/udev: Adding input device Logitech MX Anywhere 3 (/dev/input/event18)
[    89.183] (II) AutoAddDevices is off - not adding device.
[    89.183] (II) config/udev: Adding input device Logitech MX Anywhere 3 (/dev/input/mouse0)
[    89.183] (II) AutoAddDevices is off - not adding device.
[    89.184] (II) config/udev: Adding input device Logitech MX Keys (/dev/input/event19)
[    89.184] (II) AutoAddDevices is off - not adding device.
[    89.184] (II) config/udev: Adding input device Logitech MX Keys (/dev/input/mouse1)
[    89.184] (II) AutoAddDevices is off - not adding device.
[    89.184] (II) config/udev: Adding input device HDA Intel PCH Front Mic (/dev/input/event10)
[    89.184] (II) AutoAddDevices is off - not adding device.
[    89.185] (II) config/udev: Adding input device HDA Intel PCH Rear Mic (/dev/input/event11)
[    89.185] (II) AutoAddDevices is off - not adding device.
[    89.185] (II) config/udev: Adding input device HDA Intel PCH Line (/dev/input/event12)
[    89.185] (II) AutoAddDevices is off - not adding device.
[    89.185] (II) config/udev: Adding input device HDA Intel PCH Line Out Front (/dev/input/event13)
[    89.185] (II) AutoAddDevices is off - not adding device.
[    89.185] (II) config/udev: Adding input device HDA Intel PCH Line Out Surround (/dev/input/event14)
[    89.185] (II) AutoAddDevices is off - not adding device.
[    89.185] (II) config/udev: Adding input device HDA Intel PCH Line Out CLFE (/dev/input/event15)
[    89.185] (II) AutoAddDevices is off - not adding device.
[    89.186] (II) config/udev: Adding input device HDA Intel PCH Line Out Side (/dev/input/event16)
[    89.186] (II) AutoAddDevices is off - not adding device.
[    89.186] (II) config/udev: Adding input device HDA Intel PCH Front Headphone (/dev/input/event17)
[    89.186] (II) AutoAddDevices is off - not adding device.
[    89.186] (II) config/udev: Adding input device PC Speaker (/dev/input/event2)
[    89.186] (II) AutoAddDevices is off - not adding device.
[    89.190] rdpDeferredRandR:
[    89.190] rdpResizeSession: width 1024 height 768
[    89.190]   calling RRScreenSizeSet
[    89.190] rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
[    89.190] rdpRRGetInfo:
[    89.190]   screen resized to 1024x768
[    89.191]   RRScreenSizeSet ok 1
[    89.191] rdpResizeSession: width 1552 height 1084
[    89.191]   calling RRScreenSizeSet
[    89.191] rdpRRScreenSetSize: width 1552 height 1084 mmWidth 411 mmHeight 287
[    89.191] rdpRRGetInfo:
[    89.191]   screen resized to 1552x1084
[    89.193]   RRScreenSizeSet ok 1
[    89.193] rdpClientConGotConnection:
[    89.193] rdpClientConGotConnection: g_sck_accept ok new_sck 11
[    89.193] rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
[    89.193] rdpAddClientConToDev: adding first clientCon 0x5653a4a572e0
[    89.193] rdpClientConProcessMsgVersion: version 0 0 0 1
[    89.193] rdpClientConProcessScreenSizeMsg: set width 1552 height 1084 bpp 32
[    89.193] rdpClientConProcessScreenSizeMsg: shmemid 65539 shmemptr 0x7fd472993000
[    89.193] rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1552 cy 1084
[    89.218] rdpRRGetInfo:
[    89.265] rdpClientConProcessMsgClientInfo:
[    89.265]   got client info bytes 7056
[    89.265]   jpeg support 0
[    89.265]   offscreen support 0
[    89.265]   offscreen size 0
[    89.265]   offscreen entries 0
[    89.265]   client can not do offscreen to offscreen blits
[    89.265]   client can do new(color) cursor
[    89.265]   client can not do multimon
[    89.265] rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
[    89.265] rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1552 height 1084
[    90.083] rdpRRGetInfo:
[    90.691] rdpRRGetInfo:
[    95.616] rdpRRGetInfo:
[   110.573] rdpRRGetInfo:
[   114.840] rdpClientConRecv: g_sck_recv failed(returned 0)
[   114.840] rdpClientConRecvMsg: error
[   114.840] rdpClientConCheck: rdpClientConGotData failed
[   114.840] rdpClientConDisconnect:
[   114.840] rdpRemoveClientConFromDev: removing clientCon 0x5653a4a572e0
[   135.593] rdpRRGetInfo:
[   144.489] rdpClientConGotConnection:
[   144.489] rdpClientConGotConnection: g_sck_accept ok new_sck 20
[   144.489] rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
[   144.489] rdpAddClientConToDev: adding first clientCon 0x5653a4d8f3b0
[   144.490] rdpClientConProcessMsgVersion: version 0 0 0 1
[   144.490] rdpClientConProcessScreenSizeMsg: set width 1552 height 1084 bpp 32
[   144.490] rdpClientConProcessScreenSizeMsg: shmemid 98351 shmemptr 0x7fd472993000
[   144.490] rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1552 cy 1084
[   144.495] rdpClientConProcessMsgClientInfo:
[   144.495]   got client info bytes 7056
[   144.495]   jpeg support 0
[   144.495]   offscreen support 0
[   144.495]   offscreen size 0
[   144.495]   offscreen entries 0
[   144.495]   client can not do offscreen to offscreen blits
[   144.495]   client can do new(color) cursor
[   144.495]   client can not do multimon
[   144.495] rdpRRSetRdpOutputs: numCrtcs 1 numOutputs 1 monitorCount 0
[   144.495] rdpRRSetRdpOutputs: update output 0 left 0 top 0 width 1552 height 1084
[   144.495] rdpRRUpdateOutput:
[   144.496] rdpRRGetInfo:
[   154.016] rdpClientConRecv: g_sck_recv failed(returned 0)
[   154.016] rdpClientConRecvMsg: error
[   154.016] rdpClientConCheck: rdpClientConGotData failed
[   154.016] rdpClientConDisconnect:
[   154.016] rdpRemoveClientConFromDev: removing clientCon 0x5653a4d8f3b0
[   434.650] rdpClientConGotConnection:
[   434.650] rdpClientConGotConnection: g_sck_accept ok new_sck 20
[   434.650] rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
[   434.650] rdpAddClientConToDev: adding first clientCon 0x5653a4d8f3b0
[   434.650] rdpClientConProcessMsgVersion: version 0 0 0 1
[   434.650] rdpClientConProcessScreenSizeMsg: set width 1194 height 834 bpp 16
[   434.650] rdpClientConProcessScreenSizeMsg: shmemid 98356 shmemptr 0x7fd472e17000
[   434.650] rdpRRScreenSetSize: width 1194 height 834 mmWidth 316 mmHeight 221
[   434.651] rdpRRGetInfo:
[   434.651]   screen resized to 1194x834
[   434.652] rdpClientConProcessScreenSizeMsg: RRScreenSizeSet ok=[1]
[   434.652] rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1194 cy 834
[   434.657] rdpClientConProcessMsgClientInfo:
[   434.657]   got client info bytes 7056
[   434.657]   jpeg support 0
[   434.657]   offscreen support 0
[   434.657]   offscreen size 0
[   434.657]   offscreen entries 0
[   434.657]   client can not do offscreen to offscreen blits
[   434.657]   client can do new(color) cursor
[   434.657]   client can not do multimon
[   434.657] rdpRRSetRdpOutputs: numCrtcs 1 numOutputs 1 monitorCount 0
[   434.657] rdpRRSetRdpOutputs: update output 0 left 0 top 0 width 1194 height 834
[   434.657] rdpRRUpdateOutput:
[   434.666] rdpRRGetInfo:
[   434.668] rdpRRGetInfo:
[   453.023] rdpClientConRecv: g_sck_recv failed(returned 0)
[   453.023] rdpClientConRecvMsg: error
[   453.023] rdpClientConCheck: rdpClientConGotData failed
[   453.023] rdpClientConDisconnect:
[   453.024] rdpRemoveClientConFromDev: removing clientCon 0x5653a4d8f3b0`

**Comment by matt335672** [comment]
The problem seems to be with your xorg config - it's not loading any input device drivers.

I've just run up my Manjaro VM for comparison. These lines in your log file:-

```
[    88.972] (==) ServerLayout "layout"
[    88.972] (**) |-->Screen "Screen (xrdpdev)" (0)
[    88.972] (**) |   |-->Monitor "Monitor"
[    88.972] (**) |   |-->Device "Video Card (xrdpdev)"
```

Look like this in my log file:-

```
[   324.533] (==) ServerLayout "X11 Server"
[   324.533] (**) |-->Screen "Screen (xrdpdev)" (0)
[   324.533] (**) |   |-->Monitor "Monitor"
[   324.533] (**) |   |-->Device "Video Card (xrdpdev)"
[   324.533] (**) |-->Input Device "xrdpMouse"
[   324.533] (**) |-->Input Device "xrdpKeyboard"

```

I've attached my [/etc/X11/xrdp/xorg,conf](https://github.com/neutrinolabs/xrdp/files/5786734/xorg.conf.txt) which is part of the `xorgxrdp-git` package. Please compare it to yours for differences. You could also try re-installing `xorgxrdp-git`.

Let us know how you get on.

**Comment by SH160388** [comment]
Here you can see my /etc/X11/xrdp/xorg,conf 
[xorg.conf.txt](https://github.com/neutrinolabs/xrdp/files/5788195/xorg.conf.txt)
I've tried to reinstall the packages. 
With manual compilation I can't get it to work. The screen stays black after the login as if I hadn't installed xorgxrdp.
So I reinstalled the one I used so far.
![image](https://user-images.githubusercontent.com/77016355/104038406-5e7bfd00-51d5-11eb-97bd-99610d58e4b9.png)

Now I still remembered that I also did a restore as part of the kernel upgrade and since this time I received an SSL message, is there a dependency?
[systemctl_xrdp_status.log](https://github.com/neutrinolabs/xrdp/files/5788221/systemctl_xrdp_status.log)

**Comment by matt335672** [comment]
There's no depedency there that I'm aware of.

It look like the X server is finding another layout which it's loading in preference to the one we want. You're getting this message:-

```
[    88.972] (==) ServerLayout "layout"
```

instead of this one:-

```
[   324.533] (==) ServerLayout "X11 Server"
```

Can you try a couple of things for me?
1. Log the output of `grep layout /etc/X11/xorg.conf.d/* /usr/share/X11/xorg.conf.d/*`
2. Add these lines to the `[Xorg]` stanza in `/etc/xrdp/sesman.ini`:-
    ```
    param=-layout
    param=X11 Server
    ```
    Then `sudo systemctl restart xrdp-sesman` and see if that makes a difference.

The first step above looks for where the other layout could be stored, and the second step tries forcing the layout we should be using.

Let us know how it goes.

**Comment by matt335672** [comment]
@SH160388 - do you need any more help with this?

**Comment by MikaelElkiaer** [comment]
> param=-layout
> param=X11 Server

Adding those to the sesman.ini did the trick for me! I had a similar issue - I got to my window manager, but it wouldn't take any input.

**Comment by GoldenbyteGH** [comment]
> There's no depedency there that I'm aware of.
> 
> It look like the X server is finding another layout which it's loading in preference to the one we want. You're getting this message:-
> 
> ```
> [    88.972] (==) ServerLayout "layout"
> ```
> 
> instead of this one:-
> 
> ```
> [   324.533] (==) ServerLayout "X11 Server"
> ```
> 
> Can you try a couple of things for me?
> 
>     1. Log the output of `grep layout /etc/X11/xorg.conf.d/* /usr/share/X11/xorg.conf.d/*`
> 
>     2. Add these lines to the `[Xorg]` stanza in `/etc/xrdp/sesman.ini`:-
>        ```
>        param=-layout
>        param=X11 Server
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        Then `sudo systemctl restart xrdp-sesman` and see if that makes a difference.
> 
> 
> The first step above looks for where the other layout could be stored, and the second step tries forcing the layout we should be using.
> 
> Let us know how it goes.

Thanks it worked on Ubuntu 21.10

**Comment by Conor0Callaghan** [comment]
> There's no depedency there that I'm aware of.
> 
> It look like the X server is finding another layout which it's loading in preference to the one we want. You're getting this message:-
> 
> ```
> [    88.972] (==) ServerLayout "layout"
> ```
> 
> instead of this one:-
> 
> ```
> [   324.533] (==) ServerLayout "X11 Server"
> ```
> 
> Can you try a couple of things for me?
> 
> 1. Log the output of `grep layout /etc/X11/xorg.conf.d/* /usr/share/X11/xorg.conf.d/*`
> 2. Add these lines to the `[Xorg]` stanza in `/etc/xrdp/sesman.ini`:-
>    ```
>    param=-layout
>    param=X11 Server
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Then `sudo systemctl restart xrdp-sesman` and see if that makes a difference.
> 
> The first step above looks for where the other layout could be stored, and the second step tries forcing the layout we should be using.
> 
> Let us know how it goes.

Also fixed the issue on my Pi:

Raspberry Pi 4 Model B Rev 1.4
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
