### ISSUE TITLE
checkinstall used in xrdp-installer-1.2.1.sh can break the whole system

### ISSUE THREAD

**Issue by guyuming76** [neutrinolabs/xrdp#1780]
i installed xrdp with sound redirection using xrdp-installer-1.2.1.sh -c -s. It works well, the only thing is the audio quality is too bad to use.

i am trying to build a debug version of xrdp and run the following statement from the script alone.

sudo checkinstall --pkgname=xrdp --pkgversion=$pkgver --pkgrelease=1

i run it without the --default parameter, but it ask me several yes/no questions which i don't know how to answer. So, i decided to run the statement with --default again.

**I pressed Ctrl+C to break the checkinstall when it was waiting for my yes/no answer.** 

Then, everything went wrong, i cannot launch any program from KDE plasma start menu, i cannot even switch to another virtual terminal with Ctrl+Alt+F1(or F2,F3,...)

**I reboot the computer, ubuntu failed to boot, even with recovery mode,** it says something like   "/sbin/init   no such file or directory"

can anybody confirm that this is a serious issue of checkinstall? 

And modify the xrdp-installer script, not to use the dangerous checkinstall in it anymore?

**Comment by metalefty** [comment]
We're not responsible with such xrdp-installer scripts.

**Comment by metalefty** [comment]
Report it to the author.

**Comment by guyuming76** [comment]
> Report it to the author.

thanks, i just don't know how to contact the author, my system is just a dev/test machine, no big deal
