### ISSUE TITLE
XRDP over XVNC extremely sluggish on RHEL 8

### ISSUE THREAD

**Issue by athias** [neutrinolabs/xrdp#1781]
I have XRDP configured on RHEL 7 and 8.  They are configured near identical, and the XRDP was installed in the same manner:
- Server with GUI, graphical.target default
- xrdp and tigervnc-server installed
- xrdp enabled
- firewalld ports enabled
- connecting over VPN

When running on RHEL 7 there are no noticable delays or sluggishness.  When running on RHEL 8 every single action is delayed by 1-3 seconds in response.  This includes actions such as opening a terminal window, or moving a window to another location.

A console to the VM through VMware does not show the same delays.  Meaning there is some unique element of the RDP connection settings that is causing this sluggishness/delays.

The RHEL 8 box is a fresh install, with no unique elements other than those identified above.

**Comment by matt335672** [comment]
Interesting problem.

I'm assuming you're using EPEL. Both operating systems would seem to have the same version of xrdp available (0.9.14-3 as I write this), so if you've performed no other customisations you'll be running the same xrdp software and configurations in both cases. On both machines, `xrdp -v` will give you more detailed version information.

1-3 seconds is a big chunk of time. xrdp is acting as little more than a protocol converter in this situation, and there's nothing in the software I'm aware of which could account for this. This suggests you'll need to consider the problem from a more systemic perspective.

I've set up CentOS 7 and 8 boxes here (xrdp from EPEL in both cases), and I've connected to them from a Windows 10 client. Once I've done that, I can use `ss` to look at the TCP stats for the link from the VM to the Windows 10 box:-

<pre>
$ ss -it '( sport = 3389 )' 
State          Recv-Q          Send-Q                   Local Address:Port                             Peer Address:Port          
ESTAB          0               0                        172.19.64.109:ms-wbt-server                   172.19.73.183:60124         
	 cubic wscale:8,7 rto:238 rtt:37.759/22.026 ato:40 mss:1460 pmtu:1500 rcvmss:691 advmss:1460 cwnd:10 ssthresh:25 <b>bytes_sent:4815887</b> bytes_acked:4815887 bytes_received:25558 segs_out:4032 segs_in:1052 data_segs_out:3826 data_segs_in:291 send 3.1Mbps lastsnd:424277 lastrcv:132504 lastack:132520 pacing_rate 6.2Mbps delivery_rate 39.0Mbps delivered:3827 app_limited busy:12315ms sndbuf_limited:214ms(1.7%) rcv_space:29200 rcv_ssthresh:84622 minrtt:3.67
</pre>

I won't pretend I understand what a lot of these fields mean (and they differ between 7 and 8), but I can use the `bytes_sent` field to see how much data is sent when I move a window, or perform some other kind of operation. On the setup here, with no customisations, moving a terminal windows from one side of the screen to the other is more efficient on CentOS 8 than it is on 7. This may be down to the whacky CentOS 7 backdrop - I haven't investigated any further.

You mention a VPN. Where is this terminated? Is it terminated on the boxes, or is terminated on another appliance?

The VMWare console working is useful and rules out CPU/memory starvation as a cause. may give us a few clues. Here are a few questions which may be useful.
- Does the VMWare console route through the VPN?
- The VMWare console won't being going through the interface on the VM which the RDP connection is terminating on. CentOS 7 and 8 will be using different driver versions on their interfaces. Are you seeing packet drops on this interface? (use `ip -s link show <interface>` to see packet stats). Are there differences in the virtual network routing which could be significant?

Comparing bandwidths and latencies of the links between Windows and C7, and Windows and C8 could be useful. Bandwidths are easily measured using `iperf3` (available on Windows and in EPEL), and latencies can be inferred from the round-trip-times displayed by `ping` from Windows.

Sorry about the scattergun approach. I don't know about your architecture at all, and so it's pretty hard to suggest ways forward from here.

**Comment by athias** [comment]
I have multiple setups with different issues (and clearly some without any issues).  The one I'm most concerned with is clearly the RHEL 8 via xvnc over VPN.

The VPN in this case is connecting to an OpenVPN running on a PfSense Router.  This applies to the working RHEL 7 setup of XRDP over xvnc, as well as the console connection over VMWare.

As far as the virtual networking goes - Those are running over vlans on 10G switches with no significant configurations outside of ACLs.  Most traffic is separated onto several different switches, and no area is remotely saturated.

I'll certainly look into other options, but I'm in the same boat where I'm not sure what's causing the lag.

**Comment by matt335672** [comment]
Checking the bandwidth and latency between the Windows client and the C8 sounds like it's worth doing. It might point to possibilities like a duplicate MAC or a problem with the NIC driver on the VM.

**Comment by athias** [comment]
IPv6 was the culprit.  Past the VPN, IPv6 is disabled.  The OS was preferring IPv6, but could not route properly, causing a delay for all actions.  Once IPv6 was disable on the OS, everything worked fine to include remotely over the VPN.

**Comment by matt335672** [comment]
Thanks for the update - it might help someone else in the future with a similar issue.
