### ISSUE TITLE
Can I use client's camera as input device during video conferencing?

### ISSUE THREAD

**Issue by cheng-chang** [neutrinolabs/xrdp#1786]
If I use Windows RDP client to connect to a xRDP server, with audio and camera redirect enabled, if I remotely open a video conferencing app on the server, can I use the client's camera and audio as input during the video conferencing?

**Comment by matt335672** [comment]
For the client camera to work in a remote session, you'd need USB redirection which isn't implemented. So I don't believe it's possible to do what you are asking with xrdp.

**Comment by metalefty** [comment]
No update despite an answer is provided, closing.
