### ISSUE TITLE
Change listening port number?

### ISSUE THREAD

**Issue by CE1CECL** [neutrinolabs/xrdp#1788]
How do I change port 3389 to something else, not all public networks will allow that port. If the feature isn’t already there, please add, otherwise, let me know how to change it.

**Comment by matt335672** [comment]
It's the `port` setting in the `/etc/xrdp/xrdp.ini` file. The `man xrdp.ini` command will tell you more, and there are examples in the file.

There's a very good reason why this port is often blocked on public networks - the RDP protocol is susceptible to MITM and brute-force password attacks. A VPN or an ssh tunnel can provide far better security, and flexibility for that matter.

If you have to do expose your port on a public network, looking into 2FA as an additional security measure. See [this wiki page](/neutrinolabs/xrdp/wiki/Using-Authy-or-Google-Authenticator-for-2FA-with-XRDP) for an example.

Hope that's useful.

**Comment by CE1CECL** [comment]
That worked, Thanks!
