### ISSUE TITLE
Copying files from Win10 to Kubuntu20.04  and back

### ISSUE THREAD

**Issue by nikimagic** [neutrinolabs/xrdp#1791]
Copy   ctrl+c  win10,     ctrl+v  kubuntu  works well for text.

Copy files win10 to linux   only 1 time, then you need to reconnect xrdp.

Please help.

**Comment by matt335672** [comment]
Hi @nikimagic 

Can you give us more information please.

- Which version of Kubuntu are you running?
- What version of xrdp (output of `xrdp -v`)?
- How are you copying the files exactly? Is it control-c in win 10, then control-v in Kubuntu as it is for the text?

At the moment there's a bug which prevents files being copied from the `thinclient_drives` directory to the Linux side - see #1563. You can't do it this way.

**Comment by nikimagic** [comment]
Kubuntu 20.04  full update
xrdp 0.9.12

CTRL+C   win10   to  CTRL+V  Kubuntu
Text  good  copy
Files  only one copy.

**Comment by nikimagic** [comment]
how do i install the new version of xrdp v0.9.15 ???

**Comment by matt335672** [comment]
@nikmagic - I've tried reproducing this with a very simple test as follows:-

1. Kubuntu 20.04 VM running XRDP v0.9.12
2. Win 10 VM
3. Two files `temp1.txt` and `temp2.txt` in Documents on Win 10 machine, contents as follows:-
   <details>
   <summary>temp1.txt</summary>
   <pre>
   This is document 1
   </pre>
   </details>
   <details>
   <summary>temp2.txt</summary>
   <pre>
   This is document 2
   </pre>
   </details>
4. Connect to Kubuntu machine using the file [kubuntu-20.rdp](https://github.com/neutrinolabs/xrdp/files/5872583/kubuntu-20.rdp.txt). You will need to change the line `full address:s:kubuntu-20` to use this in your setup. Change `kubuntu-20` to the name of your target host.

4. Run `Dolphin` on Kubuntu and browse to home folder
5. Win 10 Explorer select `temp1.txt`, CTRL-C
6. Kubuntu Dolphin CTRL-V
7. Win 10 Explorer select `temp2.txt`, CTRL-C
8. Kubuntu Dolphin CTRL-V

That all seems to work OK. So there must be some difference between what I have and what you have. It could be RDP settings, filenames or file contents. Could you have a look at what I've done above and see what the differences are with your setup?

Regarding your second question, once Debian/Ubuntu is released with a version of XRDP it will stay the same except for security updates and important bug-fixes. So the 20.04 LTS versions of ?Ubuntu will only carry xrdp 0.9.12.

If you want to try 0.9.15 you'd have to build it yourself. There are instructions on the [wiki](https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8) if you're interested in trying this.

Finally, if you're running Kubuntu you might find the conversation at #1773 of some interest.

Let us know how you get on.

**Comment by nikimagic** [comment]
The first server copies everything well.
Second server does not copy
I don’t know yet where to look, what is the difference. I think

Both servers kubunta 20.04 full update

**Comment by matt335672** [comment]
It does sound rather difficult to debug.

I think you're right in that finding the difference between the two is a good place to start.

Possible areas I can think of are as follows. I expect you've tried a lot of these already:-
- Contents of `/etc/xrdp/sesman.ini`
- Login configurations. Using the same back-end (Xorg/Xvnc) on both servers.
- Windows client configurations. Try swapping the Windows clients between servers.
- Linux user configurations. Create new empty Linux accounts on both servers and try with those.

Has the first copy definitely finished before the second one is started? If it's a big file and a slow network it might be taking longer than expected. Disconnecting and reconnecting would stop the copy operation in progress.

**Comment by nikimagic** [comment]
Hi Matt

It turned out to be a working version on both servers.
1.sudo apt install xrdp
2. Edit /etc/xrdp/startwm.sh
3. Edit /etc/xrdp/xrdp_keyboard.ini
4. Copy /etc/polkit-1/localauthority/50-local.d/xrdp-kde.pkla (kubuntu gui reset)

5 Create new user
6 Delete old users

Copy files CTRL + C and CTRL + V ideally win 10 to kubuntu and back


[Kubuntu2004_ru_kb_xrdp.zip](https://github.com/neutrinolabs/xrdp/files/5900424/Kubuntu2004_ru_kb_xrdp.zip)

**Comment by matt335672** [comment]
If I understand you correctly it's working now. Is that right?

If so, we can close this one. If we get any more relevant information about exactly why it was behaving the way it was we can re-open it. Let me know.

**Comment by nikimagic** [comment]
Works, but I would like to test some more.
Let's wait a week.

**Comment by nikimagic** [comment]
large files 5 GB, copied to Linux, about 1 GB in size.
How to copy files 10 GB?
Copy-paste! Linux-> Windows.

**Comment by matt335672** [comment]
@nikimagic - I don't understand what you're asking above. Can you be clearer please?

**Comment by matt335672** [comment]
Closing - no more input.
