### ISSUE TITLE
xrdp 0.9.15 not working on Ubuntu 16.04.7

### ISSUE THREAD

**Issue by bakalov85** [neutrinolabs/xrdp#1794]
Hello, I followed these instructions to build: [https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8]( https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8)
I tried to install the latest versions of xrdp (0.9.15) and xorgrdp (0.2.15) on Ubuntu 16.04.7, but it didn't worked. Upon connecting I see the XRDP login screen, but after I login I see only a blank blue screen. Tested with MATE and XFCE.
Then I saw on the same page [https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8]( https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8)
that older versions are tested with Ubuntu 16.04.7 - xrdp 0.9.14 and xorgrdp 0.2.4, so I installed these and now it works.

**Comment by matt335672** [comment]
Hi @bakalov85 

The blue screen suggests your X server `Xorg` isn't starting correctly.

I suspect the 0.2.4 on the wiki page is a typo and it should be 0.2.14.

Do you want to try to get the latest version working correctly? If so, the following may be useful:
- Use a machine without the xrdp and xorgxrdp packages installed. These can clash with the ones you're building.
- It's often easier to get the `Xvnc` backend working first which doesn't need xorgxrdp.
- If the `Xvnc` backend works and the `Xorg` backend doesn't, there's a log file for `Xorg` in `$HOME/.xorgxrdp.$DISPLAY.log` which may be enlightening.

Let us know how you get on.

**Comment by bakalov85** [comment]
Hi, I installed several versions of xorgxrdp following the readme and now I don't know what version do I have. I cannot remove it with "sudo apt-get remove xordxrdp". Also about the "-hwe-16.04 suffixed packages" - some of my packages have "-hwe-16.04" and some don't. The dependencies in your readme - I tried installing both "hwe" and non-"hwe" packages. Now I really don't know what I've installed and whether my system is messed up or not.
XRDP works, but it is slow and laggy. I googled some optimizations about XRDP and applied them, but it still has some lag.
I did the manual build because "sudo apt-get install xrdp" gave me a very old version.
Why don't you release a single installation file like .DEB or .RPM, containing all the required files and scripts for the corresponding OS? With atomic installation and uninstallation. If I build from source and later decide to uninstall - there are some leftovers - dependencies.
The readme here seems very hacky and error-prone: https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8
No offence, I highly admire your work in this open-source project and Open Source as a whole. I just come from Windows and I am used to clicking "Install...Next...Next...Finish".
Thanks :)

**Comment by matt335672** [comment]
They're good questions and there's no offence taken. I'll try to explain why things are somewhat different from Windows.

When a developer targets Windows as a platform, there's not a great deal of variety in what's being targeted. On the other hand, there are all sorts of flavours of Linux distibutions. You're using Ubuntu, but there are many, many others. There's a list on [Wikipedia](https://en.wikipedia.org/wiki/List_of_Linux_distributions) which can give you some idea.

The distributions are responsible for taking the packages like xrdp from github and many other places and turning all the software into an actual consistent supportable product which is aimed at their users.

The software produced here by the xrdp project isn't intended directly for end-users. It's intended for the packagers working for the distributions. There's absolutely nothing to stop end users building xrdp directly, and it's a great way to take control of exactly what you are running. However, when you do that you're removing some of the safety nets that are provided for you by the distributions. You've already encountered what this can mean.

Your comments above about hwe packages is the result of decisions taken by the Ubuntu package maintainers to cope with changes in the X server. There's nothing we can do on this project to influence the decisions taken by the Ubuntu project, and nor should we. This is open source and it's really none of our business how people choose to use it.

I hope that's useful information about exactly what we do here and how the project works. Fell free to come back with other questions.

**Comment by matt335672** [comment]
Closing - no more input from user.
