### ISSUE TITLE
"Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory"  error in .xorgxrdp.10.log

### ISSUE THREAD

**Issue by guyuming76** [neutrinolabs/xrdp#1796]
i installed xrdp on gentoo with the Ace overlay(a non-official repository, since there is no xrdp package in gentoo official repository).

i use OpenRC in gentoo instead of systemd;

I had successfully installed xrdp on ubuntu 20.04 with the script from Griffon. But i noticed that the configuration on gentoo is different, for example, i cannot find a ssl-cert group on my gentoo.  Are there any configuration example for gentoo?

the desktop environment on gentoo is kde plasma;

after i entered xfreerdp command with correct argument, a black window appears for 2 or 3 seconds and disppears immediately.       the xrdp.log and xrdp-sesman.log looks similar as those in [](https://github.com/neutrinolabs/xrdp/issues/1783) 

the error message in xfreerdp side is: "ERRINFO_LOGOFF_BY_USER"

and i see error message in ~/.xorgxrdp.10.log :
 (EE) dbus-core: error connecting to system bus: org.freedesktop.DBus.Error.FileNotFound (Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory)

what can be wrong?

**Comment by matt335672** [comment]
Hi @guyuming76 

I'm not aware of any Gentoo users who have posted here.

I believe the error in .xorgxrdp.10.log is harmless and is generated by bits of the X server we don't interact with.

If you're getting as far as starting the X server, the problem is likely to be that sesman is unable to start a desktop. On a standard xrdp install, the script `/etc/xrdp/startwm.sh` looks for a desktop and runs it. Try running the script manually from the command line without a DISPLAY with this command:-

```
DISPLAY= bash -x /et/xrdp/startwm.sh
```

It might give you some clues as to what is going on.

**Comment by guyuming76** [comment]
> DISPLAY= bash -x /et/xrdp/startwm.sh

really thanks for this tip! i run it to find out that startwm.sh calls /etc/x11/xinit/xinitrc, and says twm, xterm, xclock is not found.
i installed twm, xterm, xclock then, after that, xfreerdp works with twm;

then, i modified startwm.sh, comment out the call to xinitrc and add startxfce4, now, xfreerdp works with xfce4
```

#!/bin/sh

# try hard to respect Gentoo's wm choice
. /etc/profile
[ -f /etc/rc.conf ] && . /etc/rc.conf
export XSESSION

USERINITRC="$HOME/.xinitrc"
if [ -f "$USERINITRC" ]; then
    . "$USERINITRC"
else
#    . /etc/X11/xinit/xinitrc
     startxfce4
fi

```

**Comment by matt335672** [comment]
Glad that works for you.

I thought from your initial message you were trying to use KDE plasma? On my Kubuntu system, there's an executable called `startplasma-x11`. I don't know whether this is the case on Gentoo or not.

Also, what login manager are you using on your login screen? If it's sddm, you might be able to find the script it's using to start plasma with `sddm --example-config | grep Session`

**Comment by guyuming76** [comment]
startplasma-x11 works for me. Thanks again!

by the way, modify the startwm.sh directly as i did above might be not so good,
now, i copy the /etc/X11/xinit/xinitrc to ~/.xinitrc, and modify it to start the desktop environment i want.

**Comment by matt335672** [comment]
I think that's a better idea - thanks for the update.

**Comment by aashipov** [comment]
Apologies for 'necrobumping'
Server: Gentoo, amd64, either openrc or systemd, desktop profile, Xfce
Client: Freerdp
Same error message 'Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory' in ~/.xorgxrdp.10.log
Solved by D-Bus installation according to https://wiki.gentoo.org/wiki/D-Bus

As Gentoo configuration expects ~/.xinitrc, you can launch Xfce with:
cat <<EOF | tee ${HOME}/.xinitrc
exec dbus-launch startxfce4
EOF

This solves #1797 as well
