### ISSUE TITLE
undefined reference to `SSL_CTX_set_options'

### ISSUE THREAD

**Issue by sydbarrett74** [neutrinolabs/xrdp#1799]
Hello,

I'm attempting to build xrdp 0.9.15 on FreeBSD 12.2 and get the following error when executing 'make':

```
  CCLD     xrdp
/usr/local/bin/ld: ../common/.libs/libcommon.so: undefined reference to `SSL_CTX_set_options'
collect2: error: ld returned 1 exit status
*** Error code 1

Stop.
make[2]: stopped in /usr/home/sydbarrett74/xrdp-0.9.15/xrdp
*** Error code 1
*** Error code 1
```

Please advise. TIA.

**Comment by matt335672** [comment]
Hi @sydbarrett74 

I haven't got a FreeBSD VM available at the moment, but I can hopefully give you some pointers.

We build xrdp on FreeBSD 12.1 as part of our CI, so this should be relatively straightforward.

The FreeBSD CI build is defined in [.cirrus.yml](/neutrinolabs/xrdp/blob/devel/.cirrus.yml). A recent log of mine is [here](https://cirrus-ci.com/task/4626177726873600). We seem to be using libressl.

Is that useful?

**Comment by sydbarrett74** [comment]
@matt335672 That worked! Thank you so much! I guess we can close this issue. :D
