### ISSUE TITLE
info for supported os

### ISSUE THREAD

**Issue by Nunya-9018** [neutrinolabs/xrdp#1809]
i used it on a arm divice worked fine

**Comment by matt335672** [comment]
Hi @Nunya-9018 

Thanks for the info.

This issue forum is primarily used for xrdp development, for people who are having problems or issues with xrdp.

Are you actually having a problem with xrdp which you wish to report?

**Comment by Nunya-9018** [comment]
um acctual im haveing trouble getting it to work on ubuntu 20.4

**Comment by matt335672** [comment]
More info is required.

1. What's the output of these commands:-
```
lsb_release --all
uname -a
sudo xrdp -v
```

2. Can we have a detailed description of the problem please?

**Comment by Nunya-9018** [comment]
thanks ill have to do it later sorry

**Comment by Nunya-9018** [comment]
![image](https://user-images.githubusercontent.com/73594766/108103366-d8669800-7057-11eb-972c-a0047c203376.png)
heres the output @matt335672

**Comment by Nunya-9018** [comment]
when i try to access the sesion i just get black screen after loging in

**Comment by matt335672** [comment]
Thanks.

A couple of questions for you:-
1. Are you trying to use the Xorg backend on the login screen on the Xvnc one?
2. When you get the black screen, could you enter the following command to get a system log from the last two minutes. Then post it here.:-
   ```
   sudo journalctl -S -2m
   ```

**Comment by Nunya-9018** [comment]
Xorg not vnc I can prob get you the logs later

**Comment by matt335672** [comment]
@Nunya-9018 - do you need more input on this?

**Comment by Nunya-9018** [comment]
Um no I think it's an issue with Ubuntu 20.1.4 it works fine on debian

**Comment by matt335672** [comment]
Thanks - I'll close this one for now then.

Feel free to open another issue if you want to get Ubuntu working and you're still having trouble. Many people are using xrdp fine on Ubuntu 20.4.

**Comment by Nunya-9018** [comment]
Okay it was just because it happened again on the same pc with a reload
