### ISSUE TITLE
Display settings and UX malfunctioning with RDP using xrdp 0.9.12

### ISSUE THREAD

**Issue by jamesjjcondon** [neutrinolabs/xrdp#1814]
Hi, 

I'm accessing Machine A, running Ubuntu 20.04, from various other machines. Some of the other machines are running Ubuntu 20.04, others Windows 10. Some are behind firewalls requiring VPN. 

Machine A has xrdp 0.9.12

When I rdp into Machine A (whether using remmina or Windows rdp) machine A desktop looks like this:
![image](https://user-images.githubusercontent.com/33615047/109407819-f9be7100-79d3-11eb-98d2-ba4a0318a3d9.png)

when in reality / it looks like this:
![image](https://user-images.githubusercontent.com/33615047/109407838-1195f500-79d4-11eb-9269-2009902efa96.png)

The odd thing is that, remotely, when I do things, like open a terminal, nothing appears, first image above is unchanged, but then when I look at Machine A directly, the terminal will have opened. 

Possibly relevant: 
I created /etc/polkit-1/localauthority.conf.d/02-allow-colord.conf and pasted the following to stop the annoying 'color managed device - auth required' pop-up:

```
`polkit.addRule(function(action, subject) {
 if ((action.id == "org.freedesktop.color-manager.create-device" ||
 action.id == "org.freedesktop.color-manager.create-profile" ||
 action.id == "org.freedesktop.color-manager.delete-device" ||
 action.id == "org.freedesktop.color-manager.delete-profile" ||
 action.id == "org.freedesktop.color-manager.modify-device" ||
 action.id == "org.freedesktop.color-manager.modify-profile") &&
 subject.isInGroup("{users}")) {
 return polkit.Result.YES;
 }
 });
```
from [here](https://c-nergy.be/blog/?p=12073)

and my /etc/X11/xrdp/corg.conf looks like this:

```
Section "ServerLayout"
    Identifier "X11 Server"
    Screen "Screen (xrdpdev)"
    InputDevice "xrdpMouse" "CorePointer"
    InputDevice "xrdpKeyboard" "CoreKeyboard"
EndSection

Section "ServerFlags"
    Option "DontVTSwitch" "on"
    Option "AutoAddDevices" "off"
EndSection

Section "Module"
    Load "dbe"
    Load "ddc"
    Load "extmod"
    Load "glx"
    Load "int10"
    Load "record"
    Load "vbe"
    Load "glamoregl"
    Load "xorgxrdp"
    Load "fb"
EndSection

Section "InputDevice"
    Identifier "xrdpKeyboard"
    Driver "xrdpkeyb"
EndSection

Section "InputDevice"
    Identifier "xrdpMouse"
    Driver "xrdpmouse"
EndSection

Section "Monitor"
    Identifier "Monitor"
    Option "DPMS"
    HorizSync 30-80
    VertRefresh 60-75
    ModeLine "1920x1080" 138.500 1920 1968 2000 2080 1080 1083 1088 1111 +hsync -vsync
    ModeLine "1280x720" 74.25 1280 1720 1760 1980 720 725 730 750 +HSync +VSync
    Modeline "1368x768" 72.25 1368 1416 1448 1528 768 771 781 790 +hsync -vsync
    Modeline "1600x900" 119.00 1600 1696 1864 2128 900 901 904 932 -hsync +vsync
EndSection

Section "Device"
    Identifier "Video Card (xrdpdev)"
    Driver "xrdpdev"
    Option "DRMDevice" "/dev/dri/renderD128"
    Option "DRI3" "1"
EndSection

Section "Screen"
    Identifier "Screen (xrdpdev)"
    Device "Video Card (xrdpdev)"
    Monitor "Monitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "640x480" "800x600" "1024x768" "1280x720" "1280x1024" "1600x900" "1920x1080"
    EndSubSection
EndSection
```

If anyone can point me in the right direction to get full remote use of machine A, that would be amazing. 

Thanks.

**Comment by aquesnel** [comment]
This feels like a bad display environment variable value. Can you please share the contents of the xrdp.ini file and which session arguments the connection is using?

Thanks

**Comment by metalefty** [comment]
What DE do you want to use really?

**Comment by matt335672** [comment]
I think there are two problems here:-

1. Using the same user on an RDP session and a console session doesn't work well, as `systemd --user` only expects one DE to be running at any one time for a user. This is outside our control. If you really have to use the same user for both on a systemd-based system, look at the [wiki](/neutrinolabs/xrdp/wiki/Debian-dbus-user-session-package), but expect some problems along the way.
2. XFCE (IIRC) is a bit funny about which desktops have been set on which screens. I suspect you'll find the console and RDP sessions have independent settings for the backdrop.

**Comment by jamesjjcondon** [comment]
Thanks all, 

Here's xrdp.ini:

some IPs redacted
`
[Globals]
; xrdp.ini file version number
ini_version=1

; fork a new process for each incoming connection
fork=true

; ports to listen on, number alone means listen on all interfaces
; 0.0.0.0 or :: if ipv6 is configured
; space between multiple occurrences
;
; Examples:
;   port=xxxx
;   port=unix://./tmp/xrdp.socket
;   port=tcp://.:xxxx                           xxx.x.x.x.xxx
;   port=tcp://:xxxx                            *:xxxx
;   port=tcp://<any ipv4 format addr>:xxxx      xxx.x.x.x.xxx
;   port=tcp6://.:xxxx                          ::1:xxxx
;   port=tcp6://:xxxx                           *:xxxx
;   port=tcp6://{<any ipv6 format addr>}:xxxx   {FC00:0:0:0:0:0:0:1}:xxxx
;   port=vsock://<cid>:<port>
port=xxxx

; 'port' above should be connected to with vsock instead of tcp
; use this only with number alone in port above
; prefer use vsock://<cid>:<port> above
use_vsock=false

; regulate if the listening socket use socket option tcp_nodelay
; no buffering will be performed in the TCP stack
tcp_nodelay=true

; regulate if the listening socket use socket option keepalive
; if the network connection disappear without close messages the connection will be closed
tcp_keepalive=true

; set tcp send/recv buffer (for experts)
#tcp_send_buffer_bytes=32768
#tcp_recv_buffer_bytes=32768

; security layer can be 'tls', 'rdp' or 'negotiate'
; for client compatible layer
security_layer=negotiate

; minimum security level allowed for client for classic RDP encryption
; use tls_ciphers to configure TLS encryption
; can be 'none', 'low', 'medium', 'high', 'fips'
crypt_level=high

; X.509 certificate and private key
; openssl req -x509 -newkey rsa:2048 -nodes -keyout key.pem -out cert.pem -days 365
; note this needs the user xrdp to be a member of the ssl-cert group, do with e.g.
;$ sudo adduser xrdp ssl-cert
certificate=
key_file=

; set SSL protocols
; can be comma separated list of 'SSLv3', 'TLSv1', 'TLSv1.1', 'TLSv1.2', 'TLSv1.3'
ssl_protocols=TLSv1.2, TLSv1.3
; set TLS cipher suites
#tls_ciphers=HIGH

; Section name to use for automatic login if the client sends username
; and password. If empty, the domain name sent by the client is used.
; If empty and no domain name is given, the first suitable section in
; this file will be used.
autorun=

allow_channels=true
allow_multimon=true
bitmap_cache=true
bitmap_compression=true
bulk_compression=true
#hidelogwindow=true
max_bpp=32
new_cursors=true
; fastpath - can be 'input', 'output', 'both', 'none'
use_fastpath=both
; when true, userid/password *must* be passed on cmd line
#require_credentials=true
; You can set the PAM error text in a gateway setup (MAX 256 chars)
#pamerrortxt=change your password according to policy at http://url

;
; colors used by windows in RGB format
;
blue=009cb5
grey=dedede
#black=000000
#dark_grey=808080
#blue=08246b
#dark_blue=08246b
#white=ffffff
#red=ff0000
#green=00ff00
#background=626c72

;
; configure login screen
;

; Login Screen Window Title
#ls_title=My Login Title

; top level window background color in RGB format
ls_top_window_bg_color=009cb5

; width and height of login screen
ls_width=350
ls_height=430

; login screen background color in RGB format
ls_bg_color=dedede

; optional background image filename (bmp format).
#ls_background_image=

; logo
; full path to bmp-file or file in shared folder
ls_logo_filename=
ls_logo_x_pos=55
ls_logo_y_pos=50

; for positioning labels such as username, password etc
ls_label_x_pos=30
ls_label_width=65

; for positioning text and combo boxes next to above labels
ls_input_x_pos=110
ls_input_width=210

; y pos for first label and combo box
ls_input_y_pos=220

; OK button
ls_btn_ok_x_pos=142
ls_btn_ok_y_pos=370
ls_btn_ok_width=85
ls_btn_ok_height=30

; Cancel button
ls_btn_cancel_x_pos=237
ls_btn_cancel_y_pos=370
ls_btn_cancel_width=85
ls_btn_cancel_height=30

[Logging]
LogFile=xrdp.log
LogLevel=DEBUG
EnableSyslog=true
SyslogLevel=DEBUG
; LogLevel and SysLogLevel could by any of: core, error, warning, info or debug

[Channels]
; Channel names not listed here will be blocked by XRDP.
; You can block any channel by setting its value to false.
; IMPORTANT! All channels are not supported in all use
; cases even if you set all values to true.
; You can override these settings on each session type
; These settings are only used if allow_channels=true
rdpdr=true
rdpsnd=true
drdynvc=true
cliprdr=true
rail=true
xrdpvr=true
tcutils=true

; for debugging xrdp, in section xrdp1, change port=-1 to this:
#port=/tmp/.xrdp/xrdp_display_10

; for debugging xrdp, add following line to section xrdp1
#chansrvport=/tmp/.xrdp/xrdp_chansrv_socket_7210


;
; Session types
;

; Some session types such as Xorg, X11rdp and Xvnc start a display server.
; Startup command-line parameters for the display server are configured
; in sesman.ini. See and configure also sesman.ini.
[Xorg]
name=Xorg
lib=libxup.so
username=ask
password=ask
ip=xxx.x.x.x
port=-1
code=20

[Xvnc]
name=Xvnc
lib=libvnc.so
username=ask
password=ask
ip=xxx.x.x.x
port=-1
#xserverbpp=24
#delay_ms=2000

[vnc-any]
name=vnc-any
lib=libvnc.so
ip=ask
port=ask5900
username=na
password=ask
#pamusername=asksame
#pampassword=asksame
#pamsessionmng=127.0.0.1
#delay_ms=2000

[neutrinordp-any]
name=neutrinordp-any
lib=libxrdpneutrinordp.so
ip=ask
port=askxxxx
username=ask
password=ask

; You can override the common channel settings for each session type
#channel.rdpdr=true
#channel.rdpsnd=true
#channel.drdynvc=true
#channel.cliprdr=true
#channel.rail=true
#channel.xrdpvr=true
`

@metalefty what does DE stand for?
Display Experience? the second one, as the first is unusable. 

@matt335672 I have other machines with, I think, the exact same setup that I can RDP to with no problems. So whatever issues are happening are unique to this machine. 

Cheers.

**Comment by matt335672** [comment]
Hi @jamesjjcondon 

DE - desktop environment.

As I said, your terminal issue is because the terminal program is confused as to which DISPLAY to open the terminal on.

Have a look at the environment variable `DBUS_SESSION_BUS_ADDRESS` in the sessions on your working machines and your non-working machine.

The bottom line is that `systemd --user` does not cover the use-case of both a remote GUI and a console GUI logged on with the same user at the same time. If you can get it working great, but you'll have less trouble in the long run if you can avoid this way of working. Please read the wiki page I linked above for pointers to more information on this.

**Comment by matt335672** [comment]
@jamesjjcondon - do you need any more help with this?
