### ISSUE TITLE
Custom banner bitmap must be multiple of 4 pixels wide

### ISSUE THREAD

**Issue by ekofluid-it** [neutrinolabs/xrdp#1819]
Custom bitmap is rendered incorrectly.

_Bitmap was created in Microsoft Paint (standard 24bit bmp)._

Bitmap and the result:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/0ZdP0Zb/banner1.png" alt="banner1" border="0"></a>
<a href="https://ibb.co/q9gcbpr"><img src="https://i.ibb.co/Y8d1vhL/bitmapinc.png" alt="bitmapinc" border="0"></a>

**Comment by matt335672** [comment]
@ekofluid-it - could I trouble you to add both images as github attatchments?

Neither of the links above are downloadable as image files with wget - they resolve to html files. Security issues aside, we can't be sure we're looking at what you're looking at. In particular, we need to see your raw bmp file, and the image you're displaying above looks like a png.

**Comment by jsorg71** [comment]
Can you try to align the width of the image to a multiple of 4

**Comment by ekofluid-it** [comment]
Hi guys, thanks for responding.

Here is original bmp file (in zip Github didn't allowed me to upload bmp)
[banner1_original.zip](https://github.com/neutrinolabs/xrdp/files/6081524/banner1_original.zip)

@jsorg71 Sorry, I don't understand what do you mean.

**Comment by ekofluid-it** [comment]
![bitmapinc](https://user-images.githubusercontent.com/79988180/109925316-e1936e00-7cc1-11eb-838b-56de33fd4666.PNG)

And I forgot here is results.

**Comment by jsorg71** [comment]
@ekofluid-it sorry, the image is 450x75, either change it to 448x75 or 452x75
I don't think height matters.

**Comment by ekofluid-it** [comment]
> @ekofluid-it sorry, the image is 450x75, either change it to 448x75 or 452x75
> I don't think height matters.

Uf i would like to use it in it's original size if that's possible.

**BUT I am convinced that is not the case i tried to cut the image to half and 4th of its length to determine if it's size error, yet effect was the same.**

**Comment by ekofluid-it** [comment]
> @ekofluid-it sorry, the image is 450x75, either change it to 448x75 or 452x75
> I don't think height matters.

IT WORKED, your solution to change it to 452x75 worked and now its displayed correctly

**Comment by matt335672** [comment]
Thanks @jsorg71

I suggest we leave this open for now as a minor issue that we can look at when we get a bit of time.
