### ISSUE TITLE
Kubuntu 21.04 Alfa  and  XRDP  0.9.12-1.1     PATH was not fixed

### ISSUE THREAD

**Issue by nikimagic** [neutrinolabs/xrdp#1827]
Hi Matt!

Test Kubuntu 21.04
KDE 5.21
Kernel   5.10.0-14-generic

`sudo apt install xrdp`                    old version 0.9.12  ?????
`sudo apt-get install timeshift`       new version  is ok

TimeShift  not work  -))

https://github.com/neutrinolabs/xrdp/issues/1773
https://bugs.launchpad.net/ubuntu/+source/xrdp/+bug/1911435

**Comment by matt335672** [comment]
Hi @nikimagic 

We can do no more than raise issues on Launchpad (or Salsa for Debian)  - it's up to downstream when (or if) they take these - they are an entirely different group of people. The fix I've suggested does not affect anything which is stored in our own git repo, so our hands are tied.

All the distros are different in this respect - if this was an EPEL issue on CentOS it would have been fixed very quickly.

I suggest you add yourself as a subscriber to the launchpad bug. which you can do on the right-hand side of the screen you've linked to above. You'll then be notified of any changes.

**Comment by nikimagic** [comment]
thank you very much,  Matt -)

**Comment by matt335672** [comment]
I've also sent a message to one of the Debian Bullseye team to see if the Launchpad fault is the best way to do this. There may be a better way.

**Comment by nikimagic** [comment]
Matt, very important, read carefully !!!
Plymouth+LUKS Bug and Reproducible Builds   ....  read more
https://blog.linuxmint.com/?p=4037

https://wiki.debian.org/UsrMerge

**Comment by nikimagic** [comment]
echo "$PATH"
XRDP  USER
/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin

echo "$PATH"
locale USER 
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
