### ISSUE TITLE
Does XRDP support printer redirection in new version.

### ISSUE THREAD

**Issue by Gpx45** [neutrinolabs/xrdp#1828]
Hello everyone, hopefully everyone's' having a good day.

So currently I have a Ubuntu 20.04LTS server in a Virtualbox VM. (USB option enabled.)

I've several users that have local printers and want to print to them. After searching I've found several other issues here that mentioned the same problem (pasted below), but they were of 2017. I wonder if at this point in time, xRDP supports printer redirection? Is the only way still through adding a network printer through cups and having the clients send jobs to it?

https://github.com/neutrinolabs/xrdp/issues/71

**Comment by metalefty** [comment]
What do you mean "in new version"? xrdp had never supported printer redirection even in older versions.

**Comment by Gpx45** [comment]
@metalefty My apologies, I meant past versions as you mentioned. I just wondering if they ever added that functionality into xrdp. So I really can't printers other than network printer via cups huh?

**Comment by metalefty** [comment]
There's no plan to support printer redirection now. There're lots of things to do that have more priority. However, if someone implements printer redirection, we're happy to merge it.

**Comment by bmullan** [comment]
@Gpx45 
Read about IPP (Internet Printing Protocol) which is supported by most modern Printers and also now supported by CUPS.

> **_Internet Printing Protocol (IPP)_**
> 
> **_IPP is the only protocol that CUPS supports natively and is supported by most network printers and print servers. IPP supports encryption and other security features over port 631 and uses the http (Windows), ipp, and ipps backends._** 

IPP is pretty simple to setup/configure and works for printing from Windows, Linux or MAC.

Best part is that once configured all IPP configured printers will show up in any Applications drop-down Print menu as a device you can select and print just like any local printer !

**https://openprinting.github.io/cups/**

**https://www.cups.org/doc/network.html**

**Comment by lakshmanpasala** [comment]
I am working on this, and will share a PR for folks who are interested.
