### ISSUE TITLE
After deleting xrdp.log file xrdp doesn't create new one

### ISSUE THREAD

**Issue by AdamPerkins** [neutrinolabs/xrdp#1829]
If you delete the xrdp.log file for whatever reason and you reboot the system you can't login remote.
xrdp doesn't create a new log file and isn't working. 

You need an alternative way to login and create manually xrdp.log(xrdp/adm/640). Normally an application creates a new empty log file if it is missing.

Tested on Ubuntu 20.10.

**Comment by matt335672** [comment]
Hi @AdamPerkins 

This is an artefact of the way that the Debian/Ubuntu developers package xrdp.

For excellent reasons, they run xrdp as an unprivileged user. I was impressed when I found this, so I've written it up on our wiki - see https://github.com/neutrinolabs/xrdp/wiki/Running-the-xrdp-process-as-non-root. In particular, read [this section](https://github.com/neutrinolabs/xrdp/wiki/Running-the-xrdp-process-as-non-root#write-to-the-log-file-1).

If you build xrdp from source and run in the default configuration, `xrdp` runs as root and does not have this particular problem.

We're unable to address this directly here, as nothing in this repository is causing the problem - you'll need to talk to the Debian package maintainers if it's causing you trouble.

I can however suggest a workaround, which is to use another `ExecStartPre` script for the xrdp service which will create the log file if it's not present.

Let me know if you'd like a hand with this.

**Comment by AdamPerkins** [comment]
Thank you for explaining this and the interesting Wiki article.
Now as I know the problem I can handle it.

However it can be very surprising for people if xrdp is maybe the only access to the host and they don't have physical access to the system.
