### ISSUE TITLE
Move mailing list to google groups

### ISSUE THREAD

**Issue by jsorg71** [neutrinolabs/xrdp#183]
The groups
xrdp-announce
xrdp-devel
xrdp-users

Tasks
1. move all the current email in xrdp-devel@sourceforge.net to xrdp-devel@googlegroups.com
2. email all currently subscribed users an invite.
3. an announcement

**Comment by jsorg71** [comment]
I moved the email and sent a notify to xrdp-devel@sf.net

**Comment by metalefty** [comment]
Thanks! I'm sorry that I couldn't help you despite I suggested migration.
