### ISSUE TITLE
Auth Window Will not Close - XRDP 0.9.12.1-1 (Win10 to Ubuntu 20.10)

### ISSUE THREAD

**Issue by Orph3usAtticus** [neutrinolabs/xrdp#1832]
When connecting via RDP from Windows 10 to Ubuntu 20.10, an authentication dialog boxes appear similar to the one below.  Unlike the normal authentication box, this one stalls if you type in your password - it grays out the the "Authenticate" button and will not leave the screen.

There is technically a work-around - click cancel - but then the color scheme is messed up (e.g. Dark theme turns to Light theme, etc).

While more of an annoyance than anything else, this is still a bug.

![image](https://user-images.githubusercontent.com/77453843/111325727-56f82a80-8642-11eb-80ea-c544c0a034e4.png)

**Comment by Orph3usAtticus** [comment]
I should clarify - after successfully connecting through XRDP, this behavior occurs.  Technically it is a native auth form from Groovy, but it only occurs in this fashion while RDP'ing to the box.

**Comment by Orph3usAtticus** [comment]
Further clarification - I tested against MobaXTerm basic X11 forwarding services as well.   While a clunkier connection, basic graphical forwarding does not cause the same issue, which seems to signal that the problem is with XRDP specifically.

**Comment by matt335672** [comment]
Hi @Orph3usAtticus 

The dialog appearing is a common issue with xrdp on Ubuntu if you're using the xorg backend. Ubuntu uses an framework called 'polkit' to authenticate what might be considered to be privileged actions. One such action is creating a 'color profile'.

If you're logging on on the console, polkit will automatically allow you to create a color profile. If you're logging on remotely you need to authenticate as an administrator.

You can work around this behaviour by either using the Xvnc backend, or configuring polkit to allow the action.

If you chose the second option beware - Ubuntu 20.04/20.10 still uses the [version 0.105 polkit](https://packages.ubuntu.com/groovy/policykit-1) which does not support writing Javascript rules. Many sites on the Internet make this mistake. What can happen if you do this is that polkit crashes. The dialog is removed, but not in the way you think!

The following 3-line file `/etc/polkit-1/localauthority.conf.d/10-remote-color-profile.conf` works for me on Ubuntu 20.04:-

```
[Configuration]
Action=org.freedesktop.color-manager.create-*
ResultAny=yes
```

That's the good news. The bad news is that we can't fix this here. We're an upstream project, and we have no control over how xrdp is packaged by the distros. The file I've given you above is useless for Fedora/EPEL for example, as they use a later version of polkit. This bug has already been raised as debian bug [907878](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907878). The Debian bug tracker is definitely the right place to raise this, but I can't comment on why it is getting relatively little attention I'm afraid.

**Comment by metalefty** [comment]
This is a polkit issue, not xrdp itself.
