### ISSUE TITLE
after entering credentials connection does nothing for long time then generates error dialog

### ISSUE THREAD

**Issue by myusrn** [neutrinolabs/xrdp#1837]
This is the same error dialog outlined in sep 14, 2020 https://github.com/neutrinolabs/xrdp/issues/1687 submission.  [ fyi, @matt335672 and @deeplee who iterated on that ]

I have a recently repaved win10 20h2 (19042.868) enterprise install that added wsl2 and kali-linux 2021.1 and ubuntu 20.04 distro installs to.

I have `xrdp/kali-rolling,now 0.9.12-1.1 amd64 [installed]` and `xrdp/focal,now 0.9.12-1 amd64 [installed]` respectively installed in these environments.  I have applied the following xrdp settings to ensure they are listening on different ports in spite of the vms both having the same `ip add` which i understand is by design.
```
# sudo sed -i 's/3389/3390/g' /etc/xrdp/xrdp.ini # for kali-linux distro install
# sudo sed -i 's/3389/3391/g' /etc/xrdp/xrdp.ini # for Ubuntu distro install 
```
What seems to be happening is whatever distro i first run `sudo service xrdp start` on that's the one i can successfully establish remote desktop client connections to from my windows host.  In the case of the distro(s) that were not the first where `sudo service xrdp start` was run the experience is you get the x credentials collection dialog followed by a solid colored background that just does nothing for appx 3 - 5 minutes followed by a dialog with the details listed below.

I can repro this problem by executing `wsl --shutdown` to stop both kali-linux and ubuntu running distros following by reopening terminal sessions to both.  Once there if i change which distro i first run `sudo service xrdp start` on that will define which distro i can successfully establish remote desktop connection to from my windows host and the other will then become the one that hangs for appx 3 - 5 minutes following credentials collection and eventually displays dialog with details listed below. 

```
Connecting to sesman IP 127.0.0.1 port 3350
sesman connect ok
sending login info to session manager, please wait...
login successful for display 12
started connecting
connection problem，giving up
some problem
```

[.xsession-errors file](https://mysawestus.blob.core.windows.net/public/xrdp-fail-xsession-errors.txt)
[xrdp-fail-kali-linux dialog](https://mysawestus.blob.core.windows.net/public/xrdp-fail-kali-linux.png)
[xrdp-fail-ubuntu dialog](https://mysawestus.blob.core.windows.net/public/xrdp-fail-ubuntu.png)

**Comment by matt335672** [comment]
Hi @myusrn 

Your two distros are likely to be interfering with each other, as I believe they're running in the same virtual machine. Here's a similar problem:-

https://github.com/microsoft/WSL/issues/4304

You could try addressing this by reconfiguring one of your distros to have sesman listening on a different port and using a different X server port range. So on one of your distros, edit `/etc/xrdp/sesman.ini` and change the `ListenPort` to `3351`, and the `X11DisplayOffset` to `15`.

**Comment by myusrn** [comment]
Excellent thank you for the response and guidance on how to resolve this.  

I made the following edits to the `/etc/xrdp/sesman.ini` on my wsl2 ubuntu 20.04 distro install and after doing that, coupled with the `/etc/xrdp/xrdp.ini` listening ports edits outlined in my initial issue post, i can now successfully establish remote desktop connections to both the kali-linux and ubuntu distros. 
```
sudo cp /etc/xrdp/sesman.ini /etc/xrdp/sesman.ini.bak
sudo sed -i 's/ListenPort=3350/ListenPort=3351/g' /etc/xrdp/sesman.ini # 3350(default) for kali-linux, 3351 for Ubuntu and 3352 for next
sudo sed -i 's/X11DisplayOffset=10/X11DisplayOffset=15/g' /etc/xrdp/sesman.ini # 10(default) for kali-linux, 15 for Ubuntu and 20 for next
```

**Comment by matt335672** [comment]
Great - thanks for letting us know this is resolved. Not everyone does!
