### ISSUE TITLE
No sound in Hyper-V enhanced session mode when pulseaudio is started by systemd

### ISSUE THREAD

**Issue by jph09** [neutrinolabs/xrdp#1838]
Hello! I'm running the latest version of Kali Linux (Xfce desktop environment) in Hyper-V and trying to enable enhanced session mode with sound. 

- xrdp version 0.9.12 (from kali repository)
- pulseaudio version 14.2 (from kali repository)
- pulseaudio-module-xrdp (from github)

Everything works _except_ each time I log in there is no sound until I do:
```
systemctl --user stop pulseaudio.socket pulseaudio.service
pulseaudio --start
```

It seems like systemd isn't passing the right environment variables to pulseaudio. When starting manually within the user session, everything works fine.

**What I have tried**

- Adding the xrdp modules to /etc/pulse/default.pa (or replacing /etc/pulse/default.pa with a link to /etc/xrdp/pulse/default.pa) - in this case the xrdp-sink ouput device does show up and I even see the volume meter moving in pavucontrol, but still no sound heard. I assume pulseaudio module-xrdp-sink is not writing to the right socket but haven't confirmed.
- Masking the pulseaudio.socket and pulseaudio.service so that pa is not started by systemd - but then I couldn't work out how to get pulseaudio to autostart by any other means. (Probably due to my inexperience with Linux desktop environments particularly Xfce). 

**What I would like**

- Pulseaudio should start automatically on login (via systemd or otherwise) and pass sound through the RDP session. 

I have tried to find the solution through search engines but most articles seem to be some years old, very little relevant to Hyper-V enhanced session mode, and barely anything relevant to pulseaudio being started by systemd. Any pointers of where to look, or what to search for would be appreciated.

**Comment by jsorg71** [comment]
Pulseaudio should start when the first audio client tried to connect to the pulseaudio daemon.  Note there is a daemon for each login.  Check if autospawn is disabled in /etc/pulse/client.conf and/or /etc/pulse/client.conf.d/

**Comment by jph09** [comment]
Thanks for the reply!

`/etc/pulse/client.conf` and `/etc/pulse/daemon.conf` are both default with all lines commented.
`/etc/pulse/client.conf.d/01-enable-autospawn.conf` symlinks to `/run/pulseaudio` (which doesn't exist). I have tried removing this, it doesn't help.
There is no pulseaudio config under `~/.config`.

In my naivete I might suppose that the "best" solution would be to stick with systemd and get it to pass the right env variables for pulseaudio and pulseaudio-module-xrdp. But I don't know how I would go about doing that...

**Comment by jsorg71** [comment]
I installed Kali, interesting distro.  I got audio working but I had to uncomment the "autospawn = yes" in /etc/pulse/client.conf
This looks like a pulseaudio bug, as the defaults should be what's commented out.
It looks like this is built on Debian testing so bugs might be expected.
Anyway, you can't use systemd to start pulseaudio with xrdp as it needs the env var PULSE_SCRIPT set so autoapawn is best.  Also note, you should reboot or kill all pulseaudio processes after changing the config.

**Comment by jsorg71** [comment]
After rebooting I noticed that again pulseaudio was starting wrong.
systemd was starting it somehow.

I was able to disable systemd's pulseaudio startups with
systemctl --user disable pulseaudio.socket
systemctl --user disable pulseaudio.service
systemctl --user mask pulseaudio.socket
systemctl --user mask pulseaudio.service

Now I can reboot and login and no pulseaudio issues.  RDP audio works great.

**Comment by jph09** [comment]
Thanks that works! 😁

I had already noticed that `systemd --user mask...` was needed. The thing I hadn’t thought to do was uncomment `autospawn = yes`. Very obvious with hindsight... Guess I assumed the defaults wouldn’t have changed!

As you note Kali is based on Debian Testing. If pulseaudio behaviour is going to change in future stable releases to prefer systemd then this might catch more people out.

**Comment by jsorg71** [comment]
For searches, it looks like everything can be done in one command
sudo systemctl enable pulseaudio-enable-autospawn
for newer Debian and Ubuntu distros using systemd
