### ISSUE TITLE
xrdp doesn't work with wildcard SSL certificates

### ISSUE THREAD

**Issue by neuhaus** [neutrinolabs/xrdp#1841]
When using a wildcard certificate, the connection can't be established.

Here is a logfile extract using DEBUG loglevel:

```
[20210325-16:37:40] [DEBUG] TLSv1.3 enabled
[20210325-16:37:40] [DEBUG] TLSv1.2 enabled
[20210325-16:37:40] [DEBUG] Security layer: requested 11, selected 1
[20210325-16:37:43] [DEBUG] Closed socket 12 (AF_INET 10.0.0.5:3389)
```
Not very helpful i'm afraid.

**Comment by matt335672** [comment]
Thanks for the report @neuhaus

Can you give us a text dump of some fields of your public cert (i.e. using `openssl x509 -noout -text`). It'll save a bit of time. We don't need it all, but please include the validity, subject, SANs, Key Usage and Extended Key Usage fields. We can then try to re-create the issue.

**Comment by matt335672** [comment]
Also, if you're trying to use ECC see #1776. Versions of xrdp up to and including v0.9.15 can only handle RSA certs.

**Comment by neuhaus** [comment]
I can provide this information on Monday, thanks for looking into it.

**Comment by moobyfr** [comment]
we use wildcard certs without problem since several years, the details are perhaps related to ECC

**Comment by neuhaus** [comment]
Here is the certificate info:

`# openssl x509 -noout -text< server_chained.crt 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            ...
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = DigiCert Inc, OU = www.digicert.com, CN = RapidSSL RSA CA 2018
        Validity
            Not Before: Jun 30 00:00:00 2020 GMT
            Not After : Jul  1 12:00:00 2022 GMT
        Subject: CN = *.domain.de
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    ...
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Authority Key Identifier: 
                keyid:...

            X509v3 Subject Key Identifier: 
                ...
            X509v3 Subject Alternative Name: 
                DNS:*.domain.de
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:http://cdp.rapidssl.com/RapidSSLRSACA2018.crl

            X509v3 Certificate Policies: 
                Policy: 2.16.840.1.114412.1.2
                  CPS: https://www.digicert.com/CPS
                Policy: 2.23.140.1.2.1

            Authority Information Access: 
                OCSP - URI:http://status.rapidssl.com
                CA Issuers - URI:http://cacerts.rapidssl.com/RapidSSLRSACA2018.crt

            X509v3 Basic Constraints: 
                CA:FALSE
            CT Precertificate SCTs: 
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : ...
                    Timestamp : Jun 30 07:..:... 2020 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                ...
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : ...
                    Timestamp : Jun 30 07:..:... 2020 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                ...
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : ...
                    Timestamp : Jun 30 07:..:... 2020 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                ...
    Signature Algorithm: sha256WithRSAEncryption
         ...
`

Hope it helps!

**Comment by matt335672** [comment]
Thanks.

Your cert looks OK to me. 

As @moobyfr says, wildcards should be fine. As a TLS server, we simply present the certificate(s), and it's up to the client as to what the client does with them. I'll freely admit that our error reporting in this area is poor.

One important question springs to mind. Are you sending the intermediate certificate to your client as well as your wildcard certificate? If you aren't try appending the intermediate cert to your wildcard cert in the certificate file.

A couple of other debugging tips for you:-
- if you're able, use remmina/freerdp from the command-line to attempt a connection. You may get better error reporting that what's available from our side.
- Wireshark is able to find the TLS handshake in the RDP protocol datastream, despite the handshake not occurring at the start. You should be able to see the certificate chain (intermediate ~+ wildcard) in the output.

Please let us know if that's useful. If not, we'll try to figure out some other way to get your certificate working.

**Comment by matt335672** [comment]
In the absence of any other information, I'm pegging this to be closed by a PR submitted for review.

**Comment by buhtz** [comment]
Maybe your user needs ssl-cert membership.
Does `sudo usermod -a -G ssl-cert xrdp` help?
