### ISSUE TITLE
Trying hard to get my sound redirected from my remote computer which is a RPI 4b running Kali Linux to RDP on Windows10

### ISSUE THREAD

**Issue by aaronquiamco** [neutrinolabs/xrdp#1842]
I have xrdp and it is working fine when I'm doing a remote session on my Windows 10 machine but I can't get the sound working. I did pulseaudio thing via this website: https://github.com/neutrinolabs/pulseaudio-module-xrdp/wiki/README but I'm having a problem when trying to build xrdp source / sink modules. It shows me this:

```
┌──(rootkali)-[/home/sscoconut/pulseaudio-module-xrdp]
└─# make                                                                     
make  all-recursive
make[1]: Entering directory '/home/sscoconut/pulseaudio-module-xrdp'
Making all in src
make[2]: Entering directory '/home/sscoconut/pulseaudio-module-xrdp/src'
  CC       module_xrdp_sink_la-module-xrdp-sink.lo
module-xrdp-sink.c:26:10: fatal error: config.h: No such file or directory
   26 | #include <config.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:481: module_xrdp_sink_la-module-xrdp-sink.lo] Error 1
make[2]: Leaving directory '/home/sscoconut/pulseaudio-module-xrdp/src'
make[1]: *** [Makefile:420: all-recursive] Error 1
make[1]: Leaving directory '/home/sscoconut/pulseaudio-module-xrdp'
make: *** [Makefile:352: all] Error 2
┌──(rootkali)-[/home/sscoconut/pulseaudio-module-xrdp]
└─#      

```

Any help?

**Comment by matt335672** [comment]
`config.h` is part of the pulseaudio build, or more exactly the pulseaudio configure.

You'll need to follow the Wiki instructions for [Debian 8 / Ubuntu](/neutrinolabs/pulseaudio-module-xrdp/wiki/README#debian-9--ubuntu) to get the pulseaudio sources and configure pulseaudio. After doing that, `config.h` should be in the pulseaudio build directory. When you configure the xrdp module, you point `PULSE_DIR` at that directory.

Does that make sense?

**Comment by aaronquiamco** [comment]
> `config.h` is part of the pulseaudio build, or more exactly the pulseaudio configure.
> 
> You'll need to follow the Wiki instructions for [Debian 8 / Ubuntu](/neutrinolabs/pulseaudio-module-xrdp/wiki/README#debian-9--ubuntu) to get the pulseaudio sources and configure pulseaudio. After doing that, `config.h` should be in the pulseaudio build directory. When you configure the xrdp module, you point `PULSE_DIR` at that directory.
> 
> Does that make sense?

Hello, I successfully managed to have  xrdp source / sink modules when I put this on the terminal:
```
ls $(pkg-config --variable=modlibexecdir libpulse)
```
But the problem is I still can't hear any sounds from my remote computer. When I ran the pavumeter, it is moving but I have no sounds.

**Comment by matt335672** [comment]
Your pulseaudio daemon is almost certainly being started as part of your `systemd --user` services, before you connect via xrdp. It's a consequence of the systemd design.

If that is the case, you can either start a new pulseaudio daemon when you log in (`pulseaudio -k` should do it), or look at adding the xrdp module(s) to the existing daemon with `pactl`. It's not something I've looked at I'm afraid,

**Comment by gamersalpha** [comment]
hello i got the same probléme with kali

**Comment by matt335672** [comment]
I'm closing this issue now. Version 0.6 of the pulseaudio module [has been released](/neutrinolabs/pulseaudio-module-xrdp/releases/tag/v0.6) with significant changes, and the [wiki README](/neutrinolabs/pulseaudio-module-xrdp/wiki/README) has been updated with better build instructions.
