### ISSUE TITLE
Devel as of march 22nd results in no screen

### ISSUE THREAD

**Issue by sshaikh** [neutrinolabs/xrdp#1844]
When building head of devel, I've had an amusing issue where no screen gets rendered even though a desktop exists and keystrokes work. Reverting to 0.9.15 tag fixes the issue, although I still have a corrupted pointer (which may be due to other issues)

**Comment by matt335672** [comment]
If you're using Xorg, you'll need to rebuild xorgxrdp (from devel head) to use the head of xrdp devel. See #1813 and neutrinolabs/xorgxrdp#184. Could that be it?

**Comment by sshaikh** [comment]
It's almost certainly this, as I use latest release of xorgxrdp. Happy to close.
