### ISSUE TITLE
stop / disable  creating XRDP .xorg.log  files on the home dir

### ISSUE THREAD

**Issue by jeet1990** [neutrinolabs/xrdp#1845]
hi,

i have ubuntu 20.04 desktop and xrdp is version (0.9.12-1).

multiple below files are created in my home dir 

-rw-rw-r--  1 saan saan   221 Mar 27 22:11 .wget-hsts
-rw-------  1 saan saan   168 Mar 27 22:09 .Xauthority
-rw-r--r--  1 saan saan 19723 Mar 27 22:11 .xorgxrdp.10.log
-rw-r--r--  1 saan saan 20732 Mar 25 16:44 .xorgxrdp.10.log.old
-rw-r--r--  1 saan saan 20847 Mar 25 21:31 .xorgxrdp.11.log
-rw-r--r--  1 saan saan 22993 Mar 25 20:09 .xorgxrdp.11.log.old
-rw-r--r--  1 saan saan 20727 Mar 25 18:57 .xorgxrdp.12.log
-rw-------  1 saan saan 15806 Mar 27 22:09 .xsession-errors

please help me to config to disable this or create in a different dir.
thanks.

**Comment by matt335672** [comment]
Hi @jeet1990 

`.wget-hsts` is not xrdp related. See `man -s1 wget` for more info on this file.

The `.Xauthority` file is written to wherever the environment variable `XAUTHORITY` is defined to point to. You should be able to set this in your profile somewhere. If you're using bash, try adding this to your `~/.bash_profile`:-

```
if [ -n "$DISPLAY" ]; then
    export XAUTHORITY=$HOME/xstuff/Xauthority
fi
```

You'll need to create `~/xstuff`, or use a different directory.

To move the .xorgxrdp* files, edit `/etc/xrdp/sesman.ini`. Locate the line `param=.xorgxrdp.%s.log` and replace it with `param=xsuff/.xorgxrdp.%s.log` (or specify a different directory).

`.xsession-errors` is created by `/etc/X11/Xsession`, so unless you want to edit a system-provided file (not recommended) you're stuck with it.

Does that help?
