### ISSUE TITLE
Shared clipboard does not work if libvnc.so and Vino are used 

### ISSUE THREAD

**Issue by yamah-byv** [neutrinolabs/xrdp#1846]
Hello.
The clipboard are work in normally, if I use XOrg session (libxup.so). But, when I use VPN Session (libvpn,so) and connect to Vino the shared clipboard are not work.  When I connected to Vino by any VNC-client, shared clipboard are work in normally,

my config xrdp.ini
```
[Globals]
ini_version=1

fork=true

port=3389

use_vsock=false

tcp_nodelay=true

tcp_keepalive=true

security_layer=negotiate

crypt_level=high

certificate=
key_file=

ssl_protocols=TLSv1.2, TLSv1.3

autorun=

allow_channels=true
allow_multimon=true
bitmap_cache=true
bitmap_compression=true
bulk_compression=true
max_bpp=32
new_cursors=true
use_fastpath=both
enable_token_login=true

blue=009cb5
grey=dedede

ls_top_window_bg_color=009cb5

ls_width=350
ls_height=430

ls_bg_color=dedede

ls_logo_filename=
ls_logo_x_pos=55
ls_logo_y_pos=50

ls_label_x_pos=30
ls_label_width=65

ls_input_x_pos=110
ls_input_width=210

ls_input_y_pos=220

ls_btn_ok_x_pos=142
ls_btn_ok_y_pos=370
ls_btn_ok_width=85
ls_btn_ok_height=30

ls_btn_cancel_x_pos=237
ls_btn_cancel_y_pos=370
ls_btn_cancel_width=85
ls_btn_cancel_height=30

[Logging]
LogFile=xrdp.log
LogLevel=INFO
EnableSyslog=true

[LoggingPerLogger]

[Channels]
rdpdr=true
rdpsnd=true
drdynvc=true
cliprdr=true
rail=true
xrdpvr=true
tcutils=true

[Xorg]  
name=New Session
lib=libxup.so
username=ask
password=ask
pamsessionmng=127.0.0.1
ip=127.0.0.1 
port=-1
code=20
cliprdr=true

[Xvnc]
name=User Session
lib=libvnc.so
pamusername=ask
pampassword=ask
pamsessionmng=127.0.0.1
ip=127.0.0.1
port=5900
code=20
cliprdr=true
rdpdr=true
delay=1200
```
xrdp - 0.9.15
The connected user include in the groups tsusers,fuse.

What am I doing wrong?

**Comment by matt335672** [comment]
Hi @yamah-byv 

The clipboard in xrdp is handled by a program called xrdp-chansrv.

If you start a session using sesman (either with Xorg or Xvnc), xrdp-chansrv is started automatically for you. It is not however started as part of a session not managed by sesman, like your vino session.

I'd just started to write up instructions for starting `xrdp-chansrv` for Vino. However, I've hit a bug which is that xrdp-chansrv won't run on display zero. I'll raise a PR for this, but at the moment I can't offer you a good solution.

Are you by any chance able to build from source? If so, I can set a patch up for you.

Sorry about the hassle.

**Comment by yamah-byv** [comment]
Hi @matt335672 
I would really appreciate the patch.

**Comment by matt335672** [comment]
It's being worked on under PR #1849.

I'll add a comment to this thread when I've got something usable.

**Comment by yamah-byv** [comment]
@matt335672 Thank you very much!

**Comment by yamah-byv** [comment]
With the patches from #1849, it was possible to forward the clipboard to the Vino session. However, it was possible to do this only after I manually started in Vino-session
`/usr/sbin/xrdp-chansrv &`
and only then began to connect to the session.

**Comment by matt335672** [comment]
@yamah-byv. 

That's right. That's how it will have to be managed.

You'll also have access to other things chansrv provides, like shared drives.
