### ISSUE TITLE
Autologin user no support remote desktop

### ISSUE THREAD

**Issue by WQuit** [neutrinolabs/xrdp#1848]
In using Autologin user, mstsc no remote login.But delet /home/user/.Xauthority file,mstsc can login.
`cd  /home/username
rm .Xauthority`
`-rw-------  1 u    u        53 Mar 31 02:50 .Xauthority`
For any user,ss long as you have not logged in remotely,mstsc non login success.Delete `Xauthority`,mstsc can login.
What is the impact of 'Xauthority' files on xrdp  remote login?

**Comment by matt335672** [comment]
When you create a session, `xrdp-sesman` stores a shared secret in `$HOME/.Xauthority` which is shared between the X server and the X clients. This is a security measure to stop another user from connecting to your X server.

If sesman is unable to write to this file, the session is not created.

sesman uses the `xauth` command to access the X authority file.

When this happens again, can you do the following as your user `username`? Either log in using ssh, or use su/sudo to become `username`:-

```
export XAUTHORITY=$HOME/.Xauthority
ls -l $XAUTHORITY
xauth list
xauth add :99 MIT-MAGIC-COOKIE-1 1234567890
xauth remove :99
```

That will give us a clue as to why you can't write to this file.
