### ISSUE TITLE
Couldn't login with password contains '@'

### ISSUE THREAD

**Issue by mkaraki** [neutrinolabs/xrdp#1853]
I tried in xrdp 0.9.12-1 and xrdp v0.9.15 (from GitHub Release) on Ubuntu 20.04.

When password contains '@' xrdp shows 'xrdp login failed for display 0' error and couldn't connect.

Sorry for my bad English.

**Comment by metalefty** [comment]
Thanks for the report. I can reproduce the issue with b04fc6f.

**Comment by metalefty** [comment]
No, it actually doesn't reproduce for me. I can successfully login with the password contains `@`. 
The first time I tried to reproduce the issue, the keyboard layout was wrong.

Can you also confirm the keyboard layout?

**Comment by mkaraki** [comment]
Yes. I tried in same keyboard. and I uses password which ends with '@'.

**Comment by mkaraki** [comment]
Sorry. 100% my fault. I thought xrdp use same keymap with server or host. But xrdp login window uses another keymap.
Now I can login to xrdp session.

I'm sorry.

**Comment by metalefty** [comment]
See also this presentation how so specify keyboard layout. Starting from page 30.

https://xrdp.vmeta.jp/%E6%B4%BB%E5%8B%95%E5%AE%9F%E7%B8%BE?action=AttachFile&do=get&target=osc2016-tokyo-spring-xrdp-keylayout.pdf
