### ISSUE TITLE
XRDP rendering issue of wxPython (wxWidget) tree checkbox widget

### ISSUE THREAD

**Issue by msvalina** [neutrinolabs/xrdp#186]
Hi xrdp developers,

I'm using xrdp (0.0.9) and X11rdp(0.0.9) compiled with [X11RDP-o-Matic](https://github.com/scarygliders/X11RDP-o-Matic) on Ubuntu 12.04, and everything works fine except programs using wxPython (2.8.12.1) won't render checkboxes (wxWidget tree checkbox widget). I tried different wxPython (2.9) versions, window mangeres, rdp clients (remmina, win rdp), programs using wxPython ([RIDE](https://github.com/robotframework/RIDE),  [Task Coach](http://taskcoach.org/)) but bug persists. What is funny is that, when rdp client window is minimized and maximized, checkboxes appear but after scrolling or checking they disappear.

Here is screenshot of [RIDE](https://github.com/robotframework/RIDE) application:
![xrdp-pywxwidget-bug](https://cloud.githubusercontent.com/assets/413062/5028187/5c24118a-6b38-11e4-8b6b-7e48fe41c20d.png)

One more thing that is interesting is that when I take screenshot from connected remote machine screenshot does not show bug.

Thanks for nevertheless great xrdp and x11rdp,
Cheers!
msvalina

**Comment by jsorg71** [comment]
Wow, I finally found it.
It looks like we've been using the wrong clip for years.
I'll close this when I push a fix.

**Comment by jsorg71** [comment]
should be fixed in devel branch now, we'll cherry pick it into master and v0.8 after some testing

**Comment by msvalina** [comment]
I just build devel branch and it works! Thank you very much, folks in office also appreciate it!
