### ISSUE TITLE
xrdp-sesman does not inform pam about the remote hosts IP, although it knows 

### ISSUE THREAD

**Issue by mjhaase** [neutrinolabs/xrdp#1861]
With xrdp you cannot change pam-authentification based on the remote hosts IP, e.g. to require 2FA only from non-lokal clients.
This is because xrdp-sesmann does not pass the remote IP to pam.
Obviously xrdp-sesman knows about this remote IP, as it later on prints it out to the logfile.

Xrdp-sesman schould pass the remote hosts IP to pam along with the user credentials.

**Comment by metalefty** [comment]
Dup of #392.
