### ISSUE TITLE
 ./configure xrdp(latest) failed with No package 'check' found on Ubuntu 20.04

### ISSUE THREAD

**Issue by i928** [neutrinolabs/xrdp#1865]
cannot run ./configure on devel branch.
...
checking for CHECK... no
configure: error: Package requirements (check >= 0.10.0) were not met:

No package 'check' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

I can compile with 0.9.15 branch.

**Comment by aquesnel** [comment]
This should be fixed by #1860

**Comment by metalefty** [comment]
Merged #1860.
