### ISSUE TITLE
XRDP can not load cpu integrated graphics(amd renoir)

### ISSUE THREAD

**Issue by MoonChoi** [neutrinolabs/xrdp#1870]
first of all, please understand that there may be grammatical errors because my native language is not English.

My apu is amd 4300u apu(and no discrete graphics ) so I need to use Linux kernel 5.8 or over. I choose debian bullseye testing version and use unstable source to had overcame most of my issues related with amd apu.

Only remain issue(at this moments) is when I connect my debian server via xrdp, xrdp session can not recognized my integrated graphics.
When I try to connect with external monitor, GNOME recognize my graphics as a "AMD Renoir" and It working smoothly, but xrdp is not.
My expectation is that the GNOME settings screen shows the graphic as "AMD renoir", but it shows "llvmpipe".

<img width="628" alt="image" src="https://user-images.githubusercontent.com/24633560/116202282-5c827d80-a775-11eb-8aa3-ad5190675aa4.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/24633560/116202482-9bb0ce80-a775-11eb-9bc1-3126e7f3643a.png">

inxi -Fxz shows like below.
<img width="714" alt="image" src="https://user-images.githubusercontent.com/24633560/116204754-07943680-a778-11eb-929e-b3580fcb1dbd.png">

xrdp / Xorg package version like below.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/24633560/116203166-5f31a280-a776-11eb-85cd-26b78e5b4cdd.png">

It seems all driver installed well, but I don't know what is the problem.

If this isn't an issue, just a lack of technical understanding, I would also appreciate it if you let me know a forum that could help.

**Comment by matt335672** [comment]
Sorry we didn't get round to commenting on this.

This is normal behaviour. The AMD driver works with the local screen only. Also, the Debian xorgxrdp package doesn't enable glamor by default, so Mesa is the best you can get.
