### ISSUE TITLE
xrdp need to update to version 0.9.16 to match xorgxrdp version

### ISSUE THREAD

**Issue by i928** [neutrinolabs/xrdp#1871]
xorgxrdp configure failed with
configure: error: Package requirements (xrdp >= 0.9.16) were not met:

Requested 'xrdp >= 0.9.16' but version of xrdp is 0.9.15

**Comment by matt335672** [comment]
@i928 - you'll need to build xrdp first, then build xorgxrdp from it. To avoid any confusion, don't use a machine which already has xrdp installed.

**Comment by i928** [comment]
I have built xrdp first, than xorgxrdp. I also setup PKG_CONFIG_PATH environment.
Above error is after I compiled xrdp.

configure: error: Package requirements (xrdp >= 0.9.16) were not met:

Requested 'xrdp >= 0.9.16' but version of xrdp is 0.9.15

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables XRDP_CFLAGS
and XRDP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by matt335672** [comment]
The `pkgconfig` utility is finding a file `xrdp.pc` installed on your system from a 0.9.15 installation. 

Couple of options for you:-
- Install the new version of xrdp using `make install` and try again.
- If you've build xrdp on your current system in (for example) `/home/i928/xrdp`, use this command to configure xorgxrdp:-
   ```
   XRDP_CFLAGS="-I/home/i928/xrdp/common" ./configure
   ```
   Adjust the path in `XRDP_CFLAGS` as appropriate and don't forget the `/common` at the end.

**Comment by metalefty** [comment]
xrdp 0.9.16 hasn't been released but will be released in a few days. We're in preparation for the release. So the version requirement will never meet right now.  Don't be rushed and reporting issues one after another you met.  You should just wait until the release.
