### ISSUE TITLE
neutrinordp: Src/Dest IP address and Port are not logging in xrdp-sesman.log

### ISSUE THREAD

**Issue by TOMATO-ONE** [neutrinolabs/xrdp#1873]
Hi,
I am the administrator of an xrdp server 
running in NeutrinoRDP Proxy mode with PAM authentication enabled.

I am having problems with insufficient xrdp logging.
The current NeutrinoRDP Proxy mode does not show PAM username and IP address/port number together.

In managing the RDP Proxy, I would like to have the following elements logged on a single line.
”timestamp, xrdp_pid, PAM username , sorce IP:Port , dest IP:port , Target Username”.
In addition, I would like to see the time of connected and disconnected.

Reference:
Logs recorded by NeutrinoRDP Proxy mode in xrdp version 0.9.15
#xrdp.log
[20210430-00:34:57] [INFO ] freerdp_connect returned Success to destination :192.168.102.101:3389
#xrdp-sesman.log
[20210430-00:34:56] [INFO ] Access permitted for user: xrdpuser

**Comment by vandenbergjohannesgmailcom** [comment]
John dory is the difference
