### ISSUE TITLE
pipewire sound redirection

### ISSUE THREAD

**Issue by rafiks** [neutrinolabs/xrdp#1876]
Fedora 34 has switched to Pipewire from pulseaudio. is it possible to get sound redirection with it?

**Comment by metalefty** [comment]
No.

**Comment by metalefty** [comment]
PipeWire has a compatibility layer with PulseAudio. It might be possible via pipewire-pulse.

**Comment by matt335672** [comment]
I'm closing this and moving the discussion to #2023 - it's clearly going to come up multiple times.
