### ISSUE TITLE
No sound after installation

### ISSUE THREAD

**Issue by gamersalpha** [neutrinolabs/xrdp#1886]
Hello there so i m using Kali linux : 
version : 2021 -1

First i do this for the sound : 

```
# Step 0 - Open repository 
sudo nano /etc/apt/sources.list  

uncomment the line
deb-src http://http.kali.org/kali kali-rolling main contrib non-free
sudo apt-get update

sudo reboot

# Step 1 - Install Some PreReqs
sudo apt-get install git libpulse-dev autoconf m4 intltool build-essential dpkg-dev -y
sudo apt build-dep pulseaudio -y

#  Download pulseaudio source in /tmp directory - Do not forget to enable source repositories
cd /tmp
sudo apt source pulseaudio

# Compile
pulsever=$(pulseaudio --version | awk '{print $2}')
cd /tmp/pulseaudio-$pulsever
sudo ./configure

# Create xrdp sound modules
sudo git clone https://github.com/neutrinolabs/pulseaudio-module-xrdp.git
cd pulseaudio-module-xrdp
sudo ./bootstrap 
sudo ./configure PULSE_DIR="/tmp/pulseaudio-$pulsever"
sudo make

#copy files to correct location (as defined in /etc/xrdp/pulse/default.pa)
cd /tmp/pulseaudio-$pulsever/pulseaudio-module-xrdp/src/.libs
sudo install -t "/var/lib/xrdp-pulseaudio-installer" -D -m 644 *.so
```

andi install xrdp : 

```
sudo apt update
sudo apt install xrdp

sudo systemctl enable xrdp
sudo systemctl restart xrdp

sudo reboot
```
if sound not working when u start try this :  

`pulseaudio -k `

the xrdp works but i still not got sound, can u tell me what is wrong please

to got more information : 

![image](https://user-images.githubusercontent.com/32466950/118013151-1a9b2f00-b352-11eb-9ea1-4bfae8238d55.png)

the session rdp works and looks like sound works to, but i heard nothing :/

webologie : 
https://c-nergy.be/blog/?p=13655

**Comment by jsorg71** [comment]
xrdp needs pulseaudio to be in autospawn mode can you try
sudo systemctl enable pulseaudio-enable-autospawn
and reboot

**Comment by gamersalpha** [comment]
i got this : 


```
┌──(root💀kali)-[/home/issa]
└─# systemctl enable pulseaudio-enable-autospawn                                                                                                         1 ⨯
Synchronizing state of pulseaudio-enable-autospawn.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable pulseaudio-enable-autospawn
Failed to enable unit: Unit file /lib/systemd/system/pulseaudio-enable-autospawn.service is masked.

```

**Comment by gamersalpha** [comment]
still  not working 

the sound looks working but not : 

![image](https://user-images.githubusercontent.com/32466950/118016690-fc373280-b355-11eb-9a4d-6f3ea456d771.png)

**Comment by jsorg71** [comment]
first remove the mask
sudo rm /lib/systemd/system/pulseaudio-enable-autospawn.service
then enable autospawn
sudo systemctl enable pulseaudio-enable-autospawn

**Comment by gamersalpha** [comment]
`
```
┌──(issa㉿kali)-[~]
└─$ sudo rm /lib/systemd/system/pulseaudio-enable-autospawn.service
[sudo] Mot de passe de issa :

┌──(issa㉿kali)-[~]
└─$ sudo systemctl enable pulseaudio-enable-autospawn
pulseaudio-enable-autospawn.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable pulseaudio-enable-autospawn
```
`
i reboot but no working

i still got all working info but no sound came out

**Comment by jsorg71** [comment]
ok, cool, now when you run pavucontrol, what do you see in the 'output devices' and 'input devices' tabs?
You should see 'xrdp sink' and 'xrdp source'.

**Comment by gamersalpha** [comment]
i got the moving : 

![image](https://user-images.githubusercontent.com/32466950/118022713-ef6a0d00-b35c-11eb-99b9-2ded5dd79c8d.png)

![image](https://user-images.githubusercontent.com/32466950/118022742-fabd3880-b35c-11eb-8181-9236c9b8efeb.png)
![Uploading image.png…]()

![XCmfrIBZIx](https://user-images.githubusercontent.com/32466950/118023099-6b645500-b35d-11eb-927c-324eb4a41cf5.gif)

![JfYiA5Xsf2](https://user-images.githubusercontent.com/32466950/118023840-4d4b2480-b35e-11eb-8fe4-950bd151bfa0.gif)


but no sound :/

**Comment by jsorg71** [comment]
I think that says 'dummy' you don't want to see that.
Check in /usr/lib/pulse-14.2/modules/
Look for 2 files
module-xrdp-sink.so and module-xrdp-source.so

**Comment by gamersalpha** [comment]
i can't see this module : 

![image](https://user-images.githubusercontent.com/32466950/118024769-5be60b80-b35f-11eb-8646-94deea98f0e9.png)

**Comment by jsorg71** [comment]
That might be it.
Maybe you missed sudo make install after building them.

**Comment by gamersalpha** [comment]
i do all step
ok i will try again

**Comment by gamersalpha** [comment]
OK so i restart evrything from scratch and still not sound, what things i misss :/ 

![image](https://user-images.githubusercontent.com/32466950/118350368-864de980-b556-11eb-8568-4e76b93a9ed4.png)

i got modules in a good directory : 

![image](https://user-images.githubusercontent.com/32466950/118350390-a54c7b80-b556-11eb-811d-86f1263c9808.png)


i reboot and still no sound

thanks all

**Comment by gamersalpha** [comment]
ok now sounds works with command 👍 

`pulseaudio -k `


and on the desktop u can see this : 

![image](https://user-images.githubusercontent.com/32466950/118351731-e1370f00-b55d-11eb-8c0a-a69d1414b690.png)


![image](https://user-images.githubusercontent.com/32466950/118351740-f0b65800-b55d-11eb-9054-0e0353be65af.png)


so now it's o kthanks all :)

**Comment by metalefty** [comment]
Close if your issue solved.
