### ISSUE TITLE
Does Xrdp 0.9.5 only support IPV6 and not IPv4?

### ISSUE THREAD

**Issue by wangyu8460958** [neutrinolabs/xrdp#1888]
@matt335672，My OS is ubuntu 18.04.5。Xrdp is 0.9.5

it@it51:~$ sudo netstat -ptan | grep xrdp
tcp6       0      0 ::1:3350                :::*                    LISTEN      4576/xrdp-sesman
tcp6       0      0 :::3389                 :::*                    LISTEN      4587/xrdp

it@it51:~$ xrdp -v
xrdp: A Remote Desktop Protocol server.
Copyright (C) Jay Sorg 2004-2014
See http://www.xrdp.org for more information.
Version 0.9.5

Xrdp 0.9.5  only bind ipv6，Can it be bound to ipv4? If so, how should I configure it?

**Comment by matt335672** [comment]
Hi @wangyu8460958 

What's your question exactly? Do you want to connect from an IPv4 client, or do you only want to bind to ipv4? You should be able to connect just fine from an ipv4 client - that's just the way that the listening socket is displayed.

**Comment by wangyu8460958** [comment]
@matt335672 ,  I want to bind my ubuntu 18.04.5 machine with xrdp 0.9.5 to ipv4 only instead of ipv6, how should I do this? Because by default, after installing xrdp, it is bound to ipv6

**Comment by metalefty** [comment]
Probably dup of #1547.

**Comment by wangyu8460958** [comment]
@metalefty , you mean xrdp 0.9.5 Only ipv6 will be bound, not ipv4

**Comment by matt335672** [comment]
@metalefty's right - if you only want to use IPv4 with this version of xrdp you'll need to recompile it without IPv6 support.

**Comment by metalefty** [comment]
Consider using newer xrdp, for instance, upgrading Ubuntu to 20.04.

**Comment by metalefty** [comment]
Because we already have newer versions that fixes the issue, closing both.
