### ISSUE TITLE
xrdp session does not provide all authorizations when connecting to a Hyper-V vm running Opensuse Tumbleweed KDE

### ISSUE THREAD

**Issue by hardhu** [neutrinolabs/xrdp#1889]
Hello everybody,
I don't know if this is related to [https://github.com/neutrinolabs/xrdp/issues/1684](url).
I have installed xrdp 0.9.15.1.4 and xorgxrdp 0.2.15-1.4 on OpenSuse Tumbleweed (which is installed as guest on Hyper-V in a Win10 professional host, I don't know if this is relevant). When I connect to OpenSuse using Microsoft Remote Desktop client, I see the splash screen of Tumbleweed for some seconds and after that the screen becomes blank and the desktop is not loaded.
Moreover, after this, I cannot anymore do logout or poweroff/shutdown from KDE: clicking on the buttons in KDE panel has no effect.

**Comment by hardhu** [comment]
Strangely, if I replace the port to listen in `/etc/xrdp/xrdp.ini`  using `port=vsock://-1:3389` in order to enable enhanced session mode on Hyper-V to connect to guest Tumbleweed, desktop is loaded without problems. The only issue is that shutdown from KDE panel seems again not to work, but in this case what happens is that the screen becomes blank but the virtual machine is not turned off. I have to ssh from host and to poweroff it from console.

**Comment by matt335672** [comment]
Hi @hardhu 

That's a useful second piece of information. It points to there being possibly being two problems here. Let's look at your shutdown issue first.

KDE makes heavy use of polkit for authentication. Polkit treats local desktops differently from remote desktops for a good reason - it's not obvious what security policy needs to be applied to the desktop in question. For example, whereas you've happy to shut your local VM down from a remote desktop, a sys admin in charge of a shared resource might be less willing to grant that privilege to all the users.

The general procedure to fix this is to figure out what polkit action is being denied by polkit. You can then add a polkit rule to authorize that action for remote users. Ther's a KDE/Manjaro example [here](https://github.com/neutrinolabs/xrdp/issues/1584).

I'm not familiar with OpenSuSE. Can you have a look in the system log files and see if you're getting any useful authentication messages from `polkitd`?

The first issue you mention could be a number of things. An obvious first thing to check is that you're not logged in to the graphical console as the same user when you also connect over xrdp. Xrdp itself supports that, but sadly anything that relies on `systemd --user` (which is most Linux distros these days) will not.

**Comment by hardhu** [comment]
> Hi @hardhu
> 
> That's a useful second piece of information. It points to there being possibly being two problems here. Let's look at your shutdown issue first.
> 
> KDE makes heavy use of polkit for authentication. Polkit treats local desktops differently from remote desktops for a good reason - it's not obvious what security policy needs to be applied to the desktop in question. For example, whereas you've happy to shut your local VM down from a remote desktop, a sys admin in charge of a shared resource might be less willing to grant that privilege to all the users.
> 
> The general procedure to fix this is to figure out what polkit action is being denied by polkit. You can then add a polkit rule to authorize that action for remote users. Ther's a KDE/Manjaro example [here](https://github.com/neutrinolabs/xrdp/issues/1584).
> 
> I'm not familiar with OpenSuSE. Can you have a look in the system log files and see if you're getting any useful authentication messages from `polkitd`?
> 
> The first issue you mention could be a number of things. An obvious first thing to check is that you're not logged in to the graphical console as the same user when you also connect over xrdp. Xrdp itself supports that, but sadly anything that relies on `systemd --user` (which is most Linux distros these days) will not.

First of all, thanks a lot for your reply.
I start by report some tests I have made about the KDE shutdown issue. Following you suggestions in (https://github.com/neutrinolabs/xrdp/issues/1584) I have edited the `/usr/lib/systemd/system/polkit.service` in this way:

```
[Unit]
Description=Authorization Manager
Documentation=man:polkit(8)

[Service]
Type=dbus
BusName=org.freedesktop.PolicyKit1
# ExecStart=/usr/libexec/polkit-1/polkitd --no-debug
Environment=G_MESSAGES_DEBUG=all
ExecStart=/usr/lib/polkit-1/polkitd
```

However, after a reboot my OpenSuse virtual machine became unresponsive, and with  `sudo journalctl -u polkit`
 got a lot of this error messages:

May 21 11:51:59 localhost systemd[1]: Starting Authorization Manager...
May 21 11:51:59 localhost systemd[598]: polkit.service: Failed to execute command: No such file or directory
May 21 11:51:59 localhost systemd[598]: polkit.service: Failed at step EXEC spawning /usr/lib/polkit-1/polkitd: No such file or directory
May 21 11:51:59 localhost systemd[1]: polkit.service: Main process exited, code=exited, status=203/EXEC
May 21 11:51:59 localhost systemd[1]: polkit.service: Failed with result 'exit-code'.
May 21 11:51:59 localhost systemd[1]: Failed to start Authorization Manager.


Then I restored  `/usr/lib/systemd/system/polkit.service` to its original version, and, following [this example from Arch wiki](https://wiki.archlinux.org/title/Polkit#Debugging/logging), I have added the `/etc/polkit-1/rules.d/00-log-access.rules`:

```
    polkit.addRule(function(action, subject) {
    polkit.log("action=" + action);
    polkit.log("subject=" + subject);
});
```

But still I cannot find any useful messages about shutdown issue when checking with `sudo journalctl -u polkit`

I also tried to add the following rule (always following the configuration script for xrdp provided here [](https://github.com/microsoft/linux-vm-tools/blob/master/arch/install-config.sh)):


`/etc/polkit-1/rules.d/02-allow-colord.rules`

```
 polkit.addRule(function(action, subject) {
    if ((action.id == "org.freedesktop.color-manager.create-device" ||
         action.id == "org.freedesktop.color-manager.modify-profile" ||
         action.id == "org.freedesktop.color-manager.delete-device" ||
         action.id == "org.freedesktop.color-manager.create-profile" ||
         action.id == "org.freedesktop.color-manager.modify-profile" ||
         action.id == "org.freedesktop.color-manager.delete-profile") &&
        subject.isInGroup("users"))
    {
        return polkit.Result.YES;
    }
});
```

But at the moment I have no improvements. I will go on investigating, of course any help would be very appreciated.

**Comment by matt335672** [comment]
Hi @hardhu 

You were nearly there with your first editing of `/usr/lib/systemd/system/polkit.service`

The line you commented out :-

```
# ExecStart=/usr/libexec/polkit-1/polkitd --no-debug
```

tells you that on your system, the polkit daemon in at `/usr/libexec/polkit-1/polkitd`, and not at `/usr/lib/polkit-1/polkitd`.

The errors you're getting from systemd are telling you the same thing.

So the two lines you need adding to the systemd unit file for your system are:-

```
Environment=G_MESSAGES_DEBUG=all
ExecStart=/usr/libexec/polkit-1/polkitd
```

Does that make sense?

**Comment by hardhu** [comment]
Indeed! What a stupid miss from me! 
I have now edited correctly `/usr/lib/systemd/system/polkit.service` and I get a lot of "not authorized" lines. I try to report a summary here of `sudo journalctl -u polkit`

First lines are about starting Authorization Manager:

```
May 24 12:32:17 localhost systemd[1]: Starting Authorization Manager...
May 24 12:32:17 localhost polkitd[609]: Successfully changed to user polkitd
May 24 12:32:17 localhost polkitd[609]: Started polkitd version 0.118
May 24 12:32:18 localhost polkitd[609]: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
May 24 12:32:18 localhost polkitd[609]: Loading rules from directory /etc/polkit-1/rules.d
May 24 12:32:18 localhost polkitd[609]: Loading rules from directory /usr/share/polkit-1/rules.d
May 24 12:32:18 localhost polkitd[609]: 12:32:18.021: Loading rules from directory /etc/polkit-1/rules.d
May 24 12:32:18 localhost polkitd[609]: 12:32:18.021: Loading rules from directory /usr/share/polkit-1/rules.d
May 24 12:32:18 localhost polkitd[609]: Finished loading, compiling and executing 3 rules
May 24 12:32:18 localhost polkitd[609]: 12:32:18.025: Finished loading, compiling and executing 3 rules
May 24 12:32:18 localhost polkitd[609]: Entering main event loop
May 24 12:32:18 localhost polkitd[609]: Connected to the system bus
May 24 12:32:18 localhost polkitd[609]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
May 24 12:32:18 localhost polkitd[609]: 12:32:18.035: Acquired the name org.freedesktop.PolicyKit1 on the system bus
May 24 12:32:18 localhost systemd[1]: Started Authorization Manager.
```


Then there are some groups of lines fo this kind, with `user of caller is unix-user:root` and `user of subject is unix-user:sddm`
for which the authorization is given:

```
May 24 12:32:19 hyperarch.mshome.net polkitd[609]: system-bus-name::1.2 is inquiring whether system-bus-name::1.18 is authorized for org.freedesktop.login1.power-off
May 24 12:32:19 hyperarch.mshome.net polkitd[609]:  user of caller is unix-user:root
May 24 12:32:19 hyperarch.mshome.net polkitd[609]:  user of subject is unix-user:sddm
May 24 12:32:19 hyperarch.mshome.net polkitd[609]: checking whether system-bus-name::1.18 is authorized for org.freedesktop.login1.power-off
May 24 12:32:20 hyperarch.mshome.net polkitd[609]:   0x7f2fd4008b00
May 24 12:32:20 hyperarch.mshome.net polkitd[609]: Checking whether session 1 is active.
May 24 12:32:20 hyperarch.mshome.net polkitd[609]: Session 1 has UID 461.
May 24 12:32:20 hyperarch.mshome.net polkitd[609]: UID 461 has state active.
May 24 12:32:20 hyperarch.mshome.net polkitd[609]:  subject is in session 1 (local=1 active=1)
May 24 12:32:20 hyperarch.mshome.net polkitd[609]:  is authorized (has implicit authorization local=1 active=1)
```

the authorization being checked are for `org.freedesktop.login1.reboot`, `org.freedesktop.login1.suspend`, `org.freedesktop.login1.hibernate`

Then there is the first group of lines referring to KDE functions where authorization is not given:

```
May 24 12:33:19 hyperarch.mshome.net polkitd[609]: system-bus-name::1.27 is inquiring whether system-bus-name::1.25 is authorized for org.kde.kded.smart.smartctl
May 24 12:33:19 hyperarch.mshome.net polkitd[609]:  user of caller is unix-user:hardhu
May 24 12:33:19 hyperarch.mshome.net polkitd[609]:  user of subject is unix-user:hardhu
May 24 12:33:19 hyperarch.mshome.net polkitd[609]: checking whether system-bus-name::1.25 is authorized for org.kde.kded.smart.smartctl
May 24 12:33:19 hyperarch.mshome.net polkitd[609]:   0x7f2fd4008ec0
May 24 12:33:19 hyperarch.mshome.net polkitd[609]: Checking whether session c1 is active.
May 24 12:33:19 hyperarch.mshome.net polkitd[609]: Session c1 has UID 1000.
May 24 12:33:19 hyperarch.mshome.net polkitd[609]: UID 1000 has state active.
May 24 12:33:19 hyperarch.mshome.net polkitd[609]:  subject is in session c1 (local=0 active=1)
May 24 12:33:19 hyperarch.mshome.net polkitd[609]:  not authorized
```

The situation is however in some sense "mixed", since for other functions the authorization is given:

```
May 24 12:33:21 hyperarch.mshome.net polkitd[609]: system-bus-name::1.36 is inquiring whether system-bus-name::1.34 is authorized for org.kde.powerdevil.discretegpuhelper.hasdualgpu
May 24 12:33:21 hyperarch.mshome.net polkitd[609]:  user of caller is unix-user:hardhu
May 24 12:33:21 hyperarch.mshome.net polkitd[609]:  user of subject is unix-user:hardhu
May 24 12:33:21 hyperarch.mshome.net polkitd[609]: checking whether system-bus-name::1.34 is authorized for org.kde.powerdevil.discretegpuhelper.hasdualgpu
May 24 12:33:21 hyperarch.mshome.net polkitd[609]:   0x56211abd9750
May 24 12:33:21 hyperarch.mshome.net polkitd[609]: Checking whether session c1 is active.
May 24 12:33:21 hyperarch.mshome.net polkitd[609]: Session c1 has UID 1000.
May 24 12:33:21 hyperarch.mshome.net polkitd[609]: UID 1000 has state active.
May 24 12:33:21 hyperarch.mshome.net polkitd[609]:  subject is in session c1 (local=0 active=1)
May 24 12:33:21 hyperarch.mshome.net polkitd[609]:  is authorized (has implicit authorization local=0 active=1)
```

Also some functions related to freedesktop are not authorized:

```
May 24 12:33:21 hyperarch.mshome.net polkitd[609]: system-bus-name::1.40 is inquiring whether unix-process:1470:6755 is authorized for org.freedesktop.RealtimeKit1.acquire-high-priority
May 24 12:33:21 hyperarch.mshome.net polkitd[609]:  user of caller is unix-user:root
May 24 12:33:21 hyperarch.mshome.net polkitd[609]:  user of subject is unix-user:hardhu
May 24 12:33:21 hyperarch.mshome.net polkitd[609]: checking whether unix-process:1470:6755 is authorized for org.freedesktop.RealtimeKit1.acquire-high-priority
May 24 12:33:21 hyperarch.mshome.net polkitd[609]:   0x56211ade84f0
May 24 12:33:21 hyperarch.mshome.net polkitd[609]: Checking whether session c1 is active.
May 24 12:33:21 hyperarch.mshome.net polkitd[609]: Session c1 has UID 1000.
May 24 12:33:21 hyperarch.mshome.net polkitd[609]: UID 1000 has state active.
May 24 12:33:21 hyperarch.mshome.net polkitd[609]:  subject is in session c1 (local=0 active=1)
May 24 12:33:21 hyperarch.mshome.net polkitd[609]:  not authorized

```
Ok, I don't want to report all messages since there are many of them and I don't know if they are useful for debugging.
Thank for your help so far and for possible future suggestions.

**Comment by hardhu** [comment]
I just a little piece of messages from journalctl to describe what happens when KDE Software Updates tries to automatically get authorization to indeed update software, and it doesn't succeed:

```
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: plasma-pk-updates: Is net online: true
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: plasma-pk-updates: Checking updates, forced
May 24 16:33:27 hyperarch.mshome.net dbus-daemon[599]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.65' (uid=1000 pid=1448 comm="/usr/bin/plasmashell ")
May 24 16:33:27 hyperarch.mshome.net systemd[1]: Starting PackageKit Daemon...
May 24 16:33:27 hyperarch.mshome.net PackageKit[2396]: daemon start
May 24 16:33:27 hyperarch.mshome.net systemd[1]: Started PackageKit Daemon.
May 24 16:33:27 hyperarch.mshome.net dbus-daemon[599]: [system] Successfully activated service 'org.freedesktop.PackageKit'
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: plasma-pk-updates: Is net mobile: false
May 24 16:33:27 hyperarch.mshome.net PackageKit[2396]: uid 1000 is trying to obtain org.freedesktop.packagekit.system-sources-refresh auth (only_trusted:0)
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: plasma-pk-updates: Is net online: true
May 24 16:33:27 hyperarch.mshome.net PackageKit[2396]: uid 1000 failed to obtain auth
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: plasma-pk-updates: Daemon changed
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: plasma-pk-updates: Transaction status changed: "wait" "(101%)"
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: plasma-pk-updates: Transaction status changed: "waiting-for-auth" "(101%)"
May 24 16:33:27 hyperarch.mshome.net polkitd[609]: system-bus-name::1.90 is inquiring whether system-bus-name::1.65 is authorized for org.freedesktop.packagekit.system-sources-refresh
May 24 16:33:27 hyperarch.mshome.net polkitd[609]:  user of caller is unix-user:root
May 24 16:33:27 hyperarch.mshome.net polkitd[609]:  user of subject is unix-user:hardhu
May 24 16:33:27 hyperarch.mshome.net polkitd[609]: checking whether system-bus-name::1.65 is authorized for org.freedesktop.packagekit.system-sources-refresh
May 24 16:33:27 hyperarch.mshome.net polkitd[609]:   0x7f2fd4004d60
May 24 16:33:27 hyperarch.mshome.net polkitd[609]: Checking whether session c1 is active.
May 24 16:33:27 hyperarch.mshome.net polkitd[609]: Session c1 has UID 1000.
May 24 16:33:27 hyperarch.mshome.net polkitd[609]: UID 1000 has state active.
May 24 16:33:27 hyperarch.mshome.net polkitd[609]:  subject is in session c1 (local=0 active=1)
May 24 16:33:27 hyperarch.mshome.net polkitd[609]:  not authorized
May 24 16:33:27 hyperarch.mshome.net polkitd[609]:  
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: PK error: "Failed to obtain authentication." type: "not-authorized"
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: plasma-pk-updates: Transaction "/1_aeaabcad" finished with status "failed" in 0 seconds
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: plasma-pk-updates: Cache transaction didn't finish successfully
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: plasma-pk-updates: Is net online: true
May 24 16:33:27 hyperarch.mshome.net plasmashell[1448]: plasma-pk-updates: Transaction status changed: "finished" "(101%)"
May 24 16:33:47 hyperarch.mshome.net PackageKit[2396]: daemon quit
May 24 16:33:47 hyperarch.mshome.net systemd[1]: packagekit.service: Succeeded.
```

I am wondering if that `PackageKit[2396]: uid 1000 is trying to obtain org.freedesktop.packagekit.system-sources-refresh auth (only_trusted:0)` message has something to do with these issues or can however be of any help to debug them.

**Comment by hardhu** [comment]
Just another little comment: being not able to found a solution to my problem so far, I have found a workaround [here](https://wiki.archlinux.org/title/Polkit)

That is, I have created this new rule `/etc/polkit-1/rules.d/49-nopasswd_global.rules`
```

polkit.addRule(function(action, subject) {
    if (subject.isInGroup("wheel")) {
        return polkit.Result.YES;
    }
});

```
and added my user to group wheel. Of course this is not appropriate for a working/production environment, but in order to run Tumbleweed in a vm could be sufficient.

**Comment by matt335672** [comment]
You should be able to fix your refresh issue above by authorizing it directly:-

```
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.packagekit.system-sources-refresh" &&
        subject.isInGroup("xrdpusers"))
    {
        return polkit.Result.YES;
    }
});
```

Create a group called `xrdpusers` and put your user in that. Hopefully the above makes sense.

**Comment by hardhu** [comment]
Yes, of course it makes sense but, as you may have noticed, I have several actions for which I don't receive the required authorization. So, until I will not able ti understand which is the common link between those, I prefer to have a more general rule which allow for all authorizations being given. 
I will edit the title of the issue accordingly to the questions I am facing.

**Comment by matt335672** [comment]
OK - I can see where you're coming from.

All I can really suggest is that you identify your actions from the log, and then use use Javascript functions (e.g. `startsWith()`) in your `addRule` functions to match as many as possible. So, for example:-

```
polkit.addRule(function(action, subject) {
    if ((action.id.startsWith("org.freedesktop.packagekit.") ||
        action.id.startsWith("org.freedesktop.")) &&
        subject.isInGroup("xrdpusers"))
    {
        return polkit.Result.YES;
    }
});
```

I'm not really familiar with Javascript, so if you are I'm sure you can improve on the above quite a bit.

**Comment by hardhu** [comment]
Thanks a lot for your support. I think that with your last answer this issue can be closed.
