### ISSUE TITLE
rdpdr documentation 

### ISSUE THREAD

**Issue by vincentkersten** [neutrinolabs/xrdp#189]
Dear Jay and all,
So I have this new version of xrdp (scarygliders build, 'version' 0.9.0) and am trying to get my fingers behind the fuse/rdpdr stuff. 
I am on google / in the source code /irc etc. for over an hour now, and I can't seem to get any further. The only bright thing I read is that jay wrote 'LK has it 90% done...' on the malinglist. 
Am i missing something obvious? Or maybe there is just no writeup anywhere (I case I would be happy to create one).
I see: xrdp-chanserv on /home/vincent/thinclient_drives type fuse.xrdp-chanserv (rw, .... )
and it also pops up on my desktop with a drive icon, but there is only 'bad file descritor' coming from it when i try to 'cp'  ib terminal or drag'n'drop to it. 

My ultimate goal is to have for my users a place where they can exchange doc/txt etc. from their windows/osx/linux dekstops to the linux server running xrdp - bit by bit :) - without having to use winscp/scp/putty al the time to kill their focus, hehe

Thank you for any pointers, regards,

  Vincent

**Comment by matt335672** [comment]
This seems somewhat stale, so I'll close it. We've done quite a bit of work on shared drives in the last 9 years!
