### ISSUE TITLE
 enable local drive redirection with x11vnc backend

### ISSUE THREAD

**Issue by van-1** [neutrinolabs/xrdp#1891]
Hello.
I successufully setup xrdp and tested it with xorg rdp.

Now I am interested in next case:
1. i opened session in local console
2. started x11vnc
3. now i am trying connect with mstc (from win10 with enabled local drive  redirection) to xrdp server

In this case local drive redirection does not work. Is it possible to enable local drive redirection with x11vnc backend ?

**Comment by matt335672** [comment]
Hi @van-1

You can do it with xrdp. However you'll need the latest version (v0.9.16) to do this, as previous versions didn't support it.

Process is as follows:-
1) In `/etc/xrdp/xrdp.ini`, add this line to the `[Xvnc]` stanza that you're using to connect:-
   ```
   chansrvport=DISPLAY(0)
   ```
2) Restart the `xrdp` service
3) Start your console session, and run `x11vnc`
4) Run `xrdp-chansrv` in your console session
5) Connect from `mstsc.exe`

Couple of other notes:-
1) If you end the desktop from the remote login, the xrdp-chansrv process will be killed without getting a chance to clean up. If that happens you'll have to run the command `fusermount -u ~/thinclent_drives` to be able to start a new one.
2) If xrdp-chansrv isn't running, you'll get a noticeable delay in the connection startup time, while xrdp looks for it.

Let us know how it goes.

**Comment by metalefty** [comment]
I recommend using standard xorgxrdp session rather than x11vnc hack.  RDP to localhost will provide consistent experience.

**Comment by van-1** [comment]
> 
> 
> Hi @van-1
> 
> You can do it with xrdp. However you'll need the latest version (v0.9.16) to do this, as previous versions didn't support it.
> 
> Process is as follows:-
> 
>     1. In `/etc/xrdp/xrdp.ini`, add this line to the `[Xvnc]` stanza that you're using to connect:-
>        ```
>        chansrvport=DISPLAY(0)
>        ```
> 
>     2. Restart the `xrdp` service
> 
>     3. Start your console session, and run `x11vnc`
> 
>     4. Run `xrdp-chansrv` in your console session
> 
>     5. Connect from `mstsc.exe`
> 
> 
> Couple of other notes:-
> 
>     1. If you end the desktop from the remote login, the xrdp-chansrv process will be killed without getting a chance to clean up. If that happens you'll have to run the command `fusermount -u ~/thinclent_drives` to be able to start a new one.
> 
>     2. If xrdp-chansrv isn't running, you'll get a noticeable delay in the connection startup time, while xrdp looks for it.
> 
> 
> Let us know how it goes.

Hi. 
Thanks. Your advise was very useful.
Now we are testing this schema.

**Comment by matt335672** [comment]
Hi @van-1 

Anything else you need from us on this?

**Comment by metalefty** [comment]
Closing due to no updates.
