### ISSUE TITLE
Authentication RDP over ADDC and redirect to Vino

### ISSUE THREAD

**Issue by mipam007** [neutrinolabs/xrdp#1896]
Hi,
on CentOS 8.1.1911, using xrdp-0.9.13, vino-3.22 and sssd-2.2.3 I am trying to achieve user authentication against Active Directory Domain Controller (ADDC) via xrdp and forward authenticated user to running Gnome Shell session available via Vino. SSH authentication over ADDC is working properly but still I am pasting here the config of sssd.conf. Kindly asking for review of the configuration and help.

RDP client (Active Directory user) --> XRDP --> Gnome Vino Shared desktop

**sssd.conf**
`[root@testpc ~]# cat /etc/sssd/sssd.conf`
`[sssd]`
`domains = example.com`
`config_file_version = 2`
`services = nss, pam, ssh`

`[domain/example.com]`
`debug_level = 0x3ff0`
`ad_site = addc-server1.example.com, addc-server2.example.com`
`ad_domain = example.com`
`krb5_realm = EXAMPLE.COM`
`realmd_tags = manages-system joined-with-adcli`
`cache_credentials = False`
`id_provider = ad`
`auth_provider = ad`
`access_provider = ad`
`ldap_user_extra_attrs = altSecurityIdentities:altSecurityIdentities`
`ldap_user_ssh_public_key = altSecurityIdentities`
`krb5_store_password_if_offline = True`
`default_shell = /bin/bash`
`ldap_id_mapping = True`
`use_fully_qualified_names = True`
`fallback_homedir = /home/%u@%d`
`ad_access_filter = (|(memberOf=CN=mygroup,OU=Area,OU=Groups,OU=Prod,DC=example,DC=com))`
`ad_gpo_access_control = permissive`
`ad_gpo_map_remote_interactive = +xrdp-sesman`

**sesman.ini**
`[root@testpc ~]# grep -vE "\;|\#|^$" /etc/xrdp/sesman.ini`
`[Globals]`
`ListenAddress=127.0.0.1`
`ListenPort=3350`
`EnableUserWindowManager=true`
`UserWindowManager=startwm.sh`
`DefaultWindowManager=startwm-bash.sh`
`ReconnectScript=reconnectwm.sh`
`[Security]`
`AllowRootLogin=true`
`MaxLoginRetry=4`
`TerminalServerUsers=tsusers`
`TerminalServerAdmins=tsadmins`
`AlwaysGroupCheck=true`
`RestrictOutboundClipboard=false`
`[Sessions]`
`X11DisplayOffset=10`
`MaxSessions=50`
`KillDisconnected=false`
`DisconnectedTimeLimit=0`
`IdleTimeLimit=0`
`Policy=Default`
`[Logging]`
`LogFile=xrdp-sesman.log`
`LogLevel=DEBUG`
`EnableSyslog=1`
`SyslogLevel=DEBUG`
`[Xorg]`
`param=Xorg`
`param=-config`
`param=xrdp/xorg.conf`
`param=-noreset`
`param=-nolisten`
`param=tcp`
`param=-logfile`
`param=.xorgxrdp.%s.log`
`[Xvnc]`
`param=Xvnc`
`param=-bs`
`param=-nolisten`
`param=tcp`
`param=-localhost`
`param=-dpi`
`param=96`
`[Chansrv]`
`FuseMountName=thinclient_drives`
`FileUmask=077`
`[SessionVariables]`
`PULSE_SCRIPT=/etc/xrdp/pulse/default.pa`

**xrdp.ini**
`[root@testpc ~]# grep -vE "\;|\#|^$" /etc/xrdp/xrdp.ini` 
`[Globals]`
`ini_version=1`
`fork=true`
`port=3389`
`use_vsock=false`
`tcp_nodelay=true`
`tcp_keepalive=true`
`security_layer=negotiate`
`crypt_level=high`
`certificate=`
`key_file=`
`ssl_protocols=TLSv1.2, TLSv1.3`
`autorun=`
`allow_channels=true`
`allow_multimon=true`
`bitmap_cache=true`
`bitmap_compression=true`
`bulk_compression=true`
`max_bpp=32`
`new_cursors=true`
`use_fastpath=both`
`blue=009cb5`
`grey=dedede`
`ls_top_window_bg_color=009cb5`
`ls_width=350`
`ls_height=430`
`ls_bg_color=dedede`
`ls_logo_filename=`
`ls_logo_x_pos=55`
`ls_logo_y_pos=50`
`ls_label_x_pos=30`
`ls_label_width=65`
`ls_input_x_pos=110`
`ls_input_width=210`
`ls_input_y_pos=220`
`ls_btn_ok_x_pos=142`
`ls_btn_ok_y_pos=370`
`ls_btn_ok_width=85`
`ls_btn_ok_height=30`
`ls_btn_cancel_x_pos=237`
`ls_btn_cancel_y_pos=370`
`ls_btn_cancel_width=85`
`ls_btn_cancel_height=30`
`[Logging]`
`LogFile=xrdp.log`
`LogLevel=DEBUG`
`EnableSyslog=true`
`SyslogLevel=DEBUG`
`[Channels]`
`rdpdr=true`
`rdpsnd=true`
`drdynvc=true`
`cliprdr=true`
`rail=true`
`xrdpvr=true`
`tcutils=true`
`[vnc]`
`name=retail`
`lib=libvnc.so`
`pamusername=ask`
`pampassword=ask`
`pamsessionmng=127.0.0.1`
`ip=127.0.0.1`
`port=5900`
`code=20`
`cliprdr=true`
`rdpdr=true`

**Vino config**
`[root@testpc ~]# sudo -Hu myuser dbus-launch gsettings list-recursively org.gnome.Vino`
`org.gnome.Vino notify-on-connect false`
`org.gnome.Vino alternative-port uint16 5900`
`org.gnome.Vino disable-background false`
`org.gnome.Vino use-alternative-port false`
`org.gnome.Vino icon-visibility 'client'`
`org.gnome.Vino use-upnp false`
`org.gnome.Vino view-only false`
`org.gnome.Vino prompt-enabled false`
`org.gnome.Vino disable-xdamage false`
`org.gnome.Vino authentication-methods ['vnc']`
`org.gnome.Vino network-interface ''`
`org.gnome.Vino require-encryption false`
`org.gnome.Vino mailto ''`
`org.gnome.Vino lock-screen-on-disconnect false`
`org.gnome.Vino vnc-password 'strongpassword'`

- I surely need to tame vino to loopback only
- Login via VNC username and password working when I replace pamusername* stanza to username and password

**Comment by matt335672** [comment]
Hi @mipam007 

The AD stuff all looks OK to me. You should be able to see that working properly from the sssd log files. It's worth checking those.

What's the actual error you're getting, if any?

One thing that jumps out is that you've got a VNC password set for Vino, but you're not putting the password in xrdp.ini using `password=strongpassword`. Try setting that and see what happens.

**Comment by mipam007** [comment]
Hi @matt335672, many thanks for prompt answer. Well surly I am watching logs, but quiet confused :) anyway, here are the logs.

`May 25 16:46:54 testpc xrdp[100284]: (100284)(140367138072000)[INFO ] Socket 12: AF_INET connection received from 10.255.1.89 port 34154`
`May 25 16:46:54 testpc xrdp[100284]: (100284)(140367138072000)[DEBUG] Closed socket 12 (AF_INET 10.30.205.37:3389)`
`May 25 16:46:54 testpc xrdp[100302]: (100302)(140367138072000)[DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)`
`May 25 16:46:54 testpc xrdp[100302]: (100302)(140367138072000)[INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem`
`May 25 16:46:54 testpc xrdp[100302]: (100302)(140367138072000)[INFO ] Using default X.509 key file: /etc/xrdp/key.pem`
`May 25 16:46:54 testpc xrdp[100302]: (100302)(140367138072000)[DEBUG] TLSv1.3 enabled`
`May 25 16:46:54 testpc xrdp[100302]: (100302)(140367138072000)[DEBUG] TLSv1.2 enabled`
`May 25 16:46:54 testpc xrdp[100302]: (100302)(140367138072000)[DEBUG] Security layer: requested 3, selected 1`
`May 25 16:46:54 testpc xrdp[100302]: (100302)(140367138072000)[INFO ] connected client computer name: mylaptop`
`May 25 16:46:54 testpc xrdp[100302]: (100302)(140367138072000)[INFO ] adding channel item name rdpdr chan_id 1004 flags 0xc0800000`
`May 25 16:46:54 testpc xrdp[100302]: (100302)(140367138072000)[INFO ] adding channel item name rdpsnd chan_id 1005 flags 0xc0000000`
`May 25 16:46:54 testpc xrdp[100302]: (100302)(140367138072000)[INFO ] adding channel item name cliprdr chan_id 1006 flags 0xc0a00000`
`May 25 16:46:55 testpc xrdp[100302]: (100302)(140367138072000)[INFO ] TLS connection established from 10.255.1.89 port 34154: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384`
`May 25 16:46:55 testpc xrdp[100302]: (100302)(140367138072000)[DEBUG] xrdp_000187ce_wm_login_mode_event_00000001`
`May 25 16:46:55 testpc xrdp[100302]: (100302)(140367138072000)[INFO ] Cannot find keymap file /etc/xrdp/km-00000405.ini`
`May 25 16:46:55 testpc xrdp[100302]: (100302)(140367138072000)[INFO ] Cannot find keymap file /etc/xrdp/km-00000405.ini`
`May 25 16:46:55 testpc xrdp[100302]: (100302)(140367138072000)[INFO ] Loading keymap file /etc/xrdp/km-00000409.ini`
`May 25 16:46:55 testpc xrdp[100302]: (100302)(140367138072000)[WARN ] local keymap file for 0x00000405 found and doesn't match built in keymap, using local keymap file`
`May 25 16:46:55 testpc xrdp[100302]: (100302)(140367138072000)[DEBUG] xrdp_wm_log_msg: Please wait, we now perform access control...`
`May 25 16:46:55 testpc xrdp-sesman[100283]: (100283)(140335559534400)[INFO ] A connection received from 127.0.0.1 port 39592`
`May 25 16:46:55 testpc xrdp-sesman[100283]: pam_unix(xrdp-sesman:auth): check pass; user unknown`
`May 25 16:46:55 testpc xrdp-sesman[100283]: pam_unix(xrdp-sesman:auth): authentication failure; logname= uid=0 euid=0 tty=xrdp-sesman ruser= rhost=`
`May 25 16:46:57 testpc xrdp-sesman[100283]: (100283)(140335559534400)[INFO ] Username or password error for user: ask`
`May 25 16:46:57 testpc xrdp-sesman[100283]: (100283)(140335559534400)[DEBUG] Closed socket 9 (AF_INET 127.0.0.1:3350)`
`May 25 16:46:57 testpc xrdp[100302]: (100302)(140367138072000)[DEBUG] Closed socket 18 (AF_INET 127.0.0.1:39592)`
`May 25 16:46:57 testpc xrdp[100302]: (100302)(140367138072000)[WARN ] getsockname() failed on socket 18: Bad file descriptor`
`May 25 16:46:57 testpc xrdp[100302]: (100302)(140367138072000)[INFO ] xrdp_wm_log_msg: Reply from access control: User not known to the underlying authentication module`

with following config
`[vnc]`
`name=area`
`lib=libvnc.so`
`#username=ask`
`password=mystrongpassword`
`pamusername=ask`
`pampassword=ask`
`pamsessionmng=127.0.0.1`
`ip=127.0.0.1`
`port=5900`
`code=20`
`cliprdr=true`
`rdpdr=true`

**Comment by matt335672** [comment]
It looks like the `ask` is being passed though to sesman!

You shouldn't have `code=20` in that section. That will break stuff. Sorry I didn't spot it earlier.

**Comment by mipam007** [comment]
OK, I have removed code=20 and here is the log

`May 25 17:19:38 testpc xrdp[100702]: (100702)(139936979006912)[INFO ] Socket 12: AF_INET connection received from 10.255.1.89 port 34782`
`May 25 17:19:38 testpc xrdp[100702]: (100702)(139936979006912)[DEBUG] Closed socket 12 (AF_INET 10.30.205.37:3389)`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[INFO ] Using default X.509 key file: /etc/xrdp/key.pem`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[DEBUG] TLSv1.3 enabled`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[DEBUG] TLSv1.2 enabled`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[DEBUG] Security layer: requested 3, selected 1`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[INFO ] connected client computer name: mylaptop`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[INFO ] adding channel item name rdpdr chan_id 1004 flags 0xc0800000`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[INFO ] adding channel item name rdpsnd chan_id 1005 flags 0xc0000000`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[INFO ] adding channel item name cliprdr chan_id 1006 flags 0xc0a00000`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[INFO ] TLS connection established from 10.255.1.89 port 34782: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[DEBUG] xrdp_00018973_wm_login_mode_event_00000001`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[INFO ] Cannot find keymap file /etc/xrdp/km-00000405.ini`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[INFO ] Cannot find keymap file /etc/xrdp/km-00000405.ini`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[INFO ] Loading keymap file /etc/xrdp/km-00000409.ini`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[WARN ] local keymap file for 0x00000405 found and doesn't match built in keymap, using local keymap file`
`May 25 17:19:38 testpc xrdp[100723]: (100723)(139936979006912)[DEBUG] xrdp_wm_log_msg: Please wait, we now perform access control...`
`May 25 17:19:38 testpc xrdp-sesman[100701]: (100701)(140369092200256)[INFO ] A connection received from 127.0.0.1 port 39754`
`May 25 17:19:38 testpc xrdp-sesman[100701]: pam_unix(xrdp-sesman:auth): check pass; user unknown`
`May 25 17:19:38 testpc xrdp-sesman[100701]: pam_unix(xrdp-sesman:auth): authentication failure; logname= uid=0 euid=0 tty=xrdp-sesman ruser= rhost=`
`May 25 17:19:40 testpc xrdp-sesman[100701]: (100701)(140369092200256)[INFO ] Username or password error for user: ask`
`May 25 17:19:40 testpc xrdp-sesman[100701]: (100701)(140369092200256)[DEBUG] Closed socket 9 (AF_INET 127.0.0.1:3350)`
`May 25 17:19:40 testpc xrdp[100723]: (100723)(139936979006912)[DEBUG] Closed socket 18 (AF_INET 127.0.0.1:39754)`
`May 25 17:19:40 testpc xrdp[100723]: (100723)(139936979006912)[WARN ] getsockname() failed on socket 18: Bad file descriptor`
`May 25 17:19:40 testpc xrdp[100723]: (100723)(139936979006912)[INFO ] xrdp_wm_log_msg: Reply from access control: User not known to the underlying authentication module`

**Comment by mipam007** [comment]
actually in previous log output I have filtered only specific services via journalctl, full log is here

`May 26 09:49:01 testpc xrdp[111610]: (111610)(140388010120640)[INFO ] Socket 12: AF_INET connection received from 10.255.1.108 port 46628`
`May 26 09:49:01 testpc xrdp[111610]: (111610)(140388010120640)[DEBUG] Closed socket 12 (AF_INET 10.30.205.37:3389)`
`May 26 09:49:01 testpc xrdp[111732]: (111732)(140388010120640)[DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)`
`May 26 09:49:01 testpc xrdp[111732]: (111732)(140388010120640)[INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem`
`May 26 09:49:01 testpc xrdp[111732]: (111732)(140388010120640)[INFO ] Using default X.509 key file: /etc/xrdp/key.pem`
`May 26 09:49:01 testpc xrdp[111732]: (111732)(140388010120640)[DEBUG] TLSv1.3 enabled`
`May 26 09:49:01 testpc xrdp[111732]: (111732)(140388010120640)[DEBUG] TLSv1.2 enabled`
`May 26 09:49:01 testpc xrdp[111732]: (111732)(140388010120640)[DEBUG] Security layer: requested 3, selected 1`
`May 26 09:49:01 testpc xrdp[111732]: (111732)(140388010120640)[INFO ] connected client computer name: mylaptop`
`May 26 09:49:01 testpc xrdp[111732]: (111732)(140388010120640)[INFO ] adding channel item name rdpdr chan_id 1004 flags 0xc0800000`
`May 26 09:49:01 testpc xrdp[111732]: (111732)(140388010120640)[INFO ] adding channel item name rdpsnd chan_id 1005 flags 0xc0000000`
`May 26 09:49:01 testpc xrdp[111732]: (111732)(140388010120640)[INFO ] adding channel item name cliprdr chan_id 1006 flags 0xc0a00000`
`May 26 09:49:02 testpc xrdp[111732]: (111732)(140388010120640)[INFO ] TLS connection established from 10.255.1.108 port 46628: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384`
`May 26 09:49:02 testpc xrdp[111732]: (111732)(140388010120640)[DEBUG] xrdp_0001b474_wm_login_mode_event_00000001`
`May 26 09:49:02 testpc xrdp[111732]: (111732)(140388010120640)[INFO ] Cannot find keymap file /etc/xrdp/km-00000405.ini`
`May 26 09:49:02 testpc xrdp[111732]: (111732)(140388010120640)[INFO ] Cannot find keymap file /etc/xrdp/km-00000405.ini`
`May 26 09:49:02 testpc xrdp[111732]: (111732)(140388010120640)[INFO ] Loading keymap file /etc/xrdp/km-00000409.ini`
`May 26 09:49:02 testpc xrdp[111732]: (111732)(140388010120640)[WARN ] local keymap file for 0x00000405 found and doesn't match built in keymap, using local keymap file`
`May 26 09:49:02 testpc xrdp[111732]: (111732)(140388010120640)[DEBUG] xrdp_wm_log_msg: Please wait, we now perform access control...`
`May 26 09:49:02 testpc xrdp-sesman[111609]: (111609)(139929377470272)[INFO ] A connection received from 127.0.0.1 port 43532`
`May 26 09:49:02 testpc xrdp-sesman[111609]: pam_unix(xrdp-sesman:auth): check pass; user unknown`
`May 26 09:49:02 testpc xrdp-sesman[111609]: pam_unix(xrdp-sesman:auth): authentication failure; logname= uid=0 euid=0 tty=xrdp-sesman ruser= rhost=`
`May 26 09:49:04 testpc xrdp-sesman[111609]: (111609)(139929377470272)[INFO ] Username or password error for user: ask`
`May 26 09:49:04 testpc xrdp-sesman[111609]: (111609)(139929377470272)[DEBUG] Closed socket 9 (AF_INET 127.0.0.1:3350)`
`May 26 09:49:04 testpc xrdp[111732]: (111732)(140388010120640)[DEBUG] Closed socket 18 (AF_INET 127.0.0.1:43532)`
`May 26 09:49:04 testpc xrdp[111732]: (111732)(140388010120640)[WARN ] getsockname() failed on socket 18: Bad file descriptor`
`May 26 09:49:04 testpc xrdp[111732]: (111732)(140388010120640)[INFO ] xrdp_wm_log_msg: Reply from access control: User not known to the underlying authentication module`
`May 26 09:49:04 testpc xrdp[111610]: logging configuration:`
`May 26 09:49:04 testpc xrdp[111610]:    LogFile:       /var/log/xrdp.log`
`May 26 09:49:04 testpc xrdp[111610]:    LogLevel:      4`
`May 26 09:49:04 testpc xrdp[111610]:    EnableSyslog:  1`
`May 26 09:49:04 testpc xrdp[111610]:    SyslogLevel:   4`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:44:42] [INFO ] starting xrdp with pid 111610`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:44:42] [INFO ] address [0.0.0.0] port [3389] mode 1`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:44:42] [INFO ] listening to port 3389 on 0.0.0.0`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:44:42] [INFO ] xrdp_listen_pp done`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:44:51] [INFO ] Socket 12: AF_INET connection received from 10.255.1.108 port 46612`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:44:51] [DEBUG] Closed socket 12 (AF_INET 10.30.205.37:3389)`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:47:01] [INFO ] Socket 12: AF_INET connection received from 10.255.1.108 port 46622`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:47:01] [DEBUG] Closed socket 12 (AF_INET 10.30.205.37:3389)`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:01] [INFO ] Socket 12: AF_INET connection received from 10.255.1.108 port 46628`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:01] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:01] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:01] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:01] [DEBUG] TLSv1.3 enabled`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:01] [DEBUG] TLSv1.2 enabled`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:01] [DEBUG] Security layer: requested 3, selected 1`
`May 26 09:49:04 testpc xrdp[111610]: ssl_tls_accept: TLS connection accepted`
`May 26 09:49:04 testpc xrdp[111610]: colorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp)`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:01] [INFO ] connected client computer name: kanatkovo`
`May 26 09:49:04 testpc xrdp[111610]: postBeta2ColorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp 0xca02 15bpp 0xca03 16bpp 0xca04 24bpp)`
`May 26 09:49:04 testpc xrdp[111610]: highColorDepth 0x0010 (0x0004 4bpp 0x0008 8bpp 0x000f 15bpp 0x0010 16 bpp 0x0018 24bpp)`
`May 26 09:49:04 testpc xrdp[111610]: supportedColorDepths 0x0007 (0x0001 24bpp 0x0002 16bpp 0x0004 15bpp 0x0008 32bpp)`
`May 26 09:49:04 testpc xrdp[111610]: earlyCapabilityFlags 0x04e1 (0x0002 want32)`
`May 26 09:49:04 testpc xrdp[111610]: got client client connection type 0x00000006`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_sec_process_mcs_data_CS_SECURITY:`
`May 26 09:49:04 testpc xrdp[111610]:   client and server support none crypt, using none crypt`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:01] [INFO ] adding channel item name rdpdr chan_id 1004 flags 0xc0800000`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:01] [INFO ] adding channel item name rdpsnd chan_id 1005 flags 0xc0000000`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:01] [INFO ] adding channel item name cliprdr chan_id 1006 flags 0xc0a00000`
`May 26 09:49:04 testpc xrdp[111610]: error unknown xrdp_sec_process_mcs_data tag 0xc006 size 8`
`May 26 09:49:04 testpc xrdp[111610]: error unknown xrdp_sec_process_mcs_data tag 0xc00a size 8`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_sec_out_mcs_data: using no security`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_load_keyboard_layout: keyboard_type [4] keyboard_subtype [0]`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_load_keyboard_layout: model [] variant [] layout [us] options []`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:02] [INFO ] TLS connection established from 10.255.1.108 port 46628: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_caps_process_order: not enough orders supported by client, using painter.`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_caps_process_pointer: client supports new(color) cursor`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_caps_process_glyphcache: support level 0`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_caps_process_surface_cmds:`
`May 26 09:49:04 testpc xrdp[111610]:   cmdFlags 0x00000052`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_caps_process_frame_ack:`
`May 26 09:49:04 testpc xrdp[111610]:   max_unacknowledged_frame_count 2`
`May 26 09:49:04 testpc xrdp[111610]: yeah, up_and_running`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_channel_drdynvc_start:`
`May 26 09:49:04 testpc xrdp[111610]: xrdp:xrdp_bitmap [2812671940]: xrdp_bitmap_create: noorders`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:02] [DEBUG] xrdp_0001b474_wm_login_mode_event_00000001`
`May 26 09:49:04 testpc xrdp[111610]: xrdp:xrdp_mm [2812671943]: xrdp_mm_create: bpp 16 mcs_connection_type 6 jpeg_codec_id 0 v3_codec_id 0 rfx_codec_id 0 h264_codec_id 0`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:02] [INFO ] Cannot find keymap file /etc/xrdp/km-00000405.ini`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:02] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:02] [WARN ] local keymap file for 0x00000405 found and doesn't match built in keymap, using local keymap file`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_wm_login_mode_changed: login_mode is 0`
`May 26 09:49:04 testpc xrdp[111610]: in xrdp_wm_init:`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_wm_init: channel rdpdr channel id 0 is allowed`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_wm_init: channel rdpsnd channel id 1 is allowed`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_wm_init: channel cliprdr channel id 2 is allowed`
`May 26 09:49:04 testpc xrdp[111610]: out xrdp_wm_init:`
`May 26 09:49:04 testpc xrdp[111610]: xrdp_wm_login_mode_changed: login_mode is 2`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:02] [DEBUG] xrdp_wm_log_msg: Please wait, we now perform access control...`
`May 26 09:49:04 testpc xrdp[111610]: Please wait, we now perform access control...`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:04] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:43532)`
`May 26 09:49:04 testpc xrdp[111610]: [20210526-09:49:04] [WARN ] getsockname() failed on socket 18: Bad file descriptor`
`May 26 09:50:00 testpc xrdp[111732]: (111732)(140388010120640)[DEBUG] Closed socket 12 (AF_INET 10.30.205.37:3389)`
`May 26 09:50:00 testpc xrdp[111732]: (111732)(140388010120640)[DEBUG] xrdp_mm_module_cleanup`
`May 26 09:50:00 testpc xrdp[111610]: [20210526-09:49:04] [INFO ] xrdp_wm_log_msg: Reply from access control: User not known to the underlying authentication module`
`May 26 09:50:00 testpc xrdp[111610]: Reply from access control: User not known to the underlying`
`May 26 09:50:00 testpc xrdp[111610]: authentication module`
`May 26 09:50:00 testpc xrdp[111610]: ssl_tls_print_error: SSL_read: I/O error`
`May 26 09:50:00 testpc xrdp[111610]: ssl_tls_print_error: SSL_shutdown: I/O error`
`May 26 09:50:00 testpc xrdp[111610]: [20210526-09:50:00] [DEBUG] Closed socket 12 (AF_INET 10.30.205.37:3389)`
`May 26 09:50:00 testpc xrdp[111610]: xrdp_mcs_disconnect - socket closed`
`May 26 09:50:00 testpc xrdp[111610]: [20210526-09:50:00] [DEBUG] xrdp_mm_module_cleanup`
`May 26 09:50:00 testpc xrdp[111610]: xrdp:xrdp_encoder [2812730277]: xrdp_encoder_delete:`

**Comment by matt335672** [comment]
This is odd.

I've just built v0.9.13 and I've added this section to my xrdp.ini, which I think is the same as yours:-

```
[vnc]
name=area
lib=libvnc.so
#username=ask
password=
pamusername=ask
pampassword=ask
pamsessionmng=127.0.0.1
ip=127.0.0.1
port=5900
cliprdr=true
rdpdr=true
```
I'm using x11vnc without a password (rather than Vino), and it all works for me as expected.

The thing that's odd about your logs is this:-

```
May 26 09:49:04 testpc xrdp-sesman[111609]: (111609)(139929377470272)[INFO ] Username or password error for user: ask
```

The `ask` user suggests that something is defeating the logic in `xrdp_login_wnd.c` which asks for this value.

Couple of things:-
- Double-check the xrdp version by looking at the output of `xrdp- -v`
- Check the `ask` string in xrdp.ini doesn't have any abnormal characters hiding in it with this command:-
   ```
   $ grep ^pamusername= /etc/xrdp/xrdp.ini | od -c -tx1
   0000000   p   a   m   u   s   e   r   n   a   m   e   =   a   s   k  \n
            70  61  6d  75  73  65  72  6e  61  6d  65  3d  61  73  6b  0a
   ```

Also, try replacing the `ask` string with an actual username and see what happens.

**Comment by metalefty** [comment]
BTW, You should use ``` block rather than quoting each line with ``.

**Comment by matt335672** [comment]
No user response - closing
