### ISSUE TITLE
Connect xrdp to existing user xsession

### ISSUE THREAD

**Issue by skochko** [neutrinolabs/xrdp#1898]
Hello!

Could you please help me with advice.

I need to run Xserver for each user after server restart and make user logged in automatically. After that I need to run program that needs Xserver running. And then I need to give access to running session for users via RDP protocol.

I met the problem that in this case when I connect to server via RDP protocol XRDP creating NEW session for user.

Maybe it's possible to run user's session via XRDP after server restart?
I tried to run session via xrdp-sesrun but met same problem - it creates NEW session.

Please advice how can I solve this problem? How can I connect to certain X session?

**Comment by matt335672** [comment]
A few possibilities here:-
1) Use xrdp-sesrun to start a new session and then connect to the same session using xrdp.
2) Start a Xvnc session for each user and then use xrdp to connect to that session.
3) Set up the sessions so that when the user logs in for the first time over xrdp, everything is created in that session at that point.

I get a feeling I'm not fully understanding your requirement here. Are you trying to control the DISPLAY number allocated to each user?

**Comment by skochko** [comment]
Thanks for the answer!
I will try to describe my problem in other words.
I need to run multiple X sessions for multiple users.
In each session, run xfce4 and other applications.
Next, I need the user, when connecting via the RDP client, to connect to an existing session and see the running applications.

I tried to start a session for the user by running xrdp-sesrun on the server (as root), the session is created, but if I connect from outside, a new session is created.
maybe you need to specify some additional parameters for running xrdp-sesrun at startup so that a new session is not created when connecting remotely?

I tried to implement option 1, but when connecting remotely, for some reason I create a new session for the user

**Comment by matt335672** [comment]
What version of xrdp are you using ? Later versions make this easier. The command `xrdp -v` will tell you what version you're running.

**Comment by skochko** [comment]
xrdp 0.9.16
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-fuse
      --enable-jpeg

  Compiled with OpenSSL 1.1.1  11 Sep 2018

**Comment by matt335672** [comment]
This isn't as straightforward as it needs to be. I'm assuming you're using Xorg. Try this.

1) Start a session with `xrdp-sesrun -b24`, e.g.:-
   ```sh
   $ xrdp-sesrun -b24 testuser
   Password: 
   ok data=1 display=:11 GUID=5c6698d4379aa980b378b77c30157aa2
   ```
2) Ensure your client is set up to connect at 24 or 32 bits-per-pixel
3) Connect to the server, and select an `Xorg` session

If you're using Xvnc:-
1) Start a session with `xrdp-sesrun -tXvnc`, e.g.:-
   ```sh
   $ xrdp-sesrun -tXvnc testuser
   Password: 
   ok data=1 display=:11 GUID=5c6698d4379aa980b378b77c30157aa2
   ```
2) Ensure your client is set up to connect at 32 bits-per-pixel
3) Connect to the server, and select an `Xvnc` session

Let us know how that goes. I'm sure we can improve the interface here somewhat.

**Comment by matt335672** [comment]
No more input - closing
