### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by setdebug** [neutrinolabs/xrdp#1904]
I'm trying to get xrdp working on OpenBSD 6.9. I am able to get xrdp to compile and run. When I connect with an RDP client, I see the login screen; however, I always get "login failed for display 0."

Here is how I am compiling it:

```
# OpenBSD doesn't have libdl because it's included in libc; create a dummy .a file to prevent linker errors
ar rc libdl.a

./configure --disable-pam --enable-bsd --enable-jpeg --enable-pixman --enable-rfxcodec --enable-painter CC=clang CFLAGS="-I/usr/local/include -include sys/select.h" LDFLAGS="-L$PWD -L/usr/local/lib"
make && make install
```

I added a printf in `sesman/verify_user_bsd.c` to print the result of `auth_userokay`. It's always `0`. If I make a simple test program that calls `auth_userokay` in the same way and run it as root, the authentication works as expected. I can't figure out why this happens. I also installed openpam and tried building with PAM support. It compiles but still doesn't work with the same issue.

I then modified the code to simulate a successful authentication in order to see how far I could get. After doing so and trying to log in, the login window goes away (showing only the background) and this appears on the console (when running sesman with the -n flag):

`sh: xauth: not found`

Then the login times out after a while and the log says `connection problem, giving up`.

I suspect that's because `xauth` is located in `/usr/X11R6/bin` and the `popen` call to execute it doesn't use or have access to the `PATH` env var (which includes the X11R6 bin dir). Running xauth manually from the shell works fine. I then modified `sesman/xauth.c` so it contains the full absolute path to the xauth binary.

I then got `file .Xauthority does not exist` when logging in. So I created an empty file with `touch ~/.Xauthority` and the message no longer appears; however, the X server still doesn't start.

I edited `/etc/xrdp/sesman.ini` and changed `param=Xorg` to `param=/usr/X11R6/bin/Xorg`. Xorg tries to start but now I get this:

```
X.Org X Server 1.20.10
X Protocol Version 11, Revision 0
Build Operating System: OpenBSD 6.9 amd64
Current Operating System: OpenBSD 6.9 GENERIC#464 amd64
Build Date: 19 April 2021  11:06:48AM

Current version of pixman: 0.38.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: ".xorgxrdp.10.log", Time: Mon May 31 00:56:45 2021
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/X11R6/share/X11/xorg.conf.d"
(EE)
Fatal server error:
(EE) xf86OpenConsole: No console driver found
        Supported drivers: wscons
        Check your kernel's console driver configuration and /dev entries(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at ".xorgxrdp.10.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.
```

I don't know where to go from here. Hopefully someone knows what I'm missing.

**Comment by matt335672** [comment]
The authentication is a bit of a mystery, to me at least. I've had a look at the OpenBSD manpage but I can't find an explanation for what type and style are, or why your test program should work and sesman doesn't. I'm not surprised PAM doesn't work as it will be using the same interfaces. Have you got any pointers to a quick intro to OpenBSD authentication?

xauth does currently need to be in the PATH. This is currently set to a default in the `env_set_user()` function in `sesman/env.c`. On PAM-based systems this will be overridden anyway.

To get the Xorg stuff working you'll need to build xorgxrdp. I'd recommend you start with the Xvnc backend for now, as it has less in the way of dependencies. You'll just need to get a vnc server installed on OpenBSD for this. The TigerVNC is a good option if it's available.

Hope that's at least a bit useful/informative.

**Comment by setdebug** [comment]
The OpenBSD manpage is about all I could find for documentation too.

As far as I can tell, style can be (and is) NULL. The "auth-xrdp" (the type) might have to be placed somewhere in `/etc/login.conf`. I tried adding this to the top of /etc/login.conf but it didn't make any difference (and I wouldn't expect it to since I can get a basic test program working without doing so):

```
auth-xrdp:auth=passwd:
```

Thanks for the tip about `env_set_user` - I'll look into it.

I was able to build and install xorgxrdp but I haven't been able to see if it works because the login process doesn't get that far yet.

**Comment by matt335672** [comment]
We had a report #1323 about MacOS struggling when `fork()` is called without `exec()`. It's possible this could affect OpenBSD too, but it's a bit of a long shot.

Can you try starting sesman from a terminal window with the `-n` flag to prevent the initial daemonisation? That should prevent forks in the codepaths before `auth_userokay()`.

You might also be able to use `ltrace` to see what is happening inside `auth_userokay()`

**Comment by matt335672** [comment]
No input for a few months - closing
