### ISSUE TITLE
Duplicated initialization of variable in xrdp_bitmap.c

### ISSUE THREAD

**Issue by qarmin** [neutrinolabs/xrdp#1909]
https://github.com/neutrinolabs/xrdp/blob/7d8f0846d9922ead538b7cb96b5a9658c271aecc/xrdp/xrdp_bitmap.c#L1359-L1360

**Comment by metalefty** [comment]
Thanks for the catch. Can you make a pull request? Then we'll merge your contribution soon.

**Comment by matt335672** [comment]
Agreed.

It looks to me like this was intended to be a setting of `brush.y_origin` cut-and-pasted from the previous line that wasn't finished.
