### ISSUE TITLE
macOS (Catalina) xrdp building error 

### ISSUE THREAD

**Issue by doanhtien** [neutrinolabs/xrdp#1917]
When building under MacOS Bigsur I get the following error :
`configure: error: please install xserver-xorg-dev, xorg-x11-server-sdk or xorg-x11-server-devel
Any help will be appreciated !

`

**Comment by matt335672** [comment]
Hi @doanhtien 

The message is telling you that you need the X11 development files installed.

It will be difficult to provide you with support for this activity - none of the developers here have access to Macs that I'm aware of. Some users in the past have had success using the vnc module to connect to the MacOS desktop being exported over VNC - you can search the issues for details of this.

**Comment by benbaker76** [comment]
Please see [this post](https://github.com/neutrinolabs/xrdp/issues/1461#issuecomment-861940943)

**Comment by metalefty** [comment]
Closing due to no updates. Advice had already been provided.
