### ISSUE TITLE
Wrong resolution after reconnect

### ISSUE THREAD

**Issue by snizzler** [neutrinolabs/xrdp#1918]
Hi everybody,
sometimes we have a very strange behaviour when a user reconnects to a running session. The server changes the resolution to 1200x120 pixels (see logfile). A fully restart is necessary to fix the problem. We already tried different settings in MS Remote Desktop Client, but without success.  Anybody have a idea how to fix this?

Version xrdp 0.9.16 (From Fedora 33 repo)

```
[20210610-06:13:35] [DEBUG] VNC matched ExtendedDesktopSize rectangle x=0, y=0 geom=1920x1200
[20210610-06:13:35] [DEBUG] VNC server supports resizing
[20210610-06:13:35] [INFO ] Layout from OldLayout (geom=1920x1200 #screens=1) : 1804289383:(1920x1200+0+0)
[20210610-06:13:35] [DEBUG] VNC setting screen id to 1804289383 from server
[20210610-06:13:35] [DEBUG] Server layout differs from the client layout. Changing server layout
[20210610-06:13:35] [DEBUG] VNC Sending SetDesktopSize
[20210610-06:13:35] [DEBUG] Skipping ENC_EXTENDED_DESKTOP_SIZE encoding x=0, y=0 geom=1200x120
[20210610-06:13:35] [DEBUG] Skipping ENC_EXTENDED_DESKTOP_SIZE encoding x=0, y=0 geom=1200x120
[20210610-06:13:35] [DEBUG] Skipping ENC_EXTENDED_DESKTOP_SIZE encoding x=0, y=0 geom=1200x120
[20210610-06:13:35] [DEBUG] Skipping ENC_EXTENDED_DESKTOP_SIZE encoding x=0, y=0 geom=1200x120
[20210610-06:13:35] [DEBUG] VNC matched ExtendedDesktopSize rectangle x=1, y=0 geom=1200x120
[20210610-06:13:35] [DEBUG] VNC server successfully resized
```

[xrdp.log](https://github.com/neutrinolabs/xrdp/files/6629777/xrdp.log)

**Comment by matt335672** [comment]
That's pretty odd.

It smells like a regression to me. Have you been using this config previously with 0.9.15?

Also, could you give me the output of `xrdp -v`?

Thanks,

**Comment by snizzler** [comment]
No, the system/config is only a few days old because the user got a new workstation with a fresh installed Fedora. But we had the same problem with his old workstation.

```
xrdp -v
xrdp 0.9.16
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-redhat-linux-gnu
      --host=x86_64-redhat-linux-gnu
      --program-prefix=
      --disable-dependency-tracking
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/sbin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --sharedstatedir=/var/lib
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-fuse
      --enable-pixman
      --enable-painter
      --enable-vsock
      --with-socketdir=/run/xrdp
      build_alias=x86_64-redhat-linux-gnu
      host_alias=x86_64-redhat-linux-gnu
      CC=gcc
      CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld 
      LT_SYS_LIBRARY_PATH=/usr/lib64:
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 1.1.1k  FIPS 25 Mar 2021
```

**Comment by matt335672** [comment]
Thanks @snizzler 

I've just built a debug build of v0.9.16 and I can' reproduce this on a simple setup.

I do notice from your full log file however this line:-

```
[20210610-06:09:08] [DEBUG] Layout from client_info (geom=1200x120 #screens=1) : 0:(1200x120+0+0)
```

which suggests either the client is sending the odd resolution, or the client info is getting distorted somehow.

A couple more questions for you:-
1. When you say 'MS Remote Desktop Client', do you mean `mstsc.exe`?
2. Regardless of the answer to 1., what happens when you run this command from a cmd prompt:-

   ```
   mstsc.exe /v:<server-name> /w:1920 /h:1200
   ```

   That should eliminate any problems with the connection file
3. At what stage do you notice the resize? Is it on the initial connect when the login box is displayed, or after the password is entered and the session is rejoined?

Thanks,

**Comment by snizzler** [comment]
Yes, we use the mstsc.exe. The login box is ok. It happens when a session is rejoined.

At the moment we are trying

`mstsc.exe /v:<server-name> /w:1920 /h:1200`

and it seems to be working.

**Comment by matt335672** [comment]
Thanks - that's useful info, but nothing definitive yet.

Are you using an .ini file for mstsc.exe when the problem occurs? If so feel free to post it and I'll go through it.

**Comment by matt335672** [comment]
One other thing occurred to me, although it's possibly a long shot.

The xrdp makes a VNC connection it loads a dynamic library `libvnc.so` (part of the xrdp RPM) which contains the VNC code.

I understand you're using v0.9.16 from the repo, but this behaviour could possibly be explained if you've got a `libvnc.so` from a previous version of xrdp lying about. This is only really likely if you've been building xrdp from scratch, or have done so in the past.

You can check the integrity of the installed xrdp rpm with:-

```
sudo rpm -V xrdp
```

You can see where the `libvnc.so` library has been loaded from by using this command after the user has logged in:-

```
sudo lsof -p $(pgrep -x -d, xrdp) | grep vnc
```

**Comment by matt335672** [comment]
No more input - closing
