### ISSUE TITLE
xorg: xorg.conf is not installed

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#192]
@jsorg71 

xorg.conf should be installed `/tmp/xorg-driver-tmpdir/etc/X11/xrdp/xorg.conf` in following example, right?

How to repeat:

```
$ cd xorg/server
$ ./bootstrap
$ ./configure
$ make 
$ make install DESTDIR=/tmp/xorg-driver-tmpdir
$ tree /tmp/xorg-driver-tmpdir
/tmp/xorg-driver-tmpdir
└── usr
    └── lib64
        └── xorg
            └── modules
                ├── drivers
                │   ├── xrdpdev_drv.a
                │   ├── xrdpdev_drv.la
                │   └── xrdpdev_drv.so
                ├── input
                │   ├── xrdpkeyb_drv.a
                │   ├── xrdpkeyb_drv.la
                │   ├── xrdpkeyb_drv.so
                │   ├── xrdpmouse_drv.a
                │   ├── xrdpmouse_drv.la
                │   └── xrdpmouse_drv.so
                ├── libxorgxrdp.a
                ├── libxorgxrdp.la
                └── libxorgxrdp.so

6 directories, 12 files
```

**Comment by therevoman** [comment]
Glad to see someone still working on xrdp!  I just downloaded and recompiled X11rdp for some RHEL 6 cloud VM's we are building.  I built from the recent devel branch but did not get an xorg.conf file generated.  

On a side note, does xrdp/X11rdp support automatic resizing?

**Comment by metalefty** [comment]
If you're talking about x11rdp, this does not affect. xorg.conf is for xorg-driver aka [xorgxrdp](https://github.com/neutrinolabs/xorgxrdp).

Yes, xrdp w/x11rdp resize your session automatically.
