### ISSUE TITLE
Feature-Request: Better debug log messages for TLS connection issues. (Connection with Microsoft Remote Desktop fails with Error 0x2104)

### ISSUE THREAD

**Issue by ingokeck** [neutrinolabs/xrdp#1922]
When I tried to connect to my xrdp server running on Ubuntu 20.04 from remmina on Ubuntu, everything works fine. But from Microsoft Remote Desktop it fails with "Protocol error" and "error 0x2104"

Looking into it, it was a problem of the self-signed certificate of the server. Running 
`sudo make-ssl-cert generate-default-snakeoil --force-overwrite `
and accepting the new certificate on the mac when prompted by Microsoft Remote Desktop solved the problem.

It would be great if xrdp could give some information about the status of the TLS connection. Even on loglevel DEBUG there is no indication what is wrong, and debugging TLS connections is not a normal user skill. Of course, the same holds true for MS RD, their messages in the console are neither helpful.

**Comment by matt335672** [comment]
I agree with this - I has a similar experience while debugging #1776, but lacked the OpenSSL knowledge to improve it then.

I'll mark this as an 'enhancement request'.

**Comment by matt335672** [comment]
@ingokeck - do you have the certificate (and private key) which was failing for you still about by any chance?

I've added some logging to the SSL stack and I'd like to test it in a real-world situation.

**Comment by ingokeck** [comment]
@matt335672 Sorry, I did not keep a copy. It probably was the "snakeoil" crt/key that came with the then newest Ubuntu install two years ago in February. Now that I think of it, the machine received a new IP and hostname some months ago. Maybe this generated a mismatch with the certificate and this was the problem?

**Comment by matt335672** [comment]
Well, that's fair enough - I thought it was worth asking anyway.

If the hostname which is used to connect the machine doesn't match one of the names in the certificate, it's really up to the client what to do - the server doesn't know what name the client used to get to it, and in fact the client and server don't necessarily share the same naming infrastructure.

On the Microsoft client there's an option under the `Advanced` tab to say what to do when the authentication of the server fails. I've tried setting this to 'Do not connect' (the strictest setting), and I get the following dialog box on a name mismatch:-

![capture](https://user-images.githubusercontent.com/30179339/122771976-d67b4280-d29e-11eb-8de6-e89c4378e3aa.png)

So no sign of an error x2104 there.

In any case I'll beef up the logging a little and maybe next time it happens to someone we can get more info.
