### ISSUE TITLE
Ubuntu 20.04 - Cannot unlock screen

### ISSUE THREAD

**Issue by cweakland** [neutrinolabs/xrdp#1923]
I have Ubuntu 20.04 running with XRDP, which works great! However, if I lock the screen I cannot unlock it. It lets me enter my password, but I cannot login. The session just hangs:

![image](https://user-images.githubusercontent.com/25326695/121920361-f55d6000-cd05-11eb-9c9d-8c28e0635470.png)

Sadly, there does not look to be much in terms of logs when this happens, here are the syslog entries while I try and unlock:

Jun 14 11:47:03 photon gnome-shell[2149247]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.gnome.DisplayManager.UserVerifier” on object at path /org/gnome/DisplayManager/Session#012cancel@resource:///org/gnome/shell/gdm/util.js:198:32#012destroy@resource:///org/gnome/shell/gdm/util.js:221:14#012_onDestroy@resource:///org/gnome/shell/gdm/authPrompt.js:122:28#012_maybeDestroyAuthPrompt@resource:///org/gnome/shell/ui/unlockDialog.js:698:30#012onComplete@resource:///org/gnome/shell/ui/unlockDialog.js:712:36#012_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:75:13#012_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:220:52
Jun 14 11:47:04 photon dbus-daemon[2590]: [system] Activating via systemd: service name='net.reactivated.Fprint' unit='fprintd.service' requested by ':1.502' (uid=1000 pid=2149247 comm="/usr/bin/gnome-shell " label="unconfined")
Jun 14 11:47:04 photon systemd[1]: Starting Fingerprint Authentication Daemon...
Jun 14 11:47:04 photon dbus-daemon[2590]: [system] Successfully activated service 'net.reactivated.Fprint'
Jun 14 11:47:04 photon systemd[1]: Started Fingerprint Authentication Daemon.

Should I just turn off screen locking? Any help or suggestions would be welcome. 

Update: I wonder if this is because my system does not have a monitor/display powered on. I consoled into the system (Supermicro IPMI), and I am unable to login there either. So I don't think this is really an XRDP issue, but rather an Ubuntu screen lock/monitor issue. Perhaps I need a dummy monitor connection?

**Comment by matt335672** [comment]
Hi @cweakland,

Can I point you in the direction of #1795, in particular [this comment](1795#issuecomment-859357531) and below?

Let us know if any of that describes your situation.

**Comment by cweakland** [comment]
fork=false solves my issue, I am okay with the single login. Thank you sir!

**Comment by matt335672** [comment]
I'll close this then. Feel free to re-comment if you need more info.

**Comment by cweakland** [comment]
Lastly, this post fixes the color-manager authentication issue at login: 

http://c-nergy.be/blog/?p=12043 

Thanks again for your help!
