### ISSUE TITLE
Feature-Request: PNG support for background images and logos

### ISSUE THREAD

**Issue by simdev5281** [neutrinolabs/xrdp#1929]
We have a customised version of XRDP where a previous employee enabled png support for images. Also enabled is the ability to scale center the background image. Compared to bitmap 24 the file size of 30MB is reduced to just 5MB. 

Unfortunately we no longer have the knowledge or skills in our team to customise the latest releases to include this and think that smaller images with the support for transparency would be beneficial to others. I believe @matt335672 may have some knowledge on how this can be achieved already.

**Comment by simdev5281** [comment]
Further to this i think all of the necessary code required is contained within this inherited github account:

https://github.com/simdev5281/xrdp/tree/login-window-png-support/xrdp

**Comment by matt335672** [comment]
Hi @simdev5281 

Discussion #1931 has been raised on this. Feel free to comment.
