### ISSUE TITLE
Glamor and GPU

### ISSUE THREAD

**Issue by EvilDevRu** [neutrinolabs/xrdp#1939]
Hi. I tested glxgears by 3 videocard:
1. 9600k, Intel UHD630 - 3000 frames
2. Ryzen 2600, AMD r9 270 - 1500 frames
3. Ryzen 2600, Nvidia 660 - 1500 frames
I compiled xrdp with glamor option but dont see effect. What am I doing wrong or where can I find information about this? 
Google ask me that xrdp work with amd and intel gpu but I dont see performance.

**Comment by matt335672** [comment]
Hi @EvilDevRu 

There is no glamor option for xrdp.

Did you mean to raise this against [xorgxrdp](/neutrinolabs/xorgxrdp) ?

**Comment by EvilDevRu** [comment]
I compiled by this https://gist.github.com/rkkoszewski/aa531cee7126edf329b76bdd0546f502
Mint 20, Cinnamon

**Comment by matt335672** [comment]
If you run `./configure --help` when you build xrdp itself, you'll see there's no `--enable-glamor` option. This only applies to xorgxrdp.

You need to build xorgxrdp with `--enable-glamor`, and then run xrdp with the Xorg backend so that you pick it up. If you use the Xvnc backend it won't have any effect.

Does that make sense?

**Comment by EvilDevRu** [comment]
Yes, I compiled xorgrdp with glamor, sorry my english. But this no effect.

**Comment by vaaale** [comment]
Hi. I have similar problems. I'm running Ubuntu 20.4 on Proxmox. I have configured PCI passthrough for an Nvidia GTX 1080Ti. Nvidia-smi can see the card, CUDA works as it should, but I'm unable to get GL support for xrdp. I have compiled xrdp and xorgxrdp with glmaor. In my log I see:
.....
[    31.538] (II) xfree86: Adding drm device (/dev/dri/card0)
[    31.539] (EE) systemd-logind: failed to take device /dev/dri/card0: Operation not permitted
[    31.540] (**) OutputClass "nvidia" ModulePath extended to "/usr/lib/x86_64-linux-gnu/nvidia/xorg,/usr/lib/xorg/modules"
[    31.542] (--) PCI:*(1@0:0:0) 10de:1b06:1458:3751 rev 161, Mem @ 0xc0000000/16777216, 0x800000000/268435456, 0x810000000/33554432, I/O @ 0x0000d000/128, BIOS @ 0x????????/524288
.....
[    31.570] (II) Loading /usr/lib/xorg/modules/libglamoregl.so
[    31.576] (II) Module glamoregl: vendor="X.Org Foundation"
[    31.576]    compiled for 1.20.9, module version = 1.0.1
[    31.576]    ABI class: X.Org ANSI C Emulation, version 0.4
[    31.576] rdpPreInit: glamor module load ok
[    31.914] (II) XRDPDEV(0): Refusing to try glamor on llvmpipe
[    31.915] rdpPreInit: glamor init failed
....

I have read and tried everything I can find google.
Any help to solve this issue would be greatly appreciated

**Comment by jsorg71** [comment]
glamor needs to have access to /dev/dri/renderD128 so make sure your user can open it.  You might have to add your user to 'video' group or 'render' group.  xorgxrdp glamor does not need access to /dev/dri/card0.
Glamor only works with amd, intel and nouveau kernel mode drivers.  If you want to use nvidia drivers, there is the nvidia_hack branch.

**Comment by vaaale** [comment]
My user is a member of both video and render group.
I cant see the nvidia_hack branch. Could you paste a link in here?

**Comment by jsorg71** [comment]
Using NVidia is a work in progress so you will need patience.
https://github.com/neutrinolabs/xrdp/issues/1697
https://github.com/jsorg71/xorgxrdp/tree/nvidia_hack

**Comment by vaaale** [comment]
Thanks you.
I'll give it a try and report back if I get it working.

**Comment by EvilDevRu** [comment]
Working! Thanks. 
I was add users to video and render group
