### ISSUE TITLE
How do I run a command after each rdp login?

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [neutrinolabs/xrdp#1942]
I want to run the following command after each RDP login.

`pulseaudio -k`

**Comment by matt335672** [comment]
I believe the environment variable `XRDP_SESSION` is set for an RDP session.

So you could achieve what you want to with something like this in `~/.profile` (single user) or `/etc/profile` (all users):-

```
if [ -n "$XRDP_SESSION" ]; then
    # Running as XRDP session - enter commands here.
    . . .
fi
```

**Comment by roychowdhuryrohit-dev** [comment]
Great thanks. I've managed to solve the issue by running this command.

```
sudo sed -i "4 a #Improved Look n Feel Method\ncat <<EOF > ~/.xsessionrc\nexport GNOME_SHELL_SESSION_MODE=ubuntu\nexport XDG_CURRENT_DESKTOP=ubuntu:GNOME\nexport XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg\n/usr/bin/pulseaudio -k\nEOF\n" /etc/xrdp/startwm.sh
```
Also I removed the existing similar commands from startwm.sh. Is this solution alright?

**Comment by matt335672** [comment]
It should be fine, provided none of your current users are using `.sessionrc` for anything else!

On the other hand:-
1. why not just run those commands as part of `startwm.sh`? 
2. As an alternative, you could just add drop in this file `/etc/X11/Xsession.d/99-xrdp-custom` to your system to do the same::-

```bash
# This file is sourced by Xsession(5), not executed.
if [ -n "$XRDP_SESSION" ]; then
    #Improved Look n Feel Method
    export GNOME_SHELL_SESSION_MODE=ubuntu
    export XDG_CURRENT_DESKTOP=ubuntu:GNOME
    export XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
    usr/bin/pulseaudio -k
fi
```

Any good?

**Comment by roychowdhuryrohit-dev** [comment]
> It should be fine, provided none of your current users are using `.sessionrc` for anything else!
> 
> On the other hand:-
> 
> 1. why not just run those commands as part of `startwm.sh`?
> 2. As an alternative, you could just add drop in this file `/etc/X11/Xsession.d/99-xrdp-custom` to your system to do the same::-
> 
> ```shell
> # This file is sourced by Xsession(5), not executed.
> if [ -n "$XRDP_SESSION" ]; then
>     #Improved Look n Feel Method
>     export GNOME_SHELL_SESSION_MODE=ubuntu
>     export XDG_CURRENT_DESKTOP=ubuntu:GNOME
>     export XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
>     usr/bin/pulseaudio -k
> fi
> ```
> 
> Any good?

1. I'm already running those as a part of startwm.sh if you scroll the full command and check.
2. Thanks for this alternative. 

My solution should be fine for personal use.

**Comment by matt335672** [comment]
OK ta - the main thing is it meets your requirement.

Are you happy to close this one?
