### ISSUE TITLE
The mstsc client exits because of the network disconnection, but the xrdp process does not exit

### ISSUE THREAD

**Issue by leeeening** [neutrinolabs/xrdp#1945]
Hello xrdp team, the mstsc client exited due to network reasons, but the corresponding process of xrdp did not exit, so there will be more and more xrdp processes, so I would like to ask if there is any way to solve it.

**Comment by matt335672** [comment]
Hi @lee415835450 

Two solutions for you:-
- Make sure the session is sending small amounts of data on a regular basis (e.g. a clock in the status bar). This will result in missing peers being detected fairly quickly.
- Set the `tcp_keepalive` option in `/etc/xrdp/xrdp.ini` to set a TCP-level keepalive.

Assuming you're on Linux, the second of these options will take around 2 hours 11 minutes to kill a dead session with default settings. You can tune this at the OS level. See tcp(7) for more details on this.

**Comment by leeeening** [comment]
> Hi @lee415835450
> 
> Two solutions for you:-
> 
> * Make sure the session is sending small amounts of data on a regular basis (e.g. a clock in the status bar). This will result in missing peers being detected fairly quickly.
> * Set the `tcp_keepalive` option in `/etc/xrdp/xrdp.ini` to set a TCP-level keepalive.
> 
> Assuming you're on Linux, the second of these options will take around 2 hours 11 minutes to kill a dead session with default settings. You can tune this at the OS level. See tcp(7) for more details on this.

Thank you very much for your reply, I will seriously consider your reply, and then try to solve this problem.

**Comment by matt335672** [comment]
No more input - closing
