### ISSUE TITLE
vnc cant't work when install xrdp on ubuntu20.04,can I get some help？

### ISSUE THREAD

**Issue by qiaofeng1227** [neutrinolabs/xrdp#1967]
1. I install xfce4-desktop on ubuntu20.04
2. I install tightvncserver
3. It can be connected by my personal pc win10
4. I installed xrdp
```
 apt install xrdp

```
5. I can connect server by win10 remote（xrdp）

![image](https://user-images.githubusercontent.com/43192516/129437351-ee0ecb44-b4c6-4778-9d33-958b0d364d8e.png)

6. but vnc can't work, it can be connected, is gray（step 3 is ok）

![image](https://user-images.githubusercontent.com/43192516/129437363-8ec8f09f-7d45-4ee2-bd7e-5b5d1a3c8ab4.png)

**Comment by qiaofeng1227** [comment]
Can xrdp and tightvnc work together On ubuntu20.04?
It seems ok on CentOS7.9(xrdp and tightvnc work together)

Is additional configuration required On ubuntu20.04?I tried for a long time and failed. Please help me see why

**Comment by matt335672** [comment]
Hi @qiaofeng1227 

I don't understand exactly what you are trying to do here.

- How are you starting the VNC session? Are you starting it from xrdp, or are you starting it elsewhere and connecting to it using xrdp?
- Are you trying to connect to the VNC session over the network?

Thanks

**Comment by matt335672** [comment]
No user response - closing
