### ISSUE TITLE
debian 11 with xrdp doesn't allow shutdown

### ISSUE THREAD

**Issue by pffffffff** [neutrinolabs/xrdp#1968]
I was using xrdp with debian 10.10 without hassle. Today i installed debian 11 and i seen that shutdown doesn't work where right upper edge on the screen. Command "sudo shutdown -h now" works without hassle. Please let shutdown menu work. This is how it looks. https://imgur.com/a/aqFjY52 

Thanks.

**Comment by pffffffff** [comment]
As an extra, setxkbmap overriding doesnt work when i login with xrdp where is located at /home/user/.profile 
Debian 11 compliancy needed

**Comment by metalefty** [comment]
It is controlled by polkit. xrdp doesn't. I recommend asking it Debian community.

**Comment by matt335672** [comment]
To add to what @metalefty has said, shutdown behaviour definitely needs to be configured by the user for remote sessions.

The main reason would be that shutting down the system from any remote session might be fine for your use-case, but it very much wouldn't be fine for a multi-user system. It's not possible to ship a default which will meet all use-cases.

Polkit allows you to fine-tune what remote sessions can or can't do. However, it's nothing to do with us, as that comes down to operating system configuration.

We've got some examples of polkit configuration [in our issues](https://github.com/neutrinolabs/xrdp/issues?q=is%3Aissue+is%3Aclosed+polkit+0.105) which may be of interest to you.
