### ISSUE TITLE
xrdp stuck on logon screen (yes, the vm still currently active)

### ISSUE THREAD

**Issue by spartacruz** [neutrinolabs/xrdp#1970]
Hi there,

I am using Ubuntu 20.04.2 LTS (GNU/Linux 5.11.0-25-generic x86_64) on virtual machine that has been set up from my network admin.

The main problem is : After several hour when I disconnect from VM (not shutdown the vm, just close the RDP windows), I cannot connect back to my VM! When I said "after several hour", yes its true. If I only leaved it for couple minutes, RDP can connect normally.

Here is the step:
1. start RDP from windows 10 machine
2. Fill the username & password then click `OK`
3. After `OK` was click, xrdp just freezing for a moment (around 10 - 15 seconds i guess, no button nor dropdown session could be clicked)
4. Then nothing was changed on screen. If I click `OK` one more time, It will back to 'freeze mode'

![image](https://user-images.githubusercontent.com/18097823/129824971-d696b72d-4dca-4ca7-949c-28f8da476bce.png)

I already tried some solution on stackoverflow and this [issue thread](https://github.com/neutrinolabs/xrdp/issues/1795), but still has not been solved my current problem. The only way to connect is restarting the xrdp services through ssh.

Could someone please assist me what I must to do? How to fix & prevent this issue?

Thanks.

**Comment by matt335672** [comment]
Best to look in the log files I think.

When this happens again:-

1) Make a note of the system time
2) Try to log in
3) Paste the lines which are added to `/var/log/xrdp.log` and `/var/log/xrdp-sesman.log` after the time you noted in step 1

Thanks.

**Comment by buhtz** [comment]
Please look at this, which helped me
https://tecadmin.net/how-to-install-xrdp-on-debian-10/

I think the possible relevant points are the `usermod` command and the two extra lines added to the `/etc/xrdp/startwm.sh` file.

Does it help in your case?

**Comment by spartacruz** [comment]
Hi folks,

I decided to change the system to be VNC.
So, I do apologize if you are waiting. I am closing this issue.
