### ISSUE TITLE
Improve log message: "Security layer: requested 3, selected 1"

### ISSUE THREAD

**Issue by buhtz** [neutrinolabs/xrdp#1974]
Xrdp's log (`0.9.12-1` from _Debian 11_ `stable`) often has entries like this

```
Security layer: requested 0, selected 1

Security layer: requested 3, selected 1
```

It is unclear what it means. We do not need the answer here in this Issue but in the log itself.

Please clarify the log message that it can be understood by the user/admin who reads the log messages.

**Comment by metalefty** [comment]
Indeed, that should be improved.

**Comment by matt335672** [comment]
Log messages can only be read by admins.

I've written a quick PR to log the negotiated security level as text strings as-per [[MS-RDPBCGR] 2.2.1.1.1](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/902b090b-9cb3-4efc-92bf-ee13373371e3)
