### ISSUE TITLE
Recreating correct filesystem rights for .thinclient_drives

### ISSUE THREAD

**Issue by will-code-for-pizza** [neutrinolabs/xrdp#1979]
Hi,

we occasionally have the problem that a single user loses the rights to his subdirectory '`/home/[user]/.thinclient_drives`'.

Per default, this directory is equipped with the following rights:

`drwxr-xr-t   2 user usergroup            4096 Sep 25  2020  .thinclient_drives/`

But in this specific home directory the rights changed again to:

`d?????????   ? ?    ?               ?            ?  .thinclient_drives/`

(done with '`# ls -aln`')

The question is, how to recreate the correct filesystem rights without restarting xrdp ?
( > 100 users online)

Cheers and many thanks in advance.
Will

**Comment by will-code-for-pizza** [comment]
I found the solution:

User is not logged in

```
# umount /home/[user]/.thinclient_drives
# rm -rf /home/[user]/.thinclient_drives
```

After re-login, everything is fine.

Regards

**Comment by metalefty** [comment]
BTW, that should be fixed automatically. There's some room to improve xrdp fuse.
