### ISSUE TITLE
xrdp not connecting at all

### ISSUE THREAD

**Issue by Xycronic** [neutrinolabs/xrdp#1982]
Yesterday xrdp was working perfectly fine. I rebooted my Ubuntu machine last night and when I try connecting today it's not working at all.

> Remote Desktop can't connect to the remote computer for one of these reasons:
> 
> 1) Remote access to the server is not enabled
> 2) The remote computer is turned off
> 3) The remote computer is not available on the network

xrdp is active when I run `sudo systemctl status xrdp` and ufw is disabled. I don't know where the problem is.

**Comment by matt335672** [comment]
Hi @XInterverse 

That suggests a problem at the network level.

- Check the hostname you're using from Windows resolves to the IP address of the Ubuntu machine. You can do that with the ping command from a cmd prompt.
- Use `sudo ss -lp 'sport = 3389'` on the Ubuntu side to check the expected process is listening on port 3389, on all interfaces.
- If you've got `nmap` on any remote machine, use `nmap -p 3389 <ubuntuhost>` to check the port is visibly open.

**Comment by XInterverse** [comment]
Hi @matt335672. Thanks for pointing me in the right direction. I figured out it was iptables that was blocking the connection. However now I'm facing a new issue when I try to login:

> connecting to sesman ip 127.0.0.1 port 3350
> sesman connect ok
> sending login info to session manager, please wait...
> login failed for display 0

This is the log file `xrdp.log`:
```[20210904-13:54:07] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
[20210904-13:54:07] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20210904-13:54:07] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
[20210904-13:54:07] [DEBUG] return value from xrdp_mm_connect 0
[20210904-13:54:08] [INFO ] xrdp_wm_log_msg: login failed for display 0
[20210904-13:54:08] [DEBUG] xrdp_mm_module_cleanup
[20210904-13:54:08] [DEBUG] Closed socket 16 (AF_INET6 ::1 port 41950)
```

Log file for `xrdp-sesman.log`:
```
[20210904-13:54:07] [INFO ] A connection received from ::1 port 41950
[20210904-13:54:08] [DEBUG] Closed socket 8 (AF_INET6 ::1 port 3350)
```

**Comment by Xycronic** [comment]
Hi @matt335672, thanks for pointing me in the right direction!
I figured out that it was iptables that was blocking the connection.

Thanks for your help.
