### ISSUE TITLE
Missing rfb_get_eds_status_msg() function in vnc/vnc.c in 0.9.17

### ISSUE THREAD

**Issue by bsmojver** [neutrinolabs/xrdp#1986]
This is preventing modern Fedora version from loading libvnc.so, because of the missing symbol in the shared library. I trivially patched that in the RPMs, which I am building now, but the implementation of the function was likely missed in the release.

**Comment by metalefty** [comment]
Can you share us the build log?

**Comment by bsmojver** [comment]
Example: https://koji.fedoraproject.org/koji/buildinfo?buildID=1826493

**Comment by matt335672** [comment]
Hi Bojan,

Thanks for this. I've had a look back and I introduced this in commit fe28af93e888e2617d310f4bded7ae468095124c. The fix I've submitted is even more trivial than your patch!

At first I didn't understand why I hadn't picked this up in local testing on Ubuntu 20.04. I traced things through and found we're passing `RTLD_LAZY` to `dlopen()` which would explain this.

Clearly you're overriding this flag in Fedora. Do you have a view on our use of `RTLD_LAZY` here?

**Comment by bsmojver** [comment]
I think these overrides come from Fedora build system. The same build works OK on RHEL 7, for example, because it simply ignores the symbol it cannot immediately resolve and loads libvnc.so. I am not entirely sure why Fedora build system decided to go this way, but this must have been announced in one of the features, in preparation of a release. I'll try to dig this up for you.

Maybe they are try to protect against shared libraries crashing when a symbol that cannot be resolved is actually invoked.

**Comment by matt335672** [comment]
Yes, it may be that. A reference will be useful if you can find one.

We can maybe add a development option to the xrdp build config to disable `RTLD_LAZY`. That should catch any future occurrences of this during module testing.

**Comment by bsmojver** [comment]
I haven't looked at the code around dlopen() in xrdp, but maybe it would be worth printing dlerror() on failure, if not already the case.

**Comment by bsmojver** [comment]
Probably this (i.e. -Wl -z now):

https://fedoraproject.org/wiki/Changes/Harden_All_Packages

Disable lazy binding, if I'm not mistaken.

**Comment by matt335672** [comment]
Yes, I think you're right.

I'll start a discussion on this.

**Comment by matt335672** [comment]
Discussion moved to #1991

**Comment by matt335672** [comment]
I've just realised I've left out an additional change for the Makefile for vnc. Patch to follow...

@bsmojver - apologies for the extra work I'm generating for you.

**Comment by bsmojver** [comment]
Please don't apologise! Thank you for contributing to xrdp!
