### ISSUE TITLE
clipboard file: xrdp is not responding CB_RESPONSE_FAIL even if it failed

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#1997]
When `clipboard_send_file_data` fails due to the file is not readable or other reasons, the client waits to finish file transfer forever. Maybe we need to abort file transfer gracefully. 

![スクリーンショット 2021-09-15 15 36 12](https://user-images.githubusercontent.com/941609/133383004-0945ead2-7873-4ec0-b7e7-d6b2137bfa74.png)

```
meta@xrdp:~/xrdp$ tail -f ~/.local/share/xrdp/xrdp-chansrv.10.log
[20210915-06:35:14] [DEBUG] [process_message_channel_data(chansrv.c:446)] process_message_channel_data: chan_id 2 chan_flags 19
[20210915-06:35:14] [DEBUG] [clipboard_data_in(clipboard.c:1523)] clipboard_data_in: chan_id 2 chan_flags 0x13 length 32 total_length 32 in_request 0 g_ins->size 8192
[20210915-06:35:14] [DEBUG] [clipboard_data_in(clipboard.c:1586)] clipboard_data_in: clip_msg_id 8 clip_msg_status 0 clip_msg_len 24
[20210915-06:35:14] [DEBUG] [clipboard_data_in(clipboard.c:1591)] clipboard_data_in: 8
[20210915-06:35:14] [DEBUG] [clipboard_process_file_request(clipboard_file.c:508)] clipboard_process_file_request:
[20210915-06:35:14] [DEBUG] [clipboard_send_file_data(clipboard_file.c:408)] clipboard_send_file_data: streamId 24422 lindex 0 nPositionLow 0 cbRequested 34520
[20210915-06:35:14] [ERROR] [clipboard_send_file_data(clipboard_file.c:415)] clipboard_send_file_data: file open [/home/meta/Downloads/paper.docx] failed
[20210915-06:35:14] [DEBUG] [scard_pcsc_check_wait_objs(smartcard_pcsc.c:401)] scard_pcsc_check_wait_objs:
[20210915-06:35:14] [DEBUG] [scard_pcsc_get_wait_objs(smartcard_pcsc.c:374)] scard_pcsc_get_wait_objs:
[20210915-06:35:14] [DEBUG] [get_timeout(chansrv.c:153)] get_timeout:
```

I haven't read MS-RDPECLIP corner to corner yet however I guess xrdp should respond to [ File Contents Request PDU](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/cbc851d3-4e68-45f4-9292-26872a9209f2) with [File Contents Response PDU](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/df87c178-ab02-471a-acde-bb921aa1af85) that contain `CB_RESPONSE_FAIL` to indicate "the request could not be satisfied". 

I quickly performed `git grep CB_RESPONSE_FAIL` but it was not used in `clipboard_file.c` at all.  The return value of `clipboard_send_file_size` and `clipboard_send_file_data` should be checked and xrdp should return `CB_RESPONSE_FAIL` when they failed.

https://github.com/neutrinolabs/xrdp/blob/23742dbb8ef4f3a0b2d7d911bafd09153c6193da/sesman/chansrv/clipboard_file.c#L496-L526

**Comment by metalefty** [comment]
I think using `goto` like this is not a bad idea in error management. It will work well rather than checking return values.

```diff
diff --git a/sesman/chansrv/clipboard_file.c b/sesman/chansrv/clipboard_file.c
index c317da79..f2ee9b3b 100644
--- a/sesman/chansrv/clipboard_file.c
+++ b/sesman/chansrv/clipboard_file.c
@@ -414,7 +414,7 @@ clipboard_send_file_data(int streamId, int lindex,
     {
         LOG_DEVEL(LOG_LEVEL_ERROR, "clipboard_send_file_data: file open [%s] failed",
                   full_fn);
-        return 1;
+        goto fail_example;
     }
     if (g_file_seek(fd, nPositionLow) < 0)
     {
@@ -450,6 +450,20 @@ clipboard_send_file_data(int streamId, int lindex,
     LOG(LOG_LEVEL_INFO, "S2C: Transfered a file: filename=%s, uid=%d", full_fn, g_getuid());

     return rv;
+
+fail_example:
+    if (s == NULL)
+    {
+        make_stream(s);
+        init_stream(s, cbRequested + 64);
+    }
+
+    out_uint16_le(s, CB_FILECONTENTS_RESPONSE);
+    out_uint16_le(s, CB_RESPONSE_FAIL);
+
+    s_mark_end(s);
+    free_stream(s);
+    return 1;
 }
```

**Comment by matt335672** [comment]
I've had a look at [MS-RDPECLIP] sections [2.2.5.4](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/df87c178-ab02-471a-acde-bb921aa1af85) [3.1.5.4.6](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/d19de33e-4027-43de-b150-668ee21bced8) and [3.1.5.4.7](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/d19de33e-4027-43de-b150-668ee21bced8), and I agree that we should be sending a CB_RESPONSE_FAIL

The `goto` discussion is an interesting one. Personally I don't find it any worse than returning in the middle of a function, which we do anyway. However, opinions on this one vary and I know @aquesnel is [against it for new code](https://github.com/neutrinolabs/xrdp/pull/1895#pullrequestreview-670919160). I'd prefer to avoid using it if there's an alternative that's just as clear.

I'd suggest replacing your example above with an early return. So your code above becomes:-

<pre>
    {
         <s>LOG_DEVEL(LOG_LEVEL_ERROR, "clipboard_send_file_data: file open [%s] failed",</s>
                   <s>full_fn);</s>
        LOG(LOG_LEVEL_ERROR, "clipboard_send_file_data: file open [%s] failed : %s",
                   full_fn, g_get_strerror());
        clipboard_send_filecontents_response_fail(streamId);
        return 1;
    }
</pre>

and `clipboard_send_filecontents_response_fail()` looks like this. This is off the top of my head and hasn't been tested:-

```c
/***
 * Sends a failure response to a CLIPRDR_FILECONTENTS_REQUEST
 * @param streamId Stream ID from CLIPRDR_FILECONTENTS_REQUEST
 * @return 0 for success
 */
static int
clipboard_send_filecontents_response_fail(int streamId)
{
    struct stream *s;
    int size;

    make_stream(s);
    init_stream(s, 64);

    out_uint16_le(s, CB_FILECONTENTS_RESPONSE); 
    out_uint16_le(s, CB_RESPONSE_FAIL); 
    out_uint32_le(s, 4);
    out_uint32_le(s, streamId);
    s_mark_end(s);
    size = (int)(s->end - s->data);
    rv = send_channel_data(g_cliprdr_chan_id, s->data, size);
    free_stream(s);
    return rv;
}
```

There are two advantages to this approach:-
1) We do early returns all over the place, so any developer working on xrdp will need to be used to this.
2) As you say, you are going to need to do something similar in `clipboard_send_file_size()`. You can just insert calls to `clipboard_send_filecontents_response_fail()` into that, so we've got less code overall.

A couple of minor points:-
1) There are LOG_DEVEL() calls all over the place here which should probably be LOG() instead. I've changed one above.
2) The `streamId` name comes straight out of [MS-RDPECLIP] but is not compatible with our coding standard. I don't know whether it's better to leave this as it is, or change it to `stream_id` or `streamid`.

**Comment by aquesnel** [comment]
Hi,
I agree with @matt335672 about creating a function to send the `CB_RESPONSE_FAIL` error.

For the variable naming, my recommendation is to follow the xrdp style guide for variable names in the code, and use the exact MS-RDP specification names when logging the variable's value.

**Comment by metalefty** [comment]
Thanks for the comments. I'll try to implement it that way.
