### ISSUE TITLE
Xrdp and Matlab from MatWorks inputs

### ISSUE THREAD

**Issue by gschwind** [neutrinolabs/xrdp#2009]
Hello,

I do not know the source of the issue, but sometime Maltab user under Xorg xrdp experience some freezes. The freezes are only on Matlab side and other application like the terminal does not freeze. The freeze can last few seconds and they repeating once they started, before freeze start every thing may be smooth for several hours but some time few minute are enough to raise the issue

I do not have any idea of the root of the issue, does some X11 request pattern may block Xrdp ?

Some places on internet reporting this kind of freeze but they do not seems to identify the source of the issue.

Best regards

**Comment by matt335672** [comment]
Hmm. This doesn't sound like an xrdp issue.

The X server is single-threaded, so hanging that will hang all the clients. Also, at the xrdp level, the X server isn't really aware of individual clients. So I could understand a freeze of the whole server, but not a freeze of a single client. It's not something I've seen reported before.

Matlab is a commercial product. Only Matlab have access to Matlab sources. We don't so it's not going to be possible for us to reproduce this.

Your best bet to solve this is to contact Matlab support and supply them with sufficient information to solve the freeze.

You can try switching to the Xvnc back-end. The difference with the Xvnc backend as opposed to the Xorg backend is that the Xvnc server is a completely standalone executable, so it removes xrdp from the problem completely.

There's a couple of standard utilities you might use to try to find out what Matlab is doing:-
1) pstack will print a stack trace of where the executable is. It only works for 32-bit ELF executables however. I don't know if Matlab is a 32-bit executable. Furthermore, it needs debug symbols in the executable to be useful.
2) strace will tell you what system calls are being made. It might tell you if (for example) Matlab has issued a blocking read to something.
3) You could attach a debugger to Matlab while it's frozen and try to figure out what it's doing. Again, this needs debug symbols to be useful.

Hope that's at least a bit useful.

**Comment by gschwind** [comment]
Thank you for this feed back.

I will give a try to Xvnc, and maybe also give a try to gdb. I guess matlab is using glibc and libX11 thus I may be able to trace what going on there.

I already seen some post about it to Matlab web site without any good explanation or answer from MatWorks. The issue is quite annoying because it does not raise that often.

Best regards.

**Comment by matt335672** [comment]
I had a quick poke about, and I can see what you mean,

It seems likely Matlab is doing something in the background which is preventing it from servicing the X event loop. It could be a blocking X11 call. There's so many possibilities. From your description, it could be a network resource which is unavailable from time-to-time. My Active Directory memories are a bit hazy these days, but if you're using Active Directory, you might want to look at DC availability when it happens, particularly remote DCs if your user belongs to any Universal Groups. This is all guesswork on my part.

**Comment by matt335672** [comment]
Hi @gschwind 

Have you managed to get anywhere with this one yet?

**Comment by gschwind** [comment]
Hello @matt335672 

I did not had time to make a formal check, I currently investigate another possible cause of the issue, linked to the file system.

Best regards

**Comment by matt335672** [comment]
I'm closing the issue for now, due to a lack of activity. Feel free to comment again if there's anything more we can do to help you with this from an xrdp perspective.

**Comment by gschwind** [comment]
Hello, I will reopen it if needed, currently it's seems that the issue does not occure anymore, maybe some update of X11 libraries fixed the issue.

Best regards
