### ISSUE TITLE
Support TLS certificate chains

### ISSUE THREAD

**Issue by ygoe** [neutrinolabs/xrdp#201]
XRDP will only provide the host certificate when using TLS security, but ignore the CA certificates in the same file. There doesn't seem to be a config option to specify a chain file. The best option would be to simply consider additional chained certificates in the specified PEM file like other TLS-enabled servers do. You just don't get non-chained signed certificates out there anymore.

**Comment by speidy** [comment]
Doubled checked it now.
From looking at a network trace, I can see the certificate chain is sent to the client as well as the server certificate itself.
Please make sure your cert file is ordered correctly: server certificate first, intermediate certificate (if any) after, then root CA cert.

**Comment by akkornel** [comment]
Hello!

I just recently started using Xrdp on CentOS 7 (installing the latest from epel).  I am using TLS, with a certificate chain.  My cert.pem file has the server's certificate first, followed by all intermediates.  The order looks like this:

• Client cert.
• Intermediate cert 1, that issued client cert.
• Intermediate cert 2, that issued intermediate cert 1.
• Root cert, that issues intermediate cert 2.

(BTW, this is the same ordering that Apache 2.4 accepts for certificate files.)

That is the certificate configuration I have, and things work fine!  I am able to use the Microsoft Remote Desktop client on macOS, and I do not get any certificate warnings.

**Comment by speidy** [comment]
@akkornel Thanks for testing this.

**Comment by ygoe** [comment]
Oh, please don't expect any further input from me, I've given up on xrdp long ago. I'm back on SSH shell only for my server admin work.

**Comment by akkornel** [comment]
@ygoe In that case, would you mind hitting the close button?  Thanks much!

**Comment by metalefty** [comment]
I close this.
