### ISSUE TITLE
I have a problem when using xrdp + chrome

### ISSUE THREAD

**Issue by MagicStarTrace** [neutrinolabs/xrdp#2012]
**Environment and version description**

OS Version: ubuntu 18.04
Google Chrom Version: 94.0.4606.61
xrdp Version: 0.9.5-2

**Problem Description**
When I use vncserver, I see that the font of chrom is not indented and the layout is neat

![image](https://user-images.githubusercontent.com/15685376/136495086-d0887c17-4128-41e7-834c-dbccb004e86f.png)

After using xrdp, but the layout has been adjusted

![image](https://user-images.githubusercontent.com/15685376/136495529-5c6bae8a-972b-4c3c-8592-b0160e7074ba.png)
Is there a way to prohibit xrdp from adjusting the chrom font typesetting?

Thank You!

**Comment by matt335672** [comment]
@huyifanstar - that may be caused by a difference between your two environments, although it's not obvious exactly what. The Ubuntu packaging for xrdp doesn't completely replicate the login environment.

In your vncserver session can you execute this command?

```
env | sort >/tmp/vnc.txt
```

Then in your xrdp session execute this command:-

```
env | sort >/tmp/xrdp.txt
```

and then have a look at the difference between the two:-

```
diff -u /tmp/vnc.txt /tmp/xrdp.txt
```

**Comment by MagicStarTrace** [comment]
> @huyifanstar - that may be caused by a difference between your two environments, although it's not obvious exactly what. The Ubuntu packaging for xrdp doesn't completely replicate the login environment.
> 
> In your vncserver session can you execute this command?
> 
> ```
> env | sort >/tmp/vnc.txt
> ```
> 
> Then in your xrdp session execute this command:-
> 
> ```
> env | sort >/tmp/xrdp.txt
> ```
> 
> and then have a look at the difference between the two:-
> 
> ```
> diff -u /tmp/vnc.txt /tmp/xrdp.txt
[diff.txt](https://github.com/neutrinolabs/xrdp/files/7311166/diff.txt)

**Comment by matt335672** [comment]
They're fairly different.

I've had a look back over previous issues, and I've found this patch from #1773. Can you edit your `/etc/xrdp/starwm.sh` and add the lines below in bold?

<pre>
#!/bin/sh
# xrdp X session start script (c) 2015, 2017 mirabilos
# published under The MirOS Licence

<b># Emulate pam_env.so
if test -r /etc/environment; then
    . /etc/environment
fi</b>

if test -r /etc/profile; then
    &lt;snipped&gt;
</pre>

That should make the two sessions a lot more alike.

**Comment by MagicStarTrace** [comment]
> /etc/xrdp/starwm.sh

"/etc/xrdp/starwm.sh" could not find it

/etc/xrdp/startwm.sh ?

**Comment by matt335672** [comment]
@huyifanstar - did this actually solve your problem?

Thanks for any info.

**Comment by MagicStarTrace** [comment]
> @huyifanstar - 这真的解决了你的问题吗？
> 
> 感谢您提供任何信息。

I found the reason, the problem with chrom
