### ISSUE TITLE
Has anyone tried Pipewire w/XRDP yet?

### ISSUE THREAD

**Issue by bmullan** [neutrinolabs/xrdp#2020]
Pulseaudio works well but it can be difficult to get working in some instances.

I've been following the progress of Pipewire and people are reporting its working well for audio (video is still being worked on from what I understand).

Anyone tried Pipewire yet over xrdp and get it working?   If so, any config tips/info.

thanks.
brian

**Comment by matt335672** [comment]
Hi Brian,

No - not yet. The Pulseaudio code works but it goes in at quite a low level, and this method won't be supported natively by Pipewire.

I've started discussion #2323 on this (closing this issue) and summarise the main points as I see them.

The bottom line is we need to do a bit of design work in this area, and at the moment we don't really have enough information to complete that task.
