### ISSUE TITLE
Resolution-dependent `ls_background_image`

### ISSUE THREAD

**Issue by rathann** [neutrinolabs/xrdp#2024]
It would be nice to have an option to load a different login scree background image (`ls_background_image` `xrdp.ini` option) depending on client resolution.

**Comment by matt335672** [comment]
Hi @rathann,

The development version of xrdp includes image scaling and zooming support - see #1962 

Are you asking for something over and above what this provides?

**Comment by rathann** [comment]
My company provides a set of branded backgrounds tailored to different resolutions, eg. 1920x1080, 2560x1440, 3840x2160, etc. I'm looking for a way to select the appropriate image based on client resolution if possible.

**Comment by matt335672** [comment]
That's interesting - thanks.

I'm going to convert this to a a discussion so we can (hopefully) widen out the conversation a bit.
