### ISSUE TITLE
Using GUI to copy file in thinclient_drives hangs chansrv hard

### ISSUE THREAD

**Issue by matt335672** [neutrinolabs/xrdp#2031]
I should have raised this earlier - apologies for that.

I noted in #1563 that:-

> When I CTRL-C on a file under `thinclient_drives`, chansrv execution enters `clipboard_get_file()` from where it calls
> `g_directory_exist()`. This results in a `stat()` system call which needs to be serviced by chansrv, but it can't be as it's still
> servicing the copy request.

A hung chansrv is bad enough, but I've lately realised that the implications of this are a lot worse than I realised. chansrv hangs hard when this happens and doesn't respond to SIGTERM. As a result the logic to end the session in session.c gets stuck in g_waitpid_status() waiting for chansrv to exit:-

https://github.com/neutrinolabs/xrdp/blob/e867c925d5f002d80c2d1ca4422ef70b68848b4c/sesman/session.c#L900-L910

As a result of this, sesman doesn't get the SIGCHLD from the session exiting, and the user is unable to log in again, as sesman tells them to connect to a session which is no longer there. This can produce artefacts like that noted in #2021

**Comment by nikimagic** [comment]
Да, у меня было такое! При копи пасте, зависало,  а потом спустя время, я не мог переподключиться в свой сеанс. Приходилось уничтожать сеанс из под другого пользователя.
