### ISSUE TITLE
Windows clipboard inbound and outbound control without sesman？

### ISSUE THREAD

**Issue by Chan-ZhiHao** [neutrinolabs/xrdp#2038]
I have a requirement that control clipboard inbound and outbound without sesman. In the new version， in sesman can control one-way clipboard data by a setting in the sesman.ini. But now I connect to windows server without sesman. How can I modify the code to realize the same effect.

**Comment by matt335672** [comment]
Hi @Chan-ZhiHao 

I don't completely understand exactly what you are trying to do.

Are using NeutrinoRDP to connect to a Windows Server? Also what is the setting you were using in `sesman.ini`?

Thanks,

**Comment by Chan-ZhiHao** [comment]
Yeah, I'm using NeutrinoRDP to connect to a Windows Sever. Can I control local client side  upload or download data through the clipboard alone？ In other words，I want to control both clipboard from server push to client and clipboard from client push to the server.

**Comment by matt335672** [comment]
You can't do this from xrdp, as far as I'm aware.

The neutrinordp module is just a proxy. The clipboard data is carried on the `cliprdr` RDP virtual channel channel. The PDUs from this channel are just passed through without any inspection.

You can probably block the channel completely, but finer-grained configuration will need to be done at the client or the server.
