### ISSUE TITLE
RDP_INPUT_SYNCHRONIZE not working in fastpath input

### ISSUE THREAD

**Issue by jsorg71** [neutrinolabs/xrdp#204]
keyboard sync not working in Xorg, X11rdp, or RDP proxy when client uses fastpath input

**Comment by System25** [comment]
Hi Jay Sorg, the problems seems to be in "xrdp_process_data_in". 
It sets "header_size" to 4 bytes, but Fast-Path Synchronize Event (TS_FP_SYNC_EVENT) is 3 bytes long.
That causes "trans_check_wait_objs" to fail because it will never ever be (read_so_far == self->header_size) (4 == 3).

Maybe a workaround could be something like:

        case 1:
            /* we have enough now to get the PDU bytes */
            len = libxrdp_get_pdu_bytes(s->data);
            if (len == -1)
            {
                g_writeln("xrdp_process_data_in: "
                          "xrdp_process_get_packet_bytes failed");
                return 1;
            }
			
			if (len == 3)
			{
				/* Special fast path frames */

				/* Process it */
				s->p = s->data;
				s->end = s->data + 3;
				if (xrdp_process_loop(pro, s) != 0)
				{
					g_writeln("xrdp_process_data_in: "
							  "xrdp_process_loop failed");
					return 1;
				}				

				/* Set the extra read byte as the first byte of a new frame */
				s->data[0] = s->data[3];
				s->end = s->data + 1;
				s->p = s->end;
				
				pro->server_trans->header_size = 4;
				pro->server_trans->extra_flags = 1;
			}
			else 
			{
				pro->server_trans->header_size = len;
				pro->server_trans->extra_flags = 2;
			}
            break;


Best regards!

**Comment by System25** [comment]
Oh! I discovered that you must set "s->next_packet = 0;" too.

            /* Set the extra read byte as the first byte of a new frame */
            s->data[0] = s->data[3];
            s->end = s->data + 1;
            s->p = s->end;
            s->next_packet = 0;

Best regards

**Comment by jsorg71** [comment]
I can't see how that can happen.
https://msdn.microsoft.com/en-us/library/cc240596.aspx
shows Fast-Path Synchronize Event 1 byte long plus three for the header.
Do you see a fast path length of three?

**Comment by jsorg71** [comment]
Oh, I see, if the fast path length field is 1 byte, the header size is 2 bytes and the total size if 3 bytes.

**Comment by jsorg71** [comment]
I create PD #425 maybe this will fix it.

**Comment by System25** [comment]
Hi Jay,
 I've tested it and PR #425 fix the problem.
Thanks
