### ISSUE TITLE
xrdp not working as expected if installed with `sudo`

### ISSUE THREAD

**Issue by IzaacJ** [neutrinolabs/xrdp#2051]
Hello

I've got Debian 11 running on my laptop, with XFCE4, xrdp 0.9.12 and xorgxrdp 0.2.12. I'm connecting from my Windows 11 desktop.

I was logged in with my user `izaac` when I installed xrdp (`sudo apt install xrdp`) and can connect and log in with my `root` user without any problems. However, as soon as I log out `izaac` locally, I can't even connect to the machine, ie I get the `Couldn't connect to server` error.

Logging in with `root` locally and running `service xrdp status` I can see that the service is running, and `netstat -tulpn` I can see that xrdp is listening on `tcp://0.0.0.0:3389`, but I'm still unable to even connect to the machine.

What could be causing this?

EDIT: I purged xrdp and installed it whilst logged on as `root`, and now it works as I expected it to do when doing `sudo apt install xrdp`.

**Comment by matt335672** [comment]
There's really no difference between installing any package as root and with `sudo`, so it seems likely something else is going on here.

The 'could not connect to server' error suggests a network issue between the two machines. You can use `ping` on a cmd prompt from the Windows machine to check basic connectivity. This will also give you the IP address that the Windows machine thinks is assigned to the laptop. Check this on the laptop with `ip addr`.

Have you configured a firewall on the laptop?

**Comment by IzaacJ** [comment]
First off, I always use IP, and all my devices in my home network has reserved IPs, so that is not an issue. And being a network problem would be highly improbable since they're both wired to the same switch underneath my desk.
My guess is that the xrdp server wasn't running when I logged out of the local account, which would give the same error.

I could double check this, but am quite occupied atm with my studies (sysadmin student, last course exam this week and then a master thesis to write).

**Comment by matt335672** [comment]
Your studies are definitely more important than this issue.

If you want to revisit this when you've got more time, please do. Your guess could indeed be correct.
