### ISSUE TITLE
XRDP Fails to start for unknown reason

### ISSUE THREAD

**Issue by TheKaese** [neutrinolabs/xrdp#2052]
Does anyone know how to resolve this? This was seemingly working up until the 7th and then all of a sudden I'm getting this error whenever xrdp starts.. This is an attempt at resinstalling xrdp:

    # apt -y install xrdp
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Suggested packages:
      guacamole xrdp-pulseaudio-installer
    The following NEW packages will be installed:
      xrdp
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 435 kB of archives.
    After this operation, 2,971 kB of additional disk space will be used.
    Get:1 http://deb.debian.org/debian buster/main amd64 xrdp amd64 0.9.9-1+deb10u1 [435 kB]
    Fetched 435 kB in 0s (2,104 kB/s)
    Selecting previously unselected package xrdp.
    (Reading database ... 64507 files and directories currently installed.)
    Preparing to unpack .../xrdp_0.9.9-1+deb10u1_amd64.deb ...
    Unpacking xrdp (0.9.9-1+deb10u1) ...
    Setting up xrdp (0.9.9-1+deb10u1) ...
    A dependency job for xrdp.service failed. See 'journalctl -xe' for details.
    invoke-rc.d: initscript xrdp, action "restart" failed.
    ● xrdp.service - xrdp daemon
       Loaded: loaded (/etc/systemd/system/xrdp.service; enabled; vendor preset: enabled)
       Active: inactive (dead)
         Docs: man:xrdp(8)
               man:xrdp.ini(5)
    
    Nov 12 09:22:28 Cerberus systemd[1]: Dependency failed for xrdp daemon.
    Nov 12 09:22:28 Cerberus systemd[1]: xrdp.service: Job xrdp.service/start failed with result 'dependency'.
    Nov 12 10:43:41 Cerberus systemd[1]: Dependency failed for xrdp daemon.
    Nov 12 10:43:41 Cerberus systemd[1]: xrdp.service: Job xrdp.service/start failed with result 'dependency'.
    dpkg: error processing package xrdp (--configure):
     installed xrdp package post-installation script subprocess returned error exit status 1
    Processing triggers for systemd (241-7~deb10u8) ...
    Processing triggers for man-db (2.8.5-2) ...
    Processing triggers for libc-bin (2.28-10) ...
    Errors were encountered while processing:
     xrdp
    E: Sub-process /usr/bin/dpkg returned an error code (1)

I think it's because I must have done an upgrade on the 7th, but there's nothing in the log files and journalctl -xe just says the same thing:

    -- Logs begin at Fri 2021-11-12 09:20:54 CST, end at Fri 2021-11-12 10:48:39 CST. --
    Nov 12 09:22:28 Cerberus systemd[1]: Dependency failed for xrdp daemon.
    -- Subject: A start job for unit xrdp.service has failed
    -- Defined-By: systemd
    -- Support: https://www.debian.org/support
    --
    -- A start job for unit xrdp.service has finished with a failure.
    --
    -- The job identifier is 67 and the job result is dependency.
    Nov 12 09:22:28 Cerberus systemd[1]: xrdp.service: Job xrdp.service/start failed with result 'dependency'.
    Nov 12 10:43:41 Cerberus systemd[1]: Dependency failed for xrdp daemon.
    -- Subject: A start job for unit xrdp.service has failed
    -- Defined-By: systemd
    -- Support: https://www.debian.org/support
    --
    -- A start job for unit xrdp.service has finished with a failure.
    --
    -- The job identifier is 932 and the job result is dependency.
    Nov 12 10:43:41 Cerberus systemd[1]: xrdp.service: Job xrdp.service/start failed with result 'dependency'.

Anybody have any idea *what* dependency is failing?

Debian Buster: Linux Cerberus 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

**Comment by matt335672** [comment]
Have a look at the configured systemd unit file with `systemctl cat xrdp.service`

On my system I get the following. Yours should be the same unless you've overridden it:-

```
$ systemctl cat xrdp.service
# /lib/systemd/system/xrdp.service
[Unit]
Description=xrdp daemon
Documentation=man:xrdp(8) man:xrdp.ini(5)
Requires=xrdp-sesman.service
After=network.target xrdp-sesman.service

[Service]
Type=forking
PIDFile=/var/run/xrdp/xrdp.pid
RuntimeDirectory=xrdp
EnvironmentFile=-/etc/sysconfig/xrdp
EnvironmentFile=-/etc/default/xrdp
User=xrdp
Group=xrdp
PermissionsStartOnly=true
ExecStartPre=/bin/sh /usr/share/xrdp/socksetup
ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS
ExecStop=/usr/sbin/xrdp $XRDP_OPTIONS --kill

[Install]
WantedBy=multi-user.target
```

The obvious dependency is on `xrdp-sesman.service`. What is the status of that?
