### ISSUE TITLE
clipboard: possibility of unused code in clipboard_event_selection_notify for s2c

### ISSUE THREAD

**Issue by kenhys** [neutrinolabs/xrdp#2072]
# Problem

Reading clipboard.c and logging with `clipboard.c=DEBUG` in `[ChansrvLoggingPerLogger]` section sesman.ini,
It seems that unused code execution path exists when copying s2c via clipboard.

So, I want to know that it is intended (there is a case that it is executed) or not and how to reproduce the intended case.

Environment:
* Linux: xrdp-0.9.17-2.el8.x86_64.rpm
* Windows: Windows 10 (Microsoft Windows [Version 10.0.19044.1387])

# Questions

## Is non TARGETS atom checked, when?

According to clipboard_event_selection_notify in clipboard.c,
if TARGETS atom exists, always `if (lxevent->target == g_targets_atom)` block is executed.

https://github.com/neutrinolabs/xrdp/blob/b557de48885337357a709e630a83902bc251e663/sesman/chansrv/clipboard.c#L1951-L1994

Thus, as TARGETS atom always exists on something copied, it seems that the following `else if (lxevent->target == g_xxxx)` block will not be executed.

https://github.com/neutrinolabs/xrdp/blob/b557de48885337357a709e630a83902bc251e663/sesman/chansrv/clipboard.c#L1995-L2081

When the above code block is executed?
I want to know the reproducible steps to be executed.

step1: ...
step2: ...

## Question 2:

When text is copied on s2c via clipboard, TARGETS atom and UTF8_STRING atom exists.

Thus the following code block is not executed.

https://github.com/neutrinolabs/xrdp/blob/b557de48885337357a709e630a83902bc251e663/sesman/chansrv/clipboard.c#L2107-L2114

To reach above code block, TARGETS atom and XA_STRING atom must be exists and UTF8_STRING atom must not exist.
How to reproduce such a situation?

**Comment by matt335672** [comment]
Hi @kenhys 

This is off the top of my head, but to try to answer your questions:-

1) The [XSelectionEvent](https://www.systutorials.com/docs/linux/man/3-XSelectionEvent/) reaches the block at 1995 following a call to `XConvertSelection()` which requests the text:-

https://github.com/neutrinolabs/xrdp/blob/b557de48885337357a709e630a83902bc251e663/sesman/chansrv/clipboard.c#L1146-L1147

2) Some older X clients may not support UTF8_STRING. In Japan I'd think most things you'd come across will support UTF8_STRING. So this may be difficult to reproduce. You can do it with the `xclip` utility:-

```
$ echo "Hello" | xclip -selection CLIPBOARD -noutf8
$ xclip -o -t TARGETS -selection CLIPBOARD
TARGETS
STRING
```

In my experiments with a modern desktop however, the clipboard would still respond to a request for a UTF8_STRING, even if it wasn't advertised.

If you want to find out more about this area, I can recommend installing the `xclip` utility and playing with it. There's some good information in the [Inter-Client Communication Conventions Manual](https://x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html), but this can be hard to understand at first. Playing with `xclip` will help.

**Comment by kenhys** [comment]
@matt335672 

Thanks! It seems that I could reproduce it about a non UTF8 case with the above xclip -noutf8 instruction.

**Comment by kenhys** [comment]
Still not understand well how to cause `XConvertSelection` situation intentionally yet...
Anyway thanks for your hint!

**Comment by kenhys** [comment]
For the record, a bit off topic, but  I've found the wrong debug message in related code, I've created PR like this: https://github.com/neutrinolabs/xrdp/pull/2074

**Comment by matt335672** [comment]
@kenhys 

The `XConvertSelection` is called when the RDP client requests UTF-8 text.

The clipboard code calls `XConvertSelection` and receives `clipboard_event_selection_notify()` from the clipboard owner. That's my understanding of it anyway!

**Comment by kenhys** [comment]
Thanks, I do not fully understand well, but it is helpful!

**Comment by matt335672** [comment]
Just as a footnote, for a full understanding you will need to know the messages from the RDP side of the connection.

These are documented in [[MS-RDPECLIP]](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/fb9b7e0b-6db4-41c2-b83c-f889c1ee7688) and processed by the `clipboard_data_in()` function. 

I hope that's useful, if you decide to dig a bit deeper into the code.
