### ISSUE TITLE
security livel is 0

### ISSUE THREAD

**Issue by GostlingX** [neutrinolabs/xrdp#208]
I have a problem with xrdp. is very strange, because I have two accounts on the server, and one I can always access it, while another almost never. Every time I try to get in, I get these data:

started connecting
connecting to 127.0.0.1:5910
tcp connected
security livel is 0 (1= none, 2 = standard)
error - problem connecting

**Comment by metalefty** [comment]
More information needed. If your issue still reproduces with the v0.9.2, please reopen or open a new isssue. `xrdp-sesman.log` will provide useful information for the issue.
