### ISSUE TITLE
Feature request: Control inbound/outbound text/file/image transfer via clipboard respectivly

### ISSUE THREAD

**Issue by kenhys** [neutrinolabs/xrdp#2081]
# Problem

It seems that https://github.com/neutrinolabs/xrdp/issues/573 is focused on outbound clipboard restriction and it was implemented by https://github.com/neutrinolabs/xrdp/pull/1298.

But it is limited to outbound only. we can not control it text, file, image respectively.
This issue is focused on extending the existing feature more.

# Expected

Adding a feature to control inbound/outbound text/file/image respectively.

I mean that the following configuration is added in /etc/xrdp/sesman.ini.

```
[Security]
; When RestrictInboundClipboard=true clipboard from the
; client is not pushed to the server.
RestrictInboundClipboard=false
; When RestrictInboundClipboardText=true text from the
; client is not pushed to the server via clipboard.
RestrictInboundClipboardText=false
; When RestrictOutboundClipboardText=true text from the
; server is not pushed to the client via clipboard.
; Note that RestrictOutboundClipboard=false
; to enable this feature.
RestrictOutboundClipboardText=false
; When RestrictInboundClipboardFile=true file from the
; client is not pushed to the server via clipboard.
RestrictInboundClipboardFile=false
; When RestrictOutboundClipboardFile=true file from the
; server is not pushed to the client via clipboard.
; Note that RestrictOutboundClipboard=false
; to enable this feature.
RestrictOutboundClipboardFile=false
; When RestrictInboundClipboardFile=true image from the
; client is not pushed to the server via clipboard.
RestrictInboundClipboardImage=false
; When RestrictOutboundClipboardImage=true image from the
; client is not pushed to the server via clipboard.
; Note that RestrictOutboundClipboard=false
; to enable this feature.
RestrictOutboundClipboardImage=false
```

This spec will extend the existing outbound restriction feature.

This feature is for `[Security]` section.
And to keep existing behavior, every new configuration parameter should be disabled by default.

Does it seem to be reasonable? If so, I'll create a PR for it.

## Use case 1

If admin want to disable inbound only via clipboard, then just set it like this:

```
RestrictInboundClipboard=true
```

## Use case 2

If admin want to disable only inbound and outbound file via clipboard, then just set it like this:

```
RestrictInboundClipboardFile=true
RestrictOutboundClipboardFile=true
```

## Use case 2

If admin want to disable only inbound and outbound something via clipboard, then just set it like this:

```
RestrictInboundClipboardText=true
RestrictOutboundClipboardText=true
....
RestrictInboundClipboardXXX=true
```

Above spec will satisfy server admin's needs.

# Actual

We can enable/disable `RestrictOutboundClipboard` only.

```
; When RestrictOutboundClipboard=true clipboard from the
; server is not pushed to the client.
RestrictOutboundClipboard=false
```

We can not disable only text, only image or only file respectively.

**Comment by metalefty** [comment]
The idea is nice and I'm happy to merge that if you work on the feature.

However, the suggested configuration is complicated for me and I don't like it much. What about specifying the target clipboard type in `Restrict(In/Out)BoundClipboard`?

The parameter `RestrictOutboundClipboard` currently accepts a boolean value expressed as `yes`, `true`, `on`.  My idea is to add `file`,`image`,`text` values to specify restricted clipboard types.

```
RestrictOutboundClipboard=file
```

```
RestrictInboundClipboard=text,image
```

If boolean values are set to these parameters, it means all types are restricted/not restricted.

## Examples

Expects comma-separated clipboard types to restrict transfer in the same way of `ssl_protocols`.

```
RestrictOutboundClipboard=file               # => Restricts file
RestrictOutboundClipboard=file,text          # => Restricts file & text
RestrictOutboundClipboard=all                # => Restricts all outbound clipboards
RestrictOutboundClipboard=yes                # => Restricts all outbound clipboards
RestrictOutboundClipboard=file, yes          # => "yes|all" takes priorify than more specific values
RestrictOutboundClipboard=false              # => No restrictions 
RestrictOutboundClipboard=                   # => No restrictions
```

**Comment by kenhys** [comment]
It seems better spec which introducing more simplified syntax.


> RestrictOutboundClipboard=file, yes          # => "yes|all" takes priorify than more specific values

I'm not sure that it is better to support this case too.

**Comment by metalefty** [comment]
@matt335672 Let us hear what you think about this.

1. Configuration syntax and backward compatibility
2. Internal expression for what types of clipboards are restricted

I'm thinking of using bitmask to express clipboard restriction. Then it will be easy to perform unit tests.

```C
restrict_outbound_clipboard = g_text2foobar("text,Image,file") // => returns TEXT| IMAGE | FILE
g_text2foobar("file,IMaGe")      // => returns FILE | IMAGE
g_text2foobar("yes")             // => returns  TEXT| IMAGE | FILE
g_text2foobar("false")           // => returns 0?
```
