### ISSUE TITLE
the ability to execute a command when a user connects / disconnects to an active session

### ISSUE THREAD

**Issue by skochko** [neutrinolabs/xrdp#2090]
Hi!
Can I, by some parameters, find out if there is now a connection to xrdp in the system?
The bottom line is to execute a specific command when connecting and disconnecting a user to an active session.
For a better understanding, I will give an example of code that does what I need.
But it looks like a crutch. I would like a more correct solution.
`while true
do
if [ -e /var/run/xrdp/xrdp_chansrv_audio_in_socket_10 ]
then
wmctrl -k off
else
wmctrl -k on
fi
sleep 1
done
`

**Comment by matt335672** [comment]
@skochko - at the moment this information isn't available directly from xrdp itself. We're currently working on re-implementing a part of the system that will make this easier (in #1961) but this isn't available yet.

You can have a script run in the context of the user by using the `ReconnectScript` setting in `/etc/xrdp/sesman.ini`, but at the moment there isn't a disconnect equivalent.

**Comment by skochko** [comment]
Understood thanks!
