### ISSUE TITLE
dear sir,we need a windows version (as windows home )

### ISSUE THREAD

**Issue by introspection3** [neutrinolabs/xrdp#2100]
RDP

**Comment by matt335672** [comment]
@introspection3 - it's not clear what you're asking for here, or what use-case you're trying to satisfy. Can you be more specific please?

**Comment by introspection3** [comment]
@matt335672 sir,windows home version can't use mstsc,but if
xrdp support running on windows,it will be very good

**Comment by matt335672** [comment]
If you're trying to replace mstsc, this isn't the right product for you. This is an RDP server, so it's emulating what a Windows server would do, not mstsc.

Have a look at MobaXterm which offers an RDP client capability.

**Comment by Nexarian** [comment]
I think what's he saying is that the RDP SERVER is not enabled on Windows 10 Home, it's only enabled by Microsoft on the professional SKU.

So his point is that for non-professional SKUs of Windows, enabling RDP for that would be a win (and perhaps an easy way to increase adoption of the system).

I have heard that long ago XRDP used to work on WIndows, but I'm not sure if it does now. I'm not even sure if we have a way to access the Windows graphics stack to enable such a thing...

But I do agree it would be a cool thing to support.

**Comment by matt335672** [comment]
I agree it would be cool technically but I don't think we have the Windows knowledge to do this in the team. I certainly don't!

There's also the potential user community to consider. The directions for the main project are driven mainly by the interests of the power users and enterprise users. I don't think they would be interested in this functionality at all. Nor will users of this functionality want to use the main product.

So although there's functional overlap between the two use-cases, I don't think there's any market overlap. This looks to me like a separate project with a different target audience and different development skills.

A little web searching led me to [rdpwrap](https://github.com/stascorp/rdpwrap) which seems like a saner way to proceed f you're interested in using Windows Home in this way. To be clear I'm not endorsing this project at all. It's not clear to me whether using it would be a violation of Windows licensing, and that may depend on your juristiction.

**Comment by matt335672** [comment]
Closing this for now.
