### ISSUE TITLE
Transport Endpoint is not connected

### ISSUE THREAD

**Issue by Isaiah-Day** [neutrinolabs/xrdp#2101]
thinclient_drives will not connect! I cannot access anything in my home directory. I am new to linux and bash. Is there a simple way to fix this? Thanks!

![Screenshot_2021-12-31_15_41_00](https://user-images.githubusercontent.com/66925301/147828814-26e5a056-5efc-4296-b1c8-14d7ff34cf37.png)

**Comment by matt335672** [comment]
Hi @Isaiah08-D,

The process which handles remote drives for the client has failed. That produces this error.

A few questions for you, so we can determine if this is a known issue.
1) what system are you running on?
2) what is the output of `xrdp -v`?

The simplest way to recover from this problem in the short-term is:-
1) Get up a terminal window
2) issue the command `fusermount -u ~/thinclient_drives`
3) Log out completely and log in again

**Comment by Isaiah-Day** [comment]
Hey @matt335672,
![image](https://user-images.githubusercontent.com/66925301/147833536-2bc69abd-5093-41a3-927f-aaf7dc0af510.png)
xrdp -v outputs:
```
xrdp 0.9.17
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-gDhwcG/xrdp-0.9.17=. -fstack-protector-strong -Wformat -Werror=format-security
      LDFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2
      PKG_CONFIG_PATH=/build/xrdp-gDhwcG/xrdp-0.9.17/pkgconfig

  Compiled with OpenSSL 1.1.1l  24 Aug 2021
```

does this help?

**Comment by Isaiah-Day** [comment]
The fix returns this:
![Screenshot_2021-12-31_18_12_52](https://user-images.githubusercontent.com/66925301/147833688-7e468ec6-afc7-4e42-8a29-60b7b1d7199b.png)
And doesn't seem to fix anything.

**Comment by Isaiah08-D** [comment]
@matt335672 
Never mind!
I tried the fix again and reinstalled xrdp and everything is fine! Thanks for your help!

**Comment by Isaiah-Day** [comment]
@matt335672
Never mind!
I tried the fix again and reinstalled xrdp and everything is fine! Thanks for your help!

**Comment by ucycg** [comment]
God save the internet where you can solve issues you only have with Linux OS without understanding neither the problem nor the solution.
