### ISSUE TITLE
GPU unavailable for openVINO when headless using XRDP

### ISSUE THREAD

**Issue by KahrenA** [neutrinolabs/xrdp#2102]
have installed XRDP on Up2 board running Ubuntu 16.04 and my acceleration on the GPU works fine when I connect a monitor and run it locally. It also works fine when I run it remotely so long as a monitor is connected. Once the monitor is disconnected I get self.exec_net =

self.ie.load_network(network=self.net,device_name=self.plugin)

File "ie_api.pyx", line 178, in

openvino.inference_engine.ie_api.IECore.load_network

File "ie_api.pyx", line 187, in

openvino.inference_engine.ie_api.IECore.load_network

RuntimeError: Failed to create plugin

/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so

for device GPU

Please, check your environment

[CLDNN ERROR]. clGetPlatformIDs error -1001

couple of further notes: 
1)  I have tried fake display dongle from Amazon https://www.amazon.com/dp/B074NNZYW4?psc=1&ref=ppx_yo2_dt_b_product_details unfortunately did not help

2) Recommendation from Stackoverflow was to post this issue here 
https://stackoverflow.com/questions/70515013/gpu-unavailable-for-openvino-when-intel-atom-e3950-nuc-is-headless/70538718#70538718

**Comment by matt335672** [comment]
The lowest level we get is using the X server modules, which as far as I know don't allow for this kind of hardware access.

We've seen issues on raspberry PIs where the access to the GPU is allowed only after the first console login. It's a bit moot on that platform as the acceleration doesn't work with remote sessions, but a similar thing may be happening here. Try powering off the board, connecting a monitor, powering it on, and then trying the xrdp session without touching the console. If that doesn't work, we may be able to figure out why.

**Comment by matt335672** [comment]
@KahrenA - any feedback on this?

**Comment by KahrenA** [comment]
Hi ,
Yes, OpenVINO folks were able to duplicate it and recommended to move to
Unbuntu 18.04…
Thank you for following up !
Cheers,
Kahren

**Comment by matt335672** [comment]
Thanks for the update. I'll close this then.
