### ISSUE TITLE
Call to find_matching_extended_rect at vnc.c:1211 looks like a bug

### ISSUE THREAD

**Issue by travnick** [neutrinolabs/xrdp#2103]
https://github.com/neutrinolabs/xrdp/blob/0c605a3cc488a5ebe977dabf5d7e932a0d080696/vnc/vnc.c#L1215

the parameter `response_code`
```
    error = find_matching_extended_rect(v,
                                        rect_is_reply_to_us,
                                        NULL,
                                        &response_code,
                                        &layout);
```
is passed as a `match_y` argument to
```
find_matching_extended_rect(struct vnc *v,
                            int (*match)(int x, int y, int cx, int cy),
                            int *match_x,
                            int *match_y,
                            struct vnc_screen_layout *match_layout)
```
by quick review, it looks like a bug. Please verify the call.

The main source of the finding is compilation with `-O3` that results with:
```
  CC       vnc.lo
  CC       vnc_clip.lo
In file included from ../common/parse.h:29,
                 from vnc.h:26,
                 from vnc.c:33:
vnc.c: In function ‘lib_data_in’:
../common/log.h:153:33: error: ‘response_code’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  153 | #define LOG(log_level, args...) log_message(log_level, args)
      |                                 ^~~~~~~~~~~
vnc.c:1211:9: note: ‘response_code’ was declared here
 1211 |     int response_code;
      |         ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by matt335672** [comment]
Thanks for this @travnick 

What platform are you on? This isn't being picked up by our CI builds at the moment.

**Comment by matt335672** [comment]
BTW the code's fine, but the call analysis is incomplete, probably for speed reasons.

**Comment by travnick** [comment]
I'm running Arch Linux x86_64 with gcc 11.1.0-3.

The analysis is somehow correct - the `response_code` passed as `match_y` to `find_matching_extended_rect` remains uninitialized if `error != 0`, but probably the compiler does not see the access to the `response_code` is guarded by `if (error == 0)` in `lib_framebuffer_waiting_for_resize_confirm`

Anyway, it's really strange that the `response_code` is the same as `match_y`, but maybe it's just kind of tricky argument and interface matching in this code.

**Comment by matt335672** [comment]
The guard is more complex than that - `error == 0` can also be returned if no error is encountered and no matching rectangle is encountered, but in that case `match_layout->s` will be NULL (this is spelled out in the function header). So I'm not surprised the compiler doesn't look that deeply. The CI system uses the latest verson of `cppcheck`, and that's happy with the code.

In any case, I think the simplest fix is to initialise `response_code` to zero. I'm just updating a Manjaro VM I've got lying about which should be able to reproduce this, so when that's done I can check I can get a clean build.

**Comment by matt335672** [comment]
Running on Manjaro, just adding an initialiser fixes the warning. I can't find any others using the configure switches used in the PKGBUILD for Arch.
