### ISSUE TITLE
make error on macOS Monterey

### ISSUE THREAD

**Issue by ClaLas** [neutrinolabs/xrdp#2104]
I'm getting this error when i try to compile and i havent found any similiar issue posted here:

`Making all in tools
  CCLD     xrdp-xcon
ld: warning: ignoring file /usr/X11/lib/libX11.dylib, missing required architecture arm64 in file /usr/X11/lib/libX11.dylib (2 slices)
Undefined symbols for architecture arm64:
  "_XConnectionNumber", referenced from:
      _main in xcon.o
  "_XNextEvent", referenced from:
      _main in xcon.o
  "_XOpenDisplay", referenced from:
      _main in xcon.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [xrdp-xcon] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
`

**Comment by matt335672** [comment]
We don't really support MacOS (see [the wiki](neutrinolabs/xrdp/wiki/Platform-Support-Tier)), but this looks to me like you're missing some development files.

A quick [search](https://duckduckgo.com/?q="missing+required+architecture+"+"+in+file+") pulled up a few hits which might be useful to fix this.

**Comment by matt335672** [comment]
@labirinth30 - did you get any further with this?
