### ISSUE TITLE
XRDP not showing reason for failed login

### ISSUE THREAD

**Issue by tfischer77** [neutrinolabs/xrdp#2113]
When I try to login into an xrdp host with a wrong username or expired password, XRDP is not showing the reason for the failed logon. It is just telling "login failed for display 0" in the Connection log.
I know that this was different in the past. Can anyone tell me what is going wrong here?
I'm using version 0.9.17 of xrdp.
LogLevel in xrdp.ini and sesman.ini is "DEBUG"

**Comment by matt335672** [comment]
Hi @tfischer77 

This code is generated by `xrdp_mm_process_login_response()` for v0.9.17:-

https://github.com/neutrinolabs/xrdp/blob/58088324956d94fd2eb5e7694a318cccec6990f1/xrdp/xrdp_mm.c#L1758-L1817

The failing branch of the `if (ok)` test is the same for xrdp v0.9.9. I went back to v0.6.1 and got this:-

https://github.com/neutrinolabs/xrdp/blob/5d5375873ee16975e994ad9fe1dfa2b3fa0c3ac2/xrdp/xrdp_mm.c#L744-L748

The protocol flag sent back from xrdp-sesman for a session login is a simple yes/no value. I'm not aware that this has changed.

Are you thinking of the responses when PAM authentication is used for proxy authentication maybe? Or am I misunderstanding your question?

We've certainly had discussions about improving this area - see #1921. For v0.9.18 (out any day now) we've removed the 'for display 0', as it's confusing. Also the logging in xrdp-sesman.log is improved for this release to improve compatibility with fail2ban.

**Comment by tfischer77** [comment]
Hi @matt335672,
I'm not sure what you mean by "proxy authentication".
Maybe it is more clear if I try to describe what I wanted to achieve: I tried to set the variable `pamerrortxt` inside `xrdp.ini` to a value like "Your password is expired, please set a new one at https://....". During my tests with expired passwords (using local PAM authentication as well as active directory users with sssd) I noticed that the `pamerrortxt` is never shown on the sesman console.
So, my question is: Why isn't `getPAMAdditionalErrorInfo` (declared in `xrdp/xrdp_mm.c` line 2266) called? I see that this function is called within `xrdp_mm_connect(struct xrdp_mm *self)`, see line 2526 of `xrdp/xrdp_mm.c`.
PAM itself seems to run correctly, because when I log on with the same account via openssh, I get the password change dialog. I understand that this dialog is not existing within xrdp (I did some implementation of a password change dialog some years ago,see #600,  but it was never merged, which I also understand, because it was only a work-around for a very special situation ).
Some more information: I'm using Debian 11, but was building my own deb package of xrdp out of the currently released version 0.9.17 and only applied the Debian patches, no additional code changes. From what I can see, these patches don't change anything in the way xrdp is checking against PAM.

**Comment by matt335672** [comment]
Thanks for the explanation.

The PAM functions in xrdp/xrdp_mm.c are only every used for what I called proxy authentication above. For a normal session, these are not used. For a normal session, xrdp just sends everything off to sesman and gets a yes/no answer.

The PAM functions are used by enabling pamusername and pampassword fields in xrdp.ini. XRDP will then use a different call to ask sesman to authenticate before doing something like connecting to a VNC session, or NeutrinoRDP. There should be some examples in xrdp.ini.

Frankly, the whole area is a bit counter-intuitive and shonky. I'm currently trying to fix it (see #1961) but there's a lot to do. It's been reformatted in v0.9.18 so it should at least be easier to follow but there aren't any functional changes yet.

I hope that makes sense, at least a bit.

**Comment by tfischer77** [comment]
OK, understood. Shall I close this issue by now, as it is already addressed in other issues?

**Comment by matt335672** [comment]
I think so. Feel free to re-open it (or another one) if you've got any more questions or suggestions - and thanks for the chat.
