### ISSUE TITLE
Slow Ubuntu Remote Desktop using xrdp

### ISSUE THREAD

**Issue by muhammadzubair220** [neutrinolabs/xrdp#2135]
Hello Everyone.

I have created an virtual machine with the following specifications:

Ubuntu 20.04 LTS
F16s_v2 Standard (16 vCPU and 32 GiB RAM)
SSD unit
Since I need to connect via Remote Desktop, I followed this guide to install xrdp. Once finished, I connected to the server with Microsoft Remote Desktop but I noticed an excessive slowness in interactivity. I don't think the problem is my internet connection because:

By connecting to other Azure Windows VM I don't have the same problem;
I asked to a colleague to do a test from his home and he experienced the same problem;

What could be the problem?

**Comment by matt335672** [comment]
@muhammadzubair220 - have a look at #2136 and try enabling RFX. That may help.

**Comment by marcsosduma** [comment]
have a look at:
https://github.com/neutrinolabs/xrdp/issues/1483
