### ISSUE TITLE
Running Cheese for WebCam causes XRDP to close, but only over VPN

### ISSUE THREAD

**Issue by hullio** [neutrinolabs/xrdp#2171]
So odd issue, when on site I can run the windows RDP client to connect to XRDP running on Ubuntu 18.04 to open Cheese and view a Webcam's input. When myself or others try over VPN, off site, opening Cheese causes XRDP to close with not a lot of info. I am going to change the settings in sesman.ini for logging to DEBUG. Is there anything specific I can look at to help root cause this issue? Thanks.

**Comment by matt335672** [comment]
Interesting problem.

Either the session is ending, or something is going wrong with the xrdp protocol. Can you work out from the logging in `/var/log/xrdp.log` and `/var/log/xrdp-sesman.log` which it is?

**Comment by hullio** [comment]
Thanks, after noting the issue I was able to dig deeper and across multiple systems. It turns out its not an XRDP issue, so you can close this out / ignore. It turns out there is something Cheese is doing to cause XOrg to crash. I am still investigating as I don’t know if its an XOrg problem or an Ubuntu O/S issue. I am noticing some odd behavior in the logs. 

 

What’s odd is this XOrg crash does not happen on local user login via GUI. What makes it more interesting is when the system is rebooted the first user to login over XRDP has no issues. We have had users log out of XRDP, not just click close on the Microsoft RDP client, and the next user who logs in via XRDP (same user or new) Cheese crashes X. So very odd. Seems like something is not closing properly on the first instance.

**Comment by matt335672** [comment]
I'll close this for now. Feel free to comment if you have more information, and we can re-open as necessary.

Also, you can try running xrdp with the Xvnc backend. Hopefully that will be fine, but in any case it may give you more information.
