### ISSUE TITLE
RPi: CPU Load very high

### ISSUE THREAD

**Issue by Becker884** [neutrinolabs/xrdp#2173]
Hello,
since the last update from xrdp my RPi4 gets ~70-85% CPU load if I sign in with xrdp on it.
I set the crypt_level=low, but no effect.
the desktop is lagging, just the login is very hard.

Any ideas except to reinstall the old version?
thanks

**Comment by matt335672** [comment]
What's using the CPU exactly?

You can try using the instructions in [this post](https://github.com/neutrinolabs/xrdp/discussions/2050#discussioncomment-1630986) to move back to openbox if you're using mutter as a window manager. That may help.

**Comment by Becker884** [comment]
yes it is "mutter" - but I can't figure out the instructions "Simple: Install tigervnc-standalone-server and use the Xvnc back end to xrdp."

**Comment by matt335672** [comment]
Sorry - I wasn't clear.

Start reading at "Configure the PI to use openbox for xrdp connections"
