### ISSUE TITLE
Remote Desktop using xRDP for RHEL 8

### ISSUE THREAD

**Issue by mahendra03** [neutrinolabs/xrdp#2181]
Hi Team.

I have installed RHEL 8 in GCP machine and when I am trying to login remote system through xrdp then it asking first

This account will be use to connect to localhost : Here I am giving my company mail id to login and password then it goes inside the xrdp system here if i create new user then i can login but unable to login using existing id and password 

Connecting to sesman on 127.0.0.1:3350
sesman connect Ok
sending login info to session manager
login failed for user xyz

the id with which i login first ideally it should using the same id , but as i said if i create new user and password and then login at second step is sucesfully login to remote desktop of RHEL

Please help me if any idea

**Comment by matt335672** [comment]
Hi @mahendra03 

I do not fully understand what you are asking.

xrdp is simply calling down to the normal user authentication facilities provided by the operating system.

If you are trying to use a user which the operating system doesn't know about, xrdp won't be able to log you in.

To find out if the system knows about a particular user, you can use this command:-

```
getent passwd <username>
```

**Comment by mahendra03** [comment]
Hi @matt335672  - I will try what you are suggesting.
Let me explain you what I am trying to do :

I am mean to say first i open mstsc for my mac and there I provide the password using which I login to macbook then it open new screen where I provide session xvnc and here I am confuse which user name and password to provide if i provide same passowrd and user name with which I login to VM then getting error 

we are using gcp instance.

**Comment by matt335672** [comment]
To do this, I think you will need to add your macbook login credentials to the GCP instance.

Alternatively, you may be able to get mstsc for the Mac to store your login credentials for xrdp so that you don't need to enter them on the xrdp login screen.

I can't comment on the overall security of this approach, as I don't know the rest of your system.You should get someone from your IT department to review the security as well.

**Comment by mahendra03** [comment]
@matt335672 Sure I ll check on this .... update you and thanks for the help
