### ISSUE TITLE
Do I really need hardware acceleration?

### ISSUE THREAD

**Issue by zhukov-andrew** [neutrinolabs/xrdp#2190]
Hello!

I am new to using XRDP. And my question is: do I really need hardware offloading on the graphics card?

At this moment I've tested XRDP from Ubuntu repositories without glamor, own build with --enable-glamor option and experimental build with GFX support. As I can see, there is less CPU load when using glamour, GFX show the best results on the high latency channel.

We plan to use XRDP on servers without Intel GPU and, as far as I understand, we won't be able to use glamour acceleration.
Will installing Nvidia GPU have any effect other than reducing the load on the CPU? Will a hardware GPU be required to work with GFX? As I can see Microsoft RDP works very well on servers without Intel/Nvidia GPU's when using GFX, will XRDP work the same after the release of GFX support?

**Comment by jsorg71** [comment]
No, you will not be required to have hardware.  We will always have a software path.
This just ballooned up as Nexarian and I both really like hardware accel.
It is great that we have a place in the xrdp GFX pipeline for hardware support but we'll always need a software pass and we'll always try to use SIMD to have the best of CPU performance.

**Comment by metalefty** [comment]
I also wondered the same thing. Thanks Jay.
