### ISSUE TITLE
Feature Request:   Colemak Support?

### ISSUE THREAD

**Issue by prg318** [neutrinolabs/xrdp#2192]
Hello,

Xrdp currently supports US QWERTY and US Dvorak, but there aren't any colemak layouts available.  I realize that colemak is not supported by Microsoft Windows natively nor is it included in the standard RDP protocol, but it would be nice to be able to use colemak with xrdp.
This issue is to pose the question: would it be feasible to add a colemak keyboard layout in xrdp that freerdp and other clients could potentially be patched to use?

If this were to be implemented, it looks like something along the lines of the following would be required (with probably something else that I'm missing):

- `xrdp_keyboard.ini`  rdp_us_colemak (and perhaps rdp_us_colemak_dh) given unused IDs and added to `[default_rdp_layouts]`. 
- `dump-keymaps.sh` modified to dump colemak from `setxkbmap`
- whatever clients would need to be patched to allow selection of colemak with the xrdp ids

Is there any interest in implementing something like this in xrdp?  I realize that it is not included in the spec and would not be compatible with microsoft RDP, but it shouldn't break anything.  I'd be interested in getting thoughts and opinions on this

Thanks again for everyone's hard work on xrdp

**Comment by RolKau** [comment]
Does the Colemak driver generate a stable keyboard layout ID (the right-hand side of the `rdp_layout_us_colemak` assignment in `[default_rdp_layouts]`), or is it generated by its installer? I suspect that the RDP protocol only sends the ID, so you must know it upfront to be able to map it to an XKB setting (`us(colemak)`)

**Comment by prg318** [comment]
Colemak is a native X.org XKB layout.  There's not a colemak entry in `[default_rdp_layouts]` at all, but the keymap can be added to the configuration file and the keymap can be dumped from `setxkbmap`.

**Comment by RolKau** [comment]
> Colemak is a native X.org XKB layout

Yes, but that is irrelevant. You need some way of identifying that the _client_ has a Colemak layout in order to propagate that selection to the server-side. (What are you going to put on the right-hand side of the entry in the default_rdp_layouts section?)

**Comment by prg318** [comment]
> > Colemak is a native X.org XKB layout
> 
> Yes, but that is irrelevant. You need some way of identifying that the _client_ has a Colemak layout in order to propagate that selection to the server-side. (What are you going to put on the right-hand side of the entry in the default_rdp_layouts section?)

As I mentioned in the OP, a new ID that is unused by other layouts would need to be used on the client and the server.  AFAIK there is not a "standard" RDP layout ID for colemak, since it's not available in Windows by default.

Perhaps the [windows colemak driver](https://colemak.com/Windows) registers some ID that can be used, but I'm not sure - I have never used the Colemak driver for windows.

**Comment by matt335672** [comment]
Things seem to have changed recently in this area.

As @RolKau correctly points out, there's no documented Colemak entry in [[MS-LCID]](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f). However, this may not be up to date. At the time-of-writing, there is a Colemak layout listed on https://www.kbdlayout.info/. Provided that sends the code 0x060409 from the Windows side, we can do something on the xrdp side.

The Windows build which introduces KBDCMK.DLL appears to be Windows 10.0.26040.1000. I'm pretty sure this will be included in Windows 11 24H2, but I haven't updated my Windows 11 VM to this version yet.

@prg318 - I take it you've got one of these keyboards? Have you got 24H2 as well?

**Comment by RolKau** [comment]
I can confirm that Windows 11 24H2 build 26100.1 contains 00060409 as Colemak.

**Comment by thom-yorkes-brother** [comment]
I have a blank-keycapped QWERTY keyboard that I was previously using the colemak layout with (you can use Colemak on a qwerty keyboard) and I do have a 24H2 installation.  Let me know if there's anything I could help testing - thanks!

**Comment by matt335672** [comment]
I've just managed to get 24H2 installed here, after a fight with driver manager!

I'll see what I can find out and get back to you.

A couple of questions in the meantime:-
1) What version of xrdp are you running?
2) Which backend are you usibf (Xorg/Xvnc).

Thanks.

**Comment by prg318** [comment]
Thanks for taking the time to implement this! I've followed up in the pull request thread. Awesome!
