### ISSUE TITLE
Cannot connect from Windows 11 to Fedora 35 via Xrdp

### ISSUE THREAD

**Issue by phsonnek** [neutrinolabs/xrdp#2196]
I just installed Fedora (upgrade from Ubuntu)  and I cannot get xrdp to allow me to login remotely
Everything installed correctly.  But here is the message I am getting when connect with Windows Remote Desktop
Sending login info to session manager.  Please wait... login failed for user phsonnek

The tail of /var/log/xrdp.log

[20220327-16:17:21] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220327-16:17:21] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20220327-16:17:21] [INFO ] sesman connect ok
[20220327-16:17:21] [INFO ] sending login info to session manager. Please wait...
[20220327-16:17:23] [INFO ] xrdp_wm_log_msg: login failed for user phsonnek
[20220327-16:17:23] [INFO ] login failed for user phsonnek

I am not sure where to even start with this.

**Comment by matt335672** [comment]
It's simply telling you that it can't authenticate 'phsonnek'.
- Have a look in `/var/log/xrdp-sesman.log`, where you might get more information.
- Also, check your keyboard mapping is working correctly for the password by entering your password characters into the username field, to check they are being processed correctly.

Fedora uses SELinux, and you may need to edit `/etc/pam.d/xrdp-sesman` to get the session to transition to the correct SELinux context. There's more information on this buried in #2094

**Comment by Kevin7ten** [comment]
I am having the same issue in Kali with Windows 11 and have read a thread on Reddit of someone else having the same problem. If you check your logs it seems the xorgxrdp package is not being installed and If you try to install it it says the package has a different name basically and so won't install. guessing this is a common update bug that just needs to be fixed or find a workaround.

**Comment by matt335672** [comment]
@Kevin7ten  - What's the install error exactly?

**Comment by Kevin7ten** [comment]
So its just not installing xorg. If you try to use `sudo apt install xorgxrdp` it will try to install it but you get "package xorgxrdp not available, but is referred to by another package. This may mean the package is missing, has been obsoleted, or is only available from another source."

**Comment by matt335672** [comment]
It sounds like the package isn't available in the Kali repositories you have enabled. IIRC, on Kali you need to enable some repositories to get all the Ubuntu packages. Have a look at #1998.

xrdp and xorgxrdp need to be installed together because of the dependencies they have. If you've installed xrdp by another method, installing xorgxrdp from a package probably won't work.

**Comment by Kevin7ten** [comment]
I followed a tutorial video, i did the same setup a few weeks ago on my desktop PC no problems. Followed the exact same instructions on my new laptop and it won't work.

**Comment by matt335672** [comment]
We don't do videos here I'm afraid - they make it hard for other people reading the thread to follow the discussion.

What do you get for these commands:-

```
apt search xrdp
xrdp -v
```
