### ISSUE TITLE
It's blue screen when I use mstc to connect a solus pc installed xrdp.

### ISSUE THREAD

**Issue by iysheng** [neutrinolabs/xrdp#2208]
I install xrdp, xorgxrdp
``` bash
▸ sudo eopkg list-installed | grep "xrdp"
xorgxrdp                                    - Xorg drivers for xrdp
xrdp                                        - xRDP Server
```
Then after I use mstc.exe on win7 to connnect solus. After I input username and password with xorg session.I get the errors, and the blue sceen.
![](https://s3.bmp.ovh/imgs/2022/04/02/00cbb17b968c7d90.png)
 I attach the logs files ``xrdp.log`` and ``xrdp-sesman.log`` under /var/log/
[xrdp.log](https://github.com/neutrinolabs/xrdp/files/8402635/xrdp.log)
[xrdp-sesman.log](https://github.com/neutrinolabs/xrdp/files/8402636/xrdp-sesman.log)

**Comment by matt335672** [comment]
It looks like your X server isn't starting properly.

I've not come across Solus Linux before.

A couple of questions for you:-
- What do you get when you enter the command `Xorg --help` when logged in as user yangyongsheng?
- What's in the file `/home/yangyongsheng/.xorgxrdp.1.log`?

**Comment by iysheng** [comment]
thanks for your reply.
* I input ``Xorg --help`` from putty then i get these printout
```
▸ Xorg --help
/usr/lib64/xorg-server/Xorg.wrap: Only console users are allowed to run the X server
```
* There is no file named `` .xorgxrdp.1.log `` file under the directory ``/home/yangyongsheng/``, these files only:
``` bash
▸ ls -la .x*
.rwx------ yangyongsheng yangyongsheng   9 B  Sat Dec 18 10:57:24 2021  .xinitrc
.rw-r--r-- yangyongsheng yangyongsheng  88 B  Sat Jul 10 00:35:03 2021  .xprofile
.rw-r--r-- yangyongsheng yangyongsheng  20 B  Sat Dec 18 16:18:55 2021  .xsession
.rw------- yangyongsheng yangyongsheng 177 B  Tue Apr  5 08:23:18 2022  .xsession-errors
.rw------- yangyongsheng yangyongsheng  19 KB Sat Apr  2 20:31:49 2022  .xsession-errors.old
```

**Comment by matt335672** [comment]
The problem seems to be that sesman is trying to start `Xorg` as a non-root user, but this isn't allowed.

Edit `/etc/xrdp/sesman.ini`. Look for a line like this:-

```
param=Xorg
```

Change it to this, and restart `xrdp-sesman`:-

```
param=/usr/lib64/xorg-server/Xorg
```

**Comment by iysheng** [comment]
> The problem seems to be that sesman is trying to start `Xorg` as a non-root user, but this isn't allowed.
> 
> Edit `/etc/xrdp/sesman.ini`. Look for a line like this:-
> 
> ```
> param=Xorg
> ```
> 
> Change it to this, and restart `xrdp-sesman`:-
> 
> ```
> param=/usr/lib64/xorg-server/Xorg
> ```

Thanks, after I do what you say, now it's ok. :smile:
