### ISSUE TITLE
Weird behaviour with the Fn key in Ubuntu 22.04

### ISSUE THREAD

**Issue by AndreasNasman** [neutrinolabs/xrdp#2210]
I've noticed some strange behavior with the Fn key when using xrdp in Ubuntu 22.04.

When pressing the Fn key, it's interpreted as a Delete key. This can be viewed in *View Keyboard Layout*; here I'm pressing down the Fn key and the Delete key lights up:
![Screenshot 2022-04-03 190725](https://user-images.githubusercontent.com/17124245/161437084-e29735c4-d2a3-4bb3-818d-04c81ff62a49.png)

This issue isn't that major, but it's quite odd, and it can cause some occasional confusion when clicking the Fn key.

Xrdp version: 0.9.17-2ubuntu2
Ubuntu version: 22.04

Windows specs:
Edition: Windows 10 Pro
Version: 21H2
OS build: 19044.1620
Experience: Windows Feature Experience Pack 120.2212.4170.0

PC specs:
Model: ThinkPad P14s Gen 2a
BIOS version: R1MET45W 1.15

**Comment by matt335672** [comment]
Hi @AndreasNasman 

What do you get for the following command:-

```
sudo grep -E '(keyboard)|(keymap)' /var/log/xrdp.log
```

we'll try to figure out what keyboard your client is sending over.

I take it everything is OK on the Windows 10 side with the keyboard?

**Comment by AndreasNasman** [comment]
Hi!

Here's the output of the `grep`:

```shell
$ sudo grep -E '(keyboard)|(keymap)' /var/log/xrdp.log
[20220404-18:00:29] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x00000409]
[20220404-18:00:29] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [us] options []
[20220404-18:00:29] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20220404-18:00:29] [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
```

With this test, my host (Windows) language and keyboard layout are set to English (US) and everything works fine there, including the Fn key.

Could the last warning have anything to do with the issue I'm having?
```shell
[WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
```

**Comment by matt335672** [comment]
No, that's fine.

Can you explain your unedited post, where you have this line:-

```
[20220404-17:48:40] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x2110110], keyboard_subtype:[0x02], keylayout:[0xA0000409]
```

The '0xA0000409' is not something I can see in the MS keyboard identifier list [here](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values?view=windows-11). It suggests your keyboard is other than completely standard, but I'm afraid I don't know what.

0x00000409 maps to a standard US English keyboard.

**Comment by AndreasNasman** [comment]
I use [EurKey](eurkey.steffen.bruentjen.eu/) by default, forgot to change it before doing the test. 🙂 The edited post is with English (US) as the layout and the Fn key behaves as Delete in Ubuntu still.

**Comment by AndreasNasman** [comment]
Can I somehow log what the Fn key is interpreted as on the Ubuntu side?

**Comment by matt335672** [comment]
You can use the `xev` utility to see what scancode the Fn key is being interpreted as.

As I correct in thinking this key is an extra key to a standard keyboard? I've got a full-size UK keyboard in front of me here, and it has no Fn key. On an Acer laptop I user for testing, there's an Fn key, but it doesn't generate a keypress that xev can see.

What do you want the Fn key to do when it's pressed in Ubuntu?

**Comment by AndreasNasman** [comment]
> You can use the xev utility to see what scancode the Fn key is being interpreted as.

Here are the result from running `xev` and repeatedly pressing the Fn key.

First with `Xrdp`. As you can see, it's interpreted as a Delete keystroke:

![xrdp](https://user-images.githubusercontent.com/17124245/161803216-b754ea19-308a-4100-ac27-da3837fad2e8.png)

Next, running the VM straight with Hyper-V. Not sure how its interpreted, but it's not a Delete key:

![hyper-v](https://user-images.githubusercontent.com/17124245/161804402-6670dcb0-3deb-4da3-869a-3fbcff940011.png)

> As I correct in thinking this key is an extra key to a standard keyboard? I've got a full-size UK keyboard in front of me here, and it has no Fn key. On an Acer laptop I user for testing, there's an Fn key, but it doesn't generate a keypress that xev can see.

It's the Fn key of a ThinkPad P14s Gen 2a laptop, with a Nordic keyboard layout:

![PXL_20220405_164143220](https://user-images.githubusercontent.com/17124245/161804235-c34169dd-ed39-4595-866a-d0b27143b8ad.jpg)

> What do you want the Fn key to do when it's pressed in Ubuntu?

Nothing, really; I want similar behavior as connecting to the VM with Hyper-V (see picture above).

Here's an example where the Fn key behaving as Delete is an issue. At work, I have a keyboard that's missing the Home key. To simulate it, I press `Fn + ⬅️`. Say I want to copy some text from Ubuntu to Windows. I highlight the word, copy it, and navigate to Windows with the keyboard. To do that, I would press `Ctrl + Alt + Home`, although I have no Home key, so the shortcut is then `Ctrl + Alt + Fn + ⬅️`. I forgot to un-highlight the text, and the Delete key event from the Fn key deletes the text in Ubuntu as I'm moved over to Windows.

It's not a major issue by any means, just an annoyance that I don't understand why it's happening.

`Xrdp` otherwise seems like a more appealing environment, enabling Enhanced mode in Hyper-V. The only issues so far I've found are this one and #2092.

**Comment by matt335672** [comment]
Can you use `xev` to see what the `keycode` is for delete?

At a technical level, there's a lot of indirection going on here. The RDP protocol uses [virtual scan codes](https://github.com/awakecoding/FreeRDP-Manuals/blob/master/Developer/FreeRDP-Developer-Manual.markdown#concepts) to represent keys. These are converted in xrdp to X11 keycodes in [xrdp/lang.c](https://github.com/neutrinolabs/xrdp/blob/cd1af4772cb6223c1348b0c6af953e45a533c2d1/xrdp/lang.c#L70) using a hard-coded table. The X server, whichever one we're using then maps those keycodes to an actual input data stream.

Esentially, if you're getting a different keycode for the `delete` key and the `Fn` key we can do something at the xrdp level. If they are the same, you'll need to figure out a way to change the virtual scan code which is getting passed over the link.

**Comment by AndreasNasman** [comment]
I see! Thanks for the explanation!

The Delete key seems to give the exact output as pressing the Fn key. Here I spam the Delete key:

![delete](https://user-images.githubusercontent.com/17124245/161959040-a57e1899-1b49-4e07-8409-2ae0245c2c6c.png)

> If they are the same, you'll need to figure out a way to change the virtual scan code which is getting passed over the link.

I guess this is the next step then? 🙂

**Comment by matt335672** [comment]
Indeed.

That'll be down to something in the Windows settings, or possibly the BIOS. By the time the code gets to us, there's not a lot we can do I'm afraid.

**Comment by AndreasNasman** [comment]
Yeah. I mean it works in Windows and when I launch the VM in Hyper-V so not really sure where to change things when the Fn key works otherwise. The issue is quite minor anyway, so I think I'll just drop it.

Thanks for the help and explanations! ❤️

**Comment by dpzimmer** [comment]
> Indeed.
> 
> That'll be down to something in the Windows settings, or possibly the BIOS. By the time the code gets to us, there's not a lot we can do I'm afraid.

How is that possible that windows RDP client sends a delete keypress when the 'Fn' key is pressed when connected to an XRDP server, but not when connected to a native Windows server?  Is is possible that the keypress is fundamentally misinterpreted at the server end? The whole thing is clear as mud to me, because I would expect that the 'Fn' key would be interpreted only on the client hardware/OS and not forwarded as a keypress at all.

Contrary to the OP opinion, processing an unwanted 'delete' keypress IS a big deal.  'Fn' keys are found on most laptops without full size keyboards.

**Comment by matt335672** [comment]
@dpzimmer - you make some good points. Thanks for that.

Are you also experiencing this issue? If so, what kind of keyboard do you have and what is the layout? I'll need to try to reproduce this using a soft keyboard I think.

**Comment by dpzimmer** [comment]
> @dpzimmer - you make some good points. Thanks for that.
> 
> Are you also experiencing this issue? If so, what kind of keyboard do you have and what is the layout? I'll need to try to reproduce this using a soft keyboard I think.

Hi Matt,

Yes, I am experiencing literally the exact same behavior as Andreas.

My system is "Lenovo ThinkPad T14 Gen 3" running "Windows 11 Pro 22H2".  The keyboard layout is attached.

I am connecting to "Ubuntu 23.04" as well as other slightly less recent Ubuntu versions, all experiencing the same issue.

Thanks,
Don.
![thinkpad keyboard](https://github.com/neutrinolabs/xrdp/assets/8901145/234ed716-65ee-41ac-8a1d-3358251140a8)

**Comment by matt335672** [comment]
@dpzimmer, @AndreasNasman 

I've connected my laptop with an Fn key up to and xrdp server. I can see keyboard events for key presses in the `xrdp_fastpath_process_input_event()` function. When I press the Fn key however, no message at all is being received from the Windows side.

This stackoverflow article suggests there is no scancode for the Fn key:-
https://stackoverflow.com/questions/24423724/what-is-the-key-scan-code-of-the-fn-key-for-use-in-autohotkey-ahk

I've also tried running these utilities:-
- [Passmark Keyboard Test Utility](https://www.passmark.com/products/keytest/). This shows the Fn key as being untestable.
- [sharpkeys](https://github.com/randyrants/sharpkeys) does not react at all when the Fn key is pressed.

I don't understand why your laptops are behaving differently. This may be Lenovo-specific functionality. I've done some looking around without huge amounts of success. Ther's this webpage for example, which suggests there may be a BIOS setting to change the operation of this key:-

https://gadgetsfeed.com/how-to-disable-fn-key-on-lenovo-laptop/

I also found some refernces to an `FnLock` key which certainly @dpzimmer does not have. Try pressing Fn+ ESC and see if the operation of the Fn key changes.

By all means investigate further using the utilities and links above. I don't have the hardware to take this any further, but it's certainly an interesting topic.

**Comment by matt335672** [comment]
I've had a bit more of a think about this; the behaviour you're both seeing must be caused by the xrdp server receiving a scancode when the Fn key is pressed.

It would be very useful indeed if either of you is able to install one of the utilities above on your systems and see if you can get a scancode from the Fn key. If there is one, and if it's being sent over the RDP link I can trace it through the keyboard logic on the server side.

**Comment by dpzimmer** [comment]
Hi Matt,

Regarding "Try pressing Fn+ ESC and see if the operation of the Fn key changes.", It toggles the FnLock state, but no change in behaviour when pressing the Fn key alone.

Following up with the tools you suggested, and one more online tool (images below), it seems that a keycode of 0xFF (not a valid code) is forwarded, which would match against anything if your are using bitwise AND at the receiving end.

![Fn_keyboardtest](https://github.com/neutrinolabs/xrdp/assets/8901145/adea462e-81f5-4e73-b51f-97e1a317366e)

![Fn_SharpKeys](https://github.com/neutrinolabs/xrdp/assets/8901145/3db45a76-7b67-4571-bc41-b5274bd20046)

![Fn_Web](https://github.com/neutrinolabs/xrdp/assets/8901145/f5126e08-1134-4a6f-ba88-30824592560b)

**Comment by matt335672** [comment]
Thanks for the swift reply @dpzimmer

The scancode used by RDP is I believe the "BIOS Key Code". So in this case it would be 99 (0x63). Also the E0 is I believe significant and is also visible in the [Keyboard Scan Code Specification](https://download.microsoft.com/download/1/6/1/161ba512-40e2-4cc9-843a-923143f3456c/scancode.doc). I don't know how this gets communicated over the RDP link.

I'll need to read and experiment further, but I think we've discovered why xrdp behaves differently from a Windows Server.

**Comment by christopherreay** [comment]
So I have an issue which I think is likely related to this (and I have this issue too)... which is causing me quite a headache.
I use i3wn, and I press "Win-Shift-Right" quite often. and Ive testing with xev, and literally nothing at all gets to xev.

I actually cannot use i3wm reasonably without being able to move windows to the right... oh I just realised I can remap that key... which I will do...

Still, with all love and humility, all this stuff worked literally perfectly 20 years ago, and it would be nice to feel like we all have control over our keyboards and VMs :)

tyty

--- before I remembered the actual issue I have :)

Would be great to sort this out. Though I do admit, I totally forgot there was an actual home and end key on my keyboard, still they are very far away, and I code a lot. Would be great to work this out.

One other thing which may have a bearing, is that I have the FN and CTRL key swapped on my lenovo (ill boot it up without that and see if it makes a difference). But looking at these posts I would guess not

**Comment by matt335672** [comment]
This should all be largely addressed in the development version of xrdp, where we've moved to evdev keycodes by default. If it's not addressed, it should be a lot easier to sort out.

**Comment by richlv** [comment]
Heya, which version should have those changes?
Observing the same problem with xrdp-0.9.23.1 on OpenSUSE Tumbleweed.

**Comment by matt335672** [comment]
The development version has these changes. That's not 0.9.x or 0.10.x.

It' s not released yet, so you'll need to build from source to try it.

**Comment by richlv** [comment]
Got it, thank you so much for the clarification. Will wait for it to trickle into Tumbleweed then :)
