### ISSUE TITLE
XRDP failing after login

### ISSUE THREAD

**Issue by 2l8baby** [neutrinolabs/xrdp#2212]
Just installed XRDP on new Debian 11 build with XFCE.  Access has been through MacOS RDP client but have also had no success with Win10 RDP client.
Oddly, enough, I had this working on another Debian 11/XFCE machine a week ago without issue.

Also, checked version - 0.9.12 downloaded from Debian repository.  I did see a version 0.9.19 on the Debian site?

Below is the status log - first is status after restarting, second is after attempting RDP connection.  Any assistance, greatly appreciated!

● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-04-05 14:51:10 EDT; 3s ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 5142 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 5150 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 5151 (xrdp)
      Tasks: 1 (limit: 9366)
     Memory: 764.0K
        CPU: 20ms
     CGroup: /system.slice/xrdp.service
             └─5151 /usr/sbin/xrdp

Apr 05 14:51:09 nuc3 xrdp[5150]: (5150)(140143160198976)[INFO ] address [0.0.0.0] port [3389] mode 1
Apr 05 14:51:09 nuc3 xrdp[5150]: (5150)(140143160198976)[INFO ] listening to port 3389 on 0.0.0.0
Apr 05 14:51:09 nuc3 xrdp[5150]: (5150)(140143160198976)[INFO ] xrdp_listen_pp done
Apr 05 14:51:09 nuc3 xrdp[5150]: (5150)(140143160198976)[DEBUG] Closed socket 7 (AF_INET6 :: port 3389)
Apr 05 14:51:09 nuc3 systemd[1]: xrdp.service: Can't open PID file /run/xrdp/xrdp.pid (yet?) after start: Operation not permitted
Apr 05 14:51:10 nuc3 systemd[1]: Started xrdp daemon.
Apr 05 14:51:11 nuc3 xrdp[5151]: (5151)(140143160198976)[INFO ] starting xrdp with pid 5151
Apr 05 14:51:11 nuc3 xrdp[5151]: (5151)(140143160198976)[INFO ] address [0.0.0.0] port [3389] mode 1
Apr 05 14:51:11 nuc3 xrdp[5151]: (5151)(140143160198976)[INFO ] listening to port 3389 on 0.0.0.0
Apr 05 14:51:11 nuc3 xrdp[5151]: (5151)(140143160198976)[INFO ] xrdp_listen_pp done

Log after attempting MacOS RDP connection -
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-04-05 14:51:10 EDT; 5min ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 5142 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 5150 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 5151 (xrdp)
      Tasks: 1 (limit: 9366)
     Memory: 764.0K
        CPU: 132ms
     CGroup: /system.slice/xrdp.service
             └─5151 /usr/sbin/xrdp

Apr 05 14:56:37 nuc3 xrdp[5160]: (5160)(140143160198976)[INFO ] xrdp_wm_log_msg: login successful for display 10
Apr 05 14:56:37 nuc3 xrdp[5160]: (5160)(140143160198976)[DEBUG] xrdp_wm_log_msg: started connecting
Apr 05 14:56:37 nuc3 xrdp[5160]: (5160)(140143160198976)[INFO ] lib_mod_log_peer: xrdp_pid=5160 connected to X11rdp_pid=5163 X11rdp_uid=1000 X11rdp_gid=1000 client>
Apr 05 14:56:37 nuc3 xrdp[5160]: (5160)(140143160198976)[DEBUG] xrdp_wm_log_msg: connected ok
Apr 05 14:56:37 nuc3 xrdp[5160]: (5160)(140143160198976)[DEBUG] xrdp_mm_connect_chansrv: chansrv connect successful
Apr 05 14:56:37 nuc3 xrdp[5160]: (5160)(140143160198976)[DEBUG] Closed socket 18 (AF_INET6 ::1 port 36382)
Apr 05 14:56:37 nuc3 xrdp[5160]: (5160)(140143160198976)[DEBUG] Closed socket 20 (AF_UNIX)
Apr 05 14:56:37 nuc3 xrdp[5160]: (5160)(140143160198976)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:10.1.10.11 port 3389)
Apr 05 14:56:37 nuc3 xrdp[5160]: (5160)(140143160198976)[DEBUG] xrdp_mm_module_cleanup
Apr 05 14:56:37 nuc3 xrdp[5160]: (5160)(140143160198976)[DEBUG] Closed socket 19 (AF_UNIX)

**Comment by 2l8baby** [comment]
Found a solution, if anyone is struggling with this - [https://github.com/neutrinolabs/xrdp/issues/764#issue-231866390](url)

/etc/X11/Xwrapper.config

and exchange the line:

allowed_users=console
by

allowed_users=anybody

then reboot.

**Comment by matt335672** [comment]
In your `/etc/xrdp/sesman.ini` you will have a line to start the X server. For Debian 11 this should be set to `param=/usr/lib/xorg/Xorg` so you run the non-wrapped X server. If it's set to `param=Xorg` you will have exactly the problem you describe.

It's probably not such a big issue for Debain, as the X server is not a privileged executable. for other platforms however, it still is.
