### ISSUE TITLE
AltGr not working in Spanish

### ISSUE THREAD

**Issue by dr-kristau** [neutrinolabs/xrdp#2217]
I'm using xrdp 0.9.19 on Fedora 35 (Wayland).

The logs tell me xrdp is using the correct ini file:

```
Apr 06 18:09:53 xrdp[6464]: [INFO ] xrdp_wm_log_msg: sesman connect ok
Apr 06 18:09:53 xrdp[6464]: [INFO ] Loading keymap file /etc/xrdp/km-0000040a.ini
Apr 06 18:09:53 xrdp[6464]: [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
Apr 06 18:09:53 xrdp[6464]: [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 7864320 MB cache entries 2000
Apr 06 18:09:53 xrdp[6464]: [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
Apr 06 18:09:53 xrdp[6464]: [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [es] options []
Apr 06 18:09:53 xrdp[6464]: [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x0000040A]
Apr 06 18:09:52 xrdp[6464]: [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Apr 06 18:09:52 xrdp[6464]: [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
```
And Spanish-specific keys like 'ñ' work fine. But when I want to type '@', for which I need the AltGr key, nothing is written.

**Comment by matt335672** [comment]
Hi @Dr-Kristau 

Keyboards aren't my strong point I'm afraid, but I'll see if we can help you with this.

- What does `setxkbmap -query -v`  say in your xrdp session?
- Which backend are you using? Xorg or Xvnc?
- If you install the `xev` utility and run it you can get information about the keypresses that X11 is seeing. What do you get for your AltGr key? For reference, I get this on my UK keyboard:-
   ```
   KeyPress event, serial 37, synthetic NO, window 0x3000001,
       root 0x3b5, subw 0x3000002, time 6559774, (45,42), root:(662,269),
       state 0x0, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
       XKeysymToKeycode returns keycode: 92
       XLookupString gives 0 bytes: 
       XmbLookupString gives 0 bytes: 
       XFilterEvent returns: False
   ```

**Comment by dr-kristau** [comment]
Thank you @matt335672, that's appreciated.

1) es+gb possibly because the OS's Language is set to English (UK), but the keyboard I use is Spanish.
```
$ setxkbmap -query -v
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+es+gb:2+inet(evdev)
geometry:   pc(pc105)
rules:      evdev
model:      pc105
layout:     es,gb
variant:    ,
```
2) I'm using Xvnc:
![Screenshot from 2022-04-07 13-03-59](https://user-images.githubusercontent.com/32355001/162186151-8aad425a-aedc-4f1e-a436-99dfc3d3584b.png)

3) I get:
```
KeyPress event, serial 37, synthetic NO, window 0x1a00001,
    root 0x3b4, subw 0x0, time 7162190, (659,579), root:(724,709),
    state 0x10, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
Thanks again.

**Comment by matt335672** [comment]
Interesting, on my keyboard I have an `Alt` key and an `Alt GR` key.

The `Alt` key gives me :-

```
keycode 64 (keysym 0xffe9, Alt_L)
```

And the ALT_GR key gives me:-

```
keycode 92 (keysym 0xfe03, ISO_Level3_Shift)
```

I suspect both of your keys are sending the same keysym.

It's possible the RDP client isn't sending over the 'extended' flag for the key, but that's not easy to determine from xrdp logging.

- Do the AltGr keys work OK on the Windows desktop?
- Have you got another Windows machine you can try connecting to over RDP, so we can rule the client side out?

**Comment by dr-kristau** [comment]
> I suspect both of your keys are sending the same keysym.

Curiously enough, the Alt key in the xrdp session gives me:
```
KeyPress event, serial 37, synthetic NO, window 0x1e00001,
    root 0x3b4, subw 0x0, time 17859040, (463,230), root:(528,360),
    state 0x10, keycode 116 (keysym 0xff54, Down), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
> Do the AltGr keys work OK on the Windows desktop?

My local machine is running Remmina on a Fedora 35 Desktop, and `xev` reports the same key mappings as yours for Alt and AltGr (that is, the correct ones).

> Have you got another Windows machine you can try connecting to over RDP, so we can rule the client side out?

The remote Fedora 35 machine with `xrdp` installed on it is a VM running under Hyper-V on a Win11 machine—I can use Windows's 'Remote Desktop Connection' on this Win11 machine to connect to it, but I get the same results (Alt=116, AltGr=64).

In Remmina, I had to set Preferences->RDP->Keyboard Layout to `0000040A` to get this far, and the client RDP connection has Keyboard Mapping->Map Meta Keys set.

One possibly relevant detail is that I can connect with VNC (I haven't tried RDP) to the remote Fedora machine using GNOME Remote Desktop—this means using the Hyper-V client to log into the account, and then using Remmina again to connect using its VNC Plugin. Running `xev` again on the remote machine gives me the correct mappings.

**Comment by matt335672** [comment]
@Dr-Kristau - I'm going to have to leave this for now I'm afraid. I'm going to be really short of time for a few days due to personal  commitments.

**Comment by matt335672** [comment]
@Dr-Kristau - a couple of thoughts for you:-

1) Does the keyboard work with `xorgxrdp` and the `Xorg` back end?
2) If it does, it might be worth trying to regenerate the `/etc/xrdp/km-0000040a.ini` file using your Xvnc server. This file is somewhat dependent on the X server.

I'll get back to you when I can - sorry about the gap.

**Comment by dr-kristau** [comment]
Hello @matt335672 

> If it does, it might be worth trying to regenerate the /etc/xrdp/km-0000040a.ini file using your Xvnc server. This file is somewhat dependent on the X server.

That was it. I had tried to run `xrdp-genkeymap` before, but only while I was connected to the machine via an xrdp session, when the command had failed. Connecting to the machine directly from Hyper-V and running the command from there successfully regenerated the ini file and I've now got my AltGr key back again.

Thank you for your time and your help.

**Comment by matt335672** [comment]
Thanks @Dr-Kristau 

For the record, I think this is what you did. Is this correct?
1) You log in to the machine on the Hyper-V console and run the command?
2) VNC now appears to be working?

I'm asking as my understanding of this area of the software is still quite poor, and I'd like to improve it!

Thanks.

**Comment by dr-kristau** [comment]
Yes @matt335672, you're right—I can now connect via RDP to my VM running xrdp using a Spanish keyboard, and the AltGr key is mapped correctly. The solution was to regenerate the `km-0000040a.ini` file using `xrdp-genkeymap` while directly connected to the machine (in my case via Hyper-V) rather than trying to do so while connected to it via an RDP session.
