### ISSUE TITLE
xrdp doesn't initiase user login correctly on *BSD.

### ISSUE THREAD

**Issue by Parakleta** [neutrinolabs/xrdp#2225]
`xrdp-sesman` should call out to the `setusercontext` method to do the proper setup from the login class capabilities database.  This probably should happen in `env_set_user`.

You can see roughly what the behaviour could look like by examining the session handling code in https://github.com/freedesktop/xdm

**Comment by matt335672** [comment]
OK - thanks.

The link is useful too. For my own reference (or whoever implements this), the symbol `HAVE_SETUSERCONTEXT` is set in https://github.com/freedesktop/xdm/blob/master/configure.ac, and referred to primarily in https://github.com/freedesktop/xdm/blob/master/xdm/session.c
