### ISSUE TITLE
XRDP uses llvmpipe instead of nvidia graphics

### ISSUE THREAD

**Issue by Leozyc-waseda** [neutrinolabs/xrdp#2236]
My local computer ubuntu, the interface shows that it is using nvidia GPU, but when I use my windows computer to remotely connect to the ubuntu computer through Xrdp, I find that it is using the integrated graphics card.
Any suggestions please?

from xrdp windows
![image](https://user-images.githubusercontent.com/52599722/164360001-c08bcc0a-badc-4965-a497-1485051b628b.png)

my nvidia-driver
![image](https://user-images.githubusercontent.com/52599722/164360056-a6fe882c-9752-4fd1-a519-8f08507c9715.png)

**Comment by matt335672** [comment]
I think that's expected behaviour.

NVidia hardware acceleration isn't yet supported in the release builds, but it's being worked on. See #1697 for more information. There's no date yet where this will be merged into a release

**Comment by Leozyc-waseda** [comment]
Thanks for your reply, I read the issues you gave.
It looks like this problem existed two years ago and there is no solution yet. . LoL

**Comment by halqadasi** [comment]
What I did:

    Go to 'additional drivers' in 'softwares and updates'

    Select 'nouveau' and apply changes

    Then changed to 'nvidia driver-450(proprietary)' and apply changes

    Reboot and it worked.

I don't know if you fixed the problem but it worked with me!
