### ISSUE TITLE
Session allocation policy - Connection setting not useful?

### ISSUE THREAD

**Issue by matt335672** [neutrinolabs/xrdp#2239]
sesman.ini contains the following section for the session allocation policy:-

```ini

;; Policy - session allocation policy
; Type: enum [ "Default" | "UBD" | "UBI" | "UBC" | "UBDI" | "UBDC" ]
; "Default" session per <User,BitPerPixel>
; "UBD" session per <User,BitPerPixel,DisplaySize>
; "UBI" session per <User,BitPerPixel,IPAddr>
; "UBC" session per <User,BitPerPixel,Connection>
; "UBDI" session per <User,BitPerPixel,DisplaySize,IPAddr>
; "UBDC" session per <User,BitPerPixel,DisplaySize,Connection>
Policy=Default
```

The above is the latest, but little has changed since xrdp v0.9.1 when this section was introduced as part of commit 1934c9ea00cb4cb35a2561273c8df8339c8023a1

The problem I've got is the 'connection' setting. A 'connection' in this context is a string created by [common/os_calls.c:g_write_ip_address()](/neutrinolabs/xrdp/blob/93c55e58a884270850794c29bd0f4e2df22e22d6/common/os_calls.c#L1178-L1209). The string is of the form:-

```
<ip_addr>:<port> - socket: <sck>
```

where `<ip_addr>` and `<port>` are from the peer connected to xrdp, and `sck` is the socket number allocated to the connection by xrdp.

If 'C'  is in the session allocation policy, the connection string for an existing session has to match the connection string for a reconnection for a reconnect to succeed (code is [here](/neutrinolabs/xrdp/blob/93c55e58a884270850794c29bd0f4e2df22e22d6/sesman/session.c#L144-L145)). I can't see how this can succeed reliably. Both `<port>` and `<sck>` are very likely to be different on a reconnect.

So as far as I can tell, the 'Connection' argument to the `Policy` setting is effectively useless. Consequently, I'd like to remove this option for the next major release as it seems to have no use cases, and so no-one can be using it. It can usefully be replaced with the client name - see #2099

Am I misunderstanding something here?

@fpaquet - am I correct in thinking you had something to do with 1934c9ea00cb4cb35a2561273c8df8339c8023a1? If so, I'd appreciate you telling me what I'm misunderstanding, or what your actual intentions were for this setting.

Thanks for any enlightenment.

**Comment by fpaquet** [comment]
Thank you for the question.

The meaning of <Connection> was basically to open a new session for each user connection.
Meant to also have a policy option, ensuring never to connect to an existing session (always start a new session).

If you are not lucky with this, you can use <IPAddr>.
Converting IP address into names would have given additional overhead, and may be forged externally in name service.

**Comment by matt335672** [comment]
Thank you for your answer.

What would you then do with the existing session(s) in that model? It seems you could never connect to them at all. Is that right?

**Comment by fpaquet** [comment]
Correct, they're kind of lost but still can run some app's or commands.

You might want to set the KillDisconnected, DisconnectedTimeLimit or IdleTimeLimit in sesman.ini
to get it cleaned up.

**Comment by matt335672** [comment]
OK - thanks for the explanation.

It seems like an odd kind of use-case to me, but I'm sure a lot of things I do seem odd to other people!

It's very easy to support. In fact, it doesn't even need to be combined with the other options, as if it's in any combination. `session_get_bydata()` will always fail.

My main reason for asking this question, incidentally, is to tidy up the sesman code in this area. I'd also like to make it easier for other contributors to provide PRs like #2099 which cater for other use-cases the team haven't thought of.

How does this look to you as a modified interface for the next major version?

```ini
; Policy - session allocation policy
;
;  Type: enum [ "Default" | "Separate" | Combination from {UBDIN} ]
;  "Default"    Same as UB
;  "Separate"   All sessions are separate. Sessions can never be rejoined,
;               and will need to be cleaned up manually, or automatically
;               by setting other sesman options.
;
;   Combination options:-
;      U        Sessions are separated per user
;      B        Sessions are separated by bits-per-pixel
;      D        Sessions are separated by initial display size
;      I        Sessions are separated by IP address
;      N        Sessions are separated by client name sent by the client
;
;   The options U and B are always active, and cannot be de-selected.
Policy=Default
```

**Comment by fpaquet** [comment]
People using 'C' will have to reconfigure Xrdp.
All others can continue without configuration change.

Hard to say how many are using option 'C'.

Needs at least a release note, pointing to the configuration change.

**Comment by matt335672** [comment]
Yes - agreed.

We've got other config changes in the next major version, including a move to Unix Domain Sockets. The old config files will work, but will generate warnings. I can add a warning that 'C' is replaced with 'Separate'. Would that help do you think?

In all the time I've been triaging faults, few people have been changing this option from the default, and no-one has mentioned the 'C' option at all.

**Comment by fpaquet** [comment]
Because it's a background service, it would be very helpful to have a logged warning. Warning will also help you, to reduce the number of support issues.

**Comment by matt335672** [comment]
I'll add a warning.
