### ISSUE TITLE
password input pop-up window is not working in some cases.

### ISSUE THREAD

**Issue by HubKing** [neutrinolabs/xrdp#2270]
By that I mean something like this screenshot: https://devanswers.co/wp-content/uploads/2021/01/authentication-is-required-to-create-a-color-managed-device.png

I have tested multiple distributions and multiple desktop environments with XRDP and all of them had issues with that sort of dialogue. In some cases, the dialogue does not appear at all (thus the app fails), and in some cases, it appears for some apps, but not for other apps. For example, for Ubuntu 22.04, that dialogue shows up for the colour profile creation, but not for other things like Settings -> Users -> Unlock. Pressing that button should show that password dialogue, but in an XRDP session, it shows nothing.

1. Is this a bug of XRDP?
2. If not, is this an inherent limitation of Linux that cannot be fixed by XRDP developers?
3. If not, is this misconfiguration of Linux or XRDP? If so, could you add a Wiki page to explain the correct set-up?
4. If not, in what distribution + desktop environment does the password window always work just like a local session?

**Comment by metalefty** [comment]
Editied title 'cause it's not sudo.
