### ISSUE TITLE
RDP not connecting - Authentication error

### ISSUE THREAD

**Issue by mattbarich** [neutrinolabs/xrdp#2279]
Hi there,

Hopefully, this is the correct place to ask this(this is my first post) but I am trying to set up xrdp to remote into my new Linux machine and I cannot seem to figure out what is wrong with the xrdp configuration. Where it seems to fail is sending the login information to the session manager. I have looked for a solution in other places but nothing has seemed to fix this. I have attached some images of xrdp.log, xrdp-sesman.log and the message that is printed out to the user. 

Hopefully, I just missed something simple, thanks in advance. 

![Windows_login](https://user-images.githubusercontent.com/56982219/169878091-ba8a659f-8cf8-4aa8-8f86-c40a2bb763d1.png)
![xrdp_log](https://user-images.githubusercontent.com/56982219/169878094-eb619c7f-44f3-49a2-a17e-203e87bdf1d5.png)
![xrdp_sesman_log](https://user-images.githubusercontent.com/56982219/169878096-bfdeab53-112c-4e01-9c5e-74fd83e041d8.png)

**Comment by matt335672** [comment]
Hi @mattbarich 

The system can't authenticate the user `chip` using the given password.

A couple of questions for you:-
1) Linux Distro/version?
2) Which RDP client are you using?
3) Can you log on using `ssh` or on the console using `chip` and the password?

One other thing - xrdp has detected a US keyboard. If this isn't correct and you've got a different keyboard, the password characters received by xrdp may not be the ones you think you've sent. You can check the characters you're expecting have been sent by trying them in the username field, and checking they're echoed correctly.

**Comment by mattbarich** [comment]
@matt335672 Thanks for getting back to me, to answer your questions:

   1. The Linux distro I am using is Clear Linux version 5.17.1145.native 
   2. I am using Windows RDP client
   3. I can log in via ssh and in the console with the user chip and the password.

As far as the keyboard, when I type the user password into the username field it is echoed correctly. I thought that it might be a firewall issue but I have the appropriate rules in place, I know this because I have the same rules on another Linux machine and am able to remote into that machine just fine.

Thanks again for your help, I really appreciate it!

- Matt

**Comment by matt335672** [comment]
Thanks.

I'm not familiar with Clear Linux.

- Did you install xrdp from a repository, or compile it yourself?
- Output of `xrdp -v` ?

Thanks.

**Comment by mattbarich** [comment]
@matt335672 I installed xrdp from a repository using the OS package manager, I am using xrpd 0.19.9. 
I appriciate you helping me with this, I tried to contact the Clear Linux team and they haven't gotten back to me.

**Comment by matt335672** [comment]
A couple of questions for you:-
- What is the output of `xrdp -v` on the command line?
- When you say the 'OS package manager', did you install xrdp using `swupd`?
- What do you get for `cat /etc/pam.d/xrdp-sesman`?
- What do you get for `ls -l /etc/pam.d`?

**Comment by mattbarich** [comment]
@matt335672 
Here is the output of `xrdp -v`.
`xrdp 0.9.19
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-generic-linux-gnu
      --host=x86_64-generic-linux-gnu
      --target=x86_64-clr-linux-gnu
      --program-prefix=
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/bin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --sharedstatedir=/usr/com
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-pixman
      --enable-jpeg
      --enable-fuse
      --enable-pam
      --enable-vsock
      build_alias=x86_64-generic-linux-gnu
      host_alias=x86_64-generic-linux-gnu
      target_alias=x86_64-clr-linux-gnu
      CC=gcc
      CFLAGS=-O2 -g -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=64 -Wformat -Wformat-security -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -ftree-vectorize -ftree-slp-vectorize -Wl,--enable-new-dtags -fcf-protection=return -Wl,--build-id=sha1 -m64 -march=westmere -mtune=skylake-avx512 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -fno-lto -fstack-protector-strong -fzero-call-used-regs=used  -fPIC
      LDFLAGS= -Wl,--build-id=sha1
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig
      PKG_CONFIG_LIBDIR=/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 1.1.1o  3 May 2022`

I did install it with swupd using the following command `sudo swupd bundle-add devpkg-xrdp`.

I found out that `/etc/pam.d/xrdp-sesman` is actually located in `/usr/share/pam.d/xrdp-sesman`. Here is that of that file: 

`#%PAM-1.0
#
# Really basic authentication set when nothing else is available
#
# You may need to edit this to suit your system depending on the
# required functionality.
#
auth       required     pam_unix.so shadow
auth       required     pam_env.so

password    required    pam_unix.so

account     required    pam_unix.so
account     required    pam_nologin.so

session     required    pam_unix.so`
 
Again there was nothing under the `/etc/pam.d` directory but here is the output of `/usr/share/pam.d`:

`total 160
-rw-r--r-- 9 root root  103 Oct 31  2019 chage
-rw-r--r-- 1 root root  427 Oct 31  2019 chfn
-rw-r--r-- 9 root root  103 Oct 31  2019 chgpasswd
-rw-r--r-- 1 root root  252 Oct 31  2019 chpasswd
-rw-r--r-- 1 root root  625 Oct 31  2019 chsh
-rw-r--r-- 1 root root 1208 Nov 13  2020 common-account
-rw-r--r-- 1 root root  883 Nov 13  2020 common-auth
-rw-r--r-- 1 root root 1633 Nov 13  2020 common-password
-rw-r--r-- 1 root root  890 Nov 13  2020 common-session
-rw-r--r-- 1 root root  818 Nov 13  2020 common-session-noninteractive
-rw-r--r-- 1 root root   56 Jan 26 14:30 cups
-rw-r--r-- 1 root root  579 Feb  1  2019 gdm-autologin
-rw-r--r-- 1 root root  548 Feb  1  2019 gdm-fingerprint
-rw-r--r-- 1 root root  646 Feb  1  2019 gdm-launch-environment
-rw-r--r-- 1 root root  494 Feb  1  2019 gdm-password
-rw-r--r-- 1 root root  520 Feb  1  2019 gdm-smartcard
-rw-r--r-- 9 root root  103 Oct 31  2019 groupadd
-rw-r--r-- 9 root root  103 Oct 31  2019 groupdel
-rw-r--r-- 9 root root  103 Oct 31  2019 groupmems
-rw-r--r-- 9 root root  103 Oct 31  2019 groupmod
-rw-r--r-- 1 root root  388 Feb  1  2019 login
-rw-r--r-- 1 root root  564 May 15 15:01 mock
-rw-r--r-- 1 root root  106 Oct 31  2019 newusers
-rw-r--r-- 1 root root  816 Nov 13  2020 other
-rw-r--r-- 1 root root  106 Oct 31  2019 passwd
-rw-r--r-- 1 root root  155 Feb  1  2019 polkit-1
-rw-r--r-- 1 root root  143 Feb  1  2019 runuser
-rw-r--r-- 1 root root  138 Feb  1  2019 runuser-l
-rw-r--r-- 1 root root  279 Feb  1  2019 sshd
-rw-r--r-- 2 root root  178 Feb  1  2019 su
-rw-r--r-- 1 root root   84 Feb  1  2019 sudo
-rw-r--r-- 2 root root  178 Feb  1  2019 su-l
-rw-r--r-- 1 root root  430 Feb  1  2019 system-auth
-rw-r--r-- 1 root root  337 Feb  1  2019 systemd-user
-rw-r--r-- 9 root root  103 Oct 31  2019 useradd
-rw-r--r-- 9 root root  103 Oct 31  2019 userdel
-rw-r--r-- 9 root root  103 Oct 31  2019 usermod
-rw-r--r-- 1 root root  316 Jan 21  2020 vlock
-rw-r--r-- 1 root root  400 Mar 23 11:50 xrdp-sesman
-rw-r--r-- 1 root root  313 Mar 10 12:17 xscreensaver`

I hope this helps maybe find the root cause to the problem! Thanks again :)

**Comment by mattbarich** [comment]
@matt335672 
Here is the output of `xrdp -v`
```
xrdp 0.9.19
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-generic-linux-gnu
      --host=x86_64-generic-linux-gnu
      --target=x86_64-clr-linux-gnu
      --program-prefix=
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/bin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --sharedstatedir=/usr/com
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-pixman
      --enable-jpeg
      --enable-fuse
      --enable-pam
      --enable-vsock
      build_alias=x86_64-generic-linux-gnu
      host_alias=x86_64-generic-linux-gnu
      target_alias=x86_64-clr-linux-gnu
      CC=gcc
      CFLAGS=-O2 -g -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=64 -Wformat -Wformat-security -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -ftree-vectorize -ftree-slp-vectorize -Wl,--enable-new-dtags -fcf-protection=return -Wl,--build-id=sha1 -m64 -march=westmere -mtune=skylake-avx512 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -fno-lto -fstack-protector-strong -fzero-call-used-regs=used  -fPIC
      LDFLAGS= -Wl,--build-id=sha1
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig
      PKG_CONFIG_LIBDIR=/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 1.1.1o  3 May 2022
```

I did use swupd with the following command `sudo swupd bundle-add devpkg-xrdp`

In Clear Linux `/etc/pam.d/xrdp-sesman` is located at `/usr/share/pam.d/xrdp-sesman`. Here is the output of that file: 
![image](https://user-images.githubusercontent.com/56982219/170587423-7987837a-1659-435d-9cff-68692a610f61.png)

`/etc/pam.d` is located at `/usr/share/pam.d/` as well. Here is the output of  `/usr/share/pam.d/`:

```
total 160
-rw-r--r-- 9 root root  103 Oct 31  2019 chage
-rw-r--r-- 1 root root  427 Oct 31  2019 chfn
-rw-r--r-- 9 root root  103 Oct 31  2019 chgpasswd
-rw-r--r-- 1 root root  252 Oct 31  2019 chpasswd
-rw-r--r-- 1 root root  625 Oct 31  2019 chsh
-rw-r--r-- 1 root root 1208 Nov 13  2020 common-account
-rw-r--r-- 1 root root  883 Nov 13  2020 common-auth
-rw-r--r-- 1 root root 1633 Nov 13  2020 common-password
-rw-r--r-- 1 root root  890 Nov 13  2020 common-session
-rw-r--r-- 1 root root  818 Nov 13  2020 common-session-noninteractive
-rw-r--r-- 1 root root   56 Jan 26 14:30 cups
-rw-r--r-- 1 root root  579 Feb  1  2019 gdm-autologin
-rw-r--r-- 1 root root  548 Feb  1  2019 gdm-fingerprint
-rw-r--r-- 1 root root  646 Feb  1  2019 gdm-launch-environment
-rw-r--r-- 1 root root  494 Feb  1  2019 gdm-password
-rw-r--r-- 1 root root  520 Feb  1  2019 gdm-smartcard
-rw-r--r-- 9 root root  103 Oct 31  2019 groupadd
-rw-r--r-- 9 root root  103 Oct 31  2019 groupdel
-rw-r--r-- 9 root root  103 Oct 31  2019 groupmems
-rw-r--r-- 9 root root  103 Oct 31  2019 groupmod
-rw-r--r-- 1 root root  388 Feb  1  2019 login
-rw-r--r-- 1 root root  564 May 15 15:01 mock
-rw-r--r-- 1 root root  106 Oct 31  2019 newusers
-rw-r--r-- 1 root root  816 Nov 13  2020 other
-rw-r--r-- 1 root root  106 Oct 31  2019 passwd
-rw-r--r-- 1 root root  155 Feb  1  2019 polkit-1
-rw-r--r-- 1 root root  143 Feb  1  2019 runuser
-rw-r--r-- 1 root root  138 Feb  1  2019 runuser-l
-rw-r--r-- 1 root root  279 Feb  1  2019 sshd
-rw-r--r-- 2 root root  178 Feb  1  2019 su
-rw-r--r-- 1 root root   84 Feb  1  2019 sudo
-rw-r--r-- 2 root root  178 Feb  1  2019 su-l
-rw-r--r-- 1 root root  430 Feb  1  2019 system-auth
-rw-r--r-- 1 root root  337 Feb  1  2019 systemd-user
-rw-r--r-- 9 root root  103 Oct 31  2019 useradd
-rw-r--r-- 9 root root  103 Oct 31  2019 userdel
-rw-r--r-- 9 root root  103 Oct 31  2019 usermod
-rw-r--r-- 1 root root  316 Jan 21  2020 vlock
-rw-r--r-- 1 root root  400 Mar 23 11:50 xrdp-sesman
-rw-r--r-- 1 root root  313 Mar 10 12:17 xscreensaver
```

Hopefully this can help find the root cause! Thanks again much appreciated :)

**Comment by matt335672** [comment]
The contents of `/usr/share/pam.d/pam-sesman` are the default contents when the install script can't work out what the platform is.

Can you try replacing that file with this one:-

```
#%PAM-1.0
@include common-auth
@include common-account
@include common-session
@include common-password
```

Also, can you give me the output of the following command:-

```
find / -xdev -name pam_unix.so\* 2>/dev/null
```

Thanks.

**Comment by mattbarich** [comment]
@matt335672 Sorry for the late response, I was out for a long weekend. I added the snippet above to `/usr/share/pam.d/pam-sesman`. I then restarted the services and I was unable to logon. I am still getting the same error messages in the log files as well. The output of `find / -xdev -name pam_unix.so\* 2>/dev/null` gave me the  following results:

```
/usr/lib64/security/pam_unix.so
/usr/lib32/security/pam_unix.so
```

**Comment by matt335672** [comment]
OK - thanks. I can see how the installation is failing now.

Does your system have something like `/var/log/auth.log` on it? It would be useful at this stage to see what PAM is doing. I suggest leaving `/usr/share/pam.d/pam-sesman` in its modified state.

**Comment by mattbarich** [comment]
@matt335672 I cannot find anything like `/var/log/auth.log` on the system, I have been looking around other forums and cannot find anything along those lines. I am kinda at the point of just installing a difference Linux Distro that wont give me as many problems lol

**Comment by matt335672** [comment]
The auth fail from the PAM stack should be logged somewhere.

After trying to log in, try this command which prints the last minute from the systemd logging facility:-

```
sudo journalctl -S -1m
```

Maybe we'll get some clues from there.

**Comment by mattbarich** [comment]
@matt335672 here is the information from that command after trying to log in:

Jun 03 15:16:18 chip-acdc sudo[7169]: pam_unix(sudo:session): session closed for user root
Jun 03 15:16:35 chip-acdc xrdp[4728]: [INFO ] Socket 12: AF_INET connection received from 192.168.72.120 port 6341
Jun 03 15:16:35 chip-acdc xrdp[7174]: [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
Jun 03 15:16:35 chip-acdc xrdp[7174]: [ERROR] Cannot read certificate file /etc/xrdp/cert.pem: No such file or directory
Jun 03 15:16:35 chip-acdc xrdp[7174]: [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Jun 03 15:16:35 chip-acdc xrdp[7174]: [ERROR] Cannot read private key file /etc/xrdp/key.pem: No such file or directory
Jun 03 15:16:35 chip-acdc xrdp[7174]: [WARN ] Cannot accept TLS connections because certificate or private key file is not readable. certificate file: [/etc/xrdp/cert.pem], private key file: [/etc/xrdp/key.pem]
Jun 03 15:16:35 chip-acdc xrdp[7174]: [INFO ] Security protocol: configured [RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [RDP]
Jun 03 15:16:35 chip-acdc xrdp[7174]: [ERROR] libxrdp_force_read: header read error
Jun 03 15:16:35 chip-acdc xrdp[7174]: [ERROR] Processing [ITU-T T.125] Connect-Initial failed
Jun 03 15:16:35 chip-acdc xrdp[7174]: [ERROR] [MCS Connection Sequence] receive connection request failed
Jun 03 15:16:35 chip-acdc xrdp[7174]: [ERROR] xrdp_sec_incoming: xrdp_mcs_incoming failed
Jun 03 15:16:35 chip-acdc xrdp[7174]: [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
Jun 03 15:16:35 chip-acdc xrdp[7174]: [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
Jun 03 15:16:35 chip-acdc xrdp[7174]: [ERROR] xrdp_iso_send: trans_write_copy_s failed
Jun 03 15:16:35 chip-acdc xrdp[7174]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jun 03 15:16:35 chip-acdc xrdp[4728]: [INFO ] Socket 12: AF_INET connection received from 192.168.72.120 port 6342
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
Jun 03 15:16:35 chip-acdc xrdp[7175]: [ERROR] Cannot read certificate file /etc/xrdp/cert.pem: No such file or directory
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Jun 03 15:16:35 chip-acdc xrdp[7175]: [ERROR] Cannot read private key file /etc/xrdp/key.pem: No such file or directory
Jun 03 15:16:35 chip-acdc xrdp[7175]: [WARN ] Cannot accept TLS connections because certificate or private key file is not readable. certificate file: [/etc/xrdp/cert.pem], private key file: [/etc/xrdp/key.pem]
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] Security protocol: configured [RDP], requested [RDP], selected [RDP]
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] Connected client computer name: DESKTOP-MATT-IT
Jun 03 15:16:35 chip-acdc xrdp[7175]: [WARN ] Client and server do not both support the same encryption.
Jun 03 15:16:35 chip-acdc xrdp[7175]: [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
Jun 03 15:16:35 chip-acdc xrdp[7175]: [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x00000409]
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [us] options []
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] Non-TLS connection established from 192.168.72.120 port 6342: with security level : none
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 10485760 MB cache entries 100
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
Jun 03 15:16:35 chip-acdc xrdp[7175]: [WARN ] xrdp_caps_process_codecs: unknown codec id 5
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
Jun 03 15:16:35 chip-acdc xrdp[7175]: [INFO ] Loading keymap file /usr/share/defaults/xrdp/km-00000409.ini
Jun 03 15:16:35 chip-acdc xrdp[7175]: [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
Jun 03 15:16:42 chip-acdc xrdp[7175]: [INFO ] connecting to sesman on 127.0.0.1:3350
Jun 03 15:16:42 chip-acdc xrdp-sesman[4722]: [INFO ] Socket 12: AF_INET connection received from 127.0.0.1 port 42180
Jun 03 15:16:42 chip-acdc xrdp[7175]: [INFO ] xrdp_wm_log_msg: sesman connect ok
Jun 03 15:16:42 chip-acdc xrdp[7175]: [INFO ] sesman connect ok
Jun 03 15:16:42 chip-acdc xrdp[7175]: [INFO ] sending login info to session manager. Please wait...
Jun 03 15:16:42 chip-acdc xrdp-sesman[4722]: pam_warn(gdm:auth): function=[pam_sm_authenticate] flags=0 service=[gdm] terminal=[gdm] user=[chip] ruser=[<unknown>] rhost=[<unknown>]
Jun 03 15:16:42 chip-acdc xrdp-sesman[4722]: [ERROR] pam_authenticate failed: Authentication failure
Jun 03 15:16:42 chip-acdc xrdp-sesman[4722]: [INFO ] AUTHFAIL: user=chip ip=192.168.72.120 time=1654291002
Jun 03 15:16:42 chip-acdc xrdp[7175]: [INFO ] xrdp_wm_log_msg: login failed for user chip
Jun 03 15:16:42 chip-acdc xrdp-sesman[4722]: [ERROR] sesman_data_in: scp_process_msg failed
Jun 03 15:16:42 chip-acdc xrdp[7175]: [INFO ] login failed for user chip
Jun 03 15:16:42 chip-acdc xrdp-sesman[4722]: [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans

**Comment by matt335672** [comment]
This looks a bit odd:-

```
Jun 03 15:16:42 chip-acdc xrdp-sesman[4722]: pam_warn(gdm:auth): function=[pam_sm_authenticate] flags=0 service=[gdm] terminal=[gdm] user=[chip] ruser=[] rhost=[]
```

What's in `/usr/share/pam.d/common-auth`?

**Comment by mattbarich** [comment]
@matt335672 Here is the contents of `/usr/share/pam.d/common-auth`

`#`
`#/etc/pam.d/common-auth - authentication settings common to all services`
`#`
`# This file is included from other service-specific PAM config files,`
`# and should contain a list of the authentication modules that define`
`# the central authentication scheme for use on the system`
`# (e.g., /etc/shadow, LDAP, Kerberos, etc.).  The default is to use the`
`# traditional Unix authentication mechanisms.`

`# here are the per-package modules (the "Primary" block)`
`auth    [success=1 default=ignore]      pam_unix.so nullok_secure`
`# here's the fallback if no module succeeds`
`auth    requisite                       pam_deny.so`
`# prime the stack with a positive return value if there isn't one already;`
`# this avoids us returning an error just because nothing sets a success code`
`# since the modules above will each just jump around`
`auth    required                        pam_permit.so`
`# and here are more per-package modules (the "Additional" block)`

**Comment by matt335672** [comment]
This isn't making a lot of sense to me at the moment.

Let's try bypassing the password authentication completely. **I'm assuming your machine isn't reachable over the Internet.**

Can you replace `/etc/pam.s/xrdp-sesman` with this file:-

```
#%PAM-1.0
#auth [success=1 default=ignore] pam_unix.so nullok_secure
# auth requisite pam_deny.so
auth required pam_permit.so

@include common-account
@include common-session
@include common-password
```

That should let you log in as `chip` with any password.

**Comment by matt335672** [comment]
No more info from OP - closing

**Comment by jchoksijudopay** [comment]
Leaving a note for future me for if/when I have this issue again. In openSUSE Tumbleweed, for some reason, the contents of the /usr/lib/pam.d/xrdp-sesman file were not taking effect. I copied that file to /etc/pam.d/xrdp-sesman and was able to login fine.

The contents of the /usr/lib/pam.d/xrdp-sesman file were:
```
#%PAM-1.0
auth        include     common-auth
account     include     common-account
session     include     common-session
session     optional    pam_keyinit.so force revoke
session     required    pam_loginuid.so
password    include     common-password
```

and I confirm that the error message I was seeing in the systemd journal was:

```
Jan 30 10:53:46 ostvm.localdomain xrdp-sesman[1870]: pam_warn(gdm:auth): function=[pam_sm_authenticate] flags=0 service=[gdm] terminal=[gdm] user=[MY_USERNAME] ruser=[<unknown>]  rhost=[<unknown>]
```

**Comment by neoacevedo** [comment]
When I updated openSUSE Tumbleweed in my remote PC some days ago, I am suddenly receiving the login failed although the credentials are right. I also see the same error:
`feb 4 13:53:46 xrdp-sesman[7823]: pam_warn(gdm:auth): function=[pam_sm_authenticate] flags=0 service=[gdm] terminal=[gdm] user=[myusername] ruser=[<unknown>]  rhost=[<unknown>]`

**Comment by matt335672** [comment]
@neoacevedo - this is nothing to do with xrdp. It's from `gdm`, which we don't use.

**Comment by mattgagliardi** [comment]
> When I updated openSUSE Tumbleweed in my remote PC some days ago, I am suddenly receiving the login failed although the credentials are right. I also see the same error:
> `feb 4 13:53:46 xrdp-sesman[7823]: pam_warn(gdm:auth): function=[pam_sm_authenticate] flags=0 service=[gdm] terminal=[gdm] user=[myusername] ruser=[<unknown>] rhost=[<unknown>]`

Same issue here, just updated this afternoon and lost my ability to connect using xrdp. Copying the xrdp-sesman file in from lib as recommended seems to have fixed the problem.

**Comment by neoacevedo** [comment]
~~Where is exactly this file? I don't find it.~~

Ok, in /usr/lib/pam.d, I got it so I copied it to /etc/pam.d and the remote session has worked again.

**Comment by RummsMurmel** [comment]
Thank you - same issue on my newly created VM with OpenSuSe Tumbleweed...

I had to copy the xrdp-sesman file to the pam.d config directory und instantly it worked...
```
cp /usr/lib/pam.d/xrdp-sesman /etc/pam.d/
```
