### ISSUE TITLE
Enable Glamour on Ubuntu Without Recompiling Everything

### ISSUE THREAD

**Issue by citratecycle** [neutrinolabs/xrdp#2284]
Hello there,

I'm a new user to `xrdp` and I'm using Ubuntu Desktop 22.04 with an Intel on-chip GPU. I learned that `xrdp` has a "glamour" feature that can use GPU to accelerate the render of desktop. However, by a search, I found that this feature can only be enabled by re-compiling `xrdp` and `xordxrdp` with flag `--enable-glamor`. I also learned that on Arch Linux, there's a package `xorgxrdp-glamour` that can enable the hardware acceleration feature. I'm wondering:

* Is it possible to enable the glamour feature by default in future Ubuntu `xrdp` package?
* If not, is it possible to include the feature and turn it off by default, and enable it by modifying some configuration file? (Like `/etc/ssh/sshd_config` for `sshd`)
* If not, is it possible to provide a separated package that can enable hardware acceleration like the package `xorgxrdp-glamour` on Arch Linux?

It will helps a lot if the feature can be enabled without recompiling everything.

Best.

**Comment by matt335672** [comment]
Hi @citratecycle 

I understand your concerns. However, we don't package xrdp and xorgxrdp for Debian/Ubuntu - this is all done by the Debian 'Remote Packaging Team'.

You can raise an issue on the Debian BTS related to this. They will assess the maturity of the feature and decide whether it is suitable for enabling in a later version of the packages. This process is, however, not quick.

Each distro has its own approach to how quickly they will package new features for sub-projects - I'm sure you're aware of this, or becoming aware of this. Arch is particularly aggressive about this, and Debian/Ubuntu is particularly conservative.

I can't add much more to this I'm afraid. Come back to me if you have more questions as a result of the above.

**Comment by citratecycle** [comment]
Oh. I see... Thanks a lot for your information and I'll try to find a resolution.

**Comment by pwn0r** [comment]
> Oh. I see... Thanks a lot for your information and I'll try to find a resolution.

just a few tricks and tips for you here, a fellow debian user :) 

* Ubuntu old versions have extremely outdated builds. Like 20.04LTS still has .12 which is ridiculous. Even 22.04 has .17 which is outdated as well. 
* Debian 12 is recommended and it has official .19 version now. 
* There is a great and easy way to install a custom xrdp build on your system, you can use a script c-nergy.be/blog/?p=17994 (the most recent version at the moment of writing) in a custom mode.
