### ISSUE TITLE
Polkitd + KDE Plasma on Kubuntu 20.04 - Possible to emulate local behaviour?

### ISSUE THREAD

**Issue by alexhorner** [neutrinolabs/xrdp#2305]
Hello,

I bring another polkitd related issue I'm afraid. I have looked at #1773 and #1889 and skimmed through some others,

I have seen mentions of .conf files not working with polkitd anymore which is something I have tried without success, so that seems likely in my scenario too.

This issue is present with both XRDP and X2Go, both of which I wish to use but am struggling due to this issue.

#1773 seems to focus very much on fixing singular popup issues, however this isn't what I want to do. My machine is fully headless, and everything works perfectly when I connect a display, mouse and keyboard, but when using it headless I get varying quantities of authentication popups named `Authentication Required - PolicyKit1 KDE Agent` regarding network controls and at various other points on the system.

The WiFi toggle and controls do not work, shutdown and restart do not work.

If at all possible, I would like to have XRDP (and X2Go, however understandably this is not for you to worry about) log into the system with the exact same policies applied as would be applied logging into a local display on the system. I do understand the security implications of doing such a thing, however seeing as this machine is intended to run fully headless I think this is an acceptable thing to do.

I understand this is probably not the most detailed issue, however I am really struggling to bring together the components of other issues here to get this to work as I intend, and the amount of information online is lacking with regards to actual fixes, just full of single popup removals and various workarounds for single scenarios, not something more generic. I am of course more than happy to provide any additional context requested.

![image](https://user-images.githubusercontent.com/33007665/177334567-0f4d92bb-c9b4-4e13-8239-a7c598c8c9e1.png)

**Comment by matt335672** [comment]
Hi @alexhorner 

> If at all possible, I would like to have XRDP (and X2Go, however understandably this is not for you to worry about) log into the system with the exact same policies applied as would be applied logging into a local display on the system.

I can see where you're coming from, but as far as we can tell, this simply isn't possible.

Depending on your distribution, you will need to set up ini-based pkla files (polkit <=0 0.105) or Javascript-based ones (polkit > 0.105). In both of these, actions can be wildcarded in order to increase their scope - this can make it easier to limit the number of files required.

At the moment, that's the best I can give you, I'm afraid.

**Comment by alexhorner** [comment]
Hi @matt335672,

> I can see where you're coming from, but as far as we can tell, this simply isn't possible.

Ah that's a real shame. I thought it might be possible to find and copy and adapt the rules defined for the local display.

> Depending on your distribution, you will need to set up ini-based pkla files (polkit <=0 0.105) or Javascript-based ones (polkit > 0.105). In both of these, actions can be wildcarded in order to increase their scope - this can make it easier to limit the number of files required.

I had considered experimenting with a blanket wildcard, but as with any permissions system, it is indeed possible to give yourself too many permissions resulting in undefined or undesired consequences, which is something I am concerned about in doing this.

I would imagine my only alternative is to try and find some way to find each permission for each broken element of the system and slowly build a list of corrections.

Any advice would be much appreciated though I understand this is a tricky subject with caveats and oddities in all directions. Thanks!

**Comment by matt335672** [comment]
You can use `pkaction` to list all the action IDs, and `pkaction --verbose --action-id=<whatever>` to see how they are set up. In theory you could script this to generate required pkla files. It's perfectly doable. Downsides:-

1) This would affect other remote sessions, like `ssh` sessions.
2) It's a bit brittle.

**Comment by alexhorner** [comment]
> You can use `pkaction` to list all the action IDs, and `pkaction --verbose --action-id=<whatever>` to see how they are set up. In theory you could script this to generate required pkla files. It's perfectly doable. Downsides:-
> 
> 1) This would affect other remote sessions, like `ssh` sessions.
> 2) It's a bit brittle.

I don't think polkitd would affect a terminal based session would it? Just X11 forwarding, which I don't use anyway.

I see what you mean by using `pkaction` but do you know if I can sort of point at a thing that's broken and get the action ID? I'm assuming if I put polkitd into som kind of verbose mode I could see this logged somewhere.

**Comment by matt335672** [comment]
`polkitd` affects everything - not just GUI sessions. Try `systemctl restart xrdp` from a ssh prompt for an unprivileged user, and you'll see it in action (at least you do on Ubuntu 20.04).

Getting the action ID can be the trickiest part of this, as different desktops present it in different ways. If you cancel a request operation this will generally get logged somewhere, like `/var/log/auth` or in the systemd journal. Alternatively you can restart polkitd in debugging mode. We did this in #1889, but you may be able to do it on the command line. This seems to work for me (again, on Ubuntu 20.04):-

```
sudo G_MESSAGES_DEBUG=all /usr/lib/policykit-1/polkitd -r
```

**Comment by alexhorner** [comment]
> `polkitd` affects everything - not just GUI sessions. Try `systemctl restart xrdp` from a ssh prompt for an unprivileged user, and you'll see it in action (at least you do on Ubuntu 20.04).
> 
> Getting the action ID can be the trickiest part of this, as different desktops present it in different ways. If you cancel a request operation this will generally get logged somewhere, like `/var/log/auth` or in the systemd journal. Alternatively you can restart polkitd in debugging mode. We did this in #1889, but you may be able to do it on the command line. This seems to work for me (again, on Ubuntu 20.04):-
> 
> ```
> sudo G_MESSAGES_DEBUG=all /usr/lib/policykit-1/polkitd -r
> ```
> 

Awesome, thanks for the advice. I'll give this a try later and report back

**Comment by alexhorner** [comment]
Hi there,

So my Kubuntu 20.04 install uses PKLA files. I feel like my understanding of this is getting better, and I think I am beginning to understand why you said

>I can see where you're coming from, but as far as we can tell, this simply isn't possible.

as there doesn't appear to be any INI option you can set when `local=0` even when `active=1`

I have successfully used your debug command to view what I was looking for with regards to what gets triggered for these popups and the system tray controls. It does indeed state that I am not authorised to access these functions when coming in from a remote connection. When coming in from a local display, I am authorised with the message `is authorized (has implicit authorization local=1 active=1)` which I assume means the `local=1` gives me implicit authorisation to the associated functions without prompt for credentials/identity proof.

I feel like if the distro came with a newer PolkitD which supported the JavaScript based rules, I might be in with a chance of working out some rules which permit the same things remotely as are permitted locally.

I have considered again doing the wildcard on literally everything to blanket permit me everything, however as I have said before I do not know the consequences of doing this, as there are a few things which are not authorised (related to backlight control for example) even when connected via a local display. I would have assumed this is because it is a desktop system without a backlight but I would say that knowledge is nothing to do with PolkitD therefore this is not the reason for not being authorised, and here stems the fear of unintended consequences if I were to do a blanket permit.

It would be awesome if this issue could be kept open for now, for I am eager to post any solutions, workarounds and findings I may find, and it would also be nice to see someone else having success that they can post here too.

For now I am no further along, however I do feel I have a better understanding of the complexities of PolkitD.

**Comment by matt335672** [comment]
Hi @alexhorner 

As regards the Javascript, don't expect that in Ubuntu/Debian any time soon. Polkit 0.106 was released in June 2012. Debian continues to stick with the old style from 0.105. See [this discussion](https://discourse.ubuntu.com/t/use-of-javascript-rules-in-polkit) for more info.

The `local=1 active=1` maps to the `implicit active` field returned by `pkaction`. On the system I'm currently on (Mint Una), `pkaction --verbose --action-id org.freedesktop.login1.reboot` gives me:-

```
$ pkaction --action-id org.freedesktop.login1.reboot
org.freedesktop.login1.reboot
mjb@andelain:~/Desktop$ pkaction --verbose --action-id org.freedesktop.login1.reboot
org.freedesktop.login1.reboot:
  description:       Reboot the system
  message:           Authentication is required to reboot the system.
  vendor:            The systemd Project
  vendor_url:        http://www.freedesktop.org/wiki/Software/systemd
  icon:              
  implicit any:      auth_admin_keep
  implicit inactive: auth_admin_keep
  implicit active:   yes
  annotation:        org.freedesktop.policykit.imply -> org.freedesktop.login1.set-wall-message
```

Consequently, the `reboot` command without `sudo` works fine from the command line on a native terminal. I just verified that by rebooting my machine halfway though writing this (In my defence I need a coffee!) On the other hand, if I `ssh localhost` as the same user, and try `reboot`, the command fails:-

```
$ reboot
Failed to set wall message, ignoring: Interactive authentication required.
Failed to reboot system via logind: Interactive authentication required.
Failed to open initctl fifo: Permission denied
Failed to talk to init daemon.
```

If you want to get a decent rule set to start with, you could maybe work on a local session for a bit with polkit logging enabled, and then parse the resulting log file to see what actions are implicitly authorized while you're in the session.

I'll convert this issue to a discussion, as this is the best place for keeping things in the long-term.
