### ISSUE TITLE
XRDP yellowish blank Screen

### ISSUE THREAD

**Issue by darkworks** [neutrinolabs/xrdp#2311]
Guys 
Am seeing XRDP yellowish screen no icons on desktop and no start menu etc totally blank but when i right click i can see menu from where currently am operating things like terminal and browser etc. so any idea how to fix and debug it 

![image](https://user-images.githubusercontent.com/12841788/178093364-ad834bd1-a154-46b8-b02b-ab20daebdb7c.png)

system
```
    Virtualization: openvz
  Operating System: Ubuntu 16.04.7 LTS
   Kernel: Linux 2.6.32-042stab134.8
      Architecture: x86-64
```

xrdp verson
```
xrdp 0.9.19
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-fuse
      --enable-mp3lame
      --enable-pixman

  Compiled with OpenSSL 1.0.2g  1 Mar 2016
```

thanks

**Comment by matt335672** [comment]
@darkworks - it's not clear to me what you're asking.

Is the background menu normal for the desktop you're expecting?

Have you set up `~/.Xsession` or `~/.xsession`?

**Comment by darkworks** [comment]
> @darkworks - it's not clear to me what you're asking.
> 
> Is the background menu normal for the desktop you're expecting?
> 
> Have you set up `~/.Xsession` or `~/.xsession`?

yes right click background menu is normal , however there is no desktop icon and start menu appearing , it was all ok but after machine reboot that started to occur 

Have you set up `~/.Xsession` or `~/.xsession`?

not sure about it , i guess its setuped as the same installation steps i did for my another machine xrdp is OK   however this one showing blank desktop while mouse right click menu is operational.
anyway can u tell how to setup :  `~/.Xsession` or `~/.xsession`

**Comment by matt335672** [comment]
I don't thing you need to set up `~/.Xsession` or `~/.xsession` - I just wondered if you'd done it.

Is this a physical machine? What happens when you try to use the same account to log in on the console?

**Comment by darkworks** [comment]
> I don't thing you need to set up `~/.Xsession` or `~/.xsession` - I just wondered if you'd done it.
> 
> Is this a physical machine? What happens when you try to use the same account to log in on the console?

no not physical machine , its OpenVZ 6 VPS.  ya via SSH i was able to access it.  yesterday i reinstall OS on it , to re setup it.

**Comment by matt335672** [comment]
Can you get to the machine console at all? That would help with the debugging,

**Comment by darkworks** [comment]
> Can you get to the machine console at all? That would help with the debugging,

i have wiped the machine and reinstalled it  , however you can see screen shot i attached in which u can see i was able to lunch terminal and also start chrome browser too from the mouse right click menu via XRDP . and other than that via SSH ya access to terminal was OK 

![image](https://user-images.githubusercontent.com/12841788/179729289-be1ba058-ca6a-4e85-916b-fbe0b0d733a5.png)

**Comment by matt335672** [comment]
Yes, I understand the xrdp situation. However, you haven't answered my question.

Are you able to connect to the machine console?

**Comment by darkworks** [comment]
> Yes, I understand the xrdp situation. However, you haven't answered my question.
> 
> Are you able to connect to the machine console?

i  not understand what u mean by `connect to the machine console?`
i had mentioned it that ya i was able to connect to machine via SSH, it present i cant because i had reinstalled OS to setup xrdp again.

**Comment by matt335672** [comment]
Imagine you have a physical machine in front of you. It's got a keyboard and mouse and a screen. You can do things from here like access the BIOS and do a bare metal install. The keyboard, mouse and screen together form the 'machine console'.

You've got a virtual machine here, so there's clearly no physical console. However, for many virtualisation platforms there is a way to get to see the output of the virtual graphics card, and provide keyboard and mouse input. So the effect is the same as sitting in front of a physical machine.

Does your virtualisation platform offer this capability?

**Comment by darkworks** [comment]
> Imagine you have a physical machine in front of you. It's got a keyboard and mouse and a screen. You can do things from here like access the BIOS and do a bare metal install. The keyboard, mouse and screen together form the 'machine console'.
> 
> You've got a virtual machine here, so there's clearly no physical console. However, for many virtualisation platforms there is a way to get to see the output of the virtual graphics card, and provide keyboard and mouse input. So the effect is the same as sitting in front of a physical machine.
> 
> Does your virtualisation platform offer this capability?

oh i see . so sadly no does not offer direct display view . beside this KVM and openVZ virtual machines does not have detected graphics unit.

**Comment by matt335672** [comment]
We need to check the desktop is fully installed I think.

Which desktop are you wishing to use, and how did you install it?

Thanks.

**Comment by matt335672** [comment]
@darkworks - do you need any more help with this?

**Comment by darkworks** [comment]
it the moment no as i had wiped that machine and did reinstallation , if occur such issue again then will report here.

thanks
