### ISSUE TITLE
xrdp provides new desktop occationally while reconnecting (Version 0.9.5, "Ubuntu 18.04.6 LTS")

### ISSUE THREAD

**Issue by syed316** [neutrinolabs/xrdp#2320]
The issue is when we are in the middle of work the xrdp faces slowness or disconnects the XDRP, when reconnects we should get the desktop/screen where we left which opened, but it terminates the old sessions with unsaved files and opens a new connection and no open file or apps.
 
This issue like getting a new session after disconnection happens not every time, it's occasional.  

During the session, termination happens and creates a new one, following logs are generated.

================

Jul 15 08:52:06 unknown[6061]: wnck-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :12.0.
Jul 15 08:52:06 notification-ar[6071]: notification-area-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :12.0.
Jul 15 08:52:06 xrdp[33630]: (33630)(140277256423232)[DEBUG] Closed socket 17 (AF_UNIX)
Jul 15 08:52:06 xrdp[33630]: (33630)(140277256423232)[DEBUG] Closed socket 18 (AF_UNIX)
Jul 15 08:52:06 xrdp-sesman[5844]: (5844)(140150289257792)[CORE ] window manager (pid 5846) did exit, cleaning up session
Jul 15 08:52:06 NetworkManager[1536]: <warn>  [1657889526.2073] error requesting auth for org.freedesktop.NetworkManager.wifi.share.open: Authorization check failed: Failed to open file “/proc/6119/status”: No such file or directory
Jul 15 08:52:06 xrdp-sesman[5844]: (5844)(140150289257792)[INFO ] calling auth_stop_session and auth_end from pid 5844
Jul 15 08:52:06 xrdp-sesman[5844]: pam_unix(xrdp-sesman:session): session closed for user xxx.xxx
Jul 15 08:52:06 xrdp-sesman[5844]: (5844)(140150289257792)[DEBUG] cleanup_sockets:
Jul 15 08:52:06 xrdp-sesman[5844]: (5844)(140150289257792)[DEBUG] cleanup_sockets: deleting /var/run/xrdp/sockdir/xrdp_chansrv_audio_out_socket_12
Jul 15 08:52:06 xrdp-sesman[5844]: (5844)(140150289257792)[DEBUG] cleanup_sockets: deleting /var/run/xrdp/sockdir/xrdp_chansrv_audio_in_socket_12
Jul 15 08:52:06 xrdp-sesman[5844]: (5844)(140150289257792)[DEBUG] cleanup_sockets: deleting /var/run/xrdp/sockdir/xrdpapi_12
Jul 15 08:52:06 xrdp-sesman[1684]: (1684)(140150289257792)[INFO ] ++ terminated session:  username xxx.xxx, display :12.0, session_pid 5844, ip ::ffff:192.168.7.99:52192 - socket: 12
Jul 15 08:52:08 pulseaudio[33671]: [pulseaudio] client-conf-x11.c: xcb_connection_has_error() returned true
Jul 15 08:52:08 pulseaudio[33674]: [pulseaudio] pid.c: Stale PID file, overwriting.
Jul 15 08:52:13 xrdp[1703]: (1703)(140277256423232)[INFO ] Socket 12: AF_INET6 connection received from ::ffff:192.168.7.98 port 64882
Jul 15 08:52:13 xrdp[1703]: (1703)(140277256423232)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.7.114 port 3389)

================

**Comment by matt335672** [comment]
We've not seen an xrdp reconnection causing a session termination before.

Looking at the above, the session terminates at 08:52:06. A new connection request comes in at 08:52:13, some 7 seconds later. There's nothing you've posted which shows these to be connected in any way.

I don't understand from your description why you're disconnecting in the first place. Is this something you are choosing to do, or is is something that happens for no reason?

**Comment by syed316** [comment]
Hello Matt,

Thank you for the response.

I tried the same Xorg session to reconnect. I was facing lag in RDP so I disconnected and reconnected back. Every time it reconnects to the same session which I left but a few times it responds with a new session and no open files. Please let me know if any configurations that you can take a look at or logs.

Thanks,
Syed

**Comment by matt335672** [comment]
This is highly unlikely to be related to the reconnection. No-one's reported a similar error, and that's a pretty old version of xrdp. If this happened a lot I'd have thought we'd have heard about it before.

Are you using the Xorg or Xvnc backend to xrdp?

**Comment by syed316** [comment]
We are Using  Xorg, and this happened to my colleagues too.

**Comment by matt335672** [comment]
Thanks @syed316 

We're going to need more complete system logs to see what's going on here I think.

Next time it happens, can you get a complete system log for the last 3 minutes with `sudo journalctl -S -3m`? We'll see if we can get any more clues from that.

**Comment by syed316** [comment]
Hello @matt335672,

Please find the "journalctl" logs with time stamps where I got disconnected and got a new desktop while reconnecting.

Time stamps: 
Apr 22 17:37:18
Jun 01 21:39:10
Jun 06 13:45:32
Jun 26 11:14:28
Jul 15 08:52:06

[Logs_to_upload_github.txt](https://github.com/neutrinolabs/xrdp/files/9239012/Logs_to_upload_github.txt)

**Comment by matt335672** [comment]
- Apr 22 17:37:18. X server has exited. There is no obvious reason for this. There's av
- Jun 01 21:39:10 sshd session closed. There is no xrdp session active I can see
- Jun 06 13:45:32 X server has exited. There are indications physical memory may be short.
- Jun 26 11:14:28 X server has exited.
- Jul 15 08:52:06 X server has exited

I'm not seeing a lot of authentication requests from sesman. There's one for Jul 15, but the rest of the time there's no evidence that an authentication is happening around the time the session exits. So I'm inclined to think your sessions are exiting because the X server is crashing, and this is unrelated to a further xrdp connection.

Next thing to do is to look at the X server logs when this happens. These are called `~/.xorgxrdp.$DISPLAY.log` where $DISPLAY is the display number used for the session.

**Comment by matt335672** [comment]
@syed316 - do you need more input on this?

**Comment by syed316** [comment]
Hello Matt, 

Thank you for your time on this, closing this case.

Thanks.
