### ISSUE TITLE
Black screen & cinnamon fallback mode after Debian 11.4 update

### ISSUE THREAD

**Issue by Benjemmin** [neutrinolabs/xrdp#2327]
I've recently updated my system from Debian 11.3 to 11.4. Unfortunately XRDP stopped working. That is, for a non-sudo user. With my local admin account I can log-in fine, but when I use the normal user, I get a Cinnamon fallback error. The .xsession-errors file is attached below. From the looks of it, it seems like a rights issue, but if I check the Debian 11.4 changelogs, nothing catches my eye in that context. Is there somewhere else I can look for clues? 

Xsession: X session started for normaluser at Thu 28 Jul 2022 05:13:22 PM CEST
WARNING: tempfile is deprecated; consider using mktemp instead.
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/2558/bus
dbus-update-activation-environment: setting DISPLAY=:10.0
localuser:normaluser being added to access control list
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting USER=normaluser
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting LD_LIBRARY_PATH=:/usr/local/lib:/packages/lib:/packages/lib/vtk:/usr/local/lib:/packages/lib:/packages/lib/vtk
dbus-update-activation-environment: setting HOME=/home/normaluser
dbus-update-activation-environment: setting CINNAMON_2D=1
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting XRDP_PULSE_SINK_SOCKET=xrdp_chansrv_audio_out_socket_10
dbus-update-activation-environment: setting XRDP_PULSE_SOURCE_SOCKET=xrdp_chansrv_audio_in_socket_10
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/2558/bus
dbus-update-activation-environment: setting PULSE_SCRIPT=/etc/xrdp/pulse/default.pa
dbus-update-activation-environment: setting LOGNAME=normaluser
dbus-update-activation-environment: setting XDG_SESSION_CLASS=user
dbus-update-activation-environment: setting PATH=/home/normaluser/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/packages/bin:/home/localsw/bin
dbus-update-activation-environment: setting GTK3_MODULES=xapp-gtk3-module
dbus-update-activation-environment: setting XRDP_SOCKET_PATH=/run/xrdp/sockdir
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/2558
dbus-update-activation-environment: setting DISPLAY=:10.0
dbus-update-activation-environment: setting LANG=en_US.UTF-8
dbus-update-activation-environment: setting UID=2558
dbus-update-activation-environment: setting SHELL=/bin/bash
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting XRDP_SESSION=1
dbus-update-activation-environment: setting GPG_AGENT_INFO=/run/user/2558/gnupg/S.gpg-agent:0:1
dbus-update-activation-environment: setting PWD=/nfs/rtsan02/userdata/home/normaluser
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/
** Message: 17:13:22.937: couldn't access control socket: /run/user/2558/keyring/control: No such file or directory
** Message: 17:13:22.938: couldn't access control socket: /run/user/2558/keyring/control: No such file or directory
** Message: 17:13:22.939: couldn't access control socket: /run/user/2558/keyring/control: No such file or directory
SSH_AUTH_SOCK=/run/user/2558/keyring/ssh
Xlib:  extension "DPMS" missing on display ":10.0".
Xlib:  extension "DPMS" missing on display ":10.0".
Xlib:  extension "DPMS" missing on display ":10.0".

** (csd-media-keys:1473): WARNING **: 17:13:23.336: Unable to inhibit keypresses: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Permission denied
Xlib:  extension "DPMS" missing on display ":10.0".
Xlib:  extension "DPMS" missing on display ":10.0".
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
** Message: 17:13:23.349: Existing monitor config (/home/normaluser/.config/cinnamon-monitors.xml) not found at startup. Looking for legacy configuration (monitors.xml)
=== xinerama setup Configuration ===
  Clone: false
  Output: Unknown attached to rdp0
     status: on
     width: 1920
     height: 1200
     rate: 50
     primary: false
     position: 0 0
=== Applying Configuration Configuration ===
  Clone: false
  Output: Unknown attached to rdp0
     status: on
     width: 1920
     height: 1200
     rate: 50
     primary: true
     position: 0 0
Xlib:  extension "DPMS" missing on display ":10.0".
Xlib:  extension "DPMS" missing on display ":10.0".
Xlib:  extension "DPMS" missing on display ":10.0".

** (csd-color:1464): WARNING **: 17:13:23.414: failed to get edid: unable to get EDID for output
Xlib:  extension "DPMS" missing on display ":10.0".

** (csd-color:1464): WARNING **: 17:13:23.433: failed to create device: failed to obtain org.freedesktop.color-manager.create-device auth

** (csd-color:1464): WARNING **: 17:13:23.433: could not find device: property match 'XRANDR_name'='rdp0' does not exist
** (csd-color:1464): WARNING **: 17:13:23.434: failed to obtain org.freedesktop.color-manager.create-profile auth

** (csd-color:1464): WARNING **: 17:13:23.439: failed to obtain org.freedesktop.color-manager.create-profile auth

** (csd-color:1464): WARNING **: 17:13:23.444: failed to obtain org.freedesktop.color-manager.create-profile auth

** (csd-color:1464): WARNING **: 17:13:23.448: failed to obtain org.freedesktop.color-manager.create-profile auth

** (csd-color:1464): WARNING **: 17:13:23.453: failed to obtain org.freedesktop.color-manager.create-profile auth

** (csd-power:1436): WARNING **: 17:13:23.454: Failed set DPMS mode: Display is not DPMS capable

** (csd-power:1436): WARNING **: 17:13:23.457: Unable to inhibit lid switch: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Permission denied
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
Xlib:  extension "DPMS" missing on display ":10.0".
Xlib:  extension "DPMS" missing on display ":10.0".
Cinnamon warning: Software rendering detected: llvmpipe (LLVM 11.0.1, 256 bits)
Cjs-Message: 17:13:48.305: Profiler is disabled. Not setting up signals.
Clutter-Message: 17:13:48.322: Sync method: PRESENTATION TIME

** (light-locker:1707): ERROR **: 17:13:48.463: Environment variable XDG_SESSION_PATH not set. Is LightDM running?
Cjs-Message: 17:13:48.509: JS LOG: About to start Cinnamon
Cjs-Message: 17:13:48.509: JS LOG: ACTIVATING SOFTWARE RENDERING
Cjs-Message: 17:13:48.510: JS LOG: [LookingGlass/error] Cinnamon Software Rendering mode enabled
git-annex: Nothing listed in /home/normaluser/.config/git-annex/autostart

** (nemo-desktop:1715): WARNING **: 17:13:48.549: Current gtk theme is not known to have nemo support (Adwaita) - checking...

** (xiccd:1732): WARNING **: 17:13:48.553: EDID is empty

** (xiccd:1732): CRITICAL **: 17:13:48.553: unable to create profile: failed to obtain org.freedesktop.color-manager.create-profile auth

** (xiccd:1732): CRITICAL **: 17:13:48.560: unable to create profile: failed to obtain org.freedesktop.color-manager.create-profile auth

** (xiccd:1732): CRITICAL **: 17:13:48.560: unable to create profile: failed to obtain org.freedesktop.color-manager.create-profile auth

** (xiccd:1732): CRITICAL **: 17:13:48.569: unable to create profile: failed to obtain org.freedesktop.color-manager.create-profile auth

** (xiccd:1732): CRITICAL **: 17:13:48.574: unable to create profile: failed to obtain org.freedesktop.color-manager.create-profile auth

** (xiccd:1732): CRITICAL **: 17:13:48.593: failed to create colord device: failed to obtain org.freedesktop.color-manager.create-device auth

** (nemo-desktop:1715): WARNING **: 17:13:48.639: The theme appears to have no nemo support.  Adding some...

(nemo-desktop:1715): GLib-CRITICAL **: 17:13:48.664: g_strstr_len: assertion 'haystack != NULL' failed
** Message: 17:13:48.664: nemo-desktop: session is not cinnamon (checked XDG_SESSION_DESKTOP,DESKTOP_SESSION environment variables.) Applying default behavior
Cjs-Message: 17:13:48.692: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 180 ms
Cjs-Message: 17:13:48.712: JS LOG: [LookingGlass/info] loading default theme
kdeconnect.core: Could not query capabilities from notifications server
blueman-applet 17.13.48 WARNING  PluginManager:148 __load_plugin: Not loading DhcpClient because its conflict has higher priority
blueman-applet 17.13.48 WARNING  PluginManager:148 __load_plugin: Not loading PPPSupport because its conflict has higher priority
blueman-applet 17.13.48 ERROR    BasePlugin:76 _load     : [Errno 13] Permission denied: '/dev/rfkill'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/plugins/BasePlugin.py", line 70, in _load
    self.on_load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py", line 61, in on_load
    self._fd = os.open('/dev/rfkill', os.O_RDONLY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/rfkill'
blueman-applet 17.13.48 ERROR    PluginManager:162 __load_plugin: Failed to load KillSwitch
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/PluginManager.py", line 160, in __load_plugin
    inst._load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/AppletPlugin.py", line 57, in _load
    super()._load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/BasePlugin.py", line 70, in _load
    self.on_load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py", line 61, in on_load
    self._fd = os.open('/dev/rfkill', os.O_RDONLY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/rfkill'
blueman-applet version 2.1.4 starting
Traceback (most recent call last):
  File "/usr/bin/blueman-applet", line 42, in <module>
    BluemanApplet()
  File "/usr/lib/python3/dist-packages/blueman/main/Applet.py", line 34, in __init__
    self.Plugins.load_plugin()
  File "/usr/lib/python3/dist-packages/blueman/main/PluginManager.py", line 122, in load_plugin
    self.__load_plugin(cls)
  File "/usr/lib/python3/dist-packages/blueman/main/PluginManager.py", line 160, in __load_plugin
    inst._load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/AppletPlugin.py", line 57, in _load
    super()._load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/BasePlugin.py", line 70, in _load
    self.on_load()
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py", line 61, in on_load
    self._fd = os.open('/dev/rfkill', os.O_RDONLY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/rfkill'
Cjs-Message: 17:13:48.963: JS LOG: [LookingGlass/info] loaded at Thu Jul 28 2022 17:13:48 GMT+0200 (CEST)
Cjs-Message: 17:13:48.963: JS LOG: Cinnamon started at Thu Jul 28 2022 17:13:48 GMT+0200 (CEST)
Cjs-Message: 17:13:48.983: JS LOG: [LookingGlass/info] ExtensionSystem started in 1 ms
Cjs-Message: 17:13:48.983: JS LOG: [LookingGlass/info] DeskletManager started in 1 ms
Cjs-Message: 17:13:48.983: JS LOG: [LookingGlass/info] SearchProviderManager started in 0 ms
openGL version 4.5 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
Cjs-Message: 17:13:49.054: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 48 ms
Cjs-Message: 17:13:49.058: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 17:13:49.061: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 7 ms
Cjs-Message: 17:13:49.069: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 8 ms
Cjs-Message: 17:13:49.079: JS LOG: [LookingGlass/info] Loaded applet favorites@cinnamon.org in 10 ms
Cjs-Message: 17:13:49.123: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 44 ms
St-Message: 17:13:49.126: cogl npot texture sizes SUPPORTED
Cjs-Message: 17:13:49.141: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 18 ms
Cjs-Message: 17:13:49.154: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 13 ms
Cjs-Message: 17:13:49.161: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 17:13:49.177: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 23 ms
Cjs-Message: 17:13:49.181: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 4 ms
Cjs-Message: 17:13:49.207: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 17:13:49.209: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 28 ms
Cjs-Message: 17:13:49.234: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 25 ms

** (csd-power:1436): CRITICAL **: 17:13:49.242: abs_to_percentage: assertion 'max > min' failed
Cjs-Message: 17:13:49.267: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 33 ms
Cjs-Message: 17:13:49.296: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 29 ms
Cjs-Message: 17:13:49.312: JS LOG: NetworkManager is not running, hiding...
Cjs-Message: 17:13:49.447: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 151 ms
Cjs-Message: 17:13:49.447: JS LOG: [LookingGlass/info] AppletManager started in 483 ms
Cjs-Message: 17:13:49.450: JS LOG: [LookingGlass/info] Cinnamon took 941 ms to start
Traceback (most recent call last):
  File "/usr/bin/cinnamon-launcher", line 72, in <module>
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "/usr/lib/python3.9/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.9/os.py", line 616, in _execvpe
    raise last_exc
  File "/usr/lib/python3.9/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
15:13:49:0956 Gs  plugin fwupd took 1.2 seconds to do setup
15:13:50:0013 Gs  enabled plugins: desktop-categories, fwupd, os-release, packagekit, packagekit-local, packagekit-offline, packagekit-proxy, packagekit-refine-repos, packagekit-refresh, packagekit-upgrade, packagekit-url-to-app, appstream, desktop-menu-path, hardcoded-blocklist, hardcoded-popular, malcontent, modalias, odrs, packagekit-refine, rewrite-resource, packagekit-history, provenance, systemd-updates, generic-updates, provenance-license, icons, key-colors, key-colors-metadata
15:13:50:0013 Gs  disabled plugins: dpkg, dummy, repos
15:13:50:0427 Gs  not handling error failed for action refresh: Failed to update metadata for lvfs: checksum failure: failed to verify data, expected 4829e71dd0c59fb5bc302ee632c7aaddbb4a4078
15:13:50:0550 Gs  not handling error no-security for action refresh: Failed to check for authentication: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
15:13:50:0701 Gs  adding wildcard app */*/*/*/org.gnome.Builder.desktop/* to plugin cache
15:13:50:0702 Gs  adding wildcard app */*/*/*/org.gnome.Calculator.desktop/* to plugin cache
15:13:50:0702 Gs  adding wildcard app */*/*/*/org.gnome.clocks.desktop/* to plugin cache
15:13:50:0702 Gs  adding wildcard app */*/*/*/org.gnome.Dictionary.desktop/* to plugin cache
15:13:50:0702 Gs  adding wildcard app */*/*/*/org.gnome.Documents.desktop/* to plugin cache
15:13:50:0702 Gs  adding wildcard app */*/*/*/org.gnome.Evince/* to plugin cache
15:13:50:0702 Gs  Only 0 apps for recent list, hiding
15:13:50:0702 Gs  adding wildcard app */*/*/*/org.gnome.gedit.desktop/* to plugin cache
15:13:50:0702 Gs  adding wildcard app */*/*/*/org.gnome.Maps.desktop/* to plugin cache
15:13:50:0705 Gs  adding wildcard app */*/*/*/org.gnome.Weather/* to plugin cache
15:13:50:0714 Gs  hiding category games featured applications: found only 0 to show, need at least 9
15:13:50:0714 Gs  hiding category audio-video featured applications: found only 0 to show, need at least 9
15:13:51:0187 Gs  FIXME: Unknown progress handling is not yet implemented for GsProgressButton
15:13:51:0187 Gs  FIXME: Unknown progress handling is not yet implemented for GsProgressButton
15:13:51:0187 Gs  FIXME: Unknown progress handling is not yet implemented for GsProgressButton
15:13:51:0187 Gs  FIXME: Unknown progress handling is not yet implemented for GsProgressButton
15:13:51:0301 Gs  automatically prevented from changing kind on system/package/*/generic/org.gphoto.libgphoto2/* from generic to unknown!
15:13:51:0323 Gs  automatically prevented from changing kind on system/package/*/generic/com.yubico.yubikey.ykpers/* from generic to unknown!
15:13:51:0332 Gs  automatically prevented from changing kind on system/package/*/generic/com.yubico.yubikey.udev/* from generic to unknown!
x-session-manager[1289]: WARNING: t+31.38578s: Detected that screensaver has appeared on the bus

**Comment by matt335672** [comment]
It could also be something stale in the user account related to Cinnamon, possibly.

Try creating a gash empty non-privileged user and see what that does.

Failing that, comparing the `~/.xsession-errors` for the sudo user and the non-sudo user could be informative.

**Comment by matt335672** [comment]
@Benjemmin - do you need any more help with this?

**Comment by Benjemmin** [comment]
Thanks for the reply. With a new user there is indeed no errors, so it has to be an issue concerning the config files. I've deleted every .file in a testaccount and that got things working again. However, after more carefully selecting which files I should delete, I couldn't figure out what file could be responsible. Do you have any pointers on that?

**Comment by matt335672** [comment]
Not really. I'd start by assuming a single file is the culprit, and using some kind of binary chop. So copy half the files in to the new account, and if that works, copy half the remainder. When it stops working, the file that's responsible is probably in the last lot you've copied, so you can work your way though that to find it.

**Comment by matt335672** [comment]
No more info from OP - closing.

**Comment by Benjemmin** [comment]
Sorry for the late response. I've found out this issue has to do with the mesa_shader_cache in the .cache folder of a user. Once we delete it, the problem seems to be solved. However, it will re-occur once a user signs in to a PC with a different Debian version (e.g. 11.2 vs 11.4). Is there someway around this, or do we need to delete the mesa_shader_cache everytime on a log-out just in case?

**Comment by matt335672** [comment]
That's useful information - thanks for sharing it.

Just had a poke around. One workaround might be to set  might be to set `MESA_SHADER_CACHE_DIR` (see [here](https://docs.mesa3d.org/envvars.html)) in `/etc/profile.d` depending on the Debian version, or even move it to the local disk in a per-user directory under `/var` or `/run` (I take it you're using networked home directories).

I also came across this which isn't quite consistent with the link above:-

https://www.phoronix.com/news/Mesa-Shader-Cache-Env-Var

It's possible you may have to set more than one environment variable.

Hope that's useful.
