### ISSUE TITLE
Feature request: please provide install package for Windows. Etc make it working on Windows.

### ISSUE THREAD

**Issue by kgfly** [neutrinolabs/xrdp#2335]
Windows 10/11 Home edition cannot have RDP service enabled. (Suck!)

Is it possible for XRDP to work on Windows for Windows home edition? Otherwise, people have to choose sth like VNC (in Intranet), which is not as convenient as XRDP.

On the Internet, there are some "hack" methods to make RPD service enabled on Windows Home edition. But they are generally "hack", which may have security concerns. So "hack" methods are generally not good.

Please consider this feature request since billons of people are using Windows Home edition. Thank you.

**Comment by matt335672** [comment]
This has been covered recently in #2100. I don't think anything has changed in that regard.
