### ISSUE TITLE
Keyboard layout issues

### ISSUE THREAD

**Issue by HottuDoku** [neutrinolabs/xrdp#2337]
Hi,

I've encountered and issue with keyboard layouts. 
To add some background. My company is running LTSP and for remote users we want to deploy RDP server.
Iam running Ubuntu 22 with Mate desktop as a server and installed version 0.9.19 along with latest xorgxrdp and fail2ban.
Connecting on the server through either Windows Remote Desktop or Remmina from another linux machine works great. The only issue is, when user connects, their layout is locked to English, whereas I need English and Czech. In language picker there are 3 options. "EN", Blank or Blank with lower index 2. All of those options work as English, when I enter layout settings and change the order of languages it 'magicaly' works as intended (both EN and CS), however when user logs out and logs back in its broken again.

```setxkbmap -query
testuser@rdp:~$ setxkbmap -query
rules:      base
model:      pc104
layout:     us
```

I've been trying to find any solution but none of them worked, for example:
Generating keymap 0405 with ```xrdp-genkeymap km-00000405``` and adding this to the xrdp_keyboard.ini under section default_rdp_layouts as ```rdp_layout_cs=0x00000405``` and under section default_layouts_map as ```rdp_layout_cs=cs```

After i restart the service and connect as test user same thing with the language picker happens, but now the options are Blank, Blank with lower index 2 and "CS". The problem here is, that the actual layout is not CS but RU (???)

```
testuser@rdp:~$ setxkbmap -query
rules:      base
model:      pc104
layout:     cs
```

In xrdp.ini i tried option ```xrdp.override_keylayout=0x00000405```, that actually did nothing. Neither does enabling autodetecting layout from client.

```setxkb -layout 'cs,us'``` works, but once again EN is english and CS is russian
Is there any way to be able to have EN and CS layout for every user that logs on to the RDP?

**Comment by matt335672** [comment]
When the client connects or reconnects, it sends some keyboard information to xrdp. It might help if you can post the contents of `/var/log/xrdp.log` after a client connection so we can see at least what the client is sending over.

The RDP protocol sends over keyboard information during the connection negotiation. Consequently it doesn't allow for keyboards to be changed mid-connection, or for multiple keyboards to work at the same time on the same connection. From your description it sounds like you may be trying to use two different keyboard layouts at once. If you aren't please can you clarify what you are trying to achieve.

Thanks.

**Comment by HottuDoku** [comment]
```
[20220809-16:06:54] [INFO ] Socket 12: connection accepted from *myIP*:63585
[20220809-16:06:54] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20220809-16:06:54] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20220809-16:06:54] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20220809-16:06:54] [INFO ] Connected client computer name: IT
[20220809-16:06:54] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20220809-16:06:54] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20220809-16:06:54] [WARN ] Client requested 32 bpp color depth, but the server configuration is limited to 16 bpp. Downgrading the color depth to 16 bits-per-pixel.
[20220809-16:06:55] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x00000405]
[20220809-16:06:55] [INFO ] overrode keyboard_type 0x04 with 0x04
[20220809-16:06:55] [INFO ] overrode keylayout 0x00000405 with 0x00000405
[20220809-16:06:55] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [cs] options []
[20220809-16:06:55] [INFO ] TLS connection established from *myIP*:63585 TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20220809-16:06:55] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20220809-16:06:55] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 10485760 MB cache entries 100
[20220809-16:06:55] [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
[20220809-16:06:55] [WARN ] xrdp_caps_process_codecs: unknown codec id 5
[20220809-16:06:55] [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
[20220809-16:06:55] [INFO ] Loading keymap file /etc/xrdp/km-00000405.ini
[20220809-16:06:55] [WARN ] local keymap file for 0x00000405 found and doesn't match built in keymap, using local keymap file
```
This should be it.

Yes, I am trying to use 2 layout at the same time, mainly Czech and secondary English. I would settle for only Czech at this point.

**Comment by matt335672** [comment]
Thanks.

The 0x405 certainly corresponds to a Czech keyboard according to the [MS list](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values).

The `xrdp-genkeymap` utility is somewhat sensitive to the X server it's run on. Personally I don't understand all the subtleties here, but in #2217 we were able to solve a generated keymap problem by running the utility on another X server. That's probably worth a go here.

**Comment by HottuDoku** [comment]
So, I jokingly tried to name the layout **CZ** instead of **CS** and now Czech layout works :facepalm: 

Is there really no way to be able to use 2 layouts and switch between them?

**Comment by matt335672** [comment]
My understanding is that a single keyboard per session is sort-of assumed by the RDP protocol.

During the initial client-server negotiations, the client sends the server a [TS_UD_CS_CORE PDU](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/00f1da4a-ee9c-421a-852f-c19f92343d73) which details the attached keyboard type. In normal operation, scancodes corresponding to that keyboard type are sent in [TS_KEYBOARD_EVENT](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/7acaec9f-c8a6-4ee9-87d6-d9b89cf56489) and [TS_FP_KEYBOARD_EVENT](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/089d362b-31eb-4a1a-b6fa-92fe61bb5dbf) PDUs.

The protocol allows for [TS_UNICODE_KEYBOARD_EVENT](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/551b9903-8fb9-4d00-b3ac-a187431efb86) and [TS_FP_UNICODE_KEYBOARD_EVENT](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/e7b13e98-d800-42bb-9a1d-6948537d2317) PDUs which could in theory support some of this functionality. We don't support them on the server-side however, and what the clients do with them is not something I have any knowledge of.

**Comment by HottuDoku** [comment]
Allright, I've made sort of a workaround.

Since our clients connect through RDP to ubuntu, script on login with command ```setxkbmap -layout 'cs,us' -option grp:ctrl_alt_toggle``` lets them locally switch layouts with ctrl alt combination.
Technicaly they are using one layout, but locally on the server they use 2.

Thanks for the help, post 2217 gave me a little idea for this. :)

**Comment by ndeffayet** [comment]
Is it possible to take the client keyboard layout and apply on server side without require some tunning on server side ?

**Comment by smokey2k** [comment]
Hi!
I solved this on Archlinux by the next:
I think the only problem is some keyboard layout not generated by default so no matter if they included in `/etc/xrdp/xrdp_keyboard.ini.`

on my system the crucial part of `/etc/xrdp/xrdp_keyboard.ini` looks like this:

```
[default]
keyboard_type=0
keyboard_subtype=0
rdp_layouts=default_rdp_layouts
layouts_map=default_layouts_map

[default_rdp_layouts]
rdp_layout_us=0x00000409
rdp_layout_us_dvorak=0x00010409
rdp_layout_us_dvp=0x19360409
rdp_layout_dk=0x00000406
rdp_layout_de=0x00000407
rdp_layout_es=0x0000040A
rdp_layout_fi=0x0000040B
rdp_layout_fr=0x0000040C
rdp_layout_hu=0x0000040E
rdp_layout_it=0x00000410
rdp_layout_jp=0x00000411
rdp_layout_jp=0xe0010411
rdp_layout_jp=0xe0200411
rdp_layout_jp=0xe0210411
rdp_layout_kr=0x00000412
rdp_layout_no=0x00000414
rdp_layout_pl=0x00000415
rdp_layout_br=0x00000416
rdp_layout_ru=0x00000419
rdp_layout_se=0x0000041D
rdp_layout_ch=0x00000807
rdp_layout_ch_fr=0x0000100C
rdp_layout_gb=0x00000809
rdp_layout_latam=0x0000080A
rdp_layout_be=0x00000813
rdp_layout_pt=0x00000816

[default_layouts_map]
rdp_layout_us=us
rdp_layout_us_dvorak=us(dvorak)
rdp_layout_us_dvp=us(dvp)
rdp_layout_dk=dk
rdp_layout_de=de
rdp_layout_es=es
rdp_layout_fi=fi
rdp_layout_fr=fr
rdp_layout_hu=hu
rdp_layout_it=it
rdp_layout_jp=jp
rdp_layout_kr=kr
rdp_layout_no=no
rdp_layout_pl=pl
rdp_layout_br=br(abnt2)
rdp_layout_ru=ru
rdp_layout_se=se
rdp_layout_ch=ch
rdp_layout_ch_fr=ch(fr)
rdp_layout_gb=gb
rdp_layout_latam=latam
rdp_layout_be=be
rdp_layout_pt=pt

```
Pick your desired keyboard layout code from here: [keymap-names.txt](https://sourceforge.net/p/rdesktop/code/1704/tree/rdesktop/trunk/doc/keymap-names.txt)

For me i picked hungarian layout which code is: `040E`

generate keymap for xrdp: 
```
xrdp-genkeymap km-0000040e.ini
sudo mv km-0000040e.ini /etc/xrdp
sudo chown root:root /etc/xrdp/km-0000040e.ini
```

insert this layout to `[default_rdp_layouts]` and `[default_layouts_map]` in `/etc/xrdp/xrdp_keyboard.ini`
```
[default_rdp_layouts]
rdp_layout_hu=0x0000040E

[default_layouts_map]
rdp_layout_hu=hu
```

then restart xrdp service

after this the xrdp server will automatically set the keyboard layout to your client keyboard layout at xrdp login screen.

**Comment by matt335672** [comment]
@smokey2k,

Thanks for this.

If you've got the time, can you raise an issue so we can add Hungarian to the supported list of keymaps for devel and v0.10.x?
