### ISSUE TITLE
Release xrdp v0.9.20

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#2346]
I'll release xrdp v0.9.20 from v0.9 branch within a month, a bug fix release.

**Comment by matt335672** [comment]
That sounds like a great idea!

**Comment by Neustradamus** [comment]
@metalefty: Nice!

**Comment by metalefty** [comment]
Will merge #2276 #2282 #2353 #2354 to v0.9 branch. 
@matt335672 Do you think there's anything worth to ship to v0.9? What about #2301 and #2310?

**Comment by matt335672** [comment]
I don't think #2301 and #2310 are worth adding at the moment, as they're both in place to enable further developments to take place. On their own, I don't think they add anything.

#2166 only benefits one user who is quite happy to build from source anyway, so I don't think that's worth merging. I've even added a patch for v0.9.19 to the thread.

In other words your list LGTM!

**Comment by metalefty** [comment]
Thanks for the confirmation!

**Comment by metalefty** [comment]
I've merged all things to be shipped to v0.9.20. I'll do some tests. After that, I'll bump version and update NEWS, and make a final release.
