### ISSUE TITLE
Can't Run the GUI App By Xrdp Remote Desktop

### ISSUE THREAD

**Issue by sixiaixixiya** [neutrinolabs/xrdp#2347]
Hello everyone! I want to use remote desktop to control  my Ubuntu host for co-simulation of Apollo+LGSVL. I can do anything except running the LGSVL simulator on the remote desktop. And I use gdb ./simulator to catch errors which shows that the libmonobdwgc-2.0.so may have some problems to be imported. Also the LGSVL simulator shows that "no protocol specified" and "core dumped" 
Needless to say, I really need your help! Thanks.
![gdb](https://user-images.githubusercontent.com/104459086/186621823-90810a89-7531-44ac-9d67-0e94bdf2faa2.png)

![svl_er](https://user-images.githubusercontent.com/104459086/186622529-5aedb23f-fd96-4c0b-9310-2c4a33b23cbf.png)

**Comment by seflerZ** [comment]
If you have no probleming running it on local session, the issue probably caused by some environment variables when using xrdp. Xrdp use Xorg, check whether your application works with.

**Comment by seflerZ** [comment]
If you have no probleming running it on local session, the issue probably caused by some environment variables (such as header path, lib path, etc.) when using xrdp. Xrdp use Xorg, check whether your application works with.

**Comment by seflerZ** [comment]
If you have no probleming running it on local session, the issue probably caused by some environment variables (such as header path, lib path, etc.) when using xrdp. Xrdp use Xorg, check whether your application works with.

**Comment by matt335672** [comment]
If you're getting "no protocol specified", this could be down to two things:-

1) The DISPLAY variable is not set, or wrong. It's possible you've got a script somewhere which is overriding the default provided by xrdp and setting it explicitly to :0 or something like that.
2) You're trying to use the GLX extension (i.e. 3D) with an X server which can't support it. Which backend are you using Xorg or Xvnc?

Although @seflerZ has a very good point above. In particular, check your PATH is correct.

Your libmonobdwgc library has either been built without debug information or has been stripped with the `strip` utility. You'll need to check your build scripts to sort that one out.
