### ISSUE TITLE
xrdp won't listen to more than one port.

### ISSUE THREAD

**Issue by arpaterson** [neutrinolabs/xrdp#2352]
If there are two `port=xxxx` entries in xrdp.ini, neither of them work.

expected behaviour is that xrdp accepts connections on both ports.
(eg. as in sshd_config)

**Comment by metalefty** [comment]
That is NOT expected way to specify multiple ports, so it works as intended.

You should read comment in xrdp.ini. It should guide you. You'll find `space between multiple occurrences`. See also `man xrdp.ini`.

This worked for me.

```
port=3389 3390
```

**Comment by arpaterson** [comment]
OK, thanks for clarifying.
I did read that line but didn't interpret that meaning.

I'm working on a minimized system, so haven't got `man` for now.

**Comment by arpaterson** [comment]
Tested, works.
