### ISSUE TITLE
[Fedora 21] xrdp-sesman.service failed

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#236]
Reported by X11RDP-RH-Matic user: metalefty/X11RDP-RH-Matic#13

I'm not sure why this is caused but X11RDP-RH-Matic just passes through xrdp's service files.
I think this issue needs to be fixed upstream. Any ideas?

**Comment by itamarjp** [comment]
this issue is related to selinux, a workarround is described here

https://bugzilla.redhat.com/show_bug.cgi?id=1177202

closing this bug.
