### ISSUE TITLE
Window not repainted if its title changed just before repaint

### ISSUE THREAD

**Issue by elfmz** [neutrinolabs/xrdp#2361]
Server: Ubuntu 22 with xrdp running 0.9.17
Client: Remmina or MSTSC
Test code for reproduction can be found here: https://pastecode.io/s/sxjwfya7 - it requires libwxgtk3.0-gtk3-dev  to be installed
Under local session or X-forwarding over SSH this program behaves in following way: each (any) keypress it repaints its window drawing alternately single line or multiple lines. Also it changes its titlebar string with random suffix  just before each repaint.
When running under xrdp many repaints are missing and window's content not changed after key press, however if after such missing repaint try to switch focus or hover mouse over test app's window - then it gets correct content.
However if comment out titlebar changes then problem stops to reproduce. Also it seems to stop reproduce if titlebar change moved after call to Update() (that actually forces window  repaint)

**Comment by matt335672** [comment]
Are you using the Xorg backend or the Xvnc backend?

If it's the Xorg backend you may be coming across neutrinolabs/xorgxrdp#171. This is fixed by neutrinolabs/xorgxrdp#186. which was released as part of [xorgxrdp v0.9.19](https://github.com/neutrinolabs/xorgxrdp/releases/tag/v0.9.19) recently.

**Comment by unxed** [comment]
Там пишут:

Вы используете бэкэнд Xorg или бэкэнд Xvnc?

Если Xorg, вы можете столкнуться с neutrinolabs/xorgxrdp#171, исправлено в neutrinolabs/xorgxrdp#186. который недавно был выпущен как часть xorgxrdp v0.9.19.

**Comment by elfmz** [comment]
yes its Xorg, regarding [#171](https://github.com/neutrinolabs/xorgxrdp/issues/171) - i will try to build recent version and check with it

**Comment by elfmz** [comment]
Unfortunatelly cannot start manually built xrdp on same system i did
```
sudo apt remove xrdp
git clone --recursive https://github.com/neutrinolabs/xorgxrdp
cd xorgxrdp
./bootstrap && ./configure && make -j5 && sudo make install
cd ..
git clone --recursive https://github.com/neutrinolabs/xrdp
cd xrdp
git checkout v0.9.19
./bootstrap && ./configure && make -j5 && sudo make install
sudo systemctl unmask xrdp-sesman
sudo systemctl unmask xrdp
sudo systemctl enable xrdp-sesman
sudo systemctl enable xrdp
sudo reboot
```

and after client connect i'm getting login prompt (as before) then just an empty blue screen for a long time then a message below.. anything missing?
![image](https://user-images.githubusercontent.com/20957349/189525456-85e4389b-a6fb-4778-b05c-7b3ae960975a.png)

**Comment by matt335672** [comment]
The X server isn't starting, or is failing most likely.

Check the following:-
1) Contents of `/var/log/xrdp-sesman.log`
2) That Xorg has the correct path specified in `/etc/xrdp/xrdp.ini`.
3) Contents of `~/.xorgxrdp.`0.log` if it's there.

**Comment by elfmz** [comment]
i already found that had to change allowed_users to anybody in /etc/X11/Xwrapper (from here https://wiki.archlinux.org/title/xrdp#Xorg_backend ) - IMHO its better to show this info somewhere in readme..
Now i have xrdp 0.9.19 (as on screenshot below) and problem still reproducible..
![image](https://user-images.githubusercontent.com/20957349/189525986-1f71d555-f57e-47d6-a0fb-8582da7c8c86.png)

**Comment by matt335672** [comment]
The Xwrapper stuff is not really correct. It's better to set a path to the unwrapped Xorg server, as you then don't need to modify the permissions for the console Xorg.

Might be worth checking the correct xorgxrdp version is loaded in `~/.xorgxrdp.10.log`. I've got something like the following for an old version:-

<pre>
[   506.840] (II) LoadModule: "xorgxrdp"
[   506.840] (II) Loading /usr/lib/xorg/modules/libxorgxrdp.so
[   506.883] (II) Module XORGXRDP: vendor="X.Org Foundation"
[   506.883]    compiled for 1.20.9, module version = <b>0.2.15</b>
[   506.883]    ABI class: X.Org Video Driver, version 24.1
</pre>

**Comment by elfmz** [comment]
i had ~/.xorgxrdp.10.log and ~/.xorgxrdp.11.log and also couple .log.old files near so i removed all that then rebooted and here is whats now in brand new .xorgxrdp.10.log :
```
/home/user$ grep 'module version' ./.xorgxrdp.*.log
[    34.334]    compiled for 1.21.1.3, module version = 1.0.0
[    34.335]    compiled for 1.21.1.3, module version = 1.0.0
[    34.336]    compiled for 1.21.1.3, module version = 1.0.0
[    34.339]    compiled for 1.21.1.3, module version = 0.9.80
[    34.342]    compiled for 1.21.1.3, module version = 0.9.80
[    34.344]    compiled for 1.21.1.3, module version = 0.9.80
[    34.346]    compiled for 1.21.1.3, module version = 0.9.80
```

also:
```
[    34.336] (II) LoadModule: "xorgxrdp"
[    34.337] (II) Loading /usr/lib/xorg/modules/libxorgxrdp.so
[    34.339] (II) Module XORGXRDP: vendor="X.Org Foundation"
[    34.339] 	compiled for 1.21.1.3, module version = 0.9.80
[    34.339] 	ABI class: X.Org Video Driver, version 25.2

```

**Comment by elfmz** [comment]
my version looks too high may be its because i've built xorgxrdp from the master branch.. anyway same issue as was reproduced with from Ubuntu's repository xrdp/xorgxrdp

**Comment by matt335672** [comment]
OK - thanks.

@jsorg71 - can you take a look at this? It's somewhat beyond my knowledge I'm afraid.

**Comment by elfmz** [comment]
Just FYI - i've changed param=Xorg to param=/usr/lib/xorg/Xorg in the /etc/xrdp/sesman.ini and then set allowed_users back to console and login works and same versions in .xorgxrdp.10.log and issue is also still there

**Comment by elfmz** [comment]
closing as it appeared that issue reproduced not only with xrdp, local reproduction also achieved, opened issue for xwayland as its most suspicious now: https://bugs.launchpad.net/ubuntu/+source/xwayland/+bug/2002456
