### ISSUE TITLE
will DRI_PRIME work with xrdp (Xorg) and dgpu?

### ISSUE THREAD

**Issue by zeusin** [neutrinolabs/xrdp#2370]
Hello guys,

I'm testing xrdp and came to my mind if using the offloading capacities of xorg will help xrdp with xorg server to have 3d hardware acceleration on applications running with DRI_PRIME=1

Can't find any related topic and I don't have an external gpu to try now.

**Comment by matt335672** [comment]
Hi @zeusin 

This is somewhat out of my area of expertise I'm afraid. I'll move it the the Q&A section where it will hopefully get more visibility.
