### ISSUE TITLE
Not working on recent debian (raspbian bullseye)

### ISSUE THREAD

**Issue by goofyseeker311** [neutrinolabs/xrdp#2371]
apt install xrdp works, but windows remote desktop login only gives a black screen, when credentials were saved and a login screen if not, but no active desktop even if desktop environment is present and working, by normal pi desktop install.

...
connecting to sesman ip 127.0.0.1 port 3350
sesman connect ok
sending login info to session manager, please wait...
login successful for display 10
started connecting
connection problem, giving up
some problem
....

...
root@raspberrypi:/# systemctl status xrdp
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-09-16 21:23:57 EEST; 30min ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 3583 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 3591 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 3592 (xrdp)
      Tasks: 1 (limit: 4164)
        CPU: 1.586s
     CGroup: /system.slice/xrdp.service
             └─3592 /usr/sbin/xrdp

Sep 16 21:46:41 raspberrypi xrdp[4434]: [ERROR] xrdp_iso_send: trans_write_copy_s failed
Sep 16 21:46:41 raspberrypi xrdp[4434]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Sep 16 21:48:09 raspberrypi xrdp[4462]: [INFO ] connection problem, giving up
Sep 16 21:48:09 raspberrypi xrdp[4462]: [INFO ] some problem
Sep 16 21:49:53 raspberrypi xrdp[4462]: [ERROR] xrdp_sec_recv: xrdp_mcs_recv failed
Sep 16 21:49:53 raspberrypi xrdp[4462]: [ERROR] xrdp_rdp_recv: xrdp_sec_recv failed
Sep 16 21:49:53 raspberrypi xrdp[4462]: [ERROR] libxrdp_process_data: xrdp_rdp_recv failed
Sep 16 21:49:53 raspberrypi xrdp[4462]: [ERROR] xrdp_process_data_in: xrdp_process_loop failed
Sep 16 21:49:53 raspberrypi xrdp[4462]: [ERROR] xrdp_iso_send: trans_write_copy_s failed
Sep 16 21:49:53 raspberrypi xrdp[4462]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
...

![xrdpproblems](https://user-images.githubusercontent.com/19920254/190710921-4d7f0c0f-4932-4475-812f-47474ec56ea6.png)

**Comment by matt335672** [comment]
@goofyseeker311 - have you seen #2060? This looks very similar, based on the information you've given us so far.

**Comment by goofyseeker311** [comment]
> @goofyseeker311 - have you seen #2060? This looks very similar, based on the information you've given us so far.

making a new user without any other adjustments worked directly, like was said in the #2060
the raspbian default primary sudo user (default account-name pi) cant do xrdp directly, same settings, different account.

the default isntall login account in raspbian seems to be special in some ways, something like that root-able cannot login with xrdp, security prevention from the developer side. ie, Xwindowsystem refusing connection because root/sudo-rights.

**Comment by matt335672** [comment]
The reasons for all of this, together with known remedies are in #2060. In particular, see [this post](/neutrinolabs/xrdp/issues/2060#issuecomment-979958020).

**Comment by cartpauj** [comment]
`sudo deluser pi render` worked for me.
