### ISSUE TITLE
Can't listen on ipv6 with alpine linux

### ISSUE THREAD

**Issue by pdropi** [neutrinolabs/xrdp#2378]
Hi!
If i use port=tcp6://:3389 in /etc/xrdp/xrdp.ini xrdp do not start:
 * Starting xrdp ...
 * start-stop-daemon: failed to start `/usr/sbin/xrdp'
 * Failed to start xrdp                                                                                                                        [ !! ]
 * ERROR: xrdp failed to start

```
[20220920-23:43:29] [INFO ] listening to port 3389 on ::1
[20220920-23:43:29] [ERROR] trans_listen_address failed
[20220920-23:43:29] [CORE ] Failed to start xrdp daemon, possibly address already in use.
```

```
 xrdp -v
xrdp 0.9.18.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --prefix=/usr
      --disable-static
      --sysconfdir=/etc
      --localstatedir=/var
      --sbindir=/usr/sbin
      --enable-fuse
      --enable-pam
      --enable-tjpeg
      CC=gcc
      CFLAGS=-Os -fomit-frame-pointer
      LDFLAGS=-Wl,--as-needed,-O1,--sort-common
      CPPFLAGS=-Os -fomit-frame-pointer

  Compiled with OpenSSL 3.0.5 5 Jul 2022
```

**Comment by metalefty** [comment]
It looks your xrdp is not compiled with IPv6 support. You'll see `--enable-ipv6` in `xrdp -v`  if IPv6 support is enabled.

**Comment by matt335672** [comment]
No further info - closing.

**Comment by sijanec** [comment]
Off-topic, but why is IPv6 not enabled by default?

**Comment by matt335672** [comment]
@sijanec - it needs more work internally to move to newer interfaces before we can do this.

The OP was using Alpine Linux.  This now adds the flag as part of the build process. Commit is [here](https://git.alpinelinux.org/aports/commit/community/xrdp/APKBUILD?id=7ced5f1fec69b6282f407e2039e84cfa00f9b4f2)

**Comment by sijanec** [comment]
Yeah, tnx, I also added the build flag in the gentoo overlay that I
use for xrdp, together with the latest version.

https://github.com/ananace/overlay/pull/24

2023-07-31 15:23 GMT+02.00, matt335672 ***@***.***>:
