### ISSUE TITLE
Nvidia and AMD libGL issues

### ISSUE THREAD

**Issue by fang64** [neutrinolabs/xrdp#238]
I have encountered an issue with xrdp and the Xorg driver usage. When ldconfig is modified by a vendor like Nvidia or AMD to utilize it's libGL Xorg will fail to start with GLX enabled. The only workaround is to launch Xorg with "LD_PRELOAD="/usr/lib64/libGL.so" /usr/bin/Xorg" instead of just calling it normally since it needs an additional environment variable. I did try and add an environment option but it seems this isn't something that can be done. I noticed that the function "g_execvp("/usr/bin/Xorg", pp1);" is set to a static path meaning I am unable to setup any environment variables at least at first glance. I noticed there is the ability to setup environment variables using the function "g_setenv" however there isn't a configuration for pre-execution for that component.

**Comment by jsorg71** [comment]
Yes, we need a way to fix this issue although the real problem is the way Nvidia and ATI install the drivers.
I was able to get openGL working with the Nvidia driver by adding a .conf to /etc/ld.conf.d.
I think after you get Xorg loading with the XGL extension, the apps will still have a problem.
Adding the .conf fixes both.  I'll document how I did this, maybe we can come up with the best solution.

If you want to use NVidia's opengl on the console and software mesa opengl in the xrdp session, we don't have a way to do that yet.

**Comment by fang64** [comment]
jsorg71, I tried removing the nvidia path configuration in /etc/ld.so.conf.d/nvidia-lib64.conf and it fixed xrdp but broke the real console of the machine. I would like to know how you got it working, thanks.

**Comment by jsorg71** [comment]
@fang64 , It broke my console too but I didn't care because all access was through xrdp.
Maybe we can use LD_PRELOAD as you tried but I'm no expert with LD_PRELOAD.
Long term we should use the NVidia, ATI, and Intel drivers from xrdp but we need a workaround until then.

**Comment by fang64** [comment]
Well in my case I assume mesa-libGL is available in some form, and set LD_PRELOAD="/path/to/libgl.so" to get around this problem. LD_LIBRARY_PATH is another option which changes the order of which paths get called. As it stands it is possible to use the GPU, but you will have to do xorg.conf switching and get clever with how those are defined. Currently you point to one file, I could reconfigure that on a per host basis using our configuration management. That's more of a kludge, using mesa libGL because it's always there is more advantageous. However I don't know how many using xrdp have gotten third party libGL working and are using it. So I definitely wouldn't make this the default, but at least offer the option to set the environment variable or capability to, since you can leave LD_PRELOAD blank and linux loader, "ld.linux.so" will not do anything to change library order.

**Comment by fang64** [comment]
After further testing it seems LD_LIBRARY_PATH is the best workaround it's sufficient enough to launch xrdp with LD_LIBRARY_PATH set to "/usr/lib64" which will load "/usr/lib64/libGL.so.1" instead of "/usr/lib64/nvidia/libGL.so.1" and avoids tampering with ld.conf.so.d files to achieve the effect. I was able to modify the service start scripts and it was then able to run. I would like to see that as a variable to pass into the launching of Xorg I suspect this doesn't apply to the X11-rdp Xorg tree since it doesn't seem to use those paths.

**Comment by fang64** [comment]
@jsorg71, Another option is to update the Xorg tree for X11 RDP, so that it has gallium. This would eliminate the need for me to fight the system installed Xorg and allow Gnome 3.8+ to work since gallium can emulate many of the fancier GL/GLX calls that gnome requires to function. That would satisfy my requirements as well, at least at the moment it's more of an issue that Gnome 3.8+ is on functional remote with Xrdp using the Xorg Xrdp "drivers."

**Comment by fang64** [comment]
@moobyfr FYI, for reference to the other issue with Xorg-rdp

**Comment by fang64** [comment]
@jsorg71 I believe I found something viable that wont touch LD_LIBRARY_PATH or LD_PRELOAD that's standard. Allow LIBGL_DRIVERS_PATH to be set and passed through, since that actually indicates which Xorg libgl drivers are to be used. I'm still experimenting on my end here on a way to get this working sanely. Since I can't use VNC sessions either at the moment.

**Comment by jsorg71** [comment]
@fang64 That is great, I'll try this next week.
You can add this environment variable(or any EV) in sesman.ini you know.

**Comment by speidy** [comment]
that's great ;)
בתאריך יום ה׳, 17 בספט׳ 2015 ב-9:19 מאת jsorg71 <notifications@github.com>:

**Comment by fang64** [comment]
@jsorg71 Ah I wasn't aware of this I was a little confused looking through xrdp code trying to figure out how to pass in a variable like that. I did run into a snag with my testing seems when Nvidia drivers are installed it's even impossible to run applications over X11 Forwarding because of the NvGLX calls from the host containing the graphics card at least from my end.

**Comment by fang64** [comment]
@jsorg71 @speidy it appears Nvidia has something in the works that will fix this problem later down the road, https://github.com/NVIDIA/libglvnd if you are aware of it. It's a vendor-neutral GL/GLX interface I'm going to close this for now since it seems my attempts to work around this were for not, it always results in a problem for the console or xrdp, instead of solving the problem on both.
