### ISSUE TITLE
Failed to enable unit, unit /etc/systemd/system/xrdp.service is masked.

### ISSUE THREAD

**Issue by dunlex** [neutrinolabs/xrdp#2381]
Hello, I get this error after the update

 **update-rc.d xrdp enable**
Failed to enable unit, unit /etc/systemd/system/xrdp.service is masked.

**Comment by akarl10** [comment]
you could try to unmask xrdp with `systemctl unmask xrdp.service`, but usually a service does not get masked "randomly", something must have done this

**Comment by matt335672** [comment]
@dunlex - you're getting systemd errors on a system where you're using `update-rc.d`

What is your operating system exactly?

**Comment by matt335672** [comment]
No further info - closing.
