### ISSUE TITLE
client used vnc-viewer tool,  connect xrdp proxy to remote vnc server.  support it?

### ISSUE THREAD

**Issue by ygm521** [neutrinolabs/xrdp#2387]

**Comment by matt335672** [comment]
@ygm521 - I don't understand what you are asking.

Can you please add some more detail as to exactly what problem you are encountering with xrdp?

Thanks.

**Comment by ygm521** [comment]
- client used vnc-viewer tool,  connect xrdp proxy to remote vnc server.  support it?
 - The client uses the rdp protocol to access. The xrdp can support the rdp or vnc protocol connect real server?

**Comment by matt335672** [comment]
You can use xrdp to connect to an existing VNC server.

xrdp only supports connections from RDP clients. So this is supported:-

```
+------------+           +--------+           +------------+
| RDP Client | --------> |  xrdp  | --------> | VNC server |
+------------+           +--------+           +------------+
```

Is that what you want to do?

**Comment by ygm521** [comment]
RDP Client use vnc-viewer tool, is vnc protocol。

**Comment by matt335672** [comment]
You can't use a VNC protocol client to talk to xrdp. You have to use RDP protocol.

If you have to use a VNC client, you will need to find a VNC proxy to do this job.

**Comment by ygm521** [comment]
there have different servers：1，VNC server；  2，RDP server； 
start an xrdp program, how to configure. The client (rdp) can both access  1，VNC server；OR   2，RDP server；

```
+------------+           +--------+           +------------+
| RDP Client | --------> |  xrdp  | --------> | VNC server |
+------------+           +--------+           +------------+
                            |             
                            |      +------------+
                            |-------> | RDP server |
			           +------------+
```

@matt335672 ??

**Comment by matt335672** [comment]
For this scenario:-

```
+------------+           +--------+           +------------+
| RDP Client | --------> |  xrdp  | --------> | RDP server |
+------------+           +--------+           +------------+
```

you'll need to build the NeutrinoRDP proxy module. This is quite complicated. The instructions are [on the Wiki](/neutrinolabs/xrdp/wiki/NeutrinoRDP-proxy-module-for-xrdp). I'm going to leave that for now because unless you're comfortable with building xrdp from source it probably isn't an option.

For this scenario:-

```
+------------+           +--------+           +------------+
| RDP Client | --------> |  xrdp  | --------> | VNC server |
+------------+           +--------+           +------------+
```

I'll make some assumptions.
1. The VNC server is reachable from the xrdp server over the LAN. The hostname is `myvnc.local`.
2. The VNC service you wish to talk to on `myvnc.local` is listening on TCP port 5910.
3. The VNC server is using a password file created with `vncpasswd(1)` and you wish to use the same password on the xrdp login screen.

You'll need to add this section to `/etc/xrdp/xrdp.ini`:-

```
[myvnc]
name=myvnc
lib=libvnc.so
ip=myvnc.local
port=5910
username=na
password=ask
```

When you get to the xrdp login screen and select the `myvnc` session you'll get a login box like this:-

![image](https://user-images.githubusercontent.com/30179339/196648392-b0da8f9d-bcc9-427e-b5f8-7429a7a63119.png)

Put your VNC password in the password box and you'll connect to the VNC service on `myvnc.local`.

**Comment by ygm521** [comment]
@matt335672 how to configure. The client (rdp) can  access VNC server and RDP server at the same time。such lili visited xrdp proxy to rdp server，Lucy visited xrdp proxy to vnc server。

**Comment by matt335672** [comment]
Are you in a position to build the NeutrinoRDP proxy module?

If so, you just have two sections set up in your xrdp.ini file, one for the VNC server and one for the RDP server.

**Comment by ygm521** [comment]
Did you do the test?  When the client requests xrdp through the rdp protocol，How does xrdp know to request the real server with rdp or vnc protocol? I see the code it does not support.

**Comment by matt335672** [comment]
You choose a 'Session' on the front end. That in turn loads the corresponding section in `xrdp.ini`. The `lib=` line tells it how to connect to the back end.

**Comment by ygm521** [comment]
@matt335672 i do not know what is your meaning. Suppose there are two users lili and lucy, what does xrdp decides whether to load libxrdp.so or libvnc.so？by username? Because both lili and lucy are accessed through the rdp protocol, xrdp cannot distinguish which so is to loaded. 
So can you clearly describe whether xrdp is supported? I tested and verified that xrdp can only support real servers as rdp_server or vnc_server, not both rdp_server and vnc_server.

**Comment by matt335672** [comment]
Have you connected to the front end where you get the login screen [above](https://github.com/neutrinolabs/xrdp/issues/2387#issuecomment-1283679695)?

From there, lili can access one session, and lucy can access the other.

**Comment by ygm521** [comment]
xrdp proxy vnc server and rdp server at the same time, can you give a configuration reference?
 Which account does the client use to access xrdp? thanks。

**Comment by matt335672** [comment]
@ygm521 - se my comment [above](https://github.com/neutrinolabs/xrdp/issues/2387#issuecomment-1283679695)

To talk to the RDP server, you'll need to build the NeutrinoRDP module as outlined in that comment. Are you in a position to do that?

I don't understand your question about the account. Can you add a bit more detail please?

**Comment by ygm521** [comment]
@matt335672 

![image](https://user-images.githubusercontent.com/7271089/197369480-5e078297-aec8-4951-8831-8cb9d74b6b16.png)

lili want to access to vnc server， lucy want to access to rdp server，at the same time，xrdp as proxy。

how config xrdp.ini can support it？ can you give an example for xrdp.ini，thanks!

**Comment by matt335672** [comment]
@ygm521 - **to talk to the RDP server, you'll need to build the NeutrinoRDP module as outlined in the above comment**. Are you in a position to do that?

**Comment by TOMATO-ONE** [comment]
Hello, @ygm521 

I am running xrdp as an RDP Proxy.
I may be able to help you.

Assuming you are using Windows `mstsc.exe` as your RDP Client.

First of all, as @matt335672  pointed out, to be able to use RDP Proxy with xrdp, you need to build xrdp with `--enable-neutrinordp` added in the configure option.
For that you also need to build and install [NeutrinoRDP](https://github.com/neutrinolabs/NeutrinoRDP).
Please refer to my [github repository](https://github.com/TOMATO-ONE/xrdp-proxy) for xrdp binary packages with RDP Proxy enabled.

Next, as for the xrdp.ini sample you are looking for, I think you can basically use the `[vnc-any]` and `[neutrinordp-any]` sections in the standard [xrd.ini.in](https://github.com/neutrinolabs/xrdp/blob/3fe20d1856e8654fed4244272e33120bf4e482ae/xrdp/xrdp.ini.in#L260-L285).
In this configuration, authentication is performed on the target vnc server or RDP server side. Authentication by xrdp is not performed.

From what you have said so far, you want authentication on the xrdp side?

If you want xrdp to authenticate as well, please add the following parameters to the [vnc-any] and [neutrinordp-any] sessions in xrdp.ini, respectively
```
pamusername=ask
pampassword=ask
pamsessionmng=127.0.0.1
```
This will perform pam authentication on the server OS running xrdp.

Best regards.

**Comment by ygm521** [comment]
@TOMATO-ONE thank you very much!   using Windows mstsc.exe as RDP Client，but i don't want input serip:serport。

**Comment by TOMATO-ONE** [comment]
@ygm521 
I am not sure about serip:serport.
Are you referring to the IP Address and Port number of the VNC Server/RDP Server?

Assuming that is what it means.

You can set the only value specified by the administrator by deleting the `ask` character in the parameter in the xrdp.ini section.
The input box on the login screen will no longer appear and the IP address and port number of the RDP Server /VNC Server can be hidden from view.

For example, set the following.
```ini
[vnc-any]
ip=198.51.100.1
port=5900

[neutrinordp-any]
ip=198.51.100.2
port=3389
```

**Comment by matt335672** [comment]
No further info - closing.
