### ISSUE TITLE
The mouse drops frames and does not follow

### ISSUE THREAD

**Issue by hzhwyh0116** [neutrinolabs/xrdp#2389]
The mouse drops frames and does not follow
I tried to use KED, XFCE and GNOME graphic frameworks, but they all had the same problem
Try modifying xrdp The configuration problem in init still exists, for example:
`max_bpp=128`
`new_cursors=false`

https://user-images.githubusercontent.com/89765365/195044048-0d6cdeed-9364-44f4-8d72-971605c78362.mov

**Comment by matt335672** [comment]
@hzhfit2cloud - are you using the VNC backend?

If you are, which package is providing the Xvnc server you are using?

**Comment by hzhwyh0116** [comment]
The server I connected with windows mstsc

**Comment by hzhwyh0116** [comment]
![xvnc](https://user-images.githubusercontent.com/89765365/195808733-dc7fce96-85c0-47c7-a14b-e6d4f1ce71df.png)

**Comment by matt335672** [comment]
A few questions for you:-
- Can you post the contents of your `[sesman-Xvnc]` section in `/etc/xrdp/sesman.ini` ?
- What do you get for the command `rpm -qf $(which Xvnc)`
- What sort of network links do you have between the client and the xrdp machine?

**Comment by matt335672** [comment]
No further info from OP - closing
