### ISSUE TITLE
os_calls.c:2202:30: error: 'S_ISVTX' undeclared (first use in this function)

### ISSUE THREAD

**Issue by blatwo** [neutrinolabs/xrdp#2390]
Hi, I encounter this error when making.
gcc 4.8.5, Centos7.9_64

[root@S01 xrdp]# make CFLAGS=-std=c99
make  all-recursive
make[1]: Entering directory `/root/xrdp'
Making all in common
make[2]: Entering directory `/root/xrdp/common'
  CC       os_calls.lo
In file included from os_calls.c:53:0:
/usr/include/sys/ipc.h:24:3: warning: #warning "Files using this header must be compiled with _SVID_SOURCE or _XOPEN_SOURCE" [-Wcpp]
 # warning "Files using this header must be compiled with _SVID_SOURCE or _XOPEN_SOURCE"
   ^
os_calls.c: In function 'g_tcp_bind_address':
os_calls.c:1262:5: warning: implicit declaration of function 'inet_aton' [-Wimplicit-function-declaration]
     if (inet_aton(address, &s.sin_addr) < 0)
     ^
os_calls.c: In function 'g_sleep':
os_calls.c:1391:5: warning: implicit declaration of function 'usleep' [-Wimplicit-function-declaration]
     usleep(msecs * 1000);
     ^
os_calls.c: In function 'hex_to_mode_t':
os_calls.c:2202:30: error: 'S_ISVTX' undeclared (first use in this function)
     mode |= (hex & 0x1000) ? S_ISVTX : 0;
                              ^
os_calls.c:2202:30: note: each undeclared identifier is reported only once for each function it appears in
os_calls.c: In function 'mode_t_to_hex':
os_calls.c:2226:20: error: 'S_ISVTX' undeclared (first use in this function)
     hex |= (mode & S_ISVTX) ?  0x1000 : 0;
                    ^
os_calls.c: In function 'g_initgroups':
os_calls.c:2803:9: warning: implicit declaration of function 'initgroups' [-Wimplicit-function-declaration]
         error = initgroups(username, gid);
         ^
os_calls.c: In function 'g_getlogin':
os_calls.c:2866:5: warning: implicit declaration of function 'getlogin_r' [-Wimplicit-function-declaration]
     return getlogin_r(name, len);
     ^
os_calls.c: In function 'g_setenv':
os_calls.c:2999:5: warning: implicit declaration of function 'setenv' [-Wimplicit-function-declaration]
     return setenv(name, value, rewrite);
     ^
os_calls.c: In function 'g_sigterm':
os_calls.c:3042:5: warning: implicit declaration of function 'kill' [-Wimplicit-function-declaration]
     return kill(pid, SIGTERM);
     ^
os_calls.c: In function 'g_gethostname':
os_calls.c:3393:5: warning: implicit declaration of function 'gethostname' [-Wimplicit-function-declaration]
     return gethostname(name, len);
     ^
make[2]: *** [os_calls.lo] Error 1
make[2]: Leaving directory `/root/xrdp/common'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/xrdp'
make: *** [all] Error 2

**Comment by matt335672** [comment]
Using `-std=c99` will restrict the features available to the compiler, so a lot of POSIX or BSD calls which xrdp relies on will not be available. We don't normally use this switch.

Since you're on glibc 2.17 (on CentOS 7), use this command instead:-

```
make CFLAGS="-std=c99 -D_XOPEN_SOURCE=500 -D_BSD_SOURCE
```

I believe for glibc 2.19 and later, you can use `_DEFAULT_SOURCE` instead of the `_XOPEN_SOURCE` and `_BSD_SOURCE` definitions. See `feature_test_macros(7)` for more information.

See also #2156 which relates to building on CentOS 7.
