### ISSUE TITLE
very slow when window is moving

### ISSUE THREAD

**Issue by ghost** [neutrinolabs/xrdp#2393]
### system summary
> host_os: ubuntu 22.04    
> dde: xfce 4    
> gpu: intel hd 2500    
> xrdp: 0.9.17    
> client_os: win11

### problem
screen is very laggy when moving window, even window compositor was disabled.    
![img](https://i.postimg.cc/PJqc7pXr/image.gif)
client side, mstsc was selected ```LAN mode``` to enable RFX protocol.
![img](https://i.postimg.cc/BbwyfSb5/b1.png)

### but
3d application is works fine without lag, but moving the window is still laggy.
![img](https://i.postimg.cc/WbCK91QT/2.gif)

```
root@ubuntu:~# xrdp --version
xrdp 0.9.17
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-asBei3/xrdp-0.9.17=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -Wno-error=deprecated-declarations
      PKG_CONFIG_PATH=/build/xrdp-asBei3/xrdp-0.9.17/pkgconfig

  Compiled with OpenSSL 3.0.2 15 Mar 2022
```

**Comment by whitegerry** [comment]
Also laggy when selecting the text from the browser. Maybe the lag was due to the only 24 fps.

**Comment by matt335672** [comment]
Depending on your CPU and/or network that might be the best you can get.

Try running a `top` in an ssh session while you're moving a window gently. That might show you any process(es) which are CPU bound, and it's easy to do.

**Comment by matt335672** [comment]
@whitegerry - did you look into CPU usage as above?

**Comment by whitegerry** [comment]
> @whitegerry - did you look into CPU usage as above?

The issue happens when gpu hardware acceleration enabled. It will be smooth if there is no gpu hardware acceleration enabled for xrdp session.

**Comment by matt335672** [comment]
Interesting.

How did you enable/disable the GPU hardware acceleration in your xrdp session?

**Comment by whitegerry** [comment]
I installed xorgxrdp-glamor to enable the GPU hw acceleration. 
Window animation will be smoother if the composer is disabled.
