### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by jhelfman** [neutrinolabs/xrdp#240]
Documentation on installing on Fedora should note to include:

yum install wget bzip2 xterm

and 

open rdp ports for firewall 3389 and 3390

Ref: http://www.xrdp.org/index.php?option=com_content&view=article&id=33:building-xrdp-in-fedora-19&catid=2:documents&Itemid=7

**Comment by itamarjp** [comment]
yum -y install xrdp should work on fedora :-)
