### ISSUE TITLE
Connection issue across networks

### ISSUE THREAD

**Issue by pludi** [neutrinolabs/xrdp#2409]
We've set up xrdp and can't connect from a different subnet, the server apparently isn't even answering with an `ACK` packet.

- OS: Rocky Linux 9
- xrdp Version: xrdp-0.9.20-1.el9.x86_64

- Source net: `10.220.0.0/22`
- Destination: `10.210.86.0/24`
- Host Firewall: none (IPTables is set to `ACCEPT` on all chains)
- Firewall between subnets is set to allow all traffic
- Connections from `localhost` and other machines in the same subnet work as expected (tested via SSH Port forwarding)

`tcpdump` on the xrdp host shows `SYN` packets arriving but no `ACK` packets leaving:
```
# tcpdump -i eth0 -s0 -nn -v 'tcp port 3389'
dropped privs to tcpdump
tcpdump: listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
12:45:08.809969 IP (tos 0x0, ttl 62, id 17655, offset 0, flags [DF], proto TCP (6), length 60)
    10.220.1.35.52512 > 10.210.86.11.3389: Flags [S], cksum 0x5533 (correct), seq 1659964691, win 64954, options [mss 1380,sackOK,TS val 1177090043 ecr 0,nop,wscale 7], length 0
12:45:09.292960 IP (tos 0x0, ttl 62, id 44995, offset 0, flags [DF], proto TCP (6), length 60)
    10.220.1.35.52516 > 10.210.86.11.3389: Flags [S], cksum 0xa1b6 (correct), seq 4287701512, win 64954, options [mss 1380,sackOK,TS val 1177090526 ecr 0,nop,wscale 7], length 0
```

**Comment by matt335672** [comment]
There's nothing at an application level which can prevent a response to the SYN packet.

If all your firewalls are down, the SYN-ACK (or RST) is going out on a different interface, or the kernel doesn't know where to send it.

Do you have other interfaces active on the machine? Your tcpdump is interface specific. You can use `-i any` to listen on all interfaces.

On the host, try `ip route get 10.220.1.35` to check that there's a route back to the originating subnet. You may not have a default router configured.

**Comment by pludi** [comment]
No other interfaces besides `eth0` and `lo`.

`tcpdump` using `-i any` gives the same result:
```
# tcpdump -i any -s0 -nn -v 'tcp port 3389'
tcpdump: data link type LINUX_SLL2
dropped privs to tcpdump
tcpdump: listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
21:14:28.850139 eth0  In  IP (tos 0x0, ttl 62, id 41187, offset 0, flags [DF], proto TCP (6), length 60)
    10.220.1.35.37744 > 10.210.86.11.3389: Flags [S], cksum 0x65ea (correct), seq 902136867, win 64954, options [mss 1380,sackOK,TS val 3774561327 ecr 0,nop,wscale 7], length 0
21:14:29.210725 eth0  In  IP (tos 0x0, ttl 62, id 46898, offset 0, flags [DF], proto TCP (6), length 60)
    10.220.1.35.37752 > 10.210.86.11.3389: Flags [S], cksum 0x9634 (correct), seq 605709331, win 64954, options [mss 1380,sackOK,TS val 3774561688 ecr 0,nop,wscale 7], length 0
```

`ip route get` tells me that there is a route back, anything else would have surprised me as SSH connections are possible without issues.

Attaching an `strace` to the process shows that apparently the `SYN` packets aren't even forwarded from the kernel to the process, so I'm closing this as the issue has to be somewhere else.

**Comment by neimanpinchas** [comment]
What was the solution, I am also having the exact same issue with xrdp working fine on local subnet (same layer 2 network), but not working from other subnet which happen to be routable to the xrdp server network (over layer 3).

Seems like xrdp is using its own IP address for some logic that coincidentali only works with local IP address.

**Comment by matt335672** [comment]
@neimanpinchas - sounds like a classic missing route.

Check the server is routable from the client and the client is routable from the server. You need both directions for a connection to be established.

**Comment by neimanpinchas** [comment]
Thats correct, the client router is masquerding when going into the server network so the server sees the gateway ip not the actual machine IP.
I did this to ease with routing and not having to intriduce additional subnets to all machines (That have a default GW on a diffrent NIC than the shared network)
For SSH (or any other tcp client/server) this is not an issue, and my current workaround is to open XRDP torough an SSH tunnel, I wonder why XRDP need to open a new connection on the machine the client is running on? where is this documented?

**Comment by matt335672** [comment]
xrdp doesn't do that - it just uses the client connection as you'd expect. Your setup should be fine as you describe it.

Suggestions:-
- Run the usual tools (nmap/traceroute) from the client to get more info as to where the routing is breaking down.
- Run wireshark / tcpdump on the server to check you're getting the initial TCP SYN/ACK on the expected port with the expected source address.
