### ISSUE TITLE
Clipboard suddenly stopped working

### ISSUE THREAD

**Issue by Soukyuu** [neutrinolabs/xrdp#241]
I'm using xrdp april 27 git snapshot with arch linux x64. Connection is via sessman-Xvnc from a win8.1 host using the RDP protocol (windows remote desktop client or mRemoteNG) 

Everything was working perfectly until today, now suddenly the complete clipboard redirection is dead. I tried restarting the remote machine, but that didn't change anything.

**Comment by jsorg71** [comment]
There is several debug techniques depending on your technical level.
One easy one is strace on xrdp-chansrv.
xrdp-chansrv handles all the clipboard trafiic.
strace -p pid-of-chansrv

Another is run xrdp and xrdp-sesman in consoles and watch the output.

**Comment by Soukyuu** [comment]
strace -p 543 (as root or user) gives me 
```
strace: attach: ptrace(PTRACE_ATTACH,...): Operation not permitted
```
The interesting thing is that ksysguard lists xrdp-chanserv as a zombie process.

I thought that maybe recompiling after system update would help, and checked out from git agian, but now I'm stuck with
```
VNC error - only supporting 8, 15, 16 and 24bpp connections
```
My connection is using 24bpp, and I've also tried all of the other modes, still same error message.

**Comment by metalefty** [comment]
Test with the latest xrdp version. If the issue still occurs, I'll reopen this.
