### ISSUE TITLE
Lubuntu: Missing icons in file manager

### ISSUE THREAD

**Issue by liyimeng** [neutrinolabs/xrdp#2411]
I run ubuntu LTS 22.04  with lxde desktop after login in, all file icons are missing in file manager  as show in the picture bellow 

<img width="747" alt="Screenshot 2022-11-05 at 22 07 10" src="https://user-images.githubusercontent.com/3155688/200141482-4ec9f97b-e247-407b-9447-c4e4dff2aa66.png">

what is going wrong?

**Comment by matt335672** [comment]
@liyimeng - are the icons visible on the computer console if you log in on that?

**Comment by liyimeng** [comment]
Yes, it shows when login vnc or nomachine

**Comment by matt335672** [comment]
Just tried this myself on 22.04, with:-

```
sudo apt install lxde
ln -s `which startlxde` $HOME/.xsession
```

Seems OK here:-

![image](https://user-images.githubusercontent.com/30179339/200547342-db46b8a8-99a6-4d26-a635-027ff6a4f0ce.png)

A couple of questions for you:-
- Have you got `lxde-icon-theme` installed?
- Are there any errors in `~/.xsession-errors`?

Also, try running `pcmanfm` in a terminal with these commands to see if you get any errors generated:-
```
pkill pcmanfm
pcmanfm
```

**Comment by liyimeng** [comment]
- No, I did not. But install it make no difference.

- Same error like this
~/.xsession-errors
```
Xsession: X session started for liyi at tis  8 nov 2022 13:13:26 CET
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
dbus-update-activation-environment: setting DISPLAY=:10.0
localuser:liyi being added to access control list
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting USER=liyi
dbus-update-activation-environment: setting LC_TIME=sv_SE.UTF-8
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting HOME=/home/liyi
dbus-update-activation-environment: setting LC_MONETARY=sv_SE.UTF-8
dbus-update-activation-environment: setting XRDP_PULSE_SINK_SOCKET=xrdp_chansrv_audio_out_socket_10
dbus-update-activation-environment: setting XRDP_PULSE_SOURCE_SOCKET=xrdp_chansrv_audio_in_socket_10
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
dbus-update-activation-environment: setting LIBVIRT_DEFAULT_URI=qemu:///system
dbus-update-activation-environment: setting PULSE_SCRIPT=/etc/xrdp/pulse/default.pa
dbus-update-activation-environment: setting LOGNAME=liyi
dbus-update-activation-environment: setting XDG_SESSION_CLASS=user
dbus-update-activation-environment: setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin
dbus-update-activation-environment: setting XRDP_SOCKET_PATH=/run/xrdp/sockdir
dbus-update-activation-environment: setting LC_ADDRESS=sv_SE.UTF-8
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1001
dbus-update-activation-environment: setting DISPLAY=:10.0
dbus-update-activation-environment: setting LANG=en_US.UTF-8
dbus-update-activation-environment: setting LC_TELEPHONE=sv_SE.UTF-8
dbus-update-activation-environment: setting UID=1001
dbus-update-activation-environment: setting SHELL=/bin/bash
dbus-update-activation-environment: setting LC_NAME=sv_SE.UTF-8
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting XRDP_SESSION=1
dbus-update-activation-environment: setting LC_MEASUREMENT=sv_SE.UTF-8
dbus-update-activation-environment: setting LC_IDENTIFICATION=sv_SE.UTF-8
dbus-update-activation-environment: setting GPG_AGENT_INFO=/run/user/1001/gnupg/S.gpg-agent:0:1
dbus-update-activation-environment: setting PWD=/home/liyi
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
dbus-update-activation-environment: setting LC_NUMERIC=sv_SE.UTF-8
dbus-update-activation-environment: setting LC_PAPER=sv_SE.UTF-8
[load.applyBestSettings()] Finished
New PolkitAgentListener  0x564ccfac2400
Adding new listener  PolkitQt1::Agent::Listener(0x7ffe9c289ed0) for  0x564ccfac2400
lxqt-config-monitor: Applying current settings...
Output:  "rdp0"
lxqt-config-monitor: Current settings can not be applied.
lxqt-config-monitor: Searching in saved settings...
Output:  "rdp0"
Output:  "rdp0"
lxqt-config-monitor: No saved settings has been found
Output:  "rdp0"
lxqt-config-monitor: Extended mode has been applied
isPrimaryInstance
systemd: "CanHibernate" = "challenge"
dbus-daemon[81226]: Activating service name='org.a11y.atspi.Registry' requested by ':1.6' (uid=1001 pid=81247 comm="/usr/bin/nm-applet " label="unconfined")

(nm-applet:81247): nm-applet-WARNING **: 13:13:27.041: failed to load icon "nm-device-wired": Icon 'nm-device-wired' not present in theme Yaru
dbus-daemon[81226]: Successfully activated service 'org.a11y.atspi.Registry'
SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
systemd: "CanSuspend" = "challenge"
systemd: "CanReboot" = "challenge"
size of cached file QSize(1440, 900) , requiredSize: QSize(2560, 1440)
no cached wallpaper. generate a new one!
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
QPngHandler: Failed to parse ICC profile
WinIdChange 1200008 handle QWidgetWindow(0x55987ba75b90, name="LXQtPanel panel1Window") QScreen(0x55987b8598d0, name="rdp0")
size of original image QSize(1920, 1280)
Systray started
()
Error on DBus request(:1.24,/org/ayatana/NotificationItem/nm_applet): QDBusError(org.freedesktop.DBus.Error.InvalidArgs, No such property “ToolTip”)
Error on DBus request(:1.24,/org/ayatana/NotificationItem/nm_applet): QDBusError(org.freedesktop.DBus.Error.InvalidArgs, No such property “OverlayIconName”)
Error on DBus request(:1.24,/org/ayatana/NotificationItem/nm_applet): QDBusError(org.freedesktop.DBus.Error.InvalidArgs, No such property “OverlayIconPixmap”)
Error on DBus request(:1.24,/org/ayatana/NotificationItem/nm_applet): QDBusError(org.freedesktop.DBus.Error.InvalidArgs, No such property “AttentionIconPixmap”)
systemd: "CanPowerOff" = "challenge"
Starting idlenesswatcher
Translator is not loaded "qlipper_en_US" "/usr/share/qlipper/translations"
"PowerButton" "org.freedesktop.DBus.Error.AccessDenied" "Permission denied"
"SuspendButton" "org.freedesktop.DBus.Error.AccessDenied" "Permission denied"
"HibenateButton" "org.freedesktop.DBus.Error.AccessDenied" "Permission denied"
QSystemTrayIcon::setVisible: No Icon set
wallpaper cached saved to  "/home/liyi/.cache/pcmanfm-qt/lxqt/wallpaper.cache"
[Notice] Started
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
[Warning] Cannot extract keycode and modifiers from shortcut 'XF86PowerOff'
[Warning] Cannot extract keycode and modifiers from shortcut 'XF86Suspend'
[Warning] Cannot extract keycode and modifiers from shortcut 'XF86Sleep'
[Warning] Cannot extract keycode and modifiers from shortcut 'XF86AudioRaiseVolume'
[Warning] Cannot extract keycode and modifiers from shortcut 'XF86AudioLowerVolume'
[Warning] Cannot extract keycode and modifiers from shortcut 'XF86AudioMute'
[Warning] Cannot extract keycode and modifiers from shortcut 'XF86Eject'
QSystemTrayIcon::setVisible: No Icon set
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 763, resource id: 41943046, major code: 18 (ChangeProperty), minor code: 0

```

- pcmanfm show no errors and show proper icons
![Screenshot 2022-11-08 at 13 23 01](https://user-images.githubusercontent.com/3155688/200562831-6ba2f6a1-ad5b-4b3c-b232-a08d9d67ee07.png)

**Comment by matt335672** [comment]
There's a couple of odd things here:-
1) `pcmanfm` is the file manager which runs when you log in. It's working from the command line, but not when you log in.
2) Your icons look quite a bit different from mine.

Did you log out and in again after installing the icon theme? The way that `pcmanfm` works makes that necessary.

**Comment by liyimeng** [comment]
I did login/out again the rdp session. My system by default actually use pcmanfm-qt, If I login with VNC/nomachine, it look like this:
![Screenshot 2022-11-08 at 18 02 19](https://user-images.githubusercontent.com/3155688/200629198-fba87fea-67e5-4ac3-a239-2b8eaa79e322.png)

**Comment by liyimeng** [comment]
But if I install pcmanfm, I get different icons. No matter it is pcmanfm or pcmanfm-qt, I always get the same looking: no icon in rdp session.

**Comment by matt335672** [comment]
How are you starting your LXDE session from XRDP? Are you using `$HOME/.xsession` or using some other method?

**Comment by liyimeng** [comment]
I following this instructions and install https://tecadmin.net/how-to-install-xrdp-on-ubuntu-22-04/ 

Did not do anything extra.

**Comment by matt335672** [comment]
OK - I'm a bit confused here then.

I've just done the following:-
- Installed an Ubuntu 22.04 minimal VM
- Done an `apt install lxde xrdp xorgxrdp pcmanfm-qt`
- added xrdp to the ssl-cert group.
- restarted xrdp.

I can then log in over xrdp, but I get a GNOME desktop.

To get an LXDE desktop I have to do one of the following:-

1) Either `ln -s `which startlxde` $HOME/.xsession`, or
2) `sudo update-alternatives --config x-session-manager` and choose `/usr/bin/startlxde`

For either of these I get a working LXDE desktop for both pcmanfm and pcmanfm-qt

Here are some questions for you:-
1. What output to you get for the command `ls -l ~/.xsession, ~/.Xsession`?
2. What output do you get for the command `update-alternatives --query x-session-manager` ?
3. What output do you get for the command `cksum /etc/xrdp/startwm.sh`?

Finally, you can see what icons `pcmanfm-qt` is trying to load with the following:-

```
sudo apt install -y strace
pkill pcmanfm
strace -e trace=%%stat pcmanfm-qt 2>&1 | grep /icons/
```

This command generates a lot of output. On my system I can see that the files which are being accessed are in `/usr/share/icons/nuoveXT2`.

**Comment by liyimeng** [comment]
@matt335672 Firstly, I wanna appreciate you great help. 
Here is my update
- 1. No, I don't have these two files in my home
- 2.  Mine seems have lxqt instead of lxde 
```
update-alternatives --query x-session-manager
Name: x-session-manager
Link: /usr/bin/x-session-manager
Slaves:
 x-session-manager.1.gz /usr/share/man/man1/x-session-manager.1.gz
Status: auto
Best: /usr/bin/startlxqt
Value: /usr/bin/startlxqt

Alternative: /usr/bin/openbox-session
Priority: 40
Slaves:
 x-session-manager.1.gz /usr/share/man/man1/openbox-session.1.gz

Alternative: /usr/bin/startlxqt
Priority: 50
Slaves:
``` 
- 3. `cksum /etc/xrdp/startwm.sh 
1729945551 407 /etc/xrdp/startwm.sh`

runnings strace go no output at all
![Uploading Screenshot 2022-11-10 at 12.44.37.png…]()

**Comment by liyimeng** [comment]
<img width="798" alt="Screenshot 2022-11-10 at 12 44 37" src="https://user-images.githubusercontent.com/3155688/201082649-6fe0edd2-6d5c-4b15-93ac-2c05e0a91f78.png">

**Comment by liyimeng** [comment]
I try `sudo update-alternatives --config x-session-manager and choose openbox` It dose not make different either. 

Could it be the lxqt problem?

**Comment by liyimeng** [comment]
I really my Machine is actually lubuntu, but not vanilla ubuntu. According to https://discourse.lubuntu.me/t/lubuntu-20-10-xrdp-working-but-not-the-right-session/2169/16 and https://ubuntuforums.org/showthread.php?t=2480733, xrdp and lxqt might not a good combination.

**Comment by matt335672** [comment]
Before running the strace, used `ps -ef` to make sure no other `pcmanfm` and `pcmanfm-qt` processes are running.

**Comment by liyimeng** [comment]
It dose run as you see, I have the FM window pop up.  I also try this https://wiki.archlinux.org/title/LXQt#Run_LXQt_with_xrdp

No, the same issue. :(

**Comment by matt335672** [comment]
I'll have a look at lubuntu - there may be some odd issue with it which we can address. It doesn't seem I can reproduce this with Ubuntu + LXDE.

**Comment by matt335672** [comment]
I've installed lubuntu latest version:-

```
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

I had a few problems with the GUI not picking up preferences. This came down to the environment variable DESKTOP_SESSION not being defined. I fixed this by adding the file `/etc/profile.d/aa_xrdp.sh` witrh the following contents:-

```sh

if [ -n "$XRDP_SESSION" ]; then
    if [ -z "$DESKTOP_SESSION" ]; then
        export DESKTOP_SESSION=Lubuntu
    fi
fi
```

xrdp seems OK now. However, I still have no problems with missing icons.

In other words I can't reproduce your problem at all, even with the same operating system.

I'm wondering if this is stale configuration. Can you try setting up a completely separate user with something like `adduser testuser`. Don't customise it at all. Then see how that behaves.

**Comment by liyimeng** [comment]
Here is my sys info 
```
testuser@ubuntu:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
testuser@ubuntu:~$ 
```

I create testuser xrdp works out of the box except the same problem persistent. I still go no icons

<img width="781" alt="Screenshot 2022-11-10 at 20 25 13" src="https://user-images.githubusercontent.com/3155688/201188468-47ad1cc9-79e4-4d21-ba8f-303d8ff4c6f8.png">

**Comment by liyimeng** [comment]
@matt335672 Problem solved! I follow your tips,  adding the file /etc/profile.d/aa_xrdp.sh witrh the contents you presented:-
```
if [ -n "$XRDP_SESSION" ]; then
    if [ -z "$DESKTOP_SESSION" ]; then
        export DESKTOP_SESSION=Lubuntu
    fi
fi
```
Logout/in again, I have the icons! :D  It magically works! 

<img width="864" alt="Screenshot 2022-11-10 at 20 38 03" src="https://user-images.githubusercontent.com/3155688/201190221-2508a978-06e1-4094-9055-ffb1b489a7f1.png">

**Comment by matt335672** [comment]
When I added that file I got the environment variables between a local session and an XRDP session more or less compatible.

The environment variable is created by SDDM, but not by xrdp. It looks like some of the login scripts in Lubuntu are assuming it will always be set.

We'll leave this open for a few days, in case you have any more comments to add. I'll change the title of this PR to more accurately reflect the problem.

Thanks for sticking with me - I'm sure this will be useful to some other people.

There's still a mystery in that I wasn't able to reproduce this at all.

**Comment by matt335672** [comment]
BTW there are probably better places to set DESKTOP_SESSION - it doesn't really belong in the bash profile.

On the other hand, it's hard to see where to put it, exactly. Deducing whether LXDE is going to be run by the user is a hard problem, so any change like that is going to potentially break other desktops on the same system.

**Comment by liyimeng** [comment]
@matt335672 Thanks for all the help!
