### ISSUE TITLE
instfiles/xrdp-sesman.service.in has no ExecReload entry

### ISSUE THREAD

**Issue by yxzzx** [neutrinolabs/xrdp#2414]
While xrdp-sesman can reread its configuration file upon reception of a SIGHUP the service file doesn't take advantage of this and the documentation doesn't mention it.
I just kicked 50 people from one of our servers because I (stupidly) believed what "systemctl reload xrdp-sesman.service" told me.
After restarting xrdp-sesman I had to manually cleanup the fallout of the orphaned sessions.
To my surprise I just found code in sesman that will do the right thing when receiving SIGHUP.

**Comment by yxzzx** [comment]
sorry, that issue should be in neutrinolabs/xrdp

**Comment by matt335672** [comment]
Good point.

The SIGHUP cleanup code was fixed by #2168 (in v0.9.19), but I failed to update the service manifest.

What version of xrdp are you running, @yxzzx ?

**Comment by yxzzx** [comment]
We are using xrdp-0.9.19.

**Comment by matt335672** [comment]
In the short-term, all I can suggest at this point is to create the following `/etc/systemd/system/xrdp-sesman.service.d/override.conf` on all nodes and do a `systemctl daemon-reload`:-

For subsequent readers, **this needs xrdp v0.9.19 or later**

```
[Service]
ExecReload=kill -HUP $MAINPID
```

This is direct from [systemd.service(5)](https://www.man7.org/linux/man-pages/man5/systemd.service.5.html). I haven't tested it myself. I'll put a PR together to fix this in the main file when I've done so.

**Comment by yxzzx** [comment]
I would have sent a SIGHUP, but as the documentation doesn't mention it, I did a restart. Having this in the service file is just nicer :-). More important would have been a note in the man page.
Thank's for all your work.
