### ISSUE TITLE
Clipboard help

### ISSUE THREAD

**Issue by HurricaneHernandez** [neutrinolabs/xrdp#242]
I'm trying to get the clipboard working using microsoft rdp client in windows 7. I have tried using vnc4server and tightvncserver.  Unfortunately no matter what combination or version of xrdp I use. I always seem to get the following error message:
```
rdp-chansrv [0726140899]: child_signal_handler:
xrdp-chansrv [0726140899]: child_signal_handler: child pid -1
xrdp-chansrv [0726140899]: scard_deinit:
chansrv:smartcard_pcsc [0726140899]: scard_pcsc_deinit:
process_message_channel_setup: chan name 'rdpdr' id 0 flags 00000000
process_message_channel_setup: chan name 'rdpsnd' id 1 flags 00000000
process_message_channel_setup: chan name 'cliprdr' id 2 flags 00000000
process_message_channel_setup: chan name 'drdynvc' id 3 flags 00000000
xrdp-chansrv [0726153081]: child_signal_handler:
xrdp-chansrv [0726153081]: child_signal_handler: child pid -1
[0726153081]: CLIPBOARD  clipboard_init: 394 : ERROR: clipboard_init: no xfixes
[0726153081]: CLIPBOARD  clipboard_init: 500 : ERROR: xrdp-chansrv: clipboard_init: error on exit
xrdp-chansrv [0726153081]: sound_init:
[0726153122]: CLIPBOARD  clipboard_data_in: 1549 : ERROR: aborting clipboard_data_in - clipboard has not been initialized
[0726153122]: CLIPBOARD  clipboard_data_in: 1549 : ERROR: aborting clipboard_data_in - clipboard has not been initialized
```

**Comment by HurricaneHernandez** [comment]
Ps the two version of xrdp that I have used are : 0.6.1 which is the one found in launchpad or ubuntu ppa for trusty. And I freshly compiled version from the dev branch.

**Comment by jsorg71** [comment]
RDP clipboard is difficult without XFixes.  It look like this Xvnc server does not support XFixes.
Can you use X11rdp as the backend instead?
X11rdp is the preferred backend.

**Comment by metalefty** [comment]
Just to inform you, [TigerVNC](http://tigervnc.org) is one of the implementation which have XFixes extension.

**Comment by HurricaneHernandez** [comment]
Thank you for the responses. I have tried both TigerVNC and X11rdp. The results are both the same. I can do one copy from host and paste to client. After that I can no longer copy and paste.

I was looking at this support thread: http://sourceforge.net/p/xrdp/mailman/message/29012336/

Should I be running a clipboard app?

**Comment by HurricaneHernandez** [comment]
Ok after further testing it seems the issue might have been the app I was trying to cut and paste from. Thanks for the help. X11rdp worked.
