### ISSUE TITLE
Scroll is not working with VNC backend after #2364

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#2423]
I don't see any scroll events when using VNC after #2364.  I'll raise a PR for this soon. 

@seflerZ I'd appreciate it if you review my PR later.

## VNC
https://user-images.githubusercontent.com/941609/201479177-8b3b2289-0243-4e7d-a6dd-930b0769f0d8.mp4

## xorgxrdp

https://user-images.githubusercontent.com/941609/201479768-4ea8ba88-478e-4d6a-b01d-7759a8d222f0.mp4

**Comment by matt335672** [comment]
I can confirm this.

I've checked out these commits:-
- d80d096e before I merged #2364. I get events for buttons 4 and 5 in xev using VNC.
- e1697879 - the merge commit for #2364. I don't get the same events for buttons 4 and 5.

Nice find @metalefty

**Comment by metalefty** [comment]
Raised #2424 for this.

**Comment by metalefty** [comment]
Solved by #2425.
