### ISSUE TITLE
Chromium based browsers dont open up and screen starts to flicker

### ISSUE THREAD

**Issue by njmulsqb** [neutrinolabs/xrdp#2430]
Hi,

I have installed xrdp on Kali WSL on Windows 11, the issue I am facing with xRDP is that whenever I open any chromium based browser i.e chrome, chromium, brave, etc the browser GUI doesnt show up, the tab shows in the tab bar but it doesn't maximize. 

To add fuel to fire, the laptop screen starts to flicker a lot.

I dont know what relevant information do you want from me. Let me know if I can provide any other information regarding environment. I have faced this issue on Windows 10 and Windows 11 WSL.

**Comment by matt335672** [comment]
Hi @njmulsqb 

Can you tell us what the output of `xrdp -v` is?

Also, can you try running the session but selecting an `Xvnc` session type instead. You will need to install the `tigervnc-standalone-server` package to do this if it isn't installed already.

**Comment by njmulsqb** [comment]
The output of `xrdp -v` is as follows:
```
└─$ xrdp -v
xrdp 0.9.19
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-Zpw7E1/xrdp-0.9.19=. -fstack-protector-strong -Wformat -Werror=format-security
      LDFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2
      PKG_CONFIG_PATH=/build/xrdp-Zpw7E1/xrdp-0.9.19/pkgconfig

  Compiled with OpenSSL 3.0.7 1 Nov 2022
```

I configured tigervnc and connected via it but this is just showing black screen
![image](https://user-images.githubusercontent.com/47940898/202171914-c9e5ec15-b275-4825-ab81-6f1d8504d10e.png)

Also when screen starts to flicker, it doesnt only flickers the rdp session but it flickers the screen of host machine as well.

**Comment by matt335672** [comment]
Are you logged in to the same account on the console and on the xrdp session?

That won't work properly - see https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-log-the-same-user-on-on-the-graphical-console-and-over-xrdp-at-the-same-time

**Comment by njmulsqb** [comment]
Same result with vnc as well. Chromium browser not opening and screen has started to flicker on host machine
The screenshot is from the session using vnc
![image](https://user-images.githubusercontent.com/47940898/202174353-ee67963b-2e3e-42d6-9489-8c3e806eb776.png)

**Comment by matt335672** [comment]
Referring to my previous comment, can you make sure both the xrdp session and the console (i.e. the host machine) are logged out?

Then log in on just the xrdp session and see what happens.

**Comment by njmulsqb** [comment]
Yes I verified that.
The issue still exists

**Comment by matt335672** [comment]
It looks like there may be (or may have been) some issues running chrome in this way.

https://askubuntu.com/questions/1048723/google-chrome-can-not-start-under-vnc-ubuntu-18-04

Try the following:-
1) Make sure console is logged out
2) Using `ps -ef` and `kill` make sure any background copies of the browser are removed.
3) Try running the browser from the command line with the `--disable-gpu` switch.

**Comment by matt335672** [comment]
@njmulsqb - did you have a try at the above link?

**Comment by njmulsqb** [comment]
No, I switched to MAC, the issue persisted. You can close the issue

**Comment by matt335672** [comment]
Thanks.
