### ISSUE TITLE
Don't start window managers until there's an ouptut

### ISSUE THREAD

**Issue by derekschrock** [neutrinolabs/xrdp#2436]
Testing [fvwm3](https://github.com/fvwmorg/fvwm3/) with xorgxrdp backend on FreeBSD 13.1 it appears xrdp is running startwm.sh (UserWindowManager or DefaultWindowManager) before there's an output (ready/registered/initialized?).

9/10 when running fvwm3 this section of [code](https://github.com/fvwmorg/fvwm3/blob/master/libs/FScreen.c#L527
) will fail.   `res` is non-NULL however `res->noutput == 0`.   Resulting in `goto randr_fail` exiting fvwm3.

Putting `sleep 1` in startwm.sh allows `XRRGetScreenResources` return value struct to have `noutput > 0`.

It's possible this is just the age of the hardware I'm running on (2011 ThinkServer TS130)?   Recommending a sleep in startup.sh is the fix otherwise should xrdp wait until there's at least 1 output until it runs startwm.sh?  Or maybe this is a possible issue with FreeBSD Xorg or xorgxrdp?

**Comment by matt335672** [comment]
Hi Derek,

At the moment we just wait for an X server unix port to appear before deciding the X server is ready. It's simple, but can lead to race conditions. Ideally the X server wouldn't be accepting connections on the listening port before fully initialised, but this doesn't seem to be what's happening here.

I don't know whether this is fixable within xorgxrdp as I don't know the code well enough. Anyone else know?

A fix within xrdp could be done by connecting to the X server and querying it before running `startwm.sh`. This may not be a bad idea, in that if the X server doesn't start properly, the logging doesn't really communicate that well to the user. We could do this either from startwm.sh, or add another executable which would need DISPLAY and XAUTHORITY set.

**Comment by derekschrock** [comment]
Testing Xvnc with fvwm3 it seems that I need to set `delay_ms` for Xvnc.  Is there any reason there isn't a `delay_ms` for Xorg?  delay the execution of startwm.sh?

If the binary is the correct path forward I have an init. pass here.  https://github.com/derekschrock/xrdp/tree/randr-wait

Future updates:
- printf to LOG()
  - Or do we just run it as the user, collect the output, then send that to log?  popen, read/LOG(), pclose, get rc, like `add_xauth_cookie`
  - Have `sesman/session.c` execute this before startwm.sh and bail if it's non-zero return code.
- Update Makefile.am
- Install to?  bin/ or libexec/ ?
- Make wait (retry) configurable?
- Make this optional? (off by default?) It seems there are some VNC (tightvnc I think) that do not support RandR.

**Comment by matt335672** [comment]
The delay for VNC was added for #182, according to `git blame`. We can add something similar for Xorg maybe? That's quick and easy. Another workaround for your particular problem is to add the delay to startwm.sh (as you've said), or elsewhere.

The binary is possibly a way forward to validate the X server before we run the session. Initial comments I've got on that:-
1) Needs to be executed as user from session.c after X server is started.
2) We need an overall timeout (SIGALRM) to prevent forever-freezes.
3) You can query the RandR extension before checking for outputs, and skip the output check if it's not supported.

**Comment by derekschrock** [comment]
I've been testing the above 3 suggestions over the last couple weeks, added the source to the Makefiles and installs to prefix bin/.

Any other suggestions or changes you can recommend?

**Comment by matt335672** [comment]
Nice work!

A couple of further suggestions:-

1) At the moment, `popen` is only used in `sesman/xauth.c`. It's not wrapped in any way in this function. Rather than introducing stdio.h and string.h to `sesman/session.c`, could you pop the `wait_for_xserver()` func in another source file? Ideally we'd stop wrapping some of the common functions from the standard C libraries, but at the moment that's in the "too difficult" pile.
2) I'm not entirely sure `2>&1` used when you run `waitforx` will be supported by all shells in the future. I'd suggest moving that feature into the code.
3) Make more use of the functions in `common/os_calls.h` in `wait_for_xserver()`.

There's more we could do, but the above will get us in a good place for a formal review, and we can run it all through CI as well.

Does that sound OK?

**Comment by derekschrock** [comment]
Ok.  I believe these comments have been addressed.

Moved `wait_for_xserver()` to its own file with a `... .h` file

`xrdp-waitfox` now just outputs to stdout.

For 3 I'm assuming since 1 we're keeping `popen`.  However, I do see something that could replace the `strchr/if/assign` `strtrime(..., 2)`.  I don't see anything wrapping `fgets` in `strings_calls.c` or anything in `os_calls.h` that handles reading a `FILE*`.  So the loop and `fgets` stay? I don't know if this was your expectation here or to just use `g_strchr`

**Comment by matt335672** [comment]
That's great.

I've got other comments, but it would be easier to comment on a PR. Do you want to open one?

**Comment by derekschrock** [comment]
Created #2492
