### ISSUE TITLE
PolicyKit errors on lubuntu/LXDE 14.04.2

### ISSUE THREAD

**Issue by abbr** [neutrinolabs/xrdp#244]
I am trying to get xrdp fully working on a later version of ubuntu flavored Linux. I knew it doesn't work on ubuntu, so I installed xrdp from ubuntu software center (xrdp version is 0.6.0-1) on a pristine lubuntu 14.04.2, and put line `lxsession -s Lubuntu -e LXDE` in ~/.xsession. When rdp to the box, I got two kinds of PolicyKit errors as shown in attached screenshots depending on whether I am logged into local desktop or not. If I am, I got "An authentication agent already exists for the given subject"; if not, I got "Cannot determine user of subject". In the first case, I found some windows launched in rdp session appears in local desktop, i.e., the rdp session shares with local desktop session. In the latter case, I can click the logout button but the session never ends.

I have also tried LXDE desktop (`sudo apt-get install lxde`). It doesn't give the PolicyKit error message but the way it handles logout button (and possibly other functions) is the same as Lubuntu.

I have tried various tactics such as disabling PolicyKit agent from session autostart without luck.

Because local desktop never give me the error. I suspect it's a problem of xrdp in that either it cannot launch an new session by itself (hence sharing a session with local desktop), or it cannot pass the authenticated user to policykit.

![image](https://cloud.githubusercontent.com/assets/6158277/7866124/26151b96-0522-11e5-9347-17fd5cba6966.png)

(screenshot 1)

![image](https://cloud.githubusercontent.com/assets/6158277/7866157/66282dd6-0522-11e5-8386-8e9dbc262a92.png)

(screenshot  2)

**Comment by metalefty** [comment]
It seems not an xrdp issue.
