### ISSUE TITLE
Didn't work xrdp after reboot

### ISSUE THREAD

**Issue by Sanchous1295** [neutrinolabs/xrdp#2451]
XRDP was configured on the server and everything worked fine until the server was rebooted

After reboot, it gives an error when entering the login password
Connecting to sesman ip 127.0.0.1 port 3350
sesman connect ok
Sending login info to session manager, please wait
login successful for display 10
started connecting
connection problem, giving up
some problem

**Comment by matt335672** [comment]
Can you post xrdp.log and xrdp-sesman.log for the login attempt in question?

**Comment by Sanchous1295** [comment]
> Can you post xrdp.log and xrdp-sesman.log for the login attempt in question?

Unfortunately, I am not the one who administers this server and the person who administers this server will be absent for a long time. Since I am now in charge of it, it would be necessary to fix access to it, but I am a novice in Linux, so it would be nice if you could tell me where to look for these logs and so on.
Imagine what you are explaining to a child))

**Comment by matt335672** [comment]
You'll need root access to the server.

Files are `/var/log/xrdp.log` and `/var/log/xrdp-sesman.log`.

Try to log in, then post the lines from those files where the timestamps are roughly before and after the login attempt.

Also, as an ex-system admin myself, I'd urge you to press your management to get some training organised for you. You can't reasonably expect people on the internet to fill in for your organisation's lack of succession planning.

**Comment by Sanchous1295** [comment]
[xrdp-sesman - Copy.log](https://github.com/neutrinolabs/xrdp/files/10200145/xrdp-sesman.-.Copy.log)
[xrdp - Copy.log](https://github.com/neutrinolabs/xrdp/files/10200146/xrdp.-.Copy.log)

**Comment by matt335672** [comment]
That's useful - thanks.

Your X server isn't starting successfully:-

```
[20221207-12:08:42] [INFO ] Starting X server on display 10: /usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log  
[20221207-12:08:52] [WARN ] Timed out waiting for X server on display 10 to startup
```

Can you post the contexts of `/home/poker/.xorgxrdp.%s.log` ?

**Comment by Sanchous1295** [comment]
I have a file /var/log/Xorg.0.log is this it?

**Comment by Sanchous1295** [comment]
And Xorg.1.log , Xorg.0.log.old

**Comment by matt335672** [comment]
Sorry - I meant `/home/poker/.xorgxrdp.10.log`. Have you got that?

The other files are the log files created by the X server on the console.

**Comment by Sanchous1295** [comment]
Okay, I understood what file we are talking about, but for some reason it is not in this directory

**Comment by matt335672** [comment]
Try running this command from the command line when logged in as `poker`:-

```
/usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
```

This is the command that sesman is using to start the X server.

**Comment by Sanchous1295** [comment]
```
/usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log

X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System: linux Debian
Current Operating System: Linux BOB 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-4kali1 (2021-08-09) x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.10.0-kali9-amd64 root=UUID=bc584131-a3e6-446a-ad52-2c45949ce91c ro quiet splash
Build Date: 13 April 2021  04:07:31PM
xorg-server 2:1.20.11-1 (https://www.debian.org/support) 
Current version of pixman: 0.40.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: ".xorgxrdp.10.log", Time: Mon Dec 12 15:53:00 2022
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xorgxrdpSetup:
xrdpdevSetup:
rdpmousePlug:
rdpkeybPlug:
rdpIdentify:
rdpDriverFunc: op 10
rdpProbe:
rdpProbe: found DRMDevice xorg.conf value [/dev/dri/renderD128]
rdpProbe: found DRI3 xorg.conf value [1]
rdpPreInit:
rdpPreInit: /dev/dri/renderD128 open failed
rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
rdpScreenInit: pfbMemory bytes 1920000
rdpScreenInit: pfbMemory 0x7fb398b8a010
rdpSimdInit: assigning yuv functions
rdpSimdInit: cpuid ax 1 cx 0 return ax 0x00050657 bx 0x04010800 cx 0xfffa3203 dx 0x0f8bfbff
rdpSimdInit: sse2 amd64 yuv functions assigned
rdpClientConInit: disconnect idle session after [0] sec
rdpClientConInit: kill disconnected [0] timeout [0] sec
rdpXvInit: depth 24
rdpScreenInit: out
rdpCreateScreenResources:
/usr/bin/xkbcomp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libX11.so.6)
/usr/bin/xkbcomp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libX11.so.6)
XKB: Failed to compile keymap
Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
(EE) 
Fatal server error:
(EE) Failed to activate virtual core keyboard: 2(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at ".xorgxrdp.10.log" for additional information.
(EE) 
rdpLeaveVT:
(EE) Server terminated with error (1). Closing log file.
```
                                                                                                                              
```
┌──(poker㉿BOB)-[~]
└─$ sudo cat ~/.xorgxrdp.log                                                                                              1 ⨯
cat: /home/poker/.xorgxrdp.log: No such file or directory
                                                                                                                              
┌──(poker㉿BOB)-[~]
└─$ ls /home/poker                                                                                                       1 ⨯
Desktop  Documents  Downloads  Music  Pictures  Public  Sert  Templates  thinclient_drives  Videos`
```

**Comment by Sanchous1295** [comment]
ps uxaww | grep Xorg                                                                                                  2 ⨯
poker     31475  0.0  0.0   6184  2256 pts/0    S+   16:10   0:00 grep --color=auto Xorg

**Comment by matt335672** [comment]
That's not good.

Your X server libraries are expecting a later version of the C library than is present on your system. That may be caused by a partial system update which has not completed, or you may have run out of disk space. There are many possibilities.

In any case this is more serious than xrdp simply not working.

I'm afraid I'm unable to help you further with this @Sanchous1295. If we attempt anything more together, we may lose the entire server. I'm not willing to take responsibility for this. I urge you to find a local expert who can examine your system and correct the error above.

**Comment by Sanchous1295** [comment]
@matt335672 In any case, thank you very much, you helped a lot. It's better than nothing
