### ISSUE TITLE
Raspi4b makefile nor found

### ISSUE THREAD

**Issue by jesko42** [neutrinolabs/xrdp#2452]
Compiling from sources neiter

```
./bootstrap
./configure
make
sudo make install
```

nor

```
cd "${XRDP_SRC_DIR}"
./bootstrap
./configure --enable-fuse --enable-mp3lame --enable-pixman
make<br>
```

works as there is NO `Makefile`.
I only find

`Makefile.am` and
`Makefile.in`

**Comment by metalefty** [comment]
I don't think it is hardware specific. It depends on your OS. What's your OS?

**Comment by jesko42** [comment]
`cat /etc/os-release`

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

`uname -a`

`Linux Multiplex 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux`

**Comment by metalefty** [comment]
That's strange that Makefile is not generated without any errors. Aren't you missing any errors?

**Comment by jesko42** [comment]
It's gone. Just by doing "./configure" (again!). Makefile present now. Sorry for bothering :-( Although this may never happen ...
