### ISSUE TITLE
pcsc ipc dir socket directory permissions

### ISSUE THREAD

**Issue by aaronknister** [neutrinolabs/xrdp#2454]
Is there a technical requirement for the pcsc ipc directory to have a mode of 0x1777? If not I'd like to see if it's possible to change it to 0x0700.

https://github.com/neutrinolabs/xrdp/blob/b4dd86fadd4927c1f8e7839d46c1fec40c598b70/sesman/chansrv/smartcard_pcsc.c#L1877

Security scanners really don't like world-writeable directories (even if they do have the sticky bit set).

**Comment by matt335672** [comment]
Hi @aaronknister 

It's a good question.

I have to admit I mis-parsed your question at first, and thought you were asking about the xrdp socket directory which is identical in many ways. I've raised a discussion about this at #2458 which you might find interesting, or want to comment on.

To answer your actual question, I can't see any reason why the sockets directory for this socket needs permissions to be anything other than 0700. I'll raise a PR to fix it.
