### ISSUE TITLE
File instfiles/pam.d/xrdp-sesman.system not in release archive

### ISSUE THREAD

**Issue by gdsotirov** [neutrinolabs/xrdp#2466]
File `instfiles/pam.d/xrdp-sesman.system` is not present in release archive available from Assets (e.g. [xrdp-0.9.21.tar.gz](https://github.com/neutrinolabs/xrdp/releases/download/v0.9.21/xrdp-0.9.21.tar.gz)). This leads to the following error, when [instfiles/pam.d/mkpamrules](https://github.com/neutrinolabs/xrdp/blob/devel/instfiles/pam.d/mkpamrules) script decides to use it:

```
make[3]: Entering directory '/usr/src/tmp/xrdp-0.9.21/instfiles/pam.d'
./mkpamrules auto . xrdp-sesman
Cannot find ./xrdp-sesman.system
```

I'm not sure how this archive is built, but the file should be present into it.

Related: #1558, #1560

**Comment by matt335672** [comment]
Sorry @gdsotirov - this is entirely my fault.

The build works fine from a `git clone`, but the releases are built using the output of `make distcheck`. This requires all the files which are to be distributed to be referenced somehow. I should have added the file to `instfiles/pam.d/Makefile.am` when I put the patch together for #1560.

I'll put a PR together to fix this.

**Comment by gdsotirov** [comment]
@matt335672 No problem and thanks for the prompt reaction!
