### ISSUE TITLE
Failed to start on Fedora22

### ISSUE THREAD

**Issue by JerryLiao26** [neutrinolabs/xrdp#247]
The xrdp service failed to start automatically on my Fedora22.After I manually execute xrdp and xrdp-sesman I can connect from MSTSC but still with login failure.I install it following the instructions in readme.txt and it seemed going smoothly.There lots of related information in journalctl and other logs.And I don't know what to show here as well as what to do.Anybody could help?

**Comment by metalefty** [comment]
Can you start xrdp **service** manually?

**Comment by JerryLIao26** [comment]
@metalefty If I use "systemctl start xrdp.service" command and it will give this back:

>A dependency job for xrdp.service failed. See 'journalctl -xe' for details.

If I start xrdp-sesman.service in the same way, the information is like this:

>Job for xrdp-sesman.service failed. See "systemctl status xrdp-sesman.service" and "journalctl -xe" for details.

I execute xrdp and xrdp-sesman in terminal and the service seemed to start but when I log in with MSTSC, I can see the login frame but after submit it returned:

>xrdp_mm_process_login_response:login failed

**Comment by metalefty** [comment]
Looks like the same issue as mine, since Fedora 21. Unfortunately I have no idea yet.
* neutrinolabs/xrdp#236
* metalefty/X11RDP-RH-Matic#13

**Comment by JerryLIao26** [comment]
@metalefty Wow, that might be something related to system designs or kernels.I do like this software a lot and I hope this problem can be solved.Thanks a lot for answering.

**Comment by itamarjp** [comment]
I am working to have a working rpm for F-22, this bug is related to selinux, here are more info ->

https://bugzilla.redhat.com/show_bug.cgi?id=1177202

**Comment by metalefty** [comment]
Good news! Fixed in Fedora 23. 
https://bugzilla.redhat.com/show_bug.cgi?id=1177202#c25

It will take significant time the fix come down to RHEL or clones but this issue is considered to be fixed.

**Comment by metalefty** [comment]
Fixed in Fedora.
