### ISSUE TITLE
xrdp breaks after installing amdgpu drivers on Ubuntu 22.04

### ISSUE THREAD

**Issue by apenngrace** [neutrinolabs/xrdp#2475]
Before installing amdgpu drivers (from AMD's website) using the amdgpu-install utility, xrdp works in Ubuntu 22.04.  After installing those drivers (and rebooting), the xrdp service still seems to run, but if I try to log in using an RDP client, I get the "oops something went wrong" screen.

**Comment by matt335672** [comment]
Hi @apenngrace

I take it you're using the Xorg backend?

After you get the Oops message, can you post the most recent xorgxrdp log (find with `ls -lt ~/.xorgxrdp.*.log`) and `~/.xsession-errors`?

That should allow us to figure out what isn't working.

**Comment by apenngrace** [comment]
[xorg log files.zip](https://github.com/neutrinolabs/xrdp/files/10249742/xorg.log.files.zip)

Here are the log files you requested.  I honestly don't know about the backends, but now I'm curious if I should read up on this.

**Comment by apenngrace** [comment]
To give additional context: 

- This is an Ubuntu virtual machine (I'm using Proxmox).  I'm using PCI passthrough for my AMD GPU (RX 6600).
- I got the error once I installed the AMD drivers from the AMD website (driver version 5.4.50401).
- xRDP runs without errors before I install the drivers from AMD (and use the open source AMD drivers that come preinstalled by Ubuntu).  The performance of xRDP is really nice even, but the performance of the AMD GPU is poor (like 1 frame per second on the Unigen Heaven demo).
- After I install the AMD drivers, I get the error that I mentioned if I try xRDP.  However, I am able to log in using x11vnc.  I can double-check that the AMD driver works that way.  When I do, and I get like 180 frames per second using Unigen (which seems good to me), but the performance of x11vnc is very slow.  The framerate I see on the VNC client is nowhere near as good as what it seems xRDP can do. 
 
It would be really great if this issue with xRDP could be fixed because I really like the MacOS client for Microsoft Remote Desktop.  If there anything else you need to troubleshoot such as screen shots, screen recordings, log files, whatever, I'll be happy to provide them.

**Comment by matt335672** [comment]
I can't see anything wrong in those logs.

We need to find out why the GNOME desktop checks are failing. After you try to log in, can you try the following which outputs the system log for the last two minutes:-

```
sudo journalctl -S -2m
```

That might give us more info.

**Comment by apenngrace** [comment]
[journalctl 2 minutes.txt](https://github.com/neutrinolabs/xrdp/files/10252035/journalctl.2.minutes.txt)

**Comment by apenngrace** [comment]
I turned off secure boot in BIOS on this VM... just mentioning in case it could affecting something.

**Comment by apenngrace** [comment]
I did some more reading, and I saw that Ubuntu uses a system called Wayland instead of X11 by default.  I checked to see if disabling Wayland would make a difference.  [This article](https://tips.graphica.com.au/ubuntu-and-remote-gnome-desktop/) discusses changes that need to be made in order to get x11vnc working with Ubuntu & Wayland.

I also tried disabling Wayland by editing `/etc/gdm3/custom.conf`, and then uncommenting the line `WaylandEanble=false`.   It says in that file that doing that will force use of Xorg.  I was able to confirm this process disables Wayland because I changed it typing `echo $XDG_SESSION_TYPE` outputs `wayland`, and then after the change it outputs `x11`.

So, with x11 enabled, I still got the oops error.  I captured the same log files you requested earlier:

[Logs X11 instead of Wayland.zip](https://github.com/neutrinolabs/xrdp/files/10254706/Logs.X11.instead.of.Wayland.zip)

**Comment by matt335672** [comment]
This could be your problem:-

```
Dec 17 10:13:11 andrew-Standard-PC-Q35-ICH9-2009 gnome-shell[2626]: libGL error: MESA-LOADER: failed to open zink: /opt/amdgpu/lib/x86_64-linux-gnu/dri/zink_dri.so: cannot open shared object file: No such file or directory (search paths /opt/amdgpu/lib/x86_64-linux-gnu/dri, suffix _dri)
```

Is the environment variable `LIBGL_DRVERS_PATH` set when you log in on the machine console?

**Comment by apenngrace** [comment]
No, `LIBGL_DRVERS_PATH` is not set.

Browsing through `/opt/amdgpu`, I found this man page:

[amdgpu_man.txt](https://github.com/neutrinolabs/xrdp/files/10287590/amdgpu_man.txt)

Searching for `zink` in their mailing list, I found this post: [Dropping libGL/EGL vs DRI driver cross compatibility](https://lists.freedesktop.org/archives/mesa-dev/2022-November/225897.html).  The post is dated Nov 30, 2022, so I think I'll try an older driver to see if that works or not.

I appreciate your patience with me.  I kind of wish I had a better understanding of this linux graphics stack terminology to know whether I'm barking up the wrong tree or not.

**Comment by matt335672** [comment]
I'm guessing, but setting `LIBGL_DRVERS_PATH` might be a way to fix this.

You could try adding this to the top of startwm.sh:-

```
export LIBGL_DRVERS_PATH=/opt/amdgpu/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/dri
```

In any case it might be interesting to see what happens to the error in the journal.

**Comment by apenngrace** [comment]
I went ahead and added that export line that you mentioned above, then restarted.  Still get the Oops error.  I reran the journal log again and attached it.

[journal.txt](https://github.com/neutrinolabs/xrdp/files/10289331/journal.txt)

Unless there is anything else to try, feel free to close the issue.  As it stands, once the AMD proprietary driver is installed, xRDP with Ubuntu 22 breaks.  It appears that it breaks due to `zink_dri.so` missing.  

If my AMD card works using Linux Mint & xRDP, even if the frame rate is sub-optimal, that is good enough for me right now.

Thanks again.

**Comment by matt335672** [comment]
Well, there's plenty to try! The fact Mint works is somewhat interesting, and suggests this needs more investigation. I'm up for it if you are.

Another thing we can try is to see whether we're missing some information. You can try running 3D programs directly from a command line by doing the following:-

- `sudo apt install xterm`
- Edit `/etc/xrdp/startwm.sh` and somewhere near the start, enter the line `xterm`.

Next time you connect, that should give you a command line on the Ubuntu machine. When you hit CTRL-D in the xterm, the system will attempt to start GNOME.

From the command line, enter the command `glxinfo` (which deisplays info about the 3D visuals available) and see what happens.

**Comment by samikha** [comment]
I had a similar problem and in xordxrdp.10.log I had this warning as well (found in the log from @apenngrace too):
 rdpPreInit: /dev/dri/renderD128 open failed
I solved it by adding the user to the 'render' group (which owns /dev/dri/renderD128).

**Comment by matt335672** [comment]
Closing for now. We can re-open this if anyone else has more information to add.
