### ISSUE TITLE
xRDP loads mesa instead of amdgpu drivers on Linux Mint 21

### ISSUE THREAD

**Issue by apenngrace** [neutrinolabs/xrdp#2479]
Note: I know you're also working on [issue 2475](https://github.com/neutrinolabs/xrdp/issues/2475) regarding Ubuntu 22 that involves the AMD proprietary GPU drivers.  I thought to make this issue separate since it is Linux mint instead of Ubuntu (and uses X11 by default instead of Wayland).

I can successfully install the AMD GPU drivers (using `sudo amdgpu-install`):
- The driver install completes without errors
- I enroll the MOK key after reboot with the UEFI Secure Boot

If the very first thing I do after reboot is to attempt logging in with xRDP, it works and I can log in (unlike with Ubuntu 22 which gives me an Oops screen).  However, when I run graphical programs such as `glmark2`, it shows that the mesa drivers get loaded instead of the AMD drivers.

<img width="1236" alt="Screen Shot 2022-12-18 at 7 12 12 PM" src="https://user-images.githubusercontent.com/3463568/208581877-98daabee-d374-418c-8d08-0526e00987d9.png">

On the other hand, if I reboot again, and the first thing I do is log in using `x11vnc` and run `glmark2`, the AMD proprietary drivers actually do load.  There is a substantial difference in performance between these, close to 10x.  

<img width="1100" alt="Screen Shot 2022-12-18 at 7 28 37 PM" src="https://user-images.githubusercontent.com/3463568/208582024-7f445fb2-7fd1-4575-bd8d-49849d91fc1f.png">

Additionally, if I log out of xRDP and then try logging in with VNC (or vice versa), I will get an error screen that says "Could not acquire session name on bus."  

<img width="451" alt="Screen Shot 2022-12-18 at 4 41 24 PM" src="https://user-images.githubusercontent.com/3463568/208582564-ad3d98b7-3c48-45cd-bfad-06740ebb8684.png">

**Comment by matt335672** [comment]
I think that's more-or-less expected behaviour.

First, there's very little difference at this level between Ubuntu and Mint. xrdp and xorgxrdp are both from the Ubuntu repositories.

The Ubuntu packages are built to use MESA acceleration with XRDP. You might be able to get hardware acceleration by recompiling the xorgxrdp package with `--enable-glamor`, but it's a bit of a long shot. The guys working at this level are currently concentrating on NVIDIA cards, and I don't think have the resources currently to fix any issues specifically to do with AMD.

Also bear in mind the VNC protocol effectively drops updates to let the X server run at full speed, and not be held up by slow clients. You'll get a high frame rate on the server side, but a lower frame rate on the client side.

You can start a console session, run x11vnc, and then connect to that from the XRDP front-end. If that works for you, go with that.

**Comment by apenngrace** [comment]
> Also bear in mind the VNC protocol effectively drops updates to let the X server run at full speed, and not be held up by slow clients. You'll get a high frame rate on the server side, but a lower frame rate on the client side.

Ok, thanks for mentioning that, I had no idea.
 
> You can start a console session, run x11vnc, and then connect to that from the XRDP front-end. If that works for you, go with that.

Sorry for my ignorance, but I'm not sure how to do that.  When you mean xRDP front-end, is that still on the sever side?  Is it a setting in the `xrdp.ini`, or a different executable?  Or would that be a client?  I'm connecting to the server by using Microsoft Remote Desktop on MacOS.

By the way, is the "Could not acquire session name on bus" issue expected logging out and then back in?

Thanks.

**Comment by matt335672** [comment]
The VNC protocol (or rather the RFP protocol) is described in [RFC6143](https://datatracker.ietf.org/doc/html/rfc6143). Section 3 describes the way that the updates are sent from the server to the client.

I'll give you the simplest possible setup for using x11vnc so you can see if it's what you want. I'm assuming  you're logging in to the local machine with an account called `testuser`.
- Edit `/etc/xrdp/xrdp.ini` and add this section:-

```
[localvnc]
name=localvnc
lib=libvnc.so
ip=localhost
port=5900
#username=ask
password=
pamusername=asktestuser
pampassword=ask
pamsessionmng=127.0.0.1
# This line needs xrdp 0.9.16 or later
#chansrvport=DISPLAY(0)
```
   This section sets up an xrdp connection type which authenticates a local user and then connects to a passwordless VNC session.
- restart the xrdp service
- Log in on the machine console. For Ubuntu, during login set the `Ubuntu on Xorg` session type.
- In a terminal, run x11vnc with `x11vnc -nopw -N forever`
- From your RDP client, connect to the local machine, and select the `localvnc` session type. Screen should look a bit like this:-
   ![image](https://user-images.githubusercontent.com/30179339/209172097-8d5e06b2-d70e-4bf1-ad34-d56f2253e30e.png)
- You should be able to log in and connect to the existing session.

If you can get that working, you should have a good idea of what is possible.

**Comment by apenngrace** [comment]
I appreciate the instructions.  Like I mentioned, I'm using Microsoft Remote Desktop for MacOS.  It looks like your screen shot is from a different RDP client.

I think this works well enough to do what I need to do, even if performance is not optimal. At least it works.

There is the "Could not acquire session name on bus" error that I'm seeing, but I can avoid it by rebooting.  Perhaps you can make a note of it as a known issue.

Thanks again.
