### ISSUE TITLE
Can't login to desktop normally (without xrdp) anymore - Debian Bullseye

### ISSUE THREAD

**Issue by Saya47** [neutrinolabs/xrdp#2483]
Hello, it seems that the version of xrdp that is included in the repositories for Debian Bullseye is not compatible with it. Therefore, I had to build and install the new version of xrdp from source using this link: https://c-nergy.be/downloads/xRDP/xrdp-installer-1.4.4.zip. This fixed the issue with the RDP, but now I am unable to log in to my laptop without using RDP. When I enter my password for my user account, it takes me to a black screen and remains there indefinitely. Sometimes, if I wait for a few hours, it will eventually show me my desktop. Can you please help me with this issue? Thank you.

**Comment by matt335672** [comment]
We can't help with issues introduced by 3rd part scripts I'm afraid.

As far as I am aware, the author of the link you include has made no effort to engage with this project. I suggest you talk to them about any incompatibilities their script has introduced with your system.

We'll be more than happy to help with any compatibility issues you might have with Bullseye. That should be fine out-of-the-box.

**Comment by Saya47** [comment]
Hello @matt335672 
Yes but I have completely read the script myself, it doesn't do anything out of ordinary, I think the xrdp is at fault here, it must have broken gdm3 or x11 somehow because startx doesn't run automatically on boot anymore and when I run it myself from a ssh, it takes like a minute for the desktop to show up, I've already removed and reinstalled `dbus-x11 gdm3 gnome-session gnome-session-bin gnome-shell-extensions` but to no success, so I asked here for help. Thanks.
ps: don't mind the Remote Desktop Protocol (RDP) part on previous post, I was grammar checking with ChatGPT. lol

**Comment by bmullan** [comment]
@Saya47 

When you executed the cenergy script did you use the "-s -c" command line options to compile from Source (-c) and Enable Sound (-s).

At a minimum use (-c) to make sure you build/compile xrdp from latest source.

**Comment by Saya47** [comment]
Hello @bmullan 
Yes I did, I first installed it with `-c` and was happy that it works but I thought maybe I should enable sound redirection too so I ran the script again with `-c -s`.
I've been trying for days to remotely connect to my laptop, I tried vnc servers such as tightvnc and then xrdp, to be honest I don't know what broke my system.

**Comment by bmullan** [comment]
@Saya47 
_Are you using freerdp as the client?

If so... did you install the freerdp-wayland or freerdp-x11?   They are both in the repository for Ubuntu.

Also, if using freerdp what command line are you using?   Something like the following:_
**example - all one line**
xfreerdp /cert-ignore +gfx /rfx /rfx-mode:video /video /bpp:32 /dynamic-resolution +clipboard /sound:sys:pulse,format:1,quality:high,rate:44100,latency:50 /v:<ip of desktop server>

obviously port 3389 or whatever you are using must be open

**Comment by Saya47** [comment]
@bmullan 
I'm using a Windows laptop's RDP client to connect to my Debian running laptop. So, no I didn't install freerdp, but I did a check and it seems to be installed for some reason:
```
$ apt list --installed | grep freerdp
libfreerdp-client2-2/stable,now 2.3.0+dfsg1-2+deb11u1 amd64 [installed,automatic]
libfreerdp2-2/stable,now 2.3.0+dfsg1-2+deb11u1 amd64 [installed,automatic]
```
