### ISSUE TITLE
Using the host's keyboard and mouse to control the client?

### ISSUE THREAD

**Issue by bweh** [neutrinolabs/xrdp#2486]
I currently have the xrdp server running on Peppermint OS, and I am able to connect to it using various RDP clients. I want to control the client's keyboard and mouse input using the keyboard and mouse of the server (a laptop).

I tried using [x2x](https://github.com/dottedmag/x2x/), but it doesn't seem to work for this case since the displays are on the same server. Any ideas?

[Here](https://superuser.com/questions/639469/rdp-using-hosts-keyboard-and-mouse) is a related thread but for Windows.

**Comment by matt335672** [comment]
@bweh - I'm afraid it doesn't work that way. The host's keyboard and mouse are not accessible from the xrdp server. That would be a security nightmare, to put it mildly!
