### ISSUE TITLE
xrdp black screen w/ error both lxde/xfce

### ISSUE THREAD

**Issue by maurerr** [neutrinolabs/xrdp#2488]
So I've been trying for the past few days to get xrdp for xfce (or lxde) on my headless Intel nuc n3060 running ubuntu 22.04 server but after almost getting it to work I'm in lost phase without proper error messages maybe this community will help me sort it out - see:
[.xsession-errors](https://paste.debian.net/1265919/)
[.xorgxrdp.12.log](https://paste.debian.net/1265920/)
[xrdp.log](http://sprunge.us/CXSu5b)
[xrdp-sesman.log](http://sprunge.us/qtExDD)

**Comment by matt335672** [comment]
@maurerr - can you please post a consistent set of log files? Some of these refer to display 11 and some to display 12. Consequently it's impossible to know if errors between the files tie up.

```
sudo systemctl stop xrdp xrdp-sesman
sudo truncate -s 0 /var/log/xrdp.log /var/log/xrdp-sesman.log
rm ~/.xsession-errors ~/.xorgxrdp*.log
```

- Reboot
- Try to connct with rdp client once
- Post log files again. If some are missing, please say so.

**Comment by maurerr** [comment]
Hi @matt335672 please see new logs below, thanks
[/var/log/xrdp.log](http://sprunge.us/g6I6SM)
[/var/log/xrdp-sesman.log](http://sprunge.us/n9eP0i)
[.xsession-errors](http://sprunge.us/c2QPyA)
[.xorgxrdp.13.log](http://sprunge.us/N7SJNm)
[/home/opengen/.cache/lxsession/LXDE/run.log](http://sprunge.us/3WX0f4)

**Comment by matt335672** [comment]
@maurerr - there's nothing wrong with those logs I can see. The session is being started by xrdp.

Let's see if we can get any display at all out of this. Install `xterm` with `sudo apt install xterm`. Then edit `/etc/xrdp/startwm.sh` and somewhere near the top add the lines:-

```
# Debugging only
xterm
```

That should give us an x terminal before the session starts when you next log in.

**Comment by maurerr** [comment]
thanks @matt335672 that worked - I can get to an xterminal inside an rdp session but both lxde and xfce fail to start there as well :( (in the x terminal)

**Comment by matt335672** [comment]
Well, that suggests that xrdp is working.

Can you check that you've installed the complete desktop? Use `sudo apt get install lubuntu-desktop` for lxde or `sudo apt get install xubuntu-desktop` for xfce.

Another thing you can try is from the xterm type `startlxde` or `startxfce4` and see if you get any errors.

**Comment by maurerr** [comment]
managed to get `mate-deskptop` running installing it via `sudo tasksel` then just added:
```
echo "mate-session" > ~/.xsession
XDG_DATA_DIRS=/usr/share/mate:/usr/share/mate:/usr/local/share
XDG_DATA_DIRS=${XDG_DATA_DIRS}:/usr/share:/var/lib/snapd/desktop
cat <<EOF > ~/.xsessionrc
export XDG_SESSION_DESKTOP=mate
export XDG_DATA_DIRS=${XDG_DATA_DIRS}
export XDG_CONFIG_DIRS=/etc/xdg/xdg-mate:/etc/xdg
EOF
```
thank you very much for your kind support @matt335672
