### ISSUE TITLE
I was able to access droplet every day via remote desktop, but today I can't

### ISSUE THREAD

**Issue by kaanguven** [neutrinolabs/xrdp#2495]
I can still connect to my Droplet with Putty, but I was able to log in to Droplet every day via Remote desktop even though I didn’t change anything. Today I can’t.

My logs when i can connect RD with XRDP:
![3](https://user-images.githubusercontent.com/83061705/211808962-8782c2f7-e0f8-4531-8bbd-8b13aeaf24d0.PNG)

Now when i cant connect RD with XRDP:
![Ekran Alıntısı](https://user-images.githubusercontent.com/83061705/211809029-de6116db-67a3-4be9-a044-dc8910374f17.PNG)

and my XRDP Service :

![asf](https://user-images.githubusercontent.com/83061705/211809108-8b628f3b-a133-431a-bc1c-531102650a0e.PNG)

I bought remote desktop from digitalocean and install ubuntu 20.04, I connect without any problem for the first 5 to 15 days, then Remote Desktop gives me the following error:

“Remote Desktop can't connect to the remote computer for one of these reasons:

Remote access to the server is not enabled The remote computer is turned off The remote computer is not available on the net

I tried to clean installion of XRDP, restart service, Firewall etc. Please an someone who has encountered or knows about this tell me how to solve it?

**Comment by matt335672** [comment]
Simply put, your client is unable to find the xrdp server on the network. The xrdp service looks to be working perfectly well.

Possible reasons:-
- your firewall is not allowing TCP access on port 3389
- your cloud provider is not allowing access to port 3389 for security reasons.
- Your RDP client is not connecting to the same name or IP address as your putty client.

You can install nmap on your Windows client and use it to see if port 3389 is reachable on the server

**Comment by kaanguven** [comment]
> Simply put, your client is unable to find the xrdp server on the network. The xrdp service looks to be working perfectly well.
> 
> Possible reasons:-
> 
> * your firewall is not allowing TCP access on port 3389
> * your cloud provider is not allowing access to port 3389 for security reasons.
> * Your RDP client is not connecting to the same name or IP address as your putty client.
> 
> You can install nmap on your Windows client and use it to see if port 3389 is reachable on the server

Yes, I opened 3389 port but I think they blocked port 3389. Also, thanks for the answer, maybe it's off-topic, but can I connect to Remote Desktop with another port?

**Comment by matt335672** [comment]
You can set up the listening port in xrdp.ini, and then set the connecting port from the RDP client. So yes, you can use any port you like. It will need to be one you know is open though.

**Comment by kaanguven** [comment]
> You can set up the listening port in xrdp.ini, and then set the connecting port from the RDP client. So yes, you can use any port you like. It will need to be one you know is open though.

I think I'm on the right way! I changed the port in XRDP, I changed the default 3389 port used by RDP over Windows. When connecting, I connect as ip:NewPort, but after I enter the username and password, it turns black and closes instantly.

**Comment by matt335672** [comment]
Make sure you're not logged in to the graphical console on the Droplet with the same user. That can cause this.

If you're still struggling, after a login attempt this command will generate a complete system log for the last two minutes:-

```
sudo journalctl -S -2m
```

**Comment by kaanguven** [comment]
> Make sure you're not logged in to the graphical console on the Droplet with the same user. That can cause this.
> 
> If you're still struggling, after a login attempt this command will generate a complete system log for the last two minutes:-
> 
> ```
> sudo journalctl -S -2m
> ```

Man, I solved the problem in this way idk its right but i changed port in XRDP.ini (3389 to some other port) and then in my windows i changed my RDP default port in regedit. It solved my problem.

**Comment by matt335672** [comment]
Great.

Can we close this one then?

**Comment by kaanguven** [comment]
> Great.
> 
> Can we close this one then?

Yes please, thank you for your effort
