### ISSUE TITLE
scard_pcsc_init fails when user home directory is a network-based folder

### ISSUE THREAD

**Issue by kamakazikamikaze** [neutrinolabs/xrdp#2501]
### User Information

* Version: 0.9.21.1-1
* OS: Kali Rolling

### Error Message

```
xrdp-chansrv[####]: [ERROR] scard_pcsc_init: trans_listen failed for port /home/example/username/.pcsc11/pcscd.comm
xrdp-chansrv[####]: [ERROR] scard_pcsc_check_wait_objs: g_lis trans_check_wait_objs error
. . . <Previous entry is duplicated 20-30 times> . . .
```

### Additional Information

Network is isolated and does not use Smart Cards for authentication, therefore no immediate impact is noted at this time. However, with 10-20 users connecting or re-connecting throughout the day, the logs are being saturated with these error messages.

User home directories are mounted via [libpam_mount](https://manpages.debian.org/testing/libpam-mount/pam_mount.8.en.html) from a CIFS share on user login to "sync" files between hosts. Unix socket files do not appear to be supported on CIFS/SMB volumes.

Other applications use environment variables to determine where to create per-process or cache files, i.e. [XDG_CACHE_HOME](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), which work around this issue. XRDP appears to rely on the `HOME` environment variable instead.

https://github.com/neutrinolabs/xrdp/blob/9b846b7b7e6b0b59b0b0d9f048acd9e04c65a082/sesman/chansrv/smartcard_pcsc.c#L1856-L1858

### Suggestion/Request

I understand that this is likely an edge case and will be incredibly low priority given the minimal amount of impact. That said, a long-term solution may be to use a new environment variable and default to the user's `HOME` if `NULL`. For example:

```c
home = g_getenv("XRDP_PCSC_IPC_DIR");
if (home == 0)
{
  home = g_getenv("HOME");
}
disp = g_display_num; 
g_snprintf(g_pcsclite_ipc_dir, 255, "%s/.pcsc%d", home, disp); 
```

[Link to g_getenv for your convenience.](https://docs.gtk.org/glib/func.getenv.html)

This would allow a system administrator to place `export XRDP_PCSC_IPC_DIR=/tmp/.xrdp_$UID/` in the `/etc/xrdp/startwm.sh` file to specify the environment variable per-user for each initialized RDP session.

**Comment by matt335672** [comment]
Hi @kamakazikamikaze 

Thanks for raising this, and in particular for your detailed report and analysis. The pcsc code is in need of a *lot* of work at the moment, but there's a certainly a chance to improve this here.

The idea of the code is that it looks like the library provided by the  [PCSC project](/LudovicRousseau/PCSC). That way, applications which use PCSC-lite can use an xrdp smartcard instead. At least that's the idea!

Looking at the PCSC-lite code, the socket is called (by default) "$HOME/pcscd.com" unless PCSCLITE_CSOCK_NAME is defined (code is [here](https://github.com/LudovicRousseau/PCSC/blob/d47fda236fca13d6286ce74034076f418409ba56/src/winscard_msg.c#L85-L106)). So personally, I think a better approach would be to mirror the code in PCSC itself and use `PCSCLITE_CSOCK_NAME` as the name of the socket.

This is a somewhat bigger change, but it's pretty easy to test and get in.

How does that sound to you?

**Comment by kamakazikamikaze** [comment]
That would work perfectly! The change would operate just the same.

**Comment by matt335672** [comment]
One a closer examination, this is slightly more awkward than I realised.

Given the PCSC code is slightly moribund and only works with patches applied, I think a simpler solution to the problem in hand is simply to not try to use the PCSC wait object if it wasn't created properly in the first place. This will still produce the first error, but not the repeated other errors.

I considered adding configuration items to the config files, but until the PCSC code is working a lot better, I don't want to paint myself into a corner by doing that.

@kamakazikamikaze - I've realised a workaround to the above for now is to disable smartcard redirection on the client side. At least that's how the code looks. Give it a go and let me know.

**Comment by kamakazikamikaze** [comment]
> @kamakazikamikaze - I've realised a workaround to the above for now is to disable smartcard redirection on the client side. At least that's how the code looks. Give it a go and let me know.

I had to look into client settings on Windows and finally found it. Disabling the forwarding of a Smart Card reader from the client does indeed mitigate the issue.

It seems a network-wide solution for now will be to push a change to default client settings via GPO for Windows and adjust our Linux client images which is completely doable.

Thank you for looking into this! I look forward to seeing your changes in the next release.

**Comment by matt335672** [comment]
Thanks for feeding back - it will be useful to someone, somewhere.
