### ISSUE TITLE
xrdp dscp datagrams value

### ISSUE THREAD

**Issue by O-ring** [neutrinolabs/xrdp#2510]
Hello everyone,

I would like to know if there is a way to set the dscp value of the packets that are sent by xrdp?

Thanks in advance

Marco

**Comment by metalefty** [comment]
You can use any packer filter to rewrite packets.

**Comment by O-ring** [comment]
Hello,

thanks for the reply.

It would be useful to have an option to have packets
generated with the desired dscp color, without having
to go to the bother of netfilter or other L3s (which
are not always available).

Marco

**Comment by matt335672** [comment]
@O-ring - what's your use-case which isn't satisfied by using iptables/nftables/pf, or indeed even using an edge router?

My understanding of this sort of thing is generally managed at network boundaries, and consequently it's best set by a network administrator. To that end, it would seem best to have it handled by the tools that those people know about, in the locations where they expect it to be.

**Comment by O-ring** [comment]
Hello Matt,

For application servers, I don't compile the linux
kernel with netfilter support, so the dscp field
cannot be changed.

Openssh allows configuring dscp using the IPQoS
option.

I believe that it is the application that sets the
dscp field to the appropriate value, not the network
devices.

I think this issue can be closed and thank you for
discussing it.

Marco

**Comment by metalefty** [comment]
I understand your opinion but we have no plan to implement that right now. There are some workarounds to achieve the same result and we have limited development resources.

Thanks for raising the discussion and understanding. It is a very good point.
