### ISSUE TITLE
Black display after authentication using Ubuntu 22.04

### ISSUE THREAD

**Issue by rapier1** [neutrinolabs/xrdp#2515]
I'm having a persistent error across multiple Ubuntu installs using xrdp from MacOS client (thincast, microsoft RDP, etc).

The problem seems to be that xrdp cannot connect to sesman. 

```
[20230125-12:13:09] [INFO ] connecting to sesman ip 127.0.0.1 port 3350
[20230125-12:13:13] [INFO ] xrdp_mm_connect: connect failed trying again...
[20230125-12:13:17] [INFO ] xrdp_mm_connect: connect failed trying again...
[20230125-12:13:21] [INFO ] xrdp_mm_connect: connect failed trying again...
[20230125-12:13:25] [INFO ] xrdp_mm_connect: connect failed trying again...
[20230125-12:13:25] [ERROR] xrdp_wm_log_msg: Error connecting to sesman: 127.0.0.1 port: 3350
[20230125-12:13:25] [INFO ] Error connecting to sesman: 127.0.0.1 port: 3350
```

semsan is running and I get the following when I check the status;

```sudo ps -e -o pid,netns,command | grep xrdp
sudo ss -alp 'sport = 3350'
sudo nmap -p 3350 127.0.0.1
   1765 4026531840 /usr/sbin/xrdp-sesman
   1797 4026531840 /usr/sbin/xrdp
  39287 4026531840 /usr/sbin/xrdp
  43977 4026531840 grep --color=auto xrdp

Netid        State          Recv-Q         Send-Q                      Local Address:Port                 Peer Address:Port        Process        
tcp          LISTEN         0              2                      [::ffff:127.0.0.1]:3350                            *:*            users:(("xrdp-sesman",pid=1765,fd=7))

Starting Nmap 7.80 ( https://nmap.org ) at 2023-01-25 12:16 EST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000042s latency).

PORT     STATE SERVICE
3350/tcp open  findviatv

Nmap done: 1 IP address (1 host up) scanned in 0.08 seconds
```

The firewall, ufw, is disabled. I can connect to sesman using telnet and that does show up in the sesman log. However, actual RDP session requests do not show up in xrdp-sesman.log. All of the configuration files are the default. 

Any suggestions because I'm at a loss here. 

Thanks!

**Comment by akarl10** [comment]
Do you get a login screen? If yes and the black screen shows up after logging in normally means sesman was about to start a session. you can check that if you try to authenticate with wrong credentials. in that case you should get a message. That message comes from sesman, so you would know that sesman is working.

for xrdp to work "oob" you need to make sure at least two things on ubuntu:
1) install xorgxrdp (the "display" driver for virtual sessions)
2) make sure you are not logged in locally with the same user

1 is not strictly needed, but without xorgxrdp you would need to change some defaults they ship

**Comment by matt335672** [comment]
I'm wondering if this is a problem with IPv6.

The code to connect to a local port says it's using 127.0.0.1, but sometimes it lies and uses ::1 instead.

@rapier1 - have you got ::1 in your loopback interface?

**Comment by matt335672** [comment]
No response form OP - closing

**Comment by palves** [comment]
FWIW, I had the same problem after disabling IPv6 by putting:

net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1

... in /etc/sysctl.conf.

However, on this machine I have a custom network setup that is started later after boot, and so I was ending up with ipv6 addresses in that connection anyhow.   That is confirmed by doing "ip address".  You should not see any inet6 addresses.  If you do, that's the problem.   I fixed it by disabling ipv6 from grub instead, with this in /etc/default/grub:

GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"
GRUB_CMDLINE_LINUX="ipv6.disable=1"

and then "sudo update-grub" (and reboot).

Hopefully it'll help someone else.

edit: This was on 22.04.3 Ubuntu, btw.  I was using the /etc/sysctl.conf method on Ubuntu 20.04 successfully, and noticed this problem when I was replicating the configuration on a new machine with the newer ubuntu.
