### ISSUE TITLE
The display refresh rate doesn’t go above 50 Hz.

### ISSUE THREAD

**Issue by issuefiler** [neutrinolabs/xrdp#2546]
# The issue

I can’t get the remote X session to have the display refresh rate of 60 Hz.

# The environment

 The RDP client is Windows 10, and the `xrdp` server is on Debian Bookworm with KDE 5. Both physical machines are _wired_, with Category 5e unshielded twisted pair cables, to the same home router on my desk. For graphics, the Debian server machine has _Intel® UHD Graphics 730_ (integrated graphics), and the Windows client has _GeForce GTX 1080 Ti_. My 4K monitor supports refresh rates of up to 60 Hz.

## The RDP server machine

![The RDP server](https://user-images.githubusercontent.com/57908781/218270949-2a6aecd0-c58c-4f66-80a4-b8b374200496.png)
![The RDP server](https://user-images.githubusercontent.com/57908781/218272212-790b4671-5ad8-4054-bbb9-d34167fe20da.png)

## The RDP client machine

![The RDP client](https://user-images.githubusercontent.com/57908781/218270988-543b43b4-9f2c-4697-93ad-ae41cc57fc53.png)

-----

I’ve found [someone with a 4K display who suffered this issue 9 months ago](https://askubuntu.com/q/1408326).

**Comment by issuefiler** [comment]
How do I get the remote display to have the 60 Hz refresh rate?

**Comment by matt335672** [comment]
The 50Hz is simply a notional value. It bears no relation to the display rate at all. You can ignore it.

Your monitor refresh rate is set by your Windows client.

**Comment by issuefiler** [comment]
That means it's actually receiving 60 Hz remote screen data from the Debian RDP server, right? Thank you for your answer.
