### ISSUE TITLE
Sitcky keys compiling xrdp with the xorg-x11 driver on RHEL 6.6

### ISSUE THREAD

**Issue by therevoman** [neutrinolabs/xrdp#255]
We are using XRDP for an internal cloud project at work with VMWare VM's running RHEL 6.6.  We've been successfully using x11rdp and recently discovered the xorg driver.  Initially it was promising, however we have run into a huge usability error.  Whenever the keyboard is used, the last key is not registering the keyup event and ends up repeating that key endlessly.  Another keypress cancels the key repetition, but this makes it difficult to use.  I am a Java developer but am willing to work through the issue with a little guidance and have successfully contributed to a bug fix in the x11rdp project.  

Thanks in advance.

**Comment by jsorg71** [comment]
is the problem gone when you run
xset r off
in the session.

**Comment by therevoman** [comment]
Yes actually.  That worked when using the xorg driver.

However using "xset r off" is un-needed when using the x11rdp server.

**Comment by jsorg71** [comment]
Ok, X11rdp has code that does what "xset r off" does.
When in an RDP session, you never what the server to handle key repeats.
This need to be merged into Xorg driver.

**Comment by therevoman** [comment]
With a little guidance I could track the problem down and submit a patch.

**Comment by jsorg71** [comment]
I did a quick push sha1
0a3868424f34ff81332f04d891d67f11f6c153ba
I did no testing :)

**Comment by jsorg71** [comment]
ok, I did minimal testing, seems to work

**Comment by therevoman** [comment]
Pulling down devel branch now.  Will close bug once I've confirmed the repeat is fixed.  

Thanks!!!

**Comment by therevoman** [comment]
Looks good.  Thanks for the quick response!

**Comment by therevoman** [comment]
What's the process for moving this fix into the "master" branch?
