### ISSUE TITLE
VScode not opening with XRDP+Remmina

### ISSUE THREAD

**Issue by hubbertsmith** [neutrinolabs/xrdp#2562]
baseline -- ubuntu baremetal 22.04 -- install VScode, works fine
docker container --xrdp  ubuntu 22.04 -- access with Remmina, apps work fine: gedit, anaconda-navigator, spyder, jyperlab works fine
same docker container -- xrdp ubuntu 22.04 access with remmina, install VScode, but code does not launch
(perhaps there is some config problem with display setting? )
thanks so much for your help

p.s. for security reasons, it is necessary to run VScode within the container
(I am aware that VScode client can access remote repository, there are reasons why this isnt right for us)
sincerely, thanks for your help

**Comment by unstabler** [comment]
have you tried launch vscode with `code --verbose`?

**Comment by hubbertsmith** [comment]
thanks for your response (I deeply appreciate it) --- this is within a running container, accessed via XRDP
(base) hannah@fabd73e3bda0:~$ code --version
1.75.1
441438abd1ac652551dbe4d408dfcec8a499b8bf
x64
(base) hannah@fabd73e3bda0:~$ code --verbose
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
(base) hannah@fabd73e3bda0:~$

**Comment by hubbertsmith** [comment]
I ran
$ code --no-sandbox
and it came up.

**Comment by hubbertsmith** [comment]
do you happen to know of a global variable to change?
so $code will work?
our goal is to secure the container (no one has syspriv, or needs sysprivs)
thanks so much for your help -- gamsahabnida

**Comment by matt335672** [comment]
@hubbertsmith - you might have more luck looking for similar discussions around Chrome, as VSCode is an electron app:-

In particular, this is an interesting read, and has some other links you might care to examine:-

https://stackoverflow.com/questions/59087200/google-chrome-failed-to-move-to-new-namespace

From what I can see, you're essentially trying to nest containers here. You may be better off concentrating your hardening efforts on the outer container and using `code --no-sandbox` within that.

I'm closing this, as it isn't an xrdp issue per-se. However, if anyone else has good ideas, I'm sure they can add them.

**Comment by hubbertsmith** [comment]
thanks so much for your help
and for your efforts in this exceptional tech

***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>
