### ISSUE TITLE
Issues with libcommon.so dlopen,dlclose,dlsym

### ISSUE THREAD

**Issue by fang64** [neutrinolabs/xrdp#257]
There seems to be a compile issue under CentOS 7.The error excerpt is supplied below this was done against both master and devel branches it doesn't seem to matter. Interestingly RHEL 7 will compile, I'm not entirely sure what is different between the compilers.

gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I../common -I../libxrdp -I/usr/include    -DXRDP_CFG_PATH=\"/etc/xrdp\" -DXRDP_SBIN_PATH=\"/usr/sbin\" -DXRDP_SHARE_PATH=\"/usr/share/xrdp\" -DXRDP_PID_PATH=\"/var/run\" -DXRDP_LIB_PATH=\"/usr/lib64/xrdp\" -DXRDP_NODEBUG  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c xrdp_encoder.c
/bin/sh ../libtool  --tag=CC   --mode=link gcc -DXRDP_CFG_PATH=\"/etc/xrdp\" -DXRDP_SBIN_PATH=\"/usr/sbin\" -DXRDP_SHARE_PATH=\"/usr/share/xrdp\" -DXRDP_PID_PATH=\"/var/run\" -DXRDP_LIB_PATH=\"/usr/lib64/xrdp\" -DXRDP_NODEBUG  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -L/usr/lib -Wl,-rpath -Wl,/usr/lib -Wl,-z,relro  -o xrdp funcs.o lang.o xrdp_bitmap.o xrdp.o xrdp_cache.o xrdp_font.o xrdp_listen.o xrdp_login_wnd.o xrdp_mm.o xrdp_painter.o xrdp_process.o xrdp_region.o xrdp_wm.o xrdp_encoder.o ../common/libcommon.la ../libxrdp/libxrdp.la
libtool: link: gcc -DXRDP_CFG_PATH=\"/etc/xrdp\" -DXRDP_SBIN_PATH=\"/usr/sbin\" -DXRDP_SHARE_PATH=\"/usr/share/xrdp\" -DXRDP_PID_PATH=\"/var/run\" -DXRDP_LIB_PATH=\"/usr/lib64/xrdp\" -DXRDP_NODEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wl,-rpath -Wl,/usr/lib -Wl,-z -Wl,relro -o .libs/xrdp funcs.o lang.o xrdp_bitmap.o xrdp.o xrdp_cache.o xrdp_font.o xrdp_listen.o xrdp_login_wnd.o xrdp_mm.o xrdp_painter.o xrdp_process.o xrdp_region.o xrdp_wm.o xrdp_encoder.o  -L/usr/lib ../common/.libs/libcommon.so ../libxrdp/.libs/libxrdp.so /home/fang64/rpmbuild/BUILD/neutrinolabs-xrdp-ee89984/common/.libs/libcommon.so -lcrypto -lssl -lpthread -Wl,-rpath -Wl,/usr/lib64/xrdp
../common/.libs/libcommon.so: error: undefined reference to 'dlopen'
../common/.libs/libcommon.so: error: undefined reference to 'dlclose'
../common/.libs/libcommon.so: error: undefined reference to 'dlsym'

**Comment by fang64** [comment]
RHEL 7 "gcc -v"
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.3/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC)

vs 

CentOS 7 "gcc -v"
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.3/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC)

**Comment by itamarjp** [comment]
theres no issue compiling for Centos 7, I am also have built a rpm here.

https://copr-be.cloud.fedoraproject.org/results/itamarjp/xrdp/epel-7-x86_64/xrdp-0.9.0-1.fc22/

you probably missing some packages that's required to build xrdp on your system, look roots log and you will see a list of packages required, closing this, since it's not a xrdp bug

**Comment by fang64** [comment]
itamarjp,

As a followup that wasn't the case, it seems I had some issues within my environment. I ultimately ended up rebuilding the machine since there were some issues with updating. It did not indicate any missing packages in the log, so it may have been a system state issue. I actually went back and built it in a VM to confirm it was my end.
