### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by sparkwj** [neutrinolabs/xrdp#2571]
I have try to uninstall and reinstall the xrdp , but nothing happens, always the same error

● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; preset: enabled)
     Active: active (running) since Fri 2023-03-03 11:24:14 CST; 7min ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 440 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 470 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 500 (xrdp)
      Tasks: 1 (limit: 2279)
     Memory: 2.0M
        CPU: 35ms
     CGroup: /system.slice/xrdp.service
             └─500 /usr/sbin/xrdp

Mar 03 11:31:06 alisrv xrdp[2689]: [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
Mar 03 11:31:06 alisrv xrdp[2689]: [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Mar 03 11:31:06 alisrv xrdp[2689]: [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP>
Mar 03 11:31:06 alisrv xrdp[2689]: [ERROR] SSL_accept: I/O error
Mar 03 11:31:06 alisrv xrdp[2689]: [ERROR] trans_set_tls_mode: ssl_tls_accept failed
Mar 03 11:31:06 alisrv xrdp[2689]: [ERROR] xrdp_sec_incoming: trans_set_tls_mode failed
Mar 03 11:31:06 alisrv xrdp[2689]: [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
Mar 03 11:31:06 alisrv xrdp[2689]: [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
Mar 03 11:31:06 alisrv xrdp[2689]: [ERROR] xrdp_iso_send: trans_write_copy_s failed
Mar 03 11:31:06 alisrv xrdp[2689]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed

**Comment by matt335672** [comment]
What client are you trying to connect from?

It's possible the client sn't happy with your SSL configuration. Set `security_layer=rdp` in xrdp.ini and see what happens.
