### ISSUE TITLE
sesman does not add groups when using ldap

### ISSUE THREAD

**Issue by karas84** [neutrinolabs/xrdp#258]
My configuration is as follows:
- Ubuntu 14.04.2
- OpenLDAP Client

I'm authenticating using a server in the local network and defined some groups to add to the ones provided by ldap by modifying `/etc/security/group.conf`.

Then I added `auth     required      pam_group.so use_first_pass` to `/etc/pam.d/common-auth` (using `pam-auth-update` and the right config file in `/usr/share/pam-configs`).

Loggin in locally or remotely with ssh results in groups being added but using xrdp no group is added. Here is my `xrdp-sesman`:

```
#%PAM-1.0
@include common-auth
@include common-account
@include common-session
@include common-password
```

**Comment by moobyfr** [comment]
IIRC, pam_group is bugged with policykit 
https://bugs.launchpad.net/ubuntu/+source/policykit-1/+bug/1281700

**Comment by karas84** [comment]
Thank you, I had indeed some problem with policykit and now I know why. Have also found some workaround to a couple (but not all) of my problems. Still, what is happening with sesman is a little bit different. Even if policykit is bugged and ldap users were not considered, when ssh-ing into my machine calling id would show the groups, even id username is working fine. With sesman groups are not added at all. Probably this is related to policykit, I do't know, and in such case there is nothing you can do about it. Still I wanted to stress this since sesman is the only pam module that "seems" to ignore the pam_group directive (even though in my case it doesn's do any good because of that bug...). Anyway thanks for your help.

**Comment by metalefty** [comment]
Not a xrdp issue, closing.
