### ISSUE TITLE
 Can't open PID file /run/xrdp/xrdp.pid (yet?) after start: Operation not permitted

### ISSUE THREAD

**Issue by testeqaleo** [neutrinolabs/xrdp#2589]
Hi I installed xrdp and tested it and this worked until pc restart

behavior:
When I try to login, when opening the xrdp login screen
when i type my username, passwords and click ok
nothing happened

after looking up how to fix it i found the same behavior here "https://github.com/neutrinolabs/xrdp/issues/1630"

and i "found fix" here "https://stackoverflow.com/questions/66445899/xrdp-can%C2%B4t-open-pid-file-run-xrdp-xrdp-pid-yet-after-start-operation-not-pe"

In my case i have to restar service always after reboot
Always run
sudo systemctl stop xrdp
sudo systemctl start xrdp
after that i can do login

linux mint cinnamon 21.1

xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: >
     Active: active (running) since Sat 2023-03-11 14:10:51 -03; 37s ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 799 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, s>
    Process: 817 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/>
   Main PID: 847 (xrdp)
      Tasks: 1 (limit: 9195)
     Memory: 1.5M
        CPU: 15ms
     CGroup: /system.slice/xrdp.service
             └─847 /usr/sbin/xrdp

systemd[1]: Starting xrdp daemon...
systemd[1]: xrdp.service: Can't open PID file /run/xrdp/xr>
systemd[1]: Started xrdp daemon.
xrdp[847]: [INFO ] starting xrdp with pid 847
xrdp[847]: [INFO ] address [0.0.0.0] port [3389] mode 1
xrdp[847]: [INFO ] listening to port 3389 on 0.0.0.0
xrdp[847]: [INFO ] xrdp_listen_pp done
lines 1-21/21 (END)...skipping...
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-03-11 14:10:51 -03; 37s ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 799 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 817 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 847 (xrdp)
      Tasks: 1 (limit: 9195)
     Memory: 1.5M
        CPU: 15ms
     CGroup: /system.slice/xrdp.service
             └─847 /usr/sbin/xrdp

systemd[1]: Starting xrdp daemon...
systemd[1]: xrdp.service: Can't open PID file /run/xrdp/xrdp.pid (yet?) after start: Operation not permitted
systemd[1]: Started xrdp daemon.
xrdp[847]: [INFO ] starting xrdp with pid 847
xrdp[847]: [INFO ] address [0.0.0.0] port [3389] mode 1
xrdp[847]: [INFO ] listening to port 3389 on 0.0.0.0
xrdp[847]: [INFO ] xrdp_listen_pp done

When i am tryng do login is here where broken
[ERROR] xrdp_wm_log_msg: Error connecting to sesman: 127.0.0.1 port: 3350
 
I dot know why that port was choosed but seem after "restart" service got right port

I installed this way

sudo apt install xrdp xorgxrdp
sudo apt install xserver-xorg-input-all
sudo adduser xrdp ssl-cert
sudo ufw allow 3389/tcp
echo env -u SESSION_MANAGER -u DBUS_SESSION_BUS_ADDRESS cinnamon-session>~/.xsession

**Comment by matt335672** [comment]
The error you've currently got is that `xrdp-sesman` isn't starting.

What do you get for `sudo systemctl status xrdp-sesman`?

**Comment by testeqaleo** [comment]
Hi i got with "sudo systemctl status xrdp-sesman"

xrdp-sesman.service - xrdp session manager
     Loaded: loaded (/lib/systemd/system/xrdp-sesman.service; enabled; vendor p>
     Active: active (running) since Tue 2023-03-14 14:26:37 -03; 50s ago
       Docs: man:xrdp-sesman(8)
             man:sesman.ini(5)
    Process: 793 ExecStart=/usr/sbin/xrdp-sesman $SESMAN_OPTIONS (code=exited, >
   Main PID: 814 (xrdp-sesman)
      Tasks: 1 (limit: 9195)
     Memory: 1.4M
        CPU: 6ms
     CGroup: /system.slice/xrdp-sesman.service
             └─814 /usr/sbin/xrdp-sesman

systemd[1]: Starting xrdp session manager...
xrdp-sesman[814]: [INFO ] starting xrdp-sesman with pid 814
systemd[1]: Started xrdp session manager.

**Comment by testeqaleo** [comment]
i did run again i got bit diference

Here not working i had to restart service
xrdp-sesman.service - xrdp session manager
     Loaded: loaded (/lib/systemd/system/xrdp-sesman.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-03-14 14:57:24 -03; 1min 36s ago
       Docs: man:xrdp-sesman(8)
             man:sesman.ini(5)
    Process: 792 ExecStart=/usr/sbin/xrdp-sesman $SESMAN_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 809 (xrdp-sesman)
      Tasks: 1 (limit: 9195)
     Memory: 1.4M
        CPU: 6ms
     CGroup: /system.slice/xrdp-sesman.service
             └─809 /usr/sbin/xrdp-sesman

systemd[1]: Starting xrdp session manager...
xrdp-sesman[809]: [INFO ] starting xrdp-sesman with pid 809
systemd[1]: Started xrdp session manager.

**Comment by matt335672** [comment]
Looks like sesman is running but xrdp can't reach it.

What is `ListenAddress` set to in `/etc/xrdp/sesman.ini`? If it's not `0.0.0.0`, try setting it to that.

**Comment by testeqaleo** [comment]
> Looks like sesman is running but xrdp can't reach it.
> 
> What is `ListenAddress` set to in `/etc/xrdp/sesman.ini`? If it's not `0.0.0.0`, try setting it to that.

Thks that solved ,where had my localhost when changed to 0 solved. tks alot.
