### ISSUE TITLE
Support resizing in VNC session

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#259]
Some implementation of VNC supports resizing.  AFAIK, [TigerVNC](http://tigervnc.org/) is the only implementation of VNC which supports resizing. It is particularly used in RedHat and its clones.  For this reason, I think it is probably possible to support resizing in VNC session now.

@jsorg71 Jay, I remember you said that sesman-Xvnc backend will be removed in #162.  Do you think this is worth to work on? Of course it depends which VNC implementation users are using. Resizing in VNC session is still convenient.

Please see also this movie I captured. How screen resizing works.
https://www.youtube.com/watch?v=ZP5fzVs5NZQ

**Comment by metalefty** [comment]
To implement VNC session resizing, session policy must be changed.
If VNC supports resizing, session policy will be UB. If not, UBD.

**Comment by metalefty** [comment]
@jsorg71
Jay, I have one question. xorgxrdp driver works only on x86 (or x86-64), right?
If so, there's one big reason to implement vnc resizing.

**Comment by bolkedebruin** [comment]
@metalefty @jsorg71 is xvmc still up for removal? xrdp over xorg is extremely slow for us

resizing would definitely be appreciated.

**Comment by jsorg71** [comment]
@metalefty 
xorgxrdp should work on all platforms that X11rdp works on.
Of course x86 works and I test on Debian Sparc and even FreeBSD x86-64.

**Comment by jsorg71** [comment]
The issue with Xvnc is that it's based on old Xorg code and even XFree86.
If there is a modern Xvnc and I think TurboVNC is maintained we can keep Xvnc support.

The reason xorgxrdp is slow is that all the order drawing is not brought over from X11rdp yet.
It really only does codec mode well currently.  I need some time to merge the rest.

**Comment by metalefty** [comment]
Nice. I found some x86 asm code in xorgxrdp repo.
That's why I misunderstood  xorgxrdp is designed only for x86.

When it comes to choosing modern VNC, TigerVNC or TurboVNC will be good choise.

**Comment by metalefty** [comment]
Now Debian has package of xorgxrdp.  I'm inclined to replace VNC  with xorgxrdp rather than adding resizing to VNC session.

https://packages.debian.org/sid/xorgxrdp

**Comment by bolkedebruin** [comment]
For is xorgrdp has been considerably slower than using Vnc sessions @metalefty

**Comment by metalefty** [comment]
Reopened. I'm working on vnc resizing based on awesome work by @matt335672 #1343.

**Comment by bolkedebruin** [comment]
@metalefty how is this going? @matt335672 patch works great and while I understand you not wanting “code=0/1” that can be done iteratively? We are applying this patch now out of tree as the speedup over xorg is tremendous (for some reason)

**Comment by metalefty** [comment]
Now VNC resizing is available with v0.9.14.
