### ISSUE TITLE
Mouse events don't work after the program runs for a while

### ISSUE THREAD

**Issue by bestxpp** [neutrinolabs/xrdp#2594]
version:  0.9.5

Looks like mouse events travel through the application's window,The application's window does not handle mouse events，
Mouse events are responded to on the desktop

After running for a while, this problem will appear occasionally

Is there any solution for this problem

**Comment by matt335672** [comment]
That's a very old version.

xrdp isn't aware of any applications on the desktop - it just delivers mouse events via the X server. So if you're getting desktop events it's hard to see how a problem with your application can be an xrdp problem. I think you need to look at the X11 infrastructure in general.

I can give you a few pointers in what you can look for:-
1) Try running `xev` and see if the events are getting to that.
2) `xdotool` can let you do things like send mouse up events to your application. See [this stackexchange question](https://unix.stackexchange.com/questions/59141/find-x-org-pointer-grab-owner) for more info.

**Comment by bestxpp** [comment]
Ok, thank you for your reply, the xserver I use is xorgxrdp，Should I go from xorgxrdp to solve this problem?

**Comment by matt335672** [comment]
You can try using the Xvnc backend to see if the same thing happens. Or try using the pointers above

**Comment by bestxpp** [comment]
ok thanks i will try
