### ISSUE TITLE
Removing restart and shutdown buttons in the GUI accessed by xrdp

### ISSUE THREAD

**Issue by D3vil0p3r** [neutrinolabs/xrdp#2597]
Hello, I'm using Arch Linux with GNOME 43. Currently, when I connect by xrdp to the Desktop Environment, I have the following power buttons:
![image](https://user-images.githubusercontent.com/83867734/226080429-3736201c-1b2d-4c52-a34a-e3a1bee35ac6.png)

Is it possible to disable/remove the Restart and Shutdown buttons when I connect to the environment by xrdp? If so, how can it be reached?

**Comment by matt335672** [comment]
You should be able to do that with polkit. In fact I'm surprised they're enabled at all.

Try reverting the changes you've made with #2578 and see what happens.

**Comment by D3vil0p3r** [comment]
> You should be able to do that with polkit. In fact I'm surprised they're enabled at all.
> 
> Try reverting the changes you've made with #2578 and see what happens.

I tried to work on `/usr/share/polkit-1/actions/org.freedesktop.login1.policy` but, even if I set to `no` all entries related to the reboot or shutdown, or deleting them, the buttons remain there. Maybe the buttons in GNOME Control Center are managed in another way?

**Comment by matt335672** [comment]
Maybe, but if so I can't find any info about it.

Your best bet in my opinion is to enable polkit logging and see exactly what is going on. That might give you some more clues.
