### ISSUE TITLE
Keyboard mapping problem in Xrdp

### ISSUE THREAD

**Issue by moobyfr** [neutrinolabs/xrdp#26]
Hi
I didn't find in documentation
How is the keyboard handled after X is starting ?

I use a french keyboard the layout is loaded correctly 
(local keymap file for 0x040c found and dosen't match built in keymap, using local keymap file)
I can log in with the correct keyboard.
But after the X session start, the keyboard goes back in  a qwerty mode.
I have to make a "setxkbmap fr" to get the normal layout again

I'm using the current git version, the server is a lucid 10.4 , with xcfe4. I use xrdp+X11rdp
the client is rdesktop, (but I get the same with xfreerdp). The client use the option to specify the layout

I think that X11rdp is missing an option to load a default keymap
Or something must be done to change the keymap with XKB when X11rdp start

Emmanuel

**Comment by HenryJacques** [comment]
I do have the same problem (still with latest dev branch) also.
I also have to force a "setxkbmap fr"....

**Comment by moobyfr** [comment]
No more reproducible on latest version
