### ISSUE TITLE
[Not able to RDP] Blue screen after trying to connect to xrdp server on Ubuntu 22.04 using RDP client (Remote Desktop Viewer) on Ubuntu 20.04 

### ISSUE THREAD

**Issue by salil-mehta** [neutrinolabs/xrdp#2602]
Hello,
I am getting blue screen after login screen and cannot see a thing of remote desktop on the ubuntu 22.04 server. It is running xrdp and I am trying to connect to it using "Remote Desktop Viewer" client on another Ubuntu 20.04 machine.

![Screenshot from 2023-03-22 02-30-49](https://user-images.githubusercontent.com/11980211/226787320-98ceb222-b819-458c-bd5f-d0460e2f371c.png)
![Screenshot from 2023-03-22 02-30-39](https://user-images.githubusercontent.com/11980211/226787324-f7f8b7ae-fb15-42ab-bcd8-37bb91400f5d.png)

Please find output of 4 log files  soon after above blue screen appears.

Log1: sudo tail -f 1000 /var/log/xrdp-sesman.log
Log 2:  sudo tail -f 1000  /var/log/xrdp.log
Log 3:   sudo tail -f ~/.xorgxrdp.10.log -n 100
Log 4: sudo journalctl -S -1m > sysctl-journal.txt

Log 1: 
$ sudo tail -f 1000 /var/log/xrdp-sesman.log
Output:
[...]
[20230322-02:43:41] [INFO ] Socket 8: AF_INET6 connection received from ::1 port 38614
[20230322-02:43:42] [INFO ] Terminal Server Users group is disabled, allowing authentication
[20230322-02:43:42] [INFO ] ++ created session (access granted): username maverick, ip ::ffff:10.11.12.24:39748 - socket: 12
[20230322-02:43:42] [INFO ] starting Xorg session...
[20230322-02:43:42] [INFO ] Starting session: session_pid 124249, display :10.0, width 1920, height 1080, bpp 24, client ip ::ffff:10.11.12.24:39748 - socket: 12, user name maverick
[20230322-02:43:42] [INFO ] [session start] (display 10): calling auth_start_session from pid 124249
[20230322-02:43:42] [ERROR] sesman_data_in: scp_process_msg failed
[20230322-02:43:42] [INFO ] Starting X server on display 10: /usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log  
[20230322-02:43:42] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20230322-02:43:42] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20230322-02:43:42] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20230322-02:43:42] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20230322-02:43:43] [INFO ] Session started successfully for user maverick on display 10
[20230322-02:43:43] [INFO ] Starting the xrdp channel server for display 10
[20230322-02:43:43] [INFO ] Starting the default window manager on display 10: /etc/xrdp/startwm.sh
[20230322-02:43:43] [INFO ] Session in progress on display 10, waiting until the window manager (pid 124264) exits to end the session
[20230322-02:43:44] [WARN ] Window manager (pid 124264, display 10) exited with non-zero exit code 255 and signal 15. This could indicate a window manager config problem
[20230322-02:43:44] [WARN ] Window manager (pid 124264, display 10) exited quickly (1 secs). This could indicate a window manager config problem
[20230322-02:43:44] [INFO ] Calling auth_stop_session and auth_end from pid 124249
[20230322-02:43:44] [INFO ] Terminating X server (pid 124265) on display 10
[20230322-02:43:44] [INFO ] Terminating the xrdp channel server (pid 124385) on display 10
[20230322-02:43:44] [INFO ] X server on display 10 (pid 124265) returned exit code 0 and signal number 0
[20230322-02:43:44] [INFO ] xrdp channel server for display 10 (pid 124385) exit code 0 and signal number 0
[20230322-02:43:45] [INFO ] cleanup_sockets:
[20230322-02:43:45] [INFO ] ++ terminated session:  username maverick, display :10.0, session_pid 124249, ip ::ffff:10.11.12.24:39748 - socket: 12
[...]

Log 2:
$ sudo tail -f 1000  /var/log/xrdp.log
Output:
[...]
[20230322-02:43:31] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.11.12.24 port 39748
[20230322-02:43:31] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230322-02:43:31] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230322-02:43:31] [INFO ] Connected client computer name: vault
[20230322-02:43:31] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20230322-02:43:31] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20230322-02:43:32] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x00000000]
[20230322-02:43:32] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [us] options []
[20230322-02:43:32] [INFO ] TLS connection established from ::ffff:10.11.12.24 port 39748: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384
[20230322-02:43:32] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20230322-02:43:32] [WARN ] Dynamic Virtual Channel named 'drdynvc' not found, channel not initialized
[20230322-02:43:32] [WARN ] Cannot find keymap file /etc/xrdp/km-00000000.ini
[20230322-02:43:32] [WARN ] Cannot find keymap file /etc/xrdp/km-00000000.ini
[20230322-02:43:32] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20230322-02:43:32] [WARN ] local keymap file for 0x00000000 found and doesn't match built in keymap, using local keymap file
[20230322-02:43:41] [INFO ] connecting to sesman ip 127.0.0.1 port 3350
[20230322-02:43:41] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20230322-02:43:42] [INFO ] sesman connect ok
[20230322-02:43:42] [INFO ] sending login info to session manager, please wait...
[20230322-02:43:42] [INFO ] xrdp_wm_log_msg: login successful for display 10
[20230322-02:43:42] [INFO ] login successful for display 10
[20230322-02:43:42] [INFO ] loaded module 'libxup.so' ok, interface size 10296, version 4
[20230322-02:43:42] [INFO ] started connecting
[20230322-02:43:42] [INFO ] lib_mod_connect: connecting via UNIX socket
[20230322-02:43:42] [INFO ] lib_mod_log_peer: xrdp_pid=123436 connected to X11rdp_pid=124265 X11rdp_uid=1000 X11rdp_gid=1000 client_ip=::ffff:10.11.12.24 client_port=39748
[20230322-02:43:42] [INFO ] connected ok
[...]

Log 3:
maverick@orion:~$ sudo tail -f ~/.xorgxrdp.10.log -n 100

[  1683.492] rdpmouseControl: what 0
[  1683.492] rdpmouseDeviceInit:
[  1683.493] rdpmouseCtrl:
[  1683.493] rdpRegisterInputCallback: type 1 proc 0x7fe1aab393b0
[  1683.493] (**) xrdpMouse: (accel) keeping acceleration scheme 1
[  1683.493] (**) xrdpMouse: (accel) acceleration profile 0
[  1683.493] (**) xrdpMouse: (accel) acceleration factor: 2.000
[  1683.493] (**) xrdpMouse: (accel) acceleration threshold: 4
[  1683.493] rdpmouseControl: what 1
[  1683.493] rdpmouseDeviceOn:
[  1683.493] (II) Using input driver 'XRDPKEYB' for 'xrdpKeyboard'
[  1683.493] (**) Option "CoreKeyboard"
[  1683.493] (**) xrdpKeyboard: always reports core events
[  1683.493] rdpkeybPreInit: drv 0x55bebd278ce0 info 0x55bebd58b700, flags 0x0
[  1683.493] (II) XINPUT: Adding extended input device "xrdpKeyboard" (type: Keyboard, id 7)
[  1683.493] rdpkeybControl: what 0
[  1683.493] rdpkeybDeviceInit:
[  1683.513] rdpkeybChangeKeyboardControl:
[  1683.513] rdpkeybChangeKeyboardControl: autoRepeat on
[  1683.513] rdpRegisterInputCallback: type 0 proc 0x7fe1aab33d50
[  1683.513] rdpkeybControl: what 1
[  1683.513] rdpkeybDeviceOn:
[  1683.526] (II) config/udev: Adding input device Power Button (/dev/input/event0)
[  1683.526] (II) AutoAddDevices is off - not adding device.
[  1683.526] (II) config/udev: Adding drm device (/dev/dri/card0)
[  1683.526] (II) xfree86: Adding drm device (/dev/dri/card0)
[  1683.526] (II) Platform probe for /sys/devices/pci0000:00/0000:00:1c.7/0000:01:00.1/drm/card0
[  1683.527] (EE) systemd-logind: failed to take device /dev/dri/card0: Operation not permitted
[  1683.528] (II) config/udev: Adding input device Logitech K330 (/dev/input/event2)
[  1683.528] (II) AutoAddDevices is off - not adding device.
[  1683.529] (II) config/udev: Adding input device Logitech M215 2nd Gen (/dev/input/event1)
[  1683.529] (II) AutoAddDevices is off - not adding device.
[  1683.530] (II) config/udev: Adding input device Logitech M215 2nd Gen (/dev/input/mouse0)
[  1683.530] (II) AutoAddDevices is off - not adding device.
[  1683.538] rdpDeferredRandR:
[  1683.538] rdpResizeSession: width 1024 height 768
[  1683.538]   calling RRScreenSizeSet
[  1683.538] rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
[  1683.538] rdpRRGetInfo:
[  1683.538]   screen resized to 1024x768
[  1683.540]   RRScreenSizeSet ok 1
[  1683.540] rdpResizeSession: width 1920 height 1080
[  1683.540]   calling RRScreenSizeSet
[  1683.540] rdpRRScreenSetSize: width 1920 height 1080 mmWidth 508 mmHeight 286
[  1683.540] rdpRRGetInfo:
[  1683.540]   screen resized to 1920x1080
[  1683.544]   RRScreenSizeSet ok 1
[  1683.544] rdpClientConGotConnection:
[  1683.544] rdpClientConGotConnection: g_sck_accept ok new_sck 9
[  1683.544] rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
[  1683.544] rdpAddClientConToDev: adding first clientCon 0x55bebd5b69f0
[  1683.544] rdpClientConProcessMsgVersion: version 0 0 0 1
[  1683.545] rdpClientConProcessScreenSizeMsg: set width 1920 height 1080 bpp 16
[  1683.545] rdpClientConProcessScreenSizeMsg: shmemid 6 shmemptr 0x7fe19e365000
[  1683.545] rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1920 cy 1080
[  1683.613] rdpInDeferredRepeatCallback:
[  1683.668] rdpkeybChangeKeyboardControl:
[  1683.668] rdpkeybChangeKeyboardControl: autoRepeat off
[  1684.609] rdpClientConProcessMsgClientInfo:
[  1684.609]   got client info bytes 7072
[  1684.609]   jpeg support 0
[  1684.609]   offscreen support 0
[  1684.610]   offscreen size 0
[  1684.610]   offscreen entries 0
[  1684.610]   client can not do offscreen to offscreen blits
[  1684.610]   client can do new(color) cursor
[  1684.610]   client can not do multimon
[  1684.610] rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
[  1684.610] rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1920 height 1080
[  1684.610] rdpLoadLayout: keylayout 0x00000000 variant  display 10
[  1684.610] rdpkeybChangeKeyboardControl:
[  1684.610] rdpkeybChangeKeyboardControl: autoRepeat on
[  1684.611] rdpkeybChangeKeyboardControl:
[  1684.611] rdpkeybChangeKeyboardControl: autoRepeat on
[  1684.710] rdpInDeferredRepeatCallback:
[  1684.710] rdpkeybChangeKeyboardControl:
[  1684.710] rdpkeybChangeKeyboardControl: autoRepeat off
[  1684.711] rdpInDeferredRepeatCallback:
[  1684.711] rdpkeybChangeKeyboardControl:
[  1684.711] rdpkeybChangeKeyboardControl: autoRepeat off
[  1685.522] rdpmouseControl: what 2
[  1685.522] rdpmouseDeviceOff:
[  1685.523] rdpkeybControl: what 2
[  1685.523] rdpkeybDeviceOff:
[  1685.525] rdpkeybControl: what 3
[  1685.525] rdpkeybUnInit: drv 0x55bebd278ce0 info 0x55bebd58b700, flags 0x0
[  1685.525] rdpUnregisterInputCallback: proc 0x7fe1aab33d50
[  1685.525] rdpmouseControl: what 3
[  1685.525] rdpmouseUnInit: drv 0x55bebd27a390 info 0x55bebd588580, flags 0x0
[  1685.525] rdpUnregisterInputCallback: proc 0x7fe1aab393b0
[  1685.526] rdpCloseScreen:
[  1685.526] xorgxrdpDownDown:
[  1685.527] xorgxrdpDownDown: 1
[  1685.527] rdpClientConDeinit:
[  1685.527] rdpClientConDeinit: disconnecting clientCon
[  1685.527] rdpClientConDisconnect:
[  1685.527] rdpRemoveClientConFromDev: removing clientCon 0x55bebd5b69f0
[  1685.527] rdpClientConDeinit: deleting file /run/xrdp/sockdir/xrdp_display_10
[  1685.527] rdpClientConDeinit: deleting file /run/xrdp/sockdir/xrdp_disconnect_display_10
[  1685.529] (II) Server terminated successfully (0). Closing log file.

Log 4: Output of  $ sudo journalctl -S -1m > sysctl-journal.txt

[...]
Mar 22 02:51:47 orion nextcloud.nextcloud-fixer[162516]: Nextcloud is not installed - only a limited number of commands are available                                  
Mar 22 02:51:47 orion xrdp[161168]: [INFO ] connecting to sesman ip 127.0.0.1 port 3350
Mar 22 02:51:47 orion xrdp-sesman[1557]: [INFO ] Socket 8: AF_INET6 connection received from ::1 port 54810
Mar 22 02:51:48 orion xrdp[161168]: [INFO ] xrdp_wm_log_msg: sesman connect ok  
Mar 22 02:51:48 orion xrdp[161168]: [INFO ] sesman connect ok                   
Mar 22 02:51:48 orion xrdp[161168]: [INFO ] sending login info to session manager, please wait...
Mar 22 02:51:48 orion xrdp-sesman[1557]: [INFO ] Terminal Server Users group is disabled, allowing authentication
Mar 22 02:51:48 orion xrdp-sesman[1557]: [INFO ] ++ created session (access granted): username maverick, ip ::ffff:10.11.12.24:40668 - socket: 12
Mar 22 02:51:48 orion xrdp-sesman[1557]: [INFO ] starting Xorg session...          
Mar 22 02:51:48 orion xrdp-sesman[1557]: [INFO ] Starting session: session_pid 162592, display :10.0, width 1920, height 1080, bpp 24, client ip ::ffff:10.11.12.24:40668 - socket: 12, user name maverick
Mar 22 02:51:48 orion xrdp-sesman[162592]: [INFO ] [session start] (display 10): calling auth_start_session from pid 162592
Mar 22 02:51:48 orion nextcloud.nextcloud-fixer[162591]: Nextcloud is not installed - only a limited number of commands are available
Mar 22 02:51:48 orion xrdp-sesman[1557]: [ERROR] sesman_data_in: scp_process_msg failed
Mar 22 02:51:48 orion xrdp[161168]: [INFO ] xrdp_wm_log_msg: login successful for display 10
Mar 22 02:51:48 orion xrdp[161168]: [INFO ] login successful for display 10        
Mar 22 02:51:48 orion xrdp-sesman[162592]: pam_unix(xrdp-sesman:session): session opened for user maverick(uid=1000) by (uid=0)
Mar 22 02:51:48 orion systemd-logind[1373]: New session c5 of user maverick.       
Mar 22 02:51:48 orion systemd[1]: Started Session c5 of User maverick.          
Mar 22 02:51:48 orion xrdp-sesman[1557]: [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
Mar 22 02:51:48 orion xrdp[161168]: [INFO ] loaded module 'libxup.so' ok, interface size 10296, version 4
Mar 22 02:51:48 orion xrdp-sesman[162601]: [INFO ] Starting X server on display 10: /usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
Mar 22 02:51:48 orion xrdp[161168]: [INFO ] started connecting                  
Mar 22 02:51:48 orion xrdp[161168]: [INFO ] lib_mod_connect: connecting via UNIX socket
Mar 22 02:51:48 orion xrdp[161168]: [INFO ] lib_mod_log_peer: xrdp_pid=161168 connected to X11rdp_pid=162601 X11rdp_uid=1000 X11rdp_gid=1000 client_ip=::ffff:10.11.12.24 client_port=40668
Mar 22 02:51:48 orion xrdp-sesman[162600]: [INFO ] Found X server running at /tmp/.X11-unix/X10
Mar 22 02:51:48 orion xrdp-sesman[162592]: [INFO ] Found X server running at /tmp/.X11-unix/X10
Mar 22 02:51:48 orion xrdp[161168]: [INFO ] connected ok     
[...]

Added below as part of the file "/etc/xrdp/startwm.sh" on Uubntu 22.04 server

[...]
export GNOME_SHELL_SESSION_MODE=ubuntu
export XDG_CURRENT_DESKTOP=ubuntu:GNOME
unset DBUS_SESSION_BUS_ADDRESS
unset XDG_RUNTIME_DIR
[...]

Any help would be highly appreciated!

Many thanks
Salil

**Comment by matt335672** [comment]
Please remove the stuff you've added to `startwm.sh`. That won't be helping to get you started. Once you've got something working, by all means play around.

Your desktop doesn't appear to be starting.

1) Make sure you aren't logged in already as maverick on the machine. Running xrdp and a console login as the same user [isn't supported](/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-log-the-same-user-on-on-the-graphical-console-and-over-xrdp-at-the-same-time). Use a separate user for xrdp.
2) Have you got anything in `~maverick/.xsession-errors`?

**Comment by iysheng** [comment]
I meet the same issue with debian12 bootkworm on aarch64 platform. I just get a blue screen as:

![Image](https://github.com/user-attachments/assets/d2f553c6-d68f-4cd3-8b10-2b279ecb322e)

when I check the xrdp and xrdp-sesman.service I can get as
``` bash
radxa@orion-o6:~$ sudo systemctl status xrdp-sesman.service
● xrdp-sesman.service - xrdp session manager
     Loaded: loaded (/lib/systemd/system/xrdp-sesman.service; enabled; preset: enabled)
     Active: active (running) since Fri 2025-04-04 20:32:15 CST; 4min 30s ago
       Docs: man:xrdp-sesman(8)
             man:sesman.ini(5)
    Process: 19813 ExecStart=/usr/sbin/xrdp-sesman $SESMAN_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 19814 (xrdp-sesman)
      Tasks: 1 (limit: 17494)
     Memory: 1.6M
        CPU: 182ms
     CGroup: /system.slice/xrdp-sesman.service
             └─19814 /usr/sbin/xrdp-sesman

Apr 04 20:32:47 orion-o6 xrdp-sesman[20677]: [INFO ] Session in progress on display 10, waiting until the window manager (pid 20678) exits to end the session
Apr 04 20:36:43 orion-o6 xrdp-sesman[19814]: [INFO ] Socket 12: AF_INET6 connection received from ::1 port 50026
Apr 04 20:36:43 orion-o6 xrdp-sesman[19814]: [INFO ] Terminal Server Users group is disabled, allowing authentication
Apr 04 20:36:43 orion-o6 xrdp-sesman[19814]: [INFO ] ++ created session (access granted): username radxa, ip ::ffff:192.168.99.141:58482 - socket: 12
Apr 04 20:36:43 orion-o6 xrdp-sesman[19814]: [INFO ] starting Xorg session...
Apr 04 20:36:43 orion-o6 xrdp-sesman[19814]: [INFO ] Starting session: session_pid 26989, display :11.0, width 1920, height 1200, bpp 24, client ip ::ffff:192.168.99.141:58482 - socket: 12, user name radxa
Apr 04 20:36:43 orion-o6 xrdp-sesman[26989]: [INFO ] [session start] (display 11): calling auth_start_session from pid 26989
Apr 04 20:36:43 orion-o6 xrdp-sesman[19814]: [ERROR] sesman_data_in: scp_process_msg failed
Apr 04 20:36:43 orion-o6 xrdp-sesman[26989]: pam_unix(xrdp-sesman:session): session opened for user radxa(uid=1000) by (uid=0)
Apr 04 20:36:43 orion-o6 xrdp-sesman[19814]: [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
radxa@orion-o6:~$ sudo systemctl status xrdp.service
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; preset: enabled)
     Active: active (running) since Fri 2025-04-04 20:32:16 CST; 5min ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 19815 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 19823 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 19824 (xrdp)
      Tasks: 2 (limit: 17494)
     Memory: 26.2M
        CPU: 414ms
     CGroup: /system.slice/xrdp.service
             ├─19824 /usr/sbin/xrdp
             └─26862 /usr/sbin/xrdp

Apr 04 20:36:38 orion-o6 xrdp[26862]: [WARN ] local keymap file for 0x00000804 found and doesn't match built in keymap, using local keymap file
Apr 04 20:36:43 orion-o6 xrdp[26862]: [INFO ] connecting to sesman on 127.0.0.1:3350
Apr 04 20:36:43 orion-o6 xrdp[26862]: [INFO ] xrdp_wm_log_msg: sesman connect ok
Apr 04 20:36:43 orion-o6 xrdp[26862]: [INFO ] sesman connect ok
Apr 04 20:36:43 orion-o6 xrdp[26862]: [INFO ] sending login info to session manager. Please wait...
Apr 04 20:36:43 orion-o6 xrdp[26862]: [INFO ] xrdp_wm_log_msg: login successful for user radxa on display 11
Apr 04 20:36:43 orion-o6 xrdp[26862]: [INFO ] login successful for user radxa on display 11
Apr 04 20:36:43 orion-o6 xrdp[26862]: [INFO ] loaded module 'libxup.so' ok, interface size 10296, version 4
Apr 04 20:36:43 orion-o6 xrdp[26862]: [INFO ] started connecting
Apr 04 20:36:43 orion-o6 xrdp[26862]: [INFO ] lib_mod_connect: connecting via UNIX socket
```

**Comment by iysheng** [comment]
after I upgrade xrdp with this repo , still failed but the status service changed with
``` bash
radxa@orion-o6:~$ sudo systemctl status xrdp-sesman.service
● xrdp-sesman.service - xrdp session manager
     Loaded: loaded (/lib/systemd/system/xrdp-sesman.service; enabled; preset: enabled)
     Active: active (running) since Fri 2025-04-04 20:53:10 CST; 34s ago
       Docs: man:xrdp-sesman(8)
             man:sesman.ini(5)
   Main PID: 8631 (xrdp-sesman)
      Tasks: 1 (limit: 17494)
     Memory: 748.0K
        CPU: 60ms
     CGroup: /system.slice/xrdp-sesman.service
             └─8631 /usr/local/sbin/xrdp-sesman --nodaemon

Apr 04 20:53:20 orion-o6 xrdp-sesexec[8905]: gkr-pam: stashed password to try later in open session
Apr 04 20:53:20 orion-o6 xrdp-sesexec[8905]: [INFO ] TerminalServerUsers group tsusers doesn't exist. Access granted for radxa
Apr 04 20:53:20 orion-o6 xrdp-sesexec[8905]: [INFO ] Access permitted for user: radxa
Apr 04 20:53:20 orion-o6 xrdp-sesman[8631]: [INFO ] Received sys login status for radxa : logged in
Apr 04 20:53:20 orion-o6 xrdp-sesman[8631]: [INFO ] Received request from xrdp to create a session for user radxa
Apr 04 20:53:20 orion-o6 xrdp-sesexec[8905]: pam_lastlog(xrdp-sesman:session): unknown option: quiet
Apr 04 20:53:20 orion-o6 xrdp-sesexec[8905]: [INFO ] PAM: Last login: Fri Apr  4 20:49:51 CST 2025 from 192.168.99.141 on :10
Apr 04 20:53:20 orion-o6 xrdp-sesexec[8905]: pam_unix(xrdp-sesman:session): session opened for user radxa(uid=1000) by (uid=0)
Apr 04 20:53:20 orion-o6 xrdp-sesexec[8905]: gkr-pam: gnome-keyring-daemon didn't start properly
Apr 04 20:53:30 orion-o6 xrdp-sesman[8631]: [INFO ] sesman: Session on display :10 has finished.
```

**Comment by iysheng** [comment]
Though I cann't connect with xorg, I found I can connect with xvnc success.

![Image](https://github.com/user-attachments/assets/cb73627b-1fc4-4352-86f4-a369a0e55571)

@matt335672  Can you please check with this ?

**Comment by matt335672** [comment]
@iysheng - this is a closed issue. Please open another one if you require some help.
