### ISSUE TITLE
login display0 on correct username and password

### ISSUE THREAD

**Issue by ProBlox42R** [neutrinolabs/xrdp#2605]
I get "_login display0_" on correct username and password. I am using ubuntu 22.04 and xrdp.

### PLEASE HELP!

**Comment by matt335672** [comment]
@ProBlox42R - this post makes no sense.

Where are you getting what exactly? "login display0" doesn't mean anything to me.

**Comment by ProBlox42R** [comment]
When logging on xrdp but no sence because I installed a new OS (Windows 10)
