### ISSUE TITLE
github ssh keys changes

### ISSUE THREAD

**Issue by jsorg71** [neutrinolabs/xrdp#2610]
Looks like github mistake
https://www.theregister.com/2023/03/24/github_changes_its_ssh_host/
You should see this error now if you are using ssh to git pull
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

**Comment by matt335672** [comment]
I spotted that in theregister too.

Only the RSA key is affected.

The github blog has [this entry](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/) which contains the fingerprint for the new key.

**Comment by metalefty** [comment]
I use an RSA key for SSH user identification to GitHub but it is a different context from this leak. I've not been affected by this incident.
