### ISSUE TITLE
Website (xrdp.org) is down

### ISSUE THREAD

**Issue by vscfreire** [neutrinolabs/xrdp#2618]
Sorry, I don't know if this is the correct place to report this, and I haven't been able to find any previous reference to this.

The xrdp.org website appears to be down. It looks like it doesn't resolve (DNS problem), even though the domain is registered (hasn't expired).

According to some monitoring tools, it has been down since March 9th ([https://www.saashub.com/xrdp-status](https://www.saashub.com/xrdp-status)).

Regards.

**Comment by jsorg71** [comment]
Thanks, yea, I noticed that too.  I looked at the DNS entry for xrdp.org, it looks the same.

Host name | Type | TTL | Data
www.xrdp.org | CNAME | 1 hour | neutrinolabs.github.io.

Has anything changed with the gh-pages branch?

**Comment by jsorg71** [comment]
I changed CNAME file in gh-pages branch.  Does it work now?

**Comment by matt335672** [comment]
Works from the UK over IPv4 and IPv6.

**Comment by vscfreire** [comment]
It's working from here.

However, only "www.xrdp.org" is working, "xrdp.org" (without the "www") is not. I don't know if it was working before.

**Comment by metalefty** [comment]
Generally, CNAME cannot be added to the zone apex. xrdp.org is not a website in design.
