### ISSUE TITLE
[ERROR] trans_set_tls_mode: ssl_tls_accept failed

### ISSUE THREAD

**Issue by Kofa1** [neutrinolabs/xrdp#2628]
I'm trying to connect to my Arch linux host laptop with mstsc.exe on Vista laptop through LAN, IP set to 192.168.1.2 and 192.168.1.3 correspondingly. 
Vista gives out an error `An authentication error has occurred (Code: 0x80090302)` almost immediately, without opening the xrdp login screen and without entering any login information.

Running `systemctl status xrdp.service` on Arch, gives 
```
Apr 07 18:04:56 archlinux xrdp[491]: [INFO ] Socket 12: AF_INET6 connection received from ::ffff:192.168.1.3 port 49189
Apr 07 18:04:56 archlinux xrdp[4763]: [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
Apr 07 18:04:56 archlinux xrdp[4763]: [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Apr 07 18:04:56 archlinux xrdp[4763]: [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|RDP], selected [SSL]
Apr 07 18:04:56 archlinux xrdp[4763]: [ERROR] SSL_accept: Failure in SSL library (protocol error?)
Apr 07 18:04:56 archlinux xrdp[4763]: [ERROR] SSL: error:0A0000BF:SSL routines::no protocols available
Apr 07 18:04:56 archlinux xrdp[4763]: [ERROR] trans_set_tls_mode: ssl_tls_accept failed
Apr 07 18:04:56 archlinux xrdp[4763]: [ERROR] xrdp_sec_incoming: trans_set_tls_mode failed
Apr 07 18:04:56 archlinux xrdp[4763]: [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
Apr 07 18:04:56 archlinux xrdp[4763]: [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
```

Also tried with Windows 10, it connects to the xrdp login screen and after a few minutes of the blank green-ish screen gives out 
```
connecting to sesman on 127.0.0.1:3350
sesman connect ok
sending login info to session manager. Please wait...
login successful for user [] on display 10
started connecting
connection problem, giving up
some problem
Error connecting to user session
```

**Comment by Kofa1** [comment]
> vgvvvvvv[ERROR] trans_set_tls_mode: ssl_tls_accept failed[ERROR] trans_set_tls_mode: ssl_tls_accept failed[ERROR] trans_set_tls_mode: ssl_tls_accept failed[ERROR] trans_set_tls_mode: ssl_tls_accept failed[ERROR] trans_set_tls_mode: ssl_tls_accept failed``

**Comment by matt335672** [comment]
@Kofa1 - if you're on Arch, this is probably #2253 or #2569. Check for #2253 first, then #2569. Please report back.

**Comment by elhananjair** [comment]
@matt335672 I am getting the same error and couldn't connect to a remote fedora PC.

![image](https://github.com/neutrinolabs/xrdp/assets/69236638/9e58ceaf-f2ff-4068-9d7f-0e4b430199f9)

**Comment by matt335672** [comment]
This doesn't look like the same fault.

Please raise a separate issue and fill in the issue template. The screenshot above doesn't contain nearly enough info.
