### ISSUE TITLE
Locale Encoding Issue? Broken Font

### ISSUE THREAD

**Issue by habibi1195** [neutrinolabs/xrdp#2638]
Hi, I'm running an XRDP session via WSL2-Ubuntu (Windows 10). 
I'm running into an issue where the text in the GUI is completely broken. I confirmed that the Windows encoding is UTF-8, and the Ubuntu locale is also UTF-8. Any thoughts would be appreciated. 

Here is what this looks [like:](https://i.imgur.com/cXHiFMd.png)

**Comment by matt335672** [comment]
What backend are you using?

If you're using Xorg can you try with Xvnc? You'll need to install `tigervnc-standalone-server` if it isn't already installed. That might help us to narrow down what exactly isn't working correctly. Xvnc is a relatively dumb protocol that doesn't understand fonts as such.
