### ISSUE TITLE
I have some error when I check the xrdp status. 

### ISSUE THREAD

**Issue by DeokchangSeo** [neutrinolabs/xrdp#2642]
Hi all,

I am a new IT admin for a small company.
We use Xmanager and XRDP for work which is circuit design.

Recently, I've found errors like below but I don't know what make this error.
For the TLSv1.3, I know the issue and I can fix it.

However, other errors? I have no idea.
System is all working fine, everyone can access to the server via Xmanager and XRDP.
Does anyone can help me to solve the issue?

OS : RHEL7
Client : Windows 11
gem, lightdm are enabled
Desktop env : GNOME

[****@**** ~]# systemctl status xrdp
● xrdp.service - xrdp daemon
   Loaded: loaded (/usr/lib/systemd/system/xrdp.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2023-04-20 11:51:42 KST; 21h ago
     Docs: man:xrdp(8)
           man:xrdp.ini(5)
 Main PID: 49486 (xrdp)
   CGroup: /system.slice/xrdp.service
           ├─49486 /usr/sbin/xrdp --nodaemon
           ├─71344 /usr/sbin/xrdp --nodaemon
           └─73210 /usr/sbin/xrdp --nodaemon

Apr 21 09:00:44 umtka xrdp[796]: [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Apr 21 09:00:44 umtka xrdp[796]: [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
Apr 21 09:00:44 umtka xrdp[796]: [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|RDP], selected [SSL]
Apr 21 09:00:44 umtka xrdp[796]: [ERROR] SSL_accept: I/O error
Apr 21 09:00:44 umtka xrdp[796]: [ERROR] trans_set_tls_mode: ssl_tls_accept failed
Apr 21 09:00:44 umtka xrdp[796]: [ERROR] xrdp_sec_incoming: trans_set_tls_mode failed
Apr 21 09:00:44 umtka xrdp[796]: [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
Apr 21 09:00:44 umtka xrdp[796]: [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
Apr 21 09:00:44 umtka xrdp[796]: [ERROR] xrdp_iso_send: trans_write_copy_s failed
Apr 21 09:00:44 umtka xrdp[796]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed

**Comment by matt335672** [comment]
Hi @DeokchangSeo

Welcome to the world of systems admin!

If I understand you correctly, everything is working correctly, but you're concerned about these error messages.

These are (currently) quite normal behaviour, and nothing to worry about.

What is probably happening is this:-
- RDP client connects to xrdp
- xrdp sends RDP client its TLS certificate.
- RDP client drops the connection while it displays a user dialog asking the user what to do. This generates the errors.
- RDP client reconnects normally.

See also #2040 which explains this in more detail.

We're aware that logging ERROR for these dropped connections isn't ideal, and we hope to address this in a future release.

Does that answer your question?

**Comment by DeokchangSeo** [comment]
Hi @matt335672 

Thank you for your reply.
Yes I'm excited with the new role ^^

For the question above, yup I have concerned about the error message.
Because I have 2 servers (use both RHEL7, nfs connected) and the message occurs only one server.
The other one has no error when I put the command "systemctl status xrdp" that shows me like below.

Apr 24 08:25:41 umtkd xrdp[58825]: [INFO ] VNC receiving server init
Apr 24 08:25:41 umtkd xrdp[58825]: [INFO ] VNC receiving pixel format
Apr 24 08:25:41 umtkd xrdp[58825]: [INFO ] VNC receiving name length
Apr 24 08:25:41 umtkd xrdp[58825]: [INFO ] VNC receiving name
Apr 24 08:25:41 umtkd xrdp[58825]: [INFO ] VNC sending pixel format
Apr 24 08:25:41 umtkd xrdp[58825]: [INFO ] VNC sending cursor
Apr 24 08:25:41 umtkd xrdp[58825]: [INFO ] VNC connection complete, connected ok
Apr 24 08:25:41 umtkd xrdp[58825]: [INFO ] VNC: Clipboard (if available) is provided by chansrv facility
Apr 24 08:25:41 umtkd xrdp[58825]: [INFO ] connected ok
Apr 24 08:25:41 umtkd xrdp[58825]: [INFO ] Layout from OldLayout (geom=1440x900 #screens=1) : 1804289383:(1440x900+0+0)

I should have a look at the post #2040 as you said.
If I have more question, I will reply.

Thank you.

**Comment by matt335672** [comment]
If I remember correctly, you won't get the message if the connection isn't dropped. This will happen if:-
- The client and the server agree to use RFB encryption.
- The client is happy with the TLS certificate presented by the server.

If that doesn't explain it, please let me know and we can dig further.

**Comment by DeokchangSeo** [comment]
@matt335672 

I might describe the situation a bit vague and misunderstand what you answered earlier.
My question was not about the connection drop and I got the errors when I put the status check command.

The siutation is like below:
1. I and my colleagues can access and login the linux server from Windows11 via xrdp.
2. There is no issue - all of processes and tools are working fine.
3. In order to change the setting - stop outbound file transfer
4. After the configuration, I needed to check the status with the command "systemctl status xrdp"
5. Received error messages like below and my computer was still connected (no connection drop)

Apr 21 09:00:44 umtka xrdp[796]: [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Apr 21 09:00:44 umtka xrdp[796]: [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
Apr 21 09:00:44 umtka xrdp[796]: [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|RDP], selected [SSL]
Apr 21 09:00:44 umtka xrdp[796]: [ERROR] SSL_accept: I/O error
Apr 21 09:00:44 umtka xrdp[796]: **[ERROR] trans_set_tls_mode: ssl_tls_accept failed**
Apr 21 09:00:44 umtka xrdp[796]: **[ERROR] xrdp_sec_incoming: trans_set_tls_mode failed**
Apr 21 09:00:44 umtka xrdp[796]: **[ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed**
Apr 21 09:00:44 umtka xrdp[796]: **[ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed**
Apr 21 09:00:44 umtka xrdp[796]: **[ERROR] xrdp_iso_send: trans_write_copy_s failed**
Apr 21 09:00:44 umtka xrdp[796]: **[ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed**

6. The error messages in bold text cause me concern.
7. Because I get this error from server1 only but the other server(server2) doesn't give the error.
8. I worried about those fail messages with the terms "trans_set_tls, xrdp_sec_incoming, xrdp_process_main_loop, etc."
9. What do they mean? do I have to worry about this?

As you know, I am a newbie in this field so I might misunderstand.
A little bit more detailed explanation can help me to comprehend what is happening here.

Thank you.

**Comment by matt335672** [comment]
The messages in bold are generated when a connection drops. This can happen right at the start when a connection is set up in the first place if the client needs to ask about the certificate. That's what #2040 is talking about.

If you want to see this in action:-

- Use this command to get a live update of the xrdp log:-
```sh
sudo tail -f /var/log/xrdp-sesman.log
```
- Connect to the machine from a client and see what happens in the log.

Finish the `tail -f` by using CTRL-C. It's a useful command to know as a sysadmin.

You don't have to worry about these messages. I'm hoping that we can improve the logging in this area at some stage, because it's not user-friendly.

**Comment by DeokchangSeo** [comment]
So, what I understand from your explanation is that the command to check the xrdp status somehow triggers a connection drop and that's the reason why the error messages come out on the screen.

To sum up, this does not affect on the system but just show me the error message.
Okay from now on, I shouldn't worry about it.

Thank you for your reponse and I hope it can be improved soon.

**Comment by matt335672** [comment]
The command to check the status will not trigger a connection drop. The connection drop happens because the client connects twice. Have a play with `tail -f` and you'll see what I mean.

**Comment by pf18387** [comment]
Hi All, and Thanks for this excellent software
(`Debian 11, xrdp 0.9.21.1`) Here is what could be done in order to avoid overfilling logfiles `syslog`and `daemon.log`:
file `/etc/xrdp.ini` section `[Logging]`
```
LogFile=/dev/null
EnableSyslog=false
```
file `/etc/sesman.ini` section `[Logging]`
```
EnableSyslog=false
```
Best regards
