### ISSUE TITLE
Unable to contact Settings

### ISSUE THREAD

**Issue by DocMAX** [neutrinolabs/xrdp#2646]
Can someone explain to me why i am getting this when i login to XFCE4?

![grafik](https://user-images.githubusercontent.com/5351323/234533713-54484891-92f5-440c-9d13-ccc00d73dda6.png)

I tried various settings in .xinitrc and found the one uncommented works.

![grafik](https://user-images.githubusercontent.com/5351323/234533970-016582ed-4d14-428b-898b-653c7a7c112d.png)

But still its not not perfect as it misses some xdg_runtime_dir environemnt variables.

![grafik](https://user-images.githubusercontent.com/5351323/234546191-a31ad856-958d-4527-8732-a4273909c1ab.png)

Which ist the perfect .xinitrc configuration to have a fully working desktop?

**Comment by matt335672** [comment]
I suspect you're missing a bunch of stuff.

You don't say exactly what OS you're running. It's clearly a Linux of some kind, but that's all I can see from here.

Start by getting XFCE4 working on the machine console first by following the instructions for your OS. When that's OK, you will probably find running startxfce4 is sufficient. Let us know how it goes.

**Comment by DocMAX** [comment]
Indeed it's not a "usual" OS. It's Arch Linux in a LXC container (Proxmox),
I can start a vncserver which has a working xfce4 desktop (systemctl --user gives an output).
But with XRDP i can't get the same environment.
Am i missing some files that have to be sourced?

**Comment by matt335672** [comment]
Almost certainly you are, but given it's a custom container, we can't really figure out for you what is happening - you'll have to do that yourself. I can try to give you a few pointers:-

- Compare the environment in both containers. What is missing in the XRDP environment?
- After logging in over XRDP, you should have `XDG_SESSION_ID` and `XDG_RUNTIME_DIR` set in your environment. If you haven't your PAM stack is incomplete and probably doesn't contain `pam_systemd.so`
- `$XDG_RUNTIME_DIR` should exist as a directory. Again, this is created by `pam_systemd.so`.
- `$DBUS_BUS_SESSION_BUS_ADDRESS` should translate to something like `unix:path=/run/user/$(id -u)/bus`.

**Comment by DocMAX** [comment]
Thank you, these are the hints i was looking for. There is a difference between the working and non-working environment. Trying to figure out how to fix.

Working;
```
docmax@desktop: /mnt/pve/data/syncthing/linux/profile $ env|sort
ALACRITTY_LOG=/tmp/Alacritty-12159.log
ALACRITTY_SOCKET=/run/user/1000/Alacritty-:12.0-12159.sock
ALACRITTY_WINDOW_ID=41943042
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DEBUGINFOD_URLS=https://debuginfod.archlinux.org
DESKTOP_SESSION=xfce
DISPLAY=:12.0
DOTNET_BUNDLE_EXTRACT_BASE_DIR=/home/docmax/.cache/dotnet_bundle_extract
DOTNET_ROOT=/usr/share/dotnet
GDMSESSION=xfce
GTK_MODULES=canberra-gtk-module:canberra-gtk-module
HISTCONTROL=ignoreboth:erasedups
HOME=/home/docmax
INVOCATION_ID=d2ed28ea71c645eea8066fd2f4e81d44
JOURNAL_STREAM=8:13478473
LANG=C.UTF-8
LOGNAME=docmax
MAIL=/var/spool/mail/docmax
MANAGERPID=79
PANEL_GDK_CORE_DEVICE_EVENTS=0
PATH=/home/docmax/bin:/home/docmax/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/home/docmax/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/docmax/bin
PWD=/mnt/pve/data/syncthing/linux/profile
SESSION_MANAGER=local/desktop:@/tmp/.ICE-unix/11859,unix/desktop:/tmp/.ICE-unix/11859
SHELL=/bin/bash
SHLVL=0
SSH_AGENT_PID=11891
SSH_AUTH_SOCK=/tmp/ssh-XXXXXX2ejcqk/agent.11890
SYSTEMD_EXEC_PID=11852
TERM=alacritty
USER=docmax
WINDOWID=41943042
XAUTHLOCALHOSTNAME=
XAUTHORITY=/home/docmax/.Xauthority
XDG_CONFIG_DIRS=/etc/xdg
XDG_CURRENT_DESKTOP=XFCE
XDG_DATA_DIRS=/usr/local/share:/usr/share
XDG_MENU_PREFIX=xfce-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_DESKTOP=xfce
_=/usr/bin/env
```

Non-Working:
```
ALACRITTY_LOG=/tmp/Alacritty-11750.log
ALACRITTY_SOCKET=/tmp/Alacritty-:10.0-11750.sock
ALACRITTY_WINDOW_ID=50331650
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/dbus-ZAvtpmoqAp,guid=4c8252615ab34dc1cca6dc9f644a24bd
DEBUGINFOD_URLS=https://debuginfod.archlinux.org
DESKTOP_SESSION=xfce
DISPLAY=:10.0
DOTNET_BUNDLE_EXTRACT_BASE_DIR=/home/docmax/.cache/dotnet_bundle_extract
DOTNET_ROOT=/usr/share/dotnet
GTK_MODULES=canberra-gtk-module
HISTCONTROL=ignoreboth:erasedups
HOME=/home/docmax
LANG=C.UTF-8
LOGNAME=docmax
MAIL=/var/spool/mail/docmax
MOTD_SHOWN=pam
OLDPWD=/mnt/pve/data/syncthing/linux/profile
PANEL_GDK_CORE_DEVICE_EVENTS=0
PATH=/home/docmax/bin:/home/docmax/.local/bin:/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/home/docmax/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/docmax/bin
PULSE_SCRIPT=/etc/xrdp/pulse/default.pa
PWD=/home/docmax
SESSION_MANAGER=local/desktop:@/tmp/.ICE-unix/11288,unix/desktop:/tmp/.ICE-unix/11288
SHELL=/bin/bash
SHLVL=1
SSH_AGENT_PID=11329
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXQvRRoT/agent.11328
TERM=alacritty
UID=1000
USER=docmax
WINDOWID=50331650
XDG_CONFIG_DIRS=/etc/xdg
XDG_CURRENT_DESKTOP=XFCE
XDG_DATA_DIRS=/usr/local/share:/usr/share
XDG_MENU_PREFIX=xfce-
XRDP_PULSE_SINK_SOCKET=xrdp_chansrv_audio_out_socket_10
XRDP_PULSE_SOURCE_SOCKET=xrdp_chansrv_audio_in_socket_10
XRDP_SESSION=1
XRDP_SOCKET_PATH=/tmp/.xrdp
_=/sbin/env
```

**Comment by DocMAX** [comment]
OK same problem like https://github.com/neutrinolabs/xrdp/issues/1684.
Commenting out "-account   [success=1 default=ignore]  pam_systemd_home.so" makes it work.
So i have to figure out what it is all about.

EDIT: After further reading this actually is the SAME problem.

**Comment by DocMAX** [comment]
Compiled and installed hack https://github.com/matt335672/pam_close_systemd_system_dbus. This fixed the issue! Thanks.

EDIT: Also "dbus-launch" is not needed anymore and the "Unable to contact Settings" window is gone. So it's all about creating a proper "session".

**Comment by DocMAX** [comment]
Only a few errors left: What are these about?
```
Apr 27 10:41:48 desktop xrdp-sesman[21100]: PAM unable to resolve symbol: pam_sm_close_session
Apr 27 10:41:48 desktop xrdp-sesman[21100]: [ERROR] sesman_data_in: scp_process_msg failed
Apr 27 10:41:48 desktop xrdp-sesman[21100]: [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans

```

**Comment by matt335672** [comment]
The PAM one may be due to `pam_close_systemd_system_dbus` not supporting that function.

Here's a patch you can try:-

```diff
diff --git a/pam_close_systemd_system_dbus.c b/pam_close_systemd_system_dbus.c
index b98ae8f..2800d55 100644
--- a/pam_close_systemd_system_dbus.c
+++ b/pam_close_systemd_system_dbus.c
@@ -36,3 +36,10 @@ pam_sm_open_session(pam_handle_t *pamh, int flags,
     pam_close_systemd_system_dbus(pamh);
     return PAM_SUCCESS;
 }
+
+int
+pam_sm_close_session(pam_handle_t *pamh, int flags,
+                     int argc, const char **argv)
+{
+    return PAM_SUCCESS;
+}
```

Let me know if that works out, and I'll update the module.

The other two are pretty standard for that version of xrdp I'm afraid. You get them whenever a connection closes for any reason.

**Comment by DocMAX** [comment]
Yes, that fixed the warning. Thank you for the quick responses.

**Comment by matt335672** [comment]
And thank you for the feedback. I've made a new release of pam_close_systemd_system_dbus with the patch in.
