### ISSUE TITLE
Window position not starting from top-left corner

### ISSUE THREAD

**Issue by jerryc05** [neutrinolabs/xrdp#2648]
might have been asked before but I did not find it.

some info about my cloud linux:
- does not have a desktop env (ubuntu server, only has X11, no kde or gnome)
- starts `google-chrome`
- chrome starts, but the position it starts is somewhere in the middle of the screen, thus hiding some part of the browser that I cannot interact with
- cannot drag the chrome window to move it somewhere else, and cannot resize it either.
- tried `x2go` and it worked just fine (and I can also resize chrome easily from the host machine), but it's slower than `xrdp`. `x2go` might be using a different protocol? not sure here

screenshot below:
![image](https://user-images.githubusercontent.com/8305074/234941843-fdace28e-7204-4dbc-9932-a8a66d865c8d.png)

**Comment by jsorg71** [comment]
Some applications don't like having no window manager.  Firefox and Chromium are among them.  My guess is that x2go is running some simple window manager.  Can you try running a simple window manager like openbox.

**Comment by jerryc05** [comment]
@jsorg71 ty! after installing openbox, it worked like a charm!
