### ISSUE TITLE
[RHEL][GNOME] RU Input Language switch does not work in GNOME in Remote Desktop in Fedora

### ISSUE THREAD

**Issue by apivovarov** [neutrinolabs/xrdp#2656]
I tried to use xrdp in RHEL 9, AlmaLinux 9  and Fedora 36.
In all of the distros I faced the same issue with the Input Language switch in xrdp session.
Regardless of what language is selected the keyboard always types in English. (Actually in "ru" mode it prints in English but all keys from bottom row (zxcvbnm) prints nothing in "ru" mode. So, the input lang swith is actuully happening but it swishes to some "strange" language.
Remote Desktop client was on Windows 11 with regular windows keyboard.
These Linux distributions use xrdp 0.9.21 from epel/9 repo - [xrdp-0.9.21-1.el9.x86_64.rpm](https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/x/xrdp-0.9.21-1.el9.x86_64.rpm)

Steps to reproduce the issue:
Install minimal OS. We can use cloud instance or Virtual box (with bridged Adapter) + install ISO.
Install epel, Workstation group and xrdp as described below:
```
sudo dnf upgrade
sudo dnf install yum-utils
sudo dnf config-manager --set-enabled crb
sudo dnf install epel-release
sudo dnf upgrade

sudo dnf group install Workstation
sudo systemctl set-default graphical
sudo reboot

sudo dnf install xrdp
sudo systemctl start xrdp
sudo systemctl enable xrdp

sudo systemctl start firewalld
sudo systemctl enable firewalld
sudo firewall-cmd --permanent --zone=public --add-service=rdp
sudo systemctl restart firewalld
```
Connect to the box using Remote Desktop
Open Settings app. (in GNOME Desktop)
Go to Keyboard - Input Sources - + - Russian
Switch to “ru” using input lang selector in the top bar
Try to type smth in some field - it will type in English (or nothing) instead of Rus

**Comment by apivovarov** [comment]
Additional Observations:
1. The issue exist only in xrdp session. If I use regular graphical Gnome session (e.g. in Virtual Box) the Input Language switching works as expected.
2. It might look like xrdp does not switch the Input Language because keyboard still types in English in "ru" mode. However some keys print nothing in "ru" mode. So, xrdp is actually switches to something in "ru" mode which looks like English but with missing letters.
Keys which type nothing in "ru" mode:
- All letter keys from bottom row - zxcvbnm
- Other keys  - `[]'{}<>~#$^&

3. I'm a bit surprised that all RHEL-like distros are affected by this issue and nobody noticed/reported it.
4. I tried distros from other camp - Ubuntu 22.04 and Debian 11 - they do not have this xrdp and input language issue. Btw, they use older xrdp version - 0.9.17 and 0.9.12

**Comment by apivovarov** [comment]
**Yes, we have a solution!!!**

We need to uncomment `[Xorg]` block in `xrdp.ini`.

Step by Step instructions:
```
## install xorgxrdp
sudo dnf install xorgxrdp

## edit /etc/xrdp/xrdp.ini
sudo vi /etc/xrdp/xrdp.ini

## Uncomment [Xorg] block to Enable it.

[Xorg]
name=Xorg
lib=libxup.so
username=ask
password=ask
ip=127.0.0.1
port=-1
code=20


## We can keep [Xvnc] block enabled.


# Save the file and Restart xrdp service
sudo systemctl restart xrdp

## Done!
When you connect to the server in Remote Desktop it will ask for login/password.
Make sure Xorg session is selected - it should be the first in the list. 
Do NOT select Xvnc!

Now the Input Language switch works correctly in Remote Desktop / Xorg / GNOME session!

Tested on Fedora 36, AlmaLinux 9, CentOS Stream 9, CentOS 7

```

The solution was found by ZOTOVP on Mar 2023 - [the article](https://zotovp.wordpress.com/2023/03/19/centos7-xrdp-on-xorg-vnc-not-supporting-language-switching-centos7-xrdp-on-xorg-vnc-%d0%bd%d0%b5-%d0%bf%d0%b5%d1%80%d0%b5%d0%ba%d0%bb%d1%8e%d1%87%d0%b0%d0%b5%d1%82-%d1%8f%d0%b7%d1%8b%d0%ba/)

Related [discussion](https://forums.fedoraforum.org/showthread.php?330477-XRDP-Keyboard-always-types-in-English-regardless-of-selected-Input-Language&p=1870292#post1870292) on Fedora forum

**Comment by metalefty** [comment]
Closing as solved.

**Comment by RomanMeR** [comment]
I faced this issue on Fedora 37. The solution with uncommenting the `[Xorg]` block in `xrdp.ini` worked for me. However, is it possible to have a fix that will make language switching on Fedora work "out of the box", without manual changes in `/etc/xrdp/xrdp.ini`? For example, the package installer could uncomment the `[Xorg]` block in `xrdp.ini` when installing on Fedora.

**Comment by matt335672** [comment]
@RomanMeR  - the EPEL packagers have decided to default to Xvnc as the X server. We ship it with Xorg as the default, but downstream apply a patch [here](https://src.fedoraproject.org/rpms/xrdp/blob/rawhide/f/xrdp-0.9.17-xrdp-ini.patch) to change this.

There is a good reason why the EPEL package would ship with Xvnc as the default, as the same package spec file is used on RHEL. The update cycles for RHEL and EPEL are different, and an Xorg update in RHEL could lead to breakages.

In any case we can't do anything about it here. You could make a suggestion on the RedHat Bugzilla about treating Fedora differently. I don't know if they'd go for that.

**Comment by RomanMeR** [comment]
I discovered that the solution with uncommenting the [Xorg] block in xrdp.ini works only during first XRDP connection. If I disconnect and after some time reconnect, switching to Russian language stop working both with Shift+Alt and by mouse in language panel. Please help!
OS: Fedora 38

> [user@fedora ~]$ dnf list xrdp*
> Последняя проверка окончания срока действия метаданных: 0:01:51 назад, Ср 27 сен 2023 13:02:54.
> Установленные пакеты
> xrdp.x86_64                                                                                                          1:0.9.23-1.fc38                                                                                                  @updates
> xrdp-selinux.x86_64                                                                                                  1:0.9.23-1.fc38                                                                                                  @updates
> Имеющиеся пакеты
> xrdp.i686                                                                                                            1:0.9.23-1.fc38                                                                                                  updates 
> xrdp-devel.i686                                                                                                      1:0.9.23-1.fc38                                                                                                  updates 
> xrdp-devel.x86_64                                                                                                    1:0.9.23-1.fc38                                                                                                  updates 
> 
[sesman.ini.txt](https://github.com/neutrinolabs/xrdp/files/12737384/sesman.ini.txt)
[xrdp.ini.txt](https://github.com/neutrinolabs/xrdp/files/12737385/xrdp.ini.txt)
[xrdp_keyboard.ini.txt](https://github.com/neutrinolabs/xrdp/files/12737386/xrdp_keyboard.ini.txt)
[xrdp.log](https://github.com/neutrinolabs/xrdp/files/12737392/xrdp.log)
[xrdp-sesman.log](https://github.com/neutrinolabs/xrdp/files/12737393/xrdp-sesman.log)

**Comment by beremour** [comment]
Same issue on Rocky 9.3. Uncommenting [Xorg] doesn't start Desktop Session.

**Comment by beremour** [comment]
Rocky 9.3. Same issue. Solution with [Xorg] section helps only for the 1st login. Switching breaks after reconnect.

**Comment by Igor-178** [comment]
I have completed the solution so that the layout switches not only at the first login. Tested on RHEL9.
First, we do everything according to apivovarov's recommendation.
The [Xvnc] block must be commented out. Only the Xorg session is used.
Additionally, for example, for the Russian layout, add /etc/xrdp/xrdp_keyboard.ini to the end of the file:

> [layouts_map_ru]
rdp_layout_us=us,ru
rdp_layout_ru=ru,us

> [rdp_keyboard_ru]
keyboard_type=4
keyboard_type=7
keyboard_subtype=1
options=grp:alt_shift_toggle
rdp_layouts=default_rdp_layouts
layouts_map=layouts_map_ru

Switching the keyboard layout for a regular user will be Alt+Shift.
Switching the keyboard layout for root will not change, in my case, the default is Win+Space.

**Comment by matt335672** [comment]
I think I can see what's going on here.

If anyone monitoring this thread would like to comment on #3322, that could be useful.

**Comment by RomanMeR** [comment]
> I have completed the solution so that the layout switches not only at the first login. Tested on RHEL9. 

Your advice helped me, thank you! Tested on Fedora 40.
