### ISSUE TITLE
rdpdr not working in debian jessie

### ISSUE THREAD

**Issue by vincentkersten** [neutrinolabs/xrdp#266]
Hi folks,
just to let you know that in debian jessie i cannot seem to get the rdpdr channel working (though it did work in wheezy). Funny enough the clipboard works fine both ways, but i do not see disks on the remote side. Tested in Cord ,  Microsoft Remote Desktop and RDP on windows.
From the linux side i do not see the channelsever being mounted by fuse. 
Any ideas?

**Comment by metalefty** [comment]
Is clipboard file working?

**Comment by vincentkersten** [comment]
There is _no_ .clipboard file in the folder normally showing local drives, however the clipboard works both ways.

**Comment by moobyfr** [comment]
do you have fuse installed on your server ?
I'm installing some jessie, and have no issues with drives redirections

**Comment by vincentkersten** [comment]
Thanks for geeting back to me...
Fuse is installed indeed, for example sshfs (fuse module) works without any issues. 
Which version did you install?

I have testest 0.9.0 (master) and 0.9.X - (dev) both not doing the drive redirection.

**Comment by moobyfr** [comment]
I've used the current "devel" branch.
Can you start "xrdp -ns" and "xrdp-sesman -ns" and save the ouput of these while connecting ?

**Comment by vincentkersten** [comment]
Currently not, since these machines are in production. 
next wednesday there is a window for that. 
I remember though that the 'rdprd channel' was not enabled ( is strted the daemons like that indeed)
only the clipboard channel and the sound channel (which choked since i did not put the pulse stuff in the proper place).

As soon as i can I will post the output here - just not quite sure why the channel is not activated at all. (It used to work in the previous debian, with some hacks for LDAP , see https://github.com/neutrinolabs/xrdp/issues/198 <https://github.com/neutrinolabs/xrdp/issues/198> )

**Comment by vincentkersten** [comment]
Ok, I just dragged what i could from journald:
Jul 24 15:19:11 blue XRDP-sesman[52153]: (52153)(140139386357504)[INFO ] An established connection closed to endpoint: 127.0.0.1:39065 - socket: 8
Jul 24 15:19:11 blue XRDP-sesman[52155]: (52155)(140139386357504)[INFO ] X11rdp :53 -geometry 1280x1024 -depth 24 -bs -ac -nolisten tcp -uds
Jul 24 15:19:11 blue XRDP-sesman[52153]: (52153)(140139386357504)[INFO ] starting xrdp-sessvc - xpid=52155 - wmpid=52154
Jul 24 15:19:11 blue XRDP-sesman[52154]: pam_unix(xrdp-sesman:session): session opened for user vincent by (uid=0)
Jul 24 15:19:11 blue systemd-logind[1504]: New session c29 of user vincent.
Jul 24 15:19:11 blue systemd[52157]: pam_unix(systemd-user:session): session opened for user vincent by (uid=0)
Jul 24 15:19:11 blue systemd[52157]: Starting Paths.
Jul 24 15:19:11 blue systemd[52157]: Reached target Paths.
Jul 24 15:19:11 blue systemd[52157]: Starting Timers.
Jul 24 15:19:11 blue systemd[52157]: Reached target Timers.
Jul 24 15:19:11 blue systemd[52157]: Starting Sockets.
Jul 24 15:19:11 blue systemd[52157]: Reached target Sockets.
Jul 24 15:19:11 blue systemd[52157]: Starting Basic System.
Jul 24 15:19:11 blue systemd[52157]: Reached target Basic System.
Jul 24 15:19:11 blue systemd[52157]: Starting Default.
Jul 24 15:19:11 blue systemd[52157]: Reached target Default.
Jul 24 15:19:11 blue systemd[52157]: Startup finished in 12ms.
Jul 24 15:19:12 blue XRDP[52066]: (52066)(140575971706624)[INFO ] lib_mod_log_peer: xrdp_pid=52066 connected to X11rdp_pid=52155 X11rdp_uid=1539 X11rdp_gid=3000 client_ip=143.121.247.57 client_port=64347
Jul 24 15:19:12 blue XRDP[52066]: (52066)(140575971706624)[DEBUG] xrdp_mm_connect_chansrv: chansrvconnect successful
Jul 24 15:19:12 blue XRDP[52066]: (52066)(140575971706624)[INFO ] An established connection closed to endpoint: 127.0.0.1:3350 - socket: 11
Jul 24 15:19:12 blue XRDP[52066]: (52066)(140575971706624)[INFO ] The following channel is allowed: rdpdr (0)
Jul 24 15:19:12 blue XRDP[52066]: (52066)(140575971706624)[INFO ] The following channel is allowed: cliprdr (1)
Jul 24 15:19:12 blue XRDP[52066]: (52066)(140575971706624)[DEBUG] The allow channel list now initialized for this session


=-=- xrdp.ini =-=-=-
[globals]
# xrdp.ini file version number
ini_version=1

bitmap_cache=yes
bitmap_compression=yes
port=3389
allow_channels=true
max_bpp=32
fork=yes
# minimum security level allowed for client
# can be 'none', 'low', 'medium', 'high', 'fips'
crypt_level=high
# security layer can be 'tls', 'rdp' or 'negotiate'
# for client compatible layer
security_layer=rdp
# X.509 certificate and private key
# openssl req -x509 -newkey rsa:2048 -nodes -keyout key.pem -out cert.pem -days 365
certificate=/etc/xrdp/cert.pem
key_file=/etc/xrdp/key.pem

# regulate if the listening socket use socket option tcp_nodelay
# no buffering will be performed in the TCP stack
tcp_nodelay=yes

# regulate if the listening socket use socket option keepalive
# if the network connection disappear without close messages the connection will be closed
tcp_keepalive=yes

#tcp_send_buffer_bytes=32768
#tcp_recv_buffer_bytes=32768

#
# colors used by windows in RGB format
#

blue=009cb5
grey=dedede
#black=000000
#dark_grey=808080
#blue=08246b
#dark_blue=08246b
#white=ffffff
#red=ff0000
#green=00ff00
#background=626c72
#autorun=xrdp1
#hidelogwindow=yes

# when true, userid/password *must* be passed on cmd line
# require_credentials=yes

# set a default entry for autorun if the client send login and pass directly
autorun=xrdp1

bulk_compression=yes

# You can set the PAM error text in a gateway setup (MAX 256 chars)
#pamerrortxt=change your password according to policy at http://url
new_cursors=yes
allow_multimon=true

# fastpath - can be set to input / output / both / none
use_fastpath=both
#
# configure login screen
#

# Login Screen Window Title
#ls_title=My Login Title

# top level window background color in RGB format
ls_top_window_bg_color=009cb5

# width and height of login screen
ls_width=350
ls_height=430

# login screen background color in RGB format
ls_bg_color=dedede

# optional background image filename (bmp format).
#ls_background_image=

# logo
# full path to bmp-file or file in shared folder
ls_logo_filename=
ls_logo_x_pos=55
ls_logo_y_pos=50

# for positioning labels such as username, password etc
ls_label_x_pos=30
ls_label_width=60

# for positioning text and combo boxes next to above labels
ls_input_x_pos=110
ls_input_width=210

# y pos for first label and combo box
ls_input_y_pos=220

# OK button
ls_btn_ok_x_pos=142
ls_btn_ok_y_pos=370
ls_btn_ok_width=85
ls_btn_ok_height=30

# Cancel button
ls_btn_cancel_x_pos=237
ls_btn_cancel_y_pos=370
ls_btn_cancel_width=85
ls_btn_cancel_height=30

[Logging]
LogFile=xrdp.log
LogLevel=DEBUG
EnableSyslog=1
SyslogLevel=DEBUG
# LogLevel and SysLogLevel could by any of: core, error, warning, info or debug

[channels]
# Channel names not listed here will be blocked by XRDP.
# You can block any channel by setting its value to false.
# IMPORTANT! All channels are not supported in all use
# cases even if you set all values to true.
# You can override these settings on each session type
# These settings are only used if allow_channels=true
rdpdr=true
rdpsnd=true
drdynvc=true
cliprdr=true
rail=true
xrdpvr=true
tcutils=true

# for debugging xrdp, in section xrdp1, change port=-1 to this:
# port=/tmp/.xrdp/xrdp_display_10

# for debugging xrdp, add following line to section xrdp1
# chansrvport=/tmp/.xrdp/xrdp_chansrv_socket_7210

[xrdp1]
name=sesman-X11rdp
lib=libxup.so
username=ask
password=ask
ip=127.0.0.1
port=-1
xserverbpp=24
code=10

[xrdp2]
name=sesman-Xvnc
lib=libvnc.so
username=ask
password=ask
ip=127.0.0.1
port=-1
#delay_ms=2000

[xrdp3]
name=console
lib=libvnc.so
ip=127.0.0.1
port=5900
username=na
password=ask
#delay_ms=2000

[xrdp4]
name=vnc-any
lib=libvnc.so
ip=ask
port=ask5900
username=na
password=ask
#pamusername=asksame
#pampassword=asksame
#pamsessionmng=127.0.0.1
#delay_ms=2000

[xrdp5]
name=sesman-any
lib=libvnc.so
ip=ask
port=-1
username=ask
password=ask
#delay_ms=2000

[xrdp6]
name=rdp-any
lib=librdp.so
ip=ask
port=ask3389

[xrdp7]
name=neutrinordp-any
lib=libxrdpneutrinordp.so
ip=ask
port=ask3389
username=ask
password=ask

[Session manager]
name=Session manager
lib=libxup.so
username=ask
password=ask
ip=127.0.0.1
port=-1
xserverbpp=24
code=20

# You can override the common channel settings for each session type
#channel.rdpdr=true
#channel.rdpsnd=true
#channel.drdynvc=true
#channel.cliprdr=true
#channel.rail=true
#channel.xrdpvr=true




=-=-==- Sesman.ini =-=-=-=-=-=

[Globals]
ListenAddress=127.0.0.1
ListenPort=3350
EnableUserWindowManager=1
UserWindowManager=startwm.sh
DefaultWindowManager=startwm.sh

[Security]
AllowRootLogin=0
MaxLoginRetry=4
TerminalServerUsers=tsusers
TerminalServerAdmins=tsadmins
# When AlwaysGroupCheck = false access will be permitted
# if the group TerminalServerUsers is not defined.
AlwaysGroupCheck = false

[Sessions]

## X11DisplayOffset - x11 display number offset
# Type: integer
# Default: 10
X11DisplayOffset=40

## MaxSessions - maximum number of connections to an xrdp server
# Type: integer
# Default: 0
MaxSessions=50

## KillDisconnected - kill disconnected sessions
# Type: integer
# Default: 0
# if 1, true, or yes, kill session after 60 seconds
KillDisconnected=0

## IdleTimeLimit - when to disconnect idle sessions
# Type: integer
# Default: 0
# if not zero, the seconds without mouse or keyboard input before disconnect
# not complete yet
IdleTimeLimit=0

## DisconnectedTimeLimit - when to kill idle sessions
# Type: integer
# Default: 0
# if not zero, the seconds before a disconnected session is killed
# min 60 seconds
DisconnectedTimeLimit=0

## Policy - session allocation policy
# Type: enum [ "Default" | "UBD" | "UBI" | "UBC" | "UBDI" | "UBDC" ]
# Default: Xrdp:<User,BitPerPixel> and Xvnc:<User,BitPerPixel,DisplaySize>
# "UBD" session per <User,BitPerPixel,DisplaySize>
# "UBI" session per <User,BitPerPixel,IPAddr>
# "UBC" session per <User,BitPerPixel,Connection>
# "UBDI" session per <User,BitPerPixel,DisplaySize,IPAddr>
# "UBDC" session per <User,BitPerPixel,DisplaySize,Connection>
Policy=Default

[Logging]
LogFile=xrdp-sesman.log
LogLevel=DEBUG
EnableSyslog=1
SyslogLevel=DEBUG

[X11rdp]
param1=-bs
param2=-ac
param3=-nolisten
param4=tcp
param5=-uds

[Xvnc]
param1=-bs
param2=-ac
param3=-nolisten
param4=tcp
param5=-localhost
param6=-dpi
param7=96

[Xorg]
param1=-config
param2=xrdp/xorg.conf
param3=-logfile
param4=/dev/null
param5=-noreset
param6=-ac
param7=-nolisten
param8=tcp

[Chansrv]
# drive redirection, defaults to xrdp_client if not set
FuseMountName=local_drives

[SessionVariables]
PULSE_SCRIPT=/etc/xrdp/pulse/default.pa

**Comment by metalefty** [comment]
@vincentkersten Debian has xrdp v0.9.1 in their repository now. Can you test again with v0.9.1?

**Comment by vincentkersten** [comment]
Wow, this is good news!
I'll get back to this , thank you for letting me know!


  Vincent

**Comment by metalefty** [comment]
Closing. If this issue is not fixed for you, please feel free to reopen.

**Comment by vincentkersten** [comment]
Debian package works quite well, i've deployed on a few places. 

- Even really old drawing methods 

- the install script could chown /var/run/xrdp 
(but that only really is because it took me so long to find it :) )

- I have a freeze since two days on the login window on two servers. Not able to type name and password. Funny enough if my rdp client sends my login credentials automatically, i am connected. 
Still looking into the issue, but i am not sure what to restart, actually, without affecting the running sessions. 

Regards,

  Vincent
