### ISSUE TITLE
Some accounts can't connect while others can

### ISSUE THREAD

**Issue by mvinsky** [neutrinolabs/xrdp#2662]
I've been searching all over the internet for a solution to this issue but I can't find any help. For some reason I can connect remotely using my account but when I try to use the guest account it doesn't work. There are two other accounts on the computer and one works and the other doesn't, but both belong to the Admin user groups, so I don't know what the issue is.

I can connect to the computer using all four account and putty (SSH) so I know the passwords are correct. I tried option number 2 from this page because I thought it was a read/write issue with ssl-cert-snakeoil.key but now I'm not sure if that is the problem.
https://c-nergy.be/blog/?p=13708

I've also checked that all users have logged out of their accounts using "w" so there are no concurrent accounts.

I'm attaching the XRDP log files, hopefully they can help.
[xrdp_sesman_copy.log](https://github.com/neutrinolabs/xrdp/files/11443318/xrdp_sesman_copy.log)
[xrdp_copy.log](https://github.com/neutrinolabs/xrdp/files/11443319/xrdp_copy.log)

I'm running Windows 11 and connecting to Ubuntu 22.04.2 with xrdp 0.9.17.

Any help would be appreciated. I'm a bit of a novice so hopefully what I've provided is useful.

**Comment by matt335672** [comment]
The X server isn't working for the `guest` user.

Is there anything useful in `~guest/.xorgxrdp.10.log`? I'm assuming the guest user has write access to their home directory.

**Comment by mvinsky** [comment]
Actually it looks like the two accounts with issues have their ownership swapped for some reason. I upgraded the system to 22.04.02 and migrated their accounts/home directories over but still have the original OS on a separate HDD. When I look at the ownership using "ls -l" they are switched, even on the original OS. XRDP was working on the original OS but I don't understand how.

I'm sorry to ask, but can you tell me how to change the ownership of the home directory for each user? I'm not sure how.

**Comment by matt335672** [comment]
A non-writeable home directory will certainly cause you problems. From your description that's probably it.

I'm not sure I fully understand what you mean by ownership swapped. There may be a simple solution here. Can we drill down a bit please?

What do you get for these commands (making the appropriate substitutions for `<account1>` and `<account2>`:-

```
getent passwd <account1>
getent passwd <account2>
sudo ls -ld /home/<account1>
sudo ls -ld /home/<account2>

```

**Comment by mvinsky** [comment]
You know what Matt, I was able to fix the issue. I used "chown" and "chrgrp" using the recursive (R) and symbolic link (h) options. Connecting with XRDP has been a problem for months and I had given up on fixing it, but this solved it.

I think the original HDD had some error in its file system that it tried to correct and when it did the ownership of the two directories got switched, so when I moved them to the new OS, on a new SSD, it came with them. I didn't realize this was the problem because prior to the HDD crashing things were working fine.

I thought there might be a permission issue with the files needed for XRDP but I didn't think the home directories were the issue. Thanks for finally pointing me in the right direction to solve this problem!

**Comment by matt335672** [comment]
Glad you've got it sorted @mvinsky 

You can check the permissions on the home directories by logging in as each user and entering this command:-

```
find ~ -xdev \! -uid $(id -u) -ls
```
I'll explain it a bit:-

The `$(id -u)` bit gets the UID of the current user with `id -u` and substitutes it into the rest of the command. Lets say it returns 1000.

The find command then looks for all files under `~` (the home directory) on the current filesystem (`-xdev`) with a UID not equal to the current user (`\! -uid 1000`) and then lists them (`-ls`).

I'd recommend you taking a bit of trouble to do that just to make sure this one is put to bed. Then feel free to close the issue!

**Comment by mvinsky** [comment]
Nothing happens when I type this in. Is there a typo?

**Comment by matt335672** [comment]
No - that's fine. The command only displays the files not owned by the user. If you're not seeing any files, all is good.
