### ISSUE TITLE
Black Screen Fedora 38 KDE Spin

### ISSUE THREAD

**Issue by LostPoE** [neutrinolabs/xrdp#2663]
I'm a Linux newb. Sorry for not supplying logs.

In an xRDP session. When trying to reboot, shutdown or logout from the KDE GUI the screen goes black and the session never exits. This does not occur when opening up a terminal in a xRDP session and using "sudo shutdown -r now".

https://imgur.com/a/RLO3YTL - KDE GUI

Notes:
Fedora 38 KDE Spin. Fresh Install, using sudo dnf install xrdp.
When trying to log in as the user again from the console its a black screen.
Also created 2nd user. The 2nd user is able to login without black screen if the black screen is on from the first user. 
2nd user can have the same black screen issue if trying to exit xrdp session from the KDE GUI.

**Comment by matt335672** [comment]
Hi @LostPoE, and welcome to the world of Linux.

There's a lot to understand here I'm afraid, and I can only give you pointers to what you need to do.

Firstly, Fedora runs SELinux. You will need to install the `xrdp-selinux` package as well as `xrdp`.

That's a small thing though. The biggest issue you will have is that KDE uses a sub-system called `polkit` to authorize operations. `polkit` treats remote users differently from local users. The main one is that Linux is used in many different environments, and so what you are trying to do (presumably shut down a single-user system) can't be permitted for a multi-user system by default as this would inconvenience other users.

To the best of my knowledge no-one has produced an easy-to-use interface to configure polkit. It all needs to be done by the user using text files.

A good description of polkit can be found on the Arch Linux wiki (as with so many other things):-

https://wiki.archlinux.org/title/Polkit

You will need to avoid descriptions of polkit which related to Debian/Ubuntu. These operating systems use an older version of polkit which is configured differently.

**Comment by LostPoE** [comment]
Thanks for the quick reply!

The xrdp-selinux package is a dependency for xrdp in Fedora 38, so that is installed also.

The polkit issue makes sense. Would having this configured to work out of the box on Fedora 38 be on the Fedora developers?
Do you know of a newer KDE Linux Distro that does not have this issue? 
I think Debian 12 Bookworm RC2 has the same issue as Fedora 38.
I do notice that Gnome does not have this issue.

Thanks again.

**Comment by matt335672** [comment]
It really depends on what you mean by "out of the box".

I agree that having the user presented by a black screen isn't ideal, but then neither would having all users being able to shut a machine down from some perspectives. The best you might hope for is that these buttons would be disabled, which I believe some users have reported is what happens on Ubuntu.

xrdp isn't a major feature of any distro I'm aware of, and so it won't be part of the normal testing effort that goes into supporting a distro.

KDE seems to make particularly heavy use of polkit compared to other desktop environments. There are certainly issues with GNOME however, but they are less obvious.

I don't know exactly which use-cases you're trying to support, but you might find the following informative:-
- A lot of our KDE users seem to use Ubuntu. Here's a [search](/neutrinolabs/xrdp/issues?q=is%3Aissue+polkit+KDE) for issues involving KDE and polkit which you might find useful.
- GNOME offers GNOME remote desktop which exports an existing desktop over RDP. It avoids a lot of the issues you're describing, but requires the user to be logged in on the machine console. It supports a different set of use-cases than xrdp.
- You can export an existing KDE desktop over VNC and use xrdp to connect to that.

**Comment by LostPoE** [comment]
Tried option 3 "You can export an existing KDE desktop over VNC and use xrdp to connect to that." Using TigerVNC
It still goes to a black screen when rebooting.. Good times.

**Comment by matt335672** [comment]
Can you be more specific on what exactly is happening, both on the session and on the console?

Thanks.

**Comment by LostPoE** [comment]
I spent too much time in this already. You can close this issue. Thanks
