### ISSUE TITLE
change autotools to install  header files required to build xorgxrdp into /usr 

### ISSUE THREAD

**Issue by itamarjp** [neutrinolabs/xrdp#268]
Hello guys

xorgxrdp utilizes some header files from xrdp, what do you think about changing xrdp to install  header files required to build xorgxrdp into /usr ?

**Comment by jsorg71** [comment]
Good idea.
Maybe something like /usr/local/include/xrdp/xrdp_client_info.h

**Comment by itamarjp** [comment]
jsorg71, do you remember the name of all files used by xorgxrdp ?

**Comment by jsorg71** [comment]
@itamarjp 
This should be it, just one.

**Comment by metalefty** [comment]
Solved by 1fe368c5b3fa05f287731e57d748afb4556d554f.
