### ISSUE TITLE
[Windows->Ubuntu] Keyboard localization/layout will be chosen based on the language setting you use at the moment

### ISSUE THREAD

**Issue by ryohajika** [neutrinolabs/xrdp#2688]
Hello people,

I just found the keyboard layout on my server (Ubuntu 22.04.2 LTS via VMware Virtual Platform) via XRDP (0.9.17 with OpenSSL 3.0.2) will be changed based on the language you type at the time on my local computer (Windows 10 Enterprise 22H2) when you use multi-lingual environment. 
I have English and Japanese (MS IME) setup on my windows computer and I selected Hiragana input at the time when I accessed my server using Windows Remote Desktop Connection. Then I found the keyboard layout became that of Japanese keyboard on Ubuntu server. It didn't matter even if I changed the typing language from Japanese to English on Windows. After I shut the connection to change windows typing language to English, then the next remote access did take English keyboard layout.

Is this any kind of bug related to the XRDP or VMware, or even it supposed to be like that by design? I'm not a server maintenance engineer so I cannot investigate much unfortunately. Also I'm aware of the XRDP version I have here is not the latest, and I'm not sure if there is any release available that is dealing with this.

**Comment by matt335672** [comment]
@ryohajika - the current recommendation is to use different users for local and xrdp access. This is [in the FAQ](https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-log-the-same-user-on-on-the-graphical-console-and-over-xrdp-at-the-same-time)

Given this seems to be an unexpected interaction between the local and remote sessions, could this be related?

**Comment by ryohajika** [comment]
Hi @matt335672 , thanks for your response. It seems like it happened most likely because of the feature the VMware solution I use, not related to XRDP. Good to know about the users switching between local and xrdp remote connection. I close this issue for now. Thanks:)
