### ISSUE TITLE
CentOS 7 error loading libvnc.so specified in xrdp.ini

### ISSUE THREAD

**Issue by alfredojoseneto** [neutrinolabs/xrdp#2689]
Hi!
I'm using xrdp to acess a CentOS 7 and when I try to connect it gives me the error:

login sucessful for user ....... on display 10
error loading **libvnc.so** specified in xrdp.ini, please add a
valid entry like **lib=libxrdp.so** or similar

In the /usr/lib64/xrdp this file does not exist.
Thanks in advance

[edited]
P.S. until the last system update yesterday the system was working perfectly and I was able to connect and use the xfce through windows 10 RDP.

**Comment by mdaneri** [comment]
Some issue after AlmaLinux updated the XRDP package to xrdp-1:0.9.22-3.el9.x86_64

**Comment by zscaorui** [comment]
I also encountered the same problem, and the specific error file is as follows：
-----------------------------------------------
connecting to sesman on 127.0.0.1:3350sesman connect ok
sending login info to session manager. Please wait...
login successtul for user caorui on display ll error loading libvnc.so specified in xrdp.ini. please add a valid entry like lib=libxrdp-vnc.so or similar

**Comment by timurkelin** [comment]
xrdp-0.9.22-4 which is currently under test worked for me
```
wget https://rpmfind.net/linux/epel/testing/7/x86_64/Packages/x/xrdp-0.9.22-4.el7.x86_64.rpm
sudo yum install ./xrdp-0.9.22-4.el7.x86_64.rpm
```

**Comment by sagar1001** [comment]
Yes latest package xrdp-0.9.22-4.el7.x86_64.rpm worked for me as well.

**Comment by zscaorui** [comment]
> xrdp-0.9.22-4 which is currently under test worked for me
> 
> ```
> wget https://rpmfind.net/linux/epel/testing/7/x86_64/Packages/x/xrdp-0.9.22-4.el7.x86_64.rpm
> sudo yum install ./xrdp-0.9.22-4.el7.x86_64.rpm
> ```
Thank you. Based on the method you provided, I am now able to use it normally

**Comment by Mac10-sudo** [comment]
xrdp-0.9.22-4.el7.x86_64.rpm  also worked for me.

**Comment by alfredojoseneto** [comment]
Guys, thanks a lot! This approach solves the problem. I'm closing this issue, but I think that @zscaorui explanation in the issue #2690 will give them an idea realted to this.

**Comment by matt335672** [comment]
Hi all,

We've had multiple threads raised here about the same issue.

I'd encourage the participants in this thread to look at #2678, in particular [this post](/neutrinolabs/xrdp/discussions/2678#discussioncomment-5937960) regarding a significant issue with 0.9.22-4

Please add further comments and queries to #2678

**Comment by mrtwister76** [comment]
xrdp-0.9.22-5.el8.x86_64 is in EPEL Testing & worked fine for me.
Enable the testing repo & add includepkgs=xrdp*

**Comment by zeus201** [comment]
bonjour
Svp comment vous faites pour installer ce package xrdp-0.9.22-5.el8.x86_64   apres avoir fait le wget

**Comment by piancageorge** [comment]
Is it just me who is not able to reach link https://rpmfind.net/linux/epel/testing/7/x86_64/Packages/x/xrdp-0.9.22-4.el7.x86_64.rpm???

**Comment by zakasmi** [comment]
This one Works perfectly for centos 7:

```
wget https://kojipkgs.fedoraproject.org//packages/xrdp/0.9.22/4.el7/x86_64/xrdp-0.9.22-4.el7.x86_64.rpm
sudo yum install ./xrdp-0.9.22-4.el7.x86_64.rpm
```

**Comment by metalefty** [comment]
LOOK HERE: https://github.com/neutrinolabs/xrdp/issues/2689#issuecomment-1554595556
