### ISSUE TITLE
xorgxrdp updated to a version not yet pushed

### ISSUE THREAD

**Issue by mirabilos** [neutrinolabs/xrdp#269]
https://github.com/neutrinolabs/xorgxrdp/tree/01e050a0ab695f01608d481f6c5f123e362b7835 says not found, git fetch and git submodule update likewise.

**Comment by mirabilos** [comment]
Hm, actually this seems to be pushed, but to the devel branch. I have got no idea how to get git to check out the submodule right now, though…

**Comment by mirabilos** [comment]
submodule.<name>.branch
           A remote branch name for tracking updates in the upstream
           submodule. If the option is not specified, it defaults to master.
           See the --remote documentation in git-submodule(1) for details.

This appears to be missing in the .gitmodules file?

**Comment by mirabilos** [comment]
Hm no, commit 01e050a0ab695f01608d481f6c5f123e362b7835 is still not pushed, only commit f72dda9984ca68217f2ed228f83571be48b50219 is…

**Comment by moobyfr** [comment]
Hello
any update on this temporary problem ?

**Comment by jsorg71** [comment]
I think it's OK now.
Sorry about that.  I guess my local change didn't get pushed.

**Comment by mirabilos** [comment]
Thanks, this is indeed fixed now, closing.

One comment: would be cool if you could update the xorgxrdp submodule again, as it’s got two commits not yet in xrdp’s devel branch, one of which (the libtoolize one) would really help us Debianista.

**Comment by jsorg71** [comment]
> One comment: would be cool if you could update the xorgxrdp submodule again, as it’s got two commits not yet in xrdp’s devel branch, one of which (the libtoolize one) would really help us Debianista.

Ok, updated
