### ISSUE TITLE
error loading libvnc.so specified in xrdp.ini

### ISSUE THREAD

**Issue by alexolinux** [neutrinolabs/xrdp#2691]
Hello, first of all, thanks for your attention.

After deploying a cluster for remote access (GUI), the environment stopped working after updating to release 0.9.22.3. While in the previous version (0.9.21) the installation was enough and xrdp ran properly. The following crash started after upgrading to the current version.

> Note: _I did a test (double check) compiling the previous version (0.9.21) and it worked normally. I also did a test compiling the current version and unfortunately, it didn't work._

**Cluster Environment details**:

AlmaLinux release 8.8 (Sapphire Caracal) - x86_64
xrdp version: 0.9.22
Release      : 3.el8
Architecture : x86_64

Steps to reproduce:

1. Installing xrdp (_from epel-release repo_):

`dnf install -y xrdp`

Service running:
xrdp.service - xrdp daemon
   Loaded: loaded (/usr/lib/systemd/system/xrdp.service; enabled; vendor preset: disabled)
   Active: active (running)

`/var/log/xrdp.log`

[INFO ] xrdp_wm_log_msg: login successful for user `$user` on display 10
[INFO ] login successful for user `$user` on display 10
[ERROR] xrdp_wm_log_msg: error loading libvnc.so specified in xrdp.ini, please add a valid entry like lib=libxrdp-vnc.so or similar
[INFO ] error loading libvnc.so specified in xrdp.ini, please add a 
[INFO ] valid entry like lib=libxrdp-vnc.so or similar
[ERROR] Failure setting up module

`/var/log/xrdp-sesman.log`

[INFO ] Starting X server on display 10: Xvnc :10 -auth .Xauthority -geometry 1872x972 -depth 32 -rfbauth /home/`$user`/.vnc/sesman_passwd-`$user`@vm1:10 -bs -nolisten tcp -localhost -dpi 96  
[INFO ] Found X server running at /tmp/.X11-unix/X10
[INFO ] Session started successfully for user `$user` on display 10
[INFO ] Found X server running at /tmp/.X11-unix/X10
[INFO ] Found X server running at /tmp/.X11-unix/X10
[INFO ] Starting the xrdp channel server for display 10
[INFO ] Session in progress on display 10, waiting until the window manager (pid 2239) exits to end the session

![xrdp](https://github.com/neutrinolabs/xrdp/assets/22567760/a7160aa2-cf35-4052-8a69-6300fe237270)

Thank's for your time!

**Comment by matt335672** [comment]
Please check out some of the closed issues in this repository, quite a few of which are related to exactly the same question.
