### ISSUE TITLE
unable to connect to xrdp 0.9.22

### ISSUE THREAD

**Issue by Maboh319** [neutrinolabs/xrdp#2695]
connecting to sesman on 127. 0.0.1:3350
sesman connect ok
sending login info to session manager. Please wait…
login successful for user admin on display 14
error loading libvnc.so specified in xrdp.ini, please add a
valid entry like lib=lib xrdp-vnc.so or similar

**Comment by metalefty** [comment]
See #2693, it was at the top just before you post this.
