### ISSUE TITLE
bypass greeter

### ISSUE THREAD

**Issue by neroita** [neutrinolabs/xrdp#2699]
Hi all , 
I'm using a single session with saved username and password on xrdp.ini .
It works but every time I login I have to hi the ok button.

I don't need auth as I'm running a chrooted read only app that have his auth.

Is there a way to directly open session without seeing the greeter ?

Thank's in advance,
marco.

**Comment by neroita** [comment]
ok , I solved setting autorun in xrdp.ini but it works only if I send user and password from client , is there a way to use user and password saved in xrdp.ini ?

**Comment by matt335672** [comment]
Hi @neroita 

No there isn't. This isn't a use-case we support.

Another way to solve your problem would be to edit the PAM file for xrdp-sesman and allow any password for the user. That would mean it wouldn't matter what password was stored in the RDP file.
