### ISSUE TITLE
couldn't search flatpak in gnome software --- Fedora 38 (including Silverblue)

### ISSUE THREAD

**Issue by m666m** [neutrinolabs/xrdp#2700]
host computer: Fedora Silverblue

    rpm-ostree install xrdp

client computer: Windows 10 mstsc

When login, open GNOME "software", search "any flatpak", no result. Menu "Software repositories" has no flathub repo.

Is this problem caused by  SELinux right?

**Comment by matt335672** [comment]
Does it work on the machine console?

**Comment by m666m** [comment]
yes, I can run flatpak app on console. 

Gnome "show app" can also show the flatpak app, I can run it .

**Comment by matt335672** [comment]
I can reproduce this, but I can't explain it.

- It's not SELinux - `sudo setenforce 0` has no change on behaviour.
- I can't find any polkit actions which would influence this behaviour.
- `flatpak search` appears to me to be working properly:-
![image](https://github.com/neutrinolabs/xrdp/assets/30179339/40e3f4d5-f80f-4a57-a07b-af344b1e805b)
- xrdp appears to be working normally

I can only conclude this is something within the `gnome-software` app.

I suggest you ask this using one of the channels listed on the Fedora Silverblue page:-

https://github.com/fedora-silverblue

**Comment by matt335672** [comment]
More info.

If you log in and kill the background gnome-software app, you can get a log out of gnome-software with `gnome-software --verbose`.

On the console the log includes this line which is missing from an xrdp session:-

```
10:39:27:046 GsPluginFlatpak successfully set up flatpak-system-default
```

There's nothing else to indicate why this should be the case.

**Comment by matt335672** [comment]
This also appears to affect F38 workstation.

**Comment by m666m** [comment]
Interesting, maybe this is a gnome-software issue ,not fedora

**Comment by matt335672** [comment]
I have little doubt it's GNOME related!

Now I can reproduce this on standard Fedora (which I understand reasonably well), I'll try to spend a bit more time on it next week. I can't guarantee a fix though.

**Comment by matt335672** [comment]
It's looking polkit related now, despite the lack of logging.

I'm out of time today. More tomorrow.

**Comment by matt335672** [comment]
This is an interesting one.

On an xrdp session you should get prompts to allow access for some of the update operations. That doesn't seem to be happening, so there's something not quite right about the interaction between `gnome-software`, `systemd --user` and the polkit authentication agent.

That said, the problem as stated can be fixed by

1. Creating the file `/etc/polkit-1/rules.d/50-xrdp-local.rules` with the following contents:-
```js
polkit.addRule(function(action, subject) {
    if (subject.isInGroup("xrdp-local")) {
        switch(action.id) {
            case "org.freedesktop.Flatpak.appstream-update":
            case "org.freedesktop.packagekit.trigger-offline-update":
            case "org.freedesktop.packagekit.system-sources-refresh":
                return "yes";
        }
    }
});
```

2. Creating the group `xrdp-local`, and adding your xrdp user(s) to it:-
```sh
$ sudo groupadd xrdp-local
$ sudo usermod -aG xrdp-local testuser
```

The polkit actions above should be using `auth_admin` for an xrdp session (e.g.):-

```
 pkaction --verbose --action-id org.freedesktop.Flatpak.appstream-update
org.freedesktop.Flatpak.appstream-update:
   . . .
  implicit any:      auth_admin
  . . .
  implicit active:   yes
```
I've changed them to be implicit for a user in the `xrdp-local` group.

Do you want to try that @m666m ?

**Comment by m666m** [comment]
That's great! Everything is ok!

I can searh and open flatpaks in Gnome Software now!

And I have learned another strange knowledge besides SELinux  :D

**Comment by m666m** [comment]
Is there anything else that hasn't been set up? 

I installed a flatpak software that prompts for a password 7 times...

**Comment by matt335672** [comment]
There's plenty you can do to disable prompting, but you'll need to find out about polkit first.

In general, distros don't check their polkit settings for remote graphical sessions as they're not that common.

I'm currently looking at producing a script which will help with this for single user systems only. When it's usable I'll drop a link here.

**Comment by m666m** [comment]
Great, thank you for your help

**Comment by matt335672** [comment]
Have a look at this script:-

https://github.com/matt335672/pk-local

It should help you see what's going on, and any additional changes you might want to make.

**Comment by m666m** [comment]
I installed the script and tested it, but no issues were found. Thank you very much for your patient help.

Because I plan to replace Windows operating system with Fedora for all my computers at home (including PCs and everyone's laptops), your help has given me great confidence. Thank you, Matt!

**Comment by matt335672** [comment]
Glad it's worked out for you.
