### ISSUE TITLE
Unable to log in to xrdp after Centos 8.5.2111 system update

### ISSUE THREAD

**Issue by 800118** [neutrinolabs/xrdp#2702]
Before the update, it was used normally until a few days ago when the system was updated and an error was reported when logging in using Windows remote desktop. How can I solve this problem? Thank you very much.

connecting to sesman on 127.0.0.1:3350
sesman connect ok
sending login info to session manager,please wait...
login successful for user centos on display 11
error loading libvnc.so specified in xrdp.ini,please add a valib entry like lib=libxrdp-vnc.so or similar

**Comment by PvPBender** [comment]
I can't help as I am in progress of trying to fix this myself on my Fedora VPS, but this is `Bug 2207769 - xrdp xrdp-0.9.22-3 missing libvnc.so`

e: I fixed it by getting to version 0.9.22-4 by upgrading Fedora from 37 to 38

**Comment by Aerithlon** [comment]
> 

Centos8 has stopped maintenance and cannot be upgraded. I don't know what to do.

**Comment by 800118** [comment]
> I can't help as I am in progress of trying to fix this myself on my Fedora VPS, but this is `Bug 2207769 - xrdp xrdp-0.9.22-3 missing libvnc.so`
> 
> e: I fixed it by getting to version 0.9.22-4 by upgrading Fedora from 37 to 38

Centos8 has stopped maintenance and cannot be upgraded. I don't know what to do.

**Comment by PvPBender** [comment]
I don't know much about packages or Linux in general, but you either need to find a way to get an older version of xrdp or find a newer package.

**Comment by metalefty** [comment]
You should checkout pinned isssue at the top before raising a new issue.

![image](https://github.com/neutrinolabs/xrdp/assets/941609/79c12132-05b1-4622-b775-43ee43d87812)

**Comment by 800118** [comment]
> You should checkout pinned isssue at the top before raising a new issue.
> 
> ![image](https://user-images.githubusercontent.com/941609/240770078-79c12132-05b1-4622-b775-43ee43d87812.png)

I'm very sorry, because my native language is not English, it's very difficult to read these contents, all through translation software.

**Comment by matt335672** [comment]
@Aerithlon - you make a good point about your native language. Thank you. It helps explain why we have had so many separate issues raised on this.

The EPEL build system is based on a system called Koji. Old xrdp builds are here:-

https://koji.fedoraproject.org/koji/packageinfo?packageID=9026

You should be able to find an older build which works for you. I don't think these packages are signed with the EPEL gpg key - you need to know that.

**Comment by 800118** [comment]
> @Aerithlon - you make a good point about your native language. Thank you. It helps explain why we have had so many separate issues raised on this.
> 
> The EPEL build system is based on a system called Koji. Old xrdp builds are here:-
> 
> https://koji.fedoraproject.org/koji/packageinfo?packageID=9026
> 
> You should be able to find an older build which works for you. I don't think these packages are signed with the EPEL gpg key - you need to know that.

Thank you very much for using the latest xrdp-0.9.22.1-2-el8.x86_ After 64.rpm, the problem was resolved.
