### ISSUE TITLE
xrdp not compatible with gnome (ubuntu 14.04)

### ISSUE THREAD

**Issue by cboseak** [neutrinolabs/xrdp#271]
When logging on via win rdp, the screen is grey with an X for the cursor. 

Remedied by the following:
gnome-session --session=gnome-classic
gnome-session --session=gnome-fallback
gnome-session –session=ubuntu-2d

FEATURE REQUEST:
Please consider support for gnome

**Comment by bolkedebruin** [comment]
This is due the hardware acceleration gnome checks for (but in reality does not require). You can remove the check for hardware acceleration by linking the program for it to /bin/true.

**Comment by Suncatcher** [comment]
> This is due the hardware acceleration gnome checks for (but in reality does not require). You can remove the check for hardware acceleration by linking the program for it to /bin/true.

Could you explain, please, where one should do this? What is *linking the program for it to /bin/true* ?
