### ISSUE TITLE
MacOS: Can't create session for user <user> - X server could not be started

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [neutrinolabs/xrdp#2718]
I'm on macOS Ventura 13.1 and am following the build guide here: https://github.com/neutrinolabs/xrdp/wiki/Building-on-OSX-(not-official)

Client is mstsc on Windows 10.

Getting the following issue after entering valid credentials for the main admin user on the macOS (this is the only user on the system):

> Can't create session for user <user> - X server could not be started

![image](https://github.com/neutrinolabs/xrdp/assets/9839187/778f3721-a8dc-4f71-89b0-4349a4a47504)

I suspected it was because XQuartz wasn't running, so I ran that explicitly (such that the X11 logo appears) both with and without sudo but this did not work.

The guide was followed and the only difference is that I needed to explicitly run `sudo xrdp-sesman`.

**Comment by matt335672** [comment]
Hi @Daniel-Khodabakhsh 

We can't offer support for MacOS in these forums I'm afraid as none of the core team have a Mac available.

See #2194 (pinned issue) for how you can get help with this.
