### ISSUE TITLE
Got black screen after restarting xrdp and xrdp-sesman service

### ISSUE THREAD

**Issue by iamryanchia** [neutrinolabs/xrdp#2720]
My server is ubuntu 22.04. And i installed `Microsoft Remote Desktop` (MRD) on mac to connect it.

Sometimes my remote desktop may be stuck and loses control. I've tried restarting xrdp, but every time it restarts, the screen goes black, and I have to reboot the server to fix it.

I've also tried restarting xrdp when it's not stuck and reconnecting, but the problem still occurs.

Have you encountered this problem before, and do you have any suggestions?

xrdp 0.9.17
xorgxrdp 1:0.2.17-1build1

**Comment by matt335672** [comment]
Hi @iamryanchia 

It's very difficult to advise you at the moment, as you're not giving us any detail on exactly what is happening.

Let's start at the top. What does this mean:-

> Sometimes my remote desktop may be stuck and loses control

Thanks

**Comment by akarl10** [comment]
a similar question was asked some weeks ago on gitter:
https://archive.matrix.org/r/neutrinolabs_xrdp:gitter.im/date/2023/05/22

sleetdrop also reported black screen after something "unknown".

personally I had something like that with plasma (don't remeber the exact version). On my system however it was simply not drawing the content because the mouse cursor changed depending on the window it was over (I could see if I was on a text input field)

"blindly" restart kwin_x11 fixed it. This is not easy to do tough

The reason why I bring this up is to ask what desktop is/was running in the broken session?

**Comment by trainzkid** [comment]
In these black screen instances, do yall get the generic xorg X mouse icon? This would imply that the desktop env/window mgr is failing in some way. Try `pkill -u $USER $WINDOWMGR` (where $USER is your username and $WINDOWMGR is the name of your window mgr, for instance "plasma" for the plasma window mgr).

**Comment by matt335672** [comment]
Again, we need more deetail from the OP on this. What does this mean:-

>   Sometimes my remote desktop may be stuck and loses control

Thanks

**Comment by iamryanchia** [comment]
Sorry for long time no reply. I guess `Microsoft Remote Desktop` is incompatible with xrdp.

What i said means the remote desktop connection becomes broken sometimes. The mouse cursor shows loading and i cannot control my remote server, have to restart the app to recover. No problem happens when connecting to windows. Because the app is made by microsoft, there may be somes issues when working with xrdp.

Than you!

**Comment by trainzkid** [comment]
I've been using win10 and win11 via rdp to connect to xrdp without issues, so this is likely not a compatibility issue

**Comment by iamryanchia** [comment]
![IMG_2555](https://github.com/neutrinolabs/xrdp/assets/41557860/8648848f-f274-43a4-80a5-e06034efd852)

The problem reproduced. The colorful circle is my mouse cursor.

**Comment by matt335672** [comment]
Is that a wait cursor?

It looks more like you've got a problem with one of the applications on your desktop there. Can you remember what you did just before that happened?

**Comment by iamryanchia** [comment]
Yes, i guess it is waitting for `Microsoft Remote Desktop` to response.

Maybe `Microsoft Remote Desktop` is incompatible with another app installed on my mac. I will pay attention afterwards.

Thank you!

**Comment by matt335672** [comment]
It's probably nothing to do with the Mac - the application will be running on the Ubuntu server.

**Comment by danielperna84** [comment]
Not sure if it is related, but I ocasionally manage to _kill_ the Mac Os RDP client by copying passwords from [Enpass](https://www.enpass.io/). The result is a frozen RDP session + the spinning Beachball of death. So at least it looks like the picture posted above.

**Comment by matt335672** [comment]
Hi @danielperna84 

It could be a copy-paste issue. We have some bugs in this area which we're still finding. See (e.g.) #2763.

@iamryanchia - are you using copy-paste?

Thanks @danielperna84 - it's a good point.
