### ISSUE TITLE
Issue template (again)

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#2723]
Inspired by [microsoft/PowerToys](https://github.com/microsoft/PowerToys/issues/new/choose), I would like to introduce the issue template (again). The primary purposes of the issue template are:

- Guide newbies to post questions as a discussion, not an issue
- Collect more information such as xrdp version, client version or something at the first post

Thanks to @matt335672 for always doing such triage kindly. 

Please see [my repository](https://github.com/metalefty/xrdp/issues/new/choose) for working samples. Now I have only 3 types of issues.
- Bug report
- Security vulnerability report
- Questions

Let me know if there are any other types to add as issue templates. A template for Q&A discussions is also needed at least. I know it is possible: https://docs.github.com/en/discussions/managing-discussions-for-your-community/creating-discussion-category-forms

**Comment by matt335672** [comment]
Thanks for looking at this @metalefty 

The bug report looks good to me. I have a few suggestions:-

- It could maybe do with the desktop being added (e.g. GNOME, KDE, XFCE).
- Another useful piece of information might be whether xrdp is running on a VM, or if on a physical machine what graphics cards are installed.

Your 3 types look fine - I think that covers pretty much all of the triaging I do ATM.
