### ISSUE TITLE
xrdp fails tests during install.

### ISSUE THREAD

**Issue by msdarck** [neutrinolabs/xrdp#2724]
When trying to install xrdp using "yay -Syu xrdp" on Arch Linux WSL, some tests fails and the package doesn't install.

It fails "test_common 42" and "test_common 43"

Full output:
https://pastebin.com/pBYEMgBs

test-suite.log: (/home/msdarck/.cache/yay/xrdp/src/xrdp-0.9.22.1/tests/common/test-suite.log)
https://pastebin.com/Gcqc8Wi0

I tried to install the package manually with "makepkg -si" but I still get the same error.

**Comment by msdarck** [comment]
I edited the code, removed the tests that weren't letting me install the package and it works just fine :p

**Comment by matt335672** [comment]
I think that's fine. We've still got a bit of work to do on the file size area. Thanks for reporting it.
