### ISSUE TITLE
xrdp.service: Can't open PID file /run/xrdp/xrdp.pid (yet?) after start: Operation not permitted

### ISSUE THREAD

**Issue by liuguangsen** [neutrinolabs/xrdp#2728]
Hello I connect to the Remote Desktop Services, enter the account password, and the black screen will flash back
The following is a command line error.

liuguangsen@LAPTOP-G1CHMO40:~$ sudo systemctl restart xrdp
liuguangsen@LAPTOP-G1CHMO40:~$ sudo systemctl status xrdp
Failed to dump process list for 'xrdp.service', ignoring: Input/output error
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-06-13 14:56:32 CST; 11s ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 1877 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 1885 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 1886 (xrdp)
      Tasks: 2 (limit: 14300)
     Memory: 3.0M
     CGroup: /system.slice/xrdp.service

Jun 13 14:56:31 LAPTOP-G1CHMO40 xrdp[1885]: (1885)(140034403936064)[INFO ] address [0.0.0.0] port [3389] mode 1
Jun 13 14:56:31 LAPTOP-G1CHMO40 xrdp[1885]: (1885)(140034403936064)[INFO ] listening to port 3389 on 0.0.0.0
Jun 13 14:56:31 LAPTOP-G1CHMO40 xrdp[1885]: (1885)(140034403936064)[INFO ] xrdp_listen_pp done
Jun 13 14:56:31 LAPTOP-G1CHMO40 xrdp[1885]: (1885)(140034403936064)[DEBUG] Closed socket 7 (AF_INET6 :: port 3389)
Jun 13 14:56:31 LAPTOP-G1CHMO40 systemd[1]: xrdp.service: Can't open PID file /run/xrdp/xrdp.pid (yet?) after start: Operation not permitted
Jun 13 14:56:32 LAPTOP-G1CHMO40 systemd[1]: Started xrdp daemon.
Jun 13 14:56:33 LAPTOP-G1CHMO40 xrdp[1886]: (1886)(140034403936064)[INFO ] starting xrdp with pid 1886
Jun 13 14:56:33 LAPTOP-G1CHMO40 xrdp[1886]: (1886)(140034403936064)[INFO ] address [0.0.0.0] port [3389] mode 1
Jun 13 14:56:33 LAPTOP-G1CHMO40 xrdp[1886]: (1886)(140034403936064)[INFO ] listening to port 3389 on 0.0.0.0
Jun 13 14:56:33 LAPTOP-G1CHMO40 xrdp[1886]: (1886)(140034403936064)[INFO ] xrdp_listen_pp done

**Comment by matt335672** [comment]
There's no problem with that listing, except for this:-

```
Failed to dump process list for 'xrdp.service', ignoring: Input/output error
```

That looks very much like a systemd problem. There are multiple reports of this online:-
- https://github.com/microsoft/WSL/issues/8879
- https://github.com/nullpo-head/wsl-distrod/issues/31
- https://bbs.archlinux.org/viewtopic.php?id=272962

It's not clear whether this is causing your xrdp problem or not. I don't understand what this means:-
> and the black screen will flash back

Can you be more specific?

Also, what distro are you running?

**Comment by liuguangsen** [comment]
Step 1, I input the command line guangsen@DESKTOP-85JA84V :~$sudo systemctl restart xrdp

Step 2: I connect to localhost: 3390 through the window Remote Desktop Services

Step 3, I input my account and password in the xrdp tool

The result screen went black and exited, but ubuntu was not successfully opened

**Comment by matt335672** [comment]
Thanks @liuguangsen 

Some questions for you:-
1. Are you logged in to the machine console using the same account? This won't work - see [this FAQ](https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-log-the-same-user-on-on-the-graphical-console-and-over-xrdp-at-the-same-time)
2. Can you post the contents of `/var/log/xrdp-sesman.log` for the time period at which you tried to log in?

Thanks
