### ISSUE TITLE
Quick and dirty patch to make Copy&Paste to work (from Mac/Windows to Linux)

### ISSUE THREAD

**Issue by skydiator** [neutrinolabs/xrdp#275]
We had a xrdp server running in Ubuntu but all our clients connecting are from Mac and Windows. When we do Copy&Paste into the xrdp session, there always an extra line added between new line.

Couldn't figure out a better solution and for the time being here is the patch, just in case someone need this.

Cheers,

```
diff --git a/sesman/chansrv/clipboard.c b/sesman/chansrv/clipboard.c
index 310e209..8d6cf59 100644
--- a/sesman/chansrv/clipboard.c
+++ b/sesman/chansrv/clipboard.c
@@ -894,6 +894,35 @@ clipboard_set_selection_owner(void)
     return 0;
 }

+char *DEFAULT_CC str_replace( const char *string, const char *substr, const char *replacement ){
+  char *tok = NULL;
+  char *newstr = NULL;
+  char *oldstr = NULL;
+  char *head = NULL;
+
+  /* if either substr or replacement is NULL, duplicate string a let caller handle it */
+  if ( substr == NULL || replacement == NULL ) return strdup (string);
+  newstr = strdup (string);
+  head = newstr;
+  while ( (tok = strstr ( head, substr ))){
+    oldstr = newstr;
+    newstr = malloc ( strlen ( oldstr ) - strlen ( substr ) + strlen ( replacement ) + 1 );
+    /*failed to alloc mem, free old string and return NULL */
+    if ( newstr == NULL ){
+      free (oldstr);
+      return NULL;
+    }
+    memcpy ( newstr, oldstr, tok - oldstr );
+    memcpy ( newstr + (tok - oldstr), replacement, strlen ( replacement ) );
+    memcpy ( newstr + (tok - oldstr) + strlen( replacement ), tok + strlen ( substr ), strlen ( oldstr ) - strlen ( substr ) - ( tok - oldstr ) );
+    memset ( newstr + strlen ( oldstr ) - strlen ( substr ) + strlen ( replacement ) , 0, 1 );
+    /* move back head right after the last replacement */
+    head = newstr + (tok - oldstr) + strlen( replacement );
+    free (oldstr);
+  }
+  return newstr;
+}
+
 /*****************************************************************************/
 static int APP_CC
 clipboard_provide_selection_c2s(XSelectionRequestEvent *req, Atom type)
@@ -901,6 +930,13 @@ clipboard_provide_selection_c2s(XSelectionRequestEvent *req, Atom type)
     XEvent xev;
     long val1[2];

+    char *new_str= NULL;
+    new_str = str_replace(g_clip_c2s.data, "\r\n", "\n");
+    memset(g_clip_c2s.data, 0, g_clip_c2s.total_bytes);
+    g_memcpy(g_clip_c2s.data, new_str, strlen(new_str));
+    g_clip_c2s.total_bytes = strlen(new_str);
+    free(new_str);
+
     log_debug("clipboard_provide_selection_c2s: bytes %d",
                 g_clip_c2s.total_bytes);
     if (g_clip_c2s.total_bytes < g_incr_max_req_size)
```

**Comment by therevoman** [comment]
Thanks for posting this quick and dirty fix.  I may have to implement this as we are experiencing extra lines in the line-ending conversion between our windows desktops and the Redhat Linux development systems we connect into.

**Comment by therevoman** [comment]
In case anyone runs across this, I used the above patch with the following patch to fix additional clipboard issues copying from a Linux server back into my Windows 7 client via mstsc.exe.  The clipboard looks something like this :
![image](https://cloud.githubusercontent.com/assets/5229889/23316820/39c72518-fa89-11e6-97f4-616c11e4c177.png)

Some applications don't handle NULL values for CF_LOCALE, CF_TEXT and CF_OEMTEXT properly, so excluding them allowed Win 7 to process the CF_UNICODETEXT properly.  
![image](https://cloud.githubusercontent.com/assets/5229889/23316916/a2b9b64e-fa89-11e6-8f2c-23d6807bb7a7.png)

Applications I experienced the issue with: Microsoft Lync (aka Skype for Business) and Visual Slick Edit.  The error would simply say "Something went wrong while pasting your content."
![image](https://cloud.githubusercontent.com/assets/5229889/23316925/ab69c9b4-fa89-11e6-8023-2db0d6e1a555.png)

This is all that's needed for connecting from Windows 7 to XRDP on RHEL 6 or 7 as it only affects the announcement of which buffers will be populated.
```c
--- neutrinolabs-xrdp-93c55e5.orig/sesman/chansrv/clipboard.c	2017-02-23 14:21:47.133035638 -0700
+++ neutrinolabs-xrdp-93c55e5/sesman/chansrv/clipboard2.c	2017-02-24 11:56:03.776073292 -0700
@@ -700,14 +700,14 @@
             case XRDP_CB_TEXT:
                 log_debug("clipboard_send_format_announce: XRDP_CB_TEXT");
                 /* canned response for "bitmap" */
-                out_uint32_le(s, 0x0000000d);
-                clipboard_out_unicode(s, "", 1);
-                out_uint32_le(s, 0x00000010);
-                clipboard_out_unicode(s, "", 1);
-                out_uint32_le(s, 0x00000001);
-                clipboard_out_unicode(s, "", 1);
-                out_uint32_le(s, 0x00000007);
+                out_uint32_le(s, 0x0000000d); // CF_UNICODETEXT
                 clipboard_out_unicode(s, "", 1);
+                //out_uint32_le(s, 0x00000010); // CF_LOCALE
+                //clipboard_out_unicode(s, "", 1);
+                //out_uint32_le(s, 0x00000001); // CF_TEXT
+                //clipboard_out_unicode(s, "", 1);
+                //out_uint32_le(s, 0x00000007); // CF_OEMTEXT
+                //clipboard_out_unicode(s, "", 1);
                 break;
             default:
                 log_debug("clipboard_send_format_announce: unknown "
```


Hope someone else finds value in this.

**Comment by skydiator** [comment]
@therevoman good find! with your stuff, will it be sufficient to create a PR? @metalefty any input on this?

**Comment by mnty7** [comment]
@skydiator Hi , could you provide an update of your patch? Applying it to the current version of clipboard.c result in this compiling error:

 `clipboard.c:903:18: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘str_replace’`
 `char *DEFAULT_CC str_replace( const char *string, const char *substr, const char *replacement ){`
 `                 ^`

Or am I doing something wrong?
Thanks for your work!

**Comment by skydiator** [comment]
@mnty7 sorry for the late reply... life is too busy.

the DEFAULT_CC was removed by this commit https://github.com/neutrinolabs/xrdp/commit/6ed4c969f4d646a7751fe2da29ba94eddd3d6477

you can use static char* instead of char *DEFAULT_CC

Cheers,

**Comment by metalefty** [comment]
Patch should be submitted as a pull request.
