### ISSUE TITLE
xrdp.service: Job xrdp.service/start failed with result 'dependency'

### ISSUE THREAD

**Issue by Mikunics** [neutrinolabs/xrdp#2750]
### xrdp version

0.9.17

### Detailed xrdp version, build options

~~~
The log reference is NULL - log not initialized properly
xrdp 0.9.17
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-asBei3/xrdp-0.9.17=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -Wno-error=deprecated-declarations
      PKG_CONFIG_PATH=/build/xrdp-asBei3/xrdp-0.9.17/pkgconfig

  Compiled with OpenSSL 3.0.2 15 Mar 2022
~~~

### Operating system & version

Ubuntu 22.04.2 LTS

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp

### What desktop environment do you use?

any

### Environment xrdp running on

Physical Machine without graphics card

### Steps to reproduce

xrdp breaks on installation and does not fix itself after reboot
sudo apt install xrdp
sudo systemctl xrdp status

### ✔️ Expected Behavior

xrdp daemon to be active

### ❌ Actual Behavior

xrdp daemon is dead

### **journalctl -xeu xrdp:**

```
Jul 03 20:46:59 limserver systemd[1]: Dependency failed for xrdp daemon.
░░ Subject: A start job for unit xrdp.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit xrdp.service has finished with a failure.
░░
░░ The job identifier is 7444 and the job result is dependency.
Jul 03 20:46:59 limserver systemd[1]: xrdp.service: Job xrdp.service/start failed with result 'dependency'.
```

### **journalctl -xeu xrdp-sesman:**

```
Jul 03 20:45:29 limserver systemd[1]: Starting xrdp session manager...
░░ Subject: A start job for unit xrdp-sesman.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit xrdp-sesman.service has begun execution.
░░
░░ The job identifier is 7443.
Jul 03 20:45:29 limserver xrdp-sesman[5687]: [INFO ] starting xrdp-sesman with pid 5687
Jul 03 20:45:29 limserver systemd[1]: xrdp-sesman.service: Can't open PID file /run/xrdp/xrdp-sesman.pid (yet?) after start: Operation not permitted
Jul 03 20:46:59 limserver systemd[1]: xrdp-sesman.service: start operation timed out. Terminating.
Jul 03 20:46:59 limserver xrdp-sesman[5687]: [INFO ] shutting down sesman 1
Jul 03 20:46:59 limserver systemd[1]: xrdp-sesman.service: Failed with result 'timeout'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit xrdp-sesman.service has entered the 'failed' state with result 'timeout'.
Jul 03 20:46:59 limserver systemd[1]: Failed to start xrdp session manager.
░░ Subject: A start job for unit xrdp-sesman.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit xrdp-sesman.service has finished with a failure.
░░
░░ The job identifier is 7443 and the job result is failed.
```

xrdp.log is empty

xrdp-sesman.log contains:

```
20230703-20:45:29] [INFO ] starting xrdp-sesman with pid 5687
[20230703-20:46:59] [INFO ] shutting down sesman 1
```

Fixes tried:
sudo apt --reinstall xrdp
sudo apt purge xrdp
sudo systemctl restart xrdp

Interestingly there is a specific line that I'm not sure of when installing using apt:

```
$ sudo apt install xrdp
...
Generating 2048 bit rsa key...

ssl_gen_key_xrdp1 ok

saving to /etc/xrdp/rsakeys.ini

Created symlink /etc/systemd/system/multi-user.target.wants/xrdp-sesman.service → /lib/systemd/system/xrdp-sesman.service.
Created symlink /etc/systemd/system/multi-user.target.wants/xrdp.service → /lib/systemd/system/xrdp.service.
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 142. <=============== WEIRD LINE HERE
Setting up xorgxrdp (1:0.2.17-1build1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
...
```

**Comment by matt335672** [comment]
This looks like #2620 

Let's pick up where that one left off. Try running sesman from the command line to see if you get any useful info:-

```
sudo xrdp-sesman -n
```

**Comment by matt335672** [comment]
I'm about to go offline for a few weeks so I won't have time to look into this.

However, I've just noted something a bit weird.

In your `xrdp -v`, you've got this line:-

```
--localstatedir=/var
```

Looking at our code, AFAICT, this means xrdp-sesman creates a PID file in `/var/run/xrdp-sesman.pid`.

However, it looks like systemd is looking for this file:-

```
/run/xrdp/xrdp-sesman.pid
```

It may be that the Debian patches are doing something clever here, but I haven't got time to look into it. I reckon that's the source of the problem though.

Try running `xrdp-sesman` by hand using `sudo xrdp-sesman`. then look for the PID file with `find /run -name xrdp-sesman.pid`. This should tally with the `PIDFile=` entry in `/usr/lib/systemd/system/xrdp-sesman.service`. If it doesn't fix the systemd unit file, reboot and try again.

Please report back!

**Comment by Mikunics** [comment]
doing `sudo xrdp-sesman -n` leads to the terminal blocking without outputting anything

running `sudo xrdp-sesman` outputs nothing but running it again shows that it is already running and outputs the ff:

`if it's not running, try removing /var/run/xrdp/xrdp-sesman.pid`

I then ran `sudo find /run -name xrdp-sesman.pid` and it didn't find anything

I then rebooted the system and tried running `sudo xrdp-sesman` and `sudo find /run -name xrdp-sesman.pid` again to no results

Checking on the journalctl -xe after rebooting, the same problem persists

**Comment by Mikunics** [comment]
I've figured out that the problem does not seem to stem from xrdp rather from a broken symlink on my installation. After running the instructions in the following [website](https://www.thegeekdiary.com/authorization-not-available-check-if-polkit-service-is-running-or-see-debug-message-for-more-information-centos-rhel-7-ssh-service-error/), xrdp started working again after a reboot. Thanks for the help troubleshooting anyways

**Comment by matt335672** [comment]
Thanks for the update @Mikunics 

The link you've provided above seems to be dead. If you've go the time, could you possibly provide a bit more info for any other users reading this thread?

Thanks.

**Comment by wogho** [comment]
> ### xrdp version
> 
> 0.9.17
> 
> ### Detailed xrdp version, build options
> 
> ~~~
> 
> The log reference is NULL - log not initialized properly
> 
> xrdp 0.9.17
> 
>   A Remote Desktop Protocol Server.
> 
>   Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
> 
>   See https://github.com/neutrinolabs/xrdp for more information.
> 
> 
> 
>   Configure options:
> 
>       --enable-ipv6
> 
>       --enable-jpeg
> 
>       --enable-fuse
> 
>       --enable-rfxcodec
> 
>       --enable-opus
> 
>       --enable-painter
> 
>       --enable-vsock
> 
>       --build=x86_64-linux-gnu
> 
>       --prefix=/usr
> 
>       --includedir=${prefix}/include
> 
>       --mandir=${prefix}/share/man
> 
>       --infodir=${prefix}/share/info
> 
>       --sysconfdir=/etc
> 
>       --localstatedir=/var
> 
>       --disable-silent-rules
> 
>       --libdir=${prefix}/lib/x86_64-linux-gnu
> 
>       --libexecdir=${prefix}/lib/x86_64-linux-gnu
> 
>       --disable-maintainer-mode
> 
>       --disable-dependency-tracking
> 
>       --with-socketdir=/run/xrdp/sockdir
> 
>       build_alias=x86_64-linux-gnu
> 
>       CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-asBei3/xrdp-0.9.17=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security
> 
>       LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
> 
>       CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -Wno-error=deprecated-declarations
> 
>       PKG_CONFIG_PATH=/build/xrdp-asBei3/xrdp-0.9.17/pkgconfig
> 
> 
> 
>   Compiled with OpenSSL 3.0.2 15 Mar 2022
> 
> ~~~
> 
> 
> 
> ### Operating system & version
> 
> Ubuntu 22.04.2 LTS
> 
> ### Installation method
> 
> dnf / apt / zypper / pkg / etc
> 
> ### Which backend do you use?
> 
> xorgxrdp
> 
> ### What desktop environment do you use?
> 
> any
> 
> ### Environment xrdp running on
> 
> Physical Machine without graphics card
> 
> ### What's your client?
> 
> _No response_
> 
> ### Area(s) with issue?
> 
> _No response_
> 
> ### Steps to reproduce
> 
> xrdp breaks on installation and does not fix itself after reboot
> 
> sudo apt install xrdp
> 
> sudo systemctl xrdp status
> 
> ### ✔️ Expected Behavior
> 
> xrdp daemon to be active
> 
> ### ❌ Actual Behavior
> 
> xrdp daemon is dead
> 
> ### Anything else?
> 
> ### **journalctl -xeu xrdp:**
> 
> 
> 
> ```
> 
> Jul 03 20:46:59 limserver systemd[1]: Dependency failed for xrdp daemon.
> 
> ░░ Subject: A start job for unit xrdp.service has failed
> 
> ░░ Defined-By: systemd
> 
> ░░ Support: http://www.ubuntu.com/support
> 
> ░░
> 
> ░░ A start job for unit xrdp.service has finished with a failure.
> 
> ░░
> 
> ░░ The job identifier is 7444 and the job result is dependency.
> 
> Jul 03 20:46:59 limserver systemd[1]: xrdp.service: Job xrdp.service/start failed with result 'dependency'.
> 
> ```
> 
> 
> 
> ### **journalctl -xeu xrdp-sesman:**
> 
> 
> 
> ```
> 
> Jul 03 20:45:29 limserver systemd[1]: Starting xrdp session manager...
> 
> ░░ Subject: A start job for unit xrdp-sesman.service has begun execution
> 
> ░░ Defined-By: systemd
> 
> ░░ Support: http://www.ubuntu.com/support
> 
> ░░
> 
> ░░ A start job for unit xrdp-sesman.service has begun execution.
> 
> ░░
> 
> ░░ The job identifier is 7443.
> 
> Jul 03 20:45:29 limserver xrdp-sesman[5687]: [INFO ] starting xrdp-sesman with pid 5687
> 
> Jul 03 20:45:29 limserver systemd[1]: xrdp-sesman.service: Can't open PID file /run/xrdp/xrdp-sesman.pid (yet?) after start: Operation not permitted
> 
> Jul 03 20:46:59 limserver systemd[1]: xrdp-sesman.service: start operation timed out. Terminating.
> 
> Jul 03 20:46:59 limserver xrdp-sesman[5687]: [INFO ] shutting down sesman 1
> 
> Jul 03 20:46:59 limserver systemd[1]: xrdp-sesman.service: Failed with result 'timeout'.
> 
> ░░ Subject: Unit failed
> 
> ░░ Defined-By: systemd
> 
> ░░ Support: http://www.ubuntu.com/support
> 
> ░░
> 
> ░░ The unit xrdp-sesman.service has entered the 'failed' state with result 'timeout'.
> 
> Jul 03 20:46:59 limserver systemd[1]: Failed to start xrdp session manager.
> 
> ░░ Subject: A start job for unit xrdp-sesman.service has failed
> 
> ░░ Defined-By: systemd
> 
> ░░ Support: http://www.ubuntu.com/support
> 
> ░░
> 
> ░░ A start job for unit xrdp-sesman.service has finished with a failure.
> 
> ░░
> 
> ░░ The job identifier is 7443 and the job result is failed.
> 
> ```
> 
> 
> 
> xrdp.log is empty
> 
> 
> 
> xrdp-sesman.log contains:
> 
> 
> 
> ```
> 
> 20230703-20:45:29] [INFO ] starting xrdp-sesman with pid 5687
> 
> [20230703-20:46:59] [INFO ] shutting down sesman 1
> 
> ```
> 
> 
> 
> Fixes tried:
> 
> sudo apt --reinstall xrdp
> 
> sudo apt purge xrdp
> 
> sudo systemctl restart xrdp
> 
> 
> 
> Interestingly there is a specific line that I'm not sure of when installing using apt:
> 
> 
> 
> ```
> 
> $ sudo apt install xrdp
> 
> ...
> 
> Generating 2048 bit rsa key...
> 
> 
> 
> ssl_gen_key_xrdp1 ok
> 
> 
> 
> saving to /etc/xrdp/rsakeys.ini
> 
> 
> 
> Created symlink /etc/systemd/system/multi-user.target.wants/xrdp-sesman.service → /lib/systemd/system/xrdp-sesman.service.
> 
> Created symlink /etc/systemd/system/multi-user.target.wants/xrdp.service → /lib/systemd/system/xrdp.service.
> 
> Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 142. <=============== WEIRD LINE HERE
> 
> Setting up xorgxrdp (1:0.2.17-1build1) ...
> 
> Processing triggers for man-db (2.10.2-1) ...
> 
> Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
> 
> ...
> 
> ```

**Comment by Paiman-Rasoli** [comment]
The easiest way is to uninstall it and re-install it.

1. remove xrdp package: `sudo apt remove --purge xrdp -y`
2. remove logs `sudo rm -rf /etc/xrdp && sudo rm -rf /var/log/xrdp*`
3. re-install `sudo apt update && sudo apt install xrdp -y`
