### ISSUE TITLE
Fresh install Debian 12/Cinnamon - Xrdp Not Working

### ISSUE THREAD

**Issue by ghost** [neutrinolabs/xrdp#2756]
### xrdp version

 0.9.80 

### Detailed xrdp version, build options
build steps
~~~
            cd ~/apps
            git clone https://github.com/neutrinolabs/xrdp
            cd ~/apps/xrdp
            ./bootstrap
            ./configure
            make
            sudo make install
~~~

### Operating system & version

Debian 12 - Cinnamon

### Installation method

other

### What desktop environment do you use?

Cinnamon

### Environment xrdp running on

Dell Optiplex 9020, Onboard Intel Video only

### What's your client?

Debian 12 - Cinnamon, Remmina 1.4.29

### Area(s) with issue?

Session manager (sesman)

### Steps to reproduce

Fresh install of Debian 12 live, download and compile xRDP via github
try to connect from another pc and doesnt work.

only error in system log is:
[ERROR] waitforx: Unable to find any RandR outputs
[ERROR] An error occurred waiting for the X server

### ✔️ Expected Behavior

successful connection 

### ❌ Actual Behavior

session is not created, cannot connect to desktop

**Comment by matt335672** [comment]
@thwerks - you're trying to run the latest development wavefront from the looks of it.

Have you also built and installed xorgxrdp?
