### ISSUE TITLE
Vertical scroll speed too fast (again)?

### ISSUE THREAD

**Issue by enricotagliavini** [neutrinolabs/xrdp#2757]
### Discussed in https://github.com/neutrinolabs/xrdp/discussions/2754

<div type='discussions-op-text'>

<sup>Originally posted by **enricotagliavini** July 18, 2023</sup>
Hello,

it looks like I'm experiencing the exact same issue as described in [#150](https://github.com/neutrinolabs/xorgxrdp/issues/150) , with a difference: it happens also when using the VNC backend, so it's not related to xorgxrdp.

The versions I'm using:
-  OS: CentOS Stream 8
- xrdp: 0.9.22.1-2
- xorgxrdp: 0.9.19-5

I tried with Remmina from Linux (Fedora) and Microsoft RDP client from MacOS and they both show the same issue. However from Microsoft Windows using RDP it works as expected, there is no scrolling issue from there. Using the same clients from Linux and MacOS, connecting to a Windows machine the scroll works fine, the issue with scrolling happens only when connecting to XRDP.

If I use a mouse with a scroll wheel the scrolling works as expected from all clients, same amount of scroll as on the client machine doing the same thing (e.g. scroll a web page or a folder with many files), but when using the two fingers scroll from a touchpad it does about 10 times the scrolling, making it next to impossible to use if you don't have access to a physical mouse, which is often the case with laptops.

I would appreciate very much any hint or advise you can share though, if any.

Iss there anything I can do to help investigating / fixing the issue? </div>

**Comment by metalefty** [comment]
Duplicate.

**Comment by enricotagliavini** [comment]
Hello,

may I ask what's the duplicate issue? I'll follow that one.

Thank you.
Kind regards.

**Comment by metalefty** [comment]
You don't need to double post the same topic both on discussions and issues. So this is duplicate of #2754.

**Comment by enricotagliavini** [comment]
Apologies for that, github proposed to convert the discussion into an issue, since there was no answer I did so. Maybe we should close the discussion and keep the issue open then? This really looks like an issue with XRDP, in my humble opinion. Not sure why it doesn't show up with all clients though.

**Comment by metalefty** [comment]
No problem. I have raised this: https://github.com/neutrinolabs/xorgxrdp/issues/265

So I would like to close both of your issue/discussion. Let's move there.

**Comment by enricotagliavini** [comment]
I see, thanks. Ok let's try that. I had the issue also when using the VNC backend, but fixing the issue in the xorg backend would be enough as that's the preferred backend anyway.

Thank you!
Kind regards.
