### ISSUE TITLE
None ASCII characters sent through keyboard not accepted.

### ISSUE THREAD

**Issue by seflerZ** [neutrinolabs/xrdp#2764]
### xrdp version

0.9.20

### Detailed xrdp version, build options

~~~
PASTE HERE
~~~

### Operating system & version

Ubuntu 22.04

### Installation method

git clone & make install

### Which backend do you use?

xorg

### What's your client?

Microsoft Android RD Client

### Area(s) with issue?

Keyboard / Mouse

### Steps to reproduce

The MS Android client supports sending none ASCII characters to remote server directly which makes none latin input easy. It works great on Winows servers, but it doesn't work on Linux running xrdp.

### ✔️ Expected Behavior

Characters displayed.

### ❌ Actual Behavior

None thing happens.

**Comment by matt335672** [comment]
Duplicate of #1990 I believe. Or am I missing something?

**Comment by seflerZ** [comment]
Indeed. I'll try to investigate that issue.
