### ISSUE TITLE
Unable to login after timeout

### ISSUE THREAD

**Issue by rtest2344** [neutrinolabs/xrdp#2769]
### xrdp version

0.9.17

### Detailed xrdp version, build options

~~~
xrdp 0.9.17
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-asBei3/xrdp-0.9.17=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -Wno-error=deprecated-declarations
      PKG_CONFIG_PATH=/build/xrdp-asBei3/xrdp-0.9.17/pkgconfig

  Compiled with OpenSSL 3.0.2 15 Mar 2022
root@ip-172-20-1-23:/# ubuntu -V
ubuntu: command not found
root@ip-172-20-1-23:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
root@ip-172-20-1-23:/# xrdp --version
xrdp 0.9.17
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-asBei3/xrdp-0.9.17=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -Wno-error=deprecated-declarations
      PKG_CONFIG_PATH=/build/xrdp-asBei3/xrdp-0.9.17/pkgconfig

  Compiled with OpenSSL 3.0.2 15 Mar 2022
~~~

### Operating system & version

Ubuntu 22.04.2

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp (I think)

### What desktop environment do you use?

GNOME (I think)

### Environment xrdp running on

AWS EC2

### What's your client?

MS RDP

### Area(s) with issue?

Authentication, Session manager (sesman)

### Steps to reproduce

1. Login to Xrdp normally
2. Wait a few minutes with no input RDP
3. Go to login after timeout and Xrdp ask to login
4. Unable to login when correct password is provided

### ✔️ Expected Behavior

Able to log in

### ❌ Actual Behavior

Unable to log in. Changing the password does nothing. 

### Anything else?

Output from from login screen says incorrect password. 
Login Screen in refference:
![image](https://github.com/neutrinolabs/xrdp/assets/92396427/1251ba95-ecff-4543-8876-3f22ca3af29f)

**Comment by matt335672** [comment]
@rtest2344 - that screen is nothing to do with xrdp. It looks like a screen lock to me.

Verify by disabling the screen lock on your desktop.

**Comment by rtest2344** [comment]
@matt335672 - I appreciate the help. I disabled the screen lock and so far so good. I'm new to anything linux admin-ish. 

I figured this was all one and the same, but was I wrong. It looks like this is a gnome related issue, and I can google from here. Just for my own education, what is the relationship between xrdp and gnome? Is gnome the underlying OS and xrdp? sits on top of it?

edit: Looks like I'm getting xrdp and xfce confused. I need more coffee.

**Comment by matt335672** [comment]
GNOME and xfce are both desktop environments. You need a desktop environment for any kind of graphical login. This would typically be used for a workstation. For a server you may or may not bother with a graphical login.

xrdp provides a way for an RDP client to connect over the network to your machine and run a desktop environment on that connection.

Screen locking can be awkward to get running. I don't recognise the screen you've posted above, so I can't say how your desktop environment is trying to provide it.

**Comment by rtest2344** [comment]
It looks like it was a GNOME based screen lock and just turning it off worked. Thanks for the background and appreciate the help!

**Comment by rtest2344** [comment]
Closing.
