### ISSUE TITLE
Sync list of keymaps to xrdp_keyboard.ini

### ISSUE THREAD

**Issue by mirabilos** [neutrinolabs/xrdp#277]
Some new keymaps were added, but xrdp/xrdp_keyboard.ini was not updated with it.

So weren't the Makefiles, but I've got a patch for that already, which will be submitted as part of a larger amount of push requests upcoming soon. For now:

--- a/instfiles/Makefile.am
+++ b/instfiles/Makefile.am
@@ -14,10 +14,14 @@ startscript_DATA = \
   km-040c.ini \
   km-0410.ini \
   km-0411.ini \
+  km-0414.ini \
   km-0415.ini \
+  km-0416.ini \
   km-0419.ini \
   km-041d.ini \
   km-0807.ini \
+  km-080c.ini \
+  km-0813.ini \
   km-0816.ini \
   km-e0010411.ini \
   km-e0200411.ini \

**Comment by itamarjp** [comment]
fixed and merged, please tell me if looks good.

https://github.com/neutrinolabs/xrdp/pull/278

please reopen if its not good enough

**Comment by mirabilos** [comment]
Sorry, not enough: the xrdp_keyboard.ini must also be adjusted to list them. I don't know which entries are correct for that, though.
