### ISSUE TITLE
Show black screen after logged in

### ISSUE THREAD

**Issue by kaizisntme** [neutrinolabs/xrdp#2775]
### xrdp version

0.9.12

### Detailed xrdp version, build options

I watched a youtube video about how to use Ubuntu GUI and followed. At that time, I can use it, but few hours later, I can't use it anymore. I've tried restart the computer but not working. After I connected to Remote Desktop, it asked me to login and after I logged in, it just showing black screen.

### Operating system & version

Ubuntu 20.04

### Installation method

dnf / apt / zypper / pkg / etc

### What desktop environment do you use?

Xfce

### Environment xrdp running on

wsl 2

### What's your client?

microsoft client on windows

### Area(s) with issue?

Session manager (sesman)

### Steps to reproduce

Connect to localhost:<port> by Remote Desktop Connection

### ✔️ Expected Behavior

Load Ubuntu after logged in

### ❌ Actual Behavior

Keep showing black screen

**Comment by matt335672** [comment]
Check you're using a different account for xrdp than you're using for logging in to the machine normally. This is covered in the FAQ:-

https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ

**Comment by kaizisntme** [comment]
> Check you're using a different account for xrdp than you're using for logging in to the machine normally. This is covered in the FAQ:-
> 
> https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ

I'm using the same one and I just have 1 account.

**Comment by matt335672** [comment]
For Ubuntu, which uses systemd, you'll have to use a different account for xrdp as explained in the FAQ. You can't log in to the console and xrdp at the same time with the same user.

**Comment by kaizisntme** [comment]
> For Ubuntu, which uses systemd, you'll have to use a different account for xrdp as explained in the FAQ. You can't log in to the console and xrdp at the same time with the same user.

It worked thanks. I created new account and it worked but I need to config again. Is there any ways to import config, packages, app, ... from old user to my new user? Thanks

**Comment by matt335672** [comment]
A lot of your configs will be stored under `$HOME/.config`. This is otherwise known as `XDG_CONFIG_HOME`. See this page on the Arch Wiki for a good explanation of XDG directories:-

https://wiki.archlinux.org/title/XDG_Base_Directory

Have a look in there, and also in `$HOME/.local`. That should give you a clue as to what can easily be copied over.

**Comment by matt335672** [comment]
@KaizOffical - do you need any more input on this?

**Comment by kaizisntme** [comment]
> @KaizOffical - do you need any more input on this?

Thanks, that's all I need.
