### ISSUE TITLE
xrdp requirement on xorgxrdp version

### ISSUE THREAD

**Issue by moobyfr** [neutrinolabs/xrdp#2796]
### xrdp version

0.9.21.1

### Detailed xrdp version, build options

~~~
xrdp 0.9.21.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/local/testing/xrdp-0.9.21.1=. -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 
      PKG_CONFIG_PATH=/local/testing/xrdp-0.9.21.1/pkgconfig

  Compiled with OpenSSL 1.1.1n  15 Mar 2022

~~~

### Operating system & version

Debian 11

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp

### What desktop environment do you use?

xfce

### Environment xrdp running on

physical/VM

### What's your client?

Microsoft remote desktop 0.9.20 

### Area(s) with issue?

Other

### Steps to reproduce

upgrading xrdp to latest debian 11 package (/2023/09/18) ( 0.9.12 -> 0.9.21.1) for security upgrade, makes the xrdp non usuable:
the user connect to the server, the screen keeps getting black, but the session is correctly started on server.
The issue is in xorgxrdp version which was kept at 0.2.12.
manually rebuilding xorgxrdp from testing ([0.9.19-1] solves the black screen issue.
(Still need to clarify some keymap changes)

### ✔️ Expected Behavior

the session must be visible

### ❌ Actual Behavior

black screen

### Anything else?

xrdp should care about xorgxrdp version ? (at least in package build )

**Comment by moobyfr** [comment]
Debian bugreport: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1052197

**Comment by metalefty** [comment]
Hello again. Yes, xorgxrdp must be updated or recompiled in this case. We bump `CLIENT_INFO_CURRENT_VERSION` when changes on xrdp cause incompatibility with xorgxrdp. Recompile xorgxrdp then.

Version match is checked here for example:
https://github.com/neutrinolabs/xorgxrdp/blob/v0.9/module/rdpClientCon.c#L870-L876

I don't remember exactly if xorgxrdp 0.2.12 have this check but this is introduced to detect & record such version mismatch.

**Comment by moobyfr** [comment]
The debian package of xorgxrdp on bullseye is 0.2.12  and the check was introduced in 0.2.16

**Comment by metalefty** [comment]
Just in case, it is recommended to rebuild xorgxrdp against the updated xrdp after updating xrdp. It is not always necessary though.

**Comment by amibumping** [comment]
> Just in case, it is recommended to rebuild xorgxrdp against the updated xrdp after updating xrdp. It is not always necessary though.

Having the same error, how can I rebuild xorgxrdp? 
I am using DietPi by the way.

**Comment by metalefty** [comment]
Same from us: https://github.com/MichaIng/DietPi/issues/5976#issuecomment-1727134233
> We don't build these packages ourselves.

Ask Debian team to rebuild and get rebuilt xorgxrdp instead. I don't recommend rebuilding by yourself.

> Having the same error, how can I rebuild xorgxrdp?

However, your issue seems different from this, not same. Because you get "login failed for diet pi". 

Version mismatch of xrdp and xorgxrdp doesn't cause "login failed". Login succeeds but black screen or close connection right after login will happen. Login failed is login failed, its another issue. Confirm your password or something.

**Comment by amibumping** [comment]
> Same from us: [MichaIng/DietPi#5976 (comment)](https://github.com/MichaIng/DietPi/issues/5976#issuecomment-1727134233)
> 
> > We don't build these packages ourselves.
> 
> Ask Debian team to rebuild and get rebuilt xorgxrdp instead. I don't recommend rebuilding by yourself.
> 
> > Having the same error, how can I rebuild xorgxrdp?
> 
> However, your issue seems different from this, not same. Because you get "login failed for diet pi".
> 
> Version mismatch of xrdp and xorgxrdp doesn't cause "login failed". Login succeeds but black screen or close connection right after login will happen. Login failed is login failed, its another issue. Confirm your password or something.

It worked right before the update, and I didn't change any passwords nor change configs

**Comment by metalefty** [comment]
If you need further help, could you raise your own issue with logs? Don't forget to include xrdp-sesman.log.

**Comment by metalefty** [comment]
Debian xorgxrdp package has been rebuilt against xrdp v0.9.22.1.
https://tracker.debian.org/news/1464971/accepted-xorgxrdp-10212-1deb11u1-source-into-oldstable-security/

@moobyfr Can be closed now?

**Comment by moobyfr** [comment]
upstream fixed the issue, closing
