### ISSUE TITLE
 belgian keyboard issue

### ISSUE THREAD

**Issue by itamarjp** [neutrinolabs/xrdp#282]
we need to include keymap for this keyboard

xrdp-genkeymap /etc/xrdp/km-080c.ini

bug reported in sourceforge.

https://sourceforge.net/p/xrdp/bugs/58/

dears,
i have a belgian keyboard (similar of azerty french but some difference)
i try everything to adapt the keyboard but it' impossible....
i try sudo xrdp-genkeymap /etc/xrdp/km-0409.ini to pu in fr but when i push on a letter, i see number 7?

What can i do ?

regards
Marin

**Comment by willemdh** [comment]
FYI, I managed to make xrdp work on my Pi with Belgian keyboard.
First log into your system with a real screen, not with xrdp. Then you need to copy km-0409.ini to km-0409.ini.bak and generate the correct ini.
You can find the country codes here: http://xrdp.sourceforge.net/documents/keymap/rfc1766.html
For me I needed to:

    sudo xrdp-genkeymap /etc/xrdp/km-0813.ini

Then I copied km-0813.ini to km-0409.ini

    sudo cp km-0813.ini km-0409.ini

And rebooted, after which I was able to use azerty keyboard.

![image](https://cloud.githubusercontent.com/assets/6462991/14291458/f86df8d2-fb63-11e5-9cb3-58886488777f.png)

**Comment by DavorJ** [comment]
Do

	nano /etc/xrdp/xrdp_keyboard.ini

and edit:

	[default_rdp_layouts]
	rdp_layout_be=0x00000813
	[default_layouts_map]
	rdp_layout_be=be

It should work without problems now. The `km-00000813.ini` is there... but not in the `xrdp_keyboard.ini` file.

**Comment by metalefty** [comment]
I've created #858.

**Comment by metalefty** [comment]
Merged.
