### ISSUE TITLE
xrdp security issue with /tmp/.xrdp/* and /tmp/*-lock files

### ISSUE THREAD

**Issue by fang64** [neutrinolabs/xrdp#283]
Hello again,
I am seeing a .xrdp folder in tmp with predictable filenames that is world writeable 
drwxrwxrwt   82 root     root    4.0K Sep 21 12:09 .xrdp

If a user creates a file with xrdp_display_# within this directory will this cause a problem if the display_# is attempted to be created later? 

The other issue is files such as these that are also predictable and could result in denial of service.
-r--r--r--    1 root     general   11 Sep 21 09:26 .X15-lock
-r--r--r--    1 root     general   11 Sep 21 09:25 .X14-lock
-r--r--r--    1 root     general   11 Sep 21 09:23 .X13-lock
-r--r--r--    1 root     general   11 Sep 21 19:54 .X12-lock

Being used on a large multi-user system this presents alot of problems I am seeing a few hundred of these .X#-lock files if someone writes there before you do what will happen?

These should exist in a more secure path in the system if these files need to be user accessible there are better paths to use /run/user/$(id -u)/\* if the files must be user accessible as this location is created on behalf of the user and that user is the only one whom can write there.

**Comment by fang64** [comment]
Are these paths configurable?

**Comment by moobyfr** [comment]
IMHO, these locks files are set by X itself, and even on non xrdp it could cause a issue.
I'm not sure Xorg support a configuration to specify the directory to use. /var/run/$(id-u)/ is not possible because the directory must list all lock files to be able to check a empty slot

**Comment by fang64** [comment]
@moobyfr 
Ah ok, well ignoring the .X#-lock, what about world writable .xrdp?

**Comment by jsorg71** [comment]
The X11 files
/tmp/.X%d-lock
/tmp/.X11-unix/X%d
are created but X11 code in X11rdp.

The files in
/tmp/.xrdp/xrdp-%s
/tmp/.xrdp/chansrv-%s
..
Are going away soon.

That leaves
/tmp/.xrdp/xrdp_display_%d
/tmp/.xrdp/xrdp_chansrv_audio_in_socket_%d
/tmp/.xrdp/xrdp_chansrv_audio_out_socket_%d
...
Currently, it's hard coded.
When sesman looks for a free display, it looks if these files exist.  There can be a problem if someone creates the file in-between the check and when the session starts.  This is an issue.
Not sure how to fix it.  Maybe /var/run/$id is an option would work.

**Comment by metalefty** [comment]
The path can be now configured.
Try `./configure --with-socket-dir=/path/to/socketdir`.
