### ISSUE TITLE
wrong message order in `[MS-RDPEFS]` setup

### ISSUE THREAD

**Issue by akallabeth** [neutrinolabs/xrdp#2834]
1. Got a report https://github.com/FreeRDP/FreeRDP/discussions/9501
1. found https://github.com/neutrinolabs/xrdp/blob/ee328784dcac48f16fb519e9d9e130737309df8e/sesman/chansrv/devredir.c#L381
1. [[MS-RDPEFS]](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpefs/2ecd5c18-8c8c-4f5d-97ef-794ce19e91ba) tells that this is the wrong state you´re sending the `RDPDR_USER_LOGGEDON_PDU`

**Comment by matt335672** [comment]
Thanks @akallabeth 

I'm out of time at the mo', but I'll look later in the week. Your OP appears to have sent all relevant info.

**Comment by matt335672** [comment]
I can confirm xrdp is not conforming to [MS-RDPEFS], so it's almost certainly an xrdp bug.

It happens with FreeRDP 2.11.2 (Alt Linux 10.1) but not 2.9.0.

By moving the `devredir_send_server_user_logged_on()` down to after we've received the client core capability response (as the specification) I can get the redirection working again.

That's a quick test. I'm not testing the client has `RDPDR_USER_LOGGEDON_PDU` set yet. I'll also need to re-test with existing working clients then I can issue a patch.
