### ISSUE TITLE
It's not clear from xrdp/xrdp.ini how to set up audio on a BSD or linux system

### ISSUE THREAD

**Issue by yurivict** [neutrinolabs/xrdp#2843]
### xrdp version

0.9.23.1

### Detailed xrdp version, build options

n/a

### Operating system & version

FreeBSD 13.2

### Installation method

Doesn't matter

### Steps to reproduce

xrdp/xrdp.ini allows to set up the remote display+keyboard+mouse, but it isn't clear how to redirect the audio.

The words "audio" or "sound" don't appear in this file.

### ✔️ Expected Behavior

Being able to use sound over RDP.

### ❌ Actual Behavior

Unclear.

**Comment by metalefty** [comment]
Hello yuri, 

you don't need to configure `xrdp.ini` to enable audio redirection but PulseAudio is required. 

`audio/pulseaudio-module-xrdp` will be installed together if you installed xrdp from pkg/ports. You will see 2 virtual sound cards `xrdp-sink` and `xrdp-source`. `xrdp-source` is for microphone, sound redirection from client to server.

Play some sound specifying the output device to `xrdp-sink`. Then audio redirection will work.

Pipewire is in progress. I just added `audio/pipewire-module-xrdp` recently but I am still not familiar with pipewire.

```
$  pacmd list-cards
2 card(s) available.
    index: 2
        name: <xrdp.sink>
        driver: <module-xrdp-sink.c>
        properties:
                device.icon_name = "audio-card"
        profiles:
                output:xrdp: xrdp audio output (priority 10, available: unknown)
        active profile: <output:xrdp>
        sinks:
                xrdp-sink/#3: remote audio output
        sources:
                xrdp-sink.monitor/#4: Monitor of remote audio output
        ports:
                xrdp-output: xrdp output (priority 0, latency offset 0 usec, available: yes)
                        properties:

    index: 3
        name: <xrdp.source>
        driver: <module-xrdp-source.c>
        properties:
                device.icon_name = "audio-card"
        profiles:
                input:xrdp: xrdp audio input (priority 10, available: unknown)
        active profile: <input:xrdp>
        sources:
                xrdp-source/#5: remote audio input
        ports:
                xrdp-input: xrdp input (priority 0, latency offset 0 usec, available: yes)
                        properties:
```


![image](https://github.com/neutrinolabs/xrdp/assets/941609/40a4110e-3daf-477d-b7ad-01f7dace276b)
