### ISSUE TITLE
Unable to Login on Ubuntu Desktop 23.10

### ISSUE THREAD

**Issue by AnastasiyaSoyka** [neutrinolabs/xrdp#2844]
### xrdp version

0.9.21.1

### Detailed xrdp version, build options

~~~
xrdp 0.9.21.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-AsZfz3/xrdp-0.9.21.1=. -fdebug-prefix-map=/build/xrdp-AsZfz3/xrdp-0.9.21.1=/usr/src/xrdp-0.9.21.1-1 -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 
      PKG_CONFIG_PATH=/build/xrdp-AsZfz3/xrdp-0.9.21.1/pkgconfig

  Compiled with OpenSSL 3.0.10 1 Aug 2023
~~~

### Operating system & version

Ubuntu 23.10

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp (v0.9.19)

### What desktop environment do you use?

GNOME

### Environment xrdp running on

Bare metal, Intel N100

### What's your client?

mstsc.exe

### Steps to reproduce

1. Open mstsc.exe.
2. Connect to remote host.
3. Login to remote host using Xorg session.

### ✔️ Expected Behavior

I was expecting to be able to login to the remote host and that a GNOME desktop environment would be shown.

### ❌ Actual Behavior

I am unable to login to the desktop environment on the remote host.

### Anything else?

When I initially installed xrdp, I wasn't experiencing any issues. However, at some point, the remote desktop client crashed, and then I was unable to get to the GNOME desktop environment again.

After logging in to the remote host using the default Xorg session, I am shown the following screen in the remote desktop client:

![Screenshot](https://github.com/neutrinolabs/xrdp/assets/6362464/054669cf-037e-4468-b41d-5cd0b34e805a)

I have attempted to reboot and reinstall the xrdp and xorgxrdp packages, but to no avail.

# Log Files

- [xrdp.log](https://github.com/neutrinolabs/xrdp/files/13238913/xrdp.log)
- [xrdp-sesman.log](https://github.com/neutrinolabs/xrdp/files/13238914/xrdp-sesman.log)

**Comment by tobias47n9e** [comment]
After updating from Ubuntu 23.04 to 23.10 I also couldn't log in. I found my error message also in the log above.

> Cannot read private key file /etc/xrdp/key.pem: Permission denied

**Comment by matt335672** [comment]
The "cannot read private key" error is a [long-standing issue with Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860890) that we can't fix here.

Check that  user apsoyka isn't logged in on the machine console first (concurrent logins on the console and xrdp with the same user [dont work](https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-log-the-same-user-on-on-the-graphical-console-and-over-xrdp-at-the-same-time)).

Assuming this isn't the reason, can you post:-
1) `~apsoyka/.xsession-errors`
2) The output of `sudo journalctl -S "2023-11-01 18:44:25" -U "2023-11-01 18:44:33"`

**Comment by AnastasiyaSoyka** [comment]
@matt335672 Could you please clarify what you mean by machine console? I'm not sure how to check that.

I added the `xrdp` user to the `ssl-cert` group, but this did not fix the problem. It does make the permission denied error go away, but I am still unable to login to the remote desktop.

Here are the requested log files:

[journalctl.log](https://github.com/neutrinolabs/xrdp/files/13258027/journalctl.log)
[xsession-errors.log](https://github.com/neutrinolabs/xrdp/files/13258030/xsession-errors.log)

**Comment by AnastasiyaSoyka** [comment]
Alright, I decided to go with the theory that there were extra user sessions that were conflicting with my attempts to login.

After doing a bit of googling, I tried the the command `loginctl show-user apsoyka`, which produced the following output:

```
UID=1000
GID=1000
Name=apsoyka
Timestamp=Sat 2023-11-04 20:32:04 EDT
TimestampMonotonic=4583718886
RuntimePath=/run/user/1000
Service=user@1000.service
Slice=user-1000.slice
Display=9
State=active
Sessions=9
IdleHint=no
IdleSinceHint=1699144371568449
IdleSinceHintMonotonic=4630478932
Linger=no
```

Based on the `Sessions=9` part in that output, I assumed that there were indeed extra conflicting sessions, and I decided to try to get rid of them all with the following command:

```sh
loginctl terminate-user apsoyka
```

I'm happy to report that this successfully resolved my issue, and `xrdp` is now working properly again. I don't understand where those extra sessions were coming from though, and I'm not sure how to prevent this problem from occuring again in the future, but at least I have some idea of what the problem was, and a way to fix it if it happens again.

**Comment by matt335672** [comment]
Glad you got it sorted - using `loginctl` is a good idea.

To respond to your earlier question, by "machine console" I mean the keyboard, mouse and screen normally connected directly to the Linux machine.

If you get an extra session in the future, the `loginctl session-status` command can be used to get more information about the session in question. This may help you to track down where it has come from.
