### ISSUE TITLE
Disconnected client sometimes leaves keyboard in an invalid state

### ISSUE THREAD

**Issue by yurivict** [neutrinolabs/xrdp#2847]
### xrdp version

0.9.23

### Operating system & version

FreeBSD 13.2

### Installation method

Doesn't matter

### Which backend do you use?

x11vnc

### What's your client?

MS MacOS client

### Area(s) with issue?

Keyboard / Mouse

### Steps to reproduce

When the MacOS client disconnects the keyboard is sometimes left in a state with a pressed Shift or Ctrl button.

When the same client re-connects - clicking on the menu items, for example, causes strange effects, because some special button is already pressed.

### ✔️ Expected Behavior

xrdp should restore all keyboard buttons to unpressed condition when the client disconnects.

It is extremely unlikely that another user would be working on the same keyboard and xrdp would mess up the keyboard's state.

### ❌ Actual Behavior

see above

### Anything else?

I have to use the Florence virtual keyboard to un-press buttons, but this isn't easy.

**Comment by matt335672** [comment]
Should be fixed in #3138 (commit 3f568b42fbf36600b179de9012bb9aeeb7bbb621)
