### ISSUE TITLE
RDP windows content does not refresh or redraw when restored from minimized, when upgraded to the newest version.

### ISSUE THREAD

**Issue by xooxl** [neutrinolabs/xrdp#2848]
### xrdp version

0.9.22.20230831

### Detailed xrdp version, build options

~~~
0.9.22.20230831
~~~

### Operating system & version

Ubuntu 22.04 LTS

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp-egfx

### What desktop environment do you use?

GNOME

### Environment xrdp running on

Physical machine which Intel CPU embedded graphic card

### What's your client?

windows 11's mstsc 

### Area(s) with issue?

Graphic glitches

### Steps to reproduce

My ubuntu installed an old version XRDP-egfx, version: 0.9.19. I upgrade xrdp-egfx and xorgxrdp-egfx by the following command.
> sudo apt update
> sudo apt upgrade

I choose replace the configuration file when prompt whether replace the old config file. and then reboot the system.

rdp the ubuntu with window 11 mstsc, everything ok. But the screen freezed when restored after the rdp client minimized. the mouse point can move, the keyboard can key in, but you will see nothing change on the screen, until you minimize the windows and restore all you done will refresh and redrawed. But the screen freezed still.

**Comment by matt335672** [comment]
Hi @xooxl 

xrdp-egfx has not yet been released - see #2383. It's at an early stage where developers can run it and contribute back to the codebase. We are not yet able to take bug reports on it. These will likely be fixed as the work progresses.

I suggest you purge xrdp and xorgxrdp packages, remove the PPA and reinstall the OS version. This will give you the least number of headaches.

**Comment by xooxl** [comment]
I know xrdp-egfx has not yet been released. when i rolled back an old version, everything OK. I need egfx branch, since OS version was too slow for me.

**Comment by matt335672** [comment]
You'll have to wait for it to be released properly I'm afraid. It's not suitable for production use yet.

The best performance you'll be able to get with the OS version is via RemoteFX using one of these methods:-
1) [production] with a Windows 10 client. RFX support was removed for Windows 11. Make sure you're using 32-bit colour and set the connection type to LAN.
2) [testing] with a FreeRDP for Windows nightly. See [this comment](2400#issuecomment-1767794164).

**Comment by xooxl** [comment]
> You'll have to wait for it to be released properly I'm afraid. It's not suitable for production use yet.
> 
> The best performance you'll be able to get with the OS version is via RemoteFX using one of these methods:-
> 
>     1. [production] with a Windows 10 client. RFX support was removed for Windows 11. Make sure you're using 32-bit colour and set the connection type to LAN.
> 
>     2. [testing] with a FreeRDP for Windows nightly. See [this comment](2400#issuecomment-1767794164).

Thanx, I have several PC with different OS, so I will remain with the 0.9.19.20230215-1ubuntu1+0egfx15~jammy version xrdp-egfx until egfx to be release. the egfx branch was the best choice for me, thank you again.
