### ISSUE TITLE
Blank (turquoise) screen after succesfull login (issue started after updating)

### ISSUE THREAD

**Issue by ghost** [neutrinolabs/xrdp#2852]
### xrdp version

XRDP 0.9.23.1 / XORGRDP 0.9.19

### Detailed xrdp version, build options

~~~
xrdp 0.9.23.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:


  Compiled with OpenSSL 3.0.11 19 Sep 2023
~~~

### Operating system & version

Kali 2023.3

### Installation method

git clone & make install

### Which backend do you use?

Xorg

### What desktop environment do you use?

xfce4-session

### Environment xrdp running on

Physical machine

### What's your client?

Microsoft RDP client (mstsc.exe)

### Area(s) with issue?

Session manager (sesman)

### Steps to reproduce

Logging in with correct user & pass, the screen turns blank (turquoise) and after 2..3 minutes  a dialog pops up with the following error

![Remote Desktop Connection](https://github.com/neutrinolabs/xrdp/assets/6375799/b482987e-c4f9-4798-b654-7fe1f921ee94)

### ✔️ Expected Behavior

Successful login with a desktop

### ❌ Actual Behavior

Logging in with correct user & pass, the screen turns blank (turquoise) and after 2..3 minutes  a dialog pops up with the following error

![Remote Desktop Connection](https://github.com/neutrinolabs/xrdp/assets/6375799/b482987e-c4f9-4798-b654-7fe1f921ee94)

Steps taken:

- Googled for a few days, tried several possible solutions, not solved
- Removed and reinstalled xrdp and xorgxrdp, not solved
- Removed xrdp and xorgxrdp
    xorgxrdp:amd64 1:0.9.19-1
    xrdp:amd64 0.9.21.1-1 (latest on Kali)

Downloaded xorgxrdp-0.9.19.tar.gz and  xrdp-0.9.23.1.tar.gz
compiled and installed both
./bootstrap
./configure
make
make install
- Issue still the same.

[journal.txt](https://github.com/neutrinolabs/xrdp/files/13324982/journal.txt)
[sesman.ini.txt](https://github.com/neutrinolabs/xrdp/files/13324983/sesman.ini.txt)
[xrdp.ini.txt](https://github.com/neutrinolabs/xrdp/files/13324984/xrdp.ini.txt)
[xrdp.log](https://github.com/neutrinolabs/xrdp/files/13324987/xrdp.log)
[xrdp-sesman.log](https://github.com/neutrinolabs/xrdp/files/13324988/xrdp-sesman.log)

.xorgxrdp.10.log is not with a timestamp of today
.xsession-errors  is not with a timestamp of today

**Comment by metalefty** [comment]
```
Nov 11 09:15:34 nix xrdp-sesman[49448]: [INFO ] Starting X server on display 10: /usr/bin/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
```

What do you see when you run the following command from CLI, for example via SSH?

```
/usr/bin/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
```

**Comment by ghost** [comment]
as non-root user
/usr/bin/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
/usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server

**Comment by ghost** [comment]
as root:

/usr/bin/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log

X.Org X Server 1.21.1.9
X Protocol Version 11, Revision 0
Current Operating System: Linux nix 6.5.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09) x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.5.0-kali3-amd64 root=UUID=4ec2fe39-e519-4df8-8fee-99f76cde89e9 ro quiet splash
xorg-server 2:21.1.9-1 (https://www.debian.org/support)
Current version of pixman: 0.42.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: ".xorgxrdp.10.log", Time: Sat Nov 11 16:43:52 2023
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xorgxrdpSetup:
xrdpdevSetup:
rdpmousePlug:
rdpkeybPlug:
rdpIdentify:
rdpDriverFunc: op 10
rdpProbe:
rdpPreInit:
rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
rdpScreenInit: pfbMemory bytes 1920000
rdpScreenInit: pfbMemory 0x7f2e23176010
rdpSimdInit: assigning yuv functions
rdpSimdInit: cpuid ax 1 cx 0 return ax 0x000306a9 bx 0x02100800 cx 0x3dbae3bf dx 0xbfebfbff
rdpSimdInit: sse2 amd64 yuv functions assigned
rdpClientConInit: disconnect idle session after [0] sec
rdpClientConInit: kill disconnected [0] timeout [0] sec
rdpClientConInit: do_touchpad_scroll_hack [0]
rdpXvInit: depth 24
rdpScreenInit: out
rdpCreateScreenResources:
rdpmousePreInit: drv 0x5616bba94db0 info 0x5616bbe0a510, flags 0x0
rdpmouseControl: what 0
rdpmouseDeviceInit:
rdpmouseCtrl:
rdpRegisterInputCallback: type 1 proc 0x7f2e245fe360
rdpmouseControl: what 1
rdpmouseDeviceOn:
rdpkeybPreInit: drv 0x5616bba93ce0 info 0x5616bbe0d680, flags 0x0
rdpkeybControl: what 0
rdpkeybDeviceInit:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpRegisterInputCallback: type 0 proc 0x7f2e245f99f0
rdpkeybControl: what 1
rdpkeybDeviceOn:
rdpDeferredRandR:
rdpResizeSession: width 1024 height 768
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
rdpRRGetInfo:
  screen resized to 1024x768
  RRScreenSizeSet ok 1
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
at this point it hangs (not sure if this a normal behavior)

**Comment by metalefty** [comment]
You need to modify the Xorg path to suit your environment.  See sesman.ini.

**Comment by ghost** [comment]
Maybe I dont understand you correctly, but I thought the param below is the right one.

which Xorg
/usr/bin/Xorg

[Xorg]
; Specify the path of non-suid Xorg executable. It might differ depending
; Fedora 26 or later    :  param=/usr/libexec/Xorg
; Debian 9 or later     :  param=/usr/lib/xorg/Xorg
; Ubuntu 16.04 or later :  param=/usr/lib/xorg/Xorg
; Arch Linux            :  param=/usr/lib/Xorg
; CentOS 7              :  param=/usr/bin/Xorg or param=Xorg
; CentOS 8              :  param=/usr/libexec/Xorg
; FreeBSD (from 2022Q4) :  param=/usr/local/libexec/Xorg
####param=/usr/lib/xorg/Xorg  <------ OLD VALUE
**param=/usr/bin/Xorg** <----- NEW VALUE
param=xrdp/xorg.conf
param=.xorgxrdp.%s.log

**Comment by ghost** [comment]
changed it into the line as mentioned in the Debian line.

param=/usr/lib/xorg/Xorg

Doesn't make a difference

**Comment by metalefty** [comment]
Paste the output again.

**Comment by ghost** [comment]
When starting Xorg from the commandline it hangs at **rdpkeybChangeKeyboardControl: autoRepeat off**
I pressed CTRL-C at that point.

[journal.txt](https://github.com/neutrinolabs/xrdp/files/13327367/journal.txt)
[sesman.ini.txt](https://github.com/neutrinolabs/xrdp/files/13327368/sesman.ini.txt)
[xorgxrdp.10.log](https://github.com/neutrinolabs/xrdp/files/13327369/xorgxrdp.10.log)
[xrdp.ini.txt](https://github.com/neutrinolabs/xrdp/files/13327370/xrdp.ini.txt)
[xrdp.log](https://github.com/neutrinolabs/xrdp/files/13327371/xrdp.log)
[xrdp-sesman.log](https://github.com/neutrinolabs/xrdp/files/13327372/xrdp-sesman.log)

**Comment by metalefty** [comment]
> When starting Xorg from the commandline it hangs at rdpkeybChangeKeyboardControl: autoRepeat off
I pressed CTRL-C at that point.

Could you share the exact command line you input?

**Comment by ghost** [comment]
tried both, same result

/usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
/usr/bin/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log

**Comment by matt335672** [comment]
@hvdm - your log files don't appear to be consistent.

In your xrdp.log you have:-

```
[20231112-07:22:50] [INFO ] lib_mod_connect: connecting via UNIX socket
[20231112-07:26:20] [INFO ] connection problem, giving up
```

in your .xorgxrdp.10.log you have:-

```
[229413.989] (++) Log file: "/usr/lib/xorg/Xorg", Time: Sun Nov 12 07:34:57 2023
```

Your path in the ini file should definitely be `/usr/lib/xorg/Xorg`.

Suggest you remove `.xorgxrdp.10.log`, reboot and try again so we can see a consistent set of logs.

**Comment by ghost** [comment]
Kali is a Debian based distro.
; Debian 9 or later     :  param=/usr/lib/xorg/Xorg
param=/usr/lib/xorg/Xorg

@matt335672 
You type: 
in your .xorgxrdp.10.log you have:- [229413.989] (++) Log file: "/usr/lib/xorg/Xorg", Time: Sun Nov 12 07:34:57 2023
Your path in the ini file should definitely be /usr/lib/xorg/Xorg.

This is already the case


BUT..... I removed the .xorgxrdp.10.log, rebooted the machine for the 6th time, reconnected and it's working (at least for now).
I have no clue why it started working now

**Comment by matt335672** [comment]
Thanks for letting us know.

Without a consistent set of logs we can't really say what's happened.

We'll leave this open for a bit. If the problem resurfaces, please report back.

**Comment by ghost** [comment]
Hereby the logs

[sesman.ini.txt](https://github.com/neutrinolabs/xrdp/files/13334468/sesman.ini.txt)
[xorgxrdp.10.log](https://github.com/neutrinolabs/xrdp/files/13334469/xorgxrdp.10.log)
[xrdp.ini.txt](https://github.com/neutrinolabs/xrdp/files/13334470/xrdp.ini.txt)
[xrdp.log](https://github.com/neutrinolabs/xrdp/files/13334471/xrdp.log)
[xrdp-sesman.log](https://github.com/neutrinolabs/xrdp/files/13334472/xrdp-sesman.log)
