### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by csmarosi** [neutrinolabs/xrdp#286]
This is a note rather than an issue:
I found several how-to-build docs, but they are either a wild collection of scripts or just an (old) wiki (e.g. here for Debian 6).
So I created yet another one in Docker: The Dockerfile (a shell script-like creature) is reasonably readable and executable: https://github.com/csmarosi/dockerFiles/blob/master/xrdp_base/Dockerfile
I tested it with Debian wheezy and sid.
An automated build is here: https://hub.docker.com/r/csmarosi/xrdp_base/

Hope this is useful, feel free to steal/adapt it if you like.
Maybe it could be linked to wiki or used for build automation or whatever.
Is there a place to collect things like this?

**Comment by scarygliders** [comment]
Hi there, in case you didn't already know, there's my X11RDP-o-Matic which has existed since 2012 which does all this .. http://scarygliders.net/x11rdp-o-matic-information/

Github repo : https://github.com/scarygliders/X11RDP-o-Matic

Regards

**Comment by metalefty** [comment]
now new build instructions are written in wiki.
