### ISSUE TITLE
xrdp-chansrv using 100% cpu

### ISSUE THREAD

**Issue by dmonizer** [neutrinolabs/xrdp#2861]
### xrdp version

0.9.17

### Detailed xrdp version, build options

~~~
xrdp 0.9.17
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-asBei3/xrdp-0.9.17=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -Wno-error=deprecated-declarations
      PKG_CONFIG_PATH=/build/xrdp-asBei3/xrdp-0.9.17/pkgconfig

  Compiled with OpenSSL 3.0.2 15 Mar 2022
~~~

### Operating system & version

elementary OS 7.1 Horus (Linux 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux)

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp/jammy,now 1:0.2.17-1build1 amd64 [installed,automatic]

### What desktop environment do you use?

XFCE 

### Environment xrdp running on

laptop, Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] (rev 02)

### What's your client?

Microsoft remote desktop from app store (Version 10.9.3 (2158))

### Area(s) with issue?

Performance

### Steps to reproduce

Performance is sluggish for some reason - there's no other load on the machine (which is quite powerful anyway (12 core Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz, 32Gb RAM) 

$ ps ax|grep rdp
   1320 ?        S      0:00 /usr/sbin/xrdp-sesman
   1337 ?        S      0:00 /usr/sbin/xrdp
   2460 ?        S      0:55 /usr/sbin/xrdp
   2463 ?        S      0:00 /usr/sbin/xrdp-sesman
   2466 ?        Sl     0:31 /usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
   2474 ?        Sl    29:13 /usr/sbin/xrdp-chansrv
   
   
![image](https://github.com/neutrinolabs/xrdp/assets/5345503/b0a526cd-f705-4278-ae02-561565f35acb)

Connecting, opening terminal takes at least 10-20 seconds. then at some point it starts moving about decently but noticed almost a complete standstill when started a large (22G) torrent with brave browsers torrent client. 
xrdp-chansrv using 100% cpu.  Switching between windows takes 10-20 seconds.
 
other sessions in the machine (ssh and also locally) are slow too, but not SO slow as in RDP session but noticeably lagging.

### ✔️ Expected Behavior

decent responsiveness :)

### ❌ Actual Behavior

100% CPU usage, sluggishness

**Comment by dmonizer** [comment]
oh, one more thing - just one RDP connection, logged in also on physical machine AND one ssh session.

**Comment by dmonizer** [comment]
when i stop that particular torrent, it becomes responsive again. but cpu usage is still 100%
![image](https://github.com/neutrinolabs/xrdp/assets/5345503/e62a1bca-6cae-447c-92c8-a89484c000bc)

**Comment by dmonizer** [comment]
$ tail -f /var/log/xrdp-sesman.log
[20231120-16:43:13] [ERROR] sesman_data_in: scp_process_msg failed
[20231120-16:43:13] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20231120-16:43:13] [INFO ] Starting X server on display 10: /usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
[20231120-16:43:13] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20231120-16:43:13] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20231120-16:43:13] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20231120-16:43:14] [INFO ] Session started successfully for user erik on display 10
[20231120-16:43:14] [INFO ] Starting the xrdp channel server for display 10
[20231120-16:43:14] [INFO ] Starting the default window manager on display 10: /etc/xrdp/startwm.sh
[20231120-16:43:14] [INFO ] Session in progress on display 10, waiting until the window manager (pid 2465) exits to end the session

$ tail -f /var/log/xrdp.log
[20231120-16:43:13] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20231120-16:43:13] [INFO ] sesman connect ok
[20231120-16:43:13] [INFO ] sending login info to session manager, please wait...
[20231120-16:43:13] [INFO ] xrdp_wm_log_msg: login successful for display 10
[20231120-16:43:13] [INFO ] login successful for display 10
[20231120-16:43:13] [INFO ] loaded module 'libxup.so' ok, interface size 10296, version 4
[20231120-16:43:13] [INFO ] started connecting
[20231120-16:43:13] [INFO ] lib_mod_connect: connecting via UNIX socket
[20231120-16:43:13] [INFO ] lib_mod_log_peer: xrdp_pid=2460 connected to X11rdp_pid=2466 X11rdp_uid=1000 X11rdp_gid=1000 client_ip=::ffff:192.168.1.168 client_port=63610
[20231120-16:43:13] [INFO ] connected ok

**Comment by matt335672** [comment]
It's possible one of the channels handled by chansrv is using all the CPU.

From the client are you able to try with remote drives disabled and the clipboard disabled?

**Comment by dmonizer** [comment]
they are disabled

**Comment by dmonizer** [comment]
![image](https://github.com/neutrinolabs/xrdp/assets/5345503/7af57cb7-2945-401a-a7bf-ac09e03d2cc1)

**Comment by dmonizer** [comment]
aaah, sry, clipboard - will try

**Comment by dmonizer** [comment]
strange.  had to restart the machine as the Xrdp hung and refused to be killed. 
trying now with or without clipboard (and sound) there's no more xrdp-sesman using 100% cpu.

BUT - fact is that when i run aforementioned torrent over rdp, whole machine grinds to a 386 basically. But when i run it in local session, while the load is still obnoxiously high, machine remains usable, maybe a tad of a lag only ..

**Comment by matt335672** [comment]
@dmonizer - is your torrent running over the same network link as your RDP session?

If so, you may be simply starving the RDP session of an adequate latency for its return packets.

**Comment by dmonizer** [comment]
aah, Matt, you might have a point there. it was indeed over the same connection. most probably thats the issue. closing it at the moment.
