### ISSUE TITLE
Couldn't connect from Fedora 38 to Fedora 39

### ISSUE THREAD

**Issue by elhananjair** [neutrinolabs/xrdp#2862]
### xrdp version

0.9.23.1

### Detailed xrdp version, build options

~~~
xrdp 0.9.23.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-redhat-linux-gnu
      --host=x86_64-redhat-linux-gnu
      --program-prefix=
      --disable-dependency-tracking
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/sbin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --runstatedir=/run
      --sharedstatedir=/var/lib
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-fuse
      --enable-pixman
      --enable-painter
      --enable-vsock
      --enable-ipv6
      --with-socketdir=/run/xrdp
      --with-imlib2
      build_alias=x86_64-redhat-linux-gnu
      host_alias=x86_64-redhat-linux-gnu
      CC=gcc
      CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer 
      LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes 
      LT_SYS_LIBRARY_PATH=/usr/lib64:
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 3.0.9 30 May 2023
~~~

### Operating system & version

Fedora 38

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

I do have both installed don't know which one is being used (tigervnc and xorgxrdp)

### What desktop environment do you use?

KDE

### Environment xrdp running on

on Physical Desktop Computer

### What's your client?

It is not working with many RDP clients, I tried with Remmina and KRDC

### Area(s) with issue?

Other

### Steps to reproduce

I just installed xrdp and tigervnc-server on a remote computer. After installation, I added port 3389 to the firewall settings.  I tried to connect to the PC using Remmina and it showed a login screen but after that, just a black screen with some crossed cursor showed up.,

### ✔️ Expected Behavior

Should have connected successfully.

### ❌ Actual Behavior

Black screen with X sign.

![image](https://github.com/neutrinolabs/xrdp/assets/69236638/7570cf2b-9802-4ec3-b7ac-8c822fd9cfa0)

### Anything else?

**xorg.ini**
https://paste.centos.org/view/deb312aa

**sesman.ini**
https://paste.centos.org/view/81a666a5

**xrdp.log**
https://paste.centos.org/view/e45caecb

**xrdp-sesman.log**
https://paste.centos.org/view/d8ccfb6d

**Comment by elhananjair** [comment]
I created a new user on remote it works fine with that user, but I am not getting it. I have already tried with other users but was not working.

**Comment by matt335672** [comment]
I can't see any problems in your log other than the one you've highlighted.

A couple of possibilities:-
1) You might be trying to use the same user on an RDP session and the console at the same time. This isn't supported on systemd-based systems. See the [FAQ](https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-log-the-same-user-on-on-the-graphical-console-and-over-xrdp-at-the-same-time)
2) If you restart the xrdp service, any session already active will remain working but you will no longer be able to reconnect to it. Symptoms are the same as 1)

Restart the system, check no-one is logged on to the console and try again.

**Comment by elhananjair** [comment]
Yeah you’re right, I was trying with the same user I was login with ssh. 
thanks
