### ISSUE TITLE
[ERROR] SSL_accept: I/O error and subsequent erroors

### ISSUE THREAD

**Issue by botox-100** [neutrinolabs/xrdp#2866]
### xrdp version

xrdp 0.9.21.1

### Detailed xrdp version, build options

I am getting this series of errors in the xrdp.log several times a second. However the connection from client to server is working. I am running on Debian 12 (bookworm).

Is there any way to get rid of these? Is the session really SSL encrypted if I see this errors or does it fall back to the (unsecure) RDP protocol? Is there a possibilty to check this?

Thanks for your help!

<img width="895" alt="Bildschirmfoto 2023-11-29 um 21 07 47" src="https://github.com/neutrinolabs/xrdp/assets/94542612/3b2e1dbc-5838-4ce5-aea6-d6319c94a72f">

### Operating system & version

Debian 12

### Installation method

dnf / apt / zypper / pkg / etc

### What desktop environment do you use?

LXDE

### Steps to reproduce

Just start XRDP

### ✔️ Expected Behavior

No Errors in the log. SSL working

### ❌ Actual Behavior

Logs errors several times a second (see above)

**Comment by matt335672** [comment]
@botox-100 - these are simply connection attempts which are getting closed by the client. The error reporting isn't great in this area. See #2040.

Are you expecting connections from the IP addresses? 45.88.97.20 is hosted by a Turkish ISP and 193.111.248.57 by a German one.

**Comment by botox-100** [comment]
> @botox-100 - these are simply connection attempts which are getting closed by the client. The error reporting isn't great in this area. See #2040.
> 
> Are you expecting connections from the IP addresses? 45.88.97.20 is hosted by a Turkish ISP and 193.111.248.57 by a German one.

Hi, thanks for the explanation!
Since this morning i am now using ssh to tunnel the RDP connection. I do  not get any errors any more in the log, which  perfectly fits to your explanation! I was not aware that attacks come up so fast and frequent, therefore I was suspecting an issue.
Thanks for all your work on this, Thomas
