### ISSUE TITLE
GFX mainline merge master issue

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#2867]
https://github.com/orgs/neutrinolabs/projects/1

**Comment by metalefty** [comment]
@jsorg71 @matt335672 @Nexarian 

I have tested the following tuple of commits and I think they are now stable enough. Thank you very much!

* https://github.com/neutrinolabs/xorgxrdp/commit/e17da50407c855bea2bad7ac2551f2cd55207722
* https://github.com/neutrinolabs/xrdp/commit/8027a424979fbd1b9f6026d1fbb4bc0c76b7fb68

Let's merge them in a few days.  I'm planning to create a new stable branch with GFX `v0.10` from `devel` branch immediately after the merge. If further GFX-related bug fixes are required, let's fix it in `devel` and backport to `v0.10` as we do on `v0.9`.  Then, active developments on `devel` branch can be resumed.

**Comment by matt335672** [comment]
That sounds good - thanks @metalefty
