### ISSUE TITLE
Session freezes after few minutes of innactivity

### ISSUE THREAD

**Issue by HottuDoku** [neutrinolabs/xrdp#2868]
### xrdp version

0.9.19

### Detailed xrdp version, build options

~~~
xrdp 0.9.80
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      

  Compiled with OpenSSL 3.0.2 15 Mar 2022

~~~

### Operating system & version

Ubuntu 22.04

### Installation method

git clone && make install

### Which backend do you use?

xorgxrdp

### What desktop environment do you use?

Mate

### Environment xrdp running on

VMware vSphere

### What's your client?

Microsoft RDP client, Remmina

### Steps to reproduce

1) User logs into the session and performs tasks.
2) After a while, the user takes a short break (e.g., for a glass of water).
3) Upon returning after 3-5 minutes, the session is frozen or displays a black screen.
3.a) If the user is fortunate, they can close the session and log back in. 
3.b) However, if unlucky, administrators with access to the RDP server must terminate all of the user's processes to allow them to log back in.

### ✔️ Expected Behavior

Session picks up right back or doesn't go into idle at all.

### ❌ Actual Behavior

The user is unable to resume work since the session is frozen or crashed, yet the session on server side appears to still be active.

### Anything else?

Greetings,

The observed behavior appears to be inconsistent and not easily reproducible. We have ruled out the client system as the cause, as the issue occurs on both Windows and Ubuntu clients connecting to the XRDP server. The problem is frequent for users within the local network and external users, and we do not employ any proxy for server connections apart from port forwarding outside the local network. Additinaly we use fail2ban to ban any user outside of local network that fails to authenticate X failed attempts.

Below are the logs for today. Upon initial inspection, I have not identified any entries that suggest the described issue. I also investigated the logs immediately after a user reported the problem, but they appeared to be identical to standard behavior. If anything, it seemed as though the session didn't close, persisting without the ability for any of us to connect to the mentioned user session until we terminated all processes associated with the user, effectively ending the session.

Feel free to ask for any additional info if needed.

[xrdp-sesman.log](https://github.com/neutrinolabs/xrdp/files/13543481/xrdp-sesman.log)
[xrdp.log](https://github.com/neutrinolabs/xrdp/files/13543482/xrdp.log)
[xorg.conf](https://github.com/neutrinolabs/xrdp/files/13543496/xorg.conf.txt)

**Comment by matt335672** [comment]
A couple of possibilities for you:-
1) Could be a lock screen issue. Disable screen locking to see if the problem goes away. If this is it we can drill down further.
2) We've seen problems where a client has grabbed the mouse or keyboard, which makes it difficult to diagnose. When the problem re-occurs, try killing user processes one at a time until the problem goes away.
3) You appear to be running a development build - that's what `xrdp 0.9.80` means. There could be almost anything going on there. Try running with the OS supplied packages.

**Comment by matt335672** [comment]
No more input from OP - closing
