### ISSUE TITLE
GFX multimon support

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#2871]

**Comment by metalefty** [comment]
@jsorg71 Jay, how is the progress of GFX multimon?

**Comment by metalefty** [comment]
>  I could see three monitors showing the same output for now. Each output was a scaled down version of the three monitors organized in the correct layout.

![image](https://github.com/neutrinolabs/xrdp/assets/941609/87ffe773-79a1-4655-9622-32e7e115486d)

**Comment by metalefty** [comment]
https://github.com/neutrinolabs/xrdp/pull/2891#issuecomment-1886247185

Jay's multimon work mentioned above is still not working. I got the screen like above.

**Comment by jsorg71** [comment]
The multimon work I did was to create and map a new surface for each monitor.  I was planning to save that for the next 
release as it is only required for H264 sessions(I thought).
It looks like it mapping the surface to monitor 1.  Oh this might be because the newer GFX versions can do scaling.  I'll test it too but can you force and older version in advertise?

**Comment by jsorg71** [comment]
I see the issue now.  Mac client does multimon different than mstsc.  I think we'll need the multi surface bits from workspot_multimon.  I'll start bringing this over.

**Comment by metalefty** [comment]
Thanks for the info. I will double-check with Mac.

**Comment by Nexarian** [comment]
> I'll start bringing this over.
Let me know if there's anything I can do to help. At this point I'd largely be doing what I've done in the past: Read what you wrote carefully, copy-paste, test against the branch, adapt, repeat.

**Comment by jsorg71** [comment]
I'm working on the login screen multimon issue.  I'm working in gfx_mainline_merge_multimon branch.  I'll have login screen working today.

**Comment by jsorg71** [comment]
ok login screen should be drawing ok now.

**Comment by Nexarian** [comment]
Looking at this it looks like the surfaces are created, but:
- Not updated dynamically
- Maybe not drawn correctly once the app loads?

So we have to lift-and-shift more of the workspot code, correct?

**Comment by jsorg71** [comment]
Right, it's only the login screen now.  I didn't work on the login screen in the workspot_multimon branch.  I'll bring over what's needed from workspot_multimon next.

**Comment by Nexarian** [comment]
Carry on! *salute*

**Comment by metalefty** [comment]
Thanks! I also confirmed the multimon login screen looks fine.
