### ISSUE TITLE
GFX screen glitches

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#2875]
There are some green screen glitches in GFX mode.

![Image](https://github.com/neutrinolabs/xrdp/assets/941609/f056542d-c762-47e2-8ef8-981ca8f48553)

![Image](https://github.com/neutrinolabs/xrdp/assets/941609/9ae528dc-2734-4af7-87fa-cbcf2ab31700)

**Comment by Nexarian** [comment]
What branch are you using?

**Comment by metalefty** [comment]
I'm using mainline_merge both for xrdp and xorgxrdp.

**Comment by Nexarian** [comment]
Is this with Progressive RFX? H264? Hardware encoded or software encoded?

**Comment by metalefty** [comment]
I think it is software-encoded progressive RFX.

Compiled with following two flags:

```
--enable-imlib2 --enable-ipv6
```

**Comment by jsorg71** [comment]
I have a patch for this, let me find it.

**Comment by jsorg71** [comment]
Try this one.
```
diff --git a/module/rdpCapture.c b/module/rdpCapture.c
index 94f16aa..8ebfa66 100644
--- a/module/rdpCapture.c
+++ b/module/rdpCapture.c
@@ -1170,7 +1170,14 @@ rdpCapture2(rdpClientCon *clientCon, RegionPtr in_reg, BoxPtr *out_rects,
             rcode = rdpRegionContainsRect(in_reg, &rect);
             LLOGLN(10, ("rdpCapture2: rcode %d", rcode));

-            if (rcode != rgnOUT)
+            if (rcode == rgnOUT)
+            {
+                LLOGLN(0, ("rdpCapture2: rgnOUT"));
+                rdpRegionInit(&tile_reg, &rect, 0);
+                rdpRegionSubtract(in_reg, in_reg, &tile_reg);
+                rdpRegionUninit(&tile_reg);
+            }
+            else
             {
                 crc = crc_start();
                 if (rcode == rgnPART)
```

**Comment by metalefty** [comment]
Thanks, I'll try tonight.

**Comment by metalefty** [comment]
@jsorg71 Which branch did you apply your fix?

**Comment by metalefty** [comment]
I could hand-apply patch, testing...

**Comment by metalefty** [comment]
Looks better but I still see fewer glitches when there are large continuous screen updates. I'm looking into some similar edge cases. For example browsing nyancat collection: https://nyancatcollection.com/

I applied the patch Jay showed on [3d30c7a](https://github.com/Nexarian/xorgxrdp/commit/3d30c7a6ad4f4a582efcb919966d8f1508aa2d31) in Nexarian/xorgxrdp mainline_merge branch.


![image](https://github.com/neutrinolabs/xrdp/assets/941609/2c4caaad-79f1-4a4e-baa6-0fefd6b207d8)

**Comment by Nexarian** [comment]
Yeah I tried this as well and it's not completely fixed :/

**Comment by metalefty** [comment]
It turned out that it doesn't occur with FreeRDP in the Zoom meeting with Jay and Nex.

**Comment by Nexarian** [comment]
It does however occur on the Mac OS client and it makes no difference whether you use Gnome or Mate. However, it goes away with certain compositors with Mate, though that might be because Mate is refreshing the entire screen continually with certain compositors, losing the advantage of damage rect detection with more efficient rendering models.

**Comment by jsorg71** [comment]
here is a patch that seems to fix it for me on mac ms client.  Can you guys check too.  It disables crc checks so it's not a final fix but points in the right direction.
```
diff --git a/module/rdpCapture.c b/module/rdpCapture.c
index 4d28a02..eb24d84 100644
--- a/module/rdpCapture.c
+++ b/module/rdpCapture.c
@@ -930,7 +930,7 @@ rdpCapture2(rdpClientCon *clientCon, RegionPtr in_reg, BoxPtr *out_rects,
                              + (x / XRDP_RFX_ALIGN);
                 LLOGLN(10, ("rdpCapture2: crc 0x%8.8x 0x%8.8x",
                        crc, clientCon->rfx_crcs[crc_offset]));
-                if (crc == clientCon->rfx_crcs[crc_offset])
+                if (crc == clientCon->rfx_crcs[crc_offset] && 0)
                 {
                     LLOGLN(10, ("rdpCapture2: crc skip at x %d y %d", x, y));
                 }
```

**Comment by jsorg71** [comment]
oh also, the -lrt is needed for shm_open.  I don't know if that is the right lib but it fixes the linker error on my Debian 11 system.

**Comment by jsorg71** [comment]
This one seems to fix it with crc enabled
```
diff --git a/module/rdpCapture.c b/module/rdpCapture.c
index 4d28a02..ef7a4ab 100644
--- a/module/rdpCapture.c
+++ b/module/rdpCapture.c
@@ -896,7 +896,14 @@ rdpCapture2(rdpClientCon *clientCon, RegionPtr in_reg, BoxPtr *out_rects,
             rcode = rdpRegionContainsRect(in_reg, &rect);
             LLOGLN(10, ("rdpCapture2: rcode %d", rcode));

-            if (rcode != rgnOUT)
+            if (rcode == rgnOUT)
+            {
+                LLOGLN(10, ("rdpCapture2: rgnOUT"));
+                rdpRegionInit(&tile_reg, &rect, 0);
+                rdpRegionSubtract(in_reg, in_reg, &tile_reg);
+                rdpRegionUninit(&tile_reg);
+            }
+            else
             {
                 crc = crc_start();
                 if (rcode == rgnPART)
@@ -933,6 +940,9 @@ rdpCapture2(rdpClientCon *clientCon, RegionPtr in_reg, BoxPtr *out_rects,
                 if (crc == clientCon->rfx_crcs[crc_offset])
                 {
                     LLOGLN(10, ("rdpCapture2: crc skip at x %d y %d", x, y));
+                    rdpRegionInit(&tile_reg, &rect, 0);
+                    rdpRegionSubtract(in_reg, in_reg, &tile_reg);
+                    rdpRegionUninit(&tile_reg);
                 }
                 else
                 {
```

**Comment by Nexarian** [comment]
Seems to have fixed it for me! I added it to [XORGXRDP's gfx_mainline_merge_work branch](https://github.com/neutrinolabs/xorgxrdp/commit/8519407d7fbcb71fd046ce42e5674c308e9ea52b)

**Comment by metalefty** [comment]
Also Fixed to me at [8519407](https://github.com/neutrinolabs/xorgxrdp/commit/8519407d7fbcb71fd046ce42e5674c308e9ea52b) !

**Comment by matt335672** [comment]
I can't reproduce the `-lrt` linker error on a Debian 11 system here. The `shm_open` symbol is definitely in librt.so, but I'm not getting a link error.

Also, on Ubuntu 22.04, this symbol is now in `libc` so nothing special is required.

@jsorg71 - does this xorgxrdp patch sort out your linker problem on Debian 11? On Ubuntu 22.04 and FreeBSD it's a no-op:-

```patch
index 4dcd904f..7ec67a39 100644
--- a/configure.ac
+++ b/configure.ac
@@ -111,6 +111,9 @@ if test "x${with_simd}" != "xno"; then
   fi
 fi
 
+# shm_open may not be in the C library
+AC_SEARCH_LIBS([shm_open], [rt])
+
 AC_ARG_ENABLE(glamor, AS_HELP_STRING([--enable-glamor],
               [Use glamor(requires xorg server 1.19+) (default: no)]),
               [], [enable_glamor=no])
```

**Comment by matt335672** [comment]
I don't have access to a Mac, so I can't test on that. I'll carry checking out the freerdp and Windows clients.

**Comment by jsorg71** [comment]
@matt335672 That patch fixes the shm_open -lrt issue.  Nice job.

This machine is actually Devuan 4 which is Debian 11 like.
jay@devuan4:~$ cat /etc/*release
PRETTY_NAME="Devuan GNU/Linux 4 (chimaera)"
NAME="Devuan GNU/Linux"
VERSION_ID="4"
VERSION="4 (chimaera)"
VERSION_CODENAME="chimaera"
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"

**Comment by matt335672** [comment]
I'll get Devuan down for testing.

@Nexarian - can you add the above patch to `gfx_mainline_merge_work` in `xorgxrdp` ?
