### ISSUE TITLE
GFX faint banding

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#2881]
I'm testing:
- https://github.com/neutrinolabs/xrdp/tree/gfx_mainline_merge
- https://github.com/neutrinolabs/xorgxrdp/tree/gfx_mainline_merge

I see a visible difference between classic RemoteFX and GFX. See the screenshot, you probably need to click and zoom in:

![image](https://github.com/neutrinolabs/xrdp/assets/941609/9a84b338-326c-4413-b88a-7bf2b5df400d)

I think this is caused by some difference in RFX compression parameters. Any ideas?

**Comment by jsorg71** [comment]
I wonder if this is related to the quantize settings

**Comment by jsorg71** [comment]
Do you remember this issue.  https://github.com/neutrinolabs/librfxcodec/issues/54

**Comment by metalefty** [comment]
Ah,  I had quite forgotten it. I will test and figure out best quantize settings.

**Comment by metalefty** [comment]
This looks fine. 

```C
static const unsigned char g_rfx_quantization_values[] =
{
    0x66, 0x66, 0x77, 0x87, 0x98,
    0x76, 0x77, 0x88, 0x98, 0x99
};
```

**Comment by metalefty** [comment]
I think this is now fixed.
