### ISSUE TITLE
drive redirection MountName error

### ISSUE THREAD

**Issue by tsz8899** [neutrinolabs/xrdp#2885]
### xrdp version

devel

### Detailed xrdp version, build options

~~~
xrdp will be compiled with:

  mp3lame                 no
  opus                    no
  fdkaac                  no
  jpeg                    no
  turbo jpeg              no
  rfxcodec                yes
  painter                 yes
  pixman                  no
  fuse                    no
  ipv6                    no
  ipv6only                no
  vsock                   no
  auth mechanism          PAM
  rdpsndaudin             no

  with imlib2             no
  with freetype2          no

  development logging     no
  development streamcheck no

  strict_locations        no
  prefix                  /usr/local
  exec_prefix             ${prefix}
  libdir                  ${exec_prefix}/lib
  bindir                  ${exec_prefix}/bin
  sysconfdir              /etc
  pamconfdir              /etc/pam.d
  localstatedir           /var
  runstatedir             ${localstatedir}/run
  socketdir               ${localstatedir}/run/xrdp

  unit tests performable  no

  CFLAGS = -g -O2 -Wall -Wwrite-strings -Werror
  LDFLAGS =
~~~

### Operating system & version

debian 11    ubuntu 22.04

### Installation method

git clone & make install

### Which backend do you use?

xorgxrdp

### What desktop environment do you use?

any

### Environment xrdp running on

vm

### What's your client?

mstsc freerdp

### Area(s) with issue?

File transfer / drive redirection

### Steps to reproduce

good --76d12c50a8a38b848a45969fc9808a1e5a834e23
the version of sesman/chansrv/devredir.c worked fine:
Non-English names drive redirection may be used
~~~
sesman.ini--
[Chansrv]
FuseMountName=幸福安康
~~~
is ok

but later versions non-english directory disappears. drive redirection MountName can only be used English..

### ✔️ Expected Behavior

drive redirection MountName Multi-language support

**Comment by matt335672** [comment]
Thanks @tsz8899 - that's very useful indeed. I've linked a PR to fix this.

I've added your string 幸福安康 as a test-case for the failing routine so this shouldn't happen again.

At some point I'll merge the PR but given it's the holiday season here that may take a few days.
