### ISSUE TITLE
Not able to connect to xrdp server

### ISSUE THREAD

**Issue by bengabp** [neutrinolabs/xrdp#2900]
### xrdp version

0.9.21.1

### Detailed xrdp version, build options

~~~
xrdp 0.9.21.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-AsZfz3/xrdp-0.9.21.1=. -fdebug-prefix-map=/build/xrdp-AsZfz3/xrdp-0.9.21.1=/usr/src/xrdp-0.9.21.1-1 -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 
      PKG_CONFIG_PATH=/build/xrdp-AsZfz3/xrdp-0.9.21.1/pkgconfig

  Compiled with OpenSSL 3.0.10 1 Aug 2023
~~~

### Operating system & version

Ubuntu 23.10

### Installation method

other

### What desktop environment do you use?

GNOME

### Environment xrdp running on

2012 intel mac mini running ubuntu 23.10

### Steps to reproduce

There is no specific step, i just installed xrdp, start the service then i try connecting using reminna on another linux pc, the connection was successful, but the reminna window closed after that. also thesame case when i used windows 11 built in remote desktop client

### Anything else?

Closes as soon as its connected.

**Comment by matt335672** [comment]
@bengabp:-

1) what do you mean by "the connection was successful"?
2) Are you logged locally to the Max Mini while you are trying to use xrdp (see [here](https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-log-the-same-user-on-on-the-graphical-console-and-over-xrdp-at-the-same-time))?

**Comment by bengabp** [comment]
> @bengabp:-
> 
> 1) what do you mean by "the connection was successful"?
> 2) Are you logged locally to the Max Mini while you are trying to use xrdp (see [here](https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-log-the-same-user-on-on-the-graphical-console-and-over-xrdp-at-the-same-time))?

The connection was successful because it didn't say anything like incorrect username of password, but the window just closes. Also I also used 2 computers to try to access the xrdp server, but they both after connecting, closed the window, I've also setup guacamole now, and it's thesame thing

**Comment by matt335672** [comment]
I still don't understand. What window? Are you getting a log on screen? Can you be more descriptive please? Also, see question 2 above.

**Comment by bengabp** [comment]
> I still don't understand. What window? Are you getting a log on screen? Can you be more descriptive please? Also, see question 2 above.

sorry for the confusion, ive resolved the issue, aparently it will close anyother connection when a display is connected to the host machine
