### ISSUE TITLE
Reconnect policy does not work

### ISSUE THREAD

**Issue by janLo** [neutrinolabs/xrdp#291]
The current config have a "Policy" option that allows to specify what should checked to decide if a new session should spawned or an old should reused:
```
## Policy - session allocation policy                                               
# Type: enum [ "Default" | "UBD" | "UBI" | "UBC" | "UBDI" | "UBDC" ]                
# Default: Xrdp:<User,BitPerPixel> and Xvnc:<User,BitPerPixel,DisplaySize>          
# "UBD" session per <User,BitPerPixel,DisplaySize>                                  
# "UBI" session per <User,BitPerPixel,IPAddr>                                       
# "UBC" session per <User,BitPerPixel,Connection>                                   
# "UBDI" session per <User,BitPerPixel,DisplaySize,IPAddr>                          
# "UBDC" session per <User,BitPerPixel,DisplaySize,Connection>                      
```
But the code at https://github.com/neutrinolabs/xrdp/blob/devel/sesman/session.c#L167 forgot to check if the SESMAN_CFG_SESS_POLICY_D flag is set or not. So it was not possible to select a policy that does _not_ account the display size. This is a problem because most rdp clients can only resize through a reconnect.

**Comment by moobyfr** [comment]
What is your backend ? Xorg X11rdp or Xvnc ?
I've made some tests and the policy is correct when using Xorg backend  (tried to reconnect with different size, policy tested Default, UBD, UBDI) : when using a different size I reconnect to the same session

**Comment by janLo** [comment]
My backend is xorg.

I looked into it again and it seems that my testing setup was missing https://github.com/janLo/xrdp/commit/12092e809840f1d0ad106f7171b197248ef4c351. So the PR above seems to be void at this commit also fixes the bug.

On the other hand: why do you branch for the backend within the loop? You set the SESMAN_CFG_SESS_POLICY_D flag on all xvnc connections in https://github.com/janLo/xrdp/blob/12092e809840f1d0ad106f7171b197248ef4c351/sesman/session.c#L113 so it can be reduced to one if statement.

**Comment by janLo** [comment]
FYI, the problem was that my testing environment was originally on v0.8 and then switched to "master" instead of "devel" - where the commit 12092e809840f1d0ad106f7171b197248ef4c351 is not present.
