### ISSUE TITLE
Restarting xrdp does not handle running sessions properly

### ISSUE THREAD

**Issue by azzid** [neutrinolabs/xrdp#2915]
### xrdp version

0.9.24

### Detailed xrdp version, build options

~~~
$ xrdp --version
xrdp 0.9.24
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-redhat-linux-gnu
      --host=x86_64-redhat-linux-gnu
      --program-prefix=
      --disable-dependency-tracking
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/sbin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --sharedstatedir=/var/lib
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-fuse
      --enable-pixman
      --enable-painter
      --enable-vsock
      --enable-ipv6
      --with-socketdir=/run/xrdp
      --with-imlib2
      build_alias=x86_64-redhat-linux-gnu
      host_alias=x86_64-redhat-linux-gnu
      CC=gcc
      CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection 
      LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 
      LT_SYS_LIBRARY_PATH=/usr/lib64:
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 3.0.7 1 Nov 2022
~~~

### Operating system & version

CentOS Stream 9

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

tigervnc-1.13.1-1-4.el9

### What desktop environment do you use?

Gnome

### Environment xrdp running on

vmware vm

### What's your client?

microsoft Remote Desktop client for macOS

### Area(s) with issue?

Other

### Steps to reproduce

After changing some configuration setting in `/etc/xrdp/` I do `systemctl restart xrdp` to enable the new setting.
I get my rdp-connection terminated by the restart and when I try to login again all I get is a black screen.

If I ssh into the machine and do `systemctl status session-*` I can see that I have old sessions with vnc still running.

If I terminate them (`systemctl stop session-X`) I can log in normally. Reboot works as well.

### ✔️ Expected Behavior

I see the expected behaviour as one of the following two:

1. I should get back into the session I was disconnected from
2. The earlier connection should be terminated automatically so that I can get a new one

### ❌ Actual Behavior

black screen

possibly related errors:

```
Jan 18 09:41:03 host.domain.local gnome-session[19769]: MESA: error: ZINK: failed to choose pdev
Jan 18 09:41:03 host.domain.local gnome-session[19769]: glx: failed to create drisw screen
Jan 18 09:41:03 host.domain.local gnome-session[19769]: failed to load driver: zink
Jan 18 09:41:04 host.domain.local gnome-session[19771]: MESA: error: ZINK: failed to choose pdev
Jan 18 09:41:04 host.domain.local gnome-session[19771]: glx: failed to create drisw screen
Jan 18 09:41:04 host.domain.local gnome-session[19771]: failed to load driver: zink
Jan 18 09:41:04 host.domain.local gnome-session[19769]: gnome-session-check-accelerated: GL Helper exited with code 512
Jan 18 09:41:04 host.domain.local gnome-session[19781]: MESA: error: ZINK: failed to choose pdev
Jan 18 09:41:04 host.domain.local gnome-session[19781]: libEGL warning: egl: failed to create dri2 screen
Jan 18 09:41:04 host.domain.local gnome-session[19769]: gnome-session-check-accelerated: GLES Helper exited with code 512
```

### Anything else?

Is `systemctl restart xrdp` the "proper" way to activate new settings?

**Comment by matt335672** [comment]
Duplicate of #800 - at least the restart bit.

We're working on fixing this in the development version. A lot of the groundwork has been laid down, but we still need to get the new `sesexec` processes to re-register with sesman when it restarts. This is not an insignificant bit of work and we've got a few more important things queued up in front of it at the moment.

As far as reloading the configuration goes, this should be largely do-able.

- Edits to `/etc/xrdp/xrdp.ini` should be picked up automatically by new sessions.
- Edits to `/etc/xrdp/sesman.ini` are picked up when sesman re-reads the file. You can send sesman a `SIGHUP` to do this - this should be in the manpage.  Also, `systemctl reload xrdp-sesman` should achieve the same thing.

Does that answer your question?

**Comment by azzid** [comment]
My manual termination of the old session also leaves mounts hanging:

```
[user@host ~]$ ls
ls: cannot access 'thinclient_drives': Transport endpoint is not connected
```

**Comment by azzid** [comment]
> Does that answer your question?

Ah, thanks for the great reply! Sorry about the duplicate.

My takeaway: no need to restart `xrdp`

Good enough for me!
