### ISSUE TITLE
GFX: Segfault due to systemd system call filter

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#2916]
I'll report the detail later.

**Comment by Nexarian** [comment]
This fixes it: https://github.com/Nexarian/xrdp/pull/9/files#diff-7c6de7dbf8f33c67f0829693b3172563857ed0890f47784e4387c87ee2cc2fd1

I'm not sure what is relevant in those changes and what isn't. I'm also not sure under what circumstances this is triggered.

**Comment by matt335672** [comment]
There's more info in finding out what is triggering SIGSYS in #2697

**Comment by metalefty** [comment]
Resolved in current devel.
