### ISSUE TITLE
Xrdp crashes when connecting

### ISSUE THREAD

**Issue by ghost** [neutrinolabs/xrdp#2919]
### xrdp version

0.9.23.1

### Detailed xrdp version, build options

~~~
PASTE HERE
~~~

### Operating system & version

ALT Server 10.2

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

Xotg

### What desktop environment do you use?

Mate

### Environment xrdp running on

Ge force 210

### What's your client?

-

### Area(s) with issue?

Authentication, Graphic glitches

### Steps to reproduce

I installed xrdp, then installed mate-session, connected the thin client to the server, entered the username and password, connected, a picture appeared and the system crashed

### ✔️ Expected Behavior

I expected to see the system working

### ❌ Actual Behavior

The connection was lost and the error trans_write_copy_s failed was received, and the error Sending [ITU T.125] DisconnectedProviderUltimatum fail was received

**Comment by matt335672** [comment]
@POdUShkA1812 - can you provide the xrdp.log and xrdp-sesman.log files from your connection attempt please?

**Comment by ghost** [comment]
[xrdp.log](https://github.com/neutrinolabs/xrdp/files/14033578/xrdp.log)
[xrdp-sesman.log](https://github.com/neutrinolabs/xrdp/files/14033579/xrdp-sesman.log)

**Comment by matt335672** [comment]
I can't see any problems at all in there.

1) Is the xrdp-sesman.log complete?
2) What does "the system crashed" mean?
3) Can you reconnect? What happens when you try?

**Comment by ghost** [comment]
1. I didn’t really understand the question about how to open the xrdp-sesman file. 
2. I'm trying to connect to the server, the connection occurs and after 10 seconds it breaks.
3. When I try to connect again, I get the same error, and sometimes the message appears: can not connect on session bus

**Comment by matt335672** [comment]
The file is in `/var/log/xrdp-sesman.log`

Can you log in on the server console normally?

**Comment by matt335672** [comment]
No further input - closing.
