### ISSUE TITLE
Warning reported by Infer

### ISSUE THREAD

**Issue by ZhipengXue97** [neutrinolabs/xrdp#2923]
### xrdp version

devel

### Detailed xrdp version, build options

~~~
PASTE HERE
~~~

### Operating system & version

Ubuntu 18.04

### Installation method

dnf / apt / zypper / pkg / etc

### Steps to reproduce

1. bug_type: NULL_DEREFERENCE, qualifier: pointer `ls->data` last assigned on line 1757 could be null and is dereferenced by call to `g_memcpy()` at line 1758, column 5. procedure: sound_process_input_data, procedure_start_line: 1743, file: xrdp/sesman/chansrv/sound.c
2. bug_type: UNINITIALIZED_VALUE, qualifier: The value read from ver was never initialized. line: 1482, column: 6, procedure: xrdp_sec_recv_fastpath, procedure_start_line: 1453, file: xrdp/libxrdp/xrdp_sec.c
3. bug_type: NULL_DEREFERENCE, qualifier: pointer `ls->data` last assigned on line 345 could be null and is dereferenced by call to `g_memcpy()` at line 346, column 5. procedure: audin_process_data, procedure_start_line: 336, file: xrdp/sesman/chansrv/sound.c
4. bug_type: NULL_DEREFERENCE, qualifier: pointer `buf` last assigned on line 305 could be null and is dereferenced at line 307, column 5. procedure: write_out_line, procedure_start_line: 289, file: xrdp/keygen/keygen.c
5. bug_type: UNINITIALIZED_VALUE, qualifier: The value read from buf[_] was never initialized. line: 1346, column: 6. procedure: fips_expand_key_bits, procedure_start_line: 1323, file: xrdp/libxrdp/xrdp_sec.c

### Anything else?

The NULL_DEREFERENCE bugs related to g_malloc.
I'm not sure whether #2 is a real bug, and #5 seems a false positive.

**Comment by matt335672** [comment]
Thanks @ZhipengXue97 

These have been raised before in a private forum. We didn't find anything significant there. In summary,

1,3. Potentially a NULL pointer dereference which would cause chansrv to fail
2. Unused variable
4. Keygen is a standalone executable if it coredumps nothing is lost.
5. Looks like a false positive. If this fails we can't establish contact with the client using FIPS
