### ISSUE TITLE
Logout of GNOME

### ISSUE THREAD

**Issue by alexmyczko** [neutrinolabs/xrdp#2927]
### xrdp version

0.9.24

### Detailed xrdp version, build options

~~~
xrdp 0.9.24
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/scratch/xrdp/xrdp-0.9.24=. -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 
      PKG_CONFIG_PATH=/scratch/xrdp/xrdp-0.9.24/pkgconfig

  Compiled with OpenSSL 3.0.11 19 Sep 2023
~~~

### Operating system & version

Debian GNU/Linux 12 (bookworm)

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

libxrdp.so.0 => /usr/lib/x86_64-linux-gnu/xrdp/libxrdp.so.0 (0x00007fc85ef09000)

### What desktop environment do you use?

GNOME

### Environment xrdp running on

physical machine, NVIDIA Corporation GF108 [GeForce GT 430]

### What's your client?

Microsoft Remote Desktop on macOS

### Area(s) with issue?

Session manager (sesman)

### Steps to reproduce

Login and session resume works, however trying to logout fails, graphically as well as with command line.

### ✔️ Expected Behavior

It logs me out.

### ❌ Actual Behavior

.xsession-errors entry with
```
 (gnome-shell:559687): Gjs-WARNING **: 15:36:04.474: JS ERROR: Gio.DBusError: 
                  GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
```

When trying with `gnome-session-quit`

Only way to end the session is with `pkill -9 -u $USER`

Not sure if I selected the right Area for the issue and if this is not a bug in GNOME, however logout locally works.

**Comment by matt335672** [comment]
Coincidentally I've just added a FAQ for this:-

https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-perform-some-privileged-gui-actions

**Comment by alexmyczko** [comment]
So I tried your tool https://github.com/matt335672/pk-local but even when enabled and all, GNOME user can not logout...

**Comment by matt335672** [comment]
Are the symptoms still the same as you describe above?

**Comment by alexmyczko** [comment]
@matt335672 yes exactly the same symptoms. no matter how well i look at `pkaction` and `pkaction -a whatever -v` I can't find a the right thing to enable logging out of GNOME without `kill`, `gnome-session-quit` fails too.

**Comment by matt335672** [comment]
Thanks for the clarification. I'll try to reproduce this on Debian 12.

**Comment by alexmyczko** [comment]
I've done some work on https://packages.debian.org/sid/xrdp if you also have a chance to test on Debian sid, that'd be great... if it works for you, it's probably some local configuration changes breaking it...

**Comment by matt335672** [comment]
Thanks. I'll start with vanilla 12.

Give me a while - we've got a priority job on at the moment.

**Comment by alexmyczko** [comment]
https://github.com/neutrinolabs/xrdp/issues/820#issuecomment-1938548126

**Comment by alexmyczko** [comment]
Aha, this problem only exists if the user has

`.xsession`

with

`exec gnome-shell`

maybe because then there's no `use-session-dbus` from /etc/X11/Xsession.options?

**Comment by alexmyczko** [comment]
background info: https://bbs.archlinux.org/viewtopic.php?id=286530
