### ISSUE TITLE
Issue with Accessing Caused By User Name

### ISSUE THREAD

**Issue by Elif-Rana** [neutrinolabs/xrdp#2930]
### xrdp version

0.9.21.1

### Detailed xrdp version, build options

~~~
xrdp 0.9.21.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=aarch64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/aarch64-linux-gnu
      --libexecdir=${prefix}/lib/aarch64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=aarch64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/reproducible-path/xrdp-0.9.21.1=. -fstack-protector-strong -Wformat -Werror=format-security
      LDFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2
      PKG_CONFIG_PATH=/build/reproducible-path/xrdp-0.9.21.1/pkgconfig

  Compiled with OpenSSL 1.1.1w  11 Sep 2023
~~~

### Operating system & version

Raspbean

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

Xorg

### What desktop environment do you use?

any

### Environment xrdp running on

Raspberry Pi 4 Model B

### Steps to reproduce

The issue that I am encountered is that the Remote Desktop Tool does not let accessing when the user name has the dash character (-) in it.
The solution I used is simple. I just changed the user name and turned it into a new one which has not  the dash character in it. But, it was just an intuition at the beginning and it was hard to capture since there is no sign or error about it.
To me, to avoid such issues (not letting accessing when user name has the character '-') and make your tool more user friendly, is making the user name, which must be supplied as an input to make the other device available to access, sensitive to dash (-). I am not sure if there are issues with some other special characters such as underscore (_). If there are, they also should be taken care.

### ✔️ Expected Behavior

I was expecting my local computer to have an access the Raspberry Pi device without any problem since there is no error raised in the terminal while fulfilling the reqirements and running xrdp.

### ❌ Actual Behavior

There is no error in the terminal but the connection is failed by Remote Desktop Tool in my local computer. Either it gives an error or just an empty screen without any application or anything. It did only work when I changed the user name. The oldest user name had an '-' character in it.

### Anything else?

I accomplished accessing by changing the user name of my Raspberry Pi which is the device I am trying to access.

**Comment by matt335672** [comment]
I'm unable to reproduce this.

I took a working installation with a user `testuser`, and did the following:-
1) Edited `/etc/passwd` and changed `testuser` to `test-user`
2) Rehashed the password for `test-user`
3) Logged in to xrdp. All OK.

This doesn't seem to be as simple as a dash in a username.

Can you please provide  the following:-
1) `/var/log/xrdp-sesman.log` for a failing login
2) The output of this command:-
   ```
   getent passwd test-user | od -Ax -c -tx1
   ```

   Substitute the name of your user for `test-user`

Thanks.

**Comment by Elif-Rana** [comment]
Here is the output for
```
 /var/log/xrdp-sesman.log
```
###ar-ge user is error output response
```
[20240131-14:25:25] [INFO ] Socket 12: AF_INET6 connection received from ::1 port 35130
[20240131-14:25:25] [INFO ] ++ reconnected session: username ar-ge, display :11.0, session_pid 7743, ip ::ffff:[192.168.1.29:48554](http://192.168.1.29:48554/) - socket: 12
[20240131-14:25:25] [INFO ] Starting session reconnection script on display 11: /etc/xrdp/reconnectwm.sh
[20240131-14:25:25] [ERROR] sesman_data_in: scp_process_msg failed
[20240131-14:25:25] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20240131-14:25:25] [INFO ] Process 8034 has exited
```
###test user is success output response
```
[20240131-14:27:19] [INFO ] Socket 12: AF_INET6 connection received from ::1 port 49802
[20240131-14:27:19] [INFO ] ++ reconnected session: username test, display :10.0, session_pid 1171, ip ::ffff:[192.168.1.29:54252](http://192.168.1.29:54252/) - socket: 12
[20240131-14:27:19] [ERROR] sesman_data_in: scp_process_msg failed
[20240131-14:27:19] [INFO ] Starting session reconnection script on display 10: /etc/xrdp/reconnectwm.sh
[20240131-14:27:19] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20240131-14:27:19] [INFO ] Process 8084 has exited
```

**Comment by matt335672** [comment]
That's interesting, and not what I expected.
Both logs show a successful reconnection (despite the errors). This means you must have logged in successfully to start with.

- Please can give me the output of the command I asked for in my previous post?
- Can you restart the machine (to make sure no-one is logged in), try to log in with `ar-ge` and report exactly what happens. The xrdp-sesman.log will be useful.

**Comment by Elif-Rana** [comment]
Here are the output and the file you can take a look:
```
```

**Comment by Elif-Rana** [comment]
Here are the output and the file you can look
###Output for the command
```
getent passwd test-user | od -Ax -c -tx1
```
```
000000   a   r   -   g   e   :   x   :   1   0   0   0   :   1   0   0
        61  72  2d  67  65  3a  78  3a  31  30  30  30  3a  31  30  30
000010   0   :   ,   ,   ,   :   /   h   o   m   e   /   a   r   -   g
        30  3a  2c  2c  2c  3a  2f  68  6f  6d  65  2f  61  72  2d  67
000020   e   :   /   b   i   n   /   b   a   s   h  \n
        65  3a  2f  62  69  6e  2f  62  61  73  68  0a
00002c
```
[xrdp.log](https://github.com/neutrinolabs/xrdp/files/14121264/xrdp.log)

**Comment by matt335672** [comment]
The command looks good. You've added the wrong log file though, and I need a description of what happens (not just the log).

Can you restart the machine (to make sure no-one is logged in), try to log in with `ar-ge` and report exactly what happens.

Attach `xrdp-sesman.log`

**Comment by matt335672** [comment]
@Elif-Rana - do you need any more help with this?
