### ISSUE TITLE
Wrong rendering of EPS files in ghostview under XRDP

### ISSUE THREAD

**Issue by bo-qeye** [neutrinolabs/xrdp#2945]
### xrdp version

0.9.24

### Detailed xrdp version, build options

~~~
xrdp 0.9.24
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-redhat-linux-gnu
      --host=x86_64-redhat-linux-gnu
      --program-prefix=
      --disable-dependency-tracking
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/sbin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --sharedstatedir=/var/lib
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-fuse
      --enable-pixman
      --enable-painter
      --enable-vsock
      --enable-ipv6
      --with-socketdir=/run/xrdp
      --with-imlib2
      build_alias=x86_64-redhat-linux-gnu
      host_alias=x86_64-redhat-linux-gnu
      CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection 
      LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 1.1.1k  FIPS 25 Mar 2021
~~~

### Operating system & version

Rocky Linux 8.9 (Green Obsidian)

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

tigervnc-1.13.1-2.el8_9.7.src.rpm

### What desktop environment do you use?

GNOME

### Environment xrdp running on

Physical machine, Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller

### What's your client?

Microsoft's official client, installed from App Store, running on an Intel MacBook Air. macOS 14.3.1 (23D60), MRD 10.9.5 (2179)

### Area(s) with issue?

Graphic glitches

### Steps to reproduce

Install Rocky Linux 8.9, install xrdp, install ghostview, connect with MRD, view EPS file from here https://people.sc.fsu.edu/~jburkardt/data/eps/eps.html with gv (ghostview).

### ✔️ Expected Behavior

gv (ghostview) to render a simple EPS (encapsulated postscript) file correctly.

### ❌ Actual Behavior

Weird transparency, garbled rendering:

<img width="606" alt="Screenshot 2024-02-14 at 13 01 07" src="https://github.com/neutrinolabs/xrdp/assets/64956251/8d75b20e-94ae-413e-a3cd-414d27aad9b7">

```
$ dnf info gv
Last metadata expiration check: 0:08:38 ago on Wed 14 Feb 2024 01:06:46 PM CET.
Installed Packages
Name         : gv
Version      : 3.7.4
Release      : 25.el8
Architecture : x86_64
Size         : 670 k
Source       : gv-3.7.4-25.el8.src.rpm
Repository   : @System
From repo    : epel
Summary      : A X front-end for the Ghostscript PostScript(TM) interpreter
URL          : http://www.gnu.org/software/gv/
License      : GPLv3+
Description  : GNU gv is a user interface for the Ghostscript PostScript(TM) interpreter.
             : Gv can display PostScript and PDF documents on an X Window System.
```

**Comment by bo-qeye** [comment]
Curiously, the glitches also appear if I take a screenshot of the screen with the GNOME screenshot utility.

**Comment by matt335672** [comment]
It'll almost certainly be a problem with tigervnc, as we're not doing a lot in this mode apart from copying chunks of text about.

What colour depth are you using on the client? If it's 32-bit, try 24-bit. See also #1906 and the links off of it.

**Comment by bo-qeye** [comment]
@matt335672 thanks for your prompt reply.

We are indeed running 32 bits color depth on the client. I couldn't find an option to reduce it to 24, only 16, and with that, the connection never came up. Fixing it serverside with the `xserverbpp=24` as described in #1906 did the trick, however, with 
no change required client-side.

I'll close this, feel free to reopen if needed.

**Comment by bo-qeye** [comment]
Could also be related to https://github.com/TigerVNC/tigervnc/issues/1308
