### ISSUE TITLE
right click issue

### ISSUE THREAD

**Issue by therevoman** [neutrinolabs/xrdp#296]
We have been using xrdp in our development environments for 6 months now.  One of the problems we experience regularly has to do with the right-click functionality.  

Expected Behavior: On tap of right mouse button the context menu opens up and stays open

Actual Behavior: On tap of right mouse button the context menu opens briefly and the item under the mouse is selected and executed.

If I tap the right mouse button and move the mouse at the same time the expected behavior happens.  
If I right click and hold I can then select the appropriate menu item.  

I don't have a problem altering my behavior, but I have a team of 30 people using this tool, and many are fighting the change.  Since I am compiling the code into an RPM, is there somewhere in the code I can alter the virtual mouse to not be so picky on right click.  I read somewhere that x11 is known to be touchy.   

Thanks in advance.

**Comment by jsorg71** [comment]
I thought I fixed that.
What branch do you build from?

**Comment by therevoman** [comment]
I am using the devel branch with nox11rdp and xorg-driver options.  I would
use the master branch but there is a fix in devel that has not been moved
yet.

I just tested again and have some more information.  On the desktop it
appears to consistently work correct.  Inside the terminal app it never
works correct.  And inside eclipse it sometimes works correct.

I am not using any of the jpeg config options or the librfxcodec as I
cannot copy files across with those options enabled.

I can do some debugging or code searching if needed.  I'm a Java developer
with limited C++ skills but can help a bit.

-Nate

**Comment by therevoman** [comment]
Tested fix 
a399a9435a0c4cec9b617c1a25cfadbd62780df1 and confirmed the right click behavior has been corrected when using the xorg driver.

Thank you!
