### ISSUE TITLE
Found many sshd zombie processes.

### ISSUE THREAD

**Issue by peijifeng** [neutrinolabs/xrdp#2961]
### xrdp version

0.9.21.1

### Detailed xrdp version, build options

~~~

Found many sshd zombie processes.

![image](https://github.com/neutrinolabs/xrdp/assets/8315865/fdda4043-20a6-4686-b3fb-d443a6ea4907)
![image](https://github.com/neutrinolabs/xrdp/assets/8315865/c51a206c-c55c-47f8-b23d-0a5682c47688)

~~~

### Operating system & version

Ubuntu 23.10

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp(1:0.9.19-1)

### What desktop environment do you use?

Xfce

### Environment xrdp running on

docker

### What's your client?

mRemoteNG

### Area(s) with issue?

Other

### Steps to reproduce

do some ssh connections

### ✔️ Expected Behavior

no sshd zombie processes leaving behind

### ❌ Actual Behavior

leaving  many sshd zombie process behind

**Comment by metalefty** [comment]
Not related to xrdp.
