### ISSUE TITLE
xrdp closes port 3389

### ISSUE THREAD

**Issue by Semperfi4000** [neutrinolabs/xrdp#297]
Hello, we ran X11RDP-o-Matic on a physical “Mint 17.2” and a Virtual “Mint 17.2”, 
The physical works fine.  But, with my virtual system, when I RDP from my windows 7 system or MAC RDP, it closes port 3389. Any idea as to why?

I do see port 3389 is open.  But, once I attempt to make a connection,  the port closes. 
I am able to open the port again, by restarting xrdp service.   However, that only works once. 
thereafter, If I make another attempt,  it closes the port again;  but. restarting xrdp services doesn't reopen the port.   At which, I have to then reboot the system 

thank you for your help.

**Comment by metalefty** [comment]
Can you try the latest release? If you still reprodue the issue, please reopen.
