### ISSUE TITLE
[xorgxrdp] xrdp cannot connect xorgxrdp on FreeBSD

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#299]
I'm using xorgxrdp=884b347 xrdp=f49e205.

I'm trying xorgxrdp on FreeBSD. I suppose it is almost working.
sesman can create new Xorg process. However, xrdp cannot connect
Xorg (xorgxrdp) created by sesman.

verbose log  of xorgxrdp:
http://w.vmeta.jp/temp/Xorg.11.log

It seems stuck in an infinite loop in rdpClientCon.c line 2079.
```
[  3032.520] rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
[  3032.562] rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
[  3032.606] rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
[  3032.651] rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
[  3032.692] rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
```

Jay, do you have any ideas?

**Comment by jsorg71** [comment]
When Xorg starts, is it running as root?  It should be the user
Check if set uid is set for /usr/local/bin/Xorg.
I see this too with newest Fedora.

**Comment by metalefty** [comment]
That's it. 

```
 $ ls -l /usr/local/bin/Xorg
-r-sr-xr-x  1 root  wheel  2146128 Dec  8 10:43 /usr/local/bin/Xorg
```

**Comment by metalefty** [comment]
I installed non-suid Xorg, now Xorg is running user privilege.

```
$ ps uxaww|grep Xorg
meta       736   0.1  3.6 172864 37296  -  I     8:01PM 0:01.07 Xorg :10 -config xrdp/xorg.conf -noreset -ac -nolisten tcp -logfile /tmp/a
```

However,  something is still going wrong.  I meet infinite rdpDeferredUpdateCallback again.

```
$ tail -f /tmp/a 
[   217.779] rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
[   217.823] rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
[   217.867] rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
[   217.911] rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
[   217.955] rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
```

**Comment by metalefty** [comment]
FYI, FreeBSD ports of xrdp and xorgxrdp are here for testing as net/xrdp-head,
x11-dervers/xorg-driver-rdp.
https://github.com/metalefty/freebsd-ports/tree/xorgxrdp

**Comment by jsorg71** [comment]
@metalefty 
I just tested PCBSD 10, it works with xorgxrdp driver.
It looks to me like the client is asking for RFX session and rfxcodec is not enabled.
It doesn't handle some fail cases very well yet.
Change the client setting to use WAN, or lower the bpp.
What client are you using?

BTW, how do you install non-suid Xorg?

**Comment by metalefty** [comment]
I tested mstsc.exe of Windows 7 and rdesktop 1.8.3.  I'll try to change client settings later, thanks.

Using ports collection, you can configure SUID option on/off.  It may be same even in PCBSD.

```
$ cd /usr/ports/x11-servers/xorg-server
# make config
(set SUID option off)
# make install
```

**Comment by metalefty** [comment]
Client setting wasn't a problem for me. Even with lower bpp or setting, infinite
rdpDeferredUpdateCallback doesn't stop. It turned out xorgxrdpsession is actually
working.  However, the screen blacked out (or can be called "greened out").

xterm is actually working in the xorgxrdp session but I can't see it.
cursor changes, I can type commands(but can't see) and execute it.
Screenshot is here (Windows 7):
https://gyazo.com/d03542ababf8baceb36eb98b9ab3e69e

**Comment by metalefty** [comment]
I confirmed tt works with xorgxrdp on PCBSD.  Probably, it is considered not to be xrdp or xorg xrdp issue.  Once I close this.
