### ISSUE TITLE
Mouse wheel scrolling in Xvnc session no longer works in 0.9.25

### ISSUE THREAD

**Issue by bsmojver** [neutrinolabs/xrdp#2993]
### xrdp version

0.9.25

### Detailed xrdp version, build options

~~~
xrdp-0.9.25-1.fc39
~~~

https://bodhi.fedoraproject.org/updates/FEDORA-2024-f55299aef8

### Operating system & version

Fedora 39

### Installation method

dnf

### Which backend do you use?

tigervnc-server-minimal-1.13.1-11.fc39

### What desktop environment do you use?

GNOME

### Environment xrdp running on

Hyper-V VM

### What's your client?

Microsoft official client on Windows 10

### Area(s) with issue?

Keyboard / Mouse

### Steps to reproduce

Upgrade to xrdp-0.9.25.

### ✔️ Expected Behavior

Mouse wheel scrolling should work.

### ❌ Actual Behavior

Nothing happens when Xvnc is used. When Xorg is used (i.e. via xorgxrdp), things work as expected.

### Anything else?

Downgrade to 0.9.24 makes mouse wheel scrolling work under Xvnc again.

**Comment by metalefty** [comment]
My bad, I forgot to pick #2425 for v0.9. It should work if you apply #2425.

I'll make another release with that fix. Sorry for the breakage.

**Comment by metalefty** [comment]
@bsmojver Can you test #2994?

**Comment by bsmojver** [comment]
> @bsmojver Can you test #2994?

Will do another build and test today. Thank you!

**Comment by bsmojver** [comment]
Updates including patch from #2994 built and tested. Scrolling with mouse wheel works in Xvnc. Thank you!

**Comment by metalefty** [comment]
Will make v0.9.25.1 release today or tomorrow, thanks for testing!

**Comment by matt335672** [comment]
I'll add my apologies here too. I also missed the missing backport. Thanks for the swift action @bsmojver!
