### ISSUE TITLE
ipv6 support for xrdp.

### ISSUE THREAD

**Issue by itamarjp** [neutrinolabs/xrdp#30]
Hello guy's 

We need to add ipv6 support into xrdp

**Comment by metalefty** [comment]
:+1: I also happy if xrdp had ipv6 support. Anything new?

**Comment by metalefty** [comment]
@jsorg71 
You disabled IPv6 at cd0a872, but why? Do you have a plan to re-enable IPv6?

**Comment by metalefty** [comment]
In other words, what should we do to re-enabling IPv6? What tasks remained?

**Comment by jsorg71** [comment]
I broke some systems.  I didn't have enough experience using ipv6.  For example, BSD is a bit different.
I think until it's tested more, we should add --enable-ipv6

**Comment by metalefty** [comment]
I did --enable-ipv6 option.  I'll give it a try for BSDs and other systems as much as I can.  Please tell me how was it broken if you remember.

**Comment by jsorg71** [comment]
I think it was something like mint 64 bit that would not accept connection.

For the BSD issue,

This is from
Thomas
on mailing list 04/04/2013


I second thing I observed:

Linux uses one socket for all -  v4 and v6.

If I remember correctly BSD does not so behave.
In the case the xrdp needs compatibility with bsd, it could be necessary
to implement two sockets.

e.g. sshd does so:

tcp        0      0 0.0.0.0:22              0.0.0.0:* LISTEN      2574/sshd
tcp        0      0 :::22                   :::* LISTEN      2574/sshd


xrdp


tcp        0      0 :::3389                 :::* LISTEN      5311/xrdp


Regards,

Thomas

**Comment by metalefty** [comment]
After further investigation, BSD (at least FreeBSD) can handle both IPv4 and IPv6 in one socket.
SSH, PostgreSQL demon have independent socket for v4 and v6 . However, MySQL daemon seems to listen v4 and v6 in one socket.

```
Active Internet connections (including servers)
Proto Recv-Q Send-Q Local Address          Foreign Address        (state)
tcp4       0      0 *.ssh                  *.*                    LISTEN
tcp6       0      0 *.ssh                  *.*                    LISTEN
tcp46      0      0 *.mysql                *.*                    LISTEN
tcp4       0      0 *.rdp                  *.*                    LISTEN
tcp4       0      0 localhost.postgresql   *.*                    LISTEN
tcp6       0      0 localhost.postgresql   *.*                    LISTEN
```

**Comment by metalefty** [comment]
The problem looks quite simple (at least on FreeBSD).

IPv6 auto detection appeared in 54463aff  is not suitable for FreeBSD.

```
AC_CHECK_MEMBER([struct in6_addr.s6_addr],
                [],
                [AC_DEFINE(NO_ARPA_INET_H_IP6, 1, [for IPv6])],
                [#include <arpa/inet.h>])
````

This always fails. NO_ARPA_INET_H_IP6 is always 1 in  FreeBSD and xrdp will always by built IPv6 support disabled.

**Comment by metalefty** [comment]
OpenBSD behaves a little bit different.  Jay and Thomas talked on the mailing list.
We need to implement two sockets for OpenBSD but one socket is enough for others.

**Comment by metalefty** [comment]
IPv6 implementation in xrdp has been improved a lot (#714 etc). Let's close this once.
I don't think we don't need to listen IPv4 and IPv6 in separate socket right now.
