### ISSUE TITLE
Scroll failure

### ISSUE THREAD

**Issue by CaptainBloodz** [neutrinolabs/xrdp#3006]
### xrdp version

0.9.25.1

### Detailed xrdp version, build options

scroll fails.
0.9.23.1 restoring fixes

[Gentoo bug report](https://bugs.gentoo.org/927218)

### Operating system & version

Gentoo

### Installation method

other

### Which backend do you use?

FreeRDP

### What desktop environment do you use?

LXDE

### Environment xrdp running on

Physical

### What's your client?

Remmina

### Area(s) with issue?

Keyboard / Mouse

### Steps to reproduce

Any mouse scroll doesn'f work, e.g. urxvtd & firefox-bin [EDITED]

### ✔️ Expected Behavior

Normal scrolling

### ❌ Actual Behavior

Fails to scroll

### Anything else?

Nothing special

**Comment by matt335672** [comment]
More info please @CaptainBloodz .

1) Are you using the Xorg or VNC backend?
2) What does "scroll failure" mean? Can you be more descriptive?

**Comment by CaptainBloodz** [comment]
> More info please @CaptainBloodz .
>     1. Are you using the Xorg or VNC backend?
Xorg
>     2. What does "scroll failure" mean? Can you be more descriptive?
Mouse scroll doesn't work.  Mouse clicks do.

**Comment by matt335672** [comment]
Thanks.

What version of xorgxrdp are you using?

**Comment by CaptainBloodz** [comment]
[I] net-misc/xorgxrdp [1]
     Available versions:  ~0.2.18-r1^m (~)0.9.19^m {glamor}
     Installed versions:  0.9.19^m(22:47:33 17/03/2024)(glamor)
     Homepage:            http://www.xrdp.org/
     Description:         Xorg drivers for xrdp

**Comment by CaptainBloodz** [comment]
Just read net-misc/xorgxrdp-0.9.20 release note...
Unfortunately not yet available on gentoo.
net-misc/xorgxrdp-0.9.19 package script replication to .20 isn't enough to install.

Above gentoo bug report has email for net-misc/*xrdp* ace [repository](https://github.com/gentoo-mirror/ace) maintenance.

**Comment by CaptainBloodz** [comment]
> Unfortunately not yet available on gentoo. net-misc/xorgxrdp-0.9.19 package script replication to .20 isn't enough to install.

I failed there, overlooking net-misc/xorgxrdp-0.9.20 claimed for net-misc/xrdp-0.9.25
Things working good enough here now.

Plz feel free to close.

Thks 4 ur attention, interest & support.

**Comment by matt335672** [comment]
That's fine @CaptainBloodz - feel free to come back to us if the update doesn't fix it.
