### ISSUE TITLE
Session no longer usable when client system crashed

### ISSUE THREAD

**Issue by firewave** [neutrinolabs/xrdp#3023]
### xrdp version

0.9.24

### Detailed xrdp version, build options

~~~
Built by AUR.
~~~

### Operating system & version

Manjaro Linux

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgrdp 0.19

### What desktop environment do you use?

KDE Plasma X11

### Environment xrdp running on

phsyical

### What's your client?

official Microsoft RDP client

### Area(s) with issue?

Other

### Steps to reproduce

- connect to the remote server
- client machine crashes/freezes while connection is open (my machine has some strange hardware which causes rare freezes)

### ✔️ Expected Behavior

The remote desktop is shown.

### ❌ Actual Behavior

You can still connect but it will not show the remote desktop. You need to restart the server for it to be usable again.

**Comment by matt335672** [comment]
This could be any number of things.

Get #3024 sorted out first, then see if you can reproduce this one when you've got a working desktop.

**Comment by firewave** [comment]
> Get #3024 sorted out first, then see if you can reproduce this one when you've got a working desktop.

The desktop is actually working fine except for the file copy and paste issue.

**Comment by matt335672** [comment]
Hmm.
File copy/paste to and from xrdp uses the X11 clipboard and the FUSE filesystem. We don't directly use any kind of message bus.

**Comment by firewave** [comment]
I think we still have a misunderstanding.

The issue happens if I try to copy+paste a file (not text) *within* the remote desktop. I do *not* try to move any data between the local and remote desktop.

I wanted to check it again to see if I can provide more details but yesterday I updated to 0.10.x via AUR and now I am encountering https://github.com/neutrinolabs/xrdp/discussions/2732 so I can no longer test it...

**Comment by matt335672** [comment]
OK - thanks.

I think the misunderstanding was all down to me, but the point is still valid I think.

**Comment by matt335672** [comment]
@firewave - are you still experiencing problems in this area?

**Comment by matt335672** [comment]
No further response - closing.

**Comment by firewave** [comment]
I hadn't used it in a while and my client machine is less crashy recently. Will re-open if it encounters again and I have some more data.

**Comment by firewave** [comment]
I just made my client machine freeze up again and the session was still working as expected afterwards. So this appears to be fixed.
