### ISSUE TITLE
copy and paste of files does not work on the remote system

### ISSUE THREAD

**Issue by firewave** [neutrinolabs/xrdp#3024]
### xrdp version

0.9.24

### Detailed xrdp version, build options

~~~
Built by AUR.
~~~

### Operating system & version

Manjaro Linux

### Installation method

other

### Which backend do you use?

xorgrdp 0.19

### What desktop environment do you use?

KDE Plasma X11

### Environment xrdp running on

physical

### What's your client?

official Microsoft RDP client

### Area(s) with issue?

Clipboard

### Steps to reproduce

Note: I am using Dolphin

- copy a file by either by using `CTRL+C` or `Copy` from the context menu
- try to paste the file either by using `CTRL+V` or `Paste` from the context menu

### ✔️ Expected Behavior

The operation is successful.

### ❌ Actual Behavior

The operation fails with the following error:
![image](https://github.com/neutrinolabs/xrdp/assets/242857/b4fc881b-7cf6-41db-b09e-0ec3a607fa95)

**Comment by matt335672** [comment]
You've possibly started your session without an active DBus. 

This can be tricky to get right on Arch/Manjaro. Check out #2975 for a few pointers. There is a link or two in there to the Arch wiki.

**Comment by firewave** [comment]
Same issue using `xrdp-0.10.0_beta.3-1` AUR package. Will dig into the linked resources later.

**Comment by matt335672** [comment]
@firewave - do you need any more help with this?

**Comment by firewave** [comment]
This is working fine now. Not sure what fixed it. My distro got some major updates (including KDE 6.0/6.1) and the installed xrdp package is `0.10.1-1` from AUR.

The copy and paste even works across the devices.

**Comment by matt335672** [comment]
Thanks for the update.
