### ISSUE TITLE
xrdp crashes on Debian 12 with rdesktop as root

### ISSUE THREAD

**Issue by alexmyczko** [neutrinolabs/xrdp#3028]
### xrdp version

0.9.24

### Detailed xrdp version, build options

~~~
simple sid backport
~~~

### Operating system & version

Debian 12

### Installation method

Doesn't matter

### Which backend do you use?

xrdp

### What desktop environment do you use?

GNOME

### Environment xrdp running on

bare metal

### What's your client?

rdesktop 1.9.0

### Area(s) with issue?

Crashes such as segfault

### Steps to reproduce

do the same as me, simple sid backport of xrdp, install on Debian 12, have gnome installed and login remotely.

### ✔️ Expected Behavior

Login works, could be a problem of GNOME, will try with user

### ❌ Actual Behavior

Crashes with:

```
Do you trust this certificate (yes/no)? yes
Connection established using SSL.
Clipboard(error): xclip_handle_SelectionNotify(), unable to find a textual target to satisfy RDP clipboard text request
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Value in failed request:  0x0
  Serial number of failed request:  21399
  Current serial number in output stream:  22036
```

**Comment by alexmyczko** [comment]
Ok don't bother, also crashes with user+rdesktop. and xfreerdp (2.6.1). ok with macOS Microsoft RDP client...

**Comment by matt335672** [comment]
Thanks for the update - I'll close this then.

At a first glance I don't think this is anything that can be attributed to xrdp - we don't speak X11 to the client.

Suggest you try xfreerdp to see if your experience is different - I think it's part of the `freerdp2-x11` package on Debian 12. We're not affiliated with either application here but we tend to use recent xfreerdp builds for testing.
