### ISSUE TITLE
Increased CPU usage in Ubuntu 24.04 Desktop LTS on Raspberry Pi 5

### ISSUE THREAD

**Issue by Chuck321123** [neutrinolabs/xrdp#3048]
### xrdp version

0.9.24-4

### Operating system & version

Ubuntu 24.04 Desktop LTS for raspberry PI

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

Xorg

### Environment xrdp running on

Win 11

### Steps to reproduce

So I used xrdp on my rpi 5 on Ubuntu 23.10 with no problem where the cpu idle usage was about 25-30% on all cores when i used remote desktop from Windows, but when i switched to Ubuntu 24.04 the cpu usage is now 60-80%, which is far too much from just idling at the desktop. The cpu usage came from gnome shell related processes. However, if i minimized the remote desktop on my windows pc, the cpu usage fell to 1% again, before spiking to 60-80% when i actively used xrdp.

### ✔️ Expected Behavior

That xrdp max uses about 25-30% just as it did in Ubuntu 23.10

### ❌ Actual Behavior

That it uses 60-80% of cpu on all cores

**Comment by matt335672** [comment]
We're having some issues with GNOME on 24.04 at the moment. See #3053 

I suggest you try the configuration in there, as at least it's been tested by the Ubuntu team.

Other than that, there's not much we can do from this end I'm afraid. This version of GNOME isn't getting much testing on X11 so I'm not surprised there are some regressions.

You can also get some mileage out of investigating why you're seeing CPU usage that high on either platform. I'm running on a Haswell VM with two cores. The CPU is a decade old. If I run `top` in an xrdp session I'm seeing idle times >90% most of the time on 24.04.

In any case, please try the config and report back.

**Comment by matt335672** [comment]
@Chuck321123 - do you need any more help with this?

**Comment by Chuck321123** [comment]
@matt335672 No, I use an alternative software instead

**Comment by matt335672** [comment]
Thanks for the update @Chuck321123
