### ISSUE TITLE
USB is not being automounted when  logged in with non-root user

### ISSUE THREAD

**Issue by modernNeo** [neutrinolabs/xrdp#3078]
### xrdp version

0.9.21.1

### Detailed xrdp version, build options

~~~
xrdp 0.9.21.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-QTF2mN/xrdp-0.9.21.1=. -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 
      PKG_CONFIG_PATH=/build/xrdp-QTF2mN/xrdp-0.9.21.1/pkgconfig

  Compiled with OpenSSL 3.0.11 19 Sep 2023
~~~

### Operating system & version

Debian GNU/Linux 12 (bookworm)

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp 1:0.9.19-1

### What desktop environment do you use?

Cinnamon

### Environment xrdp running on

physical machine with Alder Lake-P Integrated Graphics Controller

### Area(s) with issue?

Other

### Steps to reproduce

1. login with non-root user
2. plug in a USB on the physical machine that is being RDPed into

### ✔️ Expected Behavior

for the usb to be auto-mounted

### ❌ Actual Behavior

the usb is not auto-mounted. instead i see this if I click on the USB

![remmina_the-machine local_the-machine local_2024517-205822](https://github.com/neutrinolabs/xrdp/assets/14242088/882402af-27db-400c-ad27-9b4ee4d649a8)

**Comment by matt335672** [comment]
Duplicate of #2934. Have a look at [this comment](/neutrinolabs/xrdp/issues/2934#issuecomment-1926668705) and below.

In summary; by default `polkit` won't allow this operation as you're not logged in to the console. This is to prevent a security hole where remote users can read USB sticks of other users attached to the console.

**Comment by modernNeo** [comment]
oh, sorry for not responding sooner...for some reason github didn't notify me of the new comments on this issue....will follow-up tomorrow

**Comment by modernNeo** [comment]
how come the root user can see the USB drive then?

**Comment by matt335672** [comment]
You'd have to check out the polkit rules to be sure exactly what is happening.

**Comment by matt335672** [comment]
@modernNeo - do you need any more help with this?

**Comment by modernNeo** [comment]
do I need to follow the instructions in [this message](https://github.com/neutrinolabs/xrdp/issues/2934#issuecomment-1954041456) to get polkit to allow my users to mount USB drives?

**Comment by matt335672** [comment]
You'll need to do something like that to figure out exactly what is happening with Polkit.

The linked message is for GNOME rather than Cinnamon, so you may find the polkit actions are not the same.

**Comment by modernNeo** [comment]
alright, I will get to this soon and report back on how it went.

**Comment by modernNeo** [comment]
finally went down the rabbit-hole and let me tell you, times like these are why I hate Linux, the documentation is God awful and assumes certain things about a user's knowledge.

if you want to get some logging going, you **absolutely** need an active GUI session. I was desperately trying to figure out why for 2 hours, my SSH session was proving so unproductive until I got the idea to open a GUI session and things started working.

# To ensure logging will be printed

update `/lib/systemd/system/polkit.service` to remove the `--no-debug` line from 
```bash
ExecStart=/usr/lib/polkit-1/polkitd --no-debug
```

before doing `systemctl daemon-reload` and `systemctl restart polkit` to enable the logging.

and then on another terminal screen, keep the command `sudo journalctl -xef` running. really good and easy way to see continous logging.

# adding logging to polkit files

If you want to just be able to detect **any** action that is being intercepted by polkit, add the following file

> You can read `AUTHORIZATION RULES` portion of [`polkit`](https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html) to get more details on how file names matter when priority is being determined.

`/etc/polkit-1/rules.d/00-allow-usb-mounts.rules`
```js
polkit.addRule(function(action, subject) {
  polkit.log("got action "+action);
  polkit.log("got subject "+subject);
});
```

and you can do `systemctl restart polkit`, but it's really not necessary as polkit is really good at self-reloading when it detects a change in the file.



then plugged the USB into my machine and saw 
```bash
Nov 30 14:23:05 the-machine polkitd[1005038]: got action [Action id='org.freedesktop.udisks2.filesystem-mount-other-seat' device='/dev/sda1' polkit.message='Authentication is required to mount $(drive)' partition.flags='0x00000080' partition.type='0x83' drive='Kingston DataTraveler 3.0 (/dev/sda1)' drive.revision='PMAP' partition.number='1' partition.uuid='XXXXX' id.type='ext4' drive.serial='XXXXX' id.uuid='XXXXX' id.label='jace_docs' polkit.gettext_domain='udisks2' id.version='1.0' drive.removable.media='thumb' drive.removable='true' drive.vendor='Kingston' id.usage='filesystem' drive.removable.bus='usb' drive.model='DataTraveler 3.0']
Nov 30 14:23:05 the-machine polkitd[1005038]: got subject [Subject pid=XXXXX user='XXXXX' groups=XXXXX seat=null session=null local=false active=true]
```
after that, I updated my rule to

`/etc/polkit-1/rules.d/00-allow-usb-mounts.rules`
```js
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.udisks2.filesystem-mount-other-seat"){
        polkit.log("got action "+action);
        polkit.log("got subject "+subject);
        if (action.lookup('drive.serial') == 'XXXXX' && 
        action.lookup('id.uuid') == 'XXXXX' && 
            subject.user == 'XXXXX' && subject.isInGroup ("sudo") && subject.active){
                return polkit.Result.YES;
        }
    }
});
```

and now everything works.

Only thing left to do is figure out how to allow the USB to be mount-able even if I don't have an xrdp active session but that's an issue for another repo and another day.
