### ISSUE TITLE
error when copying file!

### ISSUE THREAD

**Issue by mengxin523** [neutrinolabs/xrdp#3089]
### xrdp version

0.9.13

### Detailed xrdp version, build options

~~~
Paste the result between `~~~`.  Please DO NOT remove `~~~`!
![image](https://github.com/neutrinolabs/xrdp/assets/39935125/431461a7-5cab-424b-83c6-e9fef3ca9929)

~~~

### Operating system & version

suse15 sp5

### Installation method

dnf / apt / zypper / pkg / etc

### Environment xrdp running on

VM

### What's your client?

windows rdp

### Area(s) with issue?

File transfer / drive redirection

### Steps to reproduce

Ctrl+c,and ctrl+v

**Comment by mengxin523** [comment]
![image](https://github.com/neutrinolabs/xrdp/assets/39935125/ad9400c9-580a-45d1-9299-da7871362a38)

**Comment by matt335672** [comment]
@mengxin523 - that's quite an old version of xrdp. We've made some significant improvements to copy-paste in more recent versions.

Are you able to try the copy from the command line?

**Comment by mengxin523** [comment]
> @mengxin523 - that's quite an old version of xrdp. We've made some significant improvements to copy-paste in more recent versions.
> 
> Are you able to try the copy from the command line?

How can i do it from the command line?

**Comment by matt335672** [comment]
On a default installation your Windows drives should be mounted under `~/thinclient_drives`.

Create a terminal window, and type in this command:-

```
ls -l ~/thinclient_drives/
```

Can you see your Windows drives?
Do you want to copy from Linux to Windows or Windows to Linux?

**Comment by mengxin523** [comment]
> On a default installation your Windows drives should be mounted under `~/thinclient_drives`.
> 
> Create a terminal window, and type in this command:-
> 
> ```
> ls -l ~/thinclient_drives/
> ```
> 
> Can you see your Windows drives? Do you want to copy from Linux to Windows or Windows to Linux?

I cann't find any thing , the ~/thinclient_deives is not exist!
i want to copy file from windows to linux and linux to windows,  now , linux to windows is working fine
but windows to linux is sick

**Comment by matt335672** [comment]
This version of xrdp may not be the best way to copy the files you need.

Do you have any other ways to reach the Linux machine from the Windows machine? is ssh available between the two?

**Comment by mengxin523** [comment]
> This version of xrdp may not be the best way to copy the files you need.
> 
> Do you have any other ways to reach the Linux machine from the Windows machine? is ssh available between the two?

yes, So you are suggesting that I upgrade this software version? I have downloaded the file, but I don't know how to install it.

**Comment by mengxin523** [comment]
> This version of xrdp may not be the best way to copy the files you need.
> 
> Do you have any other ways to reach the Linux machine from the Windows machine? is ssh available between the two?

So you're saying that the latest version currently supports directly copying files in Windows with ctrl+c and then pasting them in Linux with ctrl+v ？

**Comment by matt335672** [comment]
It supports it a lot better than your current version. We've fixed a lot of bugs in that area. However, it still won't be as good as a dedicated copying utility because of the way it works.

We can't help you with installation here I'm afraid. We just produce the software which is then packaged by SuSE.

**Comment by mengxin523** [comment]
> It supports it a lot better than your current version. We've fixed a lot of bugs in that area. However, it still won't be as good as a dedicated copying utility because of the way it works.
> 
> We can't help you with installation here I'm afraid. We just produce the software which is then packaged by SuSE.

OK, thanks, I will check and reinstall the software with new version
