### ISSUE TITLE
X server could not be started

### ISSUE THREAD

**Issue by tomas-pinto** [neutrinolabs/xrdp#3096]
### xrdp version

0.10.0

### Detailed xrdp version, build options

~~~
xrdp 0.10.0
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2024 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      

  Compiled with OpenSSL 3.0.2 15 Mar 2022
~~~

### Operating system & version

Ubuntu 22.04

### Installation method

git clone & make install

### Which backend do you use?

xorgxrdp v0.10.1

### What desktop environment do you use?

GNOME

### Environment xrdp running on

2x GTX 1080Ti

### What's your client?

Windows 10 Remote Desktop Connection

### Area(s) with issue?

Session manager (sesman)

### Steps to reproduce

Followed this tutorial: https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8 on clean Ubuntu 22.04 installation without compilation of X11rdp.

### ✔️ Expected Behavior

Being able to connect to remote machine.

### ❌ Actual Behavior

Got following message: Can't create session for user tomas - X server could not be started

### Anything else?

[xrdp.log](https://github.com/neutrinolabs/xrdp/files/15483066/xrdp.log)
[xrdp-sesman.log](https://github.com/neutrinolabs/xrdp/files/15483067/xrdp-sesman.log)

**Comment by metalefty** [comment]
It appears that you didn't modified `sesman.ini` to fit your environment. Search for `Ubuntu` in `seman.ini`.

**Comment by tomas-pinto** [comment]
Thank you @metalefty! I've been able to make it work now
