### ISSUE TITLE
Request to add xrdp version 10 to Ubuntu apt packages

### ISSUE THREAD

**Issue by Chuck321123** [neutrinolabs/xrdp#3099]
### xrdp version

0.9.24-4

### Operating system & version

Ubuntu 24.04

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

Xorg

### Environment xrdp running on

Windows remote desktop

### What's your client?

Microsoft official client

### Steps to reproduce

So, even though nothing shows wrong in the xrdp status and it shows its running perfectly, I can still not connect with xrdp version 0.9.24-4 on Ubuntu 24.04 LTS. Therefore, I wondered if someone could add version 10 to apt packages in Ubuntu? Maybe this will fix my connectivity problems on the new Ubuntu. 

### ✔️ Expected Behavior

That the newest version of xrdp is available on apt package

### ❌ Actual Behavior

That only version 0.9.24-4 is available through sudo apt installment

**Comment by metalefty** [comment]
Unfortunately, we're not responsible for that. Ask Ubuntu team because Ubuntu is developed by Ubuntu team.
