### ISSUE TITLE
Constant Authentication Prompts

### ISSUE THREAD

**Issue by znbaboy** [neutrinolabs/xrdp#3100]
### xrdp version

0.9.17-2ubuntu2

### Detailed xrdp version, build options

~~~
xrdp 0.9.17
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-asBei3/xrdp-0.9.17=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -Wno-error=deprecated-declarations
      PKG_CONFIG_PATH=/build/xrdp-asBei3/xrdp-0.9.17/pkgconfig

  Compiled with OpenSSL 3.0.2 15 Mar 2022
~~~

Constantly asked for authentication when the system performs ANY elevated task. This only occurs when remoting in, but not when using the desktop normally. I only have one account on the machine.

### Operating system & version

Linux Mint 21.3 Cinnamon

### Installation method

dnf / apt / zypper / pkg / etc

### What desktop environment do you use?

Cinnamon

### Environment xrdp running on

Physical Desktop with GTX 1060

### What's your client?

Connecting from Windows 11 built-in RDP 

### Area(s) with issue?

Authentication

### Steps to reproduce

Step 1. Remote in from Windows machine using same account credentials
Step 2. Install anything from Software Manager or System Updates

### ✔️ Expected Behavior

Should install/update with 1 or 2 authentication prompts if needed

### ❌ Actual Behavior

Authentication requested for EVERY elevated task required to complete task

**Comment by matt335672** [comment]
This is a Polkit issue:-

https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-perform-some-privileged-gui-actions

Have a look at that, and come back if you've further questions.
