### ISSUE TITLE
RDP Login while the account is logged in mess the session

### ISSUE THREAD

**Issue by ibaraki-douji** [neutrinolabs/xrdp#3108]
### xrdp version

0.9.17

### Detailed xrdp version, build options

~~~
xrdp 0.9.17
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-asBei3/xrdp-0.9.17=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -Wno-error=deprecated-declarations
      PKG_CONFIG_PATH=/build/xrdp-asBei3/xrdp-0.9.17/pkgconfig

  Compiled with OpenSSL 3.0.2 15 Mar 2022
~~~

### Operating system & version

Pop OS 22.04 (Ubuntu deriv)

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorg

### What desktop environment do you use?

tested with Gnome and Cinnamon

### Environment xrdp running on

Physical

### Area(s) with issue?

Authentication

### Steps to reproduce

On your Main PC that contains xrdp, login to your user account.

On your laptop, connect to the same account as the Main PC.

### ✔️ Expected Behavior

Either the RDP session close (which is the case) and the Main PC session works fine.
Or the Main PC disconnect to let the RDP session open.

### ❌ Actual Behavior

The RDP session close (expected) but the Main PC sessions is kinda broken :
- I cannot open files
- I cannot open terminal
- I can open some application (File explorer, Firefox)

*Look like the current user is half connected*

After a logout / login everything works again.

**Comment by matt335672** [comment]
@ibaraki-douji - this is a known issue. See the [FAQ](https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-log-the-same-user-on-on-the-graphical-console-and-over-xrdp-at-the-same-time)

As I hope the FAQ makes clear this is a problem on all systemd-based systems. The workaround is to use a different user for xrdp access.
