### ISSUE TITLE
Remote Desktop Connection closes almost immediately when trying to connect to Debian via WSL

### ISSUE THREAD

**Issue by RenoL911** [neutrinolabs/xrdp#3110]
### xrdp version

 0.9.21

### Detailed xrdp version, build options

~~~
Paste the result between `~~~`.  Please DO NOT remove `~~~`!
~~~

### Operating system & version

Debian 12

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

Xvnc, Xfce4, Tigervnc

### Environment xrdp running on

WSL

### Steps to reproduce

**am not quite sure but it's somthing like this:**

1. Start a Windows 10 PC.
2. Ensure WSL2 is installed and functioning correctly.
3. Open an XRDP session from the Windows PC to the Debian 12 server.
4. Attempt to authenticate and establish a remote desktop connection.
5. Observe intermittent connectivity issues during the session establishment.
6. Check the XRDP logs (/var/log/xrdp.log and /var/log/xrdp-sesman.log) for any error messages or warnings.
7. Repeat steps 3-6 multiple times to confirm the intermittent nature of the bug.

### ✔️ Expected Behavior

to login to my debian session and observe the debian GUI on RDP

### ❌ Actual Behavior

black screen after login in with the linux black cursor and it usualy just quits  

### thanks in advance hope you help me with this issue

**Comment by matt335672** [comment]
@RenoL911 - thanks for raising this.

Reading the above and #3097, it seems to me that you're not entirely comfortable troubleshooting this setup.

The first thing to do is to eliminate the possibility that you've got two graphical sessions running under the same user on the Debian machine - this [isn't supported](https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-log-the-same-user-on-on-the-graphical-console-and-over-xrdp-at-the-same-time), but I'd imagine it's an easy state to get into with WSL.

Please create a new user on the Debian machine **which will ONLY be used for logging in via xrdp**.

Once you've done that, log in over xrdp with your new user and report back what happens.
