### ISSUE TITLE
run the sudo systemctl status command to query the xrdp service status, the value of Active: activating (auto-restart) is not Active: activating (running).

### ISSUE THREAD

**Issue by lillianokok** [neutrinolabs/xrdp#3116]
When I run the sudo systemctl status command to query the xrdp service status, the value of Active: activating (auto-restart) is not Active: activating (running). What can I do? The XRDP version is 0.9.25.1, the ARM architecture is used, and the Openeuler system is used.
Symptom:
[root@localhost /]#systemctl status xrdp
● xrdp.service - xrdp Daemon
Loaded: loaded (/etc/systemd/system/xrdp.service; enabled; vendor preset: disabled)
Active: activating (auto-restart) (Result: exit-code) since Fri 2024-06-14 09:56:50 CST; 12s ago
Process: 847457 ExecStart=/home/spack/opt/spack/linux-openeuler22-aarch64/gcc-10.3.1/xrdp-0.9.25.1-eqalhp2rldtn7g6geu2zcfi46owhxree/sbin/xrdp (code=exited, status=1/FAILURE)
Main PID: 847457 (code=exited, status=1/FAILURE)

[root@localhost sbin]#systemctl cat xrdp.service
# /etc/systemd/system/xrdp.service
[Unit]
Description=xrdp Daemon
After=syslog.target network.target

[Service]
Type=simple
PIDFile=/var/run/xrdp.pid
ExecStart=/home/spack/opt/spack/linux-openeuler22-aarch64/gcc-10.3.1/xrdp-0.9.25.1-eqalhp2rldtn7g6geu2zcfi46owhxree/sbin/xrdp
ExecReload=
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target

**Comment by matt335672** [comment]
@lillianokok - there are service manifests for both xrdp and xrdp-sesman provided in the source distribution in the instfiles directory. Start with those and modify as appropriate for your OS, referring to [systemd.service(5)](https://www.man7.org/linux/man-pages/man5/systemd.service.5.html) and [systemd.unit(5)](https://www.man7.org/linux/man-pages/man5/systemd.unit.5.html)

Log files for the services are normally in `/var/log/xrdp.log` and `/var/log/xrdp-sesman.log`.
