### ISSUE TITLE
TLS not working in Ubuntu 12.04

### ISSUE THREAD

**Issue by HenryJacques** [neutrinolabs/xrdp#313]
Hello,

I am using:
- Ubuntu 12.04 64bits
- xrdp devel branch and X11Rdp

rdp security works fine, but when I switch to tls mstsc shows me the certificate and then loop forever...
I have also tried with FreeRDP.

This is what I get in the log (I interrupted the connexion):

> [20160204-15:35:06] [INFO ] A connection received from: 10.10.0.19 port 50642
[20160204-15:35:06] [INFO ] An established connection closed to endpoint: 10.10.0.19:50642 - socket: 11
[20160204-15:35:06] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 10
ssl_tls_accept: TLS connection accepted
ssl_tls_print_error: SSL_read: I/O error
libxrdp_force_read: error
xrdp_process_main_loop: libxrdp_process_incomming failed
got XRDP SIGPIPE(13)
got XRDP SIGPIPE(13)
ssl_tls_print_error: SSL_shutdown: I/O error
[20160204-15:35:06] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 11
xrdp_mcs_disconnect - socket closed
[20160204-15:35:06] [ERROR] Listening socket is in wrong state we terminate listener

>[20160204-15:35:19] [INFO ] A connection received from: 10.10.0.19 port 50645
[20160204-15:35:19] [INFO ] An established connection closed to endpoint: 10.10.0.19:50645 - socket: 11
[20160204-15:35:19] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 10
ssl_tls_accept: TLS connection accepted
colorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp)
postBeta2ColorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp 0xca02 15bpp 0xca03 16bpp 0xca04 24bpp)
highColorDepth 0x0010 (0x0004 4bpp 0x0008 8bpp 0x000f 15bpp 0x0010 16 bpp 0x0018 24bpp)
supportedColorDepths 0x000f (0x0001 24bpp 0x0002 16bpp 0x0004 15bpp 0x0008 32bpp)
earlyCapabilityFlags 0x07ad (0x0002 want32)
got client client connection type 0x00000007
xrdp_sec_process_mcs_data_CS_SECURITY:
  client supports 40 bit encryption
  client supports 128 bit encryption
  client supports 56 bit encryption
  client supports fips encryption
error unknown xrdp_sec_process_mcs_data tag 0xc006 size 8
error unknown xrdp_sec_process_mcs_data tag 0xc00a size 8
xrdp_sec_out_mcs_data: using no security
ssl_tls_print_error: SSL_write: I/O error
xrdp_process_main_loop: libxrdp_process_incomming failed
ssl_tls_print_error: SSL_write: Failure in SSL library (protocol error?)
ssl_tls_print_error: SSL_shutdown: Failure in SSL library (protocol error?)
[20160204-15:35:28] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 11
xrdp_mcs_disconnect - socket closed
[20160204-15:35:28] [ERROR] Listening socket is in wrong state we terminate listener

**Comment by jsorg71** [comment]
Did you create the certs?
You need to have these two files in /etc/xrdp/
key.pem
cert.pem

**Comment by HenryJacques** [comment]
@jsorg71 Yes I did create them with the correct Unix rights.
Besides when I connect with mstsc, it shows me the certificate (as untrusted because self-signed) but I can't go further....

**Comment by cmulk** [comment]
Any luck with this one? I'm having the same error after building the latest code today (3/8/2016). I get no messages after `xrdp_sec_out_mcs_data: using no security`

My works fine with RDP encryption as well, just not with TLS

My workaround for now is to revert to a build that I made on 1/5/2016 and that works fine with TLS

**Comment by HenryJacques** [comment]
@cmulk no, I tried today with latest devel and I also got the `xrdp_sec_out_mcs_data: using no security
` error....

It doesn't work with mstsc or FreeRDP, however it works with rdesktop!
Can you try that?

**Comment by cmulk** [comment]
Built again today and getting the same error, except mine does not work with rdesktop, see screenshot below:
![image](https://cloud.githubusercontent.com/assets/17730096/14062070/80b36864-f360-11e5-8aa7-2ac71a2dba33.png)

**Comment by cmulk** [comment]
Just did a bunch of compiling and testing and I think I've narrowed it down to the Jan 11 [commit](https://github.com/neutrinolabs/xrdp/commit/2893fefc9131b5dbb782bb315ce721477789da15). My builds before that work properly, everything after that has the same problems with TLS.

**Comment by HenryJacques** [comment]
@cmulk thanks for narrowing it down! I do have the same behaviour as you:
- commit ded462ab8eb4e8bd3e275961854a77dc9adb6537: it works (even if I'm not sure to understand the log `xrdp_sec_out_mcs_data: using no security`...)
- commit 2893fefc9131b5dbb782bb315ce721477789da15: it stops working

commit ded462ab8eb4e8bd3e275961854a77dc9adb6537:

> [20160330-14:59:16] [INFO ] A connection received from: 192.168.0.1 port 53552
[20160330-14:59:16] [INFO ] An established connection closed to endpoint: 192.168.0.1:53552 - socket: 11
[20160330-14:59:16] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 10
ssl_tls_accept: TLS connection accepted
ssl_tls_print_error: SSL_read: I/O error
libxrdp_force_read: error
xrdp_process_main_loop: libxrdp_process_incomming failed
got XRDP SIGPIPE(13)
got XRDP SIGPIPE(13)
ssl_tls_print_error: SSL_shutdown: I/O error
[20160330-14:59:16] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 11
xrdp_mcs_disconnect - socket closed
[20160330-14:59:16] [ERROR] Listening socket is in wrong state we terminate listener
[20160330-14:59:18] [INFO ] A connection received from: 192.168.0.1 port 53553
[20160330-14:59:18] [INFO ] An established connection closed to endpoint: 192.168.0.1:53553 - socket: 11
[20160330-14:59:18] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 10
ssl_tls_accept: TLS connection accepted
colorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp)
postBeta2ColorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp 0xca02 15bpp 0xca03 16bpp 0xca04 24bpp)
highColorDepth 0x0010 (0x0004 4bpp 0x0008 8bpp 0x000f 15bpp 0x0010 16 bpp 0x0018 24bpp)
supportedColorDepths 0x000f (0x0001 24bpp 0x0002 16bpp 0x0004 15bpp 0x0008 32bpp)
earlyCapabilityFlags 0x07ad (0x0002 want32)
got client client connection type 0x00000007
xrdp_sec_process_mcs_data_CS_SECURITY:
  client supports 40 bit encryption
  client supports 128 bit encryption
  client supports 56 bit encryption
  client supports fips encryption
error unknown xrdp_sec_process_mcs_data tag 0xc006 size 8
error unknown xrdp_sec_process_mcs_data tag 0xc00a size 8
xrdp_sec_out_mcs_data: using no security
xrdp_load_keyboard_layout:
xrdp_load_keyboard_layout: model [] variant [] layout [fr]
xrdp_caps_process_order: bitmap cache v3 supported
xrdp_caps_process_pointer: client supports new(color) cursor
xrdp_process_offscreen_bmpcache: support level 1 cache size 5242880 MB cache entries 100
xrdp_caps_process_frame_ack:
  max_unacknowledged_frame_count 2
xrdp_process_capset_window wnd_support_level 2 wnd_num_icon_caches 3 wnd_num_icon_cache_entries 12
xrdp_caps_process_codecs: nscodec codec id 1 prop len 3
xrdp_caps_process_codecs: unknown codec id 5
xrdp_caps_process_codecs: rfx codec id 3 prop len 49
yeah, up_and_running
[20160330-14:59:18] [DEBUG] xrdp_000044ee_wm_login_mode_event_00000001
xrdp:xrdp_mm [3348844852]: xrdp_mm_create: bpp 16 mcs_connection_type 7 jpeg_codec_id 0 v3_codec_id 0 rfx_codec_id 3 h264_codec_id 0
[20160330-14:59:18] [WARN ] local keymap file for 0x040c found and dosen't match built in keymap, using local keymap file
xrdp_wm_login_mode_changed: login_mode is 0
in xrdp_wm_init:
   xrdp_wm_init: no autologin / auto run detected, draw login window
xrdp:xrdp_cache [3348844875]: xrdp_cache_add_bitmap: reset detected cache_id 2
xrdp:xrdp_cache [3348844882]: xrdp_cache_add_bitmap: reset detected cache_id 1
out xrdp_wm_init:
xrdp_wm_login_mode_changed: login_mode is 1

commit 2893fefc9131b5dbb782bb315ce721477789da15:

> ssl_tls_accept: TLS connection accepted
ssl_tls_print_error: SSL_read: I/O error
libxrdp_force_read: error
xrdp_process_main_loop: libxrdp_process_incomming failed
got XRDP SIGPIPE(13)
got XRDP SIGPIPE(13)
ssl_tls_print_error: SSL_shutdown: I/O error
[20160330-15:01:01] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 11
xrdp_mcs_disconnect - socket closed
[20160330-15:01:01] [ERROR] Listening socket is in wrong state we terminate listener
[20160330-15:01:02] [INFO ] A connection received from: 192.168.0.1 port 53556
[20160330-15:01:02] [INFO ] An established connection closed to endpoint: 192.168.0.1:53556 - socket: 11
[20160330-15:01:02] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 10
ssl_tls_accept: TLS connection accepted
colorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp)
postBeta2ColorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp 0xca02 15bpp 0xca03 16bpp 0xca04 24bpp)
highColorDepth 0x0010 (0x0004 4bpp 0x0008 8bpp 0x000f 15bpp 0x0010 16 bpp 0x0018 24bpp)
supportedColorDepths 0x000f (0x0001 24bpp 0x0002 16bpp 0x0004 15bpp 0x0008 32bpp)
earlyCapabilityFlags 0x07ad (0x0002 want32)
got client client connection type 0x00000007
xrdp_sec_process_mcs_data_CS_SECURITY:
  client supports 40 bit encryption
  client supports 128 bit encryption
  client supports 56 bit encryption
  client supports fips encryption
error unknown xrdp_sec_process_mcs_data tag 0xc006 size 8
error unknown xrdp_sec_process_mcs_data tag 0xc00a size 8
xrdp_sec_out_mcs_data: using no security

**Comment by metalefty** [comment]
@cmulk @HenryJacques I identified the issue I encounter (#329) is as same as yours.  I will look at it.

**Comment by metalefty** [comment]
I built xrdp with `--enable-xrdpdebug` option and tried again. Here's the log.

[xrdp-tls.txt](https://github.com/neutrinolabs/xrdp/files/205805/xrdp-tls.txt)

**Comment by metalefty** [comment]
It looks never breaking while loop in `trans_force_read_s`.
https://github.com/neutrinolabs/xrdp/blob/devel/common/trans.c#L438

**Comment by jsorg71** [comment]
I think I know what's wrong.
The commit changes the order, call can_recv before recv.
I think that is causing the issue because SSL objects can be in the "want write" state.
I'll change it back.

**Comment by jsorg71** [comment]
See if it works now with 0655272

**Comment by metalefty** [comment]
works for me.

**Comment by HenryJacques** [comment]
Works for me too!

**Comment by cmulk** [comment]
All good for me too, thanks everyone!

**Comment by metalefty** [comment]
@HenryJacques close the issue if solved for you.

**Comment by HenryJacques** [comment]
@jsorg71 thanks again.
