### ISSUE TITLE
Wrong version in configure.ac

### ISSUE THREAD

**Issue by Caldwell-74** [neutrinolabs/xrdp#3135]
[commit 4c2a7e8](https://github.com/neutrinolabs/xrdp/commit/4c2a7e893b023892b9b3e6ecb21902cf6c326608)
pushed the version from **0.9.80** to **0.10.80** 
i might be mistaken but that seems to be a typo and it should be **0.10.0**

**Comment by metalefty** [comment]
It is not wrong be cause it was 0.9.80.

**Comment by Caldwell-74** [comment]
and where can i grab 0.10.80?
highest version available and buildable is 0.10.0-1

**Comment by Caldwell-74** [comment]
even more because senver would require it to go to 0.10.0 

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backward compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes.
Patch version MUST be reset to 0 when minor version is incremented.
https://semver.org

**Comment by metalefty** [comment]
It's fine because xrdp's version is actually not SemVer although it looks like SemVer.

**Comment by metalefty** [comment]
Also 0.10.0 is here: https://github.com/neutrinolabs/xrdp/releases/tag/v0.10.0

**Comment by Caldwell-74** [comment]
its not about 0.10.  **0**
its about 0.10.  **80**

which is set in the configure.ac

linux-vm-tools for arch require it because of this setting and arent usable atm
means the arch tutorial to setup hyper v- arch doesnt work

**Comment by metalefty** [comment]
0.10.0 has been released as a result of bump from 0.9.80.

**Comment by Caldwell-74** [comment]
but the file defines a 0.10.>> 80 << which doesnt exist
all iam trying is to fix that xD

**Comment by metalefty** [comment]
0.10.0 is defined here: https://github.com/neutrinolabs/xrdp/blob/v0.10/configure.ac

And 0.10.80 is also correct you don't need to fix it.

**Comment by metalefty** [comment]
Other OSS also introduce x.${y+1}.80 / x.${y+1}.90 versioning system.  
It doesn't need to be **FIX**ed because it is versioned as intended. Please don't try to fix that aren't wrong.

https://github.com/TigerVNC/tigervnc/commit/48408d185410113939a904d651962f6747e8902e
https://github.com/TigerVNC/tigervnc/commit/baf05ef240d3b5d3c103da9557cd9e6972cbe602

**Comment by Caldwell-74** [comment]
but packages depend on version .80 
and there is no way to get version .80 atm
i just cloned/build the current version and its .0-1

**Comment by metalefty** [comment]
If you change it to 0.10.0, 0.10.0 points to more than two different codes from the existing [0.10.0 tag](https://github.com/neutrinolabs/xrdp/tree/v0.10.0). This is absolutely unacceptable!


I don't get the *packages* you mention here. The latest version we release is 0.10.0. It is natural the newest version you can find is 0.10.0

**Comment by Caldwell-74** [comment]
after git clone https://github.com/neutrinolabs/xorgxrdp
and ./bootstrap
the ./configure fails with this message

![image](https://github.com/neutrinolabs/xrdp/assets/115591472/bcd6b1d9-866f-4bff-8587-cda0c5ed4283)

**Comment by metalefty** [comment]
Then, how does the change you made in [your pull request](https://github.com/neutrinolabs/xrdp/pull/3136) help? I think it doesn't.

xorgxrdp tries to find xrdp 0.10.80, you shouldn't change the version from 0.10.80 to 0.10.0. If you change it to 0.10.0, xorgxrdp is never able to find xrdp 0.10.80. Isn't it a simple thing?  You must try xorgxrdp 0.10.1 (or 0.10.0)  if you're using xrdp 0.10.0.

Anyway, your pull request doesn't make sense to resolve your issue.
