### ISSUE TITLE
File transfer from Windows encountered: "Error when getting information for file '/test.txt' "

### ISSUE THREAD

**Issue by mega-optimus** [neutrinolabs/xrdp#3163]
### xrdp version

0.10.0

### Detailed xrdp version, build options

~~~
xrdp 0.10.0
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2024 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:


  Compiled with OpenSSL 3.0.2 15 Mar 2022
~~~

### Operating system & version

Linux Mint 21.3

### Installation method

git clone & make install

### Which backend do you use?

xorgxrdp 0.10.1

### What desktop environment do you use?

Xfce / Cinnamon

### Environment xrdp running on

Physical Machine, RTX 4080 Super

### What's your client?

Windows 7 mstsc.exe

### Area(s) with issue?

Clipboard, File transfer / drive redirection

### Steps to reproduce

I built from source & installed the latest xrdp & xorgxrdp, then login with XFCE, copy test.txt from Windows desktop, paste on Linux desktop.

### ✔️ Expected Behavior

Paste should succeed.

### ❌ Actual Behavior

Failed with error.
![Untitled](https://github.com/user-attachments/assets/8c94586f-7fb2-4cb8-9ec3-aaceb6fb4835)

### Anything else?

[xrdp.log](https://github.com/user-attachments/files/16251335/xrdp.log)
[xrdp-sesman.log](https://github.com/user-attachments/files/16251377/xrdp-sesman.log)
[xorg.conf.txt](https://github.com/user-attachments/files/16251545/xorg.conf.txt)

**Comment by metalefty** [comment]
I remember this is regression #3082.
Could you try to apply dcaa31ef1614f40c5f2c059badc80366f0f7af10?

**Comment by mega-optimus** [comment]
> I remember this is regression #3082. Could you try to apply [dcaa31e](https://github.com/neutrinolabs/xrdp/commit/dcaa31ef1614f40c5f2c059badc80366f0f7af10)?

Hi, I actually downloaded the tarball from release page [May 10th], not git cloned the latest development. The regression you mentioned was introduced on May 21st, which shouldn't have affected my build.

**Comment by matt335672** [comment]
@mega-optimus - that fix is scheduled for the next release of v0.10:-

https://github.com/neutrinolabs/xrdp/wiki/NEWS (under Bug Fixes)

**Comment by mega-optimus** [comment]
Hi, I realized I followed the README in tarball instead of https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8. Specifically, `./configure --enable-fuse --enable-mp3lame --enable-pixman`  & `sudo ln -s /usr/local/sbin/xrdp{,-sesman} /usr/sbin` were not followed. 

After following these instructions, and enable drive sharing in mstsc.exe, then I git cloned the latest development version of xrdp & xorgxrdp, compiled & installed, still file paste was not functional, with following message: 
![Untitled](https://github.com/user-attachments/assets/3e5f9a17-d46c-434d-9394-93643cefd8a3)

**Comment by matt335672** [comment]
Thanks @mega-optimus - I'll have a more detailed look at this.

Can you provide the following?
- Output of `xrdp -v`
- Output of `git show HEAD | head -5` when you're in the xrdp directory.
- Output of `grep -i ^fusemountname /etc/xrdp/sesman.ini`
- A chansrv log file when the error occurs. **To make sure there are no problems with stale connections or hung-over FUSE mounts, please reboot first** . Then restart xrdp & sesman (if applicable) and log in. The log is then in `/home/allen/.local/share/xrdp-chansrv.$D.log` where $D is the display number (probably 10 or 11). You can check the time on this is current if you're not sure which file.

Please let me know if there are any problems or difficulties in obtaining any of this.

**Comment by mega-optimus** [comment]
> Thanks @mega-optimus - I'll have a more detailed look at this.

Thanks @matt335672 for the detailed instructions!

> 
> Can you provide the following?
> 
> * Output of `xrdp -v`

xrdp 0.10.80
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2024 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-fuse
      --enable-mp3lame
      --enable-pixman
      --enable-jpeg
      --enable-ibus

  Compiled with OpenSSL 3.0.2 15 Mar 2022

> * Output of `git show HEAD | head -5` when you're in the xrdp directory.

commit b6407a9bf945d14f54b3e6d83ad8b9f0f314eeb4
Merge: 2a8eea90 52dd88b5
Author: matt335672 <30179339+matt335672@users.noreply.github.com>
Date:   Mon Jul 15 09:02:32 2024 +0100

> * Output of `grep -i ^fusemountname /etc/xrdp/sesman.ini`

FuseMountName=thinclient_drives

> * A chansrv log file when the error occurs. **To make sure there are no problems with stale connections or hung-over FUSE mounts, please reboot first** . Then restart xrdp & sesman (if applicable) and log in. The log is then in `/home/allen/.local/share/xrdp-chansrv.$D.log` where $D is the display number (probably 10 or 11). You can check the time on this is current if you're not sure which file.
> 
> Please let me know if there are any problems or difficulties in obtaining any of this.

i cleared the directory before rebooting, this is the only file generated afterwards.
[xrdp-chansrv.10.log](https://github.com/user-attachments/files/16271664/xrdp-chansrv.10.log)

**Comment by mega-optimus** [comment]
Thanks @matt335672  @metalefty !
After checking xrdp-chansrv.10.log, the root cause is thinclient_drives failing to mount.
This is due to my historical attempt's left-over. 
Previously after reading some other web post, I believed there needs to be a **.clipboard** directory inside **thinclient_drives** thus I created one.
After deleting this **.clipboard** directory, it works like a charm ! :-)
Btw, drive sharing is not needed for copy & paste to work.

**Comment by matt335672** [comment]
Thanks for getting back to us
