### ISSUE TITLE
Build failed with rfxencode_dwt_shift_rem_sse2.c:41:26: error: '__m128i_u' undeclared

### ISSUE THREAD

**Issue by niiiksh** [neutrinolabs/xrdp#3166]
### xrdp version

0.10.0

### Detailed xrdp version, build options

~~~
Paste the result between `~~~`.  Please DO NOT remove `~~~`!
~~~

### Operating system & version

Debian 8.11

### Installation method

git clone & make install

### Which backend do you use?

xorgrdp

### What desktop environment do you use?

GNOME

### Environment xrdp running on

physical machine

### What's your client?

Microsoft Remote Desktop for macOS

### Area(s) with issue?

Compile error

### Steps to reproduce

Download with wget xrdp 0.10.0, bootstrap, configure and make

### ✔️ Expected Behavior

build finishes successfully

### ❌ Actual Behavior

make[5]: Entering directory '/home/nikita/soft/rdp10/xrdp/librfxcodec/src'
  CC       rfxencode_dwt_shift_rem_sse2.lo
rfxencode_dwt_shift_rem_sse2.c: In function 'rfx_encode_dwt_shift_rem_vert_lv1_u8':
rfxencode_dwt_shift_rem_sse2.c:41:26: error: '__m128i_u' undeclared (first use in this function)
         _mm_loadl_epi64((__m128i_u const *)(ic + (_offset) * 64)), \
                          ^
rfxencode_dwt_shift_rem_sse2.c:156:9: note: in expansion of macro 'IC_LL0_U8V'
         IC_LL0_U8V(x2nv, 0);
         ^
rfxencode_dwt_shift_rem_sse2.c:41:26: note: each undeclared identifier is reported only once for each function it appears in
         _mm_loadl_epi64((__m128i_u const *)(ic + (_offset) * 64)), \
                          ^
rfxencode_dwt_shift_rem_sse2.c:156:9: note: in expansion of macro 'IC_LL0_U8V'
         IC_LL0_U8V(x2nv, 0);
         ^
rfxencode_dwt_shift_rem_sse2.c:41:36: error: expected ')' before 'const'
         _mm_loadl_epi64((__m128i_u const *)(ic + (_offset) * 64)), \
                                    ^
rfxencode_dwt_shift_rem_sse2.c:156:9: note: in expansion of macro 'IC_LL0_U8V'
         IC_LL0_U8V(x2nv, 0);
         ^
rfxencode_dwt_shift_rem_sse2.c:41:36: error: expected ')' before 'const'
         _mm_loadl_epi64((__m128i_u const *)(ic + (_offset) * 64)), \
                                    ^
rfxencode_dwt_shift_rem_sse2.c:157:9: note: in expansion of macro 'IC_LL0_U8V'
         IC_LL0_U8V(x2n1v, 1);
         ^
rfxencode_dwt_shift_rem_sse2.c:41:36: error: expected ')' before 'const'
         _mm_loadl_epi64((__m128i_u const *)(ic + (_offset) * 64)), \
                                    ^
rfxencode_dwt_shift_rem_sse2.c:158:9: note: in expansion of macro 'IC_LL0_U8V'
         IC_LL0_U8V(x2n2v, 2);
         ^
rfxencode_dwt_shift_rem_sse2.c:41:36: error: expected ')' before 'const'
         _mm_loadl_epi64((__m128i_u const *)(ic + (_offset) * 64)), \
                                    ^
rfxencode_dwt_shift_rem_sse2.c:166:13: note: in expansion of macro 'IC_LL0_U8V'
             IC_LL0_U8V(x2n1v, 2 * n + 1);
             ^
rfxencode_dwt_shift_rem_sse2.c:41:36: error: expected ')' before 'const'
         _mm_loadl_epi64((__m128i_u const *)(ic + (_offset) * 64)), \
                                    ^
rfxencode_dwt_shift_rem_sse2.c:167:13: note: in expansion of macro 'IC_LL0_U8V'
             IC_LL0_U8V(x2n2v, 2 * n + 2);
             ^
rfxencode_dwt_shift_rem_sse2.c:41:36: error: expected ')' before 'const'
         _mm_loadl_epi64((__m128i_u const *)(ic + (_offset) * 64)), \
                                    ^
rfxencode_dwt_shift_rem_sse2.c:174:9: note: in expansion of macro 'IC_LL0_U8V'
         IC_LL0_U8V(x2n1v, 63);
         ^
Makefile:553: recipe for target 'rfxencode_dwt_shift_rem_sse2.lo' failed
make[5]: *** [rfxencode_dwt_shift_rem_sse2.lo] Error 1
make[5]: Leaving directory '/home/nikita/soft/rdp10/xrdp/librfxcodec/src'
Makefile:572: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/nikita/soft/rdp10/xrdp/librfxcodec/src'
Makefile:454: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/nikita/soft/rdp10/xrdp/librfxcodec'
Makefile:360: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/nikita/soft/rdp10/xrdp/librfxcodec'
Makefile:491: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/nikita/soft/rdp10/xrdp'
Makefile:422: recipe for target 'all' failed
make: *** [all] Error 2
Press any key to continue...

**Comment by niiiksh** [comment]
Replace __m128i_u with __m128i (remove _u) fixes problem.
I don't know if it is a good solution but seems like a workaround for now.

**Comment by jsorg71** [comment]
I created https://github.com/neutrinolabs/librfxcodec/pull/70
for this.

**Comment by metalefty** [comment]
Closed
