### ISSUE TITLE
Add release tags please

### ISSUE THREAD

**Issue by barrydegraaff** [neutrinolabs/xrdp#318]
Would it be possible to provide release tags for new releases,

https://github.com/neutrinolabs/xrdp/releases

last tags where added in 2014. I like to build this software from source, but I do also like to use a 

   git checkout tag

So I can use a `stable` release point, right now, this is a bit difficult.

Thanks for considering, Barry

**Comment by itamarjp** [comment]
theres no new versions released since 2014, because of that you're not seeing new tags, when we release a new one we will tag it.
