### ISSUE TITLE
Status of XRDP Audio redirection and use of Pulseaudio

### ISSUE THREAD

**Issue by bmullan** [neutrinolabs/xrdp#321]
On AWS all linux virtual servers do not have a sound card present.   On those servers there is only an snd-dummy device.

When I use guacamole and connect with xrdp/rdp to a desktop environment installed on one of those servers _I can see via pavucontrol or the default sound app that when audio is playing using the snd-dummy device the sound-level bar moves as expected for both input & output_.

When I install & use x2go on that server & with my local client audio works but x2go uses x11 port forwarding to/from the client/server for sound.   

However, x2go uses pulseaudio to enable that but it at least tells me that pulseaudio can pickup & redirect the audio from the AWS linux server's snd-dummy device.

I've tried building xrdp with the option **--withsound**.   That still doesn't seem to get xrdp & its pulseaudio support working with AWS servers that only have an snd-dummy sound device?

There is an old post asking about pulseaudio on the xrdp issues list:  https://github.com/neutrinolabs/xrdp/issues/5.    But that post is years old now.

So I am wondering what the current status of xrdp pulseaudio support is?  _Should it be capable of picking up sound from the snd-dummy device and redirect it?_

thanks...

**Comment by metalefty** [comment]
I think xrdp sound needs hand installation.  I've never tried xrdp audio redirection on AWS but  I suppose no hardware sound device will not be the problem.  Audio redirection works for me on KVM virtual machine with no sound device attached. xrdp sink behaves pulseaudio virtual 
sound device.

![2016-02-17 2 32 35](https://cloud.githubusercontent.com/assets/941609/13084909/fd8c852e-d51e-11e5-97ea-cc731dc15536.png)
I wrote an article how to install xrdp  with audio redirection. It is written in Japanese but you will be able to understand at least command line instructions.
http://w.vmeta.jp/tdiary/20140918.html

**Comment by bmullan** [comment]
Thanks I'll take a look & see if I can follow it!

**Comment by bmullan** [comment]
@metalefty  Ok I looked at your link (the one in japanese) and it seems similar to several others I've found including this one:

https://github.com/PKRoma/xrdp/blob/master/sesman/chansrv/pulse/pulse-notes.ubuntu.txt

However, I think all of these "guides" that I have found there is 1 step that always is confusing (and they all say the same text..!

I get to the point of executing the command:
> dpkg-buildpackage -rfakeroot -uc -b

then your guide & the other URL above say:

> edit Makefile and point PULSE_DIR to ~/pulseaudio<version> dir

Now I understatnd that they Makefile both are referring to is the xrdp Makefile for Pulse which for xrdp v0.9.0 is found in   /X11RDP-o-Matic/xrdp-0.9.0+master/sesman/chansrv/pulse

I make that editing change to the PULSE_DIR to point it to where my  new pulseaudio (pulseaudio v6.0) was built

But then BOTH your guide & the one above simply say:

> run make

I am assuming everyone means run "make" in the directory...
/X11RDP-o-Matic/xrdp-0.9.0+master/sesman/chansrv/pulse

That has the Makefile that I edited but that fails with the following:

$ make
cc -Wall -O2 -I/tmp/pulseaudio/pulseaudio-6.0 -I/tmp/pulseaudio/pulseaudio-6.0/src -DHAVE_CONFIG_H -fPIC   -c -o module-xrdp-sink.o module-xrdp-sink.c
In file included from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/macro.h:312:0,
                 from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/cpu-x86.h:25,
                 from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/cpu.h:23,
                 from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/core.h:25,
                 from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/sink.h:35,
                 from module-xrdp-sink.c:52:
module-xrdp-sink.c: In function ‘sink_update_requested_latency_cb’:
module-xrdp-sink.c:174:12: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘pa_usec_t {aka long unsigned int}’ [-Wformat=]
     pa_log("1 block_usec %d", u->block_usec);
            ^
/tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/log.h:130:91: note: in definition of macro ‘pa_log_error’
 #define pa_log_error(...)  pa_log_level_meta(PA_LOG_ERROR,  __FILE__, __LINE__, __func__, __VA_ARGS__)
                                                                                           ^
module-xrdp-sink.c:174:5: note: in expansion of macro ‘pa_log’
     pa_log("1 block_usec %d", u->block_usec);
     ^
module-xrdp-sink.c:179:22: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘pa_usec_t {aka long unsigned int}’ [-Wformat=]
         pa_log_debug("2 block_usec %d", u->block_usec);
                      ^
/tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/log.h:126:91: note: in definition of macro ‘pa_log_debug’
 #define pa_log_debug(...)  pa_log_level_meta(PA_LOG_DEBUG,  __FILE__, __LINE__, __func__, __VA_ARGS__)
                                                                                           ^
module-xrdp-sink.c: In function ‘process_render’:
module-xrdp-sink.c:393:18: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘pa_usec_t {aka long unsigned int}’ [-Wformat=]
     pa_log_debug("process_render: u->block_usec %d", u->block_usec);
                  ^
/tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/log.h:126:91: note: in definition of macro ‘pa_log_debug’
 #define pa_log_debug(...)  pa_log_level_meta(PA_LOG_DEBUG,  __FILE__, __LINE__, __func__, __VA_ARGS__)
                                                                                           ^
module-xrdp-sink.c: In function ‘thread_func’:
module-xrdp-sink.c:443:20: error: too many arguments to function ‘pa_rtpoll_run’
         if ((ret = pa_rtpoll_run(u->rtpoll, TRUE)) < 0) {
                    ^
In file included from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/source.h:42:0,
                 from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/core.h:50,
                 from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/sink.h:35,
                 from module-xrdp-sink.c:52:
/tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/rtpoll.h:61:5: note: declared here
 int pa_rtpoll_run(pa_rtpoll *f);
     ^
In file included from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/macro.h:312:0,
                 from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/cpu-x86.h:25,
                 from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/cpu.h:23,
                 from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/core.h:25,
                 from /tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/sink.h:35,
                 from module-xrdp-sink.c:52:
module-xrdp-sink.c: In function ‘module_xrdp_sink_LTX_pa__init’:
module-xrdp-sink.c:527:18: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘pa_usec_t {aka long unsigned int}’ [-Wformat=]
     pa_log_debug("3 block_usec %d", u->block_usec);
                  ^
/tmp/pulseaudio/pulseaudio-6.0/src/pulsecore/log.h:126:91: note: in definition of macro ‘pa_log_debug’
 #define pa_log_debug(...)  pa_log_level_meta(PA_LOG_DEBUG,  __FILE__, __LINE__, __func__, __VA_ARGS__)
                                                                                           ^
**<builtin>: recipe for target 'module-xrdp-sink.o' failed**
make: *** [module-xrdp-sink.o] Error 1

I guess I'm not smart enough to understand what the above failure means or how I resolve it in order to get the following 2 files built correctly:

module-xrdp-sink.so
module-xrdp-source.so

If anyone has any ideas I can try thanks...

**Comment by metalefty** [comment]
It looks xrdp's pulseaudio module is not compatible with pulseaudio 6.0 or later.
The easiest workaround is to use pulseaudio 5.0 or 4.0.

@jsorg71,
can you look at this? I haven't investigated deeply yet but we simply need to care the number of arguments depends of pulseaudio version. Like this pseudo patch.
```
diff --git a/sesman/chansrv/pulse/module-xrdp-sink.c b/sesman/chansrv/pulse/module-xrdp-sink.c
index f56644b..42c9332 100644
--- a/sesman/chansrv/pulse/module-xrdp-sink.c
+++ b/sesman/chansrv/pulse/module-xrdp-sink.c
@@ -440,7 +440,11 @@ static void thread_func(void *userdata) {
             pa_rtpoll_set_timer_disabled(u->rtpoll);
         }
 
+#if PULSEAUDIO >= 6.0
+        if ((ret = pa_rtpoll_run(u->rtpoll)) < 0) {
+#else
         if ((ret = pa_rtpoll_run(u->rtpoll, TRUE)) < 0) {
+#endif
             goto fail;
         }
 
diff --git a/sesman/chansrv/pulse/module-xrdp-source.c b/sesman/chansrv/pulse/module-xrdp-source.c
index 5240960..f12af80 100644
--- a/sesman/chansrv/pulse/module-xrdp-source.c
+++ b/sesman/chansrv/pulse/module-xrdp-source.c
@@ -339,7 +339,11 @@ static void thread_func(void *userdata) {
         }
 
         /* Hmm, nothing to do. Let's sleep */
+#if PULSEAUDIO >= 6.0
+        if ((ret = pa_rtpoll_run(u->rtpoll)) < 0)
+#else
         if ((ret = pa_rtpoll_run(u->rtpoll, TRUE)) < 0)
+#endif
             goto fail;
 
         if (ret == 0)
```

**Comment by bmullan** [comment]
I fixed my problem.  There is one function referenced in the xrdp pulse
files pa_rtpollrun () incorrectly.  Actually the reference occurs in 2
files.  If you remove the 2nd parameter in both (the TRUE) then make
succeeds &  the .so files for xrdp pulseaudio get built ok.  Sorry I'm not
at my computer now as its 2am here or I'd give you more info.

**Comment by bmullan** [comment]
Also ... fixing that function reference I successfully built xrdp pulse for
both pulseaudio v6.0 and v8.0...

**Comment by metalefty** [comment]
I could fix the build pulseaudio 6.0 or higher by my own. I'll make a pull request later.

**Comment by bmullan** [comment]
retested today on AWS server (ubuntu 15.10) which has ubuntu-mate
installed, only snd-dummy but with the fix to pa_rtpollrun() function calls
in xrdp to eliminate the extra parameter "TRUE"... sound now works.

Next up I have to figure out why clipboard doesn't work :-)

Thanks and glad I could get the sound working by figuring out that function
error.

Brian

**Comment by metalefty** [comment]
My pull request has been merged into devel branch. Can be closed.

**Comment by metalefty** [comment]
@bmullan close?

**Comment by metalefty** [comment]
Fix merged, closing.
