### ISSUE TITLE
remotefx need jpeg

### ISSUE THREAD

**Issue by moobyfr** [neutrinolabs/xrdp#322]
Hi
the switch `--enable-rfx` needs to require `--enable-jpeg`:
If not, the compilation is fine, but when connecting with a rfx-enable client (with `xfreerdp --rfx` for example) the screen will remain blue, and `xrdp-sesman` will spawn `rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0` forever...

**Comment by mancaveman** [comment]
Could this be related to neutrinolabs/librfxcodec#2 instead? The submodule in xrdp hasn't been updated to include the fix yet and the symptoms you describe are the same I was getting.
Maybe including the jpeg codec provides a fallback path for xfreerdp after the rfx codec init fails.

If so then a build without the jpeg codec should work after doing
cd librfxcodec
git pull origin master

**Comment by moobyfr** [comment]
I don't think it's related because I use the devel branch which incluse the patch too

**Comment by moobyfr** [comment]
I must verify , my test server use already the patch as I use the devel branch for librfc and xorgxrdp.

**Comment by metalefty** [comment]
Anything new? I also looking at this issue. xrdp takes high network bandwidth usage while `rdpDeferredUpdateCallback: ` be spawned.  I'm using librfxcodec 3f137a6, xrdp cdb967c.

**Comment by mancaveman** [comment]
FWIW I've since checked and I can confirm that I did not have the jpeg codec enabled in my build when I fixed the rfx codec so there shouldn't be a direct connection between the two unless there's been a weird regression since then in either of the projects.
