### ISSUE TITLE
Can't load login background

### ISSUE THREAD

**Issue by sousaaguilherme** [neutrinolabs/xrdp#3244]
### xrdp version

0.9.22.1-2

### Detailed xrdp version, build options

~~~
xrdp 0.9.22.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-redhat-linux-gnu
      --host=x86_64-redhat-linux-gnu
      --program-prefix=
      --disable-dependency-tracking
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/sbin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --sharedstatedir=/var/lib
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-fuse
      --enable-pixman
      --enable-painter
      --enable-vsock
      --enable-ipv6
      --with-socketdir=/run/xrdp
      --with-imlib2
      build_alias=x86_64-redhat-linux-gnu
      host_alias=x86_64-redhat-linux-gnu
      CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 1.1.1k  FIPS 25 Mar 2021

~~~

### Operating system & version

Centos 8 Stream

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

Xvnc

### What desktop environment do you use?

XFCE

### Environment xrdp running on

VM

### What's your client?

Microsoft RDP Client

### Area(s) with issue?

Authentication

### Steps to reproduce

I have the following settings in xrdp.ini

ls_background_image=/usr/share/xrdp/background.jpg

### ✔️ Expected Behavior

Background to be loaded

### ❌ Actual Behavior

background not loaded and I see this in the logs:
~~~
[INFO ] Login background not loaded as client has requested PERF_DISABLE_WALLPAPER
~~~

### Anything else?

This happened after upgrading xrdp.

I had both the logo and background with bmp, but after the upgrade neither the background or logo worked.

I also saw this error regarding the logo:
[ERROR] Error loading /usr/share/xrdp/logo.bmp [Unknown error]

So I changed both to jpg. That solved the problem with the logo, but the background still doesn't work showing:
~~~
[INFO ] Login background not loaded as client has requested PERF_DISABLE_WALLPAPER
~~~

**Comment by metalefty** [comment]
Upgrading from which version to 0.9.22.1-2?

**Comment by sousaaguilherme** [comment]
From 0.9.17

**Comment by metalefty** [comment]
BTW,  this indicates the client requests not to show the background image.  So the client does not want to show a background image, so the background is not showing. It is working as intended pretty normally.

```
[INFO ] Login background not loaded as client has requested PERF_DISABLE_WALLPAPER
```

**Comment by sousaaguilherme** [comment]
Well, I did no such configuration on the client, and before it always showed. Is there a way to force it to show?

Best regards

**Comment by metalefty** [comment]
Could you tell me again about your client? The question in the issue form asked you to answer the following information but you just answered " Microsoft RDP Client".

> What's your client?
> If you issue occurs with specific clients, tell us the client app name, app version client os version and platform.

![image](https://github.com/user-attachments/assets/31f5b754-9961-40f2-8d5f-cbeea0b1e364)

**Comment by metalefty** [comment]
Because I think definitely there must be such a configuration.

![image](https://github.com/user-attachments/assets/ac1281c4-8aac-465d-8dc6-a9fcca4d0bd3)

**Comment by sousaaguilherme** [comment]
I'm using mstsc with mremoteng, and it seems to have an option for disabling desktop background as you stated. 

The saved connection didn't had desktop background enabled (now or before), but it seems that 0.9.17 didn't took that into account so I just assumed it wasn't working. After changing the connection to enable Desktop background it worked.

Sorry for the inconvenience; I will close the issue

**Comment by sousaaguilherme** [comment]
Solved 👍

**Comment by metalefty** [comment]
Glad to hear that.
