### ISSUE TITLE
20.04.1-Ubuntu xrdp 0.9.26 crashed

### ISSUE THREAD

**Issue by 476225048** [neutrinolabs/xrdp#3251]
### xrdp version

0.9.26

### Detailed xrdp version, build options

~~~
ysp#/usr/local/sbin/xrdp -v
Argument 0 - /usr/local/sbin/xrdp
Argument 1 - -v
xrdp 0.9.26
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2024 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-neutrinordp
      --enable-fuse
      -enable-mp3lame
      --enable-pixman
      --enable-devel-all

  Compiled with OpenSSL 1.1.1f  31 Mar 2020
~~~

### Operating system & version

#129~20.04.1-Ubuntu SMP Wed Aug 7

### Installation method

Doesn't matter

### Which backend do you use?

xorgxrdp

### Environment xrdp running on

VM

### What's your client?

Windows 10 

### Area(s) with issue?

Crashes such as segfault

### Steps to reproduce

Windows 10 directly connect the Ubuntu is OK，but I use the xrdp proxy，then xrdp on Ubuntu crashed，the detail is:
step one: 
Windows 10  ------------->Ubuntu [xrdp 0.9.26] ，everything is ok；
step two:
Win 10<-------------->centos[rdp proxy]<-------------->Ubuntu [xrdp 0.9.26]
I run a xrdp proxy on centos, the version lower than 0.9.6，then the xrdp 0.9.26 on Ubuntu where crashed after connected，Even，I can saw the graphic and move the mouse；
step three:
The rdp proxy is modified by xrdp ,  the version lower than 0.9.6

**Comment by 476225048** [comment]
![ubuntu xrdp崩溃的日志](https://github.com/user-attachments/assets/2055b3c2-bc71-4dc1-b484-f55f243a44e5)
xrdp crashed

**Comment by 476225048** [comment]
Segmentation fault.
in xrdp_cache_add_bitmap at xrdp_cache.c : 350
             if ((lbm != NULL) && COMPARE_WITH_CRC32(lbm, bitmap))
xrdp_painter_copy

**Comment by matt335672** [comment]
Thanks for this @476225048 

It looks like the value in `lbm` is bad. This could be happening in a variety of ways.

I'd like to try to reproduce it here. Can you tell me more about the proxy? Are you using xrdp for this or something else? Also I don't understand what you mean by 'the version lower than 0.9.6'. 

Thanks.

**Comment by matt335672** [comment]
No response from OP - closing.
