### ISSUE TITLE
How to isolate redirected folders from non-owners?

### ISSUE THREAD

**Issue by x09** [neutrinolabs/xrdp#3264]
### xrdp version

0.10.1

### Detailed xrdp version, build options

~~~
xrdp 0.10.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2024 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-alt-linux
      --host=x86_64-alt-linux
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/sbin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/lib
      --localstatedir=/var
      --sharedstatedir=/var/lib
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --disable-dependency-tracking
      --disable-silent-rules
      --without-included-gettext
       #--disable-static
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-pixman
      --with-imlib2=yes
      --with-freetype2=yes
      --enable-mp3lame
      --enable-vsock
      --enable-rdpsndaudin
      --enable-fdkaac
      --with-systemdsystemunitdir=/lib/systemd/system
      build_alias=x86_64-alt-linux
      host_alias=x86_64-alt-linux
      target_alias= #--disable-static
      CFLAGS=-pipe -frecord-gcc-switches -Wall -g -O2 -I/usr/include/libdrm -Wno-error=int-to-pointer-cast
      CXXFLAGS=-pipe -frecord-gcc-switches -Wall -g -O2 -I/usr/include/libdrm -Wno-error=int-to-pointer-cast

  Compiled with OpenSSL 1.1.1w  11 Sep 2023
~~~

### Operating system & version

ALT Server 10.2

### Installation method

dnf / apt / zypper / pkg / etc

### What desktop environment do you use?

MATE

### What's your client?

windows - mstsc, linux - remmina, myconnector

### Area(s) with issue?

File transfer / drive redirection

### Steps to reproduce

sesmain.ini

> 
> FuseMountName=/media/shared/%U/thinclient_drives
> FileUmask=077
> 

```
# mkdir /media/shared/
# chmod 777  /media/shared/
# systemctl restart xrdp xrd-sesman
```

connect to XRDP server with folder redirection
test users: _domainuser1_, _domainuser2_, _domainuser3_,...

/media/shared:
> total 16
> drwxr-xr-x 4 root        root         4096 Oct  1 12:26 ../
> drwxr-xr-x 3 domainuser1 domain users 4096 Oct  1 16:06 domainuser1/
> drwxr-xr-x 3 domainuser2 domain users 4096 Oct  1 16:07 domainuser2/
> drwxr-xr-x 3 domainuser3 domain users 4096 Oct  1 16:09 domainuser3/
> drwxrwxrwx 4 root        root         4096 Oct  1 16:07 ./
> 
domainuser1 can see in file manager
![изображение](https://github.com/user-attachments/assets/9abf9c73-54d7-4588-bf9c-7533735ddf74)

If few users are logged in, then folders thinclient_drives are visible to everyone (but without access - see pic below)

![изображение](https://github.com/user-attachments/assets/aba4a1c4-a936-4e4c-8a18-79ce0f47fcd0)

I tried play with permission like as
chmod og= /media/shared/domainuser1 
but nothing

if define FuseMountName to  other mointpoint
> FuseMountName=/run/media/%U/thinclient_drives

get 

> Oct 01 15:45:19 host-16.test.alt xrdp-chansrv[8044]: [ERROR] mkdir /run/media/domainuser2/thinclient_drives failed (Permission denied)

because owner root

```
ll /run/media/ | grep domainuser2
drwxr-xr-x  4 root root   80 окт  1 16:16 domainuser2/ 
```

### ✔️ Expected Behavior

I want users to not see other thinclient_drives in the file file explorer (caja).

### Anything else?

I can't mount it to my home directory because it's on an nfs server (https://github.com/neutrinolabs/xrdp/issues/1048)

**Comment by matt335672** [comment]
The simplest way to do this is to use:-

```
FuseMountName=/run/user/%u/thinclient_drives
```

Only the user has access to this directory, so only the user will see the mount.

This does have the disadvantage that the user can't see the mount in the file manager. Users will need to add a favourites in the left-hand side of the file manager.

I can't see an easy way round this, as `fuse.mount` does not seem to support the `x-gvfs-show` option used by `gvfs-udisks2-volume-monitor`.

More information here:-

https://gitlab.gnome.org/GNOME/gvfs/raw/master/monitor/udisks2/what-is-shown.txt

**Comment by x09** [comment]
I make a workaround.. i use bookmarks for Caja, Thunar file manager


end of startwm.sh file

```
user_id=$(id -u)

# Клиентские диски
rdp_title="Client drives" 

desktop_path=$(xdg-user-dir DESKTOP)

if [[ ! -h "$desktop_path/$rdp_title" ]]; then
        ln -s /run/user/${user_id}/thinclient_drives "$desktop_path/$rdp_title" 
fi

if ! grep -q thinclient_drives $HOME/.config/gtk-3.0/bookmarks ; then
        echo "file:///run/user/${user_id}/thinclient_drives ${rdp_title}" >> $HOME/.config/gtk-3.0/bookmarks
fi

wm_start
fusermount -u /run/user/${user_id}/thinclient_drives
exit 1
```

![изображение](https://github.com/user-attachments/assets/64553a05-ac43-4269-9c68-e8a7db3c5a99)

**Comment by matt335672** [comment]
Nice!

I think that's the best you can do for now.
