### ISSUE TITLE
Clipboard and drive redirection are broken when "Printers" is selected as a shared local resource

### ISSUE THREAD

**Issue by therevoman** [neutrinolabs/xrdp#327]
This but is just combining #308 and #312 
When using the Microsoft Remote Desktop Connection Client.  
If "Printers" is selected as a local shared resource under the "Local Resources" tab it somehow breaks both the clipboard and drive redirection through thinclient_drives.  

It feels like something that could be addressed server side, or is not being account for on the server side.  Hoping for a fix.

**Comment by metalefty** [comment]
I can also reproduce this.

**Comment by therevoman** [comment]
This appears to be fixed in the latest master branch.

**Comment by gkyildirim** [comment]
I've tried with the latest commit (7a7445fefd9a61535881ceedf5ed82febb52d2dc).  

 If you enable printer redirection in mstsc.exe (Win 10) drives are not redirected.

**Comment by avolkov-astra** [comment]
It can be reproduced with 0.9.16. Please reopen.

**Comment by avolkov-astra** [comment]
Drives are still not redirected with 0.9.16 if printer redirection is enabled. Please reopen.

**Comment by metalefty** [comment]
Thanks for the feedback. Reopened. 

BTW, xrdp doesn't support printer redirection so far. So enabling printer redirection takes no effect. Also disabling printer redirection has no disadvantage. Turn it off.

Anyway, the issue should be fixed.
