### ISSUE TITLE
Move to FUSE3

### ISSUE THREAD

**Issue by matt335672** [neutrinolabs/xrdp#3274]
See [Debian BTS #1048879](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1084479)

@Natureshadow / @alexmyczko - would one of you like to add a reference to this issue to the Debian bug tracker? Thanks.

**Comment by metalefty** [comment]
Thanks, v0.10 needs to move to fuse3 then.

**Comment by matt335672** [comment]
Maybe:-
1) This is being driven from a Debian issue. If necessary they can back-port a patch to 0.10
2) it may depend on how quickly we can get another version together.

Regarding 2), I'd like to get on with integrating some of the other stuff we've spoken about ASAP. I'll ask Nex again what I can do to get started on this. There's also #3270 - I'll make inquiries as to what's happening there.

**Comment by alexmyczko** [comment]
I think I would wait for a release fixing this, there is still some time until the freeze https://release.debian.org/testing/freeze_policy.html

**Comment by matt335672** [comment]
Hi @alexmyczko 

Thanks for getting back to me.

Can you give me some context here? I'm not a Debian developer.

1) If I understand correctly, you are hoping to get a FUSE3 version of xrdp into Trixie(?)
2) I can't see any dates on the page you've linked. What does 'still some time' mean? A month? Three months?

Thanks.

**Comment by alexmyczko** [comment]
1. Yes that would be the hope

2. Because it has to be done yet, most likely until end of the year there won't be a freeze, and then a freeze announcement which would give about another 6 months...

**Comment by matt335672** [comment]
Thanks @alexmyczko - that's very useful.
