### ISSUE TITLE
Trying to improve/debug audio redirection to client

### ISSUE THREAD

**Issue by sputnick-dev** [neutrinolabs/xrdp#3277]
### xrdp version

0.9.21.1

### Detailed xrdp version, build options

~~~
Paste the result between `~~~`.  Please DO NOT remove `~~~`!
```
xrdp 0.9.21.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-QTF2mN/xrdp-0.9.21.1=. -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 
      PKG_CONFIG_PATH=/build/xrdp-QTF2mN/xrdp-0.9.21.1/pkgconfig

  Compiled with OpenSSL 3.0.14 4 Jun 2024
```
~~~

### Operating system & version

Debian12

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xrdp 

### What desktop environment do you use?

xfce

### Environment xrdp running on

physical

### What's your client?

rdesktop 1.9.0

### Area(s) with issue?

Audio redirection

### Steps to reproduce

`rdesktop -u xxx <IP> -p 'ZZZZ'  -f -5 -K -r sound:local`

### ✔️ Expected Behavior

Sound without cracking noise, no error in rdesktop client terminal

### ❌ Actual Behavior

Cracky noise and I get errors in terminal:

```
Sound(error): rdpsnd_queue_write(), no space to queue audio packet
Sound(error): rdpsnd_queue_write(), no space to queue audio packet
Sound(error): rdpsnd_queue_write(), no space to queue audio packet
[...]
```

### Anything else?

I use `pipewire-pulse 1.0.5` and `pulseaudio 1:16.1+`

**Comment by matt335672** [comment]
This error is being generated on your client:-

https://github.com/rdesktop/rdesktop/blob/4716f1e01647ead3093805fd4355faf92c00ed0d/rdpsnd.c#L642C47-L642C55

I suggest you ask the `rdesktop` developers what to do about it - it doesn't mean anything to us.

**Comment by sputnick-dev** [comment]
Thanks to took time to give me accurate pointers
