### ISSUE TITLE
Locale not quite right on RHEL 7 causing gnome-terminal to not start

### ISSUE THREAD

**Issue by therevoman** [neutrinolabs/xrdp#328]
I am using X11RDP-RH-Matic to build and install on an RHEL 7 system.  I am able to build xrdp and the xorg driver.  Once the services have started I log in to the desktop using the "Session Manager" option.  The desktop loads (and annoying dialogs are dismissed) I try to start the gnome-terminal application with no result.  I check /var/log/messages and see the following line:
gnome-terminal.desktop: Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/libexec/gnome-terminal-server exited with status 8
Which leads me to the Gnome Wiki:
https://wiki.gnome.org/Apps/Terminal/FAQ#Exit_status_8
stating the DBus locale is not right.

After much searching it seemed to be an errant LC_ALL value.  On RHEL 7 I believe it is supposed to be blank, but it was being set to a non UTF-8 value.  Gnome-terminal won't run unless a utf8 character set is used I guess.

I did try changing all the system locale files/settings with no luck.  

Finally, I was able to fix the issue with 2 steps.
1) Create the file /etc/default/locale with the following 2 lines 
LANG="en_US.UTF-8"
LC_ALL=
2) edit /etc/xrdp/startwm.sh to also export the LC_ALL value

There is probably a better way to accomplish this.  If so please use that for the fix.  

Thanks.

**Comment by proski** [comment]
There was a complaint that xrdp sets English locale, so that code was removed in 5575197eaa9afe4801a837a3bfa6f0e0701e525e

Does the version you compile include that patch? Did older versions work?

You mention the "errant LC_ALL setting". Do you know what it was? You can write a wrapper around gnome-terminal that would write the environment to a file, so we can find out.

Can you find out where that value is set?

**Comment by therevoman** [comment]
I'll look and see if I have that patch or not.  

I am unsure where the value is being set because my system locale is not being used.

**Comment by proski** [comment]
If you set LC_ALL in `/etc/xdrp/startwm.sh`, you should be able to run `locale` right before that to see what your settings were. I suspect there is some misconfiguration of your side that xrdp could mask until recently, but not anymore.

If the fix need to be made on the xrdp side, maybe xrdp could change `startwm.sh` to set the locale if `/etc/default/locale` is missing of fails to do so. But `/etc/default/locale` may by OS and distro specific, so it's probably not the best approach.

**Comment by matt335672** [comment]
I'm closing this one now. We removed the last bit of code to set the locale in commit f5f67e2e8091563c337564d62b7255eff6b823b0 as part of the UTF-8 changes
