### ISSUE TITLE
xrdp-0.10.1 After successful VNC connection, but cannot be clicked

### ISSUE THREAD

**Issue by baryaor** [neutrinolabs/xrdp#3285]
![image](https://github.com/user-attachments/assets/93284491-af69-4b87-bd69-3808fc57ed7e)

I can successfully connect to VNC, but the interface cannot be operated and the mouse cannot click

**Comment by metalefty** [comment]
Could you please ensure that you provide the necessary detailed information required on the issue form?

**Comment by metalefty** [comment]
Closing this one. Open another one from the issue form.

**Comment by baryaor** [comment]
@metalefty What detailed information is needed?

**Comment by metalefty** [comment]
Issue form tells.

**Comment by baryaor** [comment]
@metalefty the new Issue form done

**Comment by metalefty** [comment]
@baryaor are you kidding me?
