### ISSUE TITLE
x server failed to start

### ISSUE THREAD

**Issue by jamiecash** [neutrinolabs/xrdp#3299]
### xrdp version

0.10.1

### Detailed xrdp version, build options

~~~

xrdp 0.10.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2024 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=/include
      --mandir=/share/man
      --infodir=/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=/lib/x86_64-linux-gnu
      --libexecdir=/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu

  Compiled with OpenSSL 3.0.14 4 Jun 2024
~~~

### Operating system & version

Debian GNU/Linux 12 (bookworm)

### Installation method

git clone & make install

### Which backend do you use?

xorgxrdp 

### What desktop environment do you use?

xfce4

### Environment xrdp running on

VM - AWS

### Area(s) with issue?

Session manager (sesman)

### Steps to reproduce

Install xrdp 0.10.1 from source
Install xorgxrdp 0.10.1 from source
Start xrdp
Connect to xrdp
Login

### ✔️ Expected Behavior

User presented with desktop environment

### ❌ Actual Behavior

Error message: Cant create session for user btest@oakwoods.ac.uk -X server could not be started.

Errors in sesman.log
```
[2024-11-05T13:19:48.732+0000] [INFO ] Starting X server on display 10: Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
[2024-11-05T13:19:58.598+0000] [ERROR] waitforx: Unable to open display :10
[2024-11-05T13:19:58.601+0000] [ERROR] X server failed to start
[2024-11-05T13:19:58.604+0000] [INFO ] Session on display 10 has finished.
```

Errors in xrdp.log
```
[2024-11-05T13:19:48.432+0000] [INFO ] xrdp_wm_log_msg: login was successful - creating session
[2024-11-05T13:19:58.604+0000] [INFO ] xrdp_wm_log_msg: Can't create session for user btest@oakwoods.ac.uk - X server could not be started
[2024-11-05T13:20:36.698+0000] [INFO ] Login screen monitor height is 1080 pixels over 296 mm (92 DPI)
```

### Anything else?

The same user account can be accessed from version 0.9.21.1 installed on Debian using apt install

**Comment by matt335672** [comment]
Hi @jamiecash 

Problem seems to be that you're running `Xorg` without a PATH. If you do this, you actually end up running a wrapper script which prevents non-root running the server.

You need to edit `/etc/xrdp/sesman.ini`, find the `[Xorg]` stanza and follow the instructions for your OS. I suspect you need to replace `param=Xorg` with `param=/usr/lib/xorg/Xorg` for Debian.

Come back to me if that doesn't make sense.

**Comment by jamiecash** [comment]
Thank you. I can confirm that this fixed the issue and have closed.

**Comment by lhuanyun** [comment]
![image](https://github.com/user-attachments/assets/b07b3026-fb4a-4fbe-ba15-bc2f1643a787)
hello, i have same problem ,what can i do samething?

**Comment by metalefty** [comment]
@lhuanyun Raise your own new issue, please.
