### ISSUE TITLE
Cannot copy files into mapped drives in KDE - no free space

### ISSUE THREAD

**Issue by cyqsimon** [neutrinolabs/xrdp#3300]
### xrdp version

xrdp.x86_64 1:0.10.1-1.fc41

### Detailed xrdp version, build options

~~~
xrdp 0.10.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2024 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-redhat-linux-gnu
      --host=x86_64-redhat-linux-gnu
      --program-prefix=
      --disable-dependency-tracking
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/sbin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --runstatedir=/run
      --sharedstatedir=/var/lib
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-fuse
      --enable-pixman
      --enable-painter
      --enable-vsock
      --enable-ipv6
      --with-socketdir=/run/xrdp
      --with-imlib2
      build_alias=x86_64-redhat-linux-gnu
      host_alias=x86_64-redhat-linux-gnu
      CC=gcc
      CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer 
      LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes 
      CXX=g++
      CXXFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer 
      LT_SYS_LIBRARY_PATH=/usr/lib64:
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 3.2.2 4 Jun 2024
~~~

### Operating system & version

Fedora 41

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp

### What desktop environment do you use?

KDE

### Environment xrdp running on

KVM virtual machine

### What's your client?

Windows 10 RDP client

### Area(s) with issue?

File transfer / drive redirection

### Steps to reproduce

1. Fresh install Fedora 41 KDE spin
2. Install packages: `sudo dnf install -y plasma-workspace-x11 xrdp xorgxrdp`
3. Enable `xorgxrdp` in `/etc/xrdp/xrdp.ini`, then `sudo systemctl start xrdp`
4. Login to this machine using Windows 10's built-in RDP client with a mapped drive
5. Try to copy a file into `~/thinclient_drives/<YOUR_DRIVE>` graphically using Dolphin

### ✔️ Expected Behavior

Copy succeeds

### ❌ Actual Behavior

Copy fails; Dolphin indicates no free space available on drive

### Anything else?

This problem was mentioned in passing in https://github.com/neutrinolabs/xrdp/issues/1429#issuecomment-546966471:

It seems like xrdp is always reporting 0 available space on mapped drives. KDE checks this value before the copy commences, hence the error. If we instead use a tool that doesn't check it (e.g. `cp`/`mv`), the operation would succeed.

**Comment by matt335672** [comment]
There's no solution in xrdp at the moment I'm afraid, as we don't have the plumbing in place yet to query the remote file space. If you can disable the check in Dolphin, that would also work, but I don't know if that's possible.

See also #3246 where this issue is discussed.

**Comment by cyqsimon** [comment]
> There's no solution in xrdp at the moment I'm afraid, as we don't have the plumbing in place yet to query the remote file space.

Thanks for the swift response; that's good to know.

> If you can disable the check in Dolphin, that would also work, but I don't know if that's possible.

This behaviour doesn't look like it's configurable, but I'll go consult KDE devs to be sure.
