### ISSUE TITLE
请教 使用ssh的clipboard时，一行完整的命令换行了

### ISSUE THREAD

**Issue by bright-zxl** [neutrinolabs/xrdp#3308]
### Discussed in https://github.com/neutrinolabs/xrdp/discussions/3307

<div type='discussions-op-text'>

<sup>Originally posted by **bright-zxl** November 14, 2024</sup>
社区的朋友们好 我有一个紧急的问题需要得到你们的帮助
我在使用ssh协议的clipboard，复制一条很长的命令（这个命令很长在会话中换行显示了）再粘贴的过程中，拆分为了两条命令，如下图
我应该怎么做才能在复制时保留一条完整的命令而不被拆分呢，期待大家的回复，万分感谢
![WeChat3f53bbf7cacad15ec94801a8ea5945a5](https://github.com/user-attachments/assets/4282d6b7-f5d0-4457-9608-aa2c62da4400)
</div>

**Comment by matt335672** [comment]
@bright-zxl - this does not appear to be an xrdp issue. You also haven't filled in the issue form, so I'm closing this.

If anyone wants to contribute a suggestion, please add it to #3307
