### ISSUE TITLE
enable dynamic CHANSRV_LOG_PATH or/and possibility to change log name "xrdp-chansrv.%d.log"

### ISSUE THREAD

**Issue by Zohman** [neutrinolabs/xrdp#3337]
### xrdp version

0.10.1

### Operating system & version

Ubuntu 22.04

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

Xorg

### What desktop environment do you use?

Openbox

### Steps to reproduce

Hi,

In our environment home dirs are NFS based, and I would like to avoid writing log files there to avoid race-condition issues if a user connects to several machines with xrdp and get same DISPLAY number.

There is a partial workaround to it by setting:

[SessionVariables]
CHANSRV_LOG_PATH=/tmp

But this is still not good enough, as it can create race-condition on the /tmp/xrdp-chansrv.%d.log file,
if user logged out, the log file is not being deleted, and new user get the old display number and /tmp/xrdp-chansrv.%d.log remined own by the last user, so it can't be overriding.

1. can somehow the CHANSRV_LOG_PATH variable be handled dynamically?
   (like for example the **FuseMountName=/run/user/%u/xrdp/drives**)
  we would like to set it as **/run/user/%u/xrdp/** so it can be resolved to **/run/user/%u/xrdp/xrdp-chansrv.%d.log**

2. can the logfile name be controlled from the config? so one can add username or pid to the filename for example?
    ex. **xrdp-chansrv.%d.%u.%p.log**

Currently we have a solution by renaming /usr/sbin/xrdp-chansrv to /usr/sbin/.xrdp-chansrv
and creating /usr/sbin/xrdp-chansrv as a wrapper for dynamic CHANSRV_LOG_PATH.

```
#!/bin/sh
export CHANSRV_LOG_PATH="/run/user/$(id -u)/xrdp"
exec -a "xrdp-chansrv" "/usr/sbin/.xrdp-chansrv" "$@"
```

Also, another best practice suggestion, move executables like xrdp-chansrv and xrdp-sesman that
are not supposed to be run outside of xrdp to be placed in **/usr/libexec/xrdp/** and not in **/usr/sbin** which is part of users PATH.

Thanks!

**Comment by matt335672** [comment]
I understand where you're coming from @Zohman. That's a nice imaginative fix you've got there.

We could also move this setting to the sesman ini file where the substitution would be more natural.

Are you able to try a patch?

Thanks for the libexec suggestion. We are using that for some executables already. I can't see a compelling reason to move these however:-
1) `xrdp-chansrv` can be executed by a user. This  can be done either as part of a VNC session, or to recover it when it breaks.
2) `xrdp-sesman` is a standard daemon, like `xrdp`. The [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html) is somewhat silent on daemon locations, but quite a few other daemons appear to be in `/usr/sbin`

**Comment by Zohman** [comment]
> I understand where you're coming from @Zohman. That's a nice imaginative fix you've got there.
> 
> We could also move this setting to the sesman ini file where the substitution would be more natural.
> 
> Are you able to try a patch?

yes, sure.

> Thanks for the libexec suggestion. We are using that for some executables already. I can't see a compelling reason to move these however:-
> 
> 1. `xrdp-chansrv` can be executed by a user. This  can be done either as part of a VNC session, or to recover it when it breaks.
> 2. `xrdp-sesman` is a standard daemon, like `xrdp`. The [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html) is somewhat silent on daemon locations, but quite a few other daemons appear to be in `/usr/sbin`

seems like you have some good points, didn't know that xrdp-chansrv can (or supposed) to be executed by a user in some cases.

**Comment by matt335672** [comment]
I've started a branch for this (on v0.10):-

https://github.com/matt335672/xrdp/tree/v0_10_rename_chansrv_log_file

This should give you a patch which you can apply to v0.10.1:-

https://github.com/neutrinolabs/xrdp/commit/84711f6e677efda49fa4e6225253c9d500f4ec0b.patch

It should be easy enough to follow. The new manpage for sesman.ini has the details. The file itself has a line you can uncomment.

Let me know how you get on.

**Comment by Zohman** [comment]
seems to do the job, looking forward seeing it in the next version, many thanks!

**Comment by matt335672** [comment]
I'll probably move the setting to the [ChansrvLogging] section, as I think it belongs there rather than in [Chansrv].

@metalefty - I can get this done and retested in the next hour or so. Are you OK for it to go into v0.10.2?

**Comment by metalefty** [comment]
Yes, I think it's worth to ship to v0.10.2.
