### ISSUE TITLE
Integration work for Red Hat Distributions

### ISSUE THREAD

**Issue by antoinetran** [neutrinolabs/xrdp#338]
Hi,

We use Red Hat Server and I spends a few days into integrating xrdp. For people wanting to do the same work, they can read this. Xrdp developpers should fix theses bugs to improve integration to other distributions than Debian.
1. Packages requirements: this should be written in the README.
   For bootstrap:
   sudo yum install autoconf  automake libtool pkg-config
   For configure:
   sudo yum install openssl-devel pam-devel libjpeg-devel fuse-devel TurboJPEG libX11-devel libXfixes-devel libXrandr-devel
   For make:
   sudo yum install binutils
   For /etc/init.d/xrdp status:
   sudo yum install redhat-lsb-core
2. Our system have umask 0077. I had troubles for some directories. Theses permissions should be set explicitely, instead of relying on umask. 
   sudo chmod o+rx /usr/local/lib/xrdp
   sudo chmod o+rx /etc/xrdp
3. Pam settings: the rules are for Debian I believe. [Here](https://github.com/neutrinolabs/xrdp/issues/325#issuecomment-190264338) are the rules.
4. Profile sourcing issue. I had issue with startwm.sh. It sources both /etc/profile and ~/bash_profile, which source /etc/bashrc, which source profile. Since I had a script that cannot be launched twice (readonly variable), the X session could not be started. I don't know if it is xrdp or our system fault. Should profile be sourced in /etc/bashrc? Or should xrdp source only bash profile?
5. Tcp delay : xrdp does not wait for Xvnc to start and create the Tcp socket. With the delay at 2000ms (was commented in /etc/xrdp.ini, under Xvnc), it works. Otherwise RDesktop connexion fails.
6. The service does not use LSB (standard) functions. Services should use theses, as this improve compatibility among compliant Linux distributions. I added at /etc/default/xrdp all the wrapper functions to use the LSB ones:

```
# Creating compatibility functions for LSB.
lsb_function_compat() {
  log_action_begin_msg() {
    echo -n "$@ " 
  }
  log_action_end_msg() {
    log_success_msg "$@"
  }
  log_progress_msg() {
    echo -n "$@ "
  }
  log_daemon_msg() {
    echo "$@"
  }
  log_end_msg() {
    if test "$@" == 0
    then
      log_success_msg "$@"
    else
      log_failure_msg "$@"
    fi
  }

  start_daemon_compat() {

    while test $# -gt 0
    do
      case $1 in
      # Normal option processing
      --pidfile)
        pidfile="$2"
        shift
        ;;
      --chuid)
        chuid="$2"
        shift
        ;;
      --exec)
        exec="$2"
        shift
        ;;
      --stop)
        stop=true
        ;;
      --start|--quiet|--oknodo)
        # Not used parameter.
        ;;
      # Special cases
        "")
          # Done with options
          break
          ;;
        *)
          # error unknown (long) option $1
          echo "Unrecognized argument $1." 1>&2
          exit 2
          ;;
      esac
      shift
    done

    if test "${stop}" != 'true'
    then
      start_daemon -p "${pidfile}" chroot --userspec="${chuid}" / "${exec}"
      # For some reason, the pid file is created by Xrdp at /var/run/xrdp.pid, instead of /var/run/xrdp/xrdp.pid.
      # Workaround: symlink creation and deletion here.
      pidfile_bn=$(basename "${pidfile}")
      ln -s /var/run/"${pidfile_bn}" "${pidfile}"
    else
      killproc -p "${pidfile}" "${exec}"
      rm -f "${pidfile}"
    fi
  }

  alias start-stop-daemon="start_daemon_compat"

}
# Enable LSB functions.
lsb_function_compat
```

**Comment by metalefty** [comment]
> 3. Pam settings: the rules are for Debian I believe. Here are the rules.

I think this is done in #320. Except for mkhomedir.

**Comment by itamarjp** [comment]
for RH systems we have a rpm available here, 

http://koji.fedoraproject.org/koji/packageinfo?packageID=9026

Would you like to submit a patch to readme file ?

**Comment by antoinetran** [comment]
> I think this is done in #320. Except for mkhomedir.

I agree, before that, I used xrdp-0.6.1-4.el6, for Red Hat 6. However, to my opinion, I still think the README in xrdp should put down its requirement, just before ./bootstrap.

> Would you like to submit a patch to readme file ? 

For which point? Point 1? I could, but only for Red Hat 6. But I don't know how to do a patch.

> for RH systems we have a rpm available here, 

Indeed, but it lacks the RPM for Red Hat 6. RPMs for Red Hat 7/Fedora are not compatible for RH6, I tried. Latest for RH6 is 0.6.1-4.el6, which is way below 0.8.

**Comment by antoinetran** [comment]
> for redhat 6 is on the link that I have posted http://koji.fedoraproject.org/koji/buildinfo?buildID=669452

I said this before:

1. firstly, the latest of this RPMs is way too old. There was at least two major bug that is corrected in 0.8. I guess the package maintainer did not found useful to support Red Hat 6 anymore.
2. Secondly, even if someone has already made a RPM, I believe xrdp website should independent from them, by making a README complete enough, so that someone who decides to follow it, can build and run it, in a reasonably amount of time. I spend 4 days for this and put back everything in this page. I have even written the code for the Linux service xrdp, so that it will (in theory) work with any Linux LSB compliant distributions, out-of-the box. I am ready to submit a patch formally if needed. Among all these points, point 2, 5 and 6 are distributions independant and should be backported in the source code... my two cents!

**Comment by blackcrack** [comment]
@itamarjp 

> mandriva is almost dead, zombie distro

well, :sob: Mandriva maby but not Openmandriva, Openmandriva, as explain for you,
it is now a Private Association and the Openmandriva lives further :stuck_out_tongue_winking_eye: as the real Successor
of Mandrake because, if you have noticed , Jean Manuel Croset :innocent: the COO of die MandrivaSA in paris have get the Linuxdistribution back to the community anno 2012 and we are now strong as community for build it now up again. MandrivaLinux it's maybe die, but OpenMandriva it's the Community Phönix OpenMandriva linux = OMLx :sparkling_heart: .... -> Letz R0CK 
and the Openmandriva 3 :yum: (2016) beta it's coming up now in the next time and the cooker unter hot :fire: .. so, if you want come Home (if you was an MDKUser, the doors be open :smirk: )
abf.openmandriva.org or Openmandriva.org

**Comment by metalefty** [comment]
I found out that fuse package is also needed to *use* drive redirection or clipboard file transfer.
Just building xrdp with `--enable-fuse` option, fuse-devel is enough but it cannot be used.

If fuse is not installed, client drives cannot be mounted under thinclient_drivers directory.
`fuse: failed to exec fusermount: No such file or directory`

I think this should also be documented to requirements.

**Comment by metalefty** [comment]
@antoinetran 
Is it happy for you to document requirements in wiki? Everyone can edit it. Of course you can.
And then write the link to wiki in README. Let's update wiki first.  It will be quick.

**Comment by antoinetran** [comment]
Hi, ok I haven't seen this wiki until now. This is a good idea, thank you! I see there was already a CentOs page, so I added there a few lines, and referred to this page, because it has some useful information. Of course this might be improved, but I do not have much time in my project now.

**Comment by volga629** [comment]
Is not easy pass to vncserver 
I am trying get working with FreeIPA and xrdp report ok and vncserver failing asking for password file.

`Xvnc :1 pam_service=login`

**Comment by metalefty** [comment]
Seems to be solved.
