### ISSUE TITLE
OS X: configure: error: please install libssl-dev or openssl-devel

### ISSUE THREAD

**Issue by necktwi** [neutrinolabs/xrdp#340]
I'm trying to build it on OS X. I tried `brew install openssl-dev` or `brew install libssl-devel`. No recipes found. I've built and installed [latest openssl](https://github.com/openssl/openssl) and I've run configure again but it still says

```
...
Package systemd was not found in the pkg-config search path.
Perhaps you should add the directory containing `systemd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'systemd' found
checking for openssl/rc4.h... no
configure: error: please install libssl-dev or openssl-devel
```

**Comment by metalefty** [comment]
Build on OS X is not stable yet but focusing on openssl not found issue, maybe you have to tell configure script where openssl is.

This is an example. You can also specify the place of openssl with CFLAGS.
`./configure --includedir=/path/to/brew/openssl/installation`

**Comment by metalefty** [comment]
I think #520 is the solution. Could you reopen if #520 doesn't solve the problem?
