### ISSUE TITLE
Clipboard on Debian 7 Host

### ISSUE THREAD

**Issue by richardskumat** [neutrinolabs/xrdp#343]
I know this is a frequent & common issue both here and on other forums.

I've created a somewhat working installer for Debian 7 and the only thing that isn't working for me is clipboard, and thus copy paste between any client and the debian "xrdp" server.

I can copy and paste on the "xrdp" server desktop(I mean on the server itself) just fine but I can't copy anything to or from the "xrdp" server.

If I could get copy paste working, I could ditch using Windows servers as temporary desktops once and for all.

Clients I have:

```
Debian 9, freerdp-x11, version: 1.1.0-beta1 (git n/a)
Windows 7 SP1
Windows Server 2012 R2
```

All of these have at least fairly modern rdp clients. What's surprising is not even Windows machines can copy paste to and from the Debian 7 "xrdp" server.

I'm not sure what options I'm missing. All my installer does is standard stuff.

I'm not even modifying anything, only adding EN-GB keyboard on the server as that's what I use.

Let me know what options you want to be shared. I'm quite new to XRDP & its troubleshooting.

**Comment by therevoman** [comment]
I have been using XRDP for over a year now.  Most of our issues can be traced back to the configuration of the RDP client.  On Windows 7 SP1 we have to open the "Advanced" tab and make a few changes.  


On the tab "Local Resources"
 - Printers **MUST** be unchecked
 - Clipboard must be **checked**
 - More... Smart Cards **MUST** be unchecked

After those changes in the client, try connecting and see if your clipboard problems go away.

Best of luck to you

**Comment by metalefty** [comment]
Please reopen if the issue still happens with the latest xrdp.
