### ISSUE TITLE
Please consider taking over patches in Debian

### ISSUE THREAD

**Issue by tillea** [neutrinolabs/xrdp#344]
Hi,
I upgraded the Debian packaging to xrdp 0.8.0 since as far as I understood this is the latest released version (please correct me if I'm wrong - I was guessing from the release tags).
The packaging for 0.6.0 contained some patches which I adapted to the code I found in the source download tarball of 0.8.0.  You can find these patches including comments [here](https://anonscm.debian.org/cgit/collab-maint/xrdp.git/tree/debian/patches).  Feel free to cherry pick from these patches (some are simple spelling issues).
Moreover it would be good if you could remove the binary file tcutils/tcutils from the download tarball. Specific binaries should not be included if you can build it from the source.
Kind regards
        Andreas.

**Comment by itamarjp** [comment]
theres no binary file tcutils/tcutils in master branch,

**Comment by tillea** [comment]
Hi Itamar,

On Tue, Mar 08, 2016 at 07:40:30AM -0800, Itamar Reis Peixoto wrote:
> theres no binary file tcutils/tcutils in master branch, 

As I tried to explain I was not talking about master branch but the
latest download tarball.  If this is removed from master branch chances
are good that it will not be included into the next source download so
this is probably no issue any more.

Kind regards

        Andreas.

-- 
http://fam-tille.de

**Comment by metalefty** [comment]
@itamarjp @jsorg71 Can you please listen to what I'm saying in #311, #323?  If my opinion is nonsense, I will dismiss them.

Whichever 0.8.1 or 0.9.0 is ok but people want a new release tag.  Let me know agree or not.  Here's one more person who wants a new tarball.

**Comment by itamarjp** [comment]
@metalefty I agree with you, it's time to release a new tarball / tag, 
@jsorg71  0.8.1 or 0.9.0 ? 

I recommend releasing 0.9.0 and changing autotools to 0.9.1

**Comment by metalefty** [comment]
I don't like devel/master branch is called 0.9.0 though 0.9.0 hasn't actually been released yet.  I can understand it but confusing for non developers.  Changing autotools to 0.9.1 will repeat it.  I commented about new idea for development version in #323.

**Comment by mirabilos** [comment]
Patches now superseded, cf. https://github.com/neutrinolabs/xrdp/issues/232#issuecomment-223148594 – but our patches are available at the same location.

**Comment by metalefty** [comment]
Debian package is updated to 0.9.0 of devel branch snapshot.  I'm happy to accept Debian patches if they're worth to merge.  If Debian guys have patches should be upstreamed, feel free to create new pull requests. 

CC: @Natureshadow
