### ISSUE TITLE
x11rdp, how to always launch a new session

### ISSUE THREAD

**Issue by ScottCar** [neutrinolabs/xrdp#345]
Hey guys, I have just installed x11rdp on ubuntu 14.04
What happens is every time I remote in and login I get connected to the same existing session.  I want to make a kiosk user with a shared username and password that will always launch a new session and never connect to an existing one.  I looked through the .ini files and it seems it will always resume the session if the geometry and username are the same.  Any way around this?  Thanks!

**Comment by itamarjp** [comment]
@jsorg71 can you make this behavior configurable ?

**Comment by jsorg71** [comment]
I think it is.
see
## Policy - session allocation policy
in sesman.ini

**Comment by metalefty** [comment]
`Policy=UBDC` in sesman.ini can do that.

**Comment by metalefty** [comment]
Probably you don't want to preserve sessions which never be reconnected.

Set `KillDisconnected` to `yes`, `DisconnectedTimeLimit` to an integer value what you want.

**Comment by ScottCar** [comment]
that did it metalefty, thanks!  
The UBDC is confusing as I thought it meant to maintain session if those items were the same.

**Comment by metalefty** [comment]
@ScottCar close?

**Comment by ScottCar** [comment]
Yes, you can close.  This is working great.
