### ISSUE TITLE
x11rdp auto launch a browser (kiosk mode) without bringing up full desktop

### ISSUE THREAD

**Issue by ScottCar** [neutrinolabs/xrdp#346]
I've just setup ubuntu 14.04 with x11rdp.  I want to be able to auto launch a browser and not load the full desktop environment.  Currently I have mate installed.

My $HOME$/xsessions file looks like this:  mate-session
/usr/share/xsessions has mate.desktop which i've tried modifying a couple different ways, but it seems like mate.desktop is never actually processed.

If I get on the console directly I can choose a kiosk mode that will then launch and run the browser without a toolbars/etc.  However I can't seem to get xrdp to do anything but just launch the complete mate-session

**Comment by moobyfr** [comment]
Le 09/03/2016 18:11, ScottCar a écrit :
> I've just setup ubuntu 14.04 with x11rdp. I want to be able to auto
> launch a browser and not load the full desktop environment. Currently I
> have mate installed.
>
> My $HOME$/xsessions file looks like this: mate-session
> /usr/share/xsessions has mate.desktop which i've tried modifying a
> couple different ways, but it seems like mate.desktop is never actually
> processed.
>
> If I get on the console directly I can choose a kiosk mode that will
> then launch and run the browser without a toolbars/etc. However I can't
> seem to get xrdp to do anything but just launch the complete mate-session
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neutrinolabs/xrdp/issues/346>.
>

xrdp follows standard: Starting a session is set up with
/etc/X11/Xsession in ubuntu

To achieve that, xrdp launch /etc/xrdp/startwm.sh to find the system 
startup.
So you can adapt /etc/X11/Xsession or /etc/xrdp/startwm.sh

**Comment by ScottCar** [comment]
Sorry for my ignorance.  So it looks like /etc/xrdp/startwm.sh calls to /etc/X11/Xsession
Content of /etc/xrdp/startwm.sh
# debian
if [-r /etc/X11/Xsession]; then
   . /etc/X11/Xsession
   exit 0
fi

Then Xsession calls to $HOME/.xsession
Content of /etc/X11/Xsession:
USERXSESSION=$HOME/.xsession

Contents of $HOME/.xsession:
mate-session

It's at mate-session that i'm not sure how to launch just the browser, I don't want the menu's or toolbar.  Is there a config file for mate-session somewhere that I can see what it's launching exactly and modify that?  I thought it would be under /usr/share/xsessions/mate.desktop

**Comment by metalefty** [comment]
If you don't want to show any menus of MATE, just execute browser. 

For example,

```
chrome --kiosk
```

in your .xsession or something else. You don't have to write anything else.

**Comment by metalefty** [comment]
Ah, kiosk mode of Google Chrome obscures everything except for browser window, so .xsession can be written:
```
mate-session &
chrome --kiosk &
```

**Comment by ScottCar** [comment]
Perfect, thanks!

**Comment by metalefty** [comment]
close?
