### ISSUE TITLE
Compile X11RDP on Arm64

### ISSUE THREAD

**Issue by MacFizz** [neutrinolabs/xrdp#348]
Hello
I'm using X11RDP-o-matic on an arm64 (Odroid-C2) but there's seems to be a problem during compiling of dri2proto (which is 4 out 102).
message shows :
UNAME_MACHINE = aarch64
UNAME_RELEASE = 3.14.29-32
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT Mon Mar 14 01:56:04 BRT 2016
configure: error: cannot guess build type; you must specify one
configuration failed for module dri2proto-2.3

Something seems to be missing in dri2proto...

**Comment by itamarjp** [comment]
on fedora its builds fine, look

http://koji.fedoraproject.org/koji/buildinfo?buildID=744391

**Comment by MacFizz** [comment]
Yes, xrdp 0.9  will also build fine on it's own.
I assume that dri2prot is part of X11rdp which is the part that I'm missing.
So far I've been unable to use xrdp and vncserver.
In any case building xrdp did work and I can connect to it, but without X11RDP, I can't do much...

**Comment by MacFizz** [comment]
Oh, well, might have spoken a bit fast.
Xrdp does compile without error, but fails to start because /usr/sbin/xrdp-sesman and /usr/sbin/xrdp are missing.
I've fixed this issue making symbolic links from /usr/local/sbin and the service works...

**Comment by metalefty** [comment]
I don't have arm64 environment so I cannot test the build but probably explicitly give configure script architecture will work.

`./configure --host=aarch64-linux-gnu --build=aarch64-linux-gnu` or something,

**Comment by MacFizz** [comment]
OK, some infos now.
aarch64 architecture is unknow in the configure.guess of dri2prot, therefore it fails.
Manually adding aarch64 in the configure.guess (with same parameters as arm) will allow configure to work without error.
Xrdp-o-matic downloads sources, so I don't know how to make a test to build.
Any ideas ?

**Comment by itamarjp** [comment]
you probably need to run automake, autoconf, autoreconf to re-generate configure/makefiles.

**Comment by metalefty** [comment]
@itamarjp configure script in dri2proto is not generated. it is distributed.

**Comment by metalefty** [comment]
Now xorgxrdp is the recommended backend and xorgxrdp successfully builds on arm64.
Please try xorgxrdp instead of x11rdp, closing.
