### ISSUE TITLE
Writing news, homepage.. e.t.c

### ISSUE THREAD

**Issue by blackcrack** [neutrinolabs/xrdp#349]
Hi,

an bit news would be really fine :)
and an bit update the homepage and so on..
the last news was on 2011 .. now now 6 years ago..

what's going on.. an update would be really well
on the homepage

best regards
Blacky

**Comment by metalefty** [comment]
@jsorg71

At least mailing list address must be updated ASAP.
GitHub address and something like "xrdp is developed on GitHub now" also must be written.

**Comment by haynes11** [comment]
I agree, this project is a mess. Everything is everywhere, so many different versions everywhere. If you're a newbie and don't know about freerdp etc reading any kind of documentation on here is confusing and a mess. I would put money forward to have this project actively developed whether for hosting, sponsorship or whatever. We should all really get together and do it.

**Comment by metalefty** [comment]
Jay, if you have no time to update website, I will always help you.

**Comment by metalefty** [comment]
speidy is working on the new website.

**Comment by metalefty** [comment]
Not GitHub is the latest site.
