### ISSUE TITLE
Black screen talking to win 2k server

### ISSUE THREAD

**Issue by LawrenceK** [neutrinolabs/xrdp#35]
This is build using freerdp (fd0e93c35f) and xrdp master (c5862f367ca68763dd3070598a36ea82db7f3566) , single sign on works to Win2K8 R2, WIn2K8 and Win2K3 ok. Using libfreerdp1 to win2k gives black screen. I tried without specifying the username and password and still blackscreen typing a username password assuming login box was generating log output (debug build).

**Comment by metalefty** [comment]
@LawrenceK If you still have interest with this issue, can you try with the latest xrdp?

**Comment by LawrenceK** [comment]
I am no longer working on this.

I have cc'd osirium on this as they may still be interested.

Lawrence.

**Comment by LawrenceK** [comment]
Lawrence

    You are correct, we are extra double interested in this stuff, and 
stuff related to it.

Double Regards



Andy

**Comment by metalefty** [comment]
Closing but feel free to reopen if you started to work on this.
