### ISSUE TITLE
Error with make install (ranlib)

### ISSUE THREAD

**Issue by ivasim** [neutrinolabs/xrdp#351]
I am using checkinstall for installing the package from the latest github source.
Here is the output of an error.

> Installing with make install...
> 
> ========================= Installation results ===========================
> Making install in common
> make[1]: Entering directory '/home/user/xrdp/common'
> make[2]: Entering directory '/home/user/xrdp/common'
> make[2]: Nothing to be done for 'install-exec-am'.
>  /bin/mkdir -p '/usr/local/lib/xrdp'
>  /bin/bash ../libtool   --mode=install /usr/bin/install -c   libcommon.la '/usr/local/lib/xrdp'
> libtool: install: /usr/bin/install -c .libs/libcommon.so.0.0.0 /usr/local/lib/xrdp/libcommon.so.0.0.0
> libtool: install: (cd /usr/local/lib/xrdp && { ln -s -f libcommon.so.0.0.0 libcommon.so.0 || { rm -f libcommon.so.0 && ln -s libcommon.so.0.0.0 libcommon.so.0; }; })
> libtool: install: (cd /usr/local/lib/xrdp && { ln -s -f libcommon.so.0.0.0 libcommon.so || { rm -f libcommon.so && ln -s libcommon.so.0.0.0 libcommon.so; }; })
> libtool: install: /usr/bin/install -c .libs/libcommon.lai /usr/local/lib/xrdp/libcommon.la
> libtool: install: /usr/bin/install -c .libs/libcommon.a /usr/local/lib/xrdp/libcommon.a
> libtool: install: chmod 644 /usr/local/lib/xrdp/libcommon.a
> libtool: install: ranlib /usr/local/lib/xrdp/libcommon.a
> ranlib: could not create temporary file whilst writing archive: No more archived files
> Makefile:407: recipe for target 'install-moduleLTLIBRARIES' failed
> make[2]: *** [install-moduleLTLIBRARIES] Error 1
> make[2]: Leaving directory '/home/user/xrdp/common'
> Makefile:582: recipe for target 'install-am' failed
> make[1]: *** [install-am] Error 2
> make[1]: Leaving directory '/home/user/xrdp/common'
> Makefile:427: recipe for target 'install-recursive' failed
> make: *** [install-recursive] Error 1
> 
> ****  Installation failed. Aborting package creation.

**Comment by proski** [comment]
I googled for "checkinstall ranlib: could not create temporary file whilst writing archive", and it looks like a common problem not specific to xrdp.

I believe it's a permission problem. Did /usr/local/lib/xrdp exist prior to the install? Does the user running checkinstall have permissions to create files there?

Another possibility is that checkinstall is confused by static libraries being installed to a non-standard library directory. Please try configuring xrdp with `./configure --disable-static`, recompiling it and installing it with checkinstall.

Please specify the distro version you are using and the version of checkinstall. It may help developers reproduce your problem.

**Comment by ivasim** [comment]
It probably is a checkinstall problem, because installation went fine using "make install". Sometimes it can break an installation because of missing folder, it refuses to create it automatically even with elevated rights and I have to create it manually. In the meantime I have switched from Debian Jessie to Manjaro Linux so dealing with this problem is now obsolete. However, thank you for your answer.

**Comment by proski** [comment]
Good to know. The issue can be closed now.

**Comment by jmunsch** [comment]
for anyone else that happens upon this thread who is using checkinstall

i had to give the user permissions to `mkdir` and `dpkg-buildpackage` like:

```
jenkins ALL=(ALL) NOPASSWD: /usr/bin/dpkg-buildpackage, /bin/mkdir
```

for a jenkins user with no password
