### ISSUE TITLE
"--enable-rfxcodec" option should build librfxcodec module automatically

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#354]
To someone be familiar with autotools, configure or something,

When I try to build xrdp with `--enable-rfxcodec`, I need a special attention.
I **know** I need to execute `make -C librfxcodec` before building xrdp itself.
Without building librfxcodec module before xrdp, it fails.

```
$ git clone -b devel --recursive https://github.com/neutrinolabs/xrdp.git
(in the xrdp git repository)
$ ./bootstrap && ./configure --enable-rfxcodec
$ make
(snip)
make[2]: Entering directory '/home/meta/xrdp/xrdp'
make[2]: *** No rule to make target '../librfxcodec/src/librfxencode.a', needed by 'xrdp'.  Stop.
make[2]: Leaving directory '/home/meta/xrdp/xrdp'
Makefile:427: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/meta/xrdp'
Makefile:358: recipe for target 'all' failed
make: *** [all] Error 2
```

Correct procedure of the build so far.
```
$ ./bootstrap && ./confiure --enable-rfxcodec
$ make -C librfxcodec # this should be done automatically
$ make 
```

Let's make this automatic. The goal of this issue is the build with `--enable-rfxcodec` should go successfully without `make -C librfxcodec`. I think this will be convenient for users.  Probably this change is easy but unfortunately I'm not sure how to do that.

@proski , you know how to do this, don't you?

**Comment by proski** [comment]
Sorry for delay. I looked at the issue briefly. It may be possible, but it would require some serious hacks to suppress Automake assumptions. Automake assumes that it has full control over source code compilation (it's OK to have "plain" makefiles for the data that is not compiled). It would be easier to make librfxcodec part of xrdp or require that librfxcodec is installed separately. That's what other projects do.

**Comment by metalefty** [comment]
Thanks, I understand. It will be fine leaving it it as is.

>  It would be easier to make librfxcodec part of xrdp or require that librfxcodec is installed separately. That's what other projects do.

librfxcodec installs nothing but is required to build xrdp with `--enable-rfxcodec` option.

**Comment by proski** [comment]
Installing nothing is a fixable technical detail, but it suggests that librfxcodec probably has no other users, unless it's added as a submodule to other projects. Even if I add librfxcodec to the build from git, it won't be distributed unless we decide to distribute it with xrdp.

I see only three sound approaches to dealing with libraries:

- Turn librfxcodec into a standalone installable library, allow building xrdp against the installed library.
- Turn librfxcodec into a standalone installable library, allow xrdp to load the installed library dynamically if available (may be tricky, but libtool will facilitate possible issues).
- Integrate librfxcodec into xrdp sources, distribute it as part of xrdp.

**Comment by metalefty** [comment]
won't fix so far.
