### ISSUE TITLE
Horizontal stripe on the screen

### ISSUE THREAD

**Issue by beljaeff** [neutrinolabs/xrdp#356]
I start remote xrdp session from desktop (1280x1024), after that I connect to this session from notebook (1364x768) and then I connect to the same session from desktop again (1280x1024).
So I get horizontal strip (screenshot attached).

![s](https://cloud.githubusercontent.com/assets/5044643/14245493/ddca8d20-fa72-11e5-912f-4abd5e251a20.png)

This stripe is "above" all windows I open.

**Comment by metalefty** [comment]
Can you test with the latest xrdp & xorgxrdp?

**Comment by metalefty** [comment]
Please reopen if the issue still reproducible with the latest release.
