### ISSUE TITLE
Cannot find /etc/xrdp/xrdp.sh in OS X "El Capitan"

### ISSUE THREAD

**Issue by nestoru** [neutrinolabs/xrdp#365]
Anybody was able to run latest version in OS X "El Capitan"?

1 Instal xQuartz
2 Instal brew
3 Run the below:
```
brew update
brew install autoconf automake gettext libtool tree pkgconfig openssl
sudo ln -s /opt/X11/include/X11 /usr/local/include/X11
brew link --force openssl
cd /tmp
git clone https://github.com/neutrinolabs/xrdp.git
cd xrdp
./bootstrap
./configure
make
sudo make install
```
4 No errors so I expected to find  /etc/xrdp/xrdp.sh  however it is not there:
```
$ find /etc/xrdp/ -name "*.sh"
/etc/xrdp//startwm.sh
$ 
```

**Comment by metalefty** [comment]
It is correct. AFAIK, xrdp.sh intend to be run on GNU/Linux and is not compatible with other OS.
So xrdp doesn't install it for non-Linux OS.  If you think xrdp.sh works for OS X,  please give me the result it is actually working on OS X.  I'll change to install it for OS X.

**Comment by proski** [comment]
xrdp.sh is Linux only, so its absence on Mac OS is not a bug.

Just run xrdp and xrdp-serman manually to try them. I can connect to xrdp, but I cannot go any further yet. I suspect `libscp network error` in xrdp-sesman.log. XRDP on Mac OS needs a lot of work. I cannot even install tiger-vnc from homebrew on El Capitan.

**Comment by metalefty** [comment]
not a bug.
