### ISSUE TITLE
Patch - Session Reconnect, Startup Script Fixes, and Authentication Fixes

### ISSUE THREAD

**Issue by horn545** [neutrinolabs/xrdp#368]
The below GIT patch, uploaded as .txt, corrects the inability to reconnect to current sessions with different geometry.  It also corrects an issue in xrdp.sh where the test for is_xrdp_running would fail finding the name of the init.d script, if renamed to "/etc/init.d/xrdp".  It also corrects a failure with authentication by replacing the PAM methods in /etc/pam.d/xrdp-sesman.  Apply this patch before compiling on RHEL 6.X or CENTOS 6.X to correct these issues.

[0001-Resume-previous-sessions.txt](https://github.com/neutrinolabs/xrdp/files/234936/0001-Resume-previous-sessions.txt)

**Comment by coredump4** [comment]
Thank you!
I missed this issue and opened my own (#369) for the geometry issue.  Odd, I swear I searched for geometry-related issues and didn't see yours.
I'm looking forward to testing your patches.

**Comment by therevoman** [comment]
One of the patch items is vnc.c,  Is this only a fix when using VNC as the backend?

**Comment by metalefty** [comment]
xrdp doesn't allow reconnect VNC-backed session with different geometry on purpose because can't resize geometry. 

#369 is completely different case. xorgxrdp/x11rdp backed session allows to reconnect with different geometry but sometimes accidentally crashes using multimon. The patch changes reconnect behaviour but doesn't fix the crash.  Additionally, the patch is a mix of patches with different purpose. It should be separated.

**Comment by horn545** [comment]
This patch is to ONLY add the ability to reconnect to an existing session using the CENTOS 6.X TigerVNC server available with the CENTOS distro.  This patch has no regard for multimon support, or automatic resizing on reconnects.  This patch was provided solely to support the ability to reconnect to an existing session in a business development environment where users were not concerned with having to manually resize their display after reconnecting, but placed priority on reusing existing sessions.
This only supports VNC backend.

**Comment by metalefty** [comment]
Reported doesn't provide separated patches for a year. Once closing.
