### ISSUE TITLE
multimon session instability when geometry changes

### ISSUE THREAD

**Issue by coredump4** [neutrinolabs/xrdp#369]
I've been putting a recent Devel snapshot through the multimon paces with an Xorg backend.  One thing I notice is, if I connect with one monitor configuration, then disconnect my RDP session, and re-connect with even a slightly different monitor configuration, random processes will die.  The dying process might be a Gnome panel element, or any X client app. the user starts, like a browser.  And, after about 6 of these disconnect/reconfigure/connect cycles, the whole session will quit (eg, xrdp-sesman, xrdp-chansrv, and Xorg all exit).  The parent procs keep going and you can reconnect and start a brand-new RDP session, so it's more of an inconvenience I suppose.

The use case for this is where the user wants to collaborate with others, so they disconnect their RDP session and re-connect from a co-worker's office or conference room where the displays are different.

**Comment by coolemza** [comment]
Confirm, xubuntu 16.04, xrdp dev branch, build via xrdp-o-matic, reconnecting with different geometry kills all opened consoles

**Comment by metalefty** [comment]
I also confirmed.

On Scientific Linux release 7.2 (Nitrogen), built by RH-Matic.

```
xorg-x11-drv-xrdp.x86_64              0.9.0.gita0add6c+devel-1.el7 
xrdp.x86_64                           0.9.0.git703fedd+devel-1.el7
```

**Comment by coolemza** [comment]
Seems, that it also triggers memory leak in X11rdp.

On Xubuntu 16.04, built by X11RDP-o-Matic.

**Comment by jsorg71** [comment]
This might be fixed in devel branch.
eed0227d81257531d590556bf177def4e46b6f93
Can you test.

**Comment by metalefty** [comment]
Applying the same change to xorgxrdp will fix xorgxrdp?

https://github.com/neutrinolabs/xorgxrdp/blob/devel/module/rdpRandR.c#L447-451

**Comment by jsorg71** [comment]
If this fixes the X11rdp issue, yes, the same change in Xorg will fix that.
I'm not sure if the X11rdp fix really works.  I just noticed when I wrote a simple XRandR app that it was returning too many monitors.

**Comment by metalefty** [comment]
OK, I'll try X11rdp first and then apply the same change to xorgxrdp locally.

**Comment by metalefty** [comment]
Tested eed0227 with X11rdp. It is stable for me now.

**Comment by jsorg71** [comment]
Ok, so I'll close this one.

**Comment by metalefty** [comment]
@jsorg71 Can you update xorgxrdp submodule? I think we can close this when xrdp repository refers fixed version of xorgxrdp.
