### ISSUE TITLE
Dose not allow me to connect 

### ISSUE THREAD

**Issue by paxoboy** [neutrinolabs/xrdp#373]
The xrdp dose not allow me to connect here is the error message

xrdp_mm_process_login_responce: login failed

**Comment by coredump4** [comment]
There are a number of potential reasons for this.
What version and/or branch of Xrdp are you using?  And please post your xrdp.ini and sesman.ini files.

**Comment by paxoboy** [comment]
how do i check that i just learnt how to install the xrdp but it just saids login responce failed

**Comment by coredump4** [comment]
It depends on your Linux distribution.  A typical location for the INI files is /etc/xrdp but they could easily be elsewhere.

**Comment by metalefty** [comment]
Waiting for the submitter's feedback but we haven't heard from  for months. Closing. Feel free to reopen if the submitter is willing to get back this issue.
