### ISSUE TITLE
feature request:  configurable location for sesman login screen

### ISSUE THREAD

**Issue by coredump4** [neutrinolabs/xrdp#374]
When using spanning or multimon, the sesman login screen ends up split across multiple screens.  This doesn't look very good nor is it easy to read.
How about a simple configuration directive, maybe ls_screen, where a value of "first" restricts the login screen to the user's first monitor?  This would be perfect for multimon.  For spanning, just use the lower half of total X pixels when centering the login screen.

**Comment by metalefty** [comment]
+1 I think login dialog should position should be center of primary screen.

**Comment by speidy** [comment]
I added it in another repository , I will add it to devel soon
בתאריך יום ה׳, 12 במאי 2016 ב-11:47 מאת metalefty <notifications@github.com

**Comment by jsorg71** [comment]
I like center of primary screen or center of left most / top most screen if no primary.

**Comment by speidy** [comment]
I pushed a fix for that in 62799b8b10979e5486c1adf17bf4a43ce21b32c1
Can you verify?

**Comment by coredump4** [comment]
It looks like that got merged into devel yesterday?
Regardless, thanks, I'll be sure to test that out.

**Comment by speidy** [comment]
Yep, thanks!
בתאריך יום ו׳, 13 במאי 2016 ב-21:56 מאת coredump4 <notifications@github.com

**Comment by metalefty** [comment]
Now login dialog is not split across the screens but position is odd.

My screens are 1920x1200+1600x900. See also the debug log of xrdp.
```
processing monitors data, allow_multimon is 1
monitorCount= 2
got a monitor: left= 0, top= 0, right= 1919, bottom= 1199, is_primary?= 1
got a monitor: left= 1920, top= 0, right= 3519, bottom= 899, is_primary?= 0
```

I drew two points on this screenshot. The red point is center of the left screen and the black point is center of the right screen.
![default](https://cloud.githubusercontent.com/assets/941609/15313911/72a3c914-1c49-11e6-866a-a367629287b8.PNG)

**Comment by speidy** [comment]
Thanks for feedback. There's indeed a bug, I'll fix that soon.

As I see you left monitor is your primary one.
And the login screen drawn on the secondary monitor.
Am I right ?

בתאריך יום ג׳, 17 במאי 2016 ב-10:09 מאת metalefty <notifications@github.com

**Comment by speidy** [comment]
Should be fixed now in devel branch (
b38dcf1bb0e1ecf6e98de20ac2480cb41dc905e3)

can you verify?

Thx.

**Comment by metalefty** [comment]
> As I see you left monitor is your primary one.
> And the login screen drawn on the secondary monitor.
> Am I right ?

You're right. I'll test the latest devel branch later.

**Comment by metalefty** [comment]
Looks good.

![xrdp-multimon](https://cloud.githubusercontent.com/assets/941609/15344323/ed037c80-1ce0-11e6-89b1-deae6590bb90.png)

**Comment by speidy** [comment]
Great! Thanks.
בתאריך יום ד׳, 18 במאי 2016 ב-4:13 מאת metalefty <notifications@github.com>:

**Comment by metalefty** [comment]
@coredump4 
Login dialog location is still unconfigurable but login dialog is rendered  in primary screen now.
Is this solve your issue? Do you mind if i close this issue?

**Comment by coredump4** [comment]
Having the login window on the primary screen is perfect!  Thanks again.
