### ISSUE TITLE
ideas for getting local workstation notifications while in RDP full-screen session

### ISSUE THREAD

**Issue by coredump4** [neutrinolabs/xrdp#377]
This is not necessarily an Xrdp issue, but this group is more likely than most to have dealt with it, so here goes.  When mstsc is full-screen -- be it a single screen or multimon -- it suppresses local notifications (eg, Outlook e-mail alerts and the like).  I'd like for users to have the option to get notifications if they want.
Is there a way to disable RDP's suppression behavior?  I've not been able to find a way to do this.
Or, thinking (way?) ahead, can the client forward notifications through a channel to the remote host?  Then you _could_ augment Xrdp to receive client notifications, and maybe use something like libnotify to display a pop-up to the user.
Thoughts?

**Comment by metalefty** [comment]
Not an xrdp issue.
