### ISSUE TITLE
Change deprecated constants in xrdpvr.c

### ISSUE THREAD

**Issue by hcoin** [neutrinolabs/xrdp#378]
sed -i 's, CODEC_TYPE_VIDEO, AVMEDIA_TYPE_VIDEO,' xrdpvr/xrdpvr.c

sed -i 's, CODEC_TYPE_AUDIO, AVMEDIA_TYPE_AUDIO,' xrdpvr/xrdpvr.c

sed -i 's, PKT_FLAG_KEY, AV_PKT_FLAG_KEY,' xrdpvr/xrdpvr.c

The old constants now generate compile errors. (Ubuntu xenial LTS)

**Comment by metalefty** [comment]
Duplicate of #293.
