### ISSUE TITLE
XRDP does not accept security_layer=negotiate 

### ISSUE THREAD

**Issue by CarstenGrohmann** [neutrinolabs/xrdp#380]
XRDP prints a warning message if I change the `security_layer` parameter to `negotiate` like suggested in #207. After switching back to `rdp` XRDP work fine again.

I don't find `negotiate` in the current master branch. `hybrid` is mentioned instead. Maybe this is just an documentation error. 

It would be great if you could adapt the file xrdp.ini as well as the manpage of xrdp.ini accordingly.

Logged warning message:
```
XRDP[31727]: Warning: Your configured security layer is undefined, xrdp will negotiate client compatible
```

Installed version (built with X11RDP-RH-Matic):

- xrdp-0.9.0.gitf422461+master-1.el7.x86_64
- xorg-x11-drv-rdp-0.9.0.gitf422461+master-1.el7.x86_64

Thanks,
Carsten

**Comment by speidy** [comment]
This issue is fixed in devel branch.
בתאריך יום ג׳, 31 במאי 2016 ב-14:53 מאת Carsten Grohmann <
notifications@github.com>:
