### ISSUE TITLE
Osx ranlib malformed archive error during make

### ISSUE THREAD

**Issue by Illotus** [neutrinolabs/xrdp#383]
Osx version 10.11.5, using the devel branch, getting the following error:

>  ranlib: invalid option -- q
> Making all in libxrdp
>   CC       libxrdp.lo
>   CC       xrdp_bitmap32_compress.lo
>   CC       xrdp_bitmap_compress.lo
>   CC       xrdp_caps.lo
>   CC       xrdp_channel.lo
>   CC       xrdp_fastpath.lo
>   CC       xrdp_iso.lo
>   CC       xrdp_jpeg_compress.lo
>   CC       xrdp_mcs.lo
>   CC       xrdp_mppc_enc.lo
>   CC       xrdp_orders.lo
>   CC       xrdp_orders_rail.lo
>   CC       xrdp_rdp.lo
>   CC       xrdp_sec.lo
>   CCLD     libxrdp.la
> ranlib: invalid option -- q
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: .libs/libxrdp.a: Malformed archive

Any pointers as to what causes that?

**Comment by metalefty** [comment]
Try the latest release. It should work fine.
