### ISSUE TITLE
Xvnc faster (less laggy) than x11rdp/Xorg drivers

### ISSUE THREAD

**Issue by nktl** [neutrinolabs/xrdp#386]
Hi,

I have been testing xrdp and it is a great piece of software. In order to make experience better, I built x11rdp binary as well as Xorg drivers (all using RH-Matic).

The problem is that when using Xvnc dekstop reacts almost instantly - there is virtually no lag.
However, when using both x11rdp and Xorg driver the experience is slightly worse. The difference is tiny (we are talking about something like 50ms vs 100ms latency) but you can clearly feel it.

This is quite surprising, as Xorg drivers (or x11rdp - which actually is even slower, but it i based on older source, so I suppose it is understandable) are supposed to be 'native' and provide superior experience, witn no VNC overhead, etc.

Is this normal or am I doing something wrong?

OS: RHEL 7.2, xrdp with drivers/x11rdp build from RH-Matic (tried both master and devel), Xvnc TigerVNC 1.3.1.

**Comment by metalefty** [comment]
When you feel slow, can you see the log like this in Xorg.*.log?

```
[903647.103] rdpDeferredUpdateCallback: reschedual rect_id 154481 rect_id_ack 154480
[903647.145] rdpDeferredUpdateCallback: reschedual rect_id 154481 rect_id_ack 154480
```

xorgxrdp and x11rdp are sometimes slow and sometimes fast.  It's slow during above logs are dumped.
I think this may a bug of xorgxrdp/x11rdp.

**Comment by nktl** [comment]
Correct, this is what I am observing @metalefty 

When this slight lag occurs (well, pretty much all the time), I am seeing a log of messages like the following one on the console:

`rdpDeferredUpdateCallback: reschedual rect_id 318 rect_id_ack 317`

The message is not there when using Xvnc (although I am not sure if this would even be visible in the log, due to different back-end).

Very quick test to replicate it (at least with my setup) is to click 'start' button in KDE 4 (vanilla RHEL 7.2, with "yum install @kde") - the menu appears virtually instantly with Xvnc, but with Xorg there is 200ms or so lag (with "rdpDeferredUpdateCallback" message in the log every time: usually it is just a single entry, but sometimes more - which introduces even more lag).

I would love to use xorgxrdp (better scaling, etc), but currently Xvnc delivers visibly better user experience with my setup. Any idea what the problem could be? I am happy to test this further.

**Comment by metalefty** [comment]
In addition, you see high CPU consumption of xrdp process and high network bandwidth consumption during the slight lag, right?  At least I see that.

I haven't clarified what the actual problem is however increasing log level may help us.  I added the option `--xorgxrdpdebug` to RH-Matic in develop branch.  Rerun RH-Matic with `--xorgxrdpdebug` and let's see ` ~/.local/share/xorg/Xorg.*.log`

**Comment by nktl** [comment]
Thank you, attaching the log from a short session that has this problem.

Not entirely sure about network/CPU - it generally hoovers around 10-15% at periods of intense activity.
[Xorg.17.txt](https://github.com/neutrinolabs/xrdp/files/329682/Xorg.17.txt)

**Comment by bolkedebruin** [comment]
@metalefty were you able to track this down? We are in the same situation: we would like to use Xorg but cant because users find it unacceptable due to the lag.

**Comment by johnarnold** [comment]
Ping for update.  I moved from xrdp 0.6.1-2 + Xvnc to 0.9.1-7 with x11RDP on Ubuntu 16.04 and there's significantly more latency.

**Comment by johnarnold** [comment]
Also, I just tested setting /etc/xrdp/xrdp.ini:
`autorun=Xvnc`

(force Xvnc instead of Xorg, which is the default first option).  Performace is better / back to normal.

**Comment by johnarnold** [comment]
How do you turn on Xorg debug logging to Xorg.*.log?

**Comment by coolemza** [comment]
u can use alternative rdp client in windows, like mRemoteNG and set 256 color mode, in this case performace will better

**Comment by kaysond** [comment]
Any update on this? I'm getting poor performance on xorg (though I haven't tried anything else; definitely way worse than native rdp on windows)

**Comment by crazy-blazer** [comment]
I also confirm problem using build-in Windows RPD client. Lag was about 2 seconds. mRemoteNG with 256 color mode ( Appearance bar ) works like a charm. No lags anymore. Thanks a lot @coolemza! #protip

**Comment by overpod** [comment]
I also confirm problem using build-in Windows 10 RDP clients

**Comment by mailinglists35** [comment]
is there any workaround that does not require user to recompile from source?

I asked also in neutrinolabs/xorgxrdp but "neutrinolabs locked and limited conversation to collaborators Oct 25, 2018"

**Comment by mailinglists35** [comment]
video in action (240 fps slow motion)

https://youtu.be/2UzpAEa_UUM

**Comment by mailinglists35** [comment]
config https://pastebin.com/A0hJ7GdH

**Comment by mailinglists35** [comment]
using remmina with default settings (no channels enabled on client, connection type "fast") gives instant mouse highlight movement over login dropdown menu, but once logged in is laggy again.

so I think there are two distinct issues, one with first connection screen, second with xrdp.

note that on login window there is no cpu spike, but on session afterwards I get high cpu from both xrdp and Xorg processes.

video https://youtu.be/zFfrmsBUjbQ

**Comment by myset** [comment]
In my case on Ubuntu 18.04.04 is very fast (90% form console performance) on xorg X11 and laggy on VNC (tigervnc-standalone-server).
I'm using xrdp-0.9.5-2 x64

**Comment by Bartolomejka** [comment]
In case of Ubuntu Remmina connecting to Ubuntu xrdp use **RemoteFX** in Colordepth field in properties. In case of GFX RFX, it is laggy probably because its implementation in xrdp (0.9.5) is not final. It is similar in Windows Remote Desktop Client connecting to xrdp, but here I don't know how to force it. But if I use the highest bandwidth in the menu, the performance is OK so it is probably not using the GFX RFX variant. Just to mention, if I am not doing it this way, than the clients are always taking 2Mbit/s of network traffic even if they are minimized.

**Comment by wsdookadr** [comment]
> Also, I just tested setting /etc/xrdp/xrdp.ini:
> `autorun=Xvnc`
> 
> (force Xvnc instead of Xorg, which is the default first option). Performace is better.

Truly a hidden gem

**Comment by metalefty** [comment]
Note: using Xvnc is not a silver bullet, **Xvnc is not always faster than Xorg driver**. Sometimes Xorg driver is faster, sometimes Xvnc is faster.  It depends on the graphic type to show. The only fact is Xvnc is faster **FOR YOU**. Xorg driver might be faster for someone else.

**Comment by metalefty** [comment]
Let's turn back to the original topic, "Xvnc faster (less laggy) than x11rdp/Xorg drivers"It depends on the use case but some causes that Xorg driver is slower are already fied, for example in neutrinolabs/xorgxrdp#94.

Any further reports should be posted with using the latest version. Not with outdated versions.

**Comment by wsdookadr** [comment]
@metalefty you're right. I did more than Xvnc in the above setting. I also bought a wifi adapter, specifically AC1300 TP-Link Archer T4U, had to change my router as well, now things are moving well.
`iptraf` reveals that RDP traffic is quite big, there's quite a bit of that going on, and the wifi adapter, as well as router need to support that kind of traffic. I found problematic that even some of the newer laptops come with low performance wifi built-in.
I think a note to users in the documentation of xrdp would be helpful here.

**Comment by apivovarov** [comment]
Xvnc (tigervnc-server) has an annoying bug - it does not support Input Language change in GNOME.
It ignores the selection of the input language and keyboard always prints in English.

Affected distros are RHEL, Alma, Fedora, CentOS, Rocky. For some reason they have `[Xorg]` session type commented out in `xrdp.ini`.

Ubuntu 22.04 and Debian 11 work fine - they have both `[Xorg]` and `[Xvnc]` sessions types enabled in `xrdp.ini` and `[Xorg]` is the default

Related Links and The Solution to the issue:
- [[XRDP] Keyboard always types in English regardless of selected Input Language](https://forums.fedoraforum.org/showthread.php?330477-XRDP-Keyboard-always-types-in-English-regardless-of-selected-Input-Language)
- [CentOS7 | xRDP on Xorg: VNC not supporting language switching](https://zotovp.wordpress.com/2023/03/19/centos7-xrdp-on-xorg-vnc-not-supporting-language-switching-centos7-xrdp-on-xorg-vnc-%d0%bd%d0%b5-%d0%bf%d0%b5%d1%80%d0%b5%d0%ba%d0%bb%d1%8e%d1%87%d0%b0%d0%b5%d1%82-%d1%8f%d0%b7%d1%8b%d0%ba/)
