### ISSUE TITLE
suppress session chooser on login screen?

### ISSUE THREAD

**Issue by coredump4** [neutrinolabs/xrdp#389]
Hi,
I was looking through the configuration directives as well as source, but I can't see a way to suppress the session chooser combo box shown on the login screen.  I'm only offering my users a single session, so I have no need for the combo box, and the login screen would be cleaner without it.  Is there a way to do this today?

TIA

**Comment by therevoman** [comment]
The way we achieve the desired behavior in our environment is to modify the autorun value in the /etc/xrdp/xrdp.ini file to match the session you wish to use as the default.  Then in the RDP client save a configuration with the credentials.  Then when you connect it bypasses the login screen.

**Comment by coredump4** [comment]
In my case, I want them to get the login screen in order to view a compliance banner before logging in... I was just trying to keep it tidy.

**Comment by metalefty** [comment]
```

**Comment by metalefty** [comment]
Remove session definitions except for what you want to use from xrdp.ini. Like this.

```diff
diff --git a/xrdp/xrdp.ini b/xrdp/xrdp.ini
index 34adb07..a6cf8aa 100644
--- a/xrdp/xrdp.ini
+++ b/xrdp/xrdp.ini
@@ -139,69 +139,6 @@ tcutils=true
 # for debugging xrdp, add following line to section xrdp1
 # chansrvport=/tmp/.xrdp/xrdp_chansrv_socket_7210

-[xrdp1]
-name=sesman-X11rdp
-lib=libxup.so
-username=ask
-password=ask
-ip=127.0.0.1
-port=-1
-xserverbpp=24
-code=10
-
-[xrdp2]
-name=sesman-Xvnc
-lib=libvnc.so
-username=ask
-password=ask
-ip=127.0.0.1
-port=-1
-#delay_ms=2000
-
-[xrdp3]
-name=console
-lib=libvnc.so
-ip=127.0.0.1
-port=5900
-username=na
-password=ask
-#delay_ms=2000
-
-[xrdp4]
-name=vnc-any
-lib=libvnc.so
-ip=ask
-port=ask5900
-username=na
-password=ask
-#pamusername=asksame
-#pampassword=asksame
-#pamsessionmng=127.0.0.1
-#delay_ms=2000
-
-[xrdp4]
-name=vnc-any
-lib=libvnc.so
-ip=ask
-port=ask5900
-username=na
-password=ask
-#pamusername=asksame
-#pampassword=asksame
-#pamsessionmng=127.0.0.1
-#delay_ms=2000
-
-[xrdp5]
-name=sesman-any
-lib=libvnc.so
-ip=ask
-port=-1
-username=ask
-password=ask
-#delay_ms=2000
-
-[xrdp6]
-name=rdp-any
-lib=librdp.so
-ip=ask
-port=ask3389
-
-[xrdp7]
-name=neutrinordp-any
-lib=libxrdpneutrinordp.so
-ip=ask
-port=ask3389
-username=ask
-password=ask
-
 [Session manager]
 name=Session manager
 lib=libxup.so
```

**Comment by coredump4** [comment]
I'm already doing that; I have a single Xorg session definition in there.  Still get the session chooser pull-down menu.  Shouldn't it auto-hide itself if there's only 1 session available?

**Comment by metalefty** [comment]
AFAIK we can't do that now, unfortunately.

**Comment by nan4k7** [comment]
Is there actually a solution for this? I'm looking for the same some years later.

**Comment by metalefty** [comment]
See: https://github.com/neutrinolabs/xrdp/issues/389#issuecomment-229668360

**Comment by nan4k7** [comment]
> See: [#389 (comment)](https://github.com/neutrinolabs/xrdp/issues/389#issuecomment-229668360)

Yeah I saw the comment... thought perhaps it could have changed because 8 years have passed or pehaps think it as  a request.
