### ISSUE TITLE
xrdp and pulseaudio support & documentation

### ISSUE THREAD

**Issue by bmullan** [neutrinolabs/xrdp#393]
Is this informaiton still valid ?   Its quite old (2013) so I was wondering if there was updated build information for xrdp & pulseaudio support.

http://www.xrdp.org/index.php?option=com_content&view=article&id=19:xrdp-pulse-sink

thanks
brian

**Comment by metalefty** [comment]
AFAIK it is outdated.

sesman/chansrv/pulse/pulse-notes.ubuntu.txt also needs to be updated but still valid.

**Comment by speidy** [comment]
the pulse module building instructions are OK.
you just don't need to create an default.pa file anymore.

I'll make an updated version of this to our  github wiki.

**Comment by speidy** [comment]
Iv'e updated wiki now, look [here] (https://github.com/neutrinolabs/xrdp/wiki/Audio-Output-Virtual-Channel-support-in-xrdp)

HTH.

**Comment by bmullan** [comment]
Thanks so much for the update to the docs.

I'd needed to rebuild the xrdp pulse modules but then saw most of the docs
seem to be from 2013 including the xrdp pulsaudio info so I thought I'd ask
in case I was looking in the wrong places for documentation.

Brian

**Comment by bmullan** [comment]
Idan..

I followed the instructions of the new wiki info but pardon my being dumb
but on the  page:

https://github.com/neutrinolabs/xrdp/wiki/Audio-Output-Virtual-Channel-support-in-xrdp

this section tells me what to do but then only says "copy the file"... I've
looked at all the directories involved and still
am not sure "what file" this is talking about ?

You need to edit the Makefile in order to build the pulse sink.
Edit PULSE_DIR at the top of the file to point to pulseaudio source
directory you extracted to above.
Then run make.
*Then copy the file *to pulseaudio system modules directory on your system:
for example: /usr/lib/pulse-2.0/modules/

After the "make" what file does someone need to copy to
/usr/lib/pulse-x.0/modules  ?

Brian

**Comment by speidy** [comment]
After 'make' is completed successfully you'll find an library called
module-xrdp-sink.so in the directory where you ran make.
בתאריך יום ב׳, 27 ביוני 2016 ב-19:24 מאת bmullan <notifications@github.com>:
