### ISSUE TITLE
Does xrdp compile for Pulseaudio support are both RDPSND channel and pulseaudio used?

### ISSUE THREAD

**Issue by bmullan** [neutrinolabs/xrdp#395]
I am using Guacamole & its RDP connection capability to connect to linux servers where I've installed XRDP.    

Per the Guacamole lead developer:

_Guacamole does not use PulseAudio for grabbing the audio of an RDP connection. It supports PulseAudio for VNC connections because VNC otherwise lacks its own standard support for audio, but with RDP the "RDPSND" channel will be used.

If you wish to use RDP, then the next step would be to determine why your RDP server is not providing audio via RDPSND. Though XRDP may well use PulseAudio behind the scenes, the RDP client (in this case: Guacamole) need not be aware of this; the RDP-facing side of this audio should be standard RDPSND._

I used scarygliders script to build xrdp/x11rdp with audio support (as best I understood the instructions) and on my test servers I have a /etc/xrdp/pulse directory with a /etc/xrdp/pulse/default.pa file.

So I'm puzzled if you have the above /etc/xrdp/sesman.in pointing to the script in /etc/xrdp/pulse/default.pa

Is XRDP still using RDPSND at all?   Does it send audio to both Pulseaudio & RDPSND channel simulaneously?

I tried searching for an answer to this but haven't found any clarity.   my .ini file has channels true & rdpsnd true ?    But I'm wondering if audio is sent via both rdpsnd channel & pulseaudio or only 1 of the two.

thanks
brian

**Comment by speidy** [comment]
Hi Brian,

Pulse Audio is just the local Linux audio server.
We use pulseaudio in order to get the audio output from Linux server, then
it is all sent over RDP in the rdpsnd virtual channel. (This is a sub
protocol for sending audio output from server to client over RDP)
So, yes xrdp uses the standard rdpsnd channel.

The thing is we only support raw PCM or opus audio encoding for now which
guacamole might not support (even though raw PCM format should be supported
by any RDP client)

Hth,

Idan
בתאריך יום ד׳, 6 ביולי 2016 ב-14:16 מאת bmullan <notifications@github.com>:

**Comment by bmullan** [comment]
Idan,

In regards to xrdp's use of pulseaudio, should xrdp handle the pulseaudio the same whether pulseaudio is setup in its normal "per user" mode or in pulseaudio's "system mode".   

And yes, I know the upstream Pulseaudio discourages use of "system mode" for a variety of reasons however in my "use-case" all of the pulseaudio & xrdp is within a single Ubuntu 16.04 server in which I have multiple LXD/LXC containers.   Each container is running Ubuntu also with Ubuntu-Mate Desktop Environment installed.

Each container is accessed via Guacamole's RDP to xrdp/x11rdp running in that container to get the Ubuntu-Mate desktop presented to the user.

If I implement Pulseaudio in the "host/server" in it's "per-user" mode sound/audio works from the container's OK (except there is 1 problem to work around which causes audio/sound to stop.).

My attempt to workaround this problem was to try configuring Pulseaudio in the Host/Server in its "system wide" mode so that Pulseaudio is loaded and available via Pulseaudio TCP from the containers even if no one is logged into the Ubuntu-Mate DE itself (re user-mode pulseaudio).

However, I set up the Host/Server for Pulseaudio "system wide" mode and in the Host/Server and in the Containers - PACTL LIST MODULES shows all modules loaded and available.  

Running "aplay /usr/share/sounds/alsa/Front_Center.wav" in the host or the Containers shows audio playing properly if monitoring via the Sound program's Input display... the bars move indicating sound/audio.

However, me as the "remote" user via Guacamole hear NO sound/audio.     

Guacamole should be relaying the sound/audio to me using the RDPSND channel which XRDP should be filling from Pulseaudio.

As I mentioned earlier... 

if Pulseaudio is setup in normal "per user" mode I DO hear audio/sound remotely.

if Pulseaudio is setup in "system wide" mode I DO NOT hear audio/sound remotely.

So it seems to me that XRDP must not be handling Pulseaudio properly & filling the RDPSND channel with the audio.

I am suspecting this "may be" because in Pulseaudio "system wide" mode Pulseaudio uses "/etc/pulse/system.pa"  for configuration and NOT its normal "/etc/pulse/default.pa".

My guess is that this somehow is related to XRDP's own use of "/etc/xrdp/pulse/default.pa".

Anyway I thought I'd ask.

Thanks
Brian

**Comment by bmullan** [comment]
Ok I spent more time with this today and it does seem as though xrdp doesn't continue to capture pulseaudio sound and pass it via the RDPSND channell *if* pulseaudio is run in "system wide" mode.

I tested this by starting pulseaudio in normal "per user" mode and audio from xrdp does come back to me (the remote user) via guacamole's RDP connection to that server.
audio  is generated on the server using:  aplay /usr/share/sounds/alsa/Front_Center.wav
also...  pavucontrol shows audio on the xrdp sink

Kill pulseaudio (sudo killall pulseaudio) and restart it in system wide mode 
sudo su
pulseaudio --system

again generate audio on server using:  aplay /usr/share/sounds/alsa/Front_Center.wav
and again... pavucontrol shows audio on the xrdp sink ... BUT ... no audio/sound is now heard by me remotely via Guacamole's RDP connection !

Since Guacamole doesn't know/care about Pulseaudio in its RDP connections only the RDPSND channel audio I'm thinking xrdp must somehow not be filling the RDPSND channel with that audio any longer even though its SINK shows audio present?

Any ideas what I could try or a log I could try to look at?

A simple way to view what I'm doing would be something similar to a headless RDP terminal server I guess.

thanks
brian

**Comment by speidy** [comment]
Hi Brian,

I didn't try PA "system wide" mode ever, but there are 2 things to be aware
of:
1. PA must load our sink (aka module-xrdp-sink.so).
in a normal per-user session we set (xrdp-sesman) the PULSE_SCRIPT env var
in the USER session to point to /etc/xrdp/pulse/default.pa file, which
instructs PA to load our pulse config file instead of the deafult per-user
config /etc/pulse/default.pa when X11rdp session  starts.

2. when pulseaudio loads our sink, it is relying on the DISPLAY env var in
order to send the audio data to the right xrdp-chansrv socket matching the
current session (aka channel server, which wraps the audio data into the
RDPSND channel and send it back to client).
(you can look at:
https://github.com/neutrinolabs/xrdp/blob/devel/sesman/chansrv/pulse/module-xrdp-sink.c#L311
)
The thing is, when you run pulse audio in a system-wide mode (as root), the
DISPLAY env var might be wrong / not set.

I don't think we thought about system-wide scenario, as it make not sense
to use it when you handle multiple different user sessions running on the
same box.

HTH.


בתאריך יום ד׳, 13 ביולי 2016 ב-23:00 מאת bmullan <notifications@github.com>:

**Comment by bmullan** [comment]
Idan

>>> I understand... and don't take me wrong.   I just thought with
Container's becoming such a "big thing" I'd try to communicate what I was
seeing with LXC
>>> even though its not Docker-style containers...

>I didn't try PA "system wide" mode ever, but there are 2 things to be aware
>of:
>1. PA must load our sink (aka module-xrdp-sink.so).  in a normal per-user
session we set (xrdp-sesman) the PULSE_SCRIPT env var
>in the USER session to point to /etc/xrdp/pulse/default.pa file, which
instructs PA to load our pulse config file instead of the deafult per-user
> config /etc/pulse/default.pa when X11rdp session starts.

I tried to overcome that by putting the following into the /etc/pulse/
system.pa file:

>>> load-module module-native-protocol-tcp
auth-ip-acl=127.0.0.1;IP-of-Containers auth-anonymous=1
>>> load-module module-xrdp-sink

and remember... as I said in my bug report... XRDP's SINK does show up
properly in "pavucontrol" output and DOES show data being passed its just
that
its not being passed to RDPSND from Pulseaudio SINK that says it sees the
data in....?

2. when pulseaudio loads our sink, it is relying on the DISPLAY env var in
order to send the audio data to the right xrdp-chansrv socket matching the
current session (aka channel server, which wraps the audio data into the
RDPSND channel and send it back to client). (you can look at:
https://github.com/neutrinolabs/xrdp/blob/devel/sesman/chansrv/pulse/module-xrdp-sink.c#L311
)
The thing is, when you run pulse audio in a system-wide mode (as root), the
DISPLAY env var might be wrong / not set.

>>> I can check this again?

I don't think we thought about system-wide scenario, as it make not sense
to use it when you handle multiple different user sessions running on the
same box.

>>> again... I think that the whole lot of attention being giving to
"Containers" may mean that Pulseaudio and/or those that use it to help make
Pulseaudio "system mode" work for more headless-type operation....
especially with "cloud".

thanks so much ...

Brian Mullan
Raleigh North Carolina USA.

HTH.

**Comment by speidy** [comment]
I see what you're saying regarding containers and its popularity.

I didn't use any of them yet.

Can you help me to understand why you want xrdp running inside a container ?
בתאריך יום ה׳, 14 ביולי 2016 ב-3:16 מאת bmullan <notifications@github.com>:

**Comment by bmullan** [comment]
Idan

Its getting late here.   Let me email you my use-case tomorrow.   I do not
think I'm alone in concept.  Thx

I can also share my 6 bash scripts to install everything on an ubuntu 16.04
server if you want to try it all

**Comment by bmullan** [comment]
Idan..

My concept/setup is to require a remote desktop user to access my cloud
servers (AWS and Digital Ocean) using only a web browser - which is what
Guacamole provides.

Guacamole is an HTML5 web proxy (called "guacd") running on tomcat on a
cloud host/server (re NOT in an LXC container but on the physical host).

Pulseaudio also runs only on the physical host/server ... NOT in the LXC
containers!


The user connects to Guacamole on the host/server then ... via
configuration I've already created selects one of several Desktop
Environments (DE) to log into.

The DE's I've setup are Ubuntu-Mate, LXDE and XFCE and each of them runs in
a separate LXC container on that same Host/Server.

Guacamole's GUACD supports SSH, VNC and RDP.    But only VNC and RDP
support a remote-desktop display to the end user.

I do NOT want to use VNC because then there is the additional management of
VNC's display port requirement...  which using RDP as the protocol does NOT
require.

I also want to use Guacamole's RDP capability because then later I can also
support end user's logging into Window's servers for a Windows Desktop too.

In each LXC container on the Host/SErver I've installed XRDP and X11RDP.

So the end-user in Guacamole selects a DE to log into and Guacamole sets to
the DE in that LXC container with an RDP session.

All of that works great, performance is great and I can even run a browser
in that LXC container and watch Youtube Video's and the Video's are just
like watching them from my own Desktop/Laptop performance wise.

However, since the LXC container's do NOT have direct access to the
Host/Server's  /dev/snd sound device I am using Pulseaudio's native-TCP
module to allow audio/sound in those Containers to be redirected to the
Pulseaudio "server" running in the Host/Server itself.


In the Host Pulseaudio is configured for TCP connections per (
https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Network/
)

so in /etc/pulse/default.pa (for per-user mode)..  default.pa contains the
following:

load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;10.0.3.0/24
 # note: 10.0.3.x is the IP subnet for all the LXC containers
load-module module-xrdp-sink
                   # so xrdp's "sink" is also present


In the Host/Server (re not in the Containers) the above 1st line enables
Pulseaudio to accept TCP connections from ONLY 127.0.0.1 (the host/server
itself) and also from ANY LXC container (10.0.3.x) but from no where else.

Now in each Container because of the Host/Server's Pulseaudio configuration
(those 2 lines above)... the Container  CAN see all of the Host's
Pulseaudio Modules even though the containers themselves have NO /dev/snd
device.

Also in every LXC container... EVERY user account inherits the Pulseaudio
Environment variable:

PULSE_SERVER=10.0.3.1

The above  PULSE_SERVER redirects any Pulseaudio sound to the Host/Server
(Host's IP address from within each container is 10.0.3.1).

So XRDP in each container takes the PulseAudio sound, puts it in RDPSND
channel so the end-user Guacamole RDP connection to the DE in that
Container can provide the audio/sound BACK to the remote user to hear.

My ONLY problem with Sound  in this setup is that UNLESS the User starts &
keeps open a Desktop Session to the Host/Server's DE... Pulseaudio (in
per-user mode) will not start and if it doesn't start then any DE session
the user has in one of the LXC Containers will work ... BUT ... it will not
have any sound/audio played remotely (because the container's need access
to the Host/Server's /dev/snd device.

As you are probably ware Pulseaudio's default is "per-user" mode and in
that mode Pulseaudio ONLY get's started for a User upon initially starting
a login session.

To make sure Pulseaudio in the Host/Server is ALWAYs running in the
Host/Server even if no User is logged into the Host/Server's own DE...   I
setup Pulseaudio in "system wide" mode.   This is basically what people do
with Headless server's they use for an Audio server in their homes or
businesses and perhaps the only legitimate use of Pulseaudio's
"system-wide" mode I know of.

As part of the Pulseaudio System Wide mode configuration I have to move the
2 statements:

load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;10.0.3.0/24
 # note: 10.0.3.x is the IP subnet for all the LXC containers
load-module module-xrdp-sink
                   # so xrdp's "sink" is also present


FROM /etc/pulse/default.pa ... TO .... /etc/pulse/system.pa    as in System
Wide mode Pulseaudio uses system.pa file instead.

Again, this ALL works and at Boot the Server/Host starts Pulseaudio and it
stays running.

As an end-user I can log in via Guacamole directly to any of the LXC
container DE's and use that Container's linux desktop to do "work".

BUT .... audio/sound no longer plays remotely for me.

As I'd mentioned in a message yesterday...  I DO see via PAVUCONTROL that
the XRDP SINK does show audio/sound in it.... its just that XRDP for some
reason no longer transfers that audio/sound to the RDPSND channell so
Guacamole can relay it to me remotely.

This has to be due to the fact that the Pulseaudio is running in "system
wide" mode now instead of the normal "per user" mode.

I hope this all makes sense to you as there are alot of moving parts.

Overall the architecture works really well except for the sticking point
with Audio.

I don't want to tell users they HAVE to start a Desktop session with the
Host/Server & just leave it open if they want to have Audio play from the
DE's in the LXC containers and running Pulseaudio in system wide mode
"should" be the way to support that.

If you'd like to try using this first hand we could exchange via email the
info you'd need (IP address to put in your web browser) and i can setup a
UserID/Password in Guacamole for you to log in with

Anyway thianks again.    This is a great use for xrdp and as soon as I get
this audio issue worked out I'm going to post my 6 bash scripts that
install everything auto-magically on Github along with a user guide I've
written so others can use it too.

Brian

**Comment by bmullan** [comment]
Idan...

I found the following comment regarding a difference in how Pulseaudio uses
DBus when run in "system wide" mode versus the normal "per user" mode:

reference raspberry pi thread (
https://github.com/masmu/pulseaudio-dlna/issues/159)


* the pulseaudio service in system mode is only exposing
org.pulseaudio.Server on the system bus, while in user mode also
org.PulseAudio1 is present and both endpoints are on the session bus.*
I do not know how XRDP normally picks up pulseaudio and transfers it to
RDPSND channel that Guacamole uses but perhaps that's a clue why when
Pulseaudio is in "system wide" there is no audio in Guacamole?

**Comment by bmullan** [comment]
Idan... in particular near the bottom of the thread (
https://github.com/masmu/pulseaudio-dlna/issues/159)

It points to the solution that the Raspberry Pi users/devs apparently found:
http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/ConnectingToServer/
*Lookup Service Details*

*To give some background information (and to document this stuff
somewhere), this is how server discovery works from PulseAudio's point of
view:*


*Contrary to earlier behavior, running the pulseaudio executable with D-Bus
support compiled in doesn't necessary start a proper sound server. *


*In certain circumstances only the server lookup service, as described
above, is started. *

*This happens in two cases: the executable is run by a non-root user and
the daemon is configured to run in the system mode, or the daemon
configuration just says that no local server should be started (which is
useful when only remote servers are intended to be used).*

*There is a new option in daemon.conf: local-server-type. Its value can be
either "user", "system" or "none". The default is "user". However, the
option conflicts with the old option system-instance. If system-instance is
set and local-server-type is not, system-instance value is honored. On the
other hand, if local-server-type is set, it overrides whatever is the value
of system-instance.*


*If user's pulseaudio executable isn't running when a client reads the
Address property, D-Bus automatically starts pulseaudio. *


*Depending on server configuration, a real sound server may be started, but
another possibility is that only the server lookup service is enabled. The
server lookup service, i.e. the Address property, works by first reading
the user's (or in absence of that, the system version of) client.conf.
client.conf too has a new option: default-dbus-server. *


*If it is set, then that value is returned to the client. *


*If default-dbus-server is not set, the address is deduced from the
local-server-type option: *

*in case of "user" the returned address is the unix socket of the user's
server (~/.pulse/:runtime/dbus-socket), in case of "system" the returned
address is the system server's unix socket (/var/run/pulse/dbus-socket),
and in case of "none" the returned address is an empty string.*

**Comment by bmullan** [comment]
Bump
