### ISSUE TITLE
odd shift key behavior

### ISSUE THREAD

**Issue by coredump4** [neutrinolabs/xrdp#397]
I have observed that if I press both shift keys together and then release one, I get lower-case characters even though one shift key is still being held.  "xev" confirms I get 2 KeyRelease events when a single shift key is released.  I've noted identical behavior with both Xvnc and xorgxrdp sessions.  By comparison, if I bypass Xrdp and use VNC directly, I don't have this problem.
I'm really not sure where to start looking for this problem.  Is it a key mapping problem or something else?  Any pointers on where to start looking would be appreciated.

TIA

**Comment by coredump4** [comment]
I'm still in need of guidance to track this down.  Logically, the offending code must either be in core Xrdp, or it's duplicated in the code for each backend.  However, I've not been able to locate it.  Any help appreciated.

**Comment by jsorg71** [comment]
What client is this?

**Comment by coredump4** [comment]
mstsc.exe from Win7 Pro.

**Comment by okhowang** [comment]
I notice that there is only `XR_RDP_SCAN_LSHIFT` in `xrdp_wm.c`.
there is no `XR_RDP_SCAN_RSHIFT`.
maybe it is the root of problem.

**Comment by metalefty** [comment]
I confirmed the original issue.
