### ISSUE TITLE
Python needs updating

### ISSUE THREAD

**Issue by geiseri** [neutrinolabs/xrdp#399]
Using openssl 1.0.2.h-1causes python to not build anymore.  I see this on Arch linux.  Is it possible to build with the system python2?

**Comment by metalefty** [comment]
I'll give it a try.

**Comment by metalefty** [comment]
I confirmed that x11rdp properly builds and works with python 2.7.11 the latest version of python2. 

I don't try to use system python2. It is still on TODO list.

**Comment by metalefty** [comment]
Jay said:
> Another option is that we just remove the first line from x11_file_list.txt.
> We don't really need to build python these days.

@jsorg71 @speidy 
I concern about that python2 executable has different name depends on system.  It will be python, python2 or python2.7.  One more concern is python3.  Arch Linux for example.

[Arch Wiki](https://wiki.archlinux.org/index.php/Python) says:
> Any program requiring Python 2 needs to point to /usr/bin/python2, instead of /usr/bin/python, which points to Python 3.

**Comment by speidy** [comment]
@metalefty, I'm not sure it's needed at all for Xorg to work.
בתאריך יום ה׳, 4 באוג׳ 2016 ב-10:56 מאת metalefty <notifications@github.com

**Comment by metalefty** [comment]
Python2.7 is indirectly  needed to build Xorg. Not needed to run built Xorg.
Python2.7 is needed to build xcb-proto.  xcb-proto is needed to build Xorg.

Removing the first line of x11_file_list.txt is no problem with Scientific Linux 7.

**Comment by geiseri** [comment]
This looks to be fixed now.  I think we can close the issue as fixed.  Thanks!

**Comment by metalefty** [comment]
We'll close after making change to use system python2.

**Comment by metalefty** [comment]
Tested on Ubuntu 16.04 and Debian 8, no problem.
Now I think we can remove python from x11_file_list.txt.
