### ISSUE TITLE
ElementaryOS: Luna - Failed to load session Gnome 

### ISSUE THREAD

**Issue by cameracode** [neutrinolabs/xrdp#40]
Got XRDP 0.7.0 with X11R7.6 to compile on ElementaryOS, tried modifying the startwm.sh script to accept a pantheon-session and no dice, on rdp7.1->xrdp connection it states, "Failed to Load Session Gnome." Is this an xrdp issue or a pantheon issue? xrdp process is running just fine like in any other Debian-based distro. I wonder if it's an issue with the desktop manager. ElementaryOS utilizes a gnome2 fork known as Pantheon.

**Comment by metalefty** [comment]
It seems to be solved.

**Comment by ianwalter** [comment]
`gnome-session --session=pantheon` doesn't work on elementary OS 5.0 Juno :( 
`xfce4-session` did work but I've never used that desktop and not sure I can get used to it.

**Comment by ghost** [comment]
Elementary OS 6.1?
Anybody?
