### ISSUE TITLE
I have a unique installation use-case where automatic login is needed

### ISSUE THREAD

**Issue by bmullan** [neutrinolabs/xrdp#400]
I looked through /etc/xrdp/sesman.ini and the /etc/xrdp/xrdp.ini and checked the man pages.

What I'm looking for is this.

Does xrdp (or could it) support an automatic/anonymous login.   On Ubuntu you can setup lightdm to allow users you specify in a .conf file to be automatically logged in.

Does such a feature exist in xrdp?   Or could it?    Reason I am asking is that I'm using Guacamole & its RDP connection capability to connect to Ubuntu desktop servers using xrdp.

However, users are required to double enter their ID & passwords.   First for Guacamole and then again when presented with the xrdp authentication login.

In my use case the users have to be configured in a Guacamole encrypted mysql dbms so if a "guacamole admin" configures them with an account I'd like to create the similar account on the ubuntu desktop servers (manually)... but when an end-user logs in to guacamole & selects an Ubuntu server to connect to ... I'd prefer they get logged directly into the target Ubuntu Desktop server than be reprompted by xrdp for another credential (ID & password) entry..?

Just fyi but Neutrinolabs & xrdp could benefit from this feature as well !    In case you weren't aware [Guacamole was recently accepted as an Apache Incubator Project](http://guacamole.incubator.apache.org/)   so this could provide a lot of synergy & integration of Guacamole & Linux via XRDP ... at least from a usability point of view.

Thanks for any guidance & info.

Brian

**Comment by allquixotic** [comment]
Any update on this? I'm hitting the same problem.

**Comment by bmullan** [comment]
If you are using Guacamole and xrdp you can take advantage of what Guacamole calls Parameter Tokens:

http://guacamole.apache.org/doc/gug/configuring-guacamole.html#parameter-tokens

In particular:
${GUAC_USERNAME}
${GUAC_PASSWORD}

If you use these 2 for the UserName and Password when you configure the "connection":

https://github.com/bmullan/ciab-remote-desktop/blob/master/CIAB%20-%20README.pdf

And use the same UserName & Password on your Linux system or Windows system that "connection" connects to then Guacamole will pass the UserName and Password to XRDP and the user will only have to enter them once.

Brian
