### ISSUE TITLE
Xrdp's VNC server is (still) insecure 

### ISSUE THREAD

**Issue by itamarjp** [neutrinolabs/xrdp#401]
more info at, 

https://bugzilla.redhat.com/show_bug.cgi?id=1250193

**Comment by metalefty** [comment]
The bug seems to be private. How can I see it? I already have bugzilla account.

**Comment by metalefty** [comment]
I see. It is restricted to RHEL subscribers.

**Comment by itamarjp** [comment]
[bz-1059555-patch.txt](https://github.com/neutrinolabs/xrdp/files/372759/bz-1059555-patch.txt)

**Comment by metalefty** [comment]
@moobyfr #545 solves this issue, right?

**Comment by moobyfr** [comment]
yes #545 does the job.
