### ISSUE TITLE
how to install xrdp in Solaris x86

### ISSUE THREAD

**Issue by alilunpard** [neutrinolabs/xrdp#41]
Hello,I have installed xrdp in Linux enviroment,it's great! Now I want to compile it in Solaris x86,but I got so many errors.can anyone tell how compile xrdp in solaris x86? Thanks!

**Comment by proski** [comment]
Please try xrdp 0.9.1 or the current devel branch. Please post the first 10 errors.

**Comment by metalefty** [comment]
Please reopen or create new issue if xrdp v0.9.1 still fails to compile.
