### ISSUE TITLE
black screen if hidelogwindow=yes

### ISSUE THREAD

**Issue by cocoon** [neutrinolabs/xrdp#414]
Hi!
I had the problem, that I got a black screen since the following commit if I set hidelogwindow=yes in xrdp.ini:

https://github.com/neutrinolabs/xrdp/commit/f49e2058dfd857b441daa4b18bcde6e341d8b9da

xrdp: change when using xrdp.ini hidelogwindow
jsorg71 authored on 2 Dec 2015

Problem seems to be the change from:

if (self->session->client_info->rdp_autologin)

to:
if (self->session->client_info->rdp_autologin || self->hide_log_window)

I only want to hide the "Log-Window" that appears if something wents wrong when clicking the OK button to connect and I had to change it back to have it working.

Maybe you can confirm it.

Best regards!

**Comment by jsorg71** [comment]
Yes, that is my fault, I'll fix it.
I need to add another option hideloginwindow for when user does not want the login window

**Comment by metalefty** [comment]
@jsorg71 Have this been fixed?

**Comment by cocoon** [comment]
No it's still in there:
https://github.com/neutrinolabs/xrdp/blob/devel/xrdp/xrdp_wm.c#L569

**Comment by metalefty** [comment]
OK, thanks. This is still marked as TODO.
