### ISSUE TITLE
Corrupted data in log (accessing IP address)

### ISSUE THREAD

**Issue by Natureshadow** [neutrinolabs/xrdp#421]
Here is another issue with logging IP addresses, probably related to #412 and maybe security-relevant:

[20160904-11:25:17] [INFO ] An established connection closed to
endpoint: NULL:NULL - socket: 11
[20160904-11:25:17] [DEBUG] xrdp_mm_module_cleanup
[20160904-11:25:17] [INFO ] An established connection closed to
endpoint: 97.114.47.114:12150 - socket: 23
[20160904-11:25:17] [INFO ] An established connection closed to
endpoint: 97.114.47.114:12150 - socket: 24
[20160904-11:25:18] [ERROR] Listening socket is in wrong state we
terminate listener

97.114.47.114 is an unknown, seemingly-random address that is in no way related to this connection. It seems to be a well-known issue when getting IP addresses from the socket:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=145088&repeatmerged=yes

See the bug report in Debian for more details: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836586

**Comment by metalefty** [comment]
Maybe duplicate of #381 and #411 fixes it.

**Comment by metalefty** [comment]
@Natureshadow Can you test #411?

**Comment by Natureshadow** [comment]
Yep, I will, once I work on xrdp again (scheduled for some time next week I guess, too much to do…).

**Comment by metalefty** [comment]
Now it's merged into devel branch.  You can test devel branch. Take your time.

**Comment by metalefty** [comment]
I confirmed this is fixed in Debian's 20161006 version.

**Comment by louisabraham** [comment]
Hi, I have an issue when hooking the `connect()` method of an application I inject on macOS.

When I launch it too soon, it just shows the exact same ip and port. Did you determine the origin of this IP?

**Comment by louisabraham** [comment]
Oh, I just found it.

The `sa_family` was set to 1, aka AF_UNIX. The `sockaddr` began with `2f 76 61 72 2f 72 75 6e 2f 73 79 73 6c 6f 67` which is `/var/run/syslog` in ASCII.

Python told me:

```python
>>> int.from_bytes(b'/v', 'big')
12150
>>> list(b'ar/r')
[97, 114, 47, 114]
```

**Comment by metalefty** [comment]
Raise your own issue.
