### ISSUE TITLE
What about a release?

### ISSUE THREAD

**Issue by Natureshadow** [neutrinolabs/xrdp#429]
Hi,

I am just updating the xrdp debian package (to the current HEAD).

(As a side note, right now I have a problem with make install doing nothing…)

After I got current HEAD building and working correctly, what would be missing to do a 0.9.0 release? The "dream" is to have a real 0.9.0 release for Debian stretch. Do you have an overview of what you'd like to get done before calling the version 0.9.0? Are you interested in doing a kind of "xrdp hackathon" or something to fix stuff, test and get a 0.9.0 alpha release ready?

**Comment by metalefty** [comment]
I also think making release tag is important.  IMO, one of the big blocking issue is #246.
What do other guys think?

At least I'm interested in "xrdp hackathon".

**Comment by Natureshadow** [comment]
Is #246 a regression in 0.9.0 (i.e. it used to work in 0.6.1)?

**Comment by wschlich** [comment]
+1 for a release!

Currently, it seems that x11rdp does not build with >=xorg-server-1.17.
Will that be fixed by the new release?

**Comment by metalefty** [comment]
Probably not.  x11rdp only supports xorg-server 1.9.3 but patches are welcome.
If you want to use higher version of xorg-server, try xorgxrdp.

**Comment by Natureshadow** [comment]
I understand x11rdp is somewhat deprecated. Am I mistaken?

In Debian, we build xorgxrdp and that works great.

**Comment by metalefty** [comment]
Yes. It it not deprecated right now but to be deprecated. You can use whichever you like for now.
But probably distributors don't like to pack x11rdp.

**Comment by Natureshadow** [comment]
Please, in any case, make the release 0.9.0 or newer. Please do not go back to 0.8.1 (as proposed elsewhere). That would mean a huge hassle for Debian (at least).

**Comment by metalefty** [comment]
We started to make a new release.  The new release will be 0.9.1.  0.9.0 has not been released yet however Fedora already has xrdp pacakge of a fake 0.9.0.  So not to confuse, we decided to skip 0.9.0 and release 0.9.1.

It will be released before the end of December to be in time for Debian stretch.

**Comment by Natureshadow** [comment]
Cool! Will it be based on the devel branch? It should not be missing features compared to the (so-called) 0.9.0.

**Comment by metalefty** [comment]
Yes, it will be released from devel branch (or from master branch after devel merged into master).

**Comment by Natureshadow** [comment]
Can we raise all the 0.9.0 version codes in the source to 0.9.1, then?

**Comment by proski** [comment]
All version numbers have been updated to 0.9.1. This issue can be resolved now. The release preparation is being done in #511
