### ISSUE TITLE
Does not start with IPv6 disabled

### ISSUE THREAD

**Issue by Natureshadow** [neutrinolabs/xrdp#432]
Disabling IPv6 completely (using `ipv6.disable=1`) on the Linux command line) leads to xrdp not being able to start.

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839266 for more details and logs!

**Comment by metalefty** [comment]
Is the debian package  compiled with --with-ipv6 option?

**Comment by metalefty** [comment]
It is true. Compiled with --enable-ipv6 option.

**Comment by metalefty** [comment]
Reproduced on CentOS 7.

1. Edit /etc/default/grub
2. Append "ipv6.disable=1" to GRUB_CMDLINE_LINUX
3. `# grub2-mkconfig -o /boot/grub2/grub.cfg`
4. Reboot
5. Edit X11RDP-RH-Matic.sh like following diff
6. `$ ./X11RDP-RH-Matic.sh --branch devel --nox11rdp`
7. `# systemctl start xrdp`
8. `# tail -f /var/log/xrdp.log`

~~~diff
diff --git a/X11RDP-RH-Matic.sh b/X11RDP-RH-Matic.sh
index 8e8b09d..fc39628 100755
--- a/X11RDP-RH-Matic.sh
+++ b/X11RDP-RH-Matic.sh
@@ -47,7 +47,7 @@ TARGETS="xrdp x11rdp"
 META_DEPENDS="rpm-build rpmdevtools"
 FETCH_DEPENDS="ca-certificates git wget"
 EXTRA_SOURCE="xrdp.init xrdp.sysconfig xrdp.logrotate xrdp-pam-auth.patch buildx_patch.diff x11_file_list.patch sesman.ini.master.patch sesman.ini.devel.patch"
-XRDP_CONFIGURE_ARGS="--enable-fuse --enable-jpeg --disable-static"
+XRDP_CONFIGURE_ARGS="--enable-fuse --enable-jpeg --disable-static --enable-ipv6"
 
 # flags
 PARALLELMAKE=true   # increase make jobs
~~~~

~~~
[20161012-17:47:57] [INFO ] starting xrdp with pid 2244
[20161012-17:47:57] [ERROR] xrdp_listen_main_loop: listen error, possible port already in use
~~~
