### ISSUE TITLE
Please keep submodules in sync

### ISSUE THREAD

**Issue by Natureshadow** [neutrinolabs/xrdp#433]
I propose to keep the sbmodules (librfxcodex and xorgxrdp) in the devel branch in sync with their respective devel branches.

In the Debian build, we use librfxcodec devel HEAD instead of the commit noted in the submodule (it doesn't even build with the referenced commit…).

Maybe switch to git subtree instead would also be an option (it would make getting a full source tree and such things a lot easier).

**Comment by metalefty** [comment]
+1

@jsorg71 , is there any problem to do that?

**Comment by jsorg71** [comment]
I know we are not keeping the submodules in sync.  That is mostly my fault.
I'm hoping to move more things into submodules.  There are pros and cons.  I like that the git history is more relevant to what your working on and they can be used in other projects.
Another pro is that you can work on the submodule and not break the parent until you do update the parents submodule.
The con here is that the submodule does not get updated when it should and you break a build.

**Comment by metalefty** [comment]
So can't update submodules right now?

**Comment by jsorg71** [comment]
No, you can, I edited the comment a bit.  I hope it's more clear.

**Comment by metalefty** [comment]
I see the edited commend and I understand.  
Would you merge #435 if you agree to update xorgxrdp and librfxcodec to each devel HEAD?

**Comment by Natureshadow** [comment]
Submodules are a PITA.

git-subtree nowadays is perfectly capable of merging and splitting subtrees into their own branches if you want. See subtree split, subtree merge, subtree pull and subtree push.

If you want to change something in the subtree, create a branch like you would for the main code.

**Comment by Natureshadow** [comment]
I had to track down librfxcodec not being up to date again today ☹.

**Comment by metalefty** [comment]
xorgxrdp has been removed. It can be compiled separately.
librfxcodec has been updated to fb80d7d.

**Comment by Natureshadow** [comment]
What will happen with xorgxrdp on release?

Will it be included in the source tarball? Will it be released seperately, with a srperate version number and all?

**Comment by proski** [comment]
I believe xorgxrdp will be released as a separate package.

**Comment by metalefty** [comment]
Now submodules are up to date. Closing.
