### ISSUE TITLE
"Protocol error" when attempting to connect from Microsoft's official Android RDP client

### ISSUE THREAD

**Issue by flarn2006** [neutrinolabs/xrdp#436]
I tried to connect to an XRDP server from my Android phone, using Microsoft's [Remote Desktop app](https://play.google.com/store/apps/details?id=com.microsoft.rdc.android&hl=en) for Android. Both times I tried, it failed to connect, telling me a protocol error occurred. Considering this is an official client by the same company that created the "standard", and not just some random program someone created, I think it's important that XRDP is compatible.

**Comment by Natureshadow** [comment]
Duplicate of #246?

**Comment by flarn2006** [comment]
Oh yep, that's the error I'm getting. I didn't see that when I looked through the issues. Thanks.
