### ISSUE TITLE
xrdp-dis does not work with xorgxrdp

### ISSUE THREAD

**Issue by ricardoteixeiraduarte** [neutrinolabs/xrdp#440]
xrdp-dis does not disconnect the session because "not in an xrdp session" due to file /tmp/.xrdp/xrdp_disconnect_display_<session> not present.

**Comment by metalefty** [comment]
It is not implemented so far. We need to do it.

**Comment by metalefty** [comment]
@ricardoteixeiraduarte Hi, I've implemented it. Can you test neutrinolabs/xorgxrdp#51?

**Comment by metalefty** [comment]
That feature has been implemented.
