### ISSUE TITLE
xrdp_wm_mouse_click should move the pointer to x,y before sending mouse click

### ISSUE THREAD

**Issue by ricardoteixeiraduarte** [neutrinolabs/xrdp#442]
Mobile Clients that allow the user to click anywhere, without moving the cursor, expect the server to move to the click position before processing the click.
As xrdp_wm_mouse_click function does not do that, the click will be sent to the current position the cursor is on and not to the position the user clicks.

**Comment by jsorg71** [comment]
But the move down and up have the x and y in them already.  We shouldn't need to do this.
Where do you see this, on the login screen or in a session?
I think this will break the right click menu issue we fixed a while ago.

**Comment by jsorg71** [comment]
I checked, this does not break the right click.
merged, thanks.
