### ISSUE TITLE
X11rdp crashes on adding keyboard layout

### ISSUE THREAD

**Issue by mpari** [neutrinolabs/xrdp#449]
X11rdp crashes when I try to add new keyboard layout (tried german, danish and couple of others). I am using latest development version, Centos 7.2, mate desktop. X11rdp keeps crashing after that and it's impossible to start new session until the ~/.config is removed. 

<pre>
*** Error in X11rdp: free(): corrupted unsorted chunks: 0x0000000002768ca0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7cfe1)[0x7f8066a78fe1]
X11rdp[0x42ab20]
X11rdp[0x42ea9d]
X11rdp[0x43423d]
X11rdp[0x48bd21]
X11rdp[0x40841a]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f8066a1db15]
X11rdp[0x4086f1]
======= Memory map: ========
00400000-005a7000 r-xp 00000000 fd:00 655367                             /opt/X11rdp/bin/X11rdp
007a6000-007a8000 r--p 001a6000 fd:00 655367                             /opt/X11rdp/bin/X11rdp
007a8000-007b6000 rw-p 001a8000 fd:00 655367                             /opt/X11rdp/bin/X11rdp
007b6000-007d6000 rw-p 00000000 00:00 0 
0271a000-0290a000 rw-p 00000000 00:00 0                                  [heap]
7f8064871000-7f8064898000 r-xp 00000000 fd:00 656426                     /opt/X11rdp/lib/libexpat.so.1.5.2
7f8064898000-7f8064a98000 ---p 00027000 fd:00 656426                     /opt/X11rdp/lib/libexpat.so.1.5.2
7f8064a98000-7f8064a9a000 r--p 00027000 fd:00 656426                     /opt/X11rdp/lib/libexpat.so.1.5.2
7f8064a9a000-7f8064a9b000 rw-p 00029000 fd:00 656426                     /opt/X11rdp/lib/libexpat.so.1.5.2
7f8064a9b000-7f8064d78000 r-xp 00000000 fd:00 656299                     /opt/X11rdp/lib/dri/swrast_dri.so
7f8064d78000-7f8064f78000 ---p 002dd000 fd:00 656299                     /opt/X11rdp/lib/dri/swrast_dri.so
7f8064f78000-7f8064f87000 r--p 002dd000 fd:00 656299                     /opt/X11rdp/lib/dri/swrast_dri.so
7f8064f87000-7f8064f8b000 rw-p 002ec000 fd:00 656299                     /opt/X11rdp/lib/dri/swrast_dri.so
7f8064f8b000-7f806553d000 rw-p 00000000 00:00 0 
7f806553d000-7f8065557000 r-xp 00000000 fd:00 656581                     /opt/X11rdp/lib/libxcb.so.1.1.0
7f8065557000-7f8065757000 ---p 0001a000 fd:00 656581                     /opt/X11rdp/lib/libxcb.so.1.1.0
7f8065757000-7f8065758000 r--p 0001a000 fd:00 656581                     /opt/X11rdp/lib/libxcb.so.1.1.0
7f8065758000-7f8065759000 rw-p 0001b000 fd:00 656581                     /opt/X11rdp/lib/libxcb.so.1.1.0
7f8065759000-7f806576e000 r-xp 00000000 fd:00 1441811                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f806576e000-7f806596d000 ---p 00015000 fd:00 1441811                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f806596d000-7f806596e000 r--p 00014000 fd:00 1441811                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f806596e000-7f806596f000 rw-p 00015000 fd:00 1441811                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
</pre>

**Comment by proski** [comment]
Please provide some context so that others can reproduce the issue. What exactly do you do to add keyboard layouts? Please run unstripped X11rdp if you can, it would provide a better backtrace.

**Comment by metalefty** [comment]
Please provide more information. Once close this.
Feel free to reopen if you add more information.
