### ISSUE TITLE
Does not build with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by Natureshadow** [neutrinolabs/xrdp#458]
Title says everything ;). I am working on a patch.

**Comment by itamarjp** [comment]
fixed in https://github.com/neutrinolabs/xrdp/pull/459

**Comment by Natureshadow** [comment]
It is not fixed before the PR is merged, and merging the PR will automatically close this issue.

Please re-open so everyone can properly track which issues exist in this repository and when they are fixed.
