### ISSUE TITLE
updates to xrdp.ini do not take effect after 'service xrdp restart' or 'systemctl restart xrdp'

### ISSUE THREAD

**Issue by cypa** [neutrinolabs/xrdp#484]
Welcome to the exciting new world of Ubuntu 16.04 - updates to xrdp.ini do not take effect after 'service xrdp restart' or 'systemctl restart xrdp' ... 'stop' and then 'start' does the thing 

how, the heck, does it possible?

**Comment by proski** [comment]
I guess they just send it SIGHUP and expect xrdp to follow the common convention, but it doesn't. We should fix it even if my guess is wrong. And we should tell Ubuntu to actually restart xrdp for now.

**Comment by metalefty** [comment]
Debian guys created a package of the latest xrdp.  Can you confirm if it works?  It's already available in Ubuntu 16.10.  Probably you can stay on 16.04 and use xrdp of 16.10.

**Comment by cypa** [comment]
shell see ... but I've already compiled xrdp from sources so it depends on my client's will

**Comment by moobyfr** [comment]
I've verified, `service xrdp restart` does really stop and start, the pid for xrdp and xrdp-sesman are modified.

**Comment by proski** [comment]
I think we need a very detailed description of the issue. Is xrdp from the Ubuntu package? What is the package version? What is the change to xrdp.ini? Basically, everything needed to reproduce the issue on another system by another person.

**Comment by moobyfr** [comment]
I've tried with fresh ubuntu 16.10, `service xrdp restart` shows new pid for both of them also and modifications are taken into account.

There could be perhaps another issue: you can't restart xrdp if there are opened connections. was that your case ?

**Comment by metalefty** [comment]
Need more description. The latest Debian/Ubuntu package should work.
