### ISSUE TITLE
pkg-config install path should be fixed for FreeBSD

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#498]
I've already talked about this in gitter chat.  The same thing should be done. 
I create an issue never to forget to do.

https://patchwork.kernel.org/patch/9394235/

> pkg-config from FreeBSD ports doesn't have ${prefix}/share/pkgconfig in the
> default search path, fix this by having a PKG_INSTALLDIR variable that can
>  changed on a per-OS basis.
> 
> It would be best to use PKG_INSTALLDIR as defined by the pkg.m4 macro, but
> sadly this also reports a wrong value on FreeBSD (${libdir}/pkgconfig, which
> expands to /usr/local/lib/pkgconfig by default, and is also _not_ part of
> the default pkg-config search path).
> 
>This patch should not change the behavior for Linux installs.

**Comment by proski** [comment]
Please see #499

**Comment by metalefty** [comment]
Now pkg-config install path can be overridden by `--with-pkgconfigdir` option.
