### ISSUE TITLE
XRDP does not support Audio Redirection

### ISSUE THREAD

**Issue by lchski** [neutrinolabs/xrdp#5]
I understand that XRDP, unfortunately, does not support audio redirection from the server to the client.

Hopefully there is someway for this to be included in the project, I see it is available through RDP itself, but I am required to have this server running on a Linux machine, and the client is a Windows machine.

**Comment by metalefty** [comment]
4.5 years old issue..

Now audio redirection works and instruction to setup audio redirection now documented in wiki.
https://github.com/neutrinolabs/xrdp/wiki/Audio-Output-Virtual-Channel-support-in-xrdp
