### ISSUE TITLE
Get client name

### ISSUE THREAD

**Issue by Almtesh** [neutrinolabs/xrdp#500]
I'm currently using the 0.9.0 from Debian Jessie Backport and I want to know how I could retrieve the client's name (which defaults to client's hostname) for each active connection.

**Comment by metalefty** [comment]
If you're talking about the client name included in [Client Core Data](https://msdn.microsoft.com/en-us/library/cc240510.aspx), you cannot retrieve it so far.

**Comment by Almtesh** [comment]
I think this is this one.
If this is not possible yet, it's a request for the next versions.
Thanks.

**Comment by metalefty** [comment]
Done in #699. The client name will be logged as "connected client computer name: %s".
If you want the log message format changed, for example client name should be logged together with client's IP address. Please reopen and comment.
