### ISSUE TITLE
Slow Video Performance

### ISSUE THREAD

**Issue by sblack1969** [neutrinolabs/xrdp#501]
I am in the process of replacing one of my development servers, going from Ubuntu 12.04 to 16.04.  On the new 16.04 server, I am experiencing slow performance when using xrdp/x11rdp.  It is most noticeable when dragging an open window - under 12.04 it is smooth and responsive, under 16.06 it is very choppy and slow.  Both servers are running xfce, everything works fine and performs well under the old 12.04 server.

I have experimented with countless configuration changes, different video settings, and various rdp clients, but I'm seeing the same video slowness under 16.04 no matter what I try.  Is anyone else seeing this?  Is there a systemd issue at play here?

**Comment by itamarjp** [comment]
please take a look in your xrdp settings, encryption level for example.

**Comment by sylvain121** [comment]
Hello, I have experiment same problem with xfce and ubuntu 16.04. 
I have disable compositor in xfce windows settings. Now it's work fine.

**Comment by metalefty** [comment]
probably as same as #386.

**Comment by sblack1969** [comment]
@metalefty - I agree, we are seeing same behavior as described in #386 including the same xorg log messages.  We have spent countless hours trying different settings in xrdp and xfce including disabling compositor and we really do feel it is a bug.  I don't think there is anything we haven't tried in order to resolve this.  We've had this working fine under 12.04 for years but the exact same settings under 16.04 are painfully slow, which leaves us dead in the water.  My company is at a point where we really need to resolve this and we are happy to put a bounty out there for whoever can track it down and fix it.  Is there anything you can do to help us out?

**Comment by dies137** [comment]
I have the same issue, but it became much better after passing network delivery part to the ssh.
Procedure of configuration is described here:
http://c-nergy.be/blog/?p=6020

**Comment by sblack1969** [comment]
@dies137 - Thanks, but I tried tunneling through ssh as you described and performance is still the same (if not a bit slower due to the added overhead of ssh).

**Comment by metalefty** [comment]
Let me merge this into #386.
