### ISSUE TITLE
xorgxrdp submodule wiki

### ISSUE THREAD

**Issue by limadm** [neutrinolabs/xrdp#505]
I couldn't find a xorgxrdp submodule in the xrdp repository.
Could you please update [this "Compiling and using xorgxrdp" wiki page](https://github.com/neutrinolabs/xrdp/wiki/Compiling-and-using-xorgxrdp) to point out to the correct repository?

**Comment by proski** [comment]
I have updated that page.

**Comment by metalefty** [comment]
It has been updated.
