### ISSUE TITLE
Tasks should be done before v0.9.1

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#511]
- [x] Disable rfx when the client is mstsc.exe to avoid drawing blank screen (#358, #508)
- [x] Close all issues which have v0.9.1 milestone
- [x] Merge all pull requests which have v0.9.1 milestone
- [x] Merge noorders
- [x] Merge  vncpassfile

**Comment by speidy** [comment]
#512 should fix the first one

**Comment by proski** [comment]
We need a similar issue for xorgxrdp

I checked the noorders branch. It brings in another library, libpainter. If rebased on top on the devel branch, the overall diff size is 65k, which is quite intrusive. It this goes in before 0.9.1, and 0.9.1 is released in December, there would be no time to test the new code well. I think noorders could be merged for 0.9.2. Some small self-contained fixes (such as unicode input) could go to 0.9.1.

No objections against vncpassfile, it's a security issue.

I don't have anything in my queue that needs to be in 0.9.1.

**Comment by metalefty** [comment]
I opened neutrinolabs/xorgxrdp#40 for xorgxrdp.  Please comment at the issue if you have xorgxrdp TODOs.

It makes sense not to include noorders into 0.9.1. What about releasing 0.9.1 without noorders and annotate incompatibility with Android clients as known issues?

Just keep releasing is important rather than fix all known issues in next release.

**Comment by Natureshadow** [comment]
>It makes sense not to include noorders into 0.9.1. What about releasing
>0.9.1 without noorders and annotate incompatibility with Android
>clients as known issues?

Except that the Android issue is one of the biggest issues Teckids (the organisation driving maintenance in Debian) and others were waiting for to be fixed.

**Comment by metalefty** [comment]
If the Android issue is fixed at 0.9.2 the next next release in March for examle, isn't it possible to take it to Debian 9? or Debian 9.1?

**Comment by Natureshadow** [comment]
Hi,

>If the Android issue is fixed at 0.9.2 the next next release in March
>for examle, isn't it possible to take it to Debian 9? or Debian 9.1?

Most probably not.

If you say it needs testing and you find it too risky to merge now, then it should go to Debian unstable, and it sure as hell doesn't qualify for just being dropped into a stable release of Debian.

I'd rather have it now, and if it is broken, then it is a bug that *can* be fixed in Debian 9.1.

**Comment by proski** [comment]
Every release will have its own "biggest unfixed issue".

If noorders has to be in 0.9.1, the noorders branch should be rebased on top of devel, cleaned up and submitted as PR for review in the next few days.

The rebase is possible (two files conflict, but no hard stuff), I did in in my fork https://github.com/proski/xrdp/tree/noorders

**Comment by metalefty** [comment]
I pushed proski's noorders. 

I backuped before rebasing noorders branch in my fork.
https://github.com/metalefty/xrdp/tree/noorders

**Comment by metalefty** [comment]
A new blocker issue #534 found.  I think we have no time to work on both noorders and #534.
We have to choose either one.

**Comment by metalefty** [comment]
speidy says it's a simple issue.  We may be possible to work on both.

**Comment by Natureshadow** [comment]
As the 0.9.1 release is primarily targeted to the Debian freeze, I am in favour of merging the noorders thing. We do not build without rfxcodec, but we do have Android users.

**Comment by metalefty** [comment]
#541 affects even if you build without rfxcodec. The good news is we already have a patch to fix it.

**Comment by Natureshadow** [comment]
Just a quick reminder that I need to upload 0.9.1 within the next 10 days.

How can I help make that happen?

**Comment by metalefty** [comment]
can you update xorgxrdp package to v0.2.0 tag?

**Comment by Natureshadow** [comment]
We do not build xorgxrdp seperately in Debian, we produce it in the same build, so it gets the same version number as xrdp.

xorgxrdp used to be bundled, and I do not see the point in seperating it.

The xorgxrdp in sid right now is what you call 0.2.0.

**Comment by metalefty** [comment]
OK. No problem except for xorgxrdp package version.

**Comment by jsorg71** [comment]
tomorrow I'll PR the rest of noorders, might be 2 PRs

**Comment by proski** [comment]
I made an "integration branch" 0.9.1-test #556 to enable testing of all 0.9.1 PRs at once.

I'm glad I did. It turns out an important patch the noorders branch was not submitted, so I submitted it as #557 and added to the integration branch.

I still see VNC authentication issues on reconnect. Let's keep #519 open and mark it to be fixed in 0.9.1.

**Comment by metalefty** [comment]
- [ ] Update README based on draft on wiki

**Comment by metalefty** [comment]
@Natureshadow 
FYI, now the current code in devel branch is equivalent to the v0.9.1 release.
we still have to write README, ChangeLog etc but no code changes before release.

**Comment by wschlich** [comment]
\0/ :+1:

**Comment by Natureshadow** [comment]
Great, will update the package tonight!

**Comment by speidy** [comment]
xrdp v0.9.1 has been released.
