### ISSUE TITLE
Password failed with libvnc on OSX 10.11

### ISSUE THREAD

**Issue by sgdc3** [neutrinolabs/xrdp#527]
Hello, i'm still trying to get xrdp working on osx, i've seen that @Bllacky was able to use the osx built-in vnc server by using the libvnc.0.dylib lib, i've tried many different configurations but i get always the "VNC password failed" message. I'm sure that the VNC server is working correctly. Do you have any idea why it fails to send the password to the server?

**Comment by metalefty** [comment]
Probably as same as #519. Will be fixed shortly.

**Comment by sgdc3** [comment]
so it is a duplicate? if so i'll close this and try the passfile branch.
