### ISSUE TITLE
Add a post-install hook for Xrdp on RHEL?

### ISSUE THREAD

**Issue by ghost** [neutrinolabs/xrdp#530]
This relates to https://github.com/FreeRDP/FreeRDP/issues/3645

After installing Xrdp, RHEL still needs 
```
# firewall-cmd --permanent --zone=public --add-port=3389/tcp
# firewall-cmd --reload
```

Can we add a note or hook to make this more obvious to the end user?

**Comment by proski** [comment]
This is a packaging issue. I don't think we should handle it in xrdp sources.

**Comment by itamarjp** [comment]
Please report this bug against

http://bugz.fedoraproject.org/xrdp
http://bugz.fedoraproject.org/freerdp

I don't think a package should change system-firewall without user knowing about, but if you file a bug We will find the best solution.

**Comment by sphaugh** [comment]
Reported in https://bugzilla.redhat.com/show_bug.cgi?id=1405172.

**Comment by itamarjp** [comment]
please add that informatiion into documentation, changes to system firewall can't be added in post install scripts.

**Comment by metalefty** [comment]
I think it is the common knowledge for a system administrator.

**Comment by metalefty** [comment]
Why not to the package documentation? README.Fedora for example.
