### ISSUE TITLE
Inclease maximum length of tls_ciphers

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#544]
The length of `tls_ciphers` parameter in xrdp.ini is limited up to 63 characters.
This is due to xrdp_client_info struct has a member tls_ciphers and its length is hardcoded as 64.

```C
struct xrdp_client_info
{
  (snip)
  int disableSSLv3; /* 0 = no, 1 = yes */
  char tls_ciphers[64];
  (snip)
};
```

To fully configure TLS cipher suites not using aliases such as HIGH, MEDIUM or LOW, the current maximum length is not enough.

Here's an example of cipher suites (for web servers):
https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by metalefty** [comment]
@speidy @proski can this be shipped to v0.9.2? What is the impact of increasing size of tls_ciphers?
Will it be safe? I think 1023 is long enough to specify even complex cipher suite.


https://github.com/neutrinolabs/xrdp/blob/devel/common/xrdp_client_info.h#L151

**Comment by proski** [comment]
Yes, I believe it can be extended to 1024 bytes. The field is located in the "safe to change" part of `struct client_info`.

We could use some kind of inheritance to hide the extended fields from the backends. If the backends still compile, it would ensure that they won't be broken by the change.

**Comment by proski** [comment]
I see that `struct xrdp_client_info` has two very different roles. One is the data that is read from `xrdp.ini`. Another is the data that is passed to the backends. The fix would be to have two structures, one for config, another for passing data. That's a lot of changes. It may be too much for 0.9.2.

But at least I understand now why `tls_ciphers` was added to `struct xrdp_client_info`. The only reason is because it's read from the config, not because it needs to be send to the backends.

**Comment by metalefty** [comment]
I remember you said that `xrdp_client_info` is becoming a god's object which knows everything before. I agree with cleaning it up after 0.9.2 release.

**Comment by proski** [comment]
I'm actually more specific now. But I don't have a simple fix for that. Even if we split the structure, the protocol for communication with the backends would remain fragile.

**Comment by proski** [comment]
Since `tls_ciphers` is not used by the backends, we can use a pointer and allocate memory dynamically. That way, there would be no size limit and no wasted memory.

**Comment by jsorg71** [comment]
The client info is a bit of a mess.  As a rule I was only adding items to the bottom, never add one in the middle and never increase an items size.  That second use, passing it to the modules(and if the module wants, to the backend) is what causes the problems.  Trying to support older modules with newer xrdp and vise versa is what the "add to end" rule was for.

**Comment by metalefty** [comment]
Ah, I already changed existing item in `xrdp_client_info` by #542.  `int disableSSLv3` has been changed to `long ssl_protocols`.

**Comment by metalefty** [comment]
I created #677 for review.

**Comment by metalefty** [comment]
Do you agree this should be fixed before v0.9.2?

**Comment by proski** [comment]
I agree. I hope to have more time for XRDP next week. I'll try to make a better patch.

**Comment by metalefty** [comment]
Done by #680.
