### ISSUE TITLE
Mouse events lost when re-connecting to an existing session with monitor with different geometry

### ISSUE THREAD

**Issue by bartw72** [neutrinolabs/xrdp#56]
When you start a session with 1980x1080 and change to another system and re-connect on 1900x1200, the lower part of the screen between 1080 and 1200 is not clickable. You can see the randr info set to current=1900x1200, and max is 1900x1080. Once you explicity set the xrandr with --size to the new geometry, the lower part is clickable again.

This example works for any geometry >= 1024x768 and using any bigger geometry after that. The xrandr output also displays the correct new geometry as current size. So the max geometry should be increased once the new geometry is bigger then the max geometry.

**Comment by moobyfr** [comment]
The problem doesn't appear in Xorg, the maximum size is 16384x16384
With current X11rdp, the new size is fully usable, but xrandr still have, for maximum resolution, the first resolution and refuse to resize with `xrandr --auto` (the current resolution is the new size)

**Comment by metalefty** [comment]
Reopen if the latest release (v0.9.1) still have the issue.
