### ISSUE TITLE
./configure fails when submodules aren't cloned

### ISSUE THREAD

**Issue by speidy** [neutrinolabs/xrdp#572]
When one forget to run `git submodule init` && `git submodule update`, the submodules folders will stay empty and `./configure` will fail.

I think we should always have submodules directories available when cloning xrdp.

Suggested solutions so far:
- adotp bootstrap 
- use git subtree instead of git submodule

This one is not for v0.9.1

**Comment by Natureshadow** [comment]
>I think we should trigger submodules clone somehow (maybe in
>`configure` or `bootstrap`)

No. The build is VCS-agnostic.

If you want to circumvent this issue, use git subtree instead!

**Comment by metalefty** [comment]
+1 to subtree

**Comment by speidy** [comment]
subtree is great as we talked in gitter chat.

**Comment by proski** [comment]
Actually, bootstrap is not part of the normal build. It's a developer's tool.

**Comment by proski** [comment]
PR #587 submitted, please review.

**Comment by proski** [comment]
An alternative fix is #593 - convert submodules to subtrees. Subtrees would be always there, they are part of the top-level repository.

**Comment by metalefty** [comment]
Switching to subtree is an good idea but this issue is now solved by #587.
