### ISSUE TITLE
One way clipboard - new feature request/contribution

### ISSUE THREAD

**Issue by VMelandri** [neutrinolabs/xrdp#573]
Hi all :)

I have the business case in which I want to limit the user's ability to use clipboard, but without cutting it off entirely.
In particular, **the user should be allowed to copy something on the client host, and paste it inside the xrdp session, but no the other way around** .

This feature does not exists yet and all there is is the option to disable the clipdr channel entirely.
That is fine, meets the minimum criteria I have, but makes for a horrible user experience :)

So I took a look at your code and made my own change to this, but I'm no C developer and I am not sure how you guys think it should be done.
What I did is:
1. added a feature flag in sesman.ini
2. made the clipboard.c module inside chansrv aware of the config (reads the flag in sesman.ini)
3. discard the events I do not want to take action on:

```
clipboard_xevent(void *xevent)
{
   // [..some stuff I did not touch..]

    switch (lxevent->type)
    {
        case SelectionNotify:
            if (restricted == 0) {
                log_debug("clipboard_xevent: clipboard SelectionNotify event on xorg.")
                clipboard_event_selection_notify(lxevent);
            } else {
                log_debug("clipboard_xevent: clipboard restricted, ignoring xorg event.")
                return 1;
            }
            break;

  //   [..some more stuff I did not touch..]

}
```

What do you think? did I go the completely wrong way? I would like to contribute this and make a pull request but I would like to discuss it first.
Cheers!

**Comment by proski** [comment]
I believe any patches that cripple xrdp functionality should not be considered for inclusion in xrdp. Some patches are better left outside the mainline codebase.

**Comment by MightyMel** [comment]
It's feature flagged (under the security section), why does it cripple it?

It's a feature in other RDPs, xrdp is only missing it.
In NoMachine, as an example, you can enable the 2 directions the clipboard goes separately (client to server or server to client).

it's a use case for any organization having data on the servers that need not leave the datacenter for legal reasons.

**Comment by MightyMel** [comment]
So the feature is a reasonable request (not crippling it), and I'm willing to do the code part, discussing the architecture of it with you guys, please take it seriously :)

**Comment by proski** [comment]
I see. Maybe it's not that unreasonable as it seemed initially. Maybe some users don't want their local clipboard to be polluted with the remote data accidentally. Especially if it can get them in trouble.

**Comment by MightyMel** [comment]
That is the point. :)Plus, it would not be the default behaviour. It's up to the administrator that sets up xrdp to enable this feature manually.

**Comment by Natureshadow** [comment]
+1, under that argumentation!

**Comment by MightyMel** [comment]
pull request is in :)
https://github.com/neutrinolabs/xrdp/pull/581

**Comment by kenhys** [comment]
This issue's scope was already implemented via https://github.com/neutrinolabs/xrdp/pull/1298
