### ISSUE TITLE
librdp.so module broken

### ISSUE THREAD

**Issue by proski** [neutrinolabs/xrdp#592]
The librdp.so module (RDP proxy) is not working with the current devel branch. That's the only module that reports its version as 2; other modules report version 3.

There are some differences in `struct mod` for librdp.so and the genetic `struct xrdp_mod`. The last common field is `si` in `struct xrdp_mod` and `sck` in `struct mod`, and it's not the same thing.

It is worth the trouble to fix librdp.so? What are the use cases? Isn't it obsoleted by libxrdpneutrinordp.so?

**Comment by speidy** [comment]
This module is obsolete. we should remove it.
for RDP proxy use neutrinordp module.
