### ISSUE TITLE
OpenSuse 12.1 and YaST through xRDP

### ISSUE THREAD

**Issue by cameracode** [neutrinolabs/xrdp#6]
Hello Fellas!

Been having a lot of fun compiling xRDP and trying different builds on different distros. Love the new stuff coming up with freeRDP. Through all my installations I would have minor problems depending on the distro that I could overcome with some research. My latest one is with Open SuSe 12.1 x86_x64 that is rocking the xfce4 interface. Did a vanilla install with the latest git versions of x11rdp and xrdp.

Got everything working through an x11rdp connection, (an xvnc connection doesn't allow mouse use). My main problem though is that Gnome based utilities like gnome calc, gnome character map, and more importantly YaST cannot be accessed through an xrdp session from a windows client. Other programs not working in an xRDP session are all gnome based games, multimedia stuff etc. Connecting locally YaST and Gnome based apps work just fine. When I go into terminal and try to launch /sbin/yast2 during an x11xrdp session I get back:

(y2controlcenter -gnome:6838): Gdk-WARNING **: The program 'y2controlcenter-gnome' received an X Window System error.
This probably reflects a bug in the program. The error was 'BadLength (poly request too large or internal Xlib length erro'. (Details: serial 66 error_code 16 request_code 131 minor_code 47) (Note to programmers: normally, X errors are reported asynchronously; that is, you will receive the error a while after causing it. To debug your program, run it with the --sync command line option to change this behavior. You can then get a meaningful backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by metalefty** [comment]
Closing aged issues. Please reopen or open new issue if this still happens with the latest xrdp.
