### ISSUE TITLE
Reconnecting to existing session with a different requested display resolution creates new session

### ISSUE THREAD

**Issue by dnadle** [neutrinolabs/xrdp#604]
xrdp v0.9.0, Centos 7:

If you disconnect an existing session and reconnect with the same user but with a different display resolution selected, you get a new session instead of the existing one.

**Comment by moobyfr** [comment]
from where came the xrdp, compiled from sources, or installed through a package ? which backend did you use? Xvnc, X11rdp or Xorg ?

**Comment by proski** [comment]
That's a documented limitation of the Xvnc backend. Other backends (X11rdp and Xorg) can resize.

**Comment by dnadle** [comment]
Thanks guys. I installed the xrdp rpm from EPEL, and it was using Xvnc. I have now compile xrdp and xorgxrdp from source and it's working, except I had some SELinux problems with colord and I'm still having an "authentication required for color managed device dialog" when my session starts. If I enter a password the gnome-settings-daemon crashes. If I hit cancel everything seems to work OK.

**Comment by metalefty** [comment]
Seems to be solved, closing.
