### ISSUE TITLE
Parallels Client (MacOS) drops the connection with 'Internal Error <131088>'

### ISSUE THREAD

**Issue by speidy** [neutrinolabs/xrdp#608]
When using Parallels Client with Audio Redirection turned on, the client is dropping the connection right after user logon to backend (Xorg for example).

I found that the reason for them to drop the connection is our propriety microphone implementation inside rdpsnd channel, which is working with rdesktop, NeutrinoRDP clients.

microphone redirection is not defined inside rdpsnd channel in MS doc ([[MS-RDPEA]](https://msdn.microsoft.com/en-us/library/cc240933.aspx)). they use another dynamic channel for microphone (as defined in [MS-RDPEAI] doc)

xrdp sends some extended microphone messages inside rdpsnd channel, which are in fact ignored by most of the clients (mstsc.exe, Android, etc.). Paralells client just drops the connection if they get an unknown message,  instead of ignoring it. 

I think we should talk to Parallels guys about that.

A quick 'patch' for this issue can be commenting out those lines: https://github.com/neutrinolabs/xrdp/blob/devel/sesman/chansrv/sound.c#L948-L949

**Comment by jsorg71** [comment]
I would not say it's propriety messages.  They are just a non MS extensions to RDPSND.  xrdp has this in a few other places and we should document them.
The client should simply ignore capabilities it does not understand.

**Comment by matt335672** [comment]
Addressed by #615
