### ISSUE TITLE
Read sesman.ini & comment said idle tmeout not supported

### ISSUE THREAD

**Issue by bmullan** [neutrinolabs/xrdp#617]
I was wondering if this is still the case ?

Searching the source it found statements concerning it.

**Comment by metalefty** [comment]
IIRC, it is not implemented yet.

**Comment by proski** [comment]
It is not implemented. The setting is passed to the X server environment as `XRDP_SESMAN_MAX_IDLE_TIME`. X11rdp reads and ignores that variable. xorgxrdp doesn't read that variable at all.

**Comment by metalefty** [comment]
I reuse this issue as TODO list.

**Comment by metalefty** [comment]
Solved by #1227 and neutrinolabs/xorgxrdp#132.
