### ISSUE TITLE
Unable to download from download url

### ISSUE THREAD

**Issue by ibigpapa** [neutrinolabs/xrdp#620]
I'm unable to reach the url HTTP://server1.xrdp.org/xrdp/X11R7.6 due to our corporate firewall.

Using the wayback machine i see looks like a folder of tar.bz2 files.  Are these files specifically this project or are they source for 3rd party libraries?

I'm able to get Github no issues.  So if it's just a matter of finding the sources/binaries for each file on another site I should be good to go.

**Comment by metalefty** [comment]
Sources put there are for x11rdp the one of backend.  xrdp works together with backend X server.

You can choose either x11rdp or xorgxrdp. But I recommend to use xorgxrdp. It almost replaces x11rdp.
https://github.com/neutrinolabs/xorgxrdp

If you want to stay on x11rdp, here's alternative mirror for x11rdp sources.
https://xrdp.vmeta.jp/pub/xrdp/X11R7.6/

**Comment by ibigpapa** [comment]
I was able to successfully build using xorgrdp

**Comment by proski** [comment]
Those files are not specific to X11rdp. It should be possible to commit those files to the xrdp github repository, but that would increase the clone time and the amount of storage even for the users who don't need X1rdp.

The current .git directory (i.e. all objects that are downloaded when the repository is cloned) is 19 megabytes. The tarballs would add 56 megabytes.

It should be possible to split X11rdp into a separate repository and add the tarballs to that repository. But I'm not sure it's worth the trouble. xorgxrdp is a viable alternative to X11rdp that is much easier and faster to compile, and that is approaching X11rdp in features.

**Comment by Natureshadow** [comment]
Umm… prebuilt tarballs are never, ever going into a source repository?

**Comment by proski** [comment]
Right, that would have to be unpacked tarballs. One thing is certain, we should not do in with the xrdp repository.

**Comment by metalefty** [comment]
As proski says, adding source tarballs which x11rdp depends on to the xrdp repository is not reasonable.
