### ISSUE TITLE
Windows RemoteApp can not be opened more than one

### ISSUE THREAD

**Issue by dudustone** [neutrinolabs/xrdp#623]
I can open multiple Windows RemoteApp application without going through the xrdp agent. When accessing an application published by Window RemoteApp via an xrdp proxy, the first application can be opened, but the client does not respond when a new application is reopened.

**Comment by speidy** [comment]
Can you test it with #624 ?
I think it should solve that problem.

**Comment by speidy** [comment]
Sorry, #624  should not fix that. 

But #625  should be a fix.
Can you try?

**Comment by speidy** [comment]
Can this issue be closed?

**Comment by dudustone** [comment]
This issue has been solved perfectly.Thank you very much.

**Comment by jumpwubo** [comment]
@dudustone how do you accessing remoteapp via xrdp?can detail, thanks
