### ISSUE TITLE
mp3 is not handy, need another audio codec

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#634]
xrdp now supports MP3 codecs in audio redirection via LAME encoder however it is not handy to distribute MP3 enabled xrdp in binary form. Because MP3 has patent issue. See Fedora wiki to know legal background.

https://fedoraproject.org/wiki/Multimedia/MP3
> Introduction
> -------------
> MP3 is currently the most widely used format for lossy music compression and is widely supported among music players. For a number of years, because of the legal issues relating to implementing MP3 support, Fedora was unable to include it at all.
> 
> However, as of 2016-11-10, Fedora is now able to include MP3 decoding functionality. MP3 encoding functionality is still not permissible, because it requires patented technologies and the patent holder has not provided licenses that are compatible with Fedora's requirements. 

As some distributions such as Fedora, FreeBSD don't distribute binary package of LAME because of patent issue. No LAME means it is not possible to create & distribute binary package of xrdp with MP3 enabled. This is not convenient for ordinary users.  (Actually, distribution of MP3 enabled xrdp itself may be allowed however it is useless without LAME binary because xrdp-chansrv is dynamic linked to libmp3lame.)

Opus is an totally open, royalty-free alternative to MP3 but unfortunately the most typical RDP client mstsc.exe doesn't support Opus.  We need to add audio codec support to provide users lower-bandwidth audio redirection.

Essential requirements:
* supported by mstsc.exe
* encoder is open source
* lesser patent protection than MP3 (no payments)

Prefered requirements:
* patent free
* encoder is distributed in binary form in many distro

AAC is one of candidates but there's still patent issue. One good news is no payments if I understand correctly.

**Comment by jsorg71** [comment]
I understand.  MP3 support added by @speidy works with mstsc but opus is a format that only works with NeutrinoRDP.  Newer MS servers support AAC and there is a branch in NeutrinoRDP where that works.  We could add AAC server support but that may have similar patent issues.
For a list of formats certain servers support see
https://github.com/neutrinolabs/xrdp/blob/devel/sesman/chansrv/wave-format-server.txt

One option is WAVE_FORMAT_ADPCM
I don't think there is patents on that but its lossless format.

I think the best we can do is make formats available and let whoever does ./configure decide.

**Comment by metalefty** [comment]
I talked to speidy about this issue before creating the issue.  He also said WAVE_FORMAT_ADPCM is a possible candidate.

**Comment by metalefty** [comment]
FYI: All MP3 patents will expire in 2017 at least in Japan ant the US.

**Comment by metalefty** [comment]
MP3 is coming back to Fedora since patent has been expired.
https://fedoramagazine.org/full-mp3-support-coming-soon-to-fedora/

**Comment by matt335672** [comment]
@metalefty - given mp3 is now available, do we still need this issue?

**Comment by metalefty** [comment]
Thanks for the reminding. LAME is back also to FreeBSD now. To be more exact, all patent limitations have been removed from FreeBSD ports tree. 

https://cgit.freebsd.org/ports/commit/audio/lame?id=6356d8c7e8a5b3311140aa8b74af61db9b595ae7


It would be still nice if we implement the ADPCM codec for some clients but the original issue is now relaxed. I would like to close this.
