### ISSUE TITLE
[init/systemd] use optional prefix and localstatedir

### ISSUE THREAD

**Issue by cocoon** [neutrinolabs/xrdp#639]
Hi, I am running multiple instances with different installation directories on one system.

Example:
`./configure --enable-neutrinordp --prefix=/opt/xrdp2 --localstatedir=/run/xrdp2`

To be able to use it, the init-scripts and now service-files need to be modified and renamed as it would overwrite the existing xrdp.service-file and xrdp-sesman.service-file.

For the init-script-template (https://github.com/neutrinolabs/xrdp/blob/devel/instfiles/init.d/xrdp) 
the Makefile.am (https://github.com/neutrinolabs/xrdp/blob/devel/instfiles/Makefile.am)
already replaces 
`"__BASE__" with "$(prefix)"`

Both need additionally the localstatedir.

Would be great if all would be handled by the scripts.

**Comment by proski** [comment]
I agree. Also, changing a file on `make install` is unexpected by the user. It's better to create a file in the build directory and then install it. An example can be found in `docs/man/Makefile.am`

The FreeBSD init script needs that change too.

**Comment by proski** [comment]
Specifically for systemd files, do you really envision having two files with the same name and different contents on the same system? I don't think it would work. The systemd files are primarily for packagers. Having them substituted would add extra work for contributing changes while offering no real benefit.

**Comment by cocoon** [comment]
Only do what makes sense.
Currently I do all of those modifications with a custom script and I move the init-scripts or service-files and rename them using the instance number, because I enable and disable those services on demand.

So it already would help if the init-scripts and service files would use the specified locations.

**Comment by metalefty** [comment]
@cocoon Talking about systemd service files,  it is done by #759. It now refers to localstatedir. Can you try? I still need to change `instfiles/init.d` and `instfiles/rc.d` files.

**Comment by metalefty** [comment]
Solved by #759.
