### ISSUE TITLE
Xvnc is not aware of monitor layout

### ISSUE THREAD

**Issue by proski** [neutrinolabs/xrdp#640]
When Xvnc backend is used with two monitors, dialogs appear in the middle of the combined screen, which makes them split between monitors. `xrandr` shows one `default` monitor. Contrast that with X11rdp and xorgxrdp backends, where `xrandr` shows two monitors, `rdp0` ans `rdp1`. Even the initial xrdp login screen is placed correctly on the first monitor.

We should pass monitor layout information to Xvnc to make it behave like other backends.

**Comment by nizmow** [comment]
This is old, but I'd really like it. I spent a while searching for a solution, and to me it seems like it may actually be an issue in the libvnc.so client code. I'm going to test it by running TigerVNC manually and connecting using "Any VNC". I know that TigerVNC nicely supports dual displays with the TigerVNC client, so if it's unsupported in xrdp then it suggests that libvnc.so could be enhanced.

**Comment by matt335672** [comment]
I'm pretty sure this was fixed with #1343 - feel free to reopen if not.
