### ISSUE TITLE
confusing message when max sessions exceeded

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#642]
When sessions limit exceeded, logwindow says "login failed for display 0".  This is not user friendly. The message should be "sessions limit exceeded". 

I looked at sesman, it seems sesman doesn't return the reason of login failure to xrdp. We should think about sesman design.  The reason of login failure should be reported to the user not just written to log.

![xrdp-mm](https://cloud.githubusercontent.com/assets/941609/22274255/a92f72ec-e2e8-11e6-89d9-1d57d8c54820.PNG)

**Comment by proski** [comment]
Likewise, failure to execute a backend should be reported to xrdp.
