### ISSUE TITLE
Include config_ac.h ① in all files, and ② first, before anything else

### ISSUE THREAD

**Issue by mirabilos** [neutrinolabs/xrdp#647]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852617#42 for a lecture from GNU autoconf upstream:

> If the real-world package is not including config.h first, then that is                                     
> a bug in the real-world package that should be fixed there.  Autoconf                                       
> clearly documents that if you create config.h, it MUST be included                                          
> first, before any system headers.                                                                           

The [workaround](https://anonscm.debian.org/cgit/pkg-remote/xrdp.git/plain/debian/patches/lfs.diff?id=e17430063641d44f5596b5bfc1b32ac4ba39f9f1) I had to add to the xrdp Debian package to enable and fix Large File Support was… not nice. So, apparently, the correct fix involves having __every__ __single__ source file (`*.c`, but also C++ et al.) `#include "config_ac.h"` first, *before* __any__ other `#include` or nōn-preprocessor statement (the inclusion from various header files, such as `arch.h`, can then be removed).

Child issues:
- https://github.com/neutrinolabs/xorgxrdp/issues/66
- https://github.com/neutrinolabs/librfxcodec/issues/15
- https://github.com/neutrinolabs/libpainter/issues/8

**Comment by metalefty** [comment]
All child issues are closed. Can this be closed?

**Comment by mirabilos** [comment]
If it’s also fixed in xrdp itself?

**Comment by metalefty** [comment]
I understand that this should be fixed in xrdp itself. I need to check.

**Comment by jsorg71** [comment]
The xrdp source is including config_ac.h through the inclusion of arch.h.
But if I understand, that is not good enough?

**Comment by mirabilos** [comment]
metalefty dixit:

>I understand that this should be fixed in xrdp itself. I need to check.

Well, it certainly makes no sense to only fix it in the subprojects ;)

Sorry if I was initially unclear.

bye,
//mirabilos
-- 
15:39⎜«mika:#grml» mira|AO: "mit XFree86® wär’ das nicht passiert" - muhaha
15:48⎜<thkoehler:#grml> also warum machen die xorg Jungs eigentlich alles
kaputt? :)    15:49⎜<novoid:#grml> thkoehler: weil sie als Kinder nie den
gebauten Turm selber umschmeissen durften?	-- ~/.Xmodmap wonders…

**Comment by proski** [comment]
It's better if the `*.c` files include `config_ac.h` directly. Including one header file from another should be generally limited to the situations when one header needs another header to be compiled successfully. Even then, forward struct declarations can help resolve interdependencies between headers.
