### ISSUE TITLE
xrdp and Google Summer of Code

### ISSUE THREAD

**Issue by itamarjp** [neutrinolabs/xrdp#657]
I think submitting xrdp as a organization in GSoC is too much work, but We can try under some partnership with an existing organization like Fedora, Debian or another one.

any volunteer to be a mentor  ?

**Comment by proski** [comment]
I was invited to be a mentor for Frescobaldi. You may want to see their documents as the starting point:
https://github.com/wbsoft/frescobaldi/wiki/Google-Summer-of-Code
https://github.com/wbsoft/frescobaldi/wiki/GSoC-Application

I'm ready to be a mentor. I'm not sure what would be a good project for GSoC. Ideally, it should be something self-contained.

Some ideas:
- Network Level Authentication
- Improved sound support
- More configurable login screen

**Comment by metalefty** [comment]
I'm interested in being a mentor if I could.

**Comment by metalefty** [comment]
No feedback from the reporter and GSoC 2017 has finished, closing.
