### ISSUE TITLE
Known issues with i3 window manager?

### ISSUE THREAD

**Issue by cro** [neutrinolabs/xrdp#662]
Greetings,

I have compiled xrdp 0.9.1 and xorgxrdp 0.2.0 from source on Ubuntu 16.10.  I use i3 as my window manager.  I've noticed when I disconnect from an RDP session, i3 goes to 100% CPU, and the session no longer responds to mouse input when I reconnect.  Most keyboard commands do not work either.  Does anyone have ideas of how to fix this or even troubleshoot it?

**Comment by metalefty** [comment]
https://github.com/i3/i3/issues/2701#issuecomment-327677279 says the issue no longer happens xrdp v0.9.3.1 with xorgxrdp v0.2.3. Closing. Feel free to reopen this issue if the issue still happens.
