### ISSUE TITLE
Cannot build on macOS Sierra

### ISSUE THREAD

**Issue by smccloud** [neutrinolabs/xrdp#671]
I am trying to build xorgxrdp 0.2.0 on macOS Sierra and it will not build.  The error I get is during the `./configure PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig` setp, the error is 

> checking whether the assembler (nasm -fmacho64 -DMACHO -D__x86_64__) works... no
configure: error: installation or configuration problem: assembler cannot create object files.

**Comment by smccloud** [comment]
Nevermind, I didn't have nasm installed, running brew install nasm fixed it.  Might help someone to have that in the directions at https://github.com/neutrinolabs/xrdp/wiki/Building-on-OSX

**Comment by proski** [comment]
nasm is mentioned in xorgxrdp wiki: https://github.com/neutrinolabs/xorgxrdp/wiki

nasm is not needed to build xorgxrdp unless `--enable-rfxcodec` is given to `configure`.

**Comment by Gaulomatic** [comment]
The reason for this is because the script will take `/usr/bin/nasm` and not the version installed by HomeBrew. I solved this by disabling SIP, renamed the original file and replaced it with a symlink to the home brewed `nasm`.
