### ISSUE TITLE
unicode copy/paste does not working  and breaks the clipboard

### ISSUE THREAD

**Issue by aauni** [neutrinolabs/xrdp#69]
server: xrdp+x11rdp on debian 6
clients: ubunut, win7,..

when users login to server clipboard works fine, but when they copy any unicode string and try to paste that in remote server, operation fails and also clipboard does not work for non unicode texts and they should relogin (logout/login not disconnect/connect) to server again.

**Comment by metalefty** [comment]
Now fixed in devel branch.
