### ISSUE TITLE
XRDP don´t connect with Xorg - CentOS 7.3

### ISSUE THREAD

**Issue by br-rafael-martins** [neutrinolabs/xrdp#703]
**SO:** CentOS Linux release 7.3.1611 (Core)
**XRDP:** Version 0.9.1
Xrdp installed via yum.

With Xvnc connect, but unexpectedly closes a session.

So I'am trying to connect using Xorg, but it does not complete a connection.

Below the messages and xorgxrdp.10.log

[xorgxrdp.10.log.txt](https://github.com/neutrinolabs/xrdp/files/856364/xorgxrdp.10.log.txt)
[messages.txt](https://github.com/neutrinolabs/xrdp/files/856365/messages.txt)

**Comment by proski** [comment]
This line shows you don't have a correct xorgxrdp install:
```
(EE) Unable to locate/open config file: "xrdp/xorg.conf"
```

Did you install xorgxrdp from sources or from yum? xorgxrdp rpm package is in updates-testing now. I suggest that you try it. Run this command to install it:
```
sudo yum --enablerepo=updates-testing install xorgxrdp
```

**Comment by br-rafael-martins** [comment]
Perfect, now is working !

But I used:

`yum --enablerepo=epel-testing install xorgxrdp`


With root the same problem of: https://github.com/neutrinolabs/xrdp/issues/655

**Comment by metalefty** [comment]
Reporter said finally it works, closing.
