### ISSUE TITLE
Fix for PAM configuration file for OpenSUSE

### ISSUE THREAD

**Issue by Cris70** [neutrinolabs/xrdp#705]
Hi, I read this in the "known issues for 0.9.1" page:

> There is no PAM configuration file for OpenSUSE. The generic file that is installed is not OpenSUSE compatible.

I have managed to correct the PAM configuration file on my openSUSE Tumbleweed.
Correct PAM configuration file is here:
```
#%PAM-1.0
auth       include     common-auth
account    include     common-account
password   include     common-password
session    include     common-session
```
Hope this helps...
Cris

**Comment by proski** [comment]
This is in git already.

**Comment by metalefty** [comment]
Yes, [instfiles/pam.d/xrdp-sesman.suse](https://github.com/neutrinolabs/xrdp/blob/devel/instfiles/pam.d/xrdp-sesman.suse) is what you want. It is introduced after release of v0.9.1.
