### ISSUE TITLE
libvnc vs X11rdp vs xorgxrdp | how to connect to existing session

### ISSUE THREAD

**Issue by tuxmartin** [neutrinolabs/xrdp#706]
Hi,
I have two questions:

1) I would like to replace commercial NoMachine NX with xrdp on my Mint 18 (Ubuntu based) pc.

99% of tutorials use libvnc.

I found X11rdp and xorgxrdp. X11rdp not have ubuntu packages, xorgxrdp has ubuntu packages from ubuntu 16.10+: http://packages.ubuntu.com/yakkety/xorgxrdp

What is the best to use?

2) What is the best way to connect to existing session?

I'm using this config (https://goo.gl/WLwB2W):

```ini
[xrdp1]  
name=existing-session  
lib=libvnc.so  
username=ask  
password=ask  
ip=127.0.0.1  
port=5910  
      
[xrdp2]  
name=new-session  
lib=libvnc.so  
username=ask  
password=ask  
ip=127.0.0.1  
port=-1
```

First time I connect to `new-session`. After that I using `existing-session`. Is possible to have only one section in xrdp? I have only one user of my computer, so I not need multiple sessions.

Thanks.

**Comment by metalefty** [comment]
To connect existing session, you have to do nothing special if you're using xorgxrdp. Reconnect with the same user, you'll get back to existing session.
