### ISSUE TITLE
Support "@" to separate username and domain

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#707]
I've just noticed Microsoft Remote Desktop Beta for Mac says that two different formats are acceptable to specify username and domain.

For example, 
* DOMAIN\bob
* bob@DOMAIN

In xrdp, domain name is used to specify session type. "Xvnc\bob" uses Xvnc backend for example. If it is not very complex to implement, let's support another format "bob@Xvnc".

![2017-03-22 14 22 19](https://cloud.githubusercontent.com/assets/941609/24183397/7e329a7a-0f0b-11e7-905a-0882b4e38ea9.png)

**Comment by speidy** [comment]
I think its a client side issue, the client should parse it and fill the username/domain fields

**Comment by metalefty** [comment]
Yes, I know Client Info PDU has separated field for username and domain but I cannot say which issue so far.

When backslash separated username/domain is given, the client parses it and fills both field. However, when at sign separated username/domain is given, it looks the client fills only username field with "username@domain".  I'm still not sure if it's a bug or specification.

If it's a specification, a server side hack needed to support at sign separated username/domain. Of course it is not necessary for us to do such a hack. We can leave it unsupported.

**Comment by proski** [comment]
I believe we should not change xrdp. Most (all?) clients can parse domain and pass it to the server.

In context of xrdp, the domain selects the backend. I don't think there is a good reason to support `usename@Xorg`, as Xorg is not a host or a location.

**Comment by metalefty** [comment]
OK. I'm incluned to change nothing in xrdp.
