### ISSUE TITLE
Printer Redirection Questions

### ISSUE THREAD

**Issue by user1492** [neutrinolabs/xrdp#71]
If xrdp is built using FreeRDP library support, then is it possible to redirect printers with xrdp?  If not, will this capability be available in future releases?  Has anyone tried to double redirect a printer? That is, log into a RDP session with a redirected printer, then log into another session with the first redirected printer to see if it in fact can be carried through and used end to end?

Thnxs

**Comment by astinsan** [comment]
The only option is to use cups to connect to a network printer. If your on a remote desktop internet printing protocol will work too. Other than that .. nope

**Comment by bmullan** [comment]
The last comment on this was in 2016...  so I thought I'd ask if there has been any progress on this.

As I use Guacamole with rdp connections to connect to ubuntu linux machines running xrdp I too am interested in any update on this topic as Guacamole has the ability to take a print job, convert it to PDF then transfer the PDF to the user's local machine/browser so it can be printed locally.
is printer redirection for xrdp in any future plans?

thanks
brian
