### ISSUE TITLE
Start operation timed out (Build and run on Xubuntu)

### ISSUE THREAD

**Issue by MichaelSweden** [neutrinolabs/xrdp#710]
I am using latest code, build and run on Xubuntu. However I have some problem and now I got a strange behaviour. After about a minute after login remote (rdp), it just disappear. I can see this in syslog; "systemd[1]: xrdp.service: Start operation timed out. Terminating.".

I do like this (after fresh installation of Xubuntu 16.10 and update):
$ sudo apt install gcc make autoconf automake libtool pkgconf nasm git
$ sudo apt install xserver-xorg-dev libssl-dev libpam0g-dev libxfixes-dev libxrandr-dev
$ git clone --recursive https://github.com/neutrinolabs/xrdp
$ cd xrdp
$ ./bootstrap
$ ./configure --enable-ipv6
$ make
$ sudo make install
$ cd ..
$ git clone --recursive https://github.com/neutrinolabs/xorgxrdp
$ cd xorgxrdp
$ ./bootstrap
$ ./configure
$ make
$ sudo make install
$ sudo ln -s /usr/local/sbin/xrdp /usr/sbin
$ sudo ln -s /usr/local/sbin/xrdp-sesman /usr/sbin
$ sudo systemctl enable xrdp
$ reboot

What do I do wrong?

Best regards
Michael

PS. Part of the syslog...
Mar 24 21:35:23 VerifyXrdp xrdp[1376]: (1376)(139992840853248)[DEBUG] Closed socket 16 (AF_INET6 ::1 port 33744)
Mar 24 21:35:23 VerifyXrdp xrdp[1376]: (1376)(139992840853248)[INFO ] The following channel is allowed: rdpdr (0)
Mar 24 21:35:23 VerifyXrdp xrdp[1376]: (1376)(139992840853248)[INFO ] The following channel is allowed: cliprdr (1)
Mar 24 21:35:23 VerifyXrdp xrdp[1376]: (1376)(139992840853248)[INFO ] The following channel is allowed: rdpsnd (2)
Mar 24 21:35:23 VerifyXrdp xrdp[1376]: (1376)(139992840853248)[DEBUG] The allow channel list now initialized for this session
Mar 24 21:36:32 VerifyXrdp systemd[1]: xrdp.service: Start operation timed out. Terminating.
Mar 24 21:36:32 VerifyXrdp systemd[1]: xrdp-sesman.service: Unit not needed anymore. Stopping.
Mar 24 21:36:32 VerifyXrdp xrdp[941]: (941)(139992840853248)[DEBUG] Closed socket 11 (AF_INET6 :: port 3389)

**Comment by metalefty** [comment]
Hmm, that looks strange. Can you confirm if it works in foreground?

```
# xrdp -ns
# xrdp-sesman -ns
```

**Comment by MichaelSweden** [comment]
Thanks

Running like that did work (I used sudo, or else didn't have rights to the log files). However after logout, I loose my local desktop on that machine.

I also tested to install xrdp from Ubuntu (i.e. sudo apt install xrdp), this on a fresh Xubuntu. Now I also got this timeout problem. Need to reboot twice. Now I'm lost, I don't understand whats going on. However I have had strange problem all the time while verify xrdp in my virtual machine. Need to reinstall many times. Sometimes not able to shutdown. I have a little special environment, a router also involved. I also remote my host machine, running VMs headless. Maybe my host (running virtualbox) needs a reboot.

Thanks for help. However right now I thinking about to skip doing my verification in a virtual machine. I will use a physical labb machine instead.

**Comment by metalefty** [comment]
No feedback from the reporter for a long time, closing.  Please leave a comment when you're back. I'll reopen the issue.

**Comment by prabhinmp** [comment]
im also facing the same issue
`● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; disabled; vendor preset: enabled)
     Active: failed (Result: timeout) since Thu 2021-10-14 09:52:10 UTC; 10ms ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)

Oct 14 09:50:40 tdk-instance xrdp[1024]: (1024)(140456066168640)[DEBUG] Closed socket 7 (AF_INET6 :: port 3389)
Oct 14 09:50:40 tdk-instance systemd[1]: xrdp.service: Can't open PID file /run/xrdp/xrdp.pid (yet?) after start: Operation not permitted
Oct 14 09:50:42 tdk-instance xrdp[1038]: (1038)(140456066168640)[INFO ] starting xrdp with pid 1038
Oct 14 09:50:42 tdk-instance xrdp[1038]: (1038)(140456066168640)[INFO ] address [0.0.0.0] port [3389] mode 1
Oct 14 09:50:42 tdk-instance xrdp[1038]: (1038)(140456066168640)[INFO ] listening to port 3389 on 0.0.0.0
Oct 14 09:50:42 tdk-instance xrdp[1038]: (1038)(140456066168640)[INFO ] xrdp_listen_pp done
Oct 14 09:52:10 tdk-instance systemd[1]: xrdp.service: start operation timed out. Terminating.
Oct 14 09:52:10 tdk-instance xrdp[1038]: (1038)(140456066168640)[DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
Oct 14 09:52:10 tdk-instance systemd[1]: xrdp.service: Failed with result 'timeout'.
Oct 14 09:52:10 tdk-instance systemd[1]: Stopped xrdp daemon.`
