### ISSUE TITLE
xrdp-sesman Startup Problems on Ubuntu MATE 16.10

### ISSUE THREAD

**Issue by andregasser** [neutrinolabs/xrdp#713]
Hi all,

I am currently facing an issue, where xrdp-sesman services does not start properly after rebooting the system. The xrdp service itself is up and running after reboot. Therefore, I can connect to port 3389 an see an xrdp login screen, but nothing happens after clicking the "OK" button.

xrdp version is 0.9.0~20160601+git703fedd-3.

I have setup the machine as follows:

1. Install Ubuntu MATE 16.10 from public ISO file.
2. Configure network connectivity
3. Install package updates using "sudo apt-get update" and "sudo apt-get upgrade"
4. apt reports some held-back packages, so I did a "sudo apt-get dist-upgrade" to install them as well (kernel update to version 4.8.0-41.52)
5. Install Open VM Tools using "sudo apt-get install open-vm-tools"
6. Install XRDP using "sudo apt-get install xrdp"

Now, after rebooting the system, xrd-sesman is not running. Thus, I cannot login to the system.

Do you have any hints on where to look further or what could be wrong?

Thank you very much,
André

**Comment by andregasser** [comment]
This is how the xrdp-sesman.log looks after initia reboot:

aco@macouba:~$ cat /var/log/xrdp-sesman.log
[20170327-14:16:21] [WARN ] [init:46] libscp initialized
[20170327-14:16:21] [CORE ] starting sesman with pid 2546
[20170327-14:16:21] [INFO ] listening...
[20170327-14:16:29] [INFO ] shutting down sesman 1
[20170327-14:16:29] [INFO ] An established connection closed to endpoint: NULL:N                                                         ULL - socket: 7
[20170327-14:16:29] [INFO ] An established connection closed to endpoint: NULL:N                                                         ULL - socket: 7
aco@macouba:~$

**Comment by andregasser** [comment]
One additional info:
After reboot, I can enter these commands manually and xrdp works well:

sudo systemctl start xrdp
sudo systemctl start xrdp-sesman

But services do not come up automatically after reboot...

**Comment by metalefty** [comment]
Looks like a distro issue.
