### ISSUE TITLE
[crash] [Systemd] neutrinordp cannot get homedir from env

### ISSUE THREAD

**Issue by cocoon** [neutrinolabs/xrdp#719]
I had a crash on Ubuntu 16.04.02 when running xrdp compiled with neutrinordp with systemd and then tried to connect using the nutrinordp modul to any ip.

I compiled with debugging enabled
```./configure --enable-neutrinordp --sbindir=/usr/sbin --enable-xrdpdebug```

modified the crash dump in /var/crash/_usr_sbin_xrdp.0.crash added a line
```Package:xrdp```

so that apport-retrace could use the crashdump:
```apport-retrace -s /var/crash/_usr_sbin_xrdp.0.crash```

and that lead me to:
https://github.com/neutrinolabs/NeutrinoRDP/blob/devel/libfreerdp-utils/file.c#L81

Then I found that others had this problem in the past, too:
https://glyptodon.org/jira/si/jira.issueviews:issue-html/GUAC-154/GUAC-154.html

```
Comment by Michael Jumper [ 2012-06-19 ]

This actually appears fixed upstream. Checking the latest from FreeRDP's git repositories, they now default to / if $HOME is unavailable.
```

I made a simple test and added an additional NULL check and set it to "/"
```c
        if(settings->home_path == NULL)
        {
                settings->home_path = "/";
        }
```

And after that it was not crashing anymore.

An additional fix is to set a username in the service file, then it is able to get the HOME var:

```
vi /lib/systemd/system/xrdp.service

[Service]
Type=forking
PIDFile=/var/run/xrdp.pid
EnvironmentFile=-/etc/sysconfig/xrdp
EnvironmentFile=-/etc/default/xrdp
User=root
...
```

then reload:
systemctl daemon-reload

just for documentation a helpful command:
```systemctl show xrdp.service```

**Comment by metalefty** [comment]
I think the issue should be fixed neutrinordp side.

**Comment by metalefty** [comment]
Solved by the fix on NeutrinoRDP.
