### ISSUE TITLE
xrdp-keygen error while loading libcommon.so.0

### ISSUE THREAD

**Issue by iliocatallo** [neutrinolabs/xrdp#72]
Hi,

I installed the latest version on the devel branch. Even if everything went fine during installation, xrdp refuses to start:

> sudo service xrdp start
> * Generating xrdp RSA keys......                                                                                                                                                                xrdp-keygen: error while loading shared libraries: libcommon.so.0: cannot open shared object file: No such file or directory

I'm running Ubuntu 13.04 64bit.  Thanks.

**Comment by metalefty** [comment]
submitter should run `make install`.
