### ISSUE TITLE
thinclient_drives is empty although drives selected in Win10 RDP client

### ISSUE THREAD

**Issue by myxor** [neutrinolabs/xrdp#720]
my thinclient_drives folder in my home directory seems a bit broken:

when i `ls -al` i shows something like this:
`d?????????  ? ?    ?          ?             ? thinclient_drives`

i can't access the folder neither can i delete it. When trying to delete it an error says that the 

> socket is still connected

`mount` shows:
`xrdp-chansrv on /home/mhe/thinclient_drives type fuse.xrdp-chansrv (rw,nosuid,nodev,relatime,user_id=1001,group_id=1001)`

I am using Xrdp 0.9.2 but this happened with 0.9.1 too.

Any idea how i can fix this?

**Comment by Natureshadow** [comment]
>my thinclient_drives folder in my home directory seems a bit broken:
>
>when i `ls -al` i shows something like this:
>`d?????????  ? ?    ?          ?             ? thinclient_drives`
>

That's not broken, it's normal behaviour of FUSE. Only the owner can stat a FUSE mountpoint, and root cannot stat it either. It's a (somewhat awkward) security measure.

-nik

**Comment by myxor** [comment]
Okay thanks, good to know.

I got it so far that i can access that folder by unmounting it and reconnecting via RDP.
Sadly the folder is empty except that `.clipboard` folder which is empty.

I connected via the Windows 10 RDP client and selected my C:\ drive to get mounted by the Server but it does not show up in the thinclient_drives folder.

**Comment by gkyildirim** [comment]
AFAIK if you disable printer redirection driver redirection works. If you enable printer redirection it does not!

**Comment by myxor** [comment]
Ah yes i got it working by starting the `vmtoolsd `on the host machine **before** connecting via RDP.

**Comment by gkyildirim** [comment]
Also there seems to be another issue (at least for me).  

At the first connection thinclient_drives is redirected. If you logoff and then logon you can not enter thinclient_drives folder any more. If you disconnect it is OK.  

My distro is Debian 8 and I use the latest commit (7a7445fefd9a61535881ceedf5ed82febb52d2dc).

**Comment by purvalpatel** [comment]
disable printer from RDP client machine.
when you logoff the user, then also the xrdp-chansrv is mounted on thinclient_drives folder of users home directory.
unmount it. and  then try to relogin again.
then drive redirection works.

**Comment by moriartynz** [comment]
Thanks. sudo umount thinclient_drives on the host, unsharing the printers on the client setup and the reconnecting solved this issue for me. I now have remote access to my local client drives! This was driving me nuts. Thanks so much.

**Comment by sangmoon** [comment]
``sudo umount thinclient_drives``
solved my problem too. thanks !

**Comment by r4tt4** [comment]
Hi, as I stucked at the same problem with Ubunutu 18.04 LTS here's my quick fix:

Edit 
**/etc/xrdp/startwm.sh**
add
**umount -f xrdp-chansrv**
to the top of that file, save, exit. 

Try it, works for me.

**Comment by Thoxvi** [comment]
This is a good way for me:

edit the `/etc/xrdp/sesman.ini`

```
# comment this line: L122
#FuseMountName=thinclient_drives

# and uncomment this line: L120
FuseMountName=/run/user/%u/thinclient_drives
```
