### ISSUE TITLE
LOGNAME env should be set

### ISSUE THREAD

**Issue by seidler2547** [neutrinolabs/xrdp#725]
In [sesman/env.c](https://github.com/neutrinolabs/xrdp/blob/6ed4c969f4d646a7751fe2da29ba94eddd3d6477/sesman/env.c#L134), the environment variable `LOGNAME` should be set to the same value as `USER`. I checked the source code of other X login managers, and it is being set there. There was even a bug in Firefox that makes [Firefox crash](https://bugzilla.mozilla.org/show_bug.cgi?id=1345438) when this isn't set.

**Comment by metalefty** [comment]
+1 
I was suffering from the Firefox bug. It is finally fixed since Firefox 52.0.2 but I agree that LOGNAME environment variable should be set.
