### ISSUE TITLE
Polish keyboard layout and AltGr

### ISSUE THREAD

**Issue by raczkowski1** [neutrinolabs/xrdp#73]
Hi

I need help with set Polish keyboard layout.
I try to generate file km-0415.ini but when I use this key-map  I can't use Polish character ( eg. AltGR+a) and arrow keys not work correctly.

How setup Polish keyboard?

Thank you.
Dariusz

**Comment by metalefty** [comment]
Polish keyboard was added  9656fa866619a9e19cd24c4de7f33927b8c7b816. Closing.
