### ISSUE TITLE
Support horizontal scroll wheel

### ISSUE THREAD

**Issue by seidler2547** [neutrinolabs/xrdp#730]
I don't actually have a mouse with a horizontal scroll wheel, but I use X11 Wheel Emulation with a mouse button. It would be nice if the horizontal scroll events would be handled by xrdp. These are mouse buttons 6 and 7 I believe.

**Comment by jsorg71** [comment]
I think they are handled now
https://github.com/neutrinolabs/xorgxrdp/commit/ea4e6a6f16a670289629bf73e60ca095cd45bc6e

**Comment by metalefty** [comment]
Horizontal scroll is not working for me, too. I looked at X events by `xev` but no events for horizontal scrill.

**Comment by metalefty** [comment]
Horizontal scroll is working with FreeRDP 1.1 but not working with mstsc, RDP for Mac.

**Comment by metalefty** [comment]
Client: FreeRDP 2.0.0-rc0
Server: xrdp v0.9.4 + xorgxrdp v0.2.4 

FreeRDP shows the following log and horizontal scroll is not working.
```
[12:41:00:622] [9080:0ac71000] [WARN][com.freerdp.core] - skip mouse event 0x0 flags=0x0578, no horizontal mouse wheel supported
[12:41:00:622] [9080:0ac71000] [WARN][com.freerdp.core] - skip mouse event 0x0 flags=0x0578, no horizontal mouse wheel supported
[12:41:00:740] [9080:0ac71000] [WARN][com.freerdp.core] - skip mouse event 0x0 flags=0x0578, no horizontal mouse wheel supported
```

When I connect to Win 10 with the same FreeRDP, horizontal scroll is working properly.

**Comment by metalefty** [comment]
Horizontal left scroll: flags=0x0478
Horizontal right scroll: flags=0x0578

**Comment by metalefty** [comment]
I grab this.

**Comment by metalefty** [comment]
@seidler2547 Can you try #928?

**Comment by seidler2547** [comment]
I'll try to make a build.

**Comment by seidler2547** [comment]
@metalefty can you remind me again how to make a debian package? Do I need to use X11RDP-O-matic? I can build your branch ok, so I could just replace the files in a test system, but I'd rather have a proper way.

**Comment by metalefty** [comment]
o-Matic is discouraged now. Maybe adding a patch of horizontal wheel feature to Debian package is the simplest way.
https://anonscm.debian.org/cgit/pkg-remote/xrdp.git/

**Comment by JakkuSakura** [comment]
when using RDP for Mac and its touchpad, horizontal scrolling is still not working

**Comment by CharmingPineapple** [comment]
For horizontal scroll you can send as flag PTRFLAGS_HWHEEL instead of PTRFLAGS_WHEEL
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/2c1ced34-340a-46cd-be6e-fc8cab7c3b17
