### ISSUE TITLE
How to switch keyboard layout on the welcome screen?

### ISSUE THREAD

**Issue by laigor** [neutrinolabs/xrdp#733]
How to switch keyboard layout on the welcome screen?

**Comment by metalefty** [comment]
Specify layout on client side.

**Comment by laigor** [comment]
How can I enter the password in English if at the time of connection the keyboard was in the Russian layout?

**Comment by hartois** [comment]
+1, I have same problem

**Comment by metalefty** [comment]
Enter your password not in welcome screen but client will help you.

For example,
![gfoq3](https://cloud.githubusercontent.com/assets/941609/26534002/c7e4fae4-445a-11e7-80b4-b45e664c9977.png)

**Comment by metalefty** [comment]
We have no plans to implement such feature.
Specify the layout at client side is the only option for the meantime.
