### ISSUE TITLE
Because of a security error, the client could not connect to the remote computer. Verify that you are logged on to the network, and then try connecting again.

### ISSUE THREAD

**Issue by sjsy** [neutrinolabs/xrdp#734]
I used xrdp version 0.6.1-2 on Ubuntu 16.04 and connected to it using win10 remote desktop connection.
I had two problems with it: 
1) environment variables differed in local/ssh session with remote session.
2) sometimes when I reconnect to the server remotely it make a new session and did not connect to the previous session.

So I tried to install 0.9.x version. I make and install it but its service did not start. So I reinstall 0.6.x version using apt and after some effort its service started but the new error appeared. When I try to connect to the server the following error appears:
>Because of a security error, the client could not connect to the remote computer. Verify that you are logged on to the network, and then try connecting again.

I reinstalled it many times but the error did not fix.
How can I resolve the error?

Thanks a lot.

**Comment by metalefty** [comment]
Can you show me xrdp.log and xrdp-sesman.log?

**Comment by metalefty** [comment]
No feedback from the reporter, closing.
