### ISSUE TITLE
xrdp 0.6.2 Compile error on Archlinux

### ISSUE THREAD

**Issue by nouman8** [neutrinolabs/xrdp#739]
ssl_calls.c: In function 'ssl_mod_exp':
ssl_calls.c:188:10: error: storage size of 'lmod' isn't known
   BIGNUM lmod;
          ^~~~
ssl_calls.c:189:10: error: storage size of 'lexp' isn't known
   BIGNUM lexp;
          ^~~~
ssl_calls.c:190:10: error: storage size of 'lin' isn't known
   BIGNUM lin;
          ^~~
ssl_calls.c:191:10: error: storage size of 'lout' isn't known
   BIGNUM lout;
          ^~~~
ssl_calls.c:209:3: warning: implicit declaration of function 'BN_init' [-Wimplicit-function-declaration]
   BN_init(&lmod);
   ^~~~~~~
In file included from /usr/include/openssl/asn1.h:24:0,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from ssl_calls.c:24:
ssl_calls.c: In function 'ssl_gen_key_xrdp1':
ssl_calls.c:333:30: error: dereferencing pointer to incomplete type 'RSA {aka struct rsa_st}'
     len = BN_num_bytes(my_key->n);
                              ^
make[2]: *** [Makefile:447: ssl_calls.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/trans.Tpo .deps/trans.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DXRDP_CFG_PATH=\"/etc/xrdp\" -DXRDP_SBIN_PATH=\"/usr/local/sbin\" -DXRDP_SHARE_PATH=\"/usr/local/share/xrdp\" -DXRDP_PID_PATH=\"/var/run\" -g -O2 -MT os_calls.lo -MD -MP -MF .deps/os_calls.Tpo -c os_calls.c -o os_calls.o >/dev/null 2>&1
mv -f .deps/os_calls.Tpo .deps/os_calls.Plo
make[2]: Leaving directory '/home/Downloads/xrdp-0.6.2/common'
make[1]: *** [Makefile:414: all-recursive] Error 1
make[1]: Leaving directory '/home/Downloads/xrdp-0.6.2'
make: *** [Makefile:346: all] Error 2

**Comment by metalefty** [comment]
@nouman8 Can you test #762?

**Comment by nouman8** [comment]
i can now compile xrdp 0.6.2 successfully with #762 
Thanks!!!
