### ISSUE TITLE
Can change caption in title bar of mstsc.exe

### ISSUE THREAD

**Issue by silenceli** [neutrinolabs/xrdp#75]
when use mstsc.exe to access remote server through xrdp proxy , the caption of mstsc.exe is xrdp proxy‘s ip. A lot of remote servers should be access and manage by me, so I can’t determine which remote server is.
Should someone know how to change the caption of mstsc.exe into the remote server‘s ip?
Can xrdp send a message to mstsc.exe which let it change the caption to real remote server’s ip?

**Comment by metalefty** [comment]
Maybe it can be done but on the client side.  There's nothing we can do on xrdp side.
https://www.experts-exchange.com/questions/21962818/Change-Remote-Desktop-Title.html
