### ISSUE TITLE
Default usage with Win10 (non-domain) fails with xrdp_wm_log_msg: Section "XXX" not configured 

### ISSUE THREAD

**Issue by cbutterfield** [neutrinolabs/xrdp#750]
I'm running Win10 Pro in a non-domain environment.  When sending a password the Win10 client seems to include a domain (generally the local machinename) as part of the username.  This causes xrdp to fail (unless the server has been carefully prepared ahead of time to avoid this).

The user experience is a black screen with no server generated dialog. 
The server xrdp.log shows: [ERROR] xrdp_wm_log_msg: Section "HPC15" not configured in xrdp.ini

It seems that using the client provided domain as a section name fails, without falling back to something else (such as showing the server-side dialog, or picking the first session section, etc).

I have been unable to coax my Win10 Pro system to NOT send a domain/machine name as part of the username.  I did finally find a workaround, namely to use the "autorun" parameter in the server xrdp.ini file.  But it would be much more end-user friendly to do something other that just showing a black screen.

I initially filed this as https://bugzilla.redhat.com/show_bug.cgi?id=1450681 but the maintainer suggested I move the request upstream.

Versions

- xrdp-0.9.2-10.fc25.x86_64
- Fedora-25
- Windows-10 Pro

Regards
P.S. I have found XRDP extremely useful on my projects.

**Comment by metalefty** [comment]
Could you show me your `xrdp.ini` and `sesman.ini`?

**Comment by metalefty** [comment]
OK, I understand your situation but what is the promlem? What do you want us to do?
Do you want a fallback if the domain name did not match any session type defined in `xrdp.ini`?

**Comment by metalefty** [comment]
@cbutterfield I've tried to make a fix. Could you see #758? The first section will be used so far. Do you want to specify which section to use as fallback?

For example, add new config like this to xrdp.ini and it will be used as fallback if the given domain name doesn't match any configured sections.
```
some_new_good_name=Xvnc
```

**Comment by metalefty** [comment]
@cbutterfield can you try?

**Comment by cbutterfield** [comment]
Sorry not to have responded.  Somehow I failed to notice ALL of the notifications over the last 3 weeks.  I'll try to catch up over the next day or two, and get the repo pulled and built on my system (Fedora 25).

In the meantime, **thank you very much** for putting time and energy into this.

Regarding your proposed fix of "the first section", that seems fine to me since I it is also consistent with what happens if "autorun=" is empty and NOT domain name is sent.

**Comment by cbutterfield** [comment]
OOPS - I have cloned https://github.com/neutrinolabs/xrdp.git but don't your changes there.

I looked at the web page you indicated https://github.com/neutrinolabs/xrdp/pull/758 but don't see how to clone whatever repo holds the info.  Basically, I don't know how to deal with "pull requests" on GitHub.

**Comment by cbutterfield** [comment]
Never mind, after cloning the devel tree I just scanned the first few lines of "git log" and didn't see your commit, but it did show up AFTER some commits from March.  That behavior of "git log" often trips me up, you would think I would have learned by now :-(

**Comment by metalefty** [comment]
@cbutterfield I've created RPM with current devel head 088bd2d for you. Try this. I recommend creating another new Fedora 25 environment and test it in there.

https://xrdp.vmeta.jp/pub/tmp/xrdp-0.9.2.git088bd2d+devel-1.fc25.x86_64.rpm
https://xrdp.vmeta.jp/pub/tmp/xrdp-debuginfo-0.9.2.git088bd2d+devel-1.fc25.x86_64.rpm

**Comment by cbutterfield** [comment]
I sorry it is taking me so long to test this.  It seems that you have fixed the issue I reported, but I am having some (presumably unrelated) problem getting my configuration running, probably due to the difference between the Fedora-25 downstream RPM and the more generic one you created.  I’ll try again this weekend.

------------------------------------------
Charles Butterfield, Chief Engineer
Next Century Corporation

Phone:  443-545-3100
Direct: 443-545-3113
Email:  Charles.Butterfield@nextcentury.com<mailto:Charles.Butterfield@nextcentury.com>
Web:    www.nextcentury.com<http://www.nextcentury.com/>

**Comment by metalefty** [comment]
Do you want new config to specify which section to use when given domain name didn't match any section? Currently, the first section will be used and it cannot be changed. I can add it if users want.

**Comment by metalefty** [comment]
@cbutterfield If you don't need to specify fallback session type, please close.

**Comment by cbutterfield** [comment]
I think what you have done is great.  I think using the first section as a fallback (just like an empty autorun= parameter).  I will close the ticket.  Thank you!
