### ISSUE TITLE
strange freezing of input (mouse/keyboard do not work suddenly, sort of)

### ISSUE THREAD

**Issue by cypa** [neutrinolabs/xrdp#756]
after some time of excellent experience suddenly found no response to mouse clicks and partial response to keypresses (chromium on RDP session responded ctrl-W, TAB and text enter, but ALT-TAB do not work)
reconnect freerdp (both Ubuntu 14 version and latest compiled FreeRDP), switching to win10 client do not help
lxsession, lxpanel in place on the server, nothing strange in xrdp logs ...  
killing chromium leads to total freeze of RDP-session (view of latest browser tab remains intact and no response to input)
it's Ubuntu 16.04 with latest xrdp+xorgxrdp release compiled on the server

**Comment by cypa** [comment]
ups ... it freezed again

**Comment by cypa** [comment]
`DISPLAY=:10 xev` shows no X events delivered to after RDP freeze

**Comment by biukcompression** [comment]
Has the problem been solved and why，

**Comment by matt335672** [comment]
Nothing like this has been reported for a while, so I'm closing this.
