### ISSUE TITLE
A dependency job for xrdp.service failed.

### ISSUE THREAD

**Issue by Lukyczk** [neutrinolabs/xrdp#757]
Hi,
Im getting this issue when building xrdp from source, not installing by apt-get. I am building it because of the Android client support. The service unfortanetuly doesnt start, and I dont know why. Here is the output from journalctl -xe: https://pastebin.com/jbTLT5Mv . Any help appreciated. Thanks

**Comment by metalefty** [comment]
Did you configured xrdp with `--prefix=/usr` option?

**Comment by metalefty** [comment]
I've made a fix. Can you try #759?

**Comment by Lukyczk** [comment]
1. No
2. Git cloned your repo and installed, got this https://pastebin.com/v0cKvF0R

**Comment by Lukyczk** [comment]
Could it be that I used ./configure <the options in the tut> --enable-painter (I need to be able to use the Android client) ?

**Comment by metalefty** [comment]
It doesn't affect any other arguments.  You can use `--enable-painter`.
