### ISSUE TITLE
Update www.xrdp.org links!

### ISSUE THREAD

**Issue by JonnyJD** [neutrinolabs/xrdp#76]
xrdp.org does include the news about the switch to github:
http://www.xrdp.org/index.php?option=com_content&view=category&layout=blog&id=1&Itemid=2

However, this is _not_ mentioned on the start page and all links still go to sourceforge.

I only found out there is a repository on github because I was confused that the repository is older than the last release and github is the first where I search.
Only after that I also found the news in xrdp.org

Searching in Google the first repository I find after SF is gitorious, where there also isn't a note that the new repository is at github.

**Comment by metalefty** [comment]
Now www.xrdp.org have links to 0.9.1 release.
