### ISSUE TITLE
Problem with NUMLOCK

### ISSUE THREAD

**Issue by mightyraven** [neutrinolabs/xrdp#760]
hi all. 
When connecting to a remote server (on the client the NUMLOCK key "on"), NUMLOCK does not work, press NUMLOCK to "off" everything works. 
When connecting to a remote server (on the client the NUMLOCK key to "off"), NUMLOCK does not work, press the NUMLOCK "on" - everything works. 
Why this inversion NUMLOCK? 

Debian 8. xrdp compiled from the source files.

**Comment by jsorg71** [comment]
What client is this?  The client is supposed to sync the modifiers on connection.

**Comment by mightyraven** [comment]
windows7 (connect with mstsc)

**Comment by playmobil77d** [comment]
Hi I have the same bahavior.
I am using the windows client on Windows 7, with XRDP 0.9.5 and XFCE (xfce4-panel 4.12.0 (Xfce 4.12)).

I noted this behavior:
- open mstsc (numlock On)
- I type the password and connect and just after that, I change numlock to OFF
- the connection is opened, nulock is OFF and I can't use numpad
- I turn numlock to ON, and we can use the numpad.
But, the is a very short time window to do those action to correctly synchronize numlock.

I don't know if this can help.

**Comment by playmobil77d** [comment]
New thing, when I type CTRL+SHIFT+NumLock, this re-synchronise the numlock between mstsc and xfce.

I don't know what trace I can make to help to debug this thing.

**Comment by playmobil77d** [comment]
Hi, today, I found the problem on my side.
I was a bad configuration on XFCE.
By default, there is a parameter set to true: Restore num lock state on startup.
By typing this command:
`xfconf-query -c keyboards -p /Default/RestoreNumlock -n -t bool -s false`
I solve my problem.

I hope this can help somebody later.

**Comment by metalefty** [comment]
The issue was reporter's local issue, closing.

**Comment by g00dee** [comment]
The problem is solved like this:
1) install the package "numlockx"
**apt install numlockx**
2) in the Autorun of applications, add the script (command) to launch the program (trigger - on login) 
**numlock on**
