### ISSUE TITLE
--variable=systemdsystemunitdir: command not found

### ISSUE THREAD

**Issue by pestalent1** [neutrinolabs/xrdp#763]
II am trying to install xrdp-0.9.1 and I get this error when running   ./configure PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

 I have installed "brew install openssl"

./configure: line 12138: --variable=systemdsystemunitdir: command not found
checking for dlopen... yes
checking for OPENSSL... no

**Comment by metalefty** [comment]
`--variable=systemdsystemunitdir: command not found` is not an error.

**Comment by metalefty** [comment]
Is not an error.
