### ISSUE TITLE
Unable to change the default logo

### ISSUE THREAD

**Issue by adocampo** [neutrinolabs/xrdp#772]
I've compiled xrdp + xorgrdp from sources for Ubuntu 16.04.2LTS.  So far soo goo :)

Now I'm trying to make the server more corporative by changing the logo, but I'm stuck with it.

I used a BMP with the same size and ppi as the original xrdp_logo.bmp, I've tried also both specifying the ls_logo_filename parameter on xrdp.ini and overwritting the original xrdp_logo.bmp. No luck with any.

journalctl says, when a client connects: 
[ERROR] xrdp_bitmap_load: error bitmap file [/usr/local/share/xrdp/ajuntament.bmp] bad bpp 32

Which made me think the deep information was wrong, so I exported it with GIMP, and under advanced exporting BMP settings I selected 32 bits (X8 R8 G8 B8) whatever it means.

Is there any guide to change the logo?

Thank you!

**Comment by metalefty** [comment]
If possible, could you upload the bitmap file? Then I can reproduce your issue.

**Comment by adocampo** [comment]
Forget it... I'm a complete noob with gimp and surely I did something wrong.
Opening the same png image with Kolourpaint and saving it as Windows Bitmap works as expected.

**Comment by ibaraki-douji** [comment]
For people struggling with this :

I checked on both program and it work with Kolourpaint because by default it export with 24 bits not 32.
And for Gimp using the BMP export with a 24 bits works too. (both 32 bits fails)

**Comment by ernstki** [comment]
You can also use ImageMagick to convert from another format. For example:

```bash
convert -define bmp:format=bmp3 /usr/share/icons/gnome/32x32/devices/system.png system.bmp
```

I believe that alpha (transparency) support is only present in 32-bit bitmaps, so keep that in mind if you have a transparent GIF or PNG that you're trying to use as your xrdp login window logo.

On a Debian/Ubuntu system, you'd think that the filesystem path to the logo would be inferred, if the logo is present in `/usr/share/xrdp` (where the other logos and cursors are), but I found that not to be the case, and had to specify a full filesystem path, like this:

```ini
ls_logo_filename=/usr/share/xrdp/system.bmp
```

Hope that helps somebody.
