### ISSUE TITLE
xrdp 0.9.1, ubuntu 16.04 can't see a desktop on login

### ISSUE THREAD

**Issue by bmullan** [neutrinolabs/xrdp#774]
I normally use guacamole to access my ubuntu 16.04 machines with MATE desktop installed, which run xrdp and it works very well.

I have been trying for several days to get the new xrdp & xorgxrdp to work for me but whether I attempt to log in with guacamole, rdesktop or freerdp I fail to see a desktop.   xrdp asks for my login/password and is connection type set to default of "Xorg"

upon login with my ID/password all **/var/log/syslog** shows is...

$ tail /var/log/syslog
Jun 14 09:42:26 guac-test xrdp[3026]: (3026)(139758598113024)[INFO ] xrdp_wm_log_msg: sesman connect ok
Jun 14 09:42:26 guac-test xrdp[3026]: (3026)(139758598113024)[DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
Jun 14 09:42:26 guac-test xrdp[3026]: (3026)(139758598113024)[DEBUG] return value from xrdp_mm_connect 0
Jun 14 09:42:26 guac-test xrdp-sesman[1345]: (1345)(139871253182208)[INFO ] ++ reconnected session: username bmullan, display :10.0, session_pid 2415, ip 0.0.0.0:47104 - socket: 12
Jun 14 09:42:26 guac-test[3026]: (3026)(139758598113024)[INFO ] xrdp_wm_log_msg: login successful for display 10
Jun 14 09:42:26 guac-test xrdp-sesman[1345]: (1345)(139871253182208)[DEBUG] Closed socket 8 (AF_INET6 ::1 port 3350)
Jun 14 09:42:26 guac-test xrdp[3026]: (3026)(139758598113024)[DEBUG] xrdp_wm_log_msg: started connecting
Jun 14 09:42:28 guac-test xrdp[2229]: (2229)(139758598113024)[DEBUG] Closed socket 17 (AF_UNIX)
Jun 14 09:42:30 guac-test xrdp[3026]: (3026)(139758598113024)[DEBUG] Closed socket 17 (AF_UNIX)
Jun 14 09:42:31 guac-test xrdp[2229]: (2229)(139758598113024)[DEBUG] Closed socket 17 (AF_UNIX)
~$ 

All that **/var/log/xrdp-sesman.log** shows is:

$ tail /var/log/xrdp-sesman.log
[20170614-10:04:50] [INFO ] A connection received from ::1 port 56732
[20170614-10:04:51] [INFO ] ++ reconnected session: username bmullan, display :10.0, session_pid 2415, ip 0.0.0.0:51882 - socket: 12
[20170614-10:04:51] [DEBUG] Closed socket 8 (AF_INET6 ::1 port 3350)

All that **/var/log/xrdp.log** shows is:

$ tail /var/log/xrdp.log
[20170614-10:01:04] [DEBUG] xrdp_wm_log_msg: started connecting
[20170614-10:01:05] [DEBUG] Closed socket 17 (AF_UNIX)
[20170614-10:01:08] [DEBUG] Closed socket 17 (AF_UNIX)
[20170614-10:01:09] [DEBUG] Closed socket 17 (AF_UNIX)
[20170614-10:01:12] [DEBUG] Closed socket 17 (AF_UNIX)
[20170614-10:01:12] [DEBUG] Closed socket 17 (AF_UNIX)
[20170614-10:01:15] [DEBUG] Closed socket 17 (AF_UNIX)
[20170614-10:01:16] [DEBUG] Closed socket 17 (AF_UNIX)
[20170614-10:01:19] [DEBUG] Closed socket 17 (AF_UNIX)
[20170614-10:01:19] [DEBUG] Closed socket 17 (AF_UNIX)

If I use an earlier version of XRDP (prior to .9.1.x) I do get a desktop connection okay?

Any hints about what I could check?   If it was guacamole alone that failed I wouldn't bother anyone as I'd keep looking but when rdesktop & freerdp don't connect that's a different story.

brian

**Comment by metalefty** [comment]
Can you show me the result of `pstree` when you try to connect?

**Comment by bmullan** [comment]
see attached .gz file

in it file named:

"1" - pstree before attempting guacamole login

"2" - pstree while attempting guacamole login

"rdesktop1" - pstree while attempting rdesktop login

**Comment by metalefty** [comment]
where's the attachment?

**Comment by bmullan** [comment]
I attached it but guess github must strip it.

I am leaving early this a.m. so will try to send them as inline on Sunday
or Monday

Brian

On Jun 15, 2017 11:43 PM, "metalefty" <notifications@github.com> wrote:

where's the attachment?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/neutrinolabs/xrdp/issues/774#issuecomment-308925214>,
or mute the thread

**Comment by bmullan** [comment]
Lets hope thie tar.gz file appears this time...

[xrdp-pstree.tar.gz](https://github.com/neutrinolabs/xrdp/files/1084924/xrdp-pstree.tar.gz)

**Comment by lieff** [comment]
Looks like X server can`t start. I have same issue on 17.04, because xrdp user do not have permission to start X. Resolution is to change allowed_users=anybody in Xwrapper.config (sudo dpkg-reconfigure xserver-xorg-legacy).

**Comment by bmullan** [comment]
Lion
I don't think thats going to be the root cause here because as I'd said in the initial post..   If I uninstall xrdp 0.9.1 and install an older version (like ubuntu's old 0.6.x version) without changing anything else then things work again.

**Comment by metalefty** [comment]
@bmullan You cannot say that. Please note xrdp 0.6.x doesn't use Xorg.

**Comment by bmullan** [comment]
@metalefty 
Thanks for the README.Debian reference.
changing allowed-users=anybody in Xwrapper.config did not present a desktop  either.

attached is a pstree while using rdesktop to login
[rdesktop.txt](https://github.com/neutrinolabs/xrdp/files/1087927/rdesktop.txt)

**Comment by metalefty** [comment]
I looked at pstree. Now you get Xorg session correctly started. 
Much clearer now. There's no promlem in session starting.

Create a file named `startwm.sh` in your home diretory with exec permission.
And see what happens when login via RDP.

```
#!/bin/sh
xterm
```

**Comment by bmullan** [comment]
what is the purpose of /etc/xrdp/startwm.sh then ?

**Comment by lieff** [comment]
Default startwm.sh is not working on Ubuntu in my case. It works with some modifications:
```
#original:
#test -x /etc/X11/Xsession && exec /etc/X11/Xsession
#exec /bin/sh /etc/X11/Xsession

#modified:
export LOGNAME=$USER
mate-session
```

**Comment by metalefty** [comment]
@bmullan To confirm `/etc/xrdp/startwm.sh` whether it is working or not, I told you to override it by quite simple startwm.sh in your home directory.

**Comment by bmullan** [comment]
No.. its not.

I tried a 2nd vm with ubuntu mate & same results.  Used both freerdp &
rdesktop & both fail.

**Comment by bmullan** [comment]
Yes it didn't work

**Comment by metalefty** [comment]
Which is it? Did simple startwm.sh (xterm) work?

**Comment by bmullan** [comment]
No

I just see blank screen

**Comment by bmullan** [comment]
I rebuilt xrdp to get v0.9.2 instead of v0.9.1 and this now works.

thanks

**Comment by salvador-blanco** [comment]
I have a similar problem when trying to connect, first a blue screen and then a message appears:

connecting to sesman ip 127.0.0.1 port 3350
sesman connect ok
sending login info to session manager, please wait..
login successful for display 11
started connecting
connection problem, giving up
some problem

If I press "ok" the button then  the server asks me for my credentials and then.. the blue screen ... the message .. I press "ok"  etc etc
I'm running ubuntu Mate 16.04 and xrdp 0.9.1

![blue screen](https://user-images.githubusercontent.com/30084029/32489930-ce46798e-c3f4-11e7-9fc0-e8febdcd68c2.jpg)

**Comment by metalefty** [comment]
@salvador-blanco Can you create a new your own issue? Also, please show us xrdp-sesman.log.
