### ISSUE TITLE
Cannot customize logon screen

### ISSUE THREAD

**Issue by adocampo** [neutrinolabs/xrdp#776]
I'm my way to customize the logon screen, I faced some problems trying to change the background image. It seems it ignores the value of **ls_background_image**

I would also like to change the button's color and hide the Session dropdown.

Would it be possible?

**Comment by tourch403** [comment]
I agree that it would be nice to be able to customize the logon screen, though settings.
I did a work around and replaced the ad24b and xrdp24b files in the /usr/share/xrdp folder.
Its a crud method, but it did the trick.

**Comment by metalefty** [comment]
@adocampo @tourch403 did you see the log?

It worked for me. `ls_background_image` cannot be a full path but must be a relative path where `ad24b.bmp` is located.
![2017-08-04 9 45 01](https://user-images.githubusercontent.com/941609/28949718-9e46f7a4-78f9-11e7-9ba1-7e7f48f16263.png)

**Comment by adocampo** [comment]
That worked! I think it should be commented on xrdp.ini for better understanding :)
And regarding the session dropdown, could be possible to hide it completely? I know I can delete/comment all non-desired entries, but hidding it would be nice (if it is easy to implement, of course)

**Comment by metalefty** [comment]
Yup, it should be mentioned in man page or xrdp.ini. Or full path should be accepted.

About dropdown list, I know some people requests such a cosmetic change however priority is low.
It requies a little effort for very few benefit. If someone does it  and submits as a pull request, I'm glad to merge it :smile:

**Comment by metalefty** [comment]
@adocampo Now ls_background_image accepts full path. Closing.
