### ISSUE TITLE
UDS connection only accessible to root

### ISSUE THREAD

**Issue by ben-cohen** [neutrinolabs/xrdp#783]
_(If the "port" specified in /etc/xrdp/xrdp.ini is an absolute path then a
Unix Domain Socket (UDS) is created instead of a TCP port. I want to use
this feature to implement authentication over SSH, issue #773.)_

UDS files are created by trans_listen_address() and given permissions 0660, so only root can connect to it.  I want the RDP incoming connection only to be given permissions 0666 so that any user can connect.  I would do this in xrdp_listen_main_loop() just after trans_listen_address().

Will that be acceptable or should I require an /etc/xrdp/xrdp.ini option to be set?  (E.g. "af_unix_auth" from #773.)

Test case:

1. Edit /etc/xrdp/xrdp.ini to set "port=/var/run/xrdp-local.socket".

2. Restart xrdp.

3. Run the following.

   socat TCP-LISTEN:12345 UNIX-CONNECT:/var/run/xrdp-local.socket &
   rdesktop localhost:12345

Expected behaviour: rdesktop starts up and displays the logon dialog.
Observed behaviour: rdesktop exits with "ERROR: Connection closed" and
socat exits with "Permission denied".

**Comment by metalefty** [comment]
I think specifying port to file is not designed to do such thing. But it is interesting for me.

**Comment by ben-cohen** [comment]
@metalefty Specifying a file for the client RDP connection was added intentionally: see commit 8b1639b96b34c6867842fd0ad19203cf50a1c9d5, "xrdp: allow xrdp to listen in UDS".  And this actually works for me with this change plus #782.

To show specifically the change I propose, I have created pull request #784.

**Comment by ben-cohen** [comment]
Closing issue because the fix has been merged (PR #784 commit 8b4d057).
