### ISSUE TITLE
debian packaging?

### ISSUE THREAD

**Issue by johnarnold** [neutrinolabs/xrdp#785]
If any xrdp maintainers know the debian/Ubuntu packaging maintainers, can you try to get a bump to 0.9.2 for Ubuntu?

Maybe it would be worth pulling the packaging into the project, so that it versions along with the project, and debian/Ubuntu can pull in whatever release they feel comfortable with?

I tried to build packages locally, using modified versions of the 0.9.1-9 packaging, but I ran into a few problems:
1. pidfile path inconsistent between /etc/init.d/xrdp and the systemd service files
2. something wrong with systemd process launching order?  There's a PR on this... Tried patching it in.
3. Even with everything running, I just get black screen (like window manager didn't launch) and socket closed over and over in the var/log/xrdp.log

I'm currently just installing from source on a few machines, but it is a bit clunky bash scripting the install.

Thanks!

**Comment by metalefty** [comment]
AFAIK Ubuntu doesn't package xrdp by themselves. Ubuntu uses Debian's (a little bit old) xrdp package.
I have keep in touch with Dbian packagers but don't with Ubuntu.

Anyway, I should agree with you. I'll make an effort to make Ubuntu package more comfortable.

**Comment by dbiersach** [comment]
xrdp is up to 0.9.3 - I know Ubuntu folks will really appreciate your efforts to get the latest version packaged up well - thanks in advance!

**Comment by metalefty** [comment]
If Ubuntu packagers want, I'm always willing to cooperate packaging with them. Do you have connections with them?

**Comment by metalefty** [comment]
Now Debian have the latest v0.9.4 in unstable. We're keeping in touch with the Debian maintainers and keeping Debian package up to date.

**Comment by johnarnold** [comment]
@metalefty can we leave this open at least until Ubuntu has reasonable packages?
