### ISSUE TITLE
Cannot open display

### ISSUE THREAD

**Issue by Suncatcher** [neutrinolabs/xrdp#787]
I usually use XRDP on a system started in non-X mode.
Some of the apps are crashing because they require usual X.Org server on **:10** display.
 
    ** (linphone:23792): CRITICAL **: Cannot open display:

While these occasions are rare and the apps are weird (like Linphone or SAPgui Java) these things are pretty annoying sometimes. 
How can we fake those apps? I.e. to spoof the X on the default display to without actually starting it? Is there any trick?

**Comment by metalefty** [comment]
xrdp uses X.Org. Set the DISPLAY environment variable and it will work.

**Comment by Suncatcher** [comment]
Should I set it to '0:'?

**Comment by metalefty** [comment]
No, the running session's display number.

**Comment by Suncatcher** [comment]
Okay, I get the current display like this:

    loginctl show-session -p Display -p Active c1
    Display=:10
    Active=yes

Then I pass DISPLAY var to target program

     env DISPLAY=':10' nm-connection-editor

And the same error:

    No protocol specified
    Failed to connect to Mir: Failed to connect to server socket: No such file or directory
    Unable to init server: Could not connect: Connection refused
    
    (nm-connection-editor:1664): Gtk-WARNING **: cannot open display: :10


Any suggestions?

**Comment by metalefty** [comment]
@Suncatcher Where is your :10 value come frrom? It doesn't work unless you set it to the correct value.

**Comment by Suncatcher** [comment]
@metalefty, from `loginctl show-session -p Display -p Active c1`

**Comment by metalefty** [comment]
Why? Set it to the xrdp session DISPLAY number if you want to show the application in xrdp session.

**Comment by moobyfr** [comment]
You are using ``mir``according to the displayed error, do you have ``xmir`` available ?

**Comment by Suncatcher** [comment]
> xrdp session DISPLAY number

How to get it?

**Comment by Suncatcher** [comment]
> You are using miraccording to the displayed error, do you have xmir available ?

as far as I know, Ubuntu abandon mir in latest release and now switched again to Xorg. I use 18.04

**Comment by Suncatcher** [comment]
The problem still exists and I see no reason why it is "not our issue"? I faced the problem on multiple distros and with multiple linux apps.

I even cannot use XKB, native Xorg app with XRDP:

    root@kukus:/home/user# setxkbmap -print -verbose 1
    No protocol specified
    Cannot open display ":10.0"

**Comment by metalefty** [comment]
are you logging in to xrdp with root user?

**Comment by Suncatcher** [comment]
no, as a regular user. I [filed an issue](https://github.com/neutrinolabs/xrdp/issues/1130) before connected with my non-rootines.

**Comment by metalefty** [comment]
Then, why are you doing setxkbmap with root user? You seem to be lacking basic knowledge about X Window System. Nothing's our issue. It seems to be your misunderstanding or lacking knowledge.

We're not your teacher, cannot help you with everything about everything.

**Comment by kundeng** [comment]
wow how arrogant.  Not everybody knows everything.  

I have the same issue with a clean installation of mx-linux and xrdp.  I didn't make any changes, so it IS an issue with how xrdp decided to set itself up in my system.

**Comment by Suncatcher** [comment]
very arrogant boy and he is arrogant to whomever saying things he doesn't like 😊 you will not receive proper support here, desine sperare qui hic intras.

When smth works for 80% apps and doesn't work for 20%, this **is** your issue if you app belong to this 20%. Even if I lack some knowledge about the X system (as a user I don't have to know this), in the manual to your library you should describe such issues and how to overcome them and not spit out the oaths to own users.

P.S. BTW, never in no single manual I saw smth like _setxkbmap is prohibited in a root-mode_, becasue it is simply not true. It can be used under simple user and under root too, when run root it reads layouts from the `/usr/share/X11/xkb/`

**Comment by kundeng** [comment]
For me what worked 

> very arrogant boy and he is arrogant to whomever saying things he doesn't like blush you will not receive proper support here, desine sperare qui hic intras.
> 
> When smth works for most apps and doesn't work for 20% of other apps, this **is** your issue. Even if I lack some knowledge about the X system (as a user I don't have to know such stuff), in the manual to your library you should describe such issues with certain apps and how to overcome them,m and not to spit out oaths to users
> 
> P.S. BTW, never, in no single manual it is written that `setxkbmap` is prohibited to be used in root-mode, it can be used under user and under root as well, when root it reads layouts from `/usr/share/X11/xkb/`

You can try this: xhost +SI:localuser:root

**Comment by belmont** [comment]
XRDP is a complete junk solution for CentOS8, only usable for CentOS7.  I dont waste time to post evidence as you will see  anyways.

**Comment by dfc643** [comment]
> For me what worked
> 
> > very arrogant boy and he is arrogant to whomever saying things he doesn't like blush you will not receive proper support here, desine sperare qui hic intras.
> > When smth works for most apps and doesn't work for 20% of other apps, this **is** your issue. Even if I lack some knowledge about the X system (as a user I don't have to know such stuff), in the manual to your library you should describe such issues with certain apps and how to overcome them,m and not to spit out oaths to users
> > P.S. BTW, never, in no single manual it is written that `setxkbmap` is prohibited to be used in root-mode, it can be used under user and under root as well, when root it reads layouts from `/usr/share/X11/xkb/`
> 
> You can try this: xhost +SI:localuser:root

thank you, thats worked for me on uos/deepin v20     
and i think that is a nice things to fight with the arrogant boy when boring, lol

**Comment by incomingstick** [comment]
> You can try this: xhost +SI:localuser:root

`xhost +SI:localuser:root`

For anyone new that may find themselves in this thread, the command given by @kundeng will resolve the issue. You run it as the current session user (no need for `sudo`, etc)

To explain it a tad further, it seems that because xrdp uses the X Display system, in order to run things through it as root, the root user must be given access control to the current session. Logging out will require the command to be re-run at next log in. (note that is different than just closing the connection)

**Comment by MasterJubei** [comment]
> > You can try this: xhost +SI:localuser:root
> 
> `xhost +SI:localuser:root`
> 
> For anyone new that may find themselves in this thread, the command given by @kundeng will resolve the issue. You run it as the current session user (no need for `sudo`, etc)
> 
> To explain it a tad further, it seems that because xrdp uses the X Display system, in order to run things through it as root, the root user must be given access control to the current session. Logging out will require the command to be re-run at next log in. (note that is different than just closing the connection)

Correct thank you both! 
To the dev(s) Can this be set as the default somewhere? This is not an easy to find solution.

**Comment by matt335672** [comment]
Hi @MasterJubei 

This will indeed mostly work for a single user system if you must use `sudo`, but there are other alternatives.

A better solution (IMO) is to look into configuring `pkexec` (part of PolicyKit) for those executables which you need to run with privilege. This allows you to tailor who can run what in a much finer-grained way. There is without doubt a steeper learning curve for it, but it's the best way to configure privileges for desktops on multi-user systems.

**Comment by EightB1ts** [comment]
> We're not your teacher, cannot help you with everything about everything.

What an arrogant boy-ish response. Decided not to use xrdp based off this. 

Hopefully in the past few years you've grown.

**Comment by eric79x** [comment]
> > You can try this: xhost +SI:localuser:root
> 
> `xhost +SI:localuser:root`
> 
> For anyone new that may find themselves in this thread, the command given by @kundeng will resolve the issue. You run it as the current session user (no need for `sudo`, etc)
> 
> To explain it a tad further, it seems that because xrdp uses the X Display system, in order to run things through it as root, the root user must be given access control to the current session. Logging out will require the command to be re-run at next log in. (note that is different than just closing the connection)

That's what solved the issue for me, after quite a while of trying other things. I added this to my XFCE login items:
xcfe-terminal -e xhost +SI:localuser:root

Ubuntu Server 22.04.3 with XFCE installed to RDP into, using xrdp.

**Comment by turbo** [comment]
> That's what solved the issue for me, after quite a while of trying other things. I added this to my XFCE login items:
xcfe-terminal -e xhost +SI:localuser:root

For anyone finding this via Google, you can also persist this for all X in `~/.xsession`:

```bash
#!/bin/sh
xhost +SI:localuser:root >/dev/null 2>&1
export LOGNAME=$USER
exec dbus-launch --exit-with-session startxfce4
```
