### ISSUE TITLE
XRDP_CFG_PATH is not defined and cannot be set

### ISSUE THREAD

**Issue by cyberb** [neutrinolabs/xrdp#788]
Cannot change /etc location using XRDP_CFG_PATH.
As I understand it is a compile time variable which was defined in file_loc.h.
Was it removed by this commit:
https://github.com/neutrinolabs/xrdp/commit/58c9cb43e9e83a6f5cc8a13cd84aa67cce8cacd5#diff-9caebe81770a1b1d9bc8a072cf2f2195L24

**Comment by metalefty** [comment]
Use sysconfdir during configure instead.

`./configure --sysconfdir=/somewhere/else`
The config path will be `/somewhere/else/xrdp`.

**Comment by cyberb** [comment]
This is another issue actually.
I am trying to 'make install' under non root and it failed with 'unable to create /etc/xrdp'
Then I used --sysconfdir to override  /etc location, but this does not seem to work either.
It does not even set sysconfdir in makefiles.
After struggling with it I just set it manually in all makefiles.
Only then I was able to run 'make install'

But now I cannot run xrdp as it still looks for /etc.
After digging the code I have found that compiler preprocessor variable (XRDP_CFG_PATH) is used in many places, but I am not sure why it is not defined.

**Comment by metalefty** [comment]
XRDP_CFG_PATH will be set to ${sysconfdir}/xrdp.
So specifying the directory by sysconfdir will change XRDP_CFG_PATH.

**Comment by metalefty** [comment]
Ah, please don't forget `--enable-strict-locations` together.
If it is not given, `sysconfdir` and `localstatedir` will be forced to be `/etc` and `/var`.

**Comment by cyberb** [comment]
Ideally I would like to be able to change it while running without recompiling.
Is it possible?

**Comment by cyberb** [comment]
--enable-strict-locations helped, thanks.
