### ISSUE TITLE
Missing Symbols on Desktop

### ISSUE THREAD

**Issue by lesscomplex** [neutrinolabs/xrdp#791]
xrdp Version: 0.9.2
Kernel: 4.1.12-94.3.6.el7uek.x86_64
OS: Oracle Linux 7 (x86_64) ==> [Virtual Machine on ESX 5.5]
Desktop: Gnome (Version 3.14.2)
Language: de

Unexpected behaviour: When connecting via RDP to this virtual machine I don't see any desktop icons. 
When connecting directly to the vm (with VMware console) with the same user I see all the desktop icons.

Expected behaviour: In the remotesession you should see the desktop icons as well.

**Comment by metalefty** [comment]
It is not xrdp or xorgxrdp issue.
