### ISSUE TITLE
Add new log level TRACE

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#794]
Hi, what do you think about adding log level TRACE? It means more verbose than DEBUG.

Some logs are still written to stdout/stderr so far. However, it is a bother for me because
I need to stop running xrdp and re-run xrdp in foreground.  I don't have users to do such hack.

Ideally, any logs should not be written by `g_writeln()`. Using log level DEBUG instead of
`g_writeln()` is too noisy for most people.   Let's add log level TRACE and quit using `g_writeln()`.
Use `log_message(LOG_LEVEL_TRACE, "")` instead.

The new log level TRACE is to be used to entering functions, entering if-else, 
or other developer oriented informations.

**Comment by moobyfr** [comment]
+1 especially for xrdp-sesman

**Comment by geiseri** [comment]
I added the ```LOG_LEVEL_TRACE``` to PR #792.  I have only used it in the ```fifo.c``` of chanserv.
