### ISSUE TITLE
If socket directory not present xrdp fails to connect

### ISSUE THREAD

**Issue by geiseri** [neutrinolabs/xrdp#801]
In cases where the unix sockets are kept in a tmpfs directory the structure may not be present when the unix sockets are requested.  This will cause the connection to fail after the socket create timeout.  If we ensure the directory structure is present right before it is requested it will continue to run.

**Comment by geiseri** [comment]
@metalefty #809 effectively breaks all of the sockets since it cannot actually create the directory.

**Comment by geiseri** [comment]
I also noticed that the code chmod the socket directory so that others can create sockets in the created directory.  I think it needs to be 0x1777.

**Comment by geiseri** [comment]
Found it, I used ```g_create_path``` not ```g_create_dir```.  This ensured the entire structure was present in case it was not already.

**Comment by metalefty** [comment]
Fix has been merged into devel, closing.
