### ISSUE TITLE
Possibly, a glitch with IPv4 struct initialization

### ISSUE THREAD

**Issue by andrecbarros** [neutrinolabs/xrdp#803]
Look on "s" initialization (zero fill) on line 755 of "common/os_calls.c", it should be, it seems, "g_memset(&s, 0, sizeof(s));" ("s" instead of "sa"). Copy and past is salvation, copy and past is a sin!

[xrdp-wrong_struct_zeroed.diff.txt](https://github.com/neutrinolabs/xrdp/files/1133466/xrdp-wrong_struct_zeroed.diff.txt)

**Comment by metalefty** [comment]
Indeed.

**Comment by metalefty** [comment]
Merged, thanks!
