### ISSUE TITLE
GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: User of caller and user of subject differs

### ISSUE THREAD

**Issue by stebo85** [neutrinolabs/xrdp#808]
After an upgrade to xrdp 0.9.2 with xorgxrdp v0.2.2 we get this error in some xrdp session, but not all: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: User of caller and user of subject differs. 

Does anyone have an idea what could cause that and how to solve it?

**Comment by metalefty** [comment]
I think that is not a xrdp's issue.
