### ISSUE TITLE
Adjust wait time before aborting

### ISSUE THREAD

**Issue by andrecbarros** [neutrinolabs/xrdp#821]
First things first. I'm using xrdp devel on Debian Jessie (actually, a flavor, Openmediavault).

When I start xrdp with -n and then xrdp-sesman with -n and put them to run in background, they will complain for a while but, eventually, will accept a remote connection. But, for some reason, if I try to run them as daemons, xrdp and xrdp-sesman get killed before they get a chance to handle connections, perhaps because xrdp has a dependency on xrdp-sesman, xrdp-sesman report failure to connect too soon, and both end being killed, restart just reproduce the events.

Is there a way to tell xrdp and xrdp-sesman to postpone failure notices, i.e., to wait a little longer before reporting it?

Also, for some reason or xrdp or xrdp-sesman are not just removing what is inside socket dir but also the socket dir itself, resulting in failure to start xrdp-sesman (in my case, /var/run/xrdp -> /run/xrdp) next time. It may be the reason xrdp-sesman fail to run as daemon, but I'm not sure.

**Comment by matt335672** [comment]
this has been overtaken by events I believe.
