### ISSUE TITLE
Installing xrdp and xorgxrdp on RHEL 6

### ISSUE THREAD

**Issue by vamsheerudra** [neutrinolabs/xrdp#829]
Do we have any documentation on installing xrdp and xorgxrdp on RHEL 6?

I am trying to install xrdp ver 0.9.3 and xorgxrdp on RHEL 6 and having issues.
Copy and paste from/to the Linux system stops working if the system gets locked.

what information is needed to troubleshoot this issue?

**Comment by metalefty** [comment]
Duplicate of #841.
