### ISSUE TITLE
blank screen after logging through Xorg module

### ISSUE THREAD

**Issue by vamsheerudra** [neutrinolabs/xrdp#834]
Hi,
I am having issues connecting to RHEL 6 system using Xorg module.
I can get to the login screen but after logging in, I get a blank screen.
I am using xrdp ver 0.9.3 with xorgxrdp ver 0.2.0.

log files and the error message are attached.

![rdp issue](https://user-images.githubusercontent.com/30297253/28565758-b9fdaab2-714a-11e7-9b2d-e738acd1e4ed.jpg)

**Comment by metalefty** [comment]
That is not a log.  `xrdp.log` and `xrdp-sesman.log` will give us more helpful information.

**Comment by vamsheerudra** [comment]
modifying startwm,sh resolved the issue.

**Comment by brainode** [comment]
Type that modifying help, but didn't wrote what you change...So helpless
