### ISSUE TITLE
How can I switch the keyboard from English to Russian?

### ISSUE THREAD

**Issue by DS455** [neutrinolabs/xrdp#845]
Hey. Installed Xrdp on Xubuntu, with terminal connection there is no possibility to change keyboard layout (only English layout), keyboard settings can not help. How can I switch the keyboard from English to Russian?

**Comment by metalefty** [comment]
I'm not sure anything about Russian but it seems to be working for me.
When I typed "qwerty", "йцукен" is shown on the screen. Is that correct?

The client is FreeRDP and I specified keyboard with `/kbd:Russian` option.

**Comment by DS455** [comment]
If the local server says locally setxkbmap -layout ru, then at terminal connection on the login screen and password only russian layout is available without the possibility to switch to the english layout.
XRDP version 0.6.1-2, how to update to the current version?

**Comment by metalefty** [comment]
Which Debian do you use? Debian already has v0.9.1.

**Comment by DS455** [comment]
I use Xubuntu 16.04,( Xenial Xerus).
XRDP Installed using `apt-get install xrdp`.
Installed version 0.6.1-2.

**Comment by DS455** [comment]
I installed Xubuntu 17.10 and xrdp 0.9.1, with terminal connection only one english keyboard layout is available. When will it be possible to have several layouts in terminal mode?

**Comment by F1nZeR** [comment]
Can't use russian layout on Linux Mint 18.2 (Ubuntu 16.04).
Also there is a problem with arrow keys - they didn't work.

**Comment by metalefty** [comment]
@F1nZeR xrdp 0.6.1 doesn't support Russian layout and "won't fix".
