### ISSUE TITLE
Failed to start xrdp.service: Unit xrdp.service is masked.

### ISSUE THREAD

**Issue by porunov** [neutrinolabs/xrdp#846]
Hello,

I have compiled and installed xrdp server 0.9.3 on Ubuntu 17.04. Desktop: Gnome 3.
I cannot start it because of the next error:

```
$ sudo service xrdp start
Failed to start xrdp.service: Unit xrdp.service is masked.
```

What am I doing wrong?

Regards

**Comment by cro** [comment]
I'm not a systemd expert, but in the past it has been sufficient for me to say

systemctl unmask xrdp

and then start the service.

**Comment by porunov** [comment]
Thank you. Solved the problem by removing old xrdp.service

**Comment by Luci-f** [comment]
hey! I started kali linux on AWS later on CMD i tried to connect to rdp for kali and   I  am getting  this error !! 
```
root@kali:/home/ec2-user# systemctl start xrdp
Failed to start xrdp.service: Unit xrdp.service not found.
```

**Comment by anoduck** [comment]
@Lucifer-00007 - Just for the record, there is an extra step from the norm that needs to be completed after compilation, and that is the installation of files for the system service. It goes a little something like this.
```bash
cd instfiles
sudo make install
# then (for debian & Kali & Ubuntu & mint)
sudo systemctl unmask xrdp.service xrdp-sesman.service \
  && sudo systemctl enable xrdp.service xrdp-sesman.service \
    && sudo systemctl start xrdp.service xrdp-sesman.service
```

Then it should run, but I am getting a failure due to xrdp-sesman.service

**Comment by anoduck** [comment]
@Lucifer-00007 Samething for me. Appears that setting exe prefix has no affect.
