### ISSUE TITLE
Display issues in NeutrinoRDP 

### ISSUE THREAD

**Issue by Zhao150101** [neutrinolabs/xrdp#860]
I RDP to a windows server(OS: windows server 2008) by NeutrinoRDP and then ssh to a Linux server. I find an issue that some lines are missing when I try to scan a txt file. Like the picture below.
![image](https://user-images.githubusercontent.com/15672593/30002970-82333bf6-90e9-11e7-93af-7442c60165fc.png)
The real file content is "Aaaaaaa\nBbbbbbb" but the second line is missing in my picture.
What I had done is  

- ssh to a Linux server using SecureCRT

- input `clear` to clear screen

- input `cat /tmp/1.t` to show the txt file

By my testing, the second line is missing if it has the same length with the first line.

Besides , I also find that if I type <Ctrl+L> in windows `cmd.exe` and then type `Enter`, the screen will show some black areas in wrong place like below picture.
![image](https://user-images.githubusercontent.com/15672593/30003090-2559d83e-90eb-11e7-888f-9563a685fa73.png)

All versions of xrdp and NeutrinoRDP are latest (branch devel).
I'm not sure whether these 2 issues caused by the same reason, so would you please help to have a look?
Thanks!

**Comment by cocoon** [comment]
you can try my branch:

`git clone https://github.com/cocoon/xrdp -b 2017-9-04-devel-fixed`

and if you want to avoid a crash and running on Ubuntu1604:

`git clone https://github.com/cocoon/NeutrinoRDP -b Ubuntu1604-CrashFix-UserHomeEnv`

**Comment by Zhao150101** [comment]
It works, thanks @cocoon

**Comment by metalefty** [comment]
@cocoon Let's merge it. It is worth enough. Can you separate your fix and create a PR?
