### ISSUE TITLE
Clipboard functionality for login screen

### ISSUE THREAD

**Issue by hycc** [neutrinolabs/xrdp#862]
Hello,

My copy/paste functionality from a windows client works absolutely fine, after logging in. I believe this is unrelated to the other copy/paste issues I see on the tracker here, but I could be mistaken.

We are unable to paste passwords into the login screen. This is a must-have for users who use the clipboard-based password managers such as keepass.

I am not sure if this is intentional, broken, or just a feature that does not exist yet. Please let me know what you think.

**Comment by speidy** [comment]
dup of #816
