### ISSUE TITLE
Can not connect to one of the users

### ISSUE THREAD

**Issue by DS455** [neutrinolabs/xrdp#866]
About once a week, one of the users can not connect to the remote desktop (the rest are connected without any problems). Here is the log from the syslog of the problem user:

> Sep  7 08:24:30 x-terminal xrdp[5424]: (5424)(140366508189440)[DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
> Sep  7 08:24:30 x-terminal xrdp-sesman[19393]: (19393)(140159088006912)[INFO ] A connection received from 127.0.0.1 port 44598
> Sep  7 08:24:31 x-terminal xrdp[5424]: (5424)(140366508189440)[INFO ] xrdp_wm_log_msg: sesman connect ok
> Sep  7 08:24:31 x-terminal xrdp[5424]: (5424)(140366508189440)[DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
> Sep  7 08:24:31 x-terminal xrdp[5424]: (5424)(140366508189440)[DEBUG] return value from xrdp_mm_connect 0
> Sep  7 08:24:31 x-terminal xrdp-sesman[19393]: (19393)(140159088006912)[INFO ] ++ created session (access granted): username spu, ip 192.168.0.
> 27:37756 - socket: 12
> Sep  7 08:24:31 x-terminal xrdp-sesman[19393]: (19393)(140159088006912)[INFO ] starting Xorg session...
> Sep  7 08:24:31 x-terminal xrdp-sesman[19393]: (19393)(140159088006912)[DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5911)

Here is the log from the xrdp.log problem user:

> [20170907-08:30:21] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
> [20170907-08:30:22] [INFO ] xrdp_wm_log_msg: sesman connect ok
> [20170907-08:30:22] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
> [20170907-08:30:22] [DEBUG] return value from xrdp_mm_connect 0
> [20170907-08:30:25] [INFO ] xrdp_wm_log_msg: login failed for display 0
> [20170907-08:30:25] [DEBUG] xrdp_mm_module_cleanup

The only working solution to this problem is to reboot the server. I would like more stability of the system.
I'm using xubuntu 16.04, xrdp v0.9.3.1, xorgxrdp v0.2.3

**Comment by metalefty** [comment]
BTW, please surround logs with triple back quotation for readability. Not each log lines but whole log lines.

**Comment by DS455** [comment]
xrdp-sesman.log:

> [20170907-08:24:30] [INFO ] A connection received from 127.0.0.1 port 44598
> [20170907-08:24:31] [INFO ] ++ created session (access granted): username spu, ip 192.168.0.27:37756 -socket: 12
> [20170907-08:24:31] [INFO ] starting Xorg session...
> [20170907-08:24:31] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5911)
> [20170907-08:24:31] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6011)
> [20170907-08:24:31] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6211)
> [20170907-08:29:40] [ERROR] X server -- no display in range is available
> [20170907-08:29:40] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)

**Comment by DS455** [comment]
it's help for me?
https://gist.github.com/metalefty/2672c26ae0cb36f7a4bc100650c83a15

**Comment by metalefty** [comment]
```
[20170907-08:29:40] [ERROR] X server -- no display in range is available
```

It looks max session count is exhausted. Increase `MaxSessions` or cleaning up zombie sessions is needed. We know xrdp has a bug in releasing finished session. The bug is already fixed and waiting for merged. See also #812 #830 #831. 

There's some workarounds you can do.

1. run my script you show periodically for example by cron
2. apply #831 and recompile xrdp

**Comment by DS455** [comment]
@metalefty 
Many thanks!
