### ISSUE TITLE
Forward SSH agent over RDP using virtual channel

### ISSUE THREAD

**Issue by ben-cohen** [neutrinolabs/xrdp#868]
I've written plugins for xrdp (#867) and FreeRDP [(#4122)](https://github.com/FreeRDP/FreeRDP/pull/4122) for a virtual channel to forward ssh-agent data.  This allows programs - usually ssh itself - in the remote desktop session to authenticate using an ssh-agent running locally on the RDP client machine.

**Usage**

Run FreeRDP with the ssh-agent plugin enabled:
    
       xfreerdp /ssh-agent ...
    
In the remote desktop session run `xrdp-ssh-agent` and evaluate the output in the shell as for ssh-agent to set the required environment variables (specifically `$SSH_AUTH_SOCK`):
    
       eval "$(xrdp-ssh-agent -s)"
    
This is the same as for the normal ssh-agent.  You would typically do this in your `Xsession` or `/etc/xrdp/startwm.sh`.

**Limitations**
    
1. Error checking and handling could be improved.
    
2. This stays running when the xrdp session closes.  This should be fixed using a command line argument as for the real ssh-agent.
    
3. This is only tested on Linux and will only work on systems where clients talk to the ssh-agent via Unix domain sockets.  It won't currently work on Windows but it could be ported.

4. You need to have an ssh-agent running or a tunnel to an ssh agent locally on the client machine because the plugin doesn't perform ssh-agent services (key store and signing).  This is not really a limitation because ssh has the same behaviour: if you have no ssh-agent running locally then "ssh -A" doesn't provide an agent to the remote session.

**Security issues**

All of the security issues I can think of also apply to the normal [ssh-agent](https://security.stackexchange.com/questions/101783/are-there-any-risks-associated-with-ssh-agent-forwarding).

The main concern is that the Unix domain socket created on the server must be readable only by that user, to prevent other users signing arbitrary data using the original user's private keys.  So the socket has to be created with appropriate Unix permissions (i.e. group and other can't read/write/execute).

**How does it work?**

It simply forwards the ssh-agent [protocol](https://tools.ietf.org/id/draft-miller-ssh-agent-00.html) between the Unix domain socket on the server and the ssh-agent's [$SSH_AUTH_SOCK](http://blog.joncairns.com/2013/12/understanding-ssh-agent-and-ssh-add/) Unix domain socket on the client.  The plugin is just a proxy and doesn't need to know anything about the protocol itself.

(It should be possible to write another plugin to forward network ports (and Unix domain sockets) in general [à la SSH](https://help.ubuntu.com/community/SSH/OpenSSH/PortForwarding) in the same way.)

**Can this be ported to Windows?**

Yes, both the client and server ends can both be ported to Windows.  Windows doesn't support Unix domain sockets so no doubt the mechanism will be different - PuTTY's [Pageant](https://the.earth.li/~sgtatham/putty/0.58/htmldoc/Chapter9.html) uses [shared memory](https://stackoverflow.com/questions/12452933/putty-pageant-protocol) - although the protocol will still be the same.

**Can I use my SSH key to log in to xrdp?**

In principle, yes, by using the sshagent channel during the authentication stage of RDP instead of using a password.  However, xrdp doesn't enable virtual channels until _after_ authentication so there might be some difficulty!  I'm going to look at that next.

**Can I use my SSH key to log in to Windows?**

Again in principle, yes, by using the sshagent channel during the authentication stage of RDP instead of using a password.  I think Microsoft would need to do this, because "terminal Services [does not support ](https://blogs.msdn.microsoft.com/winsdk/2009/07/14/rdc-and-custom-credential-providers/)remote authentication with arbitrary credential types"!

**Comment by metalefty** [comment]
Hmm, it is very interesting for me. It takes time but I promise I'll look at this.

**Comment by ben-cohen** [comment]
PR [#4122](https://github.com/FreeRDP/FreeRDP/pull/4122) was merged today into the FreeRDP tree commit [ff59cf028](https://github.com/FreeRDP/FreeRDP/commit/ff59cf028c6a85566be0471451c0329906e1f718).

**Comment by metalefty** [comment]
Good work!
