### ISSUE TITLE
cannot connect from Wyse SX0(S10) client due to some encryption issue

### ISSUE THREAD

**Issue by lptadmin** [neutrinolabs/xrdp#874]
Trying to connect a WYSE SX0 to Debain 9.1.0.
Connects fine to older xrdp and windows.
Will not connect to 0.9.1from Debian packages or compiled from sources.
Also tried 0.9.3.1 compiled on CentOS7 with same error.
Tried every fix I could find on here and the web.
Any ideas?  I would really like to get this working.
Output of xrdp -ns:
```
[20170913-11:00:09] [INFO ] A connection received from: ::ffff:10.1.1.220 port 2426
[20170913-11:00:09] [DEBUG] Closed socket 11 (AF_INET6 ::ffff:10.1.1.219 port 3389)
[20170913-11:00:09] [DEBUG] Closed socket 10 (AF_INET6 :: port 3389)
[20170913-11:00:09] [DEBUG] Security layer: requested 0, selected 0
colorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp)
postBeta2ColorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp 0xca02 15bpp 0xca03 16bpp 0xca04 24bpp)
highColorDepth 0x000f (0x0004 4bpp 0x0008 8bpp 0x000f 15bpp 0x0010 16 bpp 0x0018 24bpp)
supportedColorDepths 0x0007 (0x0001 24bpp 0x0002 16bpp 0x0004 15bpp 0x0008 32bpp)
earlyCapabilityFlags 0x0001 (0x0002 want32)
got client client connection type 0x00000000
xrdp_sec_process_mcs_data_CS_SECURITY:
  client supports 40 bit encryption
  client supports 128 bit encryption
  client supports 56 bit encryption
xrdp_sec_out_mcs_data: using no security
**xrdp_process_main_loop: libxrdp_process_incoming failed
[20170913-11:00:09] [DEBUG] Closed socket 11 (AF_INET6 ::ffff:10.1.1.219 port 3389)
xrdp_mcs_disconnect - socket closed
[20170913-11:00:09] [ERROR] Listening socket is in wrong state, terminating listener**
```

**Comment by lptadmin** [comment]
Compiled 0.9.4rc1 from source on Debian 9, same error.  :(

**Comment by metalefty** [comment]
Please let me know the "older xrdp" version which you can connect.

**Comment by lptadmin** [comment]
0.6.1 from the epel packages running on CentOS 6.8

I would just use this version but it does not kill the sessions when a client disconnects.  From what I read, the later versions do.

**Comment by metalefty** [comment]
>  Tried every fix I could find on here and the web.

What did you try?

**Comment by metalefty** [comment]
Seems Wyse clients have limited encryption.  I can't reproduce on my place because it is proprietary hardware client. Proprietary software clients such as Windows built in client or Mac client are easy to repro as I have both Windows and Mac.

Can you provide the open specification of the device especially about encryption?

Anyway, I need to know what you tried. "tried every fix" tells me nothing.

**Comment by lptadmin** [comment]
From the limited information that is available:
The terminals can only support RDP 5.x
They do support TLS
128-bit encryption max.

I have tried installing from packages, and building from sources on CentOS 6, 7 and Debian 8 and 9 with the same results.
Also recreated the certificate files multiple times and ini files with no luck.
[S10.pdf](https://github.com/neutrinolabs/xrdp/files/1507320/S10.pdf)

What changed from version .6 to the latest? Whatever that is... that is what is causing the issue.

**Comment by lptadmin** [comment]
I tried it again today on a new Debian 9.2 server I set up for another purpose using the 0.9.1 package.
Same issue.
Running xrdp with -ns,  it appears this section contains the issue:

earlyCapabilityFlags 0x0001 (0x0002 want32)
got client client connection type 0x00000000
_**xrdp_sec_process_mcs_data_CS_SECURITY:
  client supports 40 bit encryption
  client supports 128 bit encryption
  client supports 56 bit encryption
  client and server support high crypt, using high crypt
xrdp_sec_out_mcs_data: using 2048 bit RSA key
xrdp_process_main_loop: libxrdp_process_incoming failed**_
[20171127-14:07:29] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:10.1.1.224 port 3389)
xrdp_mcs_disconnect - socket closed
[20171127-14:07:29] [ERROR] Listening socket is in wrong state, terminating listener

**Comment by metalefty** [comment]
Can you build xrdp with `--enable-debug` flag and run `xrdp -ns`?

If I could get the Wyse client, much easier to test... I'm looking for where I can get the second hand SX0. What about other Wyse products? If it is same with other Wyse products, maybe I can get one easier. C10LE is the most easier one to get in my place Japan.

**Comment by lptadmin** [comment]
The C10LE is a bit newer, so it may not be a good test.  The SX0 units are available really cheap on ebay or I could send you one.  It would be worth it to me to get this working.

**Comment by lptadmin** [comment]
Output of -ns with -debug  compiled on Debian 9.2 from git-devel sources

root@chat:/usr/local/sbin# ./xrdp -ns
Argument 0 - ./xrdp
Argument 1 - -ns
logging configuration:
        LogFile:       /var/log/xrdp.log
        LogLevel:      4
        EnableSyslog:  1
        SyslogLevel:   4
[20171127-20:27:23] [INFO ] starting xrdp with pid 13349
[20171127-20:27:23] [INFO ] listening to port 3389 on 0.0.0.0
[20171127-20:27:38] [INFO ] Socket 12: AF_INET connection received from 10.1.1.229 port 2364
[20171127-20:27:38] [DEBUG] Closed socket 12 (AF_INET 10.1.1.224:3389)
[20171127-20:27:38] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)
process started
xrdp_process_main_loop
in xrdp_rdp_create
cfg_file /etc/xrdp/xrdp.ini
item ini_version value 1
item fork value true
item port value 3389
item use_vsock value false
item tcp_nodelay value true
item tcp_keepalive value true
item security_layer value negotiate
item crypt_level value high
item certificate value
[20171127-20:27:38] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
item key_file value
[20171127-20:27:38] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
item ssl_protocols value TLSv1, TLSv1.1, TLSv1.2
[20171127-20:27:38] [DEBUG] TLSv1.2 enabled
[20171127-20:27:38] [DEBUG] TLSv1.1 enabled
[20171127-20:27:38] [DEBUG] TLSv1 enabled
item autorun value
item allow_channels value true
item allow_multimon value true
item bitmap_cache value true
item bitmap_compression value true
item bulk_compression value true
item max_bpp value 32
item new_cursors value true
item use_fastpath value both
item blue value 009cb5
item grey value dedede
item ls_top_window_bg_color value 009cb5
item ls_width value 350
item ls_height value 430
item ls_bg_color value dedede
item ls_logo_filename value
item ls_logo_x_pos value 55
item ls_logo_y_pos value 50
item ls_label_x_pos value 30
item ls_label_width value 60
item ls_input_x_pos value 110
item ls_input_width value 210
item ls_input_y_pos value 220
item ls_btn_ok_x_pos value 142
item ls_btn_ok_y_pos value 370
item ls_btn_ok_width value 85
item ls_btn_ok_height value 30
item ls_btn_cancel_x_pos value 237
item ls_btn_cancel_y_pos value 370
item ls_btn_cancel_width value 85
item ls_btn_cancel_height value 30
 in xrdp_sec_create
  in xrdp_mcs_create
  out xrdp_mcs_create
  in xrdp_fastpath_create
  out xrdp_fastpath_create
 out xrdp_sec_create
out xrdp_rdp_create
in xrdp_rdp_incoming
 in xrdp_sec_incoming:
[20171127-20:27:38] [DEBUG] Security layer: requested 0, selected 0
 in xrdp_sec_incoming: init rdp security
pub_mod bytes 256
pri_exp 256
  in xrdp_mcs_incoming
colorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp)
[20171127-20:27:38] [INFO ] connected client computer name: WT0080645d0989
postBeta2ColorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp 0xca02 15bpp 0xca03 16bpp 0xca04 24bpp)
highColorDepth 0x0018 (0x0004 4bpp 0x0008 8bpp 0x000f 15bpp 0x0010 16 bpp 0x0018 24bpp)
supportedColorDepths 0x0007 (0x0001 24bpp 0x0002 16bpp 0x0004 15bpp 0x0008 32bpp)
earlyCapabilityFlags 0x0001 (0x0002 want32)
got client client connection type 0x00000000
xrdp_sec_process_mcs_data_CS_SECURITY:
  client supports 40 bit encryption
  client supports 128 bit encryption
  client supports 56 bit encryption
  client and server support high crypt, using high crypt
processing channels, channels_allowed is 1
got channel flags 82000000 name RDPDR
got channel flags 88000000 name CLIPRDR
got channel flags 84000000 name rdpsnd
got channel flags 84000000 name WYVCTRL
got channel flags 82000000 name CARANOC
xrdp_sec_out_mcs_data: using 2048 bit RSA key
  in xrdp_mcs_send_connect_response
  out xrdp_mcs_send_connect_response
    in xrdp_mcs_recv_edrq
    out xrdp_mcs_recv_edrq
    in xrdp_mcs_recv_aurq
    out xrdp_mcs_recv_aurq
  in xrdp_mcs_send_aucf
  out xrdp_mcs_send_aucf
  in xrdp_mcs_send_cjcf
  out xrdp_mcs_send_cjcf
  in xrdp_mcs_send_cjcf
  out xrdp_mcs_send_cjcf
  in xrdp_mcs_send_cjcf
  out xrdp_mcs_send_cjcf
  in xrdp_mcs_send_cjcf
  out xrdp_mcs_send_cjcf
  in xrdp_mcs_send_cjcf
  out xrdp_mcs_send_cjcf
  in xrdp_mcs_send_cjcf
  out xrdp_mcs_send_cjcf
xrdp_process_main_loop: libxrdp_process_incoming failed
in xrdp_rdp_disconnect
 in xrdp_sec_disconnect
  in xrdp_mcs_disconnect
[20171127-20:27:38] [DEBUG] Closed socket 12 (AF_INET 10.1.1.224:3389)
xrdp_mcs_disconnect - socket closed
xrdp_mcs_disconnect - close sent
 out xrdp_sec_disconnect
out xrdp_rdp_disconnect
xrdp_mcs_delete processed
process done
[20171127-20:27:38] [ERROR] Listening socket is in wrong state, terminating listener
[20171127-20:27:38] [CORE ] shutting down log subsystem...

**Comment by metalefty** [comment]
@lptadmin Sorry to kept you waiting for long. If I can get one, I can investigate the issue. If you can donate me one, can you email me one? My email address can be found at git log.

**Comment by metalefty** [comment]
Hardware client issue. Cannot test & solve until any of developers get the one.

**Comment by christheradioguy** [comment]
I have a box of these thin clients and would be more then happy to send you one if this can still be looked into.
