### ISSUE TITLE
another Xserver might already be active on display

### ISSUE THREAD

**Issue by Jerry-kiwi** [neutrinolabs/xrdp#875]
xubuntu 17.04
XRDP 0.9.3.1
XORGXRDP 0.2.3

I see login window, input log and pass and then green screen

/var/log/xrdp-sesman.log:

```
[20170914-05:02:48] [DEBUG] libscp initialized
[20170914-05:02:48] [INFO ] starting xrdp-sesman with pid 11957
[20170914-05:02:48] [INFO ] listening to port 3350 on 127.0.0.1
[20170914-05:03:32] [INFO ] A connection received from ::1 port 52676
[20170914-05:03:32] [INFO ] ++ created session (access granted): username www_adm, ip 0.0.0.0:54524 - socket: 12
[20170914-05:03:32] [INFO ] starting Xorg session...
[20170914-05:03:32] [DEBUG] Closed socket 9 (AF_INET6 :: port 5910)
[20170914-05:03:32] [DEBUG] Closed socket 9 (AF_INET6 :: port 6010)
[20170914-05:03:32] [DEBUG] Closed socket 9 (AF_INET6 :: port 6210)
[20170914-05:03:32] [DEBUG] Closed socket 7 (AF_INET6 ::1 port 3350)
[20170914-05:03:32] [DEBUG] Closed socket 8 (AF_INET6 ::1 port 3350)
[20170914-05:03:32] [INFO ] Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp
[20170914-05:03:42] [ERROR] X server for display 10 startup timeout
[20170914-05:03:42] [INFO ] starting xrdp-sessvc - xpid=12123 - wmpid=12122
[20170914-05:03:42] [ERROR] X server for display 10 startup timeout
[20170914-05:03:42] [ERROR] another Xserver might already be active on display 10 - see log
[20170914-05:03:42] [DEBUG] aborting connection...
[20170914-05:03:42] [INFO ] ++ terminated session:  username www_adm, display :10.0, session_pid 12121, ip 0.0.0.0:54524 - socket: 12
```

/etc/xrdp/sesman.ini

```
[Xorg]
param=Xorg
param=-config
param=xrdp/xorg.conf
param=-noreset
param=-nolisten
param=tcp
```

/var/xrdp/startsw.sh

```
#!/bin/sh
# xrdp X session start script (c) 2015 mirabilos
# published under The MirOS Licence
```

```
if test -r /etc/default/locale; then
        . /etc/default/locale
        test -z "${LANG+x}" || export LANG
        test -z "${LANGUAGE+x}" || export LANGUAGE
        test -z "${LC_ADDRESS+x}" || export LC_ADDRESS
        test -z "${LC_ALL+x}" || export LC_ALL
        test -z "${LC_COLLATE+x}" || export LC_COLLATE
        test -z "${LC_CTYPE+x}" || export LC_CTYPE
        test -z "${LC_IDENTIFICATION+x}" || export LC_IDENTIFICATION
        test -z "${LC_MEASUREMENT+x}" || export LC_MEASUREMENT
        test -z "${LC_MESSAGES+x}" || export LC_MESSAGES
        test -z "${LC_MONETARY+x}" || export LC_MONETARY
        test -z "${LC_NAME+x}" || export LC_NAME
        test -z "${LC_NUMERIC+x}" || export LC_NUMERIC
        test -z "${LC_PAPER+x}" || export LC_PAPER
        test -z "${LC_TELEPHONE+x}" || export LC_TELEPHONE
        test -z "${LC_TIME+x}" || export LC_TIME
        test -z "${LOCPATH+x}" || export LOCPATH
fi

test -x /etc/X11/Xsession && exec /etc/X11/Xsession
exec /bin/sh /etc/X11/Xsession

```

**Comment by metalefty** [comment]
This command in your log failed. Execute it in terminal (ex. logged in by SSH) and see result.
```
Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp
```

**Comment by Jerry-kiwi** [comment]
![image](https://user-images.githubusercontent.com/8778463/30413223-801a87ae-9925-11e7-89e6-5e6c882e112c.png)

**Comment by Jerry-kiwi** [comment]
I've changed allowed_users in /etc/X11/Xwrapper.config to anybody.

**Comment by Jerry-kiwi** [comment]
www_adm@srv-bio:~$ sudo systemctl status xrdp
● xrdp.service - xrdp daemon
   Loaded: loaded (/lib/systemd/system/xrdp.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-09-14 08:27:45 MSK; 30s ago
     Docs: man:xrdp(8)
           man:xrdp.ini(5)
  Process: 3242 ExecStart=/usr/local/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 3243 (xrdp)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/xrdp.service
           └─3243 /usr/local/sbin/xrdp

сен 14 08:27:44 srv-bio systemd[1]: Starting xrdp daemon...
сен 14 08:27:44 srv-bio xrdp[3242]: (3242)(139864918095616)[DEBUG] Testing if xrdp can listen on 0.0.0.0 port 3389.
сен 14 08:27:44 srv-bio xrdp[3242]: (3242)(139864918095616)[DEBUG] Closed socket 7 (AF_INET 0.0.0.0:3389)
сен 14 08:27:45 srv-bio systemd[1]: xrdp.service: PID file /var/run/xrdp.pid not readable (yet?) after start: No such file or directory
сен 14 08:27:45 srv-bio systemd[1]: Started xrdp daemon.
сен 14 08:27:46 srv-bio xrdp[3243]: (3243)(139864918095616)[INFO ] starting xrdp with pid 3243
сен 14 08:27:47 srv-bio xrdp[3243]: (3243)(139864918095616)[INFO ] listening to port 3389 on 0.0.0.0


now everything is okay.

**Comment by LazzariPaolo** [comment]
I ran into this issue with xrdp 0.9.9
I fixed it by running:

`sudo apt-get -y install --reinstall xserver-xorg-video-intel xserver-xorg-core`

**Comment by MohsenEbrahimi86** [comment]
Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp

X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-168-generic x86_64 Ubuntu
Current Operating System: Linux Ebrahimi-AI 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-106-generic root=UUID=ce64620e-cabb-4e76-9197-6dbd80f43d2d ro quiet splash vt.handoff=1
Build Date: 14 November 2019  06:20:00PM
xorg-server 2:1.19.6-1ubuntu4.4 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/user/.local/share/xorg/Xorg.10.log", Time: Thu Jun 18 00:06:30 2020
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/user/.local/share/xorg/Xorg.10.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
