### ISSUE TITLE
cant connect to remote machine

### ISSUE THREAD

**Issue by ZaharAd** [neutrinolabs/xrdp#880]
Hello, I spent all day trying to get back to an AWS instance with Centos 7 installed on it, but without success.
The strange thing is that, to this day, I had no problems at all.
Every instance I launch went through the AWS procedure for GUI installation without any problems. 

> sudo yum install -y kernel-devel # Needed to re-build ENA driver
sudo yum groupinstall -y "Server with GUI"
sudo systemctl set-default graphical.target
sudo yum -y install epel-release
sudo rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
sudo yum install -y xrdp tigervnc-server
sudo systemctl start xrdp
sudo systemctl enable xrdp
sudo systemctl disable firewalld
sudo systemctl stop firewalld

**the errors :** 

> [centos@ip-172-31-28-203 ~]$ sudo xrdp -ns
logging configuration:
        LogFile:       /var/log/xrdp.log
        LogLevel:      4
        EnableSyslog:  1
        SyslogLevel:   4
[20170917-17:17:35] [INFO ] starting xrdp with pid 3893
[20170917-17:17:36] [ERROR] xrdp_listen_main_loop: listen error, possible port already in use
[20170917-17:17:36] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:0)
[20170917-17:17:36] [CORE ] shutting down log subsystem...

> [centos@ip-172-31-28-203~]$ sudo xrdp-sesman -ns
starting sesman in foreground...
sesman config:
        ListenAddress:            127.0.0.1
        ListenPort:               3350
        EnableUserWindowManager:  1
        UserWindowManager:        startwm.sh
        DefaultWindowManager:     startwm-bash.sh
        AuthFilePath:             disabled
Xvnc parameters:
        Parameter 00                   Xvnc
        Parameter 01                   -bs
        Parameter 02                   -nolisten
        Parameter 03                   tcp
        Parameter 04                   -localhost
        Parameter 05                   -dpi
        Parameter 06                   96
X11rdp parameters:
XOrg parameters:
        Parameter 00                   Xorg
        Parameter 01                   -config
        Parameter 02                   xrdp/xorg.conf
        Parameter 03                   -noreset
        Parameter 04                   -nolisten
        Parameter 05                   tcp
        Parameter 06                   -logfile
        Parameter 07                   .xorgxrdp.%s.log
security configuration:
        AllowRootLogin:       1
        MaxLoginRetry:        4
        AlwaysGroupCheck:     0
        No TSUsersGroup defined
        No TSAdminsGroup defined
session configuration:
        MaxSessions:                 50
        X11DisplayOffset:            10
        KillDisconnected:            0
        IdleTimeLimit:               0
        DisconnectedTimeLimit:       0
        Policy:       0
SessionVariables parameters:
  Parameter 00                   PULSE_SCRIPT=/etc/xrdp/pulse/default.pa
logging configuration:
        LogFile:       /var/log/xrdp-sesman.log
        LogLevel:      4
        EnableSyslog:  1
        SyslogLevel:   4
[20170917-17:18:10] [DEBUG] libscp initialized
[20170917-17:18:10] [INFO ] starting xrdp-sesman with pid 3903
[20170917-17:18:10] [ERROR] bind error on port '3350': 98 (Address already in use)
[20170917-17:18:10] [DEBUG] Closed socket 7 (AF_INET 0.0.0.0:0)
[20170917-17:18:10] [CORE ] shutting down log subsystem...`

Please help. I tried all the tips and solutions suggested her.
This problem stops my entire product development process

**Comment by moobyfr** [comment]
As shown in your logs:
" [20170917-17:17:36] [ERROR] xrdp_listen_main_loop: listen error, possible port already in use"

something is already listening on this port

use netstat to know what

**Comment by ZaharAd** [comment]
Hey moobyfr, thanks for the quick response,
But I still can not figure out who's listening to the port and why

> [centos@ip-172-31-20-40 ~]$ netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0     36 ip-172-31-20-40.eu-:ssh 77.125.107.129:55449    ESTABLISHED
tcp        0    875 ip-172-31:ms-wbt-server 77.125.107.129:55445    ESTABLISHED
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ]         DGRAM                    9784     /run/systemd/shutdownd
unix  2      [ ]         DGRAM                    9319     /run/systemd/notify
unix  2      [ ]         DGRAM                    9321     /run/systemd/cgroups-agent
unix  5      [ ]         DGRAM                    9342     /run/systemd/journal/socket
unix  26     [ ]         DGRAM                    9344     /dev/log
unix  3      [ ]         STREAM     CONNECTED     27925
unix  3      [ ]         STREAM     CONNECTED     19419
unix  3      [ ]         STREAM     CONNECTED     24821    @/tmp/dbus-LzDG29Nt6p
unix  2      [ ]         DGRAM                    19780
unix  3      [ ]         STREAM     CONNECTED     19793
unix  3      [ ]         STREAM     CONNECTED     19414
unix  3      [ ]         STREAM     CONNECTED     23176
unix  3      [ ]         STREAM     CONNECTED     18357
unix  3      [ ]         STREAM     CONNECTED     17208
unix  3      [ ]         STREAM     CONNECTED     26037    @/tmp/.X11-unix/X0
unix  3      [ ]         STREAM     CONNECTED     23301
unix  3      [ ]         STREAM     CONNECTED     2456     /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     14995    /var/run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    20483
unix  3      [ ]         STREAM     CONNECTED     24890    @/tmp/dbus-Qfj4QGnO
unix  3      [ ]         STREAM     CONNECTED     14334    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     13857
unix  3      [ ]         STREAM     CONNECTED     20482    /run/systemd/journal/stdout
unix  3      [ ]         DGRAM                    9898
unix  3      [ ]         STREAM     CONNECTED     13864    /run/gssproxy.sock
unix  3      [ ]         STREAM     CONNECTED     25890    @/tmp/dbus-HxXaUZ1AHw
unix  3      [ ]         STREAM     CONNECTED     20570
unix  3      [ ]         STREAM     CONNECTED     24861    @/tmp/dbus-LzDG29Nt6p
unix  3      [ ]         STREAM     CONNECTED     25725
unix  3      [ ]         STREAM     CONNECTED     23177    @/tmp/dbus-Qfj4QGnO
unix  2      [ ]         DGRAM                    18588
unix  2      [ ]         DGRAM                    26116
unix  3      [ ]         STREAM     CONNECTED     26035    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     22718    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     14822
unix  3      [ ]         STREAM     CONNECTED     13847    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     23316    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     18203
unix  3      [ ]         STREAM     CONNECTED     24849    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     25726
unix  3      [ ]         STREAM     CONNECTED     26107
unix  3      [ ]         STREAM     CONNECTED     27649    /run/user/42/pulse/native
unix  3      [ ]         STREAM     CONNECTED     13632    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     23179
unix  3      [ ]         STREAM     CONNECTED     12223    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     25723
unix  3      [ ]         STREAM     CONNECTED     15285
unix  3      [ ]         STREAM     CONNECTED     20481
unix  3      [ ]         STREAM     CONNECTED     26695    /var/run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    19697
unix  2      [ ]         DGRAM                    9887
unix  3      [ ]         STREAM     CONNECTED     23923
unix  3      [ ]         STREAM     CONNECTED     24899    /run/user/42/pulse/native
unix  3      [ ]         STREAM     CONNECTED     13037
unix  3      [ ]         STREAM     CONNECTED     24866    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     3053
unix  3      [ ]         STREAM     CONNECTED     2562     /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     28680
unix  3      [ ]         STREAM     CONNECTED     18371
unix  3      [ ]         STREAM     CONNECTED     2683
unix  3      [ ]         STREAM     CONNECTED     27654    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     13036
unix  3      [ ]         STREAM     CONNECTED     20626
unix  2      [ ]         DGRAM                    10048
unix  3      [ ]         STREAM     CONNECTED     19471
unix  3      [ ]         STREAM     CONNECTED     23867    @/tmp/dbus-LzDG29Nt6p
unix  3      [ ]         STREAM     CONNECTED     2561     /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     26133    @/tmp/dbus-Qfj4QGnO
unix  3      [ ]         STREAM     CONNECTED     23275
unix  3      [ ]         STREAM     CONNECTED     10072    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     20510    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     25883
unix  3      [ ]         STREAM     CONNECTED     2560     /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     13846    /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    26045
unix  2      [ ]         DGRAM                    2448
unix  2      [ ]         DGRAM                    14219
unix  3      [ ]         STREAM     CONNECTED     18356
unix  2      [ ]         DGRAM                    13904
unix  3      [ ]         STREAM     CONNECTED     27924
unix  3      [ ]         STREAM     CONNECTED     23300
unix  3      [ ]         STREAM     CONNECTED     24822    /var/run/dbus/system_bus_socket
unix  3      [ ]         DGRAM                    9897
unix  3      [ ]         STREAM     CONNECTED     12982
unix  3      [ ]         STREAM     CONNECTED     14152
unix  3      [ ]         STREAM     CONNECTED     20500    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     26706
unix  3      [ ]         STREAM     CONNECTED     25939    @/tmp/.X11-unix/X0
unix  2      [ ]         DGRAM                    18937
unix  3      [ ]         STREAM     CONNECTED     19852
unix  3      [ ]         STREAM     CONNECTED     2564     /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    26036
unix  3      [ ]         STREAM     CONNECTED     10069    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     26010    @/tmp/dbus-LzDG29Nt6p
unix  3      [ ]         STREAM     CONNECTED     22716    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     13913    /var/run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    22937
unix  3      [ ]         STREAM     CONNECTED     2673
unix  3      [ ]         STREAM     CONNECTED     26698
unix  3      [ ]         STREAM     CONNECTED     23852    @/tmp/dbus-LzDG29Nt6p
unix  3      [ ]         STREAM     CONNECTED     28678
unix  3      [ ]         STREAM     CONNECTED     26751
unix  3      [ ]         STREAM     CONNECTED     25884
unix  3      [ ]         STREAM     CONNECTED     13151
unix  3      [ ]         STREAM     CONNECTED     14710
unix  3      [ ]         STREAM     CONNECTED     3052
unix  3      [ ]         STREAM     CONNECTED     15217
unix  3      [ ]         STREAM     CONNECTED     19788
unix  3      [ ]         STREAM     CONNECTED     19416
unix  3      [ ]         STREAM     CONNECTED     17974
unix  3      [ ]         STREAM     CONNECTED     23922
unix  3      [ ]         STREAM     CONNECTED     10073    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     23308    @/tmp/dbus-HxXaUZ1AHw
unix  3      [ ]         STREAM     CONNECTED     14229
unix  2      [ ]         DGRAM                    2674
unix  3      [ ]         STREAM     CONNECTED     14968
unix  2      [ ]         DGRAM                    26702
unix  3      [ ]         STREAM     CONNECTED     19139
unix  3      [ ]         STREAM     CONNECTED     23382    @/tmp/dbus-HxXaUZ1AHw
unix  3      [ ]         STREAM     CONNECTED     26034    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     14213    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     18372
unix  3      [ ]         STREAM     CONNECTED     2788     /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     15120    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     18658    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     25689
unix  3      [ ]         STREAM     CONNECTED     23378
unix  3      [ ]         STREAM     CONNECTED     23889
unix  3      [ ]         STREAM     CONNECTED     24843    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     25732
unix  3      [ ]         STREAM     CONNECTED     25675
unix  3      [ ]         STREAM     CONNECTED     25711
unix  3      [ ]         STREAM     CONNECTED     26818    @/tmp/dbus-T25JVrJF
unix  3      [ ]         STREAM     CONNECTED     10001
unix  3      [ ]         STREAM     CONNECTED     25671
unix  3      [ ]         STREAM     CONNECTED     26694    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     3049     @/tmp/dbus-LzDG29Nt6p
unix  3      [ ]         STREAM     CONNECTED     25677
unix  3      [ ]         STREAM     CONNECTED     25713
unix  3      [ ]         STREAM     CONNECTED     25687
unix  3      [ ]         STREAM     CONNECTED     10074    /var/run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    23690
unix  3      [ ]         STREAM     CONNECTED     25678
unix  3      [ ]         STREAM     CONNECTED     14153    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     25695
unix  3      [ ]         STREAM     CONNECTED     25686
unix  3      [ ]         STREAM     CONNECTED     24844    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     25728
unix  3      [ ]         STREAM     CONNECTED     25690
unix  2      [ ]         DGRAM                    24367
unix  3      [ ]         STREAM     CONNECTED     26041    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     25729
unix  3      [ ]         STREAM     CONNECTED     12773    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     3028
unix  3      [ ]         STREAM     CONNECTED     23834
unix  3      [ ]         STREAM     CONNECTED     25717
unix  3      [ ]         STREAM     CONNECTED     25670
unix  2      [ ]         DGRAM                    21580
unix  3      [ ]         STREAM     CONNECTED     17520
unix  3      [ ]         STREAM     CONNECTED     27653
unix  3      [ ]         STREAM     CONNECTED     19149    @/tmp/.X11-unix/X0
unix  3      [ ]         DGRAM                    13630
unix  3      [ ]         STREAM     CONNECTED     25731
unix  3      [ ]         STREAM     CONNECTED     25674
unix  3      [ ]         STREAM     CONNECTED     21546
unix  3      [ ]         STREAM     CONNECTED     3050     /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     25710
unix  3      [ ]         STREAM     CONNECTED     23175    @/tmp/dbus-Qfj4QGnO
unix  3      [ ]         STREAM     CONNECTED     25681
unix  3      [ ]         STREAM     CONNECTED     17442
unix  2      [ ]         DGRAM                    22446
unix  3      [ ]         STREAM     CONNECTED     24869    @/tmp/.ICE-unix/2379
unix  3      [ ]         DGRAM                    13629
unix  3      [ ]         STREAM     CONNECTED     21981
unix  3      [ ]         STREAM     CONNECTED     25684
unix  2      [ ]         DGRAM                    17440
unix  2      [ ]         DGRAM                    2999
unix  3      [ ]         STREAM     CONNECTED     24160
unix  3      [ ]         STREAM     CONNECTED     26655    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     18262    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     25683
unix  3      [ ]         STREAM     CONNECTED     20228
unix  3      [ ]         STREAM     CONNECTED     17438
unix  3      [ ]         STREAM     CONNECTED     25714
unix  2      [ ]         DGRAM                    2762
unix  3      [ ]         STREAM     CONNECTED     3059     @/tmp/dbus-LzDG29Nt6p
unix  3      [ ]         STREAM     CONNECTED     17691    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     25696
unix  3      [ ]         STREAM     CONNECTED     13837
unix  3      [ ]         STREAM     CONNECTED     23921
unix  3      [ ]         STREAM     CONNECTED     25680
unix  3      [ ]         STREAM     CONNECTED     17750
unix  3      [ ]         STREAM     CONNECTED     25716
unix  3      [ ]         STREAM     CONNECTED     17441
unix  3      [ ]         STREAM     CONNECTED     23835    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     19152
unix  3      [ ]         STREAM     CONNECTED     10066
unix  3      [ ]         STREAM     CONNECTED     10037
unix  3      [ ]         STREAM     CONNECTED     23920
unix  3      [ ]         STREAM     CONNECTED     15051    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     1841
unix  3      [ ]         STREAM     CONNECTED     24865    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     24015
unix  2      [ ]         DGRAM                    10027
unix  2      [ ]         DGRAM                    21794
unix  3      [ ]         STREAM     CONNECTED     22186
unix  2      [ ]         DGRAM                    27741
unix  3      [ ]         STREAM     CONNECTED     25699
unix  3      [ ]         STREAM     CONNECTED     21735    @/tmp/.X11-unix/X0
unix  3      [ ]         STREAM     CONNECTED     25663
unix  3      [ ]         STREAM     CONNECTED     18398    @/tmp/.X11-unix/X0
unix  3      [ ]         STREAM     CONNECTED     22123
unix  3      [ ]         STREAM     CONNECTED     25661
unix  3      [ ]         STREAM     CONNECTED     25702
unix  3      [ ]         STREAM     CONNECTED     23309
unix  3      [ ]         STREAM     CONNECTED     23863
unix  3      [ ]         STREAM     CONNECTED     25660
unix  2      [ ]         DGRAM                    10086
unix  3      [ ]         STREAM     CONNECTED     23945
unix  3      [ ]         STREAM     CONNECTED     23865
unix  3      [ ]         STREAM     CONNECTED     26654    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     21881    @/tmp/.X11-unix/X0
unix  3      [ ]         STREAM     CONNECTED     25693
unix  3      [ ]         STREAM     CONNECTED     25667
unix  3      [ ]         STREAM     CONNECTED     20168
unix  3      [ ]         STREAM     CONNECTED     24925    @/tmp/dbus-T25JVrJF
unix  3      [ ]         STREAM     CONNECTED     10051
unix  3      [ ]         STREAM     CONNECTED     10033
unix  3      [ ]         STREAM     CONNECTED     25820
unix  3      [ ]         STREAM     CONNECTED     13267
unix  3      [ ]         STREAM     CONNECTED     24848
unix  3      [ ]         STREAM     CONNECTED     25701
unix  3      [ ]         STREAM     CONNECTED     25936    @/tmp/dbus-LzDG29Nt6p
unix  3      [ ]         STREAM     CONNECTED     25719
unix  3      [ ]         STREAM     CONNECTED     14647    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     23850
unix  3      [ ]         STREAM     CONNECTED     22049    @/tmp/dbus-LzDG29Nt6p
unix  3      [ ]         STREAM     CONNECTED     23918
unix  3      [ ]         STREAM     CONNECTED     21963
unix  3      [ ]         STREAM     CONNECTED     25664
unix  3      [ ]         STREAM     CONNECTED     23603
unix  3      [ ]         STREAM     CONNECTED     25704
unix  3      [ ]         STREAM     CONNECTED     25821
unix  3      [ ]         STREAM     CONNECTED     18659    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     25889    @/tmp/dbus-HxXaUZ1AHw
unix  3      [ ]         STREAM     CONNECTED     23310
unix  3      [ ]         STREAM     CONNECTED     25722
unix  3      [ ]         STREAM     CONNECTED     10067
unix  3      [ ]         STREAM     CONNECTED     15050    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     19171
unix  3      [ ]         STREAM     CONNECTED     25708
unix  3      [ ]         STREAM     CONNECTED     10022
unix  3      [ ]         STREAM     CONNECTED     13724
unix  3      [ ]         STREAM     CONNECTED     23057    @/tmp/dbus-K1MeF0Je
unix  3      [ ]         STREAM     CONNECTED     18189    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     17439
unix  3      [ ]         STREAM     CONNECTED     25720
unix  3      [ ]         STREAM     CONNECTED     18499
unix  3      [ ]         STREAM     CONNECTED     23851
unix  3      [ ]         STREAM     CONNECTED     25692
unix  3      [ ]         STREAM     CONNECTED     23146    @/tmp/.X11-unix/X0
unix  3      [ ]         STREAM     CONNECTED     25822
unix  3      [ ]         STREAM     CONNECTED     25668
unix  2      [ ]         DGRAM                    10213
unix  3      [ ]         STREAM     CONNECTED     12197    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     3048
unix  3      [ ]         STREAM     CONNECTED     24863
unix  3      [ ]         STREAM     CONNECTED     25705
unix  3      [ ]         STREAM     CONNECTED     10032
unix  3      [ ]         STREAM     CONNECTED     13725    /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    10000
unix  3      [ ]         STREAM     CONNECTED     18033
unix  3      [ ]         STREAM     CONNECTED     25707
unix  3      [ ]         STREAM     CONNECTED     26747    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     10070    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     10002
unix  3      [ ]         STREAM     CONNECTED     27651    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     22048
unix  3      [ ]         STREAM     CONNECTED     2796     /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     25698
unix  3      [ ]         STREAM     CONNECTED     27655    @/tmp/dbus-LzDG29Nt6p
unix  3      [ ]         STREAM     CONNECTED     3060     /run/user/42/pulse/native
unix  3      [ ]         STREAM     CONNECTED     10071    /var/run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    23894
unix  3      [ ]         STREAM     CONNECTED     21982

**Comment by imc0** [comment]
"lsof -i :3389" might be a better bet (needs to be run as the root user).

**Comment by tariqghd** [comment]
Hi,

I have the exact problem it look that the shell script that tiger two times which make the service running two times. We can see in the file 
/etc/xrdp/sesman.ini
[Globals]
ListenAddress=127.0.0.1
ListenPort=3350
EnableUserWindowManager=1
UserWindowManager=startwm.sh
DefaultWindowManager=startwm-bash.sh

User windowManager and default windows manager both of them tiger a bash file   "startwm.sh" and "startwm-bash.sh"

if you check the "startwm-bash.sh" file 
cat startwm-bash.sh

#!/bin/bash -l
. /etc/xrdp/startwm.sh
you will see it will invoke the "startwm.sh" script which will start another network binding service with the same port number.
This must be handle in the condition part in the  "startwm.sh" file. but still I don't know where (:
Thanks
Tariq

**Comment by metalefty** [comment]
Port altready in use is the user's local issue.
