### ISSUE TITLE
Shared session with multiple users (classroom environment)

### ISSUE THREAD

**Issue by asadm** [neutrinolabs/xrdp#883]
I am using xrdp with X11rdp and it's working great. I want to ask if it's possible to share the same screen with multiple clients.
Currently, if I connect from second RDP client the first client is kicked out and the second one continues that session.

A common scenario would be a teacher sharing screen with students remotely. Is there a config change that can make this possible? Thanks

Thanks

**Comment by metalefty** [comment]
Reverting this commit should allow multiple clients with the same user.
https://github.com/neutrinolabs/xorgxrdp/commit/f745376610d9aac769877401f84f9fe5c7293e83

**Comment by asadm** [comment]
That works. Thanks!

**Comment by mailinglists35** [comment]
@metalefty is there any chance this can become a command line or config option instead of reverting the commit?
