### ISSUE TITLE
Cannot Login with two factor authentication

### ISSUE THREAD

**Issue by vakooma** [neutrinolabs/xrdp#884]
I'm trying to connect with Xrdp on ubuntu 16.04 , in this ubuntu running two factor authentication
using  Google Authenticator.   I`m logining successfully with different RDP services like NX, bat xrdp cannot understand verification code .
  if somebody has experience please tell me how to configure xrdp.ini end sesman.ini
or /etc/pam.d/xrdp-sesman

**Comment by metalefty** [comment]
Dup of #736.
