### ISSUE TITLE
xrdp hard coded port for sesman, config settings are not fully read

### ISSUE THREAD

**Issue by FelixZhang** [neutrinolabs/xrdp#894]
After changing Globals/ListenPort in sesman.ini to a number other than 3350, clients show an error:
`"Reply from access control: Error connecting to PAM"`
and the next line is logged to xrdp.log:
`[20170926-10:34:23] [ERROR] Failure connecting to socket sesman`

It seems the issue is caused due to the sesman port hard coded to 3350 in xrdp/xrdp_mm.c, access_control(). My colleague  @osalvadorvilardaga has a patch for it which works fine in test environments.

**Comment by metalefty** [comment]
Indeed.  Maybe it is easy to fix but if you already have a patch I'll merge your patch.

**Comment by osalvadorvilardaga** [comment]
Thanks to both.

The PR can be found [here](https://github.com/neutrinolabs/xrdp/pull/895)
