### ISSUE TITLE
redirected drive permission issue in linux

### ISSUE THREAD

**Issue by purvalpatel** [neutrinolabs/xrdp#899]
hello,
i am using ubuntu RDP server, and take remote from windows machine with redirected drives.
the drives are redirected successfully.it is mounted into users home directory.
i.e. /home/$user/thinclient_drives

i have multiple users into ubuntu servers.
i want to copy some files from all users thinclient_drives folder using root user.
the it shows permission denied error.
is there any workaround related to that ?

**Comment by moobyfr** [comment]
This is a "feature" from fuse, the mount can be denied for root:

man fuse:
> No other user (including root) can access the contents of the mounted filesystem
