### ISSUE TITLE
X11rdp: segmentation fault

### ISSUE THREAD

**Issue by eworm-de** [neutrinolabs/xrdp#9]
This is called from a virtual terminal, calling from xrdp-sesman results in the same error:

$ X11rdp :10
InitOutput:

X11rdp, an X server for xrdp
Version 0.7.0
Copyright (C) 2005-2012 Jay Sorg
See http://xrdp.sf.net for information on xrdp.
Underlying X server release 10903000, The X.Org Foundation
Screen width 800 height 600 depth 24 bpp 32
dpix 100 dpiy 100
buffer size 1920000

Backtrace:
0: X11rdp (0x400000+0x228e8) [0x4228e8]
1: X11rdp (0x400000+0x13607) [0x413607]
2: /lib/libc.so.6 (0x7f0813b26000+0x349f0) [0x7f0813b5a9f0]
3: X11rdp (fbInitializeColormap+0x125) [0x4b528d]
4: X11rdp (0x400000+0xbaa2f) [0x4baa2f]
5: X11rdp (0x400000+0xb5c3c) [0x4b5c3c]
6: X11rdp (0x400000+0xaa65e) [0x4aa65e]
7: X11rdp (0x400000+0xd0926) [0x4d0926]
8: X11rdp (0x400000+0xaaa3b) [0x4aaa3b]
9: X11rdp (0x400000+0xc80e) [0x40c80e]
10: /lib/libc.so.6 (__libc_start_main+0xed) [0x7f0813b4738d]
11: X11rdp (0x400000+0xc4a9) [0x40c4a9]
Segmentation fault at address 0x2

Fatal server error:
Caught signal 11 (Segmentation fault). Server aborting

**Comment by metalefty** [comment]
If this happens in current devel branch, reopen or create a new issue.
