### ISSUE TITLE
mount drive redirection fuse with allow_root

### ISSUE THREAD

**Issue by purvalpatel** [neutrinolabs/xrdp#902]
hello,
i am using drive redirection.
how do i enable allow_root while mounting fuse on thinclient_drives on another users.

**Comment by metalefty** [comment]
xrdp doesn't have such feature so far. maybe you can allow it by editing `xfuse_init_lib` function in `sesman/chansrv/chansrv_fuse.c`.

**Comment by purvalpatel** [comment]
hello @metalefty 
As you say, i try to debug sesman/chansrv/chansrv_fuse.c into source code.
I check the function xfuse_init_lib() but not found anything useful related to fuse mount permission.

static int xfuse_init_lib(struct fuse_args *args)
{
    if (fuse_parse_cmdline(args, &g_mount_point, 0, 0) < 0)
    {
        log_error("fuse_parse_cmdline() failed");
        fuse_opt_free_args(args);
        return -1;
    }

    if ((g_ch = fuse_mount(g_mount_point, args)) == 0)
    {
        log_error("fuse_mount() failed");
        fuse_opt_free_args(args);
        return -1;
    }

    g_se = fuse_lowlevel_new(args, &g_xfuse_ops, sizeof(g_xfuse_ops), 0);
    if (g_se == 0)
    {
        log_error("fuse_lowlevel_new() failed");
        fuse_unmount(g_mount_point, g_ch);
        g_ch = 0;
        fuse_opt_free_args(args);
        return -1;
    }

    fuse_opt_free_args(args);
    fuse_session_add_chan(g_se, g_ch);
    g_bufsize = fuse_chan_bufsize(g_ch);

    g_buffer = g_new0(char, g_bufsize);
    g_fd = fuse_chan_fd(g_ch);

    g_req_list = list_create();
    g_req_list->auto_free = 1;

    return 0;
}

**Comment by metalefty** [comment]
Now it is a question about fuse API usage rather than xrdp's drive redirection feature.
Maybe you can change args of `fuse_mount()` function to allow other user.

https://lastlog.de/misc/fuse-doc/doc/html/fuse__common_8h.html#a30d394a6127b20455bf5a4899e56e759

**Comment by purvalpatel** [comment]
Thank you for  reply.
I know it is the functionality of fuse. which is not an issue of xrdp.
here i make changes in  sesman/chansrv/chansrv_fuse.c file.


int
xfuse_init(void)
{
    struct fuse_args args = FUSE_ARGS_INIT(0, NULL);

    /* if already inited, just return */
    if (g_xfuse_inited)
    {
        log_debug("already inited");
        return 1;
    }

    if (g_ch != 0)
    {
        log_error("g_ch is not zero");
        return -1;
    }

    load_fuse_config();

    /* define FUSE mount point to ~/xrdp_client, ~/thinclient_drives */
    g_snprintf(g_fuse_root_path, 255, "%s/%s", g_getenv("HOME"), g_fuse_mount_name);
    **int chmod (const char g_fuse_root_path, mode_t everyone)       /* provide all users permission of that folder */**
    g_snprintf(g_fuse_clipboard_path, 255, "%s/.clipboard", g_fuse_root_path);

    /* if FUSE mount point does not exist, create it */
    if (!g_directory_exist(g_fuse_root_path))
    {
        if (!g_create_dir(g_fuse_root_path))
        {
            log_error("mkdir %s failed. If %s is already mounted, you must "
                      "first unmount it", g_fuse_root_path, g_fuse_root_path);
            return -1;
        }
    }

    /* setup xrdp file system */
    if (xfuse_init_xrdp_fs())
        return -1;

    /* setup FIFOs */
    fifo_init(&g_fifo_opendir, 30);

    /* setup FUSE callbacks */
    g_memset(&g_xfuse_ops, 0, sizeof(g_xfuse_ops));
    g_xfuse_ops.lookup      = xfuse_cb_lookup;
    g_xfuse_ops.readdir     = xfuse_cb_readdir;
    g_xfuse_ops.mkdir       = xfuse_cb_mkdir;
    g_xfuse_ops.rmdir       = xfuse_cb_rmdir;
    g_xfuse_ops.unlink      = xfuse_cb_unlink;
    g_xfuse_ops.rename      = xfuse_cb_rename;
    g_xfuse_ops.open        = xfuse_cb_open;
    g_xfuse_ops.release     = xfuse_cb_release;
    g_xfuse_ops.read        = xfuse_cb_read;
    g_xfuse_ops.write       = xfuse_cb_write;
    g_xfuse_ops.create      = xfuse_cb_create;
    //g_xfuse_ops.fsync     = xfuse_cb_fsync; /* LK_TODO delete this */
    g_xfuse_ops.getattr     = xfuse_cb_getattr;
    g_xfuse_ops.setattr     = xfuse_cb_setattr;
    g_xfuse_ops.opendir     = xfuse_cb_opendir;
    g_xfuse_ops.releasedir  = xfuse_cb_releasedir;

    fuse_opt_add_arg(&args, "xrdp-chansrv");
    fuse_opt_add_arg(&args, g_fuse_root_path);
    //fuse_opt_add_arg(&args, "-s"); /* single threaded mode */
    //fuse_opt_add_arg(&args, "-d"); /* debug mode           */

    if (xfuse_init_lib(&args))
    {
        xfuse_deinit();
        return -1;
    }

    g_xfuse_inited = 1;
    return 0;
}

here i provide the full permission to the mounted folder but its not working.

**Comment by metalefty** [comment]
It is potentially possible with some source code modification but maybe it is out of our scope.
xrdp is not designed to allow other users to access drive redirection directory. You should manage it by your own.

I can tell you that it is a FUSE mounted directory, not an regular directory so using chmod regular directory will never work. Remember, it is a FUSE directory, not a regular directory. It should be done by FUSE strategy.  I told you to change args of `fuse_mount()` function to allow other user but you didn't right?


```C
fuse_opt_add_arg(&args, "xrdp-chansrv");
fuse_opt_add_arg(&args, g_fuse_root_path);
//fuse_opt_add_arg(&args, "-s"); /* single threaded mode */
//fuse_opt_add_arg(&args, "-d"); /* debug mode           */

/* HERE */
fuse_opt_add_arg(&args, "PUT HERE OPTION TO ALLOW OTHER USER ACCESS"); 
```

**Comment by purvalpatel** [comment]
ok, thanks for the information..

**Comment by metalefty** [comment]
No update for 1 months. Once closing. I'll reopen this if the reporter want.
