### ISSUE TITLE
Get OS name of rdp client while rdp session is running

### ISSUE THREAD

**Issue by radzz11** [neutrinolabs/xrdp#903]
Is it possible by xrdp server to get OS name/version of rdp client while rdp session is running from particular client ?

For example if i take rdp of ubuntu desktop from windows machine i.e(mstsc.exe) or take rdesktop from other ubuntu machine than, is there any provision that i can get OS name of rdp client i.e windows / linux / mac.

**Comment by metalefty** [comment]
Server can know OS type. General Capability Set message in Remote Desktop Protocol includes osMajorType and osMinorType. However, it is not very detailed. You can't get detailed client OS version.

See this protocol specification.
https://msdn.microsoft.com/en-us/library/cc240549.aspx

**Comment by radzz11** [comment]
thanks for info @metalefty 
By the way "Server can know OS type" means xrdp server can give us OS type (i.e name either windows/unix/mac) but not detailed version ?
From where i can get  os name or code (0x0001=Windows,0x0003=Macintosh,0x0004=UNIX) whether in xrdp or sesman logs !!! only getting client os name would be sufficient from me.

**Comment by metalefty** [comment]
No update from the reporter for 1 months, closing. I'll reopen this when the reporter's back.
