### ISSUE TITLE
Printer redirection not working 

### ISSUE THREAD

**Issue by purvalpatel** [neutrinolabs/xrdp#905]
hello,
i have one ubuntu xrdp server and i compiled latest xrdp into ubuntu server.
and i access it from windows mstsc client, i want to redirect windows printers to RDP.
i make settings in to mstsc client bt its not worked.

**Comment by metalefty** [comment]
xrdp doesn't support printer redirection so far.

**Comment by purvalpatel** [comment]
oky thanks.

**Comment by metalefty** [comment]
IIRC, there's just one exception xrdp can do printer redirection is RDP proxy (neutrinordp) mode.
If a client is connecting Windows RDP server via xrdp, printer can be redirecred.

**Comment by gnshkl1** [comment]
@metalefty any update on printer redirection support as i am trying to add support for same

**Comment by overpod** [comment]
@metalefty any update on printer redirection support as i am trying to add support for same

**Comment by DS455** [comment]
Does this work in the new version XRDP?
