### ISSUE TITLE
Support for clipboard with X11 PRIMARY selection?

### ISSUE THREAD

**Issue by diego-santacruz** [neutrinolabs/xrdp#916]
I have installed xrdp with xorgxrdp on CentOS 7.4.

The clipboard is working, but only for the X11 CLIPBOARD selection, that is text explicitly copied or pasted.

It would be really practical if it worked with the X11 PRIMARY selection as well, that is highlighted text and middle-mouse button paste.

In Xvnc (TigerVNC) it works for both when used from a VNC client (no xrdp involved).

Versions used:
xrdp-0.9.3-2.el7.x86_64
xorgxrdp-0.2.4-3.el7.x86_64
Windows 10 Remote Desktop client 10.0.15038

**Comment by metalefty** [comment]
AFAIK xrdp doesn't support X11 PRIMARY clipboard so far.  IMO, maybe it is possible to implement it but there's little benefit for effort because there's some workaround using third-party tools.

Syncing PRIMARY and CLIPBOARD using [parcellite](http://parcellite.sourceforge.net/) will take the same effect.

**Comment by diego-santacruz** [comment]
Indeed, I also saw (after reporting this) that gpaste could also be an alternative, although I have not tested either.

**Comment by metalefty** [comment]
@diego-santacruz Do you still want it as xrdp's feature? If no, parcellite or gpaste is enough for you, I'm willing to close this.

**Comment by diego-santacruz** [comment]
I have successfully tested gpaste and enabling the synchronization of clipboard and primary selection solves the issue.

**Comment by metalefty** [comment]
Okay, if you want the feature as xrdp's feature again, please contribute with code. We'll consider merging it but not implement it by ourselves. Closing.
