### ISSUE TITLE
Issue with pam_winbind and trusted domains.

### ISSUE THREAD

**Issue by netlore** [neutrinolabs/xrdp#920]
Hi,

I've tested this with both Ubuntu 17.10 and 17.04 with the same result, everything works perfectly as long as I remember to purge xserver-xorg-legacy, I can log in with AD users via winbind etc, etc... but if a user from another (trusted) domain tries to log in it gives a blank screen for a long time and then fails to log in, showing this error in the log:-

auth.log:Oct 18 15:31:49 terminal01 xrdp-sesman[1285]: pam_unix(xrdp-sesman:auth): authentication failure; logname= uid=0 euid=0 tty=xrdp-sesman ruser= rhost=  user=CORP\user.name
auth.log:Oct 18 15:31:49 terminal01 xrdp-sesman[1285]: pam_winbind(xrdp-sesman:auth): getting password (0x00000388)
auth.log:Oct 18 15:31:49 terminal01 xrdp-sesman[1285]: pam_winbind(xrdp-sesman:auth): pam_get_item returned a password
auth.log:Oct 18 15:32:50 terminal01 xrdp-sesman[1285]: pam_winbind(xrdp-sesman:auth): internal module error (retval = PAM_AUTHINFO_UNAVAIL(9), user = 'CORP\user.name')

This user is able to log in every time with ssh, but cannot log in to xrdp, and I'm not certain why... it looks like pam_unix failed it, which is correct becuase there is no local user, and then it tried pam_winbind, but something barfed on the login name or something.

**Comment by netlore** [comment]
Winbind users from the primary domain are able to log in fine.

**Comment by moobyfr** [comment]
The logs are showing that `pam_winbind` is failing with an internal error. `pam_unix` has probably failed because of no local user, this is not an fatal error, the next module will try to authenticate the use (`pam_winbind`) can there user open a normal session (locally or ssh, or another service ?)

**Comment by netlore** [comment]
Winbind users on the default domain (who dont have to specify their domain in the login) can log in via ssh and xrdp, but foreign domain users cannot log in with xrdp, tho they can with ssh.

**Comment by moobyfr** [comment]
I se the problem
the login is "CORP\username"
For xrdp, the domain is perhaps used for selecting the backend.

**Comment by netlore** [comment]
Is there any way around this?... as technically those are legal users on the box...

**Comment by netlore** [comment]
It's interesting to note that users on the "default" domain can type their login in full with the domain attached, and at some point before the problem happens, it is reduced so that it does not include the (unnecessary) domain component before xrdp barfs.... so those logins are accepted.

**Comment by matt335672** [comment]
This should be fixed when #2472 is merged as sesman will move to using UIDs to refer to users rather than usernames which are not unique when using a federated naming service.
