### ISSUE TITLE
Intellij IDEA leaks in xrdp session

### ISSUE THREAD

**Issue by coolemza** [neutrinolabs/xrdp#922]
Dunno, if it is a right place to put this issue, but Intellij IDEA leaks in xrdp session. To reproduce it just open or create new project in latest Intellij IDEA and leave it in session for 3-4 days, it will eat all default java heap size and freeze ui, this behavior reproduced on ubuntu 17.04 with xfce desktop. This is not so bad, you can just kill and start it again, but annoying. May be someone will point me where to dig, so i will investigate it more deeply. Thank you.

**Comment by metalefty** [comment]
I don't think this is a xrdp issue.
