### ISSUE TITLE
XRDP and HDD consumption

### ISSUE THREAD

**Issue by nestoru** [neutrinolabs/xrdp#93]
Hello,

First, this is a great service we have been using with excellent results so kudos for the developers behind it.

Then to my issue: I could not find a single post about xrdp eating HDD but after having to restart my ubuntu desktop for the second time in less than a week because the disk was apparently full I managed to verify that just restarting xrdp would free 50% of my HDD utilization! Is this something others are aware of? Is there any settings that could help with this situation?
Thanks!

- Nestor

$ df -k

Filesystem                                       1K-blocks       Used Available Use% Mounted on

/dev/sda1                                         37663756   35776368         4 100% /

$ sudo service xrdp restart

$ df -k

Filesystem                                       1K-blocks       Used Available Use% Mounted on

/dev/sda1                                         37663756   17928168  17848204  51% /

**Comment by itamarjp** [comment]
this bug report is too old, please reopen is this still happens with latest version
