### ISSUE TITLE
xrdp 0.9.4 + centos 7.4 + freeipa

### ISSUE THREAD

**Issue by choman** [neutrinolabs/xrdp#939]
Strange issue,  it seems accounts in freeipa with > 11 characters after logging into xrdp 
there username (for the most part) does not show up in the following three spots, at least:

- logout menu
- account settings
- screen lock

NOTE: rdp session is initiated from a win10 machine

Any ideas?

**Comment by metalefty** [comment]
What's your DE?

**Comment by choman** [comment]
gnome

**Comment by rjt** [comment]
Does it matter what is chosen
XVNC?
Xorg?
X11rdp?

**Comment by cro** [comment]
Xorg is the preferred backend.

I don't think X11rdp is strictly being maintained anymore.

If you need to support both VNC and RDP, Xvnc might be a good choice.

--cro

**Comment by choman** [comment]
so I'm using both xvnc (tiger) and xorgxrdp. leaning towards xorgxrdp

**Comment by moobyfr** [comment]
can you take a screenshot, I don't understand the issue, abd some xrdp-sesman.log or ~/.xorgxrdp.??.log should help us.

**Comment by metalefty** [comment]
No feedback for more than 1 month, closing. Please leave a comment when you're back.
