### ISSUE TITLE
Clipboard question

### ISSUE THREAD

**Issue by johnarnold** [neutrinolabs/xrdp#942]
I’m seeing a weird behavior when trying to copy paste from xrdp session to windows machine.

If I copy some text in pycharm, then try to paste it into Skype for Business, I get an error like its invalid.  I think same thing with paste into outlook.  I can paste into Notepad just fine though.

I’m wondering if anyone has an idea what is happening here.  I know there are multiple clipboards but it’s not clear to me how to debug.

Maybe there’s an issue with RichText or something?

**Comment by johnarnold** [comment]
Update:

Paste into outlook works just fine.   Also, it doesn't seem to be just stuff out of pycharm. If I copy from Chrome within xrdp session and try to paste into Skype for Business that fails to.

So it definitely seems like an issue with Skype, just not sure what it could be.   If someone with experience with the clipboard could give me some pointers (how do I inspect the clipboards' contents?), I would appreciate it.

**Comment by metalefty** [comment]
Clipboard is handled by xrdp-chansrv. You can see xrdp-chansrv log dumped to stdout.  You need to run xrdp-sesman in foreground to see xrdp-chansrv stdout. You might be required to increase log level and rebuild to see detailed log. To see clipboard contents of server to client copy & paste, maybe you can add printfs in `clipboard_event_selection_notify()` function.

**Comment by metalefty** [comment]
No feedback more than 1 month. Closing. If your issue is not solved, leave a comment when you're back. I'll reopen this.

**Comment by davidp-electronf-com** [comment]
This exact problem still occurs with  xrdp 1:0.9.11-5.el7 on Centos 7.6.1810

**Comment by ddeimeke** [comment]
Can you please reopen the ticket? 

I confirm this behaviour with Windows 10 and RHEL 7.7

```
$ rpm -qa | grep -i xrdp
xorgxrdp-0.2.12-2.el7.x86_64
xrdp-0.9.12-1.el7.x86_64
```

**Comment by ddeimeke** [comment]
Which data do you need to analyse this ticket?
