### ISSUE TITLE
Customize XRDP login screem

### ISSUE THREAD

**Issue by Abinayasandhiya** [neutrinolabs/xrdp#950]
Hi,

As we know if we want to change the Desktop environment in XRDP using .Xclients file,  we need to restart the xrdp services.
But now the problem is while restarting the service of xrdp some of our users connected sessions are getting terminate.
We could understand that this is not an issue but I can see that we can customize the XRDP login screen.
Can anyone let me know is there anyway to select the desktop environment(GNOME, KDE, XFCE) on login screen of XRDP.

It would be grateful if anyone help me on this.

Regards,
Abinaya

**Comment by mrichar1** [comment]
I'm not sure if there is an official way to do this, but one workaround could be to create a single startup script that contains the following:

```
#/bin/bash
case (zenity --list --column WM Gnome KDE) in
Gnome)
  gnome-session
  ;;
KDE)
  kde-session
 ;;
esac
```

That way zenity will start, prompt the user for their preferred WM, and then call the appropriate command to start that WM.

**Comment by Abinayasandhiya** [comment]
Thanks for your update.

Please let me know where this script need to be created.

**Comment by Abinayasandhiya** [comment]
As per your suggestion I could get the menu of GNOME and KDE when we open the xrdp session.
But mouse pointer getting hide.

Can you please let me know how to fix this.

**Comment by Abinayasandhiya** [comment]
![xrdpscreen](https://user-images.githubusercontent.com/31726216/33196507-97712594-d105-11e7-85fb-7fe394800213.JPG)

**Comment by Abinayasandhiya** [comment]
Please help me

**Comment by Abinayasandhiya** [comment]
Wow It seems to be working fine without any issue.
Really thanks you so much:)

**Comment by Abinayasandhiya** [comment]
Sorry to reopen this issue.

RHEL6 machine its working as expected if we restart the xrdp service mouse pointer is getting displayed.
but on RHEL7 mouse pointer is not working on that WM menus.

please suggest me
