### ISSUE TITLE
Can not disable encryption

### ISSUE THREAD

**Issue by juancarloslin** [neutrinolabs/xrdp#953]
Can not disable encryption level.
We use Dell Wyse S10 and have limited encription capabilities on LAN environment.
We try several way to disable encription with not success.

Issue cames after Fedora 22

**Comment by metalefty** [comment]
What did you try?

**Comment by lptadmin** [comment]
Same as my issue on #874

**Comment by metalefty** [comment]
Close this if your issue is identical to #874. Let's go on #874.
