### ISSUE TITLE
Error on start XRDP/XORGXRDP

### ISSUE THREAD

**Issue by Jerry-kiwi** [neutrinolabs/xrdp#955]
Ubuntu 16.04.3
XRDP 0.9.4
XORGXRDP 0.2.4

[LOG.txt](https://github.com/neutrinolabs/xrdp/files/1491907/LOG.txt)

**Comment by metalefty** [comment]
It seems built xorgxrdp doesn't match your Xorg version. 
You need to rebuild xorgxrdp and create modules match your Xorg version.

See also: https://github.com/neutrinolabs/xrdp/issues/786#issuecomment-326179740
This is a long thread but some comments provide you the essense.

~~~
[  1670.063] (EE) xrdpmouse: module ABI major version (22) doesn't match the server's version (24)
[  1670.063] (EE) xrdpkeyb: module ABI major version (22) doesn't match the server's version (24)
~~~

**Comment by Jerry-kiwi** [comment]
Thnanks.
So, what version on xorgxrdp do I need? 0.2.4 is too fresh:)
<=0.2.2 ?

**Comment by Jerry-kiwi** [comment]
Doing this:
`Meaning, if you want to use -hwe-16.04 suffixed packages, -dev packages also need to be -hwe-16.04 suffixed. Make sure xserver-xorg-dev uninstalled and xserver-xorg-dev-hwe-16.04 installed.`

fixed problem. Thanks once again for help!

**Comment by zertrin** [comment]
Thanks @Jerry-kiwi, your last comment was exactly what unstuck me from 1 hour of not understanding what was wrong.

I added this information in the wiki page https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8 because this is where I feel this information should be.
