### ISSUE TITLE
pam_sss being ignored during authentication

### ISSUE THREAD

**Issue by mrichar1** [neutrinolabs/xrdp#957]
Apologies in advance if this is an issue outside the scope of xrdp...

When I log in using a local acount (e.g. root) then everything works as expected and a session starts.

However when I use a 'remote' account, authenticated via sssd against openldap (sssd `id_provider=ldap`), then it always fails.

If I authenticate using other services, such as ssh, the auth logs show:

```
pam_sss(sshd:auth): authentication success; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.1.202 user=mrichar1
pam_unix(sshd:session): session opened for user mrichar1 by (uid=0)
```

However when I connect via rdp, I only see:

```
pam_unix(xrdp-sesman:auth): authentication failure; logname= uid=0 euid=0 tty=xrdp-sesman ruser= rhost=  user=mrichar1
```

I have the following in /etc/pam.d/xrdp-sesman (redhat el7):

```
auth       include      password-auth
account    include      password-auth
password   include      password-auth
session    include      password-auth
```

and in password-auth:

```
auth    required        /lib64/security/pam_env.so
auth    [success=done default=ignore]   pam_sss.so      forward_pass
auth    sufficient      /lib64/security/pam_unix.so     nullok try_first_pass
auth    required        /lib64/security/pam_deny.so
account [default=bad success=ok user_unknown=ignore]    pam_sss.so
account required        /lib64/security/pam_unix.so     broken_shadow
account sufficient      /lib64/security/pam_localuser.so
account sufficient      /lib64/security/pam_succeed_if.so       uid < 1000 quiet
account required        /lib64/security/pam_access.so
account required        /lib64/security/pam_permit.so
password        requisite       /lib64/security/pam_pwquality.so        try_first_pass local_users_only retry=3 authtok_type=
password        sufficient      pam_sss.so      use_authtok
password        sufficient      /lib64/security/pam_unix.so     sha512 shadow nullok try_first_pass use_authtok
password        required        /lib64/security/pam_deny.so
session optional        /lib64/security/pam_keyinit.so  revoke
session required        /lib64/security/pam_limits.so
session optional        /lib64/security/pam_systemd.so
session [success=1 default=ignore]      /lib64/security/pam_succeed_if.so       service in crond quiet use_uid
session optional        pam_sss.so
session required        /lib64/security/pam_unix.so
```
I've tried stracing the xrdp processes, and they are reading xrdp-sesman and then password-auth - it just appears that the sss config is being ignored. I've also turned debugging up high on sssd, and there appears to be no access to the ldap domain (other than the group lookups on service start (tsusers/tsdadmins).

Any advice on what I need to adjust to get this to work? Happy to submit more logs/debugging.

**Comment by moobyfr** [comment]
why is the path to the `pam_ssss.so` a relative one in `password-auth`, where all others modules use absolute ?

**Comment by mrichar1** [comment]
pam module paths can be relative or absolute (and there is only 1 pam_sss.so file on the system) - but for clarity I've changed this to be the full path to match the other lines, and there's no difference - still being ignored.

**Comment by mrichar1** [comment]
For further info, if I use `pamtester` and tell it to try authentication as the `xrdp-sesman` service it seems to work through the pam stack correctly

```
# With correct password
> pamtester xrdp-sesman mrichar1 authenticate
Password:
2017-11-22T09:37:13.429901+00:00 xrdpsrv pamtester: pam_sss(xrdp-sesman:auth): authentication success; logname=mrichar1 uid=0 euid=0 tty= ruser= rhost= user=mrichar1

# With invalid password
> pamtester xrdp-sesman mrichar1 authenticate
Password:
2017-11-22T09:37:48.432920+00:00 xrdpsrv pamtester: pam_sss(xrdp-sesman:auth): authentication failure; logname=mrichar1 uid=0 euid=0 tty= ruser= rhost= user=mrichar1
2017-11-22T09:37:48.437842+00:00 xrdpsrv pamtester: pam_unix(xrdp-sesman:auth): authentication failure; logname=mrichar1 uid=0 euid=0 tty= ruser= rhost=  user=mrichar1
```

**Comment by mrichar1** [comment]
OK - this is looking more like a race condition somewhere...

If I add any module to `password-auth` before pam_sss (set optional), then I get successful authentication. for example:

```
auth    required        /lib64/security/pam_env.so
auth    optional        /lib64/security/pam_lastlog.so
auth    [success=done default=ignore]   /lib64/security/pam_sss.so      forward_pass
<...snip...>
```

```
2017-11-22T10:14:16.176555+00:00 rdpsrv xrdp-sesman[18762]: pam_sss(xrdp-sesman:auth): authentication success; logname= uid=0 euid=0 tty=xrdp-sesman ruser= rhost= user=mrichar1
2017-11-22T10:14:16.686880+00:00 rdpsrv systemd-logind: New session c23 of user mrichar1.
2017-11-22T10:14:16.725232+00:00 rdpsrv xrdp-sesman[18939]: pam_unix(xrdp-sesman:session): session opened for user mrichar1 by (uid=0)
```

It's not pam_env (commenting that out makes no difference) and the exact position of the 'dummy' module doesn't matter, as long as it's before pam_sss.

**Comment by gogonaft** [comment]
@mrichar1 thanks! saved my day! Ubuntu 20.04 xrdp-sesman - same issue 👍

**Comment by matt335672** [comment]
This doesn't seem to be an xrdp issue. I'll close it now.
