### ISSUE TITLE
same file not copied in drive redirection

### ISSUE THREAD

**Issue by purvalpatel** [neutrinolabs/xrdp#959]
Hello,

I Found another issue in XRDP Drive redirection., i dont know is this the exectly issue of xrdp or not.

Here, I use ubuntu 14.04 as a RDP server and use Windows 8 for as a RDP client.
i redirect the C drive from the windows machine and drive is redirected successfully.

drive is mounted properly.
when i copy some file in to some folder inside redirected C drive then it is copied perfectly.

again i copy the same file into redirected c drive then this file is not replaced.

if i delete file from windows and again try to copy this file from redirected drive then it is not copied.
it shows the below error,

`cp: cannot create regular file ‘/home/user1/thinclient_drives/C:/Export/file1.txt’: Input/output error`

**Comment by purvalpatel** [comment]
@metalefty Any Clue?

**Comment by radzz11** [comment]
Hi,
I have also face this type of issue, working with current xrdp version 0.9.4 on ubuntu 14.04 & connect from window 8 remote desktop client.
Is this related to fuse !!! 
Any hints !!

**Comment by matt335672** [comment]
This was fixed in xrdp v0.9.10 I believe. Sorry I missed this one.
