### ISSUE TITLE
The colormap is all NULL！

### ISSUE THREAD

**Issue by hanchaow** [neutrinolabs/xrdp#96]
Thanks for teaching me use the NeutrinoRDP module for proxies instead of the FreeRDP module for XRDP last time.
(I download NeutrinoRDP from https://github.com/neutrinolabs/NeutrinoRDP.git and XRDP from https://github.com/FreeRDP/xrdp.git )

In order to compile xrdp server correctly,I fixed two problem as follows：

(1)the code between line 136 and 139 in the file NeutrinoRDP/channels/xrdpvr/xrdpvr_player.c is 

136 #if defined(DISTRO_UBUNTU1204) || defined(DISTRO_UBUNTU1111)
137 #define CODEC_TYPE_VIDEO AVMEDIA_TYPE_VIDEO
138 #define CODEC_TYPE_AUDIO AVMEDIA_TYPE_AUDIO
139 #endif

but the operation system of my xrdp server is CentOS:
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.4 (Final)
Release:        6.4
So,I had to comment out the line 136 and line 139 for being able to use the redefine CODEC_TYPE_VIDEO and CODEC_TYPE_AUDIO in other place.

(2)In the same file, the code in line 385 and line 386:
385 //case AV_SAMPLE_FMT_U8:
386 case SAMPLE_FMT_U8:
I commented out line 386 and used the line 385.
After fixed the two problems , I have compiled the xrdp correctly and make install xrdp. In order to build xrdp with neutrinordp module , I ran ./configure --enable-neutrinordp and modify the xrdp.ini configuration,added the following codes:
[xrdp8]
name=neutrinordp-any
lib=libxrdpneutrinordp.so
ip=ask
port=ask3389
username=ask
password=ask

But when I tested the neutrinordp-any, the error occured!I used remote desktop of my host which is the windows system to connect the xrdp server. Having connected the xrdp server, I choose the neutrinordp-any to connect another windows server. The running log of xrdp as follows:

lib=libxrdpneutrinordp.so
mod_init:
  FreeRDP version major 1 minor 0 revision 1
here
lfreerdp_context_new: 0x1af34b0
loaded module 'libxrdpneutrinordp.so' ok, interface size 404976, version 2
lfreerdp_pre_connect:
The colormap is all NULL
^Cshutting down
signal 2 threadid 0x7f812b41c7c0

 The the connected aborted! The above mentioned output maybe from the file /neutrinordp/xrdp-neutrinordp.c  in XRDP
 How can I solve this problem?

 Futhermore I used the VNC to connected the xrdp server directly, and using the following commands to connect the same windows server through the NeutrinoRDP client, it also failed:
 [root@localhost .vnc]# /root/xrdp/NeutrinoRDP/client/X11/xfreerdp -u admin 172.16.210.112
in freerdp_context_new
connected to 172.16.210.112:3389
connected to 172.16.210.112:3389
connected to 172.16.210.112:3389
null server certificate
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  1 (X_CreateWindow)
  Serial number of failed request:  32
  Current serial number in output stream:  36

 Thanks for reading this issue. And I really don’t know how to do about this.

**Comment by srini8080** [comment]
The current version on CentOS 6.6 also has the problem.

xrdpvr_player.c:343:8: error: ‘SAMPLE_FMT_U8’ undeclared (first use in this function)
   case SAMPLE_FMT_U8:

**Comment by metalefty** [comment]
Reporter says that he fixed the issue, closing.

**Comment by qq727791967** [comment]
How to fix it？The latest xrdp(0.9.9) and the latest NeutrinoRDP also has the problem in Centos 7 .Can you tell me？Thanks!!!

**Comment by metalefty** [comment]
ask it the reporter. @hanchaow how did you fix it?
