### ISSUE TITLE
Can xrdp connect to an existing Xorg session?

### ISSUE THREAD

**Issue by joakim-tjernlund** [neutrinolabs/xrdp#960]
Existing session in this case is my normal/console Xorg session.

**Comment by mrichar1** [comment]
You can use x11vnc as the 'backend' to connect to an existing X session.

I use it directly, calling it with the following options (read the man page for more...), replacing :0 as appropriate.

```
x11vnc -noxdamage -display :0 -safer  -once
```

I've not tested this, but something like this should work:
```
# xrdp.ini
[xrdp1]
name=X11vnc
lib=libvnc.so
ip=127.0.0.1
port=5900
username=ask
password=ask

# sesman.ini
[X11vnc]
param=x11vnc
param=-noxdamage 
param=-display
parasm=:0
param=-safer
param=-once
```

**Comment by metalefty** [comment]
As @mrichar1 say, can't connect to existing Xorg session because the xorgxrdp extension is not loaded to the existing Xorg session. Using other application such as x11vnc, it is possible.

**Comment by joakim-tjernlund** [comment]
I have not used xrdp yet so I struggling a bit to keep up, but this looks similar to what
tigervnc does, or am I mistaken?
I was looking to use RDP instead of VNC as I am hoping RDP is more efficient than VNC

**Comment by metalefty** [comment]
You can use xrdp for such purpose. But forget the existing Xorg session. xrdp raises xrdp's own Xorg session and you can connect to the session.

**Comment by joakim-tjernlund** [comment]
That is a good start, but I also like to connect to my existing session.
Is there any chance that could work in the future or is it  just out of scope for xrdp?

**Comment by metalefty** [comment]
Maybe not. Connecting to existing session is a different purpose. Let's suppose GNU screen or tmux. Have you ever used either of them? It create its own session and users can attach to CLI which is run under screen/tmux but can't attach to the session not in screen/tmux such as physical console. xrdp does very similar with screen/tmux, works like a GUI version of screen/tmux.

You can also connect to localhost:3389 via RDP from your existing console session and run all applications in xrdp session. It will provide you to attach to your session remotely and locally.

If you really want to connect to existing session, you need to use other softwares such as x11vnc and connect like this.  

```
[your client]--(network)--[xrdp as RDP-VNC proxy]--[x11vnc]--[existing Xorg session]
```

**Comment by Natureshadow** [comment]
What about loading xorgxrdp modules in the local X session and set up dual-screen with it?

**Comment by metalefty** [comment]
> What about loading xorgxrdp modules in the local X session and set up dual-screen with it?

xorgxrdp must be loaded when Xorg startup currently.

Closing due to out of scope. See https://github.com/neutrinolabs/xrdp/issues/960#issuecomment-347373531 for the intended use case.

**Comment by cspwizard** [comment]
Is there any chance this functionality would be implemented? It would be very helpful if XRDP would behave same way as Windows RDP does, when user can connect to existing session (that was started from console).

**Comment by grayguest** [comment]
> You can use x11vnc as the 'backend' to connect to an existing X session.
> 
> I use it directly, calling it with the following options (read the man page for more...), replacing :0 as appropriate.
> 
> ```
> x11vnc -noxdamage -display :0 -safer  -once
> ```
> 
> I've not tested this, but something like this should work:
> 
> ```
> # xrdp.ini
> [xrdp1]
> name=X11vnc
> lib=libvnc.so
> ip=127.0.0.1
> port=5900
> username=ask
> password=ask
> 
> # sesman.ini
> [X11vnc]
> param=x11vnc
> param=-noxdamage 
> param=-display
> parasm=:0
> param=-safer
> param=-once
> ```

thank you very much, it works for me on linux mint 19.3(ubuntu 18.04 lts)

**Comment by giaur500** [comment]
Can I ask how to opposite? When remote connection user is not logged out, I can't login locally with the same user

**Comment by matt335672** [comment]
@giaur500  - this is [in the FAQ](https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-log-the-same-user-on-on-the-graphical-console-and-over-xrdp-at-the-same-time)

**Comment by wmantly** [comment]
@matt335672 That FAQ does NOT address this question at all. The linked FAQ, and underlying systemd issue is related to multiple user sessions. This a request to attach xRDP to an existing Xorg session.

**Comment by matt335672** [comment]
@wmantly - I was responding to @giaur500 who has asked a different question.
