### ISSUE TITLE
USB Redirection

### ISSUE THREAD

**Issue by nanodeath** [neutrinolabs/xrdp#966]
This [ancient](http://www.xrdp.org/index.php?option=com_content&view=article&id=15:usb-redirection&catid=2:documents&Itemid=7) post of yours (2011) mentions adding USB redirection support to xrdp. Was wondering if any progress had been made since then -- I love xrdp, but am bummed out that the back/forward buttons on my mouse don't work with it.

**Comment by metalefty** [comment]
No progress right now but back/forward buttons are not related to USB redirection at all.
