### ISSUE TITLE
Drag bug

### ISSUE THREAD

**Issue by zhonghesc** [neutrinolabs/xrdp#967]
http://120.27.100.229/bug.jpeg
which happens when I drag the words

os:
Linux ubuntu 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
xrdp:master
NeutrinoRDP:devel

**Comment by cocoon** [comment]
This looks similar to this one:
https://github.com/neutrinolabs/xrdp/pull/869

Can you try this branch if it doesn't happen then?

`git clone https://github.com/cocoon/xrdp/ -b 2017-09-08-devel-fix-W2k8-distortion`

**Comment by zhonghesc** [comment]
It works, thanks.
