### ISSUE TITLE
How to pop-up username/password window like Windows

### ISSUE THREAD

**Issue by zhonghesc** [neutrinolabs/xrdp#971]
For safety, I don‘t want to conncect to xrdp server directly.
Instead, I want it to pop-up a window when I connecting the xrdp server like Windows。
I tried the option in xrdp.ini:
require_credentials=true
but it just stop to connect to the xrdp server.

**Comment by hardening** [comment]
It's more a client side concern.

**Comment by evanlinde** [comment]
The feature you're looking for is called [Network Level Authentication](https://en.wikipedia.org/wiki/Network_Level_Authentication) (NLA).

According to https://github.com/neutrinolabs/xrdp/issues/702#issuecomment-288988599, xrdp doesn't provide NLA yet.

**Comment by metalefty** [comment]
NLA forces username/password dialog at client side but you can use username/password dialog even though the server doen't support NLA.

See this screenshot. The server is xrdp which doesn't support NLA.  `require_credentials=true` requires pre input credentials at client side.
![2017-12-13](https://user-images.githubusercontent.com/941609/33922664-9647f0f8-e00f-11e7-81d2-7108bc468441.png)

**Comment by rootbdfy** [comment]
Hmm require_credentials=true not work for me.
Connection just closed.

**Comment by metalefty** [comment]
That's the logical result because `require_credentials=true` is not designed to do such thing. See https://github.com/neutrinolabs/xrdp/issues/971#issuecomment-351285269.
