### ISSUE TITLE
Problem compiling on Mac OS Sierra

### ISSUE THREAD

**Issue by hongwen000** [neutrinolabs/xrdp#978]
I am using Mac OS Sierra 10.12.6
I followed the tutorial [building on Mac OS](https://github.com/neutrinolabs/xrdp/wiki/Building-on-OSX)
But I encountered
`fatal error: 'openssl/bio.h' file not found`  when compiling xrdp.
I solved this problem by setting environment variable 
`CPPFLAGS=-I/usr/local/opt/openssl/include`
`LDFLAGS=-L/usr/local/opt/openssl/lib`
and run `./configure` rather than `./configure PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
`. 
Maybe the tutorial should be updated?
This is my brew info of openssl
```
penssl: stable 1.0.2m (bottled) [keg-only]
SSL/TLS cryptography library
https://openssl.org/
/usr/local/Cellar/openssl/1.0.2l (1,709 files, 12.2MB)
  Poured from bottle on 2017-08-14 at 11:47:48
From: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git/Formula/openssl.rb
==> Dependencies
Build: makedepend ✘
==> Options
--without-test
	Skip build-time tests (not recommended)
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.
```

**Comment by metalefty** [comment]
I use MacPorts instead of Homebrew. It builds fine for me without special config.

**Comment by metalefty** [comment]
No feedback from the reporter, macOS is out of scope, closing.

**Comment by makcuber** [comment]
@cosmo0920 just for the sake of clarity, which release version were you using when you got it to compile?

**Comment by larryathey** [comment]
@cosmo0920 I'm interested in your answer as well.
