### ISSUE TITLE
 How could I record which program started and when it started when using xrdp to connect a remote host?

### ISSUE THREAD

**Issue by hanchaow** [neutrinolabs/xrdp#98]
When using xrdp to connect a remote host,could I know and record which program started and when it started?

Could I address this problem just by modifing the xrdp source code?If I could,which which part of the xrdp code should I modify?

For example,when I open the IE browser in a  remote host,I  just want to record automatically what I opened (the program IE browser ) and when I opened it by modifing the xrdp source code.

**Comment by metalefty** [comment]
Probably it is possible but not in the scope of xrdp.
