### ISSUE TITLE
No sound over RDP session

### ISSUE THREAD

**Issue by rootbdfy** [neutrinolabs/xrdp#981]
Hello. I use XRDP (v. 0.9.4) + XORGXRDP (v. 0.2.5) with KDE as DE. I have no sound over RDP session.
I tried to compile XRDP with --enable-load_pulse_modules flag and without flags, and no sound in both case.
When I check sound output in GUI, I see only dummy output.

**Comment by metalefty** [comment]
Did you build and install `module-xrdp-sink.so` into your pulseaudio modules directory?
The module must be built separately from xrdp itself.

BTW, `--enable-load_pulse_modules` is no longer works and no longer needed.

**Comment by metalefty** [comment]
I should write up the latest build instruction of pulse modules.

**Comment by rootbdfy** [comment]
> Did you build and install module-xrdp-sink.so into your pulseaudio modules directory?
No. Will try today.
Thank you.

**Comment by metalefty** [comment]
FYI, I've written up the build instruction.
https://github.com/neutrinolabs/xrdp/wiki/How-to-build-and-install-pulseaudio-modules

**Comment by rootbdfy** [comment]
I have build modules for xrdp v0.9.4 and pulseaudio v11.1 ( I use debian testing), and sound working fine.
Thank you.

**Comment by Natureshadow** [comment]
>I have build modules for xrdp v0.9.4 and pulseaudio v11.1 ( I use
>debian testing), and sound working fine.
>Thank you.

On Debian testing, you could just have

# apt install xrdp-pulseaudio-installer
# xrdp-build-pulse-modules

and that's it.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cminnoy** [comment]
On Ubuntu (Mate) 18.04 LTS the package xrdp-build-pulse-modules seems to be broken.
When applying the build instructions manually the two *.so modules build correct, but no sound is working after the installation.

**Comment by metalefty** [comment]
@cminnoy report it to ubuntu

**Comment by patrickthoral** [comment]
@cminnoy if you followed the [instructions](https://github.com/neutrinolabs/xrdp/wiki/How-to-set-up-audio-redirection) while using Ubuntu 18.04 you will probably also need to change the [/etc/xrdp/pulse/default.pa](/etc/xrdp/pulse/default.pa) file after the Make command to reflect the actual locations of the compiled modules:

```
.nofail
.fail
load-module module-augment-properties
load-module module-always-sink
.ifexists module-xrdp-sink.so
load-module module-xrdp-sink.so
.endif
.ifexists module-xrdp-source.so
load-module module-xrdp-source.so
.endif
load-module module-native-protocol-unix
```
The default script looks in /var/lib while the instructions are using /usr/lib to copy the modules to.

**Comment by cminnoy** [comment]
On Ubuntu MATE 18.04 the script 'xrdp-build-pulse-modules' is broken. Issues with 'dget'.

**Comment by cminnoy** [comment]
You also need to install libpulse-dev before building.
And PULSE_DIR needs to be set, but not sure to what exactly.
