### ISSUE TITLE
Consider Debian's pulseaudio build script/patches

### ISSUE THREAD

**Issue by Natureshadow** [neutrinolabs/xrdp#986]
For the upcoming version of the Debian xrdp package, we have created a package that builds and installs the PulseAudio modules.

You can find everything related to it here:

https://sources.debian.org/src/xrdp/0.9.4-5/debian/xrdp-build-pulse-modules/
https://sources.debian.org/src/xrdp/0.9.4-5/debian/patches/pulse-debian.patch/

Most remarkably, PullseAudio can load modules by full path, so the manually built modules do not have to be installed into directories that must only ever be managed by dpkg.

But maybe the rest of the script is interesting as well.

**Comment by metalefty** [comment]
Can you make a pull request for the latter half of pulse-debian.patch?
It definitely makes sense. I'm glad to merge it.

**Comment by Natureshadow** [comment]
Which is the "latter half"? The part with xrdp_socket.h?

**Comment by metalefty** [comment]
Yes, include path change of xrdp_socket.h.

**Comment by metalefty** [comment]
I've created #1008.

**Comment by metalefty** [comment]
pulseaudio module is now provided as a separated repository.
Much easier to build.
