### ISSUE TITLE
xrdp-genkeymap - Add spanish and latin keyboard map.

### ISSUE THREAD

**Issue by msantinelli** [neutrinolabs/xrdp#989]
I will be great to have the spanish keymaps added to this application.

**Comment by jsorg71** [comment]
es-es (spanish-spanish) and es-la (spanish-latin)

**Comment by metalefty** [comment]
Which one?
https://docs.microsoft.com/ja-jp/windows-hardware/manufacture/desktop/windows-language-pack-default-values

**Comment by metalefty** [comment]
Spanish is already added. Can you explain the reason to make additional changes to Spanish? https://github.com/neutrinolabs/xrdp/pull/777

**Comment by metalefty** [comment]
No feedback from the reporter for 1 month. Close.

**Comment by msantinelli** [comment]
Sorry about this. The problem was when I use a debian machine from windows 10 remote desktop (new version, the one from the store). The old versions of the remote desktop work fine. It was not a problem in xrdp. When the new interface, the Alt Gr key is not sended to the client. Again, sorry. 
Thanks for yours answers.
