### ISSUE TITLE
DisconnectedTimeLimit puzzle

### ISSUE THREAD

**Issue by soldier828** [neutrinolabs/xrdp#991]
I 'man sesman.ini' about DisconnectedTimeLimit, and get the following information.

```
DisconnectedTimeLimit=<number>
    Sets the the time limit before a disconnected session is killed.
    If set to 0, automatic killing is disabled.
    -this option is currently ignored!-
```

I wonder how to set this FLAG now?  
Or can I get how long dose one specific session in idle status?

**Comment by metalefty** [comment]
If such text is written in YOUR man, YOUR xrdp installation doesn't support that feature.
https://github.com/neutrinolabs/xrdp/blob/021b79b/docs/man/sesman.ini.5.in#L128-L131

**Comment by metalefty** [comment]
No feedback from the reporter for 1 month. Close.
