### ISSUE TITLE
[FAQ] What are usable Android RDP clients to connect to xrdp session?

### ISSUE THREAD

**Issue by teneri66** [neutrinolabs/xrdp#994]
Tried a few, including Microsoft Remote Desktop but it seems to be not much usable.
Clicks are slow and inaccurate. Resolution is buggy - task bar is not shown simply at the bottom of the screen but in the middle.
System: Ubuntu 17.10, Plasma 5.11.

**Comment by cro** [comment]
I have found that using a minimal desktop with simple background (like awesomewm) works much better.  I've successfully used the Android Microsoft RDP client as well as XtraLogic's RDP client for the Chromebook.

**Comment by DS455** [comment]
https://www.parallels.com/ru/products/ras/download/client/#android 
Works great.

**Comment by metalefty** [comment]
No update, a plausible answer is provided, closing.
