### ISSUE TITLE
Some autostart windows opened in main session instead of remote

### ISSUE THREAD

**Issue by teneri66** [neutrinolabs/xrdp#995]
When opening the remote session and it starts some apps open in main session instead of remote.
So far I've see these: Google Chrome, Viber.
In case of Chrome simply new tab gets opened. In case of Viber the main window gets shown. But these apps are not started in remote session.
System: Plasma 5.11, Ubuntu 17.10.

**Comment by metalefty** [comment]
Close your Chrome in the session before starting Chrome in xrdp session.
Probably it is not xrdp issue. It's a application issue.

**Comment by metalefty** [comment]
Maybe even not an issue, application behaves like that in design. I'm not familiar with Chrome but Firefox also behaves like that. We can run multiple instances of Firefox by giving additional command line arguments. I hope Chrome has similar option.

**Comment by teneri66** [comment]
Worth to documenting such "feature" and how to fix it? Or leaving in github ticket for reference is enough? What do you think?

**Comment by moobyfr** [comment]
This is not a feature not a bug, it's the standard usage from these
programs, for example if you use it on vnc or in several x11session on the
same host
A little annoying sometime, but these programs aren't designed to be used
from several sessions

Emmanuel

**Comment by metalefty** [comment]
@teneri66 Documenting should be done in each application. As @moobyfr says, it's not an our issue.
