### ISSUE TITLE
Drive redirection not getting file information correctly

### ISSUE THREAD

**Issue by vscfreire** [neutrinolabs/xrdp#996]
When using drive redirection with Microsoft Remote Desktop client (`mstsc.exe`), file and directory information are not being correctly fetched/updated.

Apparently, `xinode` data for files on redirected drives is only created when directory contents are listed, and is never updated from that point on. This causes two separate (although related) issues.

### Issue 1: directory contents only update with `ls`

For example, if I logon through xrdp (using `mstsc.exe`), launch a terminal window and go to the redirected drive folder, until I run a `ls` command, it's like the drive contents don't exist:

    $ cd thinclient_drives
    $ ls
    C:
    $ cd C\:
    $ cd Windows
    bash: cd: Windows: No such file or directory
    $ cd Users
    bash: cd: Users: No such file or directory
    $ 

So, at this point it seems like the redirected `C:` drive is empty. However, if I run an `ls` command, it seems to fetch the information and it works correctly from that point on:

    $ ls
     'Documents and Settings'   langpacks      'Program Files'         swapfile.sys
     Drivers                    pagefile.sys   'Program Files (x86)'   'System Volume Information'
     hiberfil.sys               PerfLogs       Recovery                Users
     Intel                      ProgramData    '$Recycle.Bin'          Windows
    $ cd Windows
    $ pwd
    /home/user/thinclient_drives/C:/Windows

However, it works just for that directory (I have to use `ls` inside the directory for it to be updated as well):

    $ cd System32
    bash: cd: System32: No such file or directory
    $ ls System32
    ls: cannot access 'System32': No such file or directory
    $ ls
     addins                     INF            schemas
     appcompat                  InfusedApps    security
     ...
     IME                        RtCRU64.exe    WMSysPr9.prx
     ImmersiveControlPanel      SchCache       write.exe
    $ cd System32
    $ pwd
    /home/user/thinclient_drives/C:/Windows/System32
    $

This problem is not visible when using a graphical file manager, because it will list the directory contents automatically when we enter a directory.

I believe this is due to the `ls` command (without arguments) triggering the `xfuse_cb_opendir` callback, which uses `dev_redir_get_dir_listing`/`dev_redir_proc_query_dir_response` to create the `xinode` data.

A simple `cd` or `ls [filename]` starts by triggering the `xfuse_cb_lookup` callback, which fails immediately because there's no `xinode` corresponding to the name.

Maybe the solution is triggering a directory listing request when the `xfuse_cb_lookup` initially fails?

### Issue 2: when a file is changed on the remote (client) side, metadata is not updated on xrdp

We start by creating a test file on the redirected drive from the server (xrdp) side:

    $ cd thinclient_drives/C\:
    $ ls
     ...
    $ cd Test
    $ echo "test data" > test.txt
    $ ls -l test.txt
    -rw-r--r--. 1 user user 10 Jan 12 12:12 test.txt
    $ cat test.txt
    test data
    $

As we can see, the file is created correctly, with a size of 10 bytes (includes the newline at the end). If we check on the Windows side, the file also appears on the file system.

We now edit the file on the Windows (client) side and change the contents:

![image](https://user-images.githubusercontent.com/35369554/34874790-5c2e1c40-f792-11e7-930f-2c41a113af8d.png)

If we check the file on the xrdp (server) side, we see that it's metadata remains the same (same size, times, etc.):

    $ ls -l test.txt
    -rw-r--r--. 1 user user 10 Jan 12 12:12 test.txt
    $ stat test.txt 
      File: test.txt
      Size: 10        	Blocks: 0          IO Block: 4096   regular file
    Device: 30h/48d	Inode: 187         Links: 1
    Access: (0644/-rw-r--r--)  Uid: ( 1000/   user)   Gid: ( 1000/    user)
    Context: system_u:object_r:fusefs_t:s0
    Access: 2018-01-12 12:12:35.000000000 +0000
    Modify: 2018-01-12 12:12:35.000000000 +0000
    Change: 2018-01-12 12:12:35.000000000 +0000
     Birth: -
    $

However, if we look at it's contents, we can see the new data, although truncated to the first 10 bytes due to the incorrect metadata (notice no end of line character):

    $ cat test.txt
    this is no$

I couldn't find a way to force xrdp to update the file metadata from this point on. Also, if I try to write to the file, I will just get an error and the file will be listed as having 0 bytes:

    $ echo "test 1234567890" > test.txt
    bash: echo: write error: Input/output error
    $ cat test.txt
    $ stat test.txt
      File: test.txt
      Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
    Device: 30h/48d	Inode: 187         Links: 1
    Access: (0644/-rw-r--r--)  Uid: ( 1000/    user)   Gid: ( 1000/    user)
    Context: system_u:object_r:fusefs_t:s0
    Access: 2018-01-12 12:12:35.000000000 +0000
    Modify: 2018-01-12 12:12:35.000000000 +0000
    Change: 2018-01-12 12:12:35.000000000 +0000
     Birth: -
    $

Notice the incorrect (0 byte) size, but the same date/times.

I believe this to be caused by the `xinode` data not being updated if the file is changed on the remote (client) side, after the metadata is obtained the first time.

**Comment by vscfreire** [comment]
By the way, the tests were made with xrdp 0.9.4 and 0.9.5 on Fedora 27 (x86_64), installed from the official package (https://src.fedoraproject.org/cgit/rpms/xrdp.git), included in the distribution.

**Comment by matt335672** [comment]
I believe this one is now fixed with #1327 and later PRs.

Feel free to re-open it if this isn't the case.
