### ISSUE TITLE
Cannot open console Gnome session when xrdp session active for same user

### ISSUE THREAD

**Issue by scherepanov** [neutrinolabs/xrdp#998]
Steps to reproduce:
On Fedora 27
1) Remotely connect to xrdp (I used Xvnc) to Gnome desktop. Do not disconnect.
2) Try to open regular Gnome session (i.e. from attached terminal). It fails, return back to login prompt.
Looking at journaltctl, attempt to local login produces crashes and multiple errors.

**Comment by metalefty** [comment]
Why don't you show the error although you're talking about errors?

**Comment by scherepanov** [comment]
That is a completely valid point, sorry. I do need to post error log. Though it was quite long with couple of coredumps.
And, today it does not show coredumps. Only my excuse is that I let update system first, and it installed newer xrdp-selinux and xorgxrdp.

I tried several times, and cannot reproduce yesterday coredumps.

What I can see, on pretty vanilla Fedora 27 workstation install:
1) Power up box. Do not login into console terminal Gnome session
2) Login to box with xrdp. Xvnc works. I would expect Xorg also works with updated xorgxrdp - but no luck - still abort from gsd-color (let me know if you want to see coredump).
3) Do not close xrdp Gnome session.
4) Login to console terminal Gnome session. Screen flashes and return to login, both for Xvnc and Xorg.

journalctl logs are quite uninformative, with except message:
gdm[733]: GdmDisplay: display lasted 0.139467 seconds
Above log entry present both in Xvnc and Xorg. Xorg logs are quite long, I am omitting them here. Below is full log from Xvnc.

It does not look good that I cannot demonstrate coredumps that I observed yesterday. But, basic behavior is there - as soon as you login with xrdp, you cannot start console terminal Gnome session.

journalctl logs for Xvnc login attempt (truncated error lines are from gnome-shell):

Jan 16 20:51:29 supermedia audit[4944]: USER_AUTH pid=4944 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=pam_unix,pam_gnome_keyring acct="sergey" exe="/usr/libexec/gdm-session-worker" hostname=supermedia addr=? terminal=/dev/tty1 res
Jan 16 20:51:29 supermedia audit[4944]: USER_ACCT pid=4944 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:accounting grantors=pam_unix,pam_localuser acct="sergey" exe="/usr/libexec/gdm-session-worker" hostname=supermedia addr=? terminal=/dev/tty1 res=success
Jan 16 20:51:29 supermedia audit[4944]: CRED_ACQ pid=4944 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_unix,pam_gnome_keyring acct="sergey" exe="/usr/libexec/gdm-session-worker" hostname=supermedia addr=? terminal=/dev/tty1 res=success
Jan 16 20:51:29 supermedia systemd-logind[705]: New session 8 of user sergey.
Jan 16 20:51:29 supermedia systemd[1]: Started Session 8 of user sergey.
Jan 16 20:51:29 supermedia gdm-password][4944]: pam_unix(gdm-password:session): session opened for user sergey by sergey(uid=0)
Jan 16 20:51:29 supermedia audit[4944]: USER_START pid=4944 uid=0 auid=1000 ses=8 msg='op=PAM:session_open grantors=pam_selinux,pam_loginuid,pam_selinux,pam_keyinit,pam_namespace,pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_gnome_keyring acct="sergey" exe="
Jan 16 20:51:29 supermedia audit[4944]: USER_LOGIN pid=4944 uid=0 auid=1000 ses=8 msg='uid=1000 exe="/usr/libexec/gdm-session-worker" hostname=? addr=? terminal=? res=success'
Jan 16 20:51:29 supermedia gdm-password][4944]: pam_unix(gdm-password:session): session closed for user sergey
Jan 16 20:51:29 supermedia audit[4944]: USER_END pid=4944 uid=0 auid=1000 ses=8 msg='op=PAM:session_close grantors=pam_selinux,pam_loginuid,pam_selinux,pam_keyinit,pam_namespace,pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_gnome_keyring acct="sergey" exe="/
Jan 16 20:51:29 supermedia audit[4944]: USER_LOGOUT pid=4944 uid=0 auid=1000 ses=8 msg='uid=1000 exe="/usr/libexec/gdm-session-worker" hostname=? addr=? terminal=? res=success'
Jan 16 20:51:29 supermedia audit[4944]: CRED_DISP pid=4944 uid=0 auid=1000 ses=8 msg='op=PAM:setcred grantors=pam_unix,pam_gnome_keyring acct="sergey" exe="/usr/libexec/gdm-session-worker" hostname=supermedia addr=? terminal=/dev/tty2 res=success'
Jan 16 20:51:29 supermedia gdm[733]: GdmDisplay: display lasted 0.139467 seconds
Jan 16 20:51:29 supermedia systemd-logind[705]: Removed session 8.
Jan 16 20:51:29 supermedia gsd-color[1037]: failed to set screen _ICC_PROFILE: Failed to open file “/home/sergey/.local/share/icc/edid-da5b962320efd882c16bb5a71bdc5de5.icc”: Permission denied
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia dbus-daemon[650]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.7" (uid=0 pid=705 comm="/usr/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Unknow
Jan 16 20:51:29 supermedia gsd-color[1037]: failed to set screen _ICC_PROFILE: Failed to open file “/home/sergey/.local/share/icc/edid-da5b962320efd882c16bb5a71bdc5de5.icc”: Permission denied

**Comment by metalefty** [comment]
Can you confirm if the issue occurs when you have multiple Xvnc session not using xrdp at all?

**Comment by scherepanov** [comment]
This issue probably lays outside xrdp.
It appears Gnome itself recently lost part of multi-user capabilities. It means, you cannot start second gnome session in parallel to existing one for same user. It just silently exit.
At least, all my attempts to start second session X* session by various means always fail this way.
You still can run session for other account in parallel to existing one, as soon as accounts are different.
X used to have ability to start second parallel session by pressing Ctrl-Alt-[F7-F12]. No more.
Side consequences is that you cannot start second xrdp session in parallel with already open first one, for same account. That was my first finding why I start investigating this issue.
BTW that explains why a lot of people have trouble to use xrdp on recent Linux distributions on default out-of-box configurations. They have login in console X session, and trying to use xrdp with same account. It just silently fails.
I think it worth to mention in xrdp README, would be very helpful to user community.

**Comment by tachi** [comment]
I have the same issue as you have @scherepanov. I also look for a solution that makes it possible to login to a xrdp session when a gnome session of the same user is active or vice versa.

**Comment by metalefty** [comment]
Not our issue. Closing.  It should reproduce with console + Xvnc session.
